### ISSUE TITLE
gatsby develop fails in Gatsby tutorial part 2 - "Error There was a problem loading the local develop command..."

### ISSUE THREAD

**Issue by ericsolberg** [gatsbyjs/gatsby#10404] opened 2018-12-11 06:05 UTC
## Description

I'm trying to run part 2 of the Gatsby tutorial at https://www.gatsbyjs.org/tutorial/part-two/. I followed part 1 exactly per the instructions, including my dev setup.

The tutorial fails after installing the hello-world starter and installing the typography plugin. I see that someone else has posted this issue but a) it is not clear to me how to work around the problem by reading the vague comments in the issue and b) nobody has bothered to update the tutorial with correct steps!

It seems that every developer who wants to learn Gatsby is going to encounter this error... 

### Steps to reproduce

Just follow part 2 of the tutorial. Specifically:
```
gatsby new tutorial-part-two https://github.com/gatsbyjs/gatsby-starter-hello-world
cd tutorial-part-two
npm install --save gatsby-plugin-typography react-typography typography
gatsby develop
```
### Expected result

The hello-world starter page should display at http://localhost:8000

### Actual result

The npm install command produced these warnings:
```
npm WARN rm not removing /Users/i809433/projects/gatsby/tutorial-part-two/node_modules/.bin/browserslist as it wasn't installed by /Users/i809433/projects/gatsby/tutorial-part-two/node_modules/browserslist
npm WARN rm not removing /Users/i809433/projects/gatsby/tutorial-part-two/node_modules/.bin/regjsparser as it wasn't installed by /Users/i809433/projects/gatsby/tutorial-part-two/node_modules/regjsparser
npm WARN rm not removing /Users/i809433/projects/gatsby/tutorial-part-two/node_modules/.bin/jsesc as it wasn't installed by /Users/i809433/projects/gatsby/tutorial-part-two/node_modules/jsesc
npm WARN rm not removing /Users/i809433/projects/gatsby/tutorial-part-two/node_modules/fsevents/node_modules/.bin/node-pre-gyp as it wasn't installed by /Users/i809433/projects/gatsby/tutorial-part-two/node_modules/fsevents/node_modules/node-pre-gyp
npm WARN rm not removing /Users/i809433/projects/gatsby/tutorial-part-two/node_modules/.bin/babylon as it wasn't installed by /Users/i809433/projects/gatsby/tutorial-part-two/node_modules/babylon
npm WARN gatsby-plugin-typography@2.2.2 requires a peer of gatsby@>2.0.0-alpha but none is installed. You must install peer dependencies yourself.
npm WARN gatsby-starter-hello-world@ No repository field.
```
gatsby develop produced:
```
error There was a problem loading the local develop command. Gatsby may not be installed in your site's "node_modules" directory. Perhaps you need to run "npm install"? You might need to delete your "package-lock.json" as well.
```

### Environment

  System:
    OS: macOS 10.14
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.4.0 - ~/.nvm/versions/node/v11.4.0/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v11.4.0/bin/npm
  Browsers:
    Chrome: 70.0.3538.110
    Firefox: 63.0.1
    Safari: 12.0
  npmPackages:
    gatsby-plugin-typography: ^2.2.2 => 2.2.2 
  npmGlobalPackages:
    gatsby-cli: 2.4.6

**Comment by ericsolberg** [comment] 2018-12-11 06:55
On the related (but closed) thread one commenter said to use yarn instead of npm. I tried that and the command finished without the warnings. However, running gatsby develop now gives different errors (below). **So I'm now blocked and unable to learn Gatsby.**
```
error Unable to find plugin "gatsby-plugin-typography". Perhaps you need to install its package?


  Error: Unable to find plugin "gatsby-plugin-typography". Perhaps you need to i  nstall its package?
  
  - load.js:102 resolvePlugin
    [tutorial-part-two]/[gatsby]/dist/bootstrap/load-plugins/load.js:102:11
  
  - load.js:114 processPlugin
    [tutorial-part-two]/[gatsby]/dist/bootstrap/load-plugins/load.js:114:20
  
  - load.js:164 config.plugins.forEach.plugin
    [tutorial-part-two]/[gatsby]/dist/bootstrap/load-plugins/load.js:164:20
  
  - Array.forEach
  
  - load.js:163 module.exports
    [tutorial-part-two]/[gatsby]/dist/bootstrap/load-plugins/load.js:163:20
  
  - index.js:56 
    [tutorial-part-two]/[gatsby]/dist/bootstrap/load-plugins/index.js:56:21
  
  - Generator.next
  
  - debuggability.js:313 Promise._execute
    [lib]/[gatsby-cli]/[bluebird]/js/release/debuggability.js:313:9
  
  - promise.js:483 Promise._resolveFromExecutor
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:483:18
  
  - promise.js:79 new Promise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:79:10
  
  - index.js:96 
    [tutorial-part-two]/[gatsby]/dist/bootstrap/load-plugins/index.js:96:17
  
  - index.js:147 
    [tutorial-part-two]/[gatsby]/dist/bootstrap/index.js:147:36
  
  - Generator.next
  
  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31
  
  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18
  

error UNHANDLED REJECTION


  Error: Unable to find plugin "gatsby-plugin-typography". Perhaps you need to i  nstall its package?
  
  - load.js:102 resolvePlugin
    [tutorial-part-two]/[gatsby]/dist/bootstrap/load-plugins/load.js:102:11
  
  - load.js:114 processPlugin
    [tutorial-part-two]/[gatsby]/dist/bootstrap/load-plugins/load.js:114:20
  
  - load.js:164 config.plugins.forEach.plugin
    [tutorial-part-two]/[gatsby]/dist/bootstrap/load-plugins/load.js:164:20
  
  - Array.forEach
  
  - load.js:163 module.exports
    [tutorial-part-two]/[gatsby]/dist/bootstrap/load-plugins/load.js:163:20
  
  - index.js:56 
    [tutorial-part-two]/[gatsby]/dist/bootstrap/load-plugins/index.js:56:21
  
  - Generator.next
  
  - debuggability.js:313 Promise._execute
    [lib]/[gatsby-cli]/[bluebird]/js/release/debuggability.js:313:9
  
  - promise.js:483 Promise._resolveFromExecutor
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:483:18
  
  - promise.js:79 new Promise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:79:10
  
  - index.js:96 
    [tutorial-part-two]/[gatsby]/dist/bootstrap/load-plugins/index.js:96:17
  
  - index.js:147 
    [tutorial-part-two]/[gatsby]/dist/bootstrap/index.js:147:36
  
  - Generator.next
  
  - util.js:16 tryCatcher
    [lib]/[gatsby-cli]/[bluebird]/js/release/util.js:16:23
  
  - promise.js:512 Promise._settlePromiseFromHandler
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:512:31
  
  - promise.js:569 Promise._settlePromise
    [lib]/[gatsby-cli]/[bluebird]/js/release/promise.js:569:18
```

**Comment by jonniebigodes** [comment] 2018-12-11 17:34
@ericsolberg let me start by saying i'm sorry you're having a troublesome experience using gatsby.
If you don't mind, i would like for you to open a terminal, navigate to the folder where you're running part 2 of the tutorial, and once you're there, issue the following command `npm uninstall --save gatsby && npm install --save gatsby`. With this it will remove that version of gatsby and get the latest. After the process finishes and just to be sure, delete both .cache and public folders and check if the plugin is added correctly in the `gatsby-config.js` file.  And then issue `gatsby develop`. And if you can please report back with some feedback if all is working correctly? Sounds good?

**Comment by ericsolberg** [comment] 2018-12-11 21:53
Thanks Jonnie - it looks like that did the trick. gatsby develop works now, and serves up my hello world - so I can move on through the tutorial and start building something!

fyi my gatsby-config.js, after all of this is:
```
module.exports = {
  plugins: [`gatsby-plugin-typography`],
}
```
Is that correct?
I do recommend that you guys update the tutorial for this - I don't think there's anything unusual in my setup so other people who try to learn Gatsby are likely to encounter the same thing.
Thanks again!

**Comment by jonniebigodes** [comment] 2018-12-12 03:11
@ericsolberg you're not the first to report this type of issue, recently someone else had a similar issue like yours, i reproduced it and came up with that solution. The problem it's not actually the tutorial, it's the gatsby package version that is in the starter, i've made a pull request to that specific repository, to update the version in order to prevent issues popping here similar the ones you had.

I'm in the process of getting the official starters cloned to my machine and update the dependencies on them and check if everything is working properly and then make some pull requests to each of them to update. 
And yes the gatsy config file looks good. 
And once again, sorry for the rough start when using gatsby, hope you build some really awesome stuff and then showcase them here.
I'm closing this issue as it's resolved.
Thanks for using gatsby 👍

**Closed by jonniebigodes** 2018-12-12 03:11 UTC

**Comment by magaldistudio** [comment] 2020-06-23 20:35
Good afternoon!

After opening my project in the gatsby folder, when I turn on the gatsby develop command, I get the following error:

 ERROR

Looks like develop for this site is already running. Try visiting http://localhost:8000/ maybe?
