### ISSUE TITLE
HTML of Dynamic routes changed after deploying to Netlify and render 'Not Found Page ' before rendering the actual page

### ISSUE THREAD

**Issue by Skobraf** [gatsbyjs/gatsby#27847] opened 2020-11-05 11:05 UTC
## Description

I built a website using gatsby, the landing page works fine on the production since it's statically served during the build time, I have created a gatsby-node file to fetch dynamic data depending on the id in the route. `user/:id` in the /app I wrapped the routes with Apollo Provider since the communication with the server is done with GraphQl.
After navigation into " user/:id "the page render not found at first, then render the actual page wrapped inside a Section and Container that doesn't exist in my original code also as changing the className of the last `<div>` to head / main 
Code works fine in development and in build in localhost

### Steps to reproduce

<img width="498" alt="Screen Shot 2020-11-05 at 11 58 10 AM" src="https://user-images.githubusercontent.com/17176117/98232870-7ed1d600-1f5e-11eb-9795-992f8b6bb000.png">

### Expected result

The page should render fine like the development environment and in build in localhost

### Actual result

The page is rendering Not Found for a second (depending on connexion speed), then fetch the Dynamic page wrapped in code that I didn't create and the last divs get their classNames changed

### Environment

Gatsby-hello-world-starter with Apollo/client as devDependencies

**Comment by vladar** [comment] 2020-11-06 10:28
Thank you for opening this, @Skobraf 

This is a duplicate of #5329

You should either set up your hosting provider properly or alternatively use this as a workaround: https://github.com/gatsbyjs/gatsby/issues/5329#issuecomment-484741119

We're marking this issue as answered and closing it for now but please feel free to comment and mention me if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Closed by vladar** 2020-11-06 10:28 UTC
Labels: status: triage needed, type: bug
