### ISSUE TITLE
Site/Links are not working after redeployment unless reloaded

### ISSUE THREAD

**Issue by questionablequestion** [gatsbyjs/gatsby#35915] opened 2022-06-11 13:43 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

It's related to #4779 and I'm not sure why is it closed as it's not resolved and it's been 4 years.

This is still an issue. My site is redeployed every 30 minutes and this can cause a problem where visitor is unable to use the site anymore because files from previous build are replaced with new ones and in console it throws exception. Is there any fix for this?

Gatsby v4.0.1 is used.

![ss](https://user-images.githubusercontent.com/12873226/173190451-126ff48a-1a66-4374-b560-6d509aae94c8.jpg)

### Reproduction Link

-

### Steps to Reproduce

1. Deploy the site
2. Open up the site and keep tab open
3. Redeploy the site
4. Links aren't working anymore, you can't do anything

### Expected Result

To either detect new files are there and to reload the site at least (there's `loader.loadPage` inside cache-dir/navigation.js which I would think that it should do that)

### Actual Result

 Links aren't working anymore, you can't do anything

### Environment

```shell
It's on Azure Static Web Apps.
```

**Comment by LekoArts** [comment] 2022-06-13 06:15
Hi, thanks for the issue!

To make the process of resolving problems quicker for both sides we need you to **completely** fill out the issue template and give us a [minimal reproduction][reproduction].

[reproduction]: https://gatsby.dev/reproduction

**Comment by krystofbe** [comment] 2022-06-14 15:11
Hi everyone! We have this error, too and think that this is a bug.

`loadPageSync` can return `undefined`, see https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/loader.js#L385

This bubbles up [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/navigation.js#L88) where there is no check for `undefined` and it is assumed that `then(...)` can always be called.


```
loader.loadPage(pathname + search).then(pageResources => {
(...)
```

this behavior leads to the error 
(cc @meringuedream)

**Comment by LekoArts** [comment] 2022-06-21 04:49
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2022-06-21 04:49 UTC
Labels: type: bug, status: needs reproduction
