### ISSUE TITLE
Hot module replacement not working with the default starter

### ISSUE THREAD

**Issue by Kurren123** [gatsbyjs/gatsby#1769] opened 2017-08-11 08:48 UTC
Windows 10, Chrome 60.0.3112.90. I run:

```
gatsby new gatsby-site
cd gatsby-site
gatsby develop
```

I edit the file `src/pages/index.js` from `<h1>Hi people</h1>` to `<h1>Hi people 123</h1>`. No change is shown in the browser unless I refresh the page. No error is shown on the command line, only:

```
 DONE  Compiled successfully in 379ms                                                                                                                                                    9:40:47 AM

 I  Your site is running at http://localhost:8000
 I  Your graphql debugger is running at http://localhost:8000/___graphql
```

Only the following js errors are reported on the web page itself:

```
lowPriorityWarning.js:40 Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
printWarning @ lowPriorityWarning.js:40
:8000/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by dethi** [comment] 2017-08-12 15:42
Hi,
- What is your current version of gatsby? (run `gatsby -V` in the root directory of your project)
- Did you try in incognito mode? (maybe an extension is blocking the websocket)

**Comment by Kurren123** [comment] 2017-08-14 09:27
Hi @dethi. Still doesn't work after an `npm upgrade` or in incognito mode. My package.json file is:

```
{
  "name": "gatsby-starter-hello-world",
  "description": "Gatsby hello world starter",
  "license": "MIT",
  "scripts": {
    "develop": "gatsby develop",
    "build": "gatsby build",
    "serve": "gatsby serve"
  },
  "dependencies": {
    "gatsby": "1.8.4",
    "gatsby-link": "1.6.7"
  }
}
```

**Comment by Kurren123** [comment] 2017-08-14 09:29
@dethi  please also note that the [react hot boiler plate example](https://github.com/gaearon/react-hot-boilerplate) does work for me.

**Comment by lebilly** [comment] 2017-10-31 07:45
I'm having this issue on a Windows environment.

`gatsby develop` boots fine. I just don't get any hot reload. When I change files, they are compile successfully but no hot reloading is done.

I'm on Gatsby 1.1.13 and using node 8.7

I used `npm i gatsby-cli -g` to install gatsby.

**Comment by thibmaek** [comment] 2017-11-05 17:31
Can definitely back this up, does not work when installing from scratch.

**Comment by jamieguerrero** [comment] 2017-11-19 22:38
I am also experiencing this issue with a previous gatsby project which HMR has worked for in the past.

**Comment by GramParallelo** [comment] 2017-11-20 23:28
hmmm me tooo : / (as reference, hmr works on a clean install of create-react-app)

**Comment by brandonjcreek** [comment] 2017-11-21 15:49
I too am running into this issue when running gatsby develop from a Windows machine.

Node is currently at 9.2.0
Gatspy is currently at 1.9.118

Chrome is throwing the following error in console:
`GET http://0.0.0.0:8000/__webpack_hmr net::ERR_ADDRESS_INVALID`

**Comment by kripod** [comment] 2017-11-21 15:53
@KyleAMathews The issue is that on Windows, `localhost` should be used instead of `0.0.0.0` for development. Since some update which happened during the last few days, all of my webpack-imported resources are being loaded from `0.0.0.0`, which is incorrect for Windows users.

**Comment by mewdriller** [comment] 2017-11-21 18:30
As @kripod mentioned, it looks like the issue is that `program.host` is coming in as `0.0.0.0` on Windows [here](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/webpack.config.js#L135)

**Comment by KyleAMathews** [comment] 2017-11-21 19:25
This should be fixed now https://github.com/gatsbyjs/gatsby/pull/2983

**Closed by KyleAMathews** 2017-11-21 19:25 UTC

**Comment by thibmaek** [comment] 2017-11-21 19:30
My issue was actually occurring on macOS High Sierra (latest stable).

**Comment by rdela** [comment] 2017-11-21 19:38
@thibmaek same deal see https://github.com/gatsbyjs/gatsby/issues/2960#issuecomment-346130796 for more

**Comment by davidprae** [comment] 2017-11-25 23:17
I'm experiencing this issue as well. The site compiles fine but there is no hot reloading. On macOS Sierra.

I receive these warnings in the console when changing a file:

    [HMR] Update check failed: hotDownloadManifest/request.onreadystatechange@http://localhost:8000/commons.js:34:23
    Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://0.0.0.0:8000/80647b0b0c6bc6399147.hot-update.json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

**Comment by kripod** [comment] 2017-11-29 16:04
I just started a new Gatsby project and observed that the wrong behavior starts when I add an `imageSharp` object to a GraphQL query. I think that the bug might be related to `gatsby-plugin-sharp`.

**Comment by Kurren123** [comment] 2017-12-13 15:16
Hi @KyleAMathews. The issue still seems to be there. Windows 10 Chrome gatsby 1.1.27.

**Comment by rdela** [comment] 2017-12-13 21:29
@Kurren123 can you try with Gatsby 1.9.131
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/package.json#L4

and gatsby-cli 1.1.27
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-cli/package.json#L4

…please? If bug persists, what is happening? 0.0.0.0 error? what is your `develop` command? did you try setting `--host`/`-H` `localhost`? Or use your local IP? What works and what fails?

**Comment by Cu3PO42** [comment] 2018-01-26 10:11
It's not working for me either.

I have gatsby-cli 1.1.31 and have tried setting ̀ -H localhost` explicitly.
I have tried with Chrome (Canary) and Firefox (Dev Edition) and got the same results.
This is on Windows Server 2008 R2 (please don't ask).

The behavior I'm seeing specifically is that no hot reloading takes place, however the browser complains about a lost connection to the HMR endpoint when I stop ̀ gatsby develop`.
I'm getting none of the normal HMR output while it is running however.

It works just fine for the project in a Fedora 27 VM. At this point I'm all out of ideas unfortunately :(

**Comment by davidwesst** [comment] 2018-01-29 20:47
It looks like the browser (i.e. client) is the cause of the issue on Windows. When I load up the starter using Microsoft Edge, I see the following message in the console: `webpack-hot-middleware's client requires EventSource to work. You should include a polyfill if you want to support this browser.`

Both Chrome and Firefox appear to support Server-Side Events ([reference](https://caniuse.com/#search=EventSource)) and when I loaded it up in Chrome the hot reload worked as expected.

It looks like the MS Edge status for the feature is "Under Consideration", but until that changes we'll either have to refresh the page manually, add a polyfill, or use a different browser.

**Comment by Cu3PO42** [comment] 2018-01-29 21:32
I don't see how that could be the case in my particular instance since I tried all of Chrome, Chrome Canary, Firefox and Firefox Dev Edition (all up to date).

**Comment by sant123** [comment] 2018-02-16 19:52
With gatsby version 1.9.200 in Windows 10. It doesn't work.

![image](https://user-images.githubusercontent.com/7959437/36326432-09dc4266-1329-11e8-8d33-65740813de11.png)

**Comment by tetreault** [comment] 2018-04-27 13:39
also wanted to chime in that gatsby, while loading my fonts in chrome and safari, also wont load the fonts in mobile safari, mobile chrome, and mobile FF on iOS

**Comment by tetreault** [comment] 2018-04-27 13:53
just chiming in with even more info -- inside the generated styles.css file from `npm run build` I can find the imports of my font files in there, and I see the font files placed in the /static/ folder. so for the life of me I can't figure out why my font-family rules wont work or why these font files arent present when i check the inspector for mobile safari (at least FF had a console error pop up)

**Comment by fardarter** [comment] 2018-07-17 09:16
I'm also seeing this fail. Can't add an error because I'm not getting any – just no HMR.

**Comment by saostad** [comment] 2018-07-26 16:19
same problem here:
```
{
  "name": "gatsby-starter-hello-world",
  "description": "Gatsby hello world starter",
  "license": "MIT",
  "scripts": {
    "develop": "gatsby develop",
    "build": "gatsby build",
    "serve": "gatsby serve"
  },
  "dependencies": {
    "gatsby": "next",
    "react": "^16.3.2",
    "react-dom": "^16.3.2"
  }
}
```

**Comment by fardarter** [comment] 2018-07-26 16:55
I got it working by making a new repo. Go figure.

**Comment by saostad** [comment] 2018-07-26 17:33
what do you mean new repo? Go figure! ?

**Comment by saostad** [comment] 2018-07-27 16:17
I find out hot reloading works with plugins and transformers but if you change data in your react component, it's not working.
