### ISSUE TITLE
[www]: switch from glamor to emotion

### ISSUE THREAD

**Issue by DSchau** [gatsbyjs/gatsby#8816] opened 2018-10-05 00:07 UTC
## Summary

We should swap from glamor to emotion for our CSS in JS needs on [gatsbyjs.org](./www)

### Basic example

Not much to document, but essentially the `css` prop is fully supported in emotion with `gatsby-plugin-emotion` so this should be a relatively doable refactor!

### Motivation

emotion has better theming support, and tends to do everything glamor does (and more!). We also used it on gatsbyjs.com (migrating from glamor -> emotion) and quite liked it.

See #8799 for more info re: theming.

**Comment by KyleAMathews** [comment] 2018-10-05 01:36
>Yeah, sure I can do it. So I should just use css from emotion instead of glamor's one? Without any styled components?

Yes

**Comment by DSchau** [comment] 2018-10-05 15:38
@janczizikow yup, so as long as (for instance) styles.featuredSitesCard is used in a `css` prop block, or in something like

```js
import React from `react`
import styled from `react-emotion`

import styles from `./shared/styles`

const FeaturedSite = styled.div(styles.featuredSitesCard)
```

it should be good to go! Just test it out locally and let us know!

**Comment by janczizikow** [comment] 2018-10-06 11:04
After taking a close look today I found an issue with [GatsbyHubspotForm component](https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/hubspot-form.js#L60). The default styles from Hubspot are still applied, thus messing up a bit the styles of the form. I checked [hubspot docs](https://developers.hubspot.com/docs/methods/forms/advanced_form_options), and I think the issue is that in order to disable default styles you have to pass a `css` prop with an empty string: eg.: `<HubspotForm  css="" />`. It seems like emotion is picking this up and interpreting it as a class and just passesing a className to the `<HubspotForm />` as a prop. Not really sure how to go around this 🤔 

<img width="1280" alt="hubspotform" src="https://user-images.githubusercontent.com/13835666/46570676-394e1380-c968-11e8-9a4d-780ae0e46b8c.png">

**Comment by janczizikow** [comment] 2018-10-07 17:32
Alright, nvm passing `css={...{css: ``}}` as a prop did the trick. Should be all good to go @DSchau

**Comment by Manoz** [comment] 2018-10-09 21:50
@DSchau marked as claimed since @janczizikow is on fire :)

**Closed** 2018-10-12 22:47 UTC
Labels: Hacktoberfest, Hacktoberfest - Claimed, type: feature or enhancement

**Comment by Manoz** [comment] 2018-10-13 15:17
Good job guys. Next step: switch from emotion to styled-components :p

**Comment by DSchau** [comment] 2018-10-13 16:34
@Manoz we'll just have a recurring bi-annual issue to migrate to the hottest CSS in JS framework 😄 

@fk @janczizikow thank you _so_ much for the work here!
