### ISSUE TITLE
[gatsby 2.28.0, gatsby-plugin-mdx 1.6.0] Unable to transclude simple .md file

### ISSUE THREAD

**Issue by clang13** [gatsbyjs/gatsby#28451] opened 2020-12-02 22:57 UTC
## Description

I'm trying to simply transclude one Markdown file into another, and I get errors because it looks like the plain Markdown file is being interpreted as code. Simple text/Markdown results in an error. I believe this should work according to the docs and other examples I have seen. 

### Steps to reproduce

Repro: https://github.com/clang13/my-mdx-starter

```
$ gatsby new my-mdx-starter https://github.com/ChristopherBiscardi/gatsby-starter-mdx-basic
$ cd my-mdx-starter
```

Edit `src/pages/index.mdx`:
```
import Transcluded from './transcluded.md'

# Hi people
```

Create `src/pages/transcluded.md`:
```
Hello world
```

```
$ gatsby build
. . .
info bootstrap finished - 8.510s
success run static queries - 0.146s - 3/3 20.50/s
success run page queries - 0.006s - 4/4 684.66/s
success write out requires - 0.011s
failed Building production JavaScript and CSS bundles - 6.488s
error undefined failed

Unexpected token (1:6)
```

### Expected result

Markdown file is transcluded into index.md.

### Actual result

```
failed Building production JavaScript and CSS bundles - 6.488s
error undefined failed
```

Replacing contents of `transcluded.md` with valid JavaScript works, e.g.:

`src/pages/transcluded.md`:
```
console.log('Hello world!');
```
 
results in

```
$ gatsby build
. . .
info bootstrap finished - 4.341s
success write out requires - 0.003s
success Building production JavaScript and CSS bundles - 2.329s
Hello world!
success Building static HTML for pages - 0.702s - 4/4 5.70/s
success onPostBuild - 0.000s
info Done building in 7.474394189 sec
```

### Environment

```
  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.7.1 - /usr/local/bin/zsh
  Binaries:
    Node: 15.2.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 87.0.4280.67
    Firefox: 81.0.1
    Safari: 14.0.1
  npmPackages:
    gatsby: ^2.13.50 => 2.28.0 
    gatsby-image: ^2.2.8 => 2.7.0 
    gatsby-plugin-manifest: ^2.2.4 => 2.8.0 
    gatsby-plugin-mdx: ^1.0.0 => 1.6.0 
    gatsby-plugin-offline: ^2.2.4 => 2.2.10 
    gatsby-plugin-react-helmet: ^3.1.3 => 3.6.0 
    gatsby-plugin-sharp: ^2.2.9 => 2.10.0 
    gatsby-source-filesystem: ^2.1.8 => 2.7.0 
    gatsby-transformer-sharp: ^2.2.5 => 2.8.0 
```

**Comment by laurieontech** [comment] 2020-12-03 14:53
Thanks for opening the issue! Can you point to a repo with a minimal reproduction. I'd like to be able to see all the plugin configurations and file structure.

**Comment by clang13** [comment] 2020-12-04 13:28
Sorry for the delay. Repro is linked in the description!

> Repro: https://github.com/clang13/my-mdx-starter

Hope this helps.

**Comment by FrancoisDF** [comment] 2021-09-08 07:08
Not sure it's still relevant, but you need to update 2 files to get it transclusion to work:
- In your gatsby-config.json:
```
{
    resolve: `gatsby-plugin-mdx`,
    options: {
      extensions: [`.mdx`, `.md`],
      defaultLayouts: { default: path.resolve('./src/components/layout.js') },
   },
}
```
- In your mdx file:
``` md
import Transcluded from './transcluded.md'

# Hi people

<Transcluded/>
```

As you will see, since the `md` file is now interpreted by `mdx`, you will need to change the way you handle your layout (maybe with `gatsby-plugin-layout`). But that's not the question I think.

You will also see that it's not real transclusion since the `md` is first interpreted then added into the `mdx` file. So it will first be a component that will be cached and therefore included in your bundle... not really the best performance, but that does the trick.
hope that helps.

**Comment by wardpeet** [comment] 2021-10-29 23:19
Closing as we don't support version 2 any more :) Thank you for using Gatsby and feel free to re-open if this is still an issue in v3-v4

**Closed by wardpeet** 2021-10-29 23:19 UTC
Labels: type: bug, topic: remark/mdx
