### ISSUE TITLE
GraphQl Query for allMdx, returning a string for the images instead of a query containing childImageSharp, etc.

### ISSUE THREAD

**Issue by rachit2501** [gatsbyjs/gatsby#24848] opened 2020-06-06 23:18 UTC
## Description
GraphQl Query for allMdx, returning a string for the images instead of a query containing childImageSharp, etc..

### Expected result

This query should run and give access to the query object image.
```
  const data = useStaticQuery(graphql`
    query {
      allMdx {
        nodes {
          frontmatter {
            title
            author
            slug
            image {
              sharp: childImageSharp {
                fluid(
                  maxWidth: 100
                  maxHeight: 100
                  duotone: { shadow: "#663399", highlight: "#ddbbff" }
                ) {
                  ...GatsbyImageSharpFluid_withWebp
                }
              }
            }
          }
          excerpt
        }
      }
    }
  `);
```

### Actual result

Following error on running the dev server:

>  ERROR #85909  GRAPHQL
> Field "image" must not have a selection since type "String" has no subfields

### Environment

```
  System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
    Shell: 5.0.16 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 76.0.1
  npmPackages:
    gatsby: ^2.18.6 => 2.18.6
    gatsby-background-image: ^1.1.1 => 1.1.1
    gatsby-image: ^2.4.6 => 2.4.6
    gatsby-mdx: ^1.0.0 => 1.0.0
    gatsby-plugin-emotion: ^4.1.16 => 4.1.16
    gatsby-plugin-mdx: ^1.2.14 => 1.2.14
    gatsby-plugin-react-helmet: ^3.3.3 => 3.3.3
    gatsby-plugin-sharp: ^2.6.10 => 2.6.10
    gatsby-plugin-tslint: 0.0.2 => 0.0.2
    gatsby-plugin-typescript: ^2.4.4 => 2.4.4
    gatsby-source-filesystem: ^2.3.10 => 2.3.10
    gatsby-transformer-sharp: ^2.5.4 => 2.5.4
```

**Comment by LekoArts** [comment] 2020-06-16 09:00
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by ascorbic** [comment] 2020-06-18 09:44
Hi. I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. Thanks!

**Comment by rachit2501** [comment] 2020-06-18 09:49
Ok. I will make a minimal reproduction as soon as possible.

**Comment by LekoArts** [comment] 2020-06-26 06:52
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-06-26 06:52 UTC
Labels: status: needs reproduction

**Comment by avidrucker** [comment] 2021-05-22 21:02
I'm having the same issue... I'm afraid I can't create a minimal reproduction, though I would be willing to work with a dev one on one.
