### ISSUE TITLE
createPages is called on an infinite loop after edit when developing

### ISSUE THREAD

**Issue by gzzo** [gatsbyjs/gatsby#7456] opened 2018-08-19 19:32 UTC
## Description

createPages is called on an infinite loop after edit when developing

### Steps to reproduce

```
git clone -b without-page-creator https://github.com/gzzo/guido.nyc.git
cd guido.nyc
yarn
gatsby develop

# in new tab
echo "test" >> src/pages/about/index.md
```

### Expected result

Gatsby reloads the data, once

### Actual result

createPages is called infinitely

### Environment
```
  System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.2 - /bin/zsh
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 59.0.2
    Safari: 11.1.2
  npmPackages:
    gatsby: next => 2.0.0-beta.105
    gatsby-paginate: ^1.0.16 => 1.0.16
    gatsby-plugin-feed: next => 2.0.0-beta.4
    gatsby-plugin-google-analytics: next => 2.0.0-beta.5
    gatsby-plugin-offline: next => 2.0.0-beta.9
    gatsby-plugin-page-creator: ^1.0.1 => 1.0.1
    gatsby-plugin-react-helmet: next => 3.0.0-beta.4
    gatsby-plugin-remove-trailing-slashes: next => 2.0.0-beta.3
    gatsby-plugin-sass: next => 2.0.0-beta.10
    gatsby-plugin-sharp: next => 2.0.0-beta.7
    gatsby-remark-copy-linked-files: next => 2.0.0-beta.3
    gatsby-remark-images: next => 2.0.1-beta.10
    gatsby-remark-prismjs: next => 3.0.0-beta.7
    gatsby-remark-responsive-iframe: next => 2.0.0-beta.3
    gatsby-remark-smartypants: next => 2.0.0-beta.3
    gatsby-source-filesystem: next => 2.0.1-beta.10
    gatsby-transformer-remark: next => 2.1.1-beta.6
    gatsby-transformer-sharp: next => 2.1.1-beta.7
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```
### File contents (if changed)

`gatsby-config.js`: https://github.com/gzzo/guido.nyc/blob/without-page-creator/gatsby-config.js
`package.json`: https://github.com/gzzo/guido.nyc/blob/without-page-creator/package.json
`gatsby-node.js`: https://github.com/gzzo/guido.nyc/blob/without-page-creator/gatsby-node.js
`gatsby-browser.js`: N/A
`gatsby-ssr.js`: N/A

**Comment by anantoghosh** [comment] 2018-08-20 11:55
Gatsby already includes and uses `gatsby-plugin-page-creator` for `src/pages`.
I believe specifying it again in your `gatsby-config.js` is causing issues.
If you only want to create pages from the  `pages` directory then you don't need to install it explicitly.

and on the side note, if you do use it for different directories, install the v2 version with @next tag.

**Comment by gzzo** [comment] 2018-08-20 13:45
@anantoghosh I removed `gatsby-plugin-page-creator` entirely and the error still occurs.  I also tried moving the markdown pages I was sourcing with remark from `src/pages` to a new directory and that didn't help either.  The repro steps are the same.

**Comment by anantoghosh** [comment] 2018-08-20 13:56
I cannot reproduce the issue after removing gatsby-plugin-page-creator. Could your update your repo with the changes you made?

**Comment by anantoghosh** [comment] 2018-08-20 15:41
hmm, seems like I misdiagnosed the issue. I don't know why it started behaving correctly before.

**Comment by gzzo** [comment] 2018-08-24 18:17
@Chuloo Why the tag?  @anantoghosh was able to reproduce it.  You can reproduce it yourself too by following the steps in `Steps to reproduce`.  Were you not able to?

**Comment by Chuloo** [comment] 2018-08-24 23:17
thanks @gzzo the reproduction steps are pretty clear enough. 👍

**Comment by gzzo** [comment] 2018-08-28 22:33
@bmihelac Was this fixed somewhere?  Not clear why it was closed.

**Comment by bmihelac** [comment] 2018-08-29 04:28
No, it was not, sorry. It looks like commit from my private repository triggered closing this issue.

**Closed** 2018-08-31 14:14 UTC
Labels: status: confirmed, status: help wanted, type: bug
