### ISSUE TITLE
createNodeField with async function

### ISSUE THREAD

**Issue by IsaacBigsbyTrogdon** [gatsbyjs/gatsby#26786] opened 2020-09-04 14:37 UTC
## Summary

Using `createNodeField()` in `onCreateNode` of `gatsby-node.js`, i'm trying to add a field which uses a values from a fetch GET. It only works if i set the value before the async function, and then AGAIN in the async function... Not a huge deal, just wondering if anyone else has experience with this? Or is there a better way i should solve this?

## Relevant information

This works:

```
exports.onCreateNode = ({ node, actions }) => {
  const { createNodeField } = actions
  createNodeField({
    node,
    name: `pathAlias`,
    value: 'this is a placeholder, see below.',
  })
  const options = {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },
  }
  const fetchData = async () => {
    try {
      const res = await fetch(menuUrl, options)
      const json = await res.json()
      const { alias } = json
      if (typeof alias !== 'undefined') {
        createNodeField({
          node,
          name: `pathAlias`,
          value: alias,
        })
      }
    } catch (respError) {
      console.log(respError)
    }
  }
  fetchData()
}
```

But this doesn't:

```
exports.onCreateNode = ({ node, actions }) => {
  const { createNodeField } = actions
  const options = {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },
  }
  const fetchData = async () => {
    try {
      const res = await fetch(menuUrl, options)
      const json = await res.json()
      const { alias } = json
      if (typeof alias !== 'undefined') {
        createNodeField({
          node,
          name: `pathAlias`,
          value: alias,
        })
      }
    } catch (respError) {
      console.log(respError)
    }
  }
  fetchData()
}
```

### Environment

```
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.8.0 - ~/.nvm/versions/node/v14.8.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v14.8.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 85.0.4183.83
    Firefox: 80.0.1
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.19.32 => 2.24.51
    gatsby-awesome-pagination: ^0.3.6 => 0.3.6
    gatsby-image: ^2.2.40 => 2.4.16
    gatsby-plugin-breadcrumb: ^10.0.0 => 10.0.0
    gatsby-plugin-catch-links: ^2.2.1 => 2.3.11
    gatsby-plugin-google-analytics: ^2.2.2 => 2.3.13
    gatsby-plugin-manifest: ^2.2.42 => 2.4.25
    gatsby-plugin-nprogress: ^2.3.10 => 2.3.10
    gatsby-plugin-offline: ^3.0.32 => 3.2.25
    gatsby-plugin-react-helmet: ^3.1.22 => 3.3.10
    gatsby-plugin-robots-txt: ^1.5.1 => 1.5.1
    gatsby-plugin-sass: ^2.3.2 => 2.3.12
    gatsby-plugin-sharp: ^2.4.7 => 2.6.29
    gatsby-plugin-sitemap: ^2.2.27 => 2.4.12
    gatsby-plugin-styled-components: ^3.1.19 => 3.3.10
    gatsby-plugin-svgr: ^2.0.2 => 2.0.2
    gatsby-plugin-theme-ui: 0.3.0 => 0.3.0
    gatsby-plugin-typography: ^2.3.22 => 2.5.10
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-drupal: ^3.5.30 => 3.5.30
    gatsby-source-filesystem: ^2.1.48 => 2.3.26
    gatsby-source-rest-api: ^0.2.3 => 0.2.3
    gatsby-transformer-sharp: ^2.3.17 => 2.5.13
```

**Comment by pvdz** [comment] 2020-09-08 09:31
Hi @IsaacBigsbyTrogdon. I think what you're looking for is `await`, and to propagate that upward.

Your example would look something like the following. I've added `async` to the arrow that is assigned to `exports.onCreateNode` and added awaits for the call. 

```js
exports.onCreateNode = async ({ node, actions }) => {
  const { createNodeField } = actions
  createNodeField({
    node,
    name: `pathAlias`,
    value: 'this is a placeholder, see below.',
  })
  const options = {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },
  }
  const fetchData = async () => {
    try {
      const res = await fetch(menuUrl, options)
      const json = await res.json()
      const { alias } = json
      if (typeof alias !== 'undefined') {
        createNodeField({
          node,
          name: `pathAlias`,
          value: alias,
        })
      }
    } catch (respError) {
      console.log(respError)
    }
  }
  await fetchData()
}
```

And unless you have a deeper reason for having the `fetchData` function, you can also just omit it;

```js
exports.onCreateNode = async ({ node, actions }) => {
  const { createNodeField } = actions
  createNodeField({
    node,
    name: `pathAlias`,
    value: 'this is a placeholder, see below.',
  })
  const options = {
    method: 'GET',
    headers: {
      'Content-Type': 'application/json',
    },
  }
  try {
    const res = await fetch(menuUrl, options)
    const json = await res.json()
    const { alias } = json
    if (typeof alias !== 'undefined') {
      createNodeField({
        node,
        name: `pathAlias`,
        value: alias,
      })
    }
  } catch (respError) {
    console.log(respError)
  }
}
```

Going to close this. I'm pretty sure this is a syntactical problem, not caused by Gatsby.

**Closed by pvdz** 2020-09-08 09:31 UTC
Labels: status: triage needed, type: question or discussion
