### ISSUE TITLE
Mobile CSS not injecting after build

### ISSUE THREAD

**Issue by NLeRoy917** [gatsbyjs/gatsby#23508] opened 2020-04-26 22:15 UTC
## Description

My Gatsby site functions as expected for both browser and mobile views when I am in development mode. (`gatsby develop`). However, once deploying to Heroku and building the static site, CSS appears to not load when viewed from mobile devices (or Chromes mobile view in dev tools). Its almost as if it doesn't get injected. I can inspect the elements to see the class names are there and the same, but no CSS gets injected and all my components lose their styling.

I rely heavily on Material-UI's `makeStyles()` function to style my components. I find it so much easier to work with than separate css files.. not sure if this could be causing the issue.

Note: I have tried pretty much all permutations of `gatsby-plugin-material-ui`, `gatsby-theme-material-ui` and `gatsby-styled-components` in my `gatsby-config.json` file. Also, considering the issue is there when I build and serve locally... I can ignore Heroku/the environment as a probable cause.

### Steps to reproduce
1. `git clone https://github.com/NLeRoy917/myresume`
2. `gatsby build`
3. `gatsby serve`
4. Open https://localhost:9000 in browser
5. View web page using developer tools for a mobile view
6. Refresh page

### Expected result

CSS should remain consistent between mobile and browser views (or at least be responsive as designed using CSS). Page should re-scale and change layout according to CSS rules defined in src/. Should be able to inspect element and view my custom CSS rules on elements/components.

### Actual result

CSS fails to load/inject, and all my components lose their styling - site becomes completely dysfunctional. When inspecting element, all CSS styling is gone even though classnames persist.

### Environment

  System:
    OS: macOS 10.15.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 73.0.1
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.20.25 => 2.20.25 
    gatsby-image: ^2.3.4 => 2.3.4 
    gatsby-plugin-manifest: ^2.3.5 => 2.3.5 
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.6 
    gatsby-plugin-offline: ^3.1.4 => 3.1.4 
    gatsby-plugin-react-helmet: ^3.2.4 => 3.2.4 
    gatsby-plugin-sharp: ^2.5.6 => 2.5.6 
    gatsby-plugin-styled-components: ^3.2.4 => 3.2.4 
    gatsby-source-filesystem: ^2.2.4 => 2.2.4 
    gatsby-theme-material-ui: ^1.0.8 => 1.0.8 
    gatsby-transformer-sharp: ^2.4.6 => 2.4.6 
  npmGlobalPackages:
    gatsby-cli: 2.11.15

**Comment by NLeRoy917** [comment] 2020-04-27 14:35
I tried porting my entire website over to Next.js - The issue still persists. I imagine this must be an issue with Material-UI now, since it still occurs outside the entire Gatsby ecosystem.

**Comment by johno** [comment] 2020-05-05 15:36
Thanks for opening an issue @NLeRoy917! If you run `gatsby build` locally and then run `npx serve public` do you see the same behavior? This will help rule out potential problems in your build though it sounds to me like it might be a problem with `material-ui` since it only appears to affect certain/mobile devices.

Sometimes this can happen when you have multiple libraries on the page that share context since they will stomp eachother (styled-components or material-ui).

**Comment by johno** [comment] 2020-05-05 15:37
Since you're seeing the same behavior in Next.js as well I'm inclined to think it's not a problem on Gatsby's end so I will close this for now. If you can only reproduce it in Gatsby please let us know and we can debug!

**Closed by johno** 2020-05-05 15:37 UTC
Labels: topic: themes, type: bug

**Comment by NLeRoy917** [comment] 2020-05-05 15:51
@johno Thanks for commenting! Yes, building and serving locally has the issue persist. I agree, it's most likely not a Gatsby bug since Next.js does the exact same thing. Next time around, I will try to isolate css ad styling away from `material-ui`. Thanks!

**Comment by lrdass** [comment] 2021-03-27 01:11
If you still having the same problem: https://github.com/mui-org/material-ui/tree/master/examples/gatsby/plugins/gatsby-plugin-top-layout
I realised that in my application the `theme` wasn't being actually updated. 
Notice also that is only using `gatsby-plugin-material-ui`, `gatsby-theme-material-ui` isn't needed.
