### ISSUE TITLE
[gatsby-transformer-json] Can not query field `allFooterJson`

### ISSUE THREAD

**Issue by muuvmuuv** [gatsbyjs/gatsby#13688] opened 2019-04-28 16:42 UTC
## Description

When I try to access content from one of my JSON data files it seems GraphQL doesn't know the file. I have two files `content/data/social-media.json` and `content/data/footer.json`. The first one is an array the second an object. I added the plugin to my [gatsby-config.js](https://hastebin.com/atiyaboloj.js). `social-media.json` works fine when I call:

```graphql
{
  allSocialMediaJson {
    edges {
      node {
        id
      }
    }
  }
}
```

but `footer.json` does not work.. `"message": "Cannot query field \"allFooterJson\" on type \"Query\". Did you mean \"allDataJson\" or \"allSocialMediaJson\"?",`

### Reproduce

1. git clone https://github.com/gatsbyjs/gatsby-starter-blog
2. add gatsby-transformer-json
3. create a file like footer.json:
```json
{
  "links": [
    {
      "name": "Kontakt",
      "link": "#"
    }
  ]
}
```
4. create a second file something.json:
```json
["some", "cool"]
```

- footer.json not accessible
- something.json returns single characters instead of strings:
```graphql
{
  allSomethingJson {
    edges {     
      node {
        id
        _0
      }
    }
  }
}
```

### Environment

  System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 73.0.3683.103
    Firefox: 66.0.3
    Safari: 12.1
  npmPackages:
    gatsby: ^2.3.32 => 2.3.32 
    gatsby-plugin-catch-links: ^2.0.13 => 2.0.13 
    gatsby-plugin-emotion: ^4.0.6 => 4.0.6 
    gatsby-plugin-layout: ^1.0.15 => 1.0.15 
    gatsby-plugin-manifest: ^2.0.29 => 2.0.29 
    gatsby-plugin-purgecss: ^3.1.1 => 3.1.1 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-react-helmet-canonical-urls: ^1.2.0 => 1.2.0 
    gatsby-plugin-sass: ^2.0.11 => 2.0.11 
    gatsby-plugin-sharp: ^2.0.35 => 2.0.35 
    gatsby-plugin-typescript: ^2.0.13 => 2.0.13 
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.4 => 1.0.4 
    gatsby-remark-copy-linked-files: ^2.0.12 => 2.0.12 
    gatsby-remark-emoji: 0.0.2 => 0.0.2 
    gatsby-remark-images: ^3.0.11 => 3.0.11 
    gatsby-source-filesystem: ^2.0.32 => 2.0.32 
    gatsby-transformer-json: ^2.1.11 => 2.1.11 
    gatsby-transformer-remark: ^2.3.12 => 2.3.12 
    gatsby-transformer-sharp: ^2.1.18 => 2.1.18 
  npmGlobalPackages:
    gatsby-cli: 2.4.16

**Comment by jonniebigodes** [comment] 2019-04-28 16:47
@muuvmuuv let me take a look at it and see if i can come up with a solution for your issue. Do you mind waiting just a bit while i tackle another issue? Sounds good?

**Comment by jonniebigodes** [comment] 2019-04-28 20:00
@muuvmuuv sorry for the delay, the other issue took me a little longer to work on.
Below are the steps i took to solve your issue.

- Created a new Gatsby website, i used the hello world starter to avoid unnecessary packages being added and keep the reproduction simple.
- Added the dependencies `gatsby-source-filesystem` and `gatsby-transformer-json`.
- Created the folder structure to emulate yours which resulted in
```sh
 |project-root
   |content
     |data
       - footer.json
       - something.json
```

- The file `footer.json` has the following content:
```json
{
    "links":[
        {
            "name":"Kontakt",
            "link":"#"
        }
    ]
}
```
- The file `something.json` has the following content:
```json
["some", "cool"]
```
- Created `gatsby-config.js` with the following content:
```javascript
module.exports={
    plugins:[
        `gatsby-transformer-json`,
         {
             resolve:`gatsby-source-filesystem`,
             options:{
                 name:`json_data`,
                 path:`./content/data`
             }
         }
    ]
}
```

- Issued `gatsby develop`, waited for the build process to complete and opened `http://localhost:8000/___graphql` and created the following query
```graphql
{
  allSomethingJson {
    edges {
      node {
      }
    }
  }
}

````
I'm presented with the following:
![muuvmuuv_1](https://user-images.githubusercontent.com/22988955/56869046-f8484a00-69f2-11e9-8a9e-0e213e4cd466.png)

- The reason for that behaviour is that the plugin tried to parse the content as a valid json object as it's not, it transformed it like so.
- If you modify `something.json` to something like:
```json
{
    "something_something":["some", "cool"]
}
```
- Issue `gatsby clean && gatsby develop`, to purge the build files and rebuild the website.
- Opening up `http://localhost:8000/___graphql`, you'll loose the `allFooter` or `allsomething` nodes, as there's more than one file present in the folder, all of the json nodes will be coalesced into a diferent node called `allDataJson` as you can see below:
![muuvmuuv_2](https://user-images.githubusercontent.com/22988955/56869318-35aed680-69f7-11e9-8883-2d4e5b04bab7.png)

- Now if you want to preserve the individual files you'll have to make some adjustments.
- Move each json file to it's individual folder transforming your file/folder structure into something like
```sh
   |project-root
    |content
     |data
        |footer
          - footer.json
        |other
          -something.json
      
```
- Modify `gatsby-config.js` into something like so:
```javascript
module.exports={
    plugins:[
        `gatsby-transformer-json`,
        
         {
             resolve:`gatsby-source-filesystem`,
             options:{
                 name:`json_data`,
                 path:`./content/data/footer`
             }
         },
         {
            resolve:`gatsby-source-filesystem`,
            options:{
                name:`json_other`,
                path:`./content/data/other`
            }
         }
    ]
}
```
- If you issue once more `gatsby clean && gatsby develop` and open up `http://localhost:8000/___graphql` you'll have access to each individual files as you can see below:

![muuvmuuv_3](https://user-images.githubusercontent.com/22988955/56869417-6a6f5d80-69f8-11e9-8f1c-3eab4e19f77c.png)

Feel free to provide feedback so that we can close this issue, or continue to work on it until we find a solution.

**Comment by muuvmuuv** [comment] 2019-04-29 06:14
Hey @jonniebigodes, 

first thanks for this detailed issue fix, really awesome and easy to follow!

Okay, I understand now how it works but I really dislike this way, IMO this makes it more complex. Can we not provide an option like `parseEachFileIndividual` so we select one folder where each file gets its own query? And I didn't know that just an array in JSON is not valid... sadly :D IMO this would make JSON file more awesome and prettier! Maybe we could support this way to with an option `experimentalJson`?

I'm going to use it that way you suggested above for now but would really like to hear your opinion about my options to make it more "modern", "expendable".

**Comment by jonniebigodes** [comment] 2019-04-29 18:09
@muuvmuuv no need to thank, glad that i was able to be of assistance.

Regarding your previous comment, basically that's the way the plugin is defined and the parsing algorithm is implemented as of now, as of the present state of the plugin.

If you want and you're willing, fork the repo, read the appropriate docs [here](https://www.gatsbyjs.org/docs/how-to-contribute/) for contributions, make the necessary adjustments to the plugin in question and submit a pull request. Alternatively if you don't want to use graphql, you can bypass the plugin and add the json file directly into the client(page/component), this done at build time you'll have access to the json content you want. It's entirely up to and also the beauty of Gatsby, you don't have one way of achieving the same result but several ways.

**Closed** 2019-04-30 06:38 UTC
Labels: status: awaiting author response, type: question or discussion
