### ISSUE TITLE
Gatsby Scroll Issues on Page Change/Link Click

### ISSUE THREAD

**Issue by rabiiayed** [gatsbyjs/gatsby#30196] opened 2021-03-11 14:41 UTC
When clicking a link on front page with a list of posts after scrolling down for example, would result in the new content being scrolled down as much as previous page.

At first I have read many other posts and issues mentioning it was related to css / body height etc but could not find a solution to this.

I have setup Gatsby completely from scratch to reconfirm my problem is not related to css.

Things seems to work fine in development mode. This happens on production

**Steps to reproduce**
Scroll to bottom of post listing page
Click any links
Notice the next loaded page is scrolled to the bottom like previous page

**Expected result**
After scrolling down from index page, the link click should load a new page, with the view at top.

**Actual result**
New page is loaded at the scrolled location of previous page

**Dependencies**
"gatsby": "^2.32.8",
    "gatsby-background-image": "^1.4.1",
    "gatsby-image": "^2.11.0",
    "gatsby-plugin-catch-links": "^2.10.0",
    "gatsby-plugin-gatsby-cloud": "^1.0.2",
    "gatsby-plugin-manifest": "^2.12.1",
    "gatsby-plugin-no-sourcemaps": "^3.0.0",
    "gatsby-plugin-offline": "^3.10.2",
    "gatsby-plugin-react-helmet": "^3.10.0",
    "gatsby-plugin-sass": "^3.2.0",
    "gatsby-plugin-sharp": "^2.14.3",
    "gatsby-source-filesystem": "^2.11.1",
    "gatsby-transformer-sharp": "^2.12.0",

**Comment by LekoArts** [comment] 2021-03-11 15:50
Duplicate of https://github.com/gatsbyjs/gatsby/issues/30026 - please link your reproduction repository there. Thanks!

**Closed by LekoArts** 2021-03-11 15:50 UTC
Labels: status: triage needed
