### ISSUE TITLE
Styles don't load consistently to some of the visitors

### ISSUE THREAD

**Issue by alesanchezr** [gatsbyjs/gatsby#27328] opened 2020-10-07 20:59 UTC
## Description

Some times the website loads without styles, just the content and HTML, sometimes it also happends with only oen component and the rest loads ok.

### Steps to reproduce

I have not been able to reproduce but I have video recordings of people:
1. [This guys in minute 24. ](https://insights.hotjar.com/r?site=2016936&recording=4115787925&token=8a4d462c13370daa72c9625927db2945)

- [This guy in minute 7](https://insights.hotjar.com/r?site=2016936&recording=4073618328&token=cac9120e3c91c3885d76d85f666b7203)

I have more recordings if you guys want.

### Expected result
The styles should load fine, the website should look good.

### Actual result
Styles always load fine at the beginning, the user is able to browse but then it breaks at some point.

### Environment
The website is hosted in vercel, information about environments (browser, os, etc) is inside each recording.

Here is my local environment, this bug its not happening in local (that I know of)
```
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
    npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
  Languages:
    Python: 3.8.1 - /Users/alejandrosanchez/.pyenv/shims/python
  Browsers:
    Chrome: 85.0.4183.121
    Safari: 14.0
  npmPackages:
    gatsby: ^2.24.2 => 2.24.2
    gatsby-background-image: ^1.1.2 => 1.1.2
    gatsby-image: ^2.4.14 => 2.4.14
    gatsby-plugin-gdpr-cookies: ^1.0.7 => 1.0.7
    gatsby-plugin-google-tagmanager: ^2.1.25 => 2.1.25
    gatsby-plugin-manifest: ^2.2.14 => 2.2.21
    gatsby-plugin-meta-redirect: ^1.1.1 => 1.1.1
    gatsby-plugin-offline: ^3.0.2 => 3.0.14
    gatsby-plugin-react-helmet: ^3.1.22 => 3.1.22
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-robots-txt: ^1.5.1 => 1.5.1
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5
    gatsby-plugin-sharp: ^2.2.19 => 2.2.29
    gatsby-plugin-sitemap: ^2.2.27 => 2.2.27
    gatsby-plugin-styled-components: ^3.1.4 => 3.1.9
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-plugin-zeit-now: ^0.2.0 => 0.2.0
    gatsby-remark-images: ^3.3.27 => 3.3.27
    gatsby-remark-lazy-image-url: ^1.0.1 => 1.0.1
    gatsby-remark-lazy-load: ^1.0.2 => 1.0.2
    gatsby-remark-reading-time: ^1.1.0 => 1.1.0
    gatsby-source-filesystem: ^2.1.21 => 2.1.31
    gatsby-transformer-remark: ^2.6.32 => 2.6.32
    gatsby-transformer-sharp: ^2.2.13 => 2.2.21
    gatsby-transformer-yaml: ^2.2.15 => 2.2.15
  npmGlobalPackages:
    gatsby-cli: 2.11.5
```

**Comment by ascorbic** [comment] 2020-10-08 10:43
Hi. I'm not sure I can think of any way we can address this without a way to reproduce it. If you can think of a way then please share, otherwise we don;t really have anywhere to start. Do you have any idea of how common the issue is?

**Comment by LekoArts** [comment] 2020-10-19 08:28
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-10-19 08:28 UTC
Labels: status: needs reproduction, topic: styled-components, type: bug
