### ISSUE TITLE
Unable to load SCSS after migrating to V2 from V1

### ISSUE THREAD

**Issue by deepsyx** [gatsbyjs/gatsby#9982] opened 2018-11-16 16:45 UTC
We're migrating from gatsby v1 to v2. However we couldn't manage to resolve the following error:

> ERROR in ./src/assets/scss/app.scss (./node_modules/css-loader??ref--13-oneOf-1-1!./node_modules/postcss-loader/lib??postcss-3!./node_modules/sass-loader/lib/loader.js??ref--13-oneOf-1-3!./src/assets/scss/app.scss)
> Module build failed (from ./node_modules/sass-loader/lib/loader.js):
> 
> // LICENSE: BSD-3-Clause
> ^
>       Invalid CSS after "...://git.io/vZkLP": expected 1 selector or at-rule, was "var LTGrid = (funct"
>       in /home/viktor/Work/homepage/node_modules/layout-grid/dist/js/layout-grid.js (line 1, column 1)
>  @ ./src/assets/scss/app.scss 2:14-226 21:1-42:3 22:19-231
>  @ ./src/pages/index.jsx
>  @ ./.cache/sync-requires.js
>  @ ./.cache/app.js
>  @ multi (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app
> 

We have `pages/index.jsx`, which `import "assets/scss/app.scss";` at the beggining of the file.
Our app.scss looks like:

```
// Vendor components
@import "variables";
@import "bootstrap";
........
```

In our gatsby-config we have:

```
plugins: [  
       "gatsby-plugin-postcss",
       "gatsby-plugin-sass",
] 
```
We tried using only plugin-postcss or only plugin-sass. `node-sass` is added to package.json.

```
  "gatsby": "^2.0.50",
        "gatsby-image": "^2.0.0-rc.4",
        "gatsby-link": "^2.0.0-rc.4",
        "gatsby-plugin-canonical-urls": "^2.0.0-rc.2",
        "gatsby-plugin-html-attributes": "^1.0.5",
        "gatsby-plugin-postcss": "^2.0.0-rc.5",
        "gatsby-plugin-postcss-sass": "^1.0.0-beta.6",
        "gatsby-plugin-react-helmet": "^3.0.0-rc.1",
        "gatsby-plugin-root-import": "^2.0.4",
        "gatsby-plugin-sass": "^2.0.4",
        "gatsby-plugin-sharp": "^2.0.0-rc.7",
        "gatsby-plugin-sitemap": "^2.0.0-rc.2",
        "gatsby-source-filesystem": "^2.0.1-rc.6",
        "gatsby-transformer-json": "^2.1.1-rc.6",
        "gatsby-transformer-sharp": "^2.1.1-rc.3",
```

On Ubuntu 18.04.

What might be causing our problem?

**Comment by justinformentin** [comment] 2018-11-17 00:09
Just looking at it like that, it should work; there has to be something else going on. Are you able to link to the project so the issue can be reproduced?

**Comment by jonniebigodes** [comment] 2018-11-18 20:09
i've cloned a fresh starter and added gatsby-plugin-sass and node-sass, as per [docs](https://www.gatsbyjs.org/packages/gatsby-plugin-sass/), followed your directory structure created /assets/scss/ and added a app.scss and a variables.scss.
The contents of app.scss

```css
@import "variables.scss";

.myButton {
    background-color: $buttonbackgroundColor;
    width: $buttonwidth;
    color:$grey;
}
.myText{
    color: $textcolor;
    font-size: $smallFont;
}
.biggerText{
    color: $textcolor;
    font-size: $mediumFont;
}
```
and for ilustration purposes the contents of the variables.scss, my gatsby-config.js and the page component.
The variables scss file.
```css
$black: #000;
$white: #fff;
$grey:#c9c2bb;
$buttonbackgroundColor:#41344f;
$buttonwidth: 5em;
$textcolor:#2e0759;
$smallFont:14px;
$mediumFont:16px;
```
gatsby-config.js
```javascript
module.exports = {
  siteMetadata: {
    title: 'Gatsby Default Starter',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    'gatsby-transformer-sharp',
    'gatsby-plugin-sharp',
    'gatsby-plugin-sass',
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: 'gatsby-starter-default',
        short_name: 'starter',
        start_url: '/',
        background_color: '#663399',
        theme_color: '#663399',
        display: 'minimal-ui',
        icon: 'src/images/gatsby-icon.png', // This path is relative to the root of the site.
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.app/offline
    // 'gatsby-plugin-offline',
  ],
}
```
The index page (index.js) contents.
```javascript
import React from 'react'
import { Link } from 'gatsby'

import Layout from '../components/layout'
import Image from '../components/image'
import '../assets/scss/app.scss'

const IndexPage = () => (
  <Layout>
    <h1>Hi people</h1>
    <p>Welcome to your new Gatsby site.</p>
    <p>Now go build something great.</p>
    <div style={{ maxWidth: '300px', marginBottom: '1.45rem' }}>
      <Image />
    </div>
    <div>
      <button className="myButton">Styled with scss</button>
    </div>
    <div>
      <p className="myText">Hello</p>
      <span className="biggerText">World</span>
    </div>
    <Link to="/page-2/">Go to page 2</Link>
  </Layout>
)

export default IndexPage
```
Tested it with develop on a machine running the latest ubuntu release a windows 10 machine, it showed the result intended.
Cleaned the build and .cache folders to ensure a clean slate.
Ran `gatsby build`  and `gatsby serve` and the exact same result on both.
The only thing diferent was the `.scss` extension added to the import.

And from the description you posted, one thing caught my eye and that is the following:

```zsh
Invalid CSS after "...://git.io/vZkLP": expected 1 selector or at-rule, was "var LTGrid = (funct"
in /home/viktor/Work/homepage/node_modules/layout-grid/dist/js/layout-grid.js (line 1, column 1)
@ ./src/assets/scss/app.scss 2:14-226 21:1-42:3 22:19-231
```
You might have imported some other library and imported it into app.scss that is throwing a monkey wrench on the build.
But like @justinformentin said if you can share the repository url if the work you're doing is not private or corporate so that we can verify what is actually happening in more detail.
If not create a dummy repository similar to the work you're doing and share it.

**Comment by deepsyx** [comment] 2018-11-20 13:59
I figured out the problem. It caused because I had in my previous configuration:

```
       {
            resolve: `gatsby-plugin-postcss-sass`,
            options: {
                precision: "8",
                includePaths: [
                    path.resolve(__dirname, "./node_modules"),
                    path.resolve(__dirname, "./node_modules/bootstrap-sass/assets/stylesheets"),
                    path.resolve(__dirname, "./node_modules/layout-grid/sass"),
                    path.resolve(__dirname, "./node_modules/slick-carousel/slick"),
                ],
                postCssPlugins: [
                    autoprefixer({
                        browsers: ["last 2 versions"],
                    }),
                ],
            },
        },
```

So in the old SCSS files I was importing files from `./node_modules/layout-grid/sass` with the following line:

`@import "slick.scss";`

However with the new configuration I had to write the full path like:

`@import "~slick-carousel/slick/slick.scss";` 

and it worked fine.

Thanks for the help!

**Comment by jonniebigodes** [comment] 2018-11-20 18:21
No problem.
Glad you figured it out.
Going to close this if you don't mind, thanks for using Gatsby 👍

**Closed by jonniebigodes** 2018-11-20 18:21 UTC
Labels: status: needs more info

**Comment by fadhlaouir** [comment] 2021-06-08 22:12
is there any solution to use variables without `@import "./.."` ?
