### ISSUE TITLE
Some links' hrefs get mangled

### ISSUE THREAD

**Issue by vladdu** [gatsbyjs/gatsby#6888] opened 2018-07-31 12:30 UTC
## Description

When browsing https://www.netlifycms.org/docs/ (which uses gatsby), whenever there is a link pointing to the same domain, it is mangled:

For example on `https://www.netlifycms.org/docs/intro`, the link to `https://www.netlifycms.org/docs/start-with-a-template/` it becomes ` https://www.netlifycms.org/docs/intro/https://www.netlifycms.org/docs/start-with-a-template/`

I saw a comment in catch-links.js:56 saying that something like this can happen.

I can see this on Windows, with Chrome 68, Edge 42, but not IE 11. 

### Steps to reproduce

- Open https://www.netlifycms.org/docs/intro
- Click on link "Start with a template" near the bottom of the body text

### Expected result

The page referred to should open

### Actual result

"404 not found" error

### Environment

Chrome 68.0.3440.75 (Official Build) (64-bit)
Edge 42.17134.1.0

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by vladdu** [comment] 2018-07-31 12:34
They are using gatsby 1.9.270, according to their config file.

**Comment by vladdu** [comment] 2018-07-31 12:43
The related commit is 10ed7cb542

**Comment by vladdu** [comment] 2018-07-31 12:45
More relevant versoin number: "gatsby-plugin-catch-links": "^1.0.22",

**Comment by vladdu** [comment] 2018-07-31 14:26
I get the same thing with Edge  42.17134.1.0, but not IE 11.165.

**Comment by anantoghosh** [comment] 2018-07-31 17:07
Duplicate of https://github.com/gatsbyjs/gatsby/issues/6686

**Comment by Chuloo** [comment] 2018-07-31 21:31
Whoops! Hi @vladdu, please see the referenced duplicate issue. Should be solved soon! Feel free to [open a new one](https://github.com/gatsbyjs/gatsby/issues/new/choose) _if_ you have any more issues. 👍

**Closed by Chuloo** 2018-07-31 21:31 UTC
Labels: Duplicate
