### ISSUE TITLE
Glamor not working on html.js

### ISSUE THREAD

**Issue by ricardocosta89** [gatsbyjs/gatsby#1449] opened 2017-07-10 12:10 UTC
I can't make `glamor` work on `html.js` file, even though it works on normal pages. The generated HTML has the `<body class="css-cos7w3">` but no style is associated with it when checking Chrome Dev Tools.

`html.js` (does not work):
```
// Imports present in starter
import { css } from 'glamor'

const bodyStyle = css({
  margin: '0',
  background: 'red'
})

// No changes to HTML class

render() {
  // No changes to CSS injection

  return (
    <html lang="en">
      // No changes to <head>
      <body css={bodyStyle}>
        <div
          id="___gatsby"
          dangerouslySetInnerHTML={{ __html: this.props.body }}
        />
        {this.props.postBodyComponents}
      </body>
    </html>
  )
}
```

`pages/index.js` (works):
```
import React from 'react'
import Link from 'gatsby-link'
import { css } from 'glamor'

const h1Style = css({
  margin: '0',
  color: 'red'
})

export default class Index extends React.Component {
  render() {
    return (
      <div>
        <h1 css={h1Style}>Hi people</h1>
        <p>Welcome to your new Gatsby site.</p>
        <p>Now go build something great.</p>
        <Link to="/page-2/">Go to page 2</Link>
      </div>
    )
  }
}
```

Thanks in advance.

---
**Gatsby version:** gatsby@1.0.7
**node.js version:** v8.1.3
**OS version:** macOS Sierra 10.12.5

`gatsby-config.js`:

```
module.exports = {
  siteMetadata: {
    title: 'A title',
  },
  plugins: [
    {
      resolve: 'gatsby-plugin-google-analytics',
      options: {
        trackingId: 'YOUR_GOOGLE_ANALYTICS_TRACKING_ID',
      },
    },
    {
      resolve: 'gatsby-plugin-nprogress',
      options: {
        color: '#2F81B7',
      }
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/src/pages`,
        name: 'pages',
      },
    },
    {
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/src/posts`,
        name: 'posts',
      },
    },
    {
      resolve: 'gatsby-transformer-remark',
      options: {
        plugins: [
          {
            resolve: 'gatsby-remark-images',
            options: {
              maxWidth: 700,
            },
          },
          {
            resolve: 'gatsby-remark-responsive-iframe',
            options: {
              wrapperStyle: 'margin-bottom: 1.0725rem',
            },
          },
          'gatsby-remark-copy-linked-files',
          'gatsby-remark-prismjs',
          'gatsby-remark-smartypants'
        ]
      }
    },
    'gatsby-plugin-glamor',
    'gatsby-plugin-react-helmet'
  ],
}
```

`package.json`:
```
{
  "dependencies": {
    "gatsby": "^1.0.7",
    "gatsby-link": "^1.0.9",
    "gatsby-plugin-glamor": "^1.0.6",
    "gatsby-plugin-google-analytics": "^1.0.1",
    "gatsby-plugin-nprogress": "^1.0.1",
    "gatsby-plugin-react-helmet": "^1.0.1",
    "gatsby-remark-copy-linked-files": "^1.0.1",
    "gatsby-remark-images": "^1.0.1",
    "gatsby-remark-prismjs": "^1.0.1",
    "gatsby-remark-responsive-iframe": "^1.0.1",
    "gatsby-remark-smartypants": "^1.0.1",
    "gatsby-source-filesystem": "^1.0.1",
    "gatsby-transformer-remark": "^1.0.9"
  },
  "devDependencies": {
    "@storybook/react": "^3.1.8",
    "babel-eslint": "^7.2.3",
    "babel-jest": "^20.0.3",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "eslint": "^4.2.0",
    "eslint-config-prettier": "^2.3.0",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.1.0",
    "eslint-plugin-prettier": "^2.1.2",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-react": "^7.1.0",
    "gh-pages": "^1.0.0",
    "jest": "^20.0.4",
    "prettier": "^1.5.2",
    "react-test-renderer": "^15.6.1"
  },
  "scripts": {
    "build": "gatsby build",
    "deploy": "gatsby build --prefix-paths && gh-pages -d public",
    "develop": "gatsby develop",
    "eslint-check": "eslint --print-config .eslintrc.json | eslint-config-prettier-check",
    "lint": "eslint src stories __tests__",
    "format": "eslint --fix src stories __tests__",
    "test": "jest --colors --coverage",
    "serve": "gatsby serve",
    "storybook": "start-storybook -p 9001 -c .storybook"
  }
}
```

**Comment by felixjung** [comment] 2017-07-10 19:28
Hey, I'm pretty sure this is a duplicate of #1442. I also found that styles would only be applied after restarting the dev server. But the issue was not limited to styles. Any other changes would also not be reflected in `html.js`. Can you double check?

**Comment by ricardocosta89** [comment] 2017-07-10 19:47
I saw the issue and tried to restart the `develop` script with no success.

The only way to have the `body` recognise the style is to use `<body style={{ margin: 0, background: 'red' }}>`, or refer to a previously created object with the properties, but without using Glamor's `css()`.

**Comment by craig-mulligan** [comment] 2017-07-11 08:17
@ricardocosta89 html.js is compiled with `renderToStaticMarkup` in a separate webpack process, the core app/website is then mounted on it. I assume glamour needs the react event handlers attached to the dom to do it's magic so it won't work with `renderToStaticMarkup`. Though I can't think of a good solution, to get around this other than using `/layouts` to handle styles.

**Comment by ricardocosta89** [comment] 2017-07-11 10:00
Thanks for the explanation, @craig-mulligan. 👍 
I tried using `/layouts` to handle styles, but some of the styles do need to be applied to `body`, otherwise you get a margin on the body.
I ended up creating the style rules in a string and using the `dangerouslySetInnerHTML` approach to add the styles in `head`.

From my part, I believe the issue can be closed, since there's no way for this to work and a workaround is in place.

**Comment by felixjung** [comment] 2017-07-11 14:32
@craig-mulligan I can style stuff inside `html.js`with glamorous/glamor just fine. It just requires me to restart the develop task so `index.html` is rebuilt. This would not be possible with what you are saying, no?

**Comment by KyleAMathews** [comment] 2017-07-11 22:41
Glamor can't work in html.js because the code there never runs in the client. Gatsby only uses html.js for doing a server render. For Glamor to work you either need to run it in a browser environment so it can inject CSS in the `<head/>` or you need to extract the css it generates and ship it to the browser. Neither solution is possible with html.js as a) it runs on the server so no browser and b) you can't extract the CSS and add it to the generated HTML while in the process of generating said HTML.

@felixjung if I'm wrong, am very curious what you're doing to get this to work :-)

@ricardocosta89 just use https://github.com/threepointone/glamor/blob/master/docs/howto.md#global-css-rule for adding styles to html/body. You can do this in your layout/index.js and it'll get added to all your pages.

**Closed by KyleAMathews** 2017-07-11 22:41 UTC

**Comment by felixjung** [comment] 2017-07-12 04:52
I just realized what was going on. When testing this, I assigned the same background color to `<body>` as to some `<div>`, the former in a component, not `html.js`. Both got the same class applied, but the actual CSS came from the `<div>`. Et voila.
