### ISSUE TITLE
bug(gatsby-source-contentful): Source plugin fails with rich text resolved locales.

### ISSUE THREAD

**Issue by zakdoek** [gatsbyjs/gatsby#24612] opened 2020-05-29 12:24 UTC
## Description

The source plugin does crash when a previously added rich text field was added and changed with the option `richText.resolveFieldLocales` on true. This does only happen with a cache already in place.

The error seems to be happening in the normalization step. More specific in the getEntryWithFieldLocaleesResolved function. When a stale entry is detected no `entry.fields` or no `entry.sys.contentType` is present.

### Steps to reproduce

- Contentful space with multiple locales, no fallback and not required for at least one locale
- A contentful model with a rich text field that allows embedded entries.
- Add an entry of that content model and add a linked entry in the rich text editor.
- Make a build on a clean cache
- Remove the linked entry and add another one.
- Build again on the same cache

### Expected result

The build should succeed.

### Actual result

The source plugin throws an error and the build fails.

`"gatsby-source-contentful" threw an error while running the sourceNodes lifecycle:

Cannot read property 'sys' of undefined

  TypeError: Cannot read property 'sys' of undefined

  - rich-text.js:86 getEntryWithFieldLocalesResolved
    [2po-dgp-front-channel]/[gatsby-source-contentful]/rich-text.js:86:66

  - rich-text.js:111 getNormalizedRichTextNode
    [2po-dgp-front-channel]/[gatsby-source-contentful]/rich-text.js:111:17

  - rich-text.js:134
    [2po-dgp-front-channel]/[gatsby-source-contentful]/rich-text.js:134:46

  - Array.map

  - rich-text.js:134 getNormalizedRichTextNode
    [2po-dgp-front-channel]/[gatsby-source-contentful]/rich-text.js:134:29

  - rich-text.js:159
    [2po-dgp-front-channel]/[gatsby-source-contentful]/rich-text.js:159:42

  - Array.map

  - rich-text.js:159 getNormalizedRichTextField
    [2po-dgp-front-channel]/[gatsby-source-contentful]/rich-text.js:159:30

  - normalize.js:354
    [2po-dgp-front-channel]/[gatsby-source-contentful]/normalize.js:354:18

  - lodash.js:13401
    [2po-dgp-front-channel]/[lodash]/lodash.js:13401:38

  - lodash.js:4905
    [2po-dgp-front-channel]/[lodash]/lodash.js:4905:15

  - lodash.js:2990 baseForOwn
    [2po-dgp-front-channel]/[lodash]/lodash.js:2990:24

  - lodash.js:13400 Function.mapValues
    [2po-dgp-front-channel]/[lodash]/lodash.js:13400:7

  - normalize.js:347
    [2po-dgp-front-channel]/[gatsby-source-contentful]/normalize.js:347:33

  - Array.map

  - normalize.js:345
    [2po-dgp-front-channel]/[gatsby-source-contentful]/normalize.js:345:32

  - From previous event:

  - api-runner-node.js:231 runAPI
    [2po-dgp-front-channel]/[gatsby]/src/utils/api-runner-node.js:231:22

  - api-runner-node.js:339 Promise.catch.decorateEvent.pluginName
    [2po-dgp-front-channel]/[gatsby]/src/utils/api-runner-node.js:339:17

  - From previous event:

  - api-runner-node.js:338
    [2po-dgp-front-channel]/[gatsby]/src/utils/api-runner-node.js:338:14

  - timers.js:456 processImmediate
    internal/timers.js:456:21

  - From previous event:

  - api-runner-node.js:330
    [2po-dgp-front-channel]/[gatsby]/src/utils/api-runner-node.js:330:13

  - From previous event:

  - api-runner-node.js:246 apiRunner
    [2po-dgp-front-channel]/[gatsby]/src/utils/api-runner-node.js:246:3

  - source-nodes.js:80 module.exports
    [2po-dgp-front-channel]/[gatsby]/src/utils/source-nodes.js:80:9

  - index.js:447 module.exports
    [2po-dgp-front-channel]/[gatsby]/src/bootstrap/index.js:447:9

  - task_queues.js:97 processTicksAndRejections
    internal/process/task_queues.js:97:5

  - build.js:67 build
    [2po-dgp-front-channel]/[gatsby]/src/commands/build.js:67:53

not finished source and transform nodes - 1.065s
`

### Environment

  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.61
    Safari: 13.1
  npmPackages:
    gatsby: ^2.11.7 => 2.20.13 
    gatsby-image: ^2.2.3 => 2.3.1 
    gatsby-link: ^2.2.0 => 2.3.2 
    gatsby-plugin-catch-links: ^2.2.1 => 2.2.1 
    gatsby-plugin-eslint: ^2.0.5 => 2.0.8 
    gatsby-plugin-feed: ^2.5.0 => 2.5.0 
    gatsby-plugin-lunr: ^1.5.2 => 1.5.2 
    gatsby-plugin-manifest: ^2.2.0 => 2.3.3 
    gatsby-plugin-offline: ^2.2.0 => 2.2.10 
    gatsby-plugin-playground: ^1.0.6 => 1.0.6 
    gatsby-plugin-react-helmet: ^3.1.0 => 3.2.1 
    gatsby-plugin-react-helmet-canonical-urls: ^1.4.0 => 1.4.0 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0 
    gatsby-plugin-sass: ^2.1.0 => 2.2.1 
    gatsby-plugin-schema-snapshot: ^1.0.0 => 1.0.0 
    gatsby-plugin-sharp: ^2.2.1 => 2.5.4 
    gatsby-plugin-sitemap: ^2.4.1 => 2.4.1 
    gatsby-source-contentful: ^2.1.4 => 2.2.7 
    gatsby-source-filesystem: ^2.1.1 => 2.2.2 
    gatsby-transformer-sharp: ^2.2.0 => 2.4.4 
    gatsby-transformer-sqip: ^2.1.3 => 2.2.4

**Comment by TylerBarnes** [comment] 2020-05-29 18:06
Hi @zakdoek !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by zakdoek** [comment] 2020-05-31 13:33
Hi @TylerBarnes,

Check. I will provide a minimal reproduction until end next week.

Grt,
T.

**Comment by LekoArts** [comment] 2020-06-16 09:42
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-06-16 09:42 UTC
Labels: status: needs reproduction, topic: Contentful, type: bug

**Comment by jsl15c** [comment] 2020-09-23 17:42
@TylerBarnes 
I would love to create a minimal reproduction for this but do not want to have my creds for contentful accessible.
I am still experiencing this issue and it does not seem to be clear, other than that gatsby-source-contentful is not error handling this case:
`var defaultInline = function (type, node) {
1:39:16 PM: > 1068 |     return "<span>type: " + type + " id: " + node.data.target.sys.id + "</span>";
1:39:16 PM:        | ^
1:39:16 PM:   1069 | };
1:39:16 PM:   1070 | /**
  1071 |  * Serialize a Contentful Rich Text `document` to an html string.


  WebpackError: TypeError: Cannot read property 'sys' of undefined
  
  - rich-text-html-renderer.es5.js:1068 
    node_modules/@contentful/rich-text-html-renderer/dist/rich-text-html-rendere    r.es5.js:1068:1
  
  - rich-text-html-renderer.es5.js:1056 
    node_modules/@contentful/rich-text-html-renderer/dist/rich-text-html-rendere    r.es5.js:1056:64`

**Comment by axe312ger** [comment] 2020-10-02 13:04
Please check the canary release from #25249. This should fix your issue.
