### ISSUE TITLE
Window is not defined using the onRenderBody function 

### ISSUE THREAD

**Issue by bradypp** [gatsbyjs/gatsby#24415] opened 2020-05-24 17:32 UTC
## Description

I'm trying to inject a script and a style component using the onRenderBody function in gatsby-ssr.js. When I do this I get a window is not defined reference error. I get this error even if the function is empty.

Edit: It seems to only do this on the dev server. When I build and serve, it works perfectly.

### Steps to reproduce

This is as a result of following Josh McComeau's tutorial for a dark mode: https://joshwcomeau.com/gatsby/dark-mode/

My repo: https://github.com/bradypp/personal-website/tree/dev

### Expected result

I expected it to work as in this example repo: https://github.com/joshwcomeau/dark-mode-minimal

### Actual result

I got the following error:

```
 ERROR 

There was an error compiling the html.js component for the development server.

See our docs page on debugging HTML builds for help https://gatsby.dev/debug-html ReferenceError: window is not defined


  36 | })();
  37 | 
> 38 | var index = window.requestAnimationFrame ||
     | ^
  39 |  window.webkitRequestAnimationFrame ||
  40 |  window.mozRequestAnimationFrame ||
  41 |  polyfill;


  WebpackError: ReferenceError: window is not defined
  
  - miniraf.es.js:38 Module../node_modules/miniraf/dist/miniraf.es.js
    node_modules/miniraf/dist/miniraf.es.js:38:1
  
  - scrollreveal.es.js:1 Module../node_modules/scrollreveal/dist/scrollreveal.es.js
    node_modules/scrollreveal/dist/scrollreveal.es.js:1:1
  
  - scrollReveal.js:1 Module../src/utils/scrollReveal.js
    src/utils/scrollReveal.js:1:1
  
  - index.js:1 Module../src/utils/index.js
    src/utils/index.js:1:1
  
  - useOnEscapeKeyDown.js:1 Module../src/hooks/useOnEscapeKeyDown.js
    src/hooks/useOnEscapeKeyDown.js:1:1
  
  - index.js:1 Module../src/hooks/index.js
    src/hooks/index.js:1:1
  
  - index.js:1 Module../src/components/index.js
    src/components/index.js:1:1
  

not finished Generating image thumbnails - 6.095s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! personal-website@1.0.0 develop: `env-cmd -f ./.env.local gatsby develop -p 3000`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the personal-website@1.0.0 develop script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/paul/.npm/_logs/2020-05-24T17_20_59_845Z-debug.log
error Command failed with exit code 1.
```

### Environment

```
System:
    OS: Linux 5.4 Manjaro Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 12.16.0 - ~/.nvm/versions/node/v12.16.0/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.0/bin/npm
  Languages:
    Python: 3.8.2 - /usr/bin/python
  Browsers:
    Firefox: 76.0.1
  npmPackages:
    gatsby: ^2.21.22 => 2.21.22
    gatsby-cli: ^2.12.34 => 2.12.34
    gatsby-image: ^2.4.3 => 2.4.3
    gatsby-plugin-google-analytics: ^2.3.2 => 2.3.2
    gatsby-plugin-manifest: ^2.4.2 => 2.4.2
    gatsby-plugin-netlify: ^2.3.3 => 2.3.3
    gatsby-plugin-offline: ^3.2.7 => 3.2.7
    gatsby-plugin-react-helmet: ^3.3.1 => 3.3.1
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sharp: ^2.6.3 => 2.6.3
    gatsby-plugin-sitemap: ^2.4.2 => 2.4.2
    gatsby-plugin-styled-components: ^3.3.1 => 3.3.1
    gatsby-remark-code-titles: ^1.1.0 => 1.1.0
    gatsby-remark-embed-video: ^3.0.10 => 3.0.10
    gatsby-remark-external-links: ^0.0.4 => 0.0.4
    gatsby-remark-images: ^3.3.3 => 3.3.3
    gatsby-remark-prismjs: ^3.5.1 => 3.5.1
    gatsby-remark-relative-images: ^0.3.0 => 0.3.0
    gatsby-source-filesystem: ^2.3.1 => 2.3.1
    gatsby-transformer-remark: ^2.8.8 => 2.8.8
    gatsby-transformer-sharp: ^2.5.2 => 2.5.2
  npmGlobalPackages:
    gatsby-cli: 2.12.21
```

**Comment by LekoArts** [comment] 2020-05-25 08:48
Hi!

Please [provide a minimal reproduction][reproduction] as your stacktrace is referring to `scrollreveal` and not something related to `onRenderBody` or the dark mode article you're referring to. Moreover, the minimal example you linked shows that it works so it's most likely something on your end and individual project and not a bug in Gatsby. You can also refer to https://www.gatsbyjs.org/docs/debugging-html-builds/

So I'd advise to create a minimal example on your own as it'll most likely show you the bug you have in your code. If you can show that it's a bug on our end, please let us know.

I'll close this issue in the meantime. Thanks for using Gatsby!

[reproduction]: https://gatsby.dev/reproduction

**Closed by LekoArts** 2020-05-25 08:48 UTC
Labels: type: question or discussion
