### ISSUE TITLE
gatsby lints dependencies and fails in monorepo alongside publishable libraries

### ISSUE THREAD

**Issue by bebbi** [gatsbyjs/gatsby#19914] opened 2019-12-02 13:51 UTC
## Description

Using gatsby in a lerna monorepo fails with linting errors when importing publishable components that live alongside the app.

### Steps to reproduce

```
git clone https://github.com/bebbi/gatsby-repro-mono-nwb
# See also README in the project
cd gatsby-repro-mono-nwb
yarn
cd packages/example-component
yarn build
cd ../example-app
yarn develop
# Check error
```

### Expected result

There should be no error and it should just work.

### Actual result

gatsby fails on a lint error

```
/PathTo/gatsby-repro-mono-nwb/packages/example-component/es/index.js
  3:1  error    Import in body of module; reorder to top  import/first
```

gatsby is trying to lint the output of the separate publishable nwb modules in the monorepo, linting the output of the nwb build toolchain which is not necessary.
This is one of the reasons `create-react-app` isn't linting external modules.

### Environment

  System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM)
    Shell: 5.0.7 - /usr/local/bin/bash
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    Yarn: 1.19.2 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v8.12.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python

**Comment by blainekasten** [comment] 2019-12-02 14:18
@bebbi I'm not able to reproduce currently. when cloning the example-app folder is empty. not sure if that is intended.

![image](https://user-images.githubusercontent.com/2916023/69966444-0657cf00-14dc-11ea-8cd7-aa9d352ab133.png)

If you can fix the repro app that'd be great!

**Comment by bebbi** [comment] 2019-12-02 17:33
@blainekasten ops fixed (history-rewriting commit!) and tested..

**Comment by blainekasten** [comment] 2019-12-06 16:16
@bebbi I looked into this more. It is occurring because webpack is resolving to `example-component/es/index` instead of it happening through node_modules as a typical lerna bootstrap setup.

So an easy solution is to avoid the "build" step as you have. I'm not sure if you need a build step so that you can publish these or not, but if you just change package.json module in example-component to be `src/index.js` it should work.

So i guess the question is, do you need the build step and the module field in your package.json for any reason other than local development?

**Comment by bebbi** [comment] 2019-12-09 14:24
@blainekasten some are publishable and are consumed in other js apps as well, they have the build step to turn jsx and es2016 into plain js.

For a workaround I've created a custom eslint config that doesn't error on import first issues although this is sometimes a helpful warning.

Is there any documentation about the reason gatsby lints lib code and doesn't just treat it like node_modules code? Here's the ref to the above [CRA comment](https://github.com/facebook/create-react-app/issues/4249#issuecomment-378371089)

**Comment by 454de6e** [comment] 2020-01-03 03:46
Is there any recommendation for how to deal with published packages with build step in a monorepo? I get a lot of ESLint warnings which hide the real warnings.

**Comment by blainekasten** [comment] 2020-02-11 20:10
@454de6e @bebbi this isn't a Gatsby problem per-se. It's a systemic problem with compiling and requiring and the tooling around it all. I don't have a far and wide solution here but I think what you might want to do is somehow signal to eslint not to look at these files. Ideas are you could add a `/* eslint-disable */` pragma to the top of the compiled file. Babel and webpack have hooks to prepend text to files. Or you could maybe tell eslint to ignore certain file paths.

I'm going to close this as it's not a problem with Gatsby. I'm happy to keep this conversation going and if we can find a generalized solution I'd love to implement it.

**Closed by blainekasten** 2020-02-11 20:10 UTC
Labels: status: needs more info
