### ISSUE TITLE
docs: js-search example not working

### ISSUE THREAD

**Issue by Siregar** [gatsbyjs/gatsby#12270] opened 2019-03-04 01:07 UTC
👋
When I try the **adding search with js-search** (https://www.gatsbyjs.org/docs/adding-search-with-js-search/) tutorial, I get the following error:

*TypeError: search.search is not a function*
`const queryResult = search.search(e.target.value)`

Does anyone know how to solve it? I just did copy/paste the code.

Thanks for your help!

**Comment by jonniebigodes** [comment] 2019-03-04 01:43
I've written the documentation in question and with probably a little more information i can help solving your issue.

**Comment by DSchau** [comment] 2019-03-04 16:49
@Siregar would you be able to provide a reproduction so we could take a further look?

Tracing that example, it looks like the `rebuildIndex` function gets invoked on componentDidMount which initializes the `search` state value. This should be a searchable index that will have a `search` method.

The most likely culprits of the error are:

1. Entire lifecycle/class component has not been implemented (e.g. state is not being set)
1. Race condition where onChange is invoked _before_ search has been set up

I'd lean towards 1) being more likely, so [a reproduction](https://gatsby.dev/reproduction) of where you're at currently would help us immensely.

Thanks!

**Comment by Siregar** [comment] 2019-03-05 11:01
Hey there,
I just 1:1 copy/pasted the code from https://www.gatsbyjs.org/docs/adding-search-with-js-search/#js-search-with-a-small-to-medium-dataset.

Pushed everything into a repo. Hope it helps: https://github.com/Siregar/js-search-example

**Comment by jonniebigodes** [comment] 2019-03-05 16:16
@Siregar going to break it into smaller steps for a better understanding:
- Cloned your repository.
 - Installed the dependencies.
- Issued `gatsby develop` 
- Opened a browser window and devtools,  i'm presented with:
![search_develop_entry](https://user-images.githubusercontent.com/22988955/53817481-69243600-3f5d-11e9-8392-e048cff69eb3.png)
- Checked the component's state to see if anything was wrong with it and i'm presented with:
![search_develop_state](https://user-images.githubusercontent.com/22988955/53817566-a1c40f80-3f5d-11e9-8b8c-165c452d9bcc.png)
- Searched for a author and it yelds this:
![search_develop_author](https://user-images.githubusercontent.com/22988955/53817603-ba342a00-3f5d-11e9-9d50-18d8212fb207.png)
- Searched for a title and the i got the following result:
![search_develop_title](https://user-images.githubusercontent.com/22988955/53817663-dc2dac80-3f5d-11e9-9e0b-397e69795fab.png)

- Searched for something that does not exist:
![search_develop_empty](https://user-images.githubusercontent.com/22988955/53817711-01221f80-3f5e-11e9-89ff-b42043da3888.png)

In development all is ok, so to cover all aspects and check that this was not a issue with `gatsby` develop being overly permissive, i've stopped Gatsby ,issued `gatsby clean` to purge both `.cache` and `public` folders, for a clean slate. 

- Issued `gatsby build && gatsby serve`, to get a full blown production build.

- After the process was complete, opened a new browser window to `http://localhost:9000` and i'm presented with:
![search_build](https://user-images.githubusercontent.com/22988955/53817861-91f8fb00-3f5e-11e9-8620-7008e54cb4f9.png)

- Searching for a author yelds the following results:
![search_build_author](https://user-images.githubusercontent.com/22988955/53817881-b7860480-3f5e-11e9-9ee0-22c5186da77b.png)

- Searching for a title the following:
![search_build_title](https://user-images.githubusercontent.com/22988955/53817893-c967a780-3f5e-11e9-8caa-3a8d56661756.png)
- Searching for a non existing item yelds:
![search_build_empty](https://user-images.githubusercontent.com/22988955/53817901-d5536980-3f5e-11e9-99d5-98d806726d8f.png)

After checking your code, it seems to me that this might be the case of a race condition, probably you're typing away before the `rebuildIndex()` method finishes and with that bubbling up to the lifecycle method `componentDidMount()`. To prevent situations like this, it's the reason i've implemented the following:

```javascript
class Search extends Component {
  state = {
   .....
    isLoading: true,
   .....,
  }
rebuildIndex = () => {
 this.setState({ search: dataToSearch, isLoading: false })
}
render(){
 const {
      isLoading,
    } = this.state
   return(
     if (isLoading) {
        return (
          <div style={{ margin: `1.2rem 1rem 1.2rem 1rem` }}>
           <h1 style={{ marginTop: `3em`, textAlign: `center` }}>
            Getting the search all setup
          </h1>
        </div>
      )
   }
........
}
```

The trimmed down version of the code hosted [here](https://github.com/gatsbyjs/gatsby/blob/master/examples/using-js-search/src/components/SearchContainer.js) works as a "guard method", that prevents issues like this to spawn. I'm fully aware that looking at a `<h1>` even if it's still for 500 milliseconds or 10 seconds, depending on your dataset that is going to be indexed and primed for search might be not so elegant to look at, but when i was researching it a issue like this started happening. That's why i implemented this.

If this small but rather key piece of information was left out from the documentation, for that i'm sorry for the oversight. And i'll work on correcting it soon.

Feel free to provide feedback

**Comment by Siregar** [comment] 2019-03-07 23:05
That's weird.. I implemented your "guard method" by myself and it didn't work. Then I c&p but still the same error. 😞
<img width="711" alt="bildschirmfoto 2019-03-08 um 00 04 15" src="https://user-images.githubusercontent.com/31287148/53995602-d25ea180-4135-11e9-94b7-304e900a55fd.png">

**Comment by jonniebigodes** [comment] 2019-03-07 23:50
@Siregar i would like for you to do two things:
1. Issue `gatsby clean`, to purge the `.cache` and `public` folder.
2. Issue `gatsby develop`, open a browser window to `http://localhost:8000` , open devtools and i hope you have the the react developer tools added, under that, drill down the nodes into the page, expand the state and search nodes in there . Grab a screenshot of the that and post it here like i did on my previous comment if you don't mind.

**Comment by Siregar** [comment] 2019-03-08 10:03
@jonniebigodes here's the screenshot. I guess I figured out what's the problem. It's the  `ERR_BLOCKED_BY_CLIENT` error, isn't it?
<img width="1432" alt="screenshot" src="https://user-images.githubusercontent.com/31287148/54021991-bf79ba80-4191-11e9-8d07-72b3a7fa0be5.png">

**Comment by jonniebigodes** [comment] 2019-03-08 15:04
@Siregar yes it is, you figured it out. If the data is not fetched, then js-search cannot search on nothing. Taking note that the example needs a little tweak on the search method, to prevent this situation.

**Comment by jonniebigodes** [comment] 2019-03-12 02:35
Closing this as it's answered. Feel free to open a new one should any further issues arise

**Closed by jonniebigodes** 2019-03-12 02:35 UTC
Labels: status: awaiting author response, status: needs reproduction, type: documentation
