### ISSUE TITLE
Cannot query field \"frontmatter\" on type \"Mdx\

### ISSUE THREAD

**Issue by AnirudhPanda** [gatsbyjs/gatsby#36733] opened 2022-10-03 12:52 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I have been following the Gatsby Tutorial and in Part 5 I am facing this error.
`Cannot query field \"frontmatter\" on type \"Mdx\`

Below is my file structure:

<img width="165" alt="Screenshot 2022-10-03 at 6 19 11 PM" src="https://user-images.githubusercontent.com/66218496/193580602-ec033a70-7e78-4db1-9683-04687eee5f11.png">

Below is my `gatsby-config.js`:
```
module.exports = {
  siteMetadata: {
    title: `Learning Gatsby`,
    siteUrl: `https://www.yourdomain.tld`,
  },
  plugins: [
    "gatsby-plugin-image",
    "gatsby-plugin-sharp",
    {
      resolve:"gatsby-source-filesystem",
      options: {
        name: `blog`,
        path: `${__dirname}/blog`,
      },
    },
    "gatsby-plugin-mdx",
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `pages`,
        path: `${__dirname}/src/pages`,
      },
    },
  ],
}

```

### Reproduction Link

NA

### Steps to Reproduce

NA

### Expected Result

NA

### Actual Result

NA

### Environment

```shell
System:
    OS: macOS 12.6
    CPU: (8) arm64 Apple M1
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.16.0 - /usr/local/bin/node
    npm: 8.11.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Safari: 16.0
  npmPackages:
    gatsby: ^4.24.0 => 4.24.0
    gatsby-plugin-image: ^2.24.0 => 2.24.0
    gatsby-plugin-mdx: ^4.3.0 => 4.3.0
    gatsby-plugin-sharp: ^4.24.0 => 4.24.0
    gatsby-source-filesystem: ^4.24.0 => 4.24.0
  npmGlobalPackages:
    gatsby-cli: 4.24.0
```

**Comment by AnirudhPanda** [comment] 2022-10-03 13:10
Instead of `gatsby-plugin-mdx` if `gatsby-transformer-remark` is used and `allMdx` is removed and `allMarkdownRemark` is used then frontmatter works but if we go by the tutorial it doesn't

**Comment by pieh** [comment] 2022-10-03 19:00
@AnirudhPanda Can you create repository with current state of the site (with Mdx)?

Are all your markdown files with `.md` extension? By default `gatsby-plugin-mdx` will only handle `.mdx` extension, so if you don't have any of those the `Mdx` type might miss `frontmatter` field ( it will have just some few of the fields, because `frontmatter` is fluid and can't be declared by the plugin, as shape of it is decided by content).

Other idea is that you don't actually have actual frontmatter section in the files

**Comment by LekoArts** [comment] 2022-10-10 06:33
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2022-10-10 06:33 UTC
Labels: type: bug, status: needs reproduction
