### ISSUE TITLE
Error trying to develop Gatsby site locally

### ISSUE THREAD

**Issue by Olanetsoft** [gatsbyjs/gatsby#20725] opened 2020-01-20 20:03 UTC
## Summary
After successfully cloning a gatsby site each time I tried to develop locally I get an error

## Relevant information
The screenshot below shows the error gotten
![Screenshot (531)](https://user-images.githubusercontent.com/45847909/72754120-3dd32580-3bc7-11ea-90df-2429046b9c9f.png)

1. Link to Repo that was cloned that threw an error: https://github.com/alfieqashwa/alfieqashwa.me
2. Link to Repo that was cloned that threw an error: https://github.com/nelonoel/nelo.is

### Environment (if relevant)
Node Version: v12.13.1
Npm: 6.12.1

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by TylerBarnes** [comment] 2020-01-21 01:00
Hi @Olanetsoft , sorry to hear you're running into this issue!
I pulled down the nelo.is repo and ran `npm run develop` using the same node/npm versions as you. Unfortunately I wasn't able to reproduce the issue which leads me to believe there's something weird going on with your node/npm install. 
@wardpeet do you have any advice on troubleshooting this?

**Comment by Olanetsoft** [comment] 2020-01-21 08:44
@TylerBarnes Thanks for the response. What would you advise me to do?

**Comment by TylerBarnes** [comment] 2020-01-21 19:38
Hey @Olanetsoft I did a little looking around and found this issue https://github.com/gatsbyjs/gatsby/issues/19064#issuecomment-547552008

It looks like you can resolve this by deleting `package-lock.json` and `node_modules` and reinstalling. The problem may be something to do with your node version, or to do with recently switching node versions, or mixing `yarn` and `npm`. I'm closing this as a duplicate but please let me know if that resolves this for you.

**Closed by TylerBarnes** 2020-01-21 19:38 UTC

**Comment by Olanetsoft** [comment] 2020-01-23 08:53
@TylerBarnes I am so sorry for replying late. I am still yet to fix the issue, I tried [this]([https://github.com/gatsbyjs/gatsby/issues/19064#issuecomment-547552008])) but still get the same error each time tried using npm run develop. It seems i am not so lucky to have gatsby running on my machine :(

**Comment by Olanetsoft** [comment] 2020-01-23 13:39
it's now working fine. What I did was to run my terminal as administrator and it worked perfectly.
Thanks to everyone and @TylerBarnes

**Comment by TylerBarnes** [comment] 2020-01-24 21:29
Apologies for the late reply. Glad to hear you have it working! It sounds to me like your node/npm installs may have been installed as admin which could be the problem. I think it's a bad idea to run scripts as admin as it gives them access that can be dangerous if you were to unintentionally run a malicious package. I would recommend trying to re-install node/npm again to see if that fixes it

**Comment by Olanetsoft** [comment] 2020-01-25 08:53
Okay I will do that 🤗 and give feedback... thank you @TylerBarnes
