### ISSUE TITLE
gatsby-source-graphql threw "fetcher is not a function"

### ISSUE THREAD

**Issue by marconucara** [gatsbyjs/gatsby#23041] opened 2020-04-12 11:31 UTC
## Description

If I add gatsby-source-graphql to my project I got this:

```
ERROR #11321  PLUGIN

"gatsby-source-graphql" threw an error while running the sourceNodes lifecycle:

fetcher is not a function

  79 | 
  80 |     if (!sdl) {
> 81 |       introspectionSchema = await introspectSchema(link);
     |                                   ^
  82 |       sdl = printSchema(introspectionSchema);
  83 |     } else {
  84 |       introspectionSchema = buildSchema(sdl);

File: ../../node_modules/gatsby-source-graphql/gatsby-node.js:81:35



  TypeError: fetcher is not a function
  
  - introspectSchema.js:14 introspectSchema
    [colombo]/[gatsby-source-graphql]/[graphql-tools-fork]/dist/stitch/introspectSchema.js:14:12
  
  - gatsby-node.js:81 Object.exports.sourceNodes
    [colombo]/[gatsby-source-graphql]/gatsby-node.js:81:35
```

I removed cache, node modules and yarn.lock without success. Here my `yarn why` responses for graphql-tools-fork and apollo-link:

```
=> Found "graphql-tools-fork@9.0.1"
info Has been hoisted to "graphql-tools-fork"
info Reasons this module exists
   - "workspace-aggregator-3af4dbbb-e46e-42e0-8d9d-6742ac70aacd" depends on it
   - Hoisted from "_project_#@colombo-it#website#graphql-tools-fork"
   - Hoisted from "_project_#@colombo-it#website#gatsby-plugin-graphql-codegen#@graphql-toolkit#common#graphql-tools-fork"
   - Hoisted from "_project_#@colombo-it#website#gatsby-plugin-graphql-codegen#@graphql-toolkit#url-loader#graphql-tools-fork"
   - Hoisted from "_project_#@colombo-it#website#gatsby-plugin-graphql-codegen#@graphql-toolkit#core#@graphql-toolkit#schema-merging#graphql-tools-fork"
info Disk size without dependencies: "2.22MB"
info Disk size with unique dependencies: "3.05MB"
info Disk size with transitive dependencies: "4.85MB"
info Number of shared dependencies: 19
=> Found "gatsby-source-graphql#graphql-tools-fork@8.10.0"
info This module exists because "_project_#@colombo-it#website#gatsby-source-graphql" depends on it.
info Disk size without dependencies: "5.81MB"
info Disk size with unique dependencies: "6.64MB"
info Disk size with transitive dependencies: "8.44MB"
info Number of shared dependencies: 19
```

```
=> Found "apollo-link@1.2.14"
info Has been hoisted to "apollo-link"
info Reasons this module exists
   - "workspace-aggregator-612cc2d0-299d-4055-bf09-f33868daf8dc" depends on it
   - Hoisted from "_project_#graphql-tools-fork#apollo-link"
   - Hoisted from "_project_#@colombo-it#cms#apollo-boost#apollo-link"
   - Hoisted from "_project_#graphql-tools-fork#apollo-link-http-common#apollo-link"
   - Hoisted from "_project_#@colombo-it#cms#apollo-boost#apollo-client#apollo-link"
   - Hoisted from "_project_#@colombo-it#cms#apollo-boost#apollo-link-error#apollo-link"
   - Hoisted from "_project_#@colombo-it#cms#apollo-boost#apollo-link-http#apollo-link"
   - Hoisted from "_project_#@colombo-it#bff-website#apollo-server-lambda#graphql-tools#apollo-link"
info Disk size without dependencies: "224KB"
info Disk size with unique dependencies: "1.31MB"
info Disk size with transitive dependencies: "1.65MB"
info Number of shared dependencies: 7
=> Found "gatsby-source-graphql#apollo-link@1.2.13"
info This module exists because "_project_#@colombo-it#website#gatsby-source-graphql" depends on it.
info Disk size without dependencies: "224KB"
info Disk size with unique dependencies: "1.31MB"
info Disk size with transitive dependencies: "1.65MB"
info Number of shared dependencies: 7
=> Found "gatsby-source-graphql#graphql-tools-fork#apollo-link@1.2.14"
info This module exists because "_project_#@colombo-it#website#gatsby-source-graphql#graphql-tools-fork" depends on it.
info Disk size without dependencies: "3.45MB"
info Disk size with unique dependencies: "4.54MB"
info Disk size with transitive dependencies: "4.88MB"
info Number of shared dependencies: 7
```

I also talked about that issue here: https://github.com/gatsbyjs/gatsby/issues/21443#issuecomment-612575347

### Steps to reproduce

It is not ease to reproduce this bug, I cloned gatsby repository and successfully execute example/using-gatsby-source-graphql. I can't create a minimal reproduction.

### Environment

```

  System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - /var/folders/w2/3l_d40x17_385rlkvzk8q_tw0000gn/T/yarn--1586690876653-0.631635444216591/node
    Yarn: 1.22.4 - /var/folders/w2/3l_d40x17_385rlkvzk8q_tw0000gn/T/yarn--1586690876653-0.631635444216591/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.163
    Safari: 13.1
```

**Comment by marconucara** [comment] 2020-04-12 12:05
I temporary solved forcing some resolutions in packages.json as suggested here: https://github.com/gatsbyjs/gatsby/issues/23002

**Comment by LekoArts** [comment] 2020-04-14 07:31
I'll close this as a duplicate of https://github.com/gatsbyjs/gatsby/issues/23002. Let's track it there.

**Closed by LekoArts** 2020-04-14 07:31 UTC
Labels: type: bug
