### ISSUE TITLE
Gatsby serve should return 301/302s for redirects

### ISSUE THREAD

**Issue by alexlouden** [gatsbyjs/gatsby#19441] opened 2019-11-12 08:17 UTC
## Summary

We've been running a broken link checker as part of our site's CI process (it runs gatsby build, gatsby serve in the background, and then scans localhost:9000 for broken links). When I upgraded from Gatsby 1 to 2 the URLs that redirect which ~used to return a 301~ are now returning a 404 :(

(edit: just realised they used to return a directory listing, not a 301 - so this is unrelated to the upgrade but I think this would still be a useful addition!) 

### Basic example

gatsby-node:
```js
    createRedirect({
      fromPath: `old`,
      isPermanent: true,
      redirectInBrowser: true,
      toPath: `new`
    })
```

```bash
yarn global add broken-link-checker
gatsby build
gatsby serve
```

In another terminal:
```bash
blc -r -o http://localhost:9000/
```

> Getting links from: http://localhost:9000/
> ├─BROKEN─ http://localhost:9000/old (HTTP_404)

### Motivation

So we can distinguish between broken links and redirects before the site is deployed

**Comment by sidharthachatterjee** [comment] 2019-11-25 10:26
After some more thought and discussion with @gatsbyjs/core, we've come to the conclusion that we'd like to keep `serve` as minimal as possible and _not_ support this. 

`gatsby develop` doesn't support this either and `serve` is meant to be a quick way to test your site locally and isn't (by design) meant to be feature complete or a production-ready way to serve your site. 

We'd like to keep `serve` as minimal as possible to keep maintenance overhead and as such will be closing this (and the associated PR)

Thank you nonetheless for your great work on this and the PR as well! We _really_ appreciate you taking the time for this 💜

**Closed by sidharthachatterjee** 2019-11-25 10:26 UTC
Labels: type: feature or enhancement

**Comment by alexlouden** [comment] 2019-11-25 11:31
Thanks for the comment, I understand and appreciate how you you're erring on the side of maintainability! 

For my use case however I'm going to have to figure out another method to locally serve pages and redirects in order to check for broken links during CI. I guess I'll write a standalone cli tool 😃

**Comment by sidharthachatterjee** [comment] 2019-11-25 12:04
@alexlouden Would love to take a look at the CLI tool you write! 

Thank you so much for understanding 💜
