### ISSUE TITLE
gatsby-plugin-sharp: WorkerError @2.6.27

### ISSUE THREAD

**Issue by diegoolavarria** [gatsbyjs/gatsby#26723] opened 2020-08-31 16:36 UTC
## Description

Error processing a .png file when running `gatsby develop`

### Steps to reproduce

Upgrading gatsby-plugin-sharp to version 2.6.27

### Expected result

Images would be queried as expected

### Actual result

![image](https://user-images.githubusercontent.com/15364801/91743756-d5f6ab80-eba7-11ea-82f2-08cce31aa12c.png)

### Environment

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 AMD Ryzen 7 2700U with Radeon Vega Mobile Gfx
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.105
    Firefox: 80.0
  npmPackages:
    gatsby: ^2.23.12 => 2.24.53
    gatsby-background-image: ^1.1.1 => 1.1.2
    gatsby-image: ^2.4.15 => 2.4.16
    gatsby-plugin-google-analytics: ^2.3.13 => 2.3.13
    gatsby-plugin-layout: ^1.3.10 => 1.3.10
    gatsby-plugin-manifest: ^2.4.21 => 2.4.27
    gatsby-plugin-module-resolver: ^1.0.3 => 1.0.3
    gatsby-plugin-offline: ^3.2.21 => 3.2.26
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: 2.6.26 => 2.6.26
    gatsby-source-filesystem: ^2.3.24 => 2.3.27
    gatsby-source-graphql: ^2.7.1 => 2.7.2
    gatsby-transformer-sharp: ^2.5.13 => 2.5.14

**Comment by diegoolavarria** [comment] 2020-08-31 16:37
My current solution is to downgrade gatsby-plugin-sharp to version 2.6.26.

**Comment by t2ca** [comment] 2020-08-31 17:07
I just wanted to confirm that I am having the same error since updating all my dependencies today.

**Comment by Uhiyamind** [comment] 2020-08-31 21:29
> My current solution is to downgrade gatsby-plugin-sharp to version 2.6.26.

I also solved this problem. Thank you!

**Comment by wardpeet** [comment] 2020-09-01 07:22
Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by sbadulin** [comment] 2020-09-01 09:27
Mine is failing only on pngs with transparency

**Comment by KamranMaqbool** [comment] 2020-09-01 09:47
still same issue after downgrade my previous npm package version

**Comment by KamranMaqbool** [comment] 2020-09-01 09:53
@sbadulin how to solve this issue

**Comment by sbadulin** [comment] 2020-09-01 10:05
> @sbadulin how to solve this issue 

For now it is to downgrade gatsby-plugin-sharp to version 2.6.26.

**Comment by sbadulin** [comment] 2020-09-01 10:06
@KamranMaqbool for now it is to downgrade gatsby-plugin-sharp to version 2.6.26.

**Comment by stevemarksd** [comment] 2020-09-01 10:45
after so long time I found this bug issue.. 

On this place they closed. https://github.com/gatsbyjs/gatsby/issues/21515

Looks like `imagemin-pngquant` changed from v6 to v9

Looks like the error is swallowed so here is the real error: Command failed with exit code 99: ccc\\node_modules\\pngquant-bin\\vendor\\pngquant.exe - --strip --quality 100-100

**Comment by KamranMaqbool** [comment] 2020-09-01 10:58
my previous version is 
"gatsby-plugin-sharp": "^2.4.3",

me also try this version that you mentioned (2.6.26)
after clean node_modules,package-lock.json file and gatsby clean 
install (2.6.26) version
but same error occur 

i'm also move to my previous version (2.4.3) but still same issue  

**some packge version**
    "gatsby": "^2.19.7",

"gatsby-image": "^2.2.39",
"gatsby-transformer-sharp": "^2.3.13",
"gatsby-plugin-sharp": "^2.4.3",
"gatsby-source-filesystem": "^2.1.46",
"gatsby-source-graphql": "^2.1.33",
"gatsby-wpgraphql-inline-images": "^0.2.5",

**Comment by KamranMaqbool** [comment] 2020-09-01 11:06
@stevemarksd
yes i agree with you
when i'm delete node_modules folder then this issue is come

**Comment by josephmarkus** [comment] 2020-09-01 11:20
Getting the same error. Fails on an PNG image. Unlike @sbadulin, my PNG doesn't have transparency.

@wardpeet getting this

```
WorkerError: Processing /Users/[...]/imagename.png failed
  Original error:

  - jobs-manager.ts:318 enqueueJob
    [...]/[gatsby]/src/utils/jobs-manager.ts:318:21

  - runMicrotasks

  - task_queues.js:97 processTicksAndRejections
    internal/process/task_queues.js:97:5


not finished Generating image thumbnails - 146.376s
```

**Comment by mcqj** [comment] 2020-09-01 13:53
I'm seeing the issue with an old version of gatsby-plugin-sharp (2.2.9). Upgrading to 2.6.26 got rid of the error for me. However, I've been using gatsby-plugin-sharp v2.2.9 for a long time without issues. So, I suspect the problem is not in the plugin but in gatsby itself and how it interacts with the plugin.

**Comment by davet42** [comment] 2020-09-01 16:17
I have a fix in prototype form.  Basically, the pngquant binary (for me on Ubuntu 20.x) throws an error 99 when the input quality argument has min and max the same.

I have been seeing the same issues since recent updates of sharp-related libraries.  After convincing myself there were no cache issues, I then homed in on failing PNG handling.  Then I thought it was transparent PNG only.  

For reference, here is my environment (using v9.0.0 of imagemin-pngquant), from gatsby info:

```
gatsby info
  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.0.17 - /bin/bash

  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    npm: 6.14.8 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Firefox: 80.0
  npmPackages:
    gatsby: ^2.24.53 => 2.24.53
    gatsby-background-image: ^1.1.2 => 1.1.2
    gatsby-image: ^2.4.16 => 2.4.16
    gatsby-plugin-catch-links: ^2.3.11 => 2.3.11
    gatsby-plugin-google-analytics: ^2.3.13 => 2.3.13
    gatsby-plugin-google-tagmanager: ^2.3.11 => 2.3.11
    gatsby-plugin-manifest: ^2.4.27 => 2.4.27
    gatsby-plugin-offline: ^3.2.26 => 3.2.26
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10
    gatsby-plugin-sharp: ^2.6.31 => 2.6.31
    gatsby-remark-component: ^1.1.3 => 1.1.3
    gatsby-remark-copy-linked-files: ^2.3.13 => 2.3.13
    gatsby-remark-images: ^3.3.28 => 3.3.28
    gatsby-remark-relative-images: ^0.3.0 => 0.3.0
    gatsby-source-filesystem: ^2.3.27 => 2.3.27
    gatsby-transformer-remark: ^2.8.32 => 2.8.32
    gatsby-transformer-sharp: ^2.5.14 => 2.5.14
  npmGlobalPackages:
    gatsby-cli: 2.12.91
    gatsby-starter-default: 0.1.0
```

Example:
`<path>/node_modules/pngquant-bin/vendor/pngquant -v --strip --quality=100 - <src/images/<imagename>.png`
This returns a 0

But:
`<path>/node_modules/pngquant-bin/vendor/pngquant -v --strip --quality=100-100 - <src/images/<imagename>.png`
Returns a 99
`echo $?`
`99`

While debugging I though perhaps there were issues in how the parameters were provided, whether quotes were required, if there was an issue with the input redirection.  I ran the commands manually with and without redirection and finally determined the library was throwing the error 99 when values are same.

I patched `node_modules/imagemin-pngquant/index.js` like this.  

```
	if (typeof options.quality !== 'undefined') {
		ow(options.quality, ow.array.length(2).ofType(ow.number.inRange(0, 1)));
		const [min, max] = options.quality;
		// pngquant throws error 99 if min and max are same, rest of code does not handle
		args.push('--quality', `${Math.round(min * 100)}` +
			(min === max ? '' : `-${Math.round(max * 100)}`));
		console.log('Running quality args = ' + `${args}`)
	}
```

This works in my application for cases where 100% quality is desired and for ranges below 100 (i.e. 50-75, etc.)

I'll clean this up and post any further results after further testing.  I'll sort out a pull request once I am sure there are no negative effects

BTW, this is the detailed "error" that results when running the pngquant binary manually (an error code 99):
```
Original error:
stdin:
  read 8KB file
  made histogram...693 colors found
  selecting colors...3%
  selecting colors...24%
  selecting colors...27%
  selecting colors...48%
  selecting colors...51%
  selecting colors...72%
  selecting colors...93%
  selecting colors...100%
  moving colormap towards local minimum
  image degradation MSE=0.049 (Q=99) exceeded limit of 0.000 (100)
  writing truecolor image to stdout
Skipped 1 file out of a total of 1 file.
```

**Comment by t2ca** [comment] 2020-09-01 16:47
When I have the quality argument set to 100 I get the error, once I changed quality to a number like 90 it works again.

```
      image {
        childImageSharp {
          fluid(maxWidth: 1200, quality: 90) {
            ...GatsbyImageSharpFluid
          }
        }
      }
```

**Comment by hyalen** [comment] 2020-09-01 17:26
I'm facing this issue too.

I upgraded from version 2.2.16 to 2.6.28, and the image thumbnails are not queried during build time as expected. Then I deleted the node_modules, ran gatsby clean and the error still persists...

Does anyone have an update regarding this bug?

**Comment by davet42** [comment] 2020-09-01 20:30
> I'm facing this issue too.
> 
> I upgraded from version 2.2.16 to 2.6.28, and the image thumbnails are not queried during build time as expected. Then I deleted the node_modules, ran gatsby clean and the error still persists...
> 
> Does anyone have an update regarding this bug?

See my updated post - have found a one line patch in imagemin-pngquant that works for all my cases.  Will do a pull request after a bit more testing

**Comment by roldanjr** [comment] 2020-09-02 05:35
> When I have the quality argument set to 100 I get the error, once I changed quality to a number like 90 it works again.
> 
> ```
>       image {
>         childImageSharp {
>           fluid(maxWidth: 1200, quality: 90) {
>             ...GatsbyImageSharpFluid
>           }
>         }
>       }
> ```

So far this is the only thing that works for me. Thank you @t2ca .

**Comment by CesySoder** [comment] 2020-09-02 08:13
@wardpeet  I downgraded my gatsby-plugin-sharp to 2.6.28, its solved my problem locally, but when I push it to Netlify, it returns the same problem as in here #26746.
I am trying every version of this plugin from 26-30
What should I try to do more

**Comment by realAlexBarge** [comment] 2020-09-02 09:09
Are there any known workarounds yet? Right now as described previously not even downgrading fixes the issue anymore.

**Comment by HassanCorrigan** [comment] 2020-09-02 09:20
I started to get this error with the most recent version 2.6.31. Downgrading to 2.6.30 fixed the problem for now. I also have my quality setting as 100, although haven’t tried reducing that to fix the issue on the most recent version.

**Comment by davet42** [comment] 2020-09-02 12:36
> Are there any known workarounds yet? Right now as described previously not even downgrading fixes the issue anymore.

Have a look at my notes above - you can go to node_modules/imagemin-pngquant and change the one line in index.js.  Obviously this is just a workaround and the change will disappear if you reinstall code.  But, you will know quickly if it works.  Review process underway for the change I did in package.

**Comment by mcqj** [comment] 2020-09-02 15:02
Thanks, everyone for the help.
I can verify that in my case @davet42 patch cures the problem. Thanks @davet42 
Changing the image quality from 100 to 90 did not cure the problem.

**Comment by tjands** [comment] 2020-09-02 23:18
Downgrading isn't resolving this issue for me either

**Comment by theinhtut** [comment] 2020-09-03 04:41
I faced the same issue after upgrading `gatsby-plugin-sharp` from `2.6.2` --> `2.6.31`. Then downgraded to `2.6.30` but didn't resolve the issue. I did the following just to resolve it for now but not sure it's the right way to do it 
```
rm -rf node_module
rm package-lock.json
npm install
```

**Comment by dgorczyca** [comment] 2020-09-03 04:58
Thank you @davet42, your solution works every time (whilst upgrading and downgrading gatsby-plugin-sharp to any version makes no difference)! 
While waiting for your [pull request](https://github.com/imagemin/imagemin-pngquant/pull/71) to be merged I had to resolve the problem in the Dockerfile (before running `gatsby build`).
 Here is the code that ensures the same code as your pull request in imagemin-pngquant:
```
RUN sed -i 's/error\.code[[:space:]]===[[:space:]]99/error.exitCode===99/' /your_app_path/node_modules/imagemin-pngquant/index.js
```
Hopefully someone will find it useful

**Comment by toddgallowaymnf** [comment] 2020-09-04 00:06
I changed my image quality from 100 down to 90 and the build succeeded this morning. Yesterdays build failed here

`success onPostBootstrap - 0.259s
info bootstrap finished - 29.366s
success run static queries - 0.022s - 4/4 177.93/s
success run page queries - 1.256s - 13/13 10.35/s
success write out requires - 0.010s
error Processing /builds/group/developer/website/.cache/gatsby-source-filesystem/f52fd5367bd80495ddee0acd94c00721.png failed
.
.
not finished Generating image thumbnails - 9.717s
not finished Building production JavaScript and CSS bundles - 8.509s`

**Comment by ddiiorio** [comment] 2020-09-04 02:22
Also just started getting the same error out of nowhere, on v2.6.14 (have not touched the version in months). Tried changing quality to 90, no luck. Tried @davet42 's patch and no luck. gatsby develop works fine, but build errors every time as of the last few days. So frustrating 

`ERROR`

`UNHANDLED REJECTION EPERM: operation not permitted, lstat 'C:\apps\gatsby\mitech\.cache\caches\gatsby-source-wordpress-experimental\tmp-ed4dc5e5bb8c60d7dd20d5ccbc2f7111.jpg' `

**Comment by JohnGrattan** [comment] 2020-09-04 03:05
@davet42 's patch works for me while building locally, but would fail once deployed to Netlify. I rolled back gatsby-plugin-sharp to 2.4.13 and gatsby-plugin-manifest to 2.2.48 and finally had success deploying to Netlify. Rolling back gatsby-plugin-sharp alone did not work, only both. Once I started building locally again, I had to reapply @davet42 's patch just to successfully build. Very frustrating...

**Comment by ddiiorio** [comment] 2020-09-04 03:13
> @davet42 's patch works for me while building locally, but would fail once deployed to Netlify. I rolled back gatsby-plugin-sharp to 2.4.13 and gatsby-plugin-manifest to 2.2.48 and finally had success deploying to Netlify. Rolling back gatsby-plugin-sharp alone did not work, only both. Once I started building locally again, I had to reapply @davet42 's patch just to successfully build. Very frustrating...

My gatsby-plugin-manifest is only 2.2.30 🤔

**Comment by rasmuswoelk** [comment] 2020-09-04 09:22
Downgrading `gatsby-plugin-sharp` didn't work for me. Lowering the quality worked though. I'm using `gatsby-source-wordpress-experimental` and it was the image processing of my posts that failed. So I lowered the image quality of my posts using [this option](https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/plugin-options.md#htmlimagequality-int) and that did the trick.

**Comment by HassanCorrigan** [comment] 2020-09-07 11:49
> I started to get this error with the most recent version 2.6.31. Downgrading to 2.6.30 fixed the problem for now. I also have my quality setting as 100, although haven’t tried reducing that to fix the issue on the most recent version.

I've since upgraded the plugin to the latest version release to test the image quality settings to see if it works. If I set image quality to anything above 95 the build fails, once I set it to 95 and below the build succeeds. For now I'm using the latest version with reduced quality setting.

**Comment by karlhorky** [comment] 2020-09-07 16:00
### Workaround with latest version

1. Install [`patch-package`](https://www.npmjs.com/package/patch-package) (`npm install patch-package` or `yarn add patch-package postinstall-postinstall`)
2. Add `"postinstall": "patch-package"` to `scripts` in `package.json`
3. Go into `node_modules/imagemin-pngquant/index.js` and change `if (error.code === 99) {` to `if (error.exitCode === 99) {` on line 66
4. Run `npx patch-package imagemin-pngquant`

**Comment by wardpeet** [comment] 2020-09-08 12:13
so setting the quality to 100 is the issue?

**Comment by karlhorky** [comment] 2020-09-08 12:32
@wardpeet I guess the issue is the upgrade of `imagemin-pngquant` to version `9.0.0` in `gatsby-plugin-sharp`:

https://github.com/gatsbyjs/gatsby/commit/dedd37f79467058e0bd17d9f5db176faace272e7

**Comment by wardpeet** [comment] 2020-09-08 14:29
Can you try with `yarn add gatsby-plugin-sharp@png-revert --registry=https://registry.wardpeet.dev`

**Comment by karlhorky** [comment] 2020-09-09 11:53
@wardpeet looks like https://github.com/imagemin/imagemin-pngquant/pull/71 was merged - I guess `imagemin-pngquant` can be bumped to `9.0.1` now to see if it still causes this error.

**Comment by MKlblangenois** [comment] 2020-09-09 11:55
> @wardpeet looks like [imagemin/imagemin-pngquant#71](https://github.com/imagemin/imagemin-pngquant/pull/71) was merged - I guess `imagemin-pngquant` can be bumped to `9.0.1` now to see if it still causes this error.

I've tried, the update works great on my side, on local and Netlify 🎉

**Comment by wardpeet** [comment] 2020-09-09 14:02
Ok waiting for the latest version to merge as imagemin got an update.

**Comment by JulienKode** [comment] 2020-10-22 20:54
I still have the issue with:

- imagemin-pngquant 9.0.1
- gatsby-plugin-sharp 2.6.43

```
WorkerError: Processing **the image path**/image.png failed
Original error:
Command was killed with SIGKILL (Forced termination): ***the node module path*****/pngquant-bin/vendor/pngquant - --strip --quality 80-  100
```

May be I did something wrong

**Comment by wardpeet** [comment] 2020-10-23 10:22
is the image corrups by any chance?

**Comment by JulienKode** [comment] 2020-10-23 12:17
No but I've just update the machine that I use to have a more powerful one, works perfectly

**Comment by mxstbr** [comment] 2020-12-09 09:16
imagemin-pngquant has been updated to the fixed v9.0.1 in #26838. Closing this as its resolved!

**Closed by mxstbr** 2020-12-09 09:16 UTC
Labels: topic: sharp, type: bug

**Comment by esotericjules** [comment] 2021-01-25 18:29
thanks @theinhtut  your solution worked for me.

**Comment by KaranKaira** [comment] 2021-04-06 13:08
Thanks @theinhtut  , your solution works.

**Comment by MindMansion** [comment] 2021-06-25 21:26
if you are still facing this error, my guess is maybe you enabled ignored script at some point.

Solution:

### **globally disable the ignore-script flag**

 npm config set ignore-scripts false  

### **And then remove your project packages:**

rm -rf node_modules
rm package-lock.json 

### **A clean reinstall  of your packages**

npm install

**Comment by cangSDARM** [comment] 2021-06-28 06:40
I met the same problem. I solved it through upgrade `gatsby` and `gatsby-transformer-sharp` both
