### ISSUE TITLE
Images in markdown show blurred and full beneath each other.

### ISSUE THREAD

**Issue by NickyMeuleman** [gatsbyjs/gatsby#16629] opened 2019-08-14 18:51 UTC
## Description

When using an image in an `.mdx` file using the `![alt](image.jpg)` syntax.
The blurry image doesn't get replaced by the fullsize one. The fullsize one is placed beneath and both remain visible.

### Steps to reproduce

Not sure which step of the chain causes this behaviour:
Make a blog with:
- `gatsby-source-filesystem`
- `gatsby-plugin-sharp`
- `gatsby-transformer-sharp`
- `gatsby-plugin-mdx`
  - under `gatsbyRemarkPlugins`: `gatsby-remark-images`
  - under `gatsbyRemarkPlugins`: `gatsby-remark-copy-linked-files`

Guessing `gatsby-remark-images`.

### Expected result

The image shows the blurry image first, then "blurs up" to the full one.

### Actual result

The blurry image shows first, the full one then loads beneath it.

### Reproduction

Minimal reproduction using gatsby-starter-blog-theme
https://codesandbox.io/s/gatsby-starter-blog-theme-d3bk1

(noticed at https://gatsby-theme-nicky-blog.netlify.com/using-sitewide-assets )

**Comment by LekoArts** [comment] 2019-08-14 19:10
Sounds like a duplicate of https://github.com/gatsbyjs/gatsby/issues/15486 ? If yes, please close this issue, thanks!

**Closed** 2019-08-14 21:05 UTC
