### ISSUE TITLE
Optimize all `docs/` images

### ISSUE THREAD

**Issue by nucliweb** [gatsbyjs/gatsby#18776] opened 2019-10-17 16:15 UTC
## Summary

I know that the plugins optimize the images in the build process, but we can optimize **lossless** all images into the `docs` folder: screenshots, avatars, gif animations, etc...

This optimizes too the build time because the images are smaller

### Basic example

I have the images optimized in [perf/images-optimization](https://github.com/nucliweb/gatsby/tree/perf/images-optimization), the commit include 672 images 😱

I used [ImageOptim](https://imageoptim.com/mac) to optimize them.

<img width="780" alt="ImageOptim" src="https://user-images.githubusercontent.com/1307927/67026292-c1343500-f107-11e9-94cb-876d023ad950.png">

#### Ressult

This is the `docs` folder size:

**Before**
`258.981.060 bytes (261,7 MB on disk) for 1.516 items`

**After**
`196.442.901 bytes (199,2 MB on disk) for 1.516 items`

### Motivation

I 💜 **Image Optimization** 🏞
And with this action, we can reduce **62 MB** the repo size with the same images quality 😊

### So...

If you agree, I will send a PR to start the revision process.

**Comment by horacioh** [comment] 2019-10-17 17:24
ping @LekoArts @m-allanson :)
this would be great for the translation repos too 👍

**Comment by nucliweb** [comment] 2019-10-19 09:00
Although I would love to send a PR like this to the Gatsby's repo 😊.

I have been thinking of a better and more automated solution. I think it would be easier and will help future image optimizations implement [ImgBot](https://imgbot.net/).

**Comment by LekoArts** [comment] 2019-11-04 15:46
Hey, thanks for the issue. I'll mark this as a duplicate of https://github.com/gatsbyjs/gatsby/issues/13699

Important note: Changing images without rewriting history (like mentioned in the linked issue) hugely increases the Git history.

**Closed by LekoArts** 2019-11-04 15:46 UTC
