### ISSUE TITLE
Gatsby develop infinitely reloading with error on localhost but working fine on 127.0.0.1

### ISSUE THREAD

**Issue by polyglotpiglet** [gatsbyjs/gatsby#24947] opened 2020-06-12 09:32 UTC
## Description

With any gatsby project that I run locally I see the same problem. It infinitely reloads with an error when I look at localhost:8000 but works fine on other network interfaces. 

### Steps to reproduce

 `gatsby new example https://github.com/billyjacoby/gatsby-react-bootstrap-starter`

`gatsby develop -H 0.0.0.0`

### Expected result

Should display the homepage for the gatsby starter. 

### Actual result

Going to `localhost:8000` displays the following error and infinitely reloads:

<img width="1206" alt="Screenshot 2020-06-12 at 10 25 48" src="https://user-images.githubusercontent.com/11321048/84488088-98187400-ac97-11ea-8b50-fc137f9d194f.png">

However navigating to `127.0.0.0:8000` works just fine. 

### Environment

```
  System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.97
    Firefox: 61.0.1
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.3.34 => 2.23.3
    gatsby-image: ^2.0.41 => 2.4.7
    gatsby-plugin-manifest: ^2.0.29 => 2.4.11
    gatsby-plugin-offline: ^2.0.25 => 2.2.10
    gatsby-plugin-react-helmet: ^3.0.12 => 3.3.4
    gatsby-plugin-sass: ^2.0.11 => 2.3.4
    gatsby-plugin-sharp: ^2.0.35 => 2.6.11
    gatsby-source-filesystem: ^2.0.33 => 2.3.11
    gatsby-transformer-sharp: ^2.1.18 => 2.5.5
  npmGlobalPackages:
    gatsby-cli: 2.12.44
```

**Comment by polarathene** [comment] 2020-06-15 00:34
Check your `/etc/hosts` file, and run `ping localhost`, you might see instead of pinging `127.0.0.1` it pings the equivalent IPv6 address instead `::1`. Is it possible that it's due to that?

You should be able to tell gatsby to use a specific host address, if it's listening on `127.0.0.1` by default, it might not respond well to other addresses. I remember that I could not provide my machines local IP to view in the browser of another machine on the same local network(over WiFi in my case), for that to work I had to have gatsby listen on `0.0.0.0` which is all network interfaces.

**Comment by polarathene** [comment] 2020-06-15 00:37
Your title and post content also mention `127.0.0.0` is that correct? It should be `127.0.0.1` no?

**Comment by polyglotpiglet** [comment] 2020-06-15 17:19
Yes sorry I meant 127.0.0.1. It's not listening to that by default. I'm running on the local network ('gastby develop -H 0.0.0.0') so I can see the websites on my phone. localhost also fails when I run just 'gastby develop'.

**Comment by polarathene** [comment] 2020-06-15 23:49
Did you try the ping command on localhost to see what IP it resolves to? If you edit the hosts file, you can probably make sure it resolves to `127.0.0.1` instead, if you don't use IPv6, you can also try disabling that in case it is the cause.

**Comment by ascorbic** [comment] 2020-06-16 09:54
I can't reproduce this. I followed your steps. I had to remove the yarn.lock from the installed starter, because it's very old and installs a version of sharp that doesn;t support Node 14, but once I did that it worked fine. Could you share a repo that demonstrates this? Thanks.

**Comment by LekoArts** [comment] 2020-06-26 06:53
Please create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

[reproduction]: https://gatsby.dev/reproduction

**Comment by ascorbic** [comment] 2020-07-02 15:52
Hi. I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. Thanks!

**Closed by ascorbic** 2020-07-02 15:52 UTC
Labels: status: needs reproduction, type: bug
