### ISSUE TITLE
Netlifycms Gatsby - Field "image" must not have a selection since type "String" has no subfields.

### ISSUE THREAD

**Issue by stuartverschoyle** [gatsbyjs/gatsby#27862] opened 2020-11-05 19:33 UTC
I have spent all day trying to find the answer to this, been through every github help and just could not find the answer and I know its something very simple.

## Description

When making a change to the .md file I see this error

> error There was an error in your GraphQL query:
> Field "image" must not have a selection since type "String" has no subfields.
> This can happen if you e.g. accidentally added { } to the field "image". If you didn't expect "image" to be of type "String" > > make sure that your input source and/or plugin is correct.

### Steps to reproduce

Started a Gatsby through netlifycms

replicated the following

>         intro {
>            blurbs {
>              image {
>                childImageSharp {
>                  fluid(maxWidth: 356, quality: 64) {
>                    ...GatsbyImageSharpFluid
>                  }
>                }
>              }
>              header
>              text
>            }
>          }

Changed 'blurbs' to 'products' and changed all appropritate files to duplicate everything.

Builds just fine but whenever I make a change in the index.md file i get the error

https://github.com/stuartverschoyle/apollon-gatsby

### Expected result

I would expect the build to be successful and for the changes to change on the browser

### Actual result

I get the error

> error There was an error in your GraphQL query:
> Field "image" must not have a selection since type "String" has no subfields.
> This can happen if you e.g. accidentally added { } to the field "image". If you didn't expect "image" to be of type "String" > > make sure that your input source and/or plugin is correct.

### Environment

command not found: gatsby

Would not work as its through netlfy

**Comment by vladar** [comment] 2020-11-06 11:31
Hi @stuartverschoyle !

Is there a way to run and reproduce this locally? If not, we'll need a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by stuartverschoyle** [comment] 2020-11-06 13:22
Hi Vladar,

I am just adding a new image into the markdown, the initial build is fine, its just when I change anything in the index.md file gives this error in the terminal. Its as if the hot reload isnt picking up the new images (or image path)

>error There was an error in your GraphQL query:
>Field "image" must not have a selection since type "String" has no subfields.
>This can happen if you e.g. accidentally added { } to the field "image". If you didn't expect "image" to be of type "String" > > make sure that your input source and/or plugin is correct.

to reproduce it

 - set up a netlify gatsby cms
 - in index.md duplicate the intro schema and rename it to products (or anything)
 - add different images in the products schema
 - in index-page.js change <Features gridItems={intro.blurbs} /> to <Features gridItems={products.blurbs} />
 - netlify dev (this will build the page and it will work fine)
 - then change some copy on in the index.md and save

This is when i get the below error in the terminal
>error There was an error in your GraphQL query:
>Field "image" must not have a selection since type "String" has no subfields.
>This can happen if you e.g. accidentally added { } to the field "image". If you didn't expect "image" to be of type "String" > > make sure that your input source and/or plugin is correct.


Is there something that I am missing when adding new images??

thanks for your help.

**Comment by stuartverschoyle** [comment] 2020-11-06 13:24
Here is my repo if you want to have a look at that 
https://github.com/stuartverschoyle/apollon-gatsby

**Comment by GautierT** [comment] 2020-11-17 10:56
I have the same problem. I read and try every solution on Internet with the keywords `Field "image" must not have a selection since type "String" has no subfields.` and nothing helped...

**Comment by stuartverschoyle** [comment] 2020-11-17 11:05
@GautierT I found that in your index.md file if you put quotes around index-page it all works for hot reload. 
I didn't have quotes around mine when i downloaded it, after days and days of looking, I had a look at another index.md and realised it had quotes.

Let me know if this works for you.
`---
templateKey: 'index-page'
path: '/'`

**Comment by GautierT** [comment] 2020-11-17 13:20
Hi @stuartverschoyle . Thanks !
But it doesn't change a thing... :(
Every time i change something on `http://localhost:8000/admin/#/collections/pages/entries/index` then publish i have this error message.

**Comment by mysteryihs** [comment] 2020-11-20 03:51
Hi,

I'm having the same error as well, but I think mine is environment related. I'm running Netlify CMS with Gatsby and I haven't modified my gatsby-config.js or anything past html/text and my gatsby builds have begun to fail. Even if I run previously successful builds on netlify, they fail.

![image](https://user-images.githubusercontent.com/10860418/99755669-2b07d680-2aa0-11eb-9029-705c221a133e.png)


Ignore the orange background, it's a blue-light filter. As you can see, my past successful builds fail on netlify, and the same happens on local deploy.

[You can see my repository here.](https://github.com/mysteryihs/oscarswebservices-portfolio)

The error is too generic and there are too many solutions not working.

**Comment by aheruk-n-ix** [comment] 2020-12-29 12:47
I got stuck on the same problem. Any updates on the issue?

**Comment by erezrokah** [comment] 2021-02-18 12:31
Hello 👋 This error usually happens when Gatsby fails to detect the type of an image file referenced in the markdown, thus inferring its type as a string.
That in turns fails the `image` query.

Possible solutions are:
1. Defining a custom schema. See [here](https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization/) for more information.
2. Use relative media folders in the CMS configuration to put media files in the same directory as the markdown file. That makes it easier for Gatsby to find the file. See [here](https://www.netlifycms.org/docs/gatsby/#configuration) for an example configuration.

**Comment by erezrokah** [comment] 2021-02-22 12:47
Closing this per my comment. Please comment on the issue if still relevant and using the suggested solutions doesn't work.

**Closed by erezrokah** 2021-02-22 12:47 UTC
Labels: topic: GraphQL, type: bug
