### ISSUE TITLE
[gatsby-source-wordpress] - Gatsby V3 migration - gatsby develop resulting in Interfaces with the `nodeInterface` extension must have a field `id` of type `ID!`. Check the type definition of `WpBlockEditorContentNode`.

### ISSUE THREAD

**Issue by bnbabu55** [gatsbyjs/gatsby#30232] opened 2021-03-13 05:15 UTC
## Description
I have cloned gatsby-default-starter to my local and then updated package json to the use Gatsby v3, then ran a gatsby develp, every thing ran smoothly.

Then wanted to source data from my wordpress site, so installed gatsby-source-wordpress v5, started getting errors.

My dependencies at Package.json
  "dependencies": {
    "autoprefixer": "^10.2.5",
    "dotenv": "^8.2.0",
    "gatsby": "^3.0.4",
    "gatsby-plugin-google-analytics": "^3.0.0",
    "gatsby-plugin-image": "^1.0.1",
    "gatsby-plugin-manifest": "^3.0.0",
    "gatsby-plugin-offline": "^4.0.0",
    "gatsby-plugin-postcss": "^4.0.0",
    "gatsby-plugin-purgecss": "^5.0.0",
    "gatsby-plugin-react-helmet": "^4.0.0",
    "gatsby-plugin-sentry": "^1.0.1",
    "gatsby-plugin-sharp": "^3.0.0",
    "gatsby-source-filesystem": "^3.0.0",
    "gatsby-source-wordpress": "^5.0.0",
    "gatsby-transformer-sharp": "^3.0.0",
    "postcss": "^8.2.8",
    "prop-types": "^15.7.2",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-helmet": "^6.1.0"
  },
  "devDependencies": {
    "prettier": "^2.2.1",
    "tailwindcss": "^2.0.3"
  },

###Wordpress plugins
WordPress v5.7, graphql link https://smr-sandbox.com/graphql

1. WPGraphql 1.2.5
2. WPGatsby 1.0.6
3. WP GraphQL Gutenberg 0.3.8
4. WP GraphQL Gutenberg ACF 0.3.0
5. WPGraphQL for Advanced Custom Fields 0.4.1
6. WPGraphQL Offset Pagination 0.2.0
7. Yoast SEO 15.9.2
8. Add WPGraphQL SEO 4.11.0
--

###Error message from **gatsby develop** command
success  gatsby-source-wordpress  MediaItem - 367.948s - fetched 191
success  gatsby-source-wordpress  creating nodes - 367.973s
success  gatsby-source-wordpress  fetching nodes - 398.449s - 437 total
success Downloading remote files - 365.833s - 191/191 0.52/s
success Checking for changed pages - 0.001s
success source and transform nodes - 398.585s
warn Deprecation warning: `@nodeInterface` extension is deprecated and will be removed in Gatsby v4. Use interface inheritance instead.
To upgrade replace the old format:
  interface `WpContentNode` @nodeInterface
with the new one (in `createTypes` action of schema customization API):
  interface `WpContentNode` implements Node
Read more about schema customization here:
https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization/
warn Deprecation warning: `@nodeInterface` extension is deprecated and will be removed in Gatsby v4. Use interface inheritance instead.        
To upgrade replace the old format:
  interface `WpBlockEditorContentNode` @nodeInterface
with the new one (in `createTypes` action of schema customization API):
  interface `WpBlockEditorContentNode` implements Node
Read more about schema customization here:
https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization/

 ERROR

Interfaces with the `nodeInterface` extension must have a field `id` of type `ID!`. Check the type definition of `WpBlockEditorContentNode`.   

not finished building schema - 0.366s

### Steps to reproduce
1. use the package.json dependencies above.
2. use graphql link https://smr-sandbox.com/graphql
3. gatsby develop

### Expected result

Successfull build without any errors.

### Actual result

success  gatsby-source-wordpress  MediaItem - 367.948s - fetched 191
success  gatsby-source-wordpress  creating nodes - 367.973s
success  gatsby-source-wordpress  fetching nodes - 398.449s - 437 total
success Downloading remote files - 365.833s - 191/191 0.52/s
success Checking for changed pages - 0.001s
success source and transform nodes - 398.585s
warn Deprecation warning: `@nodeInterface` extension is deprecated and will be removed in Gatsby v4. Use interface inheritance instead.
To upgrade replace the old format:
  interface `WpContentNode` @nodeInterface
with the new one (in `createTypes` action of schema customization API):
  interface `WpContentNode` implements Node
Read more about schema customization here:
https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization/
warn Deprecation warning: `@nodeInterface` extension is deprecated and will be removed in Gatsby v4. Use interface inheritance instead.        
To upgrade replace the old format:
  interface `WpBlockEditorContentNode` @nodeInterface
with the new one (in `createTypes` action of schema customization API):
  interface `WpBlockEditorContentNode` implements Node
Read more about schema customization here:
https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization/

 ERROR

Interfaces with the `nodeInterface` extension must have a field `id` of type `ID!`. Check the type definition of `WpBlockEditorContentNode`.   

not finished building schema - 0.366s

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  Binaries:
    Node: 15.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - C:\Program Files\nodejs\yarn.CMD
    npm: 7.6.3 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17 - /c/Utilities/Python2/python
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.50)
  npmPackages:
    gatsby: ^3.0.4 => 3.0.4
    gatsby-plugin-google-analytics: ^3.0.0 => 3.0.0
    gatsby-plugin-image: ^1.0.1 => 1.0.1
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0
    gatsby-plugin-offline: ^4.0.0 => 4.0.0
    gatsby-plugin-postcss: ^4.0.0 => 4.0.0
    gatsby-plugin-purgecss: ^5.0.0 => 5.0.0
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0
    gatsby-plugin-sentry: ^1.0.1 => 1.0.1
    gatsby-plugin-sharp: ^3.0.0 => 3.0.0
    gatsby-source-filesystem: ^3.0.0 => 3.0.0
    gatsby-source-wordpress: ^5.0.0 => 5.0.0
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0
  npmGlobalPackages:
    gatsby-cli: 3.0.0
    gatsby: 3.0.4

**Comment by LekoArts** [comment] 2021-03-13 09:05
Duplicate of https://github.com/gatsbyjs/gatsby/issues/29966

**Closed by LekoArts** 2021-03-13 09:05 UTC
Labels: status: triage needed, type: bug
