### ISSUE TITLE
Gatsby wordpress hardCacheMediaFiles does not work as expected

### ISSUE THREAD

**Issue by lnikell** [gatsbyjs/gatsby#30570] opened 2021-03-30 13:54 UTC
## Description

We use the latest version of `gatsby-source-wordpress@5.1.0`, `WP Gatsby@1.0.7 `, `WP Graphql@1.3.3` however we see that hardCacheMediaFiles does not work from time to time and gatsby starts loading files from WP instead of just using the local versions in the .wordpress-cache folder.

### Expected result

If there is a .wordpres-cache folder in place there should not be any queries to WP related to data fetching, and the only checksum should be compared to decide whether it should be fetched or no.

### Actual result

Data starts loading from scratch when .wordpress-cache folder exists and all media items already in place.

### Environment

Experience in CI, local env and Kubernetes cluster with deployed preview server.

**Comment by lnikell** [comment] 2021-03-30 14:05
Another problem if we fetch almost all data but then build fails on fetching MediaItems we have to fetch everything over and over again while trying to debug the issue with failed fetching of one single MediaItem for example.

**Comment by lnikell** [comment] 2021-04-05 10:13
Forgot that I opened similar issue already and created another one but better described https://github.com/gatsbyjs/gatsby/issues/30683

**Comment by LekoArts** [comment] 2021-04-06 07:12
Duplicate of https://github.com/gatsbyjs/gatsby/issues/30683

**Closed by LekoArts** 2021-04-06 07:12 UTC
Labels: topic: WordPress, type: bug
