### ISSUE TITLE
[docs] new doc on Building Image heavy sites

### ISSUE THREAD

**Issue by aditsachde** [gatsbyjs/gatsby#18423] opened 2019-10-09 23:43 UTC
## Summary

We have documentation for dealing with images and working with images. There is already stub for building image heavy sites, this doc would be mostly about development and working with the site itself, such as using Git LFS / storing images outside of Git to prevent bloat, as well as making development easier by enabling features such as [image placeholders](https://github.com/gatsbyjs/gatsby/tree/master/www#running-slow-build-screenshots-placeholder), among other things.

For anyone interested in picking this up, please read through these resources to ensure your PR is accepted:

- [Gatsby Style Guide](https://www.gatsbyjs.org/contributing/gatsby-style-guide/)
- [Docs contributions](https://www.gatsbyjs.org/contributing/docs-contributions/), including updating the docs sidebar
- [Reference Guide template](https://www.gatsbyjs.org/contributing/docs-templates/#reference-guides)

**Comment by LekoArts** [comment] 2020-05-25 12:51
This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/10448

**Closed by LekoArts** 2020-05-25 12:51 UTC
Labels: type: documentation
