### ISSUE TITLE
examples/using-page-transitions/ does not transition out

### ISSUE THREAD

**Issue by nopjia** [gatsbyjs/gatsby#7603] opened 2018-08-24 15:29 UTC
## Description

The example "using-page-transitions" stopped working correctly. Specifically, it does not seem to perform a "transition-out". When navigating, the current page should fade out before the next page fades in.

I was relying on this example for my website, and I noticed this problem today, when upgrading from `2.0.0-beta.67` to `2.0.0-rc.0`.

### Expected result

When navigating, the current page should fade out before the next page fades in.

### Actual result

The current page does not fade out, but disappears abruptly, and the next page immediately fades in.

### Environment

  System:
    OS: OS X El Capitan 10.11.6
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
    npm: 6.2.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Safari: 9.1.2
  npmPackages:
    gatsby: next => 2.0.0-rc.0
    gatsby-plugin-react-helmet: next => 3.0.0-rc.0
  npmGlobalPackages:
    gatsby: 2.0.0-rc.0

**Comment by nopjia** [comment] 2018-08-24 16:08
Also, npm package "history" is missing, so a npm dependency is required `npm i -S history`

**Comment by nopjia** [comment] 2018-08-24 16:21
Also, would be great to get an explanation of how this example works at all. I'm not understanding what it's doing and can't debug it...

**Comment by Chuloo** [comment] 2018-08-24 21:38
Page transition seemed to work and new pages fade in when clicked. However, I had to install `history`, I think this should be fixed. 
@nopjia here's the repro attempt repro. https://github.com/Chuloo/gatsby-using-page-transition-7603.  You can verify page transition when you run `gatsby develop`.

**Comment by nopjia** [comment] 2018-08-24 22:35
Yes. New pages fade in correctly. The problem is the current page does not *fade out*.

To see this more clearly, make the timeout longer in `gatsby-browser.js` (something like `const timeout = 1000;`). You will see that the current page simply disappears, whereas before it should fade out.

**Comment by merelinguist** [comment] 2018-08-25 18:07
The problem is that the replaceHistory API has been deprecated since React Router was replaced with Reach Router.

**Closed** 2018-08-29 21:54 UTC
Labels: good first issue, status: help wanted, type: bug

**Comment by MrRobotjs** [comment] 2018-11-25 03:40
Was there ever a fix for page transitions ? receiving the same error
```
success open and validate gatsby-config — 0.011 s
⠁
Your plugins must export known APIs from their gatsby-browser.js.
The following exports aren't APIs. Perhaps you made a typo or your plugin is outdated?

See https://www.gatsbyjs.org/docs/browser-apis/ for the list of Gatsby Browser APIs

- Your site's gatsby-browser.js is exporting a variable named "replaceHistory" which isn't an API.```
