### ISSUE TITLE
gatsby rich snippets - encoding issue (cyrillic)

### ISSUE THREAD

**Issue by ivan3web** [gatsbyjs/gatsby#25258] opened 2020-06-24 14:58 UTC
Hello,

I am developing a Gatsby website and I have an issue with rich snippets.

There is a problem with the Cyrillic letters I believe, take a look at what the testing tools return. 

Link: https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fbg.dianurse.com%2Fptuvane-s-diabet%2F
Url: https://bg.dianurse.com/ptuvane-s-diabet

```
Binaries:
    Node: 12.18.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.106
    Firefox: 77.0.1
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.21.22 => 2.23.7
    gatsby-image: ^2.4.3 => 2.4.7
    gatsby-plugin-mailchimp: ^5.1.2 => 5.2.2
    gatsby-plugin-manifest: ^2.4.2 => 2.4.12
    gatsby-plugin-offline: ^3.2.1 => 3.2.11
    gatsby-plugin-react-helmet: ^3.3.1 => 3.3.4
    gatsby-plugin-sharp: ^2.6.2 => 2.6.12
    gatsby-plugin-stylus: ^2.3.1 => 2.3.4
    gatsby-source-contentful: ^2.3.3 => 2.3.16
    gatsby-source-filesystem: ^2.3.1 => 2.3.12
    gatsby-transformer-sharp: ^2.5.2 => 2.5.5
  npmGlobalPackages:
    gatsby-cli: 2.12.45
```

**Comment by pieh** [comment] 2020-06-25 12:06
I don't think this is gatsby specific issue here, but from some research that I did - this _might_ be just google's structured data testing tool issue (but this is just my feeling, I wouldn't bet on it). 

On https://webmaster.yandex.com/tools/microtest/ (might need to register) it shows like this:
![Screenshot 2020-06-25 at 13 56 56](https://user-images.githubusercontent.com/419821/85715546-dc6e3000-b6eb-11ea-91d0-998347a05729.png) (which is what we would expect, right?)

**Comment by LekoArts** [comment] 2020-06-25 12:59
So I looked a bit into this issue and think that this is not caused by Gatsby. I found this StackOverflow thread (https://stackoverflow.com/questions/8310560/microformats-hrecipe-vs-schemas-recipe) where they talk about special microdata for Yandex, however nowadays all major search engines support the schema.org format, and most people now use the JSON-LD syntax.

I looked at the test tool link you shared and indeed, Google has problems interpreting that.
I then took a russian news article (https://www.themoscowtimes.com/ru/2020/06/24/vracham-kotorie-boryutsya-s-koronavirusom-prikazivayut-golosovat-po-popravkam-v-konstitutsiyu-a270) and put it into the test tool:
https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.themoscowtimes.com%2Fru%2F2020%2F06%2F24%2Fvracham-kotorie-boryutsya-s-koronavirusom-prikazivayut-golosovat-po-popravkam-v-konstitutsiyu-a270

They are encoding the names:

```
<script type="application/ld+json" data-json-ld-for-pagemetadata>
	{"@context":"http:\/\/schema.org\/","@type":"NewsArticle","dateCreated":"2020-06-24T08:46:53+02:00","datePublished":"2020-06-24T10:19:45+02:00","dateModified":"2020-06-25T14:50:01+02:00","name":"\u0412\u0440\u0430\u0447\u0430\u043c, \u043a\u043e\u0442\u043e\u0440\u044b\u0435 \u0431\u043e\u0440\u044e\u0442\u0441\u044f \u0441 \u043a\u043e\u0440\u043e\u043d\u0430\u0432\u0438\u0440\u0443\u0441\u043e\u043c, \u043f\u0440\u0438\u043a\u0430\u0437\u044b\u0432\u0430\u044e\u0442 \u0433\u043e\u043b\u043e\u0441\u043e\u0432\u0430\u0442\u044c \u043f\u043e \u043f\u043e\u043f\u0440\u0430\u0432\u043a\u0430\u043c \u0432 \u041a\u043e\u043d\u0441\u0442\u0438\u0442\u0443\u0446\u0438\u044e","headline":"\u0412\u0440\u0430\u0447\u0430\u043c, \u043a\u043e\u0442\u043e\u0440\u044b\u0435 \u0431\u043e\u0440\u044e\u0442\u0441\u044f \u0441 \u043a\u043e\u0440\u043e\u043d\u0430\u0432\u0438\u0440\u0443\u0441\u043e\u043c, \u043f\u0440\u0438\u043a\u0430\u0437\u044b\u0432\u0430\u044e\u0442 \u0433\u043e\u043b\u043e\u0441\u043e\u0432\u0430\u0442\u044c \u043f\u043e \u043f\u043e\u043f\u0440\u0430\u0432\u043a\u0430\u043c \u0432 \u041a\u043e\u043d\u0441\u0442\u0438\u0442\u0443\u0446\u0438\u044e","description":"\u00ab\u042d\u0442\u043e \u043d\u0435\u043f\u0440\u0430\u0432\u0438\u043b\u044c\u043d\u043e. \u041f\u043e\u0441\u043b\u0435 \u0432\u0441\u0435\u0433\u043e, \u0447\u0442\u043e \u043c\u044b \u0441\u0434\u0435\u043b\u0430\u043b\u0438, \u043d\u0430\u043c \u043d\u0435 \u0434\u043e\u043b\u0436\u043d\u044b \u0433\u043e\u0432\u043e\u0440\u0438\u0442\u044c \u0447\u0442\u043e \u0434\u0435\u043b\u0430\u0442\u044c\u00bb","keywords":"\u0433\u043e\u043b\u043e\u0441\u043e\u0432\u0430\u043d\u0438\u0435","articleSection":"news","isAccessibleForFree":true,"mainEntityOfPage":"https:\/\/www.themoscowtimes.com\/ru\/2020\/06\/24\/vracham-kotorie-boryutsya-s-koronavirusom-prikazivayut-golosovat-po-popravkam-v-konstitutsiyu-a270","url":"https:\/\/www.themoscowtimes.com\/ru\/2020\/06\/24\/vracham-kotorie-boryutsya-s-koronavirusom-prikazivayut-golosovat-po-popravkam-v-konstitutsiyu-a270","thumbnailUrl":"https:\/\/static.themoscowtimes.com\/ru\/image\/320\/88\/TASS40266546.jpg","image":{"@type":"ImageObject","url":"https:\/\/static.themoscowtimes.com\/ru\/image\/1360\/88\/TASS40266546.jpg","width":1360,"height":765},"publisher":{"@type":"Organization","name":"The Moscow Times in Russian","logo":{"@type":"ImageObject","url":"https:\/\/static.themoscowtimes.com\/ru\/img\/logo.png","width":50,"height":50}},"inLanguage":{"@type":"Language","name":"Russian","alternateName":"ru"},"creator":"\u041f\u0451\u0442\u0440 \u0421\u0430\u0443\u044d\u0440","author":{"@type":"Person","name":"\u041f\u0451\u0442\u0440 \u0421\u0430\u0443\u044d\u0440","description":null,"image":"https:\/\/static.themoscowtimes.com\/ru\/image\/320\/3c\/59286.jpg","url":"https:\/\/www.themoscowtimes.com\/ru\/author\/petr-sauer","sameAs":"http:\/\/www.twitter.com\/PjotrSauer"}}</script>
```

This way - apparently - Google can understand it:

![image](https://user-images.githubusercontent.com/16143594/85724247-51ddfe80-b6f4-11ea-882e-281101a8d57d.png)

So I think this onto you now to use the JSON-LD syntax and encode the entries so that Google can read it. Therefore I'll close this issue.

**Closed by LekoArts** 2020-06-25 12:59 UTC
Labels: type: question or discussion
