### ISSUE TITLE
gatsby-source-wordpress ACF filter relation just disappeared

### ISSUE THREAD

**Issue by ernaneluis** [gatsbyjs/gatsby#25266] opened 2020-06-24 21:06 UTC
## Description

I add an ACF field `tags` to media objects on wordpress. Thus, installed gatsby config with:

```
      resolve: `gatsby-source-wordpress`,
      options: {
        baseUrl: `${process.env.GATSBY_WP_DOMAIN}`,
        protocol: `http`,
        hostingWPCOM: false,
        useACF: true,
      },
    },
```

and using this graphql query:

```
 allWordpressWpMedia(limit: 24, filter: { acf: { tags: { eq: $id } } }) {
      edges {
        node {
          id
          caption
          alt_text
          post
          slug
          source_url
          title
          localFile {
            childImageSharp {
              fluid {
                ...GatsbyImageSharpFluid_withWebp
              }
            }
          }
        }
      }
    }
```

**It used to work just fine**, but now I tried to build again, I got this error:

```
There was an error in your GraphQL query:

Field "acf" is not defined by type wordpress__wp_mediaFilterInput.

```

This filter `filter: { acf: { tags: { eq: $id } } }` just disappeared on docs inside graphql explorer `localhost/__graphql`

- The endpoint is working fine, I can query using the api the data of custom field.
- Im using WP Multisite.

### Steps to reproduce

Installed wordpress plugins:

- ACF to REST API  -> set to V2 ( I also tried v3 and did not work) - v3.2.0 
- Advanced Custom Fields v5.8.12

### Expected result
- Query media by ACF 

What should happen?
- return list of all media objects filtered by tag Id

### Actual result
- Query error

What happened.
- app crash

### Environment

```
System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.13.0 
    Yarn: 1.16.0 
    npm: 6.14.4 
  Languages:
    Python: 2.7.16
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 76.0.1
    Safari: 13.1.1
  npmPackages:
    gatsby: 2.23.11 => 2.23.11
    gatsby-core-utils: ^1.3.8 => 1.3.8
    gatsby-image: ^2.4.9 => 2.4.9
    gatsby-plugin-advanced-sitemap: ^1.5.5 => 1.5.5
    gatsby-plugin-eslint: 2.0.8 => 2.0.8
    gatsby-plugin-google-analytics: ^2.3.6 => 2.3.6
    gatsby-plugin-manifest: 2.4.14 => 2.4.14
    gatsby-plugin-offline: ^3.2.13 => 3.2.13
    gatsby-plugin-postcss: 2.3.6 => 2.3.6
    gatsby-plugin-react-helmet: 3.3.6 => 3.3.6
    gatsby-plugin-robots-txt: ^1.5.1 => 1.5.1
    gatsby-plugin-sass: ^2.3.6 => 2.3.6
    gatsby-plugin-sharp: ^2.6.14 => 2.6.14
    gatsby-source-filesystem: ^2.3.14 => 2.3.14
    gatsby-source-graphql: ^2.5.7 => 2.5.7
    gatsby-source-wordpress: ^3.3.15 => 3.3.15
    gatsby-source-wordpress-experimental: ^0.7.11 => 0.7.11
    gatsby-transformer-sharp: ^2.5.7 => 2.5.7
    gatsby-wpgraphql-inline-images: ^0.2.5 => 0.2.5
  npmGlobalPackages:
    gatsby-cli: 2.11.3
```

Definition of `wordpress__wp_mediaFilterInput `
![Screen Shot 2020-06-24 at 18 07 55](https://user-images.githubusercontent.com/1398769/85627928-ac6c5180-b645-11ea-9c17-935ea7776c5a.png)

return of API `myblog.com/wp-json/acf/v2/media/1085`
![Screen Shot 2020-06-24 at 18 12 12](https://user-images.githubusercontent.com/1398769/85628310-521fc080-b646-11ea-94ff-36229ff15d81.png)

`/wp-json/acf/v3/media`
![Screen Shot 2020-06-24 at 19 59 26](https://user-images.githubusercontent.com/1398769/85635826-45569900-b655-11ea-836a-d76777318d20.png)

`/wp-json/wp/v2/media/963`
ACF is there on the media endpoint, but still the relationship  wpMedia->acf is not there
![Screen Shot 2020-06-24 at 20 14 06](https://user-images.githubusercontent.com/1398769/85636578-50122d80-b657-11ea-9e45-20bbc4f592f4.png)

I also can query the endpoint return using this graphql query:
```
  allWordpressAcfMedia(filter: {acf: {tags: {eq: 10}}}) {
    nodes {
      wordpress_id
    }
  }
```

**Comment by TylerBarnes** [comment] 2020-07-14 23:42
Hi @ernaneluis !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

I'd also like to let you know that `gatsby-source-wordpress` will soon be undergoing a major change from v3 -> v4. We're switching from using the REST api behind the scenes to using WPGraphQL. This will result in some changes to how you query data in Gatsby, but it will also mean that the API is generally more stable. I recommend upgrading your project sooner than later by using our beta package which you can find here https://github.com/gatsbyjs/gatsby-source-wordpress-experimental. We're currently publishing the beta under a separate package name to allow folks to more easily migrate to the latest version. 

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by TylerBarnes** [comment] 2020-07-21 16:05
Hi @ernaneluis !

I'm closing this issue due to no reproduction being posted within 7 days.
Once you have a minimal reproduction feel free to re-open this issue and we'll be happy to take another look. 💜 

Thank you!

**Closed by TylerBarnes** 2020-07-21 16:05 UTC
Labels: status: needs reproduction, topic: WordPress, type: bug
