### ISSUE TITLE
[feat]: add ability to pass variables to StaticQuery

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#10482] opened 2018-12-15 02:46 UTC
In order to run queries for Gatsby, we have to know at build-time what the query is and any arguments.

We can do this with page queries as pages can be created with "context" which can be used as arguments for the GraphQL query.

I didn't allow arguments with `<StaticQuery>` because there wasn't a clear way to allow people to specify build-time arguments that wouldn't confuse people into thinking that arguments would also work at runtime (explaining the distinction between build vs. run time is very hard IME).

There also wasn't need for arguments either as the query is only run once — arguments are of course for when you want to run something multiple times but vary in specified ways how the query runs.

But a recent tweet inspired a thought for how arguments could work: https://twitter.com/wesbos/status/1073338618897448960

The tweet's example was about how to create an image component that queries for image thumbnails for gatsby-image using `<StaticQuery>`. The idea is that you'd use it by passing a prop in for the image file you want to use e.g. `<MyImage src="kyle-mathews.jpg" />`.

`my-image.jsx` might look like:

```jsx
import React from "react"
import Img from "gatsby-image"
import { StaticQuery } from "gatsby"

export default ({ src }) => {
  <StaticQuery
    query={graphql`
      query HeadingQuery($src: String!) {
         File(relativePath: { eq: $src }) {
           childImageSharp { ...etc }
         }
    `}
    render={data => (
       <Img fixed={data.path.to.query} />
    )}
  />
}
```

Now this by itself wouldn't work. At build time, we'd have no idea about how or where the component is used and what the arguments are and no way to know when and where to load in the results of the queries (how ever many there'd need to be).

But what could work is that we'd detect that a `<StaticQuery>` is taking arguments and then scan for every location that component is used. Then we'd rewrite each usage of `<MyImage>` to import a copy of `my-image.jsx` that has the arguments inserted e.g. `<MyImage src="kyle-mathews.jpg" />` gets turned into `<MyImage2344324 src="kyle-mathews.jpg" />`

`my-image-2344324.jsx` looks like:

```jsx
import React from "react"
import Img from "gatsby-image"
import { StaticQuery } from "gatsby"

export default ({ src }) => {
  <StaticQuery
    query={graphql`
      query HeadingQuery {
         File(relativePath: { eq: "kyle-mathews.jpg" }) {
           childImageSharp { ...etc }
         }
    `}
    render={data => (
       <Img fixed={data.path.to.query} />
    )}
  />
}
```

The problems with this are we'd still have to enforce that only static values would be supported as args (strings/numbers) and any run-time data would be ignored. Perhaps we could lint for this.

Dynamic runtime lookup of query results _might_ be supportable by creating a lookup table and then running queries for all possible arguments but this obviously could lead to a crap ton of extra queries being run during builds.

We could use this to ship a nice wrapper to gatsby-image e.g. `<FixedImage>` and `<FluidImage>` that would work like: `<FixedImage src="kyle-mathews.jpg" width={200} height={300} />`

**Comment by alexluong** [comment] 2018-12-15 03:16
> The problems with this are we'd still have to enforce that only static values would be supported as args (strings/numbers) and any run-time data would be ignored

This mean that we cannot pass user input values as arguments for these types of components, right? I feel like it's going to be super confusing for users to be able to use variables but only static values are supported.

Is there any way we can emphasize that "although you can pass a variable, it needs to be predefined"? I'm thinking something along the line of a Gatsby plugin that accept an array of strings. When passing a variable, it needs to be an element in the array.

**Comment by ChristopherBiscardi** [comment] 2018-12-15 03:34
This is a similar approach we take to generating wrappers in gatsby-mdx and I think it could be a fantastic approach not just for MDX content, but also potentially as a primitive for theming when the theme's image handling can be shadowed by the user without needing to write additional image queries themselves. Imagine a theme providing using an Image component that renders the result using a file in `src/components/blog-post-header-image.js`. The rendering logic for the image can be shadowed without the user having to worry about modifying the graphql query from whence it came.

As @alexluong mentions, this could be confusing if you're expecting dynamic values. We could also do something similar to webpack's require.context and if you pass in a glob, we find all of the images that match, get them processed, and you can choose between them at runtime. At which point it's sort of "your responsibility" as the user to make sure you only access images that exist (or fall back if they don't. require.context is reasonable inspiration for providing a json object of potential image values to choose from). In any case, that's "part two" or "sometime later" functionality IMO and we should focus on enabling this for static values to start.

**Comment by jgierer12** [comment] 2018-12-15 08:47
I like this, with one suggestion: Let users explicitly pass the variables as an object like so:

```javascript
<StaticQuery query={graphql`
  query HeadingQuery($src: String!) {
    File(relativePath: { eq: $src }) {
      childImageSharp { ...etc }
    }
  `
  }
  variables={{ src }}
  render={data => (
    <Img fixed={data.path.to.query} />
  )}
/>
```

That way you could remap variable names or use nested objects.

I first thought that the validation could be made as an eslint plugin, but that wouldn't work as we also need to check that the consumer of the component doesn't change the variable. I believe that would only be possible with something like TypeScript.

Another approach (that would also satisfy my first suggestion) is to require a certain name for the query variable prop, eg:

```javascript
export default ({ queryVariables: { src } }) => {
  <StaticQuery query={graphql`
    query HeadingQuery($src: String!) {
      File(relativePath: { eq: $src }) {
        childImageSharp { ...etc } }
    `}
    render={data => (
      <Img fixed={data.path.to.query} />
    )}
  />
}
```

That would be easily checkable for an eslint plugin (simply require that everytime a `queryVariables` prop is passed, it has to be immutable).

**Comment by nduc** [comment] 2019-02-09 01:15
My use case is when I use gatsby-background-image and I need to load different file for mobile vs desktop. It would be nice to be able to pass in a file name to the static query, as @KyleAMathews mentioned above.

**Comment by lxibarra** [comment] 2019-03-05 05:49
Plus one here im trying to optimize image loading bu at the same time dont want to write graphql queries for each image.

**Comment by guyinpv** [comment] 2019-03-17 07:14
I have this use-case as well, for dynamically passing in an image name to the component.

I want to use StaticQuery for the obvious benefit of the image sharp stuff, src for different screens etc.

It seems to me that in a certain sense, the variables are already immutable, since those variables would start life as a prop on the component reference somewhere.

So Gatsby needs to be able to quickly connect the StaticQuery variables to the component props, and then find each reference where the props are set.

This definitely becomes difficult if the props are converted to other variable names before used within the query. So the first idea would be to force a direct correlation between the component props, and the variables being used in the query. This, at least, erases some chicken chasing with variable definitions and so on. I don't know how it could be done, given that a prop value might need some kind of mutation before use in the query, and mutation might necessitate using another variable name.
And then again, maybe somehow in code they have to generate a variable not even based on props at all! Like a calculation based on timestamp or random generation or something.

Anyway, if you can lock in the correlation of query variables to props, you then have the issue of finding everywhere the component is referenced. Or specifically everywhere it is referenced with the given props in use, cause that's all that matters really.

All I can suggest here is that Gatsby keep a kind of lookup table/cache that actually tracks all the components and where they are referenced. This data might be heavy to process, I don't know, but that data would also be useful for debugging, as it could then be used to generate an overview of your site with simple stats like "X component is used Y times across Z pages" and be able to list each page and component reference. That is handy data even if a little heavy to process!

Finally, Gatsby would have no choice, because there simply is no other way to do it, to render additional copies of the StaticQuery with each alternate variable used. This is a given, I don't see any other way to get through this part, it simply has to run through the query multiple times with each different variable set used. So temp copies of the query would have to be generated with each variable replacement.

All that said, I understand the normal way to do this would be query all the potential images from the page itself, and pass those into the component where used. The only reason I don't want to do this is that I'm trying to make the component more self-contained and not mess the page component with tons of queries for everything. If the component has everything it needs within itself, it's so much cleaner.

Anyway I hope you get it solved some day!

**Comment by mxmkhv** [comment] 2019-03-26 12:36
Struggling with the same issue and after reading every possible stackoverflow question, github issue and twitter discussion, I came up with 2 solutions for my case.

**The goal:** 
1. fetch data from a headless CMS (custom build of my company, returns a plain JSON)
2. use the data to fetch the images (included as URLs in the JSON)
3. create pages dynamically, each page to display it's relevant image with the **gatsby-image** plugin

**The problems:** 
1. dynamically creating nodes from image URLs
2. creating dynamic queries for each page  OR pass image object via **pageContext**

**The solution: to problem 1.**

Create the image nodes with the **createRemoteFileNode** helper function, which I found out about [here](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-filesystem). Not sure if that is a proper use of it, but it works like a charm. Images are now available for querying.

```
exports.sourceNodes = async ({ actions, createNodeId, node, store, cache }) => {
  const { createNode } = actions;
  
  const fetchData = () => axios.get(myDataURL)
  const res = await fetchData();
  
  const myData = res.data;  //the JSON data from the CMS response

  const myDataNode = {  
    id: myData.id,
    parent: null,
    internal: {
      type: myData,
    },
    children: [], 
    data: myData,   //insert my data
  }
  const contentDigest = crypto
    .createHash(`md5`)
    .update(JSON.stringify(myDataNode))
    .digest(`hex`);
    myDataNode.internal.contentDigest = contentDigest;

  createNode(myDataNode); // create the node

  const allPosts = myData.posts //get all posts data

  //loop through array of image objects and create separate node for each image 
  allPosts.forEach((post) => {
    createRemoteFileNode({
      url: post.image,
      store,
      cache,
      createNode,
      createNodeId: id => post.id, //id wanted a function, so I provided one :) 
      name: post.id,   // IMPORTANT - name each image as the post ID to match them later
    })  
  })
  return
}
```

**In addition:**
For the _gatsby-image plugin_ to work, the _gatsby-source-filesystem_ plugin has to have access to the _/images folder_ (although my images are fetched and not stored locally), so the following config was required in **gatsby-config.js**


```
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`, //this is required for the gatsby-image plugin to work
      },
    },
```

So, now I have the images in my graphQL schema, but in order to render an image in my dynamically created pages, I have to query for _all images_ and filter out the one I need, similar to what was discussed in the Wes Bos [twitter post](https://twitter.com/wesbos/status/1073338618897448960).

The solution works, but it's not really scalable, so the one true solution for me was to pass the **"fixed"** or the **"fluid"** object (returned by a graphQL query for an image), as **context** to the dynamically created pages, using the createPages API.

**The solution: to problem 2.**

SPOILER: I use the **onPreExtractQueries**  api as a lifecycle hook, to init **createPages**, only after the images are fetched and nodes are created. Otherwise the image nodes are not available at build time, because they are not yet downloaded.

 **Not sure if this is by any means righteous, but it works.** And it allows me to pass the whole fuild object as context.

```
exports.onPreExtractQueries = () => { 

  exports.createPages = ({ graphql, actions }) => {
    const { createPage } = actions
    
    //make one query to fetch myData and one to fetch all images 
    return graphql(`
      {
        myData {
          ...allData
        },
        allImageSharp {  //access all images
          edges {
            node {
              id
              fluid {  // fragments did not work here, I don't know why
                ...GatsbyImageSharpFluid
              }
            }
          }
        }
      }
    `
  ).then(result => {
      const allPosts = result.myData.posts //get all posts
      const imgData = result.data.allImageSharp.edges //the array of all image nodes
      
      const fluidImageObjects = [] //create an empty array

      imgData.forEach((image) => { //push all the fluid objects to the empty array
        fluidImageObjects.push(image.node.fluid)
      })

      
      allPosts.forEach((post) => {  //iterate over each post object and create a page

        //match the relevant fluid image object, this is for jpg only, but you can slice('/').pop() the url and get the image name also
        const imageFluid= fluidImageObjects.find(image => image.originalName === `${post.id}.jpg`)
        
       createPage({
          path: `/pages/${post.title}`,
          component: path.resolve(`./src/templates/PostTemplate.js`),
          context: { 
            data: post, 
            image: imageFluid//pass the fluid object as context
          }
        })
      })
    })
  }
}
```

Then simply add this to any page, created by _createPages_

`<Img fluid={pageContext.imageFluid}/>`

And you get the post image. 

@KyleAMathews, what do you think about this approach? It there a better way to accomplish this?

**Comment by baba43** [comment] 2019-04-08 11:32
It's really sad that optimizing images using Gatsby results in so much overhead, unreadable und unreusable code. We've been so happy after being able to simply `import` images from everywhere with Webpack and other bundlers and now we're stuck with a solution that is so much worse.

While I totally understand that Gatsby has a specific way to handle data and stuff, we should not accept that the most basic things have to be done so complicated.

**Comment by KyleAMathews** [comment] 2019-04-08 15:52
@baba43 — no one is accepting anything :-P that's why this issue exists.

We'd appreciate your help fixing it. Gatsby is a community built project so needs strong developers like yourself to help improve things.

**Comment by guyinpv** [comment] 2019-04-13 00:22
It occurs to me that perhaps instead of having to duplicate and generate new queries for every possible variable used within <StaticQuery>, you could assemble all the possible variables into a list in the query itself. Kind of like `WHERE something IN [array,of,all,vars,found]`

Then the compiler just has to recognize the query as a set, and loop over it to generate each copy of the component. It only has to somehow know which component render belongs to which index of the returned set!

Just spitballing on that little idea.

**Comment by hiddentao** [comment] 2019-04-22 07:24
For dynamically querying images, I'm currently simply fetching all nodes and then filtering within the results:

```js
import safeGet from 'lodash.get'
import React, { useMemo } from "react"
import { graphql, useStaticQuery } from "gatsby"
import Img from "gatsby-image"

const Image = ({ src, ...props }) => {
  const data = useStaticQuery(graphql`
    query {
      allFile {
        nodes {
          relativePath
          childImageSharp {
            fluid(maxWidth: 300) {
              ...GatsbyImageSharpFluid_noBase64
            }
          }
        }
      }
    }
  `)

  const match = useMemo(() => (
    data.allFile.nodes.find(({ relativePath }) => src === relativePath)
  ), [ data, src ])

  return (
    <Img
      fluid={safeGet(match, 'childImageSharp.fluid')}
      Tag='div'
      {...props}
    />
  )
}

export default Image
```

**Comment by nextlevelshit** [comment] 2019-04-24 14:30
Regarding @hiddentao solution I had to transform it to fit into my setup. I was to lazy to investigate what's exactly the point; might be the environment, versions etc. But heres a apadapted solution. Thanks for your input @hiddentao:

```jsx
import React, { useMemo } from 'react'
import { graphql, useStaticQuery } from 'gatsby'
import Img from 'gatsby-image'

const Image = ({ src, ...props }) => {
  const data = useStaticQuery(graphql`
    query {
      allFile( filter: { internal: { mediaType: { regex: "images/" } } } ) {
        edges {
          node {
            relativePath
            childImageSharp {
              fluid(maxWidth: 300) {
                ...GatsbyImageSharpFluid
              }
            }
          }
        }
      }
    }
  `)

  const match = useMemo(() => (
    data.allFile.edges.find(({ node }) => src === node.relativePath)
  ), [ data, src ])

  return (
    <Img
      fluid={match.node.childImageSharp.fluid}
      {...props}
    />
  )
}

export default Image
```

**Comment by LeviSchuck** [comment] 2019-04-24 19:30
I was doing something similar as hiddentao and nextlevelshit 
I have since switched to pre-processing my markdown into an external graphql service to do more complicated mappings, the markdown makes references to entities via shortcodes (parsed with remark-shortcodes), which are then included as references in the graphql service.

Entity: 
```jsx
export default (document) => ({id, type}) => {
  switch (type) {
    case "image": {
      var images = document.referencedImages.filter(i => i.id === id);
      return (<Image data={images[0]} />)
    }
    default: {
      return (<div style={{color: "red"}}>Unhandled entity {type}:{id}</div>)
    }
  }
}
```

MarkdownDocument:
```jsx
 html = remark()
        .use(shortcodes, {startBlock: "{{>", endBlock: "<}}"})
        .use(remark2rehype, {
          handlers: {
            shortcode: shortcodeHandler, /* This converts {{> Entity type="image" id="123" <}} to <Entity type="image" id="123 /> in HAST */
          },
        })
        .use(rehype2react, {
          createElement: React.createElement,
          components: {
            /* This converts the <Entity .. /> in HAST to a react one proper
                But I close over the document so it can access the referencedImages */
            Entity: Entity(document),
          },
        })
        .processSync(content)
        .contents;
...
return (<div>{html}</div>)
```

Template:
```jsx
export default ({pageContext}) => {
    const thing = pageContext.thing;
    return (<Layout>
        <MDDocument document={thing.markdownDocument} full={true} />
    </Layout>)
}
```

gatsby-node

```js
exports.createPages = ({ graphql, actions }) => {
  const { createPage } = actions;
  return graphql(`{
    externalgraphql {
      relatedThingHere {
        partialId
        markdownDocument {
          content
          excerpt
          referencedImages {
            id
            url
          }
        }
      }
    }
  }`).then(result => {
    result.data.externalgraphql.relatedThingHere.forEach(thing => {
      createPage({
        path: `/related-things/${thing.partialId}`,
        component: path.resolve(`./src/templates/template.js`),
        context: {
          thing
        },
      })
    });
  });
};
```

and in gatsby-config

```js
{
      resolve: "gatsby-source-graphql",
      options: {
        // This type will contain remote schema Query type
        typeName: "ExternalQuery",
        // This is field under which it's accessible
        fieldName: "externalgraphql",
        // Url to query from
        url: "https://....",
      },
    },
```

**Comment by adamwade2384** [comment] 2019-05-04 13:17
I'm currently working through a related issue with the useStaticQuery hook. I want to pass a variable to the hook without pulling all nodes and filtering client side as I'm concerned with performance, and unsure of how many nodes will be added to Contentful by content editors. Has there been any progress on this feature?

**Comment by me4502** [comment] 2019-05-07 03:58
Is there any update on this? I'm working on adding translations to components, and being able to query for strings based on a language tag in the component would be ideal here, rather than passing the strings from the page into the component.

**Comment by landsman** [comment] 2019-05-17 17:22
I have exactly the same need

**Comment by denkhaus** [comment] 2019-05-17 18:55
the same here

**Comment by superfunkminister** [comment] 2019-05-20 22:40
+1

**Comment by hkr86** [comment] 2019-05-21 22:58
Fetching all nodes and then filter on client does not scale very well! I've done that and my builds is now several MB large!

**Comment by rexsohw** [comment] 2019-06-09 18:42
Hi folks, 
I was new to gatsby and is confused about the handling of static assets by gatsby.

1. Why don't we simply expose the `static/images` folder with url `/static/images` and simply use imageSharp to optimize all images? The use of gatsby-image has made it very non-trivial compared with just using relative path.

2. How can we expose the static folder so that we can access an image with directory path `static/images/test.jpg` through url `https://mydomain/static/images/test.jpg`? I couldn't find a lead in the official site.

**Comment by dandesz198** [comment] 2019-07-18 11:49
Hey! 👋 
Has there been any process regarding this issue? I see @sidharthachatterjee assigned it to himself, was there any improvement?
My use case would be the same as @lxibarra, @guyinpv, and others described. I'm trying to optimize images with `gatsby-images` but I don't want to define a GraphQL query for each picture.
I understand how and why the "download every image and then filter them" approach works, but it would kill the performance, wouldn't it? I'm pretty anxious about implementing it in prod because of those concerns.

**Comment by slorber** [comment] 2019-08-12 16:34
Couldn't we make the page context variables be available into the static queries? That would not solve all the problems but at least some of them.

**Comment by NHibiki** [comment] 2019-09-08 12:50
Any update on this issue? It is pretty annoying if we cannot dynamically query the data we want. If we just simply fetch all data and filter them locally, it is on the right opposite way where `graphql` wants to approach I think 😢.

Just provide some hints. Is it possible that we make a component named `DynamicQuery`, which is just like `StaticQuery` (as well as `useDynamicQuery`). So, we observe the input variable and do a graphql parsing + querying afterwards?

**Comment by jgierer12** [comment] 2019-09-08 13:49
Hey everyone, I see as much as anyone that this is an extremely important feature to have, but how about we keep the focus of this issue to productively finding possible solutions?

I think everyone who uses Gatsby sooner or later stumbles upon this, and I'm 100% sure that includes all of the core maintainers. Clearly the issue is not understanding *why* this feature is needed, but *how* we could implement it realistically. So I would suggest to refrain from asking about updates, or saying how badly you need it. That would keep the noise low and make sure everyone sees when there actually *is* an update on the implementation.

**Comment by cometkim** [comment] 2019-09-09 00:08
As long as it is a "static query" you shouldn't expect it to mix with runtime data.

I love the pattern of using static queries in individual components, but I often had to intersection (map, filter) it with the page context. (e.g i18n) Actually I think the "variables" means the page context.

Currently, page context can be used as a variable only for page queries. To make this to also be available for static queries, we can consider API like this: (inspired by Apollo Client)

```jsx
const data = useStaticQuery(graphql`
  query PreviewData($slug: String!, $currentLocale: String!) {
    pageContext {
      currentLocale @exports(as: "currentLocale")
      ...on BlogPost {
        # More specifically, we can add some type definition for each `createPage()` call
        slug @exports(as: "slug")
      }
    }
    markdownRemark(fields: { slug: { eq: $slug }}) {
      title
    }
    localizationMessage(locale: $currentLocale) {
      key
      value
    }
  }
`)
```

I'm not super familiar with gatsby core, but I'm doing similar (creating page context provider and intersect it with static query data) expect the gatsby compiler could automate with the proper syntax.

**Comment by tadeas22** [comment] 2019-09-17 15:26
I have an idea but i do not have a time to implement it. We can include some custom graphql client (what about Relay) and use them to query gatsby "storage" at the build time in component constructor. I do not know how to build the bridge between custom client and the gatsby "storage".

**Comment by jdesherlia** [comment] 2019-11-05 05:13
We are running into this issue as well, for more than just image fetching. I have a few page templates that are 'flexible' in nature, and have components that use nested references. In order for these to be rendered correctly, I need some way to fetch the specific element from a node that holds the data needed for a particular page (product pages with products that have referenced feature names, represented in a pricing table). The complexities of my CMS make this especially challenging because each reference simply gives me a uid that I need to go fetch dynamically. Anywho, I'm not sure that I'm smart enough to come up with a solution other than, "please support arguments for queries inside components", but would love to know how others are solving this, other than just loading everything and filtering it. Seems the concensus is, that's not scalable. Thanks everyone for the hard work and enlightening dialogue!

**Comment by bluehat974** [comment] 2019-11-17 14:49
Is it possible to do it another way?
The problem is how to inject variable in the AST process when we generate a page

I imagined something like this:
* Create *commonQuery* files in a query folder wich contains a root page query like function & allow to use fragment declared in other js component 
```
// src/queries/myCommonQuery.js

export const query = graphql`
  query productQuery($productId: Int!) {
    product(id: { eq: $productId}) {
      ...ProductInfo
      ...ProductPrice
      name
    }
  }
`

```

* Call them in createPages function... just before createPage call
* Inject the common queries in the context (or another field?) of createPage function
```
// gatsby-node.js
exports.createPages = ({ graphql createPage, createCommonQuery }) => {
  const { createPage } = actions
  ...
  const data = {...} // from a graphql or something else
  const myProductQuery = createCommonQuery({
    context: { productId: data.productId }
  }
  createPage({
    path: ...
    component: ...
    context: {
      ...
      myProductQuery // contains infos like path to get the query with useCommonQuery
    }
  })
  or
  createPage({
    path: ...
    component: ...
    context: {...}
    queries: {
      myProductQuery // contains infos like path to get the query with useCommonQuery
    }
  })
}
```

* Get the query with params using a hook 
```
// src/component/myComponent.js
const myProduct = useCommonQuery(pageContext.myProductQuery )
```

What do you think about this idea?

**Comment by arobida** [comment] 2019-11-22 05:43
I have not read all these  comments and this might be way over my head but would it be possible to create a small schema for static queries and check for differences at build time? Just wondering if that was possible any flexibility with static query would be much appreciated

**Comment by alvgaona** [comment] 2019-12-09 23:56
I think this would be really easy if `graphql` accepted interpolations like this (similar to `styled` in `styled-components`).  

```graphql
query TemplateBlogMarkdown($slug: String!){
   markdownRemark(fields: {slug: {eq: $slug}}) {
      html
      frontmatter {
        ${var}
        title
      }
    }
  }  
```

**Comment by vladar** [comment] 2019-12-12 17:42
We could explore Relay's [fragment arguments](https://relay.dev/docs/en/fragment-container#passing-arguments-to-a-fragment) for ideas.

**Comment by lourd** [comment] 2019-12-12 19:37
The critical challenge for this feature is not the API for inserting variables into the fragment, it's understanding at **build** time that the variables inserted are statically defined. The problem to be solved is the compiler/build system being able to trace variable definition and usage in some way. Typically that's either done through an understanding of the program execution graph or some type of annotation on the variables.

**Comment by kevinsullivan** [comment] 2020-01-02 04:36
I've been working head-down for about two weeks to learn Javascript, React, Gatsby, to to build a first-rate web site for my research program. I, too, just ran into this brick wall (about two hours ago), which brought me here. 

It's always a disappointment when, after weeks of effort, everything is working "perfectly", except for that one final remaining coup de grace, wherein one swaps out a stubbed constant file name for a variable to produce the dawning of Nirvana, only to hit a brick wall. Splat. Alas, I am now among the broken-hearted. 

That said, I'm sure I'm nowhere near as disappointed as the core developers, who have done a remarkable job with Gatsby, from the underlying conceptual foundations in pure functional programming to an obviously highly successful industrial implementation that, especially with the recent improvements with hooks, makes for a great programming experience.

As for solutions, I haven't thought too hard about this, but it sounds to me like a macro preprocessor is in our future, as a practical solution to the current problem. Preprocessor variables are inherently static. Think about #define in C. Using a separate pre-processing (macro expansion / generics / meta-programming) stage seems at first though that it's be much simpler than using some kind of wizardly JS program analyzer to distinguish what is effectively pre-program-execution-JS-code from just-plain-old-JS application-code. 

The variables need to be const. Their values need to be immutable. Computing these values before any program execution occurs is fine. E.g., there should be no problem with "filename = name ++ extension", because the reduction occurs before program execution starts.  Given that Javascript isn't compiled, and thus has not compiler stage preceding program execution, it's hard to see how one could readily integrate what amounts to a preprocessing stage into otherwise dynamic execution of the "real" program

Does it make sense to have a look at something like Builder for inspiration? It's in the JS ecosystem. It's supported by VS Code. It supports static meta-programming with JS code. Someone else has probably already suggested it, but I've only been looking at the issue for a few hours. I haven't had time to determine whether the idea has any merit. Here's Builder: https://www.npmjs.com/package/Builder.

**Comment by kevinsullivan** [comment] 2020-01-02 10:37
Following up on my previous comment: I think what we're seeing here is the need for what we might call "polymorphic React components," where polymorphic in this case means parametric polymorphism. This is a concept that is completely natural and elegant in the context of functional programming. So while it is clearly true that the question of the API for injecting variables into static GraphQL queries is trivial, the question of how one provides those value is anything but.
=
Here's my use case: I want a component that I invoke like this: <Code name="foo" lang="lean" />. The result is a nicely formatted code example pulled from a source code file on the file systems. I meant for this kind of function application to result in the execution of a GraphQL "file" query in which the strings, "foo" and "lean", are incorporated into the filter element to select the right file from the file system. The problem, as has been made clear, is that name and lang are runtime arguments. I'm proposing to understand them instead as type arguments (in a dependent type theory sense) of a now *polymorphic* Code component. The API question in play here then is, instead, how to write and use polymorphic components. Something like this might work as an API: <Code["foo","lean"] />, where [...] is the syntax for providing static (generic) arguments (here both of type string) to the Code "template component" (to use C++-like terminology). A "template preprocessor" would then statically instantiate the requisite GraphQL query behind the scenes.

**Comment by sidharthachatterjee** [comment] 2020-01-02 14:09
Wrote up a prototype that enables this. 

https://twitter.com/chatsidhartha/status/1212386859579428864?s=21
https://gist.github.com/sidharthachatterjee/e0c961fd92ce287dc020939037b915ce

Will open a PR with more details next week.

**Comment by riddla** [comment] 2020-01-30 09:27
@sidharthachatterjee, sounds great. Any news on this?

**Comment by funewik** [comment] 2020-02-03 13:41
Sounds REALLY great ! GG

**Comment by tadeas22** [comment] 2020-02-05 10:13
Why we need passing variables into static queries? Is it because we need specify which fields we need in Components. I hope that [this](https://gitlab.com/tadeas22/gatsby-dynamic-component-queries) can be helpfull.

Basic idea was to use Relay as graphql queries builder and gatsby as query executor but i was not able to implement it.

I know there is a lots of space improving the code but the concept is clear. In [./src/components/HeaderFragment.js](https://gitlab.com/tadeas22/gatsby-dynamic-component-queries/-/blob/master/src/components/HeaderFragment.js) you specify fields that the [./src/components/Header.js](https://gitlab.com/tadeas22/gatsby-dynamic-component-queries/-/blob/master/src/components/Header.js)  dynamic Component requires. In [./src/templates/blog-post.js:17](https://gitlab.com/tadeas22/gatsby-dynamic-component-queries/-/blob/master/src/templates/blog-post.js#L17) i am using Header component and in [./src/templates/BlogPostFragment.js](https://gitlab.com/tadeas22/gatsby-dynamic-component-queries/-/blob/master/src/templates/BlogPostFragment.js) exporting everything what blog-post.js need. In the [./gatsby-node.js](https://gitlab.com/tadeas22/gatsby-dynamic-component-queries/-/blob/master/gatsby-node.js#L41) i am executing dynamicaly created query.

**Comment by wojtekgalaj** [comment] 2020-02-14 11:24
Awesome work @sidharthachatterjee. Thanks a lot.

**Comment by pdeka** [comment] 2020-02-24 22:27
Any news on this feature?

**Comment by jnsrikanth** [comment] 2020-02-29 07:04
hi ,
is this feature available yet? why is this still open?

**Comment by sidharthachatterjee** [comment] 2020-04-04 15:47
We had an internal discussion around the useQuery prototype and this experiment brought to light reasons that led us to deciding _not_ ship this in Gatsby

- Losing the ability to statically compile GraphQL queries (which we can do now)
- Negative implications on build times and query result invalidation 
- An increase in overall complexity including a new mental model of what factors into query results as a result of allowing “runtime” variables are build time (and the ensuing confusion over what their values should be on the client side after hydration)

This issue is still open because we’re exploring alternative approaches to building an Img component that takes a url! Thank you for your positive comments, folks 🙂

**Comment by tony** [comment] 2020-04-04 16:12
@sidharthachatterjee Thank you for giving this the attention!  I wanted to comment and say thank you for being so courteous and conscientious in this thread!

If you have more details on the internal discussion and can expand upon it, that may be worth citing. If there was a blog post exploring the pros / cons / complexities of this.

> This issue is still open because we’re exploring alternative approaches to building an Img component that takes a url! Thank you for your positive comments, folks :slightly_smiling_face:

Looking forward to this!  I made good timing as this was exactly what I was looking into :)

**Comment by Vacilando** [comment] 2020-04-07 07:05
If there is a preference not to ship this with core, could it be packaged as a Gatsby plugin. Its usage will prove or disprove how much this functionality is needed, and people will undoubtedly contribute further improvements.

**Comment by jdahdah** [comment] 2020-04-24 13:12
Please consider that this functionality is not only needed for an `<Img />` component that takes a URL. Another example would be any component that grabs multilingual content from Contentful. Example: a dictionary of words used across the website, coming from Contentful, accessed through a generic `<Snippet />` component. I'm currently using the same hack suggested for `<Img />`. In general anything that requires I18n is leading to a lot of strange workarounds due to the lack of variables in non-page queries.

**Comment by Js-Brecht** [comment] 2020-04-24 17:55
@sidharthachatterjee Out of curiosity: are you able to comment about whether this will be reevaluated when React's `Suspense` is stable, and SSR compatible?

**Comment by danilobuerger** [comment] 2020-04-29 11:20
Maybe we could activate `experimentalFragmentVariables` in graphql to be able to use parameterized fragments at build time. That would at least lessen some of the pain in i18n.

**Comment by herecydev** [comment] 2020-05-01 10:57
Similar views to @jdahdah the following seems quite common from my experiences but is currently impossible:

```
  const { labels } = useStaticQuery(graphql`
    {
      labels(locale: {eq: "<mylocalevariable>"}) {
        heading
        buttonText
      }
    }
  `);
```
The only working solution I have at the moment is to query all labels as a page query and prop drill them (or use context). It massively erodes the value of colocated static queries.

**Comment by danilobuerger** [comment] 2020-05-01 10:59
@herecydev If your locale is known to the page (i.e. in the page context) you could use fragments instead. Fragments can access the arguments of the query they are in. Obviously not a pretty solution.

**Comment by LpmRaven** [comment] 2020-06-19 04:20
@hiddentao @nextlevelshit An alternate for when trying to build a dynamic images component is to attach the imageFile to the object on the data level, rather than when trying to render. Doing the match in the image component starts to throw errors when working on a project with a lot of images.

src/gatsby-api/create-resolvers/index.js
```javascript
const resolvers = {
    AWSAppSync_Product: {
        imageFile: {
            type: 'File',
            resolve: async (source, args, context, info) => {
                const node = await context.nodeModel.runQuery({
                    query: {
                        filter: {
                            Key: { eq: source.image1 }
                        }
                    },
                    type: 'S3Object',
                    firstOnly: true
                });

                if (node && node.imageFile) return node.imageFile;
            }
        },
    },
}

module.exports = {
    resolvers
}

```

gatsby-node.js
```javascript
exports.createResolvers = async ({ createResolvers }) => {
    createResolvers(resolvers)
}
```

src/components/image/index.js
```javascript
import React from 'react'
import Img from 'gatsby-image'

export const Image = props => {
  if (props.imageFile && props.imageFile.childImageSharp && props.imageFile.childImageSharp.fluid) {
    return <Img className={props.imgClassName} alt={props.alt} fluid={props.imageFile.childImageSharp.fluid} />;
  }
};
```

Then use it like:
```javascript
<Image
  imageFile={product.imageFile}
  alt=""
/>
```

`AWSAppSync_Product` is the type of node I am attaching my File to. (which can be found in the graphql playground on localhost). The resolve will match the `Key` of the `S3Object` with `image1` (which is a string) on the product. This allows me to directly use the product images without having to run a query inside the image component.

**Comment by saihaj** [comment] 2020-06-19 22:33
I am new to these things. So if I modify the string before sending it into the `useStaticQuery` hook then it should work (maybe?) Why does this not work? 

```
export const Image = path => {
  const query = `{
    allFile(filter: {sourceInstanceName: {eq: ${path}}}) {
      edges {
        node {
          childImageSharp {
            fluid {
              originalImg
            }
          }
        }
      }
    }
  }`
  const data = useStaticQuery( graphql( query ) )
  return data
}
```

**Closed** 2020-10-16 12:15 UTC
Labels: topic: GraphQL, topic: StaticQuery, type: feature or enhancement
