### ISSUE TITLE
Gatsby version 2.23.5 and above breaks local HTTPS development ...

### ISSUE THREAD

**Issue by TorrinLynn** [gatsbyjs/gatsby#25242] opened 2020-06-24 01:41 UTC
## Description

When running gatsby 2.23.5 or above, local HTTPS doesn't work. Rolling back to 2.23.4, HTTPS works properly.

### Steps to reproduce

gatsby develop --https -H \<host name\>
### Expected result

I should be able to navigate to https://\<host name\>:8000 or see the certificate by running 
```
openssl s_client -connect <host name>:8000
```

### Actual result

Navigating to https://\<host name\>:8000 in a browser shows:

```
This site can't provide a secure connection

<host name> sent an invalid response.

ERR_SSL_PROTOCOL_ERROR
```

Using openssl, returns 

```
4612808300:error:1400410B:SSL routines:CONNECT_CR_SRVR_HELLO:wrong version number:/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/libressl/libressl-47.120.1/libressl-2.8/ssl/ssl_pkt.c:386:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 5 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID: 
    Session-ID-ctx: 
    Master-Key: 
    Start Time: 1592962536
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
---
```

### Environment

  System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
    Shell: 5.0.16 - /bin/bash
  Binaries:
    Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
  npmPackages:
    gatsby: ^2.23.4 => 2.23.10
    gatsby-cli: 2.12.45 => 2.12.45
    gatsby-image: ^2.4.0 => 2.4.8
    gatsby-plugin-emotion: ^4.3.0 => 4.3.5
    gatsby-plugin-manifest: ^2.4.1 => 2.4.13
    gatsby-plugin-offline: ^3.2.0 => 3.2.12
    gatsby-plugin-react-helmet: ^3.3.0 => 3.3.5
    gatsby-plugin-sharp: ^2.6.0 => 2.6.13
    gatsby-plugin-tinacms: ^0.2.0 => 0.2.3
    gatsby-plugin-typography: ^2.5.0 => 2.5.5
    gatsby-source-filesystem: ^2.3.0 => 2.3.13
    gatsby-source-googlemaps-static: ^1.1.1 => 1.1.12
    gatsby-tinacms-git: ^0.5.1 => 0.5.5
    gatsby-tinacms-json: ^0.8.20 => 0.8.29
    gatsby-transformer-json: ^2.4.0 => 2.4.6
    gatsby-transformer-opencage-geocoder: ^1.0.0 => 1.0.0
    gatsby-transformer-sharp: ^2.5.0 => 2.5.6

**Comment by LekoArts** [comment] 2020-06-24 06:12
I think this is a duplicate of https://github.com/gatsbyjs/gatsby/issues/24272
We released a fix at `gatsby@2.23.11` so please try that version. If it doesn't work please comment on the linked issue. Thanks!

**Closed by LekoArts** 2020-06-24 06:12 UTC
Labels: type: bug
