### ISSUE TITLE
Error in function useStaticQuery in ./.cache/gatsby-browser-entry.js:77

### ISSUE THREAD

**Issue by luhc228** [gatsbyjs/gatsby#32218] opened 2021-07-04 11:40 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Error in function useStaticQuery in ./.cache/gatsby-browser-entry.js:77
The result of this StaticQuery could not be fetched. This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues

### Reproduction Link

https://github.com/luhc228/aitechlab-site/pull/2

### Steps to Reproduce

1. Clone my repo (https://github.com/luhc228/aitechlab-site) and switch to the feat/home branch
2. run the script `npm run start`

### Expected Result

work normally

### Actual Result

has error:
Error in function useStaticQuery in ./.cache/gatsby-browser-entry.js:77
The result of this StaticQuery could not be fetched. This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues

### Environment

```shell
macos 11.4
node 14.6.0
```

**Comment by LekoArts** [comment] 2021-07-06 05:58
Duplicate of https://github.com/gatsbyjs/gatsby/issues/26563 - please post your full reproduction there. Thanks!

**Closed by LekoArts** 2021-07-06 05:58 UTC
Labels: type: bug
