### ISSUE TITLE
How to fix: Gatsby build results in css files being merged, which disrupts local styling on specific Gatsby pages

### ISSUE THREAD

**Issue by mfuller22** [gatsbyjs/gatsby#14888] opened 2019-06-18 21:42 UTC
## Description

I'm converting my Gatsby site from development to an actual build. I've been able to get everything to work in "develop" mode, specifically using a separate css stylesheet for one of my pages.

When I run gatsby build and then gatsby serve, the result is the css styles for the specific page being blended into (or overwriting) the other pages.

### Steps to reproduce

Run "gatsby develop" on the project below. See that the styles of the homepage and posts are different from the styles of the DrumKit (http://localhost:8000/Projects/DrumKit/Javascript30/)

Then run "gatsby build" and "gatsby serve" on the same project. See that now the homepage and post styles are the same as the DrumKit for some reason.

https://github.com/mfuller22/FullerStackProgramming

### Expected result

Ideally, the build looks the same as the develop mode, and local styles used for specific pages remain isolated from the rest of the site.

### Actual result

While tough to distinguish, it seems like the "build" stylesheet has both of the css files merged together. I've deduced this by simply looking for the font-family: sans-serif; line from the "develop" stylesheet as well as the .keys styling from the DrumKit-specific stylesheet. Both show up in the build version, but not in the develop version, leading me to believe they stay separate in develop mode as intended. But when building the site, for some reason they're getting merged.

This results in the homepage being styled with the styles from the DrumKit instead of the default style from layout.js.

Is there any way around this?

### Environment

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-4940MX CPU @ 3.10GHz
  Binaries:
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.3
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.7.1 => 2.7.1 
    gatsby-image: ^2.0.34 => 2.0.34 
    gatsby-plugin-compile-es6-packages: ^1.1.0 => 1.1.0 
    gatsby-plugin-eslint: ^2.0.5 => 2.0.5 
    gatsby-plugin-flow: ^1.0.5 => 1.0.5 
    gatsby-plugin-manifest: ^2.0.22 => 2.0.22 
    gatsby-plugin-offline: ^2.0.24 => 2.0.24 
    gatsby-plugin-react-helmet: ^3.0.8 => 3.0.8 
    gatsby-plugin-sharp: ^2.1.1 => 2.1.1 
    gatsby-plugin-styled-components: ^3.0.7 => 3.0.7 
    gatsby-remark-embed-snippet: ^3.2.4 => 3.2.4 
    gatsby-remark-prismjs: ^3.2.6 => 3.2.6 
    gatsby-source-filesystem: ^2.0.23 => 2.0.23 
    gatsby-transformer-remark: ^2.3.2 => 2.3.2 
    gatsby-transformer-sharp: ^2.1.17 => 2.1.17

**Comment by freiksenet** [comment] 2019-06-20 11:48
Hi @mfuller22!

I'm afraid I can't reproduce, I have identical results in both serve and develop. Could you try cleaning your public folder of the build artifacts? Also you could try upgrading your version of Gatsby.

Hope this helps!

**Comment by wardpeet** [comment] 2019-09-04 09:06
Hi,

This is sadly not possible due to the nature of CSS. I suggest moving to cssmodules or css-in-js to fix this problem.

There are a variety of issues open about this topic. Sadly I can't find the right one to point you to it.

Regards,
Ward

**Closed by wardpeet** 2019-09-04 09:06 UTC
Labels: status: awaiting author response, status: needs reproduction, type: question or discussion
