### ISSUE TITLE
[gatsby-plugin-mdx] markdownNode.id === "fakeNodeIdMDXFileABugIfYouSeeThis"

### ISSUE THREAD

**Issue by flogy** [gatsbyjs/gatsby#21818] opened 2020-02-28 09:55 UTC
## Description

The `markdownNode` passed into a local `gatsbyRemarkPlugin` has set the ID to `fakeNodeIdMDXFileABugIfYouSeeThis` - so that's why I'm filing this bug here 😉 Also, linking a new node to the `markdownNode` is not possible, probably because of this.

### Steps to reproduce

▶️ **Minimal Reproduction project:** https://github.com/flogy/gatsby-remark-plugins-caching-issue (most relevant is the `./plugins/some-sub-plugin/index.js` file)

- Start the project and see the `markdownNode.id` in the console log output: `Creating a new test node and link it to parent node: fakeNodeIdMDXFileABugIfYouSeeThis`. 
- Open [this query in GraphiQL](http://localhost:8000/___graphql?query=%7B%0A%20%20test%20%7B%0A%20%20%20%20parent%20%7B%0A%20%20%20%20%20%20id%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A), execute it and see that the parent ID is `null`.

### Expected result

The ID of `markdownNode` should be a real ID.

The newly created node should be linked to the passed in `Mdx` node as a child. It's parent ID should equal the ID of the `Mdx` node.

### Actual result

The ID of `markdownNode` equals `fakeNodeIdMDXFileABugIfYouSeeThis`.

The newly created node is not linked to the passed in `Mdx` node. It's parent ID equals `null`.

### Environment

```
  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Binaries:
    Node: 10.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.5.1 - C:\Program Files\Python35\python.EXE
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.19.7 => 2.19.7 
    gatsby-plugin-mdx: ^1.0.74 => 1.0.74 
```

Thanks in advance!

**Comment by pvdz** [comment] 2020-02-28 10:52
Thanks for your repro. That's very helpful :) We'll look into why this is happening and hopefully fix it soon.

**Comment by flogy** [comment] 2020-02-28 11:02
Awesome, thank you! :)

**Comment by pvdz** [comment] 2020-02-28 11:24
Looks like this an old bug (if it is a bug) as the plugin receives the same id with `gatsby-plugin-mdx@1.0.40` (the `createNode` api is new so you have to log the args, but still). Guessing this is an artifact of plugins but will hand off to somebody who's better into this.

**Comment by flogy** [comment] 2020-03-23 07:05
Hi @pvdz and @johno 
Thanks for taking over the issue. Just wanted to ask if there is any update and I could help in any way? Sorry for the hurry but my other issue related to this is going stale: https://github.com/gatsbyjs/gatsby/issues/21804 😕

**Comment by cristiano-belloni** [comment] 2020-05-22 15:51
+1, happens for me too with `"gatsby-plugin-mdx": "^1.2.11"`

**Comment by flogy** [comment] 2021-03-07 17:11
I don't think this was resolved yet. Please keep it open for now.

**Comment by flogy** [comment] 2021-03-28 12:44
Probably still an issue...

**Comment by cristiano-belloni** [comment] 2021-06-18 08:34
Hi, this is still an issue.

**Comment by cristiano-belloni** [comment] 2021-07-08 21:49
Hi bot, this is still an issue.

**Comment by cristiano-belloni** [comment] 2021-07-29 08:45
Hi bot, this is still an issue.

**Comment by cristiano-belloni** [comment] 2021-08-18 12:22
Hi bot, guess what? This is still an issue.

**Comment by cristiano-belloni** [comment] 2021-09-08 12:12
Hiya!

This issue is still a problem. Spooky problem. 👻

**Comment by cristiano-belloni** [comment] 2021-09-29 08:44
Still an issue, bot.

**Comment by raae** [comment] 2022-04-13 05:52
I created a repo to reproduce another bug and encountered `fakeNodeIdMDXFileABugIfYouSeeThis`:

Repo: https://github.com/raae/gatsby-mdx-cache-bug/blob/main/plugins/cache-bug/index.js

<img width="770" alt="CleanShot 2022-04-13 at 07 45 26@2x" src="https://user-images.githubusercontent.com/478531/163109230-c7707411-91f2-4f36-981a-8d184893996b.png">

**Comment by LekoArts** [comment] 2022-08-11 05:13
Hi!

We merged https://github.com/gatsbyjs/gatsby/pull/35650 which means that a new major version of `gatsby-plugin-mdx` will be released on August 16. You can already try it out by installing `gatsby-plugin-mdx@next` & `gatsby@next`.

The `fakeNodeIdMDXFileABugIfYouSeeThis` is longer there. Please upgrade and try again. Thanks!

**Closed by LekoArts** 2022-08-11 05:13 UTC
Labels: type: bug, status: confirmed, topic: remark/mdx
