### ISSUE TITLE
Gatsby develop stuck on Windows 10

### ISSUE THREAD

**Issue by mimiza** [gatsbyjs/gatsby#25216] opened 2020-06-23 02:01 UTC
Hello guys. I used Solus OS (linux) and gatsby worked just fine without any problem. Now I'm using Windows 10 (x64). Everything I type "gatsby develop" the first time after turning on my computer, it stucks right here:
```
success write out requires - 0.116s
success write out redirect data - 0.016s
⠋ onPostBootstrap
⠋ Build manifest and related icons
```
And I have to Ctrl+C and then "gatsby develop" again and it works. Always stucks at the first time.

**Comment by madalynrose** [comment] 2020-06-23 15:39
Hi @mimiza!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look. 

Additionally, it would be helpful to know more about your environment (e.g. which terminal application you are using, which editor, etc.) in order to help locate the bug.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by mimiza** [comment] 2020-06-24 01:56
@madalynrose Hi there!
Please clone this repo https://github.com/mimiza/mimiza.com
I'm using Windows 10 (x64), my editor is VSCode.
Thank you so much for your response.

**Comment by wardpeet** [comment] 2020-06-24 11:07
Hey @mimiza.

I could reproduce this one but I don't really know the reason why this happens. Maybe it's the svg 🤷 
When I add console.log inside the plugin, everything works as expected.

@moonmeister do you know of any race conditions that can occur here?

**Comment by moonmeister** [comment] 2020-06-29 16:40
I'm not aware of anything off hand but possible. Maybe file system related too. If I get a chance I'll do some testing now that I have a windows machine.

**Comment by mimiza** [comment] 2020-07-07 01:55
@wardpeet @moonmeister thank you for supporting. But if it was about svg, why would Linux work?

**Comment by moonmeister** [comment] 2020-07-08 22:48
Okay, this is silly, but it's happened twice to me. When it hangs, hit "enter" (you may have to wait a bit?). Yarn and gatsby dev "froze"on me, it seems to be working in the background, but not updating the terminal. Hitting "enter" makes it spit out the missing text and continue to work. Let me know if this works for you.

**Comment by MeilleurExcellentOptimal** [comment] 2020-07-21 06:49
I have exactly the same issue as @mimiza.

**Comment by moonmeister** [comment] 2020-07-21 16:19
SInce my initial testing I've been doing more windows dev and run into this issue as well. I'm not convinced the bug is in `gatsby-source-manifest` but that is where it seems to pause consistently. While subsequent runs seem slightly more consistent for me, it seems to hang randomly.

**Comment by ediblecode** [comment] 2020-08-03 13:31
I've also had this issue, but via `gatsby build`, not just via `gatsby develop` as the issue says, just in case the 'develop' bit is a red herring for someone looking into this. The workaround of pressing a key to 'flush' the console doesn't work in my case I'm using a [vscode task](https://github.com/nice-digital/cks-gatsby/blob/3fe50d4a7ae14942955939280cdf63cf71b3c65a/.vscode/tasks.json#L78-L93).

**Comment by dkocich** [comment] 2020-08-28 05:43
This issue happened to me while I used default starter, removed `gatsby-icon.png` from the project, used my own icon but did not change it in `gatsby-config.js` (settings of `... resolve: gatsby-plugin-manifest, options { src: 'src/images/myNewIcon-icon.jpg'}...`)

**Comment by EAdeveloper** [comment] 2020-09-09 21:20
> Hello guys. I used Solus OS (linux) and gatsby worked just fine without any problem. Now I'm using Windows 10 (x64). Everything I type "gatsby develop" the first time after turning on my computer, it stucks right here:
> 
> ```
> success write out requires - 0.116s
> success write out redirect data - 0.016s
> ⠋ onPostBootstrap
> ⠋ Build manifest and related icons
> ```
> 
> And I have to Ctrl+C and then "gatsby develop" again and it works. Always stucks at the first time.

### My solution was;

1. Update the gatsby-cli and nodejs if possible.
2. Remove the node_modules, .cache, the public folder and the yarn.lock or package-lock.json files.

3. I believe the **sharp** or the **pngquant** libraries need some processing power to compress your images and icons, to free some resources you could kills some apps or processes running on your machine using Task manager on Windows OS, for example Google Chrome or any other apps consuming resources on your CPU and Memory then try to run **yarn install** and **gatsby develop** and it did worked for me.

**Comment by jordan-git** [comment] 2020-09-26 19:45
This is happening to me now too. [Repository](https://github.com/jordan-git/jordan-git.github.io). It started happening a little before my current commit, but I was able to get passed it by running the command again so I kept working. My page seems to have gotten slower and to the point where the JS breaks with my most recent addition so I'm going to have to look in to if that is something I caused but I'm too tired to do that tonight.

**Comment by jordan-git** [comment] 2020-09-26 20:14
It seems the problem was my Node not being up to date. I was able to develop my site fine up until some point where this started happening. Updating Node fixed that issue. I'm still having the issue of my application being dead when I deploy a build.

**Comment by eliooses-zondax** [comment] 2020-12-11 00:09
I have been dealing with this issue from day one of using Gatsby. No matter what starter or theme I use, the same thing always happens to me.

Any solution?

**Comment by janmauler** [comment] 2020-12-29 19:17
> I have been dealing with this issue from day one of using Gatsby. No matter what starter or theme I use, the same thing always happens to me.
> 
> Any solution?

Exactly the same for me. Would also like some solution for this (although it doesn't seem mission critical at this point as this only happens on my development Windows machine and not in my CI, so my production release cycle is not affected in any way).

**Comment by OddBlueDog** [comment] 2021-01-05 22:15
Same issue here, I have been pressing ctrl + c. On Windows 10, gatsby-cli 2.17.0, and node 14.15.3

**Comment by moonmeister** [comment] 2021-01-05 22:19
Latest Gatsby(v2.30) updated to ink@v3. I'm curios if anyone could update and test to see if this has resolved the issue.

**Comment by OddBlueDog** [comment] 2021-01-05 23:06
> Latest Gatsby(v2.30) updated to ink@v3. I'm curios if anyone could update and test to see if this has resolved the issue.

I'll give it a test over the next few days. I have updated all my packages now and done a gatsby clean.

**Comment by janmauler** [comment] 2021-01-06 06:21
I can confirm that I no longer see this issue happening after upgrading to the latest version. Thank you!

**Comment by mahmoudmiz** [comment] 2021-01-06 23:28
same here

**Comment by henrik-m** [comment] 2021-01-07 12:36
@moonmeister Looked good yesterday after updating to gatsby@2.30.1. But today I've had a change in ```gatsby-config.js``` and am experiencing the issue again unfortunately.

```gatsby develop``` stalls on ```onPostBootstrap/Build manifest and related icons``` in first build after config-change. Killing the process and re-issuing the command runs successfully to the end. Which is how it's always been for me.

**Comment by moonmeister** [comment] 2021-01-07 13:44
You mind sharing what you changed? and in you experience does it matter 
what you change in config, or is it anything?


Alex

**Comment by henrik-m** [comment] 2021-01-07 14:48
I added a require to another (dependency-less) JS file containing additional config variables. I used them to change a few options for the plugin ```gatsby-plugin-google-marketing-platform```. I would be suprised if the particular change mattered though.

I undid and redid the changes, did a production build in between, but have not been able to reproduce the issue yet. It seems to have been a "first build of the day" thing so far. So the situation has definitely improved. I was getting this a lot more often in the past.

**Comment by artdiev** [comment] 2021-01-13 20:23
I am also still getting the issue.
Running on node 15.5 & Windows 10 20H2
Gatsby 2.30.1

**Comment by OddBlueDog** [comment] 2021-01-20 19:26
I think it's better, sometimes you do just have to wait a bit for the re-building to happen around 10s for minor CSS changes.

**Comment by kimbaudi** [comment] 2021-02-06 00:23
I've been facing the same issue on Windows (stuck on onPostBootstrap & Build manifest and related icons), but largely ignore it because I just hit Ctrl+C and run it again (which works all the time). I am using an svg instead of a png for the icon. It is not a big deal, but kinda annoying since I have to hit Ctrl+C to get it to work in dev.

```
$  yarn start
yarn run v1.22.10
$ gatsby clean
info Deleting .cache, public, C:\dev\paulkode.com\node_modules\.cache\babel-loader, C:\dev\paulkode.com\node_modules\.cache\terser-webpack-plugin
info Successfully deleted directories

$ gatsby develop --host=0.0.0.0 --port=4242 --open
success open and validate gatsby-configs - 0.074s
success load plugins - 0.679s
success onPreInit - 0.037s
success initialize cache - 0.008s
success copy gatsby files - 0.132s
success onPreBootstrap - 0.033s
success createSchemaCustomization - 0.003s
success Checking for changed pages - 0.002s
success source and transform nodes - 0.066s
success building schema - 0.216s
info Total nodes: 30, SitePage nodes: 1 (use --verbose for breakdown)
success createPages - 0.004s
success Checking for changed pages - 0.001s
success createPagesStatefully - 0.158s
success update schema - 0.022s
success write out redirect data - 0.002s
⠇ onPostBootstrap
⠇ Build manifest and related icons
```

**Comment by fayzanx** [comment] 2021-03-12 19:22
I am also facing the same issue when trying to run `gatsby develop` on Windows 10 using node v12.16.3, gatsby-cli v2.19.2 and gatsby v2.32.11

I've tried almost all of the fixes suggested above, but still facing the issue.

Also, in my case the process is stuck at `onPreBootstrap`.

**Comment by eightbit** [comment] 2021-03-19 15:44
Same issue here - develop fails the first time, then runs after ctrl-c.
Subscribing to this thread. Happy to help if you need info about my config or versions.
Thx.

**Comment by jacobabiola** [comment] 2021-03-20 15:19
i am have in the same issue 

```
C:\Users\user\codes\startr-homepage>gatsby develop
success open and validate gatsby-configs - 3.508s
success load plugins - 82.187s
success onPreInit - 0.984s
success initialize cache - 0.705s
success copy gatsby files - 8.100s
success onPreBootstrap - 0.675s
success createSchemaCustomization - 0.081s
success Checking for changed pages - 0.013s
success source and transform nodes - 2.290s
success building schema - 4.693s
info Total nodes: 74, SitePage nodes: 1 (use --verbose for breakdown)
success createPages - 0.024s
success Checking for changed pages - 0.019s
success createPagesStatefully - 1.485s
success update schema - 0.701s
success write out redirect data - 0.016s
⠋ onPostBootstrap
⠏ Build manifest and related icons
```

**Comment by MartSurv** [comment] 2021-05-02 14:34
> > Hello guys. I used Solus OS (linux) and gatsby worked just fine without any problem. Now I'm using Windows 10 (x64). Everything I type "gatsby develop" the first time after turning on my computer, it stucks right here:
> > ```
> > success write out requires - 0.116s
> > success write out redirect data - 0.016s
> > ⠋ onPostBootstrap
> > ⠋ Build manifest and related icons
> > ```
> > 
> > 
> > And I have to Ctrl+C and then "gatsby develop" again and it works. Always stucks at the first time.
> 
> ### My solution was;
> 1. Update the gatsby-cli and nodejs if possible.
> 2. Remove the node_modules, .cache, the public folder and the yarn.lock or package-lock.json files.
> 3. I believe the **sharp** or the **pngquant** libraries need some processing power to compress your images and icons, to free some resources you could kills some apps or processes running on your machine using Task manager on Windows OS, for example Google Chrome or any other apps consuming resources on your CPU and Memory then try to run **yarn install** and **gatsby develop** and it did worked for me.

This solution helped me also. I updated gatsby-cli, removed the node_modules, .cache and public folders and the package-lock.json file. After that I ran a clean npm install.

**Comment by ownchoice** [comment] 2021-05-20 00:36
I'm having the same problem on Windows 10, but it doesn't always happen. Sometimes it does, sometimes it doesn't.
Even deleting `.cache`, `node_modules`, `public` and `package-lock.json` doesn't seem to fix it or to make it consistent.

But what does fix it is commenting out this code block of the `gatsby-config.js` file:
```
{
  resolve: 'gatsby-plugin-manifest',
  options: {
    name: config.siteTitle,
    short_name: config.siteTitleShort,
    description: config.siteDescription,
    start_url: validatedPathPrefix,
    background_color: config.backgroundColor,
    theme_color: config.themeColor,
    display: 'minimal-ui',
    icon: 'static/favicon.svg'
  }
},
```

**Comment by alex1a** [comment] 2021-08-03 03:58
## Steps to reproduce

1. Installed the package [gatsby-source-gitlab-api](https://github.com/28development/gatsby-source-gitlab-api)
2. Added it to my **gatsby-config.js** file
3. Run `gatsby develop`

## Result

```
...

success initialize cache - 0.040s
success copy gatsby files - 0.156s
success Compiling Gatsby Functions - 0.400s
success onPreBootstrap - 0.435s
success createSchemaCustomization - 0.083s
⠇ source and transform nodes
```

## Environment

* **OS**: Windows 10 x64 20H2 19042.1100
* **Shell**: CMD 10.0.19042.1110
* **Node**: 14.15.1
* **Yarn**: 1.22.5

yarn.lock

```
...

gatsby-source-gitlab-api@^1.0.5:
  version "1.0.5"
  resolved "https://registry.yarnpkg.com/gatsby-source-gitlab-api/-/gatsby-source-gitlab-api-1.0.5.tgz#0734ab542c235b149740b42e766f34e803afddfb"
  integrity sha512-vVs4SvkGgY2xaJZWsfaxUy33vRcOArhJtdHcei2i8tHTyleRdr8OYr8nVbTG9Yg829uHSFySC5x/VBEfAPNQcg==
  dependencies:
    "@gitbeaker/browser" "^28.0.4"
    "@gitbeaker/cli" "^28.0.4"
    "@gitbeaker/node" "^28.0.4"

...
```

package.json

```
...

  "dependencies": {
    "gatsby": "^3.8.0",
    "gatsby-image": "^3.8.0",
    "gatsby-plugin-google-analytics": "^3.8.0",
    "gatsby-plugin-manifest": "^3.8.0",
    "gatsby-plugin-offline": "^4.8.0",
    "gatsby-plugin-react-helmet": "^4.8.0",
    "gatsby-plugin-sharp": "^3.8.0",
    "gatsby-plugin-styled-components": "^4.8.0",
    "gatsby-remark-copy-linked-files": "^4.5.0",
    "gatsby-remark-images": "^5.5.0",
    "gatsby-remark-prismjs": "^5.5.0",
    "gatsby-remark-responsive-iframe": "^4.5.0",
    "gatsby-remark-smartypants": "^4.5.0",
    "gatsby-source-filesystem": "^3.8.0",
    "gatsby-source-github-api": "^1.0.0",
    "gatsby-source-gitlab-api": "^1.0.5",
    "gatsby-transformer-remark": "^4.5.0",
    "gatsby-transformer-sharp": "^3.8.0",
    "node-sass": "^6.0.1",
    "prismjs": "^1.20.0",
    "prop-types": "^15.7.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-github-btn": "^1.2.0",
    "react-github-button": "^0.1.11",
    "react-helmet": "^6.1.0",
    "react-icons": "^4.2.0",
    "sharp": "^0.28.3",
    "styled-components": "^5.1.1"
  },
  "devDependencies": {
    "prettier": "2.3.2"
  },
  "resolutions": {
    "graphql": "^15.4.0",
    "graphql-compose": "^9.0.2",
    "webpack": "^5.24.2"
  },

...

```

## What I've tried

* `gatsby clean`
* Deleting .cache dir
* Deleting public dir
* Deleting node_modules dir
* Deleting yarn.lock file
* Reinstalling packages
* Resizing my terminal window (? weirdly something that seemed to work for some)

References: [@28development/gatsby-source-gitlab-api#1](https://github.com/28development/gatsby-source-gitlab-api/issues/1), [@gatsbyjs/gatsby#17131](https://github.com/gatsbyjs/gatsby/issues/17131), [@gatsbyjs/gatsby#25216](https://github.com/gatsbyjs/gatsby/issues/25216), [@gatsbyjs/gatsby#28632](https://github.com/gatsbyjs/gatsby/issues/28632)

**Comment by ownchoice** [comment] 2021-09-26 16:15
This issue is driving me crazy, two thirds of my attempts to do Gatsby build o develop end ups stuck just like this.

Commenting out the SVG icon for the manifest plugin fixes this issue, but I need it for production builds.

**Comment by l3szcz** [comment] 2021-10-06 10:33
For me this workaround from issue #31878 works. I was hoping it was fixed in the latest version of Gatsby, but the problem just moved from production build to development build.

```js
// gatsby-node.js
// TODO: temporary workaround for https://github.com/gatsbyjs/gatsby/issues/31878
exports.onCreateWebpackConfig = ({ actions, plugins, stage, getConfig }) => {
  // override config only during production JS & CSS build
  if (stage === "build-javascript") {
    // get current webpack config
    const config = getConfig();

    const options = {
      minimizerOptions: {
        preset: [
          `default`,
          {
            svgo: {
              full: true,
              plugins: [
                // potentially destructive plugins removed - see https://github.com/gatsbyjs/gatsby/issues/15629
                // use correct config format and remove plugins requiring specific params - see https://github.com/gatsbyjs/gatsby/issues/31619
                `removeUselessDefs`,
                `cleanupAttrs`,
                `cleanupEnableBackground`,
                `cleanupIDs`,
                `cleanupListOfValues`,
                `cleanupNumericValues`,
                `collapseGroups`,
                `convertColors`,
                `convertPathData`,
                `convertStyleToAttrs`,
                `convertTransform`,
                `inlineStyles`,
                `mergePaths`,
                `minifyStyles`,
                `moveElemsAttrsToGroup`,
                `moveGroupAttrsToElems`,
                `prefixIds`,
                `removeAttrs`,
                `removeComments`,
                `removeDesc`,
                // `removeDimensions`,
                `removeDoctype`,
                `removeEditorsNSData`,
                `removeEmptyAttrs`,
                `removeEmptyContainers`,
                `removeEmptyText`,
                `removeHiddenElems`,
                `removeMetadata`,
                `removeNonInheritableGroupAttrs`,
                `removeOffCanvasPaths`,
                `removeRasterImages`,
                `removeScriptElement`,
                `removeStyleElement`,
                `removeTitle`,
                `removeUnknownsAndDefaults`,
                `removeUnusedNS`,
                `removeUselessStrokeAndFill`,
                `removeXMLProcInst`,
                `reusePaths`,
                `sortAttrs`,
              ],
            },
          },
        ],
      },
    };
    // find CSS minimizer
    const minifyCssIndex = config.optimization.minimizer.findIndex(
      (minimizer) => minimizer.constructor.name === "CssMinimizerPlugin"
    );
    // if found, overwrite existing CSS minimizer with the new one
    if (minifyCssIndex > -1) {
      config.optimization.minimizer[minifyCssIndex] =
        plugins.minifyCss(options);
    }
    // replace webpack config with the modified object
    actions.replaceWebpackConfig(config);
  }
};

```

**Closed** 2022-01-10 08:53 UTC
Labels: type: bug, status: confirmed, topic: plugins-PWA
