### ISSUE TITLE
Gatsby Build Breaks SCSS Export Variables

### ISSUE THREAD

**Issue by jasonbiondo** [gatsbyjs/gatsby#29303] opened 2021-02-02 18:04 UTC
I have a SCSS variables file which has:

```
$brandColorAnchor: #14314e;

:export {
  brandColorHighlight: $brandColorHighlight;
}
```
And then in my JavaScript file I am passing these variables to Material UI, but the variables are seem to be coming in undefined. The build throws an error saying that each color in material UI needs main defined.

```
import { createMuiTheme } from "@material-ui/core/styles"
import Variables from "../styles/variables.scss"

const Theme = createMuiTheme({
  palette: {
    primary: {
      main: Variables.brandColorHighlight
    }
  }
})

export default Theme
```
This error only happens on gatsby build and not on gatsby develop.

**Comment by LekoArts** [comment] 2021-02-03 09:41
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by jasonbiondo** [comment] 2021-02-03 12:11
@LekoArts your links aren't working and the above code is a trimmed down minimal explanation of the issue.

**Comment by LekoArts** [comment] 2021-02-15 14:10
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-02-15 14:10 UTC
Labels: status: needs reproduction, type: bug
