### ISSUE TITLE
gatsby-source-contentful preview api being rate limited.

### ISSUE THREAD

**Issue by dolphub** [gatsbyjs/gatsby#23663] opened 2020-05-01 00:14 UTC
## Description

When trying to configure gatsby local development to use the preview API key I'm receiving rate limiting errors from contentful indefinitely

### Steps to reproduce
The Contentful space being used is objectively not small, not sure if this may have an effect on it.

my `gatsby-source-contentful` config is as such:

```
const contentfulConfig = {
  spaceId: process.env.CONTENTFUL_SPACE_ID,
  accessToken: process.env.CONTENTFUL_ACCESS_TOKEN,
  host: process.env.CONTENTFUL_HOST,
  downloadLocal: true,
};
```
with the access token being correctly set to the preview token and `CONTENTFUL_HOST=preview.contentful.com`

### Expected result

Should be able to download unpublished content locally to use for development.

### Actual result
```yarn start
yarn run v1.19.2
warning ../package.json: No license field
$ env-cmd -f .env npm run develop

> gatsby-implementation@1.0.0 develop 
> gatsby develop

success open and validate gatsby-configs - 0.019s
success load plugins - 0.172s
success onPreInit - 0.007s
success initialize cache - 0.014s
success copy gatsby files - 0.037s
success onPreBootstrap - 0.008s
success createSchemaCustomization - 0.003s
Starting to fetch data from Contentful
Fetching default locale
default locale is : en-US
[warning] Rate limit error occurred. Waiting for 1572 ms before retrying...
[warning] Rate limit error occurred. Waiting for 1514 ms before retrying...
[warning] Rate limit error occurred. Waiting for 1546 ms before retrying...
```

*Updated*
We're seeing rate limiting inside of the gatsby cloud integration platform as well.
These are some log messages from the gatsby-cloud preview builds triggered by contentful unpublished changes
```
17:16:44 PM: warning The asset with id: 3br3Gfc57O8WwO0SW246WG, contains no file.
17:16:44 PM: warning The asset with id: 3br3Gfc57O8WwO0SW246WG, contains no file.
17:16:44 PM: success createSchemaCustomization - 0.123s
17:16:44 PM: warning The asset with id: 5hjP3OaaW4e2aMIgAW2UkW, contains no file.
17:16:44 PM: warning The asset with id: 3br3Gfc57O8WwO0SW246WG, contains no file.
17:16:44 PM: warning The asset with id: 3br3Gfc57O8WwO0SW246WG, contains no file.
17:16:45 PM: Starting to fetch data from Contentful
17:16:45 PM: Fetching default locale
17:16:45 PM: error (node:27127) Warning: Label 'Fetch Contentful data' already exists for console.time()
17:16:45 PM: Starting to fetch data from Contentful
17:16:45 PM: Fetching default locale
17:16:45 PM: error (node:27127) Warning: Label 'Fetch Contentful data' already exists for console.time()
17:16:45 PM: [warning] Rate limit error occurred. Waiting for 1685 ms before retrying...
17:16:45 PM: [warning] Rate limit error occurred. Waiting for 1637 ms before retrying...
17:16:45 PM: [warning] Rate limit error occurred. Waiting for 1607 ms before retrying...
17:16:53 PM: default locale is : en-US
17:16:53 PM: default locale is : en-US
17:16:53 PM: default locale is : en-US
17:16:53 PM: [warning] Rate limit error occurred. Waiting for 1567 ms before retrying...
17:16:53 PM: [warning] Rate limit error occurred. Waiting for 1517 ms before retrying...
17:16:53 PM: [warning] Rate limit error occurred. Waiting for 1607 ms before retrying...
17:17:03 PM: [warning] Rate limit error occurred. Waiting for 1671 ms before retrying...
17:17:03 PM: [warning] Rate limit error occurred. Waiting for 1535 ms before retrying...
```
This process never finishes as far as I can tell, making the preview functionality for large spaces unusable.

I recognize this is a Contentful rate limit, but does anyone have any workarounds for this? The app that's using data from contentful is using a microscopic amount of data from the Contentful space in comparison to what's actually there, why does it need to fetch the entire space?

### Environment

```npx gatsby info --clipboard

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.13.0/bin/yarn
    npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.129
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.20.25 => 2.20.25
    gatsby-plugin-google-analytics: ^2.2.4 => 2.2.4
    gatsby-plugin-google-tagmanager: ^2.2.3 => 2.2.3
    gatsby-plugin-manifest: ^2.3.5 => 2.3.5
    gatsby-plugin-offline: ^3.1.4 => 3.1.4
    gatsby-plugin-react-helmet: ^3.2.4 => 3.2.4
    gatsby-plugin-sass: ^2.2.3 => 2.2.3
    gatsby-plugin-typescript: ^2.3.3 => 2.3.3
    gatsby-source-contentful: ^2.2.9 => 2.2.9
    gatsby-source-filesystem: ^2.2.4 => 2.2.4
```

**Comment by me4502** [comment] 2020-05-01 06:34
We've been encountering the same issue.

After discussing it with Contentful, we were told the issue is Gatsby is using the Content Management API, rather than the Content Delivery API. The Content Management API has a significantly lower rate limit

**Comment by dolphub** [comment] 2020-05-01 16:58
> After discussing it with Contentful, we were told the issue is Gatsby is using the Content Management API, rather than the Content Delivery API. The Content Management API has a significantly lower rate limit

That's an alarming thought. We configure the two deliver/preview tokens in gatsbycloud, i doubt gatsby gains implicit access to the Content Management token through the integration.

Also I can reproduce this locally and I know I'm using the correct values. 

After further testing last night I did finally get the preview to work locally and in the cloud, but I suspect that's only because no one was making updates to our Contentful space so I had free range on the api requests.

**Comment by vladar** [comment] 2020-06-13 12:17
CC @axe312ger

**Comment by axe312ger** [comment] 2020-06-17 10:01
> After discussing it with Contentful, we were told the issue is Gatsby is using the Content Management API, rather than the Content Delivery API. The Content Management API has a significantly lower rate limit

Sorry but this is not correct. The source plugin does not and can not access the Management API. It does not have the management SDK included nor are any credentials for it provided.

What I can give you for now:

* #15084 will change the way the API is used, this **can** reduce the rate limit hits
* `why does it need to fetch the entire space?` It needs all the data for resolving references, but we are looking into possible solutions 
* About the limits: Delivery API and Preview API have different rate limits. Thats the reason why you encounter these errors. (https://www.contentful.com/developers/docs/references/content-delivery-api/#/introduction/api-rate-limits && https://www.contentful.com/developers/docs/references/content-preview-api/#/introduction/api-rate-limits) The source plugin does yet not implement any rate limiting solution to prevent to many API requests. We might make a follow up for #15084 to add rate limiting on Gatsby side

**Comment by axe312ger** [comment] 2020-07-22 13:52
Hey there, 

we released a new major version which optimized the way the APIs are called. Could you please try out, if you still run in the same issue with the new version?

The new Contentful source plugin can be installed via `npm i gatsby-source-contentful@next`.

If you are using Rich Text, you need to follow the migration instructions which be found here:  https://github.com/gatsbyjs/gatsby/pull/25249

Thanks,
Benedikt

**Comment by vladar** [comment] 2020-09-02 12:56
@dolphub Do you have any further input on this issue? I am going to close it but would like to hear from you first.

**Comment by dolphub** [comment] 2020-09-03 16:43
Hi @vladar ,

I will find some time to update / test in the near future! Contentful also recently made a change on how often/min it sends its webhooks in turn affects some how often we hit their API so I am very curious about this fix.

Feel free to close for now and when I find some time to test I can post a comment / open a new + reference if there are further issues.

Thanks!

**Closed** 2020-10-01 07:40 UTC
Labels: status: awaiting author response, status: inkteam assigned, topic: Contentful, type: bug
