### ISSUE TITLE
`gatsby-plugin-offline` breaking `audio.duration` in a live Gatsby app on Netlify...

### ISSUE THREAD

**Issue by rchrdnsh** [gatsbyjs/gatsby#20724] opened 2020-01-20 19:32 UTC
I have an app I'm building using Gatsby and I'm running into a bit of an odd issue, and I have not been able to figure out how to solve it.

The app is a music streaming app for a musical artist, where one can visit the site and listen to their music. Check it out here:

https://rykr.co

Everything is basically working, except for an odd edge case in safari, which seems to be triggered by implementing `gatsby-plugin-offline`. The app has persistent music player controls on the bottom of the page, implemented with `gatsby-plugin-layout`, like so:

<img width="1434" alt="Screen Shot 2020-01-19 at 11 03 33 PM" src="https://user-images.githubusercontent.com/7884263/72751758-59154500-3b75-11ea-8457-d6fcf041ad2f.png">

...where they stay active on the page constantly, and are updated to reflect which ever piece of music has been selected to play. The user can navigate anywhere in the app and the music will still play. It is very similar to Spotify, Tidal, Apple Music, Soundcloud, etc...in design.

The issue I am having is with Safari and `gatsby-plugin-layout`. One of the parts of the UI in the persistent music player controls is the `Current Time`, a clickable `Progress Bar` and the `Duration` or the current piece, which is updated when any new song is activated. This works just fine in Chrome and Firefox and Edge and Opera, etc...but not in Safari for either iOS or macOS (both latest versions). In a nutshell, when I run the app in `gatsby-develop` mode on my machine, or when I turn off `gatsby-plugin-offline` then the `audio.duration` value in safari updates just fine for every new song, and console logging the `audio.duration` value reflects this, like so:

<img width="826" alt="Screen Shot 2020-01-20 at 11 16 30 AM" src="https://user-images.githubusercontent.com/7884263/72752139-5109d500-3b76-11ea-8167-349c7fd4579c.png">

Where the value is NaN until I click play on a track, and then the `duration value` is instantiated and updates per second, and is properly visualized in the app to the right of the progress bar in minutes and seconds via a function. I DO also want to fix it starting with NaN at some point and maybe give it a placeholder value, but for the moment this issue is more pressing.

SO...

When I build the app and run `gatsby serve` with `gatsby-plugin-offline` enabled, or upload it to Netlify and run it live on the web with `gatsby-plugin-offline` enabled, in either case, the duration value is now no longer updated and returns infinity in the console, and reads `infininty:aN` in the app itself, like so:

<img width="832" alt="Screen Shot 2020-01-18 at 10 33 21 AM" src="https://user-images.githubusercontent.com/7884263/72752304-b5c52f80-3b76-11ea-8da8-b0b88d765ad6.png">

To be clear, when I upload the app to netlify with `gatsby-plugin-offline` disabled, then it works as expected, with the duration being updated in the app, even when live on the web. BUT this is not what I want, as every audio file takes 10 or more seconds to load and start playing with `gatsby-plugin-offline` disabled. When it IS enabled, then it only takes a few seconds to start playing, and then plays instantly upon subsequent listens and visits to the site, which is MOST DEFINITELY what I want.

Been googling around for a bit and ran into a few articles, but I'm having a hard time making much sense of them, as I don't know anything at all about service workers:

https://stackoverflow.com/questions/37612177/cannot-play-cached-audio-from-service-worker
https://philna.sh/blog/2018/10/23/service-workers-beware-safaris-range-request/
https://adactio.com/journal/14452
https://jakearchibald.com/2018/i-discovered-a-browser-bug/

Also getting this error message in the console while in develop mode, and I feel like this might have something to do with it:

<img width="500" alt="Screen Shot 2020-01-20 at 11 34 12 AM" src="https://user-images.githubusercontent.com/7884263/72753134-e27a4680-3b78-11ea-8e17-041b6395ba00.png">

It seems like it might have something to do with something called `range headers` although I am still very unclear what that is or means at this point. Anyway, any help that could be given to figure this out would be much appreciated.

Thank you! XD

**Comment by TylerBarnes** [comment] 2020-01-20 22:40
Hi @rchrdnsh !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by vanwalj** [comment] 2020-01-21 15:17
Hey, it seems that this is related to this issue in workbox which is used by gatsby-plugin-offlinehttps://github.com/GoogleChrome/workbox/issues/1663

**Comment by rchrdnsh** [comment] 2020-01-21 19:49
Hi @TylerBarnes,

it will take me a minute to figure out how to create minimal repo, but in the meantime, here's the repo itself:

https://github.com/rchrdnsh/RYKR

...and everything audio related is in the `audio` folder. I create an `audio context` using react context and then sprinkle it around the app.

I will start working on the minimal repro as well and post it when it's done :-)

**Comment by TylerBarnes** [comment] 2020-01-21 20:25
Thanks @vanwalj , that is indeed the issue. I installed [the latest Safari Technology Preview](https://developer.apple.com/safari/download/) and it's working there. Closing this as it's a browser bug with a soon-to-ship fix coming.

**Closed by TylerBarnes** 2020-01-21 20:25 UTC
Labels: status: needs reproduction

**Comment by rchrdnsh** [comment] 2020-01-21 23:17
hmmm....checked it out in STP and it's not showing Infinity:aN anymore, but it's also not updating with the correct duration for each song, instead seemingly showing only the placeholder duration, which is 0:00. Still thinking maybe something is missing?

**Comment by TylerBarnes** [comment] 2020-01-22 02:51
@rchrdnsh For me it stays at `345.07755` (in Chrome, STP, and Firefox). Does that happen with the offline plugin disabled?
