### ISSUE TITLE
gatsby-plugin-sitemap always generates sitemap-index even on low page count

### ISSUE THREAD

**Issue by ichik** [gatsbyjs/gatsby#31282] opened 2021-05-06 09:36 UTC
## Description

According to [documentation](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-sitemap#options) `gatsby-plugin-sitemap` should only generate sitemap-index when having more entries than `entryLimit` option

> `entryLimit` (number = 45000) Number of entries per sitemap file, a sitemap index and multiple sitemaps are created if you have more entries.

With recent updates (`4.0`) this is not the case anymore. `sitemap-index.xml` is always generated, which is quite weird for small amount of entries. It is a different problem than the one being solved currently in #31167, but it existence seems related to [recent activity](https://github.com/gatsbyjs/gatsby/blob/3d65a1cf0e5859890a98a61b0dcab7a40bdf5832/packages/gatsby-plugin-sitemap/src/gatsby-ssr.js#L20).

### Steps to reproduce

Branch with reproducible case: https://github.com/ichik/ichik.xyz/tree/sitemap-bug

### Expected result

Link to `sitemap.xml` generated

### Actual result

Link to `sitemap-index.xml` generated

### Environment

```

  System:
    OS: macOS 11.3.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    npm: 6.14.13 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 88.0
    Safari: 14.1
  npmPackages:
    gatsby: ^3.4.1 => 3.4.1 
    gatsby-plugin-humans-txt: ^1.1.4 => 1.1.4 
    gatsby-plugin-image: ^1.4.0 => 1.4.0 
    gatsby-plugin-manifest: ^3.4.0 => 3.4.0 
    gatsby-plugin-mdx: ^2.4.0 => 2.4.0 
    gatsby-plugin-netlify: ^3.4.0 => 3.4.0 
    gatsby-plugin-offline: ^4.4.0 => 4.4.0 
    gatsby-plugin-react-helmet: ^4.4.0 => 4.4.0 
    gatsby-plugin-robots-txt: ^1.5.6 => 1.5.6 
    gatsby-plugin-sharp: ^3.4.1 => 3.4.1 
    gatsby-plugin-sitemap: ^4.0.0 => 4.0.0 
    gatsby-plugin-styled-components: ^4.4.0 => 4.4.0 
    gatsby-plugin-typescript: ^3.4.0 => 3.4.0 
    gatsby-remark-images: ^5.1.0 => 5.1.0 
    gatsby-remark-unwrap-images: ^1.0.2 => 1.0.2 
    gatsby-source-filesystem: ^3.4.0 => 3.4.0 
    gatsby-transformer-sharp: ^3.4.0 => 3.4.0 
```

**Comment by LekoArts** [comment] 2021-05-06 11:51
I don't know if this was done on purpose @moonmeister?

We now use `simpleSitemapAndIndex`:

https://github.com/gatsbyjs/gatsby/blob/ea81d3b9100f91d38b63c95775f34a32bb28c0a5/packages/gatsby-plugin-sitemap/src/gatsby-node.js#L88-L95

According to https://github.com/ekalinin/sitemap.js/blob/4141469ca90e53f9f15b5107a25d16591175984f/README.md#create-sitemap-and-index-files-from-one-large-list:

> If you know you are definitely going to have more than 50,000 urls in your sitemap, you can use this slightly more complex interface to create a new sitemap every 45,000 entries and add that file to a sitemap index.

So the behavior changed and thus it's currently working as intended but the docs then might be outdated if `entryLimit` is only affecting the splitting and not the creation of an index itself.

**Comment by moonmeister** [comment] 2021-05-06 12:24
Yeah the index file always exists. Good catch, a PR would be much appreciated to clarify this language.

**Comment by ichik** [comment] 2021-05-06 13:15
I think that it's somewhat of an overkill to always generate index in case you might have over 50,000 entries. For a lot of gatsby projects out there previous behavior which resulted in a single sitemap.xml looked way more sensible.

**Comment by moonmeister** [comment] 2021-05-06 15:00
Yeah, It may be a little "cleaner", but at the end of the day I couldn't think why it really mattered. The bots don't care. 

The reason it changed was because the default behavior of the library we use changed. I wasn't going to spend hours rewriting code to fix it. 


If this is important to you, feel free to do the work and submit a PR.

**Comment by jpalo** [comment] 2021-05-07 08:20
Also the sitemap-index.xml points to `/sitemap-N.xml` at the _root_, while those files are really at `/sitemap/sitemap-N.xml`.

**Comment by abheist** [comment] 2021-05-20 09:56
One more bug though: generated index file is containing wrong URLs to individual files:
`https://abheist.com/sitemap/sitemap-index.xml`:
```xml
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <sitemap>
        <loc>https://abheist.com/sitemap-0.xml</loc>
    </sitemap>
</sitemapindex>
```
`loc` link should be: `https://abheist.com/sitemap/sitemap-0.xml`, missing a `sitemap` directory.

**Comment by moonmeister** [comment] 2021-05-20 13:06
This has been reported and fixed in the next release.

**Comment by SomiDivian** [comment] 2021-06-07 03:16
What's the news?

**Comment by prichey** [comment] 2021-06-23 16:34
Related to [this](https://github.com/gatsbyjs/gatsby/issues/31282#issuecomment-844935130), the `sitemap-index.xml` file also is also mangling my siteUrl. In this example, it's set to `https://mysite.com/foo`.

`sitemap-index.xml`:
```
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
<sitemap>
<loc>https://mysite.com/sitemap-0.xml</loc>
</sitemap>
</sitemapindex>
```

The 4. release seems to have lots of issues so I'm going to try downgrading until these are worked out

**Comment by moonmeister** [comment] 2021-06-23 17:12
@prichey Please open a separate issue for this and a reproduction or more detailed example of your configuration. and what is happening vs what you expect to happen.

**Comment by prichey** [comment] 2021-06-23 18:03
@moonmeister https://github.com/gatsbyjs/gatsby/issues/32080

**Closed** 2021-06-25 10:12 UTC
Labels: good first issue, help wanted, topic: plugins, type: documentation

**Comment by justsilencia** [comment] 2022-03-08 19:54
> Yeah, It may be a little "cleaner", but at the end of the day I couldn't think why it really mattered. The bots don't care.
> 
> The reason it changed was because the default behavior of the library we use changed. I wasn't going to spend hours rewriting code to fix it.
> 
> If this is important to you, feel free to do the work and submit a PR.

You mention that "the bots don't care." However, after doing some research, it seems that having the sitemap in a subfolder will only allow google to scan pages in that subfolder. Here's a reference to this:

[Stackoverflow answer with link to google docs](https://stackoverflow.com/a/49166055/9040866)

Could you please explain if this is incorrect?

**Comment by Pandanaax** [comment] 2022-10-14 13:33
I have multi domains and work with Gatsby 2, but since I move for Gatsby 4 my sitemap is like this :

<loc>https://inte.****.fr/https://inte.****.it/intimo-premaman</loc>
But i need only .it for work for this exemple.

Could you help me please.

**Comment by moonmeister** [comment] 2022-10-14 14:28
> I have multi domains and work with Gatsby 2, but since I move for Gatsby 4 my sitemap is like this :
> 
> <loc>https://inte.****.fr/https://inte.****.it/intimo-premaman</loc>
> But i need only .it for work for this exemple.
> 
> Could you help me please. 
> 

Hi @Pandanaax !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you open a new issue. Please include a [minimal reproduction][reproduction] and a copy of any relevant code/config or a link to the repository. 

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction
