### ISSUE TITLE
Gatsby's use of window.replaceState in app-##.js

### ISSUE THREAD

**Issue by hammund0** [gatsbyjs/gatsby#24932] opened 2020-06-11 17:21 UTC
## Summary

Hi, I think GatsbyJS is great and I enjoy using it.

I just had a quick question, I was checking the out the compiled output. (`app-###.js`).

I had spotted this. (I don't actually add this in the source code, so I'm guessing it's added in by Gatsby).

`try{a||f?t.history.replaceState(s,null,e):t.history.pushState(s,null,e)}catch(d){t.location[f?"replace":"assign"](e)}}i=o(t),a=!0;var p=new Promise((function(t){return u=t}));return n.forEach((function(t){return t({location:i,action:"PUSH"})})),p}}},a=function(){var t=arguments.length>0&&void 0!==arguments[0]?arguments[0]:"/",e=t.indexOf("?"),n={pathname:e>-1?t.substr(0,e):t,search:e>-1?t.substr(e):""},r=0,o=[n],i=[null];return{get location(){return o[r]},addEventListener:function(t,e){},removeEventListener:function(t,e){},history:{get entries(){return o},get index(){return r},get state(){return i[r]},pushState:function(t,e,n){var a=n.split("?"),u=a[0],c=a[1],s=void 0===c?"":c;r++,o.push({pathname:u,search:s.length?"?"+s:s}),i.push(t)},replaceState:function(t,e,n){var a=n.split("?"),u=a[0],c=a[1],s=void 0===c?"":c;`

I had noticed it calls `history.replaceState` and `history.pushState,` I have a use case where this actually causes a problem. As the URL it lives on, is different to what the component thinks it is so it rewrites the URL. The way we are using the Gatsby generated components is quite an edge case.

Why does it need this `window.pushState` and `window.replaceState,` and is it possible to get around this?

Thanks

**Comment by herecydev** [comment] 2020-06-11 17:53
It's from @reach/router: https://github.com/reach/router/blob/master/src/lib/history.js#L70-L94

It's used when you do programmatic navigation in gatsby, so I doubt it'll get called unless you, the consumer, are calling it.

**Comment by hammund0** [comment] 2020-06-11 17:56
Thank you @herecydev , that helps thank you.

Trying to think where I use it, perhaps the Gatsby `Link` component?

**Comment by herecydev** [comment] 2020-06-11 17:58
It can potentially trigger in the `Link` component: https://github.com/reach/router/blob/master/src/index.js#L411-L423

So a bundler will have to include it

**Comment by hammund0** [comment] 2020-06-11 17:59
Nice one! I'll remove Link and just use plain old <a>'s. Thanks again mate

**Comment by herecydev** [comment] 2020-06-11 18:00
I apologise it's not really conditional, it's pretty much always called. What issues are you running into?

**Comment by hammund0** [comment] 2020-06-11 18:59
the gatsby-link npm package seems to be installed with gatsby as a sub dependency. I'm not using `Link `anywhere in the code it's still pulling in that code.

**Comment by herecydev** [comment] 2020-06-11 19:09
It's probably because they are added to the window here: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/cache-dir/navigation.js#L152-L154

**Comment by hammund0** [comment] 2020-06-11 19:20
Yes, i've debugged the `navigate `function, and the issue is that:
 
`replace: true` in `arguments` array
the url in the argument array is wrong. (0 index)
the url in `to` is also wrong.. (in 1 index)

I think if we set these to the correct URL, it should work (if we can't get rid of the code).

The way we're using these components is a bit of a hack and definitely an edge case.

**Comment by herecydev** [comment] 2020-06-11 19:24
I'm not sure I follow. Those will only be called if you actually invoke that `navigate` function

**Comment by hammund0** [comment] 2020-06-11 21:35
Sorry yes, I wasn't clear. I had put a breakpoint on the `navigate` function and those were the variables that were set.

I'll have a look at what even calls navigate, but at a guess it's not where you said before when it gets bound to the window?

**Comment by LekoArts** [comment] 2020-06-16 08:03
Hi!
I'm not sure what your issue is about. Do you have a [reproduction][reproduction] of a bug or are you assuming things?

[reproduction]: https://gatsby.dev/reproduction

**Comment by wardpeet** [comment] 2020-06-24 10:15
@hammund0 Sadly gatsby only supports if the url matches with the URL of your page. You can use options [path-prefix](https://www.gatsbyjs.org/docs/path-prefix/) if your site isn't on a subpath.

You can also disable client-side routing by using https://github.com/wardpeet/gatsby-plugin-static-site/.

That's all we can do from a gatsby side for now.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Closed by wardpeet** 2020-06-24 10:15 UTC
Labels: status: needs more info, type: question or discussion
