### ISSUE TITLE
Memory leak - Circle CI - buudy.works ENOMEM

### ISSUE THREAD

**Issue by FONDSMATIVE** [gatsbyjs/gatsby#20812] opened 2020-01-23 10:17 UTC
Hi!
Thank you so much for this great gatsby community! I really love it!

We do have a small project using Gatsby, of course!
We do use CircleCI as well, and we have exactly the same problems described here when using [buddy.works](https://buddy.works/).

I will attach a screenshot as well. I did https://github.com/gatsbyjs/gatsby/issues/16744#issuecomment-575708913 on this topic as well with no response and now I am opening it here again. I really think, that is a bug! 

**I think, handling large images should not be a problem at all - to run into spawn ENOMEM is one really very tough question. Isn't it @LekoArts ?**

**It would be great to resolve those problems, a lot of us are experiencing.**
**Many many thanks!**

P.S.
![Here we go...](https://user-images.githubusercontent.com/47738538/72630164-1162a380-3952-11ea-81df-d63e3748e6bc.jpg)

**Comment by sidharthachatterjee** [comment] 2020-01-23 14:44
@FONDSMATIVE The issue isn't a memory leak here but the fact that `sharp` is trying to allocate more memory to process _more_ images concurrently but unable to allocate more memory because Node allows you allocating 1 GB by default. 

You should be able to fix this by setting `NODE_OPTIONS=--max_old_space_size=4096` 

While you're at it, please set `GATSBY_CPU_COUNT=2` as well since Circle CI (incorrectly) reports 8 available threads. 

Closing this since it isn't a Gatsby issue. Thanks!

**Closed by sidharthachatterjee** 2020-01-23 14:44 UTC

**Comment by FONDSMATIVE** [comment] 2020-02-11 16:43
Hi @sidharthachatterjee,

thanks very much for your reply! 
After I got some more RAM on buddy.works for testing purposes, everything seemed to work fine with no RAM limitations on buddy.works! **But let us focus on Circle CI...**

Now back to the free Circle CI account, and as by @sidharthachatterjee suggested, I added some variables at Circle CI as following:  
- **NODE_OPTIONS=--max_old_space_size=4096**
- **GATSBY_CPU_COUNT=2**

**And still, I am running out of Memory using Circle CI - at the point generating thumbnails**. 
 
Any other suggestions? I hardly can think that a 15 page Gatsby project needs more that 1GB RAM generating thumbnails. For me, that sounds it bit strange.

Any help and suggestions would be awesome! 
Many thanks to that great community! 

P.S. 
ENOMEM
![ENOMEM](https://user-images.githubusercontent.com/47738538/74257735-86c55800-4cf5-11ea-8f65-48c8c99eeaaf.jpg)
