### ISSUE TITLE
Gatsby develop (yoga-layout) crashes in Gatsby 2.22.0

### ISSUE THREAD

**Issue by ehannes** [gatsbyjs/gatsby#24411] opened 2020-05-24 15:29 UTC
## Description

I upgraded `gatsby` and now I can't run `gatsby develop`

### Steps to reproduce
1. Create a new Gatsby site with `gatsby new ...`
2. Install the following node packages:
```
    "gatsby": "2.22.0",
    "react": "16.13.1",
    "react-dom": "16.13.1"
```
3. Run `gatsby develop`

Here is a demo project: https://github.com/ehannes/broken-gatsby-develop-command.

### Expected result

I would expect the command to run without a crash :smile: 

### Actual result

It crashed with the following error:
```
$ gatsby develop
/home/foo/broken-gatsby-develop-command/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: write EACCES
    at process.target._send (internal/child_process.js:762:20)
    at process.target.send (internal/child_process.js:634:19)
    at action (/home//foo/broken-gatsby-develop-command/node_modules/gatsby-cli/lib/reporter/loggers/ipc/index.js:58:13)
    at dispatch (/home//foo/broken-gatsby-develop-command/node_modules/gatsby-cli/lib/reporter/redux/index.js:54:5)
    at dispatch (/home//foo/broken-gatsby-develop-command/node_modules/gatsby-cli/lib/reporter/redux/internal-actions.js:42:7)
    at dispatch (/home//foo/broken-gatsby-develop-command/node_modules/gatsby-cli/lib/reporter/redux/index.js:33:5)
    at action.forEach.item (/home//foo/broken-gatsby-develop-command/node_modules/gatsby-cli/lib/reporter/redux/index.js:30:28)
    at Array.forEach (<anonymous>)
    at dispatch (/home//foo/broken-gatsby-develop-command/node_modules/gatsby-cli/lib/reporter/redux/index.js:30:12)
    at Reporter.pendingActivity (/home//foo/broken-gatsby-develop-command/node_modules/redux/lib/redux.js:483:12)
    at module.exports (/home//foo/broken-gatsby-develop-command/node_modules/gatsby/dist/commands/develop-process.js:413:21)
    at Object.<anonymous> (/home//foo/broken-gatsby-develop-command/.cache/tmp-6512-KBLW7D8Kj2CY:4:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
```

### Environment

```
$ gatsby info --clipboard

  System:
    OS: Linux 5.3 Pop!_OS 18.04 LTS
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 4.4.20 - /bin/bash
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.129
    Firefox: 75.0
  npmPackages:
    gatsby: 2.22.0 => 2.22.0
```

### Temporary fix
For me, it works to downgrade to gatsby `2.21.40`.

**Comment by LekoArts** [comment] 2020-05-25 09:03
Thank you for opening this!

This sounds like a duplicate of https://github.com/gatsbyjs/gatsby/issues/22558, https://github.com/gatsbyjs/gatsby/issues/23214 and most specifically https://github.com/gatsbyjs/gatsby/issues/22991#issuecomment-630381390

`gatsby@2.20.0` is not the latest version of Gatsby and as the last comment suggests a bug existed in the CLI, too. So I used `gatsby new` with the latest version of the `gatsby-cli` package and followed your steps, I don't see the error with the latest versions of everything. I'd suggest updating your packages :)

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2020-05-25 09:03 UTC
Labels: type: bug

**Comment by ehannes** [comment] 2020-05-27 19:23
Hi @LekoArts! Thanks for your response. Unfortunately, it still doesn't work for me, even after upgrading gatsby, gatsby-cli and node. But I will move to one of the other issues. Sorry for not checking that more thoroughly before opening a new one!

**Comment by ehannes** [comment] 2020-09-18 06:51
This seems to be resolved now :)
