### ISSUE TITLE
Extract the CSS out of style tag in separate stylesheets

### ISSUE THREAD

**Issue by abdulhannanali** [gatsbyjs/gatsby#2289] opened 2017-09-30 14:35 UTC
I would love to extract the CSS out style tags into separate stylesheets, I am using Bootstrap within my site and it's less than ideal to load the full bootstrap with subsequent visits of the user. Is there any plugin for gatsby which solves this, like ExtractTextPlugin for Webpack? I can't find one

**Comment by sebastienfi** [comment] 2017-10-01 18:42
Have you looked at using react-bootstrap?

There is also [an example site](https://github.com/jaxx2104/gatsby-starter-bootstrap) here but never tried it.

**Comment by KyleAMathews** [comment] 2017-10-01 21:19
Gatsby does extract CSS but inlines it into the HTML `<head>` for performance.

If you create a custom html.js, you can link to the generated css file if you'd like.

You might be interested in this approach though which automatically removes excess CSS https://github.com/rongierlach/gatsby-plugin-purify-css

**Comment by KyleAMathews** [comment] 2017-10-03 14:40
@3stacks try to see if you can reproduce your issue with the sass example app.

**Comment by 3stacks** [comment] 2017-10-04 05:13
Kyle, are you talking about this example?
https://github.com/gatsbyjs/gatsby/tree/master/examples/using-sass

Does this exist as a starter, or do I just copy these files and run my gatsby tasks?

**Comment by KyleAMathews** [comment] 2017-10-04 05:26
Just clone the repo and navigate to its directory. I'd love to make all the examples work as starters but that'll take some infrastructure work.

**Comment by 3stacks** [comment] 2017-10-05 03:56
The sass example does work for me. I'll give it a shot converting the blog over to use that sass example tonight. I have a feeling this is just a bizarre edge case, because sass has been misbehaving from the start for me.

**Comment by 3stacks** [comment] 2017-10-05 09:12
As I started migrating my stuff, I saw the stuff getting spit out into `public/style.css`, but when I look at the HTML I see this.

```
<style id="gatsby-inlined-css">[object Object]</style>
```

**Comment by KyleAMathews** [comment] 2018-06-27 02:04
Closing this issue as it's fairly old and we have far too many open issues! If you have additional problems in this area, please open a new issue!

**Closed by KyleAMathews** 2018-06-27 02:04 UTC
Labels: 🏷 type: question or discussion

**Comment by Pencroff** [comment] 2018-08-04 13:25
Hey @3stacks.
It looks solution not to hard to maintain by html.js extraction.
Just follow https://www.gatsbyjs.org/docs/custom-html/

And then replace default logic around css like:
Before:
```javascript
    if (process.env.NODE_ENV !== `production`) {
      css = (
        <style
          id="gatsby-inlined-css"
          dangerouslySetInnerHTML={{ __html: stylesStr }}
        />
      )
    }
```
After:
```javascript
    if (process.env.NODE_ENV !== `production`) {
      css = (
        <style
          id="gatsby-inlined-css"
          dangerouslySetInnerHTML={{ __html: stylesStr }}
        />
      )
    } else {
      css = (<link rel="stylesheet" href="/styles.css"/>)
    }
```
This solution doesn't cover any `pathPrefix`, but as initial solution can help to reduce size of all html files

**Comment by wongsynee** [comment] 2018-09-25 06:48
Hi @Pencroff thanks for the tip! I have a similar requirement and would need to extract the CSS into separate stylesheets. However, where is `stylesStr` being declared from?

**Comment by Pencroff** [comment] 2018-09-25 06:57
> Hi @Pencroff thanks for the tip! I have a similar requirement and would need to extract the CSS into separate stylesheets. However, where is `stylesStr` being declared from?

I have on top of `html.js` code like:

```javascript
let stylesStr
if (process.env.NODE_ENV === `production`) {
  try {
    stylesStr = require(`!raw-loader!../public/styles.css`)
  } catch (e) {
    console.log(e)
  }
}
```

**Comment by wongsynee** [comment] 2018-09-25 08:13
Thanks @Pencroff

**Comment by wongsynee** [comment] 2018-09-26 05:39
For some reason when I run build, a `styles.css` file is not created but something like `component---src-pages-index-js.341e385fbf9137261e9d.css` is created as a stylesheet. 

I'm using the sass-example from Gatsby with the following in the config:
```
module.exports = {
  plugins: [
    `gatsby-plugin-sass`,
    {
      resolve: `gatsby-plugin-google-analytics`,
      options: {
        trackingId: `UA-93349937-2`,
      },
    },
    `gatsby-plugin-offline`,
  ],
}
```

**Comment by Glinkis** [comment] 2019-08-01 12:59
This is the solution I'm using, if anyone wants an alternative.

```js
if (process.env.NODE_ENV === "production") {
  for (const component of props.headComponents) {
    if (component.type === "style") {
      const index = props.headComponents.indexOf(component)
      const link = <link rel="stylesheet" href={component.props["data-href"]} />
      props.headComponents.splice(index, 1, link)
    }
  }
}
```
