### ISSUE TITLE
gatsby-theme-blog not showing blog posts

### ISSUE THREAD

**Issue by molebox** [gatsbyjs/gatsby#15758] opened 2019-07-15 18:17 UTC
## Description

gatsby-theme-blog not showing blog posts

### Steps to reproduce

When cloning the gatsby-theme-blog starter repo i run yarn develop and navigate to a blog post. I then get a site cant be found page. The url is also wrong, not showing the root. I have tried setting the options for the gatsby-theme-blog to explicitly point to / 

### Expected result

Should be able to view the demo blog posts

### Actual result

Got a Site cant be found page instead

### Environment

 System:
    OS: Windows 10
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
  Binaries:
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - /c/Python27/python
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.13.21 => 2.13.21
    gatsby-theme-blog: ^1.0.0 => 1.0.0

**Comment by sidharthachatterjee** [comment] 2019-07-16 00:12
Sorry you're seeing this @molebox 

I can't seem to reproduce this! I created a new site with `gatsby new test-blog gatsbyjs/gatsby-starter-blog-theme` and navigated to the first post and everything seemed fine. 

Can you push a minimal reproduction if possible? Would love to help you fix this!

**Comment by JasherIO** [comment] 2019-07-18 16:54
I've the same issue when running `gatsby new my-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme` from instructions [here](https://www.gatsbyjs.org/blog/2019-07-03-customizing-styles-in-gatsby-themes-with-theme-ui/).

System:
OS: Windows Version 10.0.18362 Build 18362
CPU: Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz, 3201 Mhz, 4 Core(s), 4 Logical Processor(s)
Binaries:
Yarn: 1.13.0
npm: 6.4.1
Languages:
Python: 2.7.14
Browsers:
Vivaldi: 2.6.1566.44
Chrome: 75.0.3770.142

**Comment by molebox** [comment] 2019-07-18 16:57
Sorry ive been away from my computer the last couple of days. I will try and show you my repo this evening

**Comment by molebox** [comment] 2019-07-23 11:49
I deleted the first one i pulled in ran gatsby new my-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme again.

I then run yarn develop and try to navigate to a blog post and i get the following page: 

![BLOG ERROR](https://user-images.githubusercontent.com/22930449/61709922-962c8600-ad50-11e9-9a1f-e238525472e8.PNG)

Here is the repo: https://github.com/molebox/hungry-bear-studio-blog

**Comment by molebox** [comment] 2019-07-25 19:42
I updated gatsby to 2.13.41 and gatsby-theme-blog to 1.0.2 and now its working!

**Comment by lannonbr** [comment] 2019-07-25 19:48
Closing as it seems to be resolved

**Closed by lannonbr** 2019-07-25 19:48 UTC
Labels: status: needs reproduction, topic: themes
