### ISSUE TITLE
webpack: wait until bundle finished: /

### ISSUE THREAD

**Issue by arpicoinpanion** [gatsbyjs/gatsby#33859] opened 2021-11-04 14:59 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Please find the `package.json` below.

I have an issue on Windows and Linux machines (but not on MacBook), what I cannot solve it.

Once I change something in React:

- Add new component
- modify a component
- modify style
- etc.

The runned dev server writes the following: `webpack: wait until bundle finished: /` and this takes forever. I do not see my modification. Even when I restart the server, then after the first or second change, the issue occurs again. 

Has anyone idea what can be the problem? Could you please share with me how I can solve it?

```{
  "name": "gatsby-starter-default",
  "private": true,
  "description": "A simple starter to get up and developing quickly with Gatsby",
  "version": "0.1.0",
  "author": "Coinpanion <info@coinpanion.com>",
  "dependencies": {
    "@blocks/kit": "0.0.28",
    "@types/react-helmet": "^6.1.4",
    "axios": "^0.23.0",
    "babel-plugin-styled-components": "^1.13.3",
    "babel-preset-gatsby": "^2.0.0",
    "bootstrap": "^5.1.3",
    "gatsby": "^4.0.0",
    "gatsby-plugin-alias-imports": "^1.0.5",
    "gatsby-plugin-glamor": "^3.11.0",
    "gatsby-plugin-google-analytics": "^4.0.0",
    "gatsby-plugin-google-tagmanager": "^4.0.0",
    "gatsby-plugin-image": "^2.0.0",
    "gatsby-plugin-manifest": "^4.0.0",
    "gatsby-plugin-netlify": "^3.14.0",
    "gatsby-plugin-react-helmet": "^5.0.0",
    "gatsby-plugin-react-svg": "^3.1.0",
    "gatsby-plugin-sharp": "^4.0.0",
    "gatsby-plugin-styled-components": "^5.0.0",
    "gatsby-plugin-typography": "^4.0.0",
    "gatsby-source-filesystem": "4.0.0",
    "gatsby-source-graphql": "^4.0.0",
    "gatsby-source-strapi": "^1.0.2",
    "gatsby-transformer-json": "^4.0.0",
    "gatsby-transformer-remark": "^5.0.0",
    "gatsby-transformer-sharp": "^4.0.0",
    "glamor": "^2.20.40",
    "glamor-inline": "^1.0.5",
    "graphql-request": "^3.6.1",
    "load-json-file": "^7.0.1",
    "marked": "^3.0.8",
    "moment": "^2.29.1",
    "path-browserify": "^1.0.1",
    "process": "^0.11.10",
    "prop-types": "^15.7.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-facebook": "^8.1.4",
    "react-feather": "^2.0.9",
    "react-helmet": "^6.1.0",
    "react-markdown": "^7.1.0",
    "react-moment": "^1.1.1",
    "react-share": "^4.4.0",
    "react-typography": "^0.16.20",
    "styled-components": "^5.3.3",
    "typography": "^0.16.21"
  },
  "devDependencies": {
    "@types/styled-components": "^5.1.15",
    "@typescript-eslint/eslint-plugin": "5.x",
    "@typescript-eslint/parser": "5.x",
    "babel-eslint": "10.x",
    "eslint": "8.x",
    "eslint-config-prettier": "^8.3.0",
    "eslint-config-react-app": "^6.0.0",
    "eslint-import-resolver-webpack": "^0.13.2",
    "eslint-plugin-flowtype": "6.x",
    "eslint-plugin-import": "2.x",
    "eslint-plugin-jsx-a11y": "6.x",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react": "7.x",
    "eslint-plugin-react-hooks": "4.x",
    "install": "^0.13.0",
    "npm": "^8.1.1",
    "prettier": "^2.4.1",
    "webpack-bundle-analyzer": "^4.5.0"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "rm -rf .cache/ public/ && gatsby build",
    "develop": "gatsby develop --open",
    "dev": "rm -rf .cache/ public/ && npm run develop",
    "lint": "eslint ./src",
    "lint:fix": "eslint ./src --fix",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "clean": "gatsby clean",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\" && exit 1",
    "strapi-sync": "node ./tools/strapi-sync/app.js"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  },
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  }
}
```

### Reproduction Link

https://#

### Steps to Reproduce

-

### Expected Result

-

### Actual Result

-

### Environment

```shell
-
```

### Config Flags

-

**Comment by LekoArts** [comment] 2021-11-05 07:48
Hi!

Please fill out the issue template and create a [minimal reproduction][reproduction] so that we can help you.

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-11-22 10:58
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-11-22 10:58 UTC
Labels: type: bug, status: needs reproduction

**Comment by vednig** [comment] 2024-02-18 06:57
Yes, I can assure this is happening causing problems in developmental testing to send out more requests and falling into a reload loop.

**Comment by justpierre003** [comment] 2025-04-18 16:28
same here, any fixes?
