### ISSUE TITLE
remark-remark-katex replaces LaTeX math with wrong html

### ISSUE THREAD

**Issue by BurkovBA** [gatsbyjs/gatsby#31427] opened 2021-05-14 16:36 UTC
## Description

I am trying to make Gatsby render LaTeX math formulas in my blog posts.

I'm using the standard `gatsby-transformer-remark` with `gatsby-remark-katex` plugin configured as follows:

From `gatsby-config.js` ([full code available here](https://github.com/BurkovBA/BurkovBA.github.io/blob/master/gatsby-config.js)):
```javascript
module.exports = {
  siteMetadata: {
    title: `Personal blog of Boris Burkov`,
    author: `Boris Burkov`,
    description: `A personal blog of Boris Burkov, version 4.1, this time written in Gatsby.`,
    siteUrl: `https://borisburkov.net/`,
    social: {
      telegram: `BorisBurkov`,
    },
  },
  plugins: [
      ...
      {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          ...
          {
            resolve: `gatsby-remark-katex`,
            options: {
              // Add any KaTeX options from https://github.com/KaTeX/KaTeX/blob/master/docs/options.md here
              strict: `ignore`
            }
          }
          ...
        ]
      ...
    ],
};
```

In the markdown of my blog posts I'm using both inline math and display-mode math like this:

```md
If we assume for a second that HDD failures were independent, then probability of
a failure of X drives at the same time corresponds to Poisson distribution:

$$
p(failure of 1 HDD) = 10^{-5}
$$

$N(HDD) = 2400$
```

In the resulting html page these math formulas are strangely converted to the following incorrect html:

```html
<div class="math math-display katex">p(failure of 1 HDD) = 10^{-5}</div>
```

Now, if I go to the source code of gatsby-remark-katex/index.js and add check, if it sees my inline math and if it replaces it with proper html, I see that it actually does. I add `    console.log('node.value = ${node.value}')` statement to the code:

`gatsby-remark-katex/index.js`
```javascript
"use strict";

const visit = require(`unist-util-visit`);

const katex = require(`katex`);

const remarkMath = require(`remark-math`);

module.exports = ({
  markdownAST
}, pluginOptions = {}) => {
  visit(markdownAST, `inlineMath`, node => {
    node.type = `html`;
    node.value = katex.renderToString(node.value, {
      displayMode: false,
      ...pluginOptions
    });
    console.log(`node.value = ${node.value}`)
  });
  visit(markdownAST, `math`, node => {
    node.type = `html`;
    node.value = katex.renderToString(node.value, {
      displayMode: true,
      ...pluginOptions
    });
  });
};

module.exports.setParserPlugins = () => [remarkMath];
```

When I say `gatsby develop`, in the console I see the expected html for math formulas, rendered by katex:

```html
node.value = <span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>N</mi><mo stretchy="false">(</mo><mi>H</mi><mi>D</mi><mi>D</mi><mo
stretchy="false">)</mo><mo>=</mo><mn>2400</mn></mrow><annotation encoding="application/x-tex">N(HDD) = 2400</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut"
style="height:1em;vertical-align:-0.25em;"></span><span class="mord mathnormal" style="margin-right:0.10903em;">N</span><span class="mopen">(</span><span class="mord mathnormal" style="margin-right:0.08125em;">H</span><span
class="mord mathnormal" style="margin-right:0.02778em;">D</span><span class="mord mathnormal" style="margin-right:0.02778em;">D</span><span class="mclose">)</span><span class="mspace"
style="margin-right:0.2777777777777778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:0.2777777777777778em;"></span></span><span class="base"><span class="strut"
style="height:0.64444em;vertical-align:0em;"></span><span class="mord">2</span><span class="mord">4</span><span class="mord">0</span><span class="mord">0</span></span></span></span>
```

Problem is that html wouldn't show up in the resulting page. It wouldn't appear in GraphQL of the page in `html` or `htmlAST` field either, if I go to query the GraphiQL for it:

<img width="599" alt="Screenshot 2021-05-14 at 19 37 23" src="https://user-images.githubusercontent.com/7602655/118301585-eb202a00-b4eb-11eb-8344-2fd57ee71d27.png"> 

Here's the page output, note the un-rendered formulae:

<img width="1421" alt="Screenshot 2021-05-14 at 19 55 00" src="https://user-images.githubusercontent.com/7602655/118303744-77335100-b4ee-11eb-949e-62d4ff51568e.png">

### Steps to reproduce

Full source code of my Gatsby 3-based blog is available here: https://github.com/BurkovBA/BurkovBA.github.io.git.

```
git clone https://github.com/BurkovBA/BurkovBA.github.io.git
nvm use 15
npm install
npm run develop
browser http://localhost:8000/2021-03-11-1/
```

### Expected result

I expected LaTeX formulas rendered in the lower part of my latest blog post: http://localhost:8000/2021-03-11-1/ as the following html:

```html
<span class="katex"><span class="katex-mathml"><math xmlns="http://www.w3.org/1998/Math/MathML"><semantics><mrow><mi>N</mi><mo stretchy="false">(</mo><mi>H</mi><mi>D</mi><mi>D</mi><mo
stretchy="false">)</mo><mo>=</mo><mn>2400</mn></mrow><annotation encoding="application/x-tex">N(HDD) = 2400</annotation></semantics></math></span><span class="katex-html" aria-hidden="true"><span class="base"><span class="strut"
style="height:1em;vertical-align:-0.25em;"></span><span class="mord mathnormal" style="margin-right:0.10903em;">N</span><span class="mopen">(</span><span class="mord mathnormal" style="margin-right:0.08125em;">H</span><span
class="mord mathnormal" style="margin-right:0.02778em;">D</span><span class="mord mathnormal" style="margin-right:0.02778em;">D</span><span class="mclose">)</span><span class="mspace"
style="margin-right:0.2777777777777778em;"></span><span class="mrel">=</span><span class="mspace" style="margin-right:0.2777777777777778em;"></span></span><span class="base"><span class="strut"
style="height:0.64444em;vertical-align:0em;"></span><span class="mord">2</span><span class="mord">4</span><span class="mord">0</span><span class="mord">0</span></span></span></span>
```

### Actual result

LaTeX is not rendered, but just replaced with pretty useless divs:

```html
<div class="math math-display">p(failure of 1 HDD) = 10^{-5}</div>
```

### Environment

```
  System:
    OS: macOS 11.1
    CPU: (8) arm64 Apple M1
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    npm: 7.12.1 - ~/.nvm/versions/node/v15.14.0/bin/npm
  Languages:
    Python: 3.9.2 - /Users/burkov/miniforge3/bin/python
  Browsers:
    Safari: 14.0.2
  npmPackages:
    gatsby: ^3.4.2 => 3.4.2 
    gatsby-plugin-feed: ^3.4.0 => 3.4.0 
    gatsby-plugin-google-analytics: ^3.4.0 => 3.4.0 
    gatsby-plugin-image: ^1.4.1 => 1.4.1 
    gatsby-plugin-manifest: ^3.4.0 => 3.4.0 
    gatsby-plugin-offline: ^4.4.0 => 4.4.0 
    gatsby-plugin-react-helmet: ^4.4.0 => 4.4.0 
    gatsby-plugin-sass: ^4.4.0 => 4.4.0 
    gatsby-plugin-sharp: ^3.4.2 => 3.4.2 
    gatsby-plugin-styled-components: ^4.4.0 => 4.4.0 
    gatsby-plugin-typography: ^3.4.0 => 3.4.0 
    gatsby-remark-copy-linked-files: ^4.1.0 => 4.1.0 
    gatsby-remark-embed-gist: ^1.2.1 => 1.2.1 
    gatsby-remark-images: ^5.1.0 => 5.1.0 
    gatsby-remark-katex: ^5.1.0 => 5.1.0 
    gatsby-remark-prismjs: ^5.1.0 => 5.1.0 
    gatsby-remark-responsive-iframe: ^4.1.0 => 4.1.0 
    gatsby-remark-smartypants: ^4.1.0 => 4.1.0 
    gatsby-source-filesystem: ^3.4.0 => 3.4.0 
    gatsby-transformer-remark: ^4.1.0 => 4.1.0 
    gatsby-transformer-sharp: ^3.4.0 => 3.4.0 
  npmGlobalPackages:
    gatsby-cli: 3.4.1
```

No `flags` inside `gatsby-config.js`.

**Comment by hendra-go** [comment] 2021-05-15 13:31
This might be duplicate #30865

**Comment by BurkovBA** [comment] 2021-05-15 19:34
@hendra-go Thank you for pointing to your solution! 

Unfortunately, the suggested fix doesn't work for me: when I try to copy-paste it in place of `gatsby-remark-katex/index.js`, I get the following errors:

```
failed Building development bundle - 6.460s
ERROR in 
/Users/burkov/Documents/Projects/personal/borisburkov.net/src/pages/index.js
  65:11  error  Cannot query field "timeToRead" on type "MarkdownRemark"  graphql/template-strings

/Users/burkov/Documents/Projects/personal/borisburkov.net/src/templates/blog-post.js
  91:15  error  Unknown argument "pruneLength" on field "MarkdownRemark.excerpt"  graphql/template-strings

✖ 4 problems (2 errors, 2 warnings)
```

But I'll be following the issue you suggested, maybe an official patch will fix these problems. Thanks a lot, once again!

**Comment by amitash** [comment] 2021-05-15 22:44
@BurkovBA you must copy the fix as a local folder instead of replacing. As described [here](https://www.gatsbyjs.com/docs/creating-a-local-plugin/), create a `plugins` directory in the root of your project and copy the contents of the zip file in there.

**Comment by BurkovBA** [comment] 2021-05-16 09:07
@amitash Wow, local installation of the plugin has actually helped:

<img width="1260" alt="Screenshot 2021-05-16 at 12 04 38" src="https://user-images.githubusercontent.com/7602655/118391831-f5067200-b63e-11eb-8c72-1738e769d190.png">

I guess, I'm not brave enough to deploy this solution to the production right now, but apparently it's the way to go. 

Hope your fix will be accepted officially and released as the new version of `gatsby-remark-katex`.

**Comment by LekoArts** [comment] 2021-05-17 08:01
Closing as a duplicate of https://github.com/gatsbyjs/gatsby/issues/30865

**Closed by LekoArts** 2021-05-17 08:01 UTC
Labels: status: triage needed, type: bug
