### ISSUE TITLE
Can't resolve "gatsby-theme-blog/src/gatsby-plugin-theme-ui/index" 

### ISSUE THREAD

**Issue by twtwtw-gj** [gatsbyjs/gatsby#27628] opened 2020-10-24 02:41 UTC
## Description

I read this page and placticed it.
But in this page, the build failuring was facing me and I couldn't do it.

https://github.com/gatsbyjs/gatsby/blame/a62927522d231e1fa7a726d748a8ef3f7db824d9/docs/tutorial/using-multiple-themes-together.md#L189

### Actual result

```
 ERROR #98124  WEBPACK

Generating SSR bundle failed

Can't resolve 'gatsby-theme-blog/src/gatsby-plugin-theme-ui/index' in '<my-repository>\src\gatsby-plugin-theme-ui'

If you're trying to use a package make sure that 'gatsby-theme-blog/src/gatsby-plugin-theme-ui/index' is installed. If you're trying to use a local file make sure that the path is correct.

```

I checked the folder "gatsby-plugin-theme-ui", but it had only the file named "conponents.js".
There was no file named "index.js".

### Environment

Windows 10

Gatsby CLI version: 2.12.111
Gatsby version: 2.24.80

**Comment by LekoArts** [comment] 2020-10-26 08:55
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by twtwtw-gj** [comment] 2020-10-27 11:21
Thank you for sending the message.

This work to make a minimum reproduction takes time.

My practice of this tutorial is uploaded in this page.

https://github.com/twtwtw-gj/multiple-themes

My comments in this repository are written in Japanese. But, I think, many programmers can understand  roughly what I did.

At a later date, I will make a minimal reproduction.

**Comment by vladar** [comment] 2020-11-06 12:01
Hi @twtwtw-gj. I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please file a new issue and link the reproduction there. Thanks!

**Closed by vladar** 2020-11-06 12:01 UTC
Labels: status: needs reproduction, type: bug
