### ISSUE TITLE
gatsby-image low quality webp

### ISSUE THREAD

**Issue by bogdansoare** [gatsbyjs/gatsby#24615] opened 2020-05-29 13:35 UTC
## Description

When using the [webp format](https://using-gatsby-image.gatsbyjs.org/prefer-webp/), the quality is degraded compared to a png or jpg format.

### Steps to reproduce

Open gatsby-image's [demo website](https://using-gatsby-image.gatsbyjs.org/prefer-webp/) in chrome/firefox and safari(a browser that doesn't support web so it defaults to png/jpg) and compare the quality difference.

Here is a screenshot, left chrome, right safari:
<img width="961" alt="Screenshot 2020-05-29 at 16 28 59" src="https://user-images.githubusercontent.com/2750170/83265492-43bac200-a1ca-11ea-8f07-1336030503ad.png">

### Expected result

The webp quality to be similar to the png/jpg one.

### Actual result

The webp quality is worse.

**Comment by stackrole-dev** [comment] 2020-05-29 15:00
Hi @bogdansoare,

You can define a quality while querying. like this 
![image](https://user-images.githubusercontent.com/64824192/83274263-2fd38800-a1eb-11ea-9c83-d2522d7e0d8b.png)

I hope this helps you.

**Comment by bogdansoare** [comment] 2020-05-29 15:45
I know about the `webpQuality`, but if I bump it up to say `80` then the webp image file size is similar to the png at quality `50` and also the png looks better, which defeats the whole purpose of webp in the first place.

My point is, I think having the same quality for `png` and `webp` should result in a same quality looking image which is not the case

**Comment by polarathene** [comment] 2020-06-30 12:34
Seems related to [this PR](https://github.com/gatsbyjs/gatsby/pull/25325).

Images processed by sharp are being processed a 2nd time via imagemin, which inherits the quality setting, thus the lower it is(50 by default), the more compounding the impact is likely to be. For my own tests, the additional file size reduction wasn't worth the increased quality degradation via artifacting(using a lower quality value would be better in a single pass instead).

> My point is, I think having the same quality for png and webp should result in a same quality looking image which is not the case

While understandable, the quality settings afaik are specific to the separate image format encoders, so it's technically best to match those. The default quality setting could perhaps try normalize visual quality across the formats, but I'm not sure how feasible that actually is to do right..

**Comment by AbdallahAbis** [comment] 2021-03-25 16:23
@bogdansoare Any workaround, Please?

**Comment by ascorbic** [comment] 2021-04-06 08:36
I'm closing this as it is related to the old version of the plugin. If anybody can reproduce it with the new image plugin then please open a new issue.

**Closed by ascorbic** 2021-04-06 08:36 UTC
Labels: topic: images/media, type: bug

**Comment by Nikhil-Ladha** [comment] 2022-01-31 09:24
> I'm closing this as it is related to the old version of the plugin. If anybody can reproduce it with the new image plugin then please open a new issue.

By new plugin, do you mean version `2.x` onwards?
Because, we are facing this issue in `1.14.2` itself.

**Comment by AbdallahAbis** [comment] 2022-01-31 09:49
@Nikhil-Ladha By the new plugin he means Gatsby-plugin-image, the issue is on gatsby-image.

**Comment by Nikhil-Ladha** [comment] 2022-01-31 09:52
Ok, we are using `gatsby-plugin-image` itself and can see the quality degrade.
Though, this happens only with the use of the `StaticImage` component.
