### ISSUE TITLE
Hot reload broken since 2.24.0

### ISSUE THREAD

**Issue by tu4mo** [gatsbyjs/gatsby#28202] opened 2020-11-20 10:11 UTC
## Description

Hot reload fails to show changes in an outside library (imported in Gatsby pages).

### Steps to reproduce

Make a change in outside library. I use a separate Yarn workspace for the library. Rollup for bundling. Gatsby detects the change (from what I can understand from the terminal) when library gets rebuild, but fails to show changes in browser.

I have a feeling like there is some race condition happening; parts of the library gets built, Gatsby notices the change and starts to rebuild pages, and during that time the rest of the library gets built (takes about 2 seconds) and Gatsby fails to notice that.

### Expected result

Everything updates like in 2.24.0.

### Actual result

Changes does not get updated in the browser. At some point the whole page hangs and I have to restart the server.

### Environment

```
  System:
    OS: macOS 11.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 87.0.4280.67
    Edge: 87.0.664.41
    Firefox: 82.0.3
    Safari: 14.0.1
```

**Comment by vladar** [comment] 2020-11-20 11:55
I think it is a duplicate of #27609 Let's keep tracking it there.

**Closed by vladar** 2020-11-20 11:55 UTC
Labels: status: triage needed, type: bug
