### ISSUE TITLE
v2 docs search modal cut off on smaller screens

### ISSUE THREAD

**Issue by kellylawrence** [gatsbyjs/gatsby#6221] opened 2018-06-28 21:18 UTC
## Description

When viewing the v2 docs site at https://next.gatsbyjs.org/docs, while using the the search field, the pop-up window appears to be cutoff on smaller screens (A 13" Macbook Pro for example), or in smaller browser windows, when there is a large amount of search result content.

![screen shot 2018-06-28 at 6 01 23 pm](https://user-images.githubusercontent.com/815248/42060742-382ca876-7afe-11e8-8464-f41e72f8c506.png)

### Steps to reproduce

- Visit https://next.gatsbyjs.org/docs on a device with a small screen (ex: 13" Macbook Pro), or resize the browser window viewport to a small height (Below 760px in this case)
- Enter a query/term into the search field (ex: `styling`) that might result in a large amount of returned results
- View that the bottom of the modal appears to be cutoff

### Expected result

I would expect the search modal to have a vertical scrollbar or some other way to reduce the overall height of the modal at smaller screen/browser window sizes.

### Actual result

Content underneath the **Reference** heading appears to be cutoff, and I was unable to see what that additional content/search results might be.

### Environment

13" Macbook Pro
macOS Sierra v10.12.6
1280x800 resolution
Google Chrome v67.0.3396.99

**Comment by m-allanson** [comment] 2018-06-29 11:58
Thanks for the detailed report @kellylawrence. I can confirm what you're seeing.  It looks like the search form [should constrain itself to the height of the browser window](https://github.com/gatsbyjs/gatsby/blob/c1d86bc6080116683eb4c4959182c0bbe25cc64d/www/src/components/search-form.js#L23), but that doesn't seem to be happening.

If you (or anyone else) would like to take a look at fixing this, you can get a local copy of the site running by following [these contribution docs](https://www.gatsbyjs.org/docs/how-to-contribute/#contributing-to-the-documentation).

Then [enable debug mode for the search form](https://github.com/gatsbyjs/gatsby/blob/c1d86bc6080116683eb4c4959182c0bbe25cc64d/www/src/components/search-form.js#L281) here. This stops the search results from auto-closing.

**Comment by m-allanson** [comment] 2018-06-29 12:00
Note that this happens on pages that have a fixed header - on the [homepage](https://www.gatsbyjs.org/) and [blog overview page](https://www.gatsbyjs.org/blog/) you can still scroll the page to see the rest of the results.

**Comment by m-allanson** [comment] 2018-06-29 12:03
While I'm thinking about this - it might be easier to modify these styles be restyling that dropdown from scratch. That would mean [removing the default DocSearch CSS](https://github.com/gatsbyjs/gatsby/blob/f41eb2a58d8a8d5e84663bb6a9080aa6b3d530df/www/gatsby-browser.js) and then rewriting [the CSS that overrides the DocSearch CSS](https://github.com/gatsbyjs/gatsby/blob/c1d86bc6080116683eb4c4959182c0bbe25cc64d/www/src/components/search-form.js#L15).

**Comment by wuweiweiwu** [comment] 2018-07-03 23:36
@m-allanson I'd be willing to pick this up!

**Comment by m-allanson** [comment] 2018-07-04 15:13
That would be great @wuweiweiwu!

**Closed** 2018-10-14 18:00 UTC
Labels: status: help wanted, type: bug
