### ISSUE TITLE
Error: Invariant Violation: Encountered an error trying to infer a GraphQL typ  e for: `products___NODE`.

### ISSUE THREAD

**Issue by pradeepsingh37** [gatsbyjs/gatsby#26139] opened 2020-07-30 14:06 UTC
## Description

Describe the issue that you're seeing.

https://www.gatsbyjs.org/docs/building-an-ecommerce-site-with-shopify/

Making e-commerce site with Shopify. Using this link.

i am trying to implement it with my store but facing an issue as mentioned below in Actual result.

### Expected result

Not able to fetch the data

### Actual result

Error: Invariant Violation: Encountered an error trying to infer a GraphQL typ  e for: `products___NODE`. There is no corresponding node with the `id` field m  atching: "Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzI2MDY4MDM4NDU0MQ==,S  hopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzI5MjkwMTcxNTk5Nw==,Shopify__Pro  duct__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzIxNTI0OTg1OTM4OTU=,Shopify__Product__Z2lkO  i8vc2hvcGlmeS9Qcm9kdWN0LzQzODg4NjU2Mzg2OQ==,Shopify__Product__Z2lkOi8vc2hvcGlm  eS9Qcm9kdWN0LzIxNTYzODM4OTU2NTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN  0LzI5MjkwMjk5Mzk0OQ==,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzI2MDY3OD  Y0NzgzNw==,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQzODg4MjkyNjYyMQ==,  Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzIxNTMxNzM4MTEzMDM=,Shopify__Pr  oduct__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQyNjI5NzA3ODU4OTU=,Shopify__Product__Z2lk  Oi8vc2hvcGlmeS9Qcm9kdWN0LzIxNTMxMzAyMjk4NjM=,Shopify__Product__Z2lkOi8vc2hvcGl  meS9Qcm9kdWN0LzQzNDU3OTcwMTc3MDM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdW  N0LzIxNTY1NTgxODg2NDc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQzNjE1O  DY5MzQwNQ==,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQyODU3MDIyNDI0MDc=  ,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzM4ODQxNzQ2MDY0Mzk=,Shopify__P  roduct__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzIxNTYzMTM5MzU5NzU=,Shopify__Product__Z2l  kOi8vc2hvcGlmeS9Qcm9kdWN0LzI2MDY4MjM1MDYyMQ==,Shopify__Product__Z2lkOi8vc2hvcG  lmeS9Qcm9kdWN0LzMzNDY0NzEzMjE4OQ==,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kd  WN0LzQyNzAzMjExMDcwNDc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE2  MDk2MDAxMDM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE2MTA2MTU5MTE  =,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE2MjMyOTcxMjc=,Shopify__  Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE2MjM3ODg2NDc=,Shopify__Product__Z2  lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE2MjQyODAxNjc=,Shopify__Product__Z2lkOi8vc2hvc  GlmeS9Qcm9kdWN0LzQ1MzE2MjU2NTY0MjM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9k  dWN0LzQ1MzIzNTI0ODM0MzE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzQ  xOTU4ODAwMzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzUzNTMyNzg1Nj  c=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NDI1NjExMjQ0NTU=,Shopify_  _Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ2NDYwMTg1NDc4MTU=,Shopify__Product__Z  2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzIxNTMxMDQ0NzQyMTU=,Shopify__Product__Z2lkOi8vc2hv  cGlmeS9Qcm9kdWN0LzQzODg3ODQwNDYzNw==,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9  kdWN0LzMzNDY5NTQzMjIyMQ==,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1Mz  E2NDI0MDA4NzE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzI1NDE3OTAxNjczM  w==,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzI1NDE3OTg2ODcwMQ==,Shopify  __Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE2NDAwNzQzNDM=,Shopify__Product__  Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE2NDA4OTM1NDM=,Shopify__Product__Z2lkOi8vc2h  vcGlmeS9Qcm9kdWN0LzQ1MzE2NDEyNTM5OTE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm  9kdWN0LzI5MjkwMjczMTgwNQ==,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1M  zE2NDE5NzQ4ODc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjM0MDExNzky  Mzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzMzNDcwMzgyMDgyOQ==,Shopif  y__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE2NDc5MDU4OTU=,Shopify__Product_  _Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjM0MTUwNDAxMDM=,Shopify__Product__Z2lkOi8vc2  hvcGlmeS9Qcm9kdWN0LzI5Mjg5OTcxNzE0OQ==,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qc  m9kdWN0LzQzNDU3NzcwMjkyMjM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQw  MDY3NDkwNDQ4Mzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE2NTAxMzQ  xMTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE2NDY3OTE3ODM=,Shopi  fy__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjM0OTUyMjMzOTk=,Shopify__Product  __Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQyODU3MDcyMjMxNDM=,Shopify__Product__Z2lkOi8vc  2hvcGlmeS9Qcm9kdWN0LzQ1MzE2NTEyNDgyMzE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Q  cm9kdWN0LzQ1MzE2NTI3NTU1NTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ  1MzE1MTU3NTI1NTE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjM1MDY2OT  IxOTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjI4NTE3NTgxODM=,Shop  ify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQzMzgwODU3NTcwMzE=,Shopify__Produc  t__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE2MTIxODg3NzU=,Shopify__Product__Z2lkOi8v  c2hvcGlmeS9Qcm9kdWN0LzQ1MzE2MTcxMDM5NzU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9  Qcm9kdWN0LzM5MzkyMTUyNzgzNw==,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0Lz  Q1NjI4NTczMjg3NDM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjI0ODk0M  Dk2Mzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjI3MjgxNTcyODc=,Sho  pify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjI4NjM3NTEyNzE=,Shopify__Produ  ct__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjQyODk0MjE0MTU=,Shopify__Product__Z2lkOi8  vc2hvcGlmeS9Qcm9kdWN0LzQ1MzIzMDk3MjExOTE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS  9Qcm9kdWN0LzQ1MzE2MTQ4NzU3NTE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0L  zQ1NjQzMDAzNjU5Mjc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjI3MjYw  NjAxMzU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjQzMTE4MDE5NTk=,Sh  opify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjQ0MjgwNjI4MjM=,Shopify__Prod  uct__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjQzMzkwNjQ5MzU=,Shopify__Product__Z2lkOi  8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjQ0MjU2Mzc5OTE=,Shopify__Product__Z2lkOi8vc2hvcGlme  S9Qcm9kdWN0LzQ1NjI4NjYyNDE2Mzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0  LzQ1MzE2MTUyMDM0MzE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjI3MzE  5NTgzNzU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjQyOTU4NDM5NDM=,S  hopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjI4NjEwMzE1Mjc=,Shopify__Pro  duct__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjI3MzY3NzUyNzE=,Shopify__Product__Z2lkO  i8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjI2NzY5NDA5MDM=,Shopify__Product__Z2lkOi8vc2hvcGlm  eS9Qcm9kdWN0LzQ1NjQ0MzA4NDgxMDM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN  0LzQ1NjQ0MjY4ODMxNzU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjQzND  I2MDM4Nzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjQzMzU1NTg3NTk=,  Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjQzMDQ2MjU3Njc=,Shopify__Pr  oduct__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjI4Njc0NTQwNTU=,Shopify__Product__Z2lk  Oi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjI4NjQ2MDMyMzk=,Shopify__Product__Z2lkOi8vc2hvcGl  meS9Qcm9kdWN0LzQ1NjI4NTQ1MTA2OTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdW  N0LzQ1MzE2MTgwMjE0Nzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE2M  jI0Nzc5Mjc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE2NDMyMjAwNzE=  ,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjU2OTIyODUwMzE=,Shopify__P  roduct__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE2MzcyNTYyOTU=,Shopify__Product__Z2l  kOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE2MTM4OTI3MTE=,Shopify__Product__Z2lkOi8vc2hvcG  lmeS9Qcm9kdWN0LzQ1MzE2MTI1MTY0NTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kd  WN0LzQ0ODMyMjI5Mjk1MTE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE1  NTExNzQ3NTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE1NTE5OTM5NTk  =,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjEyMTQ3MDE2NzE=,Shopify__  Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzIxNTY1MzQ4OTA1OTk=,Shopify__Product__Z2  lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NjIwMDAzMTQ0NzE=,Shopify__Product__Z2lkOi8vc2hvc  GlmeS9Qcm9kdWN0LzQ0ODMyNTYyMjE3OTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9k  dWN0LzQ1MzE0Mzk4OTQ2MzE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzM5Mzk  yMDkzODAxMw==,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE2NDQzOTk3MT  k=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE2NDI3Mjg1NTE=,Shopify_  _Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE2MjE3MjQyNjM=,Shopify__Product__Z  2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzE0MTQ0NDg1Nzg2NjM=,Shopify__Product__Z2lkOi8vc2hv  cGlmeS9Qcm9kdWN0LzQ1MzE2MjEwMDMzNjc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9  kdWN0LzQ1MzE1MTMzMjc3MTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NT  U0MTkwOTEwNDc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ2MzkyMzUxMTMwN  jM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQzNjQxNzY5NDkzNTE=,Shopify  __Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE1MjczODUxOTE=,Shopify__Product__  Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NTU0ODU1NDQ1NTE=,Shopify__Product__Z2lkOi8vc2h  vcGlmeS9Qcm9kdWN0LzQ1MzE2MTg1NDU3Njc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm  9kdWN0LzM5MzkxODg0MDg2MQ==,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1M  zE2MTkwNzAwNTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE0NTI3MDY5  MTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ2MzE1NzU4NTUyMDc=,Shopif  y__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE1MTg3MzQ0Mzk=,Shopify__Product_  _Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NTU0NTU5ODc4MTU=,Shopify__Product__Z2lkOi8vc2  hvcGlmeS9Qcm9kdWN0LzQzOTQ1MTg5Mzc3MDM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qc  m9kdWN0LzQzMjU5MDU4MjU4OTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1  MzE2NTcwNDgxNjc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE0NTg1NzI  zOTE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE2MTU5NTcwOTU=,Shopi  fy__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQzMjU5NDQ0MjY1OTk=,Shopify__Product  __Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NTc5MzY2ODkyNTU=,Shopify__Product__Z2lkOi8vc  2hvcGlmeS9Qcm9kdWN0LzQ1MzE1MzE4NzQ0MDc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Q  cm9kdWN0LzQ1NDczNDA0NjgzMjc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ  1NTc5MjIyNzEzMzU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzMwODYyMzgwMj  M5Nw==,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ2MzIwOTg5NjM1NTk=,Shop  ify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE1MTcxOTQzNDM=,Shopify__Produc  t__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MjU2MzE2MzU1NTk=,Shopify__Product__Z2lkOi8v  c2hvcGlmeS9Qcm9kdWN0LzQzOTQ1NDgxNjY3NTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9  Qcm9kdWN0LzQ1MzE0NzI1OTcwOTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0Lz  QzMjU4NDMzNzAwODc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NTc5MzA0M  zA1Njc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE1MDc1NjA1NTE=,Sho  pify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE1MDU1NjE3MDM=,Shopify__Produ  ct__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ2MzkyMTE3NDk0Nzk=,Shopify__Product__Z2lkOi8  vc2hvcGlmeS9Qcm9kdWN0LzMwODYxNzU3NjQ3Nw==,Shopify__Product__Z2lkOi8vc2hvcGlmeS  9Qcm9kdWN0LzQ2NDYwNDMyNTQ4ODc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0L  zQ1MzE0NzExNTUzMDM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE2NTMy  Nzk4NDc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE2NDMwNTYyMzE=,Sh  opify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE2MjkwOTcwNjM=,Shopify__Prod  uct__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQzOTQ1NDg1NTk5NzU=,Shopify__Product__Z2lkOi  8vc2hvcGlmeS9Qcm9kdWN0LzQ1NTc5Mjc4NzQ2NjM=,Shopify__Product__Z2lkOi8vc2hvcGlme  S9Qcm9kdWN0LzQ1NjU3MDE2MjM5MTE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0  LzQ1MzE2Mzc1NTEyMDc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQzMjU4NzE  2MTYxMDM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE0Nzc4NzI3NDM=,S  hopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQzMjU5OTU2NzU3NTE=,Shopify__Pro  duct__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE0ODA3ODkwOTU=,Shopify__Product__Z2lkO  i8vc2hvcGlmeS9Qcm9kdWN0LzQ2MzIwNzUyNzIyOTU=,Shopify__Product__Z2lkOi8vc2hvcGlm  eS9Qcm9kdWN0LzQ1MzE1ODEwMjY0MDc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN  0LzQzOTQ2MjI3Nzk0OTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ2NDU1MT  UxNjU3OTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ2MzIyNTkxOTkwNzk=,  Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQzOTQ1NDQwMDUyMjM=,Shopify__Pr  oduct__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ2NDIwMzMwMDg3NDM=,Shopify__Product__Z2lk  Oi8vc2hvcGlmeS9Qcm9kdWN0LzQ2MzIwNzI5MTI5OTk=,Shopify__Product__Z2lkOi8vc2hvcGl  meS9Qcm9kdWN0LzQ1MzE1ODEzNTQwODc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdW  N0LzQ1MzE1ODA3NjQyNjM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ2NDU1M  Dg4NDE1NzU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MTA3MDUzNTI4MDc=  ,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ2NDIwNTQ0MzkwMTU=,Shopify__P  roduct__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzUzNTIwMzMzODM=,Shopify__Product__Z2l  kOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE1NTAxMjYxODM=,Shopify__Product__Z2lkOi8vc2hvcG  lmeS9Qcm9kdWN0LzQ1MzE1NDg0MjIyNDc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kd  WN0LzQ1MzE1Mjk4MTAwMjM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MTA2  ODQ1NDUxMjc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MTA2OTgzMDc2ODc  =,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ2NDU1MTA5NzE0OTU=,Shopify__  Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MTA2OTE3ODY4NTU=,Shopify__Product__Z2  lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ2NDU1MDQ1NDg5Njc=,Shopify__Product__Z2lkOi8vc2hvc  GlmeS9Qcm9kdWN0LzQ2NDU1MDIzODYyNzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9k  dWN0LzQ2NDIwNjQ0OTg3OTE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ2NDI  wNDkyNjE2NzE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ2MzkyMjkzMTMxMj  c=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ2MzkyMjE2NDU0MTU=,Shopify_  _Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1NDAyNDE1NDMyNzE=,Shopify__Product__Z  2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE2NTk0NDAyMzE=,Shopify__Product__Z2lkOi8vc2hv  cGlmeS9Qcm9kdWN0LzQ1MzE2NTg4MTc2Mzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9  kdWN0LzQ1MzE2NTc2Mzc5OTE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1Mz  E2NTQ3MjE2Mzk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE2NDUwODc4N  Dc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE2MzMwMjkyMjM=,Shopify  __Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE2MTYyMTkyMzk=,Shopify__Product__  Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE1ODE0ODUxNTk=,Shopify__Product__Z2lkOi8vc2h  vcGlmeS9Qcm9kdWN0LzQ1MzE1NTg3MTEzOTk=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm  9kdWN0LzQ1MzE1NTA3MTYwMDc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1M  zE1NDk1NjkxMjc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE1MzA3NjAy  OTU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE1MjgzMzU0NjM=,Shopif  y__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE1MjAxNDM0NjM=,Shopify__Product_  _Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE1MTE1NTgyNDc=,Shopify__Product__Z2lkOi8vc2  hvcGlmeS9Qcm9kdWN0LzQ1MzE1MDk2MjQ5MzU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qc  m9kdWN0LzQ1MzE0ODczNzU0NjM=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1  MzE0ODYyNjEzNTE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE0ODUwNDg  5MzU=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE0ODQxOTY5Njc=,Shopi  fy__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE0ODI5ODQ1NTE=,Shopify__Product  __Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1MzE0ODE5MDMyMDc=,Shopify__Product__Z2lkOi8vc  2hvcGlmeS9Qcm9kdWN0LzQzMzgwMTc4Mjg5Njc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Q  cm9kdWN0LzE0MTQ0Mzk0MzYzOTE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ  zMzgwMTQxNTg5NTE=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzM2OTAyMDA3Nj  A2MQ==,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQyNjk4OTM1NTAxODM=,Shop  ify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzM4NTc2NzAyNzUxNzU=,Shopify__Produc  t__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ0MjY5MjM4MDI3Mjc=,Shopify__Product__Z2lkOi8v  c2hvcGlmeS9Qcm9kdWN0LzQ0MjY4MjkyNjcwNDc=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9  Qcm9kdWN0LzQ0NjkxMTM1MjAyMzE=".

### Environment

  System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 84.0.4147.105
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    gatsby: ^2.23.12 => 2.23.12 
    gatsby-source-shopify: ^3.2.25 => 3.2.25 
  npmGlobalPackages:
    gatsby-cli: 2.12.67

**Comment by vladar** [comment] 2020-08-03 08:34
Hi @pradeepsingh37 

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by vladar** [comment] 2020-08-31 16:58
Hi. I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please mention me in your reply and I'll reopen the issue. Thanks!

**Closed by vladar** 2020-08-31 16:58 UTC
Labels: status: needs reproduction, topic: GraphQL, type: bug
