### ISSUE TITLE
The example execution error in the tutorial

### ISSUE THREAD

**Issue by jiangry** [gatsbyjs/gatsby#26624] opened 2020-08-25 06:24 UTC
## Description

The example execution error in the tutorial :

### Steps to reproduce

The example execution error in the following tutorial :
https://www.gatsbyjs.com/tutorial/part-three/#creating-layout-components

### Expected result

gatsby develop run correct.

### Actual result

after 'gatsby develop' command, the following log is output:

 ERROR 

There was a problem loading the local develop command. Gatsby may not be installed. Perhaps you need to run "npm install"? Cannot find module 'react'
Require stack:
- /Users/reactworkspace/tutorial-part-three/node_modules/ink/build/instance.js
- /Users/reactworkspace/tutorial-part-three/node_modules/ink/build/render.js
- /Users/reactworkspace/tutorial-part-three/node_modules/ink/build/index.js
- /Users/reactworkspace/tutorial-part-three/node_modules/gatsby/node_modules/gatsby-cli/lib/reporter/loggers/ink/index.js
- /Users/reactworkspace/tutorial-part-three/node_modules/gatsby/node_modules/gatsby-cli/lib/reporter/start-logger.js
- /Users/tutorial-part-three/node_modules/gatsby/node_modules/gatsby-cli/lib/reporter/index.js
- /Users/reactworkspace/tutorial-part-three/node_modules/gatsby/dist/utils/detect-port-in-use-and-prompt.js
- /Users/reactworkspace/tutorial-part-three/node_modules/gatsby/dist/commands/develop.js
- /usr/local/lib/node_modules/gatsby-cli/lib/create-cli.js
- /usr/local/lib/node_modules/gatsby-cli/lib/index.js
- /usr/local/lib/node_modules/gatsby-cli/cli.js

### Environment

  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /Users/jiangry/.pyenv/shims/python
  Browsers:
    Chrome: 84.0.4147.135
    Firefox: 79.0
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.24.47 => 2.24.47 
    gatsby-plugin-typography: ^2.5.10 => 2.5.10 
  npmGlobalPackages:
    gatsby-cli: 2.12.88

**Comment by LekoArts** [comment] 2020-08-25 10:39
Hello and thanks for the issue!
This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/19064 and the issue outlines the reason and possible solutions.

The reason is an upstream issue with npm where it deletes packages from your `node_modules` folder (hence the missing react package) when the lock file is corrupted. Running `npm install` again should fix your issue (if that doesn't work, delete both the `node_modules` folder and the `package-lock.json` file). While we understand that this might be frustrating, we are currently still investigating how we can workaround this upstream issue.

**Closed by LekoArts** 2020-08-25 10:39 UTC
Labels: type: bug, type: documentation

**Comment by jiangry** [comment] 2020-08-26 05:48
Additional information：

Using yarn instead of NPM can work well.
