### ISSUE TITLE
A page component must export a React component for it to be valid. Please make sure this file exports a React component:

### ISSUE THREAD

**Issue by menglingyu** [gatsbyjs/gatsby#26651] opened 2020-08-27 02:32 UTC
## Description

gatsby develop is OK ,but  gatsby build fail

### Steps to reproduce
gatsby-config/siteMetadata.config.js
```
module.exports = {
  title: '国际广告平台',
  description: '国际广告平台',
  author: 'Blued Admin Team',
  pathPrefix: process.env.EXEC_ENV !== 'local' ? '/oversea-ad' : '',
  menuLinks: [
    ...
    {
      name: '插屏广告',
      path: '/insert',
      icon: 'desktop',
    },
  ]
}
```

src/pages/insert/index.jsx

```
import React, { useState } from 'react'

const InsertAd = () => {
  return <div />
}

export default InsertAd
```

```
> blued-admin-oversea-ad-site@0.0.1 build:local /Users/menglingyu/blued/blued-admin-oversea-ad-site
> EXEC_ENV=local gatsby build --prefix-paths

success open and validate gatsby-configs - 0.027s
success load plugins - 0.619s
success onPreInit - 0.032s
success delete html and css files from previous builds - 0.011s
success initialize cache - 0.029s
success copy gatsby files - 0.070s
success onPreBootstrap - 0.010s
success createSchemaCustomization - 0.004s
success source and transform nodes - 0.024s
success building schema - 0.214s
success createPages - 0.001s

 ERROR #11328

A page component must export a React component for it to be valid. Please make sure this file exports a React component:

undefined

not finished createPagesStatefully - 0.100s
```
### Expected result

build success
What should happen?

### Actual result
build fail
What happened.

### Environment

  System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.14.0/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.135
    Safari: 13.0.3
  npmPackages:
    gatsby: 2.24.7 => 2.24.7
    gatsby-plugin-env-variables: 1.0.1 => 1.0.1
    gatsby-plugin-less: 2.0.11 => 2.0.11
    gatsby-plugin-manifest: 2.4.19 => 2.4.19
    gatsby-plugin-react-helmet: 3.0.8 => 3.0.8
  npmGlobalPackages:
    gatsby-cli: 2.12.43

**Comment by vladar** [comment] 2020-08-28 20:31
Hi @menglingyu !

Sorry to hear you're running into an issue. I suspect that the issue is somewhere in other parts of your project (not in those snippets you've posted).  

To help us figure it out, it is incredibly helpful if you're able to publish your project or create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by Kevin-Carlos** [comment] 2020-08-31 05:07
@vladar [https://github.com/Kevin-Carlos/kevin-carlos.github.io](https://github.com/Kevin-Carlos/kevin-carlos.github.io) I too am having this issue, but as far as I know anything underneath src --> pages thats an actual page component follows convention if mine is any help and is reproducible

**Comment by ascorbic** [comment] 2020-09-10 11:17
Hi. I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. Thanks!

**Closed by ascorbic** 2020-09-10 11:17 UTC
Labels: status: needs reproduction, type: bug
