### ISSUE TITLE
Gatsby develop startup issue after an update

### ISSUE THREAD

**Issue by KresimirCosic** [gatsbyjs/gatsby#26438] opened 2020-08-13 09:07 UTC
## Description

Running `gatsby develop` ends in an error.

### Steps to reproduce

Changed the npm global packages install location to ~/$USER/.npm-global/ to resolve the npm permissions issue.

After downloading the tutorial templates as listed in the official documentation, they don't start anymore after an update 2 days ago (not sure which numeration it was).

Running `gatsby develop` resolves into an error.

### Expected result

To boot up the dev server.

### Actual result

Error code that a module is missing `gatsby-cli/lib/reporter`.

### Environment

kresimircosic@kresimircosic:/var/www/projects/hello-world$ gatsby info --clipboard

  System:
    OS: Linux 5.4 Pop!_OS 20.04 LTS
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.18.3 - /usr/bin/node
    npm: 6.14.7 - ~/.npm-global/bin/npm
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 79.0
  npmPackages:
    gatsby: ^2.24.41 => 2.24.41
  npmGlobalPackages:
    gatsby-cli: 2.12.87

**Comment by KresimirCosic** [comment] 2020-08-14 12:45
Hey,
not gonna lie this is pretty much a big priority for me since the CLI is utterly useless after the update. Is there any way I can help to speed up the process of debugging?

BR

**Comment by vladar** [comment] 2020-08-14 21:16
It is a duplicate of this issue: #26345

You need to upgrade from `gatsby@2.24.41` to `gatsby@^2.24.42`

Try deleting `package-lock.json` and run `npm install` again (if you use yarn - delete `yarn.lock` and run `yarn`). If the problem occurs in the CLI itself, run `npm install -g gatsby-cli`

**Closed by vladar** 2020-08-14 21:16 UTC
Labels: status: triage needed, type: bug
