### ISSUE TITLE
[gatsby-image] mobile image is cropped and have desktop image size

### ISSUE THREAD

**Issue by thomas-vermot-synolia** [gatsbyjs/gatsby#25004] opened 2020-06-15 14:33 UTC
## Description

My page content should have different images for desktop and mobile. And these images have different ratios.

I use the same structure as described in your documentation ( https://www.gatsbyjs.org/packages/gatsby-image/#art-directing-multiple-images ) and it works great on development mode.
When my site is build and I access to the page on desktop screen, it works well. The image change and is resized when the window is resized.

But when I access to the page on a small screen, the right image is displayed, but it has the proportions of the desktop image. I need to resize the screen to fix the image ratio.

The child div of .gatsby-image-wrapper has the padding that should be set on desktop instead of mobile. It looks like the padding is cached.

### Steps to reproduce

Display a fluid type image in your template and load your page with a small screen size.

### Expected result

The responsive image should be displayed with its specific size.
What should happen?

### Actual result
The responsive image has the dimensions of the desktop image

### Environment

  System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.20.1 - ~/.nvm/versions/node/v10.20.1/bin/node
    Yarn: 1.12.3 - /usr/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v10.20.1/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.97
    Firefox: 77.0.1
  npmPackages:
    gatsby: ^2.19.7 => 2.22.11
    gatsby-image: ^2.4.7 => 2.4.7
    gatsby-plugin-apollo: ^3.0.1 => 3.0.1
    gatsby-plugin-eslint: ^2.0.8 => 2.0.8
    gatsby-plugin-manifest: ^2.2.39 => 2.4.9
    gatsby-plugin-offline: ^3.0.32 => 3.2.7
    gatsby-plugin-react-helmet: ^3.1.21 => 3.3.2
    gatsby-plugin-react-redux: ^1.1.0-0 => 1.1.0-0
    gatsby-plugin-sass: ^2.1.30 => 2.3.2
    gatsby-plugin-sharp: ^2.4.3 => 2.6.9
    gatsby-source-filesystem: ^2.1.46 => 2.3.8
    gatsby-source-graphql-universal: 3.3.0 => 3.3.0
    gatsby-source-prismic-graphql: ^3.6.2 => 3.6.2
    gatsby-transformer-sharp: ^2.3.13 => 2.5.3
  npmGlobalPackages:
    gatsby: 2.22.9

**Comment by LekoArts** [comment] 2020-06-16 07:05
Thanks for the issue! This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/24748 and might be fixed by https://github.com/gatsbyjs/gatsby/pull/24811

**Closed by LekoArts** 2020-06-16 07:05 UTC
Labels: type: bug
