### ISSUE TITLE
Failed building development bundle of gatsby-starter-hello-world

### ISSUE THREAD

**Issue by benomatis** [gatsbyjs/gatsby#26023] opened 2020-07-25 21:06 UTC
## Description

Getting an error while trying to build the development bundle of gatsby-starter-hello-world without applying any change to it whatsoever.

Interestingly the starter, and my added modifications worked without a problem until I attempted to replace a plugin using yarn. I started to add a new plugin (gatsby-plugin-prefetch-google-fonts) while in another terminal tab removing another one (gatsby-plugin-google-fonts), and I started to see this error afterwards.

Removing the node_modules folder (`rm -rf node_modules`) and then reinstalling the app (`yarn install`) or using clean (`gatsby clean`) makes no difference.

I read somewhere that babel or eslint should not be installed globally, so I uninstalled them using npm (`npm uninstall -g babel...`) as yarn didn't do it (`yarn global remove babel` found nothing), but that changed nothing, the error is still the same.

I even uninstalled (`yarn global remove gatsby-cli`) and reinstalled (`yarn global add gatsby-cli`) gatsby-cli - issue still the same.

### Steps to reproduce

```shell
gatsby new my-hello-world-starter https://github.com/gatsbyjs/gatsby-starter-hello-world
cd my-hello-world-starter/
gatsby develop
```

### Expected result

Development build to successfully complete

### Actual result

Error shown in console

```shell
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Failed to load plugin 'jsx-a11y' declared in 'BaseConfig » /Users/benomatis/Sites/benomatis.com/gatsby2/node_modules/eslint-config-react-app/index.js': Cannot find module 'core-js-pure/stable/object/define-property'
Require stack:
- /Users/benomatis/Sites/benomatis.com/gatsby2/node_modules/@babel/runtime-corejs3/core-js-stable/object/define-property.js
- /Users/benomatis/Sites/benomatis.com/gatsby2/node_modules/aria-query/lib/index.js
- /Users/benomatis/Sites/benomatis.com/gatsby2/node_modules/eslint-plugin-jsx-a11y/lib/rules/aria-activedescendant-has-tabindex.js
- /Users/benomatis/Sites/benomatis.com/gatsby2/node_modules/eslint-plugin-jsx-a11y/lib/index.js
- /Users/benomatis/Sites/benomatis.com/gatsby2/node_modules/eslint/lib/cli-engine/config-array-factory.js
- /Users/benomatis/Sites/benomatis.com/gatsby2/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js
- /Users/benomatis/Sites/benomatis.com/gatsby2/node_modules/eslint/lib/cli-engine/cli-engine.js
- /Users/benomatis/Sites/benomatis.com/gatsby2/node_modules/eslint/lib/cli-engine/index.js
- /Users/benomatis/Sites/benomatis.com/gatsby2/node_modules/eslint/lib/api.js
- /Users/benomatis/Sites/benomatis.com/gatsby2/node_modules/eslint-loader/index.js
- /Users/benomatis/Sites/benomatis.com/gatsby2/node_modules/loader-runner/lib/loadLoader.js
- /Users/benomatis/Sites/benomatis.com/gatsby2/node_modules/loader-runner/lib/LoaderRunner.js
- /Users/benomatis/Sites/benomatis.com/gatsby2/node_modules/webpack/lib/NormalModule.js
- /Users/benomatis/Sites/benomatis.com/gatsby2/node_modules/webpack/lib/NormalModuleFactory.js
- /Users/benomatis/Sites/benomatis.com/gatsby2/node_modules/webpack/lib/Compiler.js
- /Users/benomatis/Sites/benomatis.com/gatsby2/node_modules/webpack/lib/webpack.js
- /Users/benomatis/Sites/benomatis.com/gatsby2/node_modules/gatsby/dist/utils/start-server.js
- /Users/benomatis/Sites/benomatis.com/gatsby2/node_modules/gatsby/dist/services/start-webpack-server.js
- /Users/benomatis/Sites/benomatis.com/gatsby2/node_modules/gatsby/dist/services/index.js
- /Users/benomatis/Sites/benomatis.com/gatsby2/node_modules/gatsby/dist/bootstrap/index.js
- /Users/benomatis/Sites/benomatis.com/gatsby2/node_modules/gatsby/dist/commands/develop-process.js
- /Users/benomatis/Sites/benomatis.com/gatsby2/.cache/tmp-41433-tJ8xTDy7blck

File: .cache/app.js

failed Building development bundle
```

### Environment

```shell
% gatsby info --clipboard 

  System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.89
    Firefox: 74.0.1
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.23.12 => 2.24.11
```

**Comment by benomatis** [comment] 2020-07-26 22:20
Update! I just used `yarn upgrade` in a different gatsby project (based on the default starter), and it started to give the same error! It worked perfectly fine until I ran `yarn upgrade`, and I do remember I did the same in the above case at some point as well. Now how do I roll that back...?

**Comment by LekoArts** [comment] 2020-07-28 05:20
Thank you for opening this!

The issues you're describing don't sound like a bug in Gatsby but like corrupted dependency trees/node_modules folder. This can happen for multiple reasons, e.g. mixing npm & yarn in the same project.

Maybe you have chosen `npm` as your default package manager at the first startup but since decided to use yarn. You can see your setting (and change it) here: https://www.gatsbyjs.org/docs/gatsby-cli/#how-to-change-your-default-package-manager-for-your-next-project

I followed your reproduction steps and couldn't see the error you're describing. Also, adding one package in one tab and removing another in the other tab at the same time also sounds like it might introduce problems.

Also, globally installed packages can do trouble, so you can list them like this:

npm: `npm list -g --depth 0`
yarn: `yarn global list`

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2020-07-28 05:20 UTC
Labels: type: bug

**Comment by benomatis** [comment] 2020-07-28 08:21
I feared this is going to be your answer... thanks anyway.

**Comment by benomatis** [comment] 2020-07-28 18:47
I have this:

```shell
% yarn global list
yarn global v1.22.4
info "create-react-app@3.4.1" has binaries:
   - create-react-app
info "expo-cli@3.22.3" has binaries:
   - expo
   - expo-cli
info "gatsby-cli@2.12.66" has binaries:
   - gatsby
info "react-devtools@3.6.0" has binaries:
   - react-devtools
info "react-native-git-upgrade@0.2.7" has binaries:
   - react-native-git-upgrade
info "react-native-rename@2.4.1" has binaries:
   - react-native-rename
info "syncyarnlock@1.0.19" has binaries:
   - syncyarnlock
✨  Done in 1.58s.
```

Now what...?

**Comment by benomatis** [comment] 2020-08-02 19:03
@LekoArts I appreciate this is not reproducible on your end or on any default setup, but unfortunately none of your pointers are helping me much, searching for the error message is also not yielding any results; I'm still getting the same message.

What I have tried since then:
- Removed all npm and yarn global packages
- While removing npm packages, I accidentally removed npm as well, so I reinstalled node using their binary distributed on their download page, just to be sure. The only 2 global packages that remained are node and npm.
  ```shell
  npm list -g --depth 0            
  /usr/local/lib
  ├── node@12.13.0
  └── npm@6.14.6
  ```
- yarn has always been my package manager for any recent project, and this is one as well, my config has yarn selected as the package manager.

I'm happy to troubleshoot myself, but I feel I ran into a dead-end, and cannot proceed trying to fix this. What would you do next?

**Comment by LekoArts** [comment] 2020-08-04 07:12
So what happens if you go into a newly created folder, and run:

```shell
yarn init -y
yarn add react react-dom gatsby
```

Add `"develop": "gatsby develop"` to the `scripts` section of the package.json and run `yarn develop`?

**Comment by benomatis** [comment] 2020-08-04 08:36
> So what happens if you go into a newly created folder, and run:
> 
> ```shell
> yarn init -y
> yarn add react react-dom gatsby
> ```
> 
> Create a valid React component at `src/pages/index.js`.
> 
> Add `"develop": "gatsby develop"` to the `scripts` section of the package.json and run `yarn develop`?

I get the exact same error :(

**Comment by benomatis** [comment] 2020-08-04 08:37
Hold on: I did it without creating a react component, let me try doing that then in a new folder...

**Comment by benomatis** [comment] 2020-08-04 08:42
Ok, tried it having a valid component in index.js, and still getting the same error, unfortunately.

**Comment by benomatis** [comment] 2020-08-04 08:43
Here is my component under `src/pages/index.js`:

```js
import React from 'react';

const IndexPage = () => <div>Test me</div>;

export default IndexPage;
```

**Comment by LekoArts** [comment] 2020-08-04 13:11
And what does `yarn global list` give you?

**Comment by benomatis** [comment] 2020-08-04 13:21
```shell
% yarn global list
yarn global v1.22.4
✨  Done in 0.03s.
```

**Comment by benomatis** [comment] 2020-08-10 11:17
Any pointers? What would be the next thing you'd do in this case @LekoArts?

**Comment by chenxizhang** [comment] 2021-07-02 01:35
same issue here

**Comment by chenxizhang** [comment] 2021-07-02 01:36
ERROR in Failed to load plugin 'jsx-a11y' declared in 'BaseConfig »
D:\temp\qiangzi\node_modules\eslint-config-react-app\index.js': Cannot find module
'core-js-pure/stable/object/define-property'
Require stack:
- D:\temp\qiangzi\node_modules\@babel\runtime-corejs3\core-js-stable\object\define-property.js
- D:\temp\qiangzi\node_modules\aria-query\lib\index.js
- D:\temp\qiangzi\node_modules\eslint-plugin-jsx-a11y\lib\rules\aria-activedescendant-has-tabindex.js
- D:\temp\qiangzi\node_modules\eslint-plugin-jsx-a11y\lib\index.js
- D:\temp\qiangzi\node_modules\@eslint\eslintrc\lib\config-array-factory.js
- D:\temp\qiangzi\node_modules\@eslint\eslintrc\lib\index.js
- D:\temp\qiangzi\node_modules\eslint\lib\cli-engine\cli-engine.js
- D:\temp\qiangzi\node_modules\eslint\lib\cli-engine\index.js
- D:\temp\qiangzi\node_modules\eslint\lib\api.js
- D:\temp\qiangzi\node_modules\eslint-webpack-plugin\dist\getESLint.js
- D:\temp\qiangzi\node_modules\eslint-webpack-plugin\dist\linter.js
- D:\temp\qiangzi\node_modules\eslint-webpack-plugin\dist\index.js
- D:\temp\qiangzi\node_modules\eslint-webpack-plugin\dist\cjs.js
- D:\temp\qiangzi\node_modules\gatsby\dist\utils\webpack-utils.js
- D:\temp\qiangzi\node_modules\gatsby\dist\utils\webpack.config.js
- D:\temp\qiangzi\node_modules\gatsby\dist\utils\start-server.js
- D:\temp\qiangzi\node_modules\gatsby\dist\services\start-webpack-server.js
- D:\temp\qiangzi\node_modules\gatsby\dist\services\index.js
- D:\temp\qiangzi\node_modules\gatsby\dist\state-machines\develop\services.js
- D:\temp\qiangzi\node_modules\gatsby\dist\state-machines\develop\index.js
- D:\temp\qiangzi\node_modules\gatsby\dist\commands\develop-process.js
- D:\temp\qiangzi\.cache\tmp-16532-Js9ja0MnWuDg
