### ISSUE TITLE
Gatsby Plugin Image

### ISSUE THREAD

**Issue by studiohic** [gatsbyjs/gatsby#30115] opened 2021-03-08 22:33 UTC
I’ve been using Gatsby Plugin Image and all has been working great. Ive been testing the site I’ve built and am having some weird results in Firefox where images are completely disappearing on widths below around 600px. Firefox stated that using will-change might cause some problems but can’t imagine this would make images completely disappear. Working fine in Safari and Chrome. I have checked the console and had the following come up in all browsers

Warning: Failed prop type: The prop `alt` is marked as required in `MainImage`, but its value is `undefined`.
MainImage

Warning: Failed prop type: The prop `alt` is marked as required in `Y`, but its value is `undefined`.
Y
Picture
MainImage
D

I tested on a fresh install and this error was also coming up so I don’t think an issue with my code.

Has anyone else experienced the same and is there a fix? 

Thanks

**Comment by KyleAMathews** [comment] 2021-03-09 01:54
Can you share your site or a reproduction.

**Comment by studiohic** [comment] 2021-03-11 11:53
Just coming back to you on this. Images are all working fine in Firefox except when layout is marked as FULL_WIDTH on browser width less than around 600px which is when they disappear. I'll work on a reproducible test shortly...

**Comment by vsimak** [comment] 2021-03-13 22:15
Having the same issue.
I can't repro at the moment, and the website is an pre-launch ecommerce website I can't share public.
Can share to a core team member if neeed.

The behavior is:
on a non-visited page images stop showing, and than all other non-visited pages don't show images, until a page visited where images were shown is loaded.

In DOM, gatsby image wrapper div's aren't created at all when images don't show.

Also in Gatsby Cloud during build 2 errors showed since upgraded to v3 and gatsby-plugin-image

![image](https://user-images.githubusercontent.com/737041/111051255-0a4dfd00-8452-11eb-90d9-1c42e453a779.png)

**Comment by studiohic** [comment] 2021-03-17 10:33
I have worked out that if images are set to layout: FULL_WIDTH then this causes issues on Chrome, Firefox and Safari for Mac, all latest versions, where the images dissapear and you are left with the alt title. Images are being pulled in from WordPress so I'm using <GatsbyImage> instead of <StaticImage>.

**Comment by LekoArts** [comment] 2021-03-26 08:31
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-03-26 08:31 UTC
Labels: status: needs reproduction, topic: images/media, type: bug

**Comment by therealgilles** [comment] 2022-07-01 20:55
I am experiencing the same issue. From the error message, I would assume that an image on WordPress is missing its `alt` property. @KyleAMathews: Would it be possible just to add the image URL to the message so that it is easy to identify which one is causing the issue? or let me know if my guess is off.

```JS
 ERROR 

Warning: Failed prop type: The prop `alt` is marked as required in `MainImage`, but its value is `undefined`.
    at MainImage
    at H (.../node_modules/gatsby-plugin-image/dist/gatsby-image.js:1:10863)

 ERROR 

Warning: Failed prop type: The prop `alt` is marked as required in `W`, but its value is `undefined`.
    at W (.../node_modules/gatsby-plugin-image/dist/gatsby-image.js:1:7410)
    at _ (.../node_modules/gatsby-plugin-image/dist/gatsby-image.js:1:7671)
    at MainImage
    at D (.../node_modules/gatsby-plugin-image/dist/gatsby-image.js:1:10511)
    at div
    at H (.../node_modules/gatsby-plugin-image/dist/gatsby-image.js:1:10863)

success  gatsby-source-wordpress  MediaItem - 13.984s - fetched 103
```
