### ISSUE TITLE
Images not showing up in allWordpressWpMedia

### ISSUE THREAD

**Issue by taylorchance** [gatsbyjs/gatsby#21886] opened 2020-03-01 20:11 UTC
I have an important issue where I need to query all images on my site. At first, it was working but it wasn't returning all the images. Everytime it only returned 35 out of about 300 images uploaded. I wanted to test on a fresh database with no images, tried different methods of uploaded files, tried directly to the media library, tried uploading as a posts featured image, attached to a custom posts ACF field etc etc.

The newly uploaded images simply wouldn't appear in my graphql query. Does anybody have any clue why?

**Comment by TylerBarnes** [comment] 2020-03-03 07:16
Hi @taylorchance !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by danabrit** [comment] 2020-05-29 23:38
Closing due to no reproduction.

**Closed by danabrit** 2020-05-29 23:38 UTC
Labels: status: needs reproduction, topic: WordPress, type: bug
