### ISSUE TITLE
Error #98123 Webpack (Generating SSR bundle failed) - helper-compilation-targets

### ISSUE THREAD

**Issue by itejman** [gatsbyjs/gatsby#21664] opened 2020-02-21 23:28 UTC
### Description

I create `gatsby new hello` and I go to the folder hello `cd hello` and run `gatsby develop`, them I get error:

```
ERROR #98123  WEBPACK
Generating SSR bundle failed

[BABEL] /home/irek/node-p/gatsby/hello/.cache/develop-static-entry.js: Package exports for '/home/irek/node-p/gatsby/hello/node_modules/@babel/helper-compilation-targets' do not define a '.' subpath

File: .cache/develop-static-entry.js
```

### Steps to reproduce

I found similar requests but it didn't work. I updated my `helper-compilation-targets`, `gatsby-cli`
It seems that the file causing this is file: `.cache/develop-static-entry.js` and with his subpath.

### Expected result

Gatsby should start my localhost.

### Actual result

Error #98123 WEBPACK
Generating SSR bundle failed

### Environment

```
System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 13.1.0 - ~/.nvm/versions/node/v13.1.0/bin/node
    Yarn: 1.22.0 - ~/.nvm/versions/node/v13.1.0/bin/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v13.1.0/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.116
    Firefox: 73.0
  npmPackages:
    gatsby: ^2.19.7 => 2.19.7
    gatsby-image: ^2.2.39 => 2.2.39
    gatsby-plugin-manifest: ^2.2.39 => 2.2.39
    gatsby-plugin-offline: ^3.0.32 => 3.0.32
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.21
    gatsby-plugin-sharp: ^2.4.3 => 2.4.3
    gatsby-source-filesystem: ^2.1.46 => 2.1.46
    gatsby-transformer-sharp: ^2.3.13 => 2.3.13
  npmGlobalPackages:
    gatsby-cli: 2.8.30

```

**Comment by itejman** [comment] 2020-02-22 19:22
I upgrade `node` version to `13.7+` and it solved problem.

**Comment by varlevi** [comment] 2020-03-08 01:11
Hi! I'm on node 13.10.1 and I'm still having this exact problem. 

Environment

```
System:
    OS: Raspian Buster
  Binaries:
    Node: 13.10.1
    npm: 6.13.7
  Browsers:
    Vivaldi: 2.8.1664.44
  npmGlobalPackages:
    gatsby-cli: 2.10.2
```

Following this error is printed:

```
Generating SSR bundle failed

[BABEL] /home/<user>/Documents/programming/personal_website/web/.cache/develop-static-entry.js: No "exports" main resolved in /home/<user>/Documents/programming/personal_website/web/node_modules/@babel/helper-compilation-targets/package.json

File: .cache/develop-static-entry.js
```

**Comment by itejman** [comment] 2020-03-08 11:42
@varlevi you need node version min. 13.7+

**Comment by Jetisr** [comment] 2020-03-09 09:08
I'm also having this issue with Node version 13.10.1, and Gatsby CLI version 2.10.2.

**Comment by varlevi** [comment] 2020-03-09 15:24
Looks like there's quite a few closed issues relating to this error, all taking place in somewhat different scenarios and being solved in different ways. Check out #22066, #20225, #19922,  and #17557.

**Comment by mlittlec** [comment] 2020-03-09 22:38
I too was having the same problem using the latest Node version (13.10.1) on my Ubuntu setup.  I eventually resolved this by 'downgrading' to the "Stable" version of Node (currently 12.16.1) by executing this command:

 _sudo n stable_

Now when I run _gatsby develop_ everything completes successfully.  So it appears this is an issue with the "Current" Node version (13.10.1).

I hope this helps others get Gatsby working :-)

**Comment by jamescrowley** [comment] 2020-03-09 22:39
I'm also hitting this issue, with Node 13.10.1

**Comment by varlevi** [comment] 2020-03-10 01:56
Yes. This works for me as well. Unfortunate we can't use the more recent version, but I'm sure the node team is working on it.

**Comment by MGT360124** [comment] 2020-03-12 02:46
i just use node version 8.12.0 without this problem

**Comment by richardnguyen99** [comment] 2020-03-16 06:39
I had the exact problem but solved by upgrading package via `yarn upgrade`

**Comment by elias-thok** [comment] 2020-03-21 14:14
Same problem here, started today all of a sudden.
Error appears in node version 13.11, NPM-6.14.

`Generating SSR bundle failed

/Users/test/repo/.cache/loader.js: Unknown helper createSuper

File: .cache/loader.js`

Switching between node versions with n, as well as deleting node_modules didn't change anything.

**Comment by rjpizarro** [comment] 2020-03-25 19:40
Same problem with Node 12.6.1
I deleted .cache and node_modules and nothing happened. 
Deleting package-lock.json did the trick.

Thanks @elias-thok

**Comment by jamesdbruner** [comment] 2020-04-28 21:25
Deleting your `package-lock.json` shouldn't be considered a solution and can have unintended consequences if you don't know what you're doing.

**Comment by varlevi** [comment] 2020-04-29 01:47
@jamesdbruner Good point. I think that this problem needs some further fleshing out.

**Comment by fenilgandhi** [comment] 2020-05-17 23:38
I am on node 14.2.0, the problem's still lurking.

**Comment by gpspake** [comment] 2020-06-12 00:16
`npx yarn upgrade` fixed this for me

**Comment by dandv** [comment] 2020-06-24 18:53
@itejman, please consider reopening this issue. It's <kbd>Closed</kbd> but it has no clear solution, and we don't even know the cause.

**Comment by itejman** [comment] 2020-06-24 19:51
> @itejman, please consider reopening this issue. It's Closed but it has no clear solution, and we don't even know the cause.

Ok.

**Comment by LekoArts** [comment] 2020-06-25 06:45
Please provide a [minimal reproduction][reproduction] then as otherwise this issue here isn't actionable.

[reproduction]: https://gatsby.dev/reproduction

**Comment by freiksenet** [comment] 2020-07-03 08:14
Hi! 

I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. 

Thanks!

**Closed by freiksenet** 2020-07-03 08:14 UTC
Labels: status: needs reproduction

**Comment by TheAdityaMoon** [comment] 2020-09-17 01:39
For anyone else having this issue, it seems that the only solution is deleting your package-lock.json file.

**Comment by sukantamaikap** [comment] 2021-01-31 08:54
I got into this mess by running :

```bash
yarn build
```

While `yarn develop` was running in another terminal.

**Comment by alexcanessa** [comment] 2021-03-19 10:39
If you add a custom babel file without using the gatsby preset, it will resolve in a similar error.
Make sure you follow [this docs](https://www.gatsbyjs.com/docs/how-to/custom-configuration/babel/).

**Comment by krislao** [comment] 2021-04-17 10:30
> 
> 
> If you add a custom babel file without using the gatsby preset, it will resolve in a similar error.
> Make sure you follow [this docs](https://www.gatsbyjs.com/docs/how-to/custom-configuration/babel/).

@alexcanessa your comment helped me fix my issue. thanks!
