### ISSUE TITLE
query dependency with wpChildren not updating with new child page

### ISSUE THREAD

**Issue by james-wfaa** [gatsbyjs/gatsby#32194] opened 2021-07-01 16:25 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I'm using gatsby-source-wordpress as a source plugin. In Gatsby node I use the createPages API to create pages from allWpPages, and inside my template I check for certain types of pages and on them I render a list of their child pages using the wpChildren.nodes array. 

When I remove or modify one of the child pages in WordPress, the parent page gets rebuilt correctly with the deletion or update. But when I add a new child page, the parent page does not get rebuilt (the child page itself does get built), and I have to do a cache-clearing cold build to get the new child page link to appear. 

### Reproduction Link

https://github.com/james-wfaa/gatsby-wordpress

### Steps to Reproduce

1. Run a page query that includes this against a WordPress page that has published child pages: wpChildren {
      nodes {
        ... on WpPage {
          id
          title
          uri
          dateGmt
          dayYear: date(formatString: "DD, YYYY")
          month: date(formatString: "MM")
          hideFromMenu {
            hideFromMenu
            fieldGroupName
          }
          menuOrder
          wpChildren {
            nodes {
              ... on WpPage {
                id
                title
                uri
                dateGmt
                dayYear: date(formatString: "DD, YYYY")
                month: date(formatString: "MM")
                hideFromMenu {
                  hideFromMenu
                  fieldGroupName
                }
                menuOrder
                wpChildren {
                  nodes {
                    ... on WpPage {
                      id
                      title
                      uri
                      dateGmt
                      dayYear: date(formatString: "DD, YYYY")
                      month: date(formatString: "MM")
                      hideFromMenu {
                        hideFromMenu
                        fieldGroupName
                      }
                      menuOrder
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
    
(I'm not sure that the nested wpChildren calls are relevant but they are in my code so I am including them)
2. In the template, map the array of child pages something like this:
 const newsList = items.map((subpage) => {
        return (<li key={subpage.id}><Link to={subpage.uri}>{subpage.title}</Link></li>)
}
3. Now add a new child page to the page this query is being run against
...

### Expected Result

The wpChildren query on the parent page will get rebuilt to reflect a new child in the array, and the page will be updated accordingly.

### Actual Result

Query does not get updated, and a cache-clearing build is required to get the new child page data onto the page.

### Environment

```shell
System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.7.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0.2
    Safari: 14.1.1
  npmPackages:
    gatsby: ^3.6.2 => 3.7.2 
    gatsby-background-image: ^1.5.3 => 1.5.3 
    gatsby-cli: ^3.6.0 => 3.7.1 
    gatsby-gravityforms-component: ^3.1.0 => 3.1.0 
    gatsby-omni-font-loader: ^1.3.0 => 1.3.1 
    gatsby-plugin-algolia: ^0.20.1 => 0.20.1 
    gatsby-plugin-gatsby-cloud: ^2.6.1 => 2.7.1 
    gatsby-plugin-google-tagmanager: ^3.6.0 => 3.7.1 
    gatsby-plugin-image: ^1.7.0 => 1.7.1 
    gatsby-plugin-manifest: ^3.6.0 => 3.7.1 
    gatsby-plugin-offline: ^4.6.0 => 4.7.1 
    gatsby-plugin-react-helmet: ^4.6.0 => 4.7.1 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.1 
    gatsby-plugin-robots-txt: ^1.6.2 => 1.6.2 
    gatsby-plugin-sharp: ^3.6.0 => 3.7.1 
    gatsby-plugin-sitemap: ^4.2.0 => 4.3.1 
    gatsby-plugin-styled-components: ^4.6.0 => 4.7.1 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.22 => 1.1.22 
    gatsby-plugin-zendesk-configurable-chat: ^1.0.1 => 1.0.1 
    gatsby-source-filesystem: ^3.6.0 => 3.7.1 
    gatsby-source-graphql: ^3.6.0 => 3.7.1 
    gatsby-source-gravityforms: ^1.0.17 => 1.0.17 
    gatsby-source-wordpress: 5.7.1 => 5.7.1 
    gatsby-transformer-sharp: ^3.6.0 => 3.7.1 
  npmGlobalPackages:
    gatsby-cli: 3.2.0
```

**Comment by LekoArts** [comment] 2021-07-19 09:50
Hi! I'll close this as a duplicate of https://github.com/gatsbyjs/gatsby/issues/32102 - please comment there. Thanks!

**Closed by LekoArts** 2021-07-19 09:50 UTC
Labels: type: bug
