### ISSUE TITLE
Build fails because a .cache/json file name is too long

### ISSUE THREAD

**Issue by benrobertsonio** [gatsbyjs/gatsby#25647] opened 2020-07-09 15:11 UTC
## Description

I have a build that fails on macOS and Linux environments because a generated cache filename is too long.

Error looks like this:

```
ENAMETOOLONG: name too long, open '/Users/ben/code/redacted/.cache/json/a-really-long-page-name-here..json'
 ERROR 

UNHANDLED REJECTION Cannot read property 'sourceMessage' of undefined

  TypeError: Cannot read property 'sourceMessage' of undefined
  
  - error-map.js:15 Object.text
    [vrdx-application]/[gatsby-cli]/lib/structured-errors/error-map.js:15:37
  
  - construct-error.js:30 constructError
    [vrdx-application]/[gatsby-cli]/lib/structured-errors/construct-error.js:30:18
  
  - reporter.js:128 Reporter.error
    [vrdx-application]/[gatsby-cli]/lib/reporter/reporter.js:128:59
  
  - reporter.js:116 
    [vrdx-application]/[gatsby-cli]/lib/reporter/reporter.js:116:48
  
  - Array.map
  
  - reporter.js:116 Reporter.error
    [vrdx-application]/[gatsby-cli]/lib/reporter/reporter.js:116:26
  
  - reporter.js:68 Reporter.panic
    [vrdx-application]/[gatsby-cli]/lib/reporter/reporter.js:68:34
  
  - create-cli.js:35 
    [vrdx-application]/[gatsby-cli]/lib/create-cli.js:35:85
```

The path name has 275 characters.

Is there a way we could limit these generated cache file names so that they work cross-OS?

### Steps to reproduce

I can provide an environment to reproduce.

### Expected result

Build should complete.

### Actual result

Build fails with error output from above.

### Environment

```
System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.8.0 - ~/.nvm/versions/node/v13.8.0/bin/node
    Yarn: 1.22.4 - /usr/local/Cellar/yvm/3.6.7/shim/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v13.8.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.116
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.22.21 => 2.23.22
    gatsby-image: ^2.2.7 => 2.2.41
    gatsby-link: ^2.2.22 => 2.2.29
    gatsby-plugin-eslint: ^2.0.4 => 2.0.8
    gatsby-plugin-google-tagmanager: ^2.1.3 => 2.1.25
    gatsby-plugin-i18next: ^1.1.7 => 1.1.10
    gatsby-plugin-react-helmet: ^3.1.1 => 3.1.22
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.2
    gatsby-plugin-resolve-src: ^2.0.0 => 2.0.0
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sharp: ^2.4.0 => 2.4.5
    gatsby-plugin-styled-components: ^3.1.1 => 3.1.19
    gatsby-react-router-scroll: ^3.0.2 => 3.0.2
    gatsby-source-contentful: ^2.3.14 => 2.3.14
    gatsby-source-filesystem: ^2.1.46 => 2.1.48
    gatsby-transformer-remark: ^2.6.3 => 2.6.51
    gatsby-transformer-sharp: ^2.3.0 => 2.3.14
```

**Comment by KyleAMathews** [comment] 2020-07-09 15:26
This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/4125

Fix is pretty straightforward if someone wants to pick it up https://github.com/gatsbyjs/gatsby/issues/4125#issuecomment-384741839

**Closed** 2020-07-09 15:26 UTC
Labels: status: triage needed, topic: reporter, type: bug
