### ISSUE TITLE
Website crashes while deploying !!!! WorkerError: Processing [Image Name]

### ISSUE THREAD

**Issue by CesySoder** [gatsbyjs/gatsby#26746] opened 2020-09-01 17:29 UTC
When I deploy my website, it crashes while processing an image, I never had this kind of error before, it just spawned out of the blue

gatsby build

```
> gatsby-starter-default@0.1.0 develop D:\ByrdByte Project\byrdbyte-landing-develop
> cross-env GATSBY_GRAPHQL_IDE=playground gatsby develop

success open and validate gatsby-configs - 0.090s

ERROR #11329

Your plugins must export known APIs from their gatsby-node.js.

See https://www.gatsbyjs.org/docs/node-apis/ for the list of Gatsby node APIs.

- The plugin gatsby-plugin-mailchimp@3.0.0 is using the API "modifyWebpackConfig" which is not a known API.

Some of the following may help fix the error(s):

- Rename "modifyWebpackConfig" -> "onCreateWebpackConfig"

success load plugins - 2.524s

success onPreInit - 0.057s

success initialize cache - 0.006s

success copy gatsby files - 0.247s

success onPreBootstrap - 0.020s

success createSchemaCustomization - 0.016s

success Checking for changed pages - 0.006s

success source and transform nodes - 0.905s

success building schema - 0.380s

success createPages - 0.004s

success Checking for changed pages - 0.003s

success createPagesStatefully - 0.596s

success update schema - 0.032s

success write out redirect data - 0.002s

success Build manifest and related icons - 0.201s

success onPostBootstrap - 0.211s

info bootstrap finished - 10.295s

success onPreExtractQueries - 0.002s

success extract queries from components - 1.237s

success write out requires - 0.172s

success run static queries - 0.136s - 4/4 29.33/s

success run page queries - 0.101s - 42/42 416.78/s

ERROR

Processing D:/ByrdByte Project/byrdbyte-landing-develop/src/assets/images/landing/visualphone2.png failed

Original error:

WorkerError: Processing D:/ByrdByte Project/byrdbyte-landing-develop/src/assets/images/landing/visualphone2.png failed

Original error:

- jobs-manager.ts:318 enqueueJob

[byrdbyte-landing-develop]/[gatsby]/src/utils/jobs-manager.ts:318:21

- task_queues.js:97 processTicksAndRejections

internal/process/task_queues.js:97:5

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! gatsby-starter-default@0.1.0 develop: `cross-env GATSBY_GRAPHQL_IDE=playground gatsby develop`

npm ERR! Exit status 1

npm ERR!

npm ERR! Failed at the gatsby-starter-default@0.1.0 develop script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Npm debug log

```
0 info it worked if it ends with ok

1 verbose cli [

1 verbose cli 'C:\\Program Files\\nodejs\\node.exe',

1 verbose cli 'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',

1 verbose cli 'run',

1 verbose cli 'develop'

1 verbose cli ]

2 info using npm@6.14.5

3 info using node@v12.18.1

4 verbose run-script [ 'predevelop', 'develop', 'postdevelop' ]

5 info lifecycle gatsby-starter-default@0.1.0~predevelop: gatsby-starter-default@0.1.0

6 info lifecycle gatsby-starter-default@0.1.0~develop: gatsby-starter-default@0.1.0

7 verbose lifecycle gatsby-starter-default@0.1.0~develop: unsafe-perm in lifecycle true

8 verbose lifecycle gatsby-starter-default@0.1.0~develop: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\ByrdByte Project\byrdbyte-landing-develop\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Python38\Scripts\;C:\Python38\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files\Git\cmd;C:\Users\asus\AppData\Local\Microsoft\WindowsApps;;C:\Users\asus\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\asus\AppData\Roaming\Composer\vendor\bin;C:\Users\asus\AppData\Roaming\npm

9 verbose lifecycle gatsby-starter-default@0.1.0~develop: CWD: D:\ByrdByte Project\byrdbyte-landing-develop

10 silly lifecycle gatsby-starter-default@0.1.0~develop: Args: [

10 silly lifecycle '/d /s /c',

10 silly lifecycle 'cross-env GATSBY_GRAPHQL_IDE=playground gatsby develop'

10 silly lifecycle ]

11 silly lifecycle gatsby-starter-default@0.1.0~develop: Returned: code: 1 signal: null

12 info lifecycle gatsby-starter-default@0.1.0~develop: Failed to exec develop script

13 verbose stack Error: gatsby-starter-default@0.1.0 develop: `cross-env GATSBY_GRAPHQL_IDE=playground gatsby develop`

13 verbose stack Exit status 1

13 verbose stack at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)

13 verbose stack at EventEmitter.emit (events.js:315:20)

13 verbose stack at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)

13 verbose stack at ChildProcess.emit (events.js:315:20)

13 verbose stack at maybeClose (internal/child_process.js:1021:16)

13 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

14 verbose pkgid gatsby-starter-default@0.1.0

15 verbose cwd D:\ByrdByte Project\byrdbyte-landing-develop

16 verbose Windows_NT 10.0.18362

17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "develop"

18 verbose node v12.18.1

19 verbose npm v6.14.5

20 error code ELIFECYCLE

21 error errno 1

22 error gatsby-starter-default@0.1.0 develop: `cross-env GATSBY_GRAPHQL_IDE=playground gatsby develop`

22 error Exit status 1

23 error Failed at the gatsby-starter-default@0.1.0 develop script.

23 error This is probably not a problem with npm. There is likely additional logging output above.

24 verbose exit [ 1, true ]
```

Enviroment:

```
System:

OS: Windows 10 10.0.18362

CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

Binaries:

Node: 12.18.1 - C:\Program Files\nodejs\node.EXE

npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD

Languages:

Python: 3.8.3

Browsers:

Chrome: 84.0.4147.135

Edge: Spartan (44.18362.449.0)

npmPackages:

gatsby: ^2.24.2 => 2.24.53

gatsby-background-image: ^1.1.1 => 1.1.2

gatsby-image: ^2.4.13 => 2.4.16

gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5

gatsby-plugin-google-tagmanager: ^2.3.11 => 2.3.11

gatsby-plugin-mailchimp: git+https://github.com/benjaminhoffman/gatsby-plugin-mailchimp.git#gatsby-v1 => 3.0.0

gatsby-plugin-manifest: ^2.4.27 => 2.4.27

gatsby-plugin-material-ui: ^2.1.10 => 2.1.10

gatsby-plugin-offline: ^3.2.17 => 3.2.26

gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10

gatsby-plugin-sass: ^2.3.12 => 2.3.12

gatsby-plugin-scroll-reveal: 0.0.7 => 0.0.7

gatsby-plugin-sharp: ^2.6.31 => 2.6.31

gatsby-plugin-styled-components: ^3.3.10 => 3.3.10

gatsby-plugin-typescript: ^2.4.14 => 2.4.18

gatsby-remark-images-contentful: ^2.3.15 => 2.3.15

gatsby-source-contentful: ^2.3.41 => 2.3.41

gatsby-source-filesystem: ^2.3.19 => 2.3.27

gatsby-transformer-sharp: ^2.5.14 => 2.5.14

gatsby-transformer-sqip: ^2.3.31 => 2.3.31

npmGlobalPackages:

gatsby-cli: 2.12.91
```

I deleted my node_modules multiple times and ran npm isntall and didnt work

Please Help

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

**Comment by tjands** [comment] 2020-09-01 23:49
Thanks for posting this @CesySoder, Im also experiencing this issue.

**Comment by lukemarohn** [comment] 2020-09-02 01:35
Same here, crashes on PNG images, though I'm not sure if that is related to the cause or just a coincidence.

**Comment by tjands** [comment] 2020-09-02 01:36
Mine is happening only on PNG images too

**Comment by visuvelu** [comment] 2020-09-02 05:07
Same here, only on PNG images, not processing from .cache folder...

**Comment by alexnitro** [comment] 2020-09-02 06:19
Having the issue as well. Was able to spin up a development server by using an package-lock.json but unsure of which dependency is the underlying cause.

**Comment by AdityaAnand1** [comment] 2020-09-02 06:50
Once I encountered this, no amount of `gatsby clean`-ing or removing node_modules, reinstalling everything - nothing seems to work. Any ideas what's happening?

**Comment by LekoArts** [comment] 2020-09-02 06:56
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by CesySoder** [comment] 2020-09-02 07:00
Same here, only on .png pictures
the wired thing that is starts compiling and processing 257 images, I dont have this many images on my site, its only around a 100 images

**Comment by alexnitro** [comment] 2020-09-02 07:03
I think this issue is also being talked about here https://github.com/gatsbyjs/gatsby/issues/26723 and is much further along.

I downgraded `gatsby-plugin-sharp` to 2.6.25 and this seems to have fixed the issue.

**Comment by LekoArts** [comment] 2020-09-02 07:06
This is indeed a duplicate of https://github.com/gatsbyjs/gatsby/issues/26723, thanks for linking that.

**Closed by LekoArts** 2020-09-02 07:06 UTC
Labels: status: needs reproduction, type: bug

**Comment by CesySoder** [comment] 2020-09-02 07:28
Thank you @alexnitro It worked locally
 
It didnt work on Netlify, I dont understand why

**Comment by CesySoder** [comment] 2020-09-02 07:30
it gives me a warning of  warning Browserslist: caniuse-lite is outdated. Please run the following command: `yarn upgrade`

is that related to anything ?

**Comment by alexnitro** [comment] 2020-09-02 08:55
@CesySoder Have you tried to clear cache within Netlify? The caniuse-lite outdated message I believe is in relation to postcss autoprefixer. Good list of solutions looks to be here with that. https://github.com/postcss/autoprefixer/issues/1184

**Comment by karlhorky** [comment] 2020-09-07 16:16
### Workaround with latest versions of plugins

1. Install [`patch-package`](https://www.npmjs.com/package/patch-package) (`npm install patch-package` or `yarn add patch-package postinstall-postinstall`)
2. Add `"postinstall": "patch-package"` to `scripts` in `package.json`
3. Go into `node_modules/imagemin-pngquant/index.js` and change `error.code` to `error.exitCode` on line 66 (see diff below)
4. Run `npx patch-package imagemin-pngquant`
5. Commit the changes, including the patch

This will save the change that you make to the `index.js` file and apply it any time / anywhere that `npm install` or `yarn` is run in the project.

#### Diff (difference before and after)

```diff
	const promise = subprocess
		.then(result => result.stdout) // eslint-disable-line promise/prefer-await-to-then
		.catch(error => {
-			if (error.code === 99) {
+			if (error.exitCode === 99) {
				return input;
			}
```
