### ISSUE TITLE
With `gatsby-remark-images` inside `gatsby-plugin-mdx`, blurred image doesn't disappear

### ISSUE THREAD

**Issue by samselikoff** [gatsbyjs/gatsby#19790] opened 2019-11-26 04:11 UTC
## Description

In a new Gatsby app, adding `gatsby-plugin-mdx` and `gatsby-remark-images` doesn't work as expected: the blurred "preview" image never is removed.

Possible duplicate of https://github.com/gatsbyjs/gatsby/issues/17017

### Steps to reproduce

1. Checkout https://github.com/samselikoff/gatsby-image-in-mdx-bug
2. Run `yarn install`
3. See two versions of the image – the blurred one never goes away:

![image](https://user-images.githubusercontent.com/2922250/69598784-895ac000-0fd8-11ea-87ca-ec87cf74e65c.png)

### Expected result

The blurred image is replaced with the full-res image

### Actual result

The blurred image doesn't go away

### Environment

<details>
  <summary>gatsby info</summary>

  ```
  System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nodenv/versions/10.16.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.1 - ~/.nodenv/versions/10.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 70.0.1
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.18.3 => 2.18.3 
    gatsby-image: ^2.2.33 => 2.2.33 
    gatsby-plugin-manifest: ^2.2.29 => 2.2.29 
    gatsby-plugin-mdx: ^1.0.57 => 1.0.57 
    gatsby-plugin-offline: ^3.0.23 => 3.0.23 
    gatsby-plugin-react-helmet: ^3.1.15 => 3.1.15 
    gatsby-plugin-sharp: ^2.3.3 => 2.3.3 
    gatsby-remark-images: ^3.1.33 => 3.1.33 
    gatsby-source-filesystem: ^2.1.38 => 2.1.38 
    gatsby-transformer-sharp: ^2.3.5 => 2.3.5 
  npmGlobalPackages:
    gatsby-cli: 2.8.13
  ```
</details>

**Comment by LekoArts** [comment] 2019-11-26 10:45
Hi. Thanks for the issue! This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/15486

**Closed by LekoArts** 2019-11-26 10:45 UTC
