### ISSUE TITLE
How to create multiple mapping between data yaml and markdown

### ISSUE THREAD

**Issue by yudyananda** [gatsbyjs/gatsby#21445] opened 2020-02-14 06:33 UTC
# Summary
Hi, it's been half month since i learn gatsby, unfortunately i have trouble to understand how content relation and the structure. 

I try to create [mapping between the markdown frontmatter and yaml](https://www.gatsbyjs.org/docs/gatsby-config/#mapping-node-types), in this case author and taxonomy tags. For the author, I managed to do it but for some reason when I added additional mapping `'MarkdownRemark.frontmatter.tags': 'TagsYaml'` for tags the results became an error

here is example of my yaml and markdown 

~~~yaml
# authors.yaml
- id: JohnDoe
  twitter: "@JohnDoe"
  email: "me@email.com"
  bio: Lorem
  desc: Ipsum
~~~
~~~yaml
# tags.yaml
- tags: Foo
~~~
~~~md
---
title: Bar
author: ["JohnDoe"]
tags: ["Foo"]
---
~~~

**the error result**
~~~
"gatsby-node.js" threw an error while running the createPages lifecycle:

runner.query(...).then is not a function

  43 |     return new Promise((resolve, reject) => {
  44 |         resolve(
> 45 |             graphql(
     |             ^
  46 |                 `
  47 |                 query {
  48 |                   pages: allMarkdownRemark(

File: gatsby-node.js:45:13
~~~

## Relevant information

My motivation is to get dynamic data for the taxonomy so that I don't have to hard coded in the template. I have searched for the similiar issue [#10169](https://github.com/gatsbyjs/gatsby/issues/10169) and [#16118](https://github.com/gatsbyjs/gatsby/issues/16118) but there seems to be no answer for me

### Environment (if relevant)

~~~
  System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.7 - C:\Users\Yudy\AppData\Roaming\npm\npm.CMD
  Languages:
    Python: 2.7.16 - /cygdrive/c/Python27/python
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.19.5 => 2.19.5
    gatsby-awesome-pagination: ^0.3.5 => 0.3.5
    gatsby-image: ^2.2.39 => 2.2.39
    gatsby-plugin-canonical-urls: ^2.1.20 => 2.1.20
    gatsby-plugin-catch-links: ^2.1.25 => 2.1.25
    gatsby-plugin-draft: 0.0.5 => 0.0.5
    gatsby-plugin-react-helmet: ^3.1.22 => 3.1.22
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-sass: ^2.1.27 => 2.1.27
    gatsby-plugin-sharp: ^2.4.0 => 2.4.0
    gatsby-remark-autolink-headers: ^2.1.24 => 2.1.24
    gatsby-remark-images: ^3.1.42 => 3.1.42
    gatsby-remark-normalize-paths: ^1.0.0 => 1.0.0
    gatsby-remark-prismjs: ^3.3.31 => 3.3.31
    gatsby-remark-relative-images: ^0.2.3 => 0.2.3
    gatsby-source-filesystem: ^2.1.46 => 2.1.46
    gatsby-transformer-remark: ^2.6.50 => 2.6.50
    gatsby-transformer-sharp: ^2.3.13 => 2.3.13
    gatsby-transformer-yaml: ^2.2.24 => 2.2.24
~~~

### File contents (if changed)

~~~
├───content
│     ├───data
│     │    ├───authors.js
│     │    └───tags.js
│     ├───images
│     │    └───foo.jpg
│     ├───pages
│     │    └───lorem.md
│     └───posts
│          └───ipsum.md
├───src
│   ├───pages
│   └───templates
│─── static
│─── gatsby-browser.js
│─── gatsby-config.js
│─── gatsby-node.js
└─── package.json
~~~

**gatsby-config.js**
~~~js
// gatsby-config.js
module.exports = {
    /* Mapping */
    mapping: {
        'MarkdownRemark.frontmatter.tags': `TagsYaml`,
        'MarkdownRemark.frontmatter.author': `AuthorsYaml`,
    },
    plugins: [
        ...
        'gatsby-transformer-yaml',
        {
            resolve: `gatsby-source-filesystem`,
            options: {
                name: `data`,
                path: `${__dirname}/content/data`, // data dir
            },
        },
      ...
    ]
 }
~~~

**gatsby-node.js**

~~~js
// gatsby-node.js
const path = require('path');
const _ = require('lodash');
const { paginate } = require('gatsby-awesome-pagination');
const { createFilePath } = require(`gatsby-source-filesystem`);
const { fmImagesToRelative } = require('gatsby-remark-relative-images');


exports.onCreateNode = ({ node, getNode, actions }) => {
  fmImagesToRelative(node);
  const { createNodeField } = actions;
  // create fields slug on every markdown
  if (node.internal.type === `MarkdownRemark`) {
    const slug = createFilePath({ node, getNode, basePath: `content` })
    createNodeField({
      node,
      name: `slug`,
      value: slug,
    })
  }
  // create fields slug on every author yaml
  if (node.internal.type === `TagsYaml`) {
    const slug = createFilePath({ node, getNode, basePath: `content` })
    createNodeField({
      node,
      name: `slug`,
      value: slug,
    })
  }
  // create fields slug on every author yaml
  if (node.internal.type === `AuthorsYaml`) {
    const slug = createFilePath({ node, getNode, basePath: `content` })
    createNodeField({
      node,
      name: `slug`,
      value: slug,
    })
  }
}
// Create pages from markdown files
exports.createPages = ({graphql, actions}) => {
    const {createPage} = actions;
    return new Promise((resolve, reject) => {
        resolve(
            graphql(
                `
                query {
                  pages: allMarkdownRemark(
                    filter: { fileAbsolutePath: { regex: "/pages/" } fields: { draft: { eq: false }} }
                    sort: { fields: [frontmatter___title], order: DESC }
                  ) 
                  { 
                    edges {
                      node {
                        id
                        frontmatter {
                          type
                          template
                          title
                          slug
                        }
                      }
                    }
                  }
                  posts: allMarkdownRemark(
                    filter: { fileAbsolutePath: { regex: "/posts/" } fields: { draft: { eq: false }} }
                    sort: { fields: [frontmatter___title], order: DESC }
                  )
                  { 
                    edges {
                      node {
                        id
                        frontmatter {
                          type
                          template
                          title
                          slug
                          tags
                        }
                      }
                    }
                  } 
                  tagsGroup: allMarkdownRemark(
                    filter: {fileAbsolutePath: {regex: "/posts/"}, 
                    fields: {draft: {eq: false}}}, 
                    sort: {fields: [frontmatter___date], 
                    order: DESC}, limit: 2000)
                  {
                    group(field: frontmatter___tags) {
                      fieldValue
                    }
                    edges {
                      node {
                        id
                        frontmatter {
                          type
                          title
                          slug
                          tags
                        }
                      }
                    }
                  }
                  author: allAuthorsYaml 
                  {
                    edges {
                      node {
                        id
                        twitter
                        bio
                        fields {
                          slug
                        }
                      }
                    }
                  }
                }
                `,
            ).then((result) => {
                // Page
                result.data.pages.edges.forEach(({node}) => {
                    //const component = path.resolve({'src/templates/custom/about.js'});
                    createPage({
                      path: node.frontmatter.slug,
                      component: path.resolve(`./src/templates/pages/${node.frontmatter.template}.js`),
                        context: {
                            id: node.id,
                        },
                    });
                });
                // Blog
                result.data.posts.edges.forEach(({node}) => {
                    const component = path.resolve(`./src/templates/posts/${node.frontmatter.template}.js`);
                    createPage({
                        path: `/blog/${node.frontmatter.slug}`,
                        component,
                        context: {
                            id: node.id,
                        },
                    });
                    // Pagination Bloglist
                    const blogPosts = result.data.posts.edges;
                    const pathPrefix = ({ pageNumber, numberOfPages }) => pageNumber === 0 ? '/blog' : '/blog/page'
                    paginate({
                        createPage,
                        items: blogPosts,
                        component: path.resolve('src/templates/posts/list.js'),
                        itemsPerPage: 4,
                        pathPrefix: pathPrefix
                    });
                    // Blog tags
                    const tags = result.data.tagsGroup.group;
                    tags.forEach(tag => {
                      createPage({
                          path: `/blog/tags/${_.kebabCase(tag.fieldValue)}`,
                          component: path.resolve('src/templates/taxonomies/list.js'),
                          context: {
                              tag: tag.fieldValue,
                          },
                      });
                      // Pagination Taglist
                      const tagPrefix = ({ pageNumber, numberOfPages }) => pageNumber === 0 ? `/blog/tags/${_.kebabCase(tag.fieldValue)}` : `/blog/tags/${_.kebabCase(tag.fieldValue)}/page`
                      paginate({
                          createPage,
                          items: tags,
                          component: path.resolve('src/templates/taxonomies/list.js'),
                          itemsPerPage: 4,
                          pathPrefix: tagPrefix,
                          context: {
                              tag: tag.fieldValue,
                          },
                      });
                    })
                    // Author
                    result.data.author.edges.forEach(({ node }) => {
                        createPage({
                        path: `${node.fields.slug}${_.kebabCase(node.id)}`,
                        component: path.resolve(`./src/templates/authors/author.js`),
                        context: {
                            // Data passed to context is available
                            // in page queries as GraphQL variables.
                            slug: node.fields.slug,
                            id: node.id
                        },
                        })
                    });
                });
                resolve();
            }),
        );
    });
};


~~~

**Comment by LekoArts** [comment] 2020-02-14 09:42
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2020-02-14 09:51
Thank you for opening this!

Your authors file works as it has an `id` key on the entry. The mapping searches for that. So for your tags you'd need something like:

```yaml
- id: Foo
  name: Foo
```

If you don't want to map by the `id` you should use the schema customization API to link by another field: https://www.gatsbyjs.org/docs/schema-customization/#foreign-key-fields

However, I'm not too sure what the purpose of your tags YAML file is so would be happy to get a longer explanation on that! You can use some GraphQL queries like `group` to get a list of posts for a tag for example.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2020-02-14 09:51 UTC
Labels: type: question or discussion

**Comment by ljpernic** [comment] 2020-06-20 22:44
Hello! I have a similar question, but I can't seem to parse the answer above. 

**My problem:** I have two yaml files, both with an id field that I'm trying to map to two different frontmatter fields on the same markdown file. Is this possible? 

I have a fuller description of the issue in a [post on stackoverflow](https://stackoverflow.com/questions/62425192/how-to-map-multiple-yaml-files-to-frontmatter-in-gatsby). I'd be very grateful for a little additional information on the solution offered above! (I can also make a new issue if that would be more appropriate.)

Thank you!
