### ISSUE TITLE
A bug with package manager selection dialog

### ISSUE THREAD

**Issue by andrewpavl** [gatsbyjs/gatsby#25499] opened 2020-07-03 09:10 UTC
## Description

I have both yarn and npm installed on my system and when gatsby asks which package manager to use the selection dialog looks wrong.
![image](https://user-images.githubusercontent.com/44530365/86452595-3347bb00-bd25-11ea-93dd-98b223556abd.png)

### Steps to reproduce

Run `gatsby new` in windows terminal. You should have both yarn and npm installed on your system.

### Expected result

No issues, just select package manager and continue installing.

### Actual result

Package manager selection dialog looks wrong.

### Environment

  System:
    OS: Windows 10 10.0.18363
    CPU: (2) x64 Intel(R) Core(TM)2 Duo CPU     E8500  @ 3.16GHz
  Binaries:
    Node: 14.3.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.3
  Browsers:
    Edge: 44.18362.449.0
  npmGlobalPackages:
    gatsby-cli: 2.12.52

Also terminal app is Microsoft Terminal installed from windows app store.

**Comment by LekoArts** [comment] 2020-07-03 09:41
Hi, thanks for the issue! This seems like a duplicate of https://github.com/gatsbyjs/gatsby/issues/24420 so I'll close this one. Feel free to comment on said issue.

**Closed by LekoArts** 2020-07-03 09:41 UTC
Labels: type: bug
