### ISSUE TITLE
Styles appearing with delay when using external UI library

### ISSUE THREAD

**Issue by meienberger** [gatsbyjs/gatsby#22550] opened 2020-03-24 19:51 UTC
## Summary

I created a UI library which uses styled-components internally and I'm trying to use it inside my Gatsby website. On dev mode everything is perfectly working but when I build, the page components of my library are rendered first with no style at all and then after a small delay, it flashes and everything is ok.

I started searching how to solve this issue and found out about this library. Some people told that they fixed their issue by just installing this plugin. But for me, the result is exactly the same. Am I missing something ?

In my `gatsby-config.js`

```js
 plugins: [
    `gatsby-plugin-styled-components`,
 ]
```

Do I have to add further options to solve my issue ? (I already tried with ssr: true) Or is this library not meant to solve my issue at all ?

Thanks for your help. Here's the repo of what I tried to do : https://github.com/meienberger/gatsby-base

**Comment by Js-Brecht** [comment] 2020-03-25 06:58
There seems to be something wrong with the UI library.  In your example repo, if I make my own styled component and add it to the page, it renders correctly during SSR, including the CSS.  So I know  `gatsby-plugin-styled-components` is working, but it's not processing the component from the UI library correctly.

It might help to be able to see the source of the UI library.

**Comment by Js-Brecht** [comment] 2020-03-25 17:55
So I just had a sec to come back to this, and I noticed that if I move the `<Footer>` component into the current project's `src` directory, SSR works just fine.

I also tried moving `waasabi-ui` out of `node_modules`, to make sure it wasn't being blocked by being there.  Same issue... so something is making it only operate correctly when the component is in your `src` directory.

I'll try to debug a little bit when I have more time later.

**Comment by Js-Brecht** [comment] 2020-03-25 19:17
> so something is making it only operate correctly when the component is in your `src` directory.

That's not completely accurate.  I can move the `Footer` directory from `waasabi-ui/dist/components` anywhere, and it will process the styles correctly.  It's when the component is imported out of the `waasabi-ui` package that the problem exists :confused: .

**Comment by Js-Brecht** [comment] 2020-03-25 19:23
Okay, the problem is a `styled-component` version conflict.

`waasabi-ui` uses version `^4.4.1`, meanwhile the consuming project is using version `^5.0.1`.  If I use
```json
  "resolutions": {
    "styled-components": "^5.0.1"
  }
```
in the `package.json` to force a consistent `styled-components`, the issue is fixed.

**Comment by meienberger** [comment] 2020-03-26 09:05
Thank you very much ! Yes it was `styled-components` version. It didn't even cross my mind...

**Comment by wardpeet** [comment] 2020-03-26 09:22
Awesome! Thanks @Js-Brecht

Marking this as resolved.

**Closed by wardpeet** 2020-03-26 09:22 UTC
Labels: type: question or discussion
