### ISSUE TITLE
client-only routes  + pathPrefix not work

### ISSUE THREAD

**Issue by stanleyyuenyiu** [gatsbyjs/gatsby#25188] opened 2020-06-22 08:46 UTC
Description
Adding pathPrefix to gatsby-config while using client-only routes breaks routing in production builds.

Steps to reproduce

add pathPrefix: '/app'
gatsby build --prefix-paths
move public/* to s3/app
use s3 website hosting
set fallback Error page to /app/app/index.html

Expected result
when visit http://[mys3].s3-website-ap-southeast-1.amazonaws.com/app/app/hi
Client-only routes should render components

Actual result
No components are rendered, reloading a route returns 404.html

**gatsby config**
const path = require('path')
module.exports = {
  pathPrefix: `/app`,
  plugins: [
    {
      resolve: `gatsby-plugin-create-client-paths`,
      options: { prefixes: [`/app/*`] },
    }
  ],
}

**page/app.js**
`import React from "react"
import { Link, withPrefix } from "gatsby"
import { Router } from "@reach/router"
import Layout from "../components/layout"
import Image from "../components/image"
import Hello from "../components/hello"
import Hi from "../components/hi"
const IndexPage = () => (
  <Layout>
      <Router basepath={withPrefix('/app')}>
        <Hello path="/:locale/hello" />
        <Hi path="/hi" />
      </Router>
    </Layout>
)
export default IndexPage`

**build command**

gatsby build --prefix-paths

**Comment by LekoArts** [comment] 2020-06-23 06:17
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2020-06-23 06:33
Also I think this is a duplicate of https://github.com/gatsbyjs/gatsby/issues/23392

**Comment by stanleyyuenyiu** [comment] 2020-06-23 10:08
@LekoArts yes, similar, but i try to set up a env for everyone to test

**Comment by ehrencrona** [comment] 2020-06-25 19:35
@stanleyyuenyiu I posted an answer in #23392 . Not sure if you're experiencing the same issue but you might want to check it out.

**Comment by ascorbic** [comment] 2020-07-02 15:55
Hi. I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. Thanks!

**Closed by ascorbic** 2020-07-02 15:55 UTC
Labels: status: needs reproduction

**Comment by stanleyyuenyiu** [comment] 2020-07-03 02:54
@ascorbic i have already create the minimal reproduction, please do not close it
@ehrencrona your example is totally incorrect

as i mention

resolve: `gatsby-plugin-create-client-paths`,
 options: { prefixes: [`/*`] },

NOT 

resolve: `gatsby-plugin-create-client-paths`,
      options: { prefixes: [`/app/*`] },
