### ISSUE TITLE
Gatsby with swagger-ui

### ISSUE THREAD

**Issue by Meemaw** [gatsbyjs/gatsby#11081] opened 2019-01-15 15:01 UTC
Hello! I'm trying to setup a documentation page with `swagger-ui` inside. I bootsraped my project with `gatsby new example`. In one of my components I import swagger-ui as:

```js
import SwaggerUI from 'swagger-ui';
```

This works when running locally, but fails at build time:
```js
WebpackError: TypeError: _dompurify2.default.addHook is not a function

  - swagger-ui.js:1 Object.<anonymous>
    [lib]/[swagger-ui]/dist/swagger-ui.js:1:231508

  - swagger-ui.js:1 __webpack_require__
    [lib]/[swagger-ui]/dist/swagger-ui.js:1:4008

  - swagger-ui.js:8 Object.<anonymous>
    [lib]/[swagger-ui]/dist/swagger-ui.js:8:88022

  - swagger-ui.js:1 __webpack_require__
    [lib]/[swagger-ui]/dist/swagger-ui.js:1:4008

  - swagger-ui.js:8 Object.<anonymous>
    [lib]/[swagger-ui]/dist/swagger-ui.js:8:78018

  - swagger-ui.js:1 __webpack_require__
    [lib]/[swagger-ui]/dist/swagger-ui.js:1:4008

  - swagger-ui.js:1 Object.<anonymous>
    [lib]/[swagger-ui]/dist/swagger-ui.js:1:327245

  - swagger-ui.js:1 __webpack_require__
    [lib]/[swagger-ui]/dist/swagger-ui.js:1:4008

  - swagger-ui.js:1 Object.<anonymous>
    [lib]/[swagger-ui]/dist/swagger-ui.js:1:292385

  - swagger-ui.js:1 __webpack_require__
    [lib]/[swagger-ui]/dist/swagger-ui.js:1:4008

  - swagger-ui.js:1
    [lib]/[swagger-ui]/dist/swagger-ui.js:1:4736

  - swagger-ui.js:1
    [lib]/[swagger-ui]/dist/swagger-ui.js:1:4790

  - swagger-ui.js:1 webpackUniversalModuleDefinition
    [lib]/[swagger-ui]/dist/swagger-ui.js:1:112

  - swagger-ui.js:1 Object../node_modules/swagger-ui/dist/swagger-ui.js
    [lib]/[swagger-ui]/dist/swagger-ui.js:1:2842

  - bootstrap:19 __webpack_require__
    lib/webpack/bootstrap:19:1
```

**Comment by itaisteinherz** [comment] 2019-01-16 10:36
I also experienced this while _not_ using Gatsby, and so this is probably related to your configuration and `swagger-ui` usage. Have you taken a look at [this issue](https://github.com/swagger-api/swagger-ui/issues/4805)?

**Comment by sidharthachatterjee** [comment] 2019-01-16 12:38
I can reproduce this

@Meemaw Take a look at [this](https://github.com/swagger-api/swagger-ui/issues/4805#issuecomment-438796130) comment in the issue linked by @itaisteinherz 

> You should definitely not be importing or calling SwaggerUIBundle directly in your server-side application - that code is meant for your user's browser. The only code relevant to server-side applications is the absolutePath helper.

It looks like the bundle isn't SSR friendly

You could load this on the client side only in `gatsby-browser.js` maybe

**Comment by jonniebigodes** [comment] 2019-02-11 20:17
@Meemaw if you haven't already resolved this, i'm implementing a way to handle this.

**Comment by OrKoN** [comment] 2019-02-23 09:56
Hi, I have used the following workaround:

1. Import swagger UI in `gatsby-browser.js`:

```
import SwaggerUI from 'swagger-ui'
window.SwaggerUI = SwaggerUI;
```
2. create a wrapper component:

```
class Swagger extends React.Component {
  componentDidMount() {
    SwaggerUI({
        dom_id: '#swagger',
        .....
    });
  }
  render() {
    return <div id="swagger" />
  }
}
```

This way swagger will not be server-rendered. Instead, it will be loaded in the user's browser.

**Comment by OrKoN** [comment] 2019-03-02 11:48
Beware of this issue as well https://github.com/swagger-api/swagger-ui/issues/4745

**Comment by DSchau** [comment] 2019-03-04 17:54
Sounds like this is an upstream issue with swagger-ui not being super server-side rendering friendly.

I'd recommend following the remediation as @OrKoN mentioned [here](https://github.com/gatsbyjs/gatsby/issues/11081#issuecomment-466634634). Additionally, I think using [null-loader](https://www.gatsbyjs.org/docs/debugging-html-builds/#fixing-third-party-modules) may also help in this case.

Since this is an issue outside of Gatsby and that seems to have a remediation, going to close this out. Please feel free to reply if we can help out further!

**Closed by DSchau** 2019-03-04 17:54 UTC
Labels: type: question or discussion

**Comment by reselbob** [comment] 2021-08-02 21:42
@OrKoN 

I want to implement your solution: https://github.com/gatsbyjs/gatsby/issues/11081#issuecomment-466634634

But, I am new to Gatsby.

Can you tell me exactly where and how to place the code snippets you describe above for the client side rendering solution? Thanks in advance. It will be a big help.
