### ISSUE TITLE
Gatsby useStaticQuery and SEO constantly yielding error "Gatsby related `graphql` calls are supposed to only be evaluated at compile time, and then compiled away"

### ISSUE THREAD

**Issue by burtonator** [gatsbyjs/gatsby#27310] opened 2020-10-06 15:50 UTC
## Description

We're following your instructions here:

https://www.gatsbyjs.com/docs/add-seo-component/

... on how to use the SEO component to build Googlebot friendly pages but we're constantly getting errors in the most recent Gatsby:

The error we're receiving is:

"  WebpackError: It appears like Gatsby is misconfigured. Gatsby related `graphql` calls are supposed to only be evaluated at compile time, and then compiled away. Unfortunately, something went wrong and the query was   left in the compiled code."
  

The error is non-deterministic and seems to happen say 20% of the time per page but since we added the Seo component in all our pages it happens at least 9/10 builds.

### Steps to reproduce

This should reproduce it...

https://github.com/polar-app/polar-site2/tree/burton-broken

### Expected result

It should build successfully.

### Actual result

It fails 95% of the time.

### Environment

  System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.11.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 85.0.4183.121
    Safari: 14.0
  npmPackages:
    gatsby: ^2.24.67 => 2.24.67 
    gatsby-image: =2.4.20 => 2.4.20 
    gatsby-plugin-breakpoints: ^1.2.4 => 1.2.4 
    gatsby-plugin-google-analytics: ^2.3.14 => 2.3.14 
    gatsby-plugin-manifest: ^2.4.31 => 2.4.31 
    gatsby-plugin-material-ui: ^2.1.10 => 2.1.10 
    gatsby-plugin-react-helmet: ^3.3.12 => 3.3.12 
    gatsby-plugin-sharp: ^2.6.36 => 2.6.36 
    gatsby-plugin-sitemap: ^2.4.13 => 2.4.13 
    gatsby-remark-images: ^3.3.30 => 3.3.30 
    gatsby-source-filesystem: ^2.3.30 => 2.3.30 
    gatsby-theme-material-ui: ^1.0.13 => 1.0.13 
    gatsby-transformer-remark: ^2.8.35 => 2.8.35 
    gatsby-transformer-sharp: =2.5.16 => 2.5.16

**Comment by burtonator** [comment] 2020-10-06 17:35
The other main issue is that it's nondeterministic.  If I run it 5 times it will fail 4 and succeed once. No code changes.

**Comment by ascorbic** [comment] 2020-10-08 12:08
Hi. I'm afraid I can't reproduce this. I've checked-out your branch and run build ten times and it worked fine each time. Do you get the same issue if you run it on another machine, or in CI?

**Comment by LekoArts** [comment] 2020-10-19 08:28
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-10-19 08:28 UTC
Labels: status: needs reproduction, type: bug
