### ISSUE TITLE
Can't download directly HTML file from public

### ISSUE THREAD

**Issue by pacocom** [gatsbyjs/gatsby#27321] opened 2020-10-07 12:53 UTC
## Description
Can't download directly HTML file from public. I want to download tutorial.html from public folder directly using markdown link.

```md
[Tutorial txt](/downloads/tutorial.txt 'Tutorial.txt')
[Tutorial html](/downloads/tutorial.html 'Tutorial.html')
```
```
```md
[Tutorial txt](/downloads/tutorial.txt 'Tutorial.txt')
```
![image](https://user-images.githubusercontent.com/7735329/95333347-f1db2480-08ac-11eb-8792-8f1d871dcbda.png)

![image](https://user-images.githubusercontent.com/7735329/95332367-9a888480-08ab-11eb-9169-1cec69423f95.png)
If I use txt file:
![image](https://user-images.githubusercontent.com/7735329/95332406-ac6a2780-08ab-11eb-9ddb-dc6006b0c6a2.png)
If I use html file:
Page 404 error appears.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by pvdz** [comment] 2020-10-07 13:27
Can you please fill in the submission form properly? Like a link to the repro with your example and the result if `gatsby info`, so we can see which platform you're on.

**Comment by LekoArts** [comment] 2020-10-19 08:28
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-10-19 08:28 UTC
Labels: status: awaiting author response, status: needs reproduction, type: bug
