### ISSUE TITLE
Algolia InstantSearch SSR

### ISSUE THREAD

**Issue by Akh0** [gatsbyjs/gatsby#1597] opened 2017-07-24 12:55 UTC
I'm trying to implement InstantSearch SSR on Gatsby but I have some troubles.

The InstantSearch SSR API provide a `findResultsState` function which compute search parameters doing a full render of the root component, build the request and make API call. (more details here: https://community.algolia.com/react-instantsearch/guide/Server-side_rendering.html)

The only way I found to access to the root component with Gatsby is to use the `bodyComponent` parameter of `replaceRenderer` API. However, this function doesn't allow to make an async call.

I suppose that I should use the Node APIs to perform async call but I don't have access to `bodyComponent` here. Even if I use the vanilla Algolia API, I don't know how to reuse the data fetched for SSR.

I'm not sure to do it the right way so any help is welcome.

**Comment by KyleAMathews** [comment] 2017-07-25 17:42
Curious why you want to SSR for Algolia? Is this for a search page? If so, just render a page with no search results because you're going to want to render the page in the client with fresh data from Algolia in response to user searchers.

**Comment by Akh0** [comment] 2017-07-26 08:43
Actually I would like to make a page that mixes list results and search results with the same display.
My page is composed of a search box and blog post items.
The first render display a paginated list of all blog posts with default search parameters (what I'm trying to pre-render) and when you start type a search, the list is updated.
The goal is to have a first rendering instantly without Algolia API call (even if it's very fast) and allow bots to crawl the page.

**Comment by KyleAMathews** [comment] 2017-07-26 19:38
Ok cool. Sounds like a good pattern.

So in short, what you'll want to do is create a plugin which adds a GraphQL schema to Gatsby which will let you write GraphQL queries to pull data from Algolia at build time.

We don't have an API for directly extending the created GraphQL schema so you'd need to add that.

If this makes sense I can help walk you through things.

**Comment by theiliad** [comment] 2017-09-06 03:33
I'm trying to add this capability, but I'm only trying to show search results on client-side and that's it.

I've made some configs in gatsby-node.js that go through my posts and can get the info out, now how do you think I should submit them to Algolia?

They do have an SDK, but I don't want to keep reporting existing documents

**Comment by LawJolla** [comment] 2017-09-12 04:04
I have a similar issue implementing Apollo.  Apollo gives an async "getDataFromTree" which will walk the bodyComponent for all graphql calls, run them, and hydrate the store.  But I can't figure out how to make it work without the function allowing an async call.

**Comment by theiliad** [comment] 2017-10-07 05:45
Just bumping this, anyone got any ideas?

**Comment by brandonmp** [comment] 2017-11-03 22:13
just finished futzing with this. there's no easy solution i think. I can confirm that [Google isn't indexing Algolia results ](https://webcache.googleusercontent.com/search?q=cache:_lYKDQg-QQkJ:https://www.admitbrain.com/mba-admissions-consultants/+&cd=1&hl=en&ct=clnk&gl=us)(at least not on my Gatsby site). 

the pattern for using Algolia SSR is basically:

1. Pass your `InstantSearch` component to `findResultsState`
2. Kind of like Relay, `findResultsState` grabs all the search params from `InstantSearch`'s children. 
3. `findResultsState` sends a call to the Algolia API & returns a snapshot of the results
4. Pass these results in as a `resultsState` prop, and you've got server-rendered search

the hard part is how to do this in Gatsby. As I see it, here are the options:

A. is in `gatsby-node` like @Akh0 tried, passing down to component via `pathContext`. i think this has a lot of potential, but because `requires` in `gatsby-node` aren't parsed thru webpack/babel, it's not trivial to import your `InstantSearch` component. You could use webpack/babel to compile your InstantSearch component by itself, but this doesn't seem trivial, so I haven't tried it yet. 

Also bear in mind that `findResultsState` mounts the component without context, etc., so if you're using context thru Redux, styled-components, etc., you'd have to essentially mock those. 

B. Load your results in dev & save them to a JSON. Not ideal, but definitely the quickest way. I tried this by calling `findResultsState` in `componentDidMount` from a parent of `InstantSearch`, storing the results in state & copying them from chrome dev tools. a good stop gap but results won't be fresh. 

C. do as @KyleAMathews  suggests & build a custom gql interface for the Algolia API. I'm not sure this is feasible, as the components are kind of a black box WRT their API calls, so mirroring that wouldn't be trivial. 


Hopefully this gives someone some idea, but for now we're looking at workarounds, since any of these solutions seems messy. 

Is there any way to mimic the role of Nextjs's  `getInitialProps` ?

**Comment by jeremylynch** [comment] 2018-08-04 23:14
It is possible to recreate the `resultsState` props. And then you could pass this through `pathContext` See below: 

```js
import algoliasearch from 'algoliasearch';
import { SearchResults, SearchParameters } from 'algoliasearch-helper';

const client = algoliasearch('latency', '6be0576ff61c053d5f9a3225e2a90f76');

const response = await client.search([
    {
      indexName: 'ikea',
      query: '',
      params: {
        hitsPerPage: 3,
        facets: ['category'],
      },
    },
  ]);

  // Create the custom resultsState props
  const resultsState = {
    content: new SearchResults(state, response.results),
    _originalResponse: response,
    state,
  };
```
Read more: https://github.com/algolia/react-instantsearch/issues/649

**Comment by KyleAMathews** [comment] 2018-09-08 05:54
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Closed by KyleAMathews** 2018-09-08 05:54 UTC
