### ISSUE TITLE
Post sorting not working properly

### ISSUE THREAD

**Issue by diegomadeit** [gatsbyjs/gatsby#27014] opened 2020-09-24 11:43 UTC
## Description

Describe the issue that you're seeing.

### Steps to reproduce

Hi,

Recently we experienced an issue in the way the posts are displayed in our blog.

In our Gatsby app we sort the posts in the query this way: sort: { fields: [date], order: DESC } but the order they are displayed doesn’t match the criteria. We get the posts from DatoCMS.

In local is working and showing the post in proper order but not in PROD environment (it looks that it show last updated post first).

Are we missing something?

Thanks,

Diego

### Expected result

Post are shown according to sorting criteria

### Actual result

Post are not shown according to sorting criteria. It looks that show last updated post first.

### Environment

System:
OS: macOS 10.15.2
CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
Shell: 3.2.57 - /bin/bash
Binaries:
Node: 10.16.0 - /usr/local/bin/node
Yarn: 1.21.1 - /usr/local/bin/yarn
npm: 6.9.0 - /usr/local/bin/npm
Languages:
Python: 2.7.16 - /usr/bin/python
Browsers:
Chrome: 83.0.4103.116
Firefox: 78.0.1
Safari: 13.0.4
npmGlobalPackages:
gatsby-cli: 2.6.7

**Comment by ascorbic** [comment] 2020-09-24 14:59
Hi 

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it would be really helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

Thanks!

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2020-10-05 14:34
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-10-05 14:34 UTC
Labels: status: needs reproduction, type: bug
