### ISSUE TITLE
gatsby-remark-images is not parsing all of my images

### ISSUE THREAD

**Issue by pol4b** [gatsbyjs/gatsby#21292] opened 2020-02-08 07:22 UTC
I'm trying to migrate my blog to GatsbyJS. My posts are written in markdown and I almost setup my blog. But, some images in my [post][1] are not loading well. I thought it casued by other plugin(gatsby-remark-relative-images, gatsby-remark-images-medium-zoom) but I guess is not because it's not fixed even I disabled those. I think gatsby-remark-images are not parsing all images well.

 This is part of my gatsby-config.js. Is there anything I have to change to fix this problem?

      resolve: 'gatsby-transformer-remark',
      options: {
        plugins: [
          'gatsby-remark-relative-images',
          {
            resolve: 'gatsby-remark-katex',
            options: {
              strict: 'ignore'
            }
          },
          {
            resolve: 'gatsby-remark-images',
            options: {
              maxWidth: 960,
              withWebp: true,
              ignoreFileExtensions: [],
              linkImagesToOriginal: false
            }
          },
          {
            resolve: 'gatsby-remark-images-medium-zoom',
            options: {
            }
          },
          {
            resolve: 'gatsby-remark-responsive-iframe',
            options: { wrapperStyle: 'margin-bottom: 1.0725rem' }
          },
          'gatsby-remark-autolink-headers',
          'gatsby-remark-prismjs',
          'gatsby-remark-copy-linked-files',
          'gatsby-remark-smartypants',
          'gatsby-remark-external-links'
        ]
      }
    },

  [1]: https://pol4.dev/posts/trip-to-tongyeong

**Comment by pol4bear** [comment] 2020-02-08 16:02
I found it. I'm not sure that what exatly causes this problem but Thumbnail generator or gatsby-remark-images has a bug. If image file extansion is uppercase markdown documents loads successfully but thumbnail not generated on ```gatsby build```. On ```gatsby develop``` it worked fine so it was hard to find the problem.

 Maybe one of the below reason will be causing this problem. I think no.2 is the reason.
 1. Thumbnail generator parses only lower case extensions.
 2. Image extansion in markdown and real image extension's case doesn't match. ex. example.jpg in markdown but example.JPG is the real image.

**Comment by LekoArts** [comment] 2020-02-14 10:55
Glad that you were able to solve it. You might be developing on a OS that is not case-sensitive with such things but if you e.g. deploy on Netlify Linux runs in the background which is case-sensitive. You'll need to watch out for your file casing (including extensions). It's not a bug on Gatsby's side so I'll close this.

Thanks for using Gatsby!

**Closed by LekoArts** 2020-02-14 10:55 UTC
Labels: type: question or discussion
