### ISSUE TITLE
The example of client-only-paths reports React hydration related error

### ISSUE THREAD

**Issue by crossz** [gatsbyjs/gatsby#37928] opened 2023-04-10 04:33 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

The latest updated client-only-paths example, reports React hydration related errors, after build and run by `gatsby serve`.

such as:
https://legacy.reactjs.org/docs/error-decoder.html/?invariant=418
https://legacy.reactjs.org/docs/error-decoder.html/?invariant=423

### Reproduction Link

https://github.com/gatsbyjs/gatsby/tree/master/examples/client-only-paths

### Steps to Reproduce

1. git pull the Gatsby repo
2. go into the example dir, `examples/client-only-paths`
3. `yarn && yarn build && yarn serve`
...

### Expected Result

clear chrome devtools console with the url of 'http://localhost:9000/'

### Actual Result

report errors such as:
```
react-dom.production.min.js:131 Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at sa (react-dom.production.min.js:131:278)
    at Ei (react-dom.production.min.js:293:379)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at as (react-dom.production.min.js:268:209)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
react-dom.production.min.js:293 Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ei (react-dom.production.min.js:293:39)
    at ks (react-dom.production.min.js:280:389)
    at ys (react-dom.production.min.js:280:320)
    at vs (react-dom.production.min.js:280:180)
    at os (react-dom.production.min.js:271:88)
    at as (react-dom.production.min.js:268:429)
    at S (scheduler.production.min.js:13:203)
    at MessagePort.T (scheduler.production.min.js:14:128)
```

### Environment

```shell
System:
    OS: macOS 13.3.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 9.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 111.0.5563.146
    Safari: 16.4
  npmPackages:
    gatsby: next => 5.9.0-next.3 
    gatsby-plugin-netlify: next => 4.0.0-next.0 
    gatsby-plugin-typography: next => 5.9.0-next.0 
  npmGlobalPackages:
    gatsby-cli: 4.24.0
```

**Comment by LekoArts** [comment] 2023-04-17 13:04
Duplicate of https://github.com/gatsbyjs/gatsby/issues/36697

**Closed by LekoArts** 2023-04-17 13:04 UTC
Labels: type: bug
