### ISSUE TITLE
gatsby-plugin-sharp no cache generated

### ISSUE THREAD

**Issue by jeremyw24** [gatsbyjs/gatsby#32358] opened 2021-07-14 04:54 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

On a fresh install of gatsby-starter, running `gatsby develop` for the first time will fail, reporting there is no .cache for gatsby-plugin-sharp.

I had this issue in another project I was working on assuming the issue was related to my code, so as a test, deployed a fresh gatsby starter and found the exact same issue.

```
ENOENT: no such file or directory, open
'/Users/username/Documents/Code/your-human/.cache/caches/gatsby-plugin-sharp/diskstore-738cc1ae55010384992a326f43c2e943.json'
```

### Reproduction Link

https://github.com/gatsbyjs/gatsby-starter-default

### Steps to Reproduce

1. `gatsby new my-site https://github.com/gatsbyjs/gatsby-starter-default`
2. `gatsby develop`
3. Receive error, gatsby develop will crash. 

### Expected Result

Gatsby develop should run and assuming a .cache as required would be created.

### Actual Result

gatsby develop instance crashes and reports error: 

```
ENOENT: no such file or directory, open
'/Users/username/Documents/Code/your-human/.cache/caches/gatsby-plugin-sharp/diskstore-738cc1ae55010384992a326f43c2e943.json'
```

### Environment

```shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.13.1 - ~/.nvm/versions/node/v14.13.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v14.13.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 91.0.4472.114
    Safari: 14.1.1
  npmPackages:
    gatsby: ^3.9.0 => 3.9.0
    gatsby-plugin-gatsby-cloud: ^2.9.0 => 2.9.0
    gatsby-plugin-image: ^1.9.0 => 1.9.0
    gatsby-plugin-manifest: ^3.9.0 => 3.9.0
    gatsby-plugin-offline: ^4.9.0 => 4.9.0
    gatsby-plugin-react-helmet: ^4.9.0 => 4.9.0
    gatsby-plugin-sharp: ^3.9.0 => 3.9.0
    gatsby-source-filesystem: ^3.9.0 => 3.9.0
    gatsby-transformer-sharp: ^3.9.0 => 3.9.0
```

**Comment by LekoArts** [comment] 2021-07-14 05:41
Hi!

This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/32288 and was fixed in `gatsby@3.9.1`. I just merged https://github.com/gatsbyjs/gatsby/pull/32317 to update the starter.

**Closed by LekoArts** 2021-07-14 05:41 UTC
Labels: type: bug
