### ISSUE TITLE
Error: Cannot find module '@mdx-js/mdx'

### ISSUE THREAD

**Issue by mikeyfe6** [gatsbyjs/gatsby#26823] opened 2020-09-08 12:50 UTC
**After the last update of today i'm getting this error. I'm using no MDX in my project howsoever..**

`npm run develop` produces this issue, does someone has some knowledge about this?

Issue on Stackoverflow: https://stackoverflow.com/q/63781043/8408438

## Description

```
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module '@mdx-js/mdx'
Require stack:
- /Users/mikey/Sites/Gimmix/node_modules/gatsby-recipes/dist/transform-recipe-mdx.js
- /Users/mikey/Sites/Gimmix/node_modules/gatsby-recipes/dist/renderer/index.js
- /Users/mikey/Sites/Gimmix/node_modules/gatsby-recipes/dist/validate-steps.js
- /Users/mikey/Sites/Gimmix/node_modules/gatsby-recipes/dist/recipe-machine/index.js
- /Users/mikey/Sites/Gimmix/node_modules/gatsby-recipes/dist/graphql-server/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/mikey/Sites/Gimmix/node_modules/gatsby-recipes/dist/transform-recipe-mdx.js:12:35)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/mikey/Sites/Gimmix/node_modules/gatsby-recipes/dist/transform-recipe-mdx.js',
    '/Users/mikey/Sites/Gimmix/node_modules/gatsby-recipes/dist/renderer/index.js',
    '/Users/mikey/Sites/Gimmix/node_modules/gatsby-recipes/dist/validate-steps.js',
    '/Users/mikey/Sites/Gimmix/node_modules/gatsby-recipes/dist/recipe-machine/index.js',
    '/Users/mikey/Sites/Gimmix/node_modules/gatsby-recipes/dist/graphql-server/server.js'
  ]
}
```

### Steps to reproduce

https://gimmix.nl = Demo/Live Project

### Expected result

No **warnings** or **errors**. Before the update it was **not** an issue.

### Actual result

My local machine is not bothered, but it don't like bugs/warnings/error, because you never know what other code it might mess up in future updates from other corresponding packages.

### Environment

```
System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.11.0 - ~/.nvm/versions/node/v13.11.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v13.11.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 85.0.4183.83
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.24.54 => 2.24.54
    gatsby-image: ^2.4.17 => 2.4.17
    gatsby-plugin-canonical-urls: ^2.3.9 => 2.3.10
    gatsby-plugin-catch-links: ^2.3.11 => 2.3.11
    gatsby-plugin-eslint: ^2.0.8 => 2.0.8
    gatsby-plugin-google-analytics: ^2.3.13 => 2.3.13
    gatsby-plugin-google-tagmanager: ^2.3.10 => 2.3.11
    gatsby-plugin-manifest: ^2.4.28 => 2.4.28
    gatsby-plugin-netlify: ^2.3.14 => 2.3.14
    gatsby-plugin-nprogress: ^2.3.9 => 2.3.10
    gatsby-plugin-offline: ^3.2.27 => 3.2.27
    gatsby-plugin-react-helmet: ^3.3.9 => 3.3.10
    gatsby-plugin-robots-txt: ^1.5.1 => 1.5.1
    gatsby-plugin-sass: ^2.3.10 => 2.3.12
    gatsby-plugin-sharp: ^2.6.32 => 2.6.32
    gatsby-plugin-sitemap: ^2.4.12 => 2.4.12
    gatsby-plugin-smoothscroll: ^1.2.0 => 1.2.0
    gatsby-remark-embedder: ^3.0.0 => 3.0.0
    gatsby-remark-images: ^3.3.29 => 3.3.29
    gatsby-remark-images-contentful: ^2.3.16 => 2.3.16
    gatsby-remark-relative-images: ^2.0.2 => 2.0.2
    gatsby-source-contentful: ^2.3.42 => 2.3.42
    gatsby-source-filesystem: ^2.3.28 => 2.3.28
    gatsby-transformer-remark: ^2.8.33 => 2.8.33
    gatsby-transformer-sharp: ^2.5.14 => 2.5.14
  npmGlobalPackages:
    gatsby-cli: 2.12.68
```

**Comment by LekoArts** [comment] 2020-09-08 12:57
Duplicate of https://github.com/gatsbyjs/gatsby/issues/26815

**Closed by LekoArts** 2020-09-08 12:57 UTC
Labels: type: bug
