### ISSUE TITLE
Differences in query/config

### ISSUE THREAD

**Issue by Immortalin** [gatsbyjs/gatsby#24190] opened 2020-05-18 16:58 UTC
When using the Gatsby-image-sharp plugin, the following query does not work and gives `Unknown fragment: GatsbyImageSharpFluid_tracedSVG`:
```graphql
 {
      space: file(relativePath: {eq: "topics/space.jpeg"}) {
        childImageSharp {
          fluid(maxWidth: 2000) {
           ...GatsbyImageSharpFluid_tracedSVG
          }
        }
  }}
```
but this works:
```graphql
{
  space: file(relativePath: {eq: "topics/space.jpeg"}) {
    childImageSharp {
      fluid(maxWidth: 2000) {        
               tracedSVG
      }
    }
  }
} 
```

Is there a misconfiguration somewhere?

**Comment by blainekasten** [comment] 2020-05-18 17:48
Are you trying to execute this query within gatsby-node? If so, we don't currently support fragments in gatsby-node.

Otherwise, share a bit more information about your setup please! The `GatsbyImageSharpFluid_tracedSVG` fragment gets added by `gatsby-transformer-sharp`, so make sure you have that package installed and part of your gatsby-config plugins.

**Comment by Immortalin** [comment] 2020-05-18 18:22
It's executed from the Gatsby graphql console, setup is from https://www.gatsbyjs.org/docs/working-with-images/#using-fragments-to-standardize-formatting

**Comment by rori4** [comment] 2020-05-20 08:22
I also have the same issue. Using GatsbyImageSharpFluid in graphql console says its unknown fragment

**Comment by LekoArts** [comment] 2020-05-20 08:40
Thank you for opening this!

GraphQL fragments like `GatsbyImageSharpFluid` get auto-imported by their respective plugins and hence are available in page and static queries. They don't get their way into gatsby-node **plus** GraphiQL. The fragments aren't available there either. So while this is unfortunate it's working as intended. We're tracking it here: https://github.com/gatsbyjs/gatsby/issues/12155

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2020-05-20 08:40 UTC
Labels: type: question or discussion
