### ISSUE TITLE
[gatsby-transformer-json] graphql name error

### ISSUE THREAD

**Issue by eLod** [gatsbyjs/gatsby#7670] opened 2018-08-27 06:18 UTC
## Description

When gatsby loads json from a directory that's name starts with numeric it fails with graphql name error (i think it's coming from the `internal.type` which is set by `gatsby-transformer-json` to start with the subdirectory name).

### Steps to reproduce

- create a new app (i used the default start v2)
- add gatsby-source-filesystem and gatsby-transformer-json
- create a json file like `src/data/42/foo.json`
- run gatsby develop

### Expected result

it should work

### Actual result

```
Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "42Json" does not.
  Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "42Json" does not.
  Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "42JsonConnectionSort" does not.
  Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "42JsonConnectionSortByFieldsEnum" does not.
  Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "42JsonConnectionSortOrderValues" does not.
...
```

### Environment

```
  System:
    OS: OS X El Capitan 10.11.2
    CPU: x64 Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.8.0 - /usr/local/bin/node
    Yarn: yarn install v0.24.6
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 8.10s. - /usr/local/bin/yarn
    npm: 6.3.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 57.0
    Safari: 9.0.2
  npmPackages:
    gatsby: next => 2.0.0-rc.0 
    gatsby-plugin-manifest: next => 2.0.2-rc.0 
    gatsby-plugin-offline: next => 2.0.0-rc.0 
    gatsby-plugin-react-helmet: next => 3.0.0-rc.0 
    gatsby-source-filesystem: ^2.0.1-rc.0 => 2.0.1-rc.0 
    gatsby-transformer-json: ^2.1.1-rc.0 => 2.1.1-rc.0 
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LeKoArts** [comment] 2018-08-27 07:15
To my knowledge this is a limitation of the GraphQL implementation and nothing that can be changed:
https://github.com/graphql/graphql-js/blob/6e7d51d6c8fb9ed66d93510fa49477a05dd751af/src/utilities/assertValidName.js#L56

You‘ll need to prefix these numbers

**Comment by LeKoArts** [comment] 2018-08-27 10:37
> yes but it is caused by gatsby-transform-json, if it would use another type string (which seems to be arbitrary in the first place) there wouldn't be any error.

No, this error occurs with every source plugin / transformer. When I built a source plugin I also had to prefix API responses when they had a number in the first place.

**Comment by eLod** [comment] 2018-08-27 11:51
look, i think we are misunderstanding each other. the json **DOES NOT** have a key with a number. it is caused/created/introduced by `gatsby-transform-json` progamatically.  gatsby tries to create a node with name/key `42JsonConnection` (and others) **BECAUSE** `gatsby-transform-json` uses the **subdirectory name** when setting `node.internal.type` and it happens when it builds schema (i guess for discovery/reflection/whatever). the json itself **DOES NOT CONTAIN ANY DATA**.

**Comment by eLod** [comment] 2018-08-27 11:54
@LeKoArts again it is caused by this line: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-json/src/gatsby-node.js#L48

because this line a json with contents `{"foo": "bar"}` inside a directory named **42** (e.g. `src/data/42/foo.json`) will trigger the error, as it tries to create a (json) node with `node.internal.type="42 Json"` which in turn will lead to the error

**Comment by eLod** [comment] 2018-08-27 11:56
in other words the error is caused by **the directory name** and has nothing to do with the json contents

**Comment by LeKoArts** [comment] 2018-08-27 12:18
I never said that the problem is the JSON file. I know that the transformer also uses the directory name to create the nodes. But that doesn’t change the meaning of my initial message. GraphQL doesn’t allow numbers as first character and that does apply for every entry while creating the node.
You‘ll need to rename the directory.

**Comment by eLod** [comment] 2018-08-27 12:32
@LeKoArts i am happy to do a pr on flipping the type or anything like that. i am new to gatsby so i also don't know about the conventions. can we ping somebody?

**Comment by pieh** [comment] 2018-09-10 20:27
This was fixed with https://github.com/gatsbyjs/gatsby/pull/7913 (thanks @eLod) and even better handling added with #7914 , so I'll close this issue

**Closed by pieh** 2018-09-10 20:27 UTC
Labels: type: maintenance
