### ISSUE TITLE
Preparing requested page loop, project won't display in browser

### ISSUE THREAD

**Issue by ggs-landscaping** [gatsbyjs/gatsby#33888] opened 2021-11-07 03:40 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When running gatsby develop, no errors occur. However when opening localhost:8000 in the browser, it only shows a blank white page and a "Preparing requested page" message in the bottom left corner. 

[Link to what I'm seeing.](https://media.discordapp.net/attachments/537691356487876624/906745999807107103/Untitled.png)

There's also a console error:

```
app.js:178 Uncaught (in promise) TypeError: $RefreshSig$ is not a function
    at eval
```

### Reproduction Link

https://github.com/ggs-landscaping/ggs

### Steps to Reproduce

1. Run gatsby develop
2. Open browser

### Expected Result

Expected to see the website project.

### Actual Result

Shows a blank white page and a "Preparing requested page" message in the bottom left corner. 

### Environment

```shell
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
  Binaries:
    Node: 14.15.4 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.10 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - /c/Users/Jarryd/.windows-build-tools/python27/python  Browsers:
    Chrome: 95.0.4638.69
    Edge: Spartan (44.19041.1266.0), Chromium (95.0.1020.44)
  npmPackages:
    gatsby: ^3.14.5 => 3.14.5
    gatsby-plugin-google-analytics: ^2.6.0 => 2.11.0
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-html-attributes: ^1.0.5 => 1.0.5
    gatsby-plugin-preact: ^4.2.0 => 4.7.0
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-preload-fonts: ^1.4.0 => 1.9.1
    gatsby-plugin-react-helmet: ^3.4.0 => 3.10.0
    gatsby-plugin-robots-txt: ^1.6.14 => 1.6.14
    gatsby-plugin-sass: ^2.5.1 => 2.8.0
    gatsby-plugin-sitemap: ^2.7.0 => 2.12.0
    gatsby-source-filesystem: ^2.6.0 => 2.11.1
  npmGlobalPackages:
    gatsby-cli: 2.15.0
```

**Comment by graysonhicks** [comment] 2021-11-07 05:01
Removing gatsby-plugin-preact resolves this fwiw.

**Comment by graysonhicks** [comment] 2021-11-07 05:08
Bumping gatsby-plugin-preact to 5.0.0 seems to resolve.

**Comment by pragmaticpat** [comment] 2021-11-10 13:54
@ggs-landscaping - did you try what @graysonhicks suggested?

**Comment by pragmaticpat** [comment] 2021-11-10 14:02
@ggs-landscaping - I just attempted to repro following the steps you shared above ( and thank you for providing a sample repo! ) - I'm not seeing the same results you are.

```
 System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /usr/local/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 8.1.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 95.0.4638.69
    Firefox: 89.0.2
    Safari: 15.1
  npmPackages:
    gatsby: ^2.32.13 => 2.32.13
    gatsby-plugin-google-analytics: ^2.6.0 => 2.11.0
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-html-attributes: ^1.0.5 => 1.0.5
    gatsby-plugin-preact: ^4.2.0 => 4.7.0
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-preload-fonts: ^1.4.0 => 1.9.1
    gatsby-plugin-react-helmet: ^3.4.0 => 3.10.0
    gatsby-plugin-robots-txt: ^1.6.14 => 1.6.14
    gatsby-plugin-sass: ^2.5.1 => 2.8.0
    gatsby-plugin-sitemap: ^2.7.0 => 2.12.0
    gatsby-source-filesystem: ^2.6.0 => 2.11.1
```

Are you still seeing this problem?

**Comment by LekoArts** [comment] 2021-11-22 11:01
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-11-22 11:01 UTC
Labels: type: bug, status: needs reproduction, gatsby 3

**Comment by nabilzouhir** [comment] 2022-04-01 06:32
I was able to reproduce the error. To solve it I ran `gatsby clean` and then `gatsby develop` and it worked
