### ISSUE TITLE
gatsby error on c9.io :: npm EPEERINVALID history 

### ISSUE THREAD

**Issue by wommy** [gatsbyjs/gatsby#180] opened 2016-03-10 04:57 UTC
let me know how else i can help

---

zipped and attached is my [terminal.log](https://github.com/gatsbyjs/gatsby/files/166526/terminal.zip) and my [npm-debug.log](https://github.com/gatsbyjs/gatsby/files/166521/npm-debug.zip)

---
'npm install -g gatsby' warnings 
```
npm WARN peerDependencies The peer dependency history@^1.12.1 || ^2.0.0 included from scroll-behavior will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN optional dep failed, continuing fsevents@1.0.8
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN optional dep failed, continuing fsevents@1.0.8
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
```

---
'gatsby new my-site-title' error
```
[Error: npm WARN package.json gatsby-starter-default@1.0.0 No repository field.
npm WARN peerDependencies The peer dependency eslint-plugin-react@^3.16.1 included from eslint-config-airbnb will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm ERR! Linux 4.2.0-c9
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v4.3.2/bin/node" "/home/ubuntu/.nvm/versions/node/v4.3.2/bin/npm" "install"
npm ERR! node v4.3.2
npm ERR! npm  v2.14.12
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package eslint-plugin-react@4.2.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-config-airbnb@5.0.1 wants eslint-plugin-react@^3.16.1

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/workspace/test/npm-debug.log
]
```

---
workspace/test 'gatsby develop' errors

`  [248] /home/ubuntu/.nvm/versions/node/v4.3.2/lib/~/gatsby/~/history/lib/DOMStateStorage.js 2.15 kB {0} [built] [1 error]`

```
ERROR in /home/ubuntu/.nvm/versions/node/v4.3.2/lib/~/gatsby/~/history/lib/DOMStateStorage.js
Module not found: Error: Cannot resolve module 'warning' in /home/ubuntu/.nvm/versions/node/v4.3.2/lib/node_modules/gatsby/node_modules/history/lib
 @ /home/ubuntu/.nvm/versions/node/v4.3.2/lib/~/gatsby/~/history/lib/DOMStateStorage.js 10:15-33
```

**Comment by KyleAMathews** [comment] 2016-03-10 18:29
I think this issue was resolved by [this PR by @scottnonnenberg](https://github.com/gatsbyjs/gatsby/pull/174) a few days ago.

Which version of Gatsby are you on?

Try installing the latest by running `npm install -g gatsby`

**Comment by mef** [comment] 2016-03-24 17:04
I have the same problem as the one reported in the issue.

> 
Which version of Gatsby are you on?

    $ gatsby -V
    0.8.11


>
Try installing the latest by running npm install -g gatsby

The problem happened right after doing a clean install today using `npm install -g gatsby`.

Problems happens both when using  node v0.12.7 and v4.4.0.

No problem with node v5.1.0.

**Comment by KyleAMathews** [comment] 2016-03-24 17:27
Hmmm... looks like the problem is with NPM 2 as some of the starters have bad dependencies. @mef or @wommy if either of you could look at upgrading the starter dependencies so they work on NPM 2 and create a PR that'd be :100:

**Comment by mef** [comment] 2016-03-24 22:05
done for default, blog and documentation starters :)

**Comment by KyleAMathews** [comment] 2016-03-24 22:08
Awesome thanks @mef!

I'll close this as it seems like the issue is solved.

**Closed by KyleAMathews** 2016-03-24 22:08 UTC

**Comment by mef** [comment] 2016-03-24 22:11
You're welcome.

In the mean time I found another dependency problem in the default starter, will have a look at it (the two other ones work well now).

**Comment by KyleAMathews** [comment] 2016-03-24 22:12
+1
