### ISSUE TITLE
ACF Relationship Field throws an error in Gatsby

### ISSUE THREAD

**Issue by gustavpursche** [gatsbyjs/gatsby#30299] opened 2020-11-23 10:55 UTC
I'm running into a problem, where a query throws an error, which works on the remote GraphiQL endpoint, when using an ACF Relationship field.

```graphql
query {
  page(id: "730", idType: DATABASE_ID) {
    acf {
      content {
        ... on Page_Acf_Content_FeaturedNews {
          news {
            ... on NewsEntry {
              id
            }
          }
        }
      }
    }
  }
}
```

returns on the remote GraphiQL:

```json
{
  "data": {
    "page": {
      "acf": {
        "content": [
          {
            "news": [
              {
                "id": "cG9zdDoyNjI4"
              },
              {
                "id": "cG9zdDoyNjMy"
              },
              {
                "id": "cG9zdDoyNjE3"
              }
            ]
          }
        ]
      }
    }
  }
}
```

but the same query throws an error in Gatsby:

```graphql
query MyQuery {
  wpPage(databaseId: {eq: 730}) {
    acf {
      content {
        ... on WpPage_Acf_Content_FeaturedNews {
          news {
            ... on WpNewsEntry {
              id
            }
          }
        }
      }
    }
  }
}
```

result:

```json
{
  "errors": [
    {
      "message": "Cannot read property 'id' of null",
      "locations": [
        {
          "line": 6,
          "column": 11
        }
      ],
      "path": [
        "wpPage",
        "acf",
        "content",
        5,
        "news"
      ],
      "stack": [
        "TypeError: Cannot read property 'id' of null",
        "    at reduce (~/node_modules/gatsby-source-wordpress-experimental/src/steps/create-schema-customization/transform-fields/transform-union.js:49:27)",
        "    at Array.reduce (<anonymous>)",
        "    at resolver (~/node_modules/gatsby-source-wordpress-experimental/src/steps/create-schema-customization/transform-fields/transform-union.js:46:28)",
        "    at wrappedTracingResolver (~/node_modules/gatsby/src/schema/resolvers.ts:518:14)",
        "    at resolveFieldValueOrError (~/node_modules/graphql/execution/execute.js:467:18)",
        "    at resolveField (~/node_modules/graphql/execution/execute.js:434:16)",
        "    at executeFields (~/node_modules/graphql/execution/execute.js:275:18)",
        "    at collectAndExecuteSubfields (~/node_modules/graphql/execution/execute.js:713:10)",
        "    at completeObjectValue (~/node_modules/graphql/execution/execute.js:703:10)",
        "    at completeAbstractValue (~/node_modules/graphql/execution/execute.js:660:10)",
        "    at completeValue (~/node_modules/graphql/execution/execute.js:585:12)",
        "    at completeValueCatchingError (~/node_modules/graphql/execution/execute.js:495:19)",
        "    at ~/node_modules/graphql/execution/execute.js:618:25",
        "    at Array.forEach (<anonymous>)",
        "    at forEach (~/node_modules/iterall/index.js:83:25)",
        "    at completeListValue (~/node_modules/graphql/execution/execute.js:614:24)",
        "    at completeValue (~/node_modules/graphql/execution/execute.js:573:12)",
        "    at ~/node_modules/graphql/execution/execute.js:492:16",
        "    at runMicrotasks (<anonymous>)",
        "    at processTicksAndRejections (internal/process/task_queues.js:93:5)",
        "    at async Promise.all (index 0)",
        "    at async Promise.all (index 0)",
        "    at async Promise.all (index 0)"
      ]
    }
  ],
  "data": {
    "wpPage": {
      "acf": {
        "content": [
          {
            "news": null
          }
        ]
      }
    }
  }
}
```

kolle-on-xps :: Development/ » npx gatsby info

  System:
    OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.15.1 - /usr/bin/node
    Yarn: 1.22.4 - ~/.npm-global/bin/yarn
    npm: 6.14.8 - ~/.npm-global/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Firefox: 83.0
  npmPackages:
    gatsby: ^2.24.91 => 2.27.0 
    gatsby-image: ^2.6.0 => 2.6.0 
    gatsby-link: ^2.4.16 => 2.6.0 
    gatsby-plugin-advanced-sitemap: ^1.5.6 => 1.5.6 
    gatsby-plugin-manifest: ^2.4.37 => 2.7.0 
    gatsby-plugin-netlify: ^2.3.25 => 2.6.0 
    gatsby-plugin-react-helmet: ^3.3.14 => 3.5.0 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-sharp: ^2.6.43 => 2.9.0 
    gatsby-plugin-styled-jsx: ^3.5.0 => 3.5.0 
    gatsby-source-filesystem: ^2.3.37 => 2.6.1 
    gatsby-source-wordpress-experimental: ^3.1.3 => 3.1.3 
    gatsby-transformer-sharp: ^2.5.20 => 2.7.0 

using WPGraphQL: 1.0

**Comment by lamnguyen1210** [comment] 2021-03-26 03:11
Are there any updates for this issue? I'm having the same issue when I add a post to a relationship field of ACF, then I trash that post or change status of the post into draft.

**Comment by peteluffman** [comment] 2021-04-09 15:05
Just ran into same issue here as @lamnguyen1210. Emptying the trash allowed me to build successfully. 

It could be a bug with the wp-graphql-acf plugin rather than with gatsby source wordpress, see  https://github.com/wp-graphql/wp-graphql-acf/issues/167

I haven't yet tried the workaround listed there.

**Comment by LekoArts** [comment] 2021-04-20 08:16
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-04-20 08:16 UTC
Labels: status: needs reproduction, topic: WordPress

**Comment by verystack** [comment] 2021-10-09 13:58
This is still an issue.

**Comment by upham-ui** [comment] 2021-10-20 00:53
It sure is...

**Comment by rotijoe** [comment] 2021-11-09 14:23
I get this error when I query a flexible content field in my gatsby-node.js, on "gatsby build" but not on "gatsby develop"...

**Comment by domvo** [comment] 2022-01-11 08:50
Very much still an issue, if there is a relationship to a post that is turned into a draft, this breaks! Didn't find a workaround other than removing these relationships by hand. In my small example that's okay, but imagine having to do this for thousands of posts (or having to write a script that alters the DB in such a way).

**Comment by stackpath-andrew** [comment] 2022-05-21 11:35
This is still an issue.

Steps to reproduce...

1. related a post to page or post using the acf relationship field
2. set the post that was related to a draft
3. republish the post that was related but do not update that actual page/post that has the relationship field

Getting this error...

```
There was an error in your GraphQL query:

Cannot read property 'id' of null

1 | query partner($id: String!, $nextPage: String, $previousPage: String) {
   2 |   partner: wpCaseStudy(id: {eq: $id}) {
   3 |     uri
   4 |     acfCaseStudy {
   5 |       heading
   6 |       companyDescription
   7 |       useCases
>  8 |       products {
     |       ^
   9 |         __typename
  10 |         ... on WpProduct {
  11 |           id
  12 |           title
  13 |           slug
  14 |         }
  15 |       }
  16 |     }
  17 |     industry {
  18 |       nodes {
```
```
