### ISSUE TITLE
Styled Components not working in MDX file?

### ISSUE THREAD

**Issue by rchrdnsh** [gatsbyjs/gatsby#19497] opened 2019-11-14 03:44 UTC
I have a couple styled components defined in a file called `ScrollBox.js`, like so:

```jsx
import styled from 'styled-components'

const Scroll = styled.div`
  grid-column: 1 / 4;
  overflow-x: scroll;
  overflow-y: hidden;
  white-space: nowrap;
  -webkit-overflow-scrolling: touch;
  background: #111;
  padding: 2rem;
`

const Image = styled.img`
  display: inline-block;
  width: calc(300px + (450 - 300) * ((100vw - 300px) / (1600 - 300)));
  height: auto;
  padding: 16px;
`

export { Scroll, Image }
```

then I import them into an MDX file, like so:

```jsx
import { Scroll, Image } from './components/ScrollBox'
```

and then use them with some images, like so:

```jsx
<Scroll>
  <Image src="images/chords/minor-triads/a-minor-triad.png" alt=""/>
  <Image src="images/chords/minor-triads/b-flat-minor-triad.png" alt=""/>
  <Image src="images/chords/minor-triads/b-minor-triad.png" alt=""/>
  <Image src="images/chords/minor-triads/c-minor-triad.png" alt=""/>
  <Image src="images/chords/minor-triads/C-sharp-minor-triad.png" alt=""/>
  <Image src="images/chords/minor-triads/d-minor-triad.png" alt=""/>
  <Image src="images/chords/minor-triads/d-sharp-minor-or-e-flat-minor-triad.png" alt=""/>
  <Image src="images/chords/minor-triads/e-minor-triad.png" alt=""/>
  <Image src="images/chords/minor-triads/f-minor-triad.png" alt=""/>
  <Image src="images/chords/minor-triads/f-sharp-minor-triad.png" alt=""/>
  <Image src="images/chords/minor-triads/g-minor-triad.png" alt=""/>
  <Image src="images/chords/minor-triads/g-sharp-minor-triad.png" alt=""/>
</Scroll>
```

...but none of the css in the styled components is working properly. The images show up but are not formatted properly at all. They should be in a container that scrolls horizontally, but they just end up being laid out as block elements down the page, also in the incorrect grid column.

If I use those same styled components in a gatsby `page` they work as expected, so I have no idea what I might be doing wrong here.

**Comment by rchrdnsh** [comment] 2019-11-20 07:19
nobody? @johno? @ChristopherBiscardi? Should I NOT expect this to work properly?

**Comment by LekoArts** [comment] 2019-11-20 09:25
Thank you for opening this!

I can't reproduce your problem in either pages or files that get used via createPage: https://codesandbox.io/s/mdx-styled-components-components-9t7it

You likely have an error in your path to the component. Have a look at the codesandbox and/or try to adapt your project.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2019-11-20 09:25 UTC
Labels: type: question or discussion

**Comment by rchrdnsh** [comment] 2019-11-20 17:57
hmmmm...so I peeked into the console and I noticed this:

```bash
[Error] Warning: The tag <scroll> is unrecognized in this browser. If you meant to render a React component, start its name with an uppercase letter.
    in scroll (created by MDXCreateElement)
    in MDXCreateElement (created by MDXContent)
    in wrapper (created by MDXCreateElement)
    in MDXCreateElement (created by MDXContent)
    in MDXContent (created by MDXRenderer)
    in MDXRenderer (at article.js:313)
    in div (created by Context.Consumer)
    in StyledComponent (created by article__Content)
    in article__Content (at article.js:312)
    in div (created by Context.Consumer)
    in StyledComponent (created by article__ArticleBlock)
    in article__ArticleBlock (at article.js:301)
    in MDXProvider (at article.js:297)
    in Article (created by HotExportedArticle)
    in AppContainer (created by HotExportedArticle)
    in HotExportedArticle (created by PageRenderer)
    in main (created by Context.Consumer)
    in StyledComponent (created by Layout__Main)
    in Layout__Main (at Layout.js:157)
    in div (created by ForwardRef(MotionComponent))
    in ForwardRef(MotionComponent) (created by Context.Consumer)
    in StyledComponent (created by Layout__App)
    in Layout__App (at Layout.js:148)
    in MusicPlayerProvider (at Layout.js:147)
    in Layout (created by PageRenderer)
    in PageRenderer (at json-store.js:93)
    in JSONStore (at root.js:51)
    in RouteHandler (at root.js:73)
    in div (created by FocusHandlerImpl)
    in FocusHandlerImpl (created by Context.Consumer)
    in FocusHandler (created by RouterImpl)
    in RouterImpl (created by Context.Consumer)
    in Location (created by Context.Consumer)
    in Router (created by EnsureResources)
    in ScrollContext (at root.js:64)
    in RouteUpdates (at root.js:63)
    in EnsureResources (at root.js:61)
    in LocationHandler (at root.js:119)
    in LocationProvider (created by Context.Consumer)
    in Location (at root.js:118)
    in Root (at root.js:126)
    in MDXProvider (at wrap-root-element.js:65)
    in MDXScopeProvider (at wrap-root-element.js:64)
    in Unknown
    in Unknown (at wrap-root-element.js:72)
    in _default (at app.js:67)
	warningWithoutStack (commons.js:25695)
	warning (commons.js:26183)
	createElement (commons.js:33015)
	createInstance (commons.js:34638)
	completeWork (commons.js:46209)
	completeUnitOfWork (commons.js:49860)
	performUnitOfWork (commons.js:49836)
	workLoopSync (commons.js:49801)
	performSyncWorkOnRoot (commons.js:49400)
	scheduleUpdateOnFiber (commons.js:48828)
	updateContainer (commons.js:52224)
	(anonymous function) (commons.js:52648)
	unbatchedUpdates (commons.js:49563)
	legacyRenderSubtreeIntoContainer (commons.js:52647)
	(anonymous function) (commons.js:1088)
```

and in the elements tab in dev tools, it looks like the styles are not getting applied properly to the element, and it's being rendered as just `<scroll>`, like so:

<img width="414" alt="Screen Shot 2019-11-20 at 9 51 56 AM" src="https://user-images.githubusercontent.com/7884263/69264112-8779a280-0b7b-11ea-9bba-961025ceac35.png">

whereas your example renders properly, with the right class applied to it, like so:

<img width="382" alt="Screen Shot 2019-11-20 at 9 54 02 AM" src="https://user-images.githubusercontent.com/7884263/69264221-b6901400-0b7b-11ea-81c2-58d376622745.png">

and the components are being imported fine it would seem, as they still render into the page, just with no styles applied...

...this seems really odd, and I'm I have no idea what could possibly be going on...

**Comment by rchrdnsh** [comment] 2019-11-25 18:50
hi @LekoArts, it seems like it might be an issue with using `gatsby-remark-images` with mdx that is causing the issue. I will try to replicate it using your sandbox and see if that is indeed the case...

**Comment by rchrdnsh** [comment] 2019-11-25 21:48
Hi @LekoArts, made a new issue here:

https://github.com/gatsbyjs/gatsby/issues/19785

As the issue seems to actually be a potential bug in `gatsby-remark-images` inside of `gatsby-plugin-mdx` and that breaking styled-components or emotion components with those images inside of them...made a minimal repo there to show the issue...
