### ISSUE TITLE
 Uncaught Error: The result of this StaticQuery could not be fetched. 

### ISSUE THREAD

**Issue by HasanEr** [gatsbyjs/gatsby#29992] opened 2021-03-04 13:40 UTC
I can not fixed this error. 

This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues

    at useStaticQuery (gatsby-browser-entry.js:77)
    at Info (info.js:7)
    at renderWithHooks (react-dom.development.js:14804)
    at mountIndeterminateComponent (react-dom.development.js:17483)
    at beginWork (react-dom.development.js:18597)
    at HTMLUnknownElement.callCallback (react-dom.development.js:189)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:238)
    at invokeGuardedCallback (react-dom.development.js:293)
    at beginWork$1 (react-dom.development.js:23204)
    at performUnitOfWork (react-dom.development.js:22158)
    at workLoopSync (react-dom.development.js:22131)
    at performSyncWorkOnRoot (react-dom.development.js:21757)
    at scheduleUpdateOnFiber (react-dom.development.js:21189)
    at updateContainer (react-dom.development.js:24374)
    at react-dom.development.js:24759
    at unbatchedUpdates (react-dom.development.js:21904)
    at legacyRenderSubtreeIntoContainer (react-dom.development.js:24758)
    at render (react-dom.development.js:24841)
    at app.js:166
    at HTMLDocument.listener (ready.js:32)

my code is

```

import React from "react"
import { graphql, useStaticQuery } from "gatsby"
import Img from "gatsby-image"


const Info = () => {
  const data = useStaticQuery(graphql`
    query {
      allStrapiInfo(filter: { id: { eq: "Info_1" } }) {
        edges {
          node {
            button
            description
            ikon {
              childImageSharp {
                fixed {
                  ...GatsbyImageSharpFixed
                }
              }
            }
            title
            id
          }
        }
      }
    }
  `)

  return (
  <div class="w-full infoHeight ">
      {data.allStrapiInfo.edges.map(node => (
        <div>
          <Img fixed={node.node.ikon.childImageSharp.fixed} />
          <h3>{node.node.title}</h3>
          <hr></hr>
          <span>{node.node.description}</span>
          <button>{node.node.button}</button>
        </div>
      ))}
  </div>
  )
}

export default Info

```

**Comment by creotip** [comment] 2021-03-05 06:37
Try to use page query instead of useStaticQuery hook

**Comment by LekoArts** [comment] 2021-03-05 09:05
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-03-15 08:38
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-03-15 08:38 UTC
Labels: status: needs reproduction, type: bug
