### ISSUE TITLE
Use source plugin data as initial value to context store

### ISSUE THREAD

**Issue by i8ramin** [gatsbyjs/gatsby#11849] opened 2019-02-18 01:08 UTC
Using React's new context API to manage my app's store. Wrapped the main root element with a Provoder (via wrapRootElement). Also loading some data via source plugins during build time. 

Question is, is it possible to access the graphQL data and pass it through to my Provider as initial value? Tried using StaticQuery within the context of wrapRootElement, but that didn't seem to work.

**Comment by wardpeet** [comment] 2019-02-18 14:49
It seems like a duplicate of #7747

**Closed** 2019-02-18 14:51 UTC
