### ISSUE TITLE
Link to sitemap tries to load `/page-data/sitemap.xml/page-data.json` and fails multiple times.

### ISSUE THREAD

**Issue by stevemarksd** [gatsbyjs/gatsby#29408] opened 2021-02-09 08:23 UTC
Link to sitemap causes error loading /page-data/sitemap.xml/page-data.json 

## Description

Link to sitemap causes error loading /page-data/sitemap.xml/page-data.json 

### Steps to reproduce

Add `<a href="/sitemap.xml">Sitemap</a>`

### Expected result
Should not try to load `/page-data/sitemap.xml/page-data.json `

### Actual result

Tries to load `/page-data/sitemap.xml/page-data.json `

![image](https://user-images.githubusercontent.com/58653359/107335504-f467b800-6af2-11eb-9af1-a21d5a340bce.png)

### Environment

```

  System:
    OS: Windows 10 10.0.190xx
    CPU: (12) x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
  Binaries:
    Node: 14.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.5
  npmPackages:
    gatsby: 2.31.1 => 2.31.1
    gatsby-image: 2.10.0 => 2.10.0
    gatsby-plugin-catch-links: ^2.0.9 => 2.3.11
    gatsby-plugin-emotion: ^4.0.0 => 4.5.0
    gatsby-plugin-layout: ^1.3.0 => 1.3.10
    gatsby-plugin-loadable-components-ssr: ^2.1.0 => 2.1.0
    gatsby-plugin-manifest: ^2.0.12 => 2.4.27
    gatsby-plugin-material-ui: ^2.1.8 => 2.1.10
    gatsby-plugin-netlify-cms: ^4.9.0 => 4.9.0
    gatsby-plugin-react-helmet: ^3.0.0 => 3.3.10
    gatsby-plugin-s3: ^0.3.4 => 0.3.5
    gatsby-plugin-sharp: 2.13.3 => 2.13.3
    gatsby-plugin-sitemap: ^2.0.3 => 2.4.12
    gatsby-plugin-typescript: ^2.0.3 => 2.4.18
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.9 => 1.1.12
    gatsby-react-router-scroll: ^3.6.0 => 3.6.0
    gatsby-remark-component: ^1.1.3 => 1.1.3
    gatsby-remark-images: ^3.10.0 => 3.10.0
    gatsby-remark-relative-images: ^2.0.2 => 2.0.2
    gatsby-source-filesystem: ^2.10.0 => 2.10.0
    gatsby-transformer-remark: ^2.15.0 => 2.15.0
    gatsby-transformer-sharp: 2.11.0 => 2.11.0


```

**Comment by ascorbic** [comment] 2021-02-11 10:15
Hi. This is being caused by [gatsby-plugin-catch-links/](https://www.gatsbyjs.com/plugins/gatsby-plugin-catch-links/) converting the `<a>` tag into a `<Link>`. If you add `sitemap.xml` to the `excludePattern` option then it should fix it. I'm going to close this issue as this should be the fix, but please reopen and tag me if this doesn't fix it. Thanks!

**Closed by ascorbic** 2021-02-11 10:15 UTC
Labels: topic: reach/router and Links, type: bug
