### ISSUE TITLE
PropTypes removed in production build from a `node_modules` package

### ISSUE THREAD

**Issue by matteofrana** [gatsbyjs/gatsby#31076] opened 2021-04-27 16:43 UTC
## Description

When I build a project importing `slate-react` v0.22.10 (I know it's quite old, but I have to stay with slate 0.47.x), the `propTypes` are stripped from the library code. Unfortunately it uses the key of the `propTypes` in the code, so that it breaks without them.

### Steps to reproduce

Install `slate@0.47.9` and `slate-react@0.22.10` and create a production build.

### Expected result

Gatsby should remove propTypes from the production build for just the project code and not for the `node_modules` packages.

### Actual result

You will see that the compiled code in the production build stripped away the propTypes. When using the library this causes an error when the code uses the propTypes internally.

### Environment

Latest Gatsby. I'll update the `gatsby info --clipboard` info tomorrow as soon as possible.

**Comment by LekoArts** [comment] 2021-04-28 08:27
Hi!

Can you provide a [minimal reproduction][reproduction] showing that this is a general problem with Gatsby and not an upstream issue with the package you're using? Our own `gatsby-plugin-image` is using `propTypes`:

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-image/src/components/static-image.tsx

And the propTypes get passed along to the browser so that you'll see errors like these:

![EvoWft1XIAgMCha](https://user-images.githubusercontent.com/16143594/116372010-4bd11680-a80c-11eb-913b-1e2d08f8ed55.png)

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-05-06 12:18
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-05-06 12:18 UTC
Labels: status: needs reproduction, type: bug
