### ISSUE TITLE
Contentful Image API returns error if requesting images with dimensions above 4000px

### ISSUE THREAD

**Issue by baseten** [gatsbyjs/gatsby#3409] opened 2018-01-04 11:00 UTC
The `responsiveSizes`, `responsiveResolution` and `resize` graphQL fields from `gatsby-source-contentful` can request images from the contentful API which are over 4000px in size. These will return errors from contentful.

**Comment by calcsam** [comment] 2018-01-04 16:47
Have you filed this with Contentful and gotten any feedback from them? Do you have a repro repo (even a bash script CURL-ing a resource would be great). 

If the issue is with an underlying CMS's API, we should get context from them before patching our plugin.

**Comment by baseten** [comment] 2018-01-04 17:44
No, I've not filed with Contentful, but will get in touch with them now. You can see the issue easily if you open a contentful image in a browser tab. Using the below image from gatsby's contentful example site:

https://images.contentful.com/rocybtov1ozk/KTRF62Q4gg60q6WCsWKw8/a8b2e93ac83fbbbb7bf9fba9f92b018e/soso.clock.jpg?w=4000&h=4000&q=50&fit=fill

If you change either the `w` or `h` to 4001 you'll receive an error saying `valid transformation: False`

**Comment by robinpyon** [comment] 2018-06-18 21:39
Came across this issue too. Reached out to Contentful who confirmed the 4000px width/height limit is real and [documented, though easy to miss](https://www.contentful.com/developers/docs/references/images-api/#/reference/resizing-&-cropping/specify-width-&-height/retrieve-an-image/console/js).

**Comment by LekoArts** [comment] 2018-12-04 15:02
Closing this as the original question was answered. If you want to document this limitation, we'd be happy to have a PR from you. It would probably be best to link to [contentful's documentation](https://www.contentful.com/developers/docs/references/images-api/) so we don't have to be in sync with theirs.

**Closed by LekoArts** 2018-12-04 15:02 UTC
Labels: status: blocked
