### ISSUE TITLE
Gatsby cache is not saving all the nodes inside  `sourceNodes`

### ISSUE THREAD

**Issue by kamit-transient** [gatsbyjs/gatsby#37545] opened 2023-01-30 08:27 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

To source data to gatsby, I am calling REST API inside `sourceNodes`, and to avoid fetching same data again I am saving the data to cache.

Currently, I am getting 232 posts, however calling `await cache.set('my_unique_key',myData)`  only saves 43 posts.

Someone, please help why gatsby's cache not saving all the posts data?

is there some size limit to cache?

Here is how I am doing:

```
let dataArr = [];
    let shouldBreak = false;

    let lastDate = await cache.get(POST_COLLECTION_LAST_CREATED_AT_CACHE_KEY);

    let body = {
        page: 1,
        limit: 50
    }

    if (lastDate) {
        body["date"] = lastDate;
    }

    while (true) {
        try {
            console.log(chalk.blueBright(`fetching data for : ${body}`));

            let response = await fetch(apiUrl, { headers: { 'Content-Type': 'application/json' }, method: 'post', body: JSON.stringify(Object.assign({}, { ...body, clientId: process.env.CONTENT_API_KEY })) })
            let data = await response.json();
            console.log(chalk.gray(`fetched total: ${data ? data.data.length : 0} contents`));

            let status = data.status;

            if (data.data && data.data.length) {
                dataArr = [...dataArr, ...data.data];
            }
            else {
                shouldBreak = true;
            }


            body.page = ++body.page;

            if (shouldBreak) {
                //elemt at index 0, would be the last fetched ement from the api
                await cache.set(POST_COLLECTION_LAST_CREATED_AT_CACHE_KEY, dataArr[0].created_at);
                await cache.set(POST_COLLECTION_CACHE_KEY, dataArr);
                console.log(chalk.green.bgYellow.bold(`Saved Total ${dataArr.length} posts to cache...`));


                break;
            }
        } catch (error) {

            if (error.message.includes("ECONNREFUSED")) {
                console.log(chalk.red(error));
                reporter.error(chalk.yellowBright.bgBlackBright("ECONNREFUSED: aborting source node"))
                break;
            }
            console.log(chalk.red(error));
        }

    }

// rest of the code......

```

Here are the version details:

```   
"gatsby": "^5.4.2"
 "react": "^18.2.0",
    "react-dom": "^18.2.0",

```

### Reproduction Link

no link

### Steps to Reproduce

1. Source Posts Data from API 
2. Try to save all the POsts to the gatsby cache, to avoid re-fetching again
3. Verify if all the Posts are saved.
...

### Expected Result

calling `cache.set(... , ...)`  should save all the data.

### Actual Result

Its not saving all the Posts (Total 232 posts), its saving only first 43 Posts data to gatsby cache.

### Environment

```shell
"gatsby": "^5.4.2",
 
"react": "^18.2.0",
    "react-dom": "^18.2.0",
```

**Comment by kamit-transient** [comment] 2023-02-02 10:58
folks, any suggestions ?

**Comment by LekoArts** [comment] 2023-02-02 11:48
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2023-02-15 08:35
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2023-02-15 08:35 UTC
Labels: type: bug, status: needs reproduction
