### ISSUE TITLE
[gatsby-image] Fixed image with media query are not resized

### ISSUE THREAD

**Issue by squelix** [gatsbyjs/gatsby#16763] opened 2019-08-20 11:26 UTC
## Description

I defined two fixed Image:
- for desktop with a media query
- for mobile without media query

When my screen resized it downloads the smallest image but it doesn't resize the `gatsby-image-wrapper` :/

### Steps to reproduce

I define the Graphql queries like this:
```javascript
export const query = graphql`
  query {
    imageDesktop: file(relativePath: { eq: "home/partners/image.png" }) {
      childImageSharp {
        fixed(width: 161) {
          ...GatsbyImageSharpFixed
        }
      }
    }
    imageMobile: file(relativePath: { eq: "home/partners/image.png" }) {
      childImageSharp {
        fixed(width: 111) {
          ...GatsbyImageSharpFixed
        }
      }
    }
  }
`;
```

Then I define the sources like this: 
```javascript
const sources = [
  data.imageMobile.childImageSharp.fixed,
  {
    ...data.imageDesktop.childImageSharp.fixed,
    media: `(min-width: 768px)`,
  },
]
```

And I use the sources:
```jsx
<Img
  alt="Alt for image"
  fixed={sources}
></Img>
```

### Expected result

What should happen?

### Actual result

The size of the Image is `161px` even after the breakpoint of `768px`, but id downloads the `111px` Image.

### Environment

```
  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.2 - /usr/local/opt/node@10/bin/node
    Yarn: 1.17.3 - /usr/local/Cellar/yvm/3.6.1/shim/yarn
    npm: 6.4.1 - /usr/local/opt/node@10/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 67.0.4
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.5.5 => 2.13.59
    gatsby-image: ^2.1.0 => 2.2.8
    gatsby-plugin-env-variables: ^1.0.1 => 1.0.1
    gatsby-plugin-manifest: ^2.1.1 => 2.2.5
    gatsby-plugin-nprogress: ^2.0.10 => 2.1.2
    gatsby-plugin-offline: ^2.1.1 => 2.2.5
    gatsby-plugin-postcss: ^2.0.7 => 2.1.2
    gatsby-plugin-react-helmet: ^3.0.12 => 3.1.3
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.2
    gatsby-plugin-robots-txt: ^1.4.0 => 1.5.0
    gatsby-plugin-sharp: ^2.1.3 => 2.2.11
    gatsby-plugin-sitemap: ^2.1.0 => 2.2.6
    gatsby-source-filesystem: ^2.0.36 => 2.1.9
    gatsby-transformer-sharp: ^2.1.21 => 2.2.6
```

**Comment by kimbaudi** [comment] 2019-09-10 19:10
@squelix - I think I'm also facing this same issue as well. I would need to create a minimal reproducible demo project, but at least wanted to comment that this issue shouldn't be stale.

BTW, I think you made a typo. In your graphql query, you name your files `lovysDesktop` and `lovysMobile`, but in your sources, you reference the files as `data.imageDesktop` and `data.imageMobile`.

**Comment by tajchumber** [comment] 2019-09-18 20:42
facing the same issue as well

**Comment by squelix** [comment] 2019-09-19 08:34
> @squelix - I think I'm also facing this same issue as well. I will try to create a minimal reproducible demo project, but at least wanted to comment that this issue shouldn't be stale.
> 
> BTW, I think you made a typo. In your graphql query, you name your files `lovysDesktop` and `lovysMobile`, but in your sources, you reference the files as `data.imageDesktop` and `data.imageMobile`.

I fixed my message, thanks :)

**Comment by yertech** [comment] 2019-11-27 06:17
Same issue for me with fixed Img

**Comment by squelix** [comment] 2019-12-17 09:08
yes :/

**Comment by zeeshanaligold** [comment] 2020-01-06 22:47
@squelix  did u get fixed?

**Comment by squelix** [comment] 2020-01-07 07:58
No... I don't have time to do it by myself, sorry :(

**Comment by qramilq** [comment] 2020-02-26 11:04
I I'm correct understanding, you can try to set media-query to mobile image too, 
Try to use `(max-width: 767px)`
```
const sources = [
  {
    ...data.imageMobile.childImageSharp.fixed,
   media: `(max-width: 767px)`
  },
  {
    ...data.imageDesktop.childImageSharp.fixed,
    media: `(min-width: 768px)`,
  },
]
```

Gatsby image use [window.matchMedia](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-image/src/index.js#L67) to get current image. Maybe it helps

**Comment by LeeRob97** [comment] 2020-03-09 19:48
@qramilq this worked for me!

**Comment by qramilq** [comment] 2020-03-10 12:18
@LeeRob97 you are welcome)

**Comment by LeeRob97** [comment] 2020-03-13 14:16
@qramilq I am running into a strange issue with the media queries, when I am in development mode things work fine, but as soon as I create my production build the first element in the array is always loaded in, regardless of the media query. I have to resize my window in order for things to start working correctly.

**Comment by qramilq** [comment] 2020-03-16 08:44
@LeeRob97 did you tried to cleat .cache and public folders before run build? Cause I don't think, that production version makes so seriously changes instead of development version.
Also, you can look to the gatsby-image source code, especially, at this line https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-image/src/index.js#L87 to understand, how it works)

**Comment by meros** [comment] 2020-04-01 13:09
I encountered this as well - the right image is loaded again when I resize the window over one of the media query boundaries... Development works fine, production suffers from the problem.

**Comment by meros** [comment] 2020-04-01 13:24
Here is a repro:
https://github.com/meros/gatsby-bug-repro-image-media-queries
So it turns out that the I do get right image, but it's layouting is not right at first load.

To trigger the bug, do: 
`yarn && yarn build`
`npx serve public`

open chrome http://localhost:5000 and resize the window. Try reloading - the image is size weirdly until you again resize window to a point where you hit one of the media query boundaries.

**Comment by LeeRob97** [comment] 2020-04-13 21:19
@qramilq I switched my images from type fixed to fluid and that works.

**Comment by crperez5** [comment] 2020-06-20 16:11
There's definitely a bug here. 

Gatsby will pick a different image depending on the environment.

- If development, it will pick the correct image based on the media property. 
- If production, it will pick the first image on the list.
 
Would be nice if someone could have a look at it. 

Thanks.

**Comment by comoser** [comment] 2020-06-24 15:25
@gatsbyjs/core how is this closed when people are still having this problem nowadays?
PS I'm having the exact same issues, so maybe we can reopen the ticket 👍

**Comment by KosGrillis** [comment] 2020-06-25 07:26
I'm experiencing the same problem, are we able to reopen this one?

I query for my images as follows:

```
imgLg: img {
  fixed(width: 734) {
    src
    srcSet
    width
    height
  }
}
imgMd: img {
  fixed(width: 568) {
    src
    srcSet
    width
    height
  }
}
imgSm: img {
  fixed(width: 375) {
    src
    srcSet
    width
    height
  }
}
```

I set up my sources as follows:

```
const imgSources = [
    {
      ...imageContent.imgSm.fixed,
      media: theme.breakpoints.sm,
    },
    {
      ...imageContent.imgSm.fixed,
      media: theme.breakpoints.md,
    },
    {
      ...imageContent.imgSm.fixed,
      media: theme.breakpoints.lg,
    },
]
```

In development this works fine, but in production the first source in that array is matched, until the screen is resized. Is it something to do with SSR?

**Comment by siffogh** [comment] 2020-07-15 14:33
Exactly the same issue, works on development but not in the production build.

**Comment by pvdz** [comment] 2020-07-15 14:48
Anybody willing to put up a PR to fix whatever the bug is?

**Comment by siffogh** [comment] 2020-07-15 15:23
I fixed it by using directly `gatsby-plugin-sharp` and not relying on `gatsby-image`:

```js

export default function Home() {
  const { mobileImage, desktopImage } = getImageSources();

  return (
    <div>
         ...
        <picture>
          <source media="(min-width: 480px)" srcSet={desktopImage.srcSet} />
          <img
            src={mobileImage.src}
            srcSet={mobileImage.srcSet}
            alt="home"
            loading="lazy"
          />
        </picture>
      ....
    </div>
  );
}

// P.S. You can also just grab src and srcSet instead of using `GatsbyImageSharpFixed` fragment
function getImageSources() {
  const data = useStaticQuery(graphql`
    query {
      mobileImage: file(relativePath: { eq: "home.png" }) {
        childImageSharp {
          fixed(width: 500) {
            ...GatsbyImageSharpFixed
          }
        }
      }
      desktopImage: file(relativePath: { eq: "home.png" }) {
        childImageSharp {
          fixed(width: 900) {
            ...GatsbyImageSharpFixed
          }
        }
      }
    }
  `);

  return {
    mobileImage: data.mobileImage.childImageSharp.fixed,
    desktopImage: data.desktopImage.childImageSharp.fixed
  };
}
```

**Comment by kaushalyap** [comment] 2020-07-21 13:34
@KyleAMathews Please reopen this issue.

**Comment by polarathene** [comment] 2020-07-22 04:09
This issue has been resolved with the following PR https://github.com/gatsbyjs/gatsby/pull/24811

Please subscribe to that and await it being reviewed and merged.

**Comment by pvdz** [comment] 2020-07-28 12:47
Reopening as there is a PR for it

**Comment by polarathene** [comment] 2020-08-18 00:40
Not stale, awaiting feedback on how to proceed from core team.

**Comment by polarathene** [comment] 2020-09-07 23:31
Not stale, awaiting feedback on how to proceed from core team.

**Closed** 2020-09-15 11:34 UTC
Labels: topic: images/media

**Comment by iheathers** [comment] 2021-01-25 14:11
@squelix  

const sources = [
{  ...data.imageMobile.childImageSharp.fixed,
media: `(max-width: 768px)`,},

  {
    ...data.imageDesktop.childImageSharp.fixed,
    media: `(max-width: 960px)`,  
  },
]

I did something like this to get it to work. I would love a mobile-first approach but this was the only way I got it to work.
