### ISSUE TITLE
Gatsby Develop hangs using iTerm2, resizing fixes it

### ISSUE THREAD

**Issue by angelod1as** [gatsbyjs/gatsby#27325] opened 2020-10-07 19:25 UTC
## Description

When I run `yarn develop`, the process hangs at `source and transform nodes`. When I resize my terminal, everything starts running again smoothly. So I need to hit the command and keep changing my terminal width to actually get to the end of building.

![image](https://user-images.githubusercontent.com/13950513/95377763-64520180-08b9-11eb-995e-16ec620c5472.png)

### Steps to reproduce

Run `yarn develop`
Wait until it hangs at `source and transform nodes`
Resize iTerm2
See everything continue smoothly

[This is the project I'm working on at the moment.](https://github.com/angelod1as/portfolio)

### Expected result

Run `yarn develop`
See everything continue smoothly

### Environment

  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - /usr/local/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 85.0.4183.121
    Firefox: 81.0.1
    Safari: 14.0
  npmPackages:
    gatsby: 2.15.14 => 2.15.14 
    gatsby-background-image: ^0.8.9 => 0.8.9 
    gatsby-cli: ^2.7.47 => 2.7.47 
    gatsby-image: ^2.2.18 => 2.2.18 
    gatsby-plugin-catch-links: ^2.1.9 => 2.1.9 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-manifest: ^2.2.16 => 2.2.16 
    gatsby-plugin-netlify-cms: ^4.1.14 => 4.1.14 
    gatsby-plugin-offline: ^3.0.6 => 3.0.6 
    gatsby-plugin-react-helmet: ^3.1.7 => 3.1.7 
    gatsby-plugin-react-svg: ^2.1.1 => 2.1.2 
    gatsby-plugin-sharp: ^2.2.21 => 2.2.21 
    gatsby-plugin-styled-components: ^3.1.5 => 3.1.5 
    gatsby-remark-autolink-headers: ^2.1.13 => 2.1.13 
    gatsby-remark-custom-blocks: ^2.1.9 => 2.1.9 
    gatsby-remark-external-links: ^0.0.4 => 0.0.4 
    gatsby-remark-images: ^3.1.21 => 3.1.21 
    gatsby-remark-lazy-load: ^1.0.1 => 1.0.1 
    gatsby-remark-picture: ^1.0.1 => 1.0.1 
    gatsby-remark-prismjs: ^3.3.13 => 3.3.13 
    gatsby-remark-relative-images: ^0.2.3 => 0.2.3 
    gatsby-remark-unwrap-images: ^1.0.1 => 1.0.1 
    gatsby-source-filesystem: ^2.1.22 => 2.1.22 
    gatsby-transformer-remark: ^2.6.22 => 2.6.22 
    gatsby-transformer-sharp: ^2.2.14 => 2.2.14

**Comment by pvdz** [comment] 2020-10-07 20:22
Can you reliably reproduce this?
Any chance you can record a video of this?

**Comment by angelod1as** [comment] 2020-10-07 20:31
Sure, uploaded it here: https://imgur.com/a/oK48n0j
You can see the moment I resize my terminal.
(I ran `gastby clean` before so I don't wait the full process to complete, but you have my word it does without a hitch after resizing)

**Comment by ascorbic** [comment] 2020-10-08 10:22
@angelod1as What a great bug! Are you saying that if you don't resize that it reliably hangs forever? Can you record another video where you let it hang for say 30 seconds before resizing? Does it only happen when the terminal is very narow like in your video?

**Comment by ascorbic** [comment] 2020-10-08 10:25
Also, is this only in iTerm? Can you repro it in Terminal too? How about if you're using a different shell, or if your shell extensions are disabled?

**Comment by angelod1as** [comment] 2020-10-08 18:22
Here's the video with iTerm fullscreen and running (actually _hanging_) for about 30 seconds before resize: https://streamable.com/5wkr3b

Here's running on Terminal: https://streamable.com/ntwbo3

Here's on Terminal + Bash (instead of zsh): https://streamable.com/kobecf

Fun, isn't it?

**Comment by angelod1as** [comment] 2020-10-08 19:31
Yep, let it running for some time and it stayed there. Then, resized and all worked fine.

![image](https://user-images.githubusercontent.com/13950513/95504783-a778a700-0983-11eb-8c03-886594449ae6.png)

**Comment by pvdz** [comment] 2020-10-08 21:04
Now all we have to do is get one of our engineers that use a mac to be able to repro this. This cracks me up, thank you for surfacing it :D

**Comment by pvdz** [comment] 2020-10-08 21:17
Since common questions don't qualify here, let me ask some unusual ones :p

- Can you tell us a bit more about your screen and resolution?
- Does the problem repro at pretty much any size of the terminal?
- Is it for example always maximized?
- Are there any particular plugins you're using? Particular settings to the terminal?
- Are there other devices where you can repro this problem?

Can you start the process in the debugger (`node --inspect node_modules/.bin/gatsby develop`), open `about:inspect` in a chrome browser, and at the step press the pause button in the "sources" tab in the devtools a few times to see where exactly it is looping? (In the video I can see that it's a blocking loop because the spinner doesn't update until you resize). This would be super helpful for our debugging process.

**Comment by angelod1as** [comment] 2020-10-08 22:14
- I have two Acer VA270H (full HD) plugged to a MacBook Pro Retina mid-2014. The bug happens regardless of screen.
- It happens at any size, from smallest to fullscreen. I usually run my terminal maximized at the Retina screen but I tested in all monitors and with different HxW and it kept happening.
- I use zsh and a few plugins, described below. But as aforementioned, I tested this on bash — no plugins at all and using good ol' Terminal — and it happened the same.
- I'm sorry, I don't have any other device to repro this.

I might be doing something wrong at the last step, the debugging one. I run this command, access the address and click the "inspect" link. I can even click the pause on "sources", but nothing appears here.

![image](https://user-images.githubusercontent.com/13950513/95518911-7192ed00-099a-11eb-86de-1fc9c4d38912.png)

Plugins:
- Zinit
- p10k
- git
- node
- osx
- npm
- zsh-z
- zsh-autosuggestions
- zsh-completions
- fast-syntax-highlighting
- colorls

**Comment by pvdz** [comment] 2020-10-08 22:32
So while the spinner is frozen (the point where you can can get unstuck by resizing) pressing the pause icon in the top-right does not actually pause anything? That... could be a very relevant clue.
The spinner being frozen indicates a blocking loop. Ohhhh right, `develop` works slightly differently in this regard (sorry I mainly work on `gatsby build` stuff). I believe you can do `gatsby develop --inspect` as a workaround?

**Comment by pvdz** [comment] 2020-10-08 22:33
And does this happen in `gatsby build` as well? (There `node --inspect` should work fwiw). Or is it only in `develop`?

**Comment by angelod1as** [comment] 2020-10-08 22:57
Now that you mentioned it, `gatsby build` also freezes. I hadn't noticed it before. Running `node --inspect` using `build` also shows nothing.

**Comment by ehowey** [comment] 2020-10-17 13:02
https://github.com/gatsbyjs/gatsby/issues/17131

Maybe similar or helpful?

**Comment by wardpeet** [comment] 2021-11-08 08:30
Hi closing this issue until we can have more information. Feel free to re-open at any time.

**Closed by wardpeet** 2021-11-08 08:30 UTC
Labels: type: bug, topic: cli
