### ISSUE TITLE
2.22.19 new typescript error 

### ISSUE THREAD

**Issue by JustFly1984** [gatsbyjs/gatsby#24758] opened 2020-06-03 16:42 UTC
# Description

in 2.22.19 version appeared new error when I run `tsc -p ./tsconfig.json --noEmit`:

### Steps to reproduce

run `tsc -p ./tsconfig.json --noEmit` in gatsby typescript project

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

no errors

### Actual result

```sh
node_modules/gatsby/index.d.ts:14:27 - error TS2307: Cannot find module './src/bootstrap/load-plugins/types' or its corresponding type declarations.

14 import { PluginRef } from "./src/bootstrap/load-plugins/types"
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.

error Command failed with exit code 1.
```
<img width="506" alt="Screenshot 2020-06-03 23 32 32" src="https://user-images.githubusercontent.com/2255993/83664148-cb9e3300-a5f3-11ea-81ad-48bb3eb059b4.png">

crosslinking issue #22070

**Comment by LekoArts** [comment] 2020-06-04 08:05
This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/24645

**Closed by LekoArts** 2020-06-04 08:05 UTC
Labels: status: needs core review, topic: TypeScript migration, type: bug
