### ISSUE TITLE
Disable Gatsby Preview notifications

### ISSUE THREAD

**Issue by rayzoor12** [gatsbyjs/gatsby#16676] opened 2019-08-16 08:53 UTC
## Summary

There's is currently no possible way of disabling push notifications from Gatsby Preview updates. Since I have the webhook to update on saves in Contentful, Gatsby preview is firing a lot of notifications that are blocking the screen.

### Basic example

I solved this by editing the code of the extension in Contentful

From:
`()=>this.props.sdk.notifier.success("Gatsby Preview updated!"),`
To:
`()=>{},/*this.props.sdk.notifier.success("Gatsby Preview updated!")*/`

You can find the code under setting -> extensions, and then click edit on Gatsby preview.

### Motivation

So that editors using Contentful wont have to see the success push notifications that are blocking the screen for them.

**Comment by sidharthachatterjee** [comment] 2019-08-20 13:27
@rizchelwood is working on resolving this. Closing this as it's a duplicate of an issue being tracked by the cloud team. 

Thank you for opening!

**Closed by sidharthachatterjee** 2019-08-20 13:27 UTC
Labels: Gatsby Cloud
