### ISSUE TITLE
Gatsby develop only works with 5 pages

### ISSUE THREAD

**Issue by williancozzi** [gatsbyjs/gatsby#28586] opened 2020-12-11 22:19 UTC
## Description

When you run `gatsby Develop`, and open 5 new pages (in different tabs), everything is going to be normal and fast. But, the subsequent pages opened in new tabs will be suspended, like indefinitely. It will load the first five pages, and the other will be blank, they will work back just when you close one or more, of the previously 5 opened tabs. (edit: as related previously on #12225)

### Steps to reproduce

1. Open Application
2. Click open in New Tab for a Unique Page
3. After doing step 2, 5 times, the other pages won’t load, but the first 5 will.

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

Open, load and work with many new tabs as you want.

### Actual result

New tabs will open but only first 5 are going to working fine, others won't open;

### Environment

System:
    OS: Windows 10 10.0.18363
    CPU: (4) x64 Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz  
  Binaries:
    Node: 12.18.3 - C:\Program Files\nodejs\node.EXE       
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.6 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.5 - /c/Users/PICHAU/AppData/Local/Programs/Python/Python38/python
  Browsers:
    Chrome: 87.0.4280.88
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    gatsby: ^2.21.31 => 2.24.11
    gatsby-background-image: ^1.1.1 => 1.1.1
    gatsby-cli: ^2.12.106 => 2.12.106
    gatsby-image: ^2.4.3 => 2.4.3
    gatsby-plugin-google-fonts-v2: 0.0.6 => 0.0.6
    gatsby-plugin-manifest: ^2.4.3 => 2.4.3
    gatsby-plugin-mdx: ^1.2.7 => 1.2.7
    gatsby-plugin-offline: ^3.2.2 => 3.2.2
    gatsby-plugin-portal: ^1.0.7 => 1.0.7
    gatsby-plugin-react-helmet: ^3.3.1 => 3.3.1
    gatsby-plugin-robots-txt: ^1.5.1 => 1.5.1
    gatsby-plugin-sharp: ^2.6.3 => 2.6.3
    gatsby-plugin-sitemap: ^2.4.11 => 2.4.11
    gatsby-plugin-styled-components: ^3.3.1 => 3.3.1
    gatsby-remark-images: ^3.3.3 => 3.3.3
    gatsby-source-filesystem: ^2.3.3 => 2.3.3
    gatsby-transformer-sharp: ^2.5.2 => 2.5.2
  npmGlobalPackages:
    gatsby-cli: 2.14.1

![Home-Cheapreats-Google-Chrome-2020-12-09-22-10-10-1](https://user-images.githubusercontent.com/39573063/101960224-be3ab480-3be5-11eb-8eba-adaa762ea044.gif)

**Comment by tu4mo** [comment] 2020-12-12 09:33
Duplicate of https://github.com/gatsbyjs/gatsby/issues/12225?

**Comment by LekoArts** [comment] 2020-12-14 08:43
Yes, this is a duplicate of the issue above. Thanks for creating the issue though!

**Closed by LekoArts** 2020-12-14 08:43 UTC
Labels: status: triage needed, type: bug
