### ISSUE TITLE
Deferred Static Generation fails with error Cannot read properties of undefined (reading '0') Running gatsby-plugin-sharp.IMAGE_PROCESSING jobs

### ISSUE THREAD

**Issue by justinluttrell** [gatsbyjs/gatsby#35767] opened 2022-05-27 19:51 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I recently upgraded a project to Gatsby 4 and attempted to make use of deferred static generation. When passing `defer: true` to the `createPages` method I get the error seen below. Removing the `defer` argument from createPages works fine.

### Steps to Reproduce

Not sure on the steps to reproduce since this project isn't small (generates over 2,000 pages) and sources content from Prismic. Passing `defer: true` to the `createPages` API will cause the build to fail.

### Expected Result

The build succeeds and defers the generation of pages that contain `defer: true` in the `createPages` argument.

### Actual Result

Build fails with the below error

```bash
failed Validating Rendering Engines - 1.695s

 ERROR #98001  WEBPACK

Built Rendering Engines failed validation failed validation.

Please open an issue with a reproduction at https://github.com/gatsbyjs/gatsby/issues/new for more help



  TypeError: Cannot read properties of undefined (reading '0')

  - index.js:22199 Function.load.path
    /Users/jl/dev/mf/.cache/query-engine/index.js:22199:37

  - index.js:22174 Object.load [as default]
    /Users/jl/dev/mf/.cache/query-engine/index.js:22174:30

  - index.js:19728 Object.<anonymous>
    /Users/jl/dev/mf/.cache/query-engine/index.js:19728:47

  - index.js:426842 __webpack_require__
    /Users/jl/dev/mf/.cache/query-engine/index.js:426842:42

  - index.js:125447 Object.exports.__esModule
    /Users/jl/dev/mf/.cache/query-engine/index.js:125447:13

  - index.js:426842 __webpack_require__
    /Users/jl/dev/mf/.cache/query-engine/index.js:426842:42

  - index.js:125211 Object.<anonymous>
    /Users/jl/dev/mf/.cache/query-engine/index.js:125211:41

  - index.js:426842 __webpack_require__
    /Users/jl/dev/mf/.cache/query-engine/index.js:426842:42

  - index.js:124775 Object.exports.__esModule
    /Users/jl/dev/mf/.cache/query-engine/index.js:124775:13

  - index.js:426842 __webpack_require__
    /Users/jl/dev/mf/.cache/query-engine/index.js:426842:42


not finished Running gatsby-plugin-sharp.IMAGE_PROCESSING jobs - 106.565s


### Environment


System:
    OS: macOS 12.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.14.0 - /var/folders/tn/9rhncw5n7_bc06qghw95w6vh0000gq/T/yarn--1653680089511-0.02622758749226839/node
    Yarn: 1.22.17 - /var/folders/tn/9rhncw5n7_bc06qghw95w6vh0000gq/T/yarn--1653680089511-0.02622758749226839/yarn
    npm: 8.3.1 - /usr/local/bin/npm
  Languages:
    Python: 3.9.7 - /Users/jl/miniconda3/bin/python
  Browsers:
    Chrome: 102.0.5005.61
    Safari: 15.3
  npmPackages:
    gatsby: 4.11.0 => 4.11.0
    gatsby-plugin-algolia: ^0.26.0 => 0.26.0
    gatsby-plugin-emotion: ^7.0.0 => 7.14.0
    gatsby-plugin-env-variables: ^2.1.0 => 2.2.0
    gatsby-plugin-extract-schema: ^0.2.0 => 0.2.1
    gatsby-plugin-gatsby-cloud: ^4.4.0 => 4.14.0
    gatsby-plugin-google-tagmanager: ^4.0.0 => 4.14.0
    gatsby-plugin-image: ^2.0.0 => 2.14.1
    gatsby-plugin-loadable-components-ssr: ^4.0.0 => 4.2.0
    gatsby-plugin-prismic-previews: ^5.0.0 => 5.2.8
    gatsby-plugin-react-helmet: ^5.0.0 => 5.14.0
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-sharp: ^4.0.0 => 4.15.0
    gatsby-plugin-sitemap: ^5.0.0 => 5.14.0
    gatsby-source-custom-api: ^2.3.1 => 2.3.6
    gatsby-source-filesystem: ^4.0.0 => 4.14.0
    gatsby-source-prismic: ^5.0.0 => 5.2.7
    gatsby-transformer-csv: ^4.0.0 => 4.14.0
    gatsby-transformer-sharp: ^4.0.0 => 4.14.0

**Comment by tyhopp** [comment] 2022-05-30 03:15
Hi @justinluttrell!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

[reproduction]: https://gatsby.dev/reproduction

**Comment by ar0ra1** [comment] 2022-06-09 19:40
Apparently, I had the same issue but I was running on Node 18. 
I tried updating the Gatsby-next but that didn't solve. 

In the end, I removed node_modules and package-lock and re-installed all the modules. Seems to work now. Weird but it works now.

**Comment by LekoArts** [comment] 2022-06-13 06:38
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2022-06-13 06:38 UTC
Labels: type: bug, status: needs reproduction
