### ISSUE TITLE
BlurUp effect gets stuck on

### ISSUE THREAD

**Issue by LyhjeHylje** [gatsbyjs/gatsby#4926] opened 2018-04-10 20:25 UTC
## Description

On some devices, iphone at least, the blurup effect does not clear after image has loaded.
This happens on the first time image is shown, if user navigates to another page and then back the blur disappears.

### Steps to reproduce

Load basic page with an gatsby-image Img-tag on iphone.

### Expected result

Blur should clear when the image has been loaded

### Actual result

Blur stays

### Environment

* Gatsby version (`npm list gatsby`):
* gatsby-cli version (`gatsby --version`): gatsby@1.9.76
* Node.js version: v6.10.3
* Operating System: macOS 10.12.6

### File contents (if changed):

`gatsby-config.js`: 
`package.json`: 
`gatsby-node.js`: 
`gatsby-browser.js`: 
`gatsby-ssr.js`:

**Comment by LyhjeHylje** [comment] 2018-04-10 20:25
Is there a way to disable the blurup effect?

**Comment by KyleAMathews** [comment] 2018-04-11 00:10
You can choose a different graphql fragment without the small blurred image.

We should really fix the problem though :-)

Would you like to take a crack at fixing the problem? It looks like we're running afoul of this problem https://stackoverflow.com/questions/12354865/image-onload-event-and-browser-cache

https://stackoverflow.com/questions/39777833/image-onload-event-in-isomorphic-universal-react-register-event-after-image-is looks like it might have a solution you could try.

**Comment by LyhjeHylje** [comment] 2018-04-11 19:01
Sorry, I don't quite understand. You mean these fragments?
GatsbyImageSharpResolutions
GatsbyImageSharpResolutions_noBase64
GatsbyImageSharpResolutions_tracedSVG
GatsbyImageSharpResolutions_withWebp
GatsbyImageSharpResolutions_withWebp_noBase64
GatsbyImageSharpResolutions_withWebp_tracedSVG

There is no "GatsbyImageSharpResolutions_NOtracedSVG", I have tried some of these and finally "GatsbyImageSharpResolutions_noBase64" seems to not to have the blurring effect.

Maybe the problem was not traced svg, I don't know. I don't understand this plugin or gatsby that well yet.

**Comment by martynhoyer** [comment] 2018-04-12 06:59
The `_noBase64` option will remove the blurUp feature I think.

The base64 part of the query is a very small, low quality JPG version of your image, encoded in base64 so it can be inlined into the document without sending any requests (and thus, loads instantly).

`_tracedSVG` is an alternative to blurUp, adding in an SVG placeholder instead of the base64 inlined image, so the non `tracedSVG` options are `NOtracedSVG` by default. You have to opt in to the tracedSVG feature.

**Comment by LyhjeHylje** [comment] 2018-04-12 07:31
Thank you for explanation.

So I was able to fix my problem but the blur-stuck is still an issue. It is quite horrible looking with partially transparent images (the blurs peek out under the correct image) and I had problems with non-transparent images as well (the blurred image just stayed on top).

I won't close this by myself since it sounds like there is a real problem although I was able to avoid it.

**Comment by graysonhicks** [comment] 2018-04-14 04:04
Having this same issue. Mine comes with a 404 for the image that is stuck as blurred, and also disappears if navigating to another page and back.

![screen shot 2018-04-14 at 12 00 45 am](https://user-images.githubusercontent.com/16200795/38764142-4774a792-3f77-11e8-8ad1-60c88e49b3c9.png)

Blurred image

<img width="784" alt="screen shot 2018-04-14 at 12 01 11 am" src="https://user-images.githubusercontent.com/16200795/38764144-4a7c66f0-3f77-11e8-95c9-38d72c68b591.png">

Same file listed above is showing a 404 in the console.

**Comment by KyleAMathews** [comment] 2018-04-14 04:49
Does anyone have a way to reliably reproduce this?

**Comment by Jaikant** [comment] 2018-04-14 05:53
I have seen the issue when the image file in public/static is deleted. It
isn't recreated if we rebuild Gatsby.

A delete of the cache followed with a Gatsby clean resolves the issue as
the images are regenerated.

**Comment by graysonhicks** [comment] 2018-04-14 15:30
Yea definitely looks like the image has been deleted from public/static somehow.  Is there a 'best way' to do this? (so if it works I can post my exact steps):

> A delete of the cache followed with a Gatsby clean resolves the issue as
the images are regenerated.

**Comment by graysonhicks** [comment] 2018-04-14 16:29
Okay, so cleared public and rebuilt, still an issue 🤷‍♂️ .  Here's the repo where its happening, with my best testing instructions if anyone wants to try and reproduce:

https://github.com/graysonhicks/react-scrolltop-button

### Set Up
1. `fork` https://github.com/graysonhicks/react-scrolltop-button
2. `git clone` it
3. `cd react-scrolltop-button`
4. Top level of repo is for the npm package so can `cd` straight into `docs/`
5. `npm install`

### Start Gatsby
6. `gatsby develop`
7. Check on local to make sure it works.

### Build and Serve Locally (works, image blurs in)
8. run `gatsby build && gatsby serve`
9. Check `public/static` folder for `logo.png`
10. Check on the local production build to make sure it works

### Build and Test on gh-pages (doesn't work, image stuck on blur)
11. `npm run build:gh` runs `rm -rf public` `gatsby build --prefix-paths` and `gh-pages -d public`
12. Check gh-pages of your forked repo.
13. See if image is stuck on blur and/or if it exists in the public/static folder.

**Comment by KyleAMathews** [comment] 2018-04-14 16:34
So... why are are you deleting the public folder?

**Comment by graysonhicks** [comment] 2018-04-14 19:47
I only did that based on what @Jaikant said above.  I then immediately rebuilt.  The public/static folder was empty before and after.

**Comment by KyleAMathews** [comment] 2018-04-14 19:58
The problem it seems is that we use the public folder as a cache for built static files and people don't know that and then delete it and then they're left with an inconsistent cache.

I can see us not storing image thumbnails, etc. that we generate there and copying them over on builds but we'd need to figure an efficient way to do that. Ideally rsync if that were possible — https://twitter.com/kylemathews/status/985244819864760320

Anyways, you should never routinely delete the `public` folder (nor do you need to check it in). Gatsby takes care of deleting any files that need removed in between builds. If you do need to delete it for some reason, also delete `.cache`.

I think the best solution is to a) figure out a fast copy solution so we can store image thumbnails, etc. in `.cache` so people don't mess up their site by deleting `public`.

**Comment by graysonhicks** [comment] 2018-04-14 20:00
Understood.  But note that touching public was trying to fix the original missing/stuck blur image.  I've done the testing process I put above on a separate machine and got the same bug.  Still curious how to fix that.

**Comment by graysonhicks** [comment] 2018-04-14 20:04
Welp! Deleting .cache and public and rebuilding seems to have fixed it. 🤷‍♂️

**Comment by m-allanson** [comment] 2018-04-16 21:56
Maybe these are useful:

- [rsync implementation in python](http://freshmeat.sourceforge.net/projects/pysync/)
- [rsync implementation in javascript](https://github.com/FractalBlocks/js-rsync)

**Comment by arggh** [comment] 2018-04-17 14:58
I just began toying around with Gatsby a day ago and at some point I noticed images were not working either in the deployed version of the project. I hadn't touched the `public` or `.cache` folder at all. Got the images working by deleting both and rebuilding and redeploying.

**Comment by ginovski** [comment] 2018-06-15 12:13
Did you manage to fix that issue? The problem still persists.

**Comment by kekami** [comment] 2018-08-09 09:27
Any progress on this? The issue still exists on iOS/Safari. Had to use `GatsbyImageSharpSizes_noBase64`

**Comment by graysonhicks** [comment] 2018-08-09 12:55
Clearing Gatsby cache or browser cache worked when I did have this issue, but I have not had this issue in a quite a while.

**Comment by coreyward** [comment] 2018-09-17 20:38
I'm experiencing this consistently in Safari on macOS as well as iOS.

**Comment by kodemi** [comment] 2018-10-22 13:35
Why issue is closed? The problem is still actual.

**Comment by coreyward** [comment] 2018-10-22 18:00
@kodemi Looks like my fault! I mentioned the issue in a totally separate private repo pull request and Github mistakenly took it as a fix. 😳

**Comment by grzegorzbialy** [comment] 2018-10-25 16:07
For me, the IntersectionObserver polyfill is fixing this. More on this: https://github.com/gatsbyjs/gatsby/issues/8323

**Comment by m-allanson** [comment] 2018-12-12 16:39
This should be fixed in `gatsby-image@2.0.24`, see #7539 for details! I'm going to close this, please re-open or create a new issue if it's not fixed for you.

**Closed by m-allanson** 2018-12-12 16:39 UTC
Labels: type: question or discussion

**Comment by goodok21** [comment] 2018-12-19 12:01
TracedSVG effect still gets stuck in Chrome/Safari in iOS, if using WEBP format.
Example query in simple Gatsby page:
```
        fluid (
          traceSVG: {
            color: "#333",
          }
          quality: 85
          toFormat: WEBP
        ) {
          ...GatsbyImageSharpFluid_tracedSVG
        }
```

Anyone can help with this issue?

**Comment by coreyward** [comment] 2018-12-19 16:34
@goodok21 Safari and Chrome for iOS do not have support for WebP images. Since you're forcing the format there's nothing to blur-up to. The fragment `GatsbyImageSharpFluid_withWebp_tracedSVG` will do what you're looking for while providing the default image format as a fallback for browsers that don't yet support WebP.

**Comment by ernestosotelo** [comment] 2019-05-28 23:36
My image stays blurred when deployed to Github - works fine on local environment... Anyone have any ideas why? Been really struggling to work with gatsby-image. Appreciate it guys.

**Comment by firsttris** [comment] 2019-06-06 08:31
Same Issue with Github Pages, images stays blurred. tracedSVG didn't help.

**Comment by witcradg** [comment] 2021-06-26 21:14
I'm seeing this issue today on chrome running on Ubuntu 20.04. I do not see it when working from localhost in either  but I do see it when accessing the site when hosted on Netlify. Removing the ```loading="eager" ``` seems to have fixed it for me.
