### ISSUE TITLE
The placeholder image in "gatsby-image" does not fade on Safari

### ISSUE THREAD

**Issue by JakeRider** [gatsbyjs/gatsby#8323] opened 2018-09-19 16:01 UTC
## Description

The low-res placeholder image that gatsby-image generates is not fading out on Safari, both on desktop and mobile. You can see it happening at the gatsby-image [example site](https://using-gatsby-image.gatsbyjs.org). It becomes an issue when using images with transparency, as you can still see parts of the placeholder.

### Steps to reproduce

Use gatsby-image on Safari. https://using-gatsby-image.gatsbyjs.org is a good example, but it seems to affect any site built with Gatsby. My project, the gatsby-image demo site, and the main Gatsby site are all being affected from what I saw.

### Expected result

The placeholder should fade out after the main image loads.

### Actual result

The placeholder remains opaque, and the main image loads over top of it. 

### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.8.0 - ~/.nvm/versions/node/v10.8.0/bin/node
    npm: 6.4.1 - ~/.nvm/versions/node/v10.8.0/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Safari: 12.0
  npmGlobalPackages:
    gatsby-cli: 2.4.0

**Comment by stefanprobst** [comment] 2018-09-19 19:33
Not sure if I am misunderstanding the issue, but could you check the css of the placeholder `<img>` in your browser's devtools? It should look like this:
```html
<div class="gatsby-image-wrapper">
  <img> <!-- CHECK IF THIS HAS opacity: 0 -->
  <picture></picture>
</div>
```
Also, is this working correctly with another browser?

**Comment by JakeRider** [comment] 2018-09-19 19:42
<img width="1264" alt="gatsby" src="https://user-images.githubusercontent.com/27035207/45776813-1b6f7780-bc22-11e8-8e6e-459a31bc0ae7.png">

The opacity is still 1. To confirm, everything works fine in Chrome/Firefox, but mobile and desktop Safari are both doing this. If you come to the page from within the site, it works fine, but if you refresh the page, or link to it directly, it doesn't seem to trigger.

**Comment by stefanprobst** [comment] 2018-09-19 20:06
Hmm, that's weird - `transition-delay` is also not updated when `state` changes. See:
https://github.com/gatsbyjs/gatsby/blob/208547ffd5c4c251652e09477023811ba7ed5d1c/packages/gatsby-image/src/index.js#L214-L219
You could check if `onLoad` gets called by passing it as a prop to `<Img onLoad={() => console.log('Image loaded!')} />`, or you could check with the React DevTools, if you have it installed in your browser. (Unfortunately I cannot check myself because Safari has no linux version).

Related to the issue that I think I spotted: in Firefox/Chrome does the placeholder actually fade out, or just gets invisible. Because it seems the placeholder `img` gets a `transition-delay` but no actual `transition`.

**Comment by stefanprobst** [comment] 2018-09-19 20:21
One more thought: difference between Safari and Firefox/Chrome is that the latter support `IntersectionObserver` (which is used in `gatsby-image`), and Safari doesn't.

**Comment by JakeRider** [comment] 2018-09-19 20:51
After having experimented a bit, polyfilling `IntersectionObserver` seems to solve the issue . It looks like #4021 already has some discussion about adding a polyfill. Would you like me to put together a PR for this & a working `transition`?

**Comment by stefanprobst** [comment] 2018-09-19 21:27
That would be great, thanks!
wrt adding IntersectionObserver: @KyleAMathews ok to add `IntersectionObserver` polyfill to `gatsby-image`?

**Comment by DSchau** [comment] 2018-09-19 21:35
I'll let @KyleAMathews answer for himself, but I'm not sure we'd want to include a polyfill explicitly within gatsby-image.

We can (and probably should!) document the usage of such polyfill(s) and mention how to use them, but I don't think I like the idea of an explicit polyfill.

That said, I'm also not 100% sure I see the issue here either. The images appear to load fine for me in Safari (`12.0 (13606.2.11)`) 🤷‍♂️ Am I missing something?

![Safari Images](https://thumbs.gfycat.com/EnergeticScratchyLacewing-size_restricted.gif)

**Comment by JakeRider** [comment] 2018-09-19 21:47
The issue is not that the images don’t load, it’s that the placeholder doesn’t fade. It’s not obvious on pictures that don’t have transparency, but it looks terrible if the image does. There’s probably a way to fix that doesn’t involve a polyfill, but Safari makes up a big enough chunk of the market that it’s probably worth considering.

**Comment by stefanprobst** [comment] 2018-09-19 22:41
Maybe we can figure this out together. AFAICS the placeholder `<img>` has `opacity: 1` even though it should be 0 when `state.imgLoaded === true`.
@JakeRider can you check the `<Img>` component state in React DevTools? And check if `props.onLoad` gets called (which should happen in `handleImageLoaded` which also sets `state.imgLoaded: true`

**Comment by DSchau** [comment] 2018-09-19 23:29
@JakeRider that example is a lot more helpful! I think I've seen something similar on a site [I helped out with](https://objectpartners.netlify.com). (_Note: the opacity is still 1 here on the placeholder image, which should be the same issue)

Note: this is before some of the gatsby-image v2 stuff was shipped, so it's a bit out of date.

I'm game to help figure this out too. @stefanprobst I think if I use the above site's source, we could debug it pretty easily.

**Comment by stefanprobst** [comment] 2018-09-20 06:39
Sounds good! The issue *should* also be visible on a simple default starter ([link to repo](https://github.com/stefanprobst/gatsby-issue-8323)). Could you (or somebody with Safari) check? This is what I see when I manually set the opacity on the placeholder:

![issue8323](https://user-images.githubusercontent.com/20753323/45799974-aa76a100-bcaf-11e8-87b2-a196f19fddde.png)

**Comment by stefanprobst** [comment] 2018-09-21 13:55
Possible duplicate of #7539 ?

**Comment by DSchau** [comment] 2018-09-21 13:57
@stefanprobst I wouldn't say that's a duplicate, I would say that (hopefully!) that fixes this issue! 🤞 I can pull it down locally and try in a bit.

**Comment by stefanprobst** [comment] 2018-09-21 14:46
Thanks! The actual issue this PR is trying to solve has [this comment ](https://github.com/gatsbyjs/gatsby/issues/2330#issuecomment-414860939) that looks very similar to what seems to be happening here.

**Comment by stefanprobst** [comment] 2018-10-08 14:19
@JakeRider Sorry for getting back at this so late. I have tried to clean-up gatsby-image a bit (esp. removing stuff from state that does not need to live there). This is not a proper PR (yet), but if you're willing to try this out I'd be very interested if it fixes this particular issue. You can install the component directly from my github:
```bash
yarn add https://github.com/stefanprobst/gatsby-image-compact
```
Then adjust your imports from `gatsby-image` to `gatsby-image-compact`, the rest should hopefully "just work".

**Comment by ThiagoMiranda** [comment] 2018-10-09 20:09
I'm having the same issue on Chrome 69.0.3497.100 for MacOS as well. Is there a fix for this?
Thanks!
![captura de tela 2018-10-09 as 17 09 00](https://user-images.githubusercontent.com/141922/46695483-09ac3f00-cbe6-11e8-81a1-5e442d8745ff.png)

**Comment by stefanprobst** [comment] 2018-10-09 22:14
> Is there a fix for this?

Not yet. You could try if #7539 (or my test repo above) fixes the issue for you and report back here.

**Comment by m-allanson** [comment] 2018-12-12 16:38
This should be fixed in `gatsby-image@2.0.24`, see #7539 for details! I'm going to close this, please re-open or create a new issue if it's not fixed for you.

**Closed by m-allanson** 2018-12-12 16:38 UTC
Labels: type: bug

**Comment by samselikoff** [comment] 2019-12-13 18:57
This issue perfectly describes a bug I hit, but my google-fu is failing me. I can't find any other traces of this & my project's dependencies are all up to date.

Should I upload a simplified reproduction?

**Comment by ooloth** [comment] 2019-12-13 19:15
@samselikoff Before you spend time on a repro, are you seeing this lack of fading in [a version of Safari that supports `IntersectionObserver`](https://caniuse.com/#feat=intersectionobserver) or one that doesn't?

If it doesn't, the first thing you might try is polyfilling `IntersectionObserver` and seeing if that solves it.

**Comment by samselikoff** [comment] 2019-12-13 19:49
Hm I did try using this technique I believe https://github.com/gatsbyjs/gatsby/issues/10435 but I can double check

**Comment by samselikoff** [comment] 2019-12-13 19:50
Awesome seeing this on latest Safari on my desktop so I don’t think it’s the issue

**Comment by ooloth** [comment] 2019-12-13 19:55
Hmm...actually, yeah: I can confirming I'm also currently seeing this lack of fading on https://using-gatsby-image.gatsbyjs.org in Safari as well.

**Comment by samselikoff** [comment] 2019-12-13 21:02
Yes, exactly. Looks like the placeholder is just disappearing.

**Comment by samselikoff** [comment] 2019-12-13 21:02
Should we open a new issue?

**Comment by ooloth** [comment] 2019-12-13 21:07
> Should we open a new issue?

Probably a good idea, with a link to this one in the description for context.

Glad you spotted this!
