### ISSUE TITLE
gatsby-source-shopify" threw an error while running the sourceNodes lifecycle

### ISSUE THREAD

**Issue by bumples** [gatsbyjs/gatsby#27593] opened 2020-10-21 20:38 UTC
## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result nodes are not loading using gatsby-source- shopify

What happened. cannot open graphql

### Environment using visual studio code
ERROR #11321  PLUGIN

"gatsby-source-shopify" threw an error while running the sourceNodes lifecycle:

Cannot read property 'includes' of undefined

  41 |   shopifyQueries = {}
  42 | }) => {
> 43 |   const client = (0, _createClient.createClient)(shopName, accessToken, apiVersion);    
     |                                                 ^
  44 |   const defaultQueries = {
  45 |     articles: _queries.ARTICLES_QUERY,
  46 |     blogs: _queries.BLOGS_QUERY,

File: node_modules\gatsby-source-shopify\gatsby-node.js:43:49

**Comment by ascorbic** [comment] 2020-10-22 09:34
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it would be really helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

Thanks!

[reproduction]: https://gatsby.dev/reproduction

**Comment by ascorbic** [comment] 2020-11-05 11:44
Hi. I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. Thanks!

**Closed by ascorbic** 2020-11-05 11:45 UTC
Labels: status: needs reproduction, topic: Shopify, type: bug
