### ISSUE TITLE
Missing Code block under Docs -> Commands (Gatsby CLI)

### ISSUE THREAD

**Issue by Amorpheuz** [gatsbyjs/gatsby#25680] opened 2020-07-10 11:07 UTC
## Description

A code-block which informs the user about the piece of code to `package.json` in order to use the gatsby commands available in the application is missing on the documentation webpage at [How to use gatsby-cli | Commands (Gatsby CLI)](https://www.gatsbyjs.org/docs/gatsby-cli/#how-to-use-gatsby-cli).

It is present in the `.md` file on [GitHub repo](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/gatsby-cli.md).

### Steps to reproduce

1. Visit https://www.gatsbyjs.org/docs/gatsby-cli/#how-to-use-gatsby-cli
2. Check for phrase `add a script like so:` after which the code-block should appear.
3. Check https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/gatsby-cli.md or the `Edit this page on GitHub` button for the source file.

### Expected result

The code block should be correctly rendered on the webpage.

### Actual result

The code block is missing and the `:` left hanging. 😞

### Environment

The one used to deploy the [GatsbyJS.org](https://www.gatsbyjs.org/docs/) site. 😅

---

I would love to help fix this issue!

**Comment by coldice** [comment] 2020-07-10 11:13
It looks like this affects more (possible: all) code blocks, see:
https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/static-query.md
https://www.gatsbyjs.org/docs/static-query/

**Comment by Arthur092** [comment] 2020-07-11 22:32
Can I take this issue?

**Comment by LekoArts** [comment] 2020-07-13 06:43
Thanks for the issue!
Please try a hard refresh/clear your cache (e.g. `Ctrl + F5`) on that site as the code block you're describing is there:

![image](https://user-images.githubusercontent.com/16143594/87278439-bf57a080-c4e4-11ea-8d34-67fa40ab9183.png)

Alternatively tell us what browser (+ version) you're using.

**Comment by Amorpheuz** [comment] 2020-07-13 09:19
Hard refresh solved the issue! The browser is Edge v83.0.478.61 if that can help the caching thing.

**Comment by coldice** [comment] 2020-07-13 17:18
All back for me now as well on Chrome 👍

**Comment by LekoArts** [comment] 2020-07-14 05:07
As this seems to be an intermittent issue with the cache on some pages I'll close this. When someone can create a [minimal reproduction][reproduction] using `gatsby-plugin-offline` with this behavior, please open a new issue. Thanks!

[reproduction]: https://gatsby.dev/reproduction

**Closed by LekoArts** 2020-07-14 05:07 UTC
Labels: status: needs docs review, type: bug, type: documentation
