### ISSUE TITLE
[www] Quick start category takes two clicks before expanding

### ISSUE THREAD

**Issue by shannonbux** [gatsbyjs/gatsby#7474] opened 2018-08-20 18:07 UTC
Jason pointed out this buggy behavior. 

### Steps
1. Click on Guides to expand it
2. Refresh the page
3. Click on Quick Start

### Expected behavior
1. Quick start expands

### Actual behavior
1. Quick start is bolded. Upon first click, it becomes unbolded.
2. On second click, it expands.

**Comment by fk** [comment] 2018-08-20 18:48
Yep, looking at this and #7468 (which I believe capture the same bug) just now!

I noticed that if I log `location.pathname`, while in develop I get e.g. `/docs/starters/`, but when running `gatsby.build` I get `//docs/starters/` -- note the second forward slash at the beginning. Removing that slash fixes both issues (as the "active state" logic depends on matching `location.pathname` to the `href` of a sidebar link).

I guess this isn't the expected behavior and might be related to the recent switch to `reach/router`?

/cc @jlengstorf @KyleAMathews

**Comment by chasemccoy** [comment] 2018-08-30 02:11
Did the changes in #7577 solve this?

**Comment by fk** [comment] 2018-08-30 03:11
Happy to report that with the most recent deploy of https://next.gatsbyjs.org/ just a few minutes ago, a couple of sidebar navigation issues related to #7528 (fixed in #7577) should be gone:

- #7474
- #7468
- #7738

I tested on https://next.gatsbyjs.org/ as well as a local build—among other things with JavaScript enabled and disabled, with and without sidebar accordion state in local storage, directly accessing e.g. `/docs/` (instead of navigating there), etc., and couldn't reproduce this issue anymore.

Please feel free to reopen this if you're still experiencing the issue.

**Closed by fk** 2018-08-30 03:11 UTC
