### ISSUE TITLE
ERROR #11615 - Trying to load dev-404-page | Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by PrimeSavant** [gatsbyjs/gatsby#31880] opened 2021-06-12 01:53 UTC
## Description

Getting this error every time i open any /en/* page. I can run localhost:8000/ just fine, but as soon as i go to any /en/* URL the / URL stops working too, the screen shows the "no codeFrame" json screen.

![image](https://user-images.githubusercontent.com/47196328/121761567-882bae00-cafe-11eb-91d2-f982fbe16037.png)

### Steps to reproduce
yarn develop (already ran yarn clean, multiple times)

### Expected result

Render page at localhost:8000/en/product-detail

### Actual result

![image](https://user-images.githubusercontent.com/47196328/121761460-e310d580-cafd-11eb-8191-c04156c6df8b.png)

### Environment
  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 16.3.0 - ~\AppData\Local\Temp\yarn--1623462049026-0.8224136521519665\node.CMD
    Yarn: 1.22.10 - ~\AppData\Local\Temp\yarn--1623462049026-0.8224136521519665\yarn.CMD
    npm: 7.15.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.41)
  npmPackages:
    gatsby: ^3.2.1 => 3.7.1
    gatsby-plugin-image: ^1.2.1 => 1.6.0
    gatsby-plugin-intl: ^0.3.3 => 0.3.3
    gatsby-plugin-manifest: ^3.2.0 => 3.6.0
    gatsby-plugin-prettier-eslint: ^1.0.6 => 1.0.6
    gatsby-plugin-react-helmet: ^4.2.0 => 4.6.0
    gatsby-plugin-sharp: ^3.2.1 => 3.6.0
    gatsby-plugin-sitemap: ^3.2.0 => 3.3.0
    gatsby-plugin-styled-components: ^4.2.0 => 4.6.0
    gatsby-source-filesystem: ^3.2.0 => 3.6.0
    gatsby-transformer-sharp: ^3.2.0 => 3.6.0

**Comment by LekoArts** [comment] 2021-06-14 06:08
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-06-21 05:31
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-06-21 05:31 UTC
Labels: status: needs reproduction, type: bug

**Comment by PrimeSavant** [comment] 2021-06-21 21:52
The solution is to remove `public/dev-404-page/` after running `yarn develop`.

**Comment by sriharsha8324** [comment] 2021-09-02 06:01
@PrimeSavant , It is still not working after removing the public/dev-404-page/. Getting error like Error: Error loading a result for the page query in "/dev-404-page/". Query was not run and no cached result was found.

**Comment by gizzidan** [comment] 2022-10-31 20:02
Any solution? I'm having the same problem right now.

**Comment by nidhish909** [comment] 2023-10-25 10:29
I'm also having the same issue! Any solution please?
