### ISSUE TITLE
Error on gatsby build command: TypeError: Unexpected response from worker: undefined

### ISSUE THREAD

**Issue by marcelo-umg** [gatsbyjs/gatsby#25736] opened 2020-07-13 23:12 UTC
I am getting this error when I run the command `$ gatsby build` on the terminal:
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/3LGvn.png

What gets my attention on this one is that it mentions `jest-worker`, and I don't see that module on my package.json. I see it only in the `node_modules` folder.

I already tried many things. Deleting `node_modules`, `package_lock.json`, `npm cache clean --force` and some other things.

I can't find these errors on the internet either.

If I keep scrolling down on the terminal, the error ends with this:
```
/Users/marcelo/Work/SM/gatsby-on-demand/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: write EPIPE
    at process.target._send (internal/child_process.js:806:20)
    at process.target.send (internal/child_process.js:676:19)
    at /Users/marcelo/Work/SM/gatsby-on-demand/node_modules/gatsby-cli/lib/reporter/loggers/ipc/index.js:58:13
    at dispatch (/Users/marcelo/Work/SM/gatsby-on-demand/node_modules/gatsby-cli/lib/reporter/redux/index.js:54:5)
    at Object.createLog (/Users/marcelo/Work/SM/gatsby-on-demand/node_modules/redux/lib/redux.js:483:12)
    at Reporter.log (/Users/marcelo/Work/SM/gatsby-on-demand/node_modules/gatsby-cli/lib/reporter/reporter.js:173:40)
    at Object.console.log (/Users/marcelo/Work/SM/gatsby-on-demand/node_modules/gatsby-cli/lib/reporter/patch-console.js:17:14)
    at WithHeaderLayout (/Users/marcelo/Work/SM/gatsby-on-demand/public/render-page.js:104712:376)
    at d (/Users/marcelo/Work/SM/gatsby-on-demand/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
    at $a (/Users/marcelo/Work/SM/gatsby-on-demand/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:39:16)
    at a.b.render (/Users/marcelo/Work/SM/gatsby-on-demand/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:476)
    at a.b.read (/Users/marcelo/Work/SM/gatsby-on-demand/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToString (/Users/marcelo/Work/SM/gatsby-on-demand/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at Module.default (/Users/marcelo/Work/SM/gatsby-on-demand/public/render-page.js:710:28)
    at /Users/marcelo/Work/SM/gatsby-on-demand/node_modules/gatsby/dist/utils/worker/render-html.js:28:36
    at Promise._execute (/Users/marcelo/Work/SM/gatsby-on-demand/node_modules/bluebird/js/release/debuggability.js:384:9)
Emitted 'error' event on process instance at:
    at processEmit [as emit] (/Users/marcelo/Work/SM/gatsby-on-demand/node_modules/signal-exit/index.js:161:32)
    at internal/child_process.js:810:39
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  errno: 'EPIPE',
  code: 'EPIPE',
  syscall: 'write'
}
```

I've been going through this the whole day.

Any ideas?

**Comment by marcelo-umg** [comment] 2020-07-14 00:01
I discovered it was a console.log. Only that threw those big errors. How is that the error logs do not provide that kind of information?

**Comment by LekoArts** [comment] 2020-07-14 05:08
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by marcelo-umg** [comment] 2020-07-14 15:17
> I discovered it was a console.log. Only that threw those big errors. How is that the error logs do not provide that kind of information?

Hi @LekoArts well I found why the issue was happening. When I run `gatsby build` it throws all of those errors for a simple `console.log` that had its place on a file within the `src` folder. So do you really think I need to create a minimal reproduction only for that?

**Comment by freiksenet** [comment] 2020-07-15 11:30
@marcelo-umg It would be super helpful if you would provide the reproduction - I'm afraid your description doesn't provide exact steps to resolve this. I have put console.log inside my component files and it still works.

**Comment by LekoArts** [comment] 2020-07-22 05:33
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-07-22 05:33 UTC
Labels: status: needs reproduction
