### ISSUE TITLE
gatsby-plugin-image onStartLoad throws warning react dev tools

### ISSUE THREAD

**Issue by lnikell** [gatsbyjs/gatsby#33748] opened 2021-10-31 18:59 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Using onStartLoad causing React Dev Tools throwing the following message:
```
Warning: Unknown event handler property `onStartLoad`. It will be ignored.
```
<img width="2232" alt="CleanShot 2021-10-31 at 19 52 15@2x" src="https://user-images.githubusercontent.com/2697570/139597469-8608a313-d48f-4321-a143-6cfb711220d5.png">
It happens no matter you use StaticImage or GatsbyImage component.

### Reproduction Link

https://github.com/pixel-point/gatsby-image-on-load-bug

### Steps to Reproduce

1. Go to https://github.com/pixel-point/gatsby-image-on-load-bug , clone repository, npm install && npm start
2. Open http://localhost:8000/page-2
3. Open Console with Installed React Dev Tools

### Expected Result

There should not be a warning.

### Actual Result

Warning appears in the console while running on local machine.

https://user-images.githubusercontent.com/2697570/139597637-b92adf05-8175-4204-823b-0d2bcbf9769d.mp4

### Environment

```shell
System:
    OS: macOS 12.0.1
    CPU: (8) arm64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.9.1 - /usr/local/bin/node
    npm: 7.21.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 95.0.4638.69
    Safari: 15.1
  npmPackages:
    gatsby: ^3.12.0 => 3.14.5
    gatsby-alias-imports: ^1.0.6 => 1.0.6
    gatsby-plugin-image: ^1.14.0 => 1.14.1
    gatsby-plugin-manifest: ^3.12.0 => 3.14.0
    gatsby-plugin-offline: ^4.12.0 => 4.14.0
    gatsby-plugin-postcss: ^4.12.0 => 4.14.0
    gatsby-plugin-react-helmet: ^4.12.0 => 4.14.0
    gatsby-plugin-sass: ^4.12.0 => 4.14.0
    gatsby-plugin-sharp: ^3.14.0 => 3.14.2
    gatsby-plugin-sitemap: ^4.8.0 => 4.10.0
    gatsby-plugin-svgr-svgo: ^1.2.2 => 1.2.2
    gatsby-source-filesystem: ^3.12.0 => 3.14.0
    gatsby-transformer-sharp: ^3.14.0 => 3.14.0
```
```


### Config Flags

_No response_

**Comment by mosesoak** [comment] 2021-11-04 18:00
This is probably caused by spreading the wrapperProps onto the img element [here](https://github.com/gatsbyjs/gatsby/blob/0a04e38d857255fe675101bd96797c67d2d6e743/packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx#L254) without deleting special Gatsby props like onStartLoad first.

**Comment by mosesoak** [comment] 2021-11-05 16:26
Thanks for filing, it affects our app and we will be tracking this issue for a fix. Stuff like this is important despite being innocuous, since we don't like to have console errors showing in our production sites.

BTW this should not be changed to a warning, it can be fixed by not adding the non-DOM prop to a dom node, so it will entirely go away once patched. Thanks!

**Comment by mqnguyen5** [comment] 2021-11-09 02:59
Hi, can I give this a try if no one is working on it at the moment? If so, are there any suggestions on how should I fix this and how can I test it? Thanks.

**Comment by pranav0281999** [comment] 2021-11-20 03:48
Hi @LekoArts , can I be assigned to this issue? Will be trying to create a PR within the next few days.

**Comment by pranav0281999** [comment] 2021-11-22 20:38
The issue is with [this](https://github.com/gatsbyjs/gatsby/blob/0a04e38d857255fe675101bd96797c67d2d6e743/packages/gatsby-plugin-image/src/components/lazy-hydrate.tsx#L70) line. Just converting the type of props isn't removing the extra properties that come with the object, like onStartLoad. It won't be possible to remove these properties while converting the type.

The ways extra props can be removed are -
* either explicitly mention which properties we want to delete in the code and delete those. But this is not optimal IMO.
* use a module like [https://github.com/kimamula/ts-transformer-keys](https://github.com/kimamula/ts-transformer-keys) which would be very easy to use but would require configuration changes.

@LekoArts @mosesoak or anyone else, what do you think can be done?

**Comment by daryazata** [comment] 2022-07-28 11:09
@wardpeet @iChenLei im looking for a 'good first issue'. Here there are some issue open even if there is a PR that solves it?

**Comment by LekoArts** [comment] 2022-09-14 05:48
This was indeed fixed, if you check out https://github.com/gatsbyjs/gatsby/blob/9ea3129e371cf7844bec2750885c2e2a18b18ca4/packages/gatsby-plugin-image/src/components/gatsby-image.browser.tsx you'll see that `onStartLoad` isn't placed onto the element anymore.

**Closed by LekoArts** 2022-09-14 05:48 UTC
Labels: type: bug, help wanted, good first issue, topic: media

**Comment by brysongilbert** [comment] 2023-08-31 21:41
I believe this is still an issue specifically when rendering the `img` fallback inside of `picture` elements, possibly here: https://github.com/gatsbyjs/gatsby/blob/d46c81585e40bc093bdd71389581a6d86f1587c1/packages/gatsby-plugin-image/src/components/picture.tsx#L46C17-L46C17

On gatsby 5.11 and gatsby-plugin-image 3.11 we see this show up in tests:

```
console.error
      Warning: Unknown event handler property `onStartLoad`. It will be ignored.
          at img
          at createElement (/<redacted-path-to-project>/node_modules/gatsby-plugin-image/src/components/picture.tsx:45:5)
          at picture
          at fallback (/<redacted-path-to-project>/node_modules/gatsby-plugin-image/src/components/picture.tsx:64:32)
          at MainImage
          at React (/<redacted-path-to-project>/node_modules/gatsby-plugin-image/src/components/layout-wrapper.tsx:107:17)
          at div
          at imgClassName (/<redacted-path-to-project>/node_modules/gatsby-plugin-image/src/components/gatsby-image.server.tsx:20:5)
          at div
          at // <our internal component which renders a GatsbyImage>
          ...
```
