### ISSUE TITLE
onCreateNode duplicated content

### ISSUE THREAD

**Issue by marcotuna** [gatsbyjs/gatsby#28687] opened 2020-12-18 11:24 UTC
## Description

When creating a custom onCreateNode for multi language.  
Example:  
```
src/pages/test/test.en.md
src/pages/test/test.pt.md
```

The pages work flawlessly, however when adding more and more it starts to mix the languageCode `pt` with the `en`, however when cleaning the `.cache` folder everything starts working flawlessly again.  

### Steps to reproduce

```
query MyQuery {
        allMarkdownRemark: allMarkdownRemark(
            filter: {
              	fields: { 
                  languageCode: {eq: "en"}
                }
              	frontmatter: {contentType: {eq: "templates/test/post"}}
            },
            sort:{
              fields: frontmatter___post___post___postTitle
            }
        ) {
            edges {
                node {
                  	fields {
                      languageCode
                    }
                    frontmatter {
                        path
                        post {
                            postTitle
                            postDescription
                            postThumbnail
                        }
                    }
                }
            }
        }
    }
```

Create a custom onCreateNode

gatsby-node.js
```
const RegexLangCode = `^.*\\.((.*?)/)$`;

exports.onCreateNode = ({node, actions, getNode}) => {
    const {createNodeField} = actions;

    if (node.internal.type === `MarkdownRemark`) {
        const value = createFilePath({node, getNode});

        let languageCode = '';
        let matchFiles = value.match(RegexLangCode);
        if (matchFiles && matchFiles[2] !== null) languageCode = matchFiles[2];

        createNodeField({
            node,
            name: `languageCode`,
            value: languageCode
        });
    }
};
```

### Expected result

```
{
  "data": {
    "allMarkdownRemark": {
      "edges": [
        {
          "node": {
            "fields": {
              "languageCode": "en"
            },
            "frontmatter": {
              "path": "test",
              "post": {
                "postTitle": "Test Post",
              }
            }
          }
        },
      ]
    }
  },
  "extensions": {}
}
```

### Actual result

```
{
  "data": {
    "allMarkdownRemark": {
      "edges": [
        {
          "node": {
            "fields": {
              "languageCode": "pt"
            },
            "frontmatter": {
              "path": "test",
              "post": {
                "postTitle": "Test Post",
              }
            }
          }
        },
        {
          "node": {
            "fields": {
              "languageCode": "en"
            },
            "frontmatter": {
              "path": "test",
              "post": {
                "postTitle": "Test Post",
              }
            }
          }
        },
      ]
    }
  },
  "extensions": {}
}
```

### Environment

```
  System:
    OS: Linux 5.4 Linux Mint 19.3 (Tricia)
    CPU: (8) x64 Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.18.4/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.198
    Firefox: 82.0.2
  npmPackages:
    gatsby: ^2.29.1 => 2.29.1
    gatsby-image: ^2.8.0 => 2.8.0
    gatsby-link: ^2.8.0 => 2.8.0
    gatsby-plugin-advanced-sitemap: ^1.5.6 => 1.5.6
    gatsby-plugin-google-analytics: ^2.8.0 => 2.8.0
    gatsby-plugin-google-tagmanager: ^2.8.0 => 2.8.0
    gatsby-plugin-manifest: ^2.9.0 => 2.9.0
    gatsby-plugin-netlify: ^2.8.0 => 2.8.0
    gatsby-plugin-netlify-cms: ^4.7.0 => 4.7.0
    gatsby-plugin-no-sourcemaps: ^2.6.0 => 2.6.0
    gatsby-plugin-react-helmet: ^3.7.0 => 3.7.0
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-robots-txt: ^1.5.3 => 1.5.3
    gatsby-plugin-sass: ^2.8.0 => 2.8.0
    gatsby-plugin-sharp: ^2.11.1 => 2.11.1
    gatsby-plugin-smoothscroll: ^1.2.0 => 1.2.0
    gatsby-plugin-svgr-loader: ^0.1.0 => 0.1.0
    gatsby-remark-copy-linked-files: ^2.7.0 => 2.7.0
    gatsby-remark-prismjs: ^3.10.0 => 3.10.0
    gatsby-source-filesystem: ^2.8.0 => 2.8.0
    gatsby-transformer-remark: ^2.13.0 => 2.13.0
    gatsby-transformer-sharp: ^2.9.0 => 2.9.0
```

**Comment by vladar** [comment] 2020-12-18 13:49
Hi @marcotuna !

Thank you for the report! To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-01-06 08:44
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2021-01-06 08:44 UTC
Labels: status: needs reproduction, topic: GraphQL, type: bug
