### ISSUE TITLE
The slugify option in gatsby-plugin-page-creator does not work

### ISSUE THREAD

**Issue by yacchi1123** [gatsbyjs/gatsby#38212] opened 2023-06-10 16:15 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

In File System Route API, there was a problem that slugs with underscores were converted to hyphens when trying to retrieve them.

So I tried to work around the above problem by using the slugify option in gatsby-plugin-page-creator.

My gatsby-config.js file is following:

```gatsby-config.js
{
  resolve: `gatsby-plugin-page-creator`,
  options: {
    path: `${__dirname}/src/pages/hoge`,
    slugify: { preserveCharacters: ['_'] },
  },
},
```

I modified `gatsby-config.js` based on the following document, but it did not work.

https://www.gatsbyjs.com/docs/reference/routing/file-system-route-api/#routing-and-linking
https://www.gatsbyjs.com/plugins/gatsby-plugin-page-creator/#options

I use gatsby Version `4.24.3`.
But I update Version to `5.3.3` had same results. 

### Reproduction Link

none

### Steps to Reproduce

1. Post data with underscored slugs in contentful(https://www.contentful.com/)

content of contentful  example:

```
title: test
slug: hoge_fuga
```

2. Create collection routes using File System Route API and Coding GraphQL queries, to retrieve the above post data.

example:

src/pages/hoge/{Hoge.slug}.tsx

```
import { graphql, PageProps } from 'gatsby'
import React from 'react'

const HogePage = ({ data }: PageProps<Queries.HogePageQuery>) => (
    <p>{data.contentfulHogePage.title}</p>
)

export default ArticleTestPage

export const data = graphql`
  query HogePage($id: String) {
    contentfulHogePage(id: { eq: $id }) {
      id
      slug
      title
    }
  }
`
```

3. Fix gatsby-config.js as follows

example:

```
{
  resolve: `gatsby-plugin-page-creator`,
  options: {
    path: `${__dirname}/src/pages/hoge`,
    slugify: { preserveCharacters: ['_'] },
  },
},
```

4. Access with underscored URL

example:
`/hoge/hoge_fuga`
...

### Expected Result

The page is displayed correctly.

### Actual Result

404 not found error.
If the underscore portion is replaced with a hyphen to access the page, the page is displayed without problems.

```
/hoge/hoge_fuga => NG
/hoge/hoge-fuga => OK
```

### Environment

```shell
System:
    OS: macOS 12.1
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 114.0.5735.106
    Safari: 15.2
  npmPackages:
    gatsby: ^4.24.3 => 4.25.6
    gatsby-image: ^2.11.0 => 2.11.0
    gatsby-legacy-polyfills: ^2.24.0 => 2.25.0
    gatsby-omni-font-loader: ^2.0.2 => 2.0.2
    gatsby-plugin-google-analytics: ^4.24.0 => 4.25.0
    gatsby-plugin-google-tagmanager: ^4.24.0 => 4.25.0
    gatsby-plugin-image: ^2.24.0 => 2.25.0
    gatsby-plugin-less: ^6.24.0 => 6.25.0
    gatsby-plugin-react-helmet: ^5.24.0 => 5.25.0
    gatsby-plugin-sass: ^5.24.0 => 5.25.0
    gatsby-plugin-sharp: ^4.24.0 => 4.25.1
    gatsby-plugin-sitemap: ^5.24.0 => 5.25.0
    gatsby-plugin-zendesk-chat: ^1.1.4 => 1.1.4
    gatsby-source-contentful: ^7.22.0 => 7.23.1
    gatsby-source-filesystem: ^4.24.0 => 4.25.0
    gatsby-telemetry: ^3.24.0 => 3.25.0
    gatsby-theme-material-ui: ^5.3.0 => 5.3.0
    gatsby-transformer-remark: ^5.24.0 => 5.25.1
    gatsby-transformer-sharp: ^4.24.0 => 4.25.0
    gatsby-transformer-yaml: ^4.24.0 => 4.25.0
```

**Comment by LekoArts** [comment] 2023-06-12 04:29
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

You should try this also:

```
{
  resolve: `gatsby-plugin-page-creator`,
  options: {
    path: `${__dirname}/src/pages`,
    slugify: { preserveCharacters: ['_'] },
  },
},
```

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by SpesEspero** [comment] 2023-06-30 11:42
Hi @LekoArts 
For me slugify: `{ preserveCharacters: ['_'] }` works for all tsx files

But I have the same problem with my mdx files. 

I named my file **{mdx.fields__slug}.tsx**  and expect that my file will have a name "hoge_fuga", but instead of this I have "hoge-fuga". 
Do you have a solution for this? If no I will try to provide the minimal reproduction

**Comment by LekoArts** [comment] 2023-06-30 11:46
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2023-06-30 11:46 UTC
Labels: type: bug, status: needs reproduction

**Comment by LekoArts** [comment] 2023-06-30 11:47
@SpesEspero 

> I named my file {mdx.fields__slug}.tsx and expect that my file will have a name "hoge_fuga", but instead of this I have "hoge-fuga".

`fields { slug }` on the `Mdx` node is manually created. You need to check the portion in your source code where this is generated. `gatsby-plugin-page-creator` doesn't change any of that.

**Comment by SpesEspero** [comment] 2023-06-30 16:29
@LekoArts 
Ye, exactly
But I do nothing with my slug, so if I write `console.log(slug)` it will be "hoge_fuga", but page name will be "hoge-fuga". I think this construction `{mdx.fields__slug}.tsx` for some reasons transform my slug

**Comment by rafalkrupinski** [comment] 2023-08-06 09:33
I have similar issue. Created a repo:

https://github.com/rafalkrupinski/gatsby-38212

**Comment by rafalkrupinski** [comment] 2023-08-14 07:55
anyone? @LekoArts ?
