### ISSUE TITLE
TypeError: Cannot read property 'allMarkdownRemark' of undefined

### ISSUE THREAD

**Issue by zhouxiang19910319** [gatsbyjs/gatsby#13233] opened 2019-04-09 01:56 UTC
I am building a page that consist this layout: 
![](https://res.cloudinary.com/zzrot/image/upload/v1551437774/slowpacedcoding_GATSBY/main_layout.png)

Both bio.js and post.js are two components that are being injected into index.js page.

**But I cannot get graphql to work on post.js.**
I got this 
> TypeError: Cannot read property 'allMarkdownRemark' of undefined
error message.

![](https://res.cloudinary.com/zzrot/image/upload/v1554774975/slowpacedcoding_GATSBY/Screen_Shot_2019-04-09_at_12.29.09_AM.png)

Here are code that matters: 

1. Index.js

```
import React from "react"
import { Link } from "gatsby"
import Layout from "../components/layout"
import SEO from "../components/seo"
import 'bootstrap/dist/css/bootstrap.css';
import Container from 'react-bootstrap/Container'
import Row from 'react-bootstrap/Row'
import Col from 'react-bootstrap/Col'
import Bio from '../components/bio'
import Blog from '../components/blog'



const IndexPage = () => (
  <Layout>
    <SEO title="slowpacedcoding" keywords={[`slowpacedcoding`, `programming`, `Matt Zhou`, `gatsbyJS`,`web development`,`zhouxiang19910319`,`web programming`]} />

    <Container>
      <Row>
        <Col xl={6} lg={6} md={12} sm={12} xs={12}>
          {/* BLOG POST SECTION IS HERE! */}
          <Blog/>
        </Col>

        <Col xl={6} lg={6} md={12} sm={12} xs={12}>
          {/* BIO SECTION IS HERE! */}
          <Bio />
        </Col>
      </Row>
     </Container>


  </Layout>
)

export default IndexPage
```

2. Bio.js
```
import React from "react"
import profile_pic from "../images/profile_pic.png"

class Bio extends React.Component{
  render (){
    return(
      <>
      <h3 style={{
        fontFamily: `'Montserrat', sans-serif`,
        fontWeight: 400,
        marginTop:`1rem`,
        color: `#f47c48`,
      }}>Bio</h3>

      <img src={profile_pic} alt="profile_pic" style={{
            width:`100px`,
          }}></img>

          <p style={{
            fontFamily: `'Montserrat', sans-serif`,
          }}>
          Former student of Singapore Polytechnic, dropped out at the end of year two, had been
          learning Web-Development since 2016. My goal is to become a web developer in an English speaking country.
          </p>

          <h5 style={{
            fontFamily: `'Montserrat', sans-serif`,
          }}>Find me at :</h5>

          <div>
            <a href="https://www.linkedin.com/in/xiang-zhou-03547755/" rel='noopener noreferrer' target="_blank" style={{backgroundColor: `#fff5e8`,color:`black`,textDecoration:`none`,}}>LinkedIn</a>
            <a href="https://github.com/zhouxiang19910319" rel='noopener noreferrer' target="_blank"  style={{backgroundColor: `#fff5e8`,color:`black`,textDecoration:`none`,}}>github</a>
            <a href="https://medium.freecodecamp.org/the-most-difficult-things-about-learning-to-code-by-yourself-b24ac8c3c23a "
            rel='noopener noreferrer' target="_blank" style={{backgroundColor: `#fff5e8`,color:`black`,textDecoration:`none`,}}>medium</a>
            <a href="https://twitter.com/zh0ux1ang" rel='noopener noreferrer' target="_blank" style={{backgroundColor: `#fff5e8`,color:`black`,textDecoration:`none`,}}>twitter</a>
            <a href="https://www.freecodecamp.org/zhouxiang19910319" rel='noopener noreferrer' target="_blank" style={{backgroundColor: `#fff5e8`,color:`black`,textDecoration:`none`,}} >freeCodeCamp</a>
          </div>
    </>
    )
  }
}

export default Bio

```

3. Blog.js
```
import React from "react"
import { Link,graphql } from "gatsby"
// import Layout from "../components/layout"
import 'bootstrap/dist/css/bootstrap.css'

class Blog extends React.Component{
  render(){
    const { data } = this.props;
    return(
      <>
      <h3
      style={{
        fontFamily: `'Montserrat', sans-serif`,
        fontWeight: 700,
      }}
      >Posts</h3>
      {data.allMarkdownRemark.edges.map(post=>(
        <div>
        <div key = {post.node.id}>
          <small
          style={{
            fontFamily: `'Montserrat', sans-serif`,
            fontWeight: 300,
            color: `#828282`,
          }}
          >{post.node.frontmatter.date}</small>
          <br></br>
          <h4
          style= {{
            display: `inline-block`,
            fontFamily: `'Montserrat', sans-serif`,
            fontWeight: 400,
            color: `#f47c48`,
          }}
          >{post.node.frontmatter.title}</h4>
        </div>
          <Link to={post.node.frontmatter.path} 
          style={{
            padding:0,}}
            >Read More</Link>
          <hr></hr>
        </div>
      ))}
      </>
    )
  }
}

export default Blog

export const pageQuery = graphql`
  query BlogIndexQuery{
      allMarkdownRemark
      (sort: { fields: [frontmatter___date], order: DESC })
      {
        edges{
          node{
            id
            frontmatter{
              path
              title
              date
              author
            }
          }
        }
      }
    }
`
```

**Comment by lannonbr** [comment] 2019-04-09 02:06
@zhouxiang19910319 So the issue is in `Blog.js` you can't do the `export const pageQuery` export in a regular react component. Those are Page Queries which only are available in either pages in `src/pages/` or pages [programmatically created with the gatsby-node apis](https://www.gatsbyjs.org/tutorial/part-seven/) and with a template.

To resolve this, you can take that graphql query and instead place it in a [StaticQuery](https://www.gatsbyjs.org/docs/static-query/) which are static graphql queries that can be placed anywhere in your codebase.

**Comment by sidharthachatterjee** [comment] 2019-04-10 21:22
Hey @zhouxiang19910319 

Marking this as answered thanks to @lannonbr and closing it out for now! Please feel free to comment or reopen if there is something we've missed. 

Thank you!

**Closed by sidharthachatterjee** 2019-04-10 21:22 UTC
Labels: type: question or discussion

**Comment by dhayzon** [comment] 2020-03-31 02:01
thanks  @lannonbr
