### ISSUE TITLE
Unable to create custom Query on 3rd party schema

### ISSUE THREAD

**Issue by baart1989** [gatsbyjs/gatsby#23446] opened 2020-04-24 07:02 UTC
## Description

Unable to create custom Query on 3rd party schema sourced through gatsby-source-graphql

### Steps to reproduce
Example [repo](https://github.com/baart1989/using-gatsby-source-graphql/tree/query-3rd-party-schema)

1. Use using-gatsby-source-graphql from gatsby examples
2. In gatsby-node.js use createResolvers function to create custom query on 3rd party data
```
//gatsby-node.js 
exports.createResolvers = ({
  actions,
  cache,
  createNodeId,
  createResolvers,
  store,
  reporter,
}) => {
  const { createNode } = actions
  createResolvers({
    Query: {
      allBlogPostTitles: {
        type: [`String!`],
        resolve(source, args, context, info) {
          const items = context.nodeModel.getAllNodes({
            type: `GraphCMS_BlogPost`,
          });
          return items.map(i => i.title);
        }
      }
    },
    GraphCMS_BlogPost: {
   .....
};
```

### Expected result

Query to return results 

### Actual result

Query returns empty result due to following function is not working as expected.

```
const items = context.nodeModel.getAllNodes({type: `GraphCMS_BlogPost` });
```

### Environment

```
System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.1 - ~/.nvm/versions/node/v12.6.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 57.0.4
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.18.10 => 2.20.29
    gatsby-cli: ^2.11.15 => 2.11.15
    gatsby-image: ^2.2.36 => 2.3.4
    gatsby-plugin-netlify: ^2.1.30 => 2.2.3
    gatsby-plugin-sharp: ^2.3.7 => 2.5.6
    gatsby-source-filesystem: ^2.1.42 => 2.2.4
    gatsby-source-graphql: ^2.1.28 => 2.4.2
    gatsby-transformer-sharp: ^2.3.9 => 2.4.6
  npmGlobalPackages:
    gatsby-cli: 2.11.7
    gatsby: 2.20.29
```

**Comment by vladar** [comment] 2020-05-06 16:27
Thank you for opening this, @baart1989 

Sadly, this is the expected behavior due to the limitations of `gatsby-source-graphql`. See #15906 for the full explanation.

Also, this comment and the whole thread may be useful: https://github.com/gatsbyjs/gatsby/issues/19803#issuecomment-561783945

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Closed by vladar** 2020-05-06 16:27 UTC
Labels: status: inkteam assigned, status: needs core review, topic: GraphQL, type: bug
