### ISSUE TITLE
Dynamic pages

### ISSUE THREAD

**Issue by razvan-soare** [gatsbyjs/gatsby#10125] opened 2018-11-25 23:35 UTC
Hey im doing a store and i encountered a problem with the product page. Not sure what are the best practices in this situation so any advice would be welcomed.

What i want: a page: `store` where ill have a list of products and then a route `store/product-name` where ill have the product details. Since the product page will be a dynamic page i added this inside gatsby-node.js
```
exports.onCreatePage = async ({ page, actions }) => {
  const { createPage } = actions;

  // page.matchPath is a special key that's used for matching pages
  // only on the client.
  if (page.path.match(/^\/store/)) {
    page.matchPath = '/store/*';

    // Update the page.
    createPage(page);
  }
};
```

it's creating the new pages all good but the product page will point to `pages/store.js`. So i tried to determine if the url is only `store` then will display the storeList component otherwise will display the productDetails component. It worked just fine on local i was so happy but when i deployed on my apache server i lost some css.. After some investigations i saw that if i go from `store -> store/product` everything was just fine but if i refreshed or went directly to `store/product` gatsby will mess the classes on wrapper divs.. (ill attach pictures)

![screen shot 2018-11-25 at 21 38 56](https://user-images.githubusercontent.com/39434481/48986030-99169e80-f10f-11e8-83cd-5033dc7051c2.png)
![screen shot 2018-11-25 at 21 38 48](https://user-images.githubusercontent.com/39434481/48986031-99169e80-f10f-11e8-9c77-9b92ef26d7ac.png)

This bits of code are from the same page (the product page) once entered from store -> product and 2nd time directly on `store/product`

also tried ->

```
createPage({
      ...page,
      component: path.resolve('./src/components/Store/ProductPage/index.jsx'),
    });
```
but i cannot get access to my store page no more :\

first i tried moving it to another page so i had `store` and `store-product/product-name` and then it worked just fine but i need them to be just on store.

I had similar problems before when i was trying to condition the render. Like i had some state and if that was true i would display componentA else componentB .. and gatsby would get the classes wrong and only display the first one.. no idea i will try to reproduce it at some point.. but time is not on my side :| 

Another thing that i find weird is that when i deployed it on netlify it worked... Same with `gatsby serve`. So the only problem is when im deploying it on my server. So wondering if im doing something wrong here? Im just grabbing the contents of public folder and adding it in public folder on my server. Do i need to do anything else ??

Any idea would be really appreciated 
Thank you.

**Comment by razvan-soare** [comment] 2018-11-26 08:15
Ok i did more tests and not sure if i can do anything from gatsby-node. Im getting for both `/store` and `/store/product` the same paths ... and i cannot determine at that level what component to use... 

Or maybe i just dont know how..

**Comment by sidharthachatterjee** [comment] 2018-12-13 16:22
Duplicate of https://github.com/gatsbyjs/gatsby/issues/10370

**Closed by sidharthachatterjee** 2018-12-13 16:22 UTC
Labels: type: duplicate
