### ISSUE TITLE
Generating JavaScript bundles failed at styles.30d557dafec19dc3b450.css

### ISSUE THREAD

**Issue by diogoyaguas** [gatsbyjs/gatsby#38254] opened 2023-06-21 09:32 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I was reviewing the logs and noticed that it was necessary to run the command "npx update-browserslist-db@latest". After executing this command, I was still able to run the project locally. However, when I tried to build the project, I encountered two errors during the process of generating JavaScript bundles.

### Reproduction Link

https://github.com/diogoyaguas/jose-vaz-creative-services

### Steps to Reproduce

1. Clone repository
2. npm install
3. gatsby build

**ERRORS*

### Expected Result

The project should be built successfully without any errors

### Actual Result

Two errors occur during the generation of JavaScript bundles

failed Building production JavaScript and CSS bundles - 1.446s

 ERROR #98123  WEBPACK.BUILD-JAVASCRIPT

Generating JavaScript bundles failed

styles.30d557dafec19dc3b450.css from Css Minimizer
/Users/diogoyaguas/Documents/jose-vaz-creative-services/styles.30d557dafec19dc3b450.css:137:5: Unknown word [styles.30d557dafec19dc3b450.css:137,5]
    at Input.error (/Users/diogoyaguas/Documents/jose-vaz-creative-services/node_modules/postcss/lib/input.js:148:16)
    at Parser.unknownWord (/Users/diogoyaguas/Documents/jose-vaz-creative-services/node_modules/postcss/lib/parser.js:540:22)
    at Parser.other (/Users/diogoyaguas/Documents/jose-vaz-creative-services/node_modules/postcss/lib/parser.js:164:12)
    at Parser.parse (/Users/diogoyaguas/Documents/jose-vaz-creative-services/node_modules/postcss/lib/parser.js:72:16)
    at parse (/Users/diogoyaguas/Documents/jose-vaz-creative-services/node_modules/postcss/lib/parse.js:11:12)
    at new LazyResult (/Users/diogoyaguas/Documents/jose-vaz-creative-services/node_modules/postcss/lib/lazy-result.js:133:16)
    at Processor.process (/Users/diogoyaguas/Documents/jose-vaz-creative-services/node_modules/postcss/lib/processor.js:28:14)
    at cssnanoMinify (eval at transform (/Users/diogoyaguas/Documents/jose-vaz-creative-services/node_modules/css-minimizer-webpack-plugin/dist/minify.js:34:28), <anonymous>:51:61)
    at minify (/Users/diogoyaguas/Documents/jose-vaz-creative-services/node_modules/css-minimizer-webpack-plugin/dist/minify.js:15:32)
    at Object.transform (/Users/diogoyaguas/Documents/jose-vaz-creative-services/node_modules/css-minimizer-webpack-plugin/dist/minify.js:35:24)

File: styles.30d557dafec19dc3b450.css

 ERROR #98123  WEBPACK.BUILD-JAVASCRIPT

Generating JavaScript bundles failed

styles.fbdc00249f328392cd69.css from Css Minimizer
/Users/diogoyaguas/Documents/jose-vaz-creative-services/styles.fbdc00249f328392cd69.css:137:5: Unknown word [styles.fbdc00249f328392cd69.css:137,5]
    at Input.error (/Users/diogoyaguas/Documents/jose-vaz-creative-services/node_modules/postcss/lib/input.js:148:16)
    at Parser.unknownWord (/Users/diogoyaguas/Documents/jose-vaz-creative-services/node_modules/postcss/lib/parser.js:540:22)
    at Parser.other (/Users/diogoyaguas/Documents/jose-vaz-creative-services/node_modules/postcss/lib/parser.js:164:12)
    at Parser.parse (/Users/diogoyaguas/Documents/jose-vaz-creative-services/node_modules/postcss/lib/parser.js:72:16)
    at parse (/Users/diogoyaguas/Documents/jose-vaz-creative-services/node_modules/postcss/lib/parse.js:11:12)
    at new LazyResult (/Users/diogoyaguas/Documents/jose-vaz-creative-services/node_modules/postcss/lib/lazy-result.js:133:16)
    at Processor.process (/Users/diogoyaguas/Documents/jose-vaz-creative-services/node_modules/postcss/lib/processor.js:28:14)
    at cssnanoMinify (eval at transform (/Users/diogoyaguas/Documents/jose-vaz-creative-services/node_modules/css-minimizer-webpack-plugin/dist/minify.js:34:28), <anonymous>:51:61)
    at minify (/Users/diogoyaguas/Documents/jose-vaz-creative-services/node_modules/css-minimizer-webpack-plugin/dist/minify.js:15:32)
    at Object.transform (/Users/diogoyaguas/Documents/jose-vaz-creative-services/node_modules/css-minimizer-webpack-plugin/dist/minify.js:35:24)

File: styles.fbdc00249f328392cd69.css

### Environment

```shell
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.14.0 - ~/.nvm/versions/node/v18.14.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.3.1 - ~/.nvm/versions/node/v18.14.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Firefox: 111.0
    Safari: 16.5
  npmPackages:
    gatsby: ^5.3.3 => 5.11.0
    gatsby-image: ^3.11.0 => 3.11.0
    gatsby-plugin-image: ^3.9.0 => 3.11.0
    gatsby-plugin-manifest: ^5.9.0 => 5.11.0
    gatsby-plugin-mdx: ^5.9.0 => 5.11.0
    gatsby-plugin-react-svg: ^3.3.0 => 3.3.0
    gatsby-plugin-sass: ^6.9.0 => 6.11.0
    gatsby-plugin-sharp: ^5.9.0 => 5.11.0
    gatsby-plugin-sitemap: ^6.9.0 => 6.11.0
    gatsby-plugin-typegen: ^3.1.0 => 3.1.0
    gatsby-source-filesystem: ^5.9.0 => 5.11.0
    gatsby-transformer-json: ^5.10.0 => 5.11.0
    gatsby-transformer-sharp: ^5.9.0 => 5.11.0
  npmGlobalPackages:
    gatsby-cli: 5.9.0
```

**Comment by LekoArts** [comment] 2023-06-26 05:55
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2023-07-05 07:23
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2023-07-05 07:23 UTC
Labels: type: bug, status: needs reproduction
