### ISSUE TITLE
Error: Operation gid://shopify/BulkOperation/{id} failed with null

### ISSUE THREAD

**Issue by davidpaulsson** [gatsbyjs/gatsby#32067] opened 2021-05-11 06:25 UTC
Just throwing this out there if anyone has ideas about what it could be. My CI builds fail ~50% of the times with `Error: Operation gid://shopify/BulkOperation/id failed with null`. If I immediately re-trigger a build it always works.

Full error from logs:

```
7:54:03 AM: error Could not source from bulk operation: null
7:54:03 AM: 
7:54:03 AM: 
7:54:03 AM:   Error: Operation gid://shopify/BulkOperation/347429568565 failed with null
7:54:03 AM:   
7:54:03 AM:   - operations.ts:156 completedOperation
7:54:03 AM:     [repo]/[gatsby-source-shopify]/src/operations.ts:156:15
7:54:03 AM:   
7:54:03 AM:   - task_queues.js:97 processTicksAndRejections
7:54:03 AM:     internal/process/task_queues.js:97:5
7:54:03 AM:   
7:54:03 AM:   - make-source-from-operation.ts:67 sourceFromOperation
7:54:03 AM:     [repo]/[gatsby-source-shopify]/src/make-source-from-operation.ts:67:18
7:54:03 AM:   
7:54:03 AM:   - gatsby-node.ts:71 sourceAllNodes
7:54:03 AM:     [repo]/[gatsby-source-shopify]/src/gatsby-node.ts:71:5
7:54:03 AM:   
7:54:03 AM:   - gatsby-node.ts:190 Object.sourceNodes
7:54:03 AM:     [repo]/[gatsby-source-shopify]/src/gatsby-node.ts:190:5
7:54:03 AM:   
7:54:03 AM:   - api-runner-node.js:434 runAPI
7:54:03 AM:     [repo]/[gatsby]/src/utils/api-runner-node.js:434:16
```

I read somewhere that _"If the query produced no results, then the url field will return null."_, but maybe that's unrelated.

### Using
```
"gatsby-source-shopify": "^5.0.0-rc.21",
"gatsby": "^3.4.1",
```

**Comment by LekoArts** [comment] 2021-06-24 05:07
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-07-06 09:54
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-07-06 09:54 UTC
Labels: status: needs reproduction, topic: source-shopify, type: bug
