### ISSUE TITLE
[gatsby-plugin-sharp] - Issue with 3.9+ version with png files: not generating cache files.

### ISSUE THREAD

**Issue by yesh** [gatsbyjs/gatsby#32310] opened 2021-07-09 16:21 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi all,

having a big issue with the plugin:

Development server stops while rendering PNG files in browser, with no consistency, with some PNG it works and with other it doesn't and randomly stops working also with the ones that worked before.

the issue is NOT reproducing in previous versions (tested 3.5 - 3.8)

current configuration:

Node: 14.17.3
Gatsby CLI version: 2.8.11
Gatsby version: 3.9.0

### Terminal Error message

```
ERROR

ENOENT: no such file or directory, open
'/Users/******/project/.cache/caches/gatsby-plugin-sharp/diskstore-8547b0fff47807685e0c93e14ccf1664.json'

Error: ENOENT: no such file or directory, open '/Users/******/project/.cache/caches/gatsby-plugin-sharp/d
  iskstore-8547b0fff47807685e0c93e14ccf1664.json'
```

in this case the folder is not even  generated in the `.cache/caches` directory.

### Reproduction Link

https://github.com/yesh/g-p-s-png-issue

### Steps to Reproduce

1. install latest gatsby-plugin-image + latest dependencies `gatsby-plugin-sharp` (3.9+)
2. render png image with GatsbyImage from graphql source or StaticImage from local image
3. development stops as soon as you render the image in browser (not consistent, sometime stops and sometimes doesn't, with the same image)

### Expected Result

image renders flawlessly

### Actual Result

image does not render and crashes development server

### Environment

```shell
System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.19.1 - ~/.nvm/versions/node/v14.17.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0.2
    Safari: 14.1.1
  npmPackages:
    gatsby: ^3.9.0 => 3.9.0 
    gatsby-plugin-gatsby-cloud: ^2.9.0 => 2.9.0 
    gatsby-plugin-image: ^1.9.0 => 1.9.0 
    gatsby-plugin-manifest: ^3.9.0 => 3.9.0 
    gatsby-plugin-offline: ^4.9.0 => 4.9.0 
    gatsby-plugin-react-helmet: ^4.9.0 => 4.9.0 
    gatsby-plugin-sharp: ^3.9.0 => 3.9.0 
    gatsby-source-filesystem: ^3.9.0 => 3.9.0 
    gatsby-transformer-sharp: ^3.9.0 => 3.9.0
```

### Config Flags

no flags

**Comment by vsolanogo** [comment] 2021-07-09 16:59
this error ruined my day

**Comment by LekoArts** [comment] 2021-07-09 17:52
Duplicate of https://github.com/gatsbyjs/gatsby/issues/32288

**Closed by LekoArts** 2021-07-09 17:52 UTC
Labels: status: triage needed, type: bug
