### ISSUE TITLE
Fresh install: Gatbyjs ERROR 98123 - unknown browser query

### ISSUE THREAD

**Issue by BenjaminMews** [gatsbyjs/gatsby#25062] opened 2020-06-17 14:48 UTC
I get from a fresh install the error:  

[BABEL] C:\user\gatsby-starter-forty\.cache\production-app.js: Unknown browser query `basedir=$(dirname "$(echo "$0" | sed -e 's`. Maybe you are using old Browserslist or made typo in query. (While processing: "C:\\user\\gatsby-starter-forty\\node_modules\\@babel\\preset-env\\lib\\index.js") 

This happens on any starter! Any ideas on that?

**Comment by vladar** [comment] 2020-06-17 18:21
Hi @BenjaminMews 

Sorry to hear you're running into an issue. I could not reproduce the problem you describe with the following steps:

```shell
gatsby new gatsby-starter-forty https://github.com/codebushi/gatsby-starter-forty
cd gatsby-starter-forty
gatsby develop
```

So probably something is not right with your local setup. Try upgrading to the latest version of gatsby-cli:

```shell
npm install -g gatsby-cli
```

If it doesn't help then please share your project via GitHub (with `package-lock.json` or `yarn.lock`). Then we can take another look.

Also, please provide this information:
- Gatsby version
- Node.js version
- OS version

Thanks for using Gatsby! 💜

**Comment by freiksenet** [comment] 2020-07-03 09:05
Hi! 

I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. 

Thanks!

**Closed by freiksenet** 2020-07-03 09:05 UTC
Labels: status: needs more info, type: question or discussion
