### ISSUE TITLE
[gatsby-transformer-remark] 3rd level Indentation bug with UTF-8 characters

### ISSUE THREAD

**Issue by FourEyebrowXiake** [gatsbyjs/gatsby#2326] opened 2017-10-04 08:24 UTC
This is the result of gatsby generation.Indentation is wrong：
![image](https://user-images.githubusercontent.com/18180417/31165998-b17cba7e-a91f-11e7-992b-3ac4a68501f6.png)
This is markdown file:
![image](https://user-images.githubusercontent.com/18180417/31166016-c55d689a-a91f-11e7-9f94-a2ec0035e37a.png)
This is local rendering
![image](https://user-images.githubusercontent.com/18180417/31166037-dd227bc8-a91f-11e7-9bd3-6f773502c924.png)

my version of gatsby-transformer-remark is 1.7.15. This is the latest version.

How do i solve this problem?

**Comment by sebastienfi** [comment] 2017-10-04 10:40
@FourEyebrowXiake Could you build a small site which reproduces this problem?

**Comment by FourEyebrowXiake** [comment] 2017-10-04 11:25
@sebastienfi  I solve the problem.
I write html in my article:
<ul>HTML
  <ul>
    <li>常用的meta头:
      <ul>
        <li>name</li>
        <li>http-equiv</li>
      </ul>
    </li>
    <li>对标签语义化的理解:</li>
    <li>HTML5 新特性:
      <ul>
        <li>Html5 的基本布局（语义化的标记）</li>
        <li>Html5 对表单的支持</li>
        <li>Html5 中的 Media</li>
        <li>动画元素 Canvas</li>
        <li>Drag&Drop</li>
        <li>Html 5 的 Application Cache</li>
        <li>Local storge</li>
      </ul>
    </li>
  </ul>
</ul>

**Comment by FourEyebrowXiake** [comment] 2017-10-04 11:27
@sebastienfi 
this is a  a small site which reproduces this problem:
http://foureyebrowxiake.github.io/%E5%89%8D%E7%AB%AF%E6%A0%A1%E6%8B%9B%E4%BC%9A%E8%80%83%E5%AF%9F%E4%BB%80%E4%B9%88%EF%BC%88%E4%B8%80%EF%BC%89/

**Comment by sebastienfi** [comment] 2017-10-04 11:28
@FourEyebrowXiake I meant the source code, on a GitHub repo than we can clone ;)

**Comment by FourEyebrowXiake** [comment] 2017-10-04 11:31
https://github.com/FourEyebrowXiake/MyNewBlog

**Comment by KyleAMathews** [comment] 2017-10-05 17:55
Probably a better path forward on this is to submit a PR with a failing test added here: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-transformer-remark/src/__tests__/gatsby-node.js

**Comment by luosong** [comment] 2018-01-19 11:01
I got same issue. How to resolve it?

**Comment by KyleAMathews** [comment] 2018-01-19 15:11
@luosong after thinking about this some more, this is almost certainly a bug in Remark, the JS library we use to parse markdown https://github.com/remarkjs/remark

You can test what's doing in the AST Explorer https://astexplorer.net/#/gist/0a92bbf654aca4fdfb3f139254cf0bad/ffe102014c188434c027e43661dbe6ec30042ee2 as well as file a bug in the Remark repo.

**Comment by KyleAMathews** [comment] 2018-09-08 04:29
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Closed by KyleAMathews** 2018-09-08 04:29 UTC
Labels: status: needs more info, type: bug :beetle:
