### ISSUE TITLE
Node schema having caching issues after subsequent runs

### ISSUE THREAD

**Issue by lannonbr** [gatsbyjs/gatsby#12981] opened 2019-04-01 01:15 UTC
## Description

On subsequent runs of `gatsby develop` in a project of mine, the schema is running into some caching issues.

### Steps to reproduce

Check out the [gatsby-schema-cache-bug-repro](https://github.com/lannonbr/gatsby-schema-cache-bug-repro) repo I just made to show off this bug.

1. clone down the repo and install dependencies
2. do `gatsby develop` once and load the frontpage and see no issues. you should see a list of events with some dates.
3. stop the dev server, and run `gatsby develop` once again without clearing the cache. you should get an error stating `Unknown argument "formatString" on field "local_date" of type "SyrEvent".`

### Expected result

On every run of `gatsby develop`, no errors should appear.

### Actual result

Got the following error on the 2nd and later run of `gatsby develop`:

```
The GraphQL query from gatsby-schema-cache-bug-repro/src/pages/index.js failed.

Errors:
  Unknown argument "formatString" on field "local_date" of type "SyrEvent".
  
  GraphQL request (5:18)
  4:       name
  5:       local_date(formatString: "MMMM DD, YYYY")
                      ^
  6:     }
  
URL path:
  /
Context:
  {}
Plugin:
  none
Query:
  query PageQuery {
    allSyrEvent {
      nodes {
        name
        local_date(formatString: "MMMM DD, YYYY")
      }
    }
  }
```

As a side-note, running `gatsby clean` and then spinning up the dev server again will resolve this for one time. running the dev server a 2nd time after this will break it again.

### Environment

```
  System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 11.10.0 - /usr/local/bin/node
    Yarn: 1.15.2 - ~/.yarn/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 73.0.3683.86
    Firefox: 66.0.2
    Safari: 12.1
  npmPackages:
    gatsby: ^2.3.3 => 2.3.3 
    gatsby-source-filesystem: ^2.0.28 => 2.0.28 
    gatsby-source-meetup: ^0.0.1 => 0.0.1 
    gatsby-transformer-json: ^2.1.11 => 2.1.11 
  npmGlobalPackages:
    gatsby-cli: 2.5.4
```

**Comment by freiksenet** [comment] 2019-04-01 08:26
Thank you for the report! I can reproduce, very weird stuff. I'll try to fix it today.

**Comment by freiksenet** [comment] 2019-04-01 08:38
Ok, so it seems that onCreateNode is called differently when running with and without cache, meaning the SyrEvent thing isn't loaded correctly. Not sure what's the issue yet.

**Comment by pieh** [comment] 2019-04-01 10:17
@lannonbr When creating nodes in `onCreateNode`, you need to set `parent` - https://github.com/lannonbr/gatsby-schema-cache-bug-repro/pull/1 .

Here's related issue https://github.com/gatsbyjs/gatsby/issues/11785 . I would classify this one as papercut, and would we could do is display warning when creating nodes in `onCreateNode` without setting parent.

This is needed because we do remove "stale" nodes on rerun (nodes that were not re-created). And if original node wasn't changed since last run, the `onCreateNode` is not called again on second run

**Comment by lannonbr** [comment] 2019-04-01 12:46
@pieh that worked! My issue has been resolved so I'm not sure if we should leave this issue open or close it and maybe look to possibly add a warning message with a separate issue.

**Comment by pieh** [comment] 2019-04-01 13:53
Let's close this one and I'll reopen issue that was originally opened for it (https://github.com/gatsbyjs/gatsby/issues/11785), as fix was created just for single instance of it (`createRemoteFileNode`).

**Closed by pieh** 2019-04-01 13:53 UTC
Labels: status: confirmed, type: bug
