### ISSUE TITLE
Don't use `css` prop in components to pass in styles

### ISSUE THREAD

**Issue by wuweiweiwu** [gatsbyjs/gatsby#6649] opened 2018-07-21 20:57 UTC
## Description

Components in the website like [Container](https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/container.js) with a prop `css`. When you actually try to specify it, it conflicts with the `glamor` css attribute and the prop isnt passed properly. 

Use something like `containerCss` shown  in [`email-capture-form`](https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/email-capture-form.js#L88)

**Comment by KyleAMathews** [comment] 2018-07-21 21:47
We are using Glamor so that component is working as expected. Or is there something else going on here?

**Comment by wuweiweiwu** [comment] 2018-07-22 07:51
Some components use like Container use the css prop to pass in additional style props to the root element that has the glamor css attribute. But when I was doing development locally, it seems to always pass an empty object. I'm thinking that the css prop name conflicts with the glamor css prop.

**Comment by trevorlitsey** [comment] 2018-08-06 16:58
Hi! Would love to help out on this if it still needs resolving. Looks like all that needs to be done is change the `<Container />` `css` prop to `containerCss`? Didn't see any other react components with a css prop from a cursory search.

**Comment by m-allanson** [comment] 2018-08-13 22:14
Hey @trevorlitsey I missed your comment earlier, apologies! It turns out there was a bit of tidying up that could happen here - check out @jamezrin's PR for details.

> We are using Glamor so that component is working as expected. Or is there something else going on here?

@KyleAMathews I think the [createElement helper](https://github.com/threepointone/glamor/blob/master/docs/createElement.md) is preventing the `css` prop from being passed through? I confirmed that it wasn't being passed through but didn't do too much digging beyond that.

**Closed** 2018-08-14 14:37 UTC
Labels: good first issue, 📍 status: help wanted

**Comment by KyleAMathews** [comment] 2018-08-14 15:42
@m-allanson yeah, looks that's right. Curious why I thought it was working before in the past 🤔
