### ISSUE TITLE
Gatsby develop failing with Unexpected Token error but no other details or stacktrace

### ISSUE THREAD

**Issue by aks1994** [gatsbyjs/gatsby#27716] opened 2020-10-29 16:32 UTC
## Description

I have a Gatsby site which has been running fine for over a year.

My site initially was building fine locally today but when I pushed to Netlify, it gave an error "Generating SSR Bundle Failed"

```
error Generating SSR bundle failed
6:22:36 PM: Unexpected token (99:31)
```

Suspecting it had something to do with package version mismatch (my project still does not use yarn), I deleted my package-lock.json and reinstalled node_modules on my local machine. Then I got the same error locally during develop and build.

Unfortunately, it does not give a stacktrace or any other info about where the Unexpected Token is coming from.

This is the exact error from develop:

```
error Generating development JavaScript bundle failed
Unexpected token (99:31)
failed Building development bundle - 22.571s
```

Any suggestions on how I can go about debugging which package / other source (line 99 of which file) could be the cause of this issue?

### Steps to reproduce

My project is private, but to reproduce in my project, I have to simply run `gatsby develop` and the issue occurs every time

### Expected result

Bundle should build successfully

### Actual result

Bundle does not build

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.0.1 - ~/.nvm/versions/node/v15.0.1/bin/node
    npm: 7.0.3 - ~/.nvm/versions/node/v15.0.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.111
    Firefox: 82.0
    Safari: 14.0
  npmPackages:
    gatsby: ^2.14.4 => 2.24.91 
    gatsby-background-image: ^0.6.2 => 0.6.2 
    gatsby-image: ^2.2.14 => 2.4.21 
    gatsby-plugin-facebook-pixel: ^1.0.3 => 1.0.5 
    gatsby-plugin-google-gtag: ^2.1.2 => 2.1.13 
    gatsby-plugin-manifest: ^2.1.1 => 2.4.37 
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0 
    gatsby-plugin-nprogress: ^2.1.4 => 2.3.13 
    gatsby-plugin-offline: ^2.2.10 => 2.2.10 
    gatsby-plugin-polyfill-io: ^1.1.0 => 1.1.0 
    gatsby-plugin-react-helmet: ^3.1.5 => 3.3.14 
    gatsby-plugin-react-svg: ^2.1.2 => 2.1.2 
    gatsby-plugin-remove-console: 0.0.2 => 0.0.2 
    gatsby-plugin-robots-txt: ^1.5.3 => 1.5.3 
    gatsby-plugin-sharp: 2.6.11 => 2.6.11 
    gatsby-plugin-sitemap: ^2.2.9 => 2.4.17 
    gatsby-source-filesystem: ^2.1.18 => 2.3.37 
    gatsby-source-sanity: ^5.0.5 => 5.0.6 
    gatsby-source-wordpress: ^3.1.25 => 3.3.41 
    gatsby-transformer-json: ^2.2.6 => 2.4.15 
    gatsby-transformer-sharp: ^2.1.21 => 2.5.20 
  npmGlobalPackages:
    gatsby-cli: 2.12.113

**Comment by LekoArts** [comment] 2020-11-02 08:59
Hi!

I fear we still need a [minimal reproduction][reproduction] as from the outside we can't give any more detail than what you're seeing. You can try running it with `gatsby develop --verbose`. Also, it shouldn't completely fail the build so looking in the browser and console could also give some more information.

[reproduction]: https://gatsby.dev/reproduction

**Comment by aks1994** [comment] 2020-11-03 13:24
Thanks for your reply. I was able to identify the issue by stripping away at my project till the build succeeded. Found that the problem was the module `node-html-parser` which had a bug in one of it's recent updates (https://github.com/taoqf/node-html-parser/issues/82) and now that it is fixed, updating that package solved my problem.

Definitely not a gatsby issue now, but only feedback is if it is at all possible to get better error stacktraces in such cases.

To recreate we need to simply install `node-html-parser@1.4.3` in a gatsby project and import it like this `var HTMLParser = require('node-html-parser');` and you will see the error

**Comment by vladar** [comment] 2020-11-06 12:27
Hey @aks1994 

Glad that you've figured out what the problem was. I am going to close this issue as the underlying problem is fixed upstream. But I encourage you to open a new feature-request for better stack-traces and your repro.

Thanks!

**Closed by vladar** 2020-11-06 12:27 UTC
Labels: status: needs reproduction, type: bug
