### ISSUE TITLE
Empty Gatsby Config

### ISSUE THREAD

**Issue by tomshaw** [gatsbyjs/gatsby#34501] opened 2022-01-15 22:28 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

After running gatsby new or npm init gatsby project is created correctly but with an empty config. 

```
module.exports = {
    siteMetadata: {
        siteUrl: `https://www.yourdomain.tld`,
    },
    plugins: [

    ]
}
```

### Reproduction Link

N/A

### Steps to Reproduce

1. gatsby new 
2. npm init gatsby
...

### Expected Result

Populated config

### Actual Result

Empty config

### Environment

```shell
Windows 10
Node v14.18.1
gatsby-cli@4.5.1
```

### Config Flags

None

**Comment by tyhopp** [comment] 2022-01-17 06:40
Hi @tomshaw!

Sorry to hear you're running into an issue. Can you please share what you expect the config file to look like specifically?

If it doesn't match what you expect, it would be great if you could also add a minimal reproduction to help us debug this.

Thanks!

**Comment by LekoArts** [comment] 2022-01-17 07:50
Duplicate of https://github.com/gatsbyjs/gatsby/issues/34477

**Closed by LekoArts** 2022-01-17 07:50 UTC
Labels: topic: cli
