### ISSUE TITLE
Gatsby-source-wordpress downloading remote files success on incomplete amount

### ISSUE THREAD

**Issue by b-reklass** [gatsbyjs/gatsby#22591] opened 2020-03-26 16:00 UTC
## Description

Recently, the connection via gatsby-source-wordpress has been incorrectly reporting complete when downloading remotely. This has seemingly started out of nowhere, without package updates. I've tried to resolve this with setting GATSBY_CONCURRENT_DOWNLOAD, etc, with no success.

### Steps to reproduce

Run gatsby develop, watch output.

### Expected result

It should download all 117 files.

### Actual result

<img width="1061" alt="Screen Shot 2020-03-26 at 9 50 39 AM" src="https://user-images.githubusercontent.com/29928251/77666973-42a9b200-6f47-11ea-9457-ebe7478d6aff.png">

### Environment

  System:
    OS: macOS 10.14.4
    CPU: x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.1 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 64.0.2
    Safari: 12.1
  npmPackages:
    gatsby: ^2.20.7 => 2.20.7 
    gatsby-image: ^2.2.8 => 2.2.8 
    gatsby-plugin-create-client-paths: ^2.0.0-rc.1 => 2.0.0-rc.1 
    gatsby-plugin-facebook-pixel: ^1.0.3 => 1.0.3 
    gatsby-plugin-favicon: ^3.1.2 => 3.1.2 
    gatsby-plugin-force-trailing-slashes: ^1.0.4 => 1.0.4 
    gatsby-plugin-google-analytics: ^2.0.7 => 2.0.7 
    gatsby-plugin-google-tagmanager: ^2.0.6 => 2.0.6 
    gatsby-plugin-manifest: ^2.2.31 => 2.2.40 
    gatsby-plugin-netlify: ^2.1.3 => 2.1.3 
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0 
    gatsby-plugin-node-fields: ^1.0.0 => 1.0.0 
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.21 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-robots-txt: ^1.3.0 => 1.3.0 
    gatsby-plugin-sharp: ^2.3.5 => 2.4.4 
    gatsby-plugin-sitemap: ^2.0.0-rc.0 => 2.0.0-rc.0 
    gatsby-plugin-sri: ^1.0.2 => 1.0.2 
    gatsby-plugin-styled-components: ^3.0.0-rc.0 => 3.0.0-rc.0 
    gatsby-source-wordpress: ^3.2.2 => 3.2.2 
    gatsby-transformer-sharp: ^2.3.6 => 2.3.13 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

**Comment by vladar** [comment] 2020-03-27 14:25
Hi @b-reklass !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by danabrit** [comment] 2020-05-29 23:29
Closing due to no reproduction. Please open with a minimal reproduction if this is still an issue. Thank you!

**Closed by danabrit** 2020-05-29 23:29 UTC
Labels: status: needs reproduction, topic: WordPress, type: bug
