### ISSUE TITLE
Gatsby new just created a never ending list of folders on my computer

### ISSUE THREAD

**Issue by yongelee** [gatsbyjs/gatsby#3266] opened 2017-12-19 03:05 UTC
I installed Gatsby cli and did the first few steps.

Gatsby develop wasn't working so I upgraded npm then tried installing gatsby-cli again.

I tried following the steps again but apparently used the same folder name for a folder that wasn't properly deleted?

Now in my documents there is a never ending folder path of the gatsby new $name that I entered.

https://imgur.com/a/0j7kY

It goes on and on and on.

Wtf?

**Comment by KyleAMathews** [comment] 2017-12-19 03:29
Dunno — try deleting the folder and trying again.

**Comment by mpolinowski** [comment] 2017-12-19 06:25
I had the same issue once with an older version of gatsby-cli. I deleted the folder, tried again and couldn't reproduce it.

**Comment by mpolinowski** [comment] 2017-12-19 16:24
Have you tried:

```
rmdir c:\[...path to directory...]\Portfolio /s
```

It should get rid of it, even if the folder structure is too deep for Windows Explorer. You might have to run your command line as administrator

```
runas /user:Administrator cmd
```

**Comment by yongelee** [comment] 2017-12-19 16:26
I think my command line doesn't see the portfolio folder? It thinks its deleted? But in my folder explorer it's still there

**Comment by mpolinowski** [comment] 2017-12-19 16:31
Ok, sounds strange - did you restart? Otherwise, I am out of luck here... did not see this problem before  ¯\_(ツ)_/¯

**Comment by yongelee** [comment] 2017-12-19 16:50
Yes I did restart..strange indeed.

**Comment by calcsam** [comment] 2017-12-26 06:39
Weird. Going to close this issue.

**Closed by calcsam** 2017-12-26 06:39 UTC
