### ISSUE TITLE
Gatsby 4.21.1 https://website.com/page-data/sq/d is missing, thus the website shows a black page for some users but not others!

### ISSUE THREAD

**Issue by ezrover** [gatsbyjs/gatsby#36906] opened 2022-10-27 20:40 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

We are using:

    "gatsby": "^4.21.1",
    "gatsby-plugin-catch-links": "^4.21.0",
    "gatsby-plugin-google-tagmanager": "^4.21.0",
    "gatsby-plugin-manifest": "^4.21.0",
    "gatsby-plugin-robots-txt": "^1.7.1",
    "gatsby-plugin-s3": "^0.3.8",
    "gatsby-plugin-sass": "^5.21.0",
    "gatsby-plugin-sitemap": "^5.21.0",
    "gatsby-plugin-styled-components": "^5.21.0",
    "gatsby-source-filesystem": "^4.21.0",
    "gatsby-transformer-json": "^4.21.0",

I have noticed that over the past two weeks, when the site is created and uploaded to S3 bucket with the s3 plugin, the /page-data/sq/d/*.json is missing which causes a black screen to be shown for some users but not others! Really strange as some users on chrome/safari or iOS devices experience the black screen where as others don't!

Any idea why it is sometimes created and uploaded to /sq/d folder and sometimes it is not created?

### Reproduction Link

https://www.lucidmotors.com

### Steps to Reproduce

1. We build static site

### Expected Result

Either the *.json files in /page-data/sq/d/*.json are required and if they are they should be reliably generated on each build. If not required, it should never result in a black page after deployment

### Actual Result

Either the *.json files in /page-data/sq/d/*.json are required and if they are they should be reliably generated on each build. If not required, it should never result in a black page after deployment

### Environment

```shell
System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.11.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Safari: 16.0
  npmPackages:
    gatsby: ^4.21.1 => 4.22.0
    gatsby-cli: ^4.11.1 => 4.22.0
    gatsby-plugin-catch-links: ^4.21.0 => 4.22.0
    gatsby-plugin-google-tagmanager: ^4.21.0 => 4.22.0
    gatsby-plugin-manifest: ^4.21.0 => 4.22.0
    gatsby-plugin-robots-txt: ^1.7.1 => 1.7.1
    gatsby-plugin-s3: ^0.3.8 => 0.3.8
    gatsby-plugin-sass: ^5.21.0 => 5.22.0
    gatsby-plugin-sitemap: ^5.21.0 => 5.22.0
    gatsby-plugin-styled-components: ^5.21.0 => 5.22.0
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.27 => 1.1.27
    gatsby-source-filesystem: ^4.21.0 => 4.22.0
    gatsby-transformer-json: ^4.21.0 => 4.22.0
```

### Config Flags

None

**Comment by LekoArts** [comment] 2022-10-28 06:34
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2022-11-07 07:01
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2022-11-07 07:01 UTC
Labels: type: bug, status: needs reproduction
