### ISSUE TITLE
GraphiQL: NO SCHEMA AVAILABLE

### ISSUE THREAD

**Issue by pacocom** [gatsbyjs/gatsby#33169] opened 2021-09-14 06:39 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I can show the schema in GraphiQL

GraphiQL NO SCHEMA AVAILABLE

### Reproduction Link

No link

### Steps to Reproduce

1. gatsby develop
2. Go to http://localhost:8000/___graphql

![image](https://user-images.githubusercontent.com/7735329/133207320-58aa34e7-5187-48b5-9a8a-583754254315.png)

### Expected Result

Show the schema

### Actual Result

GraphiQL NO SCHEMA AVAILABLE
![image](https://user-images.githubusercontent.com/7735329/133207320-58aa34e7-5187-48b5-9a8a-583754254315.png)

### Environment

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.5 - C:\Python39\python.EXE
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (93.0.961.47)
  npmPackages:
    gatsby: 2.32.13 => 2.32.13
    gatsby-image: 2.4.7 => 2.4.7
    gatsby-plugin-catch-links: 2.3.5 => 2.3.5
    gatsby-plugin-manifest: 2.4.11 => 2.4.11
    gatsby-plugin-meta-redirect: 1.1.1 => 1.1.1
    gatsby-plugin-react-helmet: 3.3.4 => 3.3.4
    gatsby-plugin-remove-serviceworker: 1.0.0 => 1.0.0
    gatsby-plugin-sass: 2.3.4 => 2.3.4
    gatsby-plugin-sharp: 2.6.11 => 2.6.11
    gatsby-plugin-typescript: 2.4.6 => 2.4.6
    gatsby-plugin-uninline-styles: 0.2.0 => 0.2.0
    gatsby-remark-autolink-headers: 2.3.5 => 2.3.5
    gatsby-remark-copy-linked-files: 2.3.5 => 2.3.5
    gatsby-remark-external-links: 0.0.4 => 0.0.4
    gatsby-remark-images: 3.3.10 => 3.3.10
    gatsby-remark-link-rewrite: 0.2.1 => 0.2.1
    gatsby-remark-prismjs: 3.5.4 => 3.5.4
    gatsby-remark-relative-images: 0.3.0 => 0.3.0
    gatsby-remark-responsive-iframe: 2.4.5 => 2.4.5
    gatsby-remark-smartypants: 2.3.4 => 2.3.4
    gatsby-source-apiserver: 2.1.8 => 2.1.8
    gatsby-source-filesystem: 2.3.11 => 2.3.11
    gatsby-transformer-json: 2.4.5 => 2.4.5
    gatsby-transformer-remark: 2.8.15 => 2.8.15
    gatsby-transformer-sharp: 2.5.5 => 2.5.5
```

**Comment by TylerBarnes** [comment] 2021-09-17 21:23
Hi @pacocom !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by pragmaticpat** [comment] 2021-09-20 09:05
I also noticed this example uses Gatsby 2.32. Can this issue be reproduced in the latest version of Gatsby 3 or Gatsby 4 Beta? Thanks again!

**Comment by LekoArts** [comment] 2021-10-04 11:42
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-10-04 11:42 UTC
Labels: status: needs reproduction
