### ISSUE TITLE
Add PR check for release notes / semantic releases

### ISSUE THREAD

**Issue by m-allanson** [gatsbyjs/gatsby#7625] opened 2018-08-24 18:36 UTC
To make it easier to create release notes (CHANGELOG.md) we want to explore using commit conventions that allow us to automate this.

Per the discussion in https://github.com/gatsbyjs/gatsby/issues/3920, we want to:

1. Use [this bot](https://github.com/probot/semantic-pull-requests) for enforcing semantic titles for PRs
2. Use _only_ squash merges so the PR title is used as the commit message
3. Add zero restrictions to contributors — they can add any commit messages they want, because the only thing that hits the CHANGELOG is the squash commit
4. Post a message for all maintainers explaining the commit format and rationale

By doing this we get the following benefits:

1. Changelogs will be automatically generated by Lerna
2. No one ever needs to read through hundreds of commits to manually pull out what's changed

Related PR https://github.com/gatsbyjs/gatsby/pull/2198

**Comment by marisamorby** [comment] 2018-08-31 06:26
We made a note in the  meeting today to research release notes a bit more before moving forward

It looks like Lerna already does what we need it to do. We just need to figure out how to make sure that PRs have the right format so we can enforce it.

**Comment by mikelax** [comment] 2018-09-20 12:18
Hi all, this is an issue that I would be interested in helping out with. I have a few questions that I have been thinking about related to this feature: 

- Should the changelog exist just within Github as a large Changelog file at the root of repo? Should each package have it's own Changelog file? 
- Should a "simple view" changelog exist on the www.gatsby.org website that would detail larger features rather than every single PR
- Is the idea to use [lerna-changelog](https://github.com/lerna/lerna-changelog) to generate the (Github) changelog automatically?
  - If so, I was thinking that we could add a new top-level label called `changelog`. Then add labels such as `changelog:bug`, `changelog:breaking`, `changelog:internal`, etc, whichever we decide we want to support. 
  - We can add a danger.js script to ensure that every PR has one and only one of these changelog labels added.

**Comment by jlengstorf** [comment] 2018-09-20 23:01
Hey, @mikelax — as of right now, I think our goals are to:

1. Use Lerna's changelog to automatically generate
2. Enforce a semantic commit message as a PR title and use squash and merge only
3. Potentially use https://github.com/probot/semantic-pull-requests to enforce this

As a first step, I think that's as far as we want to go. If it works well, we can look at expanding the checks a bit. @pieh can you confirm that this is what we agreed on for an initial scope?

**Comment by pieh** [comment] 2018-09-21 10:15
> 1. Use Lerna's changelog to automatically generate

This part we already do - this is example commit that lerna generates with changelog updates pulled from semantic commit messages https://github.com/gatsbyjs/gatsby/commit/96359acdc7649360545e661cc0f84da7405af884

But we don't enforce commit messages / PR titles yet, so most of changelog updates are "Note: Version bump only for package X"

I think it's low risk to test that bot if we start using that without requiring check from it for tests to pass - I would think we don't want to force that on PRs that add entries to showcases or doc changes on website

**Comment by jlengstorf** [comment] 2018-09-21 14:36
@pieh The title would need to be edited by the maintainer merging the PR, so I don't know that it's a big deal to add those checks everywhere.

For things like docs, changes, there's a `docs` prefix:

```
docs: add example.org to the site showcase
```

Or we could call those chores:

```
chore: add example.org to the site showcase
```

The [full list](https://github.com/marionebl/commitlint/tree/master/%40commitlint/config-conventional#type-enum) covers most use cases, and if we decide there are edge cases for Gatsby, we can extend the config to include additional types.

**Comment by mikelax** [comment] 2018-09-21 15:00
@jlengstorf  I do like the looks of the [probot semantic pull requests](https://github.com/probot/semantic-pull-requests). Maybe as a first pass give it a try on a smaller repo like the gatsby store that has lower volume? 

It will require the maintainer, or person who merges to ensure the PR message works. To try and offload some of the work this could be mentioned in the pull request template.

**Comment by jlengstorf** [comment] 2018-09-21 15:43
Yeah, I think that's the plan. Since it's pretty clear how to pass that check, and since our maintainers are a small enough group that we can post a message explaining the change, I _think_ we're planning to put it on the gatsbyjs/gatsby repo to see how it goes. @pieh has final authority on that decision, but I believe that's what we talked about previously.

**Comment by jquense** [comment] 2018-09-21 21:02
I think I noted this in the last thread, but I'm 👎 on this since it adds a level another contribution barrier for folks. I like that the merger (maintainer) can fix it but to the PR author the check is gonna r ad as something they have to do. I ama fan of coventional commits in general tho!

**Comment by jlengstorf** [comment] 2018-09-21 21:09
@jquense This is a pretty simple thing to implement, so the cost to experiment is low. If we see a lot of confusion or a drop in contributions, we'll definitely back it out. The alternative is expecting anyone merging a PR to follow a checklist that they'll have to remember to pull up (or I guess Peril could auto-post that comment every time... 🤔), which seems like a more cumbersome approach.

**Comment by hsribei** [comment] 2018-09-21 22:47
Do squash merges preserve commit authorship?

**Comment by jlengstorf** [comment] 2018-09-21 23:00
@hsribei Yep! The author of the first commit gets credit for it. There's an edge case where multiple people commit to the same PR and the second committer would lose credit, but that's pretty rare.

**Comment by jlengstorf** [comment] 2018-09-21 23:01
Example: https://github.com/gatsbyjs/gatsby/commit/a56bce36662eb3ab250ec32823c703b184c04d6c

**Comment by hsribei** [comment] 2018-09-21 23:19
Nice! Thanks for clearing that up :)

**Comment by pieh** [comment] 2018-09-24 14:59
today I started just manually editing merge commit message and found out that (didn't pay attention to it earlier):

PR title will be used for merge commit only if there is more than 1 commit in PR (otherwise it will straight use commit message), so checking PR titles for those can result in some "false positives" (which might be worse than not having that at all?)

**Comment by jlengstorf** [comment] 2018-09-25 00:36
@pieh wait, really?

Yeah, if that's the case this is completely useless.

**Comment by jlengstorf** [comment] 2018-09-25 00:41
@pieh I just confirmed that the squash merge message is used, even for single commits:

- Original commit: https://github.com/jlengstorf/presentations/pull/7/commits/f47fdf87208fdfe680d0fda4d7cf4ae84cff636d
- Pull request: https://github.com/jlengstorf/presentations/pull/7
- Squash commit message: https://github.com/jlengstorf/presentations/commit/063da9fe538758d43053779f15fa26230c7bdf07

**Comment by pieh** [comment] 2018-09-25 00:50
Yes, squash merge message is used (I should be more clear on that), but proposed message before confirming the merge is not PR title when merging PR if there is single commit - so checking PR title in those situations doesn't provide much value because it won't be used automatically.

**Comment by jlengstorf** [comment] 2018-09-25 01:19
Ugh. Yep. Okay, then. This seems like a non-starter.

Instead, let's do this:

1. I'll close this and shut up about it
2. Core maintainers will use squash and merge exclusively (this is already set up in the repo)
3. We all agree to use conventional commits when squash merging so that Lerna builds changelogs automatically
4. We do manual reviews of PRs that we didn't merge to update the changelogs as needed

It's not perfect, but I do agree that an imperfect manual system is better than an automated system that will block or confuse contributors.

**Closed by jlengstorf** 2018-09-25 01:19 UTC
Labels: 🎯 Developer Relations
