### ISSUE TITLE
hot reloading doesn't work on non-default browsers

### ISSUE THREAD

**Issue by wangsongiam** [gatsbyjs/gatsby#969] opened 2017-05-15 20:24 UTC
hi, I am currently working by`gatsby develop` with Google Chrome,  yet haven't seen it reloaded so far, nor on Safari. (Google Canary is currently my default browser)

here is the error log on Google Chrome
```
XMLHttpRequest cannot load http://0.0.0.0:8000/1c9bc2416f0c7bf8b55b.hot-update.json. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.
bundle.js:81781 [HMR] Update check failed: Error: Manifest request to http://0.0.0.0:8000/1c9bc2416f0c7bf8b55b.hot-update.json timed out.
    at XMLHttpRequest.request.onreadystatechange (http://localhost:8000/bundle.js?t=1494792522428:34:23)
```

**Comment by michaeljdeeb** [comment] 2017-05-15 20:47
This is a duplicate of #864, the current work around is to access gatsby from the exact URL given by `gatsby develop`. This can be changed to localhost using the `-H` or `--host` flag.

**Comment by wangsongiam** [comment] 2017-05-15 21:10
@michaeljdeeb Thanks a lot!

**Comment by KyleAMathews** [comment] 2017-05-20 14:22
Fixed by https://github.com/gatsbyjs/gatsby/commit/7cd0afb0365299022e464e300a21f344b3e8d2cd

**Closed** 2017-05-20 14:22 UTC
