### ISSUE TITLE
🐞[gatsby-transformer-remark] Link with double underscore doesn't work

### ISSUE THREAD

**Issue by MichaelDeBoey** [gatsbyjs/gatsby#14715] opened 2019-06-11 21:44 UTC
## Description
When converting all of @CompuIves' [Medium posts](https://medium.com/@CompuIves/latest) over to @codesandbox' blog (see codesandbox/codesandbox-client#2011), I came across a bug when a link contains 2 underscores (`_`).

When I try to include the following Tweet-link, I just see the link with an italic `d` instead of the `d` between an underscore on both sides:
```md
https://twitter.com/brian_d_vaughn/status/901488766581227520
```

I first thought it had something to do with @kentcdodds' `remark-embed` plugin, but [it didn't](https://github.com/kentcdodds/kentcdodds.com/issues/191#issuecomment-499179350).

After further investigation, I was able to reproduce it by taking the `using-remark` example and creating a file with just the link in it.

### Steps to reproduce
[CodeSandbox link](https://codesandbox.io/s/gatsby-example-using-remark-ljwmj?fontsize=14&module=%2Fsrc%2Fpages%2F2019-02-06---bug-when-having-double-underscores%2Findex.md)

### Expected result
The user should see the correct link without an italic `d` that's  inbetween 2  underscores (`_`).

```
https://twitter.com/brian_d_vaughn/status/901488766581227520
```

### Actual result
The user sees an incorrect  link with an italic `d` that's not inbetween 2 underscores (`_`).

```
https://twitter.com/briandvaughn/status/901488766581227520
```

**Comment by sidharthachatterjee** [comment] 2019-06-17 21:34
While I _can_ reproduce this, I'm not sure if I would call this a bug. It looks like this is simply a side effect of the Markdown syntax. 

An easy work around for this would be to escape the underscore so the link above would look like `https://twitter.com/brian\_d\_vaughn/status/901488766581227520`

**Comment by sidharthachatterjee** [comment] 2019-06-17 22:18
Okay, I did a little more digging. This behaviour is documented in remark as `pedantic` mode (https://github.com/remarkjs/remark/blob/master/packages/remark-parse/readme.md#optionspedantic)

From the README linked above

> Emphasis (_alpha_) and importance (__bravo__) with underscores in words

`gatsby-transformer-remark` sets `pedantic` to `true` by default. Setting it to false in options should get rid of this behaviour (screenshot below). 

```
{
  resolve: `gatsby-transformer-remark`,
  options: {
    pedantic: false,
  },
},
```

![Screenshot 2019-06-18 03 48 19](https://user-images.githubusercontent.com/7701981/59640508-e9248380-917b-11e9-9855-06a8c82b3072.png)

Closing this for now but feel free to reopen if there's anything else here that we can help with

**Closed by sidharthachatterjee** 2019-06-17 22:18 UTC
Labels: type: question or discussion

**Comment by MichaelDeBoey** [comment] 2019-06-17 22:20
@sidharthachatterjee Like you can see in @kentcdodds' comment (https://github.com/kentcdodds/kentcdodds.com/issues/191#issuecomment-499179350), this doesn't happen when using the RAW Markdown and [passing it to the `MDXRenderer`](https://github.com/kentcdodds/kentcdodds.com/blob/master/src/templates/post.js#L139).

**Comment by MichaelDeBoey** [comment] 2019-06-17 22:24
Awesome you've looked deeper into this one @sidharthachatterjee! 👊

This looks likes it indeed fixes my problem, thanks! 🙂

**Comment by edsu** [comment] 2021-07-29 15:05
I'm just noting here that escaping with `\` does not seem to fix the problem when the text is inside a link.
