### ISSUE TITLE
Home page flashes after reload page using client-only routes

### ISSUE THREAD

**Issue by rstolarczykpp** [gatsbyjs/gatsby#37340] opened 2022-12-28 09:47 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hello,

When I use client-only routes like [page].jsx I see homepage for a second then correct page, why am I seeing this homepage? I've done this page like in documentation https://www.gatsbyjs.com/docs/reference/routing/file-system-route-api/#creating-client-only-routes 

### Reproduction Link

https://www.gatsbyjs.com/docs/reference/routing/file-system-route-api/#creating-client-only-routes

### Steps to Reproduce

1. Create Homepage
2. Create [page].jsx
3. Enter [page].jsx
4. Homepage flashes for a second and then render correct page
...

### Expected Result

When I enter [page].jsx I see it immediately 

### Actual Result

Homepage flashes for a second and then render correct page

### Environment

```shell
Using "gatsby": "^4.22.0",
```

**Comment by tyhopp** [comment] 2023-01-03 04:26
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2023-01-17 14:30
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2023-01-17 14:30 UTC
Labels: type: bug, status: needs reproduction
