### ISSUE TITLE
GraphQL Filter Problem: Deep data structure causing return of erroneous items?

### ISSUE THREAD

**Issue by 74yearoldsocialist** [gatsbyjs/gatsby#32912] opened 2021-08-25 21:31 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I have been using the VSCode JSON editor Depot, which is very beautiful but forces a lot of metadata onto the file and thus grows the tree. This has left me with a rather unwieldy data structure that GraphQL appears not to be able to handle.

In the example below, the only items I expect to be returned are those "list2_list1" lists that contain "list2_list1_item": "list2_list1_item1". Instead, *all* "list2_list1" lists are returned.

JSON file:
```
{
	"list1": [{
			"metadata_item": "Metadata_item",
			"metadata_list": [{
					"metadata_list_item": "metadata_list_item1",
					"metadata_list_list": {
						"metadata_list_list_item": "metadata_list_list_item1"
					}
				},
				{
					"metadata_list_item": "metadata_list_item2",
					"metadata_list_list": {
						"metadata_list_list_item": "metadata_list_list_item2"
					}
				}
			],
			"list2": [{
					"list2_item": "list2_item1",
					"list2_list1": [{
						"list2_list1_item": "list2_list1_item1"
					}],
					"list2_list2": [{
						"list2_list2_item": "list2_list2_item1"
					}]
				},
				{
					"list2_item": "list2_item2",
					"list2_list1": [{
						"list2_list1_item": "list2_list1_item2"
					}],
					"list2_list2": [{
						"list2_list2_item": "list2_list2_item2"
					}]
				},
				{
					"list2_item": "list2_item3",
					"list2_list1": [{
						"list2_list1_item": "list2_list1_item3"
					}],
					"list2_list2": [{
						"list2_list2_item": "list2_list2_item3"
					}]
				}
			]
		},
		{
			"more_metadata_item": "more_metadata_item1",
			"more_metadata_list": [{
					"more_metadata_list_item": "more_metadata_list_item1"
				},
				{
					"more_metadata_list_item": "more_metadata_list_item2"
				}
			]
		}
	]
}

```

GraphQL Query:
```
query MyQuery {
  allSrcJson(
    filter: {list1: {elemMatch: {list2: {elemMatch: {list2_list1: {elemMatch: {list2_list1_item: {eq: "list2_list1_item1"}}}}}}}}
  ) {
    edges {
      node {
        list1 {
          list2 {
            list2_list1 {
              list2_list1_item
            }
          }
        }
      }
    }
  }
}
```

GraphQL Outcome:
```
{
  "data": {
    "allSrcJson": {
      "edges": [
        {
          "node": {
            "list1": [
              {
                "list2": [
                  {
                    "list2_list1": [
                      {
                        "list2_list1_item": "list2_list1_item1"
                      }
                    ]
                  },
                  {
                    "list2_list1": [
                      {
                        "list2_list1_item": "list2_list1_item2"
                      }
                    ]
                  },
                  {
                    "list2_list1": [
                      {
                        "list2_list1_item": "list2_list1_item3"
                      }
                    ]
                  }
                ]
              },
              {
                "list2": null
              }
            ]
          }
        }
      ]
    }
  },
  "extensions": {}
}
```

### Reproduction Link

https://example.com/example

### Steps to Reproduce

Try to use a GraphQL query against JSON with nested arrays.

### Expected Result

The only items I expect to be returned are those "list2_list1" lists that contain "list2_list1_item": "list2_list1_item1".

### Actual Result

Instead, *all* "list2_list1" lists are returned.

### Environment

```shell
System:
    OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.17.5 - ~/.nvm/versions/node/v14.17.5/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v14.17.5/bin/yarn
    npm: 7.21.0 - ~/.nvm/versions/node/v14.17.5/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 92.0.4515.159
    Firefox: 91.0.1
  npmPackages:
    gatsby: ^3.11.1 => 3.12.0
    gatsby-node-helpers: ^1.2.1 => 1.2.1
    gatsby-plugin-styled-components: ^4.12.0 => 4.12.0
    gatsby-source-filesystem: ^3.12.0 => 3.12.0
    gatsby-source-google-spreadsheets: ^3.0.8 => 3.0.8
    gatsby-transformer-json: ^3.12.0 => 3.12.0
  npmGlobalPackages:
    gatsby-cli: 3.12.0
```

**Comment by graysonhicks** [comment] 2021-08-31 23:57
Hi @74yearoldsocialist can you make a minimal reproduction of this somewhere for debugging?

**Comment by vladar** [comment] 2021-09-01 11:30
This is not a bug. It mimics the [same behavior](https://docs.mongodb.com/manual/reference/operator/query/elemMatch/) of MongoDB:

> The `$elemMatch` operator matches documents that contain an array field with at least one element that matches all the specified query criteria.

As you can see - it doesn't _filter_ nested structures - it just filters the top-level documents if at least one element matches the criteria. Your `list2` does have one element that matches the criteria:

```
{
  "list2_list1": [
    {
      "list2_list1_item": "list2_list1_item1"
    }
  ]
}
```

So the top-level document is included in query results. But nested structures won't be filtered. You can try the same data and query with MongoDB and the result will be the same.

**Comment by vladar** [comment] 2021-09-01 11:37
Also a duplicate of #24008

**Closed by vladar** 2021-09-01 11:37 UTC
Labels: type: bug, type: question or discussion, status: triage needed
