### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by michaelfedorov-realcommerce** [gatsbyjs/gatsby#33650] opened 2021-10-24 08:51 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi, I use i my project plugin 'gatsby-source-wordpress' when I run build get error.
In gatsby v4 have the same problem.
How can I resolve the issue ?

### Reproduction Link

https://gatsby.dev/reproduction

### Steps to Reproduce

1. gatsby clean
2. gatsby build

### Expected Result

```shell
warn Warning: there are unknown plugin options for "gatsby-source-wordpress": options
Please open an issue at ghub.io/gatsby-source-wordpress if you believe this option is valid.
success open and validate gatsby-configs, load plugins - 0.540s
success onPreInit - 0.002s
success initialize cache - 0.033s
success copy gatsby files - 0.037s
success Compiling Gatsby Functions - 0.131s
success onPreBootstrap - 0.136s
success  gatsby-source-wordpress  ensuring plugin requirements are met - 1.447s
warn Warning: there are unknown plugin options for "gatsby-source-wordpress": options
Please open an issue at ghub.io/gatsby-source-wordpress if you believe this option is valid.
warn Warning: there are unknown plugin options for "gatsby-source-wordpress": options
Please open an issue at ghub.io/gatsby-source-wordpress if you believe this option is valid.
⠀
info  gatsby-source-wordpress 

        This is either your first build or the cache was cleared.
        Please wait while your WordPress data is synced to your Gatsby cache.

        Maybe now's a good time to get up and stretch? :D

warn Warning: there are unknown plugin options for "gatsby-source-wordpress": options
Please open an issue at ghub.io/gatsby-source-wordpress if you believe this option is valid.
warn Warning: there are unknown plugin options for "gatsby-source-wordpress": options
Please open an issue at ghub.io/gatsby-source-wordpress if you believe this option is valid.
warn Warning: there are unknown plugin options for "gatsby-source-wordpress": options
Please open an issue at ghub.io/gatsby-source-wordpress if you believe this option is valid.
warn Warning: there are unknown plugin options for "gatsby-source-wordpress": options
Please open an issue at ghub.io/gatsby-source-wordpress if you believe this option is valid.
warn Warning: there are unknown plugin options for "gatsby-source-wordpress": options
Please open an issue at ghub.io/gatsby-source-wordpress if you believe this option is valid.
warn  gatsby-source-wordpress  Unable to find a single Node query for PaymentGateway
        This type will not be available in Gatsby.

success  gatsby-source-wordpress  ingest WPGraphQL schema - 3.402s
success createSchemaCustomization - 4.901s
success  gatsby-source-wordpress  PostFormat - 2.337s - fetched 0
success  gatsby-source-wordpress  Comment - 2.382s - fetched 1
success  gatsby-source-wordpress  Menu - 2.376s - fetched 4
success  gatsby-source-wordpress  Order - 2.492s - fetched 0
success  gatsby-source-wordpress  Category - 2.607s - fetched 1
success  gatsby-source-wordpress  Coupon - 4.106s - fetched 0
success  gatsby-source-wordpress  Customer - 4.116s - fetched 0
success  gatsby-source-wordpress  GlobalProductAddon - 4.413s - fetched 1
success  gatsby-source-wordpress  MenuItem - 4.486s - fetched 21
success  gatsby-source-wordpress  Page - 5.642s - fetched 14
success  gatsby-source-wordpress  ContentType - 6.014s - fetched 6
success  gatsby-source-wordpress  Event - 8.803s - fetched 6
success  gatsby-source-wordpress  MediaItems - 5.299s - fetched 0
success  gatsby-source-wordpress  fetch root fields - 9.965s
success  gatsby-source-wordpress  PaShape - 17.949s - fetched 7
success  gatsby-source-wordpress  PaSize - 20.844s - fetched 4
success  gatsby-source-wordpress  UserRole - 1.687s - fetched 0
success  gatsby-source-wordpress  Taxonomy - 1.944s - fetched 7
success  gatsby-source-wordpress  Tag - 1.977s - fetched 0
success  gatsby-source-wordpress  ShippingClass - 2.001s - fetched 0
success  gatsby-source-wordpress  ShippingMethod - 2.097s - fetched 3
success  gatsby-source-wordpress  TaxRate - 2.150s - fetched 0
success  gatsby-source-wordpress  Refund - 3.206s - fetched 0
success  gatsby-source-wordpress  User - 3.951s - fetched 1
success  gatsby-source-wordpress  Work - 4.032s - fetched 3
success  gatsby-source-wordpress  VisibleProduct - 4.328s - fetched 9
success  gatsby-source-wordpress  Post - 4.748s - fetched 13
success  gatsby-source-wordpress  ProductType - 5.430s - fetched 4
success  gatsby-source-wordpress  ProductTag - 5.665s - fetched 18
success  gatsby-source-wordpress  ProductCategory - 10.686s - fetched 11
success  gatsby-source-wordpress  Product - 34.482s - fetched 20
success  gatsby-source-wordpress  MediaItem - 10.003s - fetched 74
success  gatsby-source-wordpress  creating nodes - 10.013s
success  gatsby-source-wordpress  fetching nodes - 65.404s - 228 total
success Downloading remote files - 57.361s - 119/119 2.07/s
success Checking for changed pages - 0.000s
success source and transform nodes - 65.564s
⠋ building schema

 **ERROR 

Maximum call stack size exceeded



  RangeError: Maximum call stack size exceeded**
  
  - Function.keys
  
  - misc.js:93 inspectObject
    [3d-innovation-gatsby-cloud]/[graphql-compose]/lib/utils/misc.js:93:29
  
  - misc.js:102 inspect
    [3d-innovation-gatsby-cloud]/[graphql-compose]/lib/utils/misc.js:102:165
  
  - misc.js:93 
    [3d-innovation-gatsby-cloud]/[graphql-compose]/lib/utils/misc.js:93:59
  
  - Array.map
  
  - misc.js:93 inspectObject
    [3d-innovation-gatsby-cloud]/[graphql-compose]/lib/utils/misc.js:93:41
  
  - misc.js:102 inspect
    [3d-innovation-gatsby-cloud]/[graphql-compose]/lib/utils/misc.js:102:165
  
  - misc.js:93 
    [3d-innovation-gatsby-cloud]/[graphql-compose]/lib/utils/misc.js:93:59
  
  - Array.map
  
  - misc.js:93 inspectObject
    [3d-innovation-gatsby-cloud]/[graphql-compose]/lib/utils/misc.js:93:41
  
  - misc.js:102 inspect
    [3d-innovation-gatsby-cloud]/[graphql-compose]/lib/utils/misc.js:102:165
  
  - misc.js:93 
    [3d-innovation-gatsby-cloud]/[graphql-compose]/lib/utils/misc.js:93:59
  
  - Array.map
  
  - misc.js:93 inspectObject
    [3d-innovation-gatsby-cloud]/[graphql-compose]/lib/utils/misc.js:93:41
  
  - misc.js:102 inspect
    [3d-innovation-gatsby-cloud]/[graphql-compose]/lib/utils/misc.js:102:165
  
  - misc.js:93 
    [3d-innovation-gatsby-cloud]/[graphql-compose]/lib/utils/misc.js:93:59
  

not finished building schema - 0.166s
```

### Actual Result

```shell
warn Warning: there are unknown plugin options for "gatsby-source-wordpress": options
Please open an issue at ghub.io/gatsby-source-wordpress if you believe this option is valid.
success open and validate gatsby-configs, load plugins - 0.540s
success onPreInit - 0.002s
success initialize cache - 0.033s
success copy gatsby files - 0.037s
success Compiling Gatsby Functions - 0.131s
success onPreBootstrap - 0.136s
success  gatsby-source-wordpress  ensuring plugin requirements are met - 1.447s
warn Warning: there are unknown plugin options for "gatsby-source-wordpress": options
Please open an issue at ghub.io/gatsby-source-wordpress if you believe this option is valid.
warn Warning: there are unknown plugin options for "gatsby-source-wordpress": options
Please open an issue at ghub.io/gatsby-source-wordpress if you believe this option is valid.
⠀
info  gatsby-source-wordpress 

        This is either your first build or the cache was cleared.
        Please wait while your WordPress data is synced to your Gatsby cache.

        Maybe now's a good time to get up and stretch? :D

warn Warning: there are unknown plugin options for "gatsby-source-wordpress": options
Please open an issue at ghub.io/gatsby-source-wordpress if you believe this option is valid.
warn Warning: there are unknown plugin options for "gatsby-source-wordpress": options
Please open an issue at ghub.io/gatsby-source-wordpress if you believe this option is valid.
warn Warning: there are unknown plugin options for "gatsby-source-wordpress": options
Please open an issue at ghub.io/gatsby-source-wordpress if you believe this option is valid.
warn Warning: there are unknown plugin options for "gatsby-source-wordpress": options
Please open an issue at ghub.io/gatsby-source-wordpress if you believe this option is valid.
warn Warning: there are unknown plugin options for "gatsby-source-wordpress": options
Please open an issue at ghub.io/gatsby-source-wordpress if you believe this option is valid.
warn  gatsby-source-wordpress  Unable to find a single Node query for PaymentGateway
        This type will not be available in Gatsby.

success  gatsby-source-wordpress  ingest WPGraphQL schema - 3.402s
success createSchemaCustomization - 4.901s
success  gatsby-source-wordpress  PostFormat - 2.337s - fetched 0
success  gatsby-source-wordpress  Comment - 2.382s - fetched 1
success  gatsby-source-wordpress  Menu - 2.376s - fetched 4
success  gatsby-source-wordpress  Order - 2.492s - fetched 0
success  gatsby-source-wordpress  Category - 2.607s - fetched 1
success  gatsby-source-wordpress  Coupon - 4.106s - fetched 0
success  gatsby-source-wordpress  Customer - 4.116s - fetched 0
success  gatsby-source-wordpress  GlobalProductAddon - 4.413s - fetched 1
success  gatsby-source-wordpress  MenuItem - 4.486s - fetched 21
success  gatsby-source-wordpress  Page - 5.642s - fetched 14
success  gatsby-source-wordpress  ContentType - 6.014s - fetched 6
success  gatsby-source-wordpress  Event - 8.803s - fetched 6
success  gatsby-source-wordpress  MediaItems - 5.299s - fetched 0
success  gatsby-source-wordpress  fetch root fields - 9.965s
success  gatsby-source-wordpress  PaShape - 17.949s - fetched 7
success  gatsby-source-wordpress  PaSize - 20.844s - fetched 4
success  gatsby-source-wordpress  UserRole - 1.687s - fetched 0
success  gatsby-source-wordpress  Taxonomy - 1.944s - fetched 7
success  gatsby-source-wordpress  Tag - 1.977s - fetched 0
success  gatsby-source-wordpress  ShippingClass - 2.001s - fetched 0
success  gatsby-source-wordpress  ShippingMethod - 2.097s - fetched 3
success  gatsby-source-wordpress  TaxRate - 2.150s - fetched 0
success  gatsby-source-wordpress  Refund - 3.206s - fetched 0
success  gatsby-source-wordpress  User - 3.951s - fetched 1
success  gatsby-source-wordpress  Work - 4.032s - fetched 3
success  gatsby-source-wordpress  VisibleProduct - 4.328s - fetched 9
success  gatsby-source-wordpress  Post - 4.748s - fetched 13
success  gatsby-source-wordpress  ProductType - 5.430s - fetched 4
success  gatsby-source-wordpress  ProductTag - 5.665s - fetched 18
success  gatsby-source-wordpress  ProductCategory - 10.686s - fetched 11
success  gatsby-source-wordpress  Product - 34.482s - fetched 20
success  gatsby-source-wordpress  MediaItem - 10.003s - fetched 74
success  gatsby-source-wordpress  creating nodes - 10.013s
success  gatsby-source-wordpress  fetching nodes - 65.404s - 228 total
success Downloading remote files - 57.361s - 119/119 2.07/s
success Checking for changed pages - 0.000s
success source and transform nodes - 65.564s
⠋ building schema

 **ERROR 

Maximum call stack size exceeded



  RangeError: Maximum call stack size exceeded**
  
  - Function.keys
  
  - misc.js:93 inspectObject
    [3d-innovation-gatsby-cloud]/[graphql-compose]/lib/utils/misc.js:93:29
  
  - misc.js:102 inspect
    [3d-innovation-gatsby-cloud]/[graphql-compose]/lib/utils/misc.js:102:165
  
  - misc.js:93 
    [3d-innovation-gatsby-cloud]/[graphql-compose]/lib/utils/misc.js:93:59
  
  - Array.map
  
  - misc.js:93 inspectObject
    [3d-innovation-gatsby-cloud]/[graphql-compose]/lib/utils/misc.js:93:41
  
  - misc.js:102 inspect
    [3d-innovation-gatsby-cloud]/[graphql-compose]/lib/utils/misc.js:102:165
  
  - misc.js:93 
    [3d-innovation-gatsby-cloud]/[graphql-compose]/lib/utils/misc.js:93:59
  
  - Array.map
  
  - misc.js:93 inspectObject
    [3d-innovation-gatsby-cloud]/[graphql-compose]/lib/utils/misc.js:93:41
  
  - misc.js:102 inspect
    [3d-innovation-gatsby-cloud]/[graphql-compose]/lib/utils/misc.js:102:165
  
  - misc.js:93 
    [3d-innovation-gatsby-cloud]/[graphql-compose]/lib/utils/misc.js:93:59
  
  - Array.map
  
  - misc.js:93 inspectObject
    [3d-innovation-gatsby-cloud]/[graphql-compose]/lib/utils/misc.js:93:41
  
  - misc.js:102 inspect
    [3d-innovation-gatsby-cloud]/[graphql-compose]/lib/utils/misc.js:102:165
  
  - misc.js:93 
    [3d-innovation-gatsby-cloud]/[graphql-compose]/lib/utils/misc.js:93:59
  

not finished building schema - 0.166s
```

### Environment

```shell
System:
    OS: macOS 11.5.2
    CPU: (8) arm64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.9.0 - /opt/homebrew/bin/node
    npm: 7.5.3 - /opt/homebrew/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 95.0.4638.54
    Safari: 14.1.2
  npmPackages:
    gatsby: ^2.32.3 => 4.0.0
    gatsby-image: ^2.11.0 => 2.11.0
    gatsby-plugin-facebook-sdk: ^1.0.6 => 1.0.6
    gatsby-plugin-google-gapi: ^0.0.11 => 0.0.11
    gatsby-plugin-manifest: ^2.12.0 => 4.0.0
    gatsby-plugin-offline: ^3.10.0 => 5.0.0
    gatsby-plugin-react-helmet: ^3.10.0 => 5.0.0
    gatsby-plugin-sharp: ^2.14.1 => 4.0.0
    gatsby-source-filesystem: ^2.11.0 => 4.0.0
    gatsby-source-googlemaps-geocoding: ^1.0.0 => 1.0.0
    gatsby-source-wordpress: ^4.0.1 => 6.0.0
    gatsby-transformer-sharp: ^2.12.0 => 4.0.0
  npmGlobalPackages:
    gatsby-cli: 3.2.0
```

**Comment by Bruce-Hopkins-Jr** [comment] 2021-11-02 10:57
Hi!

I need a reproduction link to a Github repo and/or live demo of your site to further assist you. Without it, I can't reproduce the bug.

**Comment by bogdancss** [comment] 2021-11-03 11:23
happening on our instance as well - all of sudden, as of yesterday are getting this. Tried a clean installation, tried locally as well as on Gatsby Cloud - same error.

**Comment by LekoArts** [comment] 2021-11-08 10:12
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-11-08 10:12 UTC
Labels: type: bug, status: needs reproduction
