### ISSUE TITLE
onRenderBody in gatsby-ssr apis doesn't work as expected

### ISSUE THREAD

**Issue by BagchiMB** [gatsbyjs/gatsby#25587] opened 2020-07-08 01:51 UTC
## Description

Initially my problem was that my og meta tags weren't being fetched by the sharing debbuger or the twitter card validator, therefore I searched various issues on github I found out that the major reason was the chunk of css that were present before my tags then I got to know about onRenderBody function in gatsby-ssr API, I tried implementing it but I couldn't succeed. I hope I have not made any silly mistakes and most probably this is a bug.
My onRenderBody function fails silently with no warnings and error.

### Steps to reproduce

Here's my gatsby-ssr.js
```
// import "./src/styles/_global.scss"

const React = require("react")
const { Helmet } = require("react-helmet")

// import React from 'react'
// import Helmet from 'react-helmet'

exports.onRenderBody = (
  { setHeadComponents, setHtmlAttributes, setBodyAttributes },
  pluginOptions
) => {
  const helmet = Helmet.renderStatic()
  setHtmlAttributes(helmet.htmlAttributes.toComponent())
  setBodyAttributes(helmet.bodyAttributes.toComponent())
  setHeadComponents([
    helmet.title.toComponent(),
    helmet.link.toComponent(),
    helmet.meta.toComponent(),
    helmet.noscript.toComponent(),
    helmet.script.toComponent(),
    helmet.style.toComponent(),
  ])
}

exports.onPreRenderHTML = ({ getHeadComponents, replaceHeadComponents }) => {
  const headComponents = getHeadComponents()

  headComponents.sort((x, y) => {
    if (x.props && x.props["data-react-helmet"]) {
      return -1
    } else if (y.props && y.props["data-react-helmet"]) {
      return 1
    }
    return 0
  })

  replaceHeadComponents(headComponents)
}

// export { default as wrapRootElement } from './src/store/ReduxWrapper';
exports.wrapRootElement = require('./src/store/ReduxWrapper')
```

Here's my gatsby-config.js

```
module.exports = {
  /* Your site config here */
  siteMetadata: {
    title: "India’s Trusted Private Jet Lifestyle Services | Business Air Charter",
    description: "Experience the most exclusive aeroplane rental services and dedicated lifestyle concierge. Book your private jets and helicopters in minutes at best prices.",
    author: "@Ferofly",
    twitterUsername: "@FeroflyIndia",
    image: "/fero-logo-2.png",
    siteUrl: "https://www.ferofly.com",
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-sass`,
    `gatsby-plugin-material-ui`,
    {
      resolve: `gatsby-plugin-favicon`,
      options: {
        logo: "./src/assets/iconsmall2.png",
  
        // WebApp Manifest Configuration
        appName: 'ferofly', // Inferred with your package.json
        appDescription: "Experience the most exclusive aeroplane rental services and dedicated lifestyle concierge. Book your private jets and helicopters in minutes at best prices.",
        developerName: 'Mihir Bagchi',
        developerURL: 'https://mihirbagchi.com',
        dir: 'auto',
        lang: 'en-US',
        background: '#cdab82',
        theme_color: '#cdab82',
        display: 'standalone',
        orientation: 'any',
        start_url: '/?homescreen=1',
        version: '1.0',
  
        icons: {
          android: true,
          appleIcon: true,
          appleStartup: true,
          coast: false,
          favicons: true,
          firefox: true,
          yandex: false,
          windows: false
        }
      }
    },
    {
      resolve: `gatsby-plugin-gtag`,
      options: {
        trackingId: `UA-164667005-2`,
        head: true,
        anonymize: false,
      },
    },
  ],

}
```

Here's my html.js if relevant
```
import React from "react"
import PropTypes from "prop-types"

export default function HTML(props) {
  return (
    <html {...props.htmlAttributes}>
      <head>
        <meta charSet="utf-8" />
        <meta httpEquiv="x-ua-compatible" content="ie=edge" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        {props.headComponents}
        {/*<script src="https://account.snatchbot.me/script.js"></script>
         <script>window.sntchChat.Init(115XXX)</script>*/}
      </head>
      <body {...props.bodyAttributes}>
        {props.preBodyComponents}
        <div
          key={`body`}
          id="___gatsby"
          dangerouslySetInnerHTML={{ __html: props.body }}
        />
        {props.postBodyComponents}
      </body>
    </html>
  )
}

HTML.propTypes = {
  htmlAttributes: PropTypes.object,
  headComponents: PropTypes.array,
  bodyAttributes: PropTypes.object,
  preBodyComponents: PropTypes.array,
  body: PropTypes.string,
  postBodyComponents: PropTypes.array,
}
```
### Expected result

Styles should load after my meta tags.

### Actual result

Styles are loading before my meta tags.
### See the vertical scroll section of vs code most of the above section is filled with styles, infact my og meta tags are the last ones, before my body starts
[![Foo](https://i.imgur.com/70is1Lq.png)](https://i.imgur.com/70is1Lq.png)

### Environment

  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.1
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.23.12 => 2.23.12 
    gatsby-plugin-favicon: ^3.1.6 => 3.1.6 
    gatsby-plugin-gtag: ^1.0.13 => 1.0.13 
    gatsby-plugin-material-ui: ^2.1.9 => 2.1.9 
    gatsby-plugin-react-helmet: ^3.3.9 => 3.3.9 
    gatsby-plugin-sass: ^2.3.10 => 2.3.10 
  npmGlobalPackages:
    gatsby-cli: 2.12.48

**Comment by pieh** [comment] 2020-07-09 13:08
I was trying to reproduce this using your `gatsby-ssr` snippet and I couldn't ... unless I had `<style>` tag in `<Helmet>` in which case I had to add special case for `<style>` tags there in the snippet:

```
  const newOnes = headComponents.sort((x, y) => {
    if (x.props && x.props["data-react-helmet"] && x.type !== `style`) {
      return -1
    } else if (y.props && y.props["data-react-helmet"] && y.type !== `style`) {
      return 1
    }
    return 0
  })
```

There is not enough information here without having access to your project to concretely say what's wrong :( Can you share your project? Or create minimal reproduction site that showcase the problem?

**Comment by BagchiMB** [comment] 2020-07-09 21:26
Hi @pieh although I couldn't make this gatsby ssr thing to work but I was able to make the crawlers see my meta tags actually my meta tags were updating a second or two late therefore I was not getting them on initial render later I made a workaround, but I continue to wonder why my gatsby-ssr didn't work, can I message you personally as I am not comfortable with sharing my project here, I will post the necessary reason why  my gatsby-ssr didn't work but I can't share the project over here ? Sorry if I am bothering you :( . I hope you can help me, I am very new with gatsby...

**Comment by pieh** [comment] 2020-07-09 21:29
👍  You can dm me via https://twitter.com/mipiechowiak

**Comment by LekoArts** [comment] 2020-07-22 05:33
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-07-22 05:33 UTC
Labels: status: needs reproduction, type: bug
