### ISSUE TITLE
props.data missing 

### ISSUE THREAD

**Issue by Bouncey** [gatsbyjs/gatsby#1930] opened 2017-08-27 15:29 UTC
I have a `BlogIndex` component I am trying to build, but I cannot get anything from the query? I have a `BlogArticle` component that works perfectly.

I have read issues with similar symptoms, but no remedies I have found have helped.

Any help would be greatly appreciated.

```js
/* global graphql */
import React from 'react';
import PropTypes from 'prop-types';

const propTypes = {};

function BlogIndex(props) {
  console.log(props.data); // undefined
  return (
    <div>
      This will be the index of blog posts
    </div>
  );
}

BlogIndex.displayName = 'BlogIndex';
BlogIndex.propTypes = propTypes;

export const pageQuery = graphql`
query IndexQuery {
  allMarkdownRemark {
    edges {
      node {
        frontmatter {
          title
          author
          published
        }
        fields {
          slug
        }
        excerpt
        timeToRead
      }
    }
  }
}
`;

export default BlogIndex;

```

**Comment by dougajmcdonald** [comment] 2017-08-28 09:09
I'm seeing the same thing with the `blog-post` example from this tutorial: https://www.gatsbyjs.org/blog/2017-07-19-creating-a-blog-with-gatsby/

It works in `develop` mode, but `build` just spits out undefined for `({data})`

**Comment by alexbassy** [comment] 2017-09-06 10:32
@dougajmcdonald I'm experiencing the same thing 😞 did you work out a fix for it by any chance?

**Comment by dougajmcdonald** [comment] 2017-09-06 11:51
@alexbassy I managed to fix things, but in a roundabout way. I basically updated `gatsby`, `gatsby-cli` and all my plugins to the latest. When I than ran in develop I had some other issues which when fixed solved the problem.

Prior to that I discovered a duplicate naming issue with one of my queries which gatsby didn't like.

I think my main issue was due to my doing a pageQuery on one component and trying to pass the results as `props` to another nested component. I don't think gatsby liked me doing that, so I fiddled with my routing as a workaround.

**Comment by alexbassy** [comment] 2017-09-06 15:12
@dougajmcdonald thank you for replying! I updated Gatsby too, but I couldn't find a changelog so didn't know if anything needs migrating. In my case the error was caused by a single file which had no content, I added a check the presence of `props.data` and it built the site absolutely fine again. Not sure why it suddenly started happening though 🤔

**Comment by KyleAMathews** [comment] 2017-12-20 05:20
Closing out older issues — thanks for everyone that participated on this thread — please open more issues if you need help!

**Closed by KyleAMathews** 2017-12-20 05:20 UTC
