### ISSUE TITLE
Error: Cannot find module 'gatsby-cli/lib/reporter'

### ISSUE THREAD

**Issue by joulien3** [gatsbyjs/gatsby#26456] opened 2020-08-14 12:42 UTC
## Description

  Error: Cannot find module 'gatsby-cli/lib/reporter'
  Require stack:
  - /Users/jume/hello-world/node_modules/gatsby-plugin-page-creator/is-valid-col  lection-path-implementation.js
  - /Users/jume/hello-world/node_modules/gatsby-plugin-page-creator/create-pages  -from-collection-builder.js
  - /Users/jume/hello-world/node_modules/gatsby-plugin-page-creator/create-page-  wrapper.js
  - /Users/jume/hello-world/node_modules/gatsby-plugin-page-creator/gatsby-node.  js
  - /Users/jume/hello-world/node_modules/gatsby/dist/bootstrap/resolve-module-ex  ports.js
  - /Users/jume/hello-world/node_modules/gatsby/dist/bootstrap/load-plugins/vali  date.js
  - /Users/jume/hello-world/node_modules/gatsby/dist/bootstrap/load-plugins/load  .js
  - /Users/jume/hello-world/node_modules/gatsby/dist/bootstrap/load-plugins/inde  x.js
  - /Users/jume/hello-world/node_modules/gatsby/dist/services/initialize.js
  - /Users/jume/hello-world/node_modules/gatsby/dist/services/index.js
  - /Users/jume/hello-world/node_modules/gatsby/dist/state-machines/develop/serv  ices.js
  - /Users/jume/hello-world/node_modules/gatsby/dist/state-machines/develop/inde  x.js
  - /Users/jume/hello-world/node_modules/gatsby/dist/commands/develop-process.js  - /Users/jume/hello-world/.cache/tmp-53186-IH0e7PfKg9t2

### Steps to reproduce

With Mac os Catalina : follow first steps guides to install (npm, xcode, and run npm gatsby) then install "hello site" and gatsby developp

### Expected result

Sucess

### Actual result

  Error: Cannot find module 'gatsby-cli/lib/reporter'
  Require stack:
  - /Users/jume/hello-world/node_modules/gatsby-plugin-page-creator/is-valid-col  lection-path-implementation.js
  - /Users/jume/hello-world/node_modules/gatsby-plugin-page-creator/create-pages  -from-collection-builder.js
  - /Users/jume/hello-world/node_modules/gatsby-plugin-page-creator/create-page-  wrapper.js
  - /Users/jume/hello-world/node_modules/gatsby-plugin-page-creator/gatsby-node.  js
  - /Users/jume/hello-world/node_modules/gatsby/dist/bootstrap/resolve-module-ex  ports.js
  - /Users/jume/hello-world/node_modules/gatsby/dist/bootstrap/load-plugins/vali  date.js
  - /Users/jume/hello-world/node_modules/gatsby/dist/bootstrap/load-plugins/load  .js
  - /Users/jume/hello-world/node_modules/gatsby/dist/bootstrap/load-plugins/inde  x.js
  - /Users/jume/hello-world/node_modules/gatsby/dist/services/initialize.js
  - /Users/jume/hello-world/node_modules/gatsby/dist/services/index.js
  - /Users/jume/hello-world/node_modules/gatsby/dist/state-machines/develop/serv  ices.js
  - /Users/jume/hello-world/node_modules/gatsby/dist/state-machines/develop/inde  x.js
  - /Users/jume/hello-world/node_modules/gatsby/dist/commands/develop-process.js  - /Users/jume/hello-world/.cache/tmp-53186-IH0e7PfKg9t2

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
 System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Xeon(R) W-2140B CPU @ 3.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.8.0 - /usr/local/bin/node
    npm: 6.14.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.125
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.24.41 => 2.24.41
  npmGlobalPackages:
    gatsby-cli: 2.12.87

**Comment by Hubert-Zhu** [comment] 2020-08-14 16:17
Hey bro, I just have the same problem. There is issue with 2.24.41 version. Some Contributor mentioned that in the issue 2 days ago, but they did not update the starter demo(hello site). I think I should work, if u just change the version to 2.24.42.

**Comment by AlexAltuzar** [comment] 2020-08-14 19:21
Igual tengo el mismo problema, lo solucione de 2 formas (con el fin de que me funcionara el gatsby develop)
**Solución 1**
1. Utilice un proyecto "default" de prueba.
2. Dentro del proyecto, me dirigí a node-modules/gatsby/node-modules
3. Dentro de esa ubicación se encontrara una carpeta llamada gatsby-cli.
3. Moví la carpeta gatby-cli al node-modules principal, es decir, a nivel de la carpeta gatsby
5.- Ejecute nuevamente le comando y me funciono (al menos para correr la app)

**Solución 2**
1. Dentro de la carpeta del proyecto ejecute el siguiente comando: npm install --save gatsby-cli 
2. Eso hizo que me generara una carpeta gatsby-cli dentro de node-modules
3. Corri el comando: gatsby develop

**Comment by vladar** [comment] 2020-08-14 21:20
It is a duplicate of this issue: #26345

You need to upgrade from `gatsby@2.24.41` to `gatsby@^2.24.42`

Try deleting `package-lock.json` and run `npm install` again (if you use yarn - delete `yarn.lock` and run `yarn`). If the problem occurs in the CLI itself, run `npm install -g gatsby-cli`

**Closed by vladar** 2020-08-14 21:20 UTC
Labels: status: triage needed, type: bug

**Comment by joulien3** [comment] 2020-08-15 09:09
@vladar Thanks a lot. It works fine now.
For noobs (Beginners) like me, go to home (house) on mac, you will find "package-lock.json. Then run on terminal npm install again in order to have the great version.
