### ISSUE TITLE
Refactor memory leak by setInterval code gatsby dev-ssr

### ISSUE THREAD

**Issue by simonjoom** [gatsbyjs/gatsby#36688] opened 2022-09-25 14:42 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

The code give me a problem to get a good result in the compilation of dev-ssr

### Reproduction Link

https://github.com/noreproductionlinkprovided

### Steps to Reproduce

1. Need a big project with long webpack compilation to reproduce
2.
3.
...

### Expected Result

Compilation ssr should to pass correctly

### Actual Result

memory leak due to setInterval and too much pass attempt 
In actual code setInterval can run again before the stream finish for a big render-page 
### Environment

```shell
Mac os
Last gatsby4
```

### Config Flags

DEV_SSR:true

### code problem:
https://github.com/gatsbyjs/gatsby/blob/a62955144f4d369e18402a9c4345f213c3a1d72e/packages/gatsby/src/utils/dev-ssr/render-dev-html.ts#L113-L136

### My Resolution
increment readAttempts and remove setInterval
```
let found = await searchFileForString(page.componentChunkName, htmlComponentRendererPath);

  if (!found) { 
    const delay = (ms) => { new Promise(resolve => setTimeout(resolve, ms)) }
    const lookforit = async (readAttempts) => { 
      found = await searchFileForString(page.componentChunkName, htmlComponentRendererPath);
      if (found || allowTimedFallback && readAttempts > 50) {
        console.log("isfound", found)
        return found; 
      } else {
        console.log("notfound", found)
        await delay(300);
        return await lookforit(readAttempts+1)
      }
    } 

    const bool = await lookforit(0)
    return bool
}
```

**Comment by tyhopp** [comment] 2022-09-28 03:47
Hi @simonjoom,

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2022-10-10 06:32
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2022-10-10 06:32 UTC
Labels: type: bug, status: needs reproduction
