### ISSUE TITLE
  ERROR #11321  PLUGIN  "gatsby-node.js" threw an error while running the onPreBootstrap lifecycle:

### ISSUE THREAD

**Issue by apsychogirl** [gatsbyjs/gatsby#24922] opened 2020-06-11 12:46 UTC
## Description
 ERROR #11321  PLUGIN

"gatsby-node.js" threw an error while running the onPreBootstrap lifecycle:
Describe the issue that you're seeing.

### Steps to reproduce

gatsby develop

### Expected result

Build without errors

### Actual result
```
yarn start
yarn run v1.22.4
$ gatsby develop --host 0.0.0.0
success open and validate gatsby-configs - 0.195s
success load plugins - 4.888s
success onPreInit - 0.066s
success initialize cache - 0.010s
success copy gatsby files - 0.172s

 ERROR #11321  PLUGIN

"gatsby-node.js" threw an error while running the onPreBootstrap lifecycle:

Request failed with status code 401

  80 |     )
  81 |   } catch (error) {
> 82 |     throw Error(error.message)
     |           ^
  83 |   }
  84 | }
  85 | 

File: gatsby-node.js:82:11



  Error: Request failed with status code 401
  
  - gatsby-node.js:82 Object.exports.onPreBootstrap
    /home/apsychogirl/gatsby-portfolio/gatsby-node.js:82:11
  
  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7
  
  - From previous event:
  
  - api-runner-node.js:258 runAPI
    [gatsby-portfolio]/[gatsby]/dist/utils/api-runner-node.js:258:22
  
  - api-runner-node.js:375 resolve
    [gatsby-portfolio]/[gatsby]/dist/utils/api-runner-node.js:375:15
  
  - From previous event:
  
  - api-runner-node.js:374 Promise.mapSeries.plugin
    [gatsby-portfolio]/[gatsby]/dist/utils/api-runner-node.js:374:12
  
  - From previous event:
  
  - api-runner-node.js:368 resolve
    [gatsby-portfolio]/[gatsby]/dist/utils/api-runner-node.js:368:11
  
  - From previous event:
  
  - api-runner-node.js:275 module.exports
    [gatsby-portfolio]/[gatsby]/dist/utils/api-runner-node.js:275:12
  
  - index.js:368 module.exports
    [gatsby-portfolio]/[gatsby]/dist/bootstrap/index.js:368:9
  

success onPreBootstrap - 0.675s
success createSchemaCustomization - 0.009s
success source and transform nodes - 0.358s
success building schema - 0.636s
success createPages - 0.093s
success createPagesStatefully - 0.118s
success onPreExtractQueries - 0.003s
success update schema - 0.041s
success extract queries from components - 0.604s
success write out requires - 0.077s
success write out redirect data - 0.003s
success Build manifest and related icons - 0.111s
success onPostBootstrap - 0.129s
⠀
info bootstrap finished - 20.746s
⠀
success run page queries - 0.042s - 4/4 94.25/s
⠀
You can now view @kremalicious/portfolio in the browser.
⠀
  Local:            http://localhost:8000/
  On Your Network:  http://192.168.0.106:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  Local:            http://localhost:8000/___graphql
  On Your Network:  http://192.168.0.106:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use gatsby build
⠀
success Building development bundle - 7.401s`
```

### Environment

```
  System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (4) x64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
    Shell: 5.5.1 - /usr/bin/zsh
  Binaries:
    Node: 10.21.0 - ~/.nvm/versions/node/v10.21.0/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v10.21.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 72.0.1
  npmPackages:
    gatsby: ^2.22.17 => 2.23.3
    gatsby-image: ^2.4.5 => 2.4.7
    gatsby-plugin-manifest: ^2.4.10 => 2.4.11
    gatsby-plugin-matomo: ^0.8.3 => 0.8.3
    gatsby-plugin-offline: ^3.2.8 => 3.2.9
    gatsby-plugin-postcss: ^2.3.3 => 2.3.4
    gatsby-plugin-react-helmet: ^3.3.2 => 3.3.4
    gatsby-plugin-sharp: ^2.6.10 => 2.6.11
    gatsby-plugin-sitemap: ^2.4.4 => 2.4.5
    gatsby-plugin-svgr: ^2.0.2 => 2.0.2
    gatsby-plugin-use-dark-mode: ^1.1.2 => 1.1.2
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.10 => 1.1.10
    gatsby-plugin-webpack-size: ^1.0.0 => 1.0.0
    gatsby-source-filesystem: ^2.3.10 => 2.3.11
    gatsby-transformer-json: ^2.4.3 => 2.4.5
    gatsby-transformer-sharp: ^2.5.4 => 2.5.5
    gatsby-transformer-yaml: ^2.4.3 => 2.4.4
  npmGlobalPackages:
    gatsby-cli: 2.12.42
```

**Comment by JaybeeClassical** [comment] 2020-06-15 20:25
Having the same error

**Comment by LekoArts** [comment] 2020-06-16 08:11
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by apsychogirl** [comment] 2020-06-16 11:24
> Hi!
> 
> Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction](https://gatsby.dev/reproduction). This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.
> 
> If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction](https://gatsby.dev/reproduction) and we'll be able to take another look.
> 
> Thanks for using Gatsby! purple_heart

I'll definitely give it a try this weekend :smile:

**Comment by JaybeeClassical** [comment] 2020-06-16 13:33
I just wanted to start my Gatsby app, it ran into errors in the image
below. I tried removing the node_modules, deleting the package-lock.json
and installing npm again but this did not work as well

**Comment by LekoArts** [comment] 2020-06-26 06:52
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-06-26 06:52 UTC
Labels: status: needs reproduction
