### ISSUE TITLE
Gatsby Image Not W3C Compliant

### ISSUE THREAD

**Issue by kaufmann42** [gatsbyjs/gatsby#25669] opened 2020-07-10 04:08 UTC
## Description

The Gatsby Image component misuses the media tag. See errors reported by the W3C checkers below.
![image](https://user-images.githubusercontent.com/11468557/87115340-8a272600-c238-11ea-99d5-e20aaa017496.png)

### Steps to reproduce

1. Goto https://validator.w3.org/nu/?showsource=yes&showoutline=yes&showimagereport=yes&doc=https%3A%2F%2Fairmilkshake.com%2F

This is a validator of the site airmilkshake.com , which utilizes the Gatsby Image component. The errors are shown on that page as well as in the screenshot above.

### Expected result

No W3C validation errors.

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.20.1 - ~/.nvm/versions/node/v10.20.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v10.20.1/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 77.0.1
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.21.33 => 2.21.33 
    gatsby-cli: ^2.12.15 => 2.12.21 
    gatsby-image: ^2.0.23 => 2.3.2 
    gatsby-plugin-canonical-urls: ^2.3.9 => 2.3.9 
    gatsby-plugin-manifest: ^2.4.2 => 2.4.2 
    gatsby-plugin-netlify: ^2.0.6 => 2.2.1 
    gatsby-plugin-netlify-cms: ^4.1.6 => 4.2.2 
    gatsby-plugin-offline: ^3.2.1 => 3.2.1 
    gatsby-plugin-purgecss: ^4.0.0 => 4.0.1 
    gatsby-plugin-react-helmet: ^3.0.4 => 3.2.2 
    gatsby-plugin-sass: ^2.0.7 => 2.2.1 
    gatsby-plugin-sharp: ^2.2.9 => 2.5.4 
    gatsby-plugin-typescript: ^2.3.3 => 2.3.3 
    gatsby-remark-copy-linked-files: ^2.0.7 => 2.2.1 
    gatsby-remark-images: ^3.1.6 => 3.2.2 
    gatsby-remark-relative-images: ^0.3.0 => 0.3.0 
    gatsby-source-filesystem: ^2.0.26 => 2.2.2 
    gatsby-transformer-remark: ^2.6.9 => 2.7.1 
    gatsby-transformer-sharp: ^2.1.9 => 2.4.4

**Comment by kaufmann42** [comment] 2020-07-18 01:33
Any updates on this?

**Comment by HenrikDK2** [comment] 2020-07-24 17:42
I have this problem aswell, i hope we get some more information about this.

**Comment by ascorbic** [comment] 2021-03-08 09:32
This is fixed in [gatsby-plugin-image](https://www.gatsbyjs.com/plugins/gatsby-plugin-image/)

**Closed by ascorbic** 2021-03-08 09:32 UTC
Labels: topic: images/media, type: bug

**Comment by bnbabu55** [comment] 2022-01-08 14:40
Looks like this issue has not been fixed yet.
1. Steps to reproduce, go to [https://validator.w3.org/nu/?showsource=yes&showoutline=yes&showimagereport=yes&doc=https%3A%2F%2Fpomareslawgroup.com%2F](url) 

Expected result
No W3C validation errors.

Actual result
What happened.

Environment
Run gatsby info --clipboard in your project directory and paste the output here.

  System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  Binaries:
    Node: 16.13.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.3.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.18
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (96.0.1054.62)
  npmPackages:
    gatsby: ^4.4.0 => 4.4.0 
    gatsby-background-image: ^1.6.0 => 1.6.0 
    gatsby-plugin-advanced-sitemap: ^2.0.0 => 2.0.0 
    gatsby-plugin-image: ^2.4.0 => 2.4.0 
    gatsby-plugin-manifest: ^4.4.0 => 4.4.0 
    gatsby-plugin-offline: ^5.4.0 => 5.4.0 
    gatsby-plugin-perf-budgets: ^0.0.18 => 0.0.18 
    gatsby-plugin-postcss: ^5.4.0 => 5.4.0 
    gatsby-plugin-react-helmet: ^5.4.0 => 5.4.0 
    gatsby-plugin-react-intl: ^3.0.2 => 3.0.2 
    gatsby-plugin-schema-snapshot: ^3.4.0 => 3.4.0 
    gatsby-plugin-sharp: ^4.4.0 => 4.4.0 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.26 => 1.1.26 
    gatsby-source-filesystem: ^4.4.0 => 4.4.0 
    gatsby-source-wordpress: ^6.4.0 => 6.4.0 
    gatsby-transformer-remark: ^5.4.0 => 5.4.0 
    gatsby-transformer-sharp: ^4.4.0 => 4.4.0 
  npmGlobalPackages:
    gatsby-cli: 4.4.0
