### ISSUE TITLE
TypeError: props.theme.x is undefined (emotion)

### ISSUE THREAD

**Issue by Sondro** [gatsbyjs/gatsby#12027] opened 2019-02-24 02:23 UTC
Hi, trying to update a gatsby demo test from v1 to v2 using emotion.

I think the syntax is off because the global is not being wrapped properly with the layout/wrapper.

IE, any of the below is undefined:
```
${props => props.theme.x}
```

I currently have the following:
```
const GlobalStyle = Global` 
  html {
    text-rendering: optimizeLegibility;
  }
`;

const Layout00 = ({ children }) => {
      <ThemeProvider theme={theme}>
        <React.Fragment>
          <GlobalStyle />
          <Nav />
          {children}
        </React.Fragment>
      </ThemeProvider>
};

export default Layout00;
```

Any help would be appreciated.

**Comment by wardpeet** [comment] 2019-02-25 08:37
Hey! if I look at the emotion docs https://emotion.sh/docs/globals it looks like you're using GlobalStyle wrong. Could you try

```
const GlobalStyle = () => <Global styles={css` 
  html {
    text-rendering: optimizeLegibility;
  }
`} />;

const Layout00 = ({ children }) => {
      <ThemeProvider theme={theme}>
        <React.Fragment>
          <GlobalStyle />
          <Nav />
          {children}
        </React.Fragment>
      </ThemeProvider>
};
```

**Comment by Sondro** [comment] 2019-02-25 09:36
Hi wardpeet.

That doesn't seem to work (the error is the same).

Also tried importing with:
```
export const cssGlobal = css`
html {
    text-rendering: optimizeLegibility;
  }
`;
```
```
import cssGlobal from "/cssGlobal";

const MainLayout = ({ children }) => {
      <ThemeProvider theme={theme}>
        <React.Fragment>
           <Global styles={cssGlobal} />
            <Nav />
            {children}
          </React.Fragment>
      </ThemeProvider>
};
```

Any other ideas?

**Comment by sidharthachatterjee** [comment] 2019-02-25 11:59
@Sondro Could you link to a quick reproduction repo if possible? Might make it easier to debug 🙂

**Comment by Sondro** [comment] 2019-02-26 00:09
BTW does anyone know if these warnings are normal:
```
warning "gatsby > eslint-plugin-graphql@2.1.1" has incorrect peer dependency "gr
aphql@^0.12.0 || ^0.13.0".
warning "gatsby > express-graphql@0.6.12" has incorrect peer dependency "graphql
@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "gatsby > graphql-tools@3.1.1" has incorrect peer dependency "graphql@^0
.13.0".
```

**Comment by lyyourc** [comment] 2019-03-03 17:33
Duplicate of https://github.com/gatsbyjs/gatsby/issues/11494

**Comment by DSchau** [comment] 2019-03-04 16:59
@Sondro let's close this out as a duplicate of #11494 as @lyyourc noted.

Please, please feel free to reply to this and we can take a look once you provide a reproduction, and take a look at the above issue (which may help you resolve your issue). We'd be happy to help if we're able!

Thanks!

**Closed by DSchau** 2019-03-04 16:59 UTC
Labels: status: needs reproduction
