### ISSUE TITLE
CSS not working after deploying on Digital Ocean

### ISSUE THREAD

**Issue by mahayash** [gatsbyjs/gatsby#5468] opened 2018-05-18 01:26 UTC
After deploying the gatsby site on Digital ocean,  on navigation show 404 ... can anyone assist
http://www.squareeducation.in/
Square Education Institute
School Section & Grammar
I have used react slider, even that seems to be not working

**Comment by ryanditjia** [comment] 2018-05-18 05:33
Does it work on your local machine when you `gatsby build` and `gatsby serve`?

If it does, please fill out the bug report format below to help us help you.



## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue.

### Expected result

What should happen?

### Actual result

What happened.

### Environment
* Gatsby version (`npm list gatsby`):
* gatsby-cli version (`gatsby --version`):
* Node.js version:
* Operating System:

### File contents (if changed)
`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by mahayash** [comment] 2018-05-19 12:17
My application works  well after "gatsby build" and "gatsby serve" on my local machine

**Description**
Deploying of the build folder on the digital ocean gives 404 page

Steps to reproduce
1. Build the application with "gatsby build"
2. Deploy the build folder on DigitalOcean 
3. try to access the webiste with domain "www.squareeducation.in"

Expected result
The site with proper css and navigation should be displayed

Actual result
404 page 

Environment
Gatsby version (npm list gatsby): gatsby@1.9.241
gatsby-cli version (gatsby --version): 1.1.51
Node.js version:v8.10.0
Operating System: macOS Sierria ( v10.12.1)
File contents (if changed)
gatsby-config.js: N/A 
package.json: N/A 
gatsby-node.js: N/A 
gatsby-browser.js: N/A 
gatsby-ssr.js: N/A

**Comment by pieh** [comment] 2018-05-29 15:57
This sounds like hosting / DigitalOcean issue. Do you have any rewrites defined there? Or maybe you didn't deploy entire public directory.

**Comment by LekoArts** [comment] 2018-12-11 11:37
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Closed by LekoArts** 2018-12-11 11:37 UTC
Labels: status: needs reproduction, type: question or discussion
