### ISSUE TITLE
Conflicting routes do not generate warning

### ISSUE THREAD

**Issue by noahsb** [gatsbyjs/gatsby#33422] opened 2021-10-04 21:47 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

In the [Gatsby documentation](https://www.gatsbyjs.com/docs/reference/routing/creating-routes/#conflicting-routes), it states that:

> "Since there are multiple ways to create a page, different plugins, themes, or sections of code in your gatsby-node file may accidentally create multiple pages that are meant to be accessed by the same path. When this happens, Gatsby will show a warning at build time, but the site will still build successfully."

However, I have not found this to be true for pages created with markdown. I created two markdown pages with the same slug and no warning was generated in the console for both `yarn start` and `yarn build`. Also, no error is displayed in Chrome DevTools.

Is it still the case that an error should be displayed when there are conflicting routes? The rest of the documentation, however, is still correct:

> "In this situation, the page that was built last will be accessible and any other conflicting pages will not be."

Happy to contribute to this should there be any help required, thank you!

### Reproduction Link

https://github.com/noahsb/using-markdown-pages

### Steps to Reproduce

1. Clone the repository: `git clone https://github.com/noahsb/using-markdown-pages.git`
2. Install dependencies
3. `Yarn start`
4. Notice there are no errors anywhere and the blog post displayed at `/blog/my-first-post` could be either the first or second post given that they share the same slug

### Expected Result

A warning to be generated in the console that there are conflicting routes at `/blog/my-first-post`

### Actual Result

No warnings are generated letting the user know there are conflicting routes

### Environment

```shell
System:
    OS: macOS 11.1
    CPU: (8) x64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.5.0 - /var/folders/fq/821_lpwx2yjc_29mdbp48n900000gn/T/yarn--1633384057579-0.9794313587931136/node
    Yarn: 1.22.11 - /var/folders/fq/821_lpwx2yjc_29mdbp48n900000gn/T/yarn--1633384057579-0.9794313587931136/yarn
    npm: 7.19.1 - ~/.nvm/versions/node/v16.5.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 94.0.4606.71
    Safari: 14.0.2
  npmPackages:
    gatsby: ^4.0.0-zz-next.1 => 4.0.0-zz-next.1
    gatsby-image: next => 3.12.0-next.0
    gatsby-plugin-manifest: next => 4.0.0-zz-next.1
    gatsby-plugin-offline: next => 5.0.0-zz-next.1
    gatsby-plugin-react-helmet: next => 5.0.0-zz-next.1
    gatsby-plugin-sharp: next => 4.0.0-zz-next.1
    gatsby-source-filesystem: next => 4.0.0-zz-next.1
    gatsby-transformer-remark: next => 5.0.0-zz-next.1
    gatsby-transformer-sharp: next => 4.0.0-zz-next.1
```

**Comment by LekoArts** [comment] 2021-11-08 07:46
Hi!

Can you please upgrade your reproduction to use the latest version of Gatsby and all plugins? If it is then still the case we can have another look. Thanks!

**Comment by LekoArts** [comment] 2021-11-22 11:00
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-11-22 11:00 UTC
Labels: type: bug, status: needs reproduction, gatsby 4
