### ISSUE TITLE
[gatsby-plugin-offline] IOS 13 Safari error `null is not an object (evaluating 'n.announcementRef.current.innerText')`

### ISSUE THREAD

**Issue by JustFly1984** [gatsbyjs/gatsby#23995] opened 2020-05-12 01:52 UTC
I got error in Sentry logs, it points to `./.cache/navigation.js in apply at line 177:52`

```
      const pageHeadings = document.querySelectorAll(`#gatsby-focus-wrapper h1`)
      if (pageHeadings && pageHeadings.length) {
        pageName = pageHeadings[0].textContent
      }
      const newAnnouncement = `Navigated to ${pageName}`
      const oldAnnouncement = this.announcementRef.current.innerText // error on this line
      if (oldAnnouncement !== newAnnouncement) {
        this.announcementRef.current.innerText = newAnnouncement
      }
    })
  }
```

<img width="1113" alt="Screenshot 2020-05-12 08 44 19" src="https://user-images.githubusercontent.com/2255993/81629212-d3bbe600-942c-11ea-8c74-95bd9af41e65.png">

which triggered after 2 consecutive errors in the console `InvalidStateError: Service Worker state is redundant`

<img width="1149" alt="Screenshot 2020-05-12 08 48 10" src="https://user-images.githubusercontent.com/2255993/81629457-5a70c300-942d-11ea-914f-6ea94cbe087a.png">

As you can see on last screenshot - there is navigation action from `/en/account/transfer`, to `/en/account/withdraw`. Both routes are fully dynamic, and do not pre-rendered at build time.

iOS 13.3.1
Mobile Safari  13.0.5

**Comment by madalynrose** [comment] 2020-05-12 15:38
Hi there, @JustFly1984! A [fix for this](https://github.com/gatsbyjs/gatsby/pull/23956) actually went out just yesterday! Try updating your Gatsby version and let us know if that fixes it! 

If that doesn't fix it, to help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by JustFly1984** [comment] 2020-05-13 03:44
@madalynrose  I can't create a reproduction, since I got only single error in logs in Sentry in single project from many. I will update gatsby.js to the latest version in all my projects and will look if it repeats in logs

**Comment by mateustav** [comment] 2020-05-13 06:27
Any luck, @JustFly1984? I was facing the same issue before updating gatsby from v2.21.11 to v2.21.24. Now I get a blank page instead, and the following console errors: 
`Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

![Error](https://user-images.githubusercontent.com/8979428/81778614-0eaf2f80-94a8-11ea-888a-c2a56f4f0719.png)


Page looks fine when I open it on a new tab, but the issue above happens if I click on a Link component.

**Comment by JustFly1984** [comment] 2020-05-13 14:06
I can't deploy to staging yet, waiting for PR review before deploy. Will look at Sentry logs. Possible tomorrow.

**Comment by ascorbic** [comment] 2020-06-04 09:08
Hi. I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. Thanks!

**Closed by ascorbic** 2020-06-04 09:08 UTC
Labels: status: needs reproduction, topic: PWA, type: bug
