### ISSUE TITLE
"source and transform nodes" is taking a long time with gatsby-source-wordpress

### ISSUE THREAD

**Issue by awesomebob** [gatsbyjs/gatsby#4293] opened 2018-03-01 00:27 UTC
Context: I'm using `gatsby-source-wordpress` with lots of ACF fields. I have about 1,000 posts with a custom post type, and attached to those posts are about 1800 total images currently. The images are attached with a `gallery` ACF field. I have a bunch of other fields, but I expect the images and far and away the most resource-intensive. I have a few custom taxonomies but they don't have very many terms.

My current issue is with "source and transform nodes":

`success source and transform nodes — 459.213 s`

The little command line spinner just sits there for 459 seconds without indication of what it's doing.
What can I do to optimize this compile time specifically related to node sourcing?

**Comment by KyleAMathews** [comment] 2018-03-01 00:43
That time is probably mostly downloading images.

Add some logging to `createRemoteFileNode` in gatsby-source-filesystem and you'll have more visibility there.

I want to add a generic jobs logging framework to core so that plugins like this could update their progress there.

**Comment by awesomebob** [comment] 2018-03-01 01:01
@KyleAMathews good call, that does seem to be what's going on. Gatsby already caches downloaded images, so I'm not sure if there's anything else I can really do to speed that up.

**Comment by awesomebob** [comment] 2018-03-02 21:57
I've added logging to `createRemoteFileNode` and found that there is still additional time spent during `source and transform nodes` that happens after all the images are downloaded. Where else should I look for long-running tasks that would happen during this step?

**Comment by KyleAMathews** [comment] 2018-03-02 21:58
How much more time?

**Comment by awesomebob** [comment] 2018-03-02 22:19
10+ minutes in develop mode. I've let it run for awhile then killed it several times, and at some point it will actually complete. The production build is still only taking 9 minutes in total though.

**Comment by KyleAMathews** [comment] 2018-03-02 22:29
Try editing https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/bootstrap/page-hot-reloader.js (replace src with dist) in your node_modules folder and log whenever `CREATE_NODE` is called with the action.

What does the logging of the bootstrap process look like so I can see the times?

**Comment by awesomebob** [comment] 2018-03-02 23:37
I've added logging to `CREATE_NODE` in that file but haven't seen it do anything yet, the develop command hasn't finished yet and never gets to a point where it can live reload.

I also added a log on `actions.createNode` in `gatsby/dist/redux/actions.js` and that shows me the file nodes that are created when the images are loaded for the remote file nodes, but nothing during the time that it's hanging.

**Comment by awesomebob** [comment] 2018-03-05 20:20
I'm still looking at the createNode logs.

After the `removeFileNode` are finished, there is a long wait, followed by `wordpress__acf_posts`, `wordpress__acf_pages`, `WordPressAcf_image_and_text` and a bunch of other ACF fields.

Maybe the delay is Gatsby trying to infer the data schema of all my flexible content fields? I only have 4 layouts in the single Flexible Content field, on about 36 pages total, not a whole lot.

**Comment by KyleAMathews** [comment] 2018-03-05 20:37
Schema inference doesn't happen until it reaches that point in the bootstrap process.

**Comment by KyleAMathews** [comment] 2018-03-05 20:38
This might be a good time to get profiling working ;-)

https://github.com/gatsbyjs/gatsby/issues/4218

See what code is running.

**Comment by arminnaimi** [comment] 2018-04-17 21:38
Hi there! Is it possible to turn off fetching images and saving them locally? It would save a ton of local development time. I am using gatsby-source-contentful.

**Comment by szimek** [comment] 2018-04-23 13:48
@arminnaimi Unless you're using some image related plugin, `gatsby-source-contentful` shouldn't download any images. I've got 6 spaces with ~500 posts and ~1500 images each and it takes ~10 minutes to complete the `source and transform nodes` step. I created a ticket to speed it up as well: https://github.com/gatsbyjs/gatsby/issues/5079.

**Comment by arminnaimi** [comment] 2018-04-23 15:06
One thing I am noticing is that when excluding additional locales in the API response from Contentful, the whole build goes down to something more manageable like 40 seconds. The fact that it struggles with locales might be an issue with how effectively GraphQL can handle large JSON responses.

**Comment by szimek** [comment] 2018-04-23 15:25
@arminnaimi It might be it - in my case each space has only 1 locale, which is different for each space.

**Comment by KyleAMathews** [comment] 2018-09-08 05:12
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Closed by KyleAMathews** 2018-09-08 05:12 UTC

**Comment by r1q** [comment] 2019-09-03 15:48
I know its closed but In my case when i tried all solutions and nothing seems to fix it .. the only thing that worked was:

**Resizing the Terminal window !!** when it gets stuck.

**Comment by Firthir** [comment] 2019-09-05 06:04
@KyleAMathews @r1q I can't understand how this method works? but it dose.
Resizing the Terminal window !! when it gets stuck.

**Comment by elfatherbrown** [comment] 2019-09-10 03:42
I have this exact behaviour. Such wierd thing the terminal resizing part. Perhaps some "screen" stuff going on there?

**Comment by r1q** [comment] 2019-09-10 03:59
Maybe someone from Netlify or iTerm team can help in debugging?

**Comment by elfatherbrown** [comment] 2019-09-10 04:41
If its any help, I can reproduce it in osx terminal and platformio-ide on atom. Not a terminal thing. It happens in the gatsby stages where a terminal spinner character appears. The spinner seems to freeze and then if one resizes the terminal, things go forward.

**Comment by marciplan** [comment] 2019-09-21 07:18
> I know its closed but In my case when i tried all solutions and nothing seems to fix it .. the only thing that worked was:
> 
> **Resizing the Terminal window !!** when it gets stuck.

This fixed it for me, too. How weird. But thank you so much :)

**Comment by jmcbee** [comment] 2019-10-06 21:44
Is there an open issue regarding this bug which gets "fixed" by resizing the window?

**Comment by shanejones** [comment] 2020-11-19 08:24
Just adding in something that I've just found.

I found this would hang for a long time when I used iTerm, for a test I booted up the classic terminal for mac and this process stopped hanging. Wondering if it is a memory or buffer issue in iTerm causing this to hang?

**Comment by pvdz** [comment] 2020-12-03 08:35
> Is there an open issue regarding this bug which gets "fixed" by resizing the window?

Yeah, there's https://github.com/gatsbyjs/gatsby/issues/27325

**Comment by pvdz** [comment] 2020-12-03 08:35
I'm going to lock this issue.

**Comment by pvdz** [comment] 2020-12-03 08:36
@shanejones would love it if you could figure out what might cause it. None of us can repro it. Please continue that discussion in the linked PR.
