### ISSUE TITLE
Cannot query field "references" on type

### ISSUE THREAD

**Issue by akiraplusplus** [gatsbyjs/gatsby#30487] opened 2021-03-26 12:07 UTC
After updating to the latest gatsby-source-contentful@4.3.0 from the canary version we are getting this error.
`Cannot query field "references" on type "contentfulBlogPostBodyRichTextNode".

If you don't expect "references" to exist on the type "contentfulBlogPostBodyRichTextNode" it is most likely a typo.
However, if you expect "references" to exist there are a couple of solutions to common problems:`

**Comment by LekoArts** [comment] 2021-03-26 12:56
Hi!

Thanks for this PR! We really appreciate you taking the time to open it.

In the interest of moving this along most effectively, we strongly encourage our contributors to provide an [example project](https://gatsby.dev/example-project) which we can then use to validate the changes in this PR. This will allow us to quickly and easily ensure that this does indeed address the purported feature or fix in this PR!

An example project:

- can be run locally or credentials have been provided
	- Feel free to message on Twitter, Discord, etc.
- can be used to validate this functionality
	- In other words, the necessary functionality has been enabled/disabled in the project for us to easily validate these changes

If you're able to provide an example that we can use to test these changes we can more quickly get this merged and released. If you're unable -- we will prioritize as best as we can and test when we're able to do so.

Thanks for this PR and thanks for using Gatsby!

💜

**Comment by LekoArts** [comment] 2021-04-06 10:13
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-04-06 10:13 UTC
Labels: status: needs reproduction, type: bug
