### ISSUE TITLE
Build Looks Totally Different / Broken CSS

### ISSUE THREAD

**Issue by JimTheMan** [gatsbyjs/gatsby#19113] opened 2019-10-29 13:06 UTC
## Description

When I develop a gatsby site it looks great, but when I build the site and deploy the css gets super messed up.

Describe the issue that you're seeing.
way too much emtpy space all over the space.

### Steps to reproduce

npm run build

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

The repo is private, but the site is here: evaluates2.com

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

Things should look in the final site exactly the way they look in `gatsby serve`

### Actual result

they don't at all....

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```
System:
    OS: macOS 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.16.0 - ~/.nvm/versions/node/v8.16.0/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v8.16.0/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 78.0.3904.70
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.17.6 => 2.17.6
    gatsby-image: ^2.2.30 => 2.2.30
    gatsby-plugin-create-client-paths: ^2.1.15 => 2.1.15
    gatsby-plugin-emotion: ^4.1.13 => 4.1.13
    gatsby-plugin-manifest: ^2.2.25 => 2.2.25
    gatsby-plugin-offline: ^2.0.23 => 2.2.10
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.13
    gatsby-plugin-sharp: ^2.2.34 => 2.2.34
    gatsby-plugin-styled-components: ^3.1.11 => 3.1.11
    gatsby-remark-copy-linked-files: ^2.1.28 => 2.1.28
    gatsby-remark-video: ^1.2.5 => 1.2.5
    gatsby-source-filesystem: ^2.1.35 => 2.1.35
    gatsby-transformer-json: ^2.2.16 => 2.2.16
    gatsby-transformer-sharp: ^2.3.1 => 2.3.1
```

Thanks 👍

**Comment by JimTheMan** [comment] 2019-10-31 18:59
Hi, I still have not figured this out, and it's causing huge issues for my team! 😭 

Bumping this thread in the hopes that someone will try to help me out...

I also posted here but have no real direction for debugging this.
https://spectrum.chat/gatsby-js/general/help-experiencing-weird-broken-css-in-gatsby-build~ed4e475e-1323-416f-bfad-c79d2223dec4

@gatsbybot

**Comment by LekoArts** [comment] 2019-11-01 09:37
Thank you for opening this!

Since you've created two Spectrum chats ([one](https://spectrum.chat/gatsby-js/general/gatsby-build-breaks-css~e63b2269-4e96-4998-8493-caf72269d125) and [two](https://spectrum.chat/gatsby-js/general/help-experiencing-weird-broken-css-in-gatsby-build~ed4e475e-1323-416f-bfad-c79d2223dec4)) already, I read through those I think you've kinda got the correct help there already.

Since your repository is private we can only say that we'd appreciate a reproduction of your problem and like someone commented you should go back in your history and see where it broke. Furthermore you shouldn't mix emotion and styled-components. The advice to install the babel plugin of styled-components is also misleading as `gatsby-plugin-styled-components` already does that for you.

So make sure to only use either emotion or styled-components and use the accompanying Gatsby plugin. If you can make a reproduction of your problem feel free to comment here. 

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2019-11-01 09:37 UTC
Labels: type: question or discussion
