### ISSUE TITLE
Gatsby Image Plugin Crash 

### ISSUE THREAD

**Issue by chdryawais** [gatsbyjs/gatsby#30512] opened 2021-03-28 08:22 UTC
I am facing this issue while working with **gatsby-plugin-image** to develop according in gatsby. Its working fine on first load but when state changes  and comes to first index its crash and give error's.

> Warning: render(...): It looks like the React-rendered content of this container was removed without using React. This is not supported and will cause errors. Instead, call ReactDOM.unmountComponentAtNode to empty a container.

> The above error occurred in the <Placeholder> component:

    at Placeholder (webpack-internal:///./node_modules/gatsby-plugin-image/dist/index.browser-caee7c75.js:645:13)
    at H (webpack-internal:///./node_modules/gatsby-plugin-image/dist/index.browser-caee7c75.js:543:13)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

> The above error occurred in the <H> component:

    at H (webpack-internal:///./node_modules/gatsby-plugin-image/dist/index.browser-caee7c75.js:543:13)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

> Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

    at removeChildFromContainer (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:10307:15)
    at unmountHostComponents (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21289:9)
    at commitDeletion (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21342:5)
    at commitMutationEffects (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23402:11)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at HTMLUnknownElement.o (https://cdn.lr-ingest.io/LogRocket.min.js:9:58319)
    at HTMLUnknownElement.d (http://localhost:8000/:3:6560)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3994:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4056:31)
    at commitRootImpl (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23116:9)
    at unstable_runWithPriority (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:468:12)
    at runWithPriority$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11276:10)
    at commitRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:22985:3)
    at performSyncWorkOnRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:22324:3)
    at eval (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11327:26)
    at unstable_runWithPriority (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:468:12)
    at runWithPriority$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11276:10)
    at flushSyncCallbackQueueImpl (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11322:9)
    at flushSyncCallbackQueue (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11309:3)
    at scheduleUpdateOnFiber (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21888:9)
    at updateContainer (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:25477:3)
    at legacyRenderSubtreeIntoContainer (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26032:5)
    at render (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26098:10)
    at u (webpack-internal:///./node_modules/gatsby-plugin-image/dist/lazy-hydrate-def776d5.js:66:123)
    at eval (webpack-internal:///./node_modules/gatsby-plugin-image/dist/index.browser-caee7c75.js:751:39)

> Uncaught (in promise) DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.

    at insertInContainerBefore (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:10296:15)
    at insertOrAppendPlacementNodeIntoContainer (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21190:7)
    at insertOrAppendPlacementNodeIntoContainer (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21198:7)
    at insertOrAppendPlacementNodeIntoContainer (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21198:7)
    at insertOrAppendPlacementNodeIntoContainer (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21198:7)
    at commitPlacement (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21176:5)
    at commitMutationEffects (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23356:11)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3945:14)
    at HTMLUnknownElement.o (https://cdn.lr-ingest.io/LogRocket.min.js:9:58319)
    at HTMLUnknownElement.d (http://localhost:8000/:3:6560)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:3994:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:4056:31)
    at commitRootImpl (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:23116:9)
    at unstable_runWithPriority (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:468:12)
    at runWithPriority$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11276:10)
    at commitRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:22985:3)
    at performSyncWorkOnRoot (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:22324:3)
    at eval (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11327:26)
    at unstable_runWithPriority (webpack-internal:///./node_modules/scheduler/cjs/scheduler.development.js:468:12)
    at runWithPriority$1 (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11276:10)
    at flushSyncCallbackQueueImpl (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11322:9)
    at flushSyncCallbackQueue (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:11309:3)
    at scheduleUpdateOnFiber (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:21888:9)
    at updateContainer (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:25477:3)
    at legacyRenderSubtreeIntoContainer (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26032:5)
    at render (webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:26098:10)
    at u (webpack-internal:///./node_modules/gatsby-plugin-image/dist/lazy-hydrate-def776d5.js:66:123)
    at eval (webpack-internal:///./node_modules/gatsby-plugin-image/dist/index.browser-caee7c75.js:751:39)

**Comment by creotip** [comment] 2021-03-29 08:14
This issue is the same as https://github.com/gatsbyjs/gatsby/issues/29982

You can fix this by installing next version

**Comment by LekoArts** [comment] 2021-04-06 07:01
I'll close this as a duplicate of https://github.com/gatsbyjs/gatsby/issues/29982 - please post your findings there. Thanks!

**Closed by LekoArts** 2021-04-06 07:01 UTC
Labels: status: triage needed, type: bug
