### ISSUE TITLE
bug(plugins): missing readme for pages

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#22768] opened 2020-04-02 17:12 UTC
## Description

missing readme for some plugins

### Steps to reproduce

open https://www.gatsbyjs.org/packages/gatsby-plugin-i18n/?=i18n

### Expected result

full readme visible here from: 
- https://www.npmjs.com/package/gatsby-plugin-i18n
- https://github.com/angeloocana/gatsby-plugin-i18n#readme

### Actual result

just text:

```
View plugin on GitHub      See starters using this
README.md
```

<img width="384" alt="screenshot" src="https://user-images.githubusercontent.com/184316/78277363-aff3af00-7514-11ea-9660-bcb78d313a59.png">

### affected plugins:

i found so far:
- https://www.gatsbyjs.org/packages/gatsby-plugin-i18n/
- https://www.gatsbyjs.org/packages/gatsby-plugin-i18n-tags/
- https://www.gatsbyjs.org/packages/gatsby-plugin-i18n-category/
- https://www.gatsbyjs.org/packages/gatsby-plugin-i18n-categories/
- https://www.gatsbyjs.org/packages/@ptb/gatsby-plugin-stylus/
- https://www.gatsbyjs.org/packages/bowlingx-gatsby-plugin-sass/
- https://www.gatsbyjs.org/packages/@jesses/gatsby-plugin-postcss/
- https://www.gatsbyjs.org/packages/@wyze/gatsby-plugin-favicon/

**Comment by jzabala** [comment] 2020-04-02 23:26
Hi, I would like to give this one a try 🙂

**Comment by LekoArts** [comment] 2020-04-03 05:40
This is a duplicate of older issues I cannot find right now but the short version is that we leverage the list from Algolia and hence can’t change what we get back from them. Sometimes their store is out-of-date or empty.

**Closed by LekoArts** 2020-04-03 05:40 UTC
Labels: type: bug, type: documentation
