### ISSUE TITLE
Failed to compile Gatsby files (@parcel/core)

### ISSUE THREAD

**Issue by uladdev** [gatsbyjs/gatsby#36594] opened 2022-09-12 10:05 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hello, i started migration of my project to typescript. After migration i have issues with imports .svg .woff .png files
<img width="1108" alt="Screenshot 2022-09-12 at 13 00 50" src="https://user-images.githubusercontent.com/112949883/189626793-59545f9c-e55a-433b-996e-b019d6b407c8.png">

### Reproduction Link

i dont know

### Steps to Reproduce

Start migration from js to ts
Import image

### Expected Result

Project should start 

### Actual Result

Failed to compile Gatsby files (@parcel/core):

No transformers found for __packages/site/src/images/icons/Facebook.svg__..

File path: /Users/vladissqq/Desktop/code/cloudwall/cloudwall-public-site/node_modules/.pnpm/gatsby-parcel-config@0.6.0_@parcel+core@2.5.0/node_modules/g
atsby-parcel-config/lib/index.json

### Environment

```shell
System:
Macos 11.6.8

pnpm: 7.11.0
```

**Comment by LekoArts** [comment] 2022-09-12 10:20
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2022-09-21 06:15
This should be fixed with https://github.com/gatsbyjs/gatsby/pull/36583

**Closed by LekoArts** 2022-09-21 06:15 UTC
Labels: type: bug, status: needs reproduction
