### ISSUE TITLE
Error thrown when using the Gatsby CLI after install - "Error: Cannot find module 'detect-port'"

### ISSUE THREAD

**Issue by mitchellbusby** [gatsbyjs/gatsby#24325] opened 2020-05-22 00:14 UTC
## Description
When I installed the gatsby CLI, I was unable to run it; it throws this exception in the command line:

![image](https://user-images.githubusercontent.com/1575729/82617770-7259fb00-9c14-11ea-8c6f-378d4d518b55.png)

This is only resolveable by globally installing `detect-port`, at which point everything is fine. Perhaps a missing dependency that wasn't included?

### Steps to reproduce

1. Install `gatsby-cli` globally.
2. Try to create a new site with the Gatsby CLI per the tutorial (or run `gatsby -v` - any command will cause the failure it seems)
3. The above error is spat out

### Expected result

What should happen?

It should not throw

### Actual result

It throws an exception saying that `detect-port` could not be found.

### Environment

  System:
    OS: macOS 10.15.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.13.0/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 81.0.4044.138
    Edge: 81.0.416.72
    Firefox: 74.0.1
    Safari: 13.1
  npmGlobalPackages:
    gatsby-cli: 2.12.31

_NB I had to do the above manual install of `detect-port` to get this to work_

**Comment by lukenetti3** [comment] 2020-05-22 00:29
This exact same thing happened to me as well.

**Comment by ryan-talus** [comment] 2020-05-22 00:34
This is currently happening in my builds as well; using the `gatsby-cli` installed in my project's `node_modules` (by using `yarn build` instead of `gatsby build`, in my case) instead of the global install is fixing it (as a way to avoid globally installing `detect-port`).

**Comment by lannonbr** [comment] 2020-05-22 00:41
This is a regression of #24065

Looks like it was an removed from the gatsby-recipes package.json, but it technically is used here in [recipes.js](https://github.com/gatsbyjs/gatsby/blob/e6e7463d26975c71a9be758a9c0b673e6a015ff3/packages/gatsby-cli/src/recipes.ts) of the cli so it should be then re-added to gatsby-cli's package.json.

**Comment by valentinradu** [comment] 2020-05-22 00:44
Same here. One quick fix is to install it locally:
```
yarn add gatsby-cli
yarn add detect-port
npx gatsby help
```

**Comment by ruiehq** [comment] 2020-05-22 00:51
> Same here. One quick fix is to install everything locally:
> 
> ```
> yarn add gatsby-cli
> yarn add detect-port
> npx gatsby help
> ```
> 
> or install `detect-port` globally:
> 
> ```
> yarn global add gatsby-cli
> yarn global add detect-port
> gatsby help
> ```

Yep this solves the issue for me. Thanks mate

**Comment by DrJulik** [comment] 2020-05-22 00:54
> yarn global add gatsby-cli
> yarn global add detect-port
> gatsby help


Did it for me. Thanks

**Comment by ansonlowzf** [comment] 2020-05-22 02:10
I tried uninstall gatsby-cli globally and re-install version 2.20.29. The problem persisted.
Will wait the team to update

**Comment by PerryMoen** [comment] 2020-05-22 02:39
> Same here. One quick fix is to install everything locally:
> 
> ```
> yarn add gatsby-cli
> yarn add detect-port
> npx gatsby help
> ```
> 
> or install `detect-port` globally:
> 
> ```
> yarn global add gatsby-cli
> yarn global add detect-port
> gatsby help
> ```

Thank you!!

**Comment by romulociro** [comment] 2020-05-22 03:07
for me solved using npm
npm  i -g gatsby-cli
npm i -g detect-port
gatsby help

**Comment by voyager1302** [comment] 2020-05-22 04:10
for me not solved with yarn or npm
code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/gatsby-cli/lib/recipes.js',
    '/usr/local/lib/node_modules/gatsby-cli/lib/create-cli.js',
    '/usr/local/lib/node_modules/gatsby-cli/lib/index.js'
  ]

**Comment by kainmaligno** [comment] 2020-05-22 04:36
thanks for all the solutions !! :rocket:

**Comment by danielricecodes** [comment] 2020-05-22 04:41
None of the above solutions worked on my Mac.  I just downgraded and I will wait for a new version before upgrading `gatsby-cli` again.

`npm i -g gatsby-cli@2.11.2`

Problem solved!

**Comment by CSIDPsetup** [comment] 2020-05-22 06:39
For me solved , try this:

    - npm install -g gatsby-cli
    - npm install -g detect-port

**Comment by Awais512** [comment] 2020-05-22 06:48
> 
> 
> for me solved using npm
> npm i -g gatsby-cli
> npm i -g detect-port
> gatsby help

This worked thanks

**Comment by freiksenet** [comment] 2020-05-22 07:38
Sorry about that! Fixed in #24334 and released as `gatsby-cli@2.12.33`

**Closed by freiksenet** 2020-05-22 07:38 UTC
Labels: status: triage needed, type: bug

**Comment by Soh4il** [comment] 2020-07-25 15:08
for me solved. try this:
`npm i -g gatsby-cli
npm i -g detect-port
gatsby help`

Thanks mate.

**Comment by Soh4il** [comment] 2020-07-25 15:12
for me solved. try this:

> npm i -g gatsby-cli
> npm i -g detect-port
> gatsby help

Thanks mate.
