### ISSUE TITLE
Cannot query field "bodyRichText" on "ContentfulBlogPost" using gatsby-source-contentful v4.6.4

### ISSUE THREAD

**Issue by justsilencia** [gatsbyjs/gatsby#33323] opened 2021-09-28 18:59 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description
** EDIT ** I created a repo [here](https://github.com/justsilencia/gatsby-contentful-rt-error) that reproduces this error even with the latest version of gatsby and gatsby-source-contentful

I'm using gatsby-source-contentful v4.6.4 in a blog I'm working on with gatsby.

I have blog posts already on contentful CMS, and I'm able to query everything EXCEPT my rich text successfully.

In the GraphiQL interface in the browser, or in the project itself, I get the following message when I try to use `bodyRichText`.

    **Cannot query field "bodyRichText" on type contentfulBlogPost **

Here is an example of a basic query I'm tring to use:

    {
      contentfulBlogPost(id: {eq: "4e95d2aa-f051-52f6-a906-279e5ea5a9a2"}) {
        bodyRichText {
	      raw
              references {
                     ... on ContentfulBlogPost {
			      contentful_id
                     }
          }
        }
      }
    }

I can do something even more simple, such as this:

    query MyQuery {
          contentfulBlogPost {
		id
                bodyRichText {
			raw
                  }
            }
     }

And I still get the same result.

### Reproduction Link

https://github.com/justsilencia/gatsby-contentful-rt-error

### Steps to Reproduce

1. Open graphIql or create query in component using gatsby-source-contentful v4.6.4
2. Try querying bodyRichText
3.
...

### Expected Result

To receive formatted rich text from gatsby-source-contentful v4.6.4 plugin via graphql query.

### Actual Result

Error: Cannot query field "bodyRichText" on type contentfulBlogPost

### Environment

```shell
System:
    OS: Windows 10 10.0.18363
    CPU: (6) x64 Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    gatsby: ^2.32.3 => 2.32.13 
    gatsby-image: ^2.11.0 => 2.11.0 
    gatsby-plugin-image: ^1.0.0 => 1.8.0 
    gatsby-plugin-manifest: ^2.12.0 => 2.12.1 
    gatsby-plugin-offline: ^3.10.0 => 3.10.2 
    gatsby-plugin-react-helmet: ^3.10.0 => 3.10.0 
    gatsby-plugin-sharp: ^2.14.1 => 2.14.4 
    gatsby-source-contentful: ^4.6.2 => 4.6.4 
    gatsby-source-filesystem: ^2.11.0 => 2.11.1 
    gatsby-transformer-remark: ^2.16.0 => 2.16.1 
    gatsby-transformer-sharp: ^2.12.0 => 2.12.1
```

**Comment by justsilencia** [comment] 2021-11-02 12:44
Has anyone been able to at least confirm this issue by chance?

**Comment by wardpeet** [comment] 2021-11-08 08:33
cc @axe312ger

**Comment by axe312ger** [comment] 2021-11-08 09:08
Do you have actual content in your Rich Text field? If not, you run into the bug we try to fix via #31385 

Also, v4.6.4 is for Gatsby v2. There have been significant bugfixes in the source plugin and Gatsby itself since that release. Please consider migrating to more up to date versions of the plugin & core.

**Comment by LekoArts** [comment] 2021-11-22 11:00
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Comment by justsilencia** [comment] 2021-11-25 00:55
@axe312ger and @LekoArts thanks for the reply. Apologies for my delayed response. For some reason github didn't notify me of your comments. 

In case you didn't notice, I already edited the post on 9/29/21 and added a link to a very simple repo I created that reproduces this issue **even with the latest version of gatsby**. So in response to your comment, unfortunately this issue persists well beyond 4.6.4. 

I would humbly ask that this issue be reopened, since it is unresolved and I have provided a reproducible example.

Thanks guys.

**Comment by axe312ger** [comment] 2021-11-25 07:40
I'll have a look. Thanks for the repo

**Comment by axe312ger** [comment] 2021-11-25 08:21
@justsilencia:

I installed your repo. It works fine for me:

<img width="1081" alt="Screenshot 2021-11-25 at 09 18 58" src="https://user-images.githubusercontent.com/1737026/143404772-62210856-2047-4ba6-8fe0-e2e6f07110c8.png">


You logs above show Gatsby v2. The version of gatsby-source-contentful that is compatible with Gatsby v2 might have some rich text bugs. Your example repo uses `"gatsby-source-contentful": "^5.14.0",` which should be alright for rendering rich text.

**Comment by justsilencia** [comment] 2021-11-25 23:58
@LekoArts Thanks for responding. However, I am very frustrated because I built the repo with a two queries: one that works (the one your seeing), and another I commented out that doesn't work. Somehow when I uploaded the repo, it didn't include any of the commented out content in the index.js file. 

It was supped to be a simple matter of commenting out the working query, and uncommenting the query with `bodyRichText`  that doesn't work.

My apologies. As you can see in the screenshot you posted, there is no `bodyRichText` declaration. To test my issue, in the pages/index.js file in the repo please simply replace this:

    allContentfulBlog {
                edges {
                  node {
                    id
                      blogPost {
                        raw
                    }
                  }
                }
              }

With this:

    contentfulBlogPost {
	id
            bodyRichText {
		raw
              }
        }

Again I apologize for screwing up the repo. I can't seem to catch a win with this issue.

Thanks again.

**Comment by axe312ger** [comment] 2021-11-26 11:16
No worries! Thats how the plugin works. Each of your Contentful fields will be turned into a Gatsby GraphQL field. 

I gonna update the README to make it more clear :)

**Closed** 2021-11-26 11:23 UTC
Labels: type: bug, status: awaiting author response, topic: source-contentful
