### ISSUE TITLE
WebpackError: TypeError: Cannot read property '__H' of undefined (gatsby-plugin-preact build time error)

### ISSUE THREAD

**Issue by urmik-zwt** [gatsbyjs/gatsby#34172] opened 2021-12-02 12:27 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

We are facing a build time "WebpackError: TypeError: Cannot read property '__H' of undefined" error when we add the gatsby-plugin-preact you can also see in the below image.  

**Screen Shot:**

![Screen Shot 2021-12-02 at 4 32 29 PM](https://user-images.githubusercontent.com/79259238/144417923-87dbb451-557b-44f1-80c2-3b68eec789f8.png)

**Package.json**

```json
 "dependencies": {
    "@artsy/fresnel": "^1.3.1",
    "@babel/core": "^7.12.9",
    "@reach/router": "^1.3.4",
    "@sentry/gatsby": "^6.3.1",
    "algoliasearch": "^4.11.0",
    "axios": "^0.21.1",
    "clsx": "^1.1.1",
    "consolidated-events": "^2.0.2",
    "document.contains": "^1.0.2",
    "gatsby": "^4.2.0",
    "gatsby-cli": "^4.2.0",
    "gatsby-plugin-algolia": "^0.24.0",
    "gatsby-plugin-algolia-search": "^0.5.7",
    "gatsby-plugin-image": "^2.2.0",
    "gatsby-plugin-less": "^6.2.0",
    "gatsby-plugin-manifest": "^4.2.0",
    "gatsby-plugin-offline": "^5.2.0",
    "gatsby-plugin-preact": "^6.2.0",
    "gatsby-plugin-prismic-previews": "^5.2.1",
    "gatsby-plugin-react-helmet": "^5.2.0",
    "gatsby-plugin-robots-txt": "^1.6.14",
    "gatsby-plugin-sass": "^5.2.0",
    "gatsby-plugin-sharp": "^4.2.0",
    "gatsby-plugin-sitemap": "^5.2.0",
    "gatsby-remark-images": "^6.2.0",
    "gatsby-remark-lazy-load": "^1.0.2",
    "gatsby-source-filesystem": "^4.2.0",
    "gatsby-source-prismic": "^5.2.2",
    "gatsby-transformer-remark": "^5.2.0",
    "gatsby-transformer-sharp": "^4.2.0",
    "lazysizes": "^5.2.2",
    "less": "^3.12.2",
    "node-sass": "^4.14.1",
    "object.values": "^1.1.2",
    "preact": "^10.6.2",
    "preact-render-to-string": "^5.1.19",
    "prismic-javascript": "^3.0.2",
    "prismic-reactjs": "^1.3.3",
    "prop-types": "^15.7.2",
    "rc-slider": "^9.7.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-helmet": "^6.1.0",
    "react-hook-form": "^6.15.5",
    "react-hook-form-input": "^1.1.10",
    "react-instantsearch-dom": "^6.10.3",
    "react-live-chat-loader": "^2.3.2",
    "react-share": "^4.4.0",
    "react-slick": "^0.28.1",
    "semantic-ui-css": "^2.4.1",
    "semantic-ui-react": "^2.0.3",
    "slick-carousel": "^1.8.1",
    "slugify": "^1.5.0",
    "url-pattern": "^1.0.3",
    "use-mobile-detect-hook": "^1.0.4",
    "validator": "^13.5.2",
    "vercel": "^21.3.3"
  },
```

**gatsby-config.js**

![Screen Shot 2021-12-02 at 5 36 58 PM](https://user-images.githubusercontent.com/79259238/144419108-6e74d930-262f-4b32-94bb-5b440da05b30.png)

### Reproduction Link

--

### Steps to Reproduce

1. npm install gatsby-plugin-preact preact preact-render-to-string.
2. Add gatsby-plugin-preact to gatsby-config.js.
3. gatsby clean && gatsby build.

### Expected Result

1. gatsby build should run without any errors.
2. the JS bundle build should be reduced in size.

### Actual Result

1. gatsby build shows errors related to the gatsby-plugin-preact.
2. no further result was shown. 

### Environment

```shell
System:                                                                                       ✔ │ 17:55:18 
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.17.3 - /usr/local/bin/node
    Yarn: 1.22.11 - /usr/local/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 96.0.4664.55
    Edge: 96.0.1054.41
    Firefox: 92.0
    Safari: 14.1.2
  npmGlobalPackages:
    gatsby-cli: 4.3.0
    gatsby: 3.9.1
```

**Comment by urmik-zwt** [comment] 2021-12-03 04:59
Also, I have added this issue in preact they asked if it's an issue on the gatsby-plugin-preact package side.
https://github.com/preactjs/preact/issues/3352#issuecomment-985079933

**Comment by fshowalter** [comment] 2021-12-06 14:54
It's hitting me too. https://github.com/fshowalter/franksmovielog.com/pull/541

**Comment by LekoArts** [comment] 2021-12-06 14:57
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by fshowalter** [comment] 2021-12-06 17:18
@LekoArts I believe https://github.com/preactjs/preact/issues/3277 is the underlying issue. I'm trying to suss out what introduced the problem, but it's a combination of preact + hooks. For me, it's hitting when I call useLocation on the vendored reach-router.

**Comment by fshowalter** [comment] 2021-12-06 18:02
@LekoArts suspect this can double as a minimal reproduction: https://github.com/gatsbyjs/gatsby/issues/33509

**Comment by LarsEjaas** [comment] 2021-12-06 18:41
@LekoArts Thanks for looking into this. I think I need a bit of help with the minimal reproduction if https://github.com/gatsbyjs/gatsby/issues/33509 isn't useful. 

The error I get is also pointing towards `Building static HTML failed for path "/offline-plugin-app-shell-fallback". `
Does this imply I need a minimal reproduction including  "gatsby-plugin-offline" or what do you think?

**Comment by fshowalter** [comment] 2021-12-06 18:47
The path is a red-herring, if you look at the call-stack it's failing in preact's hooks implementation. What are you doing in `bailfacile-gatsby-app/src/context.tsx` on line 348?

**Comment by fshowalter** [comment] 2021-12-08 18:57
@LekoArts minimal reproduction repo here: https://github.com/fshowalter/gatsby-preact-issue

**Comment by urmik-zwt** [comment] 2021-12-10 16:19
> Hi!
> 
> Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction](https://gatsby.dev/reproduction). This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.
> 
> If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction](https://gatsby.dev/reproduction) and we'll be able to take another look.
> 
> Thanks for using Gatsby! 💜

@LekoArts gatsby preact reproduction repo is here: https://github.com/urmik-zwt/gatsby-preact

**Comment by fshowalter** [comment] 2021-12-15 04:00
@LekoArts I went back and found the last working gatsby version with preact was 4.0.2. 4.1.0 broke it.

**Comment by LekoArts** [comment] 2021-12-16 08:01
I'm closing this in favor of https://github.com/gatsbyjs/gatsby/issues/34263 as it provides a better minimal reproduction.

**Closed by LekoArts** 2021-12-16 08:01 UTC
Labels: type: bug, status: needs reproduction, topic: plugins
