### ISSUE TITLE
Generating development SSR bundle failed: Unexpected Token

### ISSUE THREAD

**Issue by stevepepple** [gatsbyjs/gatsby#32397] opened 2021-07-16 23:12 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Seemingly out of nowhere, I've stared to see the following Webpack error during `gatsby develop`.

Looks like an ESM issue with import statements. 

```
success run page queries - 0.626s - 3/3 4.79/s
onCreateWebpackConfig stage  develop-html
success Caching HTML renderer compilation - 0.014s

 ERROR #98123  WEBPACK

Generating development SSR bundle failed

Unexpected token (2:7)

File: node_modules/@babel/runtime/helpers/esm/possibleConstructorReturn.js:2:7

not finished Building development bundle - 2.409s

error Command failed with exit code 1.
```

### Reproduction Link

https://github.com/Studio123ca/vibemap.com

### Steps to Reproduce

1. Ran yarn; gatsby clean
2. Ran `gatsby develop`
...

### Expected Result

SSR starts up

### Actual Result

Error above

### Environment

```shell
System:
    OS: macOS 11.4
    CPU: (8) x64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.10.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 90.0
    Safari: 14.1.1
  npmPackages:
    gatsby: latest => 3.9.1
    gatsby-background-image: ^1.5.0 => 1.5.3
    gatsby-cli: latest => 3.9.0
    gatsby-core-utils: next => 2.11.0-next.0
    gatsby-gravityforms-component: ^3.1.0 => 3.1.0
    gatsby-image: next => 3.11.0-next.0
    gatsby-link: ^3.3.0 => 3.9.0
    gatsby-plugin-build-date: ^1.0.0 => 1.0.0
    gatsby-plugin-bundle-stats: ^3.0.1 => 3.0.1
    gatsby-plugin-client-side-redirect: ^1.1.0 => 1.1.0
    gatsby-plugin-facebook-pixel: ^1.0.5 => 1.0.8
    gatsby-plugin-feed: ^3.7.0-next.0 => 3.9.0
    gatsby-plugin-google-analytics: ^3.0.0 => 3.9.0
    gatsby-plugin-google-tagmanager: ^3.0.0 => 3.9.0
    gatsby-plugin-image: next => 1.11.0-next.0
    gatsby-plugin-loadable-components-ssr: ^2.1.0 => 2.1.0
    gatsby-plugin-manifest: ^3.2.0 => 3.9.0
    gatsby-plugin-netlify: ^3.3.0-next.0 => 3.9.0
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0
    gatsby-plugin-perf-budgets: ^0.0.18 => 0.0.18
    gatsby-plugin-purgecss: ^6.0.2 => 6.0.2
    gatsby-plugin-react-helmet: next => 4.11.0-next.0
    gatsby-plugin-react-helmet-canonical-urls: ^1.4.0 => 1.4.0
    gatsby-plugin-react-i18next: ^1.1.1 => 1.1.1
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.1
    gatsby-plugin-remove-fingerprints: ^0.0.2 => 0.0.2
    gatsby-plugin-resolve-src: ^2.1.0 => 2.1.0
    gatsby-plugin-robots-txt: ^1.5.1 => 1.6.8
    gatsby-plugin-sass: ^4.0.0 => 4.9.0
    gatsby-plugin-sass-resources: ^2.0.0 => 2.0.0
    gatsby-plugin-sharp: next => 3.11.0-next.0
    gatsby-plugin-sitemap: ^3.0.0 => 3.3.0
    gatsby-plugin-split-css: ^2.0.0 => 2.0.0
    gatsby-plugin-styled-components: ^4.6.0 => 4.9.0
    gatsby-plugin-transition-link: ^1.18.0 => 1.20.5
    gatsby-plugin-use-query-params: ^1.0.1 => 1.0.1
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.22 => 1.1.24
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.5 => 1.0.5
    gatsby-react-router-scroll: ^4.5.0-next.0 => 4.9.0
    gatsby-source-filesystem: ^3.2.0 => 3.9.0
    gatsby-source-gravityforms: ^1.0.15 => 1.0.17
    gatsby-source-wordpress: next => 5.11.0-next.0
    gatsby-transformer-sharp: next => 3.11.0-next.0
```

### Config Flags

I've tried a few different configs to see if that makes a difference. 

    FAST_DEV: true,
    DEV_SSR: true,
    PARALLEL_SOURCING: true,
    PRESERVE_FILE_DOWNLOAD_CACHE: false,
    PRESERVE_WEBPACK_CACHE: false

**Comment by LekoArts** [comment] 2021-07-19 08:11
Hi!

The link to your reproduction is not working. Please also provide a [minimal reproduction][reproduction] that is not your actual project but based off e.g. our `hello-world` starter or after you used `npm init`.

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-07-27 08:35
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-07-27 08:35 UTC
Labels: status: needs reproduction, type: bug
