### ISSUE TITLE
How To Guide: Adding Search with Meilisearch

### ISSUE THREAD

**Issue by shivaylamba** [gatsbyjs/gatsby#34884] opened 2022-02-21 07:18 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Summary

Add a how-to guide for integrating Meilisearch with Gatsby. 

Meilisearch has a [Gatsby plugin integration.](https://github.com/meilisearch/gatsby-plugin-meilisearch) and we have created a  how-to guide to be able to integrate Meilsearch in a Gatsby project.

**Comment by tyhopp** [comment] 2022-02-21 08:40
Hi @shivaylamba, I'll close this since it's not a bug report. We can track this in the PR itself.

**Closed by tyhopp** 2022-02-21 08:40 UTC
Labels: type: question or discussion, type: documentation, status: triage needed
