### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by ramojej** [gatsbyjs/gatsby#30780] opened 2021-04-09 09:39 UTC
## Description

Hey, everyone. So I updated these packages from
```
"gatsby": "^3.1.1",
"gatsby-plugin-image": "^1.0.0",
"gatsby-plugin-sharp": "^3.0.0",
"gatsby-source-wordpress": "^5.2.0-alpha-wordpress.34"
``` 

to: 
```
"gatsby": "^3.2.1",
"gatsby-plugin-image": "^1.2.1",
"gatsby-plugin-sharp": "^3.2.1",
"gatsby-source-wordpress": "^5.2.2",
``` 

Now I'm having [this error](https://share.getcloudapp.com/mXupAvOz), that I don't know where or how to trace, when I run gatsby build. The same error can be seen in Netlify. There are no errors or warnings in development mode though.

I tried reverting back all the updates I've done, but the error still exists.

Two other people are having the same problem in the Discord channel. 

### Steps to reproduce

I just updated those packages. Here's the repo https://github.com/ramojej/dd-source-technologies

### Expected result

Gatsby build successfully

### Actual result

failed Building production JavaScript and CSS bundles

### Environment

```
System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    npm: 6.12.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.114
    Safari: 13.0.4
  npmPackages:
    gatsby: ^3.2.1 => 3.2.1 
    gatsby-background-image: ^1.3.1 => 1.3.1 
    gatsby-image: ^2.10.0 => 2.10.0 
    gatsby-omni-font-loader: ^1.3.0 => 1.3.0 
    gatsby-plugin-anchor-links: ^1.2.0 => 1.2.0 
    gatsby-plugin-apollo: ^3.0.2 => 3.0.2 
    gatsby-plugin-image: ^1.2.1 => 1.2.1 
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0 
    gatsby-plugin-no-index: ^1.0.2 => 1.0.2 
    gatsby-plugin-offline: ^4.0.0 => 4.0.0 
    gatsby-plugin-postcss: ^4.0.0 => 4.0.0 
    gatsby-plugin-preact: ^5.2.0 => 5.2.0 
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-scroll-reveal: 0.0.7 => 0.0.7 
    gatsby-plugin-sharp: ^3.2.1 => 3.2.1 
    gatsby-source-filesystem: ^3.2.0 => 3.2.0 
    gatsby-source-wordpress: ^5.2.2 => 5.2.2 
    gatsby-transformer-sharp: ^3.2.0 => 3.2.0 
  npmGlobalPackages:
    gatsby-cli: 3.0.0
```

**Comment by antonborysov** [comment] 2021-04-09 14:54
I'm having the same issue. It also started coming up once I updated gatsby from 3.1.0 to 3.2.1, and some related packages - gatsby-cli, gatsby-plugin-sharp, etc.

My environment:
<img width="413" alt="gatsby-env" src="https://user-images.githubusercontent.com/25830178/114198749-56f6fc00-995c-11eb-8503-5b1740006c49.png">

**Comment by kamit-transient** [comment] 2021-04-09 15:42
I am migrating my codebase from gatsby V2 to V3 () and like others, I am also receiving the same error.

Also, I can confirm that I am not using `split()` function anywhere in my codebase so it must be being thrown by some `gatsby plugins`


When I run `gatsby build --verbose` , below error are being thrown(Please package.json etc after error):
Below are error snippets:


```
yarn build --verbose
yarn run v1.22.10
$ gatsby build --verbose
verbose set gatsby_log_level: "verbose"
verbose set gatsby_executing_command: "build"
verbose loading local command from: /home/bapujiom/Desktop/repo/new_code_base/node_modules/gatsby/dist/commands/build.js
verbose running command: build
success open and validate gatsby-configs - 0.244s
success load plugins - 0.802s
success onPreInit - 0.072s
success initialize cache - 0.016s
success copy gatsby files - 0.187s
success onPreBootstrap - 0.065s
success createSchemaCustomization - 0.012s


 ERROR 

(node:7991) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated

success Creating local images for Mdx - 3.243s
verbose Checking for deleted pages
verbose Deleted 0 pages
verbose Found 0 changed pages
success Checking for changed pages - 0.005s
success source and transform nodes - 17.778s
success building schema - 0.669s
isProd true
warn The enum value "MdxFieldsEnum.fields___year" is deprecated. Sorting on fields that need arguments to resolve is deprecated.
info Total nodes: 556, SitePage nodes: 87 (use --verbose for breakdown)
verbose Number of node types: 10. Nodes per type: SitePage: 87, SitePlugin: 57, Site: 1, SiteBuildMetadata: 1, Directory: 15, File: 194, ImageSharp: 76, Mdx: 115, ContentYear: 9,
LocalSearchPages: 1
success createPages - 1.291s
verbose Checking for deleted pages
verbose Deleted 0 pages
verbose Found 86 changed pages
success Checking for changed pages - 0.004s
success createPagesStatefully - 0.126s
success update schema - 0.105s
success onPreExtractQueries - 0.001s
success extract queries from components - 1.555s
warn The GraphQL query in the non-page component "/home/bapujiom/Desktop/repo/new_code_base/src/templates/ArticleListTemplate.jsx" will not be run.
warn The GraphQL query in the non-page component "/home/bapujiom/Desktop/repo/new_code_base/src/templates/ArticleTemplate.jsx" will not be run.
warn The GraphQL query in the non-page component "/home/bapujiom/Desktop/repo/new_code_base/src/templates/CategoryAndArticlesTemplate.jsx" will not be run.
warn The GraphQL query in the non-page component "/home/bapujiom/Desktop/repo/new_code_base/src/templates/LocationAndArticlesTemplate.jsx" will not be run.
warn The GraphQL query in the non-page component "/home/bapujiom/Desktop/repo/new_code_base/src/templates/TagAndArticlesTemplate.jsx" will not be run.
warn The GraphQL query in the non-page component "/home/bapujiom/Desktop/repo/new_code_base/src/templates/TagAndNewsTemplate.jsx" will not be run.
warn The GraphQL query in the non-page component "/home/bapujiom/Desktop/repo/new_code_base/src/templates/YearAndArticlesTemplate.jsx" will not be run.
Exported queries are only executed for Page components. It's possible you're
trying to create pages in your gatsby-node.js and that's failing for some
reason.

If the failing component(s) is a regular component and not intended to be a page
component, you generally want to use a <StaticQuery> (https://gatsbyjs.org/docs/static-query)
instead of exporting a page query.

If you're more experienced with GraphQL, you can also export GraphQL
fragments from components and compose the fragments in the Page component
query and pass data down into the child component — https://graphql.org/learn/queries/#fragments
success write out redirect data - 0.003s
success Build manifest and related icons - 0.167s
success onPostBootstrap - 0.173s
info bootstrap finished - 26.392s
warn The enum value "MdxFieldsEnum.fields___year" is deprecated. Sorting on fields that need arguments to resolve is deprecated.
Queried in /home/bapujiom/Desktop/repo/new_code_base/src/components/common/yearAndLocation/yearPanel.js
success run static queries - 1.763s - 11/11 6.24/s
success run page queries - 8.755s - 88/88 10.05/s
success write out requires - 0.018s
failed Building production JavaScript and CSS bundles - 97.258s

 ERROR #98123  WEBPACK

Generating JavaScript bundles failed

Cannot read property 'split' of undefined


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```


Below is my `package.json`

```
{
  "name": "Replacing it for cobc",
  "version": "1.0.0",
  "private": true,
  "description": "Replacing it for cobc",
  "author": "Replacing it for cobc",
  "keywords": [
    "gatsby"
  ],
  "scripts": {
    "develop": "gatsby develop",
    "start": "gatsby develop",
    "build": "gatsby build",
    "serve": "gatsby serve",
    "clean": "gatsby clean"
  },
  "license": "0BSD",
  "resolutions": {
    "graphql": "^15.4.0",
    "graphql-compose": "^7.25.0",
    "webpack": "^5.24.2"
  },
  "dependencies": {
    "@loadable/component": "^5.14.1",
    "@material-ui/core": "^4.11.2",
    "@material-ui/icons": "^4.11.2",
    "@material-ui/lab": "^4.0.0-alpha.57",
    "@mdx-js/mdx": "^1.6.22",
    "@mdx-js/react": "^1.6.22",
    "@raae/gatsby-remark-oembed": "^0.1.1",
    "@tailwindcss/typography": "^0.4.0",
    "autoprefixer": "^10.1.0",
    "color": "^3.1.3",
    "dotenv": "^8.2.0",
    "gatsby": "^3.2.1",
    "gatsby-image": "^3.2.0",
    "gatsby-plugin-google-analytics": "^3.2.0",
    "gatsby-plugin-image": "^1.2.1",
    "gatsby-plugin-local-search": "^2.0.0",
    "gatsby-plugin-manifest": "^3.2.0",
    "gatsby-plugin-material-ui": "^3.0.1",
    "gatsby-plugin-mdx": "^2.2.0",
    "gatsby-plugin-netlify-cms": "^5.2.0",
    "gatsby-plugin-netlify-cms-paths": "^1.3.0",
    "gatsby-plugin-offline": "^4.2.0",
    "gatsby-plugin-postcss": "^4.2.0",
    "gatsby-plugin-react-helmet": "^4.2.0",
    "gatsby-plugin-robots-txt": "^1.5.3",
    "gatsby-plugin-sharp": "^3.2.1",
    "gatsby-plugin-sitemap": "^3.2.0",
    "gatsby-remark-autolink-headers": "^3.2.0",
    "gatsby-remark-embedder": "^4.1.0",
    "gatsby-remark-external-links": "^0.0.4",
    "gatsby-remark-images": "^4.2.0",
    "gatsby-source-filesystem": "^3.2.0",
    "gatsby-transformer-remark": "^3.2.0",
    "gatsby-transformer-sharp": "^3.2.0",
    "knuth-shuffle": "^1.0.8",
    "netlify-cms-app": "^2.14.6",
    "node-vibrant": "^3.2.1-alpha.1",
    "nprogress": "^0.2.0",
    "postcss": "^8.2.1",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-helmet": "^6.1.0",
    "react-lazy-load": "^3.1.13",
    "react-share": "^4.3.1",
    "react-slick": "^0.28.1",
    "react-use-flexsearch": "^0.1.1",
    "slick-carousel": "^1.8.1",
    "styled-components": "^5.2.1",
    "tailwindcss": "^2.0.2",
    "winston": "^3.3.3",
    "winston-daily-rotate-file": "^4.5.0"
  },
  "devDependencies": {
    "husky": "^6.0.0",
    "webpack": "^5.31.0"
  },
  "engines": {
    "node": "v12.22.1"
  }
}
```

OS: `Ubuntu 20.4`

**Comment by malembetirick** [comment] 2021-04-10 01:33
Hello,
I'm facing same issue since 3 days: 
failed Building production JavaScript and CSS bundles - 21.356s
 ERROR #98123  WEBPACK
Generating JavaScript bundles failed
Cannot read property 'split' of undefined.

Below, my package.json
{
  "name": "app",
  "private": true,
  "description": "app",
  "version": "0.1.0",
  "author": "ap",
  "dependencies": {
    "babel-plugin-styled-components": "^1.12.0",
    "bootstrap": "^4.5.3",
    "gatsby": "^3.2.1",
    "gatsby-plugin-facebook-pixel": "^1.0.5",
    "gatsby-plugin-google-tagmanager": "^3.0.0",
    "gatsby-plugin-image": "^1.1.0",
    "gatsby-plugin-mailchimp": "^5.2.2",
    "gatsby-plugin-manifest": "^3.0.0",
    "gatsby-plugin-offline": "^4.0.0",
    "gatsby-plugin-react-helmet": "^4.0.0",
    "gatsby-plugin-robots-txt": "^1.5.5",
    "gatsby-plugin-sass": "^4.0.2",
    "gatsby-plugin-sharp": "^3.2.1",
    "gatsby-plugin-sitemap": "^3.0.0",
    "gatsby-plugin-styled-components": "^4.0.0",
    "gatsby-source-filesystem": "^3.0.0",
    "gatsby-transformer-sharp": "^3.2.0",
    "node-sass": "^5.0.0",
    "prop-types": "^15.7.2",
    "react": "^16.8.0",
    "react-dom": "^16.8.0",
    "react-helmet": "^6.1.0",
    "react-icons": "^4.2.0",
    "react-is": "^17.0.1",
    "react-number-format": "^4.4.4",
    "react-slick": "^0.28.0",
    "react-toastify": "^7.0.3",
    "reactstrap": "^8.8.1",
    "reactstrap-form-fields": "^1.0.8",
    "reactstrap-json-nav": "^1.0.2",
    "slick-carousel": "^1.8.1",
    "styled-components": "^5.2.1"
  },
  "devDependencies": {
    "prettier": "^2.2.1"
  },
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write \"**/*.{js,jsx,json,md}\"",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\" && exit 1"
  },
  "engines": {
    "node": "12.21.0",
    "npm": "7.9.0"
  },
  "resolutions": {
    "graphql": "15.5.0"
  }
}

**Comment by ramojej** [comment] 2021-04-10 02:40
I tried reverting the packages back, deleting package-lock.json and node_modules. Then I run npm install and gatsby build the error still exist.

**Comment by KyleAMathews** [comment] 2021-04-10 03:09
Can one of you share a reproduction I can run locally to see what's happening? E.g. @ramojej could you share your WP URL so I can run your site?

**Comment by KyleAMathews** [comment] 2021-04-10 03:12
You can also try adding this to `./node_m

```diff

 const transformWebpackError = (stage, webpackError) => {
+  console.log(webpackError)
   var _castedWebpackError$e,
```

**Comment by KyleAMathews** [comment] 2021-04-10 03:20
Thanks @ramojej for giving me access.

This is the stack trace:

```
TypeError: Cannot read property 'split' of undefined
    at formatMessage (/private/tmp/dd-source-technologies/node_modules/react-dev-ut
ils/formatWebpackMessages.js:18:23)
    at Array.map (<anonymous>)
    at formatWebpackMessages (/private/tmp/dd-source-technologies/node_modules/reac
t-dev-utils/formatWebpackMessages.js:107:43)
    at reportWebpackWarnings (/private/tmp/dd-source-technologies/node_modules/gats
by/dist/utils/webpack-error-utils.js:149:39)
    at build (/private/tmp/dd-source-technologies/node_modules/gatsby/src/commands/
build.ts:132:7)
```

Looking at react-dev-utils issues, it looks like we hit this bug: https://github.com/facebook/create-react-app/issues/9880

**Comment by kamit-transient** [comment] 2021-04-10 08:38
**I am completely unable to proceed further without this fix**. Actively looking for this PR by @KyleAMathews to be merged in the **` next minor release`**

**Comment by krisswiltshirepz** [comment] 2021-04-10 15:36
Having the same problem when upgrading from V2 to V3. I fixed the breaking changes, but this one has me stumped.

Tried a few different versions of `webpack` without any luck.

**Error**

```
ERROR #98123  WEBPACK

Generating JavaScript bundles failed

Cannot read property 'split' of undefine
```

**Build log**

```
yarn run v1.22.10
$ gatsby clean && gatsby build
info Deleting .cache, public,
/Users/[hidden]/[hidden]/[hidden]/node_modules/.cache/babel-loader,
/Users/[hidden]/[hidden]/[hidden]/node_modules/.cache/terser-webpack-plugin
info Successfully deleted directories

[netlify-cms-backend-fs] (version: 0.4.4)
[netlify-cms-backend-fs] root path is [hidden]
success open and validate gatsby-configs - 0.143s
success load plugins - 1.387s
success onPreInit - 0.034s
success initialize cache - 0.005s
success copy gatsby files - 0.070s
success onPreBootstrap - 0.014s
success createSchemaCustomization - 0.013s
success Checking for changed pages - 0.005s
success source and transform nodes - 2.161s
success building schema - 0.555s
Skipping young
Skipping roundup
Creating 3 pages
Skipping expert
Skipping categories
Creating 56 questions
info Total nodes: 774, SitePage nodes: 60 (use --verbose for breakdown)
success createPages - 0.099s
success Checking for changed pages - 0.001s
success createPagesStatefully - 0.074s
success update schema - 0.053s
success onPreExtractQueries - 0.001s
success extract queries from components - 0.633s
success write out redirect data - 0.003s
success Build manifest and related icons - 0.150s
success onPostBootstrap - 0.157s
info bootstrap finished - 8.132s
warn [gatsby-transformer-sharp] The "fixed" and "fluid" resolvers are now
deprecated. Switch to "gatsby-plugin-image" for better performance and a simpler
API. See https://gatsby.dev/migrate-images to learn how.
success run static queries - 11.367s - 6/6 0.53/s
success run page queries - 58.306s - 64/64 1.10/s
success write out requires - 0.009s
failed Building production JavaScript and CSS bundles - 35.554s

 ERROR #98123  WEBPACK

Generating JavaScript bundles failed

Cannot read property 'split' of undefined


error Command failed with exit code 1.
```


**My package.json**

```{
  "name": "app",
  "private": true,
  "description": "app",
  "version": "1.0.0",
  "author": "app",
  "dependencies": {
    "@gatsby-contrib/gatsby-plugin-elasticlunr-search": "^3.0.2",
    "babel-plugin-styled-components": "^1.10.6",
    "gatsby": "^3.2.1",
    "gatsby-image": "^3.2.0",
    "gatsby-plugin-google-analytics": "^3.2.0",
    "gatsby-plugin-manifest": "^3.2.0",
    "gatsby-plugin-netlify": "^3.2.0",
    "gatsby-plugin-netlify-cms": "^5.2.0",
    "gatsby-plugin-offline": "^4.2.0",
    "gatsby-plugin-react-helmet": "^4.2.0",
    "gatsby-plugin-robots-txt": "^1.5.5",
    "gatsby-plugin-sharp": "^3.2.1",
    "gatsby-plugin-sitemap": "^3.2.0",
    "gatsby-plugin-styled-components": "^4.2.0",
    "gatsby-remark-copy-linked-files": "^3.2.0",
    "gatsby-remark-images": "^4.2.0",
    "gatsby-remark-relative-images": "^2.0.2",
    "gatsby-source-filesystem": "^3.2.0",
    "gatsby-transformer-remark": "^3.2.0",
    "gatsby-transformer-sharp": "^3.2.0",
    "js-cookie": "^2.2.1",
    "moment": "^2.24.0",
    "netlify-cms-app": "^2.9.7",
    "netlify-cms-backend-fs": "^0.4.4",
    "netlify-identity-widget": "^1.9.1",
    "nuka-carousel": "^4.7.7",
    "prop-types": "^15.7.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-grid-system": "^7.1.2",
    "react-helmet": "^6.1.0",
    "react-moment-proptypes": "^1.8.1",
    "react-player": "^2.9.0",
    "react-slick": "^0.28.1",
    "react-styled-box": "^1.3.0",
    "rehype-react": "^6.2.0",
    "remark-parse": "^9.0.0",
    "remark-slug": "^6.0.0",
    "replace-ext": "^2.0.0",
    "slick-carousel": "^1.8.1",
    "styled-components": "^5.2.3",
    "unified": "^8.4.0",
  },
  "devDependencies": {
    "@testing-library/jest-dom": "^5.11.10",
    "@testing-library/react": "^11.2.6",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^26.6.3",
    "babel-preset-gatsby": "^1.2.0",
    "eslint": "^7.23.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-react": "^7.23.2",
    "husky": "4.3.8",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^26.6.3",
    "lint-staged": "^10.5.4",
    "prettier": "^2.2.1",
    "react-test-renderer": "^17.0.2",
    "webpack-cli": "^4.6.0"
  },
  "license": "MIT",
  "pre-push": "test",
  "scripts": {
    "build": "gatsby clean && gatsby build",
    "format": "prettier --write \"**/*.{js,jsx,json,md}\"",
    "lint": "eslint --ignore-path .gitignore . --ext js --ext jsx",
    "lint:fix": "yarn lint --fix",
    "start": "gatsby clean && gatsby develop",
    "serve": "gatsby serve",
    "kill": "rm -rf node_modules",
    "test": "jest"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/app/someapp"
  }
}
```

**Comment by KyleAMathews** [comment] 2021-04-10 18:05
To unstick people until the fix gets published, I published a canary version with the fix. Install `gatsby@webpack-split-fix` into your problem and things should work. Lemme know if you still run into any problems.

**Comment by krisswiltshirepz** [comment] 2021-04-10 21:57
@KyleAMathews Works like a charm! 🙏

**Comment by ramojej** [comment] 2021-04-10 23:51
@KyleAMathews Thanks!!!

**Closed** 2021-04-12 17:12 UTC
Labels: topic: webpack/babel, type: bug

**Comment by tsamantanis** [comment] 2022-08-29 12:16
@KyleAMathews  Thanks! I am also getting this issue on gatsby v4.21.1 . Any chance we can get a canary version with the fix on v4 ?
