### ISSUE TITLE
gatsby-plugin-mdx "window not defined" error rendering html in ___graphql query

### ISSUE THREAD

**Issue by fionawhim** [gatsbyjs/gatsby#17175] opened 2019-08-29 12:16 UTC
## Description

The `gatsby-plugin-mdx` plugin cannot generate its `html` node property when querying via GraphiQL.

The following error prints to console:

```
ReferenceError: window is not defined
    at evalmachine.<anonymous>:5:41
    at evalmachine.<anonymous>:794:10
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at ContextifyScript.Script.runInNewContext (vm.js:65:15)
    at module.exports (/Users/fin/Source/my-themed-blog/node_modules/eval/eval.js:73:12)
    at afterEmit (/Users/fin/Source/my-themed-blog/node_modules/gatsby-plugin-mdx/utils/render-html.js:81:22)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/fin/Source/my-themed-blog/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:20:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/fin/Source/my-themed-blog/node_modules/tapable/lib/Hook.js:154:20)
    at asyncLib.forEach.err (/Users/fin/Source/my-themed-blog/node_modules/webpack/lib/Compiler.js:358:27)
    at /Users/fin/Source/my-themed-blog/node_modules/neo-async/async.js:2830:7
```

and “renderMdxBody was unavailable when rendering html” errors appear in the GraphQL response.

I ran into this issue when using GraphiQL to craft the query for my blog’s RSS feed.

Based on a bit of digging into the `utils/render-html.js` code, it seems that `gatsby-plugin-mdx` is sourcing a browser bundle for generating the HTML on the server (where `window` is obvs undefined). I wasn’t able to track down exactly what in the bundle is making an un-checked access to `window`, though I suspect it might be `react-hot-loader`.

I don’t know enough about Gatsby bundling and whether it’s even feasible to run an SSR-oriented bundle in development mode.

FWIW when I used a similar GraphQL query to render rss.xml using `gatsby build` the html generated as expected with no errors.

### Steps to reproduce

1. `gatsby new my-themed-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme`
1. `cd my-themed-blog; yarn develop`
1. Visit `http://localhost:8000/___graphql`
1. Run the following query:

```graphql
query MyQuery {
  allMdx {
    nodes {
      html
    }
  }
}
```

### Expected result

The HTML for the posts should be returned in the `html` field of the GraphQL response.

If that’s infeasible, perhaps a dummy response in the `html` field that indicates that the query is correct and would work with `gatsby build`, it’s just that the plugin can’t server-side render HTML in development mode.

### Actual result

Console shows the `window is not defined` error mentioned above, as well as the following error:

```
gatsby-plugin-mdx: renderMdxBody was unavailable when rendering html.
>> This is a bug.
```

The GraphQL response in the browser shows a similar error.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4288U CPU @ 2.60GHz
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 8.16.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 68.0.2
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.13.73 => 2.13.73
    gatsby-theme-blog: ^1.0.2 => 1.0.2

**Comment by LekoArts** [comment] 2019-08-29 12:50
Hi!

I'm so free to copy my comment from a duplicate issue https://github.com/gatsbyjs/gatsby/issues/16706

> You need to use [body](https://jhr25.sse.codesandbox.io/___graphql?query=query%20MyQuery%20%7B%0A%20%20allMdx%20%7B%0A%20%20%20%20nodes%20%7B%0A%20%20%20%20%20%20body%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&operationName=MyQuery) instead of `html` as afaik the latter is only there for usage in `gatsby-plugin-feed`.

> The guide is also telling the reader to use `body` :)
https://www.gatsbyjs.org/docs/mdx/programmatically-creating-pages/#make-a-template-for-your-posts

So yeah, the `html` node is working as intended, an example for the rss feed is [here](https://github.com/LekoArts/gatsby-themes/blob/master/www/src/utils/feed.js#L14-L26).

Hope that helps -- closing it as answered!

**Closed by LekoArts** 2019-08-29 12:50 UTC
Labels: topic: MDX

**Comment by fionawhim** [comment] 2019-08-29 12:57
@LekoArts I understand that I need to use `body` in the HTML that’s actually on my post pages. I was confused by this behavior when I was building the GraphQL query that was going to power my RSS feed, where `html` is appropriate.

Is there a seam somewhere in the MDX plugin where this situation (asking for `html` in a non-SSR environment) could be detected and a clearer error thrown?

I found it surprising that a query would work when calling `gatsby build` and not when using GraphiQL.

**Comment by LekoArts** [comment] 2019-08-29 13:08
Ok, understandable! The current errors are thrown by webpack and/or GraphiQL, that's why they're verbose, but not necessarily helpful for some people.

We're always happy to throw more helpful errors, so would you like to open a new issue asking for a clearer error when using `html` outside of SSR/`gatsby build` context? That would be awesome! The potential error message could say tell people when to use this, and that they probably want to use `body` instead.

**Comment by fionawhim** [comment] 2019-08-29 14:01
Cool! I may be able to hack out a solution and put it up for PR.

What do you think about, instead of an error, returning a constant string like `"<strong>WARNING:</strong> MDX <code>html</code> field is not designed to be rendered by the development server. Did you mean <code>body</code>? (Note: this field will work correctly when running <code>gatsby build</code>.)"`

The value there is that you can see that it’s a correct query (and can test your HTML tag handling) in development mode, while it still should be obvious that you are not doing the right thing.

**Comment by LekoArts** [comment] 2019-08-29 15:15
I think it's best to put this into its own issue and discuss the right approach there 👍 	This way the rest of the team and community members can better discuss about the reasonable solution. Thanks so much!

**Comment by brandonpittman** [comment] 2020-05-02 13:06
I getting this error during `Gatsby build` and I'm not query `html` anywhere on my site.

**Comment by janosh** [comment] 2020-05-06 20:25
@brandonpittman I'm having the exact same problem even during `gatsby develop`.
