### ISSUE TITLE
www.gatsbyjs.org navigation broken if cookies disabled

### ISSUE THREAD

**Issue by gswirrl** [gatsbyjs/gatsby#10378] opened 2018-12-10 08:35 UTC
The main site level navigation and 'Get Started' button all fail to load a new page with cookies disabled (tested in latest Safari, Chrome and FF) - the hash in the address bar changes, but that's all that happens.

The console shows errors like

```
Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at t.n.shouldRenderStaticHTML
```

**Comment by jonniebigodes** [comment] 2018-12-10 15:14
@gswirrl i'm closing this issue as it's a duplicate of another issue you created namely #10266 . I would like for you to be a little patient with the team and give them time to investigate the problem and come up with a way to solve this, sounds good?

**Comment by sidharthachatterjee** [comment] 2019-01-21 14:23
This was fixed in https://github.com/gatsbyjs/gatsby/pull/10224

**Closed by sidharthachatterjee** 2019-01-21 14:23 UTC
Labels: status: confirmed
