### ISSUE TITLE
Default Layouts don't work with gatsby-plugin-mdx

### ISSUE THREAD

**Issue by motleydev** [gatsbyjs/gatsby#19408] opened 2019-11-10 23:38 UTC
Useful Links:
  - Documentation: https://www.gatsbyjs.org/packages/gatsby-plugin-mdx/?=file-s#default-layouts

## Summary
I've tried multiple ways around this and mapping `source-filesystem` names to `defaultLayouts` does not work in any of my projects.

## Relevant information

Source multiple directories, in my case one is generically `/pages` and another is `/pages/other-folder` and they always take the defaultPage as the template. I finally switched to sourcing /other-folder outside of the auto generated /pages directory.

**Comment by sever1an** [comment] 2019-11-11 00:03
At least a while ago, the order that paths were added to `gatsby-source-filesystem` affected which instance they would belong to, although I do not recall if the more specific paths had to go first or last. Since layout selection is based on the instance id, changing the definition order in `gatsby-config` might help.

**Comment by LekoArts** [comment] 2019-11-11 11:22
Duplicate of https://github.com/gatsbyjs/gatsby/issues/17808

**Closed by LekoArts** 2019-11-11 11:22 UTC
