### ISSUE TITLE
Cannot find module 'gatsby-cli/lib/reporter'

### ISSUE THREAD

**Issue by Hubert-Zhu** [gatsbyjs/gatsby#26463] opened 2020-08-14 15:22 UTC
#8413  Description

Develop Error: Cannot find module 'gatsby-cli/lib/reporter'

### Steps to reproduce

I buy a new laptop that use Windows 10.
I just downloaded NodeJS v12.18.3
I followed the tutorial on https://www.gatsbyjs.com/tutorial/part-zero/
When I run "Gatsby develop" , there is a error 

### Expected result

Should run successfully

### Actual result

Cannot find module 'gatsby-cli/lib/reporter'

### Environment

Both Node and Gatsby are latest version
Gatsby CLI Vesion : 2.12.87
Gatsby version: 2.24.41 
Node Version:  12.18.3

**Comment by Hubert-Zhu** [comment] 2020-08-14 15:50
I saw someone mentioned this issue 3-5 days ago. A contributor said it has been fixed, but it still does not work well for my local. Did I do any mistake, I am sure that I followed the instruction carefully.

**Comment by Hubert-Zhu** [comment] 2020-08-14 16:14
OK find the reason. Could someone fix the demo for starter? https://github.com/gatsbyjs/gatsby-starter-hello-world.git. The Gatsby version for this one is still 2.24.41, which is the version with the reporter problem .

**Comment by vladar** [comment] 2020-08-14 21:22
It is a duplicate of this issue: #26345

You need to upgrade from `gatsby@2.24.41` to `gatsby@^2.24.42`

Try deleting `package-lock.json` and run `npm install` again (if you use yarn - delete `yarn.lock` and run `yarn`). If the problem occurs in the CLI itself, run `npm install -g gatsby-cli`

**Closed by vladar** 2020-08-14 21:22 UTC
Labels: status: triage needed, type: bug

**Comment by vladar** [comment] 2020-08-14 21:27
AFAIK renovate bot updates starters once a week. So should be updated on Monday.
