### ISSUE TITLE
Gatsbyjs.com crashes and doesn't load with ad blocker (uBlock)

### ISSUE THREAD

**Issue by whoisryosuke** [gatsbyjs/gatsby#20805] opened 2020-01-23 00:36 UTC
## Description

[Gatsbyjs.com](gatsbyjs.com) does not load properly for me. When I load Gatsbyjs.com in my Chrome, it loads, then I get a blank white screen (and error in console, see below). I tried loading the site again in incognito, where it worked fine. And if you disable uBlock, the site loads fine as well.

### Steps to reproduce

Load Gatsby.com in Chrome using uBlock. Website loads, then finishes loading at blank white screen. Console displays errors from `raven.js` "Missing resources for /".

If you disable uBlock and reload the page (without cache), the website loads properly.

### Expected result

Website loads properly. If ads are present, they're blocked gracefully and disappear from DOM, not blocking loading or rendering.

### Actual result

Blank white screen. Console displays errors from `raven.js` "Missing resources for /".

![error message](https://i.imgur.com/7rZsGHS.png)

### Environment

Chrome: 79.0.3945.117 (Official Build) (64-bit)

**Comment by KyleAMathews** [comment] 2020-01-23 02:00
Does this happen every time? If you load the site and hit a white screen and then hit refresh, does it load correctly?

**Comment by t2ca** [comment] 2020-01-23 02:40
I can confirm, i just had the same error, loaded normally the second time.

**Comment by KyleAMathews** [comment] 2020-01-23 05:43
Ok thanks @t2ca — I'm pretty sure then this is because gatsbyjs.com is running an older version of gatsby-plugin-offline which had this bug. I've added a PR to upgrade the plugin.

**Comment by sidharthachatterjee** [comment] 2020-01-23 13:30
Closing this since it isn't a Gatsby issue. 

Thank you for the report though @whoisryosuke and for updating gatsbyjs.com @KyleAMathews 🙌

**Closed by sidharthachatterjee** 2020-01-23 13:30 UTC
