### ISSUE TITLE
SIGSEGV/SIGABRT/SIGBUS faults after update gatsby-source-contentful package to ^7.14.0 version on M1 based Macbook Pro

### ISSUE THREAD

**Issue by akilis-intent** [gatsbyjs/gatsby#36601] opened 2022-09-13 14:45 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

After switching to M1 based Macbook Pro I wasn't able to run local project environment, where on Intel based Macbook Pro all runs well. `SIGSEGV & SIGABRT & SIGBUS` faults were appearing alternately and quite regularly. Several times it runs without issue, but then after rebuilding error show up again. 

The only way to reproduce issue on Intel based Macbook Pro was by running there process profiling with command `npx process-top ./node_modules/.bin/gatsby build`.

After robust investigation it turned out that downgrade of `gatsby-source-contentful` makes things working back again. What's more I've observed that `createPages` process on version `gatsby-source-contentful@7.14.0` (Intel based Macbook Pro) tooks more than 17 seconds, while on `gatsby-source-contentful@7.13.1` only 0.3 of second.

Another weird part is that process profiling with `gatsby-source-contentful@7.13.1` package works well for M1 based device while failing with SIG fault on Intel based device.

SIG Faults e.g (M1 Macbook Pro, gatsby-source-contentful: ^7.14.0):

<img width="820" alt="Screenshot 2022-09-13 at 15 17 12" src="https://user-images.githubusercontent.com/71268270/189914668-db6720fe-4bb4-4027-a3b3-8cac42071933.png">

<img width="753" alt="Screenshot 2022-09-02 at 11 44 40" src="https://user-images.githubusercontent.com/71268270/189914674-7dc51687-e165-4587-8290-fb72b5726610.png">

<img width="710" alt="Screenshot 2022-09-02 at 11 25 30" src="https://user-images.githubusercontent.com/71268270/189914676-93ffefac-d0bf-4844-ab58-e643b334a74a.png">

Successfull building process:

<img width="1208" alt="Screenshot 2022-09-13 at 15 18 26" src="https://user-images.githubusercontent.com/71268270/189918488-afb9564f-cd2a-49fc-a2f4-4118110de3cb.png">

<img width="1165" alt="Screenshot 2022-09-06 at 12 49 59" src="https://user-images.githubusercontent.com/71268270/189918495-af099211-8bda-4e9e-a4ef-ebc3a8c1c53e.png">

### Reproduction Link

--

### Steps to Reproduce

M1 based device
1. Install`gatsby-source-contentful: ^7.14.0`
2. Create proces of dynamic pages generation with Contentful (`createPages` method)
3. Run `gatsby develop`
4. Observe issue during `createPages`

Intel based device
1. Install`gatsby-source-contentful: ^7.14.0`
2. Create proces of dynamic pages generation with Contentful (`createPages` method)
3. Run `gatsby develop`
4. Observe longer time of `createPages` process comparing to the `gatsby-source-contentful: 7.13.1`.

### Expected Result

- No SIG faults on local development
- Efficient `createPages` process time
- No SIG faults during node profiling with command `npx process-top ./node_modules/.bin/gatsby build`

### Actual Result

Often `SIGSEGV & SIGABRT & SIGBUS` faults during local development on M1 based device.
Extended `createPages` process time comparing to 7.13.1 version (x55 times).

### Environment

```shell
System:
  OS: macOS Monterey v12.5.1
  CPU: Apple M1 Pro
Binaries:
  Node: 16.17.0
  npm: 8.15.0
npmPackages:
  "gatsby": "^4.20.0",
  "gatsby-source-contentful": "^7.14.0",
```

### Config Flags

FAST_DEV: true,
DEV_SSR: false,

**Comment by LekoArts** [comment] 2022-09-14 05:45
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2022-10-04 06:15
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2022-10-04 06:15 UTC
Labels: type: bug, status: needs reproduction
