### ISSUE TITLE
Image show correctly in develop mode but didn't show when Gatsby build

### ISSUE THREAD

**Issue by meokisama** [gatsbyjs/gatsby#29270] opened 2021-01-30 10:11 UTC
## Description

__As the title, when I code in develop mode, everything is ok :__

![image](https://raw.githubusercontent.com/koeyi/bug/main/Screenshot%20from%202021-01-30%2016-49-27.png)

__But when I built it, the image didn't show correctly.__

![image](https://raw.githubusercontent.com/koeyi/bug/main/Screenshot%20from%202021-01-30%2016-49-57.png)

And there is **no error notification** or something like that, error occured with **local images.**

### Expected result

Image showed correctly

### Actual result

Error occured.

### Environment
```
System:
    OS: Linux 5.9 Kali GNU/Linux Rolling 2020.4
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 15.6.0 - /usr/local/bin/node
    npm: 7.4.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 88.0.4324.96
    Firefox: 78.6.0esr
  npmPackages:
    gatsby: ^2.24.81 => 2.24.82
    gatsby-alias-imports: ^1.0.4 => 1.0.4
    gatsby-image: ^2.4.21 => 2.4.21
    gatsby-plugin-feed: ^2.5.17 => 2.5.17
    gatsby-plugin-manifest: ^2.4.34 => 2.4.35
    gatsby-plugin-offline: ^3.2.31 => 3.2.34
    gatsby-plugin-react-helmet: ^3.3.14 => 3.3.14
    gatsby-plugin-robots-txt: ^1.5.3 => 1.5.3
    gatsby-plugin-sharp: ^2.6.42 => 2.6.43
    gatsby-plugin-sitemap: ^2.4.17 => 2.4.17
    gatsby-plugin-styled-components: ^3.3.14 => 3.3.14
    gatsby-plugin-typography: ^2.5.13 => 2.5.13
    gatsby-remark-copy-linked-files: ^2.3.19 => 2.3.19
    gatsby-remark-embedder: ^4.1.0 => 4.1.0
    gatsby-remark-images: ^3.3.33 => 3.3.36
    gatsby-remark-vscode: ^3.1.0 => 3.1.0
    gatsby-source-filesystem: ^2.3.34 => 2.3.35
    gatsby-transformer-remark: ^2.8.43 => 2.8.43
    gatsby-transformer-sharp: ^2.5.17 => 2.5.18
  npmGlobalPackages:
    gatsby-cli: 2.18.0
```

**Comment by LekoArts** [comment] 2021-02-01 08:55
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-02-08 09:39
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-02-08 09:39 UTC
Labels: status: needs reproduction, type: bug
