### ISSUE TITLE
Can't seem to disable eslint

### ISSUE THREAD

**Issue by TheKnarf** [gatsbyjs/gatsby#29188] opened 2021-01-25 13:34 UTC
## Description

According to the [documentation](https://www.gatsbyjs.com/docs/how-to/custom-configuration/eslint/#disabling-eslint), we should be able to disable eslint by creating an empty `.eslintrc.js` or `.eslintrc` file. This worked previously but after upgrading, I can no longer build my project as a lot of eslint rules currently fail.

### Steps to reproduce

- Upgrade gatsby in a working project with an empty `.eslintrc`-file.

### Expected result

Everything should just still work, eslint should be turned off.

### Actual result

Eslint is not turned off and different rules seem to trigger.

### Environment

```
  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.4.0 - /private/var/folders/sj/4r44tj652q7f117h2f8f91qr0000gn/T/xfs-6ea8d4c4/node
    Yarn: 2.3.3 - /private/var/folders/sj/4r44tj652q7f117h2f8f91qr0000gn/T/xfs-6ea8d4c4/yarn
    npm: 7.0.15 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 87.0.4280.141
    Firefox: 83.0
    Safari: 14.0.2
```

**Comment by LekoArts** [comment] 2021-01-25 13:40
This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/29133

**Closed by LekoArts** 2021-01-25 13:40 UTC
Labels: type: bug
