### ISSUE TITLE
Gatsby Starters Page Error. when you filter by categories 

### ISSUE THREAD

**Issue by niawjunior** [gatsbyjs/gatsby#21893] opened 2020-03-02 06:51 UTC
## Description

Gatsby Stater Page Error. when you filter by categories 

### Steps to reproduce

go to this page https://www.gatsbyjs.org/starters/?v=2
after that click, some categories on the left side and you will see the error

![alt text](https://i.imgur.com/hM8XBQZ.png)

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by kawamataryo** [comment] 2020-03-02 08:28
I think this one is being fixed by this issue #21867.

**Comment by LekoArts** [comment] 2020-03-02 08:42
This is a duplicate of #21867

**Closed by LekoArts** 2020-03-02 08:42 UTC
Labels: type: bug
