### ISSUE TITLE
Validating Rendering Engine fails with gatsby-source-contentful

### ISSUE THREAD

**Issue by tdelgio** [gatsbyjs/gatsby#37640] opened 2023-02-10 18:16 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I'm getting this error on **gatsby build**

```
success Building Rendering Engines - 10.090s
success Building HTML renderer - 2.834s
success Execute page configs - 0.167s
failed Validating Rendering Engines - 5.440s

 ERROR #98001  ENGINE.VALIDATION

Built Rendering Engines failed validation failed validation.

Please open an issue with a reproduction at https://gatsby.dev/new-issue for more help.



  Error: Worker exited before finishing task
  
  - index.js:205 ChildProcess.<anonymous>
    [guillot]/[gatsby-worker]/dist/index.js:205:41
  

not finished Running gatsby-plugin-sharp.IMAGE_PROCESSING jobs - 26.233s

```

In development mode works perfect.
Does anybody knows what's going on?

### Reproduction Link

https://github.com/tdelgio/guillot

### Steps to Reproduce

1. run gatsby build

### Expected Result

Build my website

### Actual Result

ERROR #98001  ENGINE.VALIDATION

### Environment

```shell
{
  "name": "gatsby-starter-default",
  "private": true,
  "description": "A simple starter to get up and developing quickly with Gatsby",
  "version": "0.1.0",
  "author": "Kyle Mathews <mathews.kyle@gmail.com>",
  "dependencies": {
    "gatsby": "^5.6.0",
    "gatsby-plugin-gatsby-cloud": "^5.6.0",
    "gatsby-plugin-image": "^3.6.0",
    "gatsby-plugin-manifest": "^5.6.0",
    "gatsby-plugin-offline": "^6.6.0",
    "gatsby-plugin-react-helmet": "^6.6.0",
    "gatsby-plugin-sharp": "^5.6.0",
    "gatsby-source-contentful": "^8.6.0",
    "gatsby-source-filesystem": "^5.6.0",
    "gatsby-transformer-sharp": "^5.6.0",
    "prop-types": "^15.7.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-helmet": "^6.1.0"
  },
  "devDependencies": {
    "autoprefixer": "^10.4.0",
    "gatsby-plugin-postcss": "^6.6.0",
    "postcss": "^8.4.4",
    "prettier": "^2.4.1",
    "tailwindcss": "^3.2.6"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "0BSD",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write \"**/*.{js,jsx,ts,tsx,json,md}\"",
    "start": "gatsby develop",
    "serve": "gatsby serve",
    "clean": "gatsby clean",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  },
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  }
}
```

**Comment by tdelgio** [comment] 2023-02-11 05:42
I finally discovered that is a problem of Contentful

**Comment by feedm3** [comment] 2023-02-13 11:28
@tdelgio Can you please tell what the problem was exaclty with Contentful? Was there some problem with your data or did you have to update some code? Also facing this issue.

**Comment by LekoArts** [comment] 2023-02-14 08:17
Duplicate of https://github.com/gatsbyjs/gatsby/issues/37632 - please comment there

**Closed by LekoArts** 2023-02-14 08:17 UTC
Labels: type: bug
