### ISSUE TITLE
[www]: Issue on compare JAMstack technologies page

### ISSUE THREAD

**Issue by nephlin7** [gatsbyjs/gatsby#26502] opened 2020-08-17 06:55 UTC
## Description
Sometimes this [issue](https://streamable.com/bb7ais) happens on the compare JAMstack technologies page https://www.gatsbyjs.com/features/jamstack/gatsby-vs-nextjs/

**Comment by LekoArts** [comment] 2020-08-25 10:30
Thanks for the issue! This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/26475

**Closed by LekoArts** 2020-08-25 10:30 UTC
Labels: topic: website, type: bug
