### ISSUE TITLE
clicks on named anchors trigger a click event

### ISSUE THREAD

**Issue by ThePeach** [gatsbyjs/gatsby#2414] opened 2017-10-10 13:05 UTC
I've got a named link in a page that is correctly rendered as `<a name="section">Section</a>`.

If I try to click on it, it will try to open a page `/null`, and it seems there's an attached click event to it.

currently using gatsby 1.9.32 and node 8.4.0 (let me know if you need more info)

**Comment by KyleAMathews** [comment] 2017-10-10 23:38
This should be fixed and we'd take a PR for it but FYI, using `<a name="something">` isn't valid HTML5 https://stackoverflow.com/questions/484719/html-anchors-with-name-or-id

Using `<a id="something">` will work.

**Comment by ThePeach** [comment] 2017-10-11 09:51
hi @KyleAMathews thanks for your reply.
Agreed about the attribute, although the problem still stands.

**Comment by KyleAMathews** [comment] 2017-10-11 12:42
Right, happy to take a PR to gatsby-link solving the issue.

**Comment by jmoujaes** [comment] 2018-02-20 14:53
I'd like to work this bug if nobody else is.
@ThePeach how can I reproduce this behavior?

**Comment by ThePeach** [comment] 2018-02-24 11:49
@jmoujaes thank you for picking this one up, unfortunately I'm not working on that project anymore, but IIRC I had a plain `<a id="anchor">Anchor</a>` in the markdown, and in the generated page clicking on it will trigger a click event. As simple as that.

**Comment by jmoujaes** [comment] 2018-02-27 23:55
@ThePeach thanks for the additional detail!

I can't seem to reproduce with gatsby version 1.9.209

I add a link to my index.js like so
    `<a id="test">Is this null?</a>`
But it is not clickable and does not open a page /null

**Comment by m-allanson** [comment] 2018-02-28 11:25
@jmoujaes In @ThePeach's first example the link uses a `name` attribute instead of an `id` attribute. Does that cause the error for you? `<a name="section">Section</a>`

**Comment by ThePeach** [comment] 2018-03-01 09:13
@jmoujaes please consider that the link was in a `.md` file that was parsed into HTML, so I don't know if that is contributing at all.
Secondly, the anchor was in an second level heading (`##`), again, no idea if that contributed at all...

**Comment by jmoujaes** [comment] 2018-03-01 22:03
@m-allanson good catch, thanks.
@ThePeach gotcha, thanks. I set up a new site with the gastby-starter-blog starter. Now I create an index.md file in one of my pages with the following:
```
title: Hello Again
date: "2018-03-01T22:12:03.284Z"
---

Hello, [Is this /null?](#section)

## Section <a name="section"></a>
```
The behavior I see is "Is this /null" renders on the page as a link, and when I click it it takes me to the Section header.

I am using Firefox 58.0.2

**Comment by KyleAMathews** [comment] 2018-09-08 04:16
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Closed by KyleAMathews** 2018-09-08 04:16 UTC
Labels: type: bug :beetle:
