### ISSUE TITLE
gatsby-remark-images shows extra white space

### ISSUE THREAD

**Issue by XHMM** [gatsbyjs/gatsby#15958] opened 2019-07-21 16:08 UTC
## Description
`gatsby-remark-images` shows extra space for image：

![image](https://user-images.githubusercontent.com/24786522/61593580-e3efa400-ac13-11e9-87e4-af90bd71aef1.png)

### Steps to reproduce
I am using `gatsby-mdx` with `gatsby-remark-images`， here is my `gatsby-config.js`：

![image](https://user-images.githubusercontent.com/24786522/61593607-39c44c00-ac14-11e9-9ab0-6d732761ff5a.png)

here is my mdx file :

![image](https://user-images.githubusercontent.com/24786522/61593639-bd7e3880-ac14-11e9-9c59-590aa9d19b59.png)

### Expected result

Not show extra white space.

### Actual result

Showed extra white space.

### Environment
 System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
  Binaries:
    Yarn: 1.16.0 - D:\softwares\yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - D:\softwares\python2\python.EXE
  Browsers:
    Edge: 44.18362.1.0
  npmPackages:
    gatsby: 2.13.32 => 2.13.32
    gatsby-image: 2.2.6 => 2.2.6
    gatsby-plugin-google-analytics: 2.1.4 => 2.1.4
    gatsby-plugin-lodash: ^3.1.2 => 3.1.2
    gatsby-plugin-manifest: 2.2.3 => 2.2.3
    gatsby-plugin-material-ui: ^2.1.4 => 2.1.4
    gatsby-plugin-mdx: ^1.0.15 => 1.0.15
    gatsby-plugin-offline: 2.2.4 => 2.2.4
    gatsby-plugin-react-helmet: 3.1.2 => 3.1.2
    gatsby-plugin-sharp: 2.2.8 => 2.2.8
    gatsby-plugin-styled-components: 3.1.2 => 3.1.2
    gatsby-plugin-typescript: ^2.1.2 => 2.1.2
    gatsby-remark-copy-linked-files: 2.1.3 => 2.1.3
    gatsby-remark-external-links: 0.0.4 => 0.0.4
    gatsby-remark-images: 3.1.7 => 3.1.7
    gatsby-remark-prismjs: 3.3.3 => 3.3.3
    gatsby-source-filesystem: 2.1.5 => 2.1.5
    gatsby-transformer-json: 2.2.2 => 2.2.2
    gatsby-transformer-remark: 2.6.8 => 2.6.8
    gatsby-transformer-sharp: ^2.2.4 => 2.2.4

**Comment by lannonbr** [comment] 2019-07-21 16:09
This is a duplicate of #15486. Closing

**Closed by lannonbr** 2019-07-21 16:09 UTC
