### ISSUE TITLE
Routing is broken in the 'using-i18n' example site...

### ISSUE THREAD

**Issue by rchrdnsh** [gatsbyjs/gatsby#18011] opened 2019-10-01 05:09 UTC
Hi @LekoArts XD

Check out the routing in the 'using-i18n' example:

https://using-i18n.netlify.com/

...if one clicks on a blog post in english, and then while on that blog post clicks on german as the language the site goes back to the home page, rather than staying on the current page, breaking user context.

I hope that makes sense, as I would like to mess around with this example, but prolly won't know how to fix that :-(

**Comment by rchrdnsh** [comment] 2019-10-01 05:15
Actually, it's also not updated to use `gatsby-plugin-mdx` either...I might take a stab at that...🤔

**Comment by rchrdnsh** [comment] 2019-10-01 06:18
Also, trying to update the example to `gatsby-plugin-mdx` and I'm running into this error when I navigate to a blog post:

<img width="1041" alt="Screen Shot 2019-09-30 at 10 49 09 PM" src="https://user-images.githubusercontent.com/7884263/65938575-271a8000-e3d8-11e9-94a8-51bac52eba16.png">

...so I ran the query on that page in graphiQL and got this:

<img width="1119" alt="Screen Shot 2019-09-30 at 11 16 13 PM" src="https://user-images.githubusercontent.com/7884263/65938684-73fe5680-e3d8-11e9-8f9a-d88438c40fd9.png">

So I'm thinking that maybe something is going on that is a little bit beyond me in the node file or something...gonna keep working on it, but if you have any thoughts @LekoArts, they would be most appreciated :-)

**Comment by LekoArts** [comment] 2019-10-01 15:18
Thank you for opening this!

The site is working as intended, I didn't want it to stay at the same blog posts as it complicates some things -- and I wanted to keep the example concise.

I'll update the example to the latest MDX plugin next week or so, thanks for mentioning that!

I'm marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2019-10-01 15:18 UTC

**Comment by rchrdnsh** [comment] 2019-10-01 19:00
hmmmm...well, in my experience, routing back to the home page breaks continuity and confuses users, so I would definitely want to alter that to use this template. So what would I need to do to get that behavior? I'm not really sure where to even start, to be honest :-(
