### ISSUE TITLE
Gatsby Link - Loads Page Data Whenever Links Are In Viewport?

### ISSUE THREAD

**Issue by jasonbiondo** [gatsbyjs/gatsby#27414] opened 2020-10-12 23:49 UTC
I have a shopify gatsby store and I have about 50+ Links in my header menu which is in a mega menu style.  When I load my index all of the page data for each one of those links loads via the Link component and it ends up being several mb of data.  Is there anyway to avoid this?  Is it possible to only load the link page-data when the link is visible or hovered over?  I imagine a lot of commercial sites would face this same issue but I couldn't find a solution.

**Comment by LekoArts** [comment] 2020-10-13 07:44
Thank you for opening this!

This was also asked in this issue: https://github.com/gatsbyjs/gatsby/issues/14016#issuecomment-491999391

Since `gatsby-link` is a thin wrapper around `@reach/router`'s Link component you can use the linked snippet to use regular anchor/Link tags for your navigation menu.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2020-10-13 07:44 UTC
Labels: status: duplicate, type: question or discussion

**Comment by jasonbiondo** [comment] 2020-10-13 11:35
When using that snippet it causes a 404 on my prefetch false pages.  Not sure why.

**Comment by LekoArts** [comment] 2020-10-14 07:30
Alternatively you can use an anchor `<a>` tag although react/router's Link should also work. If you can provide a [minimal reproduction](https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/) feel free to open a bug report.

Gatsby's Link component only requests links in the viewport with a **low priority** request and that behavior is also disabled on slow connections. So I guess also keep that in mind when considering to change this behavior.

**Comment by jasonbiondo** [comment] 2020-10-15 11:32
@LekoArts an <a> tag works without the 404 issue but then the whole page goes white as other users have stated.  Those low priority requests seem to be of importance since they cause a 404 if not present.  I assume this is because the context data never gets passed via the page-data.json files or something along those lines.
