### ISSUE TITLE
Gatsby cannot build after being pushed and cloned to github

### ISSUE THREAD

**Issue by notaduck** [gatsbyjs/gatsby#23990] opened 2020-05-11 21:38 UTC
## Description

I have a small project which builds fine on "my machine" However, as soon as I push it to github, clone it and try to build it it fails. The odd thing is that it works in a codesandbox.

### Steps to reproduce

```
git clone https://github.com/notaduck/guldberg_lab
cd guldberglab
yarn 
gatsby develop
```

### Expected result

Gatsby should build the page and serve the site on localhost.

### Actual result
```
[guldberg_lab] gatsby develop                                                                                                                                                                        master
success open and validate gatsby-configs - 0.032s
success load plugins - 0.311s
success onPreInit - 0.004s
success initialize cache - 0.012s
success copy gatsby files - 0.029s
success onPreBootstrap - 0.013s
success createSchemaCustomization - 0.015s
success source and transform nodes - 0.068s
success building schema - 0.304s
success createPages - 0.051s
warn The plugin "dev-404-page" created a page with a component path that doesn't match the casing of the actual file. This may work locally, but will break on systems which are case-sensitive, e.g. most
CI/CD pipelines.

page.component:     "/home/daniel/Nextcloud/Projects/guldberg_lab/.cache/dev-404-page.js"
path in filesystem: "/home/daniel/Nextcloud/Projects/Guldberg_Lab/.cache/dev-404-page.js"
warn The plugin "gatsby-plugin-page-creator" created a page with a component path that doesn't match the casing of the actual file. This may work locally, but will break on systems which are
case-sensitive, e.g. most CI/CD pipelines.

page.component:     "/home/daniel/Nextcloud/Projects/guldberg_lab/src/pages/404.js"
path in filesystem: "/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/pages/404.js"
warn The plugin "gatsby-plugin-page-creator" created a page with a component path that doesn't match the casing of the actual file. This may work locally, but will break on systems which are
case-sensitive, e.g. most CI/CD pipelines.

page.component:     "/home/daniel/Nextcloud/Projects/guldberg_lab/src/pages/index.js"
path in filesystem: "/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/pages/index.js"
warn The plugin "gatsby-plugin-page-creator" created a page with a component path that doesn't match the casing of the actual file. This may work locally, but will break on systems which are
case-sensitive, e.g. most CI/CD pipelines.

page.component:     "/home/daniel/Nextcloud/Projects/guldberg_lab/src/pages/page-2.js"
path in filesystem: "/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/pages/page-2.js"
success createPagesStatefully - 0.106s
success onPreExtractQueries - 0.004s
success update schema - 0.038s

 ERROR #85922  GRAPHQL

There was an error in your GraphQL query:

Field "image" must not have a selection since type "String" has no subfields.

This can happen if you e.g. accidentally added { } to the field "image". If you didn't expect "image" to be of type "String" make sure that your input source and/or plugin is correct.

File: ../Guldberg_Lab/src/pages/index.js:56:20

failed extract queries from components - 0.230s
success write out requires - 0.034s
success write out redirect data - 0.007s
success onPostBootstrap - 0.003s
⠀
info bootstrap finished - 4.429 s
⠀
success run queries - 0.035s - 6/6 171.08/s
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <head>. See https://fb.me/react-warning-keys for more information.
    in FallbackStyles
    in HTML
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <body>. See https://fb.me/react-warning-keys for more information.
    in MagicScriptTag
    in HTML
warn ESLintError:
/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/components/layout.js
  4:8  warning  'styled' is defined but never used  no-unused-vars

✖ 1 problem (0 errors, 1 warning)

warn ESLintError:
/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/components/navbar.js
  10:3   warning  'UncontrolledDropdown' is defined but never used  no-unused-vars
  11:3   warning  'DropdownToggle' is defined but never used        no-unused-vars
  12:3   warning  'DropdownMenu' is defined but never used          no-unused-vars
  13:3   warning  'DropdownItem' is defined but never used          no-unused-vars
  14:10  warning  'Router' is defined but never used                no-unused-vars

✖ 5 problems (0 errors, 5 warnings)

warn There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* /home/daniel/Nextcloud/Projects/guldberg_lab/node_modules/gatsby/dist/utils/babel-loader.js??ref--4-0!/home/daniel/Nextcloud/Projects/guldberg_lab/node_modules/eslint-loader/index.js??ref--11-0!/home/dan
iel/Nextcloud/Projects/Guldberg_Lab/src/components/layout.js
    Used by 6 module(s), i. e.
    /home/daniel/Nextcloud/Projects/guldberg_lab/node_modules/gatsby/dist/utils/babel-loader.js??ref--4-0!/home/daniel/Nextcloud/Projects/guldberg_lab/node_modules/eslint-loader/index.js??ref--11-0!/home/d
aniel/Nextcloud/Projects/Guldberg_Lab/src/pages/page-2.js
* /home/daniel/Nextcloud/Projects/guldberg_lab/node_modules/gatsby/dist/utils/babel-loader.js??ref--4-0!/home/daniel/Nextcloud/Projects/guldberg_lab/node_modules/eslint-loader/index.js??ref--11-0!/home/dan

 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed


/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/components/header.js
   1:10  warning  'Link' is defined but never used                     no-unused-vars
   2:8   warning  'Img' is defined but never used                      no-unused-vars
   3:8   warning  'PropTypes' is defined but never used                no-unused-vars
   5:8   warning  'MyImg' is defined but never used                    no-unused-vars
   7:10  warning  'Button' is defined but never used                   no-unused-vars
  25:11  error    Cannot query field "childImageSharp" on type "File"  graphql/template-strings

✖ 6 problems (1 error, 5 warnings)

File: ../Guldberg_Lab/src/components/header.js


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed


/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/components/image.js
  21:11  error  Cannot query field "childImageSharp" on type "File"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)


File: ../Guldberg_Lab/src/components/image.js


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed


/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/components/myimage.js
  23:17  error  Cannot query field "childImageSharp" on type "File"  graphql/template-strings

✖ 1 problem (1 error, 0 warnings)


File: ../Guldberg_Lab/src/components/myimage.js


 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed


/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/pages/index.js
   3:8  warning  'Img' is defined but never used                                                      no-unused-vars
   6:8  warning  'Image' is defined but never used                                                    no-unused-vars
   8:8  warning  'MyImg' is defined but never used                                                    no-unused-vars
  22:7  warning  'PostItem' is assigned a value but never used                                        no-unused-vars
  55:8  error    Cannot query field "path" on type "MarkdownRemarkFrontmatter". Did you mean "date"?  graphql/template-strings

✖ 5 problems (1 error, 4 warnings)


File: ../Guldberg_Lab/src/pages/index.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'bootstrap/dist/css/bootstrap.min.css' in '/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/components'

Perhaps you need to install the package 'bootstrap/dist/css/bootstrap.min.css'?

File: ../Guldberg_Lab/src/components/layout.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'gatsby-image' in '/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/components'

Perhaps you need to install the package 'gatsby-image'?

File: ../Guldberg_Lab/src/components/image.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'gatsby-image' in '/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/components'

Perhaps you need to install the package 'gatsby-image'?

File: ../Guldberg_Lab/src/components/myimage.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'gatsby-image' in '/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/components'

Perhaps you need to install the package 'gatsby-image'?

File: ../Guldberg_Lab/src/components/header.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'gatsby-image' in '/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/pages'

Perhaps you need to install the package 'gatsby-image'?

File: ../Guldberg_Lab/src/pages/index.js


Generating development JavaScript bundle failed

Can't resolve 'prop-types' in '/home/daniel/Nextcloud/Projects/Guldberg_Lab/.cache'

Perhaps you need to install the package 'prop-types'?

File: ../Guldberg_Lab/.cache/dev-404-page.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'prop-types' in '/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/components'

Perhaps you need to install the package 'prop-types'?

File: ../Guldberg_Lab/src/components/layout.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'prop-types' in '/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/components'

Perhaps you need to install the package 'prop-types'?

File: ../Guldberg_Lab/src/components/seo.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'prop-types' in '/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/components'

Perhaps you need to install the package 'prop-types'?

File: ../Guldberg_Lab/src/components/header.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'react' in '/home/daniel/Nextcloud/Projects/Guldberg_Lab/.cache'

Perhaps you need to install the package 'react'?

File: ../Guldberg_Lab/.cache/dev-404-page.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'react' in '/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/components'

Perhaps you need to install the package 'react'?

File: ../Guldberg_Lab/src/components/layout.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'react' in '/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/components'

Perhaps you need to install the package 'react'?

File: ../Guldberg_Lab/src/components/image.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'react' in '/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/components'

Perhaps you need to install the package 'react'?

File: ../Guldberg_Lab/src/components/seo.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'react' in '/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/components'

Perhaps you need to install the package 'react'?

File: ../Guldberg_Lab/src/components/myimage.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'react' in '/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/components'

Perhaps you need to install the package 'react'?

File: ../Guldberg_Lab/src/components/header.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'react' in '/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/components'

Perhaps you need to install the package 'react'?

File: ../Guldberg_Lab/src/components/navbar.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'react' in '/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/pages'

Perhaps you need to install the package 'react'?

File: ../Guldberg_Lab/src/pages/404.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'react' in '/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/pages'

Perhaps you need to install the package 'react'?

File: ../Guldberg_Lab/src/pages/page-2.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'react' in '/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/pages'

Perhaps you need to install the package 'react'?

File: ../Guldberg_Lab/src/pages/index.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'react-helmet' in '/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/components'

Perhaps you need to install the package 'react-helmet'?

File: ../Guldberg_Lab/src/components/seo.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'reactstrap' in '/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/components'

Perhaps you need to install the package 'reactstrap'?

File: ../Guldberg_Lab/src/components/navbar.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'styled-components' in '/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/components'

Perhaps you need to install the package 'styled-components'?

File: ../Guldberg_Lab/src/components/layout.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'styled-components' in '/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/components'

Perhaps you need to install the package 'styled-components'?

File: ../Guldberg_Lab/src/components/header.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'styled-components' in '/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/components'

Perhaps you need to install the package 'styled-components'?

File: ../Guldberg_Lab/src/components/button.js


 ERROR #98124  WEBPACK

Generating development JavaScript bundle failed

Can't resolve 'styled-components' in '/home/daniel/Nextcloud/Projects/Guldberg_Lab/src/pages'

Perhaps you need to install the package 'styled-components'?

File: ../Guldberg_Lab/src/pages/index.js

failed Building development bundle - 5.277s
```

### Environment

```
 System:
    OS: Linux 5.5 Manjaro Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.2.0 - /usr/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.5 - /usr/bin/npm
  Languages:
    Python: 3.7.2 - /home/daniel/.pyenv/shims/python
  Browsers:
    Firefox: 76.0.1
  npmPackages:
    gatsby: ^2.20.36 => 2.21.21
    gatsby-awesome-pagination: ^0.3.5 => 0.3.5
    gatsby-cli: ^2.12.16 => 2.12.16
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-manifest: ^2.3.7 => 2.4.2
    gatsby-plugin-offline: ^2.2.10 => 2.2.10
    gatsby-plugin-react-helmet: ^3.3.1 => 3.3.1
    gatsby-plugin-styled-components: ^3.3.1 => 3.3.1
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-remark-prismjs: ^3.5.0 => 3.5.1
    gatsby-source-filesystem: ^2.2.5 => 2.3.1
    gatsby-transformer-remark: ^2.8.3 => 2.8.7

```

**Comment by madalynrose** [comment] 2020-05-12 17:24
Hi there, @notaduck! I'm sorry you're having this issue! 

Unfortunately I can't reproduce this on my machine either. Could you provide any more information or reproduction steps?

**Comment by notaduck** [comment] 2020-05-13 09:31
@madalynrose  It looks like there was some version mismatch somewhere, but a user on Gatsby's discord server helped me out.

```sh
$ npm i -g n \
n 14.2.0 \
npm i -g npm@6.14.5 \
npm i -g yarn@1.22.4 \
yarn global add gatsby-cli@2.12.16 \
git clone https://github.com/notaduck/guldberg_lab.git fresh_download \
cd fresh_download \
npm i \
gatsby develop
```

But I've to admit that I still don't know what went wrong since my system packages seems to be using the same versions

```
[~] npm --version
6.14.4
[~] yarn --version
1.22.4
[~] node --version
v14.2.0
```

**Comment by TotalLag** [comment] 2020-05-27 13:41
Different error messages, but I started receiving errors too after upgrading the following packages:

Package | Type | Update | Change
-- | -- | -- | --
gatsby (changelog) | dependencies | minor | ^2.19.45 -> ^2.22.11
gatsby-image | dependencies | minor | ^2.3.1 -> ^2.4.5
gatsby-plugin-catch-links | dependencies | minor | ^2.2.1 -> ^2.3.3
gatsby-plugin-manifest | dependencies | minor | ^2.2.48 -> ^2.4.9
gatsby-plugin-offline | dependencies | minor | ^3.0.41 -> ^3.2.7
gatsby-plugin-react-helmet | dependencies | minor | ^3.2.1 -> ^3.3.2
gatsby-plugin-sass | dependencies | minor | ^2.2.1 -> ^2.3.2
gatsby-plugin-sharp | dependencies | minor | ^2.4.13 -> ^2.6.9
gatsby-source-filesystem | dependencies | minor | ^2.2.2 -> ^2.3.8
gatsby-transformer-remark | dependencies | minor | ^2.7.1 -> ^2.8.13
gatsby-transformer-sharp | dependencies | minor | ^2.3.19 -> ^2.5.3

and building under node 13.10.  the message when running `gatsby build`:
```
success Downloading remote files - 0.290s - 1/1 3.45/s
success Building production JavaScript and CSS bundles - 12.505s
success Rewriting compilation hashes - 0.001s
error UNHANDLED REJECTION Input file contains unsupported image format


 Error: Input file contains unsupported image format

not finished run queries - 14.203s
not finished Downloading remote files - 0.935s
not finished Generating image thumbnails - 14.186s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```
I think it could be version mismatch as well.  I don't seem to have any problems when using node 12
```

**Comment by danabrit** [comment] 2020-05-29 22:01
@TotalLag Thank you for sharing that you were also having issues after upgrading packages. I am going to close this issue since the original problem was resolved - could you please log a *new issue* with all required information about what you are experiencing? Thank you!

**Closed by danabrit** 2020-05-29 22:01 UTC
Labels: status: needs reproduction, type: bug
