### ISSUE TITLE
Cache error for static images

### ISSUE THREAD

**Issue by antonbks** [gatsbyjs/gatsby#28174] opened 2020-11-19 09:01 UTC
## Description

Describe the issue that you're seeing.

We use CI for building, for a while now we were seeing cache warnings for our static images like :

```
success run static queries - 0.175s - 44/44 252.04/s
error error copying file from /builds/xxx/site-xxx/src/images/svg/xxx/SELL.svg to /builds/xxx/site-xxx/public/static/1587433b55a609b1bf019a9be7204721/SELL.svg [Error: ENOENT: no such file or directory, chmod '/builds/xxx/site-xxx/public/static/1587433b55a609b1bf019a9be7204721/SELL.svg'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'chmod',
  path: '/builds/xxx/site-xxx/public/static/1587433b55a609b1bf019a9be7204721/SELL.svg'
}
success run page queries - 1.268s - 170/170 134.05/s
success write out requires - 0.015s
```
This is after deleting both .cache and public directories on a fresh gitlab CI runner. 

I disregarded them as warnings as they never broke the build, until I tried upgrading from gatsby `2.24.84` -> `2.26.1` :

```
success run static queries - 0.205s - 44/44 214.13/s
error [object Object] ENOENT: no such file or directory, chmod '/builds/xxx/site-xxx/public/static/09d54f0441d2b5f7abd18fa2a576e08d/xxx.svg'
  Error: ENOENT: no such file or directory, chmod '/builds/xxx/site-xxx/public/static/09d54f0441d2b5f7abd18fa2a576e08d/xxx.svg'
not finished run page queries - 0.476s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hosting3@1.0.0 build:preprod: `GATSBY_ACTIVE_ENV=preprod gatsby build --prefix-paths`
npm ERR! Exit status 1
```

I tried both hard deleting .cache and public, and running gatsby clean with no luck.

### Environment

  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 87.0.4280.67
    Firefox: 82.0.3
    Safari: 13.1.2
  npmPackages:
    gatsby: 2.24.84 => 2.24.84 
    gatsby-plugin-google-tagmanager: 2.3.16 => 2.3.16 
    gatsby-plugin-load-script: 1.1.0 => 1.1.0 
    gatsby-plugin-loadable-components-ssr: 2.1.0 => 2.1.0 
    gatsby-plugin-material-ui: latest => 2.1.10 
    gatsby-plugin-meta-redirect: 1.1.1 => 1.1.1 
    gatsby-plugin-react-helmet: 3.3.14 => 3.3.14 
    gatsby-plugin-remove-trailing-slashes: 2.3.13 => 2.3.13 
    gatsby-plugin-scroll-reveal: 0.0.7 => 0.0.7 
    gatsby-plugin-sitemap: 2.4.17 => 2.4.17 
    gatsby-plugin-styled-components: 3.3.14 => 3.3.14 
    gatsby-source-apiserver: 2.1.7 => 2.1.7 
    gatsby-source-drupal: 3.5.38 => 3.5.38 
    gatsby-source-filesystem: 2.3.35 => 2.3.35 
    gatsby-source-graphql: 2.7.6 => 2.7.6 
  npmGlobalPackages:
    gatsby: 2.26.1

**Comment by ascorbic** [comment] 2020-11-19 09:35
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it would be really helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

Thanks!

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2020-11-30 13:10
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-11-30 13:10 UTC
Labels: status: needs reproduction, topic: images/media, type: bug
