### ISSUE TITLE
Cache React library

### ISSUE THREAD

**Issue by sumanthyedoti** [gatsbyjs/gatsby#24020] opened 2020-05-12 16:24 UTC
I am using [React-fullpage](https://github.com/alvarotrigo/react-fullpage) library. Currently, the library is getting into action with some delay of few seconds depending on bandwidth.

I need to **fetch this library on high priority and cache** it locally so the library comes into action quickly as page loads and consecutive page hits don't download the library again

Please help with a possible ways to do this. 

[Custom Webpack Config](https://www.gatsbyjs.org/docs/add-custom-webpack-config/), caching the library using service-workers without making the website PWA, [Code Splitting and Prefetching](https://www.gatsbyjs.org/docs/how-code-splitting-works/#prefetching-chunks)? Whatever the possible solution to achieve this.

Thanks.

**Comment by herecydev** [comment] 2020-05-12 16:35
Closing as duplicate of #24003

**Closed by herecydev** 2020-05-12 16:35 UTC
Labels: status: triage needed, type: feature or enhancement
