### ISSUE TITLE
Graphql node is visible to GraphIQL but not in page query

### ISSUE THREAD

**Issue by timothymcmackin** [gatsbyjs/gatsby#23569] opened 2020-04-28 17:26 UTC
## Description
This is a more generalizable instance of the problem I mentioned in https://github.com/gatsbyjs/gatsby/issues/20484. In short, I create a graphql node that I can see in the GraphIQL IDE but returns null on my page. Am I creating the node in the wrong way, maybe not using async correctly in the plugin?

### Steps to reproduce

1. Clone this minimal reproduction repository: https://github.com/timothymcmackin/test-create-nodes-simpler.
2. Run `yarn install` to install dependencies.
3. Run `yarn start` to start the server.
4. When the server comes up, open `http://localhost:8000/___graphql` in a web browser.
5. In GraphIQL, run this query (here's a [link](http://localhost:8000/___graphql?query=query%20MyQuery%20%7B%0A%20%20testTestTest(path%3A%20%7Beq%3A%20%22%2Fmypage.html%22%7D)%20%7B%0A%20%20%20%20message%0A%20%20%7D%0A%7D%0A&operationName=MyQuery)):
    ```graphql
    query MyQuery {
      testTestTest(path: {eq: "/mypage.html"}) {
        message
      }
    }
    ```
6. Note that the query returns data for the `testTestTest` node.
7. Go to `http://localhost:8000/mypage.html`.
8. Note that on the page, the value for `data.testTestTest.message` is null.
9. In the console, note that the data returned from the page query includes no data for the `topicInternalHeadings` node:
    ```
    {markdownRemark: {…}, testTestTest: null}
    ```

Here's what's happening:

In a [Remark plugin](https://github.com/timothymcmackin/test-create-nodes-simpler/blob/master/plugins/gatsby-remark-internal-toc/index.js), I create a graphQL node:

```
module.exports = async ({ markdownAST, markdownNode, actions, createNodeId, createContentDigest }) => {

  const { createNode } = actions;

  const testValue = markdownNode.frontmatter.path;

  const testNode = {
    path: testValue,
    message: 'Hello!!!',
    id: createNodeId(testValue),
    children: [],
    internal: {
      description: `Test`,
      type: "testTestTest",
      contentDigest: createContentDigest(testValue),
      content: testValue,
    }
  };
  
  await createNode(testNode);

  return markdownAST;
}
```

In GraphIQL, I can verify that the node is created with [a simple query](http://localhost:8000/___graphql?query=query%20MyQuery%20%7B%0A%20%20testTestTest(path%3A%20%7Beq%3A%20%22%2Fmypage.html%22%7D)%20%7B%0A%20%20%20%20message%0A%20%20%7D%0A%7D%0A&operationName=MyQuery).

I access that node with this code in a [page component](https://github.com/timothymcmackin/test-create-nodes-simpler/blob/master/src/pages/page.js):
```
import React from "react"
import { graphql } from 'gatsby'

import Layout from "../components/layout"

const MainPage = ({ data }) => {
  const { markdownRemark: post } = data;
  console.log(data)

  return (
    <Layout>
    <div>Value of data.testTestTest: {JSON.stringify(data.testTestTest) || 'null'}</div>
    <div>Value of markdownRemark.frontmatter.path: {data.markdownRemark.frontmatter.path}</div>
    <h2>Content</h2>
    <div
      className="content"
      dangerouslySetInnerHTML={{ __html: post.html }}
    />
    </Layout>
  )
}

export default MainPage;

export const pageQuery = graphql`
query topicsByPath($path: String!) {
  markdownRemark(frontmatter: {path: {eq: $path}}) {
    html
    frontmatter {
      path
      title
    }
  }
  testTestTest(path: {eq: $path}) {
    message
  }
}
`;
```

### Expected result

The `testTestTest` node should return data on the page component.

### Actual result

The graphql query returns null for the `testTestTest` node on the page.

### Environment

  System:
    OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
    Yarn: 1.19.1 - ~/.yarn/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.0/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    gatsby: ^2.19.12 => 2.19.12
    gatsby-image: ^2.2.34 => 2.2.40
    gatsby-plugin-manifest: ^2.2.31 => 2.2.41
    gatsby-plugin-offline: ^3.0.27 => 3.0.34
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.22
    gatsby-plugin-sharp: ^2.3.5 => 2.4.5
    gatsby-remark-autolink-headers: ^2.1.21 => 2.1.24
    gatsby-source-filesystem: ^2.1.40 => 2.1.48
    gatsby-transformer-remark: ^2.6.50 => 2.6.50
    gatsby-transformer-sharp: ^2.3.7 => 2.3.14

**Comment by timothymcmackin** [comment] 2020-04-28 20:08
My only theory is that this is caused by the remark transformer plugin not handling the async in my plugin correctly. 

I can do things this way to access the graphql data later in the build process and it works:

1. Remove the code from [page.js](https://github.com/timothymcmackin/test-create-nodes-simpler/blob/master/src/pages/page.js) that accesses the testTestTest node, including both the graphql query and where the data is used on the page, like this:
```
import React from "react"
import { graphql } from 'gatsby'

import Layout from "../components/layout"

const MainPage = ({ data }) => {
  const { markdownRemark: post } = data;
  console.log(data)

  return (
    <Layout>
    {/* <div>Value of data.testTestTest: {data.testTestTest || 'null'}</div> */}
    <div>Value of markdownRemark.frontmatter.path: {data.markdownRemark.frontmatter.path}</div>
    <h2>Content</h2>
    <div
      className="content"
      dangerouslySetInnerHTML={{ __html: post.html }}
    />
    </Layout>
  )
}

export default MainPage;

export const pageQuery = graphql`
query topicsByPath($path: String!) {
  markdownRemark(frontmatter: {path: {eq: $path}}) {
    html
    frontmatter {
      path
      title
    }
  }
}
`;
```
2. Run `yarn start` to start Gatsby.
3. In graphIQL, access the data with this query and verify that it is available:
```
query MyQuery {
  testTestTest(path: {eq: "/mypage.html"}) {
    message
  }
}
```
4. With Gatsby still running, edit the page.js file to access the testTestTest node again:
```
import React from "react"
import { graphql } from 'gatsby'

import Layout from "../components/layout"

const MainPage = ({ data }) => {
  const { markdownRemark: post } = data;
  console.log(data)

  return (
    <Layout>
    <div>Value of data.testTestTest: {JSON.stringify(data.testTestTest) || 'null'}</div>
    <div>Value of markdownRemark.frontmatter.path: {data.markdownRemark.frontmatter.path}</div>
    <h2>Content</h2>
    <div
      className="content"
      dangerouslySetInnerHTML={{ __html: post.html }}
    />
    </Layout>
  )
}

export default MainPage;

export const pageQuery = graphql`
query topicsByPath($path: String!) {
  markdownRemark(frontmatter: {path: {eq: $path}}) {
    html
    frontmatter {
      path
      title
    }
  }
  testTestTest(path: {eq: $path}) {
    message
  }
}
`;
```
5. Visit http://localhost:8000/mypage.html and see that the data is shown on the page.

**Comment by vladar** [comment] 2020-04-29 11:01
So the problem is that you are trying to create a new node inside a sub-plugin of `gatsby-transformer-remark`. Sadly this won't work by design. Those plugins are supposed to do only one thing: transform the original `markdownAST`.

Actual markdown parsing occurs during query running step (not in `sourceNodes`). So by the moment you create your node, the query for your page is already executed.

If you want to create new nodes or do anything other than mutating `markdownAST` you should write a regular gatsby plugin, not a sub-plugin of `gatsby-transformer-remark`.

Then you can do what you want inside the [`onCreateNode` API](https://www.gatsbyjs.org/docs/node-apis/#onCreateNode) (and create your node on a new `MarkdownRemark` node).

**Comment by timothymcmackin** [comment] 2020-04-29 12:57
Darn. The plugin gatsby-remark-autolink-headers creates an AST node with the URL to each heading on the page, so I was hoping to capture that URL along with the heading text that gatsby-transformer-remark creates to create an internal TOC on each page. I'll find some other way.

**Comment by vladar** [comment] 2020-04-29 18:12
Thank you for opening this, @timothymcmackin

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Closed by vladar** 2020-04-29 18:12 UTC
Labels: type: bug
