### ISSUE TITLE
[gatsby-source-twitter] Some queries work but not others

### ISSUE THREAD

**Issue by dderooy** [gatsbyjs/gatsby#10893] opened 2019-01-07 17:02 UTC
## Description 
[gatsby-source-twitter] plug in has been setup properly according to #10889 . 

```
\\ gatsby-config.js

{
      resolve: `gatsby-source-twitter`,
      options: {
        q: `@tech`,
        count: '10',
        credentials: {
          consumer_key: 'blahblahblah',
          consumer_secret: 'blahblablah',
          bearer_token:
            ';lakjds;lfakdjsl;fka;lfjal;sdjkf',
        },
        tweet_mode: 'extended',
      },
},

```

This setup returns a list of 10 results using the '@tech' query. 

## Problem 
If I change the query to  '@simnova_UPO' then I get the issue from #10889 and 'gatsby develop' in terminal says **"warning The gatsby-source-twitter plugin has generated no Gatsby nodes. Do you need it?"**. 

Why do some queries work and not others?

**Comment by jgierer12** [comment] 2019-01-07 17:45
Hi, unfortunately I won't be able to reproduce this since I don't have a Twitter developer account. Can you try if the query works if using the [Twitter API](https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets) directly? Just to see if this is an issue with `gatsby-source-twitter` or if the issue lies in the query or your privacy settings somehow.

**Comment by dderooy** [comment] 2019-01-07 18:30
I have PostMan app running and I tried to query the Twitter API directly as suggested and it gives zero results for "@simnova_UPO". Very strange since its an active twitter feed. The status 200 result is below. 

```
{
    "statuses": [],
    "search_metadata": {
        "completed_in": 0.017,
        "max_id": 1082342669337194497,
        "max_id_str": "1082342669337194497",
        "query": "%40simnova_UPO",
        "refresh_url": "?since_id=1082342669337194497&q=%40simnova_UPO&include_entities=1",
        "count": 10,
        "since_id": 0,
        "since_id_str": "0"
    }
}
```

So it has nothing to do with the plugin. Any ideas about the Twitter API then? Perhaps other Gatsby users have similar issues.

**Comment by sidharthachatterjee** [comment] 2019-01-08 12:08
Hey @dderooy 

Found this old thread that seems to describe something similar
https://twittercommunity.com/t/search-tweets-api-returned-empty-statuses-result-for-some-queries/12257/5

Closing this for the moment since this is specific to the Twitter API and out of our control.

**Closed by sidharthachatterjee** 2019-01-08 12:08 UTC
Labels: status: needs reproduction
