### ISSUE TITLE
Dev server url construction problems with `--host=0.0.0.0` switch

### ISSUE THREAD

**Issue by palerdot** [gatsbyjs/gatsby#8348] opened 2018-09-20 05:56 UTC
## Description

There is a minor issue with running the local server with `--host` switch. The local server literally takes the host ip for constructing urls rather than taking from the base url. For example, if the local ip is 10.0.10.0 and with the host switch enabled, the page at `http://10.0.10.0:8000` should have all the urls relative to this path. Rather, gatsby local server constructs url some thing like http://0.0.0.0/__webpack which is wrong.

Right now, we can workaround this problem by giving the **exact ip address** in the host switch like `gatsby develop --host=10.0.10.0`, but this should not be the behaviour for `--host=0.0.0.0` switch by default.

### Steps to reproduce

1. Run gatsby development server with `gatsby develop --host=0.0.0.0`.
2. Access the app from `http://<local-ip>:<port>`.

The app will not load since all the urls are constructed in the form of `http://0.0.0.0/<anything>` including static files and webpack dev server.

### Expected result

The app should be accessible in local ip when running `gatsby develop --host=0.0.0.0`

### Actual result

The app cannot be run from the localip when given `--host` switch

### Environment

Not Applicable. Should be reproducible out of the box in all the environments. This is also related to https://github.com/gatsbyjs/gatsby/pull/8150

Run `gatsby info --clipboard` in your project directory and paste the output here. Not working? You may need to update your global gatsby-cli - `npm install -g gatsby-cli`

**Comment by kakadiadarpan** [comment] 2018-09-20 06:06
I'm able to reproduce this issue, refer screenshot below:

<img width="1680" alt="screen shot 2018-09-20 at 11 32 32 am" src="https://user-images.githubusercontent.com/10805593/45798827-f550e280-bcc8-11e8-8027-b54474d312fc.png">

Also, I can only see `http://0.0.0.0/<anything>` for `__webpack_hmr`

**Comment by palerdot** [comment] 2018-09-20 06:54
Sorry my bad. The problem is only with webpack dev server. But it is a main component of gatsby dev server and this issue has to address that.

**Comment by pieh** [comment] 2018-09-21 13:02
Here's where we construct HMR path https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/webpack.config.js#L73-L90 - @palerdot would you like to take a stab on that?

**Comment by palerdot** [comment] 2018-09-21 13:04
@pieh sure. will take a look and raise a PR (if possible)

**Comment by palerdot** [comment] 2018-09-21 13:13
@pieh How can we make changes to that file and test it locally since it is a part of `packages` which is meant to be published as npm package?

**Comment by pieh** [comment] 2018-09-21 14:26
Check https://www.gatsbyjs.org/docs/how-to-contribute/#contributing-to-the-repo
Create test site (just `gatsby new` would do) and in there you would run `gatsby-dev` (after setting this up using docs I linked)

**Comment by palerdot** [comment] 2018-09-21 15:02
@pieh. Ok. Thanks for the info. Will look into this.

**Comment by palerdot** [comment] 2018-09-23 06:58
@pieh I'm running into problems when running `gatsby-dev`. I have raised issues for this - https://github.com/gatsbyjs/gatsby/issues/8457, https://github.com/gatsbyjs/gatsby/issues/8447

**Comment by drubin** [comment] 2018-11-02 15:29
A workaround is to do `GATSBY_WEBPACK_PUBLICPATH=http://foo.bar.local gatsby dev -h 0.0.0.0 -p 8080`

Taken from https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/webpack.config.js#L103 

@kakadiadarpan You should be able to do.

`GATSBY_WEBPACK_PUBLICPATH=http://192.168.1.102:8080 dev -h 0.0.0.0 -p 8080`

But it would be nice if Gatsby could infer the `__webpack_hmr` from the current accessing url

**Comment by palerdot** [comment] 2018-11-05 09:23
@drubin @pieh @kakadiadarpan This issue is because `hmrPath` is configured at compile time. To fix this, there should be some way to generate `hmrPatch` dynamically during runtime. I guess this should involve some pretty big changes? And there are some redux actions wrt to setting/replacing webpack hmr config. Dispatching them will fix this issue? With the current code architecture where `hmrPath` is configured at compile time, I think this issue will not be fixed. Let me know if I'm missing anything.

**Comment by pieh** [comment] 2018-11-05 12:46
so I just tried `GATSBY_WEBPACK_PUBLICPATH=/ gatsby develop -H 0.0.0.0` and it seems to work (at least on OSX). I skipped specifying host in webpack public path

**Comment by drubin** [comment] 2018-11-05 14:20
@pieh I didn't even think of trying this. @palerdot  why is this not the default?

**Comment by drubin** [comment] 2018-11-05 14:22
Why not just default to `/` for `GATSBY_WEBPACK_PUBLICPATH` instead of `-h` which doesn't make sense if since its a network address.

**Comment by palerdot** [comment] 2018-11-06 05:50
@pieh `GATSBY_WEBPACK_PUBLICPATH=/ gatsby develop -H 0.0.0.0` works in linux also (tested in a ubuntu vagrant setup). I think `/` path should be made default so that the user's do not have to mention this explicitly. @drubin Sorry, I cannot answer for why it is not a default as I just observed this issue when working with gatsby. I think the relative path `/` should work for all host switches irrespective of `0.0.0.0`. 

So, now `getHmrPath()` can simply `return '/' + hmrSuffix` here - https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/utils/webpack.config.js#L89 ?

**Comment by pieh** [comment] 2018-11-08 13:34
`gatsby@2.0.42` was released with changes from PR

**Closed by pieh** 2018-11-08 13:34 UTC
Labels: status: confirmed, type: bug
