### ISSUE TITLE
Can I prefix generated assets path with a different hostname?

### ISSUE THREAD

**Issue by gniquil** [gatsbyjs/gatsby#11305] opened 2019-01-26 03:00 UTC
Hi All,

Is there a way to prefix generated assets path with a different hostname? For example, in one of my generated html page:

```
<script src="/webpack-runtime-9218435a32b25df1b08e.js" async=""></script>
```
I would like to make it:

```
<script src="https://123123123.cloudfront.net/webpack-runtime-9218435a32b25df1b08e.js" async=""></script>
```

Is this possible? I tried `prefixPath`, but it doesn't work. The reason I want to do this is I have a rails app. For certain pages I am using reverse proxy to host the pages. For example:
```
www.example.com/promo1 <- proxied from -< 1231232.cloudfront.net/anotherpage (generated by Gatsby)
```
While the html part of the page works, all the assets in the html, without the hostname prefix, will be coming from `www.example.com`. This is a lot less than ideal as I would like to directly fetch it from cloudfront. 

In rails, for assets, we can configure the asset host to be something other than the main site. Can this be done in Gatsby?

**Comment by gniquil** [comment] 2019-01-26 07:47
Hi All,

Here's something really hacky but seems to work.

```js
// gatsby-ssr.js

const modifyPrefix = comp => {
  if (comp.props && comp.props.href) {
    return {
      ...comp,
      props: {
        ...comp.props,
        href: `${HOSTNAME}${comp.props.href}`,
      },
    }
  } else if (comp.props && comp.props.src) {
    return {
      ...comp,
      props: {
        ...comp.props,
        src: `${HOSTNAME}${comp.props.src}`,
      },
    }
  } else {
    return comp
  }
}

export const onPreRenderHTML = ({
  getHeadComponents,
  replaceHeadComponents,
  getPreBodyComponents,
  replacePreBodyComponents,
  getPostBodyComponents,
  replacePostBodyComponents,
}) => {
  replaceHeadComponents(getHeadComponents().map(modifyPrefix))
  replacePreBodyComponents(getPreBodyComponents().map(modifyPrefix))
  replacePostBodyComponents(getPostBodyComponents().map(modifyPrefix))
}
```
and

```js
exports.onCreateWebpackConfig = ({ actions, getConfig, stage }) => {
  if (stage === 'build-html' || stage === 'build-javascript') {
    const config = getConfig()

    actions.replaceWebpackConfig({
      ...config,
      output: {
        ...(config.output || {}),
        publicPath: `${HOSTNAME}/`,
      },
    })
  }
}
```
Is this something ok to do?

**Comment by sidharthachatterjee** [comment] 2019-01-28 14:23
Hey @gniquil 

Thank you for opening this and digging around. @DSchau is working on adding support for this in https://github.com/gatsbyjs/gatsby/pull/10933. 

Closing this issue for the moment since it is a duplicate of https://github.com/gatsbyjs/gatsby/issues/8833 but please feel free to follow along the conversation there!

**Closed by sidharthachatterjee** 2019-01-28 14:23 UTC
Labels: type: duplicate
