### ISSUE TITLE
Keep groups in order of grouped items

### ISSUE THREAD

**Issue by timroes** [gatsbyjs/gatsby#7628] opened 2018-08-24 20:06 UTC
Currently when using the `group` operator the returned groups are sorted by the `fieldValue` i.e. the grouped term. I think that's a confusing default behavior and the default behavior should rather: keep the order that the original items had, since these items might have been sorted by using the `sort` parameter.

**Example**

If the original items where in the following order and all having a `g` field with the following values:

* Item 1 (g=B)
* Item 2 (g=B)
* Item 3 (g=A)
* Item 4 (g=C)
* Item 5 (g=A)

I would expect the `group(field: g)` query to return the following order:

* B
  * Item 1
  * Item 2
* A
  * Item 3
  * Item 5
* C
  * Item 4

I.e. it should return group B first, because the first item was in that group (and of course keep the order of items within each group).

**Use-Case**

On the home page I would like to show my blog posts grouped by category, but the category with the most recent posts always on top. So I am using the following query:

```graphql
{
  allMarkdownRemark(sort: { fields: frontmatter___date, order: DESC }) {
    categories: group(field: frontmatter___category) {
      name: fieldValue
      posts: edges {
        node {  ... }
      }
    }
  }
}
```

Unfortunately that does not work, since the grouping inside the query destroys the original order of posts. I think the default behavior of the `group` should be to keep the groups in the order the child items had been after the sort.

**Distinction of other issues**

There is some overlap with #5046 and #3684, which are wishing for an explicit option to sort groups. I think that would be a nice addition too, and THAT sorting option should be the place you should use to sort by grouping key. In distinction this issue should track the suggestion of NOT destroying the orders of items by grouping (independent of a possible group sorting option).

**Comment by jtstodola** [comment] 2019-03-04 22:39
Any update when/if this will be added?

**Comment by FraserThompson** [comment] 2019-04-24 01:02
Also pretty keen on this, seems like logical behaviour to honour the sort behaviour even in groups.

**Comment by wardpeet** [comment] 2019-09-04 08:47
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by timroes** [comment] 2019-09-26 08:53
not stale

**Comment by alejandrorosas** [comment] 2020-05-10 12:56
not stale, still valid. It sorts by group

**Comment by wardpeet** [comment] 2020-05-13 13:28
Can you still add a small reproduction so we can test this without having to setup a test case ourselves?

**Comment by danabrit** [comment] 2020-06-02 22:15
@timroes - Closing due to no reproduction. If you would like to attach a [minimal reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) and re-open this issue, we would be happy to take a look!

**Closed by danabrit** 2020-06-02 22:15 UTC
Labels: status: needs reproduction, topic: GraphQL, type: bug
