### ISSUE TITLE
Downsides to using "gatsby develop" in production?

### ISSUE THREAD

**Issue by acannon828** [gatsbyjs/gatsby#19670] opened 2019-11-20 17:56 UTC
I'm running in to some issues building HTML via "gatsby build" that are similar to those described [here on SO](https://stackoverflow.com/questions/55971033/es6-import-breaks-gatsby-build-webpackerror-referenceerror-element-is-not-de) and [here in the Gatsby docs](https://www.gatsbyjs.org/docs/debugging-html-builds/#fixing-third-party-modules). The suggested adjustments to gatsby-node.js haven't resolved these issues for me.

Running `gatsby develop` seems to render the pages just fine though. Given this, what are the downsides (I suspect there are some big ones?) to just running `gatsby develop` in production, behind some reverse proxy server?

I haven't spent a lot of time digging deeper in to these `gatsby build` issues, and have purposefully not gone in to detail about them here. I'm curious whether or not I can just bypass them entirely via just using `gatsby develop` even in production--I suspect not, but I'm curious why not.

The [CLI docs for develop](https://www.gatsbyjs.org/docs/gatsby-cli/#develop) don't seem to give any hints, nor does discussion of the develop and production environments [here](https://www.gatsbyjs.org/docs/environment-variables/#environments-and-environment-variables).

Thanks all in advance!

**Comment by acannon828** [comment] 2019-11-20 18:14
Maybe this gives some hints? From running `gatsby develop` with `NODE_ENV=production`:

```
Error: It appears like Gatsby is misconfigured. JSONStore is Gatsby internal development-only component and should never be used in production.
```

**Comment by lannonbr** [comment] 2019-11-20 18:26
So `gatsby develop` requires a development mode express server to be running at all times which is more intensive and with such you can not deploy it to a CDN as `gatsby build` will generate static assets, so it is highly reccomended if you are pushing to production you want to use `gatsby build`

**Comment by universse** [comment] 2019-11-21 04:45
You can consider disabling SSR instead.

```js
// gatsby-ssr.js

export const wrapPageElement = () => null
```

**Comment by sidharthachatterjee** [comment] 2019-11-22 11:01
`gatsby develop` is meant for _development_ and there's several optimisations (or rather lack there of) that you'd miss when using it in production, so we'd definitely discourage it. Here's a (probably not comprehensive) list:

- No asset chunking in webpack would mean that you'd serve a single massive JavaScript file as opposed to chunks per page
- A dev 404 page that is only meant for development
- Watchers running for change on disk would unnecessarily keep several handles open which shouldn't be necessary for serving your site 
- Watchers running for change on disk would unnecessarily keep several handles open which shouldn't be necessary for serving your site 
- Gatsby runtime keeping a websocket open on client for data updates which would unnecessarily add network overhead because of heartbeats etc
- GraphiQL would be served at __graphql which you probably don't want for a production site since that would make _all_ your data accessible

Hope this answers your question to some extent. For issues that you're seeing during `build`, perhaps open an issue and link to a reproduction so we can help fixing that?

That way you should be able to serve _built_ assets. 

Closing this for now!

**Closed by sidharthachatterjee** 2019-11-22 11:01 UTC
Labels: type: question or discussion

**Comment by awm086** [comment] 2023-10-05 23:58
Does anyone know how would one run SSR in production without gatsby develop. Suppose I have a custom node server serving the build files how do I build, render and return a response for server side generated content. Everything works in gatsby develop but what’s the point of SSR if it can’t be run in production?
