### ISSUE TITLE
WorkerError: Processing /folder/paht/.cache/caches/default-site-plugin/25582de259075d7cc9b5818039d56  380/reg-img.png failed

### ISSUE THREAD

**Issue by KamranMaqbool** [gatsbyjs/gatsby#26727] opened 2020-08-31 19:10 UTC
i'm update some plugin in my gatsby project.

"gatsby-source-graphql": "^2.1.33",            to current latest version
"gatsby-transformer-sharp": "^2.3.13",       to current latest version
"gatsby-plugin-sharp": "^2.4.3",                  to current latest version
"gatsby-source-filesystem": "^2.1.46",        to current latest version

after update and remove node_modules,package-lock.js,
run gatsby clean commands 
install npm pacakge
after installation "gatsby develop" command generate error.

`Processing /projectPath/.cache/caches/default-site-plugin/25582de259075d7cc9b5818039d56380/reg-img.png failed`

Original error:

`WorkerError: Processing /projectPath/.cache/caches/default-site-plugin/25582de259075d7cc9b5818039d56  380/reg-img.png failed`
`jobs-manager.ts:318 enqueueJob`
`task_queues.js:97 processTicksAndRejections`

not finished run static queries - 8.371s
not finished Generating image thumbnails - 1.030s

After revert to previous npm package version.same error generate

**Envirnoment**
 "gatsby": "^2.19.7",
Ubuntu OS,

![Screenshot from 2020-09-01 00-04-46](https://user-images.githubusercontent.com/53546053/91757281-7e783000-ebe7-11ea-825b-8f8377952df2.png)

**Comment by t2ca** [comment] 2020-08-31 19:41
https://github.com/gatsbyjs/gatsby/issues/26723

**Comment by byronshilly** [comment] 2020-08-31 20:58
Also hitting this issue. Reverting to 2.6.28 fixed the issue. Have no tried 2.6.29 and 2.6.30.

**Comment by ajmalafif** [comment] 2020-09-01 02:05
Same here. Was okay for `2.6.30` but same error with @KamranMaqbool for `2.6.31`

**Comment by wardpeet** [comment] 2020-09-01 05:50
Duplicate of #26723 we'll look into it and let's move the discussion to that thread.

**Closed by wardpeet** 2020-09-01 05:50 UTC
Labels: status: triage needed, type: question or discussion

**Comment by KamranMaqbool** [comment] 2020-09-01 09:39
same issue after revert my previous versions
