### ISSUE TITLE
Error: Generated engines use disallowed import "node-gyp-build". 

### ISSUE THREAD

**Issue by Gamza222** [gatsbyjs/gatsby#35003] opened 2022-03-01 13:17 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi, i faced an error when deploying gatsby app. Please help me, i tried everything
 
![image](https://user-images.githubusercontent.com/84990031/156175846-ac19e39d-1e0a-4fbe-9cb4-f8ab15f165ac.png)

### Reproduction Link

https://github.com/Gamza222/gtsby-website-v1

### Steps to Reproduce

1.pull repo
2.print npm run deploy in cmd
3.you will get an error
...

### Expected Result

i just want it to work))

### Actual Result

ERROR #98001  WEBPACK

Built Rendering Engines failed validation failed validation.

Please open an issue with a reproduction at https://github.com/gatsbyjs/gatsby/issues/new for more help

  Error: Generated engines use disallowed import "node-gyp-build". Only allowed imports are to Node.js builtin modules or engines internals.

### Environment

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 AMD Ryzen 5 1600 Six-Core Processor       
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE        
    npm: 8.5.2 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.2
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.62)
  npmPackages:
    gatsby: ^4.8.0 => 4.8.0
    gatsby-cli: ^4.8.2 => 4.8.2
    gatsby-image: ^3.11.0 => 3.11.0
    gatsby-plugin-gatsby-cloud: ^4.8.0 => 4.8.0
    gatsby-plugin-image: ^2.8.0 => 2.8.0
    gatsby-plugin-manifest: ^4.8.0 => 4.8.0
    gatsby-plugin-offline: ^5.8.0 => 5.8.0
    gatsby-plugin-react-helmet: ^5.8.0 => 5.8.0
    gatsby-plugin-sass: ^5.8.0 => 5.8.0
    gatsby-plugin-sharp: ^4.8.2 => 4.8.2
    gatsby-plugin-styled-components: ^5.8.0 => 5.8.0        
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-filesystem: ^4.8.0 => 4.8.0
    gatsby-transformer-sharp: ^4.8.0 => 4.8.0
  npmGlobalPackages:
    gatsby-cli: 4.8.2
    gatsby-starter-default: 0.1.0
```

**Comment by LekoArts** [comment] 2022-03-01 14:33
Duplicate of https://github.com/gatsbyjs/gatsby/issues/34912

**Closed by LekoArts** 2022-03-01 14:33 UTC
Labels: type: bug
