### ISSUE TITLE
[gatsby] Expose Not Found Page Path to 404 Page

### ISSUE THREAD

**Issue by Undistraction** [gatsbyjs/gatsby#5544] opened 2018-05-24 18:01 UTC
## Summary

It would be useful to be able to access the the page of the path that triggered the 404 within the 404 page so a message could be display:

> Sorry there was no page at 'example/path/here'

`location.pathname` returns `/404` so it is of no use here.

**Comment by Undistraction** [comment] 2018-05-29 16:11
Currently implementation clobbers the `location.pathname' passed into a 404 page and overwrites it with '/404.html', meaning the actual url of the page (as displayed in the address bar) is gone. I don't think this makes any sense, and the PR above (which addressed another issue) also ensures the correct url is passed down to the 404 page via props.

**Comment by Undistraction** [comment] 2018-09-08 05:45
I can understand closing stale bug reports, but this is a valid feature request that is still valid as of V2.

There is still no way to access the original URL that triggered the 404 page on the 404 page in production, though this information is available in development.

**Comment by KyleAMathews** [comment] 2018-09-08 06:07
👍 @davidbailey00 wanna add this to your queue to fix?

**Comment by davidbailey00** [comment] 2018-09-08 06:27
@KyleAMathews @Undistraction I think this should be possible when #7943 is merged (and before I wrote the code which #7943 fixes) since the URL shouldn't be rewritten upon a 404, i.e. `window.location.pathname` should work perfectly fine assuming you can see it in the address bar.

**Comment by rileyjshaw** [comment] 2020-01-01 00:42
Was this fixed? I'm still noticing it in v2.18.17.

I'm just starting to look into it, but it seems `location.pathname` isn't rehydrated. The initial values from build time are used instead.

**Comment by rileyjshaw** [comment] 2020-01-01 00:54
From https://github.com/gatsbyjs/gatsby/pull/5583#issuecomment-423153494:

> There seems to be issue now when visiting non existing page directly (not by gatsby-link or navigate) - react app doesn't get mounted because of thrown errors.

Can confirm.

**Comment by LekoArts** [comment] 2020-05-25 12:33
Please open up a new issue with a reproduction following the issue template if you're still experiencing issues.

**Closed by LekoArts** 2020-05-25 12:33 UTC
Labels: type: bug

**Comment by rileyjshaw** [comment] 2020-05-25 16:53
Okay. Re-logged at https://github.com/gatsbyjs/gatsby/issues/24448.
