### ISSUE TITLE
Hovering over links is causing a page rerender.  Only on pages generated using createPage and that use useStaticQuery

### ISSUE THREAD

**Issue by mrbjjackson** [gatsbyjs/gatsby#30798] opened 2021-04-09 21:35 UTC
## Description
I was noticing that when I hovered over some of the links on my site, some page content (content generated by a custom hook containing a useStaticQuery hook) was changing.

I've discovered that this was because on certain pages, hovering over links was causing a page rerender. This rerender was, in turn causing the useStaticQuery to return "undefined".

Strangely this is only happening on pages created using a `createPage` in gatsby-node.js.

I've created a simplified minimal reproduction of the site that uses JSON as a source rather than sources I was using (Wordpress and Google Calendar) and the bug still occurs.

There is also another strange issue happening (see below) that I'm not sure is linked to the above.

### Steps to reproduce

[https://github.com/mrbjjackson/useStaticQueryBug](https://github.com/mrbjjackson/useStaticQueryBug)

To reproduce the bug, develop the site, open the console, and click "Activities". Then click one of the Activities. Then refresh the page. Finally, hover over any of the links on the page. You will see in the console that the page is rerendering on every link you hover over (You need to have refreshed the page to see this effect).

### Expected result

I don't think this is intended behaviour. And if it is, why is it only happening on pages created using createPage. 

Also - on my production site, this causes the useStaticQuery hooks to fail which is breaking my site.

NOTE: There is also another strange bug that may or may not be related:
In the static query hook I'm using "useCalendar" (which is basically acting as a wrapper for useStaticQuery), the query is returning an empty array, followed by the array with the content I need. As such, to fix this I'm using `data.allDataJson.nodes[1].calendarEvents.nodes` when I would expect to use `data.allDataJson.nodes[0].calendarEvents.nodes` . The first nodes array item is empty for some reason. 

Thanks so much, I really appreciate the help

### Environment

  System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 15.11.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.6.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 87.0
    Safari: 12.1.1
  npmPackages:
    gatsby: ^3.2.1 => 3.2.1 
    gatsby-plugin-gatsby-cloud: ^2.2.0 => 2.2.0 
    gatsby-plugin-google-gtag: ^3.2.0 => 3.2.0 
    gatsby-plugin-image: ^1.2.0 => 1.2.1 
    gatsby-plugin-manifest: ^3.2.0 => 3.2.0 
    gatsby-plugin-offline: ^4.2.0 => 4.2.0 
    gatsby-plugin-react-helmet: ^4.2.0 => 4.2.0 
    gatsby-plugin-sass: ^4.2.0 => 4.2.0 
    gatsby-plugin-sharp: ^3.2.0 => 3.2.1 
    gatsby-source-filesystem: ^3.2.0 => 3.2.0 
    gatsby-transformer-json: ^3.2.0 => 3.2.0 
    gatsby-transformer-sharp: ^3.2.0 => 3.2.0 
  npmGlobalPackages:
    gatsby-cli: 3.2.0

**Comment by mrbjjackson** [comment] 2021-04-09 21:43
Just to add a description of what the site is trying to acheive: 
There are "Activity" content types and "Calendar Entry" content types. The Activity pages are generated by createPage and on each Activity page, I'm trying to use useStaticQuery to query the calendar to show a list of Calendar Events associated with this Activity.

**Comment by vladar** [comment] 2021-04-11 16:46
I think this is a duplicate of #29011 Let's track it there.

**Closed by vladar** 2021-04-11 16:46 UTC
Labels: type: bug
