### ISSUE TITLE
allShopifyProduct createdAt not working using gatsby-source-shopify

### ISSUE THREAD

**Issue by yohdev-gerya** [gatsbyjs/gatsby#38208] opened 2023-06-08 20:41 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

allShopifyProduct createdAt not working using `gatsby-source-shopify`

![Screenshot from 2023-06-08 16-22-07](https://github.com/gatsbyjs/gatsby/assets/135631665/25c92252-ba3d-4f8d-81c0-864572c7719f)

I encountered issues while trying to build the code that I implemented. The code runs successfully in the GraphQL playground, where I am able to obtain the desired values. However, when I attempt to implement the code in a code base files, I encounter an error during the build process.

```
[gatsby-plugin-sitemap]: Error serializing pages Cannot read properties of
undefined (reading 'nodes')

TypeError: Cannot read properties of undefined (reading 'nodes')

```

### Reproduction Link

https://stackblitz.com/github/gatsbyjs/gatsby-starter-minimal

### Steps to Reproduce

1.  
```
{
  allShopifyProduct {
    nodes {
      title
      updatedAt
    }
  }
}

```
2. Above query is working perfect in the playground.
3. I need to run the same query code base in Gatsby config file.
...

### Expected Result

I need the exact product modification dates to the site-map.

### Actual Result

Current I don't have any result it show me a error on the build.

### Environment

```shell
System: Ubuntu 22.04.2 LTS
```

**Comment by LekoArts** [comment] 2023-06-12 04:38
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2023-06-30 11:48
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2023-06-30 11:48 UTC
Labels: type: bug, status: needs reproduction
