### ISSUE TITLE
GraphQL data doesn't match markdown file

### ISSUE THREAD

**Issue by samwilliscreative** [gatsbyjs/gatsby#25860] opened 2020-07-20 00:19 UTC
## Summary
I am performing a query to get some content from a footer.md file in my project. I am then trying to build a button that links to another page using the links array from my file. However, when getting the data back with a GraphQL query, my link url is ../pages/prices instead of just /prices.

My footer.md file:

```
templateKey: footer
links:
  - url: /prices
    text: Prices
```

What actually comes back:

`[{"url":"../pages/prices","text":"Prices"}]`

How can I get just the original data back rather than having the additional ../pages/?

Thanks.

## Reproducing

I have created a small repo that replicates the bug here: https://github.com/samwilliscreative/gatsby-bug
The key files being `src\components\Footer.js` and `src\data\footer.md`
When running the app, you can see that the JSON result of the graphQl query in the footer prints out the full `../pages/prices` rather than `/pages` as seen in the markdown file.

**Comment by LekoArts** [comment] 2020-07-20 06:07
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by samwilliscreative** [comment] 2020-07-20 08:41
@LekoArts I've created a repo that replicates the issue here: https://github.com/samwilliscreative/gatsby-bug

**Comment by samwilliscreative** [comment] 2020-07-23 00:50
It appears that this issue is exclusive to arrays, I have a specific button field rather than an array of buttons, and the link works.

**Comment by samwilliscreative** [comment] 2020-08-12 13:41
Not stale please!

**Comment by freiksenet** [comment] 2020-08-12 14:47
Hi!

I can definitely reproduce this. However I couldn't find where exactly this is happening, it is definitely after initial frontmatter processing, so it's somewhere when page is created, it seems. I'll assign our Subject Matter Expert to this so they can look into it.

Thank you for your patience!

**Comment by pieh** [comment] 2020-08-12 15:16
After checking this out - it's the `fmImagesToRelative` helper function from `gatsby-remark-relative-images` that does it - after adding some debug logs in the package (you have this snippet in gatsby-node that calls it - https://github.com/samwilliscreative/gatsby-bug/blob/54fa5a8f3c6f07bfef5c7a26fcf2851fbfc34d94/gatsby-node.js#L50-L62 )

Result is following:
![Screenshot 2020-08-12 at 17 06 48](https://user-images.githubusercontent.com/419821/90032547-c37f0580-dcbe-11ea-8237-dc1642ff3dac.png)

So this issue should be reported in https://github.com/danielmahon/gatsby-remark-relative-images - I'm not sure if it's even possible to do generic fix for this case, and instead plugin configuration needs to be added there to - for example specify which fields shouldn't be converted (right now it "guesses" if some value is a path or not).

**Closed by pieh** 2020-08-12 15:16 UTC
Labels: topic: Markdown/remark, type: bug
