### ISSUE TITLE
Get stuck on "Building static HTML for pages"

### ISSUE THREAD

**Issue by meiyouqing** [gatsbyjs/gatsby#10630] opened 2018-12-23 10:48 UTC
## Description

I got stuck on "Building static HTML for pages" when I run "gatsby build --prefix-paths".

### Steps to reproduce

I used to build successfully.
At last time i ran `rm -rf public/`
Then run  `gatsby build --prefix-paths`
And i got the unexpected result: 
The process `Building static HTML for pages` last forever!

### Expected result

build complete successfully

### Actual result
forever proceeding the below:
Building static HTML for pages

### Environment

  System:
    OS: macOS 10.14
    CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 60.0.2
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.21 => 2.0.21
    gatsby-image: ^2.0.5 => 2.0.9
    gatsby-plugin-algolia: ^0.1.0 => 0.1.0
    gatsby-plugin-catch-links: ^2.0.2 => 2.0.3
    gatsby-plugin-feed: ^2.0.5 => 2.0.5
    gatsby-plugin-google-analytics: ^2.0.6 => 2.0.6
    gatsby-plugin-layout: ^1.0.2 => 1.0.2
    gatsby-plugin-manifest: ^2.0.2 => 2.0.3
    gatsby-plugin-netlify: ^2.0.0 => 2.0.0
    gatsby-plugin-offline: ^2.0.6 => 2.0.6
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
    gatsby-plugin-react-svg: ^2.0.0 => 2.0.0
    gatsby-plugin-sharp: ^2.0.5 => 2.0.5
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.1
    gatsby-plugin-styled-jsx: ^3.0.1 => 3.0.1
    gatsby-plugin-styled-jsx-postcss: ^2.0.2 => 2.0.2
    gatsby-remark-copy-linked-files: ^2.0.5 => 2.0.5
    gatsby-remark-emojis: ^0.2.3 => 0.2.3
    gatsby-remark-external-links: ^0.0.4 => 0.0.4
    gatsby-remark-images: ^2.0.1 => 2.0.2
    gatsby-remark-prismjs: ^3.0.0 => 3.0.0
    gatsby-remark-responsive-iframe: ^2.0.5 => 2.0.5
    gatsby-remark-smartypants: ^2.0.5 => 2.0.5
    gatsby-source-filesystem: ^2.0.1 => 2.0.1
    gatsby-transformer-remark: ^2.1.3 => 2.1.3
    gatsby-transformer-sharp: ^2.1.1 => 2.1.2
  npmGlobalPackages:
    gatsby-cli: 2.4.6

**Comment by meiyouqing** [comment] 2018-12-23 10:51
here is the screen cut of the command lines
<img width="1092" alt="wx20181223-164223 2x" src="https://user-images.githubusercontent.com/6309684/50382857-731af480-06e3-11e9-99fe-a77804a43fe7.png">

**Comment by sidharthachatterjee** [comment] 2018-12-24 12:39
@meiyouqing I just tried to reproduce this using the steps you listed in your issue and everything seems to be working fine. 

Can you try deleting the `.cache` directory in root and build again? Please link to a minimal reproduction repo if possible.

**Comment by meiyouqing** [comment] 2018-12-24 14:18
@sidharthachatterjee Thanks a lot! It solved my issue by deleting the `.cache` directory. Everything work fine now!

**Comment by sidharthachatterjee** [comment] 2018-12-24 14:21
You're welcome @meiyouqing 🙂 

Closing this for now but please feel free to comment if you see this again

**Closed by sidharthachatterjee** 2018-12-24 14:21 UTC
Labels: status: needs reproduction, type: question or discussion
