### ISSUE TITLE
gatsby-image generates images for unused components

### ISSUE THREAD

**Issue by vsolanogo** [gatsbyjs/gatsby#26561] opened 2020-08-20 13:26 UTC
to improve development start time sometimes i remove all the pages in page folder expect one i will work on, i expect that gatsby image will render images only for those components that it used in that page.js file and its children, but it doesn't, gatsby will render same amount of images, same size of images as it was all pages anyway

### Expected result

don't generate images with gatsby image for unused components

### Actual result

doesn't matter whether you develop with just single file in page folder (meaninig you deloping only 1 page) or 50 gatsby-image will generate all the images into public folder

**Comment by polarathene** [comment] 2020-08-21 01:59
Did you clear out any cache? `gatsby clean` should work. If you are referring to image graphql queries, I'm not sure how that's handled, but the JS side for `gatsby-image` components should not be built or included in your bundle. The graphql queries are run at build time triggering the image processing, none of that matters for deployment.

What you want is being tracked [here](https://github.com/gatsbyjs/gatsby/issues/24822). Unrelated to `gatsby-image` components.

**Comment by blainekasten** [comment] 2020-08-25 15:22
Closing as duplicate of https://github.com/gatsbyjs/gatsby/issues/24822

**Closed by blainekasten** 2020-08-25 15:22 UTC
Labels: status: triage needed, type: bug
