### ISSUE TITLE
Meta tags generated by react-helmet are not placed directly in the HTML

### ISSUE THREAD

**Issue by ukch** [gatsbyjs/gatsby#10414] opened 2018-12-11 13:27 UTC
## Description

I am using react-helmet and the equivalent Gatsby plugin to generate meta tags for my site. At a cursory glance, everything seems to be working OK, except the meta tags are not written to the HTML itself (during `gatsby build`) but are dynamically added by JavaScript after the page is loaded. This has the side effect that many if not all of my meta tags are functionally useless, as most search engines only inspect the raw HTML to find meta tags. Would it be possible to change the process so that these meta tags are actually written to the HTML files?

### Steps to reproduce

`src/pages/index.js`:
```jsx
import React from "react";
import Helmet from "react-helmet";

export default () => (
    <Helmet>
        <meta name="test" value="helmet is working properly" />
    </Helmet>
);
```

`gatsby-config/js`:
```javascript
module.exports = {
    plugins: [
        "gatsby-plugin-react-helmet",
    ],
};
```

Run `gatsby build` and inspect the contents of the generated `public/` directory.

### Expected result

`public/index.html` should contain the 'test' meta tag with the value 'helmet is working properly'.

### Actual result

The 'test' meta tag is dynamically added to the DOM via one of the JS files.

### Environment
```
  System:
    OS: Linux 4.16 Debian GNU/Linux buster/sid undefined
    CPU: (4) x64 Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz
    Shell: 5.6.2 - /usr/bin/zsh
  Binaries:
    Node: 9.2.1 - /usr/local/nvm/versions/node/v9.2.1/bin/node
    Yarn: 1.3.2 - /usr/local/nvm/versions/node/v9.2.1/bin/yarn
    npm: 6.4.1 - /usr/local/nvm/versions/node/v9.2.1/bin/npm
  Browsers:
    Chrome: 70.0.3538.110
    Firefox: 63.0.3
  npmPackages:
    gatsby: ^2.0.55 => 2.0.55 
    gatsby-image: ^2.0.22 => 2.0.22 
    gatsby-plugin-eslint: ^2.0.1 => 2.0.1 
    gatsby-plugin-postcss: ^2.0.0 => 2.0.0 
    gatsby-plugin-react-helmet: ^3.0.4 => 3.0.4 
    gatsby-plugin-sharp: ^2.0.14 => 2.0.14 
    gatsby-source-filesystem: ^2.0.10 => 2.0.10 
    gatsby-transformer-sharp: ^2.1.9 => 2.1.9 
  npmGlobalPackages:
    gatsby-cli: 2.4.6
```

**Comment by LekoArts** [comment] 2018-12-11 14:09
Hi 👋 
I couldn't reproduce this with the default starter: https://github.com/gatsbyjs/gatsby-starter-default
The build output shows all tags.

Did you try other meta tags? Do you have a repository where this issue occurs?

**Comment by DSchau** [comment] 2018-12-11 15:49
`react-helmet` has an SSR mode--that we're using.

To validate this, as @LekoArts said, you can use the default starter and inspect the generated contents.

```bash
npx gatsby new meta-example # this uses the default starter
cd meta-example
npm run build
cat public/index.html | grep meta
```

or (if on Node 6)

```bash
npm install -g gatsby-cli
gatsby new meta-example && cd meta-example
npm run build
cat public/index.html | grep meta
```

This will let you see all the generated meta tags at _build time_ which doesn't require JS to enhance or augment that functionality.

I'm going to close this as answered, but if you can provide a reproduction showing differently we'd love to take a look!

**Closed by DSchau** 2018-12-11 15:49 UTC
Labels: status: needs more info, type: question or discussion

**Comment by alexpchin** [comment] 2020-11-06 14:43
@ukch Do you have an example of the solution that you came up with to solve this problem?

**Comment by rvalle** [comment] 2022-06-18 06:54
@ukch I came to this issue. have spent long time trying to debug why helmet is not generating meta tags on static html. In my case I believe that using the same react function name for pages triggered the issue. (probably a copy&paste issue of page.js files)

**Comment by PieterT2000** [comment] 2023-02-28 15:06
In my case the meta tags weren't included in the static html file because I was conditionally rendering the SEO component. 
![image](https://user-images.githubusercontent.com/47913749/221893644-b64abcac-6114-41a8-97f9-82a809602104.png)
