### ISSUE TITLE
Some `<p/>` elements have no className when build only on homepage "/", but works if you change page and come back

### ISSUE THREAD

**Issue by hackhat** [gatsbyjs/gatsby#9141] opened 2018-10-16 04:52 UTC
## Description

Some paragraphs are rendered just as `<p>text</p>` instead of the p with the class from emotion-js. 

### Steps to reproduce

Add config:

    `gatsby-plugin-emotion`,
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              // It's important to specify the maxWidth (in pixels) of
              // the content container as this plugin uses this as the
              // base for generating different widths of each image.
              maxWidth: 1200,
              linkImagesToOriginal: false,
              backgroundColor: 'transparent',
              withWebp: true,
            },
          },
        ],
      },
    },

Render with custom ast function:

    export const renderAst = new rehypeReact({
      createElement: React.createElement,
      components: {
        'main-cta': MainCta,
        'buy-product-button': BuyProductButton,
        'youtube': (props) => <YouTubeEmbeed {...props}/>,
        h1: types.H1,
        h2: types.H2,
        h3: types.H3,
        p: types.Paragraph,
        a: (props) => <types.Link {...props} to={props.href}/>,
        li: types.Li,
        ul: types.Ul,
      },
    }).Compiler

Add some markdown with h1, h2 and paragraphs.

Some paragraphs are rendered just as `<p>text</p>` instead of the p with the class from emotion-js. 

 - Only happens in the output build on the first page render
 - If I change page and I come back the <p> has the classname
 - Happens in the same places on every re-build
   - Sometimes the first <p/> immediately below a <h2/>
   - Sometimes the first <p/> immediately below a <h1/>
   - Sometimes 2nd <p/> below a <h2/> (first <p/> in this case renders correctly)
   - I have a side bar that renders on many pages. It is broken only on the home page.
 - Consistent in different browsers (even google fetch sees the same bug)
 - All broken text is from the home page, path "/"

### Expected result

All <p> should have the classname from emotion-js

### Actual result

Some <p> have no classname at all.

### Environment

    System:
        OS: Windows 10
        CPU: x64 Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
      Binaries:
        Yarn: 1.9.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
        npm: 5.5.1 - C:\Program Files\nodejs\npm.CMD
      Browsers:
        Edge: 42.17134.1.0
      npmPackages:
        gatsby: ^2.0.19 => 2.0.21
        gatsby-plugin-catch-links: ^2.0.4 => 2.0.4
        gatsby-plugin-emotion: ^2.0.5 => 2.0.5
        gatsby-plugin-google-analytics: ^2.0.6 => 2.0.6
        gatsby-plugin-manifest: ^2.0.5 => 2.0.5
        gatsby-plugin-offline: ^2.0.5 => 2.0.6
        gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0
        gatsby-plugin-sharp: ^2.0.6 => 2.0.6
        gatsby-plugin-typescript: ^2.0.0 => 2.0.0
        gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
        gatsby-remark-images: ^2.0.4 => 2.0.4
        gatsby-source-filesystem: ^2.0.3 => 2.0.3
        gatsby-transformer-remark: ^2.1.7 => 2.1.7

**Comment by pieh** [comment] 2018-10-16 12:07
Could you put together minimal reproduction site and post link to repo?

**Comment by hackhat** [comment] 2018-10-17 15:02
I can't reproduce anymore. But definitively was broken. I just added different text and it fixed. You can close if you wish or you can investigate.

**Comment by pieh** [comment] 2018-10-17 16:12
@hackhat It's hard to investigate if we can't reproduce and backtrack to see what is causing this. Let's close this for now - but if you hit this problem please comment back so we re-open issue with more details

**Closed by pieh** 2018-10-17 16:12 UTC
Labels: status: needs reproduction, type: bug
