### ISSUE TITLE
(node:4770) [DEP0130] DeprecationWarning

### ISSUE THREAD

**Issue by t2ca** [gatsbyjs/gatsby#19604] opened 2019-11-18 21:30 UTC
Getting the following error since upgrading node to v13.1.0

```
success load plugins - 1.937s

 ERROR

(node:4770) [DEP0130] DeprecationWarning: Module.createRequireFromPath() is deprecated. Use Module.createRequire() instead.
```

**Comment by LekoArts** [comment] 2019-11-19 09:13
Hi!
Please follow our issue template in the future so that we can help you better.

We still support Node 8 and hence some of our dependencies might use deprecated APIs. Similar issue: https://github.com/gatsbyjs/gatsby/issues/18433#issuecomment-545040822

Depending on your stack it might or might not be possible right now to update.

**Comment by LekoArts** [comment] 2019-11-20 10:00
Duplicate of https://github.com/gatsbyjs/gatsby/issues/19634

**Closed by LekoArts** 2019-11-20 10:00 UTC
Labels: status: needs more info
