### ISSUE TITLE
Gatsby and trailing slashes: inconsistent behavior

### ISSUE THREAD

**Issue by MaximeHeckel** [gatsbyjs/gatsby#26193] opened 2020-08-02 18:53 UTC
## Description

Hi so I'm just catching up on some SEO knowledge I didn't have in the past and looking at canonical URLs where I had a couple of things to fix.  I see a lot of issues that were opened related to SEO, trailing slashes, and Netlify a while ago but no clear answers.

1. I use gatsby-plugin-canonical-urls to generate my canonical URLs and they do not have a trailing `/`
2. On my website, I do not have any links navigating a user to a URL with a trailing `/`
3. When running a Lighthouse SEO audit I do see that Lighthouse was redirected:

<img width="1351" alt="Screen Shot 2020-08-02 at 1 30 51 PM" src="https://user-images.githubusercontent.com/2974412/89129849-b7c95d00-d4ce-11ea-921d-cf9213e67c52.png">

4. I use gatsby-plugin-offline (latest) and I'm getting a weird behavior with the generated canonical URLs:
- When the cache is cleared: the canonical URL is set as expected
- When the website is cached: the canonical URL points to https://blog.maximeheckel.com/offline-plugin-app-shell-fallback/

I'm pretty sure this is somehow related to the trailing `/` issue but I'm not 100% sure

What I'm looking for here is to have a clear solution or the official version for what to do to fix this bug 😄 

Shall I:
- Add a trailing `/` to every link? This seems to fix the Lighthouse issue but my canonical URLs still do not have trailing `/`
- Add a trailing `/` to every slug of my blog entries? 
- Remove gatsby-plugin-offline? I've seen it causing related issues to many people
- Edit some Netlify settings in my `netlify.toml` (I host my blog on Netlify)

### Steps to reproduce

- Clone [my blog](https://github.com/MaximeHeckel/blog.maximeheckel.com) (it's a fairly light gatsby project as everything is abstracted in a theme)
- Run `yarn build:dev`
- Run `yarn serve`
- Go to http://localhost:9000
- Run a lighthouse SEO audit on one of the blog entries and observe the error message showcased in the screenshot above
- View the source of the website and observe the canonical url being present without `/` or some times replaced by https://blog.maximeheckel.com/offline-plugin-app-shell-fallback/

### Expected result

I should have a consistent result and behavior regarding trailing `/`

### Actual result

I have generated canonical URLs without trailing `/` but Lighthouse tells me that the actual true URLs for my posts have trailing `/` and I'm scared of being negatively impacted on my SEO ranking

### Environment

```

  System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.6.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.13.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4147.105
    Firefox: 76.0.1
    Safari: 13.1.1
  npmPackages:
    gatsby: 2.21.11 => 2.21.11 
    gatsby-image: 2.2.43 => 2.2.43 
    gatsby-plugin-canonical-urls: ^2.3.10 => 2.3.10 
    gatsby-plugin-feed: ^2.5.7 => 2.5.7 
    gatsby-plugin-google-analytics: ^2.0.9 => 2.3.1 
    gatsby-plugin-lunr: ^1.5.2 => 1.5.2 
    gatsby-plugin-manifest: 2.3.3 => 2.3.3 
    gatsby-plugin-mdx: ^1.2.6 => 1.2.6 
    gatsby-plugin-offline: 3.2.21 => 3.2.21 
    gatsby-plugin-printer: 1.0.8 => 1.0.8 
    gatsby-plugin-react-helmet: ^3.1.3 => 3.3.1 
    gatsby-plugin-sitemap: 2.2.27 => 2.2.27 
    gatsby-plugin-typescript: ^2.2.2 => 2.4.2 
    gatsby-remark-sectionize: ^1.0.0 => 1.0.0 
    gatsby-source-filesystem: ^2.1.9 => 2.3.1 
    gatsby-theme-maximeheckel: 0.10.0 => 0.10.0 

```

Thank you in advance, I absolutely have a blast with Gatsby, but this issue is a bit of a rabbit hole

**Comment by vladar** [comment] 2020-08-03 15:42
I did a quick sanity check - disabled javascript, service workers, cleared all caches, and opened a blog post on your website (without a trailing slash). Was immediately redirected to the URL with a trailing slash.

So it looks like your webserver is redirecting to URLs like this. Seems that you're using Netlify, so you probably need to set it up properly to avoid redirects in the first place.

**Comment by vladar** [comment] 2020-08-03 15:43
Oh, also sounds like a duplicate of https://github.com/gatsbyjs/gatsby/issues/9207

**Comment by vladar** [comment] 2020-08-03 15:47
I am closing this as a duplicate of #9207 but feel free to re-open if you're sure that your situation is different.

**Closed by vladar** 2020-08-03 15:47 UTC
Labels: type: bug

**Comment by MaximeHeckel** [comment] 2020-08-03 17:53
Thank you @vladar yes after looking a bit there're a lot of different standards clashing between Netlify and Gatsby. Will dig deeper and document here or the other issue my findings
