### ISSUE TITLE
gatsby-source-filesystem: cannot query allFile

### ISSUE THREAD

**Issue by designforhuman** [gatsbyjs/gatsby#9281] opened 2018-10-21 16:42 UTC
I can't query allFile after installing gatsy-source-filesystem.
It is the same when I started a fresh gatsby hello-world project with only the plugin installed. I didn't do anything else, but I still cannot find allFile tag on graphiQL either.
Does it has to be with my computer? Do you have some suggestions to solve this? Thanks.

  System:
    OS: macOS 10.14.1
    CPU: x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    Yarn: 1.10.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Firefox: 57.0.2
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.0.0 => 2.0.19 
    gatsby-source-filesystem: ^2.0.5 => 2.0.5 
  npmGlobalPackages:
    gatsby-cli: 2.4.3
    gatsby: 1.9.261

**Comment by KyleAMathews** [comment] 2018-10-21 16:50
Can you share your code? Or a site which reproduces the problem? I assume you've read the plugin's README closely?

**Comment by designforhuman** [comment] 2018-10-21 16:57
@KyleAMathews 
On my main project, I heavily use gatsby-source-contentful. But when I installed gatsby-source-filesystem, I couldn't query somehow.
To just be sure, I started a fresh basic project -> https://www.gatsbyjs.org/tutorial/part-one/
Then I installed gatsby-source-filesystem -> https://www.gatsbyjs.org/tutorial/part-five/#source-plugins
Then I guess I should be able to query allFile like in the tutorial?
![image](https://user-images.githubusercontent.com/4755755/47269806-b77ffc00-d59d-11e8-9ade-b479c1937858.png)
But I don't see it.

**Comment by KyleAMathews** [comment] 2018-10-21 16:59
Can you provide steps to reproduce the problem? We don't hear this bug report often so we need to understand better what you're doing to help.

**Comment by designforhuman** [comment] 2018-10-21 17:11
@KyleAMathews 
NPM 6.x and the latest gatsby installed. 
1. gatsby new hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world
2. npm install --save gatsby-source-filesystem
3. made gatsby-config.js
4. added the code below
module.exports = {
  plugins: [
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `src`,
        path: `${__dirname}/src/`,
      },
    },
  ],
}
5. access to localhost:8000/___graphql
6. can't find allFile
I did this both on my Mac and MacBook. They don't work. 
Did I miss some step?

**Comment by KyleAMathews** [comment] 2018-10-21 17:13
Did you run `gatsby develop`?

**Comment by designforhuman** [comment] 2018-10-21 17:15
@KyleAMathews 
Yes. That would be the step between 5 and 6. Otherwise I wouldn't able to see the graphql ready screen.

**Comment by KyleAMathews** [comment] 2018-10-21 17:16
Can you push your code to a repo on GitHub?

**Comment by stefanprobst** [comment] 2018-10-22 09:17
> npmGlobalPackages:
> gatsby-cli: 2.4.3
> gatsby: 1.9.261

I cannot reproduce this with your reproduction repo. Could you try again after removing your outdated global gatsby version?

**Comment by stefanprobst** [comment] 2018-10-22 09:17
> npmGlobalPackages:
> gatsby-cli: 2.4.3
> gatsby: 1.9.261

I cannot reproduce this with your reproduction repo. Could you try again after removing your outdated global gatsby version?

**Comment by stefanprobst** [comment] 2018-10-22 09:18
> npmGlobalPackages:
> gatsby-cli: 2.4.3
> gatsby: 1.9.261

I cannot reproduce this with your reproduction repo. Could you try again after removing your outdated global gatsby version?

**Comment by stefanprobst** [comment] 2018-10-22 09:19
> npmGlobalPackages:
> gatsby-cli: 2.4.3
> gatsby: 1.9.261

I cannot reproduce this with your reproduction repo. Could you try again after removing your outdated global gatsby version?

**Comment by designforhuman** [comment] 2018-10-22 15:32
@stefanprobst Could you try again?

**Comment by stefanprobst** [comment] 2018-10-22 15:46
Yup, still working. To me this seems to indicate a problem with your local setup. I assume you have removed your global gatsby install?

**Comment by designforhuman** [comment] 2018-10-22 15:52
@stefanprobst Yes. I did npm uninstall gatsby-cli.
Do you guess which local setup may cause the problem?

**Comment by designforhuman** [comment] 2018-10-22 16:40
@stefanprobst Oh you're right. I did npm uninstall -g gatsby.
But I still don't see the allFile. Do you have other suspicious local setups that cause the problem?

**Comment by stefanprobst** [comment] 2018-10-22 16:52
Ok so to summarize, after the following steps it works for me, but not for you:
```bash
git clone https://github.com/designforhuman/gatsby-test
cd gatsby-test
npm install
npm run develop
```
Then I'm out of ideas, sorry, maybe someone else?

**Comment by designforhuman** [comment] 2018-10-22 16:59
@stefanprobst I did the 4 steps you mentioned. It still doesn't work. It is very strange.

**Comment by designforhuman** [comment] 2018-10-23 17:42
@stefanprobst @KyleAMathews 
It seems like most of the plugins are not working for me (ie. gatsby-transformer-remark, gatsby-plugin-sharp, etc.) 
while some of them is working properly such as gatsby-source-contentful.
Do you have any idea what is happening here? Have you heard of similar problems?
This is what I tested with.
https://github.com/designforhuman/gatsby-test2.git

**Comment by designforhuman** [comment] 2018-10-26 15:15
I formatted my drive and reinstalled a Mojave beta as before. It's still not working. Could it be something to do with the beta OS? Let me go back to the public release and try this again.

**Comment by stefanprobst** [comment] 2018-11-01 09:44
If this is solved, can you close the issue?

**Comment by DSchau** [comment] 2018-11-01 14:20
@stefanprobst always feel comfortable to close if the issue seems objectively closed!

@designforhuman thanks for letting us know it's fixed!

**Closed by DSchau** 2018-11-01 14:20 UTC

**Comment by petermunro** [comment] 2019-02-15 13:58
Just leaving this here in case it helps anyone else. I had the same problem, with `allDirectory` and `directory` appearing in GraphiQL, but not `allFile` or `file` on node v11.9.0 and MacOS 10.14.2. I did a `touch src/data/foo.mdx`, restarted `npm run develop` and they appeared.

**Comment by sanderfish** [comment] 2019-04-02 08:07
I just ran into the same / similar issue. Running `gatsby clean` solved it for me.

**Comment by chadalen** [comment] 2019-06-01 17:20
I had the same issue with the allFile not being shown. @petermunro's solution worked for me on Ubuntu Linux.
