### ISSUE TITLE
Gatsby V4 looping rebuild

### ISSUE THREAD

**Issue by Yofret-Rios** [gatsbyjs/gatsby#37334] opened 2022-12-24 17:06 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi Folks, I decided to open an issue since I have been browsing the discussion forums and the Issues section and couldn't find something that might help in solving this issue.

I recently upgraded from Gatsby V3 to V4 as part of our upgrade plans, we are planning to get to V5 eventually, but we would like to do it incrementally.

After following all the upgrade steps and upgrading the plugins and necessary library, I found out that Gatsby version 4 has an infinite looping **rebuilt** behavior, it does recompile the bundle too often and with no apparent pattern and also without changes to the codebase itself, the files that trigger the rebuild are located in `./cache` directory as seen in the logs, this was not a behavior present on V3.

I was wondering if there is a way to prevent the bundle from rebuilding if there are changes in the `./cache` folder, thanks in advance for any help provided.

### Reproduction Link

Can't provide a reproduction link

### Steps to Reproduce

- Upgrade from v3 to v4

### Expected Result

It should not rebuild if there are no changes to the codebase (Or preloading content via Link hover)

### Actual Result

The bundle will rebuild

```
verbose Transition to "waiting"
success Writing page-data.json files to public directory - 0.011s - 0/312 27713.21/s
verbose Webpack file changed:*/.cache/webpack/stage-develop/index.pack
verbose Transition to "waiting" > "aggregatingFileChanges"
verbose Transition to "runningQueries"
success onPreExtractQueries - 0.003s
success extract queries from components - 0.341s
verbose Transition to "runningQueries" > "waitingPendingQueries"
verbose Transition to "runningQueries" > "writingRequires"
success write out requires - 0.031s
verbose Transition to "runningQueries" > "calculatingDirtyQueries"
verbose Transition to "runningQueries" > "runningStaticQueries"
verbose Transition to "runningQueries" > "runningPageQueries"
verbose Transition to "runningQueries" > "waitingForJobs"
verbose Transition to "runningQueries" > "done"
verbose Transition to "recompiling"
warn ./.cache/app.js
Critical dependency: the request of a dependency is an expression
success Re-building development bundle - 0.809s
warn The size of at least one page context chunk exceeded 500kb, which could lead to degraded performance. Consider putting less data in the page context.
verbose Transition to "waiting"
success Writing page-data.json files to public directory - 0.011s - 0/312 28315.59/s
verbose Webpack file changed: */.cache/webpack/stage-develop/index.pack
verbose Transition to "waiting" > "aggregatingFileChanges"
verbose Transition to "runningQueries"
success onPreExtractQueries - 0.003s
success extract queries from components - 0.346s
verbose Transition to "runningQueries" > "waitingPendingQueries"
verbose Transition to "runningQueries" > "writingRequires"
success write out requires - 0.028s
verbose Transition to "runningQueries" > "calculatingDirtyQueries"
verbose Transition to "runningQueries" > "runningStaticQueries"
verbose Transition to "runningQueries" > "runningPageQueries"
verbose Transition to "runningQueries" > "waitingForJobs"
verbose Transition to "runningQueries" > "done"
verbose Transition to "recompiling"
warn ./.cache/app.js
Critical dependency: the request of a dependency is an expression
success Re-building development bundle - 0.637s
warn The size of at least one page context chunk exceeded 500kb, which could lead to degraded performance. Consider putting less data in the page context.
verbose Transition to "waiting"
success Writing page-data.json files to public directory - 0.012s - 0/312 26169.28/s
verbose Webpack file changed: */.cache/webpack/stage-develop/index.pack
verbose Transition to "waiting" > "aggregatingFileChanges"
verbose Transition to "runningQueries"
success onPreExtractQueries - 0.001s
success extract queries from components - 0.250s
verbose Transition to "runningQueries" > "waitingPendingQueries"
verbose Transition to "runningQueries" > "writingRequires"
success write out requires - 0.028s
verbose Transition to "runningQueries" > "calculatingDirtyQueries"
verbose Transition to "runningQueries" > "runningStaticQueries"
verbose Transition to "runningQueries" > "runningPageQueries"
verbose Transition to "runningQueries" > "waitingForJobs"
verbose Transition to "runningQueries" > "done"
verbose Transition to "recompiling"
warn ./.cache/app.js
Critical dependency: the request of a dependency is an expression
success Re-building development bundle - 0.785s
warn The size of at least one page context chunk exceeded 500kb, which could lead to degraded performance. Consider putting less data in the page context.
verbose Transition to "waiting"
success Writing page-data.json files to public directory - 0.007s - 0/312 45212.48/s
verbose Webpack file changed: */.cache/webpack/stage-develop/index.pack
verbose Transition to "waiting" > "aggregatingFileChanges"
verbose Transition to "runningQueries"
success onPreExtractQueries - 0.003s
success extract queries from components - 0.341s
verbose Transition to "runningQueries" > "waitingPendingQueries"
verbose Transition to "runningQueries" > "writingRequires"
success write out requires - 0.028s
verbose Transition to "runningQueries" > "calculatingDirtyQueries"
verbose Transition to "runningQueries" > "runningStaticQueries"
verbose Transition to "runningQueries" > "runningPageQueries"
verbose Transition to "runningQueries" > "waitingForJobs"
verbose Transition to "runningQueries" > "done"
verbose Transition to "recompiling"
warn ./.cache/app.js
```

### Environment

```shell
System:
    OS: macOS 13.0.1
    CPU: (8) arm64 Apple M1
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.98
    Firefox: 107.0.1
    Safari: 16.1
  npmPackages:
    gatsby: ^4.24.0 => 4.25.0 
    gatsby-cli: ^4.24.0 => 4.25.0 
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5 
    gatsby-plugin-create-client-paths: ^3.9.0 => 3.15.0 
    gatsby-plugin-datadog: ^1.1.1 => 1.1.1 
    gatsby-plugin-google-tagmanager: ^4.24.0 => 4.25.0 
    gatsby-plugin-image: ^2.24.0 => 2.25.0 
    gatsby-plugin-jss: ^4.24.0 => 4.25.0 
    gatsby-plugin-manifest: ^4.24.0 => 4.25.0 
    gatsby-plugin-purgecss: ^6.1.2 => 6.1.2 
    gatsby-plugin-react-helmet: ^5.24.0 => 5.25.0 
    gatsby-plugin-react-helmet-canonical-urls: ^1.4.0 => 1.4.0 
    gatsby-plugin-s3: ^0.3.8 => 0.3.8 
    gatsby-plugin-sass: ^5.24.0 => 5.25.0 
    gatsby-plugin-schema-snapshot: ^3.24.0 => 3.25.0 
    gatsby-plugin-sentry: ^1.0.1 => 1.0.1 
    gatsby-plugin-sharp: ^4.24.0 => 4.25.0 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.24 => 1.1.30 
    gatsby-source-contentful: ^7.22.0 => 7.23.0 
    gatsby-source-filesystem: ^4.24.0 => 4.25.0 
    gatsby-transformer-sharp: ^4.24.0 => 4.25.0
```

### Config Flags

FAST_DEV: true
PRESERVE_FILE_DOWNLOAD_CACHE: true
DEV_SSR: true

**Comment by tyhopp** [comment] 2023-01-03 07:11
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2023-01-17 14:30
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2023-01-17 14:30 UTC
Labels: type: bug, status: needs reproduction

**Comment by stevenbdf** [comment] 2023-03-02 19:30
@Yofret-Rios I'm having this issue too. I'm working in a Nx monorepo, with Yarn v3 and PnP.
I tried with both Gatsby v4 and v5 and I get the same warning and it builds in loop, which is annoying.

```
warn ./.cache/app.js
Critical dependency: the request of a dependency is an expression
``` 

Did you make it work in your end?

**Comment by Yofret-Rios** [comment] 2023-03-07 14:57
Hi @stevenbdf, Unfortunately, I haven't been able to work around this issue, what I did to alleviate the issues was to downgrade the current version to `4.14.0` I noticed that for some reason is a lot more stable than the latest version 4, which I'm aware that is not latest overall version, please let me know if you find a different workaround, I did try various flags and different things but I had no effect.

**Comment by joshytaco** [comment] 2023-03-08 16:51
I'm also having this issue. I _think_ I've been able to trace it down to the conditional `require` statements in `./.cache/app.js`, for example:
```js
if (HAS_REACT_18) {
  const reactDomClient = require(`react-dom/client`)
...
```
