### ISSUE TITLE
TypeScript sites break with gatsby@2.9.9

### ISSUE THREAD

**Issue by ryanditjia** [gatsbyjs/gatsby#14905] opened 2019-06-19 11:41 UTC
## Description

Something changed between 2.9.8 and 2.9.9 that breaks Gatsby sites with TypeScript. Problem doesn’t seem to have to do with `gatsby-plugin-typescript`, but more to do with Gatsby looking for an `index.js`. But please take that observation with a grain of salt.

### Steps to reproduce

Clone this minimal repo: https://github.com/ryanditjia/gatsby2.9.9-issue.git

Run `npm start`

### Expected result

Develop should run fine.

### Actual result

Getting this error:

```
project_root/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

RangeError: Maximum call stack size exceeded
    at Array.values (<anonymous>)
    at Object.console.error
... and so on
```

### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.4.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.7.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 60.0.2
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.9.9 => 2.9.9 
    gatsby-plugin-typescript: ^2.0.15 => 2.0.15

**Comment by IngoValente** [comment] 2019-06-19 11:45
Same here, reverting back to 2.9.8 works without problems.

**Comment by chrsep** [comment] 2019-06-19 11:59
Same here, this happens to me only on `gatsby develop`, not on `gatsby build`. I think this might have something to do with the introduction of the status bar a0353be34b53eec7263c236256bfa9ca164fa7cf? Crash seems to be coming from GatsbyReporter.

**Comment by iAdramelk** [comment] 2019-06-19 12:10
Same for me. Reverting to 2.9.8 fixed issue.

MacOS 10.14.5 (18F132), node 12.4.0.

**Comment by KyleAMathews** [comment] 2019-06-19 12:31
Hmm will look soon. I started a (non typescript) site and it worked correctly. Are the rest of you using typescript as well?

**Comment by KyleAMathews** [comment] 2019-06-19 12:31
2.9.9 was the release with the status bar.

**Comment by chrsep** [comment] 2019-06-19 12:33
Yes, i am on typescript as well.

**Comment by iAdramelk** [comment] 2019-06-19 12:42
Typescript, yes.

**Comment by wardpeet** [comment] 2019-06-19 12:49
@ryanditjia thanks for the repro. Currently testing it out with the following fix:
`npm install gatsby@process-develop`

**Comment by n8tb1t** [comment] 2019-06-19 12:58
I'm having the same error, though, I'm not using `typescript`

**Comment by n8tb1t** [comment] 2019-06-19 13:01
installing the `gatsby@process-develop` seems to fix the bug.

**Comment by wardpeet** [comment] 2019-06-19 13:09
We forgot to add `import fetch from "node-fetch"` on the file where we were using fetch. `node-fetch` adds fetch to the global namespace so you should only import it once. While testing it on a repo where a plugin was also initiating node-fetch it gave no problem.

Projects without any plugins using node-fetch break.

**Comment by wardpeet** [comment] 2019-06-19 13:10
@n8tb1t can you define ugly? 😛 

![image](https://user-images.githubusercontent.com/1120926/59768302-6ba86280-92a4-11e9-8912-9bd8036ea07b.png)

**Comment by n8tb1t** [comment] 2019-06-19 13:14
> @n8tb1t can you define ugly? 😛
> 
> ![image](https://user-images.githubusercontent.com/1120926/59768302-6ba86280-92a4-11e9-8912-9bd8036ea07b.png)

Yes, exactly like this. The horizontal line takes too much space, and the project name breaks at the end.
I noticed it has some kind of prompt, what it can be used for?
:)

**Comment by sidharthachatterjee** [comment] 2019-06-19 13:23
Fixed and published in `gatsby-cli@2.6.13`

Thank you for opening this @ryanditjia and fixing this @wardpeet 🙌

**Comment by dennisroethig** [comment] 2019-08-26 06:56
Hm, I'm still getting this on `gatsby serve` 😕

**Comment by dandv** [comment] 2020-05-31 01:28
I'm on Gatsby 2.22.13 and get this cryptic error,

```
/sandbox/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: write EPIPE
```

Here's the [Code Sandbox](https://codesandbox.io/s/gatsby-typescript-minimal-ilhi7?file=/package.json).

**Comment by sidharthachatterjee** [comment] 2020-06-16 12:49
@dandv This issue is likely unrelated. The unfortunate fact here is the cryptic error message (which is internal and conceals the real error 😞)

Apologies for the confusion. I'll go ahead and close this issue again. (By the way your Sandbox seems to work fine)

If you're still seeing this issue, a new issue with a reproduction would be helpful!

**Closed by sidharthachatterjee** 2020-06-16 12:49 UTC
Labels: status: confirmed, type: bug
