### ISSUE TITLE
yoga-layout-preview throws error after a WordPress change has been detected: gatsby-source-wordpress

### ISSUE THREAD

**Issue by kelleyco2** [gatsbyjs/gatsby#31563] opened 2021-05-24 20:01 UTC
## Description

Running `gatsby develop` usually fails with this errror:
```
/Users/cooperkelley/HQ/hey-grill-hey-3.0/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:62005
    at Server.setupListenHandle [as _listen2] (net.js:1318:16)
    at listenInCluster (net.js:1366:12)
    at GetAddrInfoReqWrap.doListen (net.js:1503:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:8)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1345:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 62005
}
```

It seems to happen when the gatsby-source-wordpress plugin detects a change in WordPress.

### Environment
```
System:
    OS: macOS 11.3.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.npm-global/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 87.0
    Safari: 14.1
  npmPackages:
    gatsby: ^3.3.0 => 3.3.0
    gatsby-plugin-algolia: ^0.19.0 => 0.19.0
    gatsby-plugin-gatsby-cloud: ^2.1.0 => 2.1.0
    gatsby-plugin-google-analytics: ^3.1.0 => 3.1.0
    gatsby-plugin-image: ^1.1.2 => 1.1.2
    gatsby-plugin-react-helmet: ^4.1.0 => 4.1.0
    gatsby-plugin-root-import: ^2.0.6 => 2.0.6
    gatsby-plugin-sharp: ^3.1.2 => 3.1.2
    gatsby-plugin-sitemap: ^3.1.0 => 3.1.0
    gatsby-plugin-styled-components: ^4.1.0 => 4.1.0
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-filesystem: ^3.1.0 => 3.1.0
    gatsby-source-shopify: ^4.4.0 => 4.4.0
    gatsby-source-wordpress: ^4.1.0-next.1 => 4.1.0-next.1
    gatsby-transformer-sharp: ^3.1.0 => 3.1.0
  npmGlobalPackages:
    gatsby-cli: 3.4.1
```

**Comment by LekoArts** [comment] 2021-05-25 07:46
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by jacksellwood** [comment] 2021-05-25 18:23
Closing as duplicate in favor of this issue: https://github.com/gatsbyjs/gatsby/issues/30308

**Closed by jacksellwood** 2021-05-25 18:23 UTC
Labels: status: needs reproduction, topic: WordPress, type: bug
