### ISSUE TITLE
 failed Building production JavaScript and CSS bundles,ERROR #98123  WEBPACK 

### ISSUE THREAD

**Issue by anto-pv** [gatsbyjs/gatsby#28610] opened 2020-12-14 14:50 UTC
I lost my entire day searching solution for ERROR #98123  WEBPACK  when building gatsby site . 
I found it's due to case-sensitive in the components, and tried many times changing name case of all compenents.
But getting,
failed Building production JavaScript and CSS bundles - 0.095s

 ERROR #98123  WEBPACK

undefined failed

Cannot read property 'includes' of undefined

The issues similar to this doesn't giving an accurate solution, so please provide a solution else it should be better to move to other react frameworks.

**Comment by LekoArts** [comment] 2020-12-14 16:06
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by anto-pv** [comment] 2020-12-14 17:13
Website: https://github.com/anto-pv/Portfolio.git
It is running in locally without any errors.
But when doing, netlify deploy or  gatsby build, it's showing:
............................................
`success run static queries - 0.015s - 1/1 68.59/s
success write out requires - 0.007s
failed Building production JavaScript and CSS bundles - 0.104s

 ERROR #98123  WEBPACK

undefined failed

Cannot read property 'includes' of undefined`

**Comment by ibrahimgediktr** [comment] 2020-12-17 17:36
> Website: https://github.com/anto-pv/Portfolio.git
> It is running in locally without any errors.
> But when doing, netlify deploy or gatsby build, it's showing:
> ............................................
> `success run static queries - 0.015s - 1/1 68.59/s
> success write out requires - 0.007s
> failed Building production JavaScript and CSS bundles - 0.104s
> 
> ERROR #98123 WEBPACK
> 
> undefined failed
> 
> Cannot read property 'includes' of undefined`

did you solve the problem ? I'm having the same problem.

**Comment by whatjackhasmade** [comment] 2020-12-19 10:47
I'm also only having this issue on Netlify and not locally

**Comment by ibrahimgediktr** [comment] 2020-12-19 11:43
> I'm also only having this issue on Netlify and not locally

I also get this problem on Netlify. I couldn't solve the problem for 2 days. Local is also running the project, but I get this error when I build at locally.

**Comment by anto-pv** [comment] 2020-12-19 14:10
I don't found the solution yet, then I tried with gh-pages using Gatsby Deploy github actions and it worked for me.

**Comment by ajayalfred** [comment] 2020-12-22 02:36
Same problem as @ibrahimgediktr. gatsby develop is building the site just fine, gatsby build gives me the same error
====
failed Building production JavaScript and CSS bundles - 0.102s
error undefined failed

Cannot read property 'includes' of undefined

**Comment by anto-pv** [comment] 2020-12-22 03:27
> Same problem as @ibrahimgediktr. gatsby develop is building the site just fine, gatsby build gives me the same error pasted below:
> 
> failed Building production JavaScript and CSS bundles - 0.102s
> error undefined failed
> 
> Cannot read property 'includes' of undefined

Try gatsby build, may be your code was wrong ,or  if that's building site fine then try using github actions

**Comment by ajayalfred** [comment] 2020-12-22 17:41
I did try **gatsby-build**. I'm developing locally, when I run **gatsby-develop** the website build correctly without any errors. When I try **gatsby-build** it throws this error at the "Building production JavaScript and CSS bundles" step. I tried deploying to Netlify and running build, got the same error.

Attaching screenshots of the output logs when using gatsby-develop:
<img width="649" alt="Screen Shot 2020-12-22 at 9 40 19 AM" src="https://user-images.githubusercontent.com/2425179/102917250-b7a80a80-4439-11eb-803a-19fb944b3154.png">

Attaching screenshots of the output logs when using gatsby-build:
<img width="889" alt="Screen Shot 2020-12-22 at 9 40 53 AM" src="https://user-images.githubusercontent.com/2425179/102917277-cabada80-4439-11eb-9126-bc60dd2f8bc8.png">

Info about my build environment
<img width="507" alt="Screen Shot 2020-12-22 at 9 41 21 AM" src="https://user-images.githubusercontent.com/2425179/102917316-dad2ba00-4439-11eb-87f9-1df118240688.png">

**Comment by ajayalfred** [comment] 2020-12-22 17:47
Updated npm and install gatsby-cli globally. Getting this error now. Making some progress! Any suggestions for this issue?

<img width="561" alt="Screen Shot 2020-12-22 at 9 46 02 AM" src="https://user-images.githubusercontent.com/2425179/102917732-8ed44500-443a-11eb-8caa-fc515f6d971d.png">

**Comment by ibrahimgediktr** [comment] 2020-12-22 17:58
> Updated npm and install gatsby-cli globally. Getting this error now. Making some progress! Any suggestions for this issue?
> 
> <img width="561" alt="Screen Shot 2020-12-22 at 9 46 02 AM" src="https://user-images.githubusercontent.com/2425179/102917732-8ed44500-443a-11eb-8caa-fc515f6d971d.png">
> 

I tried every way but it didn't work, I deleted my node module and package-lock.json file but it didn't work, I had to created the project again, I completely deleted and rebuilt the project, and I didn't get any errors.

**Comment by ajayalfred** [comment] 2020-12-22 18:00
Ok I'll give that a shot. Can you post your **gatsby-info** here? Thanks

**Comment by ibrahimgediktr** [comment] 2020-12-22 18:13
> Ok I'll give that a shot. Can you post your **gatsby-info** here? Thanks
Here

![Adsız](https://user-images.githubusercontent.com/67916168/102919741-7267f500-449a-11eb-93a9-34f2b21c5ab1.png)

**Comment by ajayalfred** [comment] 2020-12-22 19:19
Found the issue! I went through package.json line by line and removed all the packages that weren't necessary. Webpack was included for some reason. Able to run **develop** and **build** without any issues now.

**Comment by ibrahimgediktr** [comment] 2020-12-22 20:20
> Found the issue! I went through package.json line by line and removed all the packages that weren't necessary. Webpack was included for some reason. Able to run **develop** and **build** without any issues now.

I'm glad you solved the problem, but I still don't know what caused the real problem.

**Comment by mjwbenton** [comment] 2020-12-23 12:07
I had this issue as well after using npm-check-updates to upgrade everything. This had moved my webpack dependency to 5.11.0. Going back to webpack@4 has solved the issue for me.

Not working: webpack@5.11.0
Working: webpack@4.22.2

**Comment by ibrahimgediktr** [comment] 2020-12-24 01:04
> I had this issue as well after using npm-check-updates to upgrade everything. This had moved my webpack dependency to 5.11.0. Going back to webpack@4 has solved the issue for me.
> 
> Not working: webpack@5.11.0
> Working: webpack@4.22.2

yes, I updated the version of the webpack in the old project, and it works, the cause of the issue was webpack, Thanks Matt 👍

**Comment by chrispytoes** [comment] 2020-12-29 21:42
I just has the same issue as well. Downgrading Webpack from `5.11.0` to `4.22.0` also fixed it for me. `gatsby develop` was working but `gatsby build` would always stop with:

```
ERROR #98123  WEBPACK

undefined failed

Cannot read property 'includes' of undefined
```

**Comment by ibrahimgediktr** [comment] 2020-12-29 21:58
> I just has the same issue as well. Downgrading Webpack from `5.11.0` to `4.22.0` also fixed it for me. `gatsby develop` was working but `gatsby build` would always stop with:
> 
> ```
> ERROR #98123  WEBPACK
> 
> undefined failed
> 
> Cannot read property 'includes' of undefined
> ```

are you using graphql query ? can you share your codes ?

**Comment by arsinclair** [comment] 2020-12-30 00:49
The error thrown by webpack doesn't provide any information as on where is this `undefined.includes()` happening, so I guessing it is in my code I had to check it in all places where I use includes. But the problem is not in our code. I thought that sharing my findings will save someone a few minutes. The actual places where the issue happens is index.js of `mini-css-extract-plugin`. 

https://github.com/webpack-contrib/mini-css-extract-plugin/blob/master/src/index.js#L113

This package receives a `webpack.compiler` config object and tries to call includes() method on  `compiler.options.optimization.splitChunks.defaultSizeTypes` which is _undefined_. As you can see in the code above, it does it only if the webpack version !== 4.

**Comment by arsinclair** [comment] 2020-12-30 02:37
> status: needs reproduction

@LekoArts , here's a small repository I've created to reproduce the problem: https://github.com/arsinclair/gatsby-webpack-err-repro

**Comment by chrispytoes** [comment] 2020-12-31 14:20
@ibrahimgediktr I have many graphql queries but I'm not sure which ones would be relevant. I am using `gatsby-source-wordpress-experimental`, and TailwindCSS with PostCSS using `gatsby-plugin-postcss`. If any of that information helps.

**Comment by lgastler** [comment] 2021-01-05 13:14
> I had this issue as well after using npm-check-updates to upgrade everything. This had moved my webpack dependency to 5.11.0. Going back to webpack@4 has solved the issue for me.
> 
> Not working: webpack@5.11.0
> Working: webpack@4.22.2

Had the same problem & error. Webpack was installed in version 5 because gatsby is used within in a monorepo (nx). Downgrading Webpack to version 4 or removing it also solved the problem for me. Now, `gatsby build` runs without problems again, `gatsby develop` has worked without problems all the time.

**Comment by LekoArts** [comment] 2021-01-11 10:15
I'll close the issue as the original issue was solved (if you use different casings for filenames, you must respect those as build systems like Netlify that run on Linux are not forgiving on this and are case-sensitive). The error is then coming from an internal part of webpack and we can't control that error messsage itself.

As the other reports are not related to that, but plenty of answers came in anyways:

Gatsby isn't compatible with webpack 5 at the moment. If you somehow override the internal version used by Gatsby breakages are expected. You'll need to resolve/force the version of Gatsby to v4 (e.g. with yarn's `resolutions` feature).

**Closed by LekoArts** 2021-01-11 10:15 UTC
Labels: status: needs reproduction, type: bug

**Comment by Camus1859** [comment] 2021-02-27 18:26
Not working: webpack@5.11.0
Working: webpack@4.19.1
