### ISSUE TITLE
scheduler.development.js:107 Uncaught TypeError: callback is not a function

### ISSUE THREAD

**Issue by FengShangWuQi** [gatsbyjs/gatsby#17705] opened 2019-09-18 05:06 UTC
## Description

callback is not a function when update gatsby related packages and react to latest.

### Steps to reproduce

repositories: https://github.com/FengShangWuQi/fengshangwuqi.github.io

1、`npm run check` // update all packages to latest
2、`npm start` // start project

### Expected result

open page with no error

### Actual result

callback is not a function

### Environment

```
  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.132
    Safari: 12.1.2
  npmPackages:
    gatsby: 2.15.16 => 2.15.16 
    gatsby-image: 2.2.19 => 2.2.19 
    gatsby-plugin-emotion: 4.1.6 => 4.1.6 
    gatsby-plugin-feed: 2.3.12 => 2.3.12 
    gatsby-plugin-google-analytics: 2.1.16 => 2.1.16 
    gatsby-plugin-offline: 3.0.7 => 3.0.7 
    gatsby-plugin-page-creator: 2.1.17 => 2.1.17 
    gatsby-plugin-react-helmet: 3.1.7 => 3.1.7 
    gatsby-plugin-sharp: 2.2.22 => 2.2.22 
    gatsby-plugin-svgr: 2.0.2 => 2.0.2 
    gatsby-plugin-twitter: 2.1.6 => 2.1.6 
    gatsby-plugin-typescript: 2.1.8 => 2.1.8 
    gatsby-plugin-typography: 2.3.7 => 2.3.7 
    gatsby-remark-autolink-headers: 2.1.10 => 2.1.10 
    gatsby-remark-copy-linked-files: 2.1.19 => 2.1.19 
    gatsby-remark-emojis: 0.3.2 => 0.3.2 
    gatsby-remark-external-links: 0.0.4 => 0.0.4 
    gatsby-remark-images: 3.1.22 => 3.1.22 
    gatsby-remark-prismjs: 3.3.13 => 3.3.13 
    gatsby-remark-responsive-iframe: 2.2.16 => 2.2.16 
    gatsby-remark-smartypants: 2.1.8 => 2.1.8 
    gatsby-source-filesystem: 2.1.22 => 2.1.22 
    gatsby-transformer-remark: 2.6.22 => 2.6.22 
    gatsby-transformer-sharp: 2.2.14 => 2.2.14 
  npmGlobalPackages:
    gatsby-cli: 2.7.47
```

react

```
react: 16.9.0
react-dom: 16.9.0
```

**Comment by LekoArts** [comment] 2019-09-18 13:17
Could you please post the complete error message you're getting?

**Comment by thomascorthouts** [comment] 2019-09-18 16:51
I got the same error while working locally, was fixable by downgrading `react` & `react-dom` like this
```
react: 16.9.0 -> 16.8.6
react-dom: 16.9.0 -> 16.8.6
```

I'm not 100% sure, but it might be because of a mismatch in scheduler versions, e.g. running `npm list scheduler` w/ `react` & `react-dom` upgraded resulted in this:
<img width="252" alt="Screenshot 2019-09-18 at 12 48 46" src="https://user-images.githubusercontent.com/26603461/65168553-c58b0680-da12-11e9-860c-c61962cc2b25.png">

And after downgrading, they matched again:
<img width="521" alt="Screenshot 2019-09-18 at 12 46 38" src="https://user-images.githubusercontent.com/26603461/65168579-d89dd680-da12-11e9-8a32-964f824b55a6.png">

**Comment by thomascorthouts** [comment] 2019-09-18 16:55
By recreating this issue locally, I found that (for my project) this only happens after upgrading `react-dom` to `16.9.0` 

```
react: 16.9.0
react-dom: 16.8.6
```

doesn't create this issue

**Comment by FengShangWuQi** [comment] 2019-09-19 03:10
@thomascorthouts thanks so much, really appreciated. I also learned how to resolve dependency problem such like this. thanks again.

**Comment by thomascorthouts** [comment] 2019-09-19 14:24
Hey @FengShangWuQi 

Nice to hear this fixed the issue for you, I'm going to reopen the issue as it is something Gatsby needs to be aware of as it raises the question of how we want to fix this. e.g. setting a specific peer dependency version vs. upgrading the scheduler in gatsby-cli. 
Maybe @wardpeet knows whether this is on the short-term planning for the team (Sorry Ward if you weren't the person to drag in) I'd be fine with helping to resolve this issue in general, I would just need to know what the preferred approach would be.

**Comment by FengShangWuQi** [comment] 2019-09-19 14:50
I find some thing interesting, mismatch of scheduler versions is also appears in gatsby-starter-default project, but gatsby-starter-default works well.

**Comment by LekoArts** [comment] 2019-09-20 11:23
Before we can move to next steps we'd need [a minimal reproduction][reproduction] of the problem first :)

[reproduction]: https://gatsby.dev/reproduction

**Comment by thomascorthouts** [comment] 2019-09-27 08:00
This issue is resolved in the newest version of Gatsby & Gatsby CLI.

**Closed by thomascorthouts** 2019-09-27 08:00 UTC
Labels: status: needs reproduction, type: bug
