### ISSUE TITLE
gatsby-plugin-manifest - Input file contains unsupported image format

### ISSUE THREAD

**Issue by fmunirdev** [gatsbyjs/gatsby#28204] opened 2020-11-20 11:54 UTC
Started facing this issue recently on the Nelify build. `gatsby build` works perfectly fine in the local env.

##### `gatsby-config.js`
```javascript
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `name`,
        short_name: `sname`,
        description: `desc`,
        lang: `en`,
        start_url: `/`,
        background_color: `#fff`,
        theme_color: `#a50f20`,
        display: `standalone`,
        icon: `static/assets/images/icon.png`,
        icon_options: { purpose: `maskable` },
      },
    },
```

### Nelify Deploy Logs
![Nelify Deploy Logs Screenshot](https://i.imgur.com/tyRTlom.png)

**Comment by vladar** [comment] 2020-11-20 12:49
This sounds like is a duplicate of #20698 

Likely happening because Netlify has global `libvips` installed that is incompatible with a local sharp version. The suggested solution is to re-install dependencies from scratch using `SHARP_IGNORE_GLOBAL_LIBVIPS=true`:

```
rm -rf node_modules &&
SHARP_IGNORE_GLOBAL_LIBVIPS=true yarn
```

We're marking this issue as answered and closing it for now but please feel free to comment and mention me if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Closed by vladar** 2020-11-20 12:49 UTC
Labels: status: triage needed, type: bug

**Comment by yiochen** [comment] 2022-01-01 19:11
For anyone using Netlify and facing this issue, you can add the environment variable `SHARP_IGNORE_GLOBAL_LIBVIPS` with value `true` to https://app.netlify.com/sites/<your site>/settings/deploys#environment

This fixed the issue for me.

**Comment by srianbury** [comment] 2022-07-07 23:28
After the deploy failed, I was able to "Clear cache and retry deploy" and that build was successful
<img width="715" alt="Screen Shot 2022-07-07 at 4 23 49 PM" src="https://user-images.githubusercontent.com/27159564/177887795-31e483a1-cdf0-4a0e-b437-3db9a1eb549e.png">

**Comment by eindra** [comment] 2022-08-18 16:02
Setting the SHARP_IGNORE_GLOBAL_LIBVIPS fixed the issue for me! Thank you!

**Comment by TomaszWaszczyk** [comment] 2022-08-18 21:26
Lost on that flag `SHARP_IGNORE_GLOBAL_LIBVIPS` so much time! Thanks @yiochen!

**Comment by jung-youjin** [comment] 2022-12-13 01:17
Works like charm with the `SHARP_IGNORE_GLOBAL_LIBVIPS` variable setting and **Clear cache and retry deploy**! Thank you
