### ISSUE TITLE
The remote WPGraphQL schema hasn't changed but local generated type definitions have. This is a bug, please open an issue on Github and include the following text..

### ISSUE THREAD

**Issue by ThePrimeDev** [gatsbyjs/gatsby#37937] opened 2023-04-13 05:00 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Changed type defs:

Typename WpUser diff:
 {
   kind: "OBJECT"
   config: {
     name: "WpUser"
     fields: {
+      shouldShowAdminToolbar: {
+        type: "Boolean"
+        description: "Whether the Toolbar should be displayed when the user is viewing the site."
+      }
       avatar: {
         type: "WpAvatar"
         description: "Avatar object for user. The avatar object can be retrieved in different sizes by specifying the size argument."
       }
       capKey: {
         type: "String"
         description: "User metadata option name. Usually it will be &quot;wp_capabilities&quot;."
       }
       capabilities: {
         type: "[String]"
         description: "A list of capabilities (permissions) granted to the user"
       }
       comments: {
         type: "WpUserToCommentConnectionType"
         description: "Connection between the User type and the Comment type"
       }
       databaseId: {
         type: "Int!"
         description: "Identifies the primary key from the database."
       }
       description: {
         type: "String"
         description: "Description of the user."
       }
       email: {
         type: "String"
         description: "Email address of the user. This is equivalent to the WP_User-&gt;user_email property."
       }
       extraCapabilities: {
         type: "[String]"
         description: "A complete list of capabilities including capabilities inherited from a role. This is equivalent to the array keys of WP_User-&gt;allcaps."
       }
       firstName: {
         type: "String"
         description: "First name of the user. This is equivalent to the WP_User-&gt;user_first_name property."
       }
       id: {
         type: "ID!"
         description: "The globally unique identifier for the user object."
       }
       isContentNode: {
         type: "Boolean!"
         description: "Whether the node is a Content Node"
       }
       isTermNode: {
         type: "Boolean!"
         description: "Whether the node is a Term"
       }
       lastName: {
         type: "String"
         description: "Last name of the user. This is equivalent to the WP_User-&gt;user_last_name property."
       }
       locale: {
         type: "String"
         description: "The preferred language locale set for the user. Value derived from get_user_locale()."
       }
       name: {
         type: "String"
         description: "Display name of the user. This is equivalent to the WP_User-&gt;dispaly_name property."
       }
       nicename: {
         type: "String"
         description: "The nicename for the user. This field is equivalent to WP_User-&gt;user_nicename"
       }
       nickname: {
         type: "String"
         description: "Nickname of the user."
       }
       pages: {
         type: "WpUserToPageConnectionType"
         description: "Connection between the User type and the page type"
       }
       posts: {
         type: "WpUserToPostConnectionType"
         description: "Connection between the User type and the post type"
       }
       registeredDate: {
         type: "String"
         description: "The date the user registered or was created. The field follows a full ISO8601 date string format."
       }
       roles: {
         type: "WpUserToUserRoleConnectionType"
         description: "Connection between the User type and the UserRole type"
       }
       slug: {
         type: "String"
         description: "The slug for the user. This field is equivalent to WP_User-&gt;user_nicename"
       }
       uri: {
         type: "String"
         description: "The unique resource identifier path"
       }
       url: {
         type: "String"
         description: "A website url that is associated with the user."
       }
       username: {
         type: "String"
         description: "Username for the user. This field is equivalent to WP_User-&gt;user_login."
       }
       nodeType: "String"
     }
     description: "A User object"
     extensions: {
       infer: false
     }
     interfaces: [
       "WpNode"
       "WpUniformResourceIdentifiable"
       "WpCommenter"
       "WpDatabaseIdentifier"
       "Node"
     ]
   }
 }

not finished createSchemaCustomization - 1.794s

### Reproduction Link

https://example.com/no-reproduction

### Steps to Reproduce

1. a
2. b
3. c
...

I dont know how 2 reproduce it, it said that It would be good to report it.

### Expected Result

Expected result: The npm run develop command runs successfully and the program starts.

### Actual Result

I got this error.

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor         
  Binaries:
    Node: 18.15.0 - E:\NodeJS\node.EXE
    npm: 8.12.1 - E:\NodeJS\npm.CMD
  Languages:
    Python: 3.10.9
  Browsers: {}
  npmPackages:
    gatsby: ^5.8.1 => 5.8.1 
    gatsby-plugin-image: ^3.8.0 => 3.8.0 
    gatsby-plugin-sass: ^6.8.0 => 6.8.0 
    gatsby-plugin-sharp: ^5.8.1 => 5.8.1 
    gatsby-source-wordpress: ^7.8.0 => 7.8.0 
    gatsby-transformer-sharp: ^5.8.0 => 5.8.0
```

**Comment by LekoArts** [comment] 2023-04-13 06:44
Duplicate of https://github.com/gatsbyjs/gatsby/issues/37931 - and please provide a minimal reproduction.

**Closed by LekoArts** 2023-04-13 06:44 UTC
Labels: type: bug
