### ISSUE TITLE
 Error: Cannot create as TypeComposer the following value: Date.

### ISSUE THREAD

**Issue by jack0wsky** [gatsbyjs/gatsby#23062] opened 2020-04-13 17:04 UTC
## Description

While running 'gatsby develop' everything works till graphql schema is going to be built. Then it throws error.

 ```
ERROR 

UNHANDLED REJECTION Cannot create as TypeComposer the following value: Date.



  Error: Cannot create as TypeComposer the following value: Date.
  
  - SchemaComposer.js:365 SchemaComposer.createTempTC
    [store]/[graphql-compose]/lib/SchemaComposer.js:365:11
  
  - SchemaComposer.js:563 SchemaComposer.addAsComposer
    [store]/[graphql-compose]/lib/SchemaComposer.js:563:27
  
  - schema-composer.js:35 createSchemaComposer
    [store]/[gatsby]/dist/schema/schema-composer.js:35:18
  
  - index.js:135 Object.build
    [store]/[gatsby]/dist/schema/index.js:135:26
  
  - index.js:419 async module.exports
    [store]/[gatsby]/dist/bootstrap/index.js:419:3
  
  - develop.js:429 async module.exports
    [store]/[gatsby]/dist/commands/develop.js:429:7
  
not finished building schema - 0.172s
```

### Steps to reproduce

Everything worked well until I installed Apollo dependencies and plugin

### Expected result

Error shouldn't appear and app should work

### Actual result

Error when building graphql schema

### Environment

```
  System:
    OS: macOS 10.15.4
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 13.12.0 - ~/.nvm/versions/node/v13.12.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v13.12.0/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v13.12.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 74.0.1
    Safari: 13.1
  npmPackages:
    gatsby: ^2.20.12 => 2.20.18
    gatsby-cli: ^2.11.7 => 2.11.7
    gatsby-image: ^2.3.1 => 2.3.2
    gatsby-plugin-apollo: ^3.0.1 => 3.0.1
    gatsby-plugin-manifest: ^2.3.3 => 2.3.3
    gatsby-plugin-offline: ^3.1.2 => 3.1.2
    gatsby-plugin-react-helmet: ^3.2.1 => 3.2.2
    gatsby-plugin-sharp: ^2.5.3 => 2.5.4
    gatsby-plugin-styled-components: ^3.2.1 => 3.2.1
    gatsby-source-filesystem: ^2.2.2 => 2.2.2
    gatsby-source-graphql: ^2.3.2 => 2.3.2
    gatsby-source-shopify: ^3.1.2 => 3.1.2
    gatsby-theme-apollo: ^3.0.2 => 3.0.2
    gatsby-transformer-sharp: ^2.4.3 => 2.4.4
  npmGlobalPackages:
    gatsby-cli: 2.11.7
    gatsby-starter-default: 0.1.0

```

**Comment by KyleAMathews** [comment] 2020-04-13 17:25
Can you try removing node_modules and reinstalling? Something is breaking the schema creation and it doesn't seem like any of those dependencies would do that.

**Comment by jack0wsky** [comment] 2020-04-13 17:41
> Can you try removing node_modules and reinstalling? Something is breaking the schema creation and it doesn't seem like any of those dependencies would do that.

I tried this solution but didn't work. I will try one more time

**Comment by LekoArts** [comment] 2020-04-14 07:22
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by ParadoxMH** [comment] 2020-04-17 08:47
I have the same issue after update [graphql](https://github.com/graphql/graphql-js/releases/tag/v15.0.0) to 15.0.0
@jack0wsky have you found a solution?

**Comment by jack0wsky** [comment] 2020-04-17 08:49
> I have the same issue after update [graphql](https://github.com/graphql/graphql-js/releases/tag/v15.0.0) to 15.0.0
> @jack0wsky have you found a solution?

No, uninstalled Apollo and refused to solve it :/

**Comment by pkleckner** [comment] 2020-04-25 20:27
In case it helps anyone, I had this issue last night. The solution that seemed to work for me was to delete both the node_modules folder and the package-lock.json file, and then reinstall.

**Comment by bchipev** [comment] 2020-04-26 09:08
Struggling with the same issue on the gatsby auth-aws-amplify starter. Deleting node modules and package-lock.json and then running npm install doesn't change anything.

**Comment by wardpeet** [comment] 2020-05-13 15:23
You probably want to make sure only one grapqhl version is inside your project.

try running
```
npm ls graphql
yarn why graphql
```

If you have multiple, please use [yarn resolutions](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) or remove your lock file and node_modules.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Closed by wardpeet** 2020-05-13 15:23 UTC
Labels: status: needs reproduction, topic: GraphQL

**Comment by jack0wsky** [comment] 2020-05-13 15:31
For those who will face with this issue, I found out that you simply need to install older version of GraphQL. In my case, I had to install ```graphql@^14.6.0``` instead of 15.0.0 version.

**Comment by p0wl** [comment] 2020-05-14 09:33
Installing `graphql@^14.6.0` wasn't enough for me. 
Had to update all dependencies (probably especially gatsby) to solve the issue.

**Comment by guillempuche** [comment] 2020-06-06 17:08
For me, it wasn't downdating Graphql from v15.0 (the latest) to v14.6.0, the solution was in updating Gatsby from v2.21 to v2.23.1 (the latest).

**Comment by pfftdammitchris** [comment] 2020-07-19 16:43
I think the issue was having two graphqls.
I had graphql installed in dependencies, uninstalled it, then npm install gatsby and it worked.

**Comment by kevin-dignizant** [comment] 2022-08-22 07:28
gdffgdggddfdgdfgddggffffffffgd
