### ISSUE TITLE
Gatsby Image and Gatsby Link Slow

### ISSUE THREAD

**Issue by albinoiii** [gatsbyjs/gatsby#29415] opened 2021-02-09 15:10 UTC
Good Day Team,

Images loads so slow and the route using gatsby link is slow.

url: https://zion-ph.com/
project repository url: https://github.com/binoiii/zionph-app

**Comment by LekoArts** [comment] 2021-02-09 15:50
Hi, please fill out the issue template:

```
<!--
  Please fill out each section below, otherwise, your issue will be closed. This info allows Gatsby maintainers to diagnose (and fix!) your issue as quickly as possible.

  Useful Links:
  - Documentation: https://www.gatsbyjs.com/docs/
  - How to File an Issue: https://www.gatsbyjs.com/contributing/how-to-file-an-issue/

  Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
-->

## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```

**Comment by LekoArts** [comment] 2021-02-25 08:37
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-02-25 08:37 UTC
Labels: status: needs reproduction

**Comment by katiasmet** [comment] 2022-07-04 12:40
We have the same problem which is especially visible in desktop Safari.
