### ISSUE TITLE
Problem with multiple images

### ISSUE THREAD

**Issue by milevgeorgi** [gatsbyjs/gatsby#24482] opened 2020-05-26 14:50 UTC
I am using gatsby for 1 month and I am loving it, but I have a question. How to use multiple images on diffrent elements, not one after another. The way I am doing it now is by making multiple image.js files and importing them, I don't think that is correct. I searched in documentation, forums, youtube and many more. Every solution is to query and return them at once. Please help if you can. :)

**Comment by madalynrose** [comment] 2020-05-26 17:19
Hi @milevgeorgi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by milevgeorgi** [comment] 2020-05-26 20:24
I don't think we need minimal reproduction... It's just a general question, how can I add multiple images in different places of a page? Should I make different file for every image or just make a query with all the images that I need and use them on the page ?

**Comment by LekoArts** [comment] 2020-05-27 07:37
Thank you for opening this!

The doc section about images will give you an idea about your options: https://www.gatsbyjs.org/docs/images-and-files/

So e.g.

1) gatsby-iamge
2) static folder
3) webpack import

You can create individual image files for this, you can use a single `useStaticQuery` in a component with multiple queries, you can directly import them.
Having individual files for them is perfectly fine!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2020-05-27 07:37 UTC
Labels: topic: images/media, type: question or discussion
