### ISSUE TITLE
Gatsby latest update breaks execution if run from VSCode terminal, produces several severe errors

### ISSUE THREAD

**Issue by Lokdex** [gatsbyjs/gatsby#27676] opened 2020-10-27 02:10 UTC
## Description

After updating the Gatsby cli to the latest version, I tried to start the development server from VSCode's integrated terminal, it compiles fine, yet when opening the page on the browser the following error message appears:

Error: It appears like Gatsby is misconfigured. JSONStore is Gatsby internal development-only component and should never be used in production.

Unless your site has a complex or custom webpack/Gatsby configuration this is likely a bug in Gatsby. Please report this at https://github.com/gatsbyjs/gatsby/issues with steps to reproduce this error.

Only if run from a separate terminal it seems to work. I am using MacOS btw.

### Steps to reproduce

1. Download or update to latest Gatsby cli.
2. Open project on VSCode and open an integrated terminal within.
3. Start development server

### Expected result

The project compiles and then the page loads.

### Actual result

The following screen shows up:
![image](https://user-images.githubusercontent.com/55822420/97248370-a4791580-17cf-11eb-8d25-285742b85b19.png)

### Environment

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.13.0 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.111
    Safari: 14.0
  npmPackages:
    gatsby: ^2.22.11 => 2.24.80 
  npmGlobalPackages:
    gatsby-cli: 2.12.113
    gatsby-starter-base: 0.4.4

**Comment by vladar** [comment] 2020-11-06 12:20
Hi @Lokdex !

I tried following your steps to reproduce but it worked fine for me. I suspect there is something more to it - maybe some environment quirks, cache, dependencies, or something else.

We need to reproduce this reliably to be able to help. So, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by Lokdex** [comment] 2020-11-06 16:48
Hello, thanks for the reply, but in the latest updates it doesn't happen anymore, and temporarily managed to get over the issue by reinstalling and running from a separate terminal. Would love to help, but currently I have no way of reproducing the error once more. Still loving Gatsby though.

**Comment by vladar** [comment] 2020-11-09 16:42
Thank you for opening this, @Lokdex 

I am going to close this as it appears to be solved. But please feel free to comment and tag me if you would like to continue this discussion.

**Closed by vladar** 2020-11-09 16:42 UTC
Labels: status: needs reproduction, type: bug
