### ISSUE TITLE
gatsby-theme-ui is not working.

### ISSUE THREAD

**Issue by mujeex** [gatsbyjs/gatsby#23962] opened 2020-05-10 15:24 UTC
## Summary
Hello everyone! I am trying to use the theme-ui for a new gatsby project I am working on. After following the instructions on the theme-ui documentation, I am still unable to get theming to work properly. The **sx** props doesn't seem to have access to the theme object create at **/src/gatsby-theme-ui/index.js**. Thanks in advance.
## Relevant information
This is a bug-repo created for reproduction.
https://github.com/mujeex/embsy-bug-repo

### File contents (if changed)

`gatsby-config.js`: 
```
module.exports = {
  ...
  plugins: [
    ...
    'gatsby-plugin-theme-ui',
    
  ],
}
```

`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by laurieontech** [comment] 2020-05-11 13:02
Thanks for your question! I cloned your repo and changed some styles in the sx prop without issue. It appears to be working. My suspicion is that it was a hot-reload or installation issue. Confirm that you've run `npm install` and try starting up your project with `gatsby develop` after that.

I'm going to close this because I haven't be able to reproduce the issue. However, please come back if you're still having trouble.

**Closed by laurieontech** 2020-05-11 13:02 UTC
Labels: topic: themes, type: question or discussion

**Comment by mujeex** [comment] 2020-05-11 13:08
> Thanks for your question! I cloned your repo and changed some styles in the sx prop without issue. It appears to be working. My suspicion is that it was a hot-reload or installation issue. Confirm that you've run `npm install` and try starting up your project with `gatsby develop` after that.
> 
> I'm going to close this because I haven't be able to reproduce the issue. However, please come back if you're still having trouble.

Thank you very much for your support. I also just noticed it was a hot-reload problem and a little bit of CSS specifity issue that caused the issue.
