### ISSUE TITLE
Can't resolve '@reach/router' in 'gatsby-link' and 'gatsby-react-router-scroll'

### ISSUE THREAD

**Issue by codepunkt** [gatsbyjs/gatsby#30029] opened 2021-03-05 10:50 UTC
## Description

Migrated to gatsby 3, now running into this:

```
 ERROR #98124  WEBPACK

Generating development SSR bundle failed

Can't resolve '@reach/router' in
'/home/christoph/projects/codepunkt.de/node_modules/gatsby-link'

If you're trying to use a package make sure that '@reach/router' is installed. If
you're trying to use a local file make sure that the path is correct.

File: node_modules/gatsby-link/index.js:22:14


 ERROR #98124  WEBPACK

Generating development SSR bundle failed

Can't resolve '@reach/router' in
'/home/christoph/projects/codepunkt.de/node_modules/gatsby-react-router-scroll'

If you're trying to use a package make sure that '@reach/router' is installed. If
you're trying to use a local file make sure that the path is correct.

File: node_modules/gatsby-react-router-scroll/use-scroll-restoration.js:10:14

not finished Building development bundle - 4.058s

error Command failed with exit code 1.
```

### Environment

```
  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.15.3 - ~/.nvm/versions/node/v14.15.3/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.9 - ~/.nvm/versions/node/v14.15.3/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
  npmPackages:
    gatsby: ^3.0.2 => 3.0.2
    gatsby-image: ^3.0.0 => 3.0.0
    gatsby-plugin-catch-links: ^3.0.0 => 3.0.0
    gatsby-plugin-feed: ^3.0.0 => 3.0.0
    gatsby-plugin-linaria: ^2.2.0 => 2.2.0
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0
    gatsby-plugin-offline: ^4.0.0 => 4.0.0
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0
    gatsby-plugin-remove-generator: ^1.0.8 => 1.0.8
    gatsby-plugin-robots-txt: ^1.5.5 => 1.5.5
    gatsby-plugin-sharp: ^3.0.0 => 3.0.0
    gatsby-plugin-sitemap: ^3.0.0 => 3.0.0
    gatsby-remark-acronyms: ^1.1.2 => 1.1.2
    gatsby-remark-autolink-headers: ^3.0.0 => 3.0.0
    gatsby-remark-copy-linked-files: ^3.0.0 => 3.0.0
    gatsby-remark-external-links: ^0.0.4 => 0.0.4
    gatsby-remark-images: ^4.0.0 => 4.0.0
    gatsby-remark-opengraph: 2.0.1 => 2.0.1
    gatsby-remark-table-of-contents: ^1.0.0 => 1.0.0
    gatsby-remark-vscode: ^3.2.0 => 3.2.0
    gatsby-source-filesystem: ^3.0.0 => 3.0.0
    gatsby-transformer-remark: ^3.0.0 => 3.0.0
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0
```

**Comment by LekoArts** [comment] 2021-03-05 11:06
Duplicate of https://github.com/gatsbyjs/gatsby/issues/29964

**Closed by LekoArts** 2021-03-05 11:06 UTC
Labels: status: triage needed, type: bug

**Comment by codepunkt** [comment] 2021-03-05 11:10
@LekoArts Is it a duplicate? The other issue looks like it's about to be closed.

**Comment by LekoArts** [comment] 2021-03-05 11:14
It's the same issue, yeah. From our standpoint it's not solved yet.

**Comment by codepunkt** [comment] 2021-03-05 11:14
Can I do anything to help?

**Comment by LekoArts** [comment] 2021-03-05 11:18
Thanks for the offer! :) I'll let @pieh know as he assigned himself this internally.

**Comment by codepunkt** [comment] 2021-03-05 11:21
Great, thanks Lennart!

**Comment by JimLynchCodes** [comment] 2021-05-29 17:00
I didn't see any solution in that issue... I'm getting these errors after a fresh gatsby scaffold- seems to happen with all node versions.

Is there any fix?

**Comment by rowanD72** [comment] 2021-08-24 02:58
I deleted Gatsby-link and downloaded It again, problem solved. Gatsby-link is what is causing the error.

**Comment by bmediax** [comment] 2021-09-18 16:00
Looks like I'm having the same exact issue but on Gatsby Cloud Build
