### ISSUE TITLE
Images displaying incorrectly with gatsby-plugin-mdx

### ISSUE THREAD

**Issue by mrbjjackson** [gatsbyjs/gatsby#17514] opened 2019-09-09 17:31 UTC
Hello,

I was using gatsby-transformer-remark to write content for my website and it was working great. But now I'd like the option of being able to add components to my markdown to make my content fancier.

I've had some success - .mdx content is being passed to my layout and the text is being produced fine. However, each of the images in my content are being displayed twice - once in the ultra-low res "blur-up" version, and below that, in the correct, expected way.

I presume there is some part of the "blur-up" process that is being missed out when my .mdx files are rendered which means that the blurred version remains visible.

Has anyone else had this problem? I'm not sure if this a bug or something I'm doing wrong.

If anyone can help that would be much appreciated. Happy to post any code you need from me too.

Thanks very much.

Ben

**Comment by dcastil** [comment] 2019-09-09 18:52
You can add

```
plugins: ['gatsby-transformer-remark']
```

to the `gatsby-plugin-mdx` options as a temporary workaround and it should work. The bug is tracked in this issue: https://github.com/gatsbyjs/gatsby/issues/15486

**Comment by LekoArts** [comment] 2019-09-09 19:17
Thanks for opening the issue. Let's close this as a duplicate of https://github.com/gatsbyjs/gatsby/issues/15486 :)

**Closed by LekoArts** 2019-09-09 19:17 UTC

**Comment by mrbjjackson** [comment] 2019-09-09 20:30
Fantastic,
Thanks very much for the quick reply. Apologies for raising a duplicate issue. I did have a good search around but didn't see the thread you've linked to. Thanks again.
