### ISSUE TITLE
__refresh only works when Gatsby is running on port 8000

### ISSUE THREAD

**Issue by IAmNatch** [gatsbyjs/gatsby#28333] opened 2020-11-27 22:33 UTC
## Description
When using `ENABLE_GATSBY_REFRESH_ENDPOINT`, the `__refresh` endpoint will only trigger a data refresh if Gatsby's port is set to the default 8000. Setting to other ports causes this to fail silently. 

### Steps to reproduce
1. Fresh install of Gatsby Starter
2. Run `gatsby develop -p 8005`
3. Attempt the curl command: `curl -X POST http://localhost:8005/__refresh`

### Expected result
Command should refresh data as expected.

### Actual result
Silent failure.

### Environment
  ```System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.9.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.9 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /Users/shanerobbins/.pyenv/shims/python
  Browsers:
    Chrome: 87.0.4280.67
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.27.4 => 2.27.4 
    gatsby-image: ^2.5.0 => 2.6.0 
    gatsby-plugin-emotion: ^4.5.0 => 4.5.0 
    gatsby-plugin-manifest: ^2.6.1 => 2.7.0 
    gatsby-plugin-offline: ^3.4.0 => 3.5.0 
    gatsby-plugin-react-helmet: ^3.4.0 => 3.5.0 
    gatsby-plugin-sharp: ^2.9.1 => 2.9.1 
    gatsby-plugin-theme-ui: ^0.3.4 => 0.3.4 
    gatsby-plugin-webfonts: ^1.1.3 => 1.1.3 
    gatsby-source-filesystem: ^2.6.1 => 2.6.1 
    gatsby-source-wagtail: github:GrappleGQL/gatsby-source-wagtail => 0.5.1 
    gatsby-transformer-sharp: ^2.6.0 => 2.7.0 
  npmGlobalPackages:
    gatsby-cli: 2.10.4
```

**Comment by LekoArts** [comment] 2020-11-30 10:30
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2020-12-07 08:09
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-12-07 08:09 UTC
Labels: status: needs reproduction, topic: frontend-core, type: bug
