### ISSUE TITLE
Ship graphql playground as default

### ISSUE THREAD

**Issue by rockmandash** [gatsbyjs/gatsby#4518] opened 2018-03-13 16:42 UTC
Ship https://github.com/graphcool/graphql-playground as default please

**Comment by fk** [comment] 2018-03-13 16:47
Replacing https://github.com/graphql/graphiql?

**Comment by rockmandash** [comment] 2018-03-13 16:56
@fk Yes, as graphql-playground is built upon graphiql.

**Comment by pieh** [comment] 2018-03-13 17:02
This is duplicate of https://github.com/gatsbyjs/gatsby/issues/4231 . Check there to see how you can currently use `graphql-playground`

**Closed by pieh** 2018-03-13 17:02 UTC

**Comment by rockmandash** [comment] 2018-03-14 02:50
Insane~~

**Comment by KyleAMathews** [comment] 2018-03-14 05:22
@rockmandash please be more polite. Your last message feels like harassment which is against our community code of conduct https://www.gatsbyjs.org/code-of-conduct/

**Comment by rockmandash** [comment] 2018-03-14 05:41
@KyleAMathews No, you misunderstand my word.
I mean I can now use graphql-playground which is good.
OK?  you misunderstand too much.

**Comment by KyleAMathews** [comment] 2018-03-14 06:32
Ah sorry! Miscommunication :-)
