### ISSUE TITLE
Gatsby 3 Error: PostCSS plugin postcss-flexbugs-fixes requires PostCSS 8

### ISSUE THREAD

**Issue by LegendaryMediaTV** [gatsbyjs/gatsby#29999] opened 2021-03-04 16:23 UTC
## Description

When I run Gatsby or a Gatsby build, I get the following error on one of my projects:

```
Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS plugin postcss-flexbugs-fixes requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
```

I use identical Gatsby configurations with several other projects and they work fine. I even commented out all of my CSS imports, deleted gatsby-config.js and gatsby-node.js deleted node_modules and re-installed all packages via NPM, but none of that helped.

I looked in the project's node_modules folder and saw that postcss (which is not a direct dependency in my projects) is 7.0.35 and not 8. Interestingly, Gatsby's package.json shows that it wants postcss 8.2.6 and it's node_modules subfolder has that version. So perhaps another plugin (e.g., parcel-bundler, which requires "^7.0.11") won the fight for the main postcss version?

After determining that, I explicitly installed postcss and that finally got it going again. So, perhaps it's an NPM bug (and/or an inherit problem behind my needs to run Gatsby and Parcel Bundler) and not a Gatsby bug, but I figured I would share just in case there was something.

### Steps to reproduce

```
gatsby clean
gatsby develop
```

or

```
gatsby clean
gatsby build
```

### Expected result

The project should build without the PostCSS error.

### Actual result

The project won't run in dev or build for production and gets the following error:

```
success run page queries - 0.044s - 2/2 45.06/s

 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS plugin postcss-flexbugs-fixes requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (C:\Users\username\pathToProject\node_modules\postcss\lib\processor.es6:117:15)
    at new Processor (C:\Users\username\pathToProject\node_modules\postcss\lib\processor.es6:38:25)
    at postcss (C:\Users\username\pathToProject\node_modules\postcss\lib\postcss.es6:34:10)
    at Object.loader (C:\Users\username\pathToProject\node_modules\postcss-loader\dist\index.js:87:20)

File: .cache\blank.css

failed Re-building development bundle - 0.587s
ERROR in ./.cache/blank.css
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
Error: PostCSS plugin postcss-flexbugs-fixes requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users
    at Processor.normalize (C:\Users\username\pathToProject\node_modules\postcss\lib\processor.es6:117:15)
    at new Processor (C:\Users\username\pathToProject\node_modules\postcss\lib\processor.es6:38:25)
    at postcss (C:\Users\username\pathToProject\node_modules\postcss\lib\postcss.es6:34:10)
    at Object.loader (C:\Users\username\pathToProject\node_modules\postcss-loader\dist\index.js:87:20)
    at processResult (C:\Users\username\pathToProject\node_modules\webpack\lib\NormalModule.js:598:19)
    at C:\Users\username\pathToProject\node_modules\webpack\lib\NormalModule.js:692:5
    at C:\Users\username\pathToProject\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at C:\Users\username\pathToProject\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (C:\Users\username\pathToProject\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at Object.loader (C:\Users\username\pathToProject\node_modules\postcss-loader\dist\index.js:96:7)
 @ ./.cache/app.js 26:0-21

1 ERROR in child compilations (Use 'stats.children: true' resp. '--stats-children' for more details)
webpack compiled with 2 errors
```

### Environment

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.81)
  npmPackages:
    gatsby: ^3.0.1 => 3.0.1
    gatsby-plugin-sass: ^4.0.0 => 4.0.0
  npmGlobalPackages:
    gatsby-cli: 2.17.0

**Comment by vladar** [comment] 2021-03-04 17:41
This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/29933

**Closed by vladar** 2021-03-04 17:41 UTC
Labels: status: triage needed, type: bug

**Comment by LegendaryMediaTV** [comment] 2021-03-04 19:49
Sorry I missed the other issue. I think I accidentally left the "open" filter on when searching.

Thanks again!
