### ISSUE TITLE
Using a mapping of mappings in frontmatter of markdown file

### ISSUE THREAD

**Issue by maxwell8888** [gatsbyjs/gatsby#14243] opened 2019-05-22 15:13 UTC
Having generated the gatsby starter blog with:
```
gatsby new my-blog-starter https://github.com/gatsbyjs/gatsby-starter-blog
```
I have added the following mapping of mappings to the frontmatter of the hello world index.md (adapted from example 2.6 of the YAML spec here: https://yaml.org/spec/1.2/spec.html).
```
test: {hr: 65, avg: 0.278}
```
However, running the following GraphQL query returns an error. How can I add a mapping of mappings to the frontmatter without returning an error?
```
{
  allMarkdownRemark {
    edges {
      node {
        frontmatter {
          test
        }
      }
    }
  }
}
```

**Comment by wardpeet** [comment] 2019-05-22 15:27
Hi @maxwell8888!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by maxwell8888** [comment] 2019-05-22 16:36
Hi @wardpeet 
Thanks for your response. Below is a minimal reproduction.

Generate the gatsby starter blog with:
```
gatsby new my-blog-starter https://github.com/gatsbyjs/gatsby-starter-blog
```
Update `content/blog/hello-world/index.md` to (simply adding test: {hr: 65, avg: 0.278} to frontmatter):
```

---
title: Hello World
date: "2015-05-01T22:12:03.284Z"
test: {hr: 65, avg: 0.278}
---

This is my first post on my new fake blog! How exciting!

I'm sure I'll write a lot more interesting things in the future.

Oh, and here's a great quote from this Wikipedia on
[salted duck eggs](http://en.wikipedia.org/wiki/Salted_duck_egg).

> A salted duck egg is a Chinese preserved food product made by soaking duck
> eggs in brine, or packing each egg in damp, salted charcoal. In Asian
> supermarkets, these eggs are sometimes sold covered in a thick layer of salted
> charcoal paste. The eggs may also be sold with the salted paste removed,
> wrapped in plastic, and vacuum packed. From the salt curing process, the
> salted duck eggs have a briny aroma, a gelatin-like egg white and a
> firm-textured, round yolk that is bright orange-red in color.

![Chinese Salty Egg](./salty_egg.jpg)
```
Run develop mode:
```
gatsby develop
```
Open GraphiQL in the browser at http://localhost:8000/___graphql.
Run the below query which generates the unexpected error.
```
{
  allMarkdownRemark {
    edges {
      node {
        frontmatter {
          test
        }
      }
    }
  }
}
```

**Comment by DSchau** [comment] 2019-05-23 18:52
@maxwell8888 I followed your reproduction, and it works just fine!

![Screen Shot 2019-05-23 at 1 50 54 PM](https://user-images.githubusercontent.com/3924690/58278508-d2983180-7d61-11e9-98c8-aa9d4d44dc14.png)

I've provided a [working example here](https://github.com/DSchau/gatsby-14243) so I'm going to close this as answered. Please reply or re-open if we can help further, thanks!

**Closed by DSchau** 2019-05-23 18:52 UTC
