### ISSUE TITLE
gatsby-plugin-emotion adds same css code multiple times

### ISSUE THREAD

**Issue by SimonKlausLudwig** [gatsbyjs/gatsby#27400] opened 2020-10-12 09:12 UTC
## Description

I createad a simple component:

`
import styled from "@emotion/styled";
export const VBList = styled.ul`SOME_CSS`;
`

and used it in my component:

```
export const List = ({items}) => {
    return <VBList>
       <div></div>
    </VBList>
}

```
which then I use in one of my pages multiple times:

`<List/>`

For each time I use the <List/> component I get exact the same CSS code injected into my .html file.

I expected to contains the css just one time. Its a huge overload to inlude it multiple times.

<img width="305" alt="Bildschirmfoto 2020-10-12 um 11 11 21" src="https://user-images.githubusercontent.com/13765114/95728373-bdd07c80-0c7b-11eb-9488-97ab731ee06b.png">
<img width="309" alt="Bildschirmfoto 2020-10-12 um 11 11 12" src="https://user-images.githubusercontent.com/13765114/95728378-bf9a4000-0c7b-11eb-8b16-4470315d9661.png">
<img width="344" alt="Bildschirmfoto 2020-10-12 um 11 11 02" src="https://user-images.githubusercontent.com/13765114/95728380-c032d680-0c7b-11eb-9205-bde57485261f.png">

**Comment by vladar** [comment] 2020-10-12 10:14
Closing as a duplicate of #14321

See also suggestions in https://github.com/emotion-js/emotion/issues/1061

**Closed by vladar** 2020-10-12 10:14 UTC
Labels: topic: emotion, type: bug
