### ISSUE TITLE
activity.setStatus causes a massive performance hit during build (1s slower per 1.000 queries)

### ISSUE THREAD

**Issue by georgiee** [gatsbyjs/gatsby#17452] opened 2019-09-06 16:39 UTC
## Summary
`activity.setStatus` which is used by gatsby during the build to report the page query and html page building progress introduces a performance hit in the dimension of 1s for every 1000 queries. It's like the status call costs exactly 1ms per call. This heavily builds up in environments with 10k's of queries.

Demonstration:
https://github.com/georgiee/gatsby/tree/performance-test-activity/benchmarks/query

(run on my machine, 2,7 GHz Intel Core i7 13 macbook 2018)

## Description
I observed a rather dramatic performance difference while using gatsby's activity tool in our internal source plugin where we process 10-20k pages at the moment. First we thought it's caused by the code block but soon we identified the status update as the cause.

```

exports.sourceNodes = ({ reporter }) => {
  const activity = reporter.activityTimer(`foo`);
  activity.start();

  const count = 10000;
  for(let i = 0; i < count; i++) {
    activity.setStatus('bar' + i);
  }

  activity.end();
}
```

This will take 8.5s on my machine during the build and is doing nothing. From this point I checked on the page query and static html output as those two things also rely on the status update.

Here the results for 10.000 pages/queries. The pages are almost empty, there are actually no page queries to run but still being processed. `.cache` is always cleared.

**1. With activity updates**

| Queries | Static HTML |
| ------------- | ------------- |
| 12.476 s | 4.170 s |
| 13.538 s | 3.981 s |
| 13.190 s | 4.802 s |
| 12.780 s | 4.976 s |

here how it looks like (excerpt). You can see the status being updated. Each update costs around 1ms.
![on](https://user-images.githubusercontent.com/1701755/64443725-de222500-d0d2-11e9-9bf5-57fc8e481cc5.gif)

**2. Without activity updates**
(disabled in gatsby core, behind a new flag)

| Queries | Static HTML |
| ------------- | ------------- |
| 4.181 s | 4.236 s |
| 4.289 s | 4.518 s |
| 4.262 s | 4.327 s |
| 4.158 s | 4.051 s |

Here how it looks like (excerpt). No more status updates.
![off](https://user-images.githubusercontent.com/1701755/64443740-e1b5ac00-d0d2-11e9-8a56-62fad8d68747.gif)

You can see how much faster the queries are running now.  The page process is also a little bit faster but their update frequency is larger so the impact is smaller (0.5-1s faster, comapred to 8-9s faster queries).

This scales almost linear. 20.000 queries causes almost an overhead of 20 seconds.

## Example/Reproduction
Here is the modified Gatsby Project. I used the benchmark project and synced it with `gatsby-dev-cli`.

https://github.com/georgiee/gatsby/tree/performance-test-activity/benchmarks/query

## Solution/Workarounds
1. Let me silence the gatsby build output entirely (I couldn't find any option https://www.gatsbyjs.org/docs/gatsby-cli/#options-1) 
2. Let me choose to display progress updates or not
3. Like with the pages update in larger batches not per query.

## Edit/Appendix
This has also an impact on `gatsby develop` (startup, refresh if enabled) of course as the output is the same for the page queries runner.

**Comment by sidharthachatterjee** [comment] 2019-09-07 08:05
Thanks for the detailed issue! This is known issue and is being tracked upstream in https://github.com/vadimdemedes/ink/issues/212

Also in https://github.com/gatsbyjs/gatsby/issues/15505

**Comment by georgiee** [comment] 2019-09-10 16:09
Hello thanks for those useful references and the upstream issue. My initial idea to turn off status reports entirely with an option would get rid of the Ink dependency and clean up the logs. 

Is this even an option as I don't find any signs of different log output levels in the sources nor do people request that feature. I found the issue with the number 3 from Kyle https://github.com/gatsbyjs/gatsby/issues/3 which was open for quite some time but never implemented.

Should we leave this issue open or close it as a duplicate of #15505 ? Thanks for taking your time, very much appreciated!

**Comment by wardpeet** [comment] 2019-09-10 16:54
thanks @georgiee i'll close this as a duplicate of #15505, let's move the discussion to that thread. This issue will still be linked so we don't lose any information.

Thanks a ton you for the awesome write-down. This is really great.

**Closed by wardpeet** 2019-09-10 16:54 UTC
