### ISSUE TITLE
Unable to load scss file to gatsby 

### ISSUE THREAD

**Issue by anto-pv** [gatsbyjs/gatsby#28524] opened 2020-12-08 05:43 UTC
Describe the issue that you're seeing.

## Description
when gatsby develop,
it gives error on importing scss file giving the error log in console as below :

Generating development JavaScript bundle failed

Node Sass version 5.0.0 is incompatible with ^4.0.0.

package.json:
"gatsby-plugin-sass": "^2.7.0",
    "gatsby-plugin-sharp": "^2.8.0",
    "gatsby-source-filesystem": "^2.5.0",
    "gatsby-transformer-sharp": "^2.6.0",
    "node-sass": "^5.0.0",
    "prop-types": "^15.7.2",

### Steps to reproduce
gatsby new filename
npm install node-sass gatsby-plugin-sass
give the plugin in config
new scss file
import it in a js file
gatsby develop
Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?
should give success build

### Actual result

Generating development JavaScript bundle failed

Node Sass version 5.0.0 is incompatible with ^4.0.0.

File: src\components\header.module.scss

failed Building development bundle - 3.924s

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by LekoArts** [comment] 2020-12-08 08:13
Hey, thanks for the issue! This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/27754

**Closed by LekoArts** 2020-12-08 08:13 UTC
Labels: type: bug

**Comment by anto-pv** [comment] 2020-12-08 08:58
> Hey, thanks for the issue! This is a duplicate of #27754

Thanks for giving the solution. The sass-plugin information in official gatsby website must be changed...to avoid these issues for others
