### ISSUE TITLE
ERROR #11328 A page component must export a React component ... undefined

### ISSUE THREAD

**Issue by Swizec** [gatsbyjs/gatsby#24860] opened 2020-06-08 00:50 UTC
## Description

I'm getting a funky error 11328 with unhelpful debugging information when I run `gatsby build`. Running `gatsby develop` works fine.

### Steps to reproduce

Updated all my dependencies to latest, tried to build the project, it failed.

```
 ERROR #11328 

A page component must export a React component for it to be valid. Please make sure this file exports a React component:

undefined

not finished createPagesStatefully - 0.039s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Here's a minimal-ish repository I extracted from my project where this fails:
https://github.com/Swizec/reactd3lander/tree/error-11328

It correctly shows a single "Hello world" page when you run development mode.

### Expected result

The project should build

### Actual result
```
 ERROR #11328 

A page component must export a React component for it to be valid. Please make sure this file exports a React component:

undefined

not finished createPagesStatefully - 0.039s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Environment

```
  System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.0 - /usr/local/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 71.0
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.23.1 => 2.23.1 
    gatsby-image: 2.4.6 => 2.4.6 
    gatsby-plugin-catch-links: ^2.3.4 => 2.3.4 
    gatsby-plugin-facebook-pixel: ^1.0.3 => 1.0.3 
    gatsby-plugin-google-analytics: ^2.3.3 => 2.3.3 
    gatsby-plugin-manifest: ^2.4.10 => 2.4.10 
    gatsby-plugin-mdx: ^1.2.14 => 1.2.14 
    gatsby-plugin-react-helmet: ^3.3.3 => 3.3.3 
    gatsby-plugin-sharp: ^2.6.10 => 2.6.10 
    gatsby-plugin-simple-analytics: ^1.0.3 => 1.0.3 
    gatsby-plugin-theme-ui: ^0.3.0 => 0.3.0 
    gatsby-plugin-twitter: ^2.3.3 => 2.3.3 
    gatsby-remark-copy-linked-files: ^2.3.4 => 2.3.4 
    gatsby-remark-embedder: ^2.1.1 => 2.1.1 
    gatsby-remark-giphy: ^1.0.4 => 1.0.4 
    gatsby-remark-images: ^3.3.9 => 3.3.9 
    gatsby-remark-relative-images: ^0.3.0 => 0.3.0 
    gatsby-remark-social-cards: ^0.4.1 => 0.4.1 
    gatsby-source-filesystem: ^2.3.10 => 2.3.10 
    gatsby-transformer-remark: ^2.8.14 => 2.8.14 
    gatsby-transformer-sharp: ^2.5.4 => 2.5.4 
  npmGlobalPackages:
    gatsby-cli: 2.7.54
```

**Comment by Swizec** [comment] 2020-06-08 01:08
Downgrading back to this version of everything fixes the problem:

```
  System:
    OS: macOS 10.15.5
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.0 - /usr/local/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 71.0
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.13.48 => 2.15.29 
    gatsby-image: 2.2.0 => 2.2.0 
    gatsby-plugin-catch-links: ^2.1.2 => 2.1.12 
    gatsby-plugin-facebook-pixel: ^1.0.3 => 1.0.3 
    gatsby-plugin-google-analytics: ^2.1.20 => 2.1.20 
    gatsby-plugin-manifest: ^2.2.23 => 2.2.23 
    gatsby-plugin-mdx: ^1.0.22 => 1.0.47 
    gatsby-plugin-offline: ^3.0.16 => 3.0.16 
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.10 
    gatsby-plugin-sharp: ^2.2.31 => 2.2.31 
    gatsby-plugin-simple-analytics: ^1.0.1 => 1.0.1 
    gatsby-plugin-theme-ui: ^0.2.26 => 0.2.43 
    gatsby-plugin-twitter: ^2.1.14 => 2.1.14 
    gatsby-remark-copy-linked-files: ^2.1.28 => 2.1.28 
    gatsby-remark-embedder: ^2.0.1 => 2.0.1 
    gatsby-remark-giphy: ^1.0.4 => 1.0.4 
    gatsby-remark-images: ^3.1.28 => 3.1.28 
    gatsby-remark-relative-images: ^0.2.3 => 0.2.3 
    gatsby-remark-social-cards: ^0.4.1 => 0.4.1 
    gatsby-source-filesystem: ^2.1.33 => 2.1.33 
    gatsby-transformer-remark: ^2.6.37 => 2.6.45 
    gatsby-transformer-sharp: ^2.2.23 => 2.2.23 
  npmGlobalPackages:
    gatsby-cli: 2.7.54
```

**Comment by sarathm09** [comment] 2020-06-08 08:33
Even I'm facing the same issue when running `gatsby build` inside Github Actions. In mo system it works fine. I tried changing the versions as mentioned above, but it didn't help.

**Comment by sarathm09** [comment] 2020-06-08 08:36
Logs:
``` 
gatsby build --prefix-paths
success open and validate gatsby-configs - 0.045s
success load plugins - 1.026s
success onPreInit - 0.026s
success delete html and css files from previous builds - 0.010s
success initialize cache - 0.009s
success copy gatsby files - 0.018s
success onPreBootstrap - 1.189s
success createSchemaCustomization - 0.003s
success source and transform nodes - 3.049s
success building schema - 0.242s
success createPages - 0.000s
error A page component must export a React component for it to be valid. Please make sure this file exports a React component:
undefined
not finished createPagesStatefully - 0.057s
Action failed: see logs above for details
```

**Comment by raae** [comment] 2020-06-08 08:54
I upgraded everything today and I am also getting this same error.

**Comment by janosh** [comment] 2020-06-08 13:02
Same error here. I can confirm that `yarn add gatsby@2.22.20` solves the problem.

**Comment by apipkin** [comment] 2020-06-08 14:56
Same error. Gatsby 2.22.20 did *not* work for me. I am building an MDX maintained site. I have modified the error message to give me the file which normally shows up as `undefined`. Site builds properly in `gatsby develop`. 

Not sure if the order of the plugins matter, but posting them here just in case. 

```
module.exports = ({ contentPath = `${__dirname}/src/pages` }) => {
  return {
    plugins: [
      {
        resolve: 'gatsby-source-filesystem',
        options: {
          name: 'content',
          path: contentPath,
        },
      },
      {
        resolve: 'gatsby-plugin-react-helmet', 
        options: {},
      },
      {
        resolve: 'gatsby-remark-static-images', 
        options: {},
      },
      {
        resolve: 'gatsby-plugin-page-creator',
        options: {
          path: contentPath,
        },
      },
      {
        resolve: 'gatsby-plugin-mdx',
        options: {
          defaultLayouts: {
            content: require.resolve('./src/components/ContentLayout.js'),
            default: require.resolve('./src/components/PageLayout.js'),
          },
          gatsbyRemarkPlugins: [
            {
              resolve: 'gatsby-remark-static-images',
              options: {},
            },
          ],
        },
      },
      {
        resolve: 'gatsby-plugin-sass',
        options: {},
      },
      {
        resolve: 'gatsby-plugin-meta-redirect',
        options: {},
      },
    ],
  };
};
```

**Comment by apipkin** [comment] 2020-06-08 15:01
```
Sometimes you don’t want to include the layout in every file, so gatsby-plugin-mdx offers the option to set default layouts in the gatsby-config.js plugin config. Set the key to the name set in the gatsby-source-filesystem config. If no matching default layout is found, the default default layout is used.
```
From https://www.gatsbyjs.org/packages/gatsby-plugin-mdx/#default-layouts states that you may not want to do an `export default` in every file (only way I can currently get a build to move past the file is to add `export default ()=>{}` to the file reported). This feels like maybe a plugin order or something expected to work isn't inside one of the plugins.

**Comment by janosh** [comment] 2020-06-08 15:02
The webpack loader automatically picks up files in `src/pages`. Do you really need `gatsby-source-filesystem` and `gatsby-plugin-page-creator`?

**Comment by apipkin** [comment] 2020-06-08 15:05
@janosh Great question! If I remove the `gatsby-plugin-page-creator`, the error moves to the `[theme]/src/pages/index.mdx` file. But it does skip over all the "content" pages

**Comment by Swizec** [comment] 2020-06-08 17:07
@janosh in my case I believe I need `gatsby-source-filesystem` for the images that come with pages. It's easier to manage files when everything that belongs to a page is in a folder and kept together.

**Comment by mpeyper** [comment] 2020-06-09 01:52
[I think this issue is affecting docz users as well.](https://github.com/doczjs/docz/issues/1520)

**Comment by ascorbic** [comment] 2020-06-09 08:42
Hey. Thanks for the report. This should be fixed in gatsby@2.23.2

**Closed by ascorbic** 2020-06-09 08:42 UTC
Labels: status: inkteam assigned, topic: webpack/babel, type: bug

**Comment by karl-kallavus** [comment] 2020-06-09 09:32
All good with gatsby@2.23.2

```
"dependencies": {
    "@mdx-js/mdx": "1.6.5",
    "@mdx-js/react": "1.6.5",
    "gatsby": "2.23.2",
    "gatsby-cli": "2.12.44",
    "gatsby-image": "2.4.6",
    "gatsby-plugin-manifest": "2.4.10",
    "gatsby-plugin-mdx": "1.2.14",
    "gatsby-plugin-offline": "2.2.10",
    "gatsby-plugin-react-helmet": "3.3.3",
    "gatsby-plugin-sharp": "2.6.10",
    "gatsby-plugin-styled-components": "3.3.3",
    "gatsby-plugin-typescript": "2.4.4",
    "gatsby-remark-autolink-headers": "2.3.4",
    "gatsby-source-filesystem": "2.3.10",
    "gatsby-transformer-json": "2.4.4",
    "gatsby-transformer-sharp": "2.5.4",
    "mdx-utils": "0.2.0",
    "polished": "3.4.1",
    "prism-react-renderer": "1.1.1",
    "react": ">= 16.10.2",
    "react-dom": ">= 16.10.2",
    "react-helmet": "5.2.0",
    "react-live": "2.2.2",
    "styled-components": "4.4.1"
}
```

**Comment by ivoneijr** [comment] 2020-07-11 02:59
One more thing to add

If you are using `typescript` with `gatsby-plugin-page-creator` and `styled-components` is very common create a file named `styles.tsx` , you must be sure you are ignoring this files on `gatsby-plugin-page-creator`  in `gatsby-config.js`

```
{
      resolve: `gatsby-plugin-page-creator`,
      options: {
        path: `${__dirname}\\src\\pages`,
        ignore: [`**/styles.js`, `**/styles.tsx`],
      },
    },
```

**Comment by Dakojr** [comment] 2020-10-13 10:17
I have the same error

**Comment by dspacejs** [comment] 2021-04-09 00:02
@ivoneijr your solution was missing a few things for me:

For starters, I had to run `yarn add gatsby-plugin-page-creator` because it's not included by default.

Secondly, the `path` option you specified was incorrect. It shouldn't be `\\src\\pages`, but `/src/pages`. The latter throws an error:

```js
module.exports = {
  plugins: [
      resolve: "gatsby-plugin-page-creator",
      options: {
        path: `${__dirname}/src/pages`,
        ignore: ["**/styles.ts", "**/styles.tsx"],
      },
    },
};
```
