### ISSUE TITLE
useStaticQuery problem

### ISSUE THREAD

**Issue by dbelovol** [gatsbyjs/gatsby#25987] opened 2020-07-23 21:48 UTC
Got this message
Error: The result of this StaticQuery could not be fetched.

This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues
Software used
Gatsby CLI version: 2.11.0
Gatsby version: 2.19.43

Tried to use gatsby-plugin-material-ui. Cheked out from https://github.com/mui-org/material-ui/tree/master/examples/gatsby
Inserted useStaticQuery in TopLayout.js like so:

export default function TopLayout(props) {

  const data = useStaticQuery(
    graphql \`
      query {
        site {
          siteMetadata {
            title
          }
        }
      }
    `
  )
.....
queried data presented in graphiql

**Comment by DanielRHayes** [comment] 2020-07-24 05:17
Same for me.

```
const { site } = useStaticQuery(
    graphql`
      query {
        site {
          siteMetadata {
            title
            description
            author
          }
        }
      }
    `
  );
``` 

```
WebpackError: The result of this StaticQuery could not be fetched.
```

**Comment by DanielRHayes** [comment] 2020-07-24 05:34
I unpinned all my dependencies and it worked. I probably should have tried adding a comment to the static query first as per https://github.com/gatsbyjs/gatsby/issues/24127#issuecomment-645759545

**Comment by Chanakya888** [comment] 2020-07-24 06:36
Hey I am having the same issue, I tried unpinning, removing and reinstalling, it's still not working, can you please look into it?
[https://github.com/gatsbyjs/gatsby/issues/25985](https://github.com/gatsbyjs/gatsby/issues/25985)

**Comment by dbelovol** [comment] 2020-07-24 12:19
Add comment to Query, reinstall libraries - nothing helps

**Comment by Chanakya888** [comment] 2020-07-24 13:14
Any ideas on how you are going to proceed with it now?

**Comment by dbelovol** [comment] 2020-07-24 13:40
I'm not sure I use it correctly. In fact I inserted query in local plugin. 
I use official integration example of material-ui library for Gatsby. This example includes, among other stuff, local plugin, where they do common things like wrapping in provider, SEO with Helmet and so on. 
I've tried to inject useStaticQuery into this plugin. My aim was query some site metadata for SEO, which was hard coded in above mentioned scenario. 
And it fails. When I use same construction in component - it works as expected. 
I hoped that it would work "out of the box" and I don't need to deep dive into details. 
I googled about possibility of using query inside local plugin, but found nothing. 

So I intend to write wrapper component by myself.

**Comment by dbelovol** [comment] 2020-07-24 13:41
But I still interested - is it possible to query in plugin or not?

**Comment by TylerBarnes** [comment] 2020-07-24 19:14
Closing this issue as a duplicate of https://github.com/gatsbyjs/gatsby/issues/25985, lets follow up on this bug there instead since it was opened first and has a reproduction repo. Thanks everyone!

**Closed by TylerBarnes** 2020-07-24 19:14 UTC
Labels: status: triage needed

**Comment by jonsherrard** [comment] 2021-08-10 12:19
I had a very weird error:

I'd done a find and replace on the `seo` component to make it `Seo` to make a `PascalCase` eslint error go away, and it updated my imports from

`components/seo`

to 

`components/Seo`

Which it turned out... was causing this error. Mental.
