### ISSUE TITLE
Parameter in <Script /> not properly parsed when using off-main-thread

### ISSUE THREAD

**Issue by hammund0** [gatsbyjs/gatsby#36760] opened 2022-10-06 17:45 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [x] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

inside the component - `<Script
    id="ze-snippet"
    src="https://static.zdassets.com/ekr/snippet.js?key={blanked-api-key}"
    strategy='off-main-thread'
/>`

gatsby-config.js -`  partytownProxiedURLs: [
    `https://static.zdassets.com/ekr/snippet.js?key={blanked-api-key}`
  ],`

When using <Script /> the snippet doesn't properly execute because key cannot be parsed. This is the URL that comes back.

`http://localhost:8000/__third-party-proxy?url=https%3A%2F%2Fstatic.zdassets.com%2Fekr%2Fsnippet.js%3Fkey%3D{blanked-api-key}`

I think as key isn't properly a query param, the script cannot read the key. 

I'm sorry I couldn't provide a working link, I assume this issue is relatively easy to understand.

### Reproduction Link

https://github.com/hammund0/gatsby-script-bug

### Steps to Reproduce

inside the component - `<Script
    id="ze-snippet"
    src="https://static.zdassets.com/ekr/snippet.js?key={blanked-api-key}"
    strategy='off-main-thread'
/>`

gatsby-config.js -`  partytownProxiedURLs: [
    `https://static.zdassets.com/ekr/snippet.js?key={blanked-api-key}`
  ],`

When using <Script /> the snippet doesn't properly execute because key cannot be parsed. This is the URL that comes back.

`http://localhost:8000/__third-party-proxy?url=https%3A%2F%2Fstatic.zdassets.com%2Fekr%2Fsnippet.js%3Fkey%3D{blanked-api-key}`

I think as key isn't properly a query param, the script cannot read the key. 

I'm sorry I couldn't provide a working link, I assume this issue is relatively easy to understand.

### Expected Result

key to be a query param

### Actual Result

key is not a query param as the question mark is URL encoded

### Environment

```shell
System:
    OS: macOS 12.5
    CPU: (8) arm64 Apple M1
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.2 - /usr/local/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.1.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 106.0.5249.91
    Firefox: 103.0.1
    Safari: 15.6
  npmPackages:
    gatsby: 4.17.2 => 4.17.2
    gatsby-cli: ^4.19.0 => 4.19.0
    gatsby-plugin-facebook-pixel: ^1.0.8 => 1.0.8
    gatsby-plugin-fontawesome-css: ^1.2.0 => 1.2.0
    gatsby-plugin-gatsby-cloud: ^4.0.0 => 4.17.0
    gatsby-plugin-google-analytics: ^4.16.0 => 4.17.0
    gatsby-plugin-google-gtag: ^4.9.0 => 4.17.0
    gatsby-plugin-google-tagmanager: ^4.12.1 => 4.17.0
    gatsby-plugin-hotjar: ^1.1.1 => 1.1.1
    gatsby-plugin-image: ^2.17.0 => 2.17.0
    gatsby-plugin-manifest: ^4.17.0 => 4.17.0
    gatsby-plugin-netlify: ^5.0.0 => 5.0.0
    gatsby-plugin-offline: ^5.0.0 => 5.17.0
    gatsby-plugin-postcss: ^5.17.0 => 5.17.0
    gatsby-plugin-react-helmet: ^5.0.0 => 5.17.0
    gatsby-plugin-react-redux-persist: ^1.1.0 => 1.1.0
    gatsby-plugin-remove-trailing-slashes: ^4.12.1 => 4.17.0
    gatsby-plugin-robots-txt: ^1.7.1 => 1.7.1
    gatsby-plugin-sass: ^5.16.0 => 5.17.0
    gatsby-plugin-sharp: ^4.17.0 => 4.17.0
    gatsby-plugin-sitemap: ^5.12.1 => 5.17.0
    gatsby-source-filesystem: ^4.17.0 => 4.17.0
    gatsby-transformer-sharp: ^4.17.0 => 4.17.0
  npmGlobalPackages:
    gatsby: 4.5.2
```

### Config Flags

N/A

**Comment by LekoArts** [comment] 2022-10-07 05:54
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by hammund0** [comment] 2022-10-07 13:32
Hi, 

please see the link below for the repo.

https://github.com/hammund0/gatsby-script-bug

You can see in the console that 'Snippet is missing key', as the key param in the proxy URL isn't parsed

**Comment by tyhopp** [comment] 2022-10-11 02:11
Hi @hammund0, can you update your repro to use a minimal script so we can see more clearly what behavior you expect to see? The script you're using now is minified and contains a lot of other logic, so we can't rule out that the issue is with the script itself.

A quick way to do this is to add a script to the `static` directory and point to that.

**Comment by LekoArts** [comment] 2022-10-25 11:02
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2022-10-25 11:02 UTC
Labels: type: bug, status: needs reproduction
