### ISSUE TITLE
How can I control the scroll position of an individual react component with overflow: scroll?

### ISSUE THREAD

**Issue by rchrdnsh** [gatsbyjs/gatsby#14690] opened 2019-06-10 19:54 UTC
Hi Everybody! cc: @DSchau @jlengstorf @KyleAMathews  XD

ok, I think I have nailed down my issue to the following:

I have a particular use case where I have a layout with items that are positioned statically, or fixed, in the layout, but I cannot use any of the CSS position properties like `fixed` or `sticky` to set those custom pieces in place. The reason for this is because of a hack I am using to stop the UI of mobile browsers (Safari and Chrome in particular) from minimizing it's UI upon scroll down, then maximizing it's UI upon scroll up, which I consider to be an anti-pattern that the browser makers seem to disagree with me on. Here is an article explaining the issue in depth:

https://www.eventbrite.com/engineering/mobile-safari-why/

But the TLDR is that when this happens iOS Safari in particular hijacks the tappable area at the bottom of the visual viewport when the Browser UI minimizes, making it impossible to tap on anything in that area of the screen, until the Browser UI has scrolled back into view. This is absolutely maddening for any user, and my team has tested this a bit informally and found it to be the case, at least for what we are trying to build.

So what we do now is use the following hack to stop the Browser UI from minimizing, which allows us to put our navigation on the bottom of the page, where it is most comfortable for the user and their thumbs. We add the following code to the app:

```css
html, body {
  margin: 0;
  padding: 0;
  height: 100%;
  overflow: hidden;
}
```

Which essentially makes the browser think that the window is NOT scrolling ever.

Now, this would make no sense without making another div with scrollable content, which we end up nesting in the layout component, kind of like this:

```css
main {
  width: 100vw;
  height: 100vh;
  overflow-y: scroll;
  -webkit-overflow-scrolling: touch
}
```

Where the `<main>` element contains all content and scrolls just fine and even bounces inertially when the end is reached, just like people would expect, due to that last line of css. But the important part is that the Browser UI does NOT minimize and therefor cannot hijack the bottom portion of the screen where all the navigation lives, which is great!

We do this because we want our navigation to be at the bottom of the screen, rather than at the top of the screen, to make the UX as pleasant as possible. Here is a simple illustration of our concern. The menu button and most of the menu UI should always be in the green zone, and nowhere else:

<img width="640" alt="Phone_Phablet_Average_Thumb_Reach" src="https://user-images.githubusercontent.com/7884263/59220439-d3123400-8b79-11e9-87eb-bc6cad15c0c9.png">

And our hack ends up working great because we stop the browser from breaking the UX with it's own opinion and we have control and agency over the behavior of the UI...here is an animated GIF with the before and after of controlling the bottom navbar with this technique. In our opinion, the right option is preferable, because it doesn't move anywhere. It also stops the browser from hijacking the tappable area at the bottom of the screen, which are all big wins, in our opinion.

![iOS-browser-insanity](https://user-images.githubusercontent.com/7884263/59311636-21e5c980-8c5f-11e9-8d81-3e6c78d2dd8b.gif)

So, this is all well and good, until...

routing in a framework like Gtasby that utilizes window scroll position to reset routes, especially using something like `gatsby-plugin-layout`. For window reset to work properly in this case, we need to be able to update the scroll position of the main content container upon each subseqent route, rather then updating the windows scroll position, which never changes from 0,0 because the window is not actually doing the scrolling, but the views inside the window.

but it turns out that I sort of had this problem before while building a Vue app came up with a bit of a solution, doing the follow in the `main.js` file:

```javascript
methods: {
  mainContentScroll () {
    document.getElementById('main-content').scrollTop = 0
  }
}
```

...which updates the scroll position of only the main content container when the route changes. It was pretty simple to do in a basic vue app and allowed me to use my unique and rather odd css design exactly the way that I wanted to, which was great.

I have now run into this issue again, but this time with Gatsby, and what I want to know is how I can achieve the same thing in Gatsby. I'm not sure where code like this would go and how to go about adding it to the app.

Been trying things like this in the `gatsby-browser.js` file with the `shouldUpdateScroll` hook, but I really don't know what I'm doing. Trying to select an element/component in react seems a bit tough for me. In trying to do this, I'm also converting commonjs to es modules, because I don't know commonjs at all:

```js
import { ReactDOM } from 'react'
import PageWrapper from 'components/PageWrapper'

const shoudUpdateScroll = ({ routerProps: { location }, getSavedScrollPosition}) => {
  const currentPosition = getSavedScrollPosition(location)
  const queriedPosition = getSavedScrollPosition({ pathname: `/` })

  // window.scrollTo(...(currentPosition || [0, 0]))
  // document.querySelector('PageWrapper').scrollTo(...(currentPosition || [0, 0]))
  ReactDOM.findDOMNode(PageWrapper).scrollTo(...(currentPosition || [0, 0]))

  return false

}

export default shoudUpdateScroll
```

I read about findDOMNode somewhere but i have no idea if any of this code is doing anything and i don't really know how to test it either, but in my mind i'm trying to get the PageWrapper element, which is my scroll container, then reset it's scroll position on every route...no idea at all here...also read something about refs, but haven't wrapped my head around them, and also don't know if this would be the best approach...maybe doing something in the component would be better? I just don't know on this one and feel rather lost.

Anyway, thank you in advance for any help that you can give on this matter!

**Comment by rchrdnsh** [comment] 2019-06-11 06:08
Been trying things like this is the `gatsby-browser.js` file with the `shouldUpdateScroll` hook, but I really don't know what I'm doing. Trying to get an element in react seems a bit tough for me.

```js
  // window.scrollTo(...(currentPosition || [0, 0]))
  ReactDOM.findDOMNode(PageWrapper).scrollTo(...(currentPosition || [0, 0]))
  document.querySelector('PageWrapper').scrollTo(...(currentPosition || [0, 0]))
```

read about findDOMNode but it seems i have to import react, then it tells me not to mix es modules and something else, which i forgot what the name was, which i don't understand, but in might have been commonjs or something, so I'm not sure what that means exactly.

**Comment by DSchau** [comment] 2019-06-12 15:36
Hi Richard!

There's a lot to unwind here. In general, I have some high-level advice:

I think you're optimizing for the wrong thing, and in particular, over-optimizing. If you solve one problem and it makes other, more fundamental problems much more challenging I don't think that's a good solution to the initial problem. Remember that you're optimizing for iPhone here and that is making it harder for _every other platform_ to be usable in an intuitive manner.

> We do this because we want our navigation to be at the bottom of the screen, rather than at the top of the screen, to make the UX as pleasant as possible

Couldn't you do this outside of preventing native browser overflows? In particular, iOS exposes some constants. If the issue is button overlapping on iOS (particularly iPhone X) I would propose using CSS constants that iOS exposes, e.g. [this article](https://medium.com/@draganeror/iphone-x-layout-features-with-css-environment-variables-d57423433dec)

Re: gatsby-browser.js, few notes:

1. It's `export const shouldUpdateScroll` (there's a typo in yours, and it's the default export--which won't be parsed)
1. If you are going to use ReactDOM.findDOMNode, make sure to import it from react-dom, not react.
1. Again, I'd urge you to not really use this approach. You're making it harder on yourself.

My thoughts are that you could probably do this in your layout component or in a wrapper component using an approach like the [React docs outline here with getSnapshotBeforeupdate](https://reactjs.org/docs/react-component.html#getsnapshotbeforeupdate). If you go this route, you'll probably just want to disable scroll handling in gatsby-browser.js (which again, I don't think is a great idea!).

Once more for effect, I'd recommend whether the value add here is really being met with the level of additional engineering that needs to be done to get it working. It seems like the easier solution is to just not mess with default browser scroll behavior and "use the platform" so that's what I'd urge you to do here!

I'm going to close this out as answered--thanks for all the work you've done on getting it this far!

**Closed by DSchau** 2019-06-12 15:36 UTC
Labels: type: question or discussion

**Comment by rchrdnsh** [comment] 2019-06-12 17:48
Hi @DSchau 😁,

I hope you are well, and that your recent talk was well received :-)

I also appreciate your comments and concerns regarding thus issue. I must disagree with your conclusion, however, as I ultimately value the user experience far above the developer experience in all cases, and I consider the decisions that some of the browser makers are making in this instance to be extremely user hostile. I do most definitely value the developer experience as well, or I probably wouldn't be using something like Gatsby in the first place, but I must put the user above myself every time and in every way, as this is a core tenant of my development philosophy. 

With that being said, the crux of the issue for me is that I find the choices that mobile browsers are making, and iOS Safari in particular, to be especially troubling and frustrating, as it feels like they think of mobile apps as second, if not third, class citizens of the connected world. The decisions that they are making makes it almost impossible to create an app like experience that can equal or exceed native apps in terms of speed, fluidity, and especially, ergonomics. I'm not one for conspiracy theories in general, but something about apple's approach here feels a little bit off. They tout user experience and ease of use so much, but they don't seem to give web app developers the tools they need to solve some of these basic issues properly, making native apps appear to be the more desirable solution almost every time. And chrome is starting to follow their lead, making it more difficult for us designers and developers to provide a good experience to the user.

In regards to solving the issue, I am totally down for any approach that can do so. If this `env()` thing can work, then I'm all for it. If `getSnapshotBeforeUpdate()` can work, then I'm all for that as well. But it definitely has to be solved for me. If I (we, anybody, and at this point, and I will gladly pay good honest money for a solution...maybe I can make it a contest and pay the winner who can solve it...🤔) can solve this, then I would componentize it or make it a plugin and use it on literally everything I ever make, and would be very grateful that it exists. I still need to solve the 100vh issue as well, but that is a slightly less important concern than this one, which is, in my opinion, a very bad, no good, horrible decision that has been made on the part of Apple. If I can solve this issue in an intelligent and  performant way then it won't negatively impact other form factors and platforms as well, as I can use the same pattern across everything, so long as this issue can be solved.

In the end, I will generally agree with you nine times out of ten that less work is better work, but there are few edge cases that don't qualify, and in my opinion, this is one of them. I am gladly willing to do the work to make this work, but hopefully find the best, most performant and re-usable approach possible. As some may say, I think I am willing to 'die on this hill' to give my users the best user experience that I can. To be honest, I'm considering going back to Vue because of this, and re-building the entire app there, just for this 'one little thing', because it was just so easy to solve with that framework, literally a one line method. Of course I would rather not, as Gatsby does so so many awesome things, but this 'one platform' I'm trying to optimize for is potentially millions of users/customers, and similar things are happening in mobile chrome, which is basically all of the known world, in terms of user base, so I think the effort is more than justified. In fact, depending on the product in question, the audience could be mostly mobile iOS Safari users, so it would be absolutely imperative to optimize for maybe all of the the potential customers of the product.

And on the Addy Osmani / Sebastian Markbåge continuum of user experience, I'm definitely more on the Seb side of things:

Addy.....................................................................................................................................................Seb

|--------------------------------------------------|------------------------😃me!-------------------|

Speed.......................................................................................................................................Experience

...where the fluidity, ease of use, logical layout, and ergonomics of the app outweigh the speed to initial paint and time to interaction. I think speed is super important(another reason to use Gastby, of course! XD), but after the site/app loads, the majority of time spent with the site/app will be interacting with it. So, does every route transition smoothly from one to the next with meaningful animation? Are UI components reloaded that shouldn't be upon a new route, or do UI components persist from one state to the next if they do not change in any way? Is the navigation comfortable, logical and consistent? Does the navigation constantly move up and down because the browser UI likes to dance to 80's new wave and the 80 year old well heeled potential customer of the product or service on display has to play 'whack-a-mole' just to click on a friggin' button, so justifiably gets frustrated, and then leaves the site/app, leaving a potential customer/sale on the table because of a poor user experience?

And I'm all for 'using the platform' right up until the platform isn't right, and I feel incredibly strongly that the platform is most definitely not right in this regard. These issues actually affect gatsbyjs.org as well, as it can be quite frustrating to use the bottom nav on the mobile site, and the 100vh issue in mobile safari actually cuts off half of the bottom navigation in the browser of the native iOS Twitter app, of which there is a long standing, unfixed issue floating around in here that I think I started many moons ago when I was first getting into Gatsby.

So, in conclusion, I'm going to keep trying to find a solution for my issue, and if anybody wants to help, I will gladly accept said help. And I appreciate you taking the time to read through the issue and share your thoughts on the matter. The team behind, and community around, Gatsby is/are fantastic, and I am really appreciative of everything that you and your team have done for me thus far. And I hope I don't come off as mad or ungrateful to anybody at Gatsby, because nothing could be further from the truth, cuz y'all are just great 😆 I'm just really frustrated with browser makers and the decisions that they are making around user experience and the effect that these decisions are having on my ability to create a great, app-like experience on the open web.

Cheers,

Richard

P.S. - Apple could fix these issues with some way for web developers to declare browser UI behavior. Something along the lines of:

```YAML
Browser UI:
  Top Tool Bar: fixed, or fluid
  Bottom Tool Bar: fixed or fluid
  100vh = Visual viewport  or  Visual Viewport + Bottom Toolbar
```

...and all my concerns go away. But alas, this does not appear to be the case, and I don't think any solutions like these will be coming along in the near future, unfortunately 😔

**Comment by rchrdnsh** [comment] 2019-06-13 17:10
So I found a pen from a few years back where I was playing around with this general pattern for building a more complex UI for an App, and it seems to work really really really really well...

https://codepen.io/rchrdnsh/pen/LWWwBw

Trying to do a layout like this would be really challenging, if not impossible, without using CSS Grid and overflow:scroll on all of the content containers. Using something like `position: fixed` or `position: sticky` would not really allow me to make the design smoothly responsive like it is. And using those antiquated layout techniques when something so much more suited to the task exists would also be folly, in my opinion.
