### ISSUE TITLE
found broken page https://www.gatsbyjs.com/features/jamstack/gatsby-vs-nextjs-vs-jekyll-vs-hugo-vs-nuxtjs

### ISSUE THREAD

**Issue by babono** [gatsbyjs/gatsby#26606] opened 2020-08-23 17:03 UTC
hi i think i found a broken page on your documentation website please check this out

https://www.gatsbyjs.com/features/jamstack/gatsby-vs-nextjs-vs-jekyll-vs-hugo-vs-nuxtjs

![Screen Shot 2020-08-24 at 00 02 13](https://user-images.githubusercontent.com/8475841/90984081-126d4a80-e59d-11ea-8740-06e2b106d4cc.png)

cheers

**Comment by capndave** [comment] 2020-08-23 17:46
@babono - Which browser are you using? Looks good for me on Chrome using Linux Mint.

**Comment by kamal250** [comment] 2020-08-24 16:19
@capndave, I hope this [video](http://srecorder.com/s/9utt) will be helpful to you. It is appearing on loading when accessing page for the first time.

**Comment by LekoArts** [comment] 2020-08-25 10:14
Thanks for the issue. This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/26475

**Closed by LekoArts** 2020-08-25 10:14 UTC
Labels: topic: website
