### ISSUE TITLE
Issue with downloadImages: true

### ISSUE THREAD

**Issue by tom-attachdigital** [gatsbyjs/gatsby#32068] opened 2021-05-14 13:24 UTC
When I try adding 'downloadImages: true' into the config I get the below error;

```
Polling bulk operation: gid://shopify/BulkOperation/364790513857
Status: COMPLETED
Object count: 1841

info Completed bulk operation PRODUCTS: gid://shopify/BulkOperation/364790513857
info Creating nodes from bulk operation PRODUCTS
Failed to validate error [Error [ValidationError]: "error" must be of type object] {
  _original: {
    context: { sourceMessage: 'Could not source from bulk operation' },
    error: 'failed to process https://cdn.shopify.com/s/files/1/0538/7583/5073/products/3bf041_66af7a562fd24893b980613b648b711d_mv2.jpg?v=1614509291\n' +
      'RequestError: socket hang up',
    pluginName: 'gatsby-source-shopify',
    text: 'Could not source from bulk operation',
    level: 'ERROR',
    category: 'THIRD_PARTY',
    stack: [],
    docsUrl: 'https://gatsby.dev/issue-how-to',
    code: 'gatsby-source-shopify_111001'
  },
  details: [
    {
      message: '"error" must be of type object',
      path: [Array],
      type: 'object.base',
      context: [Object]
    }
  ]
}
not finished source and transform nodes - 52.796s
not finished Source from bulk operation PRODUCTS - 51.074s - Processing 1841 results for PRODUCTS: gid://shopify/BulkOperation/364790513857
```

I'm on the latest versions of Gatsby and this plugin, but I've had this issue for a while and have never been able to use the  download images option.

**Comment by LekoArts** [comment] 2021-06-24 05:06
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-07-06 09:54
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-07-06 09:54 UTC
Labels: status: needs reproduction, topic: source-shopify, type: bug
