### ISSUE TITLE
gatsby-plugin-sass README not showing on GatsbyJS plugin page

### ISSUE THREAD

**Issue by RilDev** [gatsbyjs/gatsby#26643] opened 2020-08-26 08:09 UTC
The documentation for the `gatsby-plugin-sass` is not displayed on [https://www.gatsbyjs.com/plugins/gatsby-plugin-sass/?=sass](https://www.gatsbyjs.com/plugins/gatsby-plugin-sass/?=sass)

![gatsby-sass-not-showing-on-plugin-page](https://user-images.githubusercontent.com/13135150/91278063-0099cc00-e784-11ea-8262-832f7af5bd7e.png)

**Comment by LekoArts** [comment] 2020-08-26 08:39
Hi, thanks for the issue. This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/24137

**Closed by LekoArts** 2020-08-26 08:39 UTC
Labels: type: documentation

**Comment by RilDev** [comment] 2020-08-26 09:41
Thanks for the quick reply!
