### ISSUE TITLE
`unknown tag` error from gatsby-transformer-remark

### ISSUE THREAD

**Issue by hirenoble** [gatsbyjs/gatsby#19247] opened 2019-11-04 07:39 UTC
## Description

gatsby-transformer-remark throwing 'unknown tag' error.

### Steps to reproduce

create a markdown file with  ` !<!DNL> ` tag.

### Expected result

Ignore if there are unknown tags instead of failing the build.

### Actual result
Build fails with error ` unknown tag !<!DNL> at line 2, column 20:`

### Environment
production

**Comment by LekoArts** [comment] 2019-11-05 10:24
Thank you for opening this!

I couldn't find anything about a "DNL" tag on the internet or repositories so doesn't seem to be valid. Hence I think it's working as intended that the underlying package (remark) is failing. Users should be notified about invalid tags and we shouldn't just ignore such things. Otherwise people will be surprised why it silently fails.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2019-11-05 10:24 UTC
