### ISSUE TITLE
print warning when resolvers take too long

### ISSUE THREAD

**Issue by KyleAMathews** [gatsbyjs/gatsby#23098] opened 2020-04-14 13:31 UTC
Custom graphql resolvers can hang indefinitely.

This is hard to discover and debug. We should print a warning when resolvers take too long to return. We tried setting a maxTimeout in https://github.com/gatsbyjs/gatsby/pull/23095 but this broke some sites as @pvdz said:

>for reference; this will block builds because the time isn't properly measured so if the first query gets delayed by another blocking process (webpack?) it'll measure a timeout for the first query and then abort the build

**Comment by vladar** [comment] 2020-04-14 14:03
Related: #21825

**Comment by freiksenet** [comment] 2020-04-16 11:30
Closing as duplicate of #21825.

**Closed by freiksenet** 2020-04-16 11:30 UTC
Labels: help wanted, topic: GraphQL
