### ISSUE TITLE
[gatsby-source-filesystem] File content missing during build 

### ISSUE THREAD

**Issue by jdahdah** [gatsbyjs/gatsby#34605] opened 2022-01-27 09:03 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I am upgrading from Gatsby 2 to Gatsby 4 and have run into an issue that is not present in v2. File content from `gatsby-source-filesystem` that is available during `gatsby develop` is not available during `gatsby build`. When I read the content of a file that needs to be embedded into a page (via a pageQuery, but `useStaticQuery` behaves identically), it works fine in `develop`.

**pages/index.js:**

```
export const pageQuery = graphql`
  query {
    example: file(name: { eq: "example" }) {
      id
      lastUpdated: modifiedTime
      name
      ext
      internal {
        content
      }
    }
  }
`;
```

**files/example.html:**
```
<p>success</p>
```

**gatsby-config:**
```
  plugins: [
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `html`,
        path: `${__dirname}/src/files`,
      },
    },
  ],
```

**gatsby-node.js** (as adapted from [this comment](https://github.com/gatsbyjs/gatsby/issues/21396#issuecomment-585377703)):

```
exports.onCreateNode = async ({ node, loadNodeContent }) => {
  if (node.name !== "example") return;

  // Ensure Gatsby loads the item into memory so that its
  // content becomes available in the GraphQL File node
  try {
    const nodeContent = await loadNodeContent(node);
    console.log(node);
  } catch (error) {
    console.error(error);
  }
};

```

Result in `develop`:

```
{
    "example": {
        "id": "6fec6f1f-32b7-5da1-b235-0563112c93bc",
        "lastUpdated": "2022-01-26T14:54:38.306Z",
        "name": "example",
        "ext": ".html",
        "internal": {
            "content": "<p>success</p>\n"
        }
    }
}
```

Result in `build`:

```
{
    "example": {
        "id": "6fec6f1f-32b7-5da1-b235-0563112c93bc",
        "lastUpdated": "2022-01-26T14:54:38.306Z",
        "name": "example",
        "ext": ".html",
        "internal": {
            "content": null
        }
    }
}
```

This was working fine in v2. We need this to work because we are pulling remote html during build time that is embedded into the static html via `dangerouslySetInnerHTML`.

### Reproduction Link

CodeSandbox: https://codesandbox.io/s/elastic-mccarthy-m6qgy
Repo: https://github.com/jdahdah/gatsby-transform

### Steps to Reproduce

1. If you check out the repo locally, run `yarn install && gatsby develop`. If you use the CodeSandbox example instead, it does this step for you.
2. You will see that the box is filled with the word "success".
3. Run `gatsby clean && gatsby build && gatsby serve` (or if you're on CodeSandbox: `yarn run gatsby clean && yarn run gatsby build && yarn run gatsby serve`).
4. You will see that the box is empty.

Note that the `console.log(node)` that is written by `gatsby-node.js` during the build *does* contain the correct data. The `console.log(data)` from `pages/index.js` does not. So the data is available during `onCreateNode`, it's just not reaching the page query for some reason. See also the follow-up https://github.com/gatsbyjs/gatsby/issues/34605#issuecomment-1026668361.

### Expected Result

I expected the build to include the file contents just like it does during the build. `internal.content` should result in `"<p>success</p>\n"`.

### Actual Result

`internal.content` is `null`.

### Environment

```shell

  System:
    OS: macOS 12.1
    CPU: (10) arm64 Apple M1 Max
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.2/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Firefox: 95.0
    Safari: 15.2
  npmPackages:
    gatsby: ^4.7.0-next.0 => 4.7.0-next.0 
    gatsby-source-filesystem: ^4.6.0 => 4.6.0 
  npmGlobalPackages:
    gatsby-cli: 4.6.0
```

**Comment by denisgoryaynov** [comment] 2022-01-27 11:37
I have the same issue, specifically it happens with images using gatsby-transformer-remark. All images are loaded correctly in development, but the production build crashes while compiling with `Cannot read properties of null (reading 'dir')`.
I have an 8 core Apple M1, I updated to macOS 12.2 overnight and the issue still happens

**Comment by MiKatre** [comment] 2022-01-27 16:13
Same here. I get the message `Cannot read property 'dir' of null` On builds since updating to Gatsby 4 and Gatsby-plugin-image 2.6 yesterday.

**Comment by timurrustamov** [comment] 2022-01-28 13:13
Same here ! Encountered the issue with gatsby@^4.6.0, but when downgrading to gatsby@4.5.4 everything is working as expected.

**Comment by rmiller61** [comment] 2022-01-28 14:36
@timurrustamov thank you so much. Was tearing my hair out trying to figure this out but downgrading to 4.5.4 worked.

**Comment by rajanmagar** [comment] 2022-01-30 12:17
@timurrustamov Is there something wrong with gatsby@^4.6.0?

**Comment by LekoArts** [comment] 2022-01-31 09:51
Hi!

For the issue with `gatsby-plugin-image`, can you please also provide a [minimal reproduction][reproduction]? It might not be directly related to this issue as the author doesn't mention the error message at all.

[reproduction]: https://gatsby.dev/reproduction

**Comment by jdahdah** [comment] 2022-02-01 10:05
> Same here ! Encountered the issue with gatsby@^4.6.0, but when downgrading to gatsby@4.5.4 everything is working as expected.

Hmm, I'm not getting consistent results here. If I do a `gatsby develop` followed by a `gatsby build` with `gatsby@4.5.4`, it works. If I do a `gatsby clean && gatsby build` (which is closer to a CI environment) it still breaks as described above.

**Comment by vannyle** [comment] 2022-02-02 12:21
I have the same issue after upgrading `gatsby@3.12.0` to version `gatsby@4.5.4`.

**Comment by rajan-magar** [comment] 2022-02-02 12:49
> 
@jdahdah 
For me, this issue after gatsby develop for gatsby build
`internal-data-bridge" threw an error while running the sourceNodes lifecycle`

**Comment by LekoArts** [comment] 2022-02-03 09:28
For the image issue, please go to https://github.com/gatsbyjs/gatsby/issues/34693 and post your reproduction there. The image issue seems completely separate from the author's issue. For that we'll still need a reliable minimal reproduction + steps.

My guess is that it's not different between 4.5.4 and 4.6 because it's due to the introduction of LMDB in v4 in general which in some cases breaks `loadNodeContent` as the way we're handling data now is completely different.

**Comment by rajan-magar** [comment] 2022-02-03 11:59
@LekoArts I am not using LMDB even then it's getting failed. Can we have any solution?

**Comment by LekoArts** [comment] 2022-02-03 12:01
@rajan-magar Your issue is also separate from the two. Delete your lock file and `node_modules` and re-install. This was a bug in `msgpackr` 1.5.3

**Comment by rajan-magar** [comment] 2022-02-03 12:05
@LekoArts I tried deleting both `node_modules` as well as `package-lock.json` still not working with `gatsby build` but working `gatsby develop`.
node v16.13.1
npm v8.1.2
gatsby-cli 4.6.0

**Comment by LekoArts** [comment] 2022-02-03 12:07
Then please go to https://github.com/gatsbyjs/gatsby/issues/34693 as post your [minimal reproduction][reproduction] there.

[reproduction]: https://gatsby.dev/reproduction

**Comment by jdahdah** [comment] 2022-02-03 12:09
@LekoArts Thanks for that hint. Is there any way to work around this issue at the moment? If I set `LMDB_STORE = false` I get the following message:

> Those flags no longer have any effect and you can remove them from config:
> - LMDB_STORE · EXPERIMENTAL · (Umbrella Issue (https://gatsby.dev/lmdb-feedback)) · Store nodes in a persistent embedded
> database (vs in-memory). Lowers peak memory usage. Requires Node v14.10 or above.

Right now our hands are pretty tied and it looks like we'll have to hold off on the upgrade until this is resolved?

**Comment by LekoArts** [comment] 2022-02-03 12:28
We'll look at it and fix it/provide a solution how you now should do it :) So is the repository you showed in the first post reliably showing it?

**Comment by jdahdah** [comment] 2022-02-03 12:35
@LekoArts Thank you! As far as I can tell, yes, the example is reliably showing it. I've added the direct link for the [GitHub repo](https://github.com/jdahdah/gatsby-transform) to the post as well (aside from the CodeSandbox).

**Comment by natapg** [comment] 2022-02-03 16:48
same issue here, after updating from gatsby 4.5.3 to 4.6.1 I get the message `Cannot read properties of null (reading 'dir')`

**Comment by joelwmale** [comment] 2022-02-03 23:43
Following for updates here. Getting the exact same error:

```
Cannot read property 'dir' of null
```

When trying to add a featured og image for my blog posts.

**Comment by pieh** [comment] 2022-02-07 13:18
Hey @jdahdah - workaround for this can be done via:

```diff
exports.onCreateNode = async ({ node, loadNodeContent }) => {
  if (node.name !== "example") return;

  // Ensure Gatsby loads the item into memory so that its
  // content becomes available in the GraphQL File node
  try {
    const nodeContent = await loadNodeContent(node);
+   // to ensure we update a node in LMDB we create dummy child node,
+   // and use `createNodeField` to ensure LMDB is updated
+   actions.createNodeField({ node, name: `contentLoaded`, value: true });
    console.log(node);
  } catch (error) {
    console.error(error);
  }
};
```

`loadNodeContent` currently doesn't update LMDB (it only mutates node in memory). We can to update node in lmdb by using `createNodeField` action which should ensure content is stored in lmdb

**Comment by pieh** [comment] 2022-02-07 14:01
The other issue is trying to use `internal.content` - this is really meant as "memoization" and not something you should reach directly - if you want actual content, you should probably use `createNodeField` with `value` being set to `await loadNodeContent(node)` and whatever field name you'd like to use (it will be later available as `node.fields.<yourFieldName>`

**Comment by jdahdah** [comment] 2022-02-08 08:47
@pieh Thank you so much! 🙏 This workaround fixes the issue for us.

For anyone else running into this, here's the full solution:

```
exports.onCreateNode = async ({
  node,
  loadNodeContent,
  actions: { createNodeField },
}) => {
  if (node.parent !== "priceTickers") return

  try {
    // Ensure Gatsby loads the item into memory so that its content becomes
    // available in the GraphQL File node. We create a child node with the file
    // content and use `createNodeField` to ensure LMDB is updated. Note that
    // `internal.content` is for memoization and should not be used directly.
    const nodeContent = await loadNodeContent(node)
    createNodeField({ node, name: `content`, value: nodeContent })
  } catch (error) {
    console.error(error)
  }
}
```

The file content can then be queried via `fields.content` (instead of `internal.content`) like so:

```
export const pageQuery = graphql`
  query {
    example: file(name: { eq: "example" }) {
      id
      lastUpdated: modifiedTime
      name
      ext
      fields {
        content
      }
    }
  }
`;
```

**Comment by LekoArts** [comment] 2022-02-08 11:34
Great, thanks for your code snippet (future Google users will thank you). I'll mark this issue as closed as the issue you're seeing is fixed by using the proper API (`createNodeField`) 👍

**Closed by LekoArts** 2022-02-08 11:34 UTC
Labels: type: bug, topic: GraphQL
