### ISSUE TITLE
Importing SystemJS in gatsby-node causes the build to fail

### ISSUE THREAD

**Issue by moigonzalez** [gatsbyjs/gatsby#29987] opened 2021-03-04 11:47 UTC
## Description

Simply including SystemJS exports on top of the gastby-node file causes the build to fail with the following log:

```
...
success run page queries - 0.036s - 2/2 56.19/s

 ERROR 

Cannot read property 'default' of undefined



  TypeError: Cannot read property 'default' of undefined
  
  - loadLoader.js:6 
    [bug-repro]/[loader-runner]/lib/loadLoader.js:6:67
  

not finished Building development bundle - 0.220s
```

### Steps to reproduce

1. Install SystemJS
2. Add { System, applyImportMap } = require('systemjs'); in gatsby-node.js
3. run gastby develop or gatsby build

Reproduction [repo](https://github.com/moigonzalez/bug-repro)

### Environment

  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.12.0 - ~/.nvm/versions/node/v13.12.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v13.12.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 88.0.4324.192
    Firefox: 84.0.2
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.32.9 => 2.32.9
  npmGlobalPackages:
    gatsby-cli: 2.12.60

**Comment by LekoArts** [comment] 2021-03-04 13:04
Hi, thanks for the issue!

Can you please elaborate on why you need to use `systemjs` in `gatsby-node.js`?

**Comment by LekoArts** [comment] 2021-03-15 08:39
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction/more information I'm going to close this now, as we can't do much to help without that. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-03-15 08:39 UTC
Labels: status: needs more info, type: bug
