### ISSUE TITLE
Add way to dynamically trigger load gatsby-image

### ISSUE THREAD

**Issue by theskillwithin** [gatsbyjs/gatsby#24396] opened 2020-05-23 23:58 UTC
Add way to dynamically trigger load gatsby-image

# problem
using a 3rd party slider library in loop mode can sometimes cause the image to not load again after looping all the way through and then seeing the same image but now its just the images skeleton.  maybe related to its intersection observer not detecting its viewable on the screen.
issue pointed out here https://github.com/kidjp85/react-id-swiper/issues/394

# possible solution
create a way to dynamically trigger image load so can manually tell the image to load again

**Comment by LekoArts** [comment] 2020-05-25 09:30
Hi, thanks for the issue! I think this is a duplicate of https://github.com/gatsbyjs/gatsby/issues/16678

**Closed by LekoArts** 2020-05-25 09:30 UTC
Labels: type: feature or enhancement
