### ISSUE TITLE
Gatsby-plugin-Preact failing during build on Gatsby 4.2/4.3 

### ISSUE THREAD

**Issue by LarsEjaas** [gatsbyjs/gatsby#34177] opened 2021-12-02 22:26 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I have just migrated my project from Gatsby v3 to Gatsby v4. My build is failing when building locally/on Netlify but is running fine in development. 
I have narrowed the issue down to `gatsby-plugin-preact` as uncommenting/disabling the plugin will cause the build to complete.

The error-message is a bit unclear to me, and I am unsure what I really need to include in a minimal reproduction.

I get the following error when the build fails:

```
error Page data from page-data.json for the failed page "/en/offline-plugin-app-shell-fallback/": {
10:48:56 PM:   "componentChunkName": "component---cache-caches-gatsby-plugin-offline-app-shell-js",
10:48:56 PM:   "path": "/en/offline-plugin-app-shell-fallback/",
10:48:56 PM:   "result": {
10:48:56 PM:     "pageContext": {
10:48:56 PM:       "language": "en",
10:48:56 PM:       "i18n": {
10:48:56 PM:         "language": "en",
10:48:56 PM:         "languages": [
10:48:56 PM:           "en",
10:48:56 PM:           "da"
10:48:56 PM:         ],
10:48:56 PM:         "defaultLanguage": "da",
10:48:56 PM:         "generateDefaultLanguagePage": false,
10:48:56 PM:         "routed": true,
10:48:56 PM:         "originalPath": "/offline-plugin-app-shell-fallback/",
10:48:56 PM:         "path": "en/offline-plugin-app-shell-fallback/"
10:48:56 PM:       }
10:48:56 PM:     }
10:48:56 PM:   },
10:48:56 PM:   "staticQueryHashes": [
10:48:56 PM:     "1672338075",
10:48:56 PM:     "2249152690"
10:48:56 PM:   ]
10:48:56 PM: }
10:48:56 PM: failed Building static HTML for pages - 5.222s
10:48:56 PM: error Building static HTML failed for path "/en/offline-plugin-app-shell-fallback/"
10:48:56 PM: 
10:48:56 PM:   684 | // Junk
10:48:56 PM:   685 | var stripSlashes = function stripSlashes(str) {
10:48:56 PM: > 686 |   return str.replace(/(^\/+|\/+$)/g, "");
10:48:56 PM:       | ^
10:48:56 PM:   687 | };
10:48:56 PM:   688 |
10:48:56 PM:   689 | var createRoute = function createRoute(basepath) {
10:48:56 PM: 
10:48:56 PM:   WebpackError: TypeError: Cannot read properties of undefined (reading 'replace  ')
10:48:56 PM:   
10:48:56 PM:   - index.js:686 
10:48:56 PM:     [lars_ejaas_portfolio]/[@gatsbyjs]/reach-router/es/index.js:686:1
10:48:56 PM:   
10:48:56 PM:   - index.js:710 
10:48:56 PM:     [lars_ejaas_portfolio]/[@gatsbyjs]/reach-router/es/index.js:710:1
10:48:56 PM:   
10:48:56 PM:   - index.js:223 
10:48:56 PM:     [lars_ejaas_portfolio]/[@gatsbyjs]/reach-router/es/index.js:223:1
10:48:56 PM:   
10:48:56 PM:   - index.js:222 
10:48:56 PM:     [lars_ejaas_portfolio]/[@gatsbyjs]/reach-router/es/index.js:222:40
10:48:56 PM:   
10:48:56 PM:   - commonjs.js:1 
10:48:56 PM:     [lars_ejaas_portfolio]/[preact-render-to-string]/dist/commonjs.js:1:2266
10:48:56 PM:   
10:48:56 PM:   - commonjs.js:1 
10:48:56 PM:     [lars_ejaas_portfolio]/[preact-render-to-string]/dist/commonjs.js:1:2603
10:48:56 PM:   
10:48:56 PM:   - commonjs.js:1 
10:48:56 PM:     [lars_ejaas_portfolio]/[preact-render-to-string]/dist/commonjs.js:1:2603
10:48:56 PM:   
10:48:56 PM:   - commonjs.js:1 
10:48:56 PM:     [lars_ejaas_portfolio]/[preact-render-to-string]/dist/commonjs.js:1:2603
10:48:56 PM:   
10:48:56 PM:   - commonjs.js:1 
10:48:56 PM:     [lars_ejaas_portfolio]/[preact-render-to-string]/dist/commonjs.js:1:2603
10:48:56 PM:   
10:48:56 PM:   - commonjs.js:1 
10:48:56 PM:     [lars_ejaas_portfolio]/[preact-render-to-string]/dist/commonjs.js:1:1551
10:48:56 PM:   
10:48:56 PM:   - commonjs.js:1 
10:48:56 PM:     [lars_ejaas_portfolio]/[preact-render-to-string]/dist/commonjs.js:1:2603
10:48:56 PM:   
10:48:56 PM:   - commonjs.js:1 
10:48:56 PM:     [lars_ejaas_portfolio]/[preact-render-to-string]/dist/commonjs.js:1:2603
10:48:56 PM:   
10:48:56 PM:   - commonjs.js:1 
10:48:56 PM:     [lars_ejaas_portfolio]/[preact-render-to-string]/dist/commonjs.js:1:2603
10:48:56 PM:   
10:48:56 PM:   - commonjs.js:1 
10:48:56 PM:     [lars_ejaas_portfolio]/[preact-render-to-string]/dist/commonjs.js:1:2603
10:48:56 PM:   
10:48:56 PM:   - commonjs.js:1 
10:48:56 PM:     [lars_ejaas_portfolio]/[preact-render-to-string]/dist/commonjs.js:1:2603
```

### Reproduction Link

https://

### Steps to Reproduce

1. Build the project with Gatsby Build. All dependencies/plugins are updated to latest version.
...

### Expected Result

Expected the build to complete with gatsby-plugin-preact activated.

### Actual Result

The following error occured during HTML-render fase of the build:

```
error Page data from page-data.json for the failed page "/en/offline-plugin-app-shell-fallback/": {
10:48:56 PM:   "componentChunkName": "component---cache-caches-gatsby-plugin-offline-app-shell-js",
10:48:56 PM:   "path": "/en/offline-plugin-app-shell-fallback/",
10:48:56 PM:   "result": {
10:48:56 PM:     "pageContext": {
10:48:56 PM:       "language": "en",
10:48:56 PM:       "i18n": {
10:48:56 PM:         "language": "en",
10:48:56 PM:         "languages": [
10:48:56 PM:           "en",
10:48:56 PM:           "da"
10:48:56 PM:         ],
10:48:56 PM:         "defaultLanguage": "da",
10:48:56 PM:         "generateDefaultLanguagePage": false,
10:48:56 PM:         "routed": true,
10:48:56 PM:         "originalPath": "/offline-plugin-app-shell-fallback/",
10:48:56 PM:         "path": "en/offline-plugin-app-shell-fallback/"
10:48:56 PM:       }
10:48:56 PM:     }
10:48:56 PM:   },
10:48:56 PM:   "staticQueryHashes": [
10:48:56 PM:     "1672338075",
10:48:56 PM:     "2249152690"
10:48:56 PM:   ]
10:48:56 PM: }
10:48:56 PM: failed Building static HTML for pages - 5.222s
10:48:56 PM: error Building static HTML failed for path "/en/offline-plugin-app-shell-fallback/"
10:48:56 PM: 
10:48:56 PM:   684 | // Junk
10:48:56 PM:   685 | var stripSlashes = function stripSlashes(str) {
10:48:56 PM: > 686 |   return str.replace(/(^\/+|\/+$)/g, "");
10:48:56 PM:       | ^
10:48:56 PM:   687 | };
10:48:56 PM:   688 |
10:48:56 PM:   689 | var createRoute = function createRoute(basepath) {
10:48:56 PM: 
10:48:56 PM:   WebpackError: TypeError: Cannot read properties of undefined (reading 'replace  ')
10:48:56 PM:   
10:48:56 PM:   - index.js:686 
10:48:56 PM:     [lars_ejaas_portfolio]/[@gatsbyjs]/reach-router/es/index.js:686:1
10:48:56 PM:   
10:48:56 PM:   - index.js:710 
10:48:56 PM:     [lars_ejaas_portfolio]/[@gatsbyjs]/reach-router/es/index.js:710:1
10:48:56 PM:   
10:48:56 PM:   - index.js:223 
10:48:56 PM:     [lars_ejaas_portfolio]/[@gatsbyjs]/reach-router/es/index.js:223:1
10:48:56 PM:   
10:48:56 PM:   - index.js:222 
10:48:56 PM:     [lars_ejaas_portfolio]/[@gatsbyjs]/reach-router/es/index.js:222:40
10:48:56 PM:   
10:48:56 PM:   - commonjs.js:1 
10:48:56 PM:     [lars_ejaas_portfolio]/[preact-render-to-string]/dist/commonjs.js:1:2266
10:48:56 PM:   
10:48:56 PM:   - commonjs.js:1 
10:48:56 PM:     [lars_ejaas_portfolio]/[preact-render-to-string]/dist/commonjs.js:1:2603
10:48:56 PM:   
10:48:56 PM:   - commonjs.js:1 
10:48:56 PM:     [lars_ejaas_portfolio]/[preact-render-to-string]/dist/commonjs.js:1:2603
10:48:56 PM:   
10:48:56 PM:   - commonjs.js:1 
10:48:56 PM:     [lars_ejaas_portfolio]/[preact-render-to-string]/dist/commonjs.js:1:2603
10:48:56 PM:   
10:48:56 PM:   - commonjs.js:1 
10:48:56 PM:     [lars_ejaas_portfolio]/[preact-render-to-string]/dist/commonjs.js:1:2603
10:48:56 PM:   
10:48:56 PM:   - commonjs.js:1 
10:48:56 PM:     [lars_ejaas_portfolio]/[preact-render-to-string]/dist/commonjs.js:1:1551
10:48:56 PM:   
10:48:56 PM:   - commonjs.js:1 
10:48:56 PM:     [lars_ejaas_portfolio]/[preact-render-to-string]/dist/commonjs.js:1:2603
10:48:56 PM:   
10:48:56 PM:   - commonjs.js:1 
10:48:56 PM:     [lars_ejaas_portfolio]/[preact-render-to-string]/dist/commonjs.js:1:2603
10:48:56 PM:   
10:48:56 PM:   - commonjs.js:1 
10:48:56 PM:     [lars_ejaas_portfolio]/[preact-render-to-string]/dist/commonjs.js:1:2603
10:48:56 PM:   
10:48:56 PM:   - commonjs.js:1 
10:48:56 PM:     [lars_ejaas_portfolio]/[preact-render-to-string]/dist/commonjs.js:1:2603
10:48:56 PM:   
10:48:56 PM:   - commonjs.js:1 
10:48:56 PM:     [lars_ejaas_portfolio]/[preact-render-to-string]/dist/commonjs.js:1:2603
``` 

### Environment

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
  Binaries:
    Node: 16.10.0 - C:\Program Files\nodejs\node.EXE
    npm: 7.14.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.0 - /c/Python39/python
  Browsers:
    Chrome: 96.0.4664.45
    Edge: Spartan (44.22000.120.0), Chromium (96.0.1054.41)
  npmPackages:
    gatsby: ^4.2.0 => 4.3.0 
    gatsby-cli: ^4.2.0 => 4.3.0 
    gatsby-image: ^3.2.0 => 3.11.0 
    gatsby-plugin-brotli: ^2.1.0 => 2.1.0 
    gatsby-plugin-exclude: ^1.0.2 => 1.0.2 
    gatsby-plugin-force-trailing-slashes: ^1.0.5 => 1.0.5 
    gatsby-plugin-image: ^2.2.0 => 2.3.0 
    gatsby-plugin-manifest: ^4.2.0 => 4.3.0 
    gatsby-plugin-offline: ^5.2.0 => 5.3.0 
    gatsby-plugin-postcss: ^5.2.0 => 5.3.0 
    gatsby-plugin-preact: ^6.2.0 => 6.3.0 
    gatsby-plugin-react-helmet: ^5.2.0 => 5.3.0 
    gatsby-plugin-react-i18next: ^1.2.2 => 1.2.2 
    gatsby-plugin-react-svg: ^3.1.0 => 3.1.0 
    gatsby-plugin-robots-txt: ^1.6.14 => 1.6.14 
    gatsby-plugin-sharp: ^4.2.0 => 4.3.0 
    gatsby-plugin-sitemap: ^5.2.0 => 5.3.0 
    gatsby-plugin-transition-link: ^1.20.5 => 1.20.5 
    gatsby-remark-external-links: ^0.0.4 => 0.0.4 
    gatsby-remark-footnotes: ^0.0.8 => 0.0.8 
    gatsby-remark-images: ^6.2.0 => 6.3.0 
    gatsby-remark-prismjs: ^6.2.0 => 6.3.0 
    gatsby-remark-reading-time: ^1.1.0 => 1.1.0 
    gatsby-source-filesystem: ^4.2.0 => 4.3.0 
    gatsby-transformer-remark: ^5.2.0 => 5.3.0 
    gatsby-transformer-sharp: ^4.2.0 => 4.3.0
```

### Config Flags

No flags activated

**Comment by saby22** [comment] 2021-12-06 13:33
Facing the same issue

**Comment by LekoArts** [comment] 2021-12-06 14:58
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

This also might be related to https://github.com/gatsbyjs/gatsby/issues/34172 -- please check if we could close this here as a duplicate, too.

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-12-16 07:58
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-12-16 07:58 UTC
Labels: type: bug, status: needs reproduction
