### ISSUE TITLE
ERROR gatsby-source-wordpress_112004  PLUGIN

### ISSUE THREAD

**Issue by aliaksandr-bandziuk** [gatsbyjs/gatsby#37940] opened 2023-04-13 15:40 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I'm using gatsby-source-wordpress plugin with Local WP. When I build the project I receive this bug.

ERROR #gatsby-source-wordpress_112004  PLUGIN

The remote WPGraphQL schema hasn't changed but local       
generated type definitions have. This is a bug, please open an issue on Github and   
include the following text

Changed type defs:

Typename WpAcfOptionsMainMenu diff:
{
  kind: "OBJECT"
  config: {
    name: "WpAcfOptionsMainMenu"
    fields: {
      mainMenu: {
        type: "WpAcfOptionsMainMenu_Mainmenu"
        description: "Added to the GraphQL Schema because the ACF Field Group       
&quot;Menu&quot; was set to Show in GraphQL."
      }
      pageSlug: {
        type: "String"
        description: ""
      }
      pageTitle: {
        type: "String"
        description: ""
      }
    }
    description: "Main menu options."
    extensions: {
      infer: false
    }
    interfaces: [
    ]
  }
}

Typename WpAcfOptionsMainMenu_Mainmenu diff:
{
  kind: "OBJECT"
  config: {
    name: "WpAcfOptionsMainMenu_Mainmenu"
    fields: {
      callToAction: {
        type: "WpAcfOptionsMainMenu_Mainmenu_CallToAction"
        description: ""
      }
      fieldGroupName: {
        type: "String"
        description: "The name of the ACF Field Group"
      }
      menuItems: {
        type: "[WpAcfOptionsMainMenu_Mainmenu_menuItems]"
        description: ""
      }
    }
    description: "Field Group"
    extensions: {
      infer: false
    }
    interfaces: [
      "WpAcfFieldGroup"
    ]
  }
}

Typename WpAcfFieldGroup diff:
{
  kind: "INTERFACE"
  config: {
    name: "WpAcfFieldGroup"
   fields: {
      fieldGroupName: {
        type: "String"
        description: "The name of the ACF Field Group"
      }
    }
    extensions: {
      infer: false
    }
    interfaces: [
    ]
  }
}

Typename WpAcfOptionsMainMenu_Mainmenu_CallToAction diff:
{
  kind: "OBJECT"
  config: {
    name: "WpAcfOptionsMainMenu_Mainmenu_CallToAction"
    fields: {
      destination: {
        type: "WpAcfOptionsMainMenu_Mainmenu_CallToAction_Destination"
        description: ""
      }
      fieldGroupName: {
        type: "String"
        description: "The name of the ACF Field Group"
      }
      label: {
        type: "String"
        description: ""
      }
    }
    description: "Field Group"
    extensions: {
      infer: false
    }
    interfaces: [
      "WpAcfFieldGroup"
    ]
  }
}

Typename WpAcfOptionsMainMenu_Mainmenu_CallToAction_Destination diff:
{
  kind: "UNION"
  config: {
    name: "WpAcfOptionsMainMenu_Mainmenu_CallToAction_Destination"
    types: [
      "WpPage"
    ]
    extensions: {
      infer: false
    }
  }
}

Typename WpUser diff:
 {
   kind: "OBJECT"
   config: {
     name: "WpUser"
     fields: {
      shouldShowAdminToolbar: {
        type: "Boolean"
        description: "Whether the Toolbar should be displayed when the user is      
viewing the site."
      }
       avatar: {
         type: "WpAvatar"
         description: "Avatar object for user. The avatar object can be retrieved in 
different sizes by specifying the size argument."
       }
       capKey: {
         type: "String"
         description: "User metadata option name. Usually it will be
&quot;wp_capabilities&quot;."
       }
       capabilities: {
         type: "[String]"
         description: "A list of capabilities (permissions) granted to the user"     
       }
       comments: {
         type: "WpUserToCommentConnectionType"
         description: "Connection between the User type and the Comment type"        
       }
       databaseId: {
         type: "Int!"
       description: {
         type: "String"
         description: "Description of the user."
       }
       email: {
         type: "String"
         description: "Email address of the user. This is equivalent

### Reproduction Link

no link yet

### Steps to Reproduce

1. Add Local WP
2. Connect Local with Gatsby project
3. Create advanced custom fields pro
4. Command 'gatsby develop'

### Expected Result

The project must be builded.

### Actual Result

"not finished createSchemaCustomization"

### Environment

```shell
System: Windows 11
Browser: Chrome
npmPackages:
    "@apollo/client": "^3.7.3",
    "@fortawesome/fontawesome-svg-core": "^6.2.1",
    "@fortawesome/free-solid-svg-icons": "^6.2.1",
    "@fortawesome/react-fontawesome": "^0.2.0",
    "@tailwindcss/nesting": "^0.0.0-insiders.565cd3e",
    "@webdeveducation/wp-block-tools": "^1.1.19",
    "gatsby": "^5.3.3",
    "gatsby-plugin-apollo": "^4.0.3",
    "gatsby-plugin-image": "^3.3.2",
    "gatsby-plugin-manifest": "^5.3.1",
    "gatsby-plugin-react-helmet": "^6.3.0",
    "gatsby-plugin-sharp": "^5.3.2",
    "gatsby-source-filesystem": "^5.3.1",
    "gatsby-source-graphql": "^5.3.1",
    "gatsby-source-wordpress": "^7.8.0",
    "gatsby-transformer-sharp": "^5.3.1",
    "graphql": "^16.6.0",
    "numeral": "^2.0.6",
    "postcss-reporter": "^7.0.5",
    "prettier": "^2.8.1",
    "prettier-plugin-tailwindcss": "^0.2.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "uuid": "^9.0.0"
```

**Comment by LekoArts** [comment] 2023-04-14 06:53
Duplicate of https://github.com/gatsbyjs/gatsby/issues/37931 - please provide a minimal reproduction there.

**Closed by LekoArts** 2023-04-14 06:53 UTC
Labels: type: bug, status: triage needed
