### ISSUE TITLE
Working with images in front matter

### ISSUE THREAD

**Issue by asdac3** [gatsbyjs/gatsby#21116] opened 2020-02-01 03:13 UTC
## Description

Getting an error in GraphQL Query
```
Field "cover" must not have a selection since type "String" has no subfields.

This can happen if you e.g. accidentally added { } to the field "cover". If you didn't expect "cover" to be of type "String" make sure that your input source and/or plugin is correct.
```

### Steps to reproduce

It's appearing weirdly, see below

### Expected result

Should parse a frontmatter field as File

### Actual result

parsing frontmatter field as String

### Environment

I don't think it is a problem on my side, because if I change the word cover to image it is giving correct output where I can use it with gatsby-image but when used word "cover" it is giving the above error.
Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by asdac3** [comment] 2020-02-01 03:22
I want to know how gatsby works to find whether a frontmatter element is a string or file?

**Comment by asdac3** [comment] 2020-02-01 03:44
I don't know the issue but when I changed the word _cover_ to _coverImage_, it's working now.
Is the word **image** necessary?
Please anyone explain, or update the docs please...

**Comment by LekoArts** [comment] 2020-02-02 17:23
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by sidharthachatterjee** [comment] 2020-02-12 20:54
@asdac3 If a filepath points to an actual image, it will be transformed into a File node in GraphQL and then you can get the image data out of it by using the childImageSharp field.

Make sure the that in a Markdown file, the path to the image is relative to the page file

Hope that helps! Closing for now but please feel free to reopen with more information if you need any more help 🙂

**Closed by sidharthachatterjee** 2020-02-12 20:54 UTC
Labels: status: needs reproduction
