### ISSUE TITLE
Somtime images not loaded with gatsby-source-image

### ISSUE THREAD

**Issue by nashvinxtn** [gatsbyjs/gatsby#37184] opened 2022-12-06 08:41 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I have a website integrated on gatsby 4 with drupal api. I am fetching all images & with gatsby-image-plugin converting them to webp for display. But sometime after data changes build, some images is not generating & giving a 404. After a clear cache and build it generates all images. 
What can be the source of the prob?

### Reproduction Link

https://build-40b9182d-99cc-407d-acf8-cc5bd83d04c8.gatsbyjs.io/hotels-mauritius/le-telfair/restaurants-bars/annabellas

### Steps to Reproduce

For example this was the build with images 404 :
https://build-40b9182d-99cc-407d-acf8-cc5bd83d04c8.gatsbyjs.io/hotels-mauritius/le-telfair/restaurants-bars/annabellas

This is the good version : 
https://heritageresorts.mu/hotels-mauritius/le-telfair/restaurants-bars/annabellas

### Expected Result

Know what is the caused of the prob, how to prevent it from occuring again.

### Actual Result

No needing to do clear cache & build each the we have the issue.

### Environment

```shell
System:
    OS: Linux 5.4 Linux Mint 20.3 (Una)
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.14.0/bin/yarn
    npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
  Languages:
    Python: 3.8.10 - /usr/bin/python
  Browsers:
    Chrome: 108.0.5359.71
    Firefox: 107.0
  npmPackages:
    gatsby: ^4.24.1 => 4.24.1 
    gatsby-plugin-brotli: ^2.1.0 => 2.1.0 
    gatsby-plugin-config: ^1.0.7 => 1.0.7 
    gatsby-plugin-cookiebot: ^1.0.3 => 1.0.3 
    gatsby-plugin-gatsby-cloud: ^4.13.0 => 4.15.0 
    gatsby-plugin-google-tagmanager: ^4.20.0 => 4.20.0 
    gatsby-plugin-image: ^2.10.1 => 2.24.0 
    gatsby-plugin-local-search: ^2.0.1 => 2.0.1 
    gatsby-plugin-manifest: ^4.11.1 => 4.15.1 
    gatsby-plugin-minify-html: ^1.0.4 => 1.0.4 
    gatsby-plugin-offline: ^5.11.1 => 5.15.1 
    gatsby-plugin-preconnect: ^1.3.0 => 1.3.0 
    gatsby-plugin-react-helmet: ^5.11.0 => 5.15.0 
    gatsby-plugin-react-helmet-canonical-urls: ^1.4.0 => 1.4.0 
    gatsby-plugin-react-intl: ^4.0.0 => 4.0.0 
    gatsby-plugin-robots-txt: ^1.7.1 => 1.7.1 
    gatsby-plugin-sass: ^5.11.1 => 5.15.1 
    gatsby-plugin-sharp: ^4.24.0 => 4.24.0 
    gatsby-plugin-sitemap: ^5.19.0 => 5.19.0 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-plugin-zopfli: ^2.0.0 => 2.0.0 
    gatsby-source-drupal: ^5.14.0 => 5.16.2 
    gatsby-source-filesystem: ^4.24.0 => 4.24.0 
    gatsby-source-wordpress: ^6.17.0 => 6.17.0 
    gatsby-transformer-sharp: ^4.24.0 => 4.24.0 
  npmGlobalPackages:
    gatsby-cli: 4.8.1
```

### Config Flags

PRESERVE_FILE_DOWNLOAD_CACHE: true,
FAST_DEV: true,
PARALLEL_SOURCING: true,
PARALLEL_QUERY_RUNNING: true,

**Comment by LekoArts** [comment] 2022-12-06 08:47
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by dmxt** [comment] 2022-12-13 23:17
> To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction](https://gatsby.dev/reproduction).

I don't know what kind of problem is causing this. I didn't add much other than gatsby's official blog starter.

**Comment by LekoArts** [comment] 2022-12-14 08:16
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2022-12-14 08:16 UTC
Labels: type: bug, status: needs reproduction, topic: media
