### ISSUE TITLE
Server terminates when adding a image file

### ISSUE THREAD

**Issue by dantehemerson** [gatsbyjs/gatsby#28754] opened 2020-12-26 06:36 UTC
## Description

When the server is running in development mode and I add a new file to my project, the server terminates with errors.

### Steps to reproduce

Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/
Clone https://github.com/dantehemerson/dantecalderon.dev

* Run the development server
* Add an image file inside the project folder `/content/images`

### Expected result

What should happen?

Shouldn't crash the server.

### Actual result

What happened.
The server terminates with the next error:
```
success createPages - 0.056s
success Checking for changed pages - 0.001s
success update schema - 0.025s
success onPreExtractQueries - 0.001s
success extract queries from components - 0.063s
success write out requires - 0.001s
success run static queries - 0.014s - 1/1 71.58/s
success run page queries - 0.653s - 38/38 58.15/s
success Re-building development bundle - 0.091s
warn Error persisting state: function plugin({
  beginMarker,
  endMarker,
  pattyName = 'patty',
  onlyRunWithMarker = false,
  insertBef...<omitted>...
} could not be cloned.
info added file at
/home/dantehemerson/Documents/repos/dantecalderon.dev/content/images/bidirectional-communication.png.crdownload
Failed to validate error Error [ValidationError]: "errno" is not allowed. "syscall" is not allowed. "path" is not allowed
    at Object.exports.process
(/home/dantehemerson/Documents/repos/dantecalderon.dev/node_modules/@hapi/joi/lib/errors.js:202:19)
    at internals.Object._validateWithOptions
(/home/dantehemerson/Documents/repos/dantecalderon.dev/node_modules/@hapi/joi/lib/types/any/index.js:763:31)
    at internals.Object.validate
(/home/dantehemerson/Documents/repos/dantecalderon.dev/node_modules/@hapi/joi/lib/types/any/index.js:797:21)
    at constructError (/home/dantehemerson/Documents/repos/dantecalderon.dev/node_modules/gatsby-cli/lib/structured-error
s/construct-error.js:52:32)
    at Reporter.error
(/home/dantehemerson/Documents/repos/dantecalderon.dev/node_modules/gatsby-cli/lib/reporter/reporter.js:135:59)
    at Object.error
(/home/dantehemerson/Documents/repos/dantecalderon.dev/node_modules/gatsby/src/utils/api-runner-node.js:190:16)
    at /home/dantehemerson/Documents/repos/dantecalderon.dev/node_modules/gatsby-source-filesystem/gatsby-node.js:157:58
{
  isJoi: true,
  details: [
    {
      message: '"errno" is not allowed',
      path: [Array],
      type: 'object.allowUnknown',
      context: [Object]
    },
    {
      message: '"syscall" is not allowed',
      path: [Array],
      type: 'object.allowUnknown',
      context: [Object]
    },
    {
      message: '"path" is not allowed',
      path: [Array],
      type: 'object.allowUnknown',
      context: [Object]
    }
  ],
  _object: {
    context: {},
    errno: -2,
    code: 'ENOENT',
    syscall: 'open',
    path:
'/home/dantehemerson/Documents/repos/dantecalderon.dev/content/images/bidirectional-communication.png.crdownload',
    pluginName: 'gatsby-source-filesystem',
    text: 'There was an error',
    level: 'ERROR',
    stack: [],
    docsUrl: 'https://gatsby.dev/issue-how-to'
  },
  annotate: [Function]
}

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
```

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.18.0/bin/yarn
    npm: 6.14.9 - ~/.nvm/versions/node/v12.18.0/bin/npm
  Languages:
    Python: 3.8.3 - /home/dantehemerson/anaconda3/bin/python
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 84.0
  npmGlobalPackages:
    gatsby-cli: 2.16.2
```

**Comment by stevenwally** [comment] 2021-01-06 19:21
@dantehemerson I'm slightly suspicious of the `.crdownload` extension on that image file, `bidirectional-communication.png.crdownload`;

Have you tried adding the image after renaming it and dropping that extension in favor of the `.png`? eg. `bidrectional-communication.png`.

That particular extension is a temporary extension created by Chrome (browser) when a download is incomplete/in progress. You typically aren't able to open those files until you drop that extension.

**Comment by ascorbic** [comment] 2021-01-14 09:25
Hi @dantehemerson 
I'm afraid I can't reproduce this. I followed your exact steps and it continues fine after adding the image. I can see from your logs that you're adding a ".crdownload" file rather than an image, though I don't think that is the problem. Are you able to produce a more minimal reproduction, without quite so many plugins? Could you also ensure you're including the full output of gatsby info run from the project directory: there should be a list of plugins and local npm packages

**Comment by saiemsaeed** [comment] 2021-01-14 21:54
The exact same error is happening for me also. I'm sourcing content from WordPress. But the weirdness is that it happens occasionally, sometimes build generates successfully and sometimes I get this error and when I rebuild, it works fine.

**Comment by alexdkaminski** [comment] 2021-03-09 22:05
I am also having this issue, did you have any luck resolving it?

**Comment by justyn-clark** [comment] 2021-03-13 00:19
Same, having this issue right now.

**Comment by KornelijusGlinskas** [comment] 2021-03-14 13:57
+1 having this one as well

**Comment by LekoArts** [comment] 2021-03-15 08:43
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-03-15 08:43 UTC
Labels: status: awaiting author response, topic: filesystem, type: bug
