### ISSUE TITLE
index.d.ts Typescript types are incorrect and block build

### ISSUE THREAD

**Issue by Bartmr** [gatsbyjs/gatsby#31305] opened 2021-05-07 09:53 UTC
## Description

Gatsby's Typescript declaration files stop the build process

### Steps to reproduce

Update Gatsby to `3.4.1` and try to run a Typescript build or typecheck

### Expected result

Typecheck or build should pass normally

### Actual result

Typescript fails and shows the missing types:
```
node_modules/gatsby/index.d.ts:1538:14 - error TS2304: Cannot find name 'T'.

1538   send: Send<T>
                  ~

node_modules/gatsby/index.d.ts:1542:14 - error TS2304: Cannot find name 'T'.

1542   json: Send<T>
                  ~

node_modules/gatsby/index.d.ts:1546:35 - error TS2315: Type 'GatsbyAPIFunctionResponse' is not generic.

1546   status: (statusCode: number) => GatsbyAPIFunctionResponse<T>
                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/gatsby/index.d.ts:1546:61 - error TS2304: Cannot find name 'T'.

1546   status: (statusCode: number) => GatsbyAPIFunctionResponse<T>
                                                                 ~

node_modules/gatsby/index.d.ts:1547:26 - error TS2315: Type 'GatsbyAPIFunctionResponse' is not generic.

1547   redirect(url: string): GatsbyAPIFunctionResponse<T>
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/gatsby/index.d.ts:1547:52 - error TS2304: Cannot find name 'T'.

1547   redirect(url: string): GatsbyAPIFunctionResponse<T>
                                                        ~

node_modules/gatsby/index.d.ts:1548:42 - error TS2315: Type 'GatsbyAPIFunctionResponse' is not generic.

1548   redirect(status: number, url: string): GatsbyAPIFunctionResponse<T>
                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/gatsby/index.d.ts:1548:68 - error TS2304: Cannot find name 'T'.

1548   redirect(status: number, url: string): GatsbyAPIFunctionResponse<T>
```

### Environment

  System:
    OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: 88.0.1
  npmPackages:
    gatsby: ^3.4.1 => 3.4.1
    gatsby-plugin-image: ^1.4.0 => 1.4.0
    gatsby-plugin-manifest: ^3.4.0 => 3.4.0
    gatsby-plugin-offline: ^4.4.0 => 4.4.0
    gatsby-plugin-react-helmet: ^4.4.0 => 4.4.0
    gatsby-plugin-robots-txt: ^1.5.6 => 1.5.6
    gatsby-plugin-sass: ^4.4.0 => 4.4.0
    gatsby-plugin-sharp: ^3.4.1 => 3.4.1
    gatsby-plugin-sitemap: ^4.0.0 => 4.0.0
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.22 => 1.1.22
    gatsby-source-filesystem: ^3.4.0 => 3.4.0
    gatsby-transformer-sharp: ^3.4.0 => 3.4.0

**Comment by LekoArts** [comment] 2021-05-07 11:09
Hi, thanks for the issue! This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/31135 and will be released next tuesday.

**Closed by LekoArts** 2021-05-07 11:09 UTC
Labels: status: triage needed, type: bug
