### ISSUE TITLE
[gatsby-plugin-manifest] cannot start development server

### ISSUE THREAD

**Issue by ARXChrono** [gatsbyjs/gatsby#17336] opened 2019-09-03 07:43 UTC
## Description

When i start up the development server an error occurs

### Steps to reproduce

When i bump to gatsby-plugin-manifest 2.2.7 or higher this will give me this error. Everything before seems to work

### Expected result

Development server should boot up like normal

### Actual result

![Screen Shot 2019-09-03 at 2 45 02 pm](https://user-images.githubusercontent.com/6690757/64153255-0f93ba00-ce61-11e9-93d1-f77175af92ef.png)

### Environment

  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.11.0 - ~/.nvm/versions/node/v8.11.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.nvm/versions/node/v8.11.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 66.0.5
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.13.45 => 2.15.3
    gatsby-plugin-catch-links: ^2.1.2 => 2.1.7
    gatsby-plugin-compile-es6-packages: ^1.1.0 => 1.2.0
    gatsby-plugin-favicon: ^3.1.6 => 3.1.6
    gatsby-plugin-google-tagmanager: ^2.1.8 => 2.1.8
    gatsby-plugin-manifest: 2.2.6 => 2.2.6 **(It works here, just not on 2.2.7+)**
    gatsby-plugin-polyfill-io: ^1.1.0 => 1.1.0
    gatsby-plugin-react-helmet: ^3.1.2 => 3.1.6
    gatsby-plugin-sitemap: ^2.2.4 => 2.2.10
    gatsby-plugin-styled-components: ^3.1.4 => 3.1.2

**Comment by 97thjingba** [comment] 2019-09-06 03:46
You can try changing the order of the plugins in your configuration. 
if it is work, please tell me

**Comment by LekoArts** [comment] 2019-09-06 08:14
Sounds like a duplicate of https://github.com/gatsbyjs/gatsby/issues/16957
Please have a look there for solutions and try `npm rebuild` first! Thanks

**Closed by LekoArts** 2019-09-06 08:14 UTC
Labels: type: bug

**Comment by ARXChrono** [comment] 2019-09-10 08:49
> Sounds like a duplicate of #16957
> Please have a look there for solutions and try `npm rebuild` first! Thanks

Yup, that thread had the solution i was looking for
