### ISSUE TITLE
Plugin library not rendering some READMEs

### ISSUE THREAD

**Issue by robinmetral** [gatsbyjs/gatsby#13720] opened 2019-04-29 16:31 UTC
## Description

The plugin library doesn't render READMEs for some plugins.

I've seen this happen in the `gatsby-plugin-i18n` series of plugins, organized as a monorepo. Not sure if the monorepo structure causes this. They render correctly on the npm registry.

### Steps to reproduce

Go to:
- https://www.gatsbyjs.org/packages/gatsby-plugin-i18n/
- https://www.gatsbyjs.org/packages/gatsby-plugin-i18n-tags/
- https://www.gatsbyjs.org/packages/gatsby-plugin-i18n-readnext/

### Expected result

The READMEs should be rendered

### Actual result

They aren't

### Environment

User agent `Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0`

**Comment by robinmetral** [comment] 2019-04-29 16:38
Further investigation:

The "View plugin on GitHub" link on these plugin pages doesn't work either, it links to a GitHub *search* instead of the repo.

A weird case is this of [`gatsby-plugin-i18nstatic`](https://www.gatsbyjs.org/packages/gatsby-plugin-i18nstatic/). The README renders correctly, but the link still points to a GitHub search.

**Comment by LekoArts** [comment] 2019-04-30 09:25
Thanks for the issue! This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/11129 and hence I'm closing this. Please leave a comment there, thanks!

**Closed by LekoArts** 2019-04-30 09:25 UTC

**Comment by robinmetral** [comment] 2019-04-30 10:58
Oops! Sorry about this, it didn't come out in my search. Thanks @LekoArts
