### ISSUE TITLE
How to fix this? Using `gatsby-theme-andy` but can't work.

### ISSUE THREAD

**Issue by JackQAQ-byte** [gatsbyjs/gatsby#26529] opened 2020-08-18 11:16 UTC
<!--
  Please fill out each section below, otherwise, your issue will be closed. This info allows Gatsby maintainers to diagnose (and fix!) your issue as quickly as possible.

  Useful Links:
- `gatsby-theme-andy` https://github.com/aravindballa/gatsby-theme-andy

## Description

ERROR #85923  GRAPHQL

`There was an error in your GraphQL query:`

`Cannot query field "siteMetadata" on type "Site".`

`If you don't expect "siteMetadata" to exist on the type "Site" it is most likely a typo.`

### Steps to reproduce

I followed all the steps from https://www.youtube.com/watch?v=bf5Wj-1IHa4

### Expected result

i can see my notes in `localhost:8080`

### Actual result

The error above

### Environment

  System:
    OS: Linux 5.7 ArchLabs
    CPU: (4) x64 Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.22.0 - ~/.nvm/versions/node/v10.22.0/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v10.22.0/bin/npm
  Languages:
    Python: 3.8.5 - /usr/bin/python
  Browsers:
    Firefox: 79.0
  npmPackages:
    gatsby: ^2.24.47 => 2.24.47
    gatsby-theme-andy: ^0.2.1 => 0.2.1
  npmGlobalPackages:
    gatsby-cli: 2.12.87

**Comment by pieh** [comment] 2020-08-20 23:07
I'll close the issue because there is no details here. 

If the issue you are facing is related to that particular theme - you'd need to report it in https://github.com/aravindballa/gatsby-theme-andy (that theme is not maintained in this repository) - but please, do add some description there, because "can't work" is not actionable for anyone. If the maintainer(s) of the theme will find that the issue is indeed in `gatsby` itself - then please open new issue here with link to the issue in theme's repository.

**Closed by pieh** 2020-08-20 23:07 UTC
Labels: status: triage needed, type: bug, type: question or discussion
