### ISSUE TITLE
PNG image failed to be processed by vips2png

### ISSUE THREAD

**Issue by miiitch** [gatsbyjs/gatsby#29234] opened 2021-01-27 17:38 UTC
## Description

I have this issue at build and develop time:

`SearchGraphProcess2.png.
It is probably corrupt, so please try replacing it.  If it still fails, please open an issue with the image attached.

  Error: vips2png: unable to write to target target`

### Steps to reproduce

clone this repo: https://github.com/miiitch/gatsby-issue-img and build it to have the issue. This is a clone of starter blog with the image that make the build failed.

### Environment

 System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Node: 12.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.1
  Browsers:
    Chrome: 88.0.4324.104
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.50), ChromiumDev (89.0.767.0)
  npmPackages:
    gatsby: ^2.31.1 => 2.31.1
    gatsby-image: ^2.10.0 => 2.10.0
    gatsby-plugin-feed: ^2.12.0 => 2.12.0
    gatsby-plugin-google-analytics: ^2.10.0 => 2.10.0
    gatsby-plugin-manifest: ^2.11.0 => 2.11.0
    gatsby-plugin-offline: ^3.9.0 => 3.9.0
    gatsby-plugin-react-helmet: ^3.9.0 => 3.9.0
    gatsby-plugin-sharp: ^2.13.2 => 2.13.2
    gatsby-plugin-typescript: ^2.11.0 => 2.11.0
    gatsby-remark-copy-linked-files: ^2.9.0 => 2.9.0
    gatsby-remark-images: ^3.10.0 => 3.10.0
    gatsby-remark-prismjs: ^3.12.0 => 3.12.0
    gatsby-remark-responsive-iframe: ^2.10.0 => 2.10.0
    gatsby-remark-smartypants: ^2.9.0 => 2.9.0
    gatsby-source-filesystem: ^2.10.0 => 2.10.0
    gatsby-transformer-remark: ^2.15.0 => 2.15.0
    gatsby-transformer-sharp: ^2.11.0 => 2.11.0
  npmGlobalPackages:
    gatsby-cli: 2.18.0
    gatsby: 2.31.1

**Comment by ascorbic** [comment] 2021-01-28 10:13
Hi. Did you try replacing the png? That error means that libspng found an error that meant it couldn't process the image.

**Comment by miiitch** [comment] 2021-01-28 16:05
The png is good, I have this error just after updating the gatsby packages. It was working with this config: 

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 12.12.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.1
  Browsers:
    Chrome: 88.0.4324.104
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.50), ChromiumDev (89.0.774.4)
  npmPackages:
    gatsby: ^2.24.58 => 2.24.62 
    gatsby-image: ^2.4.17 => 2.4.19 
    gatsby-plugin-feed: ^2.5.11 => 2.5.12 
    gatsby-plugin-google-analytics: ^2.3.13 => 2.3.14 
    gatsby-plugin-manifest: ^2.4.28 => 2.4.30 
    gatsby-plugin-offline: ^3.2.27 => 3.2.28 
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.11 
    gatsby-plugin-sharp: ^2.6.35 => 2.6.36 
    gatsby-plugin-typescript: ^2.4.19 => 2.4.20 
    gatsby-remark-copy-linked-files: ^2.3.14 => 2.3.15 
    gatsby-remark-images: ^3.3.29 => 3.3.30 
    gatsby-remark-prismjs: ^3.5.12 => 3.5.13 
    gatsby-remark-responsive-iframe: ^2.4.13 => 2.4.14 
    gatsby-remark-smartypants: ^2.3.10 => 2.3.11 
    gatsby-source-filesystem: ^2.3.29 => 2.3.30 
    gatsby-transformer-remark: ^2.8.34 => 2.8.35 
    gatsby-transformer-sharp: ^2.5.14 => 2.5.15 
  npmGlobalPackages:
    gatsby-cli: 2.18.0
    gatsby: 2.31.1

**Comment by domvo** [comment] 2021-01-28 16:35
Possible duplicate of https://github.com/gatsbyjs/gatsby/issues/28203

**Comment by miiitch** [comment] 2021-01-28 16:51
Thanks for the notice @domvo. It is very annoying

**Comment by domvo** [comment] 2021-01-28 17:09
@ascorbic I'm pretty sure the `failOnError` option is not passed down to sharp correctly. When trying locally like so it works just fine:

```javascript
const sharp = require('sharp');

sharp('./test.png', {
  failOnError: false,
})
  .resize(300, 200)
  .toFile('output.png', (err) => {
    console.log(err);
  });
```

Note: test.png is a file that is corrupted. Without the `failOnError` option I get the following error:
```
[Error: pngload: non-recoverable state
vips2png: unable to write to target output.png
]
```

**Comment by ascorbic** [comment] 2021-01-28 17:09
The reason this appeared after upgrading is that libvips switched png libraries, and the new one is stricter with corrupt images. A fix will just mean we skip corrupt images rather than failing the build: it's not going to be able to process them. I strongly recommend seeing if you can fix the image. I'm going to close this as a duplicate of #28203

**Closed** 2021-01-28 17:10 UTC
Labels: status: awaiting author response, topic: images/media, type: bug

**Comment by domvo** [comment] 2021-01-28 17:26
Fixing the image is not a viable option since the image comes from my client. Making the `failOnError` option work as intended would be enough for most people running into issues now, I would assume.

**Comment by randy408** [comment] 2021-05-06 17:49
`SearchGraphProcess2.png` has an invalid chunk CRC, that should be ignored since [v0.6.2](https://github.com/randy408/libspng/releases/tag/v0.6.2) (current is v0.6.3).
