### ISSUE TITLE
Cannot find module '..\.cache\caches\gatsby-plugin-mdx\webpack\output.js'

### ISSUE THREAD

**Issue by PhanTheAnhAndrew** [gatsbyjs/gatsby#32327] opened 2021-07-11 11:14 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi, I'm getting this error while building before deployment. I tried to run "gatsby clean" or even "rm node-modules" but it doesn't work. 

Thank you for your help <3

```
> 
> **UNHANDLED REJECTION** Cannot find module 'D:\Tutorial\gastby\lazy-nerds-gatsby\.cache\caches\gatsby-plugin-mdx\webpack\output.js'
> Require stack:
> - D:\Tutorial\gastby\lazy-nerds-gatsby\node_modules\gatsby-plugin-mdx\utils\render-html.js
> - D:\Tutorial\gastby\lazy-nerds-gatsby\node_modules\gatsby-plugin-mdx\gatsby\create-schema-customization.js
> - D:\Tutorial\gastby\lazy-nerds-gatsby\node_modules\gatsby-plugin-mdx\gatsby-node.js
> - D:\Tutorial\gastby\lazy-nerds-gatsby\node_modules\gatsby\dist\bootstrap\load-plugins\validate.js
> - D:\Tutorial\gastby\lazy-nerds-gatsby\node_modules\gatsby\dist\bootstrap\load-plugins\load.js
> - D:\Tutorial\gastby\lazy-nerds-gatsby\node_modules\gatsby\dist\bootstrap\load-plugins\index.js
> - D:\Tutorial\gastby\lazy-nerds-gatsby\node_modules\gatsby\dist\bootstrap\load-config-and-plugins.js
> - D:\Tutorial\gastby\lazy-nerds-gatsby\node_modules\gatsby\dist\services\initialize.js
> - D:\Tutorial\gastby\lazy-nerds-gatsby\node_modules\gatsby\dist\services\index.js
> - D:\Tutorial\gastby\lazy-nerds-gatsby\node_modules\gatsby\dist\bootstrap\index.js
> - D:\Tutorial\gastby\lazy-nerds-gatsby\node_modules\gatsby\dist\commands\build.js
> - C:\Users\Admin-s\AppData\Roaming\npm\node_modules\gatsby\node_modules\gatsby-cli\lib\create-cli.js
> - C:\Users\Admin-s\AppData\Roaming\npm\node_modules\gatsby\node_modules\gatsby-cli\lib\index.js
> - C:\Users\Admin-s\AppData\Roaming\npm\node_modules\gatsby\dist\bin\gatsby.js
> - C:\Users\Admin-s\AppData\Roaming\npm\node_modules\gatsby\cli.js
```

**Here are my configs:**

```
{
      resolve: "gatsby-plugin-mdx",
      options: {
          extensions: [`.mdx`, `.md`],
      },
  },
```

**plugin details:**
```

"gatsby-plugin-mdx": "^2.9.0",
"@mdx-js/mdx": "^1.6.22",
"@mdx-js/react": "^1.6.22",
```

### Reproduction Link

https://github.com/PhanTheAnhAndrew/lazy-nerds-gatsby/tree/master

### Steps to Reproduce

1. gatsby clean & gatsby build

### Expected Result

Should build successfully

### Actual Result

Getting Error:
UNHANDLED REJECTION Cannot find module 'D:\Tutorial\gastby\lazy-nerds-gatsby\.cache\caches\gatsby-plugin-mdx\webpack\output.js'
Require stack:
- D:\Tutorial\gastby\lazy-nerds-gatsby\node_modules\gatsby-plugin-mdx\utils\render-html.js
- D:\Tutorial\gastby\lazy-nerds-gatsby\node_modules\gatsby-plugin-mdx\gatsby\create-schema-customization.js
- D:\Tutorial\gastby\lazy-nerds-gatsby\node_modules\gatsby-plugin-mdx\gatsby-node.js
- D:\Tutorial\gastby\lazy-nerds-gatsby\node_modules\gatsby\dist\bootstrap\load-plugins\validate.js
- D:\Tutorial\gastby\lazy-nerds-gatsby\node_modules\gatsby\dist\bootstrap\load-plugins\load.js
- D:\Tutorial\gastby\lazy-nerds-gatsby\node_modules\gatsby\dist\bootstrap\load-plugins\index.js
- D:\Tutorial\gastby\lazy-nerds-gatsby\node_modules\gatsby\dist\bootstrap\load-config-and-plugins.js
- D:\Tutorial\gastby\lazy-nerds-gatsby\node_modules\gatsby\dist\services\initialize.js
- D:\Tutorial\gastby\lazy-nerds-gatsby\node_modules\gatsby\dist\services\index.js
- D:\Tutorial\gastby\lazy-nerds-gatsby\node_modules\gatsby\dist\bootstrap\index.js
- D:\Tutorial\gastby\lazy-nerds-gatsby\node_modules\gatsby\dist\commands\build.js
- C:\Users\Admin-s\AppData\Roaming\npm\node_modules\gatsby\node_modules\gatsby-cli\lib\create-cli.js
- C:\Users\Admin-s\AppData\Roaming\npm\node_modules\gatsby\node_modules\gatsby-cli\lib\index.js
- C:\Users\Admin-s\AppData\Roaming\npm\node_modules\gatsby\dist\bin\gatsby.js
- C:\Users\Admin-s\AppData\Roaming\npm\node_modules\gatsby\cli.js

### Environment

```shell
Window 10
Node: v14.16.0
Gatsby: ^3.6.2
"gatsby-plugin-mdx": "^2.9.0",
"@mdx-js/mdx": "^1.6.22",
"@mdx-js/react": "^1.6.22",
```

### Config Flags

```
{
            resolve: "gatsby-plugin-mdx",
            options: {
                extensions: [`.mdx`, `.md`],
            },
        },
        `gatsby-remark-images`,
        {
            resolve: `gatsby-plugin-mdx`,
            options: {
                gatsbyRemarkPlugins: [
                    {
                        resolve: `gatsby-remark-images`,
                        options: {
                            maxWidth: 1200,
                            loading: "lazy",
                            linkImagesToOriginal: true,
                            showCaptions: true,
                        },
                    },
                ],
            },
        },
```

**Comment by LekoArts** [comment] 2021-07-19 09:36
Hi!

Please link to a [minimal reproduction][reproduction] that is not your live project. The repository you linked has activity in it and we can't tell what we should check out now.

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-07-27 08:32
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-07-27 08:32 UTC
Labels: status: needs reproduction, type: bug

**Comment by Talaxy009** [comment] 2021-12-17 10:55
The same problem occurred after I try to migrate Remark to MDX, I solved this problem by checking my GraphQL query and then changed the `html` field in mdx to `body` as the [official docs](https://www.gatsbyjs.com/docs/how-to/routing/migrate-remark-to-mdx/#update-usage-in-pages) says.

**Comment by 12finger** [comment] 2022-04-26 20:42
I also migrated from Remark/gatsby-transformer-remark to MDX and was bugged by the `Cannot find module ' ... /.cache/caches/gatsby-plugin-mdx/webpack/output.js'` obscure error message.
Clearly the plugin is there and after resolving with @Talaxy009 finding, MDX is working just fine.

Would be nice @LekoArts if the MDX plugin would account for this (seemingly) common error, which stems from the malformed/malworded query ->     html (in remark) vs. body(in mdx) and if the plugin would out a better error message, if possible? Should i report this somewhere ? Where specifically? Creating a new issue here?

**Comment by kalebheitzman** [comment] 2022-07-28 18:37
> changed the `html` field in mdx to `body` as the [official docs](https://www.gatsbyjs.com/docs/how-to/routing/migrate-remark-to-mdx/#update-usage-in-pages) says.

THANK. YOU.
