### ISSUE TITLE
gatsby-plugin-mdx invalid custom  remarkPlugins

### ISSUE THREAD

**Issue by zaw929** [gatsbyjs/gatsby#36223] opened 2022-07-24 20:21 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

gatsby-plugin-mdx invalid custom  remarkPlugins

Gatsby and gatsby-plugin-mdx versions are invalid after a comprehensive upgrade

If the problem description is not clear, please leave a message, I can add

### Reproduction Link

https ://gatsby.dev/reproduction

### Steps to Reproduce

1.Create gatsby project
2.Migration code
3.Download dependencies, use pnpm
4.Everything works fine, but remarkPlugins doesn't work

### Expected Result

Change content in markdown

### Actual Result

 doesn't work

### Environment

```shell
new project

{
  "dependencies": {
    "@mdx-js/mdx": "v1",
    "@mdx-js/react": "v1",
    "@types/react-helmet": "^6.1.5",
    "gatsby": "^4.18.0",
    "gatsby-plugin-emotion": "^7.18.0",
    "gatsby-plugin-manifest": "^4.18.1",
    "gatsby-plugin-mdx": "^3.18.1",
    "gatsby-plugin-pnpm": "^1.2.10",
    "gatsby-plugin-react-helmet": "^5.18.0",
    "gatsby-plugin-react-svg": "3.0.0",
    "gatsby-plugin-sass": "^5.18.1",
    "gatsby-plugin-sharp": "^4.18.1",
    "gatsby-remark-copy-linked-files": "^5.18.0",
    "gatsby-remark-external-links": "^0.0.4",
    "gatsby-remark-images": "^6.18.1",
    "gatsby-remark-images-medium-zoom": "^1.7.0",
    "gatsby-remark-responsive-iframe": "^5.18.0",
    "gatsby-remark-smartypants": "^5.18.0",
    "gatsby-source-filesystem": "^4.18.1",
    "gatsby-transformer-sharp": "^4.18.1",
    "gatsby-transformer-yaml": "^4.18.0",
  },
}
```

**Comment by zaw929** [comment] 2022-07-24 20:23
{
    resolve: 'gatsby-plugin-mdx',
    options: {
      extensions: ['.mdx', '.md'],
      remarkPlugins: [
        [
          require('./plugins/xxxxx'), // custom plugin path
        ],
      ],
    },
  },

**Comment by LekoArts** [comment] 2022-07-25 04:33
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2022-08-03 06:00
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2022-08-03 06:00 UTC
Labels: type: bug, status: needs reproduction
