### ISSUE TITLE
[gatsby-transformer-remark] Third level nested unordered list items render as second level

### ISSUE THREAD

**Issue by fk** [gatsbyjs/gatsby#4096] opened 2018-02-17 00:19 UTC
Just noticed that in the latest blog post https://www.gatsbyjs.org/blog/2018-2-16-how-to-build-a-website-with-react/ this rendered fine when indented with four spaces ([like @shannonbux initially did](https://github.com/gatsbyjs/gatsby/commit/f949ea6ce50055a2b53e32a51d937d8f00a33857))

```
* Whole list
    * Title
    * add a to-do line
    * to-do line
        * subtasks within to-dos
    * show completed to-dos button
```

![image](https://user-images.githubusercontent.com/21834/36335431-3c45bece-1380-11e8-98fc-3705f93db01f.png)

but not when using two spaces ([after formatting with Prettier](https://github.com/gatsbyjs/gatsby/commit/acdf59472655707857e352135217ae545313c4da)):

```
* Whole list
  * Title
  * add a to-do line
  * to-do line
    * subtasks within to-dos
  * show completed to-dos button
```

![image](https://user-images.githubusercontent.com/21834/36335308-2f671dde-137f-11e8-891d-d14674cad532.png)

FWIW, the [TOC on `using-remark`](https://using-remark.gatsbyjs.org/hello-world-kitchen-sink/) also looks off, but it's been ages since I last conciously took a look on that:

![image](https://user-images.githubusercontent.com/21834/36335389-e0aa7da2-137f-11e8-8229-a2b65f7abe26.png)

**Comment by KyleAMathews** [comment] 2018-09-08 04:32
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Closed by KyleAMathews** 2018-09-08 04:32 UTC

**Comment by baerrach** [comment] 2020-02-04 04:41
@fk did you resolve this problem?

2 spaces = same indentation
3 spaces = same indentation
4 spaces = proper new indentation level

**Comment by fk** [comment] 2020-02-04 13:08
👋 Hey @baerrach — not that I remember :(

**Comment by kikunantoka** [comment] 2020-03-30 17:37
I also see this problem. I hope to solve this problem :)

**Comment by fk** [comment] 2020-03-31 21:42
Happy to reopen this issue; if anyone of y'all has the time for it, a minimal reproduction would be super nice.

Also—just thinking out loud—maybe using MDX would be an alternative?

**Comment by YaboLee** [comment] 2020-05-08 03:02
Same here.

Thanks for this issue(though it was closed) such that I could make my 3-level list...

**Comment by Mattsi-Jansky** [comment] 2021-05-16 11:38
Thanks for the fix @baerrach. Unfortunately it upsets my linter, as 2 spaces is standard for markdown: https://github.com/DavidAnson/markdownlint/blob/v0.23.1/doc/Rules.md#md007

What's the chance of getting this fixed? Taking a quick look it seems the problem is probably with remark: https://github.com/gnab/remark/issues/135 (Remark is used by Gatsby to parse MD: https://github.com/gatsbyjs/gatsby/blob/a35d615f9c8d596230ecd1f121f214b9879eb7d3/packages/gatsby-transformer-remark/src/extend-node-type.js#L184)

But remark say it's an issue further down the chain with one of their dependencies. If that's the case, then the issue is with Marked: https://github.com/markedjs/marked

I can't find any indication that Marked are aware of an issue. But looking at their tests, it seems they only tested nested lists with tabs not spaces: https://raw.githubusercontent.com/markedjs/marked/master/test/specs/original/ordered_and_unordered_lists.md

Presumably it's something to do with 4 spaces being recognised as a tab, while 2 isn't?
