### ISSUE TITLE
[CLI] UX - Remote download progress not visible

### ISSUE THREAD

**Issue by polarathene** [gatsbyjs/gatsby#25041] opened 2020-06-17 05:49 UTC
## Description

During a build, when the CLI outputs the stage `source and transform nodes` and remote images are being downloaded, this activity and progress briefly flickers before disappearing again, unlike the later stages like `Generating image thumbnails`.

Ideally, the feedback about download progress would not be hidden like that and would remain visible, nothing else was contending with it visually.

### Steps to reproduce

Build a project with sufficient remote content, or a slower / throttled connection that this step in the build process would be visible to witness.

I can provide a repo for trying this, but it's really going to depend on your network speed.

### Expected result

I should be able to see the progress of the files being downloaded.

### Actual result

It's a blank line, except for a brief moment/frame, where the progress is updated(download completed or new one started triggered it), and then it's blank again.

### Environment

```
  System:
    OS: Linux 5.4 Manjaro Linux
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Shell: 5.0.16 - /bin/bash
  Binaries:
    Node: 14.4.0 - ~/.asdf/installs/nodejs/14.4.0/bin/node
    Yarn: 1.22.4 - ~/.asdf/installs/nodejs/14.4.0/.npm/bin/yarn
    npm: 6.14.5 - ~/.asdf/installs/nodejs/14.4.0/bin/npm
  Languages:
    Python: 3.8.2
  Browsers:
    Firefox: 76.0.1
  npmPackages:
    gatsby: ^2.23.3 => 2.23.3
    gatsby-image: ^2.4.7 => 2.4.7
    gatsby-plugin-remote-images: ^2.1.0 => 2.1.0
    gatsby-plugin-sharp: ^2.6.11 => 2.6.11
    gatsby-plugin-styled-components: ^3.3.4 => 3.3.4
    gatsby-source-filesystem: ^2.3.11 => 2.3.11
    gatsby-transformer-sharp: ^2.5.5 => 2.5.5
    gatsby-transformer-yaml: ^2.4.4 => 2.4.4
  npmGlobalPackages:
    gatsby-cli: 2.12.43
```

`gatsby info --clipboard` is inaccurate with Languages and Browsers if that's meant to be system installed. I have many more languages and browsers on the system, although not relevant to this issue.

**Comment by vladar** [comment] 2020-06-17 17:33
Hi @polarathene 

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by polarathene** [comment] 2020-06-18 01:57
@vladar Did you read the issue before the copy/paste reproduction response?

Gatsby should already have an abundance of test projects with remote content download that can reproduce the same issue, but you'd need to do so with a network connection that is slow enough to witness the download progress, that can't be provided via a reproduction repo.

If you'd like, I can provide a project to clone, but if you don't have slow internet or a way to throttle it, you probably won't be able to reproduce it and would need a larger dataset to download.

**Comment by DSchau** [comment] 2020-06-18 03:53
@polarathene I mean -- yes, and also I read the issue as well and I think asking for a reproduction is abundantly fair.

You state here:

> I can provide a repo for trying this, but it's really going to depend on your network speed.

Could you provide this, please? It's _far_ _far_ easier to get up and debugging this (particularly when it appears to be network dependent) when we have something to go on, and it's immensely helpful.

A .gif or something visual to demonstrate the issue as clearly as possible would also help. 

We'd appreciate it; thank you.

**Comment by vladar** [comment] 2020-06-18 09:08
@polarathene, Of course, I've read the issue, and I completely understand what you mean. But the next step for anyone starting the work on it is to have an actual project to work with. Also, we need some common grounds if multiple people are interested in working on this.

Someone must still go and find an appropriate reproduction and share it here (ideally with all the steps on how to throttle the network). Since you already have enough context to file this issue, it makes perfect sense if you provide it.

Reproduction always makes it easier to move the work forward, as @DSchau correctly pointed out above.

**Comment by polarathene** [comment] 2020-06-19 12:15
Here is the [reproduction repo](https://gitlab.com/polarathene/example-cssgrid-gatsby-pugs/-/tree/remote-images), live on Netlify [here](https://css-grid-pugs.netlify.app/). It has 24 images from Unsplash that will pull down about ~150MB.

As gif is the only animated format supported natively here, the capture is a 4 second clip with a brief frame revealing the progress bar before it disappears again. On my machine the next one is about 10 seconds later.

![gatsby-download-cli-ux-bug](https://user-images.githubusercontent.com/5098581/85130834-c7c40f00-b289-11ea-9550-5918ccef9c35.gif)

---

I'm only aware how to throttle a connection via the browser, not on the system. If your connections are too fast, please add a larger remote set to download if nobody on the Gatsby team has knowledge how to throttle their network either.

**Comment by wardpeet** [comment] 2020-06-24 09:29
Hey @polarathene,

Thanks for the issue, it seems like `gatsby-plugin-remote-images` isn't using the proper API to fix this. CreateRemoteFileNode needs to use gatsby's reporter, if not it fallback to a different one.

https://github.com/gatsbyjs/gatsby/blob/debe18e972b73d26a7f6d45ed632ab1721c0f230/packages/gatsby-source-filesystem/src/create-remote-file-node.js#L324-L336

I suggest opening a PR on that repo and pass the reporter on the correct line. It should be exposed by the onCreateNode api.
https://github.com/graysonhicks/gatsby-plugin-remote-images/blob/0c71e8089a0b348777793a8ed72a172919149a66/src/gatsby-node.js#L71-L79

We're going to rework the reporter so it's part of the gatsby package and it will become easier to import it than what we have now.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Closed by wardpeet** 2020-06-24 09:29 UTC
Labels: status: needs reproduction, topic: cli, type: bug

**Comment by polarathene** [comment] 2020-06-24 09:47
@wardpeet ah ok, thanks for looking into the issue and identifying the problem and advising of a fix! I'll relay that information, cheers :)
