### ISSUE TITLE
`gatsby build` fails with `Couldn't find temp query result for (...)` error

### ISSUE THREAD

**Issue by belfz** [gatsbyjs/gatsby#35865] opened 2022-06-07 12:41 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I'm getting
```
 ERROR 

UNHANDLED REJECTION Couldn't find temp query result for "/learn-more/en-us".



  Error: Couldn't find temp query result for "/learn-more/en-us".
  
  - page-data.ts:104 readPageQueryResult
    [www-2022]/[gatsby]/src/utils/page-data.ts:104:11
  
  - task_queues:60 runNextTicks
    node:internal/process/task_queues:60:5
  
  - timers:442 processImmediate
    node:internal/timers:442:9
  
  - page-data.ts:121 writePageData
    [www-2022]/[gatsby]/src/utils/page-data.ts:121:18
  
  - page-data.ts:232 
    [www-2022]/[gatsby]/src/utils/page-data.ts:232:24
```

upon running `gatsby build`.

`learn-more` is created using `createPage` API, precisely:

```
actions.createPage({
        path: `/learn-more/en-us`,
        component: path.resolve(`src/non-cms-pages/learn-more.tsx`),
        context: {
          lang,
        },
      });
```

### Reproduction Link

https://github.com/belfz/gatsby-bug-reproduce

### Steps to Reproduce

run `yarn build` (running `gatsby build` under the hood)

### Expected Result

properly built static pages.

### Actual Result

error as mentioned in the description.

### Environment

```shell
System:
    OS: macOS 12.3.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.2.0 - /var/folders/pv/qbfq6qlj0k5gb43j33jmp1v80000gp/T/yarn--1654605646468-0.18090503546208625/node
    Yarn: 1.22.19 - /var/folders/pv/qbfq6qlj0k5gb43j33jmp1v80000gp/T/yarn--1654605646468-0.18090503546208625/yarn
    npm: 8.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.14 - /usr/local/bin/python
  Browsers:
    Chrome: 102.0.5005.61
    Firefox: 97.0.2
    Safari: 15.4
  npmPackages:
    gatsby: 4.14.1 => 4.14.1
    gatsby-env-variables: 2.0.0 => 2.0.0
    gatsby-plugin-image: 2.15.0 => 2.15.0
    gatsby-plugin-react-helmet: 5.15.0 => 5.15.0
    gatsby-plugin-react-svg: 3.1.0 => 3.1.0
    gatsby-plugin-robots-txt: 1.7.1 => 1.7.1
    gatsby-plugin-segment-js: 3.7.1 => 3.7.1
    gatsby-plugin-styled-components: 5.15.0 => 5.15.0
    gatsby-source-custom-api: 2.1.3 => 2.1.3
    gatsby-source-filesystem: 4.15.0 => 4.15.0
    gatsby-source-prismic: 5.2.7 => 5.2.7
```

### Config Flags

none

**Comment by LekoArts** [comment] 2022-06-07 12:45
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by belfz** [comment] 2022-06-14 05:50
@LekoArts any update on this?

**Comment by LekoArts** [comment] 2022-06-14 06:02
I'll close this as a duplicate of https://github.com/gatsbyjs/gatsby/issues/35018, please post your reproduction there. Thanks!

**Closed by LekoArts** 2022-06-14 06:02 UTC
Labels: type: bug, status: needs reproduction
