### ISSUE TITLE
Static queries not working in Storybook

### ISSUE THREAD

**Issue by mrseanbaines** [gatsbyjs/gatsby#26440] opened 2020-08-13 12:37 UTC
## Description

I'm getting "Loading (StaticQuery)" in Storybook for any component that uses `StaticQuery` and "The result of this StaticQuery could not be fetched." in Storybook for any component that uses `useStaticQuery`. Everything seems to work fine locally and when built, but in Storybook I am getting this:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/24367010/90175592-8dfe1900-dd9f-11ea-90eb-474390a9d72d.png">

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/24367010/90175825-ef25ec80-dd9f-11ea-9a14-dca0bb5939a8.png">

Minimal reproduction: https://github.com/mrseanbaines/gatsby-storybook-static-query

Also opened an issue with Storybook: https://github.com/storybookjs/storybook/issues/12061

### Steps to reproduce

1. Clone the repo (`git@github.com:mrseanbaines/gatsby-storybook-static-query.git`)
2. Run Storybook (`yarn storybook`)

### Expected result

The components should render

### Actual result

I get errors instead

### Environment

Using `gatsby-source-prismic-graphql` to source data. Also happens with `@prismicio/gatsby-source-prismic-graphql`.

```sh
  System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.17.0 - ~/.nvm/versions/node/v12.17.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.17.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 79.0
    Safari: 13.1.2
  npmPackages:
    gatsby: 2.24.43 => 2.24.43 
    gatsby-source-prismic-graphql: 3.6.2 => 3.6.2 
```

**Comment by mrseanbaines** [comment] 2020-08-15 14:32
**Update:** I've just made the minimal reproduction even more minimal and tried removing any use of Prismic and only querying data from the `siteMetadata` and I'm still getting the same results. Updated _all_ of the packages to the latest versions and also added a version of the stories using the new [CSF format](https://storybook.js.org/docs/react/api/csf) but again, same results. Made a branch with these changes [here](https://github.com/mrseanbaines/gatsby-storybook-static-query/tree/no-prismic).

**Comment by mrseanbaines** [comment] 2020-08-16 13:25
Also tried removing usage of TypeScript but still doesn't work

https://github.com/mrseanbaines/gatsby-storybook-static-query/tree/no-typescript

**Comment by botteu** [comment] 2020-08-18 15:39
I have the same problem. Although sometimes it works which is weird and leads me to think there's some kind of caching issue?

**Comment by IsaiahByDayah** [comment] 2020-09-11 19:05
Running into this issue as well. Followed the gatsby guides to get Storybook running (v5), but it seemed to be working for Storybook v6 until I tried making a story that uses StaticQueries. Could it be that with Storybook v6 a change is needed for `babel-plugin-remove-graphql-queries` usage?

**Comment by LekoArts** [comment] 2020-09-21 08:05
I'll close this as a duplicate of https://github.com/gatsbyjs/gatsby/issues/26099 so that we can discuss this in a single space.

**Closed by LekoArts** 2020-09-21 08:05 UTC
Labels: status: inkteam assigned, topic: StaticQuery, type: bug
