### ISSUE TITLE
[plugin-postcss] v2 postcss plugin causes build (but not develop) to fail

### ISSUE THREAD

**Issue by seaneking** [gatsbyjs/gatsby#6880] opened 2018-07-31 04:40 UTC
## Description

Including the new `gatsby-plugin-postcss` plugin in a v2 site is causing prod build to fail, but dev mode works fine. 

```sh
  28 | // Run the specified API in any plugins that have implemented it
  29 | module.exports = (api, args, defaultReturn) => {
> 30 |   if (!apis[api]) {
     |        ^
  31 |     console.log(`This API doesn't exist`, api)
  32 |   }
  33 |

  WebpackError: ./src/components/.../styles.module.css

 - api-runner-ssr.js:30 childCompiler.runAsChild
    lib/.cache/api-runner-ssr.js:30:8

  ...
```

### Steps to reproduce

Include `gatsby-plugin-postcss` and try to build site.

### Expected result

Should work the same as develop build.

### Actual result

Production build breaks when compiling HTML.

### Environment

```sh
System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.5.1 - /usr/local/bin/zsh
  Binaries:
    Node: 9.0.0 - /usr/local/bin/node
    npm: 6.2.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 60.0.1
    Safari: 11.1.2
  npmPackages:
    gatsby: next => 2.0.0-beta.61
    gatsby-image: next => 2.0.0-beta.7
    gatsby-plugin-manifest: next => 2.0.2-beta.3
    gatsby-plugin-netlify: next => 2.0.0-beta.4
    gatsby-plugin-nprogress: next => 2.0.0-beta.4
    gatsby-plugin-offline: next => 2.0.0-beta.5
    gatsby-plugin-postcss: ^1.0.0 => 1.0.0
    gatsby-plugin-react-css-modules: next => 2.0.0-beta.4
    gatsby-plugin-react-helmet: next => 3.0.0-beta.4
    gatsby-plugin-segment: latest => 1.0.2
    gatsby-plugin-sharp: next => 2.0.0-beta.7
    gatsby-plugin-sitemap: next => 2.0.0-beta.3
    gatsby-plugin-svgr: github:coreyward/gatsby-plugin-svgr#gatsby2-compatibility => 1.0.0
    gatsby-source-prismic: next => 2.0.0-alpha.2
    gatsby-transformer-sharp: next => 2.1.1-beta.6
  npmGlobalPackages:
    gatsby-cli: 1.1.58
    gatsby-plugin-react-css-modules: 2.0.0-beta.1
```

**Comment by Chuloo** [comment] 2018-08-02 22:32
Hi @seaneking, following your steps, I couldn't reproduce your error. Here's a [simple reproduction](https://github.com/Chuloo/postcss-6880) code with the hello-world starter and using `gatsby-plugin-postcss`. 
Upgrade to the latest Gatsby version and see if it persists. 👍

**Comment by seaneking** [comment] 2018-08-03 03:34
@KyleAMathews sure thing, WIP migration here: https://github.com/littleplanetcreative/littleplanetcreative.com/tree/gatsby-v2

**Comment by andrewn** [comment] 2018-08-03 16:00
I'm also seeing this issue. Here's an [minimal gatsby project showing this issue](https://github.com/andrewn/gatsby-postcss-fail) (`^2.0.0-beta.67`) with `gatsby-plugin-postcss`.

`npm run develop` loads the index page with the big "Heading" styles from `index.module.css` as expected.

`npm run build` fails with the error:

> `WebpackError: ./src/components/Heading/index.module.css`

The [full terminal output is here](https://gist.github.com/andrewn/7ef28ec0f35305cf8473874cee9d9155).

Hope that helps and let me know if there's anything I can do to help get this fixed.

**Comment by youngboy** [comment] 2018-08-03 18:09
I was trying to lookup the problem ...

only thing I dig so far is that webpack error(it is swallow by createErrorFromString ...) 
```
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
TypeError: this[NS] is not a function
    at childCompiler.runAsChild (/Users/yanghaku/github/gatsby-postcss-fail/node_modules/mini-css-extract-plugin/dist/loader.js:148:15)
    at compile (/Users/yanghaku/github/gatsby-postcss-fail/node_modules/webpack/lib/Compiler.js:296:11)
    at hooks.afterCompile.callAsync.err (/Users/yanghaku/github/gatsby-postcss-fail/node_modules/webpack/lib/Compiler.js:553:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/yanghaku/github/gatsby-postcss-fail/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:24:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/yanghaku/github/gatsby-postcss-fail/node_modules/tapable/lib/Hook.js:35:21)
    at compilation.seal.err (/Users/yanghaku/github/gatsby-postcss-fail/node_modules/webpack/lib/Compiler.js:550:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/yanghaku/github/gatsby-postcss-fail/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/yanghaku/github/gatsby-postcss-fail/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeAssets.callAsync.err (/Users/yanghaku/github/gatsby-postcss-fail/node_modules/webpack/lib/Compilation.js:1284:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/yanghaku/github/gatsby-postcss-fail/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/yanghaku/github/gatsby-postcss-fail/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.optimizeChunkAssets.callAsync.err (/Users/yanghaku/github/gatsby-postcss-fail/node_modules/webpack/lib/Compilation.js:1275:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/yanghaku/github/gatsby-postcss-fail/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/yanghaku/github/gatsby-postcss-fail/node_modules/tapable/lib/Hook.js:35:21)
    at hooks.additionalAssets.callAsync.err (/Users/yanghaku/github/gatsby-postcss-fail/node_modules/webpack/lib/Compilation.js:1270:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/yanghaku/github/gatsby-postcss-fail/node_modules/tapable/lib/HookCodeFactory.js:24:12), <anonymous>:6:1)
 @ ./src/components/Heading/index.js 2:0-40 5:13-19
 @ ./src/pages/index.js
 @ ./.cache/sync-requires.js
 @ ./.cache/static-entry.js
```

after little googling, I think the bug might need to wait `mini-css-extract-plugin` or `html-webpack-plugin` to fix ..

**Comment by youngboy** [comment] 2018-08-03 18:34
Off topic, I think the webpack error isn't much useful now, also see https://github.com/gatsbyjs/gatsby/issues/6978

`gatsby-cli/lib/reporter/errors.js`'s function `createErrorFromString` in  is not worked as expect currently

according to its code 
```javascript
/**
 * Convert a stringified webpack compilation error back into
 * an Error instance so it can be formatted properly
 * @param {string} errorStr
 */


function createErrorFromString(errorStr = ``, sourceMapFile) {
  let _errorStr$split = errorStr.split(/\r\n|[\n\r]/g),
      message = _errorStr$split[0],
      rest = _errorStr$split.slice(1); // pull the message from the first line then remove the `Error:` prefix
  // FIXME: when https://github.com/AriaMinaei/pretty-error/pull/49 is merged


  message = message.replace(/^(Error:)/, ``);
  let error = new Error(message);
  error.stack = [message, rest.join(`\n`)].join(`\n`);
  error.name = `WebpackError`;

  try {
    if (sourceMapFile) prepareStackTrace(error, sourceMapFile);
  } catch (err) {// don't shadow a real error because of a parsing issue
  }

  return error;
}
```

the PR url mentioned in fixme is already merged  https://github.com/AriaMinaei/pretty-error/pull/49

so change this function to
```javascript
function createErrorFromString(errorStr = ``, sourceMapFile) {

  const pe = new PrettyError();
  const error = pe.render(new Error(errorStr));
  error.name = `WebpackError`;
  try {
    if (sourceMapFile) prepareStackTrace(error, sourceMapFile);
  } catch (err) {// don't shadow a real error because of a parsing issue
  }

  return error;
}
```
is much much useful here.

**Comment by youngboy** [comment] 2018-08-04 02:33
@seaneking @andrewn I spent so much time to debugging this ... turn out your gatsby-plugin-postcss plugin version is still in v1....... 😂😂😂😂😂

run following command and your error goes away 
```javascript
yarn upgrade gatsby-plugin-postcss@2.0.0-beta.2
```

the real reason behind this is that v1's gatsby-plugin-postcss  include `mini-css-extract-plugin` in server side rendering mode, and its requiring add `MiniCssExtractPlugin` to webpack plugin ...

**Comment by andrewn** [comment] 2018-08-04 06:41
🤦‍♂️ 🤦‍♂️ 🤦‍♂️  I'm *so* sorry about this @youngboy. You're completely right. Upgrading to `gatsby-plugin-postcss@2.0.0-beta.2` works perfectly.

Thanks so much for figuring this out!

**Comment by KyleAMathews** [comment] 2018-08-04 15:33
Thanks everyone for working together on this!

**Closed by KyleAMathews** 2018-08-04 15:33 UTC
Labels: 📍 status: needs more info
