### ISSUE TITLE
gatsby-plugin-sharp@2.3.0 slows down build performance considerably 

### ISSUE THREAD

**Issue by janicduplessis** [gatsbyjs/gatsby#19572] opened 2019-11-17 17:47 UTC
## Description

Since updating gatsby-plugin-sharp to 2.3.0 I'm seeing build timeouts on netlify. The slowdown seems to happen during fetching query for pages (I'm using source-graphql to fetch data from an external graphql api). Instead of going through all the queries rapidly it seems to pause every ~20 queries for a few seconds then resume.

Here are the relevent build logs with 2.2.x

```
success Building production JavaScript and CSS bundles - 55.021s
success Rewriting compilation hashes - 0.003s
success run queries - 154.600s - 1632/1632 10.56/s
success Building static HTML for pages - 36.473s - 1631/1631 44.72/s
```

2.3.0

```
success Building production JavaScript and CSS bundles - 54.488s
success Rewriting compilation hashes - 0.003s
success run queries - 581.536s - 1632/1632 2.81/s
 [================---------] 1695/2697 67.6 s 62% Generating image thumbnails
gave up lol
```

### Steps to reproduce

Run a production build in a project with 1k+ pages with `2.3.0`

### Expected result

run queries step takes ~150s

### Actual result

run queries step takes ~580s

### Environment

  System:
    OS: macOS 10.15
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.12.0 - /var/folders/dj/vrrkmv_s2mj85d4h4q_z2r640000gn/T/yarn--1574012283287-0.34050389663062397/node
    Yarn: 1.19.0 - /var/folders/dj/vrrkmv_s2mj85d4h4q_z2r640000gn/T/yarn--1574012283287-0.34050389663062397/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.36
    Firefox: 63.0.3
  npmGlobalPackages:
    gatsby-cli: 2.4.4
    gatsby-dev-cli: 2.4.8

**Comment by janicduplessis** [comment] 2019-11-17 17:47
Looking at the commit log it is probably related to https://github.com/gatsbyjs/gatsby/commit/24feca0417231a218044348333f1458fe8442849

cc @wardpeet

**Comment by LekoArts** [comment] 2019-11-18 09:21
This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/19576

**Closed by LekoArts** 2019-11-18 09:21 UTC
