### ISSUE TITLE
Gatsby build failed:  ERROR #98123  WEBPACK  Generating JavaScript bundles failed

### ISSUE THREAD

**Issue by JayMGurav** [gatsbyjs/gatsby#22755] opened 2020-04-02 11:38 UTC
## Description
Gatsby build is throwing error 
 ERROR #98123  WEBPACK
Generating JavaScript bundles failed
Can't resolve '..\..\public\static\d\3978990474.json' in 'F:\projects\gatsby\src\hooks'
File: src\hooks\use-sitemetadata.js

### Steps to reproduce
**use-posts**
![use-posts](https://user-images.githubusercontent.com/42145480/78243591-aca2f800-7501-11ea-998a-ec9cfb88bdb8.jpg)
![use-posts2](https://user-images.githubusercontent.com/42145480/78243651-c5aba900-7501-11ea-98fa-4741d29cbcfb.jpg)

**use-sitemetadata.js**
![sitemetadata](https://user-images.githubusercontent.com/42145480/78243776-fc81bf00-7501-11ea-9918-708062cd2727.jpg)

**profile.js**
![profile1](https://user-images.githubusercontent.com/42145480/78244874-16bc9c80-7504-11ea-9a8a-5f2e32af517f.jpg)
![profile2](https://user-images.githubusercontent.com/42145480/78244888-18866000-7504-11ea-8955-ec317197e8ab.jpg)

### Expected result
successful build

### Actual result

![gatsby build](https://user-images.githubusercontent.com/42145480/78243122-cee84600-7500-11ea-9a59-6f6a342ceb5d.jpg)

### Environment

"gatsby": "^2.20.4",
node : v12.13.1

**Comment by Js-Brecht** [comment] 2020-04-03 23:03
Well that's definitely odd.  Can you share a [minimal reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/)?  It would help immensely to be able to see this in action.

**Comment by JayMGurav** [comment] 2020-04-04 08:06
I certainly couldn't figure out what the error or problem was, cleaned build files and tried to build locally again it was successful but when I tried the same thing on Netlify it failed with the same errors....then I completely made a new directory and pasted the same code, configuration and tried it with new repository on my GitHub , it worked without any error -still can't figure out what was the issue.....

**not working**
here is my older repo : https://github.com/JayMGurav/Myblog 

**working**
and a newer one : https://github.com/JayMGurav/blog

**Comment by Js-Brecht** [comment] 2020-04-04 08:16
In your older repo: I'm not seeing the static query chunk issues, but I do see some things that would definitely cause a Netlify build to break.  There are files and directories with case issues.

`src/pages/index.js` imports `../components/profile.js`, but the file is actually `src/components/Profile.js`.  Same thing in `src/templates/post.js`.

`src/components/modeBtn.js` imports `../theme/themeContext`, but it is actually `../Theme/themeContext`.  A lot of components import that one wrong.

I see in your newer repo all of the file/folder casing is correct, so it looks like you've already fixed the problem.  Would you say that your issue is resolved?

**Comment by JayMGurav** [comment] 2020-04-05 06:01
yeh...I have it working, apart from the case issues and some small issues which I learned and solved later, I don't know what the above mentioned build errors were they occurred to me 3-4 times I just went on cleaning the cache and build files....and rebuild every time, mystically didn't get any of the issues any more..Thank you for your follow-up though.

**Comment by Js-Brecht** [comment] 2020-04-05 06:24
Okay, I'm going to go ahead and close this now.  Please comment again if you have any questions!

**Closed by Js-Brecht** 2020-04-05 06:24 UTC

**Comment by Js-Brecht** [comment] 2020-04-05 20:22
Hey @JayMGurav, just wanted to follow up a bit on your OP.

I just cloned a reproduction repository and noticed the same kind of error you were getting originally, about it not finding `../../public/static/d/...`, which are the static query data chunks.  What I noticed right away about this repo is that they had committed their `.cache` directory.

I'm not 100% on this, but what I _**think**_ is happening is that Gatsby is looking in `.cache`, and seeing that these queries have already been resolved according to the cached Redux state.  Since it sees those queries have already been resolved, it doesn't try to do it again; which also means that it **expects** to find the results in the `public/static/d` directory.  Since the `public` directory wasn't committed to the repo, they were, in fact, missing.  Running `gatsby clean` completely clears up the error.

This is one reason that `gatsby clean` will delete **both** the `.cache` and the `public` directories at the same time.  `public` can exist without `.cache`, but `.cache` cannot exist without `public`, unless it is a new instance and it's building everything up from scratch.  If the `.cache` directory is committed to the repo, so should the `public`.

Does this fit your scenario?

**Comment by probablyup** [comment] 2020-07-16 02:28
@Js-Brecht Why is gatsby relying on anything inside the _public_ folder for compilation?

**Comment by Js-Brecht** [comment] 2020-07-16 03:26
@probablyup because that's where the data is; this is the same data you get in the browser to run your app.  During SSR, Gatsby is running the same code that gets run in the browser, so it makes sense for the resources it needs to be in `public`.

**Comment by probablyup** [comment] 2020-07-16 03:32
Yes understood, but why does the _build_ need `public`. It should be _creating_ `public`

**Comment by Js-Brecht** [comment] 2020-07-16 04:20
The build (bootstrap in this case) doesn't _need_ `public`, precisely, but it does do some things to try to save time & resources; there are some cases where it will try not to recreate everything that already exists, and `.cache` is the source of truth for that.

Pretty sure that this particular issue is a result of one of those cases.  I say "pretty sure" because I haven't actually examined the code for the caching of static queries very closely, so I'm just making an educated guess based on the rest of what I know about Gatsby, and the behavior in this issue.

Overall, the caching strategy is an effort to save time & resources...  There are some sites that are massive, and the cost in time alone adds up pretty quick.  There's a great deal of data that doesn't change all the time, so costs of regenerating it on every build can get pretty crazy, especially if your build takes a lot of time.

Imagine a site that has hundreds of images.  If each image gets hit by `sharp` 6-7 times to cover various circumstances, it could quickly add up to thousands of images generated.  That is a very expensive process; very time consuming.  The fact that you can build one time and it takes forever, then build again and it's quick, is a direct result of using the data that was generated by previous builds.

But always, the cache is invalidated based on what it finds in `.cache`.  If Gatsby looks at `.cache` and it says that changes don't need to be made, then changes won't be made.  There are some cases where it looks at `public` as a secondary source, like it does with images; but that's always secondary to the data in `.cache`.

Because of this, if you've deleted `public` and `.cache` still thinks it exists, then there will be problems :man_shrugging:.  I guess a different way you could do it would be to maintain a separate directory for everything that usually goes in public, then copy it all over... but then you have all the same time it took before, plus the time it takes to copy everything over.  Seems to make sense to just put it all in `public`.

Of course, if you have a better idea in mind, IME the Gatsby team is always open for input & feedback.  Perhaps they'd accept an RFC for a new caching strategy.

I'm not exactly the best person to talk to about the reasons behind a lot of things in Gatsby.  I only know what I know because I've spent a great deal of time elbow deep in the codebase; analyzing the code, writing some of it, and reading the (public) conversations.  I'm not a member of the core team, though, so I don't make driving decisions. Nor am I privy to the decision making process in most cases, so there's a whole lot that I don't know.

**Comment by probablyup** [comment] 2020-07-16 14:24
@pieh maybe you can weigh in on this? In my opinion everything needed to create a build should either be made fresh or stored in `.cache` and copied over. There should never be a time where the _compilation_ process references a compiled target as a source because that breaks idempotent builds.

**Comment by pieh** [comment] 2020-07-16 14:36
> Yes understood, but why does the _build_ need `public`? It should be _creating_ `public`.

There are some build artefacts (some of which are used as both intermediate - needed for some part of build and final ones used later on when deployed) that Gatsby will assume are there on next builds unchanged and if they don't need to be rebuild because of some input changes, Gatsby will not rebuild them assuming they are still there. This is why `gatsby clean` clears both `.cache` and `public` and not just one of those. Right now they are stored just in `public` but I can see that we could switch it to store them always in `.cache` and then copy back to public or adding some checks to verify that assets we assume to be there (based on state of last build) are actually still there

**Comment by probablyup** [comment] 2020-07-16 14:37
> Right now they are stored just in public but I can see that we could switch it to store them always in .cache and then copy back to public or adding some checks to verify that assets we assume to be there (based on state of last build) are actually still there

This sounds like a better strategy that's less surprising and should be more fault-tolerant.

**Comment by dowi** [comment] 2020-08-08 08:58
This error happened to me after I manually deleted the public folder. 
After reading this thread, I used "gatsby clean" and then build was successful.

**Comment by 13rac1** [comment] 2020-10-16 21:35
Similar error on a local project after some minor updates. `rm -rf public` didn't fix it. `rm -rf .cache` did.

**Comment by infinitbility** [comment] 2021-03-31 17:49
gatsby build generating javaScript bundles failed issue solution

https://infinitbility.com/gatsby-build-generating-javascript-bundles-failed
