### ISSUE TITLE
Build fails on fresh Gatsby starter with gatsby-plugin-sitemap

### ISSUE THREAD

**Issue by cafca** [gatsbyjs/gatsby#31944] opened 2021-06-16 13:09 UTC
## Description

Running `gatsby build` or `npm run build` fails right after creating a fresh site using `gatsby-cli new` and the sitemap plugin. There is no specific documentation on additional required steps in the tutorial or build output.

### Steps to reproduce

1. Run `npx gatsby-cli new`
2. Select options
  - no cms
  - no styling system
  - add an automatic sitemap
3. Observe a success message "Your new Gatsby site has been successfully created"
4. Run `npm run build`

### Expected result

The build either succeeds or I am notified about any additional steps required after creating a fresh site at the end of `gatsby-cli new`.

### Actual result

An error message

```
> npm run build                                                                                                    15:07:21

> test@1.0.0 build /Users/work/code/test
> gatsby build

success open and validate gatsby-configs - 0.050s
success load plugins - 0.185s
success onPreInit - 0.024s
success initialize cache - 0.007s
success copy gatsby files - 0.119s
success Compiling Gatsby Functions - 0.492s
success onPreBootstrap - 0.512s
success createSchemaCustomization - 0.002s
success Checking for changed pages - 0.001s
success source and transform nodes - 0.030s
success building schema - 0.242s
success createPages - 0.001s
success createPagesStatefully - 0.034s
info Total nodes: 24, SitePage nodes: 3 (use --verbose for breakdown)
success Checking for changed pages - 0.001s
success update schema - 0.038s
success onPreExtractQueries - 0.001s
success extract queries from components - 0.097s
success write out redirect data - 0.002s
success onPostBootstrap - 0.001s
info bootstrap finished - 4.598s
success run page queries - 0.009s - 3/3 328.96/s
success write out requires - 0.006s
success Building production JavaScript and CSS bundles - 5.073s
success Rewriting compilation hashes - 0.002s
success Building HTML renderer - 0.791s
success Building static HTML for pages - 0.114s - 3/3 26.29/s

 ERROR #11321  PLUGIN

"gatsby-plugin-sitemap" threw an error while running the onPostBuild lifecycle:

Page array from `query` wasn't found at `data.allSitePage.nodes`.
      Fix the custom query or provide a custom `resolvePages` function.
      https://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap/#api-reference


  46 |             queryRecords = _yield$graphql.data;
  47 |             _context.next = 8;
> 48 |             return Promise.resolve(resolvePages(queryRecords)).catch(function (err) {
     |                                    ^
  49 |               return reporter.panic(_internals.REPORTER_PREFIX + " Error resolving Pages", err);
  50 |             });
  51 |

File: node_modules/gatsby-plugin-sitemap/gatsby-node.js:48:36



  Error: Page array from `query` wasn't found at `data.allSitePage.nodes`.
        Fix the custom query or provide a custom `resolvePages` function.
        https://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap/#api-reference

  - internals.js:101 resolvePages
    [test]/[gatsby-plugin-sitemap]/internals.js:101:11

  - gatsby-node.js:48 _callee$
    [test]/[gatsby-plugin-sitemap]/gatsby-node.js:48:36


not finished onPostBuild - 0.081s

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! test@1.0.0 build: `gatsby build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the test@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/work/.npm/_logs/2021-06-16T13_07_36_292Z-debug.log
```

### Environment

```
> npx gatsby info --clipboard                                                                                      15:08:20

  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.4/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Safari: 14.1.1
  npmPackages:
    gatsby: ^3.6.2 => 3.7.2
    gatsby-plugin-sitemap: ^4.3.1 => 4.3.1
```

**Comment by LekoArts** [comment] 2021-06-16 13:15
Hi!

This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/31903

**Closed by LekoArts** 2021-06-16 13:15 UTC
Labels: type: bug

**Comment by cafca** [comment] 2021-06-16 14:29
Thanks. I missed that.
