### ISSUE TITLE
Issue to deploy on Netlify using gatsby-source-instagram

### ISSUE THREAD

**Issue by Regisnut** [gatsbyjs/gatsby#24780] opened 2020-06-04 15:03 UTC
## Description

I'm trying to deploy on Netlify but it has failed, showing me it can't query Instagram data whereas it's working on my local setup.
Here is the message from Netlify : Cannot query field "allInstaNode" on type "Query".
I try to remove, and install again the plugin but still not working when I 've tried to deploy.

### Steps to reproduce

I'm using plugin gatsby-source-instagram, and I have added the plugin to my gatsby.config.js file.

### Expected result

deploy

### Actual result

deploy failed

**Comment by diogocapela** [comment] 2020-06-05 00:30
I'm having the same problem as @Regisnut. The development and build instances both work locally but they fail when deployed on to Netlify. Here is the Netlify deploy error log:

```
1:13:09 AM: error There was an error in your GraphQL query:
1:13:09 AM: Cannot query field "allInstaNode" on type "Query".
1:13:09 AM: If you don't expect "allInstaNode" to exist on the type "Query" it is most likely a typo.
1:13:09 AM: However, if you expect "allInstaNode" to exist there are a couple of solutions to common problems:
1:13:09 AM: - If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
1:13:09 AM: - The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
1:13:09 AM: - You want to optionally use your field "allInstaNode" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")
1:13:09 AM: It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
1:13:09 AM: https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions
1:13:09 AM: failed extract queries from components - 0.220s
1:13:09 AM: npm
1:13:09 AM:  ERR! code ELIFECYCLE
1:13:09 AM: npm ERR!
1:13:09 AM:  errno 1
1:13:09 AM: npm ERR! jam-stack-boiler@0.0.1 build: `gatsby build`
1:13:09 AM: npm ERR! Exit status 1
1:13:09 AM: npm ERR!
1:13:09 AM: npm ERR! Failed at the jam-stack-boiler@0.0.1 build script.
1:13:09 AM: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
1:13:09 AM: npm
1:13:09 AM:  ERR! A complete log of this run can be found in:
1:13:09 AM: npm ERR!     /opt/buildhome/.npm/_logs/2020-06-05T00_13_09_340Z-debug.log
```

**Comment by kirstenjvd** [comment] 2020-06-05 02:58
I'm having the same issue, and have found duplicate issues posted on Netlify, and gatsby-source-instagram but haven't seen a solution anywhere.

**Comment by alexadark** [comment] 2020-06-05 06:17
I have the same issue on netlify and gatsby cloud
it has been working in the beginning, then failed like that

**Comment by sjelfull** [comment] 2020-06-05 14:26
This is a known issue: https://github.com/oorestisime/gatsby-source-instagram/issues/24

I believe the only real solution at the moment is to create a Facebook app that is connected to the Instagram account in question: https://github.com/oorestisime/gatsby-source-instagram#instagram-graph-api-token

**Comment by Regisnut** [comment] 2020-06-05 14:51
thanks @sjelfull I will take a look if it can help me. still no reply from  @ascorbic .

**Comment by ascorbic** [comment] 2020-06-05 15:11
Hi. As this seems to be an issue with gatsby-source-instagram, which is a community plugin, I'm going to close this issue. Your best bet is to continue to work with [the active issue](https://github.com/oorestisime/gatsby-source-instagram/issues/24) on the plugin's repo. Thanks @sjelfull for highlighting this.

**Closed by ascorbic** 2020-06-05 15:11 UTC
Labels: status: needs reproduction

**Comment by oorestisime** [comment] 2020-06-05 15:18
For anyone landing here public scraping method no longer works on infras such as Netlify, Amplify Gatsby Cloud because instagram started adding login screens :/

Best solution right now is use the graph api method of the plugin. seems instructions are a bit outdated or confusing so please help me get them straight. I have my token for 2 years so i haven't gone through them recently!

**Comment by sjelfull** [comment] 2020-06-05 15:20
@oorestisime Thanks for the summary.

Yes, I'm right in the middle of muddling trough getting a token, and i'm struggling.

**Comment by wadebarrie** [comment] 2021-01-19 01:40
> Update the package to latest version, apply usernameID as a number in gatsby-config and it works for me on Netlify.

I have my gatsby-config set up like this but it still fails when I try to deploy to netlify

**Comment by johnthealy3** [comment] 2021-01-19 21:50
Same as many others, I'm having this problem only on deploying to Netlify, and only some of the time. The frustrating bit is that the plugin actually still works as intended once deployed, even without using the Graph API, it just can't get through the deploy process. Really at a loss here.

**Comment by oorestisime** [comment] 2021-01-20 08:30
Hey folks sorry I havent had time to look yet, but 

1. lets not pollute gatsby issues with this. its unrelated. there's a specific issue on the plugin to talk
2. it seems another login wall was added if the public scraping fails again

**Comment by nemethricsi** [comment] 2021-03-22 20:29
> Same as many others, I'm having this problem only on deploying to Netlify, and only some of the time. The frustrating bit is that the plugin actually still works as intended once deployed, even without using the Graph API, it just can't get through the deploy process. Really at a loss here.

I confirm: sometimes it works... weird 😒
