### ISSUE TITLE
[gatsby-remark-mdx] remark plugin API doesn't match original gatsby-transformer-remark API

### ISSUE THREAD

**Issue by Exmirai** [gatsbyjs/gatsby#37609] opened 2023-02-02 16:53 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

https://www.npmjs.com/package/gatsby-remark-images-remote this plugin not working with gatsby-plugin-mdx because it requires 'actions', 'createNodeid' etc object to be available which is not provided by gatsby-plugin-mdx
This is only available imports to "gatsbyRemarkPlugins" plugin collection
Here is  imports which gatsby-plugin-mdx provides: 
https://github.com/gatsbyjs/gatsby/blob/65739fcc1af12d0f878820a589de7dde5964b93d/packages/gatsby-plugin-mdx/src/get-source-plugins-as-remark-plugins.ts#L15

### Reproduction Link

Too simple to setup repro sandbox

### Steps to Reproduce

1. add 'gatsby-remark-images-remote' to 'gatsbyRemarkPlugins' list of 'gatsby-plugin-mdx'

### Expected Result

images processeed with gatsby-plugin-sharp

### Actual Result

![image](https://user-images.githubusercontent.com/6436703/216387293-092df74d-8ae4-46b8-8c10-fc849b7e46cb.png)

### Environment

```shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx
  Binaries:
    Node: 14.21.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.17 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.11.0
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (109.0.1518.61)
  npmPackages:
    gatsby: ^4.24.8 => 4.25.4
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5
    gatsby-plugin-eslint: ^4.0.2 => 4.0.3
    gatsby-plugin-fresnel: ^1.0.1 => 1.1.0
    gatsby-plugin-google-analytics: ^3.13.0 => 3.15.0
    gatsby-plugin-google-gtag: ^4 => 4.25.0
    gatsby-plugin-image: ^2 => 2.25.0
    gatsby-plugin-iubenda-cookie-footer: ^1.4.0 => 1.4.0
    gatsby-plugin-manifest: ^4 => 4.25.0
    gatsby-plugin-mdx: ^4.4.0 => 4.4.0
    gatsby-plugin-minify-html: ^1.0.4 => 1.0.4
    gatsby-plugin-postcss: ^5 => 5.25.0
    gatsby-plugin-react-helmet: ^5 => 5.25.0
    gatsby-plugin-remote-images: ^3.4.0 => 3.5.0
    gatsby-plugin-root-import: ^2.0.7 => 2.0.9
    gatsby-plugin-sass: ^5 => 5.25.0
    gatsby-plugin-sharp: ^4 => 4.25.0
    gatsby-plugin-split-css: ^2.0.2 => 2.0.3
    gatsby-plugin-svgr-loader: ^0.1.0 => 0.1.0
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.27 => 1.1.30
    gatsby-remark-component: ^1.1.3 => 1.1.3
    gatsby-remark-hard-breaks: ^1.0.0 => 1.0.0
    gatsby-remark-images-remote: ^2.1.1 => 2.1.1
    gatsby-source-custom-api: ^2.3.6 => 2.3.6
    gatsby-source-filesystem: ^4 => 4.25.0
    gatsby-transformer-json: ^4 => 4.25.0
    gatsby-transformer-remark: ^5 => 5.25.1
    gatsby-transformer-sharp: ^4 => 4.25.0
```

**Comment by LekoArts** [comment] 2023-02-03 10:19
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by Peyu5h** [comment] 2023-02-04 17:22
To resolve this issue, you will need to use **gatsby-transformer-remark** instead of **gatsby-plugin-mdx**, as gatsby-transformer-remark provides the required actions and createNodeId objects.

_For example_:
To configure your gatsby-config.js file:

module.exports = {
  plugins: [
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [`gatsby-remark-images-remote`]
      }
    }
  ]
}

**Comment by Exmirai** [comment] 2023-02-08 17:15
But i need to use mdx markdown not md :) (i'm trying to move from md to mdx )

**Comment by LekoArts** [comment] 2023-02-20 07:32
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2023-02-20 07:32 UTC
Labels: type: bug, status: needs reproduction
