### ISSUE TITLE
Error when running `gatsby serve`

### ISSUE THREAD

**Issue by nratter** [gatsbyjs/gatsby#5184] opened 2018-04-29 19:11 UTC
## Description

Error thrown when running `gatsby serve`

### Steps to reproduce

Run `gatsby serve` after running `gatsby build`

### Expected result

Expect to work.

### Actual result

```
/Users/nratter/Development/jw.com-gatsby/node_modules/serve/bin/serve.js:83
detect(port).then(async open => {
                  ^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
```

### Environment

* Gatsby version: 1.9.253
* gatsby-cli version: 1.1.51
* Node.js version: 6.11.0
* Operating System: Mac OS 10.11.6

**Comment by KyleAMathews** [comment] 2018-04-29 19:14
Hmm looks like serve, the package that we use for serving sites, isn't supporting node 6 anymore.

**Comment by KyleAMathews** [comment] 2018-04-29 19:15
Yeah, they changed things recently https://github.com/zeit/serve/issues/349

**Comment by alexito4** [comment] 2018-06-14 18:04
It seems that this was fixed in serve's side https://github.com/zeit/serve/issues/349#issuecomment-388971661
Is there anything that needs to be updated in gatsby? It's still crashing for me.

**Comment by serendipitist** [comment] 2018-07-03 13:29
Is this working ? How to fix it

**Comment by dandaka** [comment] 2018-07-16 10:21
I can confirm this bug

Gatsby: 2.0.0-beta.36
gatsby-cli: 1.1.58
Node.js: v6.11.2
OS: MacOS 10.11.6

**Comment by KyleAMathews** [comment] 2018-08-08 09:49
Fixed by https://github.com/gatsbyjs/gatsby/pull/7139

**Closed by KyleAMathews** 2018-08-08 09:49 UTC
Labels: 🏷 type: bug, 📍 status: blocked
