### ISSUE TITLE
Webpack Error, static-entry: transpile

### ISSUE THREAD

**Issue by yasserzubair** [gatsbyjs/gatsby#2427] opened 2017-10-12 10:39 UTC
Hi there,
Whenever I try to build, I am getting this error. Can anyone please tell me whats it related to and how can I get rid of it.

`
> 1 | import React from "react"
    | ^
  2 | import { renderToString, renderToStaticMarkup } from "react-dom/server"
  3 | import { StaticRouter, Route, withRouter } from "react-router-dom"
  4 | import { kebabCase, get, merge, isArray, isString } from "lodash"

  WebpackError:

  - static-entry.js:1 transpile
    .cache/static-entry.js:1:1

  - static-entry.js:7
    .cache/static-entry.js:7:1

  - React.js:82 FSReqWrap.readFileAfterOpen [as oncomplete]
    ~/react/lib/React.js:82:1`

**Comment by KyleAMathews** [comment] 2017-10-12 18:45
Does this happen in the default starter?

**Comment by halloween603** [comment] 2017-10-14 05:20
Hi there,
I am also getting the same error.
Yeah it is happening in the default starter.

**Comment by halloween603** [comment] 2017-10-27 05:39
Hi,
I am also getting the same error while building. can anyone help me out to get rid of it.
Yeah it is happening in default starter only.

**Comment by hirviid** [comment] 2017-11-27 08:03
@yasserzubair @halloween603 Did you find the cause / solution for this?

**Comment by DarrylD** [comment] 2017-11-29 21:08
I'm getting the same error out of nowhere. Any idea what It would be?

**Comment by arnondora** [comment] 2017-12-25 19:08
I also got this error. Is there any solution?

**Comment by Metturan** [comment] 2018-01-12 14:46
Hi,

have this same error, can't build or deploy. Any solution for this?

**Comment by arnondora** [comment] 2018-01-12 19:05
I have no `.babelrc` in any directory in my project. For me, it might from something else?

**Comment by apnerve** [comment] 2018-01-12 20:42
@arnondora Are you also getting "Webpack Error"?

**Comment by arnondora** [comment] 2018-01-13 05:15
Yes, I also got webpack error. Now, the problem is gone but I don’t know why. I just re-build project again and again.

**Comment by alexmacarthur** [comment] 2018-01-18 03:22
Having this same issue as well. Anyone have any ideas?

**Comment by Redmega** [comment] 2018-01-25 02:33
Facing this same issue, no `.babelrc` here.

**Comment by Redmega** [comment] 2018-01-25 03:15
Mine looks a bit different, probably because of the newer gatsby version:

```
1 | import React from "react"
    | ^
  2 | import { renderToStaticMarkup } from "react-dom/server"
  3 | import { merge } from "lodash"
  4 | import apiRunner from "./api-runner-ssr"


  WebpackError:

  - develop-static-entry.js:1 transpile
    .cache/develop-static-entry.js:1:1

  - develop-static-entry.js:7
    .cache/develop-static-entry.js:7:1
```

**Comment by arnondora** [comment] 2018-01-25 06:15
Sometime I just remove some of graphql query in the `gatsby-node.js` And build, it worked.  Then I just add the part that has removed and build again, it also work. I still don’t know why this problem happened.

**Comment by Redmega** [comment] 2018-01-25 16:43
In my case it ended up being a syntax error that eslint wasn't alerting me to for some reason. I had a missing ] in my `typography.js`. Run your code through eslint and make sure there are no errors

**Comment by yasserzubair** [comment] 2018-01-28 10:27
Mine also ended up being a syntax error.

**Comment by grundmanise** [comment] 2018-02-03 21:05
same for me.. it was a syntax error.

**Comment by alexmacarthur** [comment] 2018-02-05 00:56
Same here -- syntax error. Specifically, I had some JSON-LD structured data I was outputting inside of `<Helmet></Helmet> tags. Just missing a comma, but wasn't notified clear of that in my terminal.

**Comment by elrumordelaluz** [comment] 2018-02-05 17:58
In case could be useful for someone having this issue, in my case was using `yeld` inside a function not declared as _generator_ so without `*`, adding it solved this issue.

**Comment by hogyun3709** [comment] 2018-02-11 13:25
Hi I have got a simple solution for this error which is replacing "gatsby-config.js" file name to "gatsby.config.js". Try this :)

**Comment by KyleAMathews** [comment] 2018-09-08 04:12
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Closed by KyleAMathews** 2018-09-08 04:12 UTC

**Comment by JustFly1984** [comment] 2019-06-24 13:00
I got this error then updating gatsby from 2.5.3 to 2.10.0
