### ISSUE TITLE
Hot reload of markdown files not working

### ISSUE THREAD

**Issue by rcoedo** [gatsbyjs/gatsby#94] opened 2015-11-26 09:46 UTC
I just installed gatsby for the first time and followed the examples found [here](https://www.npmjs.com/package/gatsby). The page loads but when I make some changes to one of the markdown files I need to manually reload the page.

It seems to be some kind of CORS problem.

```
XMLHttpRequest cannot load http://0.0.0.0:1418/info?t=1448531803680. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access. The response had HTTP status code 404.
```

Thanks for such a nice tool!

**Comment by KyleAMathews** [comment] 2015-11-27 02:23
Oh CORS. I can confirm this on a fresh install of Gatsby in a Linux VM. Can't reproduce in my Mac install. Investigating...

**Comment by rcoedo** [comment] 2015-11-27 15:08
I'm using osx El Capitan and node 5.1.0 if that helps. I tried older versions of gatsby and older versions of node but I get the same behaviour.

**Comment by syrusakbary** [comment] 2015-11-28 20:37
@KyleAMathews I can reproduce this in OSX too :( `node v5.0.0`

**Comment by KyleAMathews** [comment] 2015-11-30 02:17
Ok, I can reproduce on my mac by deleting `node_modules` and reinstalling. Which suggests one of our lovely dependencies changed something...

**Comment by KyleAMathews** [comment] 2015-11-30 02:55
Arggg... it was this https://github.com/webpack/webpack-dev-server/pull/302

Downgrading webpack-dev-server to 1.12.1 fixed the problem... investigating further...

**Comment by KyleAMathews** [comment] 2015-11-30 03:00
Apparently a known problem https://github.com/webpack/webpack-dev-server/issues/326 and https://github.com/webpack/webpack-dev-server/pull/328 I'll release a new version of Gatsby downgrading webpack-dev-server and do a new release once https://github.com/webpack/webpack-dev-server/pull/328 is merged and I've confirmed it's fixed.

**Comment by KyleAMathews** [comment] 2015-11-30 03:03
Fixed in https://github.com/gatsbyjs/gatsby/commit/62fff69d1e81b5242d0ce89f1f52066926ffdac7

Released 0.7.3

**Closed by KyleAMathews** 2015-11-30 03:03 UTC

**Comment by rcoedo** [comment] 2015-11-30 09:25
Yay! thanks for the fix.

**Comment by SpaceK33z** [comment] 2016-01-16 14:29
@KyleAMathews, webpack-dev-server v1.14.1 has been released, which should fix the issue. It could be interesting to upgrade, since sockjs is much lighter than socket.io (doesn't have native build deps).
