### ISSUE TITLE
Gatsby's Component-level GraphQL Fetches only 10 Results for a One-to-many Relation

### ISSUE THREAD

**Issue by hsensh** [gatsbyjs/gatsby#27382] opened 2020-10-11 06:18 UTC
Hello, I wouldn't be posting this here had I found something but there is literally nothing I stumbled upon that implied it has happened to anybody else.

I am using Gatsby with the Strapi data source and everything was working perfectly following [this tutorial](https://strapi.io/blog/build-a-static-blog-with-gatsby-and-strapi)

I was attempting to query from a component with the following code:
````const data = useStaticQuery(graphql`
    query ContactQuery {
      allStrapiContact {
        nodes {
          email
          latitude
          longitude
          phone
          fax
          extensions {
            arabicName
            id
            name
            value
          }
        }
      }
    }
  `).allStrapiContact.nodes[0]````

The code was fetched but I noticed that only 10 results were returned for the extensions object when I had 12 in my Strapi database.

I tried to query the same thing using GraphiQL and I got 12 results instead of 10. Gatsby is fetching all of the results at startup but for some reason is limiting them upon direct request?

I hope someone could help. Thanks.

**Comment by herecydev** [comment] 2020-10-11 13:57
Not that I know of, one query I have for allNodes returns 300 results

**Comment by LekoArts** [comment] 2020-10-12 07:27
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by ascorbic** [comment] 2020-10-22 11:38
Hi. I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. Thanks!

**Closed by ascorbic** 2020-10-22 11:38 UTC
Labels: status: needs reproduction
