### ISSUE TITLE
Updating `gatsby-plugin-offline` breaks the site

### ISSUE THREAD

**Issue by josephmarkus** [gatsbyjs/gatsby#24225] opened 2020-05-19 15:20 UTC
## Description

Yesterday, I updated `gatsby-plugin-offline` from 2.2.6 to 3.2.2.

In `gatsby-config.js` the plugin is used with its default options, like so:

```
plugins: [
  ...
  'gatsby-plugin-offline',
  ...
],
```

Soon after deploy the website became unavailable after hard-refreshing the page.

In Chrome 81 it would say:

```
The site can't be reached

The web page at https://[REDACTED]/ might be temporarily down or it maye have moved permanently to a new web address.

ERR_FAILED
```

In Firefox 76 it would say

```
Oops.

The site at https://[REDACTED]/ has experienced a network protocol violation that cannot be repaired.

The page you are trying to view cannot be shown because an error in the data transmission was detected

Please contact the web site owners to inform them of this problem
```

In Safari 13 on iOS 13 it would say

```
Safari cannot open the page.

The error was: "FetchEvent.respondWith received an error: Returned response is null.".
```

On the back of this, I reverted the change, which fixed the issue, but that's only after clearing the site's cache.

In Chrome unregistering the worker (via DevTools > Application > Service Workers) and refreshing the page would not help. It would throw the same error. 

Only by going to DevTools > Application > Clear storage > Clear site data, then refreshing the page, would actually load the site.

In Safari on iOS refreshing the page wouldn't help, but almost 24 hours later, hitting refresh a couple of times finally reloaded the site.

I left Firefox cache as is. 24 hours later, refreshing the page throws the same error.

I was a bit surprised that with default configuration for `gatsby-offline-plugin`, the update of the plugin could cause this side effect.

I have some questions on the back of this:

- how can I prevent this happening in the future? Previewing this deploy didn't present the issue
- how can I set a way to essentially invalidate a Service Worker for users who still may be experiencing this? Does this have to happen at the CDN level as Service Worker is called before anything in the application itself? This is so different to just invalidating cache on a CDN. It's almost as if Service Worker itself has to have a mechanism to handle issues such as this
- are there best practices for monitoring service workers, so that any changes could be detected and dealt with more easily than just "it doesn't work for me"?

### Steps to reproduce

I upgraded `gatsby-plugin-offline` from 2.2.6 to 3.2.2

Locally this didn't present any issues.

The issue occured after deploy.

### Expected result

Application shouldn't break

### Actual result

After deploying the application, the website would not work.

### Environment

```
System:
  OS: macOS Mojave 10.14.6
  CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Shell: 5.3 - /bin/zsh
Binaries:
  Node: 12.16.1 - ~/.nvm/versions/node/v12.16.1/bin/node
  Yarn: 1.22.4 - /usr/local/bin/yarn
  npm: 6.13.4 - ~/.nvm/versions/node/v12.16.1/bin/npm
Languages:
  Python: 2.7.16 - /usr/bin/python
Browsers:
  Chrome: 81.0.4044.138
  Firefox: 76.0.1
  Safari: 13.1
npmPackages:
  gatsby: ~2.13.x => 2.13.64
  gatsby-background-image: ^0.8.0 => 0.8.3
  gatsby-image: ~2.1.x => 2.1.4
  gatsby-plugin-catch-links: ~2.3.1 => 2.3.1
  gatsby-plugin-emotion: ~2.0.5 => 2.0.7
  gatsby-plugin-favicon: ~3.1.5 => 3.1.6
  gatsby-plugin-google-gtag: ~2.1.1 => 2.1.1
  gatsby-plugin-manifest: ~2.2.x => 2.2.5
  gatsby-plugin-mdx: ^1.2.7 => 1.2.7
  gatsby-plugin-offline: ~3.2.2 => 3.2.2
  gatsby-plugin-postcss: ~2.3.1 => 2.3.1
  gatsby-plugin-react-helmet: ~3.3.1 => 3.3.1
  gatsby-plugin-remove-generator: ^1.0.4 => 1.0.4
  gatsby-plugin-robots-txt: ~1.5.x => 1.5.0
  gatsby-plugin-root-import: ~2.0.5 => 2.0.5
  gatsby-plugin-sharp: ~2.2.x => 2.2.11
  gatsby-plugin-sitemap: ~2.2.x => 2.2.20
  gatsby-remark-autolink-headers: ^2.1.24 => 2.1.24
  gatsby-remark-copy-linked-files: ^2.3.2 => 2.3.2
  gatsby-remark-external-links: ~0.0.4 => 0.0.4
  gatsby-remark-images: ~3.1.x => 3.1.11
  gatsby-remark-relative-images: ^0.2.2 => 0.2.3
  gatsby-remark-responsive-iframe: ~2.4.2 => 2.4.2
  gatsby-source-filesystem: ~2.3.3 => 2.3.3
  gatsby-source-youtube-v2: ^1.0.1 => 1.0.1
  gatsby-transformer-remark: ^2.5.0 => 2.6.14
  gatsby-transformer-sharp: ~2.2.x => 2.2.6
npmGlobalPackages:
  gatsby-cli: 2.11.7
```

**Comment by LekoArts** [comment] 2020-05-20 08:55
Hi, thanks for the issue! We'd need to see at least the website but better a reproduction of your issue as all the sites I'm running with the latest version of the offline plugin don't show this behavior and we also haven't heard any other complaints about a recent breakage.

Have you tried this on different computers, updated your browsers?

**Comment by josephmarkus** [comment] 2020-05-20 09:05
Hi @LekoArts, thanks for getting back to me. I did ask people to try and it was breaking for others. I also checked it on my phone. The error in Safari was most descriptive and search results bring up service workers. However, it's still unclear how I can test my changes to prevent this from happening. As things stand, what would be a safe approach here that you could recommend? I appreciate this isn't particularly helpful without reproduction of the issue, but I'm wondering what I could do in the meantime to narrow down the issue described.

**Comment by LekoArts** [comment] 2020-05-20 09:19
You could switch out the plugin https://www.gatsbyjs.org/packages/gatsby-plugin-offline/#remove and see if your site works without the service worker. Then re-add the latest plugin.

You'd need to deploy these changes then. On that note: Have you tried other deployment options? Since it seems you can't share the URL I don't know what you're using. I'd suggest trying Netlify and gatsby-plugin-netlify and see if a build on their infra works.

Lastly, maybe try upgrading `gatsby` to the latest version.

**Comment by josephmarkus** [comment] 2020-05-21 09:45
Thank you for the suggestions. I will try and see if I can try to remove and re-add updated version of the plugin on the staging version of the site.

While researching service workers I came across this short explanatory YouTube video [The Service Worker Lifecycle](https://www.youtube.com/watch?v=TF4AB75PyIc) by Jake Archibald from Google.

A couple of things that stood out for me were:
- when service worker updates, you need to close your browser and reopen it, so that a newly fetched copy can take over the old one
- he strongly recommends setting cache time of a service worker to 0

I wonder, if there any defaults set up _under the hood_ of the plugin that would be useful to bear in mind in relation to the above?

Thanks!

**Comment by ascorbic** [comment] 2020-06-04 09:12
Hi. I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. Thanks!

**Closed by ascorbic** 2020-06-04 09:12 UTC
Labels: status: needs more info, status: needs reproduction, topic: PWA

**Comment by Necmttn** [comment] 2020-09-02 06:50
This issue happens with version`"gatsby-plugin-offline": "^3.2.26",` as well. it's only occurs when you second visit the website in Safari browser.

**Comment by fruluu** [comment] 2020-09-04 09:16
same happens on reload with version "gatsby-plugin-offline": "^3.2.26"

**Comment by gazben** [comment] 2020-09-21 13:58
This happens without the plugin also on my setup.

**Comment by sadewole** [comment] 2020-12-26 09:14
I'm also facing this issue. 
Currently using the latest `gatsby-plugin-offine @^3.7.0`

URL: samador-dev.netlify.app 
The site breaks after refresh but works fine when I remove the plugin.
Please, is there any solution or ways to implement service worker with gatsby?

**Comment by smpetrey** [comment] 2020-12-29 00:37
This is still an issue I'm seeing in prod:
URL: https://petreygatsbymaster41424.gtsb.io/
Site works in FireFox, but the error occurs on Safari

**Comment by sadewole** [comment] 2020-12-30 12:31
> This is still an issue I'm seeing in prod:
> URL: https://petreygatsbymaster41424.gtsb.io/
> Site works in FireFox, but the error occurs on Safari
> 
> Update:
> FWIW, `gatsby-plugin-offine @^3.8.0` appeared to fix the issue.

`3.8.0` ? The current version i'm seeing on npm registry is `3.7.1` and it's still not fixing it

**Comment by smpetrey** [comment] 2020-12-30 22:39
Apologies, my clipboard deceived me. I meant 3.7.1 (I’ll update my previous comment). That seemed to do the trick for me 😕

**Comment by kiril-daskalov** [comment] 2021-01-12 22:55
I got same problem not sure form how long. I tried @3.4.0 and @^3.8.0.

**Comment by daledesilva** [comment] 2021-02-11 05:07
I'm getting the same issue. Happening in Chrome - haven't tested the others.

```

  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.23.1 - /usr/local/bin/node
    npm: 6.14.10 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 88.0.4324.150
    Firefox: 85.0.1
    Safari: 14.0.2
  npmPackages:
    gatsby: ^2.26.1 => 2.32.3 
    gatsby-image: ^2.10.0 => 2.11.0 
    gatsby-plugin-eslint: ^3.0.0 => 3.0.0 
    gatsby-plugin-layout: ^1.9.0 => 1.10.0 
    gatsby-plugin-manifest: ^2.11.0 => 2.12.0 
    gatsby-plugin-material-ui: ^2.1.10 => 2.1.10 
    gatsby-plugin-nprogress: ^2.9.0 => 2.10.0 
    gatsby-plugin-offline: ^3.10.0 => 3.10.0 
    gatsby-plugin-react-helmet: ^3.8.0 => 3.10.0 
    gatsby-plugin-sharp: ^2.13.0 => 2.14.1 
    gatsby-plugin-transition-link: ^1.20.5 => 1.20.5 
    gatsby-source-filesystem: ^2.10.0 => 2.11.0 
    gatsby-source-graphql: ^2.14.0 => 2.14.0 
    gatsby-theme-material-ui: ^1.0.13 => 1.0.13 
    gatsby-transformer-sharp: ^2.11.0 => 2.12.0 
  npmGlobalPackages:
    gatsby-cli: 2.19.0
```

**Comment by daledesilva** [comment] 2021-02-15 00:55
> I'm getting the same issue.
> Happening in Chrome, Firefox, and Safari.
> Fine on first viewing, doesn't load after that.

#### I fixed my issue.
Here's an update to what I did and what caused it.

I had previously created an `onCreatePage` script in `gatsby-node.js` that took over the page creation (deleting pages created and creating them anew). This was in order to make sure each html file wasn't named index.html and in a folder of the page name, but rather, named the `<page_name>.html` and without the extra folder (Because we were having trouble with Amazon S3 loading the non-root index pages.

This caused the `/offline-plugin-app-shell-fallback/` folder (which this plugin creates) to be renamed in the process to `/offline-plugin-app-shell-fallback.html/`.

So I modified that script to ignore that folder and now everything is all well.
It does seem strange that the folder's creation calls the `onCreatePage` function (since it's not a page but a folder), so I'll have to be sure to keep an eye out for this with other plugins as well in the future.

**Comment by acarnwath** [comment] 2021-02-22 21:40
I was experiencing this issue as well with `gatsby-plugin-offline@3.10.1` on the [Federalist platform](https://github.com/18F/federalist-uswds-gatsby) (but not locally), and found the solution for me noted on the [Netlify forum](https://community.netlify.com/t/site-unreachable-upon-refresh/10922/3).
Simply including `globPatterns: ['*.html'],` in the config fixed it.
