### ISSUE TITLE
FetchError: request to [wordpresssite]/graphql failed, reason: read ECONNRESET

### ISSUE THREAD

**Issue by mikeriley131** [gatsbyjs/gatsby#31720] opened 2021-06-02 05:10 UTC
## Description

I've been getting successful Netlify builds for weeks up until a couple of nights ago when I started getting the following error:
`error "gatsby-source-graphql" threw an error while running the sourceNodes lifecycle:
request to https://pnm.059.myftpupload.com/graphql failed, reason: read ECONNRESET`

### Steps to reproduce
Seeing this when pushing a commit to GitHub or manually triggering a build in Netlify,

### Expected result
Build should complete successfully.

### Actual result
Getting the error shown above.

### Environment
The WordPress instance is hosted on GoDaddy. The client set that up so not sure about the details of the plan but can find out if it's relevant.
```
  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.23.0 - ~/.nvm/versions/node/v10.23.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v10.23.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 91.0.4472.77
    Firefox: 87.0
    Safari: 14.1
  npmPackages:
    gatsby: ^2.24.36 => 2.32.13 
    gatsby-image: ^2.4.14 => 2.11.0 
    gatsby-plugin-accessibilityjs: ^1.0.3 => 1.0.3 
    gatsby-plugin-google-tagmanager: ^2.3.11 => 2.11.0 
    gatsby-plugin-manifest: ^2.4.22 => 2.12.1 
    gatsby-plugin-offline: ^2.2.7 => 2.2.10 
    gatsby-plugin-react-helmet: ^3.3.10 => 3.10.0 
    gatsby-plugin-remove-trailing-slashes: ^2.3.11 => 2.10.0 
    gatsby-plugin-sass: ^2.3.12 => 2.8.0 
    gatsby-plugin-sharp: ^2.6.25 => 2.14.4 
    gatsby-plugin-sitemap: ^2.4.11 => 2.12.0 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-source-filesystem: ^2.3.24 => 2.11.1 
    gatsby-source-graphql: ^3.4.0 => 3.4.0 
    gatsby-transformer-sharp: ^2.5.12 => 2.12.1 
```

Here's the full build log:
```
10:35:46 PM: Build ready to start
10:35:48 PM: build-image version: 0582042f4fc261adc7bd8333f34884959c577302
10:35:48 PM: build-image tag: v3.7.6
10:35:48 PM: buildbot version: 0e23307adb9080898b837c5147a17e2f7890cb10
10:35:48 PM: Building without cache
10:35:48 PM: Starting to prepare the repo for build
10:35:48 PM: No cached dependencies found. Cloning fresh repo
10:35:48 PM: git clone https://github.com/mikeriley131/cartel
10:35:51 PM: Preparing Git Reference refs/heads/main
10:35:52 PM: Parsing package.json dependencies
10:35:52 PM: Different publish path detected, going to use the one specified in the Netlify configuration file: 'public' versus 'public/' in the Netlify UI
10:35:52 PM: Starting build script
10:35:52 PM: Installing dependencies
10:35:52 PM: Python version set to 2.7
10:35:53 PM: v12.18.0 is already installed.
10:35:54 PM: Now using node v12.18.0 (npm v6.14.4)
10:35:54 PM: Started restoring cached build plugins
10:35:54 PM: Finished restoring cached build plugins
10:35:54 PM: Attempting ruby version 2.7.1, read from environment
10:35:55 PM: Using ruby version 2.7.1
10:35:56 PM: Using PHP version 5.6
10:35:56 PM: Started restoring cached yarn cache
10:35:56 PM: Finished restoring cached yarn cache
10:35:56 PM: Installing yarn at version 1.22.4
10:35:56 PM: Installing Yarn!
10:35:56 PM: > Downloading tarball...
10:35:56 PM: [1/2]: https://yarnpkg.com/downloads/1.22.4/yarn-v1.22.4.tar.gz --> /tmp/yarn.tar.gz.MaqsMpx5Io
10:35:56 PM:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
10:35:56 PM:                                  Dload  Upload   Total   Spent    Left  Speed
10:35:56 PM:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
10:35:56 PM: 100    79  100    79    0     0    407      0 --:--:-- --:--:-- --:--:--   409
10:35:56 PM: 100    93  100    93    0     0    166      0 --:--:-- --:--:-- --:--:--   166
10:35:57 PM:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
10:35:57 PM: 100   625  100   625    0     0    713      0 --:--:-- --:--:-- --:--:--  6067
10:35:57 PM: 100 1215k  100 1215k    0     0   993k      0  0:00:01  0:00:01 --:--:--  993k
10:35:57 PM: [2/2]: https://yarnpkg.com/downloads/1.22.4/yarn-v1.22.4.tar.gz.asc --> /tmp/yarn.tar.gz.MaqsMpx5Io.asc
10:35:57 PM: 100    83  100    83    0     0   1740      0 --:--:-- --:--:-- --:--:--  1740
10:35:57 PM: 100    97  100    97    0     0   1243      0 --:--:-- --:--:-- --:--:--  1243
10:35:57 PM: 100   629  100   629    0     0   3811      0 --:--:-- --:--:-- --:--:--  3811
10:35:57 PM: 100  1028  100  1028    0     0   4692      0 --:--:-- --:--:-- --:--:--  4692
10:35:57 PM: > Verifying integrity...
10:35:57 PM: gpg: Signature made Mon 09 Mar 2020 03:52:13 PM UTC using RSA key ID 69475BAA
10:35:57 PM: gpg: Good signature from "Yarn Packaging <yarn@dan.cx>"
10:35:57 PM: gpg: WARNING: This key is not certified with a trusted signature!
10:35:57 PM: gpg:          There is no indication that the signature belongs to the owner.
10:35:57 PM: Primary key fingerprint: 72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310
10:35:57 PM:      Subkey fingerprint: 6D98 490C 6F1A CDDD 448E  4595 4F77 6793 6947 5BAA
10:35:57 PM: > GPG signature looks good
10:35:57 PM: > Extracting to ~/.yarn...
10:35:57 PM: > Adding to $PATH...
10:35:58 PM: > Successfully installed Yarn 1.22.4! Please open another terminal where the `yarn` command will now be available.
10:35:58 PM: No yarn workspaces detected
10:35:58 PM: Started restoring cached node modules
10:35:58 PM: Finished restoring cached node modules
10:35:58 PM: Installing NPM modules using Yarn version 1.22.4
10:35:59 PM: yarn install v1.22.4
10:35:59 PM: [1/4] Resolving packages...
10:36:00 PM: [2/4] Fetching packages...
10:36:06 PM: warning url-loader@1.1.2: Invalid bin field for "url-loader".
10:36:33 PM: info fsevents@2.3.2: The platform "linux" is incompatible with this module.
10:36:33 PM: info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
10:36:33 PM: info fsevents@1.2.13: The platform "linux" is incompatible with this module.
10:36:33 PM: info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
10:36:33 PM: [3/4] Linking dependencies...
10:36:33 PM: warning "gatsby > @typescript-eslint/eslint-plugin > tsutils@3.21.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
10:36:33 PM: warning "gatsby-source-graphql > @graphql-tools/utils@7.9.0" has unmet peer dependency "graphql@^14.0.0 || ^15.0.0".
10:36:33 PM: warning "gatsby > eslint-plugin-graphql > graphql-config > @endemolshinegroup/cosmiconfig-typescript-loader > ts-node@9.1.1" has unmet peer dependency "typescript@>=2.7".
10:36:33 PM: warning "gatsby-source-graphql > @graphql-tools/links > @graphql-tools/delegate@7.1.5" has unmet peer dependency "graphql@^14.0.0 || ^15.0.0".
10:36:33 PM: warning "gatsby-source-graphql > @graphql-tools/wrap@7.0.8" has unmet peer dependency "graphql@^14.0.0 || ^15.0.0".
10:36:33 PM: warning "gatsby-plugin-sass > sass-loader@7.3.1" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
10:36:33 PM: warning " > gatsby-source-graphql@3.4.0" has incorrect peer dependency "gatsby@^3.0.0-next.0".
10:36:33 PM: warning "gatsby-source-graphql > @graphql-tools/links@7.1.0" has unmet peer dependency "@apollo/client@~3.2.5 || ~3.3.0".
10:36:33 PM: warning "gatsby-source-graphql > @graphql-tools/links@7.1.0" has unmet peer dependency "graphql@^14.0.0 || ^15.0.0".
10:36:33 PM: warning "gatsby-source-graphql > apollo-link@1.2.14" has unmet peer dependency "graphql@^0.11.3 || ^0.12.3 || ^0.13.0 || ^14.0.0 || ^15.0.0".
10:36:33 PM: warning "gatsby-source-graphql > apollo-link-http@1.5.17" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
10:36:33 PM: warning "gatsby-source-graphql > @graphql-tools/links > apollo-upload-client@14.1.3" has unmet peer dependency "graphql@14 - 15".
10:36:33 PM: warning "gatsby-source-graphql > apollo-link > apollo-utilities@1.3.4" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
10:36:33 PM: warning "gatsby-source-graphql > apollo-link-http > apollo-link-http-common@0.2.16" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
10:36:33 PM: warning "gatsby-source-graphql > @graphql-tools/links > apollo-upload-client > @apollo/client@3.3.16" has unmet peer dependency "graphql@^14.0.0 || ^15.0.0".
10:36:33 PM: warning "gatsby-source-graphql > @graphql-tools/links > apollo-upload-client > @apollo/client > @graphql-typed-document-node/core@3.1.0" has unmet peer dependency "graphql@^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
10:36:33 PM: warning "gatsby-source-graphql > @graphql-tools/links > apollo-upload-client > @apollo/client > graphql-tag@2.12.4" has unmet peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
10:36:51 PM: [4/4] Building fresh packages...
10:36:58 PM: Done in 59.82s.
10:36:59 PM: NPM modules installed using Yarn
10:36:59 PM: Started restoring cached go cache
10:36:59 PM: Finished restoring cached go cache
10:36:59 PM: go version go1.14.4 linux/amd64
10:36:59 PM: go version go1.14.4 linux/amd64
10:36:59 PM: Installing missing commands
10:36:59 PM: Verify run directory
10:36:59 PM: ​
10:36:59 PM: ────────────────────────────────────────────────────────────────
10:36:59 PM:   Netlify Build                                                 
10:36:59 PM: ────────────────────────────────────────────────────────────────
10:36:59 PM: ​
10:36:59 PM: ❯ Version
10:36:59 PM:   @netlify/build 11.29.2
10:36:59 PM: ​
10:36:59 PM: ❯ Flags
10:36:59 PM:   deployId: 60b70aa2d8b6bc62a9785e23
10:36:59 PM: ​
10:36:59 PM: ❯ Current directory
10:36:59 PM:   /opt/build/repo
10:36:59 PM: ​
10:36:59 PM: ❯ Config file
10:36:59 PM:   No config file was defined: using default values.
10:36:59 PM: ​
10:36:59 PM: ❯ Context
10:36:59 PM:   production
10:36:59 PM: ​
10:36:59 PM: ────────────────────────────────────────────────────────────────
10:36:59 PM:   1. Build command from Netlify app                             
10:36:59 PM: ────────────────────────────────────────────────────────────────
10:36:59 PM: ​
10:36:59 PM: $ yarn build
10:37:00 PM: yarn run v1.22.4
10:37:00 PM: $ gatsby build
10:37:03 PM: success open and validate gatsby-configs - 0.059s
10:37:03 PM: warning Plugin gatsby-source-graphql is not compatible with your gatsby version 2.32.13 - It requires gatsby@^3.0.0-next.0
10:37:04 PM: success load plugins - 0.845s
10:37:04 PM: success onPreInit - 0.125s
10:37:04 PM: success delete html and css files from previous builds - 0.004s
10:37:04 PM: success initialize cache - 0.009s
10:37:04 PM: success copy gatsby files - 0.047s
10:37:04 PM: success onPreBootstrap - 0.015s
10:37:04 PM: success createSchemaCustomization - 0.016s
10:37:04 PM: error "gatsby-source-graphql" threw an error while running the sourceNodes lifecycle:
10:37:04 PM: request to https://pnm.059.myftpupload.com/graphql failed, reason: read ECONNRESET
10:37:04 PM: 
10:37:04 PM: 
10:37:04 PM:   FetchError: request to https://pnm.059.myftpupload.com/graphql failed, reason:   read ECONNRESET
10:37:04 PM:   
10:37:04 PM:   - index.js:1461 ClientRequest.<anonymous>
10:37:04 PM:     [repo]/[node-fetch]/lib/index.js:1461:11
10:37:04 PM:   
10:37:04 PM:   - destroy.js:92 emitErrorNT
10:37:04 PM:     internal/streams/destroy.js:92:8
10:37:04 PM:   
10:37:04 PM:   - destroy.js:60 emitErrorAndCloseNT
10:37:04 PM:     internal/streams/destroy.js:60:3
10:37:04 PM:   
10:37:04 PM:   - task_queues.js:84 processTicksAndRejections
10:37:04 PM:     internal/process/task_queues.js:84:21
10:37:04 PM:   
10:37:04 PM: 
10:37:04 PM: not finished source and transform nodes - 0.177s
10:37:04 PM: error Command failed with exit code 1.
10:37:04 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
10:37:04 PM: ​
10:37:04 PM: ────────────────────────────────────────────────────────────────
10:37:04 PM:   "build.command" failed                                        
10:37:04 PM: ────────────────────────────────────────────────────────────────
10:37:04 PM: ​
10:37:04 PM:   Error message
10:37:04 PM:   Command failed with exit code 1: yarn build
10:37:04 PM: ​
10:37:04 PM:   Error location
10:37:04 PM:   In Build command from Netlify app:
10:37:04 PM:   yarn build
10:37:04 PM: ​
10:37:04 PM:   Resolved config
10:37:04 PM:   build:
10:37:04 PM:     command: yarn build
10:37:04 PM:     commandOrigin: ui
10:37:04 PM:     publish: /opt/build/repo/public
10:37:04 PM:   functions:
10:37:04 PM:     '*': {}
10:37:05 PM: Caching artifacts
10:37:05 PM: Started saving node modules
10:37:05 PM: Finished saving node modules
10:37:05 PM: Started saving build plugins
10:37:05 PM: Finished saving build plugins
10:37:05 PM: Started saving yarn cache
10:37:05 PM: Finished saving yarn cache
10:37:05 PM: Started saving pip cache
10:37:05 PM: Finished saving pip cache
10:37:05 PM: Started saving emacs cask dependencies
10:37:05 PM: Finished saving emacs cask dependencies
10:37:05 PM: Started saving maven dependencies
10:37:05 PM: Finished saving maven dependencies
10:37:05 PM: Started saving boot dependencies
10:37:05 PM: Finished saving boot dependencies
10:37:05 PM: Started saving rust rustup cache
10:37:05 PM: Finished saving rust rustup cache
10:37:05 PM: Started saving go dependencies
10:37:05 PM: Finished saving go dependencies
10:37:07 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
10:37:07 PM: Creating deploy upload records
10:37:07 PM: Failing build: Failed to build site
10:37:07 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2
10:37:08 PM: Finished processing build request in 1m19.680975814s
```

**Comment by LekoArts** [comment] 2021-06-04 06:28
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by TylerBarnes** [comment] 2021-06-11 21:21
This is likely due to your Godaddy uptime. Godaddy isn't a very good host so the site is likely going down during a request. I recommend using WPEngine for hosting headless WP backends. Closing this due to no reproduction in 7 days. Feel free to comment here and/or reopen when you have a reproduction :+1: thanks!

**Closed by TylerBarnes** 2021-06-11 21:21 UTC
Labels: status: needs reproduction, type: bug
