### ISSUE TITLE
Warning: Event "xstate.after(1000)#waitingMachine.batchingNodeMutations

### ISSUE THREAD

**Issue by mikeyfe6** [gatsbyjs/gatsby#26839] opened 2020-09-09 17:38 UTC
## Description

**I'm getting this error after saving a file in my local environment.**

`" Warning: Event "xstate.after(1000)#waitingMachine.batchingNodeMutations" was sent to stopped service "waitingMachine". This service has already reached "`

Also **hot reloading** is working whenever it wants too. Sometimes I even have to restart the whole server to see my changes.

### Steps to reproduce

I did the usual: **deleted the cache, node_modules and lockfile, updated npm, gatsby-cli and other packages**.

_I have this problem for approximately 3 weeks and its still isn't fixed so I don't think its a bug from Gatsby itself._

**Live Project:** https://gimmix.nl/
**Repo with code:** https://github.com/mikeyfe6/Gimmix

### Expected result

No errors and normal hot reloading.

### Actual result

`" Warning: Event "xstate.after(1000)#waitingMachine.batchingNodeMutations" was sent to stopped service "waitingMachine". This service has already reached "`

### Environment

```
System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.11.0 - ~/.nvm/versions/node/v13.11.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v13.11.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 85.0.4183.83
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.24.56 => 2.24.56
    gatsby-image: ^2.4.17 => 2.4.17
    gatsby-plugin-canonical-urls: ^2.3.9 => 2.3.10
    gatsby-plugin-catch-links: ^2.3.11 => 2.3.11
    gatsby-plugin-eslint: ^2.0.8 => 2.0.8
    gatsby-plugin-google-analytics: ^2.3.13 => 2.3.13
    gatsby-plugin-google-tagmanager: ^2.3.10 => 2.3.11
    gatsby-plugin-manifest: ^2.4.28 => 2.4.28
    gatsby-plugin-netlify: ^2.3.14 => 2.3.14
    gatsby-plugin-nprogress: ^2.3.9 => 2.3.10
    gatsby-plugin-offline: ^3.2.27 => 3.2.27
    gatsby-plugin-react-helmet: ^3.3.9 => 3.3.10
    gatsby-plugin-robots-txt: ^1.5.1 => 1.5.1
    gatsby-plugin-sass: ^2.3.10 => 2.3.12
    gatsby-plugin-sharp: ^2.6.34 => 2.6.34
    gatsby-plugin-sitemap: ^2.4.12 => 2.4.12
    gatsby-plugin-smoothscroll: ^1.2.0 => 1.2.0
    gatsby-remark-embedder: ^3.0.0 => 3.0.0
    gatsby-remark-images: ^3.3.29 => 3.3.29
    gatsby-remark-images-contentful: ^2.3.16 => 2.3.16
    gatsby-remark-relative-images: ^2.0.2 => 2.0.2
    gatsby-source-contentful: ^2.3.44 => 2.3.44
    gatsby-source-filesystem: ^2.3.29 => 2.3.29
    gatsby-transformer-remark: ^2.8.34 => 2.8.34
    gatsby-transformer-sharp: ^2.5.14 => 2.5.14
  npmGlobalPackages:
    gatsby-cli: 2.12.93
```

**Comment by ascorbic** [comment] 2020-09-10 10:17
Duplicate of #26192. This should be fixed today.

**Closed by ascorbic** 2020-09-10 10:17 UTC
Labels: topic: state machine, type: bug
