### ISSUE TITLE
website & blog needs css background: #000

### ISSUE THREAD

**Issue by tomByrer** [gatsbyjs/gatsby#14772] opened 2019-06-13 14:34 UTC
After changing my Firefox's default background to dark, some of Gatsby's website & all the blog articles are unreadable.  Seems the font color everywhere is fixed, but assumed incorrectly everyone's browser background would be white

![gatsbyjs_org_firefox_background_color](https://user-images.githubusercontent.com/1308419/59440369-79e61280-8dbc-11e9-9253-e40082f90480.JPG)

I have not tested in other browsers, but I assume it would be same issue.

### Expected Action

Ensure CSS `background: #000` is added, instead of assuming that is the default, where needed.  Which is not everywhere, since much of the site has a light-purple background..

#### Advanced Action

Not sure if you use a Web Accessibility checker, but would be nice to add a rule there or a visual checker to ensure any additional components / templates have their CSS `background` set.

### Background of Issue

I have a head concussion, so extended bright lights are bothersome.  I don't expect websites to all have a 'dark theme' yet, so I was hoping to circumvent this by changing the default color & background colors & use openstyles / stylus to hack frequently visited websites.

thanks for your work!

**Comment by mokimo** [comment] 2019-06-14 13:41
Looks like a good suggestion, are you up for making a PR?
It should be somewhere around here: https://github.com/gatsbyjs/gatsby/blob/master/themes/

**Comment by tomByrer** [comment] 2019-06-16 10:26
Sure, I could poke around abit.

**Comment by fk** [comment] 2019-06-17 16:13
Hey @tomByrer! Thanks for brining this up, and sorry to hear that this is causing problems for you!

I just added #14838, which sets the default `html`(page) background for gatsbyjs.org to `#fff`/`white`. I _assume_ this is what you were after—I was confused that you mentioned `#000`, which is the (shorthand) HEX code for black, not white …

With #14838 merged and deployed, gatsbyjs.org will display "as designed"—with a white page background—no matter what your browser's default background is set to.

To address your issue in regards to gatsbyjs.org, maybe you want to give a browser extension like https://addons.mozilla.org/de/firefox/addon/dark-background-light-text/ a try? It seems to produce acceptable results:

![image](https://user-images.githubusercontent.com/21834/59619681-6247ba80-912b-11e9-8e53-4a20f20db9d6.png)

Let us know if this was helpful please! 🙏

**Comment by fk** [comment] 2019-06-17 16:18
@mokimo The source for gatsbyjs.org is located at https://github.com/gatsbyjs/gatsby/tree/master/www 😉—the `themes` directory is for Gatsby Themes, which you can read more about here:

* https://www.gatsbyjs.org/blog/2018-11-11-introducing-gatsby-themes/
* https://www.gatsbyjs.org/blog/2019-01-29-themes-update-child-theming-and-component-shadowing/
* https://www.gatsbyjs.org/blog/2019-01-31-why-themes/
* https://www.gatsbyjs.org/blog/2019-02-11-gatsby-themes-livestream-and-example/
* https://www.gatsbyjs.org/blog/2019-02-26-getting-started-with-gatsby-themes/
* https://www.gatsbyjs.org/blog/2019-03-11-gatsby-themes-roadmap/

**Comment by fk** [comment] 2019-06-17 16:35
@tomByrer I'll close this now that #14838 is merged.
Please feel free to reopen this issue if needed!

PS: We have an issue for a dark theme for gatsbyjs.org at #8789.

**Closed by fk** 2019-06-17 16:35 UTC

**Comment by mokimo** [comment] 2019-06-17 18:05
Ah nice just had a quick peek at where the css class is used in the gatsby repo.
Thanks flo!

**Comment by fk** [comment] 2019-07-31 13:34
Oh, missed your comment @mokimo!
You're welcome—thank _you_ for helping out here! 🤗
