### ISSUE TITLE
Using GatsbyImage with prev/next buttons results in DOMException error

### ISSUE THREAD

**Issue by lswest** [gatsbyjs/gatsby#30072] opened 2021-03-07 17:31 UTC
## Description

Upon updating from gatsby-image to gatsby-plugin-image an image gallery page I created throws errors when trying to advance left/right through the lightbox. It yields the following error: `Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.`

There is another line complaining about `removeChild`, but other than that the text remains the same.

### Steps to reproduce

I've outlined the basic framework of my gallery system in [this repository](https://github.com/lswest/gallery-example).

Simply clone the above repository, install dependencies, and start the project.

The main page is a gallery with 3 categories (most likely irrelevant for the issue), and thumbnails of images. By clicking on the thumbnail you can open a Lightbox (this works). The lightbox also offers next/prev buttons that control the Lightbox component's state, to load the correct image from GraphQL. This fails in 99% of the cases (if it works for you on the first try, simply try to navigate forward/back).

The page should crash with the Gatsby error dialog.

### Expected result

The lightbox should load the next image in the sequence (and the connected description).

### Actual result

Page crashes with the DOMException listed above.

### Environment

This is the environment for the minimum reproducible example above.

```

  System:
    OS: Linux 5.4 Manjaro Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 3.1.2 - /bin/fish
  Binaries:
    Node: 15.10.0 - /usr/bin/node
    Yarn: 1.22.10 - /usr/bin/yarn
    npm: 6.14.11 - /usr/bin/npm
  Languages:
    Python: 3.9.1 - /usr/bin/python
  npmPackages:
    gatsby: ^3.0.1 => 3.0.1 
    gatsby-plugin-image: ^1.0.0 => 1.0.0 
    gatsby-plugin-postcss: ^4.0.0 => 4.0.0 
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0 
    gatsby-plugin-sharp: ^3.0.0 => 3.0.0 
    gatsby-source-filesystem: ^3.0.0 => 3.0.0 
    gatsby-transformer-json: ^3.0.0 => 3.0.0 
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0 
  npmGlobalPackages:
    gatsby-cli: 3.0.0

```

### Hunches

I've done some experimenting and comparing with the old gatsby-image setup. Here is what I learned:

1. Removing the GatsbyImage tag (and leaving everything else the same) doesn't yield the error.
2. Viewing the site in the React DevTools I see that the actual dynamic images are "floating" with ForwardRef indicators (no longer seems to be a child of the Lightbox component). This didn't seem to be the case with the old gatsby-image approach.

Googling the issue seems to indicate that it can be caused by React.Fragment (whereupon a child component has no immediate "parent"), but my guess in this situation is the references utilized by GatsbyImage. In doing so, it seems the "child" (dynamic element that isn't hierarchically linked to the <Type> parent) can't be cleaned up properly when changing the image={} prop of the component.

### Screenshot

Below is a screenshot of the error (also visible in the repo above). Feel free to remove this section of the bug report, if preferred.

[![Screenshot](https://github.com/lswest/gallery-example/raw/main/error.png)](https://github.com/lswest/gallery-example/raw/main/error.png)

**Comment by LekoArts** [comment] 2021-03-08 08:39
This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/29982. Please post your findings there. Thanks!

**Closed by LekoArts** 2021-03-08 08:39 UTC
Labels: topic: images/media, type: bug
