### ISSUE TITLE
Gatsby Site takes a long time to interactive (possibly issue with prefetching images)

### ISSUE THREAD

**Issue by tjands** [gatsbyjs/gatsby#24522] opened 2020-05-27 05:07 UTC
## Summary

Hey all, 
This is most likely a weird question as I can imagine the solution to my problem will be quite a few things (or Im just doing something really dumb haha), I have a gatsby site that handles around a hundred pages, about half of which are rendered, but almost all contain a lot of images and gifs to display in a collection of galleries.

My issue is that my site takes a reaaaally long time before it reaches interactivity, and my chrome lighthouse performance is really bad.  I can see that gatsby is prefetching every image file I use, regardless of if the image is used on the page or if there is a link to that page or not, so I think that might be a configuration error on my part.
Elsewise I think I might be doing something wrong with how Im loading fonts (theyre included through woff files imported into Static Components), or maybe I've done a general configuration setting incorrectly.

![Screen Shot 2020-05-27 at 3 00 56 pm](https://user-images.githubusercontent.com/34981174/82979620-e0465e00-a02a-11ea-8311-80bb916bcf9d.png)

Any help or recommendations of where to look or even issue adjacent memes would be immensely appreciated!

Thanks so much :)
Tim

### Environment (if relevant)

```
  System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.2.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 69.0.3
    Safari: 13.1
  npmPackages:
    gatsby: ^2.22.6 => 2.22.6 
    gatsby-background-image: ^1.1.1 => 1.1.1 
    gatsby-graphiql-explorer: ^0.4.2 => 0.4.2 
    gatsby-image: ^2.4.5 => 2.4.5 
    gatsby-plugin-catch-links: ^2.3.2 => 2.3.2 
    gatsby-plugin-feed: ^2.5.2 => 2.5.2 
    gatsby-plugin-humans-txt: ^1.1.4 => 1.1.4 
    gatsby-plugin-manifest: ^2.4.8 => 2.4.8 
    gatsby-plugin-no-sourcemaps: ^2.2.0 => 2.2.0 
    gatsby-plugin-nprogress: ^2.3.2 => 2.3.2 
    gatsby-plugin-offline: ^3.2.7 => 3.2.7 
    gatsby-plugin-page-transitions: ^1.0.8 => 1.0.8 
    gatsby-plugin-react-helmet: ^3.3.2 => 3.3.2 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-remove-trailing-slashes: ^2.3.3 => 2.3.3 
    gatsby-plugin-s3: ^0.3.3 => 0.3.3 
    gatsby-plugin-sass: ^2.3.2 => 2.3.2 
    gatsby-plugin-sharp: ^2.6.8 => 2.6.8 
    gatsby-plugin-sitemap: ^2.4.3 => 2.4.3 
    gatsby-plugin-styled-components: ^3.3.2 => 3.3.2 
    gatsby-plugin-zopfli: ^1.3.2 => 1.3.2 
    gatsby-remark-copy-images: ^0.2.1 => 0.2.1 
    gatsby-remark-copy-linked-files: ^2.3.3 => 2.3.3 
    gatsby-remark-images: ^3.3.7 => 3.3.7 
    gatsby-remark-prismjs: ^3.5.2 => 3.5.2 
    gatsby-remark-responsive-iframe: ^2.4.3 => 2.4.3 
    gatsby-remark-smartypants: ^2.3.2 => 2.3.2 
    gatsby-source-filesystem: ^2.3.7 => 2.3.7 
    gatsby-source-instagram: ^0.7.0 => 0.7.0 
    gatsby-transformer-json: ^2.4.3 => 2.4.3 
    gatsby-transformer-remark: ^2.8.12 => 2.8.12 
    gatsby-transformer-sharp: ^2.5.3 => 2.5.3 
    gatsby-transformer-yaml: ^2.4.2 => 2.4.2 
  npmGlobalPackages:
    gatsby-cli: 2.12.29
    gatsby: 2.22.4
```

### File contents (if changed)

gatsby-config.js:
 
```
 plugins: [
    `gatsby-plugin-styled-components`,
    `gatsby-plugin-remove-trailing-slashes`,
    {
      resolve: `gatsby-source-filesystem`,
      options: { path: `${config.content_root}/site/`},
    },
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          {
            resolve: `gatsby-remark-responsive-iframe`,
            options: {wrapperStyle: `margin-bottom: 1rem`,},
          },
          {
            resolve: `gatsby-remark-images`,
            options: {maxWidth: 1200, linkImagesToOriginal: false}
          },
          `gatsby-remark-copy-images`,
        ],
      },
    },
    `gatsby-plugin-catch-links`,
    `gatsby-remark-smartypants`,
    `gatsby-remark-prismjs`,
    `gatsby-transformer-json`,
    `gatsby-transformer-yaml`,
    `gatsby-transformer-sharp`,
    `gatsby-plugin-no-sourcemaps`,
    `gatsby-plugin-sass`,
    `gatsby-plugin-react-helmet`,
    'gatsby-plugin-zopfli',
    `gatsby-remark-copy-linked-files`,
    {
      resolve: `gatsby-source-instagram`,
      options: {username: `thegraphicdesignschool`,},
    },
    {
      resolve: `gatsby-plugin-sharp`,
      options: {
        width: 1200,
        defaultQuality: 80
      }
    },
    {
      resolve: `gatsby-plugin-sitemap`,
      options: {output: `./sitemap.xml`,}
    },
    { resolve: `gatsby-plugin-nprogress`,
      options: {color: `#d4163a`,}
    },
    {
      resolve: `@gatsby-contrib/gatsby-plugin-elasticlunr-search`,
      options: {
        fields: [ `title`, `tags` ],
        resolvers: { 
          MarkdownRemark: {
            title: node => node.frontmatter.title,
            tags: node => node.frontmatter.tags,
            slug: node => node.fields.slug,
            html: node => node.html
          },
        },
        filter: (node, getNode) =>   node.frontmatter.tags !== 'exempt', 
      },
    },
    {
      resolve: `gatsby-plugin-manifest`,
    },
    `gatsby-plugin-offline`
```

```
package.json: {
dependencies": {
    "@gatsby-contrib/gatsby-plugin-elasticlunr-search": "^2.3.0",
    "babel-plugin-styled-components": "^1.10.7",
    "cheerio": "^0.22.0",
    "dotenv": "^8.2.0",
    "elasticlunr": "^0.9.5",
    "flatted": "^2.0.2",
    "gatsby": "^2.22.6",
    "gatsby-background-image": "^1.1.1",
    "gatsby-graphiql-explorer": "^0.4.2",
    "gatsby-image": "^2.4.5",
    "gatsby-plugin-catch-links": "^2.3.2",
    "gatsby-plugin-feed": "^2.5.2",
    "gatsby-plugin-humans-txt": "^1.1.4",
    "gatsby-plugin-manifest": "^2.4.8",
    "gatsby-plugin-no-sourcemaps": "^2.2.0",
    "gatsby-plugin-nprogress": "^2.3.2",
    "gatsby-plugin-offline": "^3.2.7",
    "gatsby-plugin-page-transitions": "^1.0.8",
    "gatsby-plugin-react-helmet": "^3.3.2",
    "gatsby-plugin-remove-serviceworker": "^1.0.0",
    "gatsby-plugin-remove-trailing-slashes": "^2.3.3",
    "gatsby-plugin-s3": "^0.3.3",
    "gatsby-plugin-sass": "^2.3.2",
    "gatsby-plugin-sharp": "^2.6.8",
    "gatsby-plugin-sitemap": "^2.4.3",
    "gatsby-plugin-styled-components": "^3.3.2",
    "gatsby-plugin-zopfli": "^1.3.2",
    "gatsby-remark-copy-images": "^0.2.1",
    "gatsby-remark-copy-linked-files": "^2.3.3",
    "gatsby-remark-images": "^3.3.7",
    "gatsby-remark-prismjs": "^3.5.2",
    "gatsby-remark-responsive-iframe": "^2.4.3",
    "gatsby-remark-smartypants": "^2.3.2",
    "gatsby-source-filesystem": "^2.3.7",
    "gatsby-source-instagram": "^0.7.0",
    "gatsby-transformer-json": "^2.4.3",
    "gatsby-transformer-remark": "^2.8.12",
    "gatsby-transformer-sharp": "^2.5.3",
    "gatsby-transformer-yaml": "^2.4.2",
    "intersection-observer": "^0.10.0",
    "node-sass": "^4.14.1",
    "npm-check": "^5.9.2",
    "object-fit-images": "^3.2.4",
    "overlayscrollbars": "^1.12.0",
    "payment": "^2.3.0",
    "polished": "^3.6.3",
    "prismjs": "^1.20.0",
    "react": "^16.13.1",
    "react-credit-cards": "^0.8.2",
    "react-dom": "^16.13.1",
    "react-dropzone": "^11.0.1",
    "react-helmet": "^6.0.0",
    "react-inlinesvg": "^1.2.0",
    "react-markdown": "^4.3.1",
    "react-modal": "^3.11.2",
    "react-paypal-express-checkout": "^1.0.5",
    "react-places-autocomplete": "^7.2.1",
    "react-player": "^2.0.1",
    "react-pose": "^4.0.10",
    "react-typography": "^0.16.19",
    "search-js": "^0.0.1",
    "styled-components": "^5.1.0",
    "typeface-raleway": "0.0.75"
  },
}
```

`gatsby-node.js`: STANDARD PAGE BUILDER

```
`gatsby-browser.js`: 
export const onClientEntry = async () => {
  if (typeof IntersectionObserver === `undefined`) {
    await import(`intersection-observer`);
  }
}
export const onServiceWorkerUpdateReady = () => {
  const answer = window.confirm(
    `This application has been updated. ` +
    `Reload to display the latest version?`
  )
  if (answer === true) {
    window.location.reload()
  }
}
```

`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment] 2020-05-27 07:39
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by stackrole-dev** [comment] 2020-05-27 07:39
Hey @tjands,
Have you tried. using srcSetBreakpoints https://www.gatsbyjs.org/docs/gatsby-image/#images-that-stretch-across-a-fluid-container

This would dramatically decrease load based on the device the end user is using.
![image](https://user-images.githubusercontent.com/64824192/82991271-0b28b600-a01b-11ea-9bed-70b80f0444a8.png)

**Comment by Undistraction** [comment] 2020-05-27 16:27
@tjands Are you loading any third-party scripts. Intercom for example will absolutely kill your Lighthouse performance scores.

**Comment by tjands** [comment] 2020-05-27 23:09
Thank you at @Undistraction, I don't think we are but I will try removing these this morning. and thanks @stackrole-dev, I am on most images but not all I will try these too.

And thanks @LekoArts, Ill try to put together a minimal reproduction soon, should be able to find some time today or tomorrow. :)

Thanks so much all!

**Comment by ascorbic** [comment] 2020-06-04 09:13
Hi. I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. Thanks!

**Closed by ascorbic** 2020-06-04 09:13 UTC
Labels: status: needs reproduction, topic: performance
