### ISSUE TITLE
GraphQL not pulling back leading forward slash from string widget in markdown file

### ISSUE THREAD

**Issue by jf-home** [gatsbyjs/gatsby#25422] opened 2020-06-30 18:31 UTC
## GraphQL not pulling back leading forward slash from string widget in markdown file
Repeatable section (list widget) in markdown file contains a string widget (name: "link").  The leading forward slash "/" of one of three values is not being returned.  Bizarrely, this only happen when the string value is "/real-estate".  Changing the value to "/deal-estate" will return the leading slash when testing in GraphiQL.  The other two values reliably return the leading slash!  I have tried clearing cache are re-running - same result.  I also got a collegue to test - same result.

### Steps to reproduce

This is the structure for the page: 

      - label: "index"
        name: "index"
        file: "src/content/index.md"
        fields:
          - { label: "Template", name: "template", widget: "select", options: ["other"] }
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Image", name: "image", widget: "image", required: false }
          - { label: "Image alt text", name: alttext, widget: string, required: false }
          - { label: "Body title", name: bodytitle, widget: string, required: false }
          - { label: "Body image", name: "bodyimage", widget: "image", required: false }
          - { label: "Body image alt text", name: bodyalttext, widget: string, required: false }
          - { label: "Body", name: "body", widget: "markdown" } 
          - label: Section
            name: section
            widget: list
            fields:
              - { label: "Section title", name: title, widget: string }
              - { label: "Section subtitle", name: subtitle, widget: string, required: false }
              - { label: "Section description", name: description, widget: string }
              - { label: "Section image", name: image, widget: image }
              - { label: "Section image alt text", name: alttext, widget: string }
              - { label: "Section image placement", name: "placement", widget: "select", options: ["card", "left", "right"] }
              - { label: "Section link", name: link, widget: string }

Upload to a project and buld the site.  Then put the content in via the NetlifyCMS interface.  Set the "link" field test in one of the sections to "/real-estate" and publish.  Pull the markdown file into your local project and run a local develop session.  Finally, pull back the data via GraphiQL.  

### Expected result

The query should return the value "/real-estate" in the appropriate section.

### Actual result

The query erroneously returns the value "real-estate" e.g. no loeading forward slash.

### Environment

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.6 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.0.76 => 2.21.22 
    gatsby-background-image: ^0.9.19 => 0.9.19 
    gatsby-image: ^2.0.20 => 2.4.3 
    gatsby-plugin-catch-links: ^2.3.2 => 2.3.2 
    gatsby-plugin-html-attributes: ^1.0.5 => 1.0.5 
    gatsby-plugin-manifest: ^2.0.9 => 2.4.2 
    gatsby-plugin-netlify: ^2.3.7 => 2.3.5 
    gatsby-plugin-netlify-cms: ^4.3.1 => 4.3.1 
    gatsby-plugin-offline: ^2.0.16 => 2.2.10 
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.3.1 
    gatsby-plugin-recaptcha: ^1.0.5 => 1.0.5 
    gatsby-plugin-sharp: ^2.0.14 => 2.6.2 
    gatsby-plugin-sitemap: ^2.4.4 => 2.4.4 
    gatsby-plugin-svgr: ^2.0.1 => 2.0.2 
    gatsby-remark-images: ^3.3.3 => 3.3.3 
    gatsby-remark-relative-images: ^0.3.0 => 0.3.0 
    gatsby-source-contentful: ^2.3.7 => 2.3.7 
    gatsby-source-filesystem: ^2.0.8 => 2.3.1 
    gatsby-transformer-remark: ^2.8.7 => 2.8.7 
    gatsby-transformer-sharp: ^2.1.8 => 2.5.2 
  npmGlobalPackages:
    gatsby-cli: 2.12.24

Thanks in advance!

**Comment by vladar** [comment] 2020-07-01 17:31
Hi @jf-home !

Just to clarify, do we need Netlify CMS step to reproduce this? Or this be reproduced on plain Gatsby?

To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by TylerBarnes** [comment] 2020-07-10 19:12
Hi @jf-home!

I'm closing this issue due to no reproduction being posted within 7 days.
Once you have a minimal reproduction feel free to re-open this issue and we'll be happy to take another look. 💜 

Thank you!

**Closed by TylerBarnes** 2020-07-10 19:12 UTC
Labels: status: needs reproduction, type: bug
