### ISSUE TITLE
Gatsby develop works, gatsby build works, but gatsby serve displays a white blank page.

### ISSUE THREAD

**Issue by tejaswinivantigodi** [gatsbyjs/gatsby#34066] opened 2021-11-24 09:46 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Gatsby develop works, gatsby build works, but gatsby serve displays a white blank page.

### Reproduction Link

https://github.com/tejaswinivantigodi/Portfolio

### Steps to Reproduce

1. run gatsby develop (runs fine) displays on localhost:8000
2. run gatsby build (looks fine no errors while running).
3. run gatsby serve (displays a blank white page with no content)

### Expected Result

Expecting the same result as gatsby develop command is producing.

### Actual Result

A blank white page with no content.

### Environment

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Binaries:
    Node: 14.17.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.6
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (96.0.1054.29)
  npmGlobalPackages:
    gatsby-cli: 4.2.0
```

**Comment by LekoArts** [comment] 2021-11-24 09:56
Hi, the repository you linked is not available. Please also make sure that you give us a [minimal reproduction][reproduction] and not a full-blown project. Thanks!

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-12-14 06:08
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-12-14 06:08 UTC
Labels: type: bug, status: needs reproduction
