### ISSUE TITLE
gatsby-plugin-emotion hydration issue

### ISSUE THREAD

**Issue by jsejcksn** [gatsbyjs/gatsby#26199] opened 2020-08-03 14:43 UTC
## Description

When using [`gatsby-plugin-emotion`](https://www.gatsbyjs.org/packages/gatsby-plugin-emotion/) with styles depending on the value of an initial URL fragment, the styles are not rendered appropriately after building (but are when using `gatsby develop`).

### Steps to reproduce

1. Setup

```shell
gatsby new hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world
cd hello-world
npm install gatsby-plugin-emotion @emotion/core
```

2. Add `gatsby-plugin-emotion` to the list of plugins in `gatsby-config.js` and modify the default page:

<details>
<summary><code>src/pages/index.js</code></summary>

```js
/** @jsx jsx */

import {css, jsx} from '@emotion/core';
import {useEffect} from 'react';
import {useLocation} from '@reach/router';

const blue = css`color: blue;`;
const red = css`color: red;`;
const defaultText = 'No fragment';

export default function Home() {
  useLocation();

  let text = defaultText;
  
  if (
    typeof window !== 'undefined'
    && window.location.hash.slice(1) !== ''
  ) text = decodeURIComponent(window.location.hash.slice(1));

  useEffect(() => {
    const twoSeconds = 2000;
    setTimeout(() => window.location.hash = 'Hello world', twoSeconds);
  }, []);

  return <div css={text === defaultText ? red : blue}>{text}</div>
};
```
</details>

3. Compare behavior between `gatsby develop` and `gatsby build; gatsby serve`:

---

**develop**

✅ <img alt="develop-01" src="https://user-images.githubusercontent.com/868251/89194278-c49c8e00-d56c-11ea-9b82-7cc4bffea4b5.gif" width="362" />

✅ <img alt="develop-02" src="https://user-images.githubusercontent.com/868251/89194349-db42e500-d56c-11ea-807b-6ddab753617a.gif" width="362" />

---

**build/serve**

✅ <img alt="build-02" src="https://user-images.githubusercontent.com/868251/89194412-edbd1e80-d56c-11ea-8ea8-81c6c4bc6219.gif" width="362" />

❌ <img alt="build-02" src="https://user-images.githubusercontent.com/868251/89194420-f150a580-d56c-11ea-87ef-8f07d7089bc4.gif" width="362" />

---

The result is still the same even if I do a one-time, [two-pass render](https://reactjs.org/docs/react-dom.html#hydrate) like this in the component:

```js
const [, setValue] = useState({});
useEffect(() => setValue({}), []);
```

### Expected result

See above. The text should render in blue in all cases where the text is not the default text.

### Actual result

The text renders in red on navigation to an address with a URL fragment.

<details>
<summary>Environment</summary>

```
System:
  OS: macOS 10.15.6
  Shell: 5.7.1 - /bin/zsh
Binaries:
  Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
  npm: 6.14.7 - ~/.nvm/versions/node/v12.18.3/bin/npm
Languages:
  Python: 2.7.18 - ~/.pyenv/shims/python
Browsers:
  Chrome: 84.0.4147.105
  Safari: 13.1.2
npmPackages:
  gatsby: ^2.23.12 => 2.23.12
  gatsby-plugin-emotion: ^4.3.10 => 4.3.10
npmGlobalPackages:
  gatsby-cli: 2.12.68
```
</details>

**Comment by vladar** [comment] 2020-08-03 16:40
Thank you for opening this, @jsejcksn 

The issue is that you are rendering different element trees in SSR and develop (with `typeof window !== 'undefined'` check). This is not supported by React hydration process. Here is a quote from https://reactjs.org/docs/react-dom.html#hydrate:

> React expects that the rendered content is identical between the server and the client. It can patch up differences in text content, but you should treat mismatches as bugs and fix them.
> 
> In development mode, React warns about mismatches during hydration. There are no guarantees that attribute differences will be patched up in case of mismatches. This is important for performance reasons because in most apps, mismatches are rare, and so validating all markup would be prohibitively expensive.

The whole section explains what's going on very well. Also, I suggest you read this blog post if you want an in-depth understanding of this process: https://joshwcomeau.com/react/the-perils-of-rehydration

We have several very similar issues: #10988 #21997 Also, check out this ongoing discussion on hydration issues: #17914

I am closing this as a duplicate but feel free to re-open if you think your situation is different.

**Closed by vladar** 2020-08-03 16:40 UTC
Labels: status: triage needed, type: bug

**Comment by jsejcksn** [comment] 2020-08-03 17:21
@vladar Not sure if you read my post. I linked to that exact page in the React docs. The two-pass render method I described comes from that page.

> feel free to re-open

I don't have the repo permissions to re-open. Will you please re-open?

**Comment by vladar** [comment] 2020-08-03 19:04
Sadly, the two-pass render as you describe it is not correct. I mean this won't help:

```js
const [, setValue] = useState({});
useEffect(() => setValue({}), []);
```

The point of two-pass render is to have **identical first render** on both the client and the server. But in your case (even with the code above) you have different rendered content during the first render (in the failing case). The first render will produce "red" on the server and "blue" on the client.

The correct two-pass render would be something like this:

```js
/** @jsx jsx */

import {css, jsx} from '@emotion/core';
import {useEffect, useState} from 'react';
import {useLocation} from '@reach/router';

const blue = css`color: blue;`;
const red = css`color: red;`;
const defaultText = 'No fragment';

export default function Home() {
  useLocation();

  const [isClient, setIsClient] = useState(false);
  useEffect(() => setIsClient(true), []);

  let text = defaultText;

  if (isClient && window.location.hash.slice(1) !== '') {
    text = decodeURIComponent(window.location.hash.slice(1));
  }

  useEffect(() => {
    const twoSeconds = 2000;
    setTimeout(() => window.location.hash = 'Hello world', twoSeconds);
  }, []);

  return <div css={text === defaultText ? red : blue}>{text}</div>
};
```

It will consistently produce "red" for the initial render - on both the server and the client, but on subsequent render on the client, it will switch to "blue" as expected.

So this is the same issue as other linked issues. Sorry if I couldn't clarify this enough in the first message.

**Comment by jsejcksn** [comment] 2020-08-04 16:01
@vladar Thanks for clarifying.

> There are no guarantees that attribute differences will be patched up in case of mismatches. This is important for performance reasons because in most apps, mismatches are rare, and so validating all markup would be prohibitively expensive.

I thought that information ☝️ from the `hydrate` docs didn't apply to `render`, but I guess it does.
