### ISSUE TITLE
[v2] Facing issues with the build

### ISSUE THREAD

**Issue by rtm619** [gatsbyjs/gatsby#7186] opened 2018-08-09 16:54 UTC
Hi all,

I'm facing an error with the build. Looks like a problem with the router. Can anyone suggest me the required changes to resolve this?

Console Log:
```
error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  4 | // startsWith(string, search) - Check if `string` starts with `search`
  5 | var startsWith = function startsWith(string, search) {
> 6 |   return string.substr(0, search.length) === search;
    | ^
  7 | };
  8 |
  9 | ////////////////////////////////////////////////////////////////////////////////


  WebpackError: TypeError: Cannot read property 'substr' of null

  - utils.js:6 startsWith
    [lib]/[@reach]/router/es/lib/utils.js:6:1

  - utils.js:143 resolve
    [lib]/[@reach]/router/es/lib/utils.js:143:1

  - index.js:454
    [lib]/[@reach]/router/es/index.js:454:1

  - index.js:51 Object.children
    [lib]/[@reach]/router/es/index.js:51:1

  - react-dom-server.node.production.min.js:34 a.render
    [lib]/[react-dom]/cjs/react-dom-server.node.production.min.js:34:375

  - react-dom-server.node.production.min.js:32 a.read
    [lib]/[react-dom]/cjs/react-dom-server.node.production.min.js:32:246

  - react-dom-server.node.production.min.js:43 renderToString
    [lib]/[react-dom]/cjs/react-dom-server.node.production.min.js:43:1

  - static-entry.js:146 Module../.cache/static-entry.js.__webpack_exports__.default
    lib/.cache/static-entry.js:146:16
```

### Environment (if relevant)

System:
    OS: Windows 10
    CPU: x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 5.6.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 41.16299.248.0
  npmPackages:
    gatsby: ^2.0.0-beta.87 => 2.0.0-beta.87
    gatsby-image: ^1.0.55 => 1.0.55
    gatsby-link: ^2.0.0-beta.12 => 2.0.0-beta.17
    gatsby-plugin-canonical-urls: ^1.0.18 => 1.0.18
    gatsby-plugin-google-analytics: ^2.0.0-beta.4 => 2.0.0-beta.4
    gatsby-plugin-google-tagmanager: ^1.0.19 => 1.0.19
    gatsby-plugin-i18n: ^0.4.2 => 0.4.2
    gatsby-plugin-manifest: ^2.0.2-beta.4 => 2.0.2-beta.4
    gatsby-plugin-offline: ^2.0.0-beta.9 => 2.0.0-beta.9
    gatsby-plugin-purify-css: ^2.2.1 => 2.2.1
    gatsby-plugin-react-helmet: ^3.0.0-beta.4 => 3.0.0-beta.4
    gatsby-plugin-robots-txt: ^1.3.0 => 1.3.0
    gatsby-plugin-sharp: ^2.0.0-beta.7 => 2.0.0-beta.7
    gatsby-plugin-sitemap: ^2.0.0-beta.3 => 2.0.0-beta.3
    gatsby-source-contentful: ^2.0.1-beta.15 => 2.0.1-beta.15
    gatsby-transformer-remark: ^2.1.1-beta.6 => 2.1.1-beta.6
    gatsby-transformer-sharp: ^2.1.1-beta.6 => 2.1.1-beta.6

**Comment by vishalniit** [comment] 2018-08-09 17:26
`success Building production JavaScript and CSS bundles — 65.719 s
⠠ Building static HTML for pages — 100/230 35.04 pages/secondHere

error Building static HTML for pages failed

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  163 |
  164 |     this.props.PLPStore.setFilter(
> 165 |       decodeURI(this.props.location.hash.replace('#', ''))
      |                                          ^
  166 |     );
  167 |   }
  168 |


  WebpackError: TypeError: Cannot read property 'replace' of undefined

  - index.js:165 ProductListingPage.componentWillMount
    lib/src/components/Brand/ProductListingPage/index.js:165:42

  - react-dom-server.node.production.min.js:27 d
    [lib]/[react-dom]/cjs/react-dom-server.node.production.min.js:27:128

  - react-dom-server.node.production.min.js:28 ya
    [lib]/[react-dom]/cjs/react-dom-server.node.production.min.js:28:493

  - react-dom-server.node.production.min.js:33 a.render
    [lib]/[react-dom]/cjs/react-dom-server.node.production.min.js:33:46

  - react-dom-server.node.production.min.js:32 a.read
    [lib]/[react-dom]/cjs/react-dom-server.node.production.min.js:32:246

  - react-dom-server.node.production.min.js:43 renderToString
    [lib]/[react-dom]/cjs/react-dom-server.node.production.min.js:43:1

  - static-entry.js:145 Module../.cache/static-entry.js.__webpack_exports__.default
    lib/.cache/static-entry.js:145:16




  - bootstrap:68 new Promise
    lib/webpack/bootstrap:68:1

  - bootstrap:16 Promise.map.path
    lib/webpack/bootstrap:16:1

  - bootstrap:5 tryCatcher
    lib/webpack/bootstrap:5:1

  - bootstrap:50 MappingPromiseArray._promiseFulfilled
    lib/webpack/bootstrap:50:1

  - api-runner-ssr.js:6 MappingPromiseArray.PromiseArray._iterate
    lib/.cache/api-runner-ssr.js:6:16

  - bootstrap:67 MappingPromiseArray.init
    lib/webpack/bootstrap:67:1


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

Updating the issue after running with latest Gatsby Beta Build-92, rest of all packages are good, source ode build great if in develop or V1. Not sure, but guess, this issue is more likely with latest router change.

**Comment by vishalniit** [comment] 2018-08-09 18:32
Not sure if this helps..
I replaced the error line in code with following code
this.props.location.**pathname**.replace('#', ''), which stopped that error but now i see different error without much details:

`success Building production JavaScript and CSS bundles — 23.507 s
⠂ Building static HTML for pages — 100/230 30.05 pages/secondHere
⠄ Building static HTML for pages — 100/230 30.05 pages/secondHere
Here
⡀ Building static HTML for pages — 100/230 30.05 pages/secondHere
Here
⢀ Building static HTML for pages — 100/230 30.05 pages/secondHere
Here
⠠ Building static HTML for pages — 100/230 30.05 pages/secondHere
error Cannot read property 'split' of null


  TypeError: Cannot read property 'split' of null

  - errors.js:50 createErrorFromString
    [MT-MW-Braun-CA]/[gatsby-cli]/lib/reporter/errors.js:50:34

  - build-html.js:56 renderHTMLQueue.then.catch.e
    [MT-MW-Braun-CA]/[gatsby]/dist/commands/build-html.js:56:18

  - util.js:16 tryCatcher
    [MT-MW-Braun-CA]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [MT-MW-Braun-CA]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [MT-MW-Braun-CA]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [MT-MW-Braun-CA]/[bluebird]/js/release/promise.js:614:10

  - promise.js:689 Promise._settlePromises
    [MT-MW-Braun-CA]/[bluebird]/js/release/promise.js:689:18

  - async.js:133 Async._drainQueue
    [MT-MW-Braun-CA]/[bluebird]/js/release/async.js:133:16

  - async.js:143 Async._drainQueues
    [MT-MW-Braun-CA]/[bluebird]/js/release/async.js:143:10

  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [MT-MW-Braun-CA]/[bluebird]/js/release/async.js:17:14


error UNHANDLED REJECTION


  TypeError: Cannot read property 'split' of null

  - errors.js:50 createErrorFromString
    [MT-MW-Braun-CA]/[gatsby-cli]/lib/reporter/errors.js:50:34

  - build-html.js:56 renderHTMLQueue.then.catch.e
    [MT-MW-Braun-CA]/[gatsby]/dist/commands/build-html.js:56:18

  - util.js:16 tryCatcher
    [MT-MW-Braun-CA]/[bluebird]/js/release/util.js:16:23

  - promise.js:512 Promise._settlePromiseFromHandler
    [MT-MW-Braun-CA]/[bluebird]/js/release/promise.js:512:31

  - promise.js:569 Promise._settlePromise
    [MT-MW-Braun-CA]/[bluebird]/js/release/promise.js:569:18

  - promise.js:614 Promise._settlePromise0
    [MT-MW-Braun-CA]/[bluebird]/js/release/promise.js:614:10

  - promise.js:689 Promise._settlePromises
    [MT-MW-Braun-CA]/[bluebird]/js/release/promise.js:689:18

  - async.js:133 Async._drainQueue
    [MT-MW-Braun-CA]/[bluebird]/js/release/async.js:133:16

  - async.js:143 Async._drainQueues
    [MT-MW-Braun-CA]/[bluebird]/js/release/async.js:143:10

  - async.js:17 Immediate.Async.drainQueues [as _onImmediate]
    [MT-MW-Braun-CA]/[bluebird]/js/release/async.js:17:14


error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by KyleAMathews** [comment] 2018-08-09 20:25
This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/7107

@reach/router doesn't add hash by default to the `location` object like react-router did. We're hopeful to get a fix upstream soon but in the meantime, you'll need to check if `location.hash` is set or use `pathname` like you did @vishalniit. The second error is in gatsby-cli in our error reporter code. It looks like it's expecting error objects to have certain code. Could you add a console.log before the offending line to see what data is available there? I can PR a fix to account for different error object shapes.

**Comment by zyhou** [comment] 2018-08-10 09:06
I have the same error as @vishalniit, `TypeError: Cannot read property 'split' of null` in build mode.
In my case, the problem seems to come from `<Redirect />` (@reach/router). I have no problem with `<Redirect />` in develop mode, `gatsby develop` work well.

```js
import React from 'react';
import Helmet from 'react-helmet';
import { Redirect } from '@reach/router';

import Layout from '../components/layout';
import { detectLocale } from '../components/i18n';

const Blog = () => {
    const locale = detectLocale() == 'fr' ? 'fr' : 'en';

    return (
        <Layout>
            <Helmet>
                <link rel="canonical" href={`/${locale}/blog`} />
            </Helmet>
            <Redirect to={`/${locale}/blog`} />
        </Layout>
    );
};

export default Blog;
```

If I remove `<Redirect />` code, the `gatsby build` work well.

Any idea @KyleAMathews  ?

**Comment by zyhou** [comment] 2018-08-10 12:55
@KyleAMathews Ah yes thanks. I have another error, but he comes from @reach/router. Redirect doesn't work well [simple exemple](https://github.com/zyhou/gatsby-reach-router-redirect/blob/master/src/pages/index.js)

**Comment by KyleAMathews** [comment] 2018-08-10 14:05
>Redirect need to be inside a Router https://reach.tech/router/api/Redirect

By which I mean they must be a _direct_ child of `<Router>` :-)

In your example, `<Redirect>` is two levels deep not one.

**Closed** 2018-08-20 09:47 UTC
