### ISSUE TITLE
the right side panel isnt showing the contents

### ISSUE THREAD

**Issue by karan-tewari** [gatsbyjs/gatsby#26596] opened 2020-08-22 17:27 UTC
Hi, 

When I go to this link https://www.gatsbyjs.com/plugins/gatsby-plugin-sass/?=sass and select this, the documentation part is not showing up, attaching a screenshot for reference. Please check this 

![gat](https://user-images.githubusercontent.com/10368871/90962032-8854b180-e4ca-11ea-8c22-d9a446c5495b.JPG)

**Comment by LekoArts** [comment] 2020-08-25 08:54
Hi, thanks for the issue! This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/24137

**Closed by LekoArts** 2020-08-25 08:54 UTC
Labels: type: documentation
