### ISSUE TITLE
Hindi translation

### ISSUE THREAD

**Issue by sakkshm** [gatsbyjs/gatsby#18855] opened 2019-10-20 12:02 UTC
```yaml
name: Hindi
code: hi
maintainers:
  - tesseralis
  - marcysutton
```

**Comment by lannonbr** [comment] 2019-10-21 13:24
Hey @sakkshm so this is a duplicate of #18780 so I am going to close this issue and suggest you posting a comment there saying you're interested in helping out with translations for Hindi.

**Closed by lannonbr** 2019-10-21 13:24 UTC
