### ISSUE TITLE
allMarkdownRemark query with filter "in" return duplicated object

### ISSUE THREAD

**Issue by piramore** [gatsbyjs/gatsby#26705] opened 2020-08-30 13:58 UTC
## Summary
First, i have several blog post data with multiple value in tags field. But when i'm trying to get blog post for some tags using GraphQL query with filter "in", i'm getting duplicated blog post with multiple same tags as i'm querying. How can i get rid of that's duplicated items from the GraphQL query?

Here is my GraphQL query
```
query myQuery {
  allMarkdownRemark(filter: {frontmatter: {tags: {in: ["Music", "Musician"]}}}) {
    nodes {
      frontmatter {
        tags
        title
      }
    }
  }
}
```
and here is the response
```
{
  "data": {
    "allMarkdownRemark": {
      "nodes": [
        {
          "frontmatter": {
            "tags": [
              "Music",
              "Nogizaka46"
            ],
            "title": "Idol Ungu 46 Album"
          }
        },
        {
          "frontmatter": {
            "tags": [
              "Music",
              "Musician"
            ],
            "title": "Aimyon Tour 2019 -SIXTH SENSE STORY"
          }
        },
        {
          "frontmatter": {
            "tags": [
              "Music",
              "Musician"
            ],
            "title": "Aimyon Tour 2019 -SIXTH SENSE STORY"
          }
        },
        {
          "frontmatter": {
            "tags": [
              "Music",
              "Hinatazaka46"
            ],
            "title": "Hinatazaka46 Single [Doremisolasido]"
          }
        },
        {
          "frontmatter": {
            "tags": [
              "Music",
              "Musician"
            ],
            "title": "She Is Summer"
          }
        },
        {
          "frontmatter": {
            "tags": [
              "Music",
              "Musician"
            ],
            "title": "She Is Summer"
          }
        },
        {
          "frontmatter": {
            "tags": [
              "Music",
              "Hinatazaka46"
            ],
            "title": "She Is Winter"
          }
        }
      ]
    }
  },
  "extensions": {}
}
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by LekoArts** [comment] 2020-08-31 07:59
Hello, thanks for the issue! Could you please clarify what response you're expecting?

**Comment by piramore** [comment] 2020-08-31 08:39
I'm expecting there is no duplicated blog post on my response.
Something like this
```
{
  "data": {
    "allMarkdownRemark": {
      "nodes": [
        {
          "frontmatter": {
            "tags": [
              "Music",
              "Nogizaka46"
            ],
            "title": "Idol Ungu 46 Album"
          }
        },
        {
          "frontmatter": {
            "tags": [
              "Music",
              "Musician"
            ],
            "title": "Aimyon Tour 2019 -SIXTH SENSE STORY"
          }
        },
        {
          "frontmatter": {
            "tags": [
              "Music",
              "Hinatazaka46"
            ],
            "title": "Hinatazaka46 Single [Doremisolasido]"
          }
        },
        {
          "frontmatter": {
            "tags": [
              "Music",
              "Musician"
            ],
            "title": "She Is Summer"
          }
        },
        {
          "frontmatter": {
            "tags": [
              "Music",
              "Hinatazaka46"
            ],
            "title": "She Is Winter"
          }
        }
      ]
    }
  },
  "extensions": {}
}
```

**Comment by piramore** [comment] 2020-09-02 03:30
Is there any solution?

**Comment by LekoArts** [comment] 2020-09-02 07:14
This is a bug and not expected behavior. I assigned a colleague of mine to look into it, though there probably won't be an immediate fix. So unfortunately you'll need to filter out the duplicates via JavaScript yourself at the top of your React component where you get the data (for now).

**Comment by piramore** [comment] 2020-09-02 10:22
Ok, I guess I willl filtering the response from the javascript for now.
Thank you so much for the response!

And yeah, I will wait for the bug fixes.

**Comment by pvdz** [comment] 2020-09-08 08:52
Duplicate of #26382

It's on my radar, just have to find time for it.

**Closed by pvdz** 2020-09-08 08:52 UTC
Labels: topic: GraphQL, type: bug
