### ISSUE TITLE
How to specify order of plugins

### ISSUE THREAD

**Issue by herecydev** [gatsbyjs/gatsby#24141] opened 2020-05-16 14:37 UTC
As a plugin author, I want my plugin to run after the "site plugins", as it provides information that the consumer can use.

A contrived example is:

```jsx
// my plugin gatsby-browser.js
export const wrapPageElement = ({ element}) => {
return <Context.Provider value={"some useful info"}>{element}</Context.Provider>
}

// site plugin gatsby-browser.js
export const wrapPageElement = ({ element}) => {
// I want to consume that info from the plugin
return <div>{element}</div>
}
```

Because the site plugins always get injected last, it always runs last and thus wraps the plugin component. Therefore making it impossible to access the information. Is there a method to flag order?

**Comment by blainekasten** [comment] 2020-05-18 15:31
@herecydev No there is not a way to flag the order of the plugins. We'd have to do a decent amount of exploration to consider supporting an API to do that. Right now the site plugin is loaded in by gatsby (along with some other internal plugins), and we push those at the end.

I don't see us changing the way this works any time soon. So you'll have to find a different way to achieve this. 

If you can tell me more what you're trying to do I can try to find suggestions. I'm going to close this issue for now as it's not a supported feature and not a bug. Thanks for raising the idea though!

**Closed by blainekasten** 2020-05-18 15:31 UTC
Labels: status: triage needed, type: question or discussion

**Comment by herecydev** [comment] 2020-05-18 15:34
Is there anything unclear about the example I provided? When the consumer of a plugin relies on a react "context provider" that the plugin provides.

Because the site always "goes last" and wraps the provider, it can never consume the information

**Comment by piducancore** [comment] 2020-12-14 23:11
I think you could turn your _site plugin_ into a [local plugin](https://www.gatsbyjs.com/docs/creating-a-local-plugin/). That way you could order them in your `gatsby-config.js`.

**Comment by Vacilando** [comment] 2021-12-20 21:17
@herecydev did you ever find a solution for this problem? I face a similar one - we need to get data from a source but the list of the IDs to get are provided by another source, which sometimes runs later ( see https://github.com/gatsbyjs/gatsby/discussions/34289 ).

**Comment by herecydev** [comment] 2021-12-22 08:27
I'm sorry I didn't, we just worked around this limitation.
