### ISSUE TITLE
Gatsby 4 `gatsby develop` - "warn Non-deterministic routing danger"

### ISSUE THREAD

**Issue by karldanninger** [gatsbyjs/gatsby#33640] opened 2021-10-22 21:55 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Upgrading to Gatsby 4.0.0 exhibits these warnings on startup

```
...
warn Non-deterministic routing danger: Attempting to create page: "/dev-404-page/", but page "/dev-404-page" already exists
This could lead to non-deterministic routing behavior
warn Non-deterministic routing danger: Attempting to create page: "/404/", but page "/404" already exists
This could lead to non-deterministic routing behavior
...
```

'gatsby-plugin-remove-trailing-slashes' is also upgraded to 4.0.0

The bug: Trailing slashes appear on all pages

### Reproduction Link

-

### Steps to Reproduce

1. Update to Gatsby 4.0.0
2. gatsby start
3. exhibit warnings
...

### Expected Result

No warnings

### Actual Result

warnings

### Environment

```shell
-
```

### Config Flags

-

**Comment by LekoArts** [comment] 2021-11-08 10:13
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-11-08 10:13 UTC
Labels: type: bug, status: needs reproduction, gatsby 4
