### ISSUE TITLE
Process is jammed/ stopped at ' load  plugins..' when I run ' gatsby develop' in the terminal . why ?

### ISSUE THREAD

**Issue by serenahappyhacking** [gatsbyjs/gatsby#26915] opened 2020-09-16 09:13 UTC
## Description

The process is jammed/ stopped at ' load plugins..' when I run ' gatsby develop' in the terminal. 

### Steps to reproduce

run 'gatsby develop' in the terminal

### Expected result

What should happen?
 running normally 

### Actual result

![image](https://user-images.githubusercontent.com/29164467/93317290-e1043980-f83f-11ea-8655-5e343285ee59.png)

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by wardpeet** [comment] 2020-09-17 14:26
Hi @serenahappyhacking!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by serenahappyhacking** [comment] 2020-09-21 07:04
Hi  wardpeet ! 
Thanks so much for leaving the reply of how to cope with the issue. But I have no idea about " create a minimal reproduction " ?  would you mind giving me a further explanation about how to do it?  

thank you very much!  
Have a great day!

**Comment by LekoArts** [comment] 2020-10-05 14:32
Sorry, my colleague must have missed to add the needed link for it.

You can find instructions here: https://gatsby.dev/reproduction

**Comment by ascorbic** [comment] 2020-10-22 10:57
Hi. I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. Thanks!

**Closed by ascorbic** 2020-10-22 10:57 UTC
Labels: status: needs reproduction, type: bug
