### ISSUE TITLE
[gatsby-transformer-sharp] Fail when build

### ISSUE THREAD

**Issue by arnondora** [gatsbyjs/gatsby#3584] opened 2018-01-18 16:22 UTC
I got this error when run `gatsby build`, this error is happened. But when I use `gatsby develop` this error is not happen.

```
error UNHANDLED EXCEPTION


  RangeError: Invalid string length
  
  - join
  
  - Object.stringify
  
  - stringify.js:5 stringify
    [arnondoraBlog]/[json-stringify-safe]/stringify.js:5:15
  
  - index.js:56 
    [arnondoraBlog]/[gatsby]/dist/redux/index.js:56:60
  
  - lodash.js:10350 invokeFunc
    [arnondoraBlog]/[lodash]/lodash.js:10350:23
  
  - lodash.js:10397 trailingEdge
    [arnondoraBlog]/[lodash]/lodash.js:10397:18
  
  - lodash.js:10385 Timeout.timerExpired [as _onTimeout]
    [arnondoraBlog]/[lodash]/lodash.js:10385:18
```

After I investigated I found the problem from this following query in `gatsby-node.js`

```
                    image {
                      childImageSharp {
                        sizes(maxWidth: 1240 ) {
                          base64
                          tracedSVG
                          aspectRatio
                          src
                          srcSet
                          srcWebp
                          srcSetWebp
                          sizes
                          originalImg
                          originalName
                        }
       }
}
```

But after I change this query into `original` one, the problem is gone. I don't know is this problem comes from this warning "vips warning: VipsJpeg: error reading resolution" I also wanna ask how to get rid of this warning.

**Comment by KyleAMathews** [comment] 2018-01-18 16:41
The VipsJpeg error will go away with the bump to a new version of Sharp in Gatsby v2 (coming soon).

Not sure what the other error is — is this reproducible? Can you create a small site that shows the error that I or someone else could look at?

**Comment by arnondora** [comment] 2018-01-18 16:46
I still don't know why this problem is happen. I am looking into which article is the cause of this problem. I'll keep in touch

**Comment by arnondora** [comment] 2018-01-18 16:52
```
(node:6262) Warning: Possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit
```

@KyleAMathews Is this warning is related to this problem ?

**Comment by KyleAMathews** [comment] 2018-01-18 16:57
No

**Comment by arnondora** [comment] 2018-01-18 16:57
Ok, I'll dig into which article causes this problem.

**Comment by arnondora** [comment] 2018-01-18 18:42
I have tried by building with some of article randomly for several times, the error is not come up. But when I increase more articles, the error came up. I think it may come from the number of article?

```
GATSBY_ENV=staging node --max-old-space-size=20000 ./node_modules/.bin/gatsby  build
success delete html files from previous builds — 0.466 s
success open and validate gatsby-config.js — 0.007 s
success copy gatsby files — 0.035 s
success onPreBootstrap — 0.017 s
success source and transform nodes — 1.894 s
success building schema — 1.820 s
success createLayouts — 0.011 s
success createPages — 37.940 s
success createPagesStatefully — 0.158 s
success onPreExtractQueries — 0.062 s
success update schema — 15.923 s
success extract queries from components — 0.158 s
error UNHANDLED EXCEPTION


  RangeError: Invalid string length
  
  - join
  
  - Object.stringify
  
  - stringify.js:5 stringify
    [arnondoraBlog]/[json-stringify-safe]/stringify.js:5:15
  
  - index.js:56 
    [arnondoraBlog]/[gatsby]/dist/redux/index.js:56:60
  
  - lodash.js:10350 invokeFunc
    [arnondoraBlog]/[lodash]/lodash.js:10350:23
  
  - lodash.js:10397 trailingEdge
    [arnondoraBlog]/[lodash]/lodash.js:10397:18
  
  - lodash.js:10385 Timeout.timerExpired [as _onTimeout]
    [arnondoraBlog]/[lodash]/lodash.js:10385:18
```

As every time, it died on the step of query the GraphQL

**Comment by calcsam** [comment] 2018-01-18 18:50
Can you post a repo that reproduces this error?

**Comment by calcsam** [comment] 2018-01-18 18:50
Can you post a repo that reproduces this error?

**Comment by arnondora** [comment] 2018-01-18 19:00
@calcsam Here's the original repo. It's contain the exact things that I use.
https://github.com/arnondora/arnondoraBlog

The error is in the `develop` branch

**Comment by KyleAMathews** [comment] 2018-01-19 13:42
Oh... it seems like it's actually a node.js error meaning your system is out of memory https://github.com/nodejs/node-v0.x-archive/issues/14170

**Comment by arnondora** [comment] 2018-01-19 15:07
So the temporary solution is increasing max-old-space-size ?

**Comment by KyleAMathews** [comment] 2018-01-19 15:39
Not sure as I haven't run into this error before. Could you try that and report back if it fixes the error?

**Comment by arnondora** [comment] 2018-01-19 15:51
@KyleAMathews I tried with max-old-space-size=9999999, it also stuck with the same error. I also tried with the PC that has more memory, it also stuck with the same error.

**Comment by KyleAMathews** [comment] 2018-01-19 17:28
So tried running this locally and got a different error

```bash
Generating image thumbnails [------------------------------] 9/4773 1.5 secs 0%(node:52482) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 finish listeners added. Use emitter.setMaxListeners() to increase limit
success createPages — 74.604 s
success createPagesStatefully — 0.181 s
success onPreExtractQueries — 0.005 s
success update schema — 5.634 s
success extract queries from components — 0.167 s
⠐ run graphql queriesError: async hook stack has become corrupted (actual: 83833, expected: 83834)
 1: node::InternalCallbackScope::Close() [/usr/local/bin/node]
 2: node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
 3: node::(anonymous namespace)::TimerWrap::OnTimeout(uv_timer_s*) [/usr/local/bin/node]
 4: uv__run_timers [/usr/local/bin/node]
 5: uv_run [/usr/local/bin/node]
 6: node::Start(v8::Isolate*, node::IsolateData*, int, char const* const*, int, char const* const*) [/usr/local/bin/node]
 7: node::Start(uv_loop_s*, int, char const* const*, int, char const* const*) [/usr/local/bin/node]
 8: node::Start(int, char**) [/usr/local/bin/node]
 9: start [/usr/local/bin/node]
/p/t/arnondoraBlog (develop=) gatsby build
success delete html files from previous builds — 0.020 s
success open and validate gatsby-config.js — 0.005 s
success copy gatsby files — 0.030 s
success onPreBootstrap — 0.012 s
success source and transform nodes — 2.288 s
success building schema — 0.927 s
success createLayouts — 0.011 s
success createPages — 85.449 s
success createPagesStatefully — 0.105 s
success onPreExtractQueries — 0.035 s
success update schema — 29.236 s
success extract queries from components — 0.510 s
⡀ run graphql queriesError: async hook stack has become corrupted (actual: 71247, expected: 71248)
 1: node::InternalCallbackScope::Close() [/usr/local/bin/node]
 2: node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
 3: node::(anonymous namespace)::TimerWrap::OnTimeout(uv_timer_s*) [/usr/local/bin/node]
 4: uv__run_timers [/usr/local/bin/node]
 5: uv_run [/usr/local/bin/node]
 6: node::Start(v8::Isolate*, node::IsolateData*, int, char const* const*, int, char const* const*) [/usr/local/bin/node]
 7: node::Start(uv_loop_s*, int, char const* const*, int, char const* const*) [/usr/local/bin/node]
 8: node::Start(int, char**) [/usr/local/bin/node]
 9: start [/usr/local/bin/node]
```

I've never tried generating that many thumbnails so somewhere in how we're doing things, scaling image processing is breaking down. I'd need to do a deep-dive on this to understand where and how to scale up image processing more. Would love to hear from you @arnondora or anyone else who wants to start exploring.

**Comment by arnondora** [comment] 2018-01-19 18:12
I'll dig into more detail ASAP. Thank you for investing this problem. @KyleAMathews

**Comment by KyleAMathews** [comment] 2018-09-08 04:26
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Closed by KyleAMathews** 2018-09-08 04:26 UTC
