### ISSUE TITLE
Gatsby 2.24.85 not working when we update react & react-dom 17

### ISSUE THREAD

**Issue by ppatel31** [gatsbyjs/gatsby#27618] opened 2020-10-23 13:16 UTC
The above error occurred in the <StoreStateProvider> component:
    in StoreStateProvider
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.

 ERROR 

Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.

 ERROR 

UNHANDLED REJECTION Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

  Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
  1. You might have mismatching versions of React and the renderer (such as React DOM)
  2. You might be breaking the Rules of Hooks
  3. You might have more than one copy of React in the same app
  See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
  
  - react.development.js:1465 resolveDispatcher
    [gatsby]/[react]/cjs/react.development.js:1465:13
  
  - react.development.js:1496 useState
    [gatsby]/[react]/cjs/react.development.js:1496:20
  
  - context.js:21 StoreStateProvider
    [gatsby]/[gatsby-cli]/lib/reporter/loggers/ink/context.js:21:49
  
  - react-reconciler.development.js:6036 renderWithHooks
    [ink]/[react-reconciler]/cjs/react-reconciler.development.js:6036:18
  
  - react-reconciler.development.js:8570 mountIndeterminateComponent
    [ink]/[react-reconciler]/cjs/react-reconciler.development.js:8570:13
  
  - react-reconciler.development.js:9938 beginWork$1
    [ink]/[react-reconciler]/cjs/react-reconciler.development.js:9938:16
  
  - react-reconciler.development.js:11563 Object.invokeGuardedCallbackImpl
    /[ink]/[react-reconciler]/cjs/react-reconciler.development.js:11563:10
  
  - react-reconciler.development.js:11740 invokeGuardedCallback
    /[ink]/[react-reconciler]/cjs/react-reconciler.development.js:11740:31
  
  - react-reconciler.development.js:15778 beginWork$$1
     /[ink]/[react-reconciler]/cjs/react-reconciler.development.js:15778:7
  
  - react-reconciler.development.js:14696 performUnitOfWork
    /[ink]/[react-reconciler]/cjs/react-reconciler.development.js:14696:12

Describe the issue that you're seeing.

### Steps to reproduce

update following versions in package.json

"gatsby": "^2.24.85",
"react": "^17.0.0",
"react-dom": "^17.0.0",

npm install

### Expected result

should work

### Actual result

getting error

### Environment

System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.13.0 - /usr/local/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.111
    Edge: 86.0.622.51
    Firefox: 81.0.2
    Safari: 14.0
  npmPackages:
    gatsby: ^2.24.85 => 2.24.85
    gatsby-plugin-canonical-urls: ^2.3.10 => 2.3.13
    gatsby-plugin-google-tagmanager: ^2.3.11 => 2.3.16
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.14
    gatsby-plugin-remove-trailing-slashes: ^2.3.11 => 2.3.13
    gatsby-plugin-robots-txt: ^1.5.1 => 1.5.3
    gatsby-plugin-s3: ^0.3.5 => 0.3.8
    gatsby-plugin-sitemap: ^2.4.12 => 2.4.17
    gatsby-plugin-verify-bing: ^1.1.18 => 1.1.20
    gatsby-remark-external-links: 0.0.4 => 0.0.4
    gatsby-source-filesystem: ^2.3.27 => 2.3.35
    gatsby-source-graphql: ^2.7.2 => 2.7.6
    gatsby-transformer-json: ^2.4.11 => 2.4.15
    gatsby-transformer-remark: ^2.8.32 => 2.8.46
  npmGlobalPackages:
    gatsby-cli: 2.12.111
    gatsby: 2.19.41

**Comment by ppatel31** [comment] 2020-10-23 13:21
I did following steps.

Updated gatsby-cli latest version
Deleted node_module, .cache, package-lock.json
run npm install

but still same error

**Comment by vladar** [comment] 2020-10-23 14:58
Hi @ppatel31 !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by ppatel31** [comment] 2020-10-23 15:41
Sure, here is my package.json file, you could reproduce it using this npm versions.

{
  "name": "my-app",
  "description": "my-app",
  "license": "MIT",
  "scripts": {
    "develop": "gatsby develop",
    "build": "gatsby build",
    "deploy": "gatsby-plugin-s3 deploy --yes",
    "serve": "gatsby serve",
    "lint:check": "eslint . --ext=js,jsx;  exit 0",
    "lint:fix": "eslint . --ext=js,jsx --fix;  exit 0",
    "cy:open": "cypress open",
    "cy:run": "cypress run",
    "test:e2e": "start-server-and-test develop http://localhost:8000 cy:open",
    "test:e2e:ci": "start-server-and-test develop http://localhost:8000 cy:run",
    "test:unit": "jest",
    "test:unit:compact": "CI=true jest 2>&1"
  },
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^1.2.32",
    "@fortawesome/free-brands-svg-icons": "^5.15.1",
    "@fortawesome/free-regular-svg-icons": "^5.15.1",
    "@fortawesome/free-solid-svg-icons": "^5.15.1",
    "@fortawesome/react-fontawesome": "^0.1.11",
    "@types/react-redux": "^7.1.9",
    "aws-amplify": "^3.3.4",
    "aws-amplify-react": "^4.2.8",
    "aws-amplify-react-extended": "^2.3.57",
    "aws-cli": "0.0.2",
    "aws-sdk": "^2.777.0",
    "classnames": "^2.2.6",
    "core-js": "^3.6.5",
    "dotenv": "^8.2.0",
    "es6-promise": "^4.2.8",
    "formik": "^2.2.0",
    "gatsby": "^2.24.85",
    "gatsby-plugin-canonical-urls": "^2.3.13",
    "gatsby-plugin-google-tagmanager": "^2.3.16",
    "gatsby-plugin-react-helmet": "^3.3.14",
    "gatsby-plugin-robots-txt": "^1.5.3",
    "gatsby-plugin-s3": "^0.3.8",
    "gatsby-plugin-sitemap": "^2.4.17",
    "gatsby-plugin-verify-bing": "^1.1.20",
    "gatsby-remark-external-links": "0.0.4",
    "gatsby-source-filesystem": "^2.3.35",
    "gatsby-source-graphql": "^2.7.6",
    "gatsby-transformer-json": "^2.4.15",
    "gatsby-transformer-remark": "^2.8.46",
    "google-map-react": "^2.1.8",
    "graphql": "^15.3.0",
    "he": "^1.2.0",
    "html-react-parser": "^0.14.0",
    "html2canvas": "^1.0.0-rc.7",
    "isomorphic-fetch": "^3.0.0",
    "jspdf": "^2.1.1",
    "local-storage": "^2.0.0",
    "lodash": "^4.17.20",
    "moment": "^2.29.1",
    "query-string": "^6.13.6",
    "react": "^17.0.1",
    "react-accessible-accordion": "^3.3.3",
    "react-add-to-calendar": "^0.1.5",
    "react-back-to-top-button": "^0.0.14",
    "react-calendar-icon": "^0.9.4",
    "react-dom": "^17.0.1",
    "react-favicon": "^0.0.18",
    "react-helmet": "^6.1.0",
    "react-instagram-embed": "^1.5.0",
    "react-select": "^3.1.0",
    "react-table": "^7.6.0",
    "react-tooltip": "^4.2.10",
    "react-twitter-embed": "^3.0.3",
    "reactstrap": "^8.6.0",
    "serialize-javascript": "^5.0.1",
    "styled-components": "^5.2.0",
    "styled-jss": "^2.2.3",
    "youtube-embed-video": "^1.2.1"
  },
  "devDependencies": {
    "@testing-library/cypress": "^7.0.1",
    "@testing-library/jest-dom": "^5.11.5",
    "@testing-library/react": "^11.1.0",
    "axe-core": "^4.0.2",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^26.6.1",
    "babel-preset-gatsby": "^0.5.14",
    "cypress": "^5.4.0",
    "cypress-axe": "^0.8.1",
    "eslint": "^7.11.0",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-config-prettier": "^6.14.0",
    "eslint-plugin-cypress": "^2.11.2",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.21.5",
    "gatsby-plugin-remove-trailing-slashes": "^2.3.13",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^26.6.1",
    "moment-locales-webpack-plugin": "^1.2.0",
    "prettier": "^2.1.2",
    "start-server-and-test": "^1.11.5"
  }
}

**Comment by martynhoyer** [comment] 2020-10-23 16:47
Also seeing this issue. Oddly it seems to run the `npm run build` command on the Netlify pipeline without issue (although I'm not sure if that's a cache thing).

It also seems to work ok if I switch over to use Yarn, but I don't really want to do that permanently.

**Comment by tomdewildt** [comment] 2020-10-23 17:09
This issue is probably a duplicate of https://github.com/gatsbyjs/gatsby/issues/27592.

There are also some (temporary) solutions over there.

**Comment by pieh** [comment] 2020-10-23 17:39
We do track this issue already https://github.com/gatsbyjs/gatsby/issues/27592 so I will close this one as duplicate

Duplicate of #27592

**Closed by pieh** 2020-10-23 17:39 UTC
Labels: topic: cli, type: bug
