### ISSUE TITLE
[gatsby-source-contentful] and useStaticQuery, incremental build issue

### ISSUE THREAD

**Issue by Prichmondo** [gatsbyjs/gatsby#31578] opened 2021-05-25 08:18 UTC
I am having an issue using useStaticQuery on a project. 

Recently , I have migrated the project to Gatsby 3 to take advantage of the incremental build. 
Contents are managed on Contentful and I use **gatsby-source-contentful** to pull them at build time.

I access to the content in two different way:
- On pages by using standard page-query
- On components and hooks by using useStaticQuery hook

I noticed that in the first case the incremental build works: when a content pulled by a page-query changes on Contentful, the page is rebuilt by Gatsby.
The second scenario fails instead. when a content pulled by a useStaticQuery changes, the page using that component is not rebuilt. It seems like the incremental build process is not able to detect changes on pages using useStaticQuery.

Of course I can easily find a workaround to this issue, but using useStaticQuery is a much better solution.

I am wondering if incremental build is supposed to work with useStaticQuery

**Comment by LekoArts** [comment] 2021-05-26 07:06
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-06-04 06:37
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-06-04 06:37 UTC
Labels: status: needs reproduction, topic: source-contentful, type: bug
