### ISSUE TITLE
Blog: themes GA announcement

### ISSUE THREAD

**Issue by prestonso** [gatsbyjs/gatsby#15122] opened 2019-06-25 17:43 UTC
Two blog posts:

* Themes stable blog post by @christopherbiscardi
* Theme Jam announcement blog post by @jlengstorf

Will need review from @lindaleebumblebee.

**Comment by lannonbr** [comment] 2019-07-06 19:10
This is partially done as Chris's post on Themes being stable is out. There is not a post yet on the Theme Jam but it has been promoted on places like Twitch, Twitter, Reddit, etc

**Comment by lannonbr** [comment] 2019-07-16 12:22
And with #15769 merged, I am closing this as the issue is now fully resolved.

**Closed by lannonbr** 2019-07-16 12:22 UTC
Labels: effort: med, impact: high, status: inkteam assigned, topic: internal
