### ISSUE TITLE
SEO Crawler issue : Importing bootstrap and other css causing bigger document size on view source

### ISSUE THREAD

**Issue by shivaping** [gatsbyjs/gatsby#25040] opened 2020-06-17 05:27 UTC
## Description

SEO Crawler issue : Importing bootstrap and other css causing bigger document size on browser view source

### Steps to reproduce

Import statement of the css converts all the css, scss used in the web application causing page size to increase after the build an release process. 

For example add import './layout.css' in gatsby-browser.js and do a gatsby build and serve. 

Observe that the view source of the page has all the css styles from boostrap embeded

Same issue happens when we import 'bootstrap/dist/css/bootstrap.min.css' 

### Expected result

Expected is to import the stylesheets as ref instead of embedded source

### Actual result

All the stylesheets are compiled with web pack and rendered in the page causing SEO crawler complaining that the document size is too big

**Comment by LekoArts** [comment] 2020-06-17 07:40
Thank you for opening this!

It is working as intended that the CSS gets inlined in the document as overall this increases speed. If you don't want webpack to bundle your CSS and put it into the document you can e.g. put your CSS file inside the `static` folder and request it with a `<script>` tag with React Helmet. See: https://www.gatsbyjs.org/docs/static-folder/#when-to-use-the-static-folder

So this isn't something we want to change, as we also provide possibilities for escape hatches.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2020-06-17 07:40 UTC
Labels: type: question or discussion
