### ISSUE TITLE
upgrade today to moment@^2.25.0 makes a crash

### ISSUE THREAD

**Issue by tidiview** [gatsbyjs/gatsby#23673] opened 2020-05-01 13:58 UTC
upgrade today to moment@^2.25.0 makes a crash.

**Comment by TylerBarnes** [comment] 2020-05-01 21:34
Hi @tidiview !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2020-05-04 10:19
Hi, I'll close this issue as it's not actionable and you didn't follow the issue template. It also sounds like this is not related to Gatsby but moment.js
Please create an issue on their issue tracker or if it only happens on a Gatsby project a new issue with a more descriptive description. Thanks!

**Closed by LekoArts** 2020-05-04 10:19 UTC
Labels: status: need core review, status: needs more info, status: needs reproduction
