### ISSUE TITLE
Is it just me or Gatsby super bugy?

### ISSUE THREAD

**Issue by alextseitlin** [gatsbyjs/gatsby#26931] opened 2020-09-17 11:25 UTC
## Description

I am only 3 days with gatsby but I see strange issues. For example:

1. the graphql officials example stop working with an error `Error: The result of this StaticQuery could not be fetched`. (full details on that issue here https://github.com/gatsbyjs/gatsby/issues/26925) Tried deleting the cache, modules, reinstalling, checking updats. Did this in a loop for 5 hours. Nothing helping. Then I tried to use a hook like in here https://www.gatsbyjs.com/docs/use-static-query/#composing-custom-usestaticquery-hooks and it started working. Not only the hook but also the same, not touched first query that did not work for 5 hours.

2. A lot of time the render not working. I edit, no change. Then I edit another component (just added a space and save) and the render works again.

3. I get a lot of other rander issues that are fixed with deleting cache, modules, reinstalled. Is this only me?

I wanted to use Gatsby for a project but right now I have doubts. Is Gatsby safe to use at the moment? Is something wrong with me or this is happening to you too? Because when I google Gatsby I see that a lot of people say it is super buggy =(

**Comment by vsolanogo** [comment] 2020-09-17 12:12
makes sense to swithc from gatsby to something else. It becae buggy latelym i use older version for development. try:
npm i gatsby@2.20.6

**Comment by wardpeet** [comment] 2020-09-17 13:03
We are sad to hear that it's becoming buggy. We're actively trying to make it better and more stable. If you could share a reproduction we're happy to look at it.

**Comment by dreezaster** [comment] 2020-09-17 14:03
It would be extremely amazing if your support, actually supported us. At least by answering our e-mails...

**Comment by wardpeet** [comment] 2020-09-17 14:41
@dreezaster are you talking about https://www.gatsbyjs.com/contact-us/ I'll ping our team internally

**Comment by dreezaster** [comment] 2020-09-17 14:44
@wardpeet I am talking about the customer support button on dashboard. 

![image](https://user-images.githubusercontent.com/51114504/93486874-f4c5a380-f904-11ea-9fd3-eb7fc31bc133.png)

**Comment by wardpeet** [comment] 2020-09-17 16:33
@dreezaster I'm truly sorry, I've escalated this internally. That's all I can do at this point.

**Comment by LekoArts** [comment] 2020-09-18 07:51
Sorry to hear that you encounter problems. Gatsby is certainly safe to use and we're happy to look into bug reports that enable us to see a reproduction. As this issue here isn't actionable I'll close this in favour of https://github.com/gatsbyjs/gatsby/issues/26925. Please post a reproduction there 👍 

Sometimes these issues arise due to local environment, sometimes due to a bug on our side, e.g. your IDE or OS permissions might block some options. With some investigation we'll find out.

**Closed by LekoArts** 2020-09-18 07:51 UTC
Labels: type: bug, type: question or discussion

**Comment by bigbizze** [comment] 2020-12-08 23:43
> ## Description
> I am only 3 days with gatsby but I see strange issues. For example:
> 
> 1. the graphql officials example stop working with an error `Error: The result of this StaticQuery could not be fetched`. (full details on that issue here #26925) Tried deleting the cache, modules, reinstalling, checking updats. Did this in a loop for 5 hours. Nothing helping. Then I tried to use a hook like in here https://www.gatsbyjs.com/docs/use-static-query/#composing-custom-usestaticquery-hooks and it started working. Not only the hook but also the same, not touched first query that did not work for 5 hours.
> 2. A lot of time the render not working. I edit, no change. Then I edit another component (just added a space and save) and the render works again.
> 3. I get a lot of other rander issues that are fixed with deleting cache, modules, reinstalled. Is this only me?
> 
> I wanted to use Gatsby for a project but right now I have doubts. Is Gatsby safe to use at the moment? Is something wrong with me or this is happening to you too? Because when I google Gatsby I see that a lot of people say it is super buggy =(

Not just you, I have seriously tried to use it multiple times now for projects and it not only feels like every time you run anything that there are constantly bugs, but also that the bugs are extremely vague and difficult to even really understand.

**Comment by ukWaqas** [comment] 2021-02-07 22:29
I've just started using gatsby. I find it extremely buggy when running. A simple command like `gatsby develop` and I get the following error:

```
success open and validate gatsby-configs - 0.068s
success load plugins - 0.460s
success onPreInit - 0.021s
success initialize cache - 0.004s
success copy gatsby files - 0.104s
success onPreBootstrap - 0.018s
success createSchemaCustomization - 0.006s
success Checking for changed pages - 0.010s
success source and transform nodes - 0.207s
success building schema - 0.567s
info Total nodes: 74, SitePage nodes: 1 (use --verbose for breakdown)
success createPages - 0.003s
success Checking for changed pages - 0.001s

 ERROR 

EPERM: operation not permitted, copyfile
'_<Project Path>_\node_modules\gatsby\dist\internal-plugins\dev-404-page\raw_dev-404-page.js'  
-> '<Project Path>\.cache\dev-404-page.js'



  Error: EPERM: operation not permitted, copyfile '_<Project Path>_\node_modules\gatsby\dist\in  ternal-plugins\dev-404-page\raw_dev-404-page.js' -> '_<Project Path>_\.cache\dev-404-page.js'not finished createPagesStatefully - 0.038s

```

Running the same command immediately a second time (no modification whatsoever to the code), and it works:

```
success open and validate gatsby-configs - 0.065s
success load plugins - 0.304s
success onPreInit - 0.021s
success initialize cache - 0.004s
success copy gatsby files - 0.091s
success onPreBootstrap - 0.016s
success createSchemaCustomization - 0.006s
success Checking for changed pages - 0.005s
success source and transform nodes - 0.286s
success building schema - 0.578s
info Total nodes: 74, SitePage nodes: 1 (use --verbose for breakdown)
success createPages - 0.003s
success Checking for changed pages - 0.001s
success createPagesStatefully - 0.100s
success update schema - 0.020s
success write out redirect data - 0.001s
success onPostBootstrap - 0.001s
info bootstrap finished - 3.917s
success onPreExtractQueries - 0.005s
success extract queries from components - 0.210s
success write out requires - 0.012s
success run page queries - 0.024s - 1/1 42.39/s
⠀
You can now view mwt-portal in the browser.
⠀
  http://localhost:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://localhost:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use gatsby build
⠀
```

What gives?

**Comment by clovus** [comment] 2021-02-09 17:24
I heartily agree. Since I started using Gatsby a few months ago, I really gave it a chance, and as a result have spent more time troubleshooting bugs than getting my work done. After finally getting a 'stable' development environment (for the nth time) yesterday, I fired it up today only to get a big purple Gatsby error in the browser. I put in [**this ticket**](https://github.com/gatsbyjs/gatsby/issues/29416) this morning, but honestly, I think I'm done with trying to make Gatsby work.

**Comment by Tony221268** [comment] 2021-11-15 11:21
Agree with all those complaing about this. Too many updates, too many breaking updates and too many random errors. Tried migrating to 4 and it has taken 2 days already, most of the issues resulting in the most obscure error messages. 

The documentation is frankly very poor. 

For instance the gatsby 4 docs are still pointing at @reach-router which no longer works with this version. Too many more instances to list. My advice: stop this endless releasing of error strewn packages, slow down and have higher standards.

**Comment by NafiurSiddiqui** [comment] 2023-03-07 17:46
I am 3 days into it as well and I wanted to dig in since I have a strong react foundation. I have been extremely patient with this but now I am backing off since I don't want to use it for any production. We dev may understand what it is like to build and maintain something like this but the client won't. While I do love the whole idea of the gatsby at this point this is incredibly risky and more likely to jeopardize our reputation. But I would really like to come back to it if it is stable. 

Best of luck you guys! 🙌
