### ISSUE TITLE
Upgrading to latest versions of Gatsby, Node, and React breaks Preact

### ISSUE THREAD

**Issue by juliannehalversen** [gatsbyjs/gatsby#37124] opened 2022-11-29 19:03 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When upgrading to the latest version of Gatsby, Node, and React, the build will succeed until preact packages are installed. I followed this documentation to install preact packages (https://www.gatsbyjs.com/plugins/gatsby-plugin-preact/). I think upgrading to React 18 breaks preact (Gatsby 5 requires React 18 https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/#minimal-required-react-version-is-18) and the previous solution was to install React 17. Since React 18 is required by Gatsby 5 this is no longer a viable solution (https://github.com/gatsbyjs/gatsby/issues/35500). I could not find any other documentation pointing this out or any updates to the gatsby-plugin-preact documentation displaying version requirements. 

The same behavior is happening with the gatsby starter blog (steps to reproduce). Is preact still usable or is there a current workaround for this? If not, then the Gatsby v5 migration documentation should be updated to note this breaking change from a gatsby plugin. 

### Reproduction Link

https://github.com/juliannehalversen/gatsby-starter

### Steps to Reproduce

1. npx gatsby new gatsby-starter-blog https://github.com/gatsbyjs/gatsby-starter-blog (or git clone https://github.com/juliannehalversen/gatsby-starter.git)
2. cd gatsby-starter-blog
3. gatsby build

Build succeeds like expected. 

5. npm install gatsby-plugin-preact preact preact-render-to-string
6. gatsby build 

Build now breaks with this error : 
` ERROR  UNKNOWN

Page data from page-data.json for the failed page "/hello-world/": {
  "componentChunkName": "component---src-templates-blog-post-js",
  "path": "/hello-world/",
  "result": {
    "data": {
      "site": {
        "siteMetadata": {
          "title": "Gatsby Starter Blog"
        }
      },
      "markdownRemark": {
        "id": "d30ef1ef-ab91-5a7c-afce-a9d09ad353ba",
        "excerpt": "This is my first post on my new fake blog! How exciting! I'm sure I'll write a lot more interesting things in the future. Oh, and here's a great
 quote from this…",
        "html": "<p>This is my first post on my new fake blog! How exciting!</p>\n<p>I'm sure I'll write a lot more interesting things in the future.</p>\n<p>Oh,
and here's a great quote from this Wikipedia on\n<a href=\"https://en.wikipedia.org/wiki/Salted_duck_egg\">...",
        "frontmatter": {
          "title": "Hello World",
          "date": "May 01, 2015",
          "description": "Hello World"
        }
      },
      "previous": null,
      "next": {
        "fields": {
          "slug": "/my-second-post/"
        },
        "frontmatter": {
          "title": "My Second Post!"
        }
      }
    },
    "pageContext": {
      "id": "d30ef1ef-ab91-5a7c-afce-a9d09ad353ba",
      "previousPostId": null,
      "nextPostId": "3c425d22-1251-57db-9b9a-f0385134e5a1"
    }
  },
  "staticQueryHashes": [
    "2841359383",
    "3257411868"
  ],
  "slicesMap": {}
}

failed Building static HTML for pages - 3.440s

 ERROR #95313  HTML.COMPILATION

Building static HTML failed for path "/hello-world/"

See our docs page for more info on this error: https://gatsby.dev/debug-html

  351 |       try {
  352 |         const writableStream = new WritableAsPromise()
> 353 |         const { pipe } = renderToPipeableStream(bodyComponent, {
      |                          ^
  354 |           onAllReady() {
  355 |             pipe(writableStream)
  356 |           },

  WebpackError: TypeError: renderToPipeableStream is not a function
  
  - static-entry.js:353 
    gatsby-starter-blog/.cache/static-entry.js:353:26
  
  - TemplateTag.js:147 
    [gatsby-starter-blog]/[common-tags]/es/TemplateTag/TemplateTag.js:147:1`

...

### Expected Result

Build should succeed

### Actual Result

Build throws an error once preact packages are installed. 

### Environment

```shell
System:
    OS: macOS 12.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 107.0.5304.121
    Firefox: 47.0.2
    Safari: 16.0
  npmPackages:
    gatsby: ^5.2.0 => 5.2.0
    gatsby-plugin-google-tagmanager: ^5.2.0 => 5.2.0
    gatsby-plugin-image: ^3.2.0 => 3.2.0
    gatsby-plugin-manifest: ^5.2.0 => 5.2.0
    gatsby-plugin-preact: ^7.2.0 => 7.2.0
    gatsby-plugin-react-helmet: ^6.2.0 => 6.2.0
    gatsby-plugin-sass: ^6.2.0 => 6.2.0
    gatsby-plugin-sharp: ^5.2.0 => 5.2.0
    gatsby-plugin-sitemap: ^6.2.0 => 6.2.0
    gatsby-plugin-styled-components: ^6.2.0 => 6.2.0
    gatsby-source-filesystem: ^5.2.0 => 5.2.0
    gatsby-transformer-remark: ^6.2.0 => 6.2.0
    gatsby-transformer-sharp: ^5.2.0 => 5.2.0
  npmGlobalPackages:
    gatsby-cli: 5.2.0

React 18.2.0.
```

**Comment by LekoArts** [comment] 2022-11-30 06:50
This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/35500

**Closed by LekoArts** 2022-11-30 06:50 UTC
Labels: type: bug, status: triage needed
