### ISSUE TITLE
[gatsby-cache] nothing happens when data on database changes

### ISSUE THREAD

**Issue by SaiRO97** [gatsbyjs/gatsby#29081] opened 2021-01-19 06:43 UTC
Hi i have such a problem. When the data in my database changes, the application does not react to it in any way (even if the page is reloaded). I only see my changes if I rebuild the application. How can I solve this problem? I suppose that the matter is in the cache, I tried to use gatsby-plugin-offline but it did not help me also read the documentation but did not find anything either. I want my gatsby site to see the change immediately when the data in my database changes. Thanks in advance for your help

gatsby-node
```
const path = require('path');

module.exports = {
  siteMetadata: {
    title: 'title',
    description: 'Some desc',
    url: 'http://localhost:8000/',
  },
};

module.exports.onCreateNode = ({ node, actions, getNode }) => {
  const { createNodeField } = actions;

  switch (node.internal.type) {
    case 'MarkdownRemark': {
      const { permalink, layout } = node.frontmatter;
      const { relativePath } = getNode(node.parent);

      if (relativePath) {
        let slug = permalink;

        if (!slug) {
          slug = `/${relativePath.replace('.md', '')}/`;
        }

        // Used to generate URL to view this content.
        createNodeField({
          node,
          name: 'slug',
          value: slug || '',
        });

        // Used to determine a page layout.
        createNodeField({
          node,
          name: 'layout',
          value: layout || '',
        });
      }
      break;
    }
    default:
  }
};

module.exports.createPages = async ({ graphql, actions }) => {
  const { createPage } = actions;
  const news = path.resolve('./src/templates/news.tsx');

  const result = await graphql('
    query {
      allRestApiApiNews {
        nodes {
          items {
            slug
            title
            description
            thumbnail
            slug
            created_at(formatString: "DD.MM.YY")
          }
        }
      }
    }
  ');

  result.data.allRestApiApiNews.nodes[0].items.forEach((data) => {
    createPage({
      path: `/news/${data.slug}`,
      component: news,
      context: {
        data,
      },
    });
  });
};
```
gatsby-config
```
/**
 * Configure your Gatsby site with this file.
 *
 * See: https://www.gatsbyjs.com/docs/gatsby-config/
 */
require('dotenv').config({
  path: `.env.${process.env.NODE_ENV}`,
});

module.exports = {
  siteMetadata: {
    title: `title`,
    description: 'some description',
    url: 'http://localhost:8000/',
  },
  plugins: [
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/pages`,
        name: 'pages',
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `img`,
        path: `${__dirname}/src/assets/img/`,
      },
    },
    {
      resolve: `gatsby-plugin-typescript`,
      options: {
        isTSX: true,
        jsxPragma: `jsx`,
        allExtensions: true,
      },
    },
    {
      resolve: 'gatsby-plugin-sass',
      options: {
        includePaths: ['src/scss/bootstrap'],
      },
    },
    {
      resolve: 'gatsby-source-rest-api',
      options: {
        endpoints: [process.env.SERVER_API],
      },
    },
    {
      resolve: 'gatsby-plugin-anchor-links',
      options: {
        offset: -200,
      },
    },
    `gatsby-plugin-typescript-scss-modules`,
    `gatsby-plugin-react-helmet`,
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    `gatsby-plugin-offline`,
  ],
};
```

**Comment by LekoArts** [comment] 2021-01-19 10:10
Thank you for opening this!

This is working as intended. You're pulling your data at build time thus it'll only refresh if you rebuild the site. You can send triggers to your build pipeline when something changed to kick off a new build or partially pull the data directly on the client. Here's a conceptual guide on data fetching in Gatsby:
https://gatsbyjs.com/docs/data-fetching/

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2021-01-19 10:10 UTC
Labels: type: question or discussion
