### ISSUE TITLE
when run gatsby develop, Error: getaddrinfo ENOTFOUND localhost

### ISSUE THREAD

**Issue by dragonishare** [gatsbyjs/gatsby#20558] opened 2020-01-12 17:54 UTC
## Description

when i follow the doc, run `gatsby develop`, it doesn't work
### Steps to reproduce
follow the doc
```
npx gatsby new gatsby-site  

cd gatsby-site

# here, not as Expected
gatsby develop
```

### Actual result
```
/Users/gatsby-site/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: getaddrinfo ENOTFOUND localhost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:26)
Emitted 'error' event on Server instance at:
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1493:12)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:64:17) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'localhost'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 7
npm ERR! gatsby-starter-default@0.1.0 develop: `gatsby develop`
npm ERR! Exit status 7
npm ERR! 
```
### Environment

macOS 10.15.2
node v13.6.0

1、i check my host file, as follow：
```
$ sudo cat /private/etc/hosts
127.0.0.1               localhost
255.255.255.255 broadcasthost
::1                             localhost
fe80::1%lo0             localhost
```
2、i check port on my mac, 8000 port is not occupied

**Comment by DanielRuf** [comment] 2020-01-12 18:21
Does `ping localhost` work on your system at all?

**Comment by DanielRuf** [comment] 2020-01-12 18:23
> i check port on my mac, 8000 port is not occupied

How exactly did you check that?

Also `telnet localhost 8000' should work.

**Comment by DanielRuf** [comment] 2020-01-12 18:25
> i check port on my mac, 8000 port is not occupied

How exactly did you check that?
With `lsof -nP -i4TCP:8000 | grep LISTEN`?

Also `telnet localhost 8000` should work.

**Comment by jackw** [comment] 2020-01-12 18:42
I just ran the same commands using the same OS version and Node version and gatsby started fine for me. I'd suggest checking your DNS server settings and any VPN configuration you might have.

**Comment by LekoArts** [comment] 2020-01-13 08:31
Thank you for opening this!

As others have written this is most likely a local issue of yours as I also can't reproduce it following your steps. Please try the suggestions here :)

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2020-01-13 08:31 UTC
Labels: type: question or discussion

**Comment by dragonishare** [comment] 2020-04-01 18:26
> Does `ping localhost` work on your system at all?
ping localhost 
output  ping: cannot resolve localhost: Unknown host

i check hosts file in directory /etc, i found  file type show Unix exec
i don't know why, please tell me why, thanks

**Comment by DanielRuf** [comment] 2020-04-01 18:39
> i check hosts file in directory /etc

Not sure if you are in Git bash, msys or something similar. These look like a Linux environment.

**Comment by viraf** [comment] 2020-05-12 15:20
I am facing the same issue. ping localhost does not work however 127.0.0.1 does work.

My environment is macOS 10.15.4
node 14.0
