### ISSUE TITLE
Head API reports exports warning with gatsby-plugin-i18n

### ISSUE THREAD

**Issue by aidanlister** [gatsbyjs/gatsby#36916] opened 2022-10-29 16:53 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

During Gatsby build, all of my .au or .uk pages generate out a warning that the file exports something other than the page component and the Head component:

<img width="1184" alt="Screenshot 2022-10-29 at 2 24 39 pm" src="https://user-images.githubusercontent.com/54896/198843483-1a6431be-54f1-44a2-98e4-363d19d5afab.png">

You can see from the screenshot that this isn't the case.

### Reproduction Link

TBC

### Steps to Reproduce

1. Install gatsby-plugin-i18n
2. Create a index.uk.js page which imports and exports per screenshot above

### Expected Result

No warnings

### Actual Result

A warning for every page

### Environment

```shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Max
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /var/folders/g4/zbzrvqn10k9g0zt_smyjjfrm0000gn/T/yarn--1667062391857-0.7112126466391109/node
    Yarn: 1.22.17 - /var/folders/g4/zbzrvqn10k9g0zt_smyjjfrm0000gn/T/yarn--1667062391857-0.7112126466391109/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Languages:
    Python: 3.10.0 - /Users/aidanlister/.pyenv/shims/python
  Browsers:
    Chrome: 106.0.5249.119
    Safari: 16.1
  npmPackages:
    gatsby: ^4.24.4 => 4.24.4
    gatsby-cli: ^4.13.0 => 4.24.0
    gatsby-plugin-gatsby-cloud: ^4.21.0 => 4.24.0
    gatsby-plugin-google-tagmanager: ^4.24.0 => 4.24.0
    gatsby-plugin-i18n: ^1.0.1 => 1.0.1
    gatsby-plugin-image: ^2.13.0 => 2.24.0
    gatsby-plugin-manifest: ^4.13.0 => 4.24.0
    gatsby-plugin-no-sourcemaps: ^4.24.0 => 4.24.0
    gatsby-plugin-pathdata: ^1.1.0 => 1.1.0
    gatsby-plugin-perf-budgets: ^0.0.18 => 0.0.18
    gatsby-plugin-react-helmet: ^5.24.0 => 5.24.0
    gatsby-plugin-robots-txt: ^1.7.1 => 1.7.1
    gatsby-plugin-sass: ^5.13.0 => 5.24.0
    gatsby-plugin-sharp: ^4.13.0 => 4.24.0
    gatsby-plugin-sitemap: ^5.24.0 => 5.24.0
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.27 => 1.1.27
    gatsby-source-contentful: ^7.14.0 => 7.22.0
    gatsby-source-filesystem: ^4.13.0 => 4.24.0
    gatsby-transformer-sharp: ^4.13.0 => 4.24.0
```

**Comment by LekoArts** [comment] 2022-10-31 06:55
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2022-11-07 07:01
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2022-11-07 07:01 UTC
Labels: type: bug, status: needs reproduction
