### ISSUE TITLE
Problem in iterating graphql data in ... on WpPage

### ISSUE THREAD

**Issue by rcapdepaula** [gatsbyjs/gatsby#30804] opened 2021-04-10 16:47 UTC
`const PageTemplate = ({ data }) => {
  const orderdChild = [...data.wpPage.wpChildren.nodes].sort((x, y) => {
    if (x.title < y.title) return -1
    if (x.title > y.title) return 1
    return 0
  })
  return (....`

Graphql:

` wpChildren {
        nodes {
          ... on WpPage {
            id
            uri
            title
          }
        }
      }`

Error:
**Invalid attempt to spread non-iterable instance.**

**Comment by vladar** [comment] 2021-04-11 17:17
Hi @rcapdepaula 

Please edit the issue as described here: https://www.gatsbyjs.com/contributing/how-to-file-an-issue/

Also, to help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-04-20 08:15
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-04-20 08:15 UTC
Labels: status: needs reproduction, topic: WordPress
