### ISSUE TITLE
Aint No Deployo

### ISSUE THREAD

**Issue by JimTheMan** [gatsbyjs/gatsby#8965] opened 2018-10-09 20:09 UTC
## Description

Errors when I deploy:

![raw_plants_foundation](https://user-images.githubusercontent.com/5354163/46695439-8d156280-cbdd-11e8-8635-1c7114d51d93.jpg)

### Steps to reproduce

in gatsby.config:

```
module.exports = {
  siteTitle: "Derp Foundation", // <title>
  shortSiteTitle: "RPF", // <title> ending for posts and pages
  siteDescription: "Enlightening humans on derp and derp.",
  siteUrl: "https://jimtheman.github.io",
  pathPrefix: "/Raw-Plants-Foundation-Website",
  siteImage: "preview.jpg",
  siteLanguage: "en",
  // author
  authorName: "Jim Lynch",
  authorTwitterAccount: "webwhizjim",
  // info
  headerTitle: "The Raw Plants Foundation",
  headerSubTitle: "Changing the world one raw plant at a time.",
  // manifest.json
  manifestName: "RPF",
  manifestShortName: "RPF", // max 12 characters
  manifestStartUrl: "/index.html",
  manifestBackgroundColor: "white",
  manifestThemeColor: "#666",
  manifestDisplay: "standalone",
  // social
  authorSocialLinks: [
    { name: "github", url: "https://github.com/rawplants" },
    { name: "twitter", url: "https://twitter.com/rawplants" },
    { name: "facebook", url: "http://facebook.com/rawplants" }
  ]
};

```

### Expected result
it worky path prefix

### Actual result

no worky 

### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.11.1 - /usr/local/bin/node
    npm: 5.6.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 69.0.3497.100
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.4 => 2.0.19 
    gatsby-image: ^2.0.5 => 2.0.13 
    gatsby-plugin-algolia: ^0.1.0 => 0.1.1 
    gatsby-plugin-catch-links: ^2.0.2 => 2.0.4 
    gatsby-plugin-feed: ^2.0.5 => 2.0.7 
    gatsby-plugin-google-analytics: ^2.0.6 => 2.0.6 
    gatsby-plugin-layout: ^1.0.2 => 1.0.3 
    gatsby-plugin-manifest: ^2.0.2 => 2.0.4 
    gatsby-plugin-netlify: ^2.0.0 => 2.0.1 
    gatsby-plugin-offline: ^2.0.5 => 2.0.5 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.0 
    gatsby-plugin-react-svg: ^2.0.0 => 2.0.0 
    gatsby-plugin-sharp: ^2.0.5 => 2.0.6 
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.1 
    gatsby-plugin-styled-jsx: ^3.0.1 => 3.0.1 
    gatsby-plugin-styled-jsx-postcss: ^2.0.2 => 2.0.2 
    gatsby-remark-copy-linked-files: ^2.0.5 => 2.0.5 
    gatsby-remark-emojis: ^0.2.3 => 0.2.3 
    gatsby-remark-external-links: ^0.0.4 => 0.0.4 
    gatsby-remark-images: ^2.0.1 => 2.0.3 
    gatsby-remark-prismjs: ^3.0.0 => 3.0.1 
    gatsby-remark-responsive-iframe: ^2.0.5 => 2.0.5 
    gatsby-remark-smartypants: ^2.0.5 => 2.0.5 
    gatsby-source-filesystem: ^2.0.1 => 2.0.2 
    gatsby-transformer-remark: ^2.1.3 => 2.1.6 
    gatsby-transformer-sharp: ^2.1.1 => 2.1.3 
  npmGlobalPackages:
    gatsby-cli: 2.4.2

**Comment by pieh** [comment] 2018-10-09 21:09
Do you build using `gatsby build --prefix-paths`? It should worky then

**Comment by pieh** [comment] 2018-10-09 21:34
Can you try-o deleting `.cache` and running `gatsby build --prefix-paths` and deploying again? I think this might be same issue as https://github.com/gatsbyjs/gatsby/issues/7881

**Comment by JimTheMan** [comment] 2018-10-09 21:55
Will try-o and circle back,. L

On Oct 9, 2018 5:35 PM, "Michal Piechowiak" <notifications@github.com>
wrote:

Can you try-o deleting .cache and running gatsby build --prefix-paths and
deploying again? I think this might be same issue as #7881
<https://github.com/gatsbyjs/gatsby/issues/7881>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gatsbyjs/gatsby/issues/8965#issuecomment-428360935>,
or mute
the thread

**Comment by JimTheMan** [comment] 2018-10-09 22:05
Ok will give it a go-o and circle back to the squadron hq. thanks again,
panda lava sky leader.

**Comment by JimTheMan** [comment] 2018-10-10 14:05
please sir, is there anyone who can think of to be done?

**Comment by DSchau** [comment] 2018-10-10 14:12
@JimTheMan would you be able to provide a repo we can take a look at? It seems unlikely that this is broken in Gatsby, because we have e2e tests validating this behavior!

Thank you!

**Comment by JimTheMan** [comment] 2018-10-10 15:18
thanks @DSchau, it's this repository: https://github.com/JimTheMan/Raw-Plants-Foundation-Website

**Comment by JimTheMan** [comment] 2018-10-10 15:23
btw love this pic of you :D

![duntim](https://user-images.githubusercontent.com/5354163/46747317-f00b0600-cc7e-11e8-848d-4de13dcd68e7.jpg)

**Comment by DSchau** [comment] 2018-10-10 15:38
Lots of issues with that site (mostly the Cat2Page.js page), but the main issue is that pathPrefix isn't actually set in your config.

Setting up pathPrefix in [content/meta/config.js](https://github.com/JimTheMan/Raw-Plants-Foundation-Website/blob/master/content/meta/config.js#L6) will ensure that pathPrefix is actually set. If it's not set in gatsby-config.js (it's not currently), then the build step won't work.

Additionally, `pathPrefix` needs to be at the top level of [gatsby-config.js](https://github.com/JimTheMan/Raw-Plants-Foundation-Website/blob/master/gatsby-config.js#L38), not nested within siteMetadata.

So if that's added, and you ensure that `gatsby build --prefix-paths` is used prior to deploying, this should work just dandy.

Going to close this as answered, thanks for the question!

**Closed by DSchau** 2018-10-10 15:38 UTC
Labels: type: question or discussion

**Comment by DSchau** [comment] 2018-10-10 16:31
Whoa! I didn't intend to be negative, sorry about that! It didn't build for me, and I had to solve a few issues to get it building, that's all I meant!

Sorry for the confusion here!

**Comment by JimTheMan** [comment] 2018-10-10 16:33
lol it's all good. I more angry about you closing my issue before I confirmed it was solved.

**Comment by DSchau** [comment] 2018-10-10 16:35
@JimTheMan yeah, I can empathize with that. I think it's pretty reasonable to close when the issue was resolved after I fixed it and I confirmed the fix! I tend to treat issues that way, i.e. let's close until we hear differently that it needs to be re-opened.

Not intended to downplay your issue or anything! In the future, I'll be sure to make it clear that the issue is closed _for now_ but feel free to re-open if the fix didn't work or further info comes up.

**Comment by JimTheMan** [comment] 2018-10-10 16:52
It's ok. I tend to troll too much. 👺

Anyway, that's for the help and have fun working at gatsby

**Comment by JimTheMan** [comment] 2018-10-10 18:04
hmm actually it still doesn't work properly. Now whenever I click on a link it puts the prefix path twice...

see [this page](https://jimtheman.github.io/Raw-Plants-Foundation-Website/what-we-do/) and try clicking on "contact us".

The link is just a link in markdown: `[contact us](/contact)`
