### ISSUE TITLE
Error: vips_colourspace: no known route from 'cmyk' to 'srgb' 

### ISSUE THREAD

**Issue by discovrbookings** [gatsbyjs/gatsby#9980] opened 2018-11-16 15:51 UTC
Sandbox of error - [https://codesandbox.io/s/jj597mrvmw](https://codesandbox.io/s/jj597mrvmw)

I am having an issue with some data returned from an external **API** to my **GatsbyJS* site.

More specifically, the issue appears to be when generating and processing some image thumbnails with `gatsby-image` and `gatsby-plugin-sharp` using the API `...GatsbyImageSharpFluid` on **GraphQL** queries.

```
  error
The GraphQL query from /sandbox/src/templates/event.js failed.

Errors:
  icc_transform: no input profile
  vips_colourspace: no known route from 'cmyk' to 'srgb'


  GraphQL request (9:11)
   8:         childImageSharp {
   9:           fluid(maxWidth: 1800) {
                ^
  10:             ...GatsbyImageSharpFluid

URL path:
  /event/fastlove-:-a-tribute-to-george-michael/
Context:
  {
    "id": "5f9b3031-ef73-5884-9893-da56317daf3b",
    "slug": "fastlove-:-a-tribute-to-george-michael"
  }
Plugin:
  none
Query:
  query sandboxSrcTemplatesEventJs3738613760(
    $slug: String!
  ) {
    allFile(filter: {fields: {slug: {eq: $slug}}}) {
      edges {
        node {
          id
          childImageSharp {
            fluid(maxWidth: 1800) {
              ...GatsbyImageSharpFluid
            }
          }
          fields {
            name
            slug
          }
        }
      }
    }
  }

  fragment GatsbyImageSharpFluid on ImageSharpFluid {
    base64
    aspectRatio
    src
    srcSet
    sizes
  }


(sharp:5650): GLib-CRITICAL **: 16:17:47.149: g_hash_table_lookup: assertion 'hash_table != NULL' failed

(sharp:5650): GLib-CRITICAL **: 16:17:47.149: g_hash_table_insert_internal: assertion 'hash_table != NULL' failed

(sharp:5650): GLib-CRITICAL **: 16:17:47.149: g_hash_table_lookup: assertion 'hash_table != NULL' failed
Segmentation fault (core dumped)
error Command failed with exit code 139.

```
I could just filter this image out but am sure someone else would have faced this problem.

`gatsby-node.js` is as

    exports.sourceNodes = async ({ actions, store, cache, createNodeId }) => {
      const { createNode, createNodeField } = actions;
      const { data } = await axios.get(API_URI);
    
      for (const event of data._embedded.events) {
        let fileNode;
        let output = [];
        let filterResults = event.images.filter(e => e.width >= 1900);
        output.push(...filterResults);
        try {
          fileNode = await createRemoteFileNode({
            url: output[0].url,
            cache,
            store,
            createNode,
            createNodeId,
          });
          await createNodeField({
            node: fileNode,
            name: 'EventImage',
            value: 'true'
          });
          await createNodeField({
            node: fileNode,
            name: 'name',
            value: event.name
          });
        } catch (error) {
          console.warn('error creating node', error);
        }
      }
    };
```
exports.createPages = ({ graphql, actions }) => {
  const { createPage } = actions

  return new Promise((resolve, reject) => {
    resolve(
      graphql(`
        {
          allFile(filter: {fields: {EventImage: {eq: "true"}}}) {
            edges {
              node {
                id
                fields {
                  slug
                }
              }
            }
          }
        }
      `).then(result => {
        if (result.errors) {
          reject(new Error(result.errors))
        }
        const postTemplate = path.resolve(`src/templates/event.js`)
        _.each(result.data.allFile.edges, edge => {
          createPage({
            path: `/event/${edge.node.fields.slug}/`,
            component: slash(postTemplate),
            context: {
              id: edge.node.id,
              slug: edge.node.fields.slug
            }
          })
        })
        return
      })
    )
  });
}
```

`gatsby-config.js` is 
```
module.exports = {
  plugins: [
    `ticketmaster-events-feed`,
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-styled-components`,
    `gatsby-plugin-sharp`,
    `gatsby-transformer-sharp`,
    `gatsby-transformer-remark`
  ]
};
```
![screen shot 2018-11-17 at 2 19 30 am](https://user-images.githubusercontent.com/37088656/48631804-4baf7880-ea0f-11e8-88d2-b85e805e10f9.png)

**Comment by pieh** [comment] 2018-11-23 13:07
Closing as this is duplicate of #10040

**Closed by pieh** 2018-11-23 13:07 UTC
