### ISSUE TITLE
[gatsby-plugin-twitter] Twitter script not being loaded on first load - works after reload

### ISSUE THREAD

**Issue by bogdancss** [gatsbyjs/gatsby#32771] opened 2021-08-11 10:20 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

The Twitter script is not being loaded when first loading the page. However, it does seem to load after a page refresh.

### Reproduction Link

https://kaizen.co.uk/blog/seo/the-most-unorthodox-and-creative-seo-strategies/

### Steps to Reproduce

1. Load the page
2. Observe that the twitter blockquotes are not being replaced with the embeded cards
3. Checking the page source and the elements panel, the script is not loaded
4. After a page reload - the script is then loaded and the blockquotes are replaced with the twitter embeded cards
...

### Expected Result

The Twitter cards should consistently load on first load as well as on all consequent page loads.

### Actual Result

The Twitter cards are not being loaded on initial page load.

### Environment

```shell
System:
  OS: macOS 11.5.1
  CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Shell: 5.8 - /bin/zsh
Binaries:
  Node: 14.15.1 - /usr/local/bin/node
  npm: 7.13.0 - /usr/local/bin/npm
Languages:
  Python: 2.7.16 - /usr/bin/python
Browsers:
  Chrome: 92.0.4515.131
  Firefox: 90.0.2
  Safari: 14.1.2
npmPackages:
  gatsby: ^3.11.1 => 3.11.1
  gatsby-plugin-canonical-urls: ^3.11.0 => 3.11.0
  gatsby-plugin-catch-links: ^3.11.0 => 3.11.0
  gatsby-plugin-force-trailing-slashes: ^1.0.5 => 1.0.5
  gatsby-plugin-gatsby-cloud: ^2.11.0 => 2.11.0
  gatsby-plugin-gdpr-cookies: ^2.0.6 => 2.0.6
  gatsby-plugin-image: ^1.11.0 => 1.11.0
  gatsby-plugin-manifest: ^3.11.0 => 3.11.0
  gatsby-plugin-no-sourcemaps: ^3.11.0 => 3.11.0
  gatsby-plugin-nprogress: ^3.11.0 => 3.11.0
  gatsby-plugin-polyfill-io: ^1.1.0 => 1.1.0
  gatsby-plugin-preload-fonts: ^2.11.0 => 2.11.0
  gatsby-plugin-react-helmet: ^4.11.0 => 4.11.0
  gatsby-plugin-sharp: ^3.11.0 => 3.11.0
  gatsby-plugin-sitemap: ^4.7.0 => 4.7.0
  gatsby-plugin-styled-components: ^4.11.0 => 4.11.0
  gatsby-plugin-twitter: ^3.11.0 => 3.11.0
  gatsby-source-filesystem: ^3.11.0 => 3.11.0
  gatsby-source-wordpress: ^5.11.0 => 5.11.0
  gatsby-transformer-sharp: ^3.11.0 => 3.11.0
npmGlobalPackages:
  gatsby-cli: 3.11.0
```

**Comment by LekoArts** [comment] 2021-08-16 13:43
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-08-30 07:07
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-08-30 07:07 UTC
Labels: type: bug, status: needs reproduction
