### ISSUE TITLE
Routing between pages returning blank page with react dom production min js errors

### ISSUE THREAD

**Issue by amaan-nadeem** [gatsbyjs/gatsby#24398] opened 2020-05-24 05:00 UTC
## Description
I have been going through a build time page crash issue from a quite while. Throwing error of stack n is not a function when ever i routed between pages after hard reload everything works as expected. Searched each and everything possible but nothing seems to work, im using material ui in my project. Don't whether its an cache issue but when whenever we route between pages through gatsby link app crashes and it returns blank page after hard reload page seems to appear. As i already said i have tried everything i found related to this issue it would be good to know if any solid solution anyone would have to solve this issue. 
And point to notice is that under local server its working fine but on local build or in production this issue coming in.....

### Expected result
Expected result is simply route to each page smoothly without a crash

What should happen?

### Actual result
app.json returning 304 while routing in between while page.json on load returning 200 
![DeepinScreenshot_select-area_20200524095327](https://user-images.githubusercontent.com/44071255/82746021-9ba99100-9da4-11ea-8f9d-ccbc540fb8b1.png)

this is console errors occuring on each time navigating between but on load they disappear. It might be a cache problem but no solution seems to work here.
![DeepinScreenshot_select-area_20200524095256](https://user-images.githubusercontent.com/44071255/82746026-a19f7200-9da4-11ea-9b36-60e67551bac9.png)

I can not make minimal reproduction of this issue as you need to have alot of data atleast to have this error appears like i think page takes some time to returning the data and in between gatsby found that there is no page like the one we are routing to and it returns error while on load it prefetched the data and returns the page fine. 

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by LekoArts** [comment] 2020-05-25 09:14
Hi!

Sadly we can't help you unless you [provide a minimal reproduction][reproduction] as your issue could be anything really. Thanks!

[reproduction]: https://gatsby.dev/reproduction

**Comment by danabrit** [comment] 2020-06-02 22:29
@amaan-nadeem Closing this issue due to no reproduction within 7 days. If you would like to re-open it with a minimal reproduction, we'd be happy to take a look. Thank you!

**Closed by danabrit** 2020-06-02 22:29 UTC
Labels: status: needs reproduction, topic: reach/router and Links
