### ISSUE TITLE
Gatsby v4: The argument 'path' must be a string or Uint8Array without null bytes. Received '/node_modules/es5-ext/array/\x00#/e-index-of.js

### ISSUE THREAD

**Issue by hirenoble** [gatsbyjs/gatsby#34011] opened 2021-11-17 17:47 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I'm upgrading Gatsby from v2 to v4, I followed the migration guide for v2 to v3 and v3 to v4. I'm seeing this error on 
`gatsby develop`
 
the `gatsby build` executes successfully.

### Reproduction Link

https://github.com/adobe/parliament-client-template

### Steps to Reproduce

1. Switch to dev branch and setup a .env.development file following the instructions
2. yarn install
3. yarn develop
...

### Expected Result

localhost:8000 should spin up the site.

### Actual Result

Generating development JavaScript bundle failed

The argument 'path' must be a string or Uint8Array without null bytes. Received
'/Users/hireshah/parliament-client-template/node_modules/es5-ext/array/\x00#/e-index-of.js'

### Environment

```shell
OS: Mac OS
Node: 16.x
Gatsby: 4.1.1
```

**Comment by graysonhicks** [comment] 2021-11-18 03:29
👋 Thanks for the report!  I tried to clone and repro this, but the repo seems to rely on a lot of env vars and won't start.  If there is a way to make a reproduction with env vars that can be public, that would be helpful for debugging.

Just spitballing that that error sounds like it could be coming from `fs`, although the path arguments I see in the `fs` usage in the repo certainly appear to be hardcoded strings.  But maybe the `searchIndex.json` isn't being created as expected?  Then again, the fact that it says the path received is `'/Users/hireshah/parliament-client-template/node_modules/es5-ext/array/\x00#/e-index-of.js'` is odd and makes it seem like something internal.

Again, a repo that can be run would be required for full debugging.

**Comment by graysonhicks** [comment] 2021-11-18 03:31
@hirenoble 🤦 I see the env instructions now, I'll give that a go!

**Comment by graysonhicks** [comment] 2021-11-18 04:36
Unfortunately, seeing some other errors/warnings while trying to build:

during sourceNodes:
>  The Github API didn't return the expected data, returning an empty contributor array. res: {
  "data": {
    "repository": {
      "object": null
    }
  }
}

during createPages:
>"@adobe/parliament-source-changelog" threw an error while running the createPages lifecycle:
>Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "$ref" does not.

I think the repo is missing a`changelog` directory?

**Comment by hirenoble** [comment] 2021-11-18 18:06
@graysonhicks thanks for looking into this! "@adobe/parliament-source-changelog" looks for changelog repo in the source folder, if it's not there it simply skips.

**Comment by graysonhicks** [comment] 2021-11-19 01:18
@hirenoble Okay, the build was taking a while so I cancelled.  So those are expected warnings and I should let the build continue?

**Comment by graysonhicks** [comment] 2021-11-22 18:23
@hirenoble I think this is likely trying to load those JSON files with `fs` which the query engine then can't find.  I'm thinking that change either didn't get documented or not well documented in the migration guide.  I believe any file you are importing that way will need to be imported.  @pieh or @LekoArts can likely confirm.

**Comment by graysonhicks** [comment] 2021-11-22 20:17
After chatting with @pieh, since this is happening during the JS bundling, not the query engine bundling, it is more likely a webpack caching issue.  Is there any way you can make a more minimal reproduction that allows only a subset of the build but still illustrates the bug?  That would allow for investigating in a more timely manner.  Thanks!

**Comment by hirenoble** [comment] 2021-11-22 20:31
@graysonhicks sure, I am creating another repo that would allow minimal reproduction.

**Comment by hirenoble** [comment] 2021-11-22 22:20
@graysonhicks I created a repo to allow minimal reproduction. https://github.com/hirenoble/gatsby-v4-issue-reproduction

Just do `yarn install` and `yarn develop` to see the issue.

**Comment by LekoArts** [comment] 2021-11-23 09:09
@hirenoble I'm not able to run your site as your source plugins are not generating the necessary nodes. You'll need to further slim this down so that we don't need any env vars :)

![image](https://user-images.githubusercontent.com/16143594/142996991-9ed59f63-2063-428e-8a49-d9e42e5a6592.png)

**Comment by hirenoble** [comment] 2021-11-23 15:10
@LekoArts that's weird, which OS you are running on? The repo https://github.com/hirenoble/gatsby-v4-issue-reproduction has an `.env.development` and `.env.production` file with a sample `parliament-docs-template` source part of the repo.

**Comment by pieh** [comment] 2021-11-23 16:27
@hirenoble I saw same thing as @LekoArts when I tried it.

My os info:
```
OS: macOS 11.2.3
Node: 14.17.0
```

When looking again it seems like `parliament-docs-template` is supposed to be git submodule but `.gitmodules` wasn't commited so it ends up being just empty dir when checked out locally so there is no data to source from and I do see some warnings during the build:

```
warn The @adobe/gatsby-source-parliament plugin has generated no Gatsby nodes. Do you need it?
warn The @adobe/parliament-source-changelog plugin has generated no Gatsby nodes. Do you need it?
```

The `path` error on `GithubContributors` shouldn't be related to above (?) and I'm not yet sure why that happen

**Comment by hirenoble** [comment] 2021-11-24 03:31
@pieh @LekoArts I added `parliament-docs-template` as a submodule. Could you please try now?

**Comment by LekoArts** [comment] 2021-11-24 09:26
Checked out the repo in a fresh directory with submodules, same error:

![image](https://user-images.githubusercontent.com/16143594/143210793-b84c5cb0-6a89-4bab-998b-d7f850c66496.png)

**Comment by hirenoble** [comment] 2021-11-24 18:36
[logs_v4.txt](https://github.com/gatsbyjs/gatsby/files/7597912/logs_v4.txt)

I did a fresh clone of the repo, ran `yarn install` and `yarn develop` and it works without these errors. Could you please ensure that you see a `.env.development` and `.env.production` files with below content:
```
GATSBY_SITE_PATH_PREFIX = /navigation
GATSBY_GIT_CORP_TOKEN = XXXX
GATSBY_SOURCE = https://github.com/hirenoble/gatsby-v4-issue-reproduction
GATSBY_SOURCE_TITLE = Gatsby v4 Issue Reproduction
GATSBY_SOURCE_PATTERNS = **/*
GATSBY_SOURCE_BRANCH = main
# Url for your analytics script
GATSBY_LAUNCH_SRC=//assets.adobedtm.com/<id>/launch-<id>.min.js
LOCAL_PROJECT_DIRECTORY=../parliament-docs-template
```

Also, try updating the `LOCAL_PROJECT_DIRECTORY` to be the absolute path to `parliament-docs-template`

**Comment by hirenoble** [comment] 2021-12-01 16:58
@LekoArts @pieh Could you please help? We are blocked due to this issue. Would it be better if we schedule some time to debug this in a quick session?

**Comment by hirenoble** [comment] 2021-12-01 21:41
@KyleAMathews Could you please help me here? I would highly appreciate your attention to this. 🙌  In other thread I saw the same error related to memoizee. But don't see any resolution on this: https://githubmemory.com/repo/gatsbyjs/gatsby/issues/32382

![image](https://user-images.githubusercontent.com/3747836/144318440-52a5b513-c282-4e11-91c9-5c01a6e9afbd.png)

**Comment by graysonhicks** [comment] 2021-12-02 02:35
@hirenoble @LekoArts Okay, I at least figured out the query error blocking above.  It is because `git clone` without `--recursive` leaves the submodule empty even if it is committed.  You can update the repo after you've cloned with:

`git submodule update --init`

The instructions for the reproduction should include: `git clone git@github.com:hirenoble/gatsby-v4-issue-reproduction.git --recursive`.  After running that, I do see the original error.

**Comment by graysonhicks** [comment] 2021-12-02 03:02
FWIW, running `gatsby develop` again after letting the failed one run through seems to complete.  I am thinking it is caching the JS so it doesn't try to create the bundle again.  Running `yarn clean` and `gatsby develop` again and it resurfaces.

**Comment by graysonhicks** [comment] 2021-12-02 03:24
The last successful step I see completing when running with `--verbose` is `Attaching functions to development server`.  There is a `catch` there so it is likely whatever step in the `develop` command runs after that, although I'm having trouble figuring out what that is.

**Comment by hirenoble** [comment] 2021-12-13 17:35
@graysonhicks @LekoArts @pieh @KyleAMathews I really appreciate your efforts into this. But honestly, I was expecting a quicker resolution on this. Could you please prioritize this issue? We are currently blocked due to this. Please 🙌

**Comment by graysonhicks** [comment] 2021-12-13 21:06
@hirenoble Sorry, I don't have any additional insights.  I imagine we will need a stack trace to find this error.  Like I said, I am able to get a successful develop locally after running it a second time.  A build also works.  Not sure if you have tried that to have a look at the schema to see if it looks as expected.  I'll have to leave to deep digging to those more familiar with the webpack internals.  Maybe @wardpeet has some insights.

**Comment by LekoArts** [comment] 2022-03-07 09:55
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2022-03-07 09:55 UTC
Labels: type: bug, status: needs reproduction, topic: build
