### ISSUE TITLE
Building gatsby-links from data removes their children in production

### ISSUE THREAD

**Issue by gosseti** [gatsbyjs/gatsby#1104] opened 2017-06-05 02:56 UTC
I often like to build my navigations from data, e.g. like this:

```
import Link from "gatsby-link"

const links = [{
  to: '/',
  children: 'Index'
}, {
  to: '/blog',
  children: 'Blog'
}]

<ul>
  {links.map(link => (
    <li>
      <Link {...link} />
    </li>
  ))}
</ul>
```

However, when running this in production, the children (text) will appear on first page load, but then navigating to any other pages will cause them to disappear.

**Comment by KyleAMathews** [comment] 2017-06-05 03:49
Could you build a small reproduction for this?

**Comment by gosseti** [comment] 2017-06-05 05:34
Sure!

https://slimy-mind.surge.sh

**Comment by KyleAMathews** [comment] 2017-06-05 05:36
And the source please :-) Need the source to play with the problem / fix it.

**Comment by gosseti** [comment] 2017-06-05 06:16
Sure, it’s up here: https://github.com/gosseti/gatsby/tree/fix/link-children-issue

**Comment by KyleAMathews** [comment] 2017-06-05 18:15
Couldn't reproduce. Dunno what's happening on your end

![out](https://cloud.githubusercontent.com/assets/71047/26796988/45afb34e-49e0-11e7-8a0e-9114edda2453.gif)

**Comment by gosseti** [comment] 2017-06-06 00:41
Is that a live production deployment?

**Comment by KyleAMathews** [comment] 2017-06-06 16:30
Oh no. I'm working on a refactor today of the production runtime so will address this bug there.

**Comment by KyleAMathews** [comment] 2017-07-13 20:40
Hey, closing this out. Lemme know if it's still an issue on the latest release.

**Closed by KyleAMathews** 2017-07-13 20:40 UTC
Labels: bug, v1
