### ISSUE TITLE
Gatsby Build still reading old GraphQL queries

### ISSUE THREAD

**Issue by minimicrowave** [gatsbyjs/gatsby#22855] opened 2020-04-06 12:46 UTC
## Summary
I am new to Gatsby and used the [Gatsby Starter Blog](https://github.com/gatsbyjs/gatsby-starter-blog) as a starting template. I changed the GraphQL queries to fit my current content. However, once I changed the original queries i.e.

> allMarkdownRemark(sort: { fields: [frontmatter___date], order: [DESC] }) 

to 

> allMarkdownRemark(sort: { fields: [frontmatter___year], order: [DESC] }),

`gatsby build` fails.

This is the error shown on `gatsby build`:
```
  Error: Expected type MarkdownRemarkFieldsEnum, found frontmatter___date. Did you mean the enum value frontmatter___title, frontmatter___year, frontmatter___description, frontmatter___cover___id, or frontmatter___  cover___dir?
  GraphQL request:7:22
  6 |             order: DESC,
  7 |             fields: [frontmatter___date]
    |                      ^
  8 |           }, Cannot query field "date" on type "MarkdownRemarkFrontmatter".
  GraphQL request:14:17
  13 |                 title
  14 |                 date
     |                 ^
  15 |               }
```

To reiterate, I do not have any fields titled `date` nor did I have ` fields: [frontmatter___date]` anywhere in my project. The queries and everything else are working fine on `gatsby develop`.

How should I go about resolving this issue?

## Relevant information
I have tried  `gatsby clean`, removing cache and removing and reinstalling package.json, but to no avail.

### Environment (if relevant)
```
  "gatsby": "^2.19.45",
    "gatsby-image": "^2.2.44",
    "gatsby-plugin-feed": "^2.3.29",
    "gatsby-plugin-google-analytics": "^2.1.38",
    "gatsby-plugin-manifest": "^2.2.48",
    "gatsby-plugin-offline": "^3.0.41",
    "gatsby-plugin-react-helmet": "^3.1.24",
    "gatsby-plugin-sharp": "^2.4.13",
    "gatsby-plugin-typography": "^2.3.25",
    "gatsby-remark-copy-linked-files": "^2.1.40",
    "gatsby-remark-images": "^3.1.50",
    "gatsby-remark-prismjs": "^3.3.36",
    "gatsby-remark-responsive-iframe": "^2.2.34",
    "gatsby-remark-smartypants": "^2.1.23",
    "gatsby-source-filesystem": "^2.1.56",
    "gatsby-transformer-remark": "^2.6.59",
    "gatsby-transformer-sharp": "^2.3.19",
```

**Comment by LekoArts** [comment] 2020-04-06 13:14
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by vladar** [comment] 2020-04-14 20:24
Gatsby Starter Blog has a `date` field here: https://github.com/gatsbyjs/gatsby-starter-blog/blame/master/content/blog/hello-world/index.md#L3

So this is a valid query:
```
allMarkdownRemark(sort: { fields: [frontmatter___date], order: [DESC] })
```

But this is not:
```
allMarkdownRemark(sort: { fields: [frontmatter___year], order: [DESC] }),
```

Simply because there is no `year` field in the frontmatter.

**Comment by dsanderson90** [comment] 2020-05-09 14:30
I am experieincing what looks to be the same issue on this project https://github.com/dsanderson90/gatsby-source-pokeapi

**Comment by wardpeet** [comment] 2020-05-13 13:41
@dsanderson90 could you elaborate what problem you're seeing?

**Comment by dsanderson90** [comment] 2020-05-13 13:54
Unfortunately I can't reproduce the bug because I rebuilt the project, force pushed and erased the history of the repo :( Here was the behavior - when I would run gatsby develop or build I was seeing an old GQL query and and console.log that had been removed from `gatsby-node.js`. I tried clearing the cache with gatsby clean, removing node_modules/reinstalling, and deleting the lock files all to no avail.

**Comment by vladar** [comment] 2020-05-19 10:29
Thank you for opening this, @minimicrowave 

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

@dsanderson90 Please open a new issue if you see it again. Thanks!

**Closed by vladar** 2020-05-19 10:29 UTC
Labels: status: awaiting author response, status: needs reproduction, topic: GraphQL
