### ISSUE TITLE
[gatsby-image] alt property is not shown

### ISSUE THREAD

**Issue by winstonma** [gatsbyjs/gatsby#20613] opened 2020-01-15 04:18 UTC
## Description

There is no observation problem. Just the SEO checker find out that the alt property is missing.

### Steps to reproduce

```
gatsby new gatsby-site
cd gatsby-site
gatsby develop
```

Then go to the src\components\image.js and replace the line from
`return <Img fluid={data.placeholderImage.childImageSharp.fluid} />`
with
`return <Img fluid={data.placeholderImage.childImageSharp.fluid} alt="test" />`

### Expected result

Open the test page on browser and inspect the astronaut. I would expect the image would have the `alt="test"` property and with the word test.

### Actual result

Instead it shows `alt=""` on the **outmost** image div.

### Environment

```
  System:
    OS: Windows 10 10.0.19041
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.6
  Browsers:
    Edge: 44.19041.1.0
  npmPackages:
    gatsby: ^2.18.22 => 2.18.22
    gatsby-image: ^2.2.38 => 2.2.38
    gatsby-plugin-manifest: ^2.2.37 => 2.2.37
    gatsby-plugin-offline: ^3.0.31 => 3.0.31
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.21
    gatsby-plugin-sharp: ^2.3.13 => 2.3.13
    gatsby-source-filesystem: ^2.1.46 => 2.1.46
    gatsby-transformer-sharp: ^2.3.12 => 2.3.12
```

**Comment by vladar** [comment] 2020-01-15 13:44
I could not reproduce this. For me, it puts `alt` attribute to `img` tag as expected and not to the outmost div:

```html
<div class=" gatsby-image-wrapper" style="position:relative;overflow:hidden">
    <div style="width:100%;padding-bottom:100%"></div>
    <img src="..."
         alt="test"
         style="position:absolute;top:0;left:0;width:100%;height:100%;object-fit:cover;object-position:center;opacity:1;transition-delay:500ms"/>
    <noscript>
        <picture>
            <source srcset="..."
                    sizes="(max-width: 300px) 100vw, 300px"/>
            <img loading="lazy" sizes="(max-width: 300px) 100vw, 300px" srcset="..."
                 src="..."
                 alt="test"
                 style="position:absolute;top:0;left:0;opacity:1;width:100%;height:100%;object-fit:cover;object-position:center"/>
        </picture>
    </noscript>
</div>
```

I guess we need more details. Can you build the site and demonstrate this in the resulting HTML (and maybe share the repo where you could reproduce this)? Also, I'd suggest disabling any browser plugins when doing this.

**Comment by vladar** [comment] 2020-01-17 07:06
@winstonma The [line in the repo](https://github.com/winstonma/gatsby-image-test/blob/33979439123af473b99c396ebb1a76e50885bb83/src/components/image.js#L29) has no alt tag:

```js
return <Img fluid={data.placeholderImage.childImageSharp.fluid} />
```

And the Netlify site has `alt=""` for both `img` tags (there is no `alt="test"`). Am I missing something?

**Comment by winstonma** [comment] 2020-01-17 07:56
@vladar Sorry you are right. I wrongly deploy the wrong repo. After pointing to the right repo the problem is gone.

But the problem exist on [my website](https://5e21227cda07d9000790b0e8--go-ahead.netlify.com/), please check the **Concept Development & Script Writing** photo.

**Comment by winstonma** [comment] 2020-01-17 08:04
@vladar Sorry I pointed the Netlify site to the wrong deployment. The correct repo is [here](https://github.com/winstonma/gatsby-starter-default). And after pointing the Netlify to the correct repo the error is gone.

However when I clone the repo onto my PC, which is running Win10, and build it. I saw this missing alt locally. Just wonder if it relates to Win10?

The reason why I am asking is because I saw the same problem when I develop and the problem is gone in Netlify.

**Comment by vladar** [comment] 2020-01-17 08:57
Maybe you can build it on Windows and publish your `public` folder on GitHub? I just tried building your repo on my local Windows 10 and it worked fine (`alt="test"`), so it is something else.

**Comment by winstonma** [comment] 2020-01-17 09:24
I added the public folder in my [Repo](https://github.com/winstonma/gatsby-starter-default).

Thanks for checking

**Comment by vladar** [comment] 2020-01-17 09:28
Hm, but the `index.html` has an empty body:

```html
<body><div id="___gatsby"></div><script src="/commons.js"></script></body>
```

**Comment by winstonma** [comment] 2020-01-17 09:44
Sorry I published after running `gatsby develop`.

After the build it seems it is okay. But I saw the problem in `gatsby develop`. Not sure if they have any relationship.

**Comment by vladar** [comment] 2020-01-17 10:23
I think it is by design. See #8579 and #8671 for some details. Basically Gatsby puts a placeholder image on top of an actual image. And when the placeholder is visible we hide its `alt` tag to prevent it from being read twice on screen readers (so that only `alt` of the actual `img` tag is read).

I am marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. I hope we managed to help and thank you for using Gatsby! 💜

**Closed by vladar** 2020-01-17 10:23 UTC
Labels: status: needs reproduction

**Comment by winstonma** [comment] 2020-01-17 10:52
Thanks for your time.
