### ISSUE TITLE
Gatsby Develop: Generating image thumbnails never ends

### ISSUE THREAD

**Issue by ElijahCano33** [gatsbyjs/gatsby#22649] opened 2020-03-30 00:33 UTC
## Description
I am trying to setup the Gatsby docs locally on my Windows computer. I have followed all the step described on this [page from Gatsby's docs](https://www.gatsbyjs.org/contributing/docs-contributions/#docs-site-setup-instructions) under the header titled "Docs site setup instructions." When I ran the command "gatsby develop", the command never finishes. When it begins generating the image thumbnails, it just stays there for hours on end continuing to generate them.  The generating image thumbnails percentage has gone over 8000% for me.

### Steps to reproduce
* Clone a new fork of the gatsby project:  git clone --depth=1 https://github.com/<your-username>/gatsby.git.
* cd www
*  yarn install
*  gatsby develop

### Expected result
To run the Gatsby docs locally.

### Actual result
Gatsby Develop never finishes because generating image thumbnails goes on for hours on end.

### Environment
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
  Binaries:
    Node: 13.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Users\Owner\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.6.4
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.18.8 => 2.20.8
    gatsby-cli: ^2.11.3 => 2.11.3
    gatsby-core-utils: ^1.0.28 => 1.1.1
    gatsby-design-tokens: ^2.0.1 => 2.0.4
    gatsby-image: ^2.2.34 => 2.3.1
    gatsby-plugin-canonical-urls: ^2.1.16 => 2.2.1
    gatsby-plugin-catch-links: ^2.1.19 => 2.2.1
    gatsby-plugin-emotion: ^4.1.22 => 4.2.1
    gatsby-plugin-feed: ^2.3.23 => 2.4.1
    gatsby-plugin-google-analytics: ^2.1.29 => 2.2.2
    gatsby-plugin-google-tagmanager: ^2.1.18 => 2.2.1
    gatsby-plugin-guess-js: ^1.1.26 => 1.2.1
    gatsby-plugin-layout: ^1.1.16 => 1.2.1
    gatsby-plugin-mailchimp: ^2.2.3 => 2.2.3
    gatsby-plugin-manifest: ^2.2.31 => 2.3.3
    gatsby-plugin-mdx: ^1.0.59 => 1.1.3
    gatsby-plugin-netlify: ^2.1.28 => 2.2.1
    gatsby-plugin-netlify-cache: ^0.1.0 => 0.1.0
    gatsby-plugin-nprogress: ^2.1.15 => 2.2.1
    gatsby-plugin-offline: ^3.0.27 => 3.1.2
    gatsby-plugin-react-helmet: ^3.1.16 => 3.2.1
    gatsby-plugin-sharp: ^2.3.5 => 2.5.3
    gatsby-plugin-sitemap: ^2.2.22 => 2.3.1
    gatsby-plugin-theme-ui: ^0.3.0 => 0.3.0
    gatsby-plugin-twitter: ^2.1.15 => 2.2.1
    gatsby-plugin-typography: ^2.3.18 => 2.4.1
    gatsby-remark-autolink-headers: ^2.1.19 => 2.2.1
    gatsby-remark-code-titles: ^1.1.0 => 1.1.0
    gatsby-remark-copy-linked-files: ^2.1.31 => 2.2.1
    gatsby-remark-embedder: ^1.11.0 => 1.16.0
    gatsby-remark-graphviz: ^1.1.18 => 1.2.1
    gatsby-remark-http-to-https: ^1.0.2 => 1.0.2
    gatsby-remark-images: ^3.1.35 => 3.2.1
    gatsby-remark-normalize-paths: ^1.0.0 => 1.0.0
    gatsby-remark-prismjs: ^3.3.25 => 3.4.1
    gatsby-remark-responsive-iframe: ^2.2.28 => 2.3.1
    gatsby-remark-smartypants: ^2.1.17 => 2.2.1
    gatsby-source-airtable: ^2.0.12 => 2.1.0
    gatsby-source-filesystem: ^2.1.40 => 2.2.2
    gatsby-source-git: ^1.0.2 => 1.0.2
    gatsby-source-npm-package-search: ^2.1.19 => 2.2.1
    gatsby-transformer-csv: ^2.1.19 => 2.2.1
    gatsby-transformer-documentationjs: ^4.1.20 => 4.2.1
    gatsby-transformer-remark: ^2.6.39 => 2.7.1
    gatsby-transformer-screenshot: ^2.1.44 => 2.2.1
    gatsby-transformer-sharp: ^2.3.7 => 2.4.3
    gatsby-transformer-yaml: ^2.2.18 => 2.3.1

**Comment by vladar** [comment] 2020-04-01 14:02
Hi @ElijahCano33 !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by ElijahCano33** [comment] 2020-04-02 17:08
Hi vladar,

Thank you for responding. I wouldn't mind at all to create a minimal reproduction issue, but I am not sure how to go about doing so with my specific problem as I am just simply trying to setup the Gatsby docs locally on my computer so I can begin contributing. I listed the steps to reproduce the issue. I am not sure if I should add more details to them.

**Comment by moonmeister** [comment] 2020-04-06 08:41
@ElijahCano33 Hey, this is a known issue...Gatsby is literally screen-shoting hundreds of websites during this process...it's painful. #13699 was opened, in part, to resolve issues like this...but really hasn't gone anywhere. 

It is my opinion that some serious work needs to be done on the Gatsby www/repo in this area as it's becoming unrealistic for those without massive bandwidth, processing power, and time to contribute to the Gatsby docs. 

The only suggestion i have is just to not run development on your local machine. Create a branch, and open a draft PR with your changes. This will create a longer development cycle but it means your changes will be built in the cloud and you should be able to see Netlify site or gatsby preview site with those changes (assuming they're still doing those on PRs).

The other only ray of hope is that as long as you don't change any plugins or delete the cache, this process gets a lot faster...so let it run.  Then hope and pray you don't invalidate the cache.

sorry there's no real solution...I with there was.

**Comment by LekoArts** [comment] 2020-04-06 09:00
Thank you for opening this!

You should skip the screenshot part as written out here: https://github.com/gatsbyjs/gatsby/tree/master/www#running-slow-build-screenshots-placeholder

The initial startup will take time nevertheless, afterwards you shouldn't clear your cache. It'a non-ideal situation and we'll do some work much needed work on the site (including the showcase etc.) but until then this is the only advice we can give :/

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2020-04-06 09:00 UTC
Labels: status: confirmed, topic: website

**Comment by moonmeister** [comment] 2020-04-06 09:03
I'm glad there's a partial solution at least!

**Comment by ElijahCano33** [comment] 2020-04-14 15:37
Thank you guys for the assistance. The "skip the screenshot" solution worked for me. Cheers!
