### ISSUE TITLE
Debugging Gatsby Build. No Page or Line # Given

### ISSUE THREAD

**Issue by Jacob124** [gatsbyjs/gatsby#25603] opened 2020-07-08 11:21 UTC
This has given me a few headaches now. I've been trying to build my e-commerce site with Gatsby and I keep getting errors I didn't have in development. I keep getting the common error `'ReferenceError: window is not defined'` but I get no line number or code. 
![image](https://user-images.githubusercontent.com/15256522/86912356-d5cbb980-c0ea-11ea-8b5a-0116550a2143.png)
A quick project search proves my code doesn't reference the window object, so it must be in a dependency. How can I know which one?

## Question
How can I get Gatsby to output more robust information about the build failure? Looking at other people's issues shows that most have exactly that: A page and line number to where the error is being thrown. Is this a configuration? 

I didn't think the gatsby API files were necessary to this question but I will gladly add them if you need me to.

**Comment by LekoArts** [comment] 2020-07-08 11:56
This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/25507 - please post a reproduction there.

**Closed by LekoArts** 2020-07-08 11:56 UTC
Labels: type: question or discussion
