### ISSUE TITLE
gatsby build 出来的访问目录是否可以更改

### ISSUE THREAD

**Issue by tgy3300** [gatsbyjs/gatsby#13108] opened 2019-04-04 02:46 UTC
比如这个 <script src="/app-22adb05f700e9fcdf5a5.js" async="">
能否在 gatsby build 后，自动变成我想要的访问目录

比如就成
<script src="https://s1.aaa.com/app-22adb05f700e9fcdf5a5.js" async="">

或者

<script src="/a/test/app-22adb05f700e9fcdf5a5.js" async="">

**Comment by pieh** [comment] 2019-04-04 14:33
Hey, I used google translate to try to understand what do you mean.

For the first one:
`<script src="https://s1.aaa.com/app-22adb05f700e9fcdf5a5.js" async="">` - right now this is not possible - we are working on support for that - see https://github.com/gatsbyjs/gatsby/pull/12128 . There you can define `assetPrefix`, but you would need use test release of gatsby as described by Dustin in https://github.com/gatsbyjs/gatsby/pull/12128#issuecomment-477679398

The second one:
`<script src="/a/test/app-22adb05f700e9fcdf5a5.js" async="">` - you should be able to use Path Prefix ( https://www.gatsbyjs.org/docs/path-prefix/ ) - just note that this will change not only paths to scripts and assets - but also change the paths of pages

**Comment by tgy3300** [comment] 2019-04-05 06:31
感谢，你的回答很赞，已经解决

**Comment by LekoArts** [comment] 2019-04-05 08:44
Seems like the issue is resolved 👍 
Closing this then :)

**Closed by LekoArts** 2019-04-05 08:44 UTC
Labels: type: question or discussion
