### ISSUE TITLE
Adding Tailwind to Gatsby Getting Flicker of Unstyled Content (FOUC)

### ISSUE THREAD

**Issue by chadalen** [gatsbyjs/gatsby#28805] opened 2020-12-31 04:12 UTC
## Description

I'm trying to use Tailwind in my Gatsby project and I'm seeing a flicker of unstyled content when I try reloading the page.

**This only happens in development** environment (Using `gatsby develop`)

The code is here
https://github.com/chadalen/personal-website/tree/gatsby-issue

For setting up Tailwindcss with Gatsby I have tried following these guides
https://tailwindcss.com/docs/guides/gatsby
https://www.gatsbyjs.com/docs/how-to/styling/tailwind-css/

### Steps to reproduce

1. Run the following commands
```
git clone https://github.com/chadalen/personal-website.git
cd personal-website
git fetch
git checkout -t origin/gatsby-issue
npm install or yarn
npm run start or yarn start
```

2. Open a new tab, go to http://localhost:8000/ 
3. Refresh the page you should see the flicker of unstyled content
![2020-12-30 22 47 43](https://user-images.githubusercontent.com/12568665/103394066-382ed100-4af4-11eb-877d-4b43d5ea72fc.gif)

### Expected result

There should not be any unstyled content upon loading the page.

### Actual result

There is unstyled content upon loading the page.

### Environment

  System:
    OS: macOS 11.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 3.1.2 - /usr/local/bin/fish
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 87.0.4280.88
    Edge: 87.0.664.66
    Firefox: 78.0.2
    Safari: 14.0.3
  npmPackages:
    gatsby: ^2.25.0 => 2.29.3 
    gatsby-image: ^2.4.7 => 2.8.0 
    gatsby-plugin-anchor-links: ^1.1.0 => 1.2.0 
    gatsby-plugin-html-attributes: ^1.0.5 => 1.0.5 
    gatsby-plugin-manifest: ^2.2.29 => 2.9.1 
    gatsby-plugin-netlify-cms: ^4.3.10 => 4.7.0 
    gatsby-plugin-postcss: ^3.4.0 => 3.4.0 
    gatsby-plugin-react-helmet: ^3.1.0 => 3.7.0 
    gatsby-plugin-sharp: ^2.6.11 => 2.11.2 
    gatsby-remark-prismjs: ^3.3.24 => 3.10.0 
    gatsby-source-filesystem: ^2.1.0 => 2.8.1 
    gatsby-transformer-remark: ^2.5.0 => 2.13.1 
    gatsby-transformer-sharp: ^2.5.5 => 2.9.0

**Comment by lukebennett88** [comment] 2021-01-01 00:00
I'm experiencing the same issue.

At first I thought it was caused by Tailwind using PostCSS 8, but I installed the [PostCSS 7 compatibly build](https://tailwindcss.com/docs/installation#post-css-7-compatibility-build) and was having the same issues.

Downgrading to an older version of Gatsby fixed the issue for me (gatsby@2.24.91, I didn't do much testing so not sure which version introduced this but, — I had an older project was using Tailwind 1.9.x  with that version of Gatsby so that's what I tried first).

**Comment by chadalen** [comment] 2021-01-01 01:03
> I'm experiencing the same issue.
> 
> At first I thought it was caused by Tailwind using PostCSS 8, but I installed the [PostCSS 7 compatibly build](https://tailwindcss.com/docs/installation#post-css-7-compatibility-build) and was having the same issues.
> 
> Downgrading to an older version of Gatsby fixed the issue for me (gatsby@2.24.91, I didn't do much testing so not sure which version introduced this but, — I had an older project was using Tailwind 1.9.x with that version of Gatsby so that's what I tried first).

Yeah this must of been a recent update. I've tried a tailwind 2.0 + gatsby starter project but getting the same issue.
https://github.com/taylorbryant/gatsby-starter-tailwind

I don't want to downgrade to tailwind 1, have you found a solution that works with tailwind 2?

**Comment by lukebennett88** [comment] 2021-01-01 01:32
I did the same thing!

If you look at the commits though, the version or Gatsby was updated at the same time.

I'm confident that it's a bug with Gatsby and not Tailwind.

**Comment by chadalen** [comment] 2021-01-01 01:48
> I did the same thing!
> 
> If you look at the commits though, the version or Gatsby was updated at the same time.
> 
> I'm confident that it's a bug with Gatsby and not Tailwind.

Yeah you're right. Using tailwind 1.9.6 with gatsby 2.27.3 issue doesn't happen. Upgrading to gatsby 2.28.2 the issue happens...

**Comment by pieh** [comment] 2021-01-04 19:15
I was checking this issue a bit, and it seems to me that `style-loader` (webpack loader that gatsby currently use css (esque type things) for `gatsby develop`) appends `<link>` tags to `<head>` quite late and because initial render is not blocked before those load and process - that initial render can be unstyled.

![Screenshot 2021-01-04 at 20 02 50](https://user-images.githubusercontent.com/419821/103569624-ed340580-4ec7-11eb-884e-0a02f98af5d9.png)

Is some charts on it:
`FP` is first paint - this is moment in time when initial render actually paints to screen - notice that purple `blog:X` is still in progress (that's styles). And it get repainted once `LCP` (Largest Contentful Paint) happens which is after styles are loaded and recalculated.

I'm not sure if reverting gatsby (or tailwind) versions actually "fixes" it - it's much more probable that it just have different timing or so, but previous gatsby versions didn't have code that waited for style-loader code to load either. I'm not sure here why timing seems to consistently trigger first paint with provided repro before styles are loaded and parsed (but we did add some speedups in other area of gatsby runtime so maybe runtime just loads faster and it just exposed this issue more).

That said - I'm not sure if we will be pursing making fixes for `style-loader` integration, as we are working on approach that essentially drops use of it - https://github.com/gatsbyjs/gatsby/pull/28471 and instead acts actually the same as production builds (so css is extracted and inlined). Linked PR fixes the issue and will likely be merged soon, but it is part of https://github.com/gatsbyjs/gatsby/discussions/28138 which requires to opt-in to use SSR in `gatsby develop`

**Comment by icy-meteor** [comment] 2021-03-27 12:52
Facing the same issue.

**Comment by paulmaker** [comment] 2021-03-31 12:21
Same issue

**Comment by cjones26** [comment] 2021-04-15 01:35
Same issue here as well.

**Comment by 123ndy** [comment] 2021-04-17 13:44
Same issue here as well

**Comment by zanio** [comment] 2021-04-19 12:58
Same issue here as well but not with gatsby project

**Comment by MaxChu23** [comment] 2021-07-03 15:35
Same issue

**Comment by lowewenzel** [comment] 2021-08-17 22:46
Still occuring!

**Comment by LekoArts** [comment] 2021-08-18 06:50
I'll close this issue as it doesn't seem actionable to me anymore.

Besides OP there was no further reproduction given for this (commenting "same issue" sadly doesn't help) and in the meantime two major things happened:

- You can active SSR in Develop that will help with huge CSS files in development: https://github.com/gatsbyjs/gatsby/discussions/28138
- More importantly: Tailwind itself shipped a JIT compiler: https://tailwindcss.com/docs/just-in-time-mode

If either of those two things doesn't solve your problem, please open a new issue, reference this one here and post a reproduction as asked in the issue template.

Thanks!

**Closed by LekoArts** 2021-08-18 06:50 UTC
Labels: type: bug, topic: core, topic: DX

**Comment by shdq** [comment] 2022-01-26 13:40
I upgraded gatsby from v3 to v4 and have the same issue with FOUC (gatsby + styletron). So it is gatsby's problem.
