### ISSUE TITLE
Unable to Change Start URL 

### ISSUE THREAD

**Issue by jordanlesich** [gatsbyjs/gatsby#22668] opened 2020-03-30 20:57 UTC
## Description

I would like to change the URL path where my website starts. For example, instead of starting at '/' index, I would like it to start at '/blog/'. 

I've tried following the instructions here: https://www.gatsbyjs.org/docs/path-prefix/, but it only sends me to a white screen. 

- 

### Steps to reproduce

1. install a gatsby new bug-repro https://github.com/gatsbyjs/gatsby-starter-hello-world
2. create a blog.js file in pages. 
3. Make it into a react component that renders 'Blog' to the screen. 
4. test in browser to see if it loads if /blog/ is added to url. (should work at this point) 
5. Follow all steps in the above mentioned article by:
   - adding pathPrefix: '/blog' or '/blog/' (tried both) to gatsby-config.js
   - gatsby build --prefix-paths
   - gatsby serve --prefix-paths

https://github.com/jordanlesich/path-prefix-test-case

### Expected result

White screen. The word 'Blog' that is rendered on screen normally is not there. This also what hapenned to my project I was initially working on. 

What should happen?

We should start at the blog page. 

### Actual result

White screen

### Other things I tried

- Not in the reproduction, but in my own project, I tried changing the start_url in my gatsby-plugin-manifest object.
- I tried this with the path-prefix instructions
- I tried it without

### Note

I am not sure if adding path-prefix add this to all my files, or if it just adds it to the index. If so, is it causing a collision with the currently existing blog.js? Not entirely sure how this works. I would just like to have the site start at my already exisiting blog page instead of the root domain. Any help is greatly appreciated, thanks!

### Environment

  System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-3570 CPU @ 3.40GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17 - /c/Python27/python
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.19.45 => 2.19.45

**Comment by arthurjdam** [comment] 2020-03-31 01:41
path-prefix is intended to prefix all routes with a string. If you set path-prefix to "/blog/", that would mean that you would see "pages/index.js" on "http://localhost:9000/blog/". Consequently, "localhost:9000/blog/blog/" will return your "pages/blog.js" page (this seems to be confirmed by your test-case)

What is your expected behavior?

**Comment by LekoArts** [comment] 2020-03-31 10:29
Thank you for opening this!

As Arthur correctly said this is an error on your end. If you expect to see something at `/blog` you'll need to create a file at `src/pages/index.js` and use the pathPrefix.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2020-03-31 10:29 UTC
Labels: type: bug
