### ISSUE TITLE
[gatsby-plugin-offline] TypeError: messageApi[gatsbyApi] is not a function

### ISSUE THREAD

**Issue by bitttttten** [gatsbyjs/gatsby#18531] opened 2019-10-11 20:24 UTC
### Description

In my browser Firefox, page navigations are issued and then the website immediately refreshes which breaks the "single page application". I am not sure if this is related, so I came here to report this issue.

So after a page navigation, I see an error in the console from the service worker and then the page refreshes.

> TypeError: messageApi[gatsbyApi] is not a function sw.js:106:39

Which leads here:

```js
self.addEventListener(`message`, event => {
  const { gatsbyApi } = event.data
  if (gatsbyApi) messageApi[gatsbyApi](event, event.data)
})
```

### Steps to reproduce

Use my config:

```js
module.exports = {
	siteMetadata: {},
	plugins: [
		{
			resolve: `gatsby-plugin-layout`,
			options: {
				component: require.resolve(`./src/layouts/default.tsx`),
			},
		},
		`gatsby-plugin-netlify`,
		{
			resolve: `gatsby-plugin-netlify-headers`,
			options: {
				headers: {
					"/storybook/*": [
						"Basic-Auth: letmein:please",
						"X-Frame-Options: sameorigin",
					],
				},
			},
		},
		`gatsby-plugin-emotion`,
		`gatsby-plugin-typescript`,
		`gatsby-plugin-react-helmet`,
		`gatsby-plugin-sharp`,
		{
			resolve: `gatsby-plugin-create-client-paths`,
			options: { prefixes: [`/recipe/*`] },
		},
		{
			resolve: `gatsby-plugin-offline`,
			options: {
				workboxConfig: {
					cacheId: `my-app`,
				},
				appendScript: require.resolve(`./src/sw-extension.js`),
			},
		},
		{
			resolve: `gatsby-plugin-gtag`,
			options: {
				trackingId: process.env.GATSBY_GOOGLE_ANALYTICS_ID,
				head: true,
				anonymize: true,
				respectDNT: true,
			},
		},
		{
			resolve: "gatsby-plugin-react-svg",
			options: {
				rule: {
					include: /theme\/icons/,
				},
			},
		},
		{
			resolve: `gatsby-plugin-manifest`,
			options: {},
		},
	],
}

```

```
// src/sw-extension.js
function getEndpoint() {
	return self.registration.pushManager.getSubscription().then((subscription) => {
		if (subscription) {
			return subscription.endpoint;
		}

		throw new Error('User not subscribed');
	});
}

self.addEventListener('push', (event) => {
	event.waitUntil(getEndpoint()
		.then((endpoint) => {
			return fetch(`myurl`, {
				headers: {}
			});
		})
		.then(response => response.json())
		.then((data) => {
			let cont = {
				body: data.body,
				icon: data.icon,
			};
			if (
				typeof data.click_action !== 'undefined' &&
					data.click_action &&
					typeof data.click_title !== 'undefined' &&
					data.click_title
			) {
				cont.data = { url: data.click_action };
				cont.actions = [{ action: 'open_url', title: data.click_title }];
			}
			self.registration.showNotification(data.title, cont);
		}));
});

self.addEventListener(
	'notificationclick',
	(event) => {
		switch (event.action) {
		case 'open_url':
			clients.openWindow(event.notification.data.url);
			break;
		}
		// Close notification after click and open the PWA if we've clicked the notification itself.
		event.notification.close();
		if (clients.openWindow && event.notification.data.url) {
			event.waitUntil(clients.openWindow(event.notification.data.url));
		}
	},
	false
);
```

### Expected result

Error should not throw.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```sh
  System:
    OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (16) x64 AMD Ryzen 7 1700X Eight-Core Processor
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node       
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
  npmPackages:
    gatsby: ^2.15.17 => 2.15.17
    gatsby-image: ^2.2.19 => 2.2.19
    gatsby-plugin-create-client-paths: ^2.1.8 => 2.1.8
    gatsby-plugin-emotion: ^4.1.6 => 4.1.6
    gatsby-plugin-gtag: ^1.0.11 => 1.0.11
    gatsby-plugin-layout: ^1.1.7 => 1.1.7
    gatsby-plugin-manifest: ^2.2.16 => 2.2.16
    gatsby-plugin-netlify: ^2.1.13 => 2.1.13
    gatsby-plugin-netlify-headers: ^1.0.1 => 1.0.1
    gatsby-plugin-offline: ^3.0.7 => 3.0.7 
    gatsby-plugin-react-helmet: ^3.1.7 => 3.1.7
    gatsby-plugin-react-svg: ^2.1.2 => 2.1.2
    gatsby-plugin-sharp: ^2.2.23 => 2.2.23
    gatsby-plugin-typescript: ^2.1.8 => 2.1.8
    gatsby-source-filesystem: ^2.1.23 => 2.1.23
  npmGlobalPackages:
    gatsby-cli: 2.5.7
```

**Comment by barbalex** [comment] 2019-10-18 19:37
Since a few days I am getting a very similar error when the site loads for the first time after a new version was published:

```
Site has changed on server. Reloading browser
sw.js:126 Uncaught TypeError: MessageAPI[api] is not a function
    at sw.js:126
```

This leads to the site reloading indefinitely until the user closes the window. Next time the site is opened, it works.

Not nice UX 😞

**Comment by barbalex** [comment] 2019-10-18 22:50
It seems that the error comes from https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-offline/src/sw-append.js#L60 or https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-offline/src/sw-append.js#L67.

The variable `api` seems to be something else than expected in `const MessageAPI` (https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-offline/src/sw-append.js#L40-L56).

**Comment by bitttttten** [comment] 2019-10-21 13:24
I could also imagine it's another plugin sending a postMessage to the service-worker, and this is not handling those cases. I didn't investigate this idea yet though.

**Comment by macko911** [comment] 2019-10-30 20:30
We were facing the same issue with indefinitely refreshing website. It looks like the issue is caused by this code:
https://github.com/gatsbyjs/gatsby/blob/589c599f9e4c494e6aa867ded162650805327c95/packages/gatsby/cache-dir/navigation.js#L108-L110
It tries to clear the cached paths using `resetWhitelist` but that is no longer a method on the MessageAPI object. Changing it to `clearPathResources` fixed it for us.

**Comment by bitttttten** [comment] 2019-10-31 09:58
That's awesome that you debugged it! Hope it gets through quickly ✨

**Comment by barbalex** [comment] 2019-11-14 21:12
Works fine for us now. Thanks @macko911 !

**Comment by macko911** [comment] 2019-11-15 16:12
That's great news, thanks for the feedback! Closing the issue then.

**Closed by macko911** 2019-11-15 16:12 UTC
Labels: type: bug
