### ISSUE TITLE
gatsby-source-wordpress: sometimes querying image works, sometimes doesn't

### ISSUE THREAD

**Issue by orshick** [gatsbyjs/gatsby#13347] opened 2019-04-14 01:05 UTC
## Description

While making a site using gatsby-source-wordpress I noticed that builds failed occasionally, with the error message `error    Cannot query field "localFile" on type "wordpress__PAGEAcfHero_image"  graphql/template-strings`

I've checked the sections in the docs with regard to issues querying images and null files, and have taken steps to address them ([this](https://www.gatsbyjs.org/packages/gatsby-source-wordpress/#graphql-error---unknown-field-localfile-on-type-image-field) one seems particularly relevant). But here's the kicker: This issue happens seemingly randomly. In other words, the image is certainly not null, and IS available, since it is being queried some of the time, but not at other times.

### Steps to reproduce

Clone [repo](https://gitlab.com/orshick/the-ocma-gatsby)  and run `gatsby develop`. It should not take many attempts to error out.

### Expected result

A locally served version of the site should open, which should look like [this](https://dreamy-yalow-915c97.netlify.com/)

### Actual result

Build fails, showing the line `error    Cannot query field "localFile" on type "wordpress__PAGEAcfHero_image"  graphql/template-strings`

### Environment

System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
  Binaries:
    Yarn: 1.10.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    gatsby: ^2.3.21 => 2.3.21
    gatsby-image: ^2.0.38 => 2.0.38
    gatsby-plugin-emotion: ^4.0.6 => 4.0.6
    gatsby-plugin-manifest: ^2.0.29 => 2.0.29
    gatsby-plugin-offline: ^2.0.25 => 2.0.25
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-sharp: ^2.0.34 => 2.0.34
    gatsby-source-filesystem: ^2.0.29 => 2.0.29
    gatsby-source-wordpress: ^3.0.53 => 3.0.53
    gatsby-transformer-sharp: ^2.1.18 => 2.1.18

**Comment by RikoSmith** [comment] 2019-04-14 17:43
Replicated. Error occurred after second run  of ````gatsby develop````.  It occurred once out of ten tries though. 

Environment:
````
  System:
    OS: Windows 10    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:    Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.2.0 - C:\Program Files\nodejs\npm.CMD  Languages:
    Python: 2.7.15  Browsers:
    Edge: 44.17763.1.0  npmPackages:
    gatsby: ^2.3.21 => 2.3.21    gatsby-image: ^2.0.38 => 2.0.38
    gatsby-plugin-emotion: ^4.0.6 => 4.0.6    gatsby-plugin-manifest: ^2.0.29 => 2.0.29
    gatsby-plugin-offline: ^2.0.25 => 2.0.25
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12
    gatsby-plugin-sharp: ^2.0.34 => 2.0.34
    gatsby-source-filesystem: ^2.0.29 => 2.0.29
    gatsby-source-wordpress: ^3.0.53 => 3.0.53
    gatsby-transformer-sharp: ^2.1.18 => 2.1.18
````

**Comment by orshick** [comment] 2019-04-15 01:40
@RikoSmith  Thank you for trying it out! Good to know it isn't just something odd on my and Netlify's machines (the errors happen on Netlify too).

**Comment by hesselberg** [comment] 2019-04-15 11:31
I believe this is a Duplicate of #10347

**Comment by orshick** [comment] 2019-04-15 22:44
@hesselberg  Yes, seems likely.

**Comment by wardpeet** [comment] 2019-04-16 08:10
Duplicate of #10347

Thanks for opening this issue, let us move this discussion to #10347

**Closed by wardpeet** 2019-04-16 08:10 UTC
Labels: type: bug
