### ISSUE TITLE
Image query from root index page returns an error

### ISSUE THREAD

**Issue by cdaein** [gatsbyjs/gatsby#36728] opened 2022-10-02 18:44 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

To reproduce the issue, clone the repo below:
https://github.com/cdaein/gatsby-image-query-issue

### Reproduction Link

https://github.com/cdaein/gatsby-image-query-issue

### Steps to Reproduce

1. clone the official tutorial example from https://github.com/gatsbyjs/tutorial-example

2. `npm i` to install packages. (ignoring peer dependency warnings below)

```
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: react-server-dom-webpack@0.0.0-experimental-c8b778b7f-20220825
npm WARN Found: react@18.2.0
npm WARN node_modules/react
npm WARN   react@"^18.2.0" from the root project
npm WARN   9 more (@mdx-js/react, gatsby, react-dom, gatsby-plugin-image, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer react@"0.0.0-experimental-c8b778b7f-20220825" from react-server-dom-webpack@0.0.0-experimental-c8b778b7f-20220825
npm WARN node_modules/react-server-dom-webpack
npm WARN   react-server-dom-webpack@"0.0.0-experimental-c8b778b7f-20220825" from gatsby@4.24.1
npm WARN   node_modules/gatsby
npm WARN 
npm WARN Conflicting peer dependency: react@0.0.0-experimental-c8b778b7f-20220825
npm WARN node_modules/react
npm WARN   peer react@"0.0.0-experimental-c8b778b7f-20220825" from react-server-dom-webpack@0.0.0-experimental-c8b778b7f-20220825
npm WARN   node_modules/react-server-dom-webpack
npm WARN     react-server-dom-webpack@"0.0.0-experimental-c8b778b7f-20220825" from gatsby@4.24.1
npm WARN     node_modules/gatsby
npm WARN deprecated async-cache@1.1.0: No longer maintained. Use [lru-cache](http://npm.im/lru-cache) version 7.6 or higher, and provide an asynchronous `fetchMethod` option.
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
```

3. move the `src/pages/blog/index.js` content to the root `src/pages/index.js` and make necessary changes such as import paths, component name.

4. Add `hero_image` to the root `src/pages/index.js` page query.

```
export const query = graphql`
  query {
    allMdx(sort: { fields: frontmatter___date, order: DESC }) {
      nodes {
        frontmatter {
          date(formatString: "MMMM D, YYYY")
          title
          slug
          hero_image {
            childImageSharp {
              gatsbyImageData
            }
          }
        }
        id
        excerpt
      }
    }
  }
`;
```

5. Add `<GatsbyImage image={getImage(node.frontmatter.hero_image)}/>` to the page content.

6. `gatsby clean && gatsby develop`

7. GraphQL returns an error as below:

```
 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Cannot read properties of null (reading 'dir')

   1 | query pageUsersdaneDesktoptutorialExampleMainsrcpagesindexJs3626874412 {
   2 |   allMdx(sort: {fields: frontmatter___date, order: DESC}) {
   3 |     nodes {
   4 |       frontmatter {
   5 |         date(formatString: "MMMM D, YYYY")
   6 |         title
   7 |         slug
>  8 |         hero_image {
     |         ^
   9 |           childImageSharp {
  10 |             gatsbyImageData
  11 |           }
  12 |         }
  13 |       }
  14 |       id
  15 |       excerpt
  16 |     }
  17 |   }
  18 | }

File path: /Users/dane/Desktop/tutorial-example-main/src/pages/index.js
Url path: /
Plugin: none



  TypeError: Cannot read properties of null (reading 'dir')
  
  - resolvers.ts:535 queryNodeByPath
    [tutorial-example-main]/[gatsby]/src/schema/resolvers.ts:535:63
  
  - resolvers.ts:546 fileByPathResolver
    [tutorial-example-main]/[gatsby]/src/schema/resolvers.ts:546:14
  
  - task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
  
  - async Promise.all
  
  - async Promise.all
  
  - async Promise.all
  
  - async Promise.all
```

8. Copy the exactly same image query/GatsbyImage codes back to blog `index.js` and update import path accordingly. This page query does NOT return an error. So, it must be something to do only with the root index page query. Also, as I make some changes to the code (js and mdx), sometimes, images show up on the root index page, other times not. But `gatsby clean && gatsby develop` will always return the same error on the root index page.

### Expected Result

There shouldn't be an error, and the images should show up on the root index page.

### Actual Result

GraphQL page query returns an error. And in the browser, the images do not show up.

### Environment

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm
  Browsers:
    Chrome: 106.0.5249.91
  npmPackages:
    gatsby: ^4.21.0 => 4.24.1 
    gatsby-plugin-image: ^2.20.0 => 2.24.0 
    gatsby-plugin-mdx: ^4.0.0 => 4.3.0 
    gatsby-plugin-sharp: ^4.20.0 => 4.24.0 
    gatsby-source-filesystem: ^4.20.0 => 4.24.0 
    gatsby-transformer-sharp: ^4.20.0 => 4.24.0 
  npmGlobalPackages:
    gatsby-cli: 4.24.0
```

**Comment by pieh** [comment] 2022-10-03 18:53
Let's start with workaround for the bug - you can add following snippet to `gatsby.node.js` (until this is resolved):

```js
const cloneDeep = require(`lodash/cloneDeep`);

// workaround for https://github.com/gatsbyjs/gatsby/issues/36728
exports.onCreatePage = ({ page, actions }) => {
  if (page?.context?.frontmatter && !page?.context?.didCreateClone) {
    actions.createPage({
      ...page,
      context: {
        ...page.context,
        frontmatter: cloneDeep(page.context.frontmatter),
        didCreateClone: true,
      },
    });
  }
};
```

Now explanation, and some paper trail to why this is happening (that's going to be quite a deep dive):

Moving this to `src/pages/index.js` makes Gatsby prerun query for it early on. But this issue would happen in for old page as well on `/blog/` page visit (we defer most of the queries other than main index page and few others until users tries to view them). It's possible that it's not always or even often reproducable with the `/blog/` location due to non-deterministic way Node.js clears ups memory (garbage collection).

For queries like:
```graphql
{
  frontmatter {
    hero_image {
      childImageSharp {
        gatsbyImageData
      }
    }
  }
}
```
to work, we need to track nested objects (frontmatter object in here) and be able which node it belong to, as under the hood we only get frontmatter object
![image](https://user-images.githubusercontent.com/419821/193654626-ad3e42bc-55c3-4388-944f-732ce5a02393.png)
For that reason we have `WeakMap` that points to actual node - in this case it should be `Mdx` node, but it actually isn't:
![image](https://user-images.githubusercontent.com/419821/193654958-f1ba7087-33c1-42c8-b23c-a3a490b1ae03.png)

Instead it currently maps to `SitePage` node created for this Mdx node. And this happens because helper that injects `frontmatter` via page context ( https://github.com/gatsbyjs/gatsby/blob/ba146fd3b7ee1f18c1c695bc654890151d2cc0b3/packages/gatsby-plugin-mdx/src/gatsby-node.ts#L325-L367 ) pass same `frontmatter` instance as for actual `Mdx` node (note that `parseFrontmatter` used there is memoized so it will always return same object for same input instead of creating new instance). That overwrites our mapping that should map frontmatter object to `Mdx` node and instead it points to `SitePage` node.

Problem here is the assumption that we have 1:1 mapping instead of 1:N, which makes it impossible (or flaky at very least) to get this to work correctly. The change that needs to happen here is to make `nodeModel._rootNodeMap` map object to array/set of node ids and not just 1 and adjust any consumer of that map to work with new structure

**Comment by cdaein** [comment] 2022-10-03 21:10
Thank you for the response @pieh

In my project, I am already using Node API `createPages` unlike the aforementioned official tutorial that uses File System Route API.

My question is,
Is it okay to use **both** `createPages`(my code) and `onCreatePage`(your workaround) together? 
From the docs, I read that they can create infinite loops/callbacks (https://www.gatsbyjs.com/docs/reference/config-files/gatsby-node/#onCreatePage). When I implemented both, it seems to work, but it would be great to know what the best practice is to avoid this bug.

**Comment by pieh** [comment] 2022-10-03 21:30
I did add `didCreateClone` "toggle" in the snippet as a way to prevent infinite callbacks (and `gatsby-plugin-mdx` has similar guard around `// Avoid loops ` code comment), so this should be fine. 

It's not really best practice here, because your `gatsby-node` creates a page, then `gatsby-plugin-mdx` takes over and injects the `frontmatter` and then it goes back to your `gatsby-node`'s `onCreatePage`, so it's a bit of "ping-pong" happening, but it was most "robust" workaround I could think of at least for FS Routes scenario.

If you are creating pages in `createPages` and not via FS Routes, then I think you could short-circuit the problem by passing `frontmatter` field in page context that would skip what mdx plugin is trying to do - https://github.com/gatsbyjs/gatsby/blob/ba146fd3b7ee1f18c1c695bc654890151d2cc0b3/packages/gatsby-plugin-mdx/src/gatsby-node.ts#L350-L351 as this would not be satisfied anymore. If you don't use `frontmatter` passed in via `context` in your site then you could just do something like:

```js
createPage({
  path: [...],
  component: [...],
  context: {
    // set truthy frontmatter to bypass automatic frontmatter injection by gatsby-plugin-mdx
    frontmatter: {}
  }
})
```

Or if you need the frontmatter being passed in you could query for it to pass it back - if you would query for it it would create new object as that's just what graphql would do when constructing results

**Comment by amalitsky** [comment] 2022-10-12 06:43
Thanks, @pieh. There is no way I would figure this out myself. `frontmatter: {}` worked for my case like a charm.

**Closed** 2022-10-25 06:53 UTC
Labels: type: bug, status: confirmed, topic: remark/mdx

**Comment by pieh** [comment] 2022-10-25 15:15
`gatsby@4.24.5` was released with the fix for this, so you should be able to upgrade and drop the workaround

**Comment by AAverin** [comment] 2022-10-28 18:41
Still get this on hot reloads:
```
 TypeError: Cannot read properties of null (reading 'dir')
  
  - resolvers.ts:535 queryNodeByPath
    [gSite]/[gatsby]/src/schema/resolvers.ts:535:63
  
  - resolvers.ts:525 queryNodesByPath
    [gSite]/[gatsby]/src/schema/resolvers.ts:525:13
  
  - resolvers.ts:544 fileByPathResolver
    [gSite]/[gatsby]/src/schema/resolvers.ts:544:14
  
  - task_queues:96 processTicksAndRejections
    node:internal/process/task_queues:96:5
    ```
