### ISSUE TITLE
Plugin default-site-plugin returns an error when invalid pages are created

### ISSUE THREAD

**Issue by nodox** [gatsbyjs/gatsby#2945] opened 2017-11-17 01:32 UTC
I'm running thought the tutorial to create a [blog](https://www.gatsbyjs.org/blog/2017-07-19-creating-a-blog-with-gatsby/) and I keep getting this error which is not particularly helpful.

<img width="639" alt="screen shot 2017-11-16 at 8 20 36 pm" src="https://user-images.githubusercontent.com/7632841/32924791-5f6c6cf2-cb0c-11e7-88c3-2a3f6b192767.png">

**Comment by nodox** [comment] 2017-11-17 01:35
Update: I was working with the `createPages` api and the markdown plugin. What I realized was that I was caluclating more posts than I actually has so the function was returning that errors. I have fixed the issue in my code however there should be a more informative error handling. I'm going to keep this open for @KyleAMathews to give his thoughts.

Usually the error is a result og mispelling something in your `gatsby-node.js`. Please correct me if I am wrong.

**Comment by KyleAMathews** [comment] 2017-11-20 19:23
oh interesting! Yeah, this comes up fairly often — someone complains about `default-site-plugin` returning an error but this makes sense that it'd be an invalid page causing trouble.

I'll assign this to myself to look into. Probably we need better validation when creating pages to catch the problem earlier.

**Comment by KyleAMathews** [comment] 2017-11-20 19:25
Could you create a small site reproducing the error? Or describe in detail how you were creating the invalid pages?

**Comment by exrishu** [comment] 2017-11-21 11:44
Same error with same work. I am also new to gatsby trying to run blog tutorial but getting the same error. How should I resolve it.

**Comment by exrishu** [comment] 2017-11-21 11:52
@KyleAMathews check out this link this is what exactly I am doing. [markdown-tutorial] ( https://www.youtube.com/watch?v=n1NaVkKdrwc) But there is small difference in naming the files and folders 

>  Markdown file - src/pages/home.md
> template file -src/templates/home.js

This is what  gatsby-node.js look like:
`const path = require('path');

exports.createPages = ({ boundActionCreators,graphql}) =>{
 const { createPage } = boundActionCreators;


 const postTemplate = path.resolve('src/templates/home.js');


 return graphql (`{
     allMarkdownRemark {
         edges{
             node{
                 html
                 id
                 frontmatter {
                     path
                     tittle
                 }
             }
         }
     }

 }`)
 .then( res => {
     if(res.errors){
         return Promise.reject(res.errors);
     }

     res.data.allMarkdownRemark.edges.array.forEach( ({node}) =>{
        createPage({
            path: node.frontmatter.path,
            component : postTemplate
        })

     }
    );
 })
}`

**Comment by exrishu** [comment] 2017-11-21 12:31
@nodox Can u tell me exactly where were u wrong because I have checked twice and I can't find any misspelled words.  and still am fighting to solve this error.

**Comment by nodox** [comment] 2017-11-21 13:47
I would have to reproduce the error via commit messages (which I'm not sure how I introduced/fixed in the first place). I find that if you misspell something or miss a comma it'll cause the error. The problem is that it needs to build with a programmer error as any operational error will break the bootstrap build.

**Comment by nodox** [comment] 2017-11-21 13:49
@KyleAMathews I believe you might be right on this one. While the server was on I kept creating and deleting markdown pages to get stuff working with my GraphQL queries. I will look into how I can reproduce this error.

**Comment by exrishu** [comment] 2017-11-22 06:07
@nodox I have figured out the error. and yes I agree with you, I missed the comma in gatsby-node.js.

**Comment by acroyear** [comment] 2018-01-13 20:54
I found another 'user error' that resulted in this useless error message.

I was adding markdown, per https://www.gatsbyjs.org/docs/adding-markdown-pages/, but decided that for my purposes I didn't need dates. I wasn't making a blog, i just wanted MD pages.

However, I had left behind "sort: { order: DESC, fields: [frontmatter___date] }" in the gatsby-node.js file from my copy-paste. Since there was no date field, this fired an error.  The subsequent promise rejected them, resulting in the useless message. Adding a console.log of the result in the promise then revealed it.

**Closed** 2018-01-15 18:28 UTC
Labels: review

**Comment by KyleAMathews** [comment] 2018-01-15 18:29
I improved the error so it shows the actual source of the error — your site's gatsby-node.js. `default-site-plugin` is the internal name for `gatsby-node.js` but that's super confusing :-( Sorry about how long it took to fix this!

**Comment by aman-developer** [comment] 2018-09-02 13:52
![screenshot from 2018-09-02 19-21-04](https://user-images.githubusercontent.com/29298440/44956677-6a5ca380-aee5-11e8-92ed-ad0679255285.png)
![screenshot from 2018-09-02 19-21-21](https://user-images.githubusercontent.com/29298440/44956680-6f215780-aee5-11e8-848b-7d7a85426f1c.png)
![screenshot from 2018-09-02 19-21-26](https://user-images.githubusercontent.com/29298440/44956681-721c4800-aee5-11e8-9d05-98c42e0a5d1e.png)

Hello -

Thank you for revert back to me.

I have downloaded gatsby folder and i reach to /www directory. I run "yarn install" command , it works fine.
when i run "yarn run develop" then i am getting errors.

Regards
Aman
