### ISSUE TITLE
**Duplicating nodes displaying in static query**

### ISSUE THREAD

**Issue by Brad19** [gatsbyjs/gatsby#26284] opened 2020-08-07 01:56 UTC
## Description

**Duplicating nodes displaying in static query**

### Steps to reproduce

Hi, I'm relatively new to Gatsby echo system. I've a small issue which i want to get that fixed. I'm using gatsby-source-contentful - 2.1.91. I'm getting the duplicate nodes in the static query result.

I was checking similar issues  for e.g. - https://github.com/gatsbyjs/gatsby/issues/6254 which suggested to check my node_locale. I did that and it looks like node_locale is same for both the records with the same contentful_id. But it has different id. The only difference was the second record does have the updatedAt value besides the createdAt.

I did bit of search to check for solution. Unsure how to clear this. Can someone please advise as i got struck and not sure about the solution.. any help will be really timely and helpful.. At the moment, I suppose the only way is to check if the record has updatedAt value and if yes, read from that. Other than that i'm not sure how to resolve or clear duplicated record.

PFA the screenshot of the same

![image](https://user-images.githubusercontent.com/10935246/89599609-67257b80-d8a3-11ea-9ae7-4f4eff5fca4b.png)

### Environment

Binaries:
    Node: 13.12.0 
    Yarn: 1.22.4 
    npm: 6.14.4 
  npmPackages:
    gatsby: ^2.19.7 => 2.23.4
    gatsby-plugin-env-variables: 1.0.2 => 1.0.2
    gatsby-plugin-react-helmet: ^3.1.23 => 3.3.4
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.1
    gatsby-plugin-s3: ^0.3.2 => 0.3.3
    gatsby-plugin-sass: 2.3.4 => 2.3.4
    gatsby-plugin-sitemap: ^2.2.28 => 2.4.5
    gatsby-plugin-styled-components: 3.3.4 => 3.3.4
    gatsby-plugin-web-font-loader: 1.0.4 => 1.0.4
    gatsby-source-contentful: ^2.1.91 => 2.3.15
  npmGlobalPackages:
    gatsby-cli: 2.11.7
    gatsby: 2.20.24

Thanks,
Brad

**Comment by TylerBarnes** [comment] 2020-08-07 23:46
Hi @Brad19 !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by Brad19** [comment] 2020-08-09 10:28
@TylerBarnes 
Thanks for your reply. Much appreciated!!!  But unsure how I can give you the minified version as data is flowing from the contentful and the env is secured, cloud based and so others can't access it outside. But if there is a chance to point me in a direction where there might be a potential issue, that'll be really helpful.

**Comment by mikehawkfish** [comment] 2020-08-26 16:50
Hey there Gatsby Team,

I am also having this issue. Querying the Contentful API directly works perfectly fine, but Gatsby Source is duplicating entries(specifically from References Many fields). 

I've tried filtering with `(filter: {node_locale: {eq: "en-US"}})` with no luck at all.

To fix the issue temporarily:

1. Go to the problem type in the Content Editor
2. Remove all referenced items(References Many) field, except for 2.
3. Save/publish
4. Add them back
5. Save/publish

This will fix it until you stop and start your build a few times, and it will break again.

here's the query that works in Contentful:

```graphql
query {
  mainNavCollection {
    items {
      theme
      pagesCollection {
        items {
          route
        }
      }
    }
  }
}
```

Is this a regression perhaps? Maybe I need to delete the Content Type and start fresh?

Thanks for any insight!

**Comment by mikehawkfish** [comment] 2020-08-26 19:34
Having a similar issue: https://github.com/gatsbyjs/gatsby/issues/6254#issuecomment-681002268

**Comment by ascorbic** [comment] 2020-09-10 11:20
Hi. I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. Thanks!

**Closed by ascorbic** 2020-09-10 11:20 UTC
Labels: status: needs reproduction
