### ISSUE TITLE
gatsby-source-contentful returing undefined but working in gql playground

### ISSUE THREAD

**Issue by DennisJunior247** [gatsbyjs/gatsby#27493] opened 2020-10-16 11:30 UTC
### Summary
for some weeks now I've been working with gatsby and contentful but  few days ago I encountered a bug where my contentful data returns in my gql playground but when I console.log(data) it returns an empty object or undefined when I try to destructure.
****
###  Here is  my gql which is returning the data successfully
![Screenshot from 2020-10-16 12-02-50](https://user-images.githubusercontent.com/58556466/96252243-921a0300-0fa9-11eb-8fa8-00c89ef94d1b.png)

### gatsby-config file

```module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`,
  },
  plugins: [
    {
      resolve : 'gatsby-source-contentful',
      options: {
        spaceId: process.env.SPACE_ID,
        accessToken: process.env.ACCESS_TOKEN
      }
    },
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,
  ],
}

```
### gatsby-node.js
```
const path = require(`path`);

/**
 * Implement Gatsby's Node APIs in this file.
 *
 * See: https://www.gatsbyjs.com/docs/node-apis/
 */

// You can delete this file if you're not using it

exports.createPages = async ({ graphql, actions }) => {
  const { createPage } = actions
  const result = await graphql(`
    query {
      allContentfulLfTeamPosts {
        edges {
          node {
            slug
          }
        }
      }
    }
  `)
  result.data.allContentfulLfTeamPosts.edges.forEach(({ node }) => {
    createPage({
      path: `${node.slug}`,
      component: path.resolve(`./src/pages/article-page.js`),
      context: {
        // Data passed to context is available
        // in page queries as GraphQL variables.
        slug: node.slug,
      },
    });
  });
}
 ```
### The Article.js file

```import React from "react";
import { graphql } from "gatsby";
import { ArticleWrapper } from "./styles";
import { documentToReactComponents } from "@contentful/rich-text-react-renderer";

export const data =
  graphql`
    query($slug: String!) {
      contentfulLfTeamPosts(slug: { eq: $slug }) {
        title
        publishedDate(formatString: "MMMM Do ,YYYY")
        subTitle
        author
        aboutAuthor
        writerImage {
          fluid {
            src
          }
        }
        articleHeaderImage {
          fluid {
            src
          }
        }
        contentWithPictures {
          json
        }
      }
    }
  `;


const Article = ( data ) => {
  console.log(data,"data")
  return (
    <ArticleWrapper>
      <div className="article-header">
        <h1>James Blazers features at World’s Largest Tech Summit </h1>
        <div className="authors-name-date">
          <p>Ralph Hawkins</p>
          <span>
            May 7, 2019
          </span>
        </div>
      </div>
      <div className="text-container">
     <p>contenful article body will de here </>
      </div>
    </ArticleWrapper>
  );
};

export default Article;

```

**Comment by xaverfleer** [comment] 2020-10-16 12:16
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction](https://gatsby.dev/reproduction). This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a [minimal reproduction](https://gatsby.dev/reproduction) and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by LekoArts** [comment] 2020-10-26 08:59
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-10-26 08:59 UTC
Labels: status: needs reproduction, type: bug
