### ISSUE TITLE
JS Caching Issues With Safari

### ISSUE THREAD

**Issue by ryanwiemer** [gatsbyjs/gatsby#5231] opened 2018-05-02 19:43 UTC
## Description

This is for an issue originally reported by @soniCaH on https://github.com/ryanwiemer/gatsby-starter-gcn/issues/7. The issue involves potentially the JS not getting properly cleared from the cache in Safari if the website is updated while the user is in the middle of a browser session. 

### Steps to reproduce 
(Updated on 5/03/2018 to make it easier to reproduce)

1. `gatsby new gatsby-blog https://github.com/gatsbyjs/gatsby-starter-blog`
2. `gatsby build`
3. `gatsby serve` and open up the URL in Safari. Keep this tab/window open. 
4. Make a change by adding a new page i.e. my-thrid-post
5. Run `gatsby build` and `gatsby serve` again
7. Go back to Safari and refresh the page. You will see that the JS in no longer working and there is an error in the console. If you open a new tab or new window then everything works as expected. 

This potential "bug" only occurs in Safari. My question is whether or not this is something that can be resolved or if it is just how Safari differs in some way from other browsers in keeping the old JS in the session cached. 

### Environment
- Gatsby version: 1.9.248
- Operating System: MacOS 10.12.6
- Browser: Safari 11.1

**Comment by KyleAMathews** [comment] 2018-05-03 05:42
Hmm are the images in the DOM at all?

That error is interesting — is JS working at all? Perhaps Safari is caching the JS for some reason which is what's causing the trouble since JS caching has to be disabled in v1.

**Comment by ryanwiemer** [comment] 2018-05-03 06:00
The images are not in the DOM and you are right that the JS is not working at all. Weird. Like I said though if I close the tab or open a new window everything works as expected. So maybe Safari persists the old JS in the browser session as long as the tab isn't closed even though the JS changed on the server. 

<img width="1250" alt="no imges in the dom" src="https://user-images.githubusercontent.com/5171579/39561672-fcda8186-4e5b-11e8-8de8-e7ccd4b72d69.png">

**Comment by m-allanson** [comment] 2018-05-03 12:15
Is it possible to replicate this issue using [`gatsby-starter-blog`](https://github.com/gatsbyjs/gatsby-starter-blog) and `gatsby serve`? That'd make it easier to investigate the problem.

**Comment by ryanwiemer** [comment] 2018-05-03 20:31
@m-allanson, 

Yes good idea. I originally thought it was related to Contentful or Netlify but it is not. I am able to reproduce the issue locally using [gatsby-starter-blog](https://github.com/gatsbyjs/gatsby-starter-blog) and the `gatsby serve` command. 

I have updated the instructions at top.

**Comment by m-allanson** [comment] 2018-05-03 21:49
Thanks @ryanwiemer, I can confirm I'm seeing the same behaviour. I've marked this up as _help wanted_.

**Comment by KyleAMathews** [comment] 2018-05-04 03:05
I'm not sure we can do much then until v2 when filenames always change when data/content changes.

**Comment by danwade** [comment] 2018-05-08 14:43
This is happening on Chrome too.

Environment
Gatsby version: 1.1.25
Operating System: MacOS 11.3.1
Browser: Chrome 66.0.3359.122

**Comment by KyleAMathews** [comment] 2018-09-08 05:16
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Closed by KyleAMathews** 2018-09-08 05:16 UTC
Labels: status: help wanted, type: bug :beetle:
