### ISSUE TITLE
Console throws a weird mix of characters when prompted to select package manager during gatsby tutorial

### ISSUE THREAD

**Issue by arjunamrith** [gatsbyjs/gatsby#25850] opened 2020-07-19 11:31 UTC
## Description

I was following the [Setup Your Development Environment](https://www.gatsbyjs.org/tutorial/part-zero/) instructions on the gatsby-js site.When I try to [create a gatsby site](https://www.gatsbyjs.org/tutorial/part-zero/#create-a-gatsby-site) using the gatsby new command for the first time, I get a weird mix of characters on the cmd line.

![image](https://user-images.githubusercontent.com/45686646/87873335-5e493480-c9de-11ea-9263-a33c39cde99e.png)

Upon closer inspection in this part it wants me to select the default package manager (yarn/npm). I was unable to select the right one because of the display but this is a weird issue. 

### Steps to reproduce
1. Open a new PowerShell tab in windows Terminal (my terminal was not in full screen if that helps in anyway)
2. Follow the steps [here](https://www.gatsbyjs.org/tutorial/part-zero/) for windows to setup your Gatsby development environment
3. In the step where you [create a gatsby test site](https://www.gatsbyjs.org/tutorial/part-zero/#create-a-gatsby-site) using the gatsby new command you are asked to select the package manager. The UI here is completely broken as you are unable to view the options properly (even finding out what it wants is hard if you're not used to the terminal).

### Expected result

What should happen?
A clear view of the options(like below) to select the package manager with the prompt "Which package manager would you like to use?"

> Which package manager would you like to use?
> \>NPM
> 2. Yarn

### Actual result

What happened.
The PowerShell showed me a mix of characters and the prompt mixed into it (see image below, I'm unable to clearly explain)

![image](https://user-images.githubusercontent.com/45686646/87873626-b8e39000-c9e0-11ea-9454-aac67ff93997.png)

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: Windows 10 10.0.20161
    CPU: (4) x64 Intel(R) Core(TM) i5-2500 CPU @ 3.30GHz
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.6 - ~\AppData\Roaming\npm\npm.CMD
  Languages:
    Python: 3.7.4
  Browsers:
    Edge: 44.20170.1000.0
  npmGlobalPackages:
    gatsby-cli: 2.12.60

Terminal/cmd line used - Windows Terminal (Version: 1.0.1811.0)
Powershell - version 5.1

**Comment by LekoArts** [comment] 2020-07-20 06:00
Thanks for the issue! This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/24420

**Closed by LekoArts** 2020-07-20 06:00 UTC
Labels: type: bug
