### ISSUE TITLE
Gatsby Styled Components Plugin not working without SSR

### ISSUE THREAD

**Issue by codejamninja** [gatsbyjs/gatsby#9908] opened 2018-11-13 18:33 UTC
## Description

Gatsby Styled Components Plugin is not overriding styled properties when server-side rendering is disabled.

For example, I am using carbon components react, and carbon components react applies the following styles to a button.

This only happens when I am not using server-side rendering.

### Steps to reproduce

1. Generate new gatsby project
```sh
gatsby new gatsby-site
```

2. Install carbon components
```sh
npm install --save carbon-components carbon-components-react carbon-icons gatsby-plugin-sass
```

_gatsby-config.js_
```js
module.exports = {
  plugins: [
    'gatsby-plugin-sass'
  ]
}
```

3. Install styled components
```sh
npm install --save styled-components gatsby-plugin-styled-components
```

_gatsby-config.js_
```js
module.exports = {
  plugins: [
    'gatsby-plugin-styled-components'
  ]
}
```

4. Create a styled carbon components button

_pages/index.js_
```js
import React from 'react'
import Button from '../components/Button'
import '../styles'
import Layout from '../components/layout'

const IndexPage = () => (
  <Layout>
    <Button>Hello</Button>
  </Layout>
)

export default IndexPage
```

_components/Button/index.js_
```js
import React, { Component } from 'react'
import styled, { withTheme } from 'styled-components'
import { Button } from 'carbon-components-react'

class StyledButton extends Component {
  get style() {
    return {
      ...this.props.style,
    }
  }

  render() {
    return <Button {...this.props} style={this.style} />
  }
}

export default styled(withTheme(StyledButton))`
  color: blue;
  background-color: orange;
`
```

### Expected result

_carbon-components style_
.bx--btn--primary {
    ~~background-color: #3d70b2;~~
    border-width: 2px;
    border-style: solid;
    border-color: transparent;
    ~~color: #fff;~~
}

_styled-components style_
.buyTmI {
    color: blue;
    background-color: orange;
}

### Actual result

_carbon-components style_
.bx--btn--primary {
    background-color: #3d70b2;
    border-width: 2px;
    border-style: solid;
    border-color: transparent;
    color: #fff;
}

_styled-components style_
.buyTmI {
    ~~color: blue;~~
    ~~background-color: orange;~~
}

### Environment

```
  System:
    OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
    Yarn: 1.12.3 - /usr/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
  Browsers:
    Firefox: 63.0
  npmPackages:
    gatsby: ^2.0.19 => 2.0.47 
    gatsby-image: ^2.0.15 => 2.0.20 
    gatsby-plugin-manifest: ^2.0.5 => 2.0.9 
    gatsby-plugin-offline: ^2.0.11 => 2.0.13 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.2 
    gatsby-plugin-sass: ^2.0.4 => 2.0.4 
    gatsby-plugin-sharp: ^2.0.7 => 2.0.12 
    gatsby-plugin-styled-components: ^3.0.1 => 3.0.1 
    gatsby-source-filesystem: ^2.0.4 => 2.0.8 
    gatsby-transformer-sharp: ^2.1.4 => 2.1.8 
```

**Comment by codejamninja** [comment] 2018-11-13 18:34
I have used styled components in the past without server-side rendering, and it has no problem overriding stylesheets.

**Comment by kakadiadarpan** [comment] 2018-11-14 05:04
@codejamninja can you provide a minimal reproduction repo for this issue?

**Comment by codejamninja** [comment] 2018-11-14 19:54
Absolutely, I'll get it to you later today.

**Comment by codejamninja** [comment] 2018-11-14 20:03
```sh
git clone git@github.com:codejamninja/gatsby-carbon-styled-components.git
cd gatsby-carbon-styled-components && yarn
```

```sh
yarn start
```

Go to [localhost:8000](http://localhost:8000) and notice that the button is blue because `styled-components` **is not** overriding `carbon-components`.

```sh
yarn build:serve
```

Go to [localhost:9000](http://localhost:900) and notice that the button is orange because `styled-components` **is** overriding `carbon-components`.

**Comment by kakadiadarpan** [comment] 2018-11-15 09:19
@codejamninja This issue is because of the ordering of the stylesheets. Please refer the 2 screenshots below:

1. Original development output:

<img width="933" alt="screenshot 2018-11-15 at 2 36 52 pm" src="https://user-images.githubusercontent.com/10805593/48542053-27a34880-e8e4-11e8-8405-2c381c7e23cf.png">

2. Modified development output:

<img width="933" alt="screenshot 2018-11-15 at 2 37 05 pm" src="https://user-images.githubusercontent.com/10805593/48542055-27a34880-e8e4-11e8-9c9f-5fb9af341562.png">

Before taking the 2nd screenshot I moved the style tag at the bottom, which contains the styles from styled components. The production output has the the proper order already and hence it work there as expected. Please refer the screenshot below:

<img width="933" alt="screenshot 2018-11-15 at 2 42 47 pm" src="https://user-images.githubusercontent.com/10805593/48542305-d34c9880-e8e4-11e8-911b-68dd55b34776.png">

You might have a question that how do we confirm that style tag contains the css from `styled-components`. `styled-compnents` inserts the styles following way:
```
<style data-styled="" data-styled-version="4.1.1"></style>
```

We already have an open issue regarding the CSS ordering being different in develop vs build. We'll be closing this issue in favour of #9733. Please follow that issue for updates related to this.

**Closed by kakadiadarpan** 2018-11-15 09:19 UTC
Labels: status: needs more info, status: needs reproduction

**Comment by codejamninja** [comment] 2018-11-15 21:54
How do I move the stylesheet below?
