### ISSUE TITLE
[gatsby-starter-blog-theme] Clean up react keys warning

### ISSUE THREAD

**Issue by sidharthachatterjee** [gatsbyjs/gatsby#16196] opened 2019-07-29 20:46 UTC
A new project instantiated using `gatsby-starter-blog-theme` currently displays the following error:

```
Warning: Each child in a list should have a unique "key" prop.

Check the top-level render call using <body>. See https://fb.me/react-warning-keys for more information.
    in EmotionCssPropInternal
```

Need to investigate and clean this up

**Comment by alexluong** [comment] 2019-07-29 21:54
I think the problem is with `gatsby-plugin-theme-ui`. Here is a sandbox with only that plugin, and it displays the same error.

https://codesandbox.io/s/gatsby-starter-l4puk

**Comment by sidharthachatterjee** [comment] 2019-07-29 23:02
Fixed in gatsby-plugin-theme-ui v0.2.23 (updated themes in https://github.com/gatsbyjs/gatsby/pull/16200)

Will close this once the starters are updated and published

**Comment by johno** [comment] 2019-08-02 15:10
Starters have been updated so I'm going to close this now.

**Closed by johno** 2019-08-02 15:10 UTC
Labels: help wanted, topic: themes, type: upstream

**Comment by brotzky** [comment] 2019-08-15 15:46
Hey, on v0.2.23 I'm getting a similar error

> Check the top-level render call using <body>. See https://fb.me/react-warning-keys for more information.
    in InitializeColorMode

is this theme-ui related?

**Comment by dungle-scrubs** [comment] 2021-07-03 07:45
I know this is an old thread, but I just started experiencing this error warning as soon as I added an array of two scripts to `onRenderBody`'s `setPostBodyComponents` in `gatsby-ssr.js`

I'm using Gatsby v3.8.1

**Comment by GerardKetuma** [comment] 2021-08-20 18:00
> I know this is an old thread, but I just started experiencing this error warning as soon as I added an array of two scripts to `onRenderBody`'s `setPostBodyComponents` in `gatsby-ssr.js`
> 
> I'm using Gatsby v3.8.1

You have to ensure the script tags have a key prop as well. So do something like this:
`<script key="my-script" src="https://gatsby.dev/my-script" />`
