### ISSUE TITLE
Minified React error #62; visit http://facebook.github.io/react/  docs/error-decoder.html?

### ISSUE THREAD

**Issue by avinashs735** [gatsbyjs/gatsby#4611] opened 2018-03-19 16:48 UTC
Minified React error #62; visit http://facebook.github.io/react/  docs/error-decoder.html?invariant=62&args[]= for the full message or use the n  on-minified dev environment for full errors and additional helpful warnings.

I am unable to figure out the actual reason for this.....
![image](https://user-images.githubusercontent.com/34059263/37609544-6102b9be-2bc3-11e8-91a8-4bbda855272f.png)

**Comment by m-allanson** [comment] 2018-03-19 20:29
Based on the error message at https://reactjs.org/docs/error-decoder.html?invariant=62&args[]=, it looks like you're doing something like:

```jsx
<Component style="margin-right: 1em" />
```

instead of:

```jsx
<Component style={{marginRight: '1em'}} />
```

It looks like you're using Styled Components, so it may be something to do with how that's set up. Can you push up a minimal test repo that reproduces this error?

**Comment by garrynsk** [comment] 2018-03-31 18:57
Hi there! I've got the same error. Sure this is because of mix of UI tools: material-ui and styled-components. I tried to implement SSR, but the build breaks. If I remove SSR completely, the build goes smooth, but I definitely need it. Probably, something is wrong with my gatsby-ssr.js setup, but I can't track the error. The repo is [here](https://github.com/garrynsk/gatsby-freestyle). Please, help!

**Comment by garrynsk** [comment] 2018-03-31 22:37
Well, I've resolved the problem.
1. installed jss
2. fixed my setup with help of [official material ui - gatsby repo](https://github.com/mui-org/material-ui) and this [gatsby-styled components gist](https://gist.github.com/LawJolla/5fa01d54c64f1b17eea498b68068acab).

You can find the working repo [here](https://github.com/garrynsk/gatsby-freestyle) .

**Comment by KyleAMathews** [comment] 2018-07-02 05:11
Looks like this is resolved so closing.

**Closed by KyleAMathews** 2018-07-02 05:11 UTC
