### ISSUE TITLE
Gatsbys wrapPageElement throws a runtime error.

### ISSUE THREAD

**Issue by andreisemianiuk** [gatsbyjs/gatsby#36787] opened 2022-10-10 19:33 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Getting runtime error after upgrading npm packages.
![image](https://user-images.githubusercontent.com/62586934/194939642-aa6d6f1a-b8fb-4c47-9ac3-c907da7d4e27.png)
  [This](https://github.com/openscript/gatsby-starter-dogmatism/blob/4daa8bb564cd0a436cc98691c326777ff31094ee/src/pages/index.tsx#L4) solution doesn't work for me.

### Reproduction Link

https://github.com/andreisemianiuk/ecosiprom-bug-report

### Steps to Reproduce

1. Launch project
2. 
3.
...

### Expected Result

Working project without runtime error

### Actual Result

![image](https://user-images.githubusercontent.com/62586934/194939042-2ea5032c-62bb-46cc-8b2f-1680991ccde0.png)

### Environment

```shell
System:
    OS: Windows 10 10.0.22000
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
  Binaries:
    Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.10.5
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (106.0.1370.37)
  npmPackages:
    gatsby: ^4.24.4 => 4.24.4
    gatsby-background-image: ^1.6.0 => 1.6.0
    gatsby-plugin-breadcrumb: ^12.3.1 => 12.3.1
    gatsby-plugin-gatsby-cloud: ^4.24.0 => 4.24.0
    gatsby-plugin-image: ^2.24.0 => 2.24.0
    gatsby-plugin-modal-routing-3: ^3.0.0 => 3.0.0
    gatsby-plugin-react-svg: ^3.1.0 => 3.1.0
    gatsby-plugin-sharp: ^4.24.0 => 4.24.0
    gatsby-plugin-styled-components: ^5.24.0 => 5.24.0
    gatsby-source-filesystem: ^4.24.0 => 4.24.0
    gatsby-source-wordpress: ^6.24.0 => 6.24.0
    gatsby-transformer-sharp: ^4.24.0 => 4.24.0
  npmGlobalPackages:
    gatsby-cli: 4.24.0
```

**Comment by marvinjude** [comment] 2022-10-11 11:09
Hi @andreisemianiuk,

The reproduction site doesn't have all the changes you described above. Please make sure your reproduction site is in good shape to enable us investigate this easily.

**Comment by andreisemianiuk** [comment] 2022-10-11 14:11
> Hi @andreisemianiuk,
> 
> The reproduction site doesn't have all the changes you described above. Please make sure your reproduction site is in good shape to enable us investigate this properly.

@marvinjude my bad, already replaced it with working link!

**Comment by marvinjude** [comment] 2022-10-12 11:07
Hi @andreisemianiuk,

It appears that there's an issue with one of the updated packages. This commonly happens when you do big dependency upgrade like this. I'd suggest **individually updating packages**. That way, you can see which one breaks. 

### Extra Tip
When upgrading to a major, there are likely breaking changes so you also want to see the migration guide of these dependencies and see what needs to change on your end

**Comment by andreisemianiuk** [comment] 2022-10-13 07:01
> Hi @andreisemianiuk,
> 
> It appears that there's an issue with one of the updated packages. This commonly happens when you do big dependency upgrade like this. I'd suggest **individually updating packages**. That way, you can see which one breaks.
> 
> ### Extra Tip
> When upgrading to a major, there are likely breaking changes so you also want to see the migration guide of these dependencies and see what needs to change on your end

@marvinjude I found the issue in gatsby-plugin-modal-routing-3 plugin. After uninstall this plugin all work fine. But another problem is how I can replace it. gatsby-plugin-modal-routing doesn't work.

**Comment by marvinjude** [comment] 2022-10-13 07:23
Hi @andreisemianiuk, 

If you're using the plugin then you don't want to completely uninstall it. Trying out an older/ newer version is most likely your best bet. 

If that doesn't resolve it then  you'll want to open an issue on https://github.com/lsirivong/gatsby-plugin-modal-routing since we don't maintain the plug-in on our end. 

I'll proceed to close this issue. Feel free to reopen if you need to

💜

**Closed** 2022-10-13 07:25 UTC
