### ISSUE TITLE
Webpack error #98123 when running "gatsby develop"

### ISSUE THREAD

**Issue by coldPen** [gatsbyjs/gatsby#17557] opened 2019-09-11 14:31 UTC
## Description

`gatsby develop` doesn't work because of an error `#98123` from Webpack.

### Steps to reproduce

1. Clone my repo
2. `cd` into that repo
3. Run `npm install`
4. Run `gatsby develop`

### Expected result

Development server should start

### Actual result

I get this output:
```
ERROR #98123  WEBPACK
Generating SSR bundle failed
[BABEL] /home/fw33n/ateliers-chartreux/.cache/develop-static-entry.js: Cannot find module '@babel/helper-create-class-features-plugin' (While processing: "/home/fw33n/ateliers-chartreux/node_modules/@babel/plugin-proposal-class-properties/lib/index.js")
File: .cache/develop-static-entry.js
⠼ start webpack server
```

### Environment

`gatsby info --clipboard` (I'm running Ubuntu in WSL):
```
System:
  OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
  CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  Shell: 4.4.19 - /bin/bash
Binaries:
  Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
  npm: 6.11.3 - ~/.nvm/versions/node/v10.16.3/bin/npm
Languages:
  Python: 2.7.15+ - /usr/bin/python
npmPackages:
  gatsby: ^2.15.9 => 2.15.9
  gatsby-plugin-sass: ^2.1.13 => 2.1.13
  gatsby-source-contentful: ^2.1.33 => 2.1.33
npmGlobalPackages:
  gatsby-cli: 2.7.47
```

Additionnally, my `package.json`:
```
{
  "name": "ateliers-chartreux",
  "private": true,
  "description": "Le site des Ateliers Chartreux",
  "version": "0.1.0",
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write \"**/*.{js,jsx,json,md}\"",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing \""
  },
  "dependencies": {
    "gatsby": "^2.15.9",
    "gatsby-plugin-sass": "^2.1.13",
    "gatsby-source-contentful": "^2.1.33",
    "node-sass": "^4.12.0",
    "react": "^16.9.0",
    "react-dom": "^16.9.0"
  },
  "devDependencies": {
    "prettier": "^1.18.2"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-hello-world"
  },
  "bugs": {
    "url": "https://github.com/gatsbyjs/gatsby/issues"
  }
}

```

**Comment by jonniebigodes** [comment] 2019-09-11 20:24
@coldPen sorry that you're experiencing errors with gatsby, but based on the description itself it's a bit difficult to triage. Also you forgot to link the repo.

**Comment by coldPen** [comment] 2019-09-13 15:48
Thank you @jonniebigodes , [here's the repo](https://github.com/coldPen/ateliers-chartreux) although I'm not sure this has anything to do with the project itself, I can run `develop` and `build` on my Linux computer, this seems specific to WSL?

**Comment by jonniebigodes** [comment] 2019-09-14 01:07
@coldPen cloning it to my wsl machine and going to take a look at what could be the issue.

**Comment by jonniebigodes** [comment] 2019-09-14 22:35
@coldPen i've been testing this today and this one is kinda tricky to triage. Here are the steps i took.
- Cloned the repo into my ubuntu wsl "machine". I'm running Ubuntu 18.04 LTS
- Here's the result of `gatsby info` in Ubuntu.
![cold_pen_wsl_1](https://user-images.githubusercontent.com/22988955/64914209-3944bf00-d746-11e9-9152-20507399a9b9.png)
- Installed the dependencies and issued `sudo yarn develop`, since i've not configured yarn/npm i've got to run it with elevated privileges and i'm presented with the following:
![cold_pen_wsl_2](https://user-images.githubusercontent.com/22988955/64914231-7741e300-d746-11e9-9ade-2faef43db793.png)

The errors thrown are based on the fact that i confugured a space  for  issues regarding gatsby and contenful and when the plugin tries to fetch the data based on your query it will fail.

I would like for you to do a couple of steps to see if you can get it to run in wsl.
- Remove `package-lock.json` and/or `yarn.lock`
- Issue `gatsby clean` to purge any stale data.
- Remove `node_modules` folder.
- Install the dependencies again with your package manager of choice, either npm or yarn.
- Issue `gatsby develop` and see if the error does not pop back.

These because if memory serves me right it could be some issue with a package

**Comment by coldPen** [comment] 2019-09-15 11:34
Thank you for paying close attention to this! I'll get back to you as soon as I get back on this computer.

**Comment by shicholas** [comment] 2019-09-16 07:45
I am seeing this error too. My code works fine on my mac, but fails in CI, which uses Ubuntu (https://circleci.com/gh/1337lawyers/web/360)

**Comment by shicholas** [comment] 2019-09-16 07:59
I solved my issue by adding python to my environment - perhaps it's the same issue you're having @coldPen ?

**Comment by coldPen** [comment] 2019-09-16 13:19
@shicholas `Python: 2.7.15+ - /usr/bin/python` was displayed when I ran `gatsby info`, so I don't know? Maybe gatsby can't find python even if installed.

**Comment by jonniebigodes** [comment] 2019-09-16 20:11
@shicholas locally on ubuntu 18.04 it comes with python 2.7+ if not mistaken.

**Comment by shicholas** [comment] 2019-09-16 20:56
hmm, it's probably not it then. fwiw, I have Python 3.8 installed.

**Comment by shaneiadt** [comment] 2019-09-19 12:25
I'm getting the same issue when attempting to run `gatsby develop`.

```
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15
  Browsers:
    Edge: 44.18362.329.0
  npmPackages:
    gatsby: ^2.15.18 => 2.15.18
    gatsby-image: ^2.2.19 => 2.2.19
    gatsby-plugin-manifest: ^2.2.17 => 2.2.17
    gatsby-plugin-offline: ^3.0.7 => 3.0.7
    gatsby-plugin-react-helmet: ^3.1.7 => 3.1.7
    gatsby-plugin-sharp: ^2.2.24 => 2.2.24
    gatsby-source-filesystem: ^2.1.24 => 2.1.24
    gatsby-transformer-sharp: ^2.2.15 => 2.2.15
```
I've tried `gatsby clean` & re-installed all npm packages but no joy :(

Any help would be great, not quite sure were to go from here.

**Comment by shaneiadt** [comment] 2019-09-19 13:07
I've also updated to Python: 3.7.4 but still not working....dang!

**Comment by shaneiadt** [comment] 2019-09-19 13:19
I tried moving the project folder to another directory as I had a special character in the folder path & everything works fine now 👍

Maybe check your folder structure doesn't have any special characters. @coldPen

**Comment by coldPen** [comment] 2019-09-19 13:59
@shaneiadt thank you, but that isn't the case (repo is named `ateliers-chartreux`)
@jonniebigodes I followed  your instructions and nothing changed. I then reinstalled the Ubuntu subsystem and it's working again (till next time ?)

**Comment by jonniebigodes** [comment] 2019-09-19 18:15
@shaneiadt special characters would be for instance `à`,`ç`,`é`,`â` or `ã`, these being particular to the portuguese language, if it had used any of those for filenames and/or on path it would probably  break the build.

I considered that the use of characters could be the case in the last test that i did, because one special character of those listed above is being used in a query, but i confirmed that was not the case by modifying the query in the appropriate file to my contentful space and it returned the data correctly.

Also when i test a issue that pops in here, i usually use the following nomenclature for testing, create a gatsby site called `test-nameofauthorofissue` and it works fine with either windows 10 or linux in vm or wsl. 

@coldPen on one side i'm happy that it's working, but on the other side having to reinstall the wsl is something that is not actually productive if the issue persists.

**Comment by coldPen** [comment] 2019-09-27 13:34
I feel this problem is largely beyond my understanding, furthermore this only concerned a work environment which I only use secondarily. I'm sorry but I need to make this repo private since I have to commit my environment variables file to start deploying it. Won't close the issue though, if you think it's still relevant?

**Comment by jonniebigodes** [comment] 2019-09-29 14:33
@coldpen it could be some variable we're both missing, probably due to some permissions or something like that,go ahead and make the repo private and continue your work. I'll leave it you to if you want this open or not. If you want to close it feel free to do so and we can always re-open it.

**Closed** 2019-09-30 09:55 UTC
Labels: type: question or discussion

**Comment by denvercoder** [comment] 2019-10-06 12:22
For what it's worth I had this same issue and it came down to a case-sensitivity issue. It worked fine on my mac but failed on Netlify's servers because of some of the component names:

import Button from '../components/button

src 
     - components
          - Button
               -Button.js

**Comment by prydda** [comment] 2019-10-14 13:56
`npm run develop` will get you up & running for now.

**Comment by mujeeb91** [comment] 2019-12-04 08:11
I was facing the same issue. Then I checked my Node version and it was 8.9.0, **updated it to 12.13.1** (via nvm) and that fixed it.

**Comment by 454de6e** [comment] 2019-12-04 14:04
This error was introduced by updating an ESLint plugin, which is not related to Gatsby at all. My workaround is to delete `yarn.lock` and run `yarn` again to recreate the file. This may be a hint that the issue is triggered by a dependency that Gatsby and whatever caused it have in common.

**Comment by DevWichrowski** [comment] 2019-12-09 13:57
Hello,
I also had that problem, for typohraphy you need a file src/utils/typography.js
```
import Typography from "typography"
import fairyGateTheme from "typography-theme-fairy-gates"

const typography = new Typography(fairyGateTheme)

export const { scale, rhythm, options } = typography
export default typography
```

Also remember about gatsby-config.js in root
```
module.exports = {
  plugins: [
    {
      resolve: `gatsby-plugin-typography`,
      options: {
        pathToConfigModule: `src/utils/typography`,
      },
    },
  ],
```

**Comment by ForkInSpace** [comment] 2020-01-18 14:36
For some of you the issue could be with the node version. 
I just switched to node 10.13.0 from 8.9.4 with nvm and the development bundle compiles now w/o an error.

**Comment by Jongtelles** [comment] 2020-01-24 19:46
I am still running into this issue now attempting to follow the Gatsby tutorial, running node v13.6.0

**Comment by pravynandas** [comment] 2020-01-30 01:41
For what it's worth.. for the same package.json file, below two commands install the packages in node_modules quite differently. Pay attention to the 'core-js' folder (to which I'm getting **#98123 WEBPACK** error. The **gatsby new** version works great.

Note: Project under test is an official starter example from [here](https://www.gatsbyjs.org/starters/muhajirdev/gatsby-starter-redux-firebase/)

`gatsby new gatsby-starter-redux-firebase https://github.com/muhajirdev/gatsby-starter-redux-firebase`

`npm install` (with just only package.json file copied from above folder to another new folder)


Comparison of node_modules from both:
![image](https://user-images.githubusercontent.com/4099637/73412561-f8091200-42d6-11ea-92e5-995f1789a209.png)

Error on `gatsby develop`
![image](https://user-images.githubusercontent.com/4099637/73412736-9dbc8100-42d7-11ea-8064-c17233b6c34b.png)

**Comment by Connor-Callahan** [comment] 2020-02-07 03:29
deleted my .cache folder - worked like a charm.

**Comment by nimaiwalsh** [comment] 2020-02-22 23:43
> This error was introduced by updating an ESLint plugin, which is not related to Gatsby at all. My workaround is to delete `yarn.lock` and run `yarn` again to recreate the file. This may be a hint that the issue is triggered by a dependency that Gatsby and whatever caused it have in common.

This fixed it for me too.

**Comment by webmastervishal** [comment] 2020-02-23 07:18
> @coldPen i've been testing this today and this one is kinda tricky to triage. Here are the steps i took.
> 
> * Cloned the repo into my ubuntu wsl "machine". I'm running Ubuntu 18.04 LTS
> * Here's the result of `gatsby info` in Ubuntu.
>   ![cold_pen_wsl_1](https://user-images.githubusercontent.com/22988955/64914209-3944bf00-d746-11e9-9152-20507399a9b9.png)
> * Installed the dependencies and issued `sudo yarn develop`, since i've not configured yarn/npm i've got to run it with elevated privileges and i'm presented with the following:
>   ![cold_pen_wsl_2](https://user-images.githubusercontent.com/22988955/64914231-7741e300-d746-11e9-9ade-2faef43db793.png)
> 
> The errors thrown are based on the fact that i confugured a space for issues regarding gatsby and contenful and when the plugin tries to fetch the data based on your query it will fail.
> 
> I would like for you to do a couple of steps to see if you can get it to run in wsl.
> 
> * Remove `package-lock.json` and/or `yarn.lock`
> * Issue `gatsby clean` to purge any stale data.
> * Remove `node_modules` folder.
> * Install the dependencies again with your package manager of choice, either npm or yarn.
> * Issue `gatsby develop` and see if the error does not pop back.
> 
> These because if memory serves me right it could be some issue with a package.
> 
> Feel free to provide feedback so that we can close this issue or continue to work on it until we find a suitable solution.

Works perfectly fine

**Comment by alveshelio** [comment] 2020-03-20 20:56
I'm running into this issue too and I'm on a Mac but my setup is within a monorepo. If I create a new project outside of the monorepo I have no issues, however, if I create a new project within my monorepo or if I create it outside and move it to the monorepo I start having this issue.

One way I found was to remove node_modules and instead of using `yarn`, I've used `npm install` and it works just fine. However, this is a no go for me since I need to use yarn workspaces.
Has anyone experiences this same issue with a monorepo?

**Comment by bigxalx** [comment] 2020-03-30 08:17
I've been running into this issue using `gatsby build` (development worked fine) after updating an old gatsby v1 codebase to v2. 
It gave me the an additional message that webpack has some error with "vw". Didn't mention file name. I was able to fix it by pinning down the issue to a CSS file and editing the rules that contained calc and vw. It didn't like vw in the denominator. For example I changed stuff like `calc(1/5vw)` into `calc(1vw/5)`.  
Hope this is helpful to anyone who's getting the same issue.

**Comment by davidshq** [comment] 2020-04-07 20:35
I'm also running into this issue. I've attempted:
1. Running `gatsby clean`.
2. Deleting node_modules, package-lock.json and then re-running `npm install` followed by `gatsby develop`.

I'm using a Windows 10 Professional computer running an administrator session on Windows command prompt.

Seems like #19922 and #19268 may be related.

(I had tried using WSLv2 and Git Bash but encountered other issues with these)

**Comment by iyubinest** [comment] 2020-04-23 21:18
I was facing this also, adding `"babel-preset-gatsby"` to my babel config did the trick.

**Comment by software2019** [comment] 2020-04-30 15:36
Hi,
I having the following issue when running it. Could you please help me?
I am developing on my Mac. 
![Screenshot 2020-04-30 at 16 22 45](https://user-images.githubusercontent.com/47646501/80729702-8b352c00-8b00-11ea-884b-75db74c1b431.png)

**Comment by karthickram286** [comment] 2020-05-01 13:09
This is how I solved this problem,

1. Switched to node version 12.6.1 using nvm
2. Remove .cache, node_modules and package-lock.json/yarn-lock.json.
3. npm install

If the issue persists still, try doing a gatsby clean.

**Comment by aaronadamsCA** [comment] 2020-05-09 02:19
I resolved this by removing an old `.eslintrc` that referred to a plugin I'd uninstalled.

So if you're stuck, check that too!

**Comment by OoNascimentoOo** [comment] 2020-07-07 19:18
Hi guys, I can't solve this problem, I would like to help...

Generating development JavaScript bundle failed

Can't resolve '@styled-icons/foundation/Lightbulb' in 'C:\xampp\htdocs\my-blog\src\components\MenuBar'

If you're trying to use a package make sure that '@styled-icons/foundation/Lightbulb' is installed. If you're trying to use a local file make sure that the path is correct.

**Comment by johnmikel** [comment] 2020-07-10 02:18
> @coldPen i've been testing this today and this one is kinda tricky to triage. Here are the steps i took.
> 
> * Cloned the repo into my ubuntu wsl "machine". I'm running Ubuntu 18.04 LTS
> * Here's the result of `gatsby info` in Ubuntu.
>   ![cold_pen_wsl_1](https://user-images.githubusercontent.com/22988955/64914209-3944bf00-d746-11e9-9152-20507399a9b9.png)
> * Installed the dependencies and issued `sudo yarn develop`, since i've not configured yarn/npm i've got to run it with elevated privileges and i'm presented with the following:
>   ![cold_pen_wsl_2](https://user-images.githubusercontent.com/22988955/64914231-7741e300-d746-11e9-9ade-2faef43db793.png)
> 
> The errors thrown are based on the fact that i confugured a space for issues regarding gatsby and contenful and when the plugin tries to fetch the data based on your query it will fail.
> 
> I would like for you to do a couple of steps to see if you can get it to run in wsl.
> 
> * Remove `package-lock.json` and/or `yarn.lock`
> * Issue `gatsby clean` to purge any stale data.
> * Remove `node_modules` folder.
> * Install the dependencies again with your package manager of choice, either npm or yarn.
> * Issue `gatsby develop` and see if the error does not pop back.
> 
> These because if memory serves me right it could be some issue with a package.
> 
> Feel free to provide feedback so that we can close this issue or continue to work on it until we find a suitable solution.

This worked! Fantastic solution.

**Comment by baloghrebecca** [comment] 2020-07-14 10:56
I've encountered the very same problem and I've tried out all the answers on here and it still threw the same error for me. 

Turns out I had following import `import { clearConfigCache } from "prettier";` in one of my files (not sure where that came from). As soon as I deleted it, it worked again.

**Comment by lsmucassi** [comment] 2020-09-16 17:40
The issue for me is running npm install with sudo, it al went fine when I removed the .lock files and node modules, re-installed modules by just running npm install

**Comment by manavm1990** [comment] 2020-11-03 16:58
The main culprit was: '.babelrc' I had created a custom one to work with _styled components._ In doing so, I had 'disrupted' the 'Gatsby flow'.'

The fix was to make sure I had this in '.babelrc':

```json
"presets": [
    [
      "babel-preset-gatsby",
      {
        "targets": {
          "browsers": [
            ">0.25%",
            "not dead"
          ]
        }
      }
    ]
  ]
```

Well, `"targets"` don't necessarily matter - but must include `"babel-preset-gatsby"`

**Comment by kuworking** [comment] 2020-12-20 18:42
@manavm1990 thanks! Exactly my very same problem, now my working `.babelrc` looks like this 

```json
{
  "plugins": ["babel-plugin-styled-components", "@babel/plugin-proposal-class-properties"],
  "presets": [
    [
      "babel-preset-gatsby",
      {
        "targets": {
          "browsers": [">0.25%", "not dead"]
        }
      }
    ]
  ]
}
```

**Comment by rwchampin** [comment] 2021-01-18 07:02
Hey Guys - just to confirm - this is 100% from using react-styled-components & perhaps sass as well - im using sass so I had to deal w that too - watch the node-sass version you're runing b it tries to run ^5.0.0 but it should be ^4.0.0 make sure you add ```gatsby-plugin-styled-components``` to gatsby-config.js and your .babelrc has, at the minimum:
```
{
  "presets": ["babel-preset-gatsby"],
  "plugins": ["@babel/plugin-syntax-jsx", "@babel/plugin-proposal-class-properties"]
}
```

**Comment by AndrewTraub** [comment] 2021-03-25 21:38
I'm having the same problem.  It's specific to a css file and if I remove reference to the file, the compilation works.  The css file though, has worked in the past and has not been modified.  I'm getting an error URIERROR: URI Malformed but the line and column referenced in the error is just the } character and my IDE (php storm) is not showing any errors.

**Comment by vKeeReaL** [comment] 2021-07-14 19:02
My fix :)
Be an old-school develop I always name my urgent folders with "#" prefix to make them first into explorer list) And this time I called my folder D://#Sites/gatsby and get this issue. After I've renamed it to D://Sites/gatsby and reinstall gatsby instance, the issue is gone.

**Comment by KoolP** [comment] 2021-08-30 20:06
updatet a eslint devDependencie with `npm install eslint@latest --save-dev` from 6. to 7. version fixed my.

**Comment by paulvscode** [comment] 2022-04-21 05:13
Hi, for those still looking for a fix for that issue, and after trying 300000 solutions, what worked for me is to "yarn", let yarn install the yarn.lock, then gatsby develop again. Sounds like yarn is a prerequisite after all...

**Comment by Luchanso** [comment] 2022-07-25 07:54
I had the same issue, but after some updates to the yarn.lock file, I got success build:
https://github.com/Luchanso/luchanso.github.io/pull/62/commits/7d43256e671382bb71e5f8d21cce604dc23220c2

I think this happen with babel plugin - maybe exist not compatible patch version with gatsby

**Comment by nyrzeff** [comment] 2025-03-27 15:46
Tried many solutions and the only one that worked was removing `gatsby-plugin-eslint` from `gatsby-config.ts` and deleting it with `pnpm remove gatsby-plugin-eslint`, apparently this plugin no longer works with Gatsby v5?
