### ISSUE TITLE
[gatsby-source-wordpress] fetch more than 10 posts (per_page)

### ISSUE THREAD

**Issue by owenhoskins** [gatsbyjs/gatsby#1647] opened 2017-07-28 13:15 UTC
Hello. Amazing amazing work first off. I am so excited by the prospect of fetching data into Gatsby from legacy Wordpress sites. 

The default limit of posts that can be pulled from the api is 10. 

```
=== [ Fetching wordpress__POST ] === http://wordpress:8888/wp-json/wp/v2/posts
⢀ source and transform nodeswordpress__POST fetched : 10
```

The `per_page` and `page` query parameters allows this to be configured. 

Would it be possible to set this parameter from options config?

`http://example.com/wp-json/wp/v2/posts?per_page=20`

**Comment by sebastienfi** [comment] 2017-07-28 13:32
Just spotted that today. This will be fixed asap. Thanks a lot for reporting it I got kinda lazy to create an issue :)

The `per_page` query parameter is maxed to 100 so I will have to provide a function that will loop throught pages. `/wp-json/wp/v2/posts/?per_page=100&page=1000`

**Comment by owenhoskins** [comment] 2017-07-31 14:01
Just tested out the snippet from https://github.com/gatsbyjs/gatsby/issues/1647#issuecomment-318652606 and ran into errors. 

I came across another issue with a slightly different approach and with a simple modification got it working:

https://github.com/WP-API/WP-API/issues/2316#issuecomment-319068834

```
add_filter( 'rest_endpoints', function( $endpoints ){
    if ( ! isset( $endpoints['/wp/v2/posts'] ) ) {
        return $endpoints;
    }
    $endpoints['/wp/v2/posts'][0]['args']['per_page']['default'] = 100;
    return $endpoints;
});
```

**Comment by sebastienfi** [comment] 2017-07-31 22:26
This may be a suitable solution and an easy workaround. Thank you for sharing it ! Can you PR a modification of the documentation on the readme of the package so that users know that the issue is bypassed by having their `function.php` tweaked ? https://github.com/gatsbyjs/gatsby/edit/master/packages/gatsby-source-wordpress/README.md

**Comment by cr101** [comment] 2017-08-06 00:22
@owenhoskins  will this solution work for custom post types as well?

**Comment by owenhoskins** [comment] 2017-08-07 07:55
@cr101 Have not tested but I believe so. If you dump $endpoints to the debug log you will likely find your custom post type with a nested array like this:

  ```
  [per_page] => Array
      (
          [description] => Maximum number of items to be returned in result set.
          [type] => integer
          [default] => 10
          [minimum] => 1
          [maximum] => 100
          [sanitize_callback] => absint
          [validate_callback] => rest_validate_request_arg
      )
  ```
Setting the per_page default should work by just swapping out `posts` with `books`, for example:

`$endpoints['/wp/v2/books'][0]['args']['per_page']['default'] = 100;`

**Comment by sebastienfi** [comment] 2017-08-08 09:31
Here is an intent to solve this problem without having to modify WordPress : https://github.com/gatsbyjs/gatsby/pull/1733

**Closed** 2017-08-14 19:32 UTC
