### ISSUE TITLE
gatsby develop -H 0.0.0.0 --open does not open correct page on Windows

### ISSUE THREAD

**Issue by crhistianramirez** [gatsbyjs/gatsby#16434] opened 2019-08-07 15:38 UTC
## Description
`--open` does not play nicely with `-H`. Sends me to and prints that I should be able to access local dev server on `http://0.0.0.0:8000/` however I get a "site can't be reached message"

### Steps to reproduce
1. run `gatsby develop -H 0.0.0.0 --open`

### Expected result
Should open my app

What should happen?
Should open my app

### Actual result
Renders a non functional page

### Environment

System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 10.16.0 - C:\Users\CRHIST~1\AppData\Local\Temp\yarn--1565192299909-0.8662975271117463\node.CMD
    Yarn: 1.13.0 - C:\Users\CRHIST~1\AppData\Local\Temp\yarn--1565192299909-0.8662975271117463\yarn.CMD
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.1 - C:\Users\CrhistianR\AppData\Local\Programs\Python\Python37-32\python.EXE
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    gatsby: ^2.13.38 => 2.13.39
    gatsby-image: ^2.2.0 => 2.2.6
    gatsby-plugin-catch-links: ^2.1.0 => 2.1.2
    gatsby-plugin-manifest: ^2.2.0 => 2.2.4
    gatsby-plugin-material-ui: ^2.0.1 => 2.1.4
    gatsby-plugin-mdx: ^1.0.7 => 1.0.16
    gatsby-plugin-offline: ^2.2.0 => 2.2.4
    gatsby-plugin-react-helmet: ^3.1.0 => 3.1.2
    gatsby-plugin-sharp: ^2.2.1 => 2.2.9
    gatsby-plugin-typescript: ^2.1.0 => 2.1.2
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-remark-autolink-headers: ^2.1.0 => 2.1.3
    gatsby-remark-images: ^3.1.2 => 3.1.7
    gatsby-remark-prismjs: ^3.3.0 => 3.3.3
    gatsby-source-filesystem: ^2.1.6 => 2.1.6
    gatsby-transformer-json: ^2.2.2 => 2.2.2
    gatsby-transformer-remark: ^2.5.0 => 2.6.9
    gatsby-transformer-sharp: ^2.2.0 => 2.2.4

**Comment by devrchancay** [comment] 2019-08-08 19:20
Hi, you can attach a screenshot to see the problem better, I just tried `npx gatsby -H 0.0.0.0 --open` and I had no problem.

>try using the latest version of gatsby cli

**Comment by lannonbr** [comment] 2019-08-10 12:03
So I can confirm this is a Windows issue, as `0.0.0.0` as a host to listen on means to push to be routable on the network on all interfaces.

The issue is, MacOS and Linux will route these if you try navigating to it, but on Windows, it returns a 404. Likely due to Windows commenting that 0.0.0.0 is technically an invalid IP so it wouldn't need to implement routing functionality for this.

So the question here is if when we use `gatsby develop -H 0.0.0.0 --open` on Windows, if we should maybe instead push people to the network IP (192.168...) or just open localhost:8000. Or if we should just make a note of this in the docs as making a gotcha for a particular OS & IP feels a bit messy.

**Comment by crhistianramirez** [comment] 2019-08-11 19:28
> commenting that 0.0.0.0 is technically an invalid IP

Could we not just push people to localhost:8000 instead of that invalid IP? That would work for everyone right?

**Comment by sidharthachatterjee** [comment] 2019-08-20 13:16
> Or if we should just make a note of this in the docs as making a gotcha for a particular OS & IP feels a bit messy.

This is documented in https://www.gatsbyjs.org/docs/gatsby-cli/#develop

I've opened a fix for this in https://github.com/gatsbyjs/gatsby/issues/16434. Please test (don't have access to Windows myself)

**Closed** 2019-08-30 16:26 UTC
