### ISSUE TITLE
[gatsby-plugin-postcss ] build failed

### ISSUE THREAD

**Issue by Dogtiti** [gatsbyjs/gatsby#10466] opened 2018-12-14 09:21 UTC
```

  System:
    OS: macOS 10.14.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.12.1 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.110
    Safari: 12.0.1
  npmPackages:
    gatsby: ^2.0.19 => 2.0.50 
    gatsby-image: ^2.0.15 => 2.0.20 
    gatsby-plugin-less: ^2.0.7 => 2.0.7 
    gatsby-plugin-manifest: ^2.0.5 => 2.0.9 
    gatsby-plugin-offline: ^2.0.11 => 2.0.15 
    gatsby-plugin-postcss: ^2.0.2 => 2.0.2 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.2 
    gatsby-plugin-sharp: ^2.0.7 => 2.0.12 
    gatsby-source-filesystem: ^2.0.4 => 2.0.8 
    gatsby-source-strapi: ^0.0.5 => 0.0.5 
    gatsby-transformer-sharp: ^2.1.4 => 2.1.8 
```

here is the error img:
![image](https://user-images.githubusercontent.com/38354472/49994457-841d8480-ffc4-11e8-8bd9-f196ef7ed78a.png)

![image](https://user-images.githubusercontent.com/38354472/49994204-d01bf980-ffc3-11e8-8847-1f6adcbabf9a.png)

here is my `gatsby-config.js`:
![image](https://user-images.githubusercontent.com/38354472/49994260-f93c8a00-ffc3-11e8-9afb-e5c617b44e50.png)

and my css:
![image](https://user-images.githubusercontent.com/38354472/49994286-08233c80-ffc4-11e8-9d1c-cbf62f522084.png)

I read the [document](https://www.gatsbyjs.org/packages/gatsby-plugin-postcss/?=),it said:
![image](https://user-images.githubusercontent.com/38354472/49994355-40c31600-ffc4-11e8-88f8-a0bacb792bec.png)
So,I have done it with the document,but it doesn't work..

**Comment by LekoArts** [comment] 2018-12-14 11:03
Do you have a link to your repository so that we could have a look at the complete code? Would help us reproduce this issue

**Comment by Dogtiti** [comment] 2018-12-14 11:21
@LekoArts sorry,I made a mistake in the usage of the plugin.
I don‘t use CSS Module，I just use CSS in each JS file like this:
![image](https://user-images.githubusercontent.com/38354472/50000545-d8306500-ffd4-11e8-8266-42d17eaa1528.png)
![image](https://user-images.githubusercontent.com/38354472/50000554-de264600-ffd4-11e8-959a-a9f6a5ed9498.png)
and in the` gatsby-config.js`,I add `gatsby-plugin-postcss` without any extra options liake this:
![image](https://user-images.githubusercontent.com/38354472/50000670-352c1b00-ffd5-11e8-94fd-0eea6053bb50.png)
but it still returns an error like this:

![image](https://user-images.githubusercontent.com/38354472/50000697-4bd27200-ffd5-11e8-9e0d-e9ce4402f4d6.png)

and I'm sorry to provide the repo for some reasons..(T T)

**Comment by sidharthachatterjee** [comment] 2018-12-17 10:55
@Dogtiti Apologies for the issues you're facing. Based on the screenshot, it appears that build is failing because no PostCSS config is found. 

We'll need a little more info to help you resolve this. Is it possible for you to link to a minimal reproduction repo? You can strip off all private code and only keep the minimum required to reproduce this. 

That'll really help us in resolving this quickly. Thanks!

**Closed** 2019-01-19 02:34 UTC
Labels: status: needs reproduction
