### ISSUE TITLE
Placeholder not completing on Google Chrome

### ISSUE THREAD

**Issue by glassesUSA** [gatsbyjs/gatsby#33796] opened 2021-11-01 13:53 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When using Google Chrome, not all images load fully. On any other browser it seems to work fine.

This is not always though, it is only on occasion that it doesnt work...

### Reproduction Link

https://github.com/glassesUSA/gatsby-bug - Only seems to trigger on build

### Steps to Reproduce

Go to site
Scroll to testimonials
Observe

### Expected Result

all images load

### Actual Result

Side images do not load

![image](https://user-images.githubusercontent.com/76479522/139682563-dd977744-fa54-4484-8bfc-3d7487ad79f9.png)

### Environment

```shell
System:
    OS: macOS 11.2
    CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 95.0.4638.54
    Edge: 94.0.992.38
    Firefox: 87.0
    Safari: 14.0.3
  npmPackages:
    gatsby: ^4.0.1 => 4.0.2 
    gatsby-cli: ^4.0.0 => 4.0.0 
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5 
    gatsby-plugin-image: ^2.0.0 => 2.0.0 
    gatsby-plugin-manifest: ^4.0.0 => 4.0.0 
    gatsby-plugin-react-helmet: ^5.0.0 => 5.0.0 
    gatsby-plugin-sass: ^5.0.0 => 5.0.0 
    gatsby-plugin-sharp: ^4.0.1 => 4.0.1 
    gatsby-remark-images: ^6.0.0 => 6.0.0 
    gatsby-source-filesystem: ^4.0.0 => 4.0.0 
    gatsby-transformer-sharp: ^4.0.0 => 4.0.0
```

### Config Flags

    DEV_SSR: true,

**Comment by LekoArts** [comment] 2021-11-01 14:08
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by glassesUSA** [comment] 2021-11-01 17:00
Hey!

https://github.com/glassesUSA/gatsby-bug You can find it here! This seems to only happen when on build and not on develop and only with Google Chrome

**Comment by Bruce-Hopkins-Jr** [comment] 2021-11-02 10:50
Hi! 

I'm trying to reproduce the issue by visiting the link provided. I used Google Chrome and also Chromium but the images are loading on my side.

Have you checked if the images load on other devices?

**Comment by glassesUSA** [comment] 2021-11-02 11:24
The images load on other web browsers perfectly... It's only on Chrome. It's the majority of the time it doesn't load on chrome but sometimes it can.

**Comment by glassesUSA** [comment] 2021-11-02 11:25
![image](https://user-images.githubusercontent.com/76479522/139837738-7908ca98-c828-4eb0-959c-c87089a950d5.png)

Just checked again and yeah it still doesnt load for me. Console showing no errors

**Comment by glassesUSA** [comment] 2021-11-04 09:30
@LekoArts Are you able to reproduce?

**Comment by BarrySaikSoundry** [comment] 2021-11-04 23:27
I ran into this. forcing https:// for all images fixed it. 
I was using wp media offload and the free version does not support forcing https. you may have to upgrade. 

it's due to new security settings on chrome.

**Comment by glassesUSA** [comment] 2021-11-30 09:46
@LekoArts ?

**Comment by linoxyn** [comment] 2021-12-12 18:19
I get this same issue, again only on Google Chrome's desktop browser. All my packages are up to date. I find it tends to  happen after running a push or merge to a new build and deploy.  I have set the code in gatsby-browsser.js onServiceWorkerUpdateReady to prompt 'Reload to display the latest version?' Config has 'gatsby-plugin-offline' set. Sorry, I have not yet built a small repo for this issue to test.

**Comment by linoxyn** [comment] 2021-12-15 02:50
I've just updated to `"gatsby": "^4.4.0"` along with all other new package updates. I now see that this issue happens in all browsers I have installed on a Windows 11 machine. It seems random which 2 to 6 images don't get past the placeholder stage though if I do a browser refresh on any page all the images will load normally. This issue consistently happens after a new build/deploy to the host. Could this be a cache issue? 

URL: [johnhansenartist.com](https://johnhansenartist.web.app/)

I have implemented the recommended cache settings to the  `firebase.json` file from the [Gatsby ](https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/deploying-to-firebase/) documents.

package.json (snip)
```
"dependencies": {
    "@fontsource/lato": "^4.5.0",
    "babel-plugin-styled-components": "^2.0.2",
    "dotenv": "^10.0.0",
    "firebase": "^9.6.1",
    "gatsby": "^4.4.0",
    "gatsby-plugin-firebase-v9.0": "^1.0.2",
    "gatsby-plugin-google-gtag": "^4.4.0",
    "gatsby-plugin-image": "^2.4.0",
    "gatsby-plugin-manifest": "^4.4.0",
    "gatsby-plugin-offline": "^5.4.0",
    "gatsby-plugin-react-helmet": "^5.4.0",
    "gatsby-plugin-react-svg": "^3.1.0",
    "gatsby-plugin-robots-txt": "^1.6.14",
    "gatsby-plugin-sharp": "^4.4.0",
    "gatsby-plugin-sitemap": "^5.4.0",
    "gatsby-plugin-styled-components": "^5.4.0",
    "gatsby-plugin-typography": "^4.4.0",
    "gatsby-source-filesystem": "^4.4.0",
    "gatsby-source-google-docs": "^2.2.0",
    "gatsby-transformer-remark": "^5.4.0",
    "gatsby-transformer-sharp": "^4.4.0",
    "prop-types": "^15.7.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-helmet": "^6.1.0",
    "styled-components": "^5.3.3",
    "typography": "^0.16.21",
    "typography-breakpoint-constants": "^0.16.19"
  },
  "devDependencies": {
    "@babel/eslint-parser": "^7.16.5",
    "@babel/preset-react": "^7.16.5",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.25.3",
    "eslint-plugin-prettier": "^4.0.0",
    "eslint-plugin-react-hooks": "^4.3.0",
    "prettier": "^2.5.1",
    "stylelint": "^14.1.0",
    "stylelint-config-recommended": "^6.0.0",
    "stylelint-config-styled-components": "^0.1.1",
    "stylelint-processor-styled-components": "^1.10.0"
  },
```

**Comment by linoxyn** [comment] 2021-12-18 12:41
FWIW, this is a quirky issue, though in my case, this seems resolved. Again after making sure all packages are up to date, the one thing I changed was the GatsbyImage loading. I had 2 larger images open on a new page where the iteration contained `loading={i === 0 ? 'eager' : 'lazy'}`  Since it was difficult for me to pinpoint this random issue I cannot say with certainty that the removal of this code fixed the issue.

**Comment by LekoArts** [comment] 2022-04-06 06:41
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2022-04-06 06:41 UTC
Labels: type: bug, status: needs reproduction, topic: media
