### ISSUE TITLE
gatsby production build throwing yoga-layout-prebuilt module error

### ISSUE THREAD

**Issue by 10-seconds** [gatsbyjs/gatsby#25166] opened 2020-06-21 06:50 UTC
## gatsby production build throwing below error

```
$ gatsby build
11:55:23 AM: /opt/build/repo/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
11:55:23 AM:         throw ex;
11:55:23 AM:         ^
11:55:23 AM: Error: Cannot find module 'acorn'
11:55:23 AM: Require stack:
11:55:23 AM: - /opt/build/repo/node_modules/acorn-jsx/index.js
11:55:23 AM: - /opt/build/repo/node_modules/buble-jsx-only/dist/buble.cjs.js
```

### Steps to reproduce
Goto [https://github.com/10secondsofcode/10secondsofcode.git](https://github.com/10secondsofcode/10secondsofcode.git) and Pull the code into local.
npm install and npm run build

### Expected result

Built will be success without any error.

### Actual result

Now throwing error as
``` 
$ gatsby build
11:55:23 AM: /opt/build/repo/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
11:55:23 AM:         throw ex;
11:55:23 AM:         ^
11:55:23 AM: Error: Cannot find module 'acorn'
11:55:23 AM: Require stack:
11:55:23 AM: - /opt/build/repo/node_modules/acorn-jsx/index.js
11:55:23 AM: - /opt/build/repo/node_modules/buble-jsx-only/dist/buble.cjs.js
```
### Environment
```
$ gatsby info --clipboard

  System:
    OS: Windows 8.1
    CPU: (4) x64 Intel(R) Core(TM) i3-5010U CPU @ 2.10GHz
  Binaries:
    npm: 6.13.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    gatsby: ^2.23.0 => 2.23.7
    gatsby-plugin-feed: ^2.0.8 => 2.5.5
    gatsby-plugin-google-analytics: ^2.0.5 => 2.3.4
    gatsby-plugin-manifest: ^2.0.5 => 2.4.12
    gatsby-plugin-offline: ^3.0.30 => 3.2.11
    gatsby-plugin-react-helmet: ^3.0.0 => 3.3.4
    gatsby-plugin-sharp: ^2.0.16 => 2.6.12
    gatsby-plugin-sitemap: ^2.0.4 => 2.4.5
    gatsby-plugin-typography: ^2.2.0 => 2.5.4
    gatsby-remark-autolink-headers: ^2.0.12 => 2.3.5
    gatsby-remark-copy-linked-files: ^2.0.5 => 2.3.5
    gatsby-remark-images: ^3.1.39 => 3.3.11
    gatsby-remark-prismjs: ^3.0.0 => 3.5.4
    gatsby-remark-responsive-iframe: ^2.0.5 => 2.4.5
    gatsby-remark-smartypants: ^2.0.5 => 2.3.4
    gatsby-source-filesystem: ^2.0.12 => 2.3.12
    gatsby-transformer-remark: ^2.1.17 => 2.8.17
    gatsby-transformer-sharp: ^2.1.9 => 2.5.5
```

Thanks

**Comment by LekoArts** [comment] 2020-06-22 08:53
Hi, thanks for the issue!

I cloned your repository and was able to build it without problems. Your issue is one of a couple issues that were already opened about this topic (https://github.com/gatsbyjs/gatsby/issues?q=is%3Aissue+sort%3Aupdated-desc+yoga-layout-prebuilt+is%3Aopen) and to keep things organized I'll close this as a duplicate of https://github.com/gatsbyjs/gatsby/issues/24577 for now. Please comment on that issue. Thanks!

**Closed by LekoArts** 2020-06-22 08:53 UTC
Labels: topic: cli, type: bug

**Comment by 10-seconds** [comment] 2020-07-11 04:46
@LekoArts  Thanks..!
