### ISSUE TITLE
Cache is not invalidated when programatically build pages and the data is changed

### ISSUE THREAD

**Issue by vstoyanoff** [gatsbyjs/gatsby#28281] opened 2020-11-25 09:20 UTC
## Description

I am using Netlify CMS with markdown files and generating pages from certain collections. When the data for an entry in the collection changes the page is not updated with new data after the build. The site is deployed in Netlify and a caching plugin is used to persist cache between builds for faster builds.

### Steps to reproduce

Use Netlify CMS with markdown files and build pages in gatsby-node using a certain collection.

### Expected result

Page data should be updated with the changes.

### Actual result

The page is displaying old data.

### Environment

  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.17.0 - ~/.nvm/versions/node/v12.17.0/bin/node
    Yarn: 1.22.1 - ~/.yarn/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.17.0/bin/npm
  Languages:
    Python: 3.8.5 - /Users/macintoshhd/.pyenv/shims/python
  Browsers:
    Chrome: 86.0.4240.198
    Firefox: 72.0.2
    Safari: 14.0
  npmPackages:
    gatsby: ^2.27.1 => 2.27.1 
    gatsby-image: ^2.3.1 => 2.6.0 
    gatsby-plugin-i18n: ^1.0.1 => 1.0.1 
    gatsby-plugin-mailchimp: ^5.2.2 => 5.2.2 
    gatsby-plugin-manifest: ^2.3.3 => 2.7.0 
    gatsby-plugin-netlify: ^2.6.0 => 2.6.0 
    gatsby-plugin-netlify-cms: ^4.5.0 => 4.5.0 
    gatsby-plugin-offline: ^3.1.2 => 3.5.0 
    gatsby-plugin-purgecss: ^5.0.0 => 5.0.0 
    gatsby-plugin-react-helmet: ^3.2.1 => 3.5.0 
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.3 
    gatsby-plugin-sass: ^2.2.1 => 2.6.0 
    gatsby-plugin-sharp: ^2.5.3 => 2.9.0 
    gatsby-plugin-sitemap: ^2.3.2 => 2.7.0 
    gatsby-remark-images: ^3.2.2 => 3.6.0 
    gatsby-source-filesystem: ^2.2.2 => 2.6.1 
    gatsby-transformer-remark: ^2.7.1 => 2.11.0 
    gatsby-transformer-sharp: ^2.4.3 => 2.7.0

**Comment by LekoArts** [comment] 2020-11-25 09:39
I'll close this as a duplicate of https://github.com/gatsbyjs/gatsby/issues/26520

**Closed by LekoArts** 2020-11-25 09:39 UTC
Labels: status: triage needed, type: bug
