### ISSUE TITLE
Can you traceback errors plase?

### ISSUE THREAD

**Issue by MichaelLisboa** [gatsbyjs/gatsby#26019] opened 2020-07-25 12:21 UTC
## Summary

It would be great if you guys could write in some tracebacks in build errors.

### Motivation

If it drives me crazy, I'm sure it probably drives other people crazy.

## Steps to resolve this issue

Some try/catch plus traceback to file/line error messages would be a massive help in debugging `gatsby build` errors.

For example, the error I'm getting is

`Expected an attribute.`

That is so cryptic I've chosen to build altars to all known and unknown gods. I'll sacrifice a few chickens and goats, and pray until the new moon, upon which, I will prostrate myself in the most demeaning way possible. Hoping that one of those gods will come down, tap my forehead, and I will be enlightened to know exactly which line of my code is breaking the build.

Cheers,

Michael ;-)

**Comment by blainekasten** [comment] 2020-07-27 14:17
Hey @MichaelLisboa, we do actually have code to catch errors and try to print stack traces from the error site. 

2 questions:

1. What gatsby version are you on?
1. Can you create a repro for this specific error?

**Comment by LekoArts** [comment] 2020-09-21 10:04
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-09-21 10:04 UTC
Labels: status: needs reproduction, type: question or discussion
