### ISSUE TITLE
gatsby-plugin-create-client-paths not working with build command

### ISSUE THREAD

**Issue by chuyenlee** [gatsbyjs/gatsby#22234] opened 2020-03-13 03:04 UTC
## Description

Gatsb + Contentful

I following this document https://medium.com/the-couch/live-preview-in-gatsby-without-the-cost-21f8ac0337bb to create a dynamic link to present data from a content type without generate content type page. 

The idea is use gatsby-plugin-create-client-paths plugin to create link.

I see this working with development stage. but when build i got 404 page when access link.

**Comment by LekoArts** [comment] 2020-03-16 10:57
Thank you for opening this!

Quickly skimming over the article it seems it's intended behavior that it only works in development mode (which makes sense). Reach out to the author to clarify your question :)

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2020-03-16 10:57 UTC
Labels: type: question or discussion
