### ISSUE TITLE
[gatsby-plugin-postcss-sass] Fails build on fresh cache

### ISSUE THREAD

**Issue by ryami333** [gatsbyjs/gatsby#3093] opened 2017-12-01 22:42 UTC
When I build with an empty/deleted `.cache` folder, I get the following error:

```bash
error Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "6" does not.


  Error: Names must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but "6" does not.
  
  - Array.forEach
  
  - Array.forEach
  
  - Array.forEach
  
  - Array.forEach
  

error Command failed with exit code 1.
```

I am using `gatsby-plugin-postcss-sass` in combination with `gatsby-source-prismic` and on the surface it would appear that the issue lies with the latter (which is why I have contributed to an [issue](https://github.com/angeloashmore/gatsby-source-prismic/issues/14) on that Github repo), but if I swap `gatsby-plugin-postcss-sass` for just `gatsby-plugin-sass` then this issue goes away.

I can confirm that Prismic documents have alphanumeric IDs eg. 'WhKeviAAAPVGBcE6' so the source of the "6" in this instance is not Prismic - I suspect it's the webpack module id.

It's peculiar that on the second and subsequent builds, the build succeeds without error.

**Comment by ryami333** [comment] 2017-12-03 23:56
The largest consequence of this is that I can't do builds on CI/CD platforms like Netlify.

**Comment by szimek** [comment] 2018-01-10 10:58
I'm getting the same error, just with `"0"` instead of `"6"`. I'm not using Prismic, but filesystem source plugin.

**Comment by tuyakhov** [comment] 2018-03-11 13:08
I had the similar issue and it was caused by passing the wrong parameters to `postCssPlugins` attribute in the configuration file. This might be helpful https://github.com/gatsbyjs/gatsby-starter-blog/issues/30

**Comment by KyleAMathews** [comment] 2018-09-08 04:27
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Closed by KyleAMathews** 2018-09-08 04:27 UTC
