### ISSUE TITLE
[gatsby-source-contentful] Optional fields

### ISSUE THREAD

**Issue by lambert-velir** [gatsbyjs/gatsby#29556] opened 2021-02-17 17:17 UTC
## Description

I'd like to have optional fields in my Contentful models.  The problem is stated on https://www.gatsbyjs.com/plugins/gatsby-source-contentful/:

> At the moment, fields that do not have at least one populated instance will not be created in the GraphQL schema.

If there doesn't exist an entry with a certain optional field, and the graphql query is expecting that field, then the gatsby build will break.

Here's our real world example: 

We have our build triggered by a Contentful webhook whenever an Entry changes in contentful.  Imagine we have some entries that have an optional field, eg, `email`.  We add some entries with `email` populated, write our graphql queries and build the site, everything works.

One day, the content authors decided that they don't want to have the emails show on the frontend, so they delete the emails from all the entries.  The webhook fires and it starts a build.  At this point, no entry has an `email` in it, so the schema doesn't have `email` in it either.  The graphql query was written to include an email, but it's no longer in the schema, so the build will break.

Our current workaround involves using [gatsby-plugin-schema-snapshot](https://www.gatsbyjs.com/plugins/gatsby-plugin-schema-snapshot/) and maintaining a whole host of stub content in Contentful that we need to publish every time we want to update any Contentful models and `schema.gql`.  To say the least, it's not a very efficient workflow.  

The "At the moment" in the documentation suggests this might change in the future. Is it on the roadmap to include all possible fields in the graphql schema to avoid this situation? Is it possible to build the schema based on the _model_ instead of the _data_?

### Steps to reproduce

1. Create a Contentful model with a `name` and `email`.
2. Create an entry with just a `name` (leave `email` blank)
3. Run project and open graphiql, `email` is not available in graphql

### Expected result

All possible fields should be available in graphql, including `email`

### Actual result

Only `name` is available

**Comment by LekoArts** [comment] 2021-02-18 08:24
This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/28892

**Closed by LekoArts** 2021-02-18 08:24 UTC
Labels: status: triage needed, type: bug
