### ISSUE TITLE
Gatsby develop fails with no such file or directory .cache/json/_dev-404-page_.json

### ISSUE THREAD

**Issue by jeffreymeng** [gatsbyjs/gatsby#26859] opened 2020-09-10 22:50 UTC
## Description

Occasionally, when I run `gatsby develop`, I will get the error 
`Error: ENOENT: no such file or directory, open '/Users/jmeng/montavistamun/.cache/json/_dev-404-page_.json'` after gatsby finishes the build step.

**It doesn't happen every time, and if I rerun gatsby develop it will usually go away.**

You can see the error here: https://asciinema.org/a/4GK7BPO6GsT5fA9P9SwXlHd4K?t=1:53
In this recording, I clone the repo straight from github and make no modifications.

### Steps to reproduce

Clone https://github.com/jeffreymeng/montavistamun
Run `yarn install` and then `gatsby develop`.
It should fail with the error.
If you run `gatsby develop` again, the error is gone.

### Expected result

Gatsby should start the dev server.

### Actual result

About one in every two times I run the command, I get the error, and the command fails. The other times, it runs with no issue.

### Environment

```
 System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 85.0.4183.102
    Firefox: 77.0.1
    Safari: 13.1.2
  npmPackages:
    gatsby: 2.24.57 => 2.24.57
    gatsby-background-image: ^1.1.2 => 1.1.2
    gatsby-image: ^2.4.17 => 2.4.17
    gatsby-plugin-eslint: 2.0.8 => 2.0.8
    gatsby-plugin-heap: ^1.1.0 => 1.1.0
    gatsby-plugin-manifest: 2.4.28 => 2.4.28
    gatsby-plugin-offline: 3.2.27 => 3.2.27
    gatsby-plugin-postcss: ^2.3.11 => 2.3.11
    gatsby-plugin-react-helmet: 3.3.10 => 3.3.10
    gatsby-plugin-sass: ^2.3.12 => 2.3.12
    gatsby-plugin-sharp: ^2.6.35 => 2.6.35
    gatsby-plugin-typegen: ^2.2.1 => 2.2.1
    gatsby-source-filesystem: ^2.3.29 => 2.3.29
    gatsby-transformer-sharp: ^2.5.14 => 2.5.14
  npmGlobalPackages:
    gatsby-cli: 2.12.87
```

**Comment by mlenser** [comment] 2020-09-11 08:06
Duplicate of #26287

This is a mac only issue as discussed in that issue.

**Comment by LekoArts** [comment] 2020-09-14 06:16
Duplicate of https://github.com/gatsbyjs/gatsby/issues/26287

**Closed by LekoArts** 2020-09-14 06:16 UTC
Labels: status: triage needed, type: bug
