### ISSUE TITLE
gatsby-source-wordpress problem while querying some fields from Polylang, in combination with Wp Graphql Polylang

### ISSUE THREAD

**Issue by tiggeymone** [gatsbyjs/gatsby#30597] opened 2021-03-31 15:37 UTC
Hello,

I'm facing some inexpected issues while trying to fetch posts that belong to multiple post types, using WpContentNode and Polylang, in combination with the Wp Graphql Polylang plugin. Unfortunately, it seems that Gatsby Source Wordpress isn't able to filter WpContentNode by language. Instead, WpContentNodes seem to be properly queried by language using the graphiql interface of the WpGraphQL plugin.

As you can see below, in the graphiql interface on the Wordpress Admin side I can filter contentNodes by language:

<img width="261" alt="Screenshot 2021-03-31 at 17 35 05" src="https://user-images.githubusercontent.com/4254655/113171063-7187f180-9247-11eb-8118-62c59e345afd.png">

But, unfortunately, the same filter doesn't work on the Gatbsy side:

<img width="240" alt="Screenshot 2021-03-31 at 17 35 59" src="https://user-images.githubusercontent.com/4254655/113171249-92504700-9247-11eb-9b96-a0728db882a6.png">

Instead, the language filter is correctly supported for each post type that supports translations:

<img width="282" alt="Screenshot 2021-04-02 at 16 19 16" src="https://user-images.githubusercontent.com/4254655/113423676-2e588a80-93cf-11eb-81ae-3046a03c0e53.png">

I noticed that I have the same problem while filtering menu items by language. Below you can see that I have no problems on the WP Admin side:

<img width="264" alt="Screenshot 2021-04-02 at 16 22 10" src="https://user-images.githubusercontent.com/4254655/113423904-960ed580-93cf-11eb-9a02-b73463ab9f20.png">

But the same filter doesn't show up on the Gatsby side:

<img width="274" alt="Screenshot 2021-04-02 at 16 23 13" src="https://user-images.githubusercontent.com/4254655/113424002-bb9bdf00-93cf-11eb-9e4b-7f087ad9a9a7.png">

Because of these issues I have adopted a hacky solution, parsing the objects directly from gatsby-node and injecting via page context in templates, but this is very annoying, because of bad design and no incremental build support.

I created an issue in wp-graphql-polylang repo as well, but they think that it should be a gatsby-source-wordpress related problem. Do you have any idea on how to overcome these issues and include support for the missing filters?

Thank you in advance!

**Comment by LekoArts** [comment] 2021-04-06 08:29
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-04-14 07:55
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed** 2021-04-14 07:57 UTC
Labels: status: needs reproduction, topic: WordPress, type: bug
