### ISSUE TITLE
Client Side Data Fetching Axios headers returning as html not json in gatsby but passes jest test

### ISSUE THREAD

**Issue by Kielan** [gatsbyjs/gatsby#25036] opened 2020-06-17 01:05 UTC
## Description

This is at minimum at request for additional documentation regarding how gatsby manages client side requests.

Reference repo with tests here
https://github.com/Kielan/restaurant-suggest

I am attempting to use miragejs and gatsbyjs together

### Steps to reproduce

clone repo

yarn

jest,

then try to run yarn run start

the app will run at localhost:/8000/protected route.

while the test passes, both the fetch and axios requests fail, because the content headers are not being set properly. Or maybe being overridden by a gatsbyjs configuration.

I am attempting to use 

I know that I could try to use axios and set the graphql template, but for test and sanity's sake I should be able to match the client request to the jest request. What is happening?!

### Environment
  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.106
    Firefox: 56.0
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.21.37 => 2.21.37 
    gatsby-image: ^2.4.4 => 2.4.4 
    gatsby-plugin-manifest: ^2.4.5 => 2.4.5 
    gatsby-plugin-offline: ^3.2.3 => 3.2.3 
    gatsby-plugin-react-helmet: ^3.3.1 => 3.3.1 
    gatsby-plugin-sharp: ^2.6.4 => 2.6.4 
    gatsby-source-filesystem: ^2.3.4 => 2.3.4 
    gatsby-theme-auth0: ^1.1.1 => 1.1.1 
    gatsby-transformer-sharp: ^2.5.2 => 2.5.2 
  npmGlobalPackages:
    gatsby-cli: 2.5.4

**Comment by vladar** [comment] 2020-06-17 09:49
The reproduction seems incomplete:

1. It requires environment variables for auth0. I could workaround this by commenting out the `gatsby-theme-auth0` plugin in `gatsby-config`

2. After this the project fails with:

```
Generating development JavaScript bundle failed

Can't resolve '../utils/auth' in 'restaurant-suggest\src\pages'

If you're trying to use a package make sure that '../utils/auth' is installed. If you're trying to use a local file make sure that the path is correct.
```

I was able to workaround this by removing `callback.js` from pages (imports `../utils` which do not exist).

3. Then it turned out that `MirageMockServer();` was commented out in `gatsby-browser.js`. So I enabled it and it finally ran. 

4. Then it looked like Mirage passthrough was set incorrectly here: https://github.com/Kielan/restaurant-suggest/blob/a8d9450ccf315f2a835148a2564369ae3a9d4b6d/src/mirage-mock-server.ts#L68

So had to change `this.passthrough('localhost:8000/page-data/**');` to `this.passthrough('/**');`

Finally, it ran and now I see the following in the console:

![screenshot](https://user-images.githubusercontent.com/115628/84882418-6d745400-b0b9-11ea-9eb2-c887952f470f.png)

This seems to be working fine for me now. I get correct headers (as set in `mirage-mock-server.ts`). 

Maybe the problem was because of the incorrect passthrough? Or am I missing something? Please provide more details.

**Comment by freiksenet** [comment] 2020-07-03 09:05
Hi! 

I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. 

Thanks!

**Closed by freiksenet** 2020-07-03 09:05 UTC
Labels: status: needs more info, type: question or discussion
