### ISSUE TITLE
Gatsby es-lint loader prevents other loaders to manipulate source

### ISSUE THREAD

**Issue by MamoonAhmad** [gatsbyjs/gatsby#25847] opened 2020-07-18 22:59 UTC
## Description

I built a custom webpack loader which's job was to convert a specific JSX Element to CallExpression.
for example 

`<SomeJSX />`

will get converted to 

`{AnotherCall()}`

Bearing in mind that `AnotherCall` is defined somewhere in the code but `<SomeJSX />` is not.
my loader was able to successfully convert JSX to a callExpression but I always got the error `<SomeJSX />` is not defined. 

Reason why it was happening was, eslint loader from gatsby was enforced to `pre` in webpack config.
If this is intentional behavior then, (I apologize for my lack of knowledge) please provide a way to alter this behavior.

**Comment by madalynrose** [comment] 2020-07-21 18:31
I'm sorry you're running into this issue @MamoonAhmad! I've tagged in a teammate who has more context on the way we handle webpack. 

In the meantime, to help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by wardpeet** [comment] 2020-07-22 07:10
@MamoonAhmad It's intentional behaviour. There are 3 workarounds for this.

1. You can remove the eslint-loader all together (below is some pseudo code)
```js
// gatsby-node.js
exports.onCreateWebpackConfig = ({
  actions,
  getConfig
}) => {
  const config  = getConfig();
  const eslintRuleIndex = config.module.rules.findIndex(rule => rule.enforce === 'pre')
  config.module.rules.splice(eslintRuleIndex, 1);

  actions.replaceWebpackConfig(config);
}
```
2. Create a .eslintrc where you disable a few eslint rules or add `SomeJSX` to the list of globals
3. Add `/* globals SomeJSX */` to every file that uses it.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Closed by wardpeet** 2020-07-22 07:10 UTC
Labels: status: needs reproduction, topic: webpack/babel, type: bug
