### ISSUE TITLE
How to manage theme conflicts? Putting 2 themes together

### ISSUE THREAD

**Issue by mostafachatillon** [gatsbyjs/gatsby#21512] opened 2020-02-16 20:24 UTC
I am using 2 Gatsby themes that work great individually, but when I try to put them together in one website (theme 1 for mywebsite.com and theme 2 for mywebsite.com/blog), they fail. My gatsby-config.js plugins are: 

```js
module.exports = {
  plugins: [
    {
      resolve: "gatsby-theme-musician",
        basePath: `/`,
        content: `contentlanding`,
        // pwaName: null
      }
    },
    {
      resolve: "@narative/gatsby-theme-novela",
      options: {
        contentPosts: "content/posts",
        contentAuthors: "content/authors",
        basePath: "blog",
        sources: {
          local: true,
          contentful: false
        },
      },
    },
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `Novela by Narative`,
        short_name: `Novela`,
        start_url: `/`,
      },
    },
  ],
};
```

I get  errors:

 ERROR #85923  GRAPHQL
...
 ERROR #11321  PLUGIN
...
failed createPages - 5.921s

**Comment by LekoArts** [comment] 2020-02-17 09:18
This is most likely not a bug with Gatsby but with how both themes were set up. However, to be sure on that we'd need to see the full error log and/or a [minimal reproduction][reproduction].

[reproduction]: https://gatsby.dev/reproduction

**Comment by mostafachatillon** [comment] 2020-02-17 21:10
@LekoArts I deployed each website separately on a netlify instance, and then combine them with proxy rewrite 200. But I found another issue: https://github.com/gatsbyjs/gatsby/issues/21525

**Comment by LekoArts** [comment] 2020-02-18 08:47
Will close this issue then :)

**Closed by LekoArts** 2020-02-18 08:47 UTC
Labels: status: needs more info, type: question or discussion
