### ISSUE TITLE
[gatsby-source-wordpress] Your WordPress server appears to be overloaded

### ISSUE THREAD

**Issue by supriome** [gatsbyjs/gatsby#30902] opened 2021-04-16 13:45 UTC
## Description

Your WordPress server at http://api.sunnwell.com/graphql appears to be overloaded, even when i set schema all option to 1.

![image](https://user-images.githubusercontent.com/19944032/115033365-f1c37d80-9efc-11eb-8a15-83fe73f4af5e.png)

Is there a problem of plugin gatsby-source-wordpress?

**Comment by LekoArts** [comment] 2021-04-19 08:31
Hi, thanks for the issue!

To make the process of resolving problems quicker for both sides we need you to fill out the issue template and give us a minimal reproduction:

```md
<!--
  Please fill out each section below, otherwise, your issue will be closed. This info allows Gatsby maintainers to diagnose (and fix!) your issue as quickly as possible.

  Useful Links:
  - Documentation: https://www.gatsbyjs.com/docs/
  - How to File an Issue: https://www.gatsbyjs.com/contributing/how-to-file-an-issue/

  Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
-->

## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
```

**Comment by harunalrashyid** [comment] 2021-04-19 18:06
recently i'm facing same of this issue, when our client site grows. Try checking your wordpress.

in my case, the server don't have enough memory. 
so increasing memory limit should solve this problem

**Comment by LekoArts** [comment] 2021-04-26 08:42
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-04-26 08:42 UTC
Labels: status: needs reproduction, topic: WordPress, type: bug
