### ISSUE TITLE
On mobile (iOS): multiple instances of the same image - additional instances remain blurred

### ISSUE THREAD

**Issue by jaredhill4** [gatsbyjs/gatsby#33194] opened 2021-09-15 16:02 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

This issue seems to be specific to mobile devices, as I have yet to experience it in a desktop browser.

I have tested and seen it in both iOS Safari and Chrome.

On initial load (or reload) of a page, when trying to use two instances of the same image (same local file path or remote URL) on the same page, the one that is last to enter the viewport after load/reload does not unblur (lazy load). Rather it remains unloaded until the user navigates to another page.

This issue is occurring when trying to use multiple instances of the same image from a server/CMS (with `GatsbyImage`) and a local, static image (with `StaticImage`).

### Reproduction Link

https://capitolcitychurch-postlaunchbugs.gtsb.io/

### Steps to Reproduce

1. Open the link in an iOS device on Safari or Chrome.
2. Note that the logo in the header lazy loads just fine.
3. Scroll down to the footer and see that the logo at the top of the footer is still blurred.
4. Upon navigating to another page, the footer logo will load.
5. Refreshing the page allows you to reproduce the issue, regardless of the page you are on.

### Expected Result

All instances of the same image used on a page should load as expected (when they enter the viewport, or however/whenever images are normally expected to load).

### Actual Result

Only one instance of the same image (the one that enters the viewport first) loads when the site is first loaded. Only navigating to another page causes other instances to load.

### Environment

```shell
System:
    OS: macOS 11.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.10.0/bin/yarn
    npm: 7.18.1 - ~/.nvm/versions/node/v12.10.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 93.0.4577.82
    Edge: 93.0.961.44
    Firefox: 91.0.2
    Safari: 14.0.3
  npmGlobalPackages:
    gatsby-cli: 2.12.101
```

### Config Flags

PRESERVE_FILE_DOWNLOAD_CACHE: true
PARALLEL_SOURCING: true
PRESERVE_WEBPACK_CACHE: true

**Comment by LekoArts** [comment] 2021-09-20 06:32
Closing as duplicate of https://github.com/gatsbyjs/gatsby/issues/31669

**Closed by LekoArts** 2021-09-20 06:32 UTC
Labels: type: bug, topic: media
