### ISSUE TITLE
gatsby develop ERROR #11321  PLUGIN ERROR #98123  WEBPACK ERROR #85925  GRAPHQL

### ISSUE THREAD

**Issue by fcsm82** [gatsbyjs/gatsby#22191] opened 2020-03-12 01:18 UTC
## Description

 ERROR #11321  PLUGIN

 Error: Input file contains unsupported image format

ERROR
Failed to retrieve metadata from image /Users/alexey.ivanov/Documents/gatsby-wordpress/src/images/gatsby-astronaut.png Input file contains unsupported image format

ERROR #98123  WEBPACK

Generating SSR bundle failed

[BABEL] /Users/alexey.ivanov/Documents/gatsby-wordpress/.cache/develop-static-entry.js: No "exports" main resolved in /Users/alexey.ivanov/Documents/gatsby-wordpress/node_modules/@babel/helper-compilation-targets/package.json

### Steps to reproduce

gatsby develop

### Expected result

Generated bundle

### Actual result

 ~/Documents/gatsby-wordpress | on master  gatsby develop                                                                                                                   ✔ | ≡ | at 21:14:24 
success open and validate gatsby-configs - 0.024s
success load plugins - 0.508s
success onPreInit - 0.004s
success initialize cache - 0.009s
success copy gatsby files - 0.051s
success onPreBootstrap - 0.008s
success createSchemaCustomization - 0.005s
success source and transform nodes - 0.049s
success building schema - 0.261s
success createPages - 0.002s
success createPagesStatefully - 0.060s
success onPreExtractQueries - 0.002s
success update schema - 0.034s
success extract queries from components - 0.264s
success write out requires - 0.028s
success write out redirect data - 0.002s

 ERROR #11321  PLUGIN

"gatsby-plugin-manifest" threw an error while running the onPostBootstrap lifecycle:

Input file contains unsupported image format

  Error: Input file contains unsupported image format

success onPostBootstrap - 0.057s
⠀
info bootstrap finished - 4.237 s
⠀

 ERROR

Failed to retrieve metadata from image /Users/alexey.ivanov/Documents/gatsby-wordpress/src/images/gatsby-astronaut.png Input file contains unsupported image format

  Error: Input file contains unsupported image format

 ERROR #85925  GRAPHQL

There was an error in your GraphQL query:

Cannot return null for non-nullable field ImageSharpFluid.aspectRatio.

The field "ImageSharpFluid.aspectRatio." was explicitly defined as non-nullable via the schema customization API (by yourself or a plugin/theme). This means that this field is not optional and you have to define a value. If this is not your desired behavior and you defined the schema yourself, go to "createTypes" in gatsby-node.js. If you're using a plugin/theme, you can learn more here on how to fix field types:
https://www.gatsbyjs.org/docs/schema-customization/#fixing-field-types

   1 | fragment GatsbyImageSharpFluid on ImageSharpFluid {
   2 |   base64
>  3 |   aspectRatio
     |   ^
   4 |   src
   5 |   srcSet
   6 |   sizes
   7 | }
   8 |
   9 | query usersalexeyIvanovDocumentsgatsbyWordpresssrccomponentsimageJs2969191536 {
  10 |   placeholderImage: file(relativePath: {eq: "gatsby-astronaut.png"}) {
  11 |     id
  12 |     childImageSharp {
  13 |       id

File path: /Users/alexey.ivanov/Documents/gatsby-wordpress/src/components/image.js
Plugin: none

success run queries - 0.078s - 8/8 102.77/s

 ERROR #98123  WEBPACK

Generating SSR bundle failed

[BABEL] /Users/alexey.ivanov/Documents/gatsby-wordpress/.cache/develop-static-entry.js: No "exports" main resolved in /Users/alexey.ivanov/Documents/gatsby-wordpress/node_modules/@babel/helper-compilation-targets/package.json

File: .cache/develop-static-entry.js

not finished Build manifest and related icons - 0.503s

### Environment

System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.10.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.2 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: 73.0.1
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.19.7 => 2.19.7
    gatsby-image: ^2.2.39 => 2.2.39
    gatsby-plugin-manifest: ^2.2.39 => 2.2.39
    gatsby-plugin-offline: ^3.0.32 => 3.0.32
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.21
    gatsby-plugin-sharp: ^2.4.3 => 2.4.3
    gatsby-source-filesystem: ^2.1.46 => 2.1.46
    gatsby-transformer-sharp: ^2.3.13 => 2.3.13
  npmGlobalPackages:
    gatsby-cli: 2.10.7

**Comment by pieh** [comment] 2020-03-12 09:49
Hey this is likely caused by outdated `@babel/helper-compilation-targets` dependency of dependency (which had problem in some versions to work in Node 13) - please try to delete package-lock.json or yarn.lock (depending which package manager you use and re-install dependencies).

**Comment by fcsm82** [comment] 2020-03-12 12:03
> Hey this is likely caused by outdated `@babel/helper-compilation-targets` dependency of dependency (which had problem in some versions to work in Node 13) - please try to delete package-lock.json or yarn.lock (depending which package manager you use and re-install dependencies).

Thanks, It resolved ERROR #98123 WEBPACK

**Comment by vladar** [comment] 2020-03-13 11:21
Thank you for opening this, @fcsm82 

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by fcsm82** [comment] 2020-03-13 13:06
Hi  @vladar it resolved only last issue ERROR #98123 WEBPACK, but I still have ERROR #11321 and ERROR #85925

**Comment by vladar** [comment] 2020-03-13 13:28
Oh, sorry, I didn't realize it was a partial fix. The other error seems similar to #20698 

Have you tried the fix proposed there:

```
rm -rf node_modules &&
SHARP_IGNORE_GLOBAL_LIBVIPS=true yarn
```

**Comment by FranciscoImanolSuarez** [comment] 2020-03-13 14:06
The Webpack error  #98123  what is it due to? I'm in the same situation

**Comment by fcsm82** [comment] 2020-03-13 15:17
> rm -rf node_modules &&
> SHARP_IGNORE_GLOBAL_LIBVIPS=true yarn

@vladar It works! Thanks! Also helped to remove globally installed libvips

**Closed** 2020-03-13 20:52 UTC
Labels: type: bug

**Comment by DCStudioProjects** [comment] 2020-12-23 17:50
> Oh, sorry, I didn't realize it was a partial fix. The other error seems similar to #20698
> 
> Have you tried the fix proposed there:
> 
> ```
> rm -rf node_modules &&
> SHARP_IGNORE_GLOBAL_LIBVIPS=true yarn
> ```

Hey guys, this has removed all my node modules, but fortunately I had a backup, so I have the same error, use NPM, and don't know what to do :) Could you help me?

**Comment by OliverHuntsman** [comment] 2021-02-07 20:48
> > Oh, sorry, I didn't realize it was a partial fix. The other error seems similar to #20698
> > Have you tried the fix proposed there:
> > ```
> > rm -rf node_modules &&
> > SHARP_IGNORE_GLOBAL_LIBVIPS=true yarn
> > ```
> 
> Hey guys, this has removed all my node modules, but fortunately I had a backup, so I have the same error, use NPM, and don't know what to do :) Could you help me?

This happened to me too - did you get anywhere with it?

**Comment by DCStudioProjects** [comment] 2021-02-08 06:59
> > > Oh, sorry, I didn't realize it was a partial fix. The other error seems similar to #20698
> > > Have you tried the fix proposed there:
> > > ```
> > > rm -rf node_modules &&
> > > SHARP_IGNORE_GLOBAL_LIBVIPS=true yarn
> > > ```
> > 
> > Hey guys, this has removed all my node modules, but fortunately I had a backup, so I have the same error, use NPM, and don't know what to do :) Could you help me?
> 
> @DCStudioProjets This happened to me too - did you get anywhere with it?
> 

I'm sorry for incorrect info, you should run `npm i` after removing node_modules and package-lock.json.

**Comment by OliverHuntsman** [comment] 2021-02-08 21:00
Great - I got there thank you - I had to delete package-lock-json before running the command to get it to work - it took a few goes!
