### ISSUE TITLE
error There was a problem parsing the GraphQL query in file:

### ISSUE THREAD

**Issue by kumaresan-subramani** [gatsbyjs/gatsby#27006] opened 2020-09-23 14:29 UTC
## Description

I am using below mentioned gatsby verison, my compilation getting failed fro 4pm today

`"[gatsby](https://npmjs.com/package/gatsby)": "^2.24.27",`

### Steps to reproduce

My  application is huge i can share  my entire application

### Expected result

get compiled

### Actual result

```
error There was a problem parsing the GraphQL query in file: /jenkins/workspace/EJ2-13795-gatsby-automation-6SSPORWHIBTZVEP3ULARN7IOUBUZRIK4MULEBTPLVFGIZ2YJBTRQ/repositories/ej2-react-api-library/api-apps/src/templates/layout.js _graphql.default.stripIgnoredCharacters is not a function

[0m
[0m  [0m[97m[41mTypeError[0m[37m[41m:[0m[37m[41m [0m[97m[41m_graphql.default.stripIgnoredCharacters is not a function[0m
[0m  [0m
[0m  [0m[90m-[0m [0m[93mindex.js[0m[90m:[0m[93m157[0m[37m [0m[37mgetGraphQLTag[0m
[0m  [0m  [0m[90m[ej2-react-api-library]/[babel-plugin-remove-graphql-queries]/index.js:157:4[0m  [0m  [0m[90m3[0m
[0m  [0m
```

### Environment

[EJ2-13795-gatsby-automation-6SSPORWHIBTZVEP3ULARN7IOUBUZRIK4MULEBTPLVFGIZ2YJBTRQ] Running shell script
+ gatsby info --clipboard

  [4mSystem:[0m
    OS: Linux 4.15 Ubuntu 18.04.5 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz
    Shell: 4.4.20 - /bin/bash
  [4mBinaries:[0m
    Node: 10.22.1 - /usr/bin/node
    npm: 6.5.0 - /usr/bin/npm
  [4mnpmPackages:[0m
    gatsby-cli: 2.11.1 => 2.11.1 
  [4mnpmGlobalPackages:[0m
    gatsby-cli: 2.4.1

**Comment by ascorbic** [comment] 2020-09-24 14:56
Hi

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it would be really helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

Thanks!

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2020-10-05 14:34
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-10-05 14:34 UTC
Labels: status: needs reproduction, type: bug
