### ISSUE TITLE
In case height is not defined, it still remans as not null or undefined

### ISSUE THREAD

**Issue by selodev** [gatsbyjs/gatsby#30864] opened 2021-04-14 02:10 UTC
Even in case, width is defined, height remains null or undefined
Also if height is defined, this time with remains null or undefined. 

Replace the following code:

  // Case 1: width of height were passed in, make sure it isn't larger than the actual image
  width = width && Math.min(width, imgDimensions.width)
  height = height && Math.min(height, imgDimensions.height)

  // Case 2: neither width or height were passed in, use default size
  if (!width && !height) {
    width = Math.min(DEFAULT_FLUID_WIDTH, imgDimensions.width)
    height = width / aspectRatio
  }

  // if it still hasn't been found, calculate width from the derived height.
  // TS isn't smart enough to realise the type for height has been narrowed here
  if (!width) {
    width = (height as number) * aspectRatio
  }

To the following code fixes all scenarios.

 // Neither width or height were passed in, use default size
  width = width ?? height ? Math.round(height * aspectRatio) : DEFAULT_FLUID_WIDTH;
  height = height ?? Math.round(width / aspectRatio);

  // width and height were passed in, make sure it isn't larger than the actual image
  width = width && Math.min(width, imgDimensions.width);
  height = height && Math.min(height, imgDimensions.height);

https://github.com/gatsbyjs/gatsby/blob/0daa8f4cad2373a8d2ab1f5d55402ac3a4276313/packages/gatsby-plugin-image/src/image-utils.ts#L526
https://github.com/gatsbyjs/gatsby/blob/0daa8f4cad2373a8d2ab1f5d55402ac3a4276313/packages/gatsby-plugin-image/src/image-utils.ts#L531

**Comment by LekoArts** [comment] 2021-04-14 07:42
Hi, thanks for the issue!

To make the process of resolving problems quicker for both sides we need you to fill out the issue template and give us a minimal reproduction:

```md
<!--
  Please fill out each section below, otherwise, your issue will be closed. This info allows Gatsby maintainers to diagnose (and fix!) your issue as quickly as possible.

  Useful Links:
  - Documentation: https://www.gatsbyjs.com/docs/
  - How to File an Issue: https://www.gatsbyjs.com/contributing/how-to-file-an-issue/

  Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
-->

## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
```

**Comment by LekoArts** [comment] 2021-04-21 08:00
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-04-21 08:00 UTC
Labels: status: needs more info, status: needs reproduction
