### ISSUE TITLE
[gatsby-plugin-schema-snapshot] clears schema.gql on update if file already exists

### ISSUE THREAD

**Issue by njbmartin** [gatsbyjs/gatsby#30583] opened 2021-03-31 04:58 UTC
https://github.com/gatsbyjs/gatsby/blob/f628c3801226f5b500d74b5b41bca4caa72a9e00/packages/gatsby-plugin-schema-snapshot/gatsby-node.js#L17-L26

`update` doesn't work as expected. First results in a schema.gql file that contains just this comment:

```### Type definitions saved at 2021-03-31T04:58:56.193Z ###```

Then the next build complains of an unexpected EOF as a results of the above.

I have a feeling the offending line is line 21, combined with nuking the file on line 24?

For context, using this mainly with `gatsby-source-contentful`, as Gatsby can't infer fields or content types unless they are used at least once. The workaround is to create a `kitchen sink` environment which has every possible content type and field used and use this plugin to store the inferred types.

**Comment by LekoArts** [comment] 2021-04-06 08:32
Hi, thanks for the issue!

To make the process of resolving problems quicker for both sides we need you to fill out the issue template and give us a minimal reproduction:

```md
<!--
  Please fill out each section below, otherwise, your issue will be closed. This info allows Gatsby maintainers to diagnose (and fix!) your issue as quickly as possible.

  Useful Links:
  - Documentation: https://www.gatsbyjs.com/docs/
  - How to File an Issue: https://www.gatsbyjs.com/contributing/how-to-file-an-issue/

  Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
-->

## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
```

**Comment by LekoArts** [comment] 2021-04-14 07:55
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed** 2021-04-14 07:56 UTC
Labels: status: needs more info, status: needs reproduction
