### ISSUE TITLE
Sitemap Plugin Not Respecting PathPrefix

### ISSUE THREAD

**Issue by dcurletti** [gatsbyjs/gatsby#4723] opened 2018-03-26 22:10 UTC
https://github.com/gatsbyjs/gatsby/blob/c707cd17446e4f23d0015a286ce4609208b6b50b/packages/gatsby-plugin-sitemap/src/internals.js#L51

The current sitemap generator does not append the path prefix when writing the sitemap file.  

If I'm not mistaken, this file needs `import { withPrefix } from "gatsby-link"` and the line should be: 
`url: site.siteMetadata.siteUrl + withPrefix(edge.node.path)`.  

I'm unsure if `withPrefix` already grabs the siteUrl, so it might just be `url: withPrefix(edge.node.path)`

**Comment by KyleAMathews** [comment] 2018-03-26 22:18
Sounds like a bug! Would you like to add a PR fixing this?

**Comment by lightstrike** [comment] 2018-03-30 04:47
@dcurletti I took a shot at this in #4770 based on your recommendation, can you try testing on your side?

**Comment by lightstrike** [comment] 2018-04-11 02:50
@KyleAMathews I took another look at this and came up empty. Here are steps to reproduce the issue:

1. Clone this sample repo: `git clone https://github.com/lightstrike/gatsby-prefix-sitemap` that applies the attempted fix I made [here](https://github.com/gatsbyjs/gatsby/pull/4770/commits/0675fda12882eb031b89961a3c7193c229d154ae#diff-a627f3ef3dc8b682479f174b8c29fc20R55)
2. Follow the instructions in the example README
3. Go to http://localhost:9000/prefix/sitemap.xml
4. Observe no prefix, such as `http://localhost:8000/a/`

It seems that the `__PREFIX_PATHS__` global is not set before the the sitemap serialize function runs. Is there some kind of test we could write to check this?

**Comment by pieh** [comment] 2018-04-11 10:05
`pathPrefix` is passed to `gatsby-node.js` function hooks - you can extract it here https://github.com/gatsbyjs/gatsby/blob/c707cd17446e4f23d0015a286ce4609208b6b50b/packages/gatsby-plugin-sitemap/src/gatsby-node.js#L7 (`{ graphql, pathPrefix }`) and pass it around

**Comment by lightstrike** [comment] 2018-04-12 22:30
Thanks @pieh, very insightful! I got a working version together in #4770

**Comment by KyleAMathews** [comment] 2018-09-08 04:26
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Closed by KyleAMathews** 2018-09-08 04:26 UTC
