### ISSUE TITLE
[gatsby-source-wordpress] Support non-pretty permalinks

### ISSUE THREAD

**Issue by robinmetral** [gatsbyjs/gatsby#12649] opened 2019-03-18 19:23 UTC
## Summary

I'd like to reopen the discussion that was started in [this PR last june](https://github.com/gatsbyjs/gatsby/pull/5053) about supporting non-pretty urls in `gatsby-source-wordpress`.

As mentioned in [WordPress's REST API Handbook](https://developer.wordpress.org/rest-api/#routes-endpoints), the typical WP API endpoint is `http://oursite.com/wp-json/`, unless we have **non-pretty permalinks**:

> If you’re using non-pretty permalinks, you should pass the REST API route as a query string parameter. The route http://oursite.com/wp-json/ in the example above would hence be http://oursite.com/?rest_route=/.

This is also the case if the WordPress instance is hosted on a subdomain, for example `admin.oursite.com`.

The endpoint here is `http://oursite.com/?rest_route=/`, and hitting `http://oursite.com/wp-json/` returns a 404.

### Motivation

I think it makes sense to host the WordPress endpoint on a subdomain, so that editors can easily reach the CMS. For this `gatsby-source-wordpress` needs to support endpoints with query params like `http://oursite.com/?rest_route=/`

**Comment by robinmetral** [comment] 2019-03-18 19:27
(also I think that [this part of the plugin's docs](https://www.gatsbyjs.org/packages/gatsby-source-wordpress/#test-your-wordpress-api) can be updated: changing permalinks to anything other than Plain won't work if WordPress is hosted on a subdomain)

**Comment by robinmetral** [comment] 2019-03-19 08:26
There seems to have been a problem on my end, a brand new installation of WordPress on a subdomain exposes as expected the `/wp-json` endpoint.

**Comment by re1** [comment] 2019-03-27 16:07
I am running into a similar issue with a local docker instance based on https://docs.docker.com/compose/wordpress/. [localhost:8080/wp-json/](http://localhost:8080/wp-json/) cannot be found while [localhost:8080/?rest_route=/](http://localhost:8080/?rest_route=/) works fine.

Changing the permalink settings did not help either.

**Comment by robinmetral** [comment] 2019-03-27 16:53
@re1 feel free to reopen this issue if you'd like, even though it was solved for me I still think that supporting non-pretty permalinks would be a good thing :slightly_smiling_face:

**Comment by re1** [comment] 2019-03-27 17:17
Thank you for the fast response :+1:  It seems like I do not have permission to re-open your issue.

> even though it was solved for me I still think that supporting non-pretty permalinks would be a good thing

This is especially true as `?rest_route=` seems to be the more robust solution anyway. The WordPress Developer Handbook even states that
> Clients should keep this variation in mind and ensure that both routes can be handled seamlessly.

**Comment by robinmetral** [comment] 2019-03-27 17:19
Reopening :+1:

**Comment by wardpeet** [comment] 2019-04-16 06:54
Hi @re1!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by re1** [comment] 2019-04-19 08:39
Hey @wardpeet!
Please excuse my late response. I am building upon gatsby-starter-default including gatsby-source-wordpress through the following lines inside `gatsby-config.js`.

```js
{
  resolve: 'gatsby-source-wordpress',
  options: {
    baseUrl: process.env.WP_URL,
    protocol: process.env.WP_PROTOCOL,
    hostingWPCOM: false,
    useACF: false,
    includedRoutes: ['**/media', '**/pages', '**/posts'],
  },
},
```

WordPress was hosted locally using Docker as described here: https://docs.docker.com/compose/wordpress/.

As WordPress does not expose `wp-json` (http://localhost:8080/wp-json/) by default I was unable to use the Gatsby WordPress source. This can usually be resolved by setting [pretty permalinks](https://codex.wordpress.org/Using_Permalinks).

> Changing the permalink settings did not help either.

Because of an issue in my docker setup pretty permalinks did not work for me, which is why this became a problem for me.

WordPress itself recommends using `?rest_route=` (http://localhost:8080/?rest_route=/) instead as it will also work without permalink configuration ([1]).

To reproduce this issue setting up the gatsby-wordpress-starter with a local WordPress instance should be enough as non-pretty permalinks are used by default.

[1]: https://developer.wordpress.org/rest-api/#routes-endpoints

**Comment by cjhaviland** [comment] 2019-04-21 19:25
Hey @wardpeet  and @re1 ,

I am just setting up GatsbyJS to make a new website for my podcast that uses wordpress and I ran into the same issue. Our Wordpress installation is using the non-pretty permalinks, and we can't change that without breaking our RSS feed.

Anyway... since I knew what was going on here, and I'd like to continue learning and trying GatsbyJS I took a stab at fixing this. I changed the code to allow you to configure using the Non-Pretty Permalinks instead, but I honestly don't now how to build and test node_modules...

**Comment by shinebayar-g** [comment] 2019-07-23 12:58
Any plan to support `?rest_route`URL? as others said its more reliable endpoint if one doesn't use pretty urls

**Comment by cjhaviland** [comment] 2019-07-23 16:45
@shinebayar-g I guess I should take another serious look at the changes I made. As far as I could tell it doesn't _seem_ difficult based on how I did it. I'll see if I can actually build the files and test though. Then maybe we can get someone to re-open this ticket and I can do a pull request.

**Comment by fwielstra** [comment] 2019-09-30 13:40
Can this issue be looked into again? We're running Wordpress as purely a rest api, in that use case adding pretty URLs doesn't make a lot of sense. I can only find two instances of wp-json in https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/src/fetch.js but I'm not sure if there's any subtleties in there I'm missing.

**Comment by magicink** [comment] 2020-02-16 00:55
@wardpeet The assumption that `wp-json` is the WordPress default might be incorrect. As other have noted above, using the parameter `rest_route` is the actual WordPress default as it is available with or without pretty permalinks (`wp-json` is only accessible with pretty permalinks). I have a fork branch which would allow `wp-json` to continue to be used as the default value, but it its used, it uses the `rest_route` parameter instead.

https://github.com/magicink/gatsby/blob/627a6cbd1bade30435b59913e405b9023c078abf/packages/gatsby-source-wordpress/src/fetch.js#L277-L290

The other issue is that `getPages` always prepends `?`, which is the real reason you can just slap `?rest_route=` as the value for `restApiRoutePrefix`.

https://github.com/magicink/gatsby/blob/627a6cbd1bade30435b59913e405b9023c078abf/packages/gatsby-source-wordpress/src/fetch.js#L402-L405

This "works" but I think a new option called `useRestRouteParameter` at the config level is more elegant, anyway I'm open to your thoughts on the matter.

**Comment by robations** [comment] 2020-06-05 13:39
It seems to me like `?rest_route=` would be a better default (ignoring potential BC issues). Perhaps an update could detect whether `?` is in the `restApiRoutePrefix` and behave accordingly?

**Comment by robinmetral** [comment] 2020-06-05 15:04
I'll reopen this issue because it's obviously still affecting people.

@magicink I agree that a plugin option like `useRestRouteParameter` would be cleaner and ensures that there would be no regressions. If `?rest_route` is more common than `wp-json`, the option could possibly be `true` by default and set to `false` for users using pretty permalinks.

On the other hand, adding an option exposes this setting to plugin users, and I'm not sure that it should be (users shouldn't have to care about pretty permalinks or not, especially when using WP as a headless CMS).

I think a PR could actually be open if anyone feels like it, the implementation details will be easier to discuss over there.

**Comment by TylerBarnes** [comment] 2020-06-18 15:14
Hey everyone, thanks for your comments, thoughts and debugging on this.
We will soon be sunsetting our usage of the WP REST API in favour of using WPGraphQL in v4. We're currently working on an alpha (moving to beta within a couple weeks) of that next major version. I'd highly recommend upgrading as this will no longer be a problem in v4 (https://github.com/gatsbyjs/gatsby-source-wordpress-experimental). 
You can see some reasons on why it's a good idea to upgrade [here](https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/why-use-this-plugin.md#why-use-this-plugin-instead-of-x-source-plugin) and some notes on how to migrate [here](https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/blob/master/docs/migrating-from-other-wp-source-plugins.md#migrating-from-gatsby-source-wordpressv3).

For this reason, I don't believe it's worth fixing this issue as v3 will soon be deprecated. However, if anyone would like to contribute a PR we can get that merged before v4.

Thanks!

**Comment by anicioalexandre** [comment] 2021-02-08 14:22
Hey @TylerBarnes i'am trying to query custom wordpress admin menus and I found out that with the older version of `gatsby-source-wordpress` (before the experimental version) we could do something this inside the plugin option: `includedRoutes: [ ...,  "**/menus"]` to access those menus inside GraphQL.
Do you know if we can still fetch those menus on `gatsby-source-wordpress-experimental`/`v4`, i couldn't found a includeRoutes option on this new plugin version.

**Comment by TylerBarnes** [comment] 2021-03-18 21:56
@anicioalexandre that feature isn't currently implemented - [this PR](https://github.com/gatsbyjs/gatsby-source-wordpress-experimental/pull/129) addressed it but it didn't get merged. If you want to make that same PR on the Gatsby repo instead I'm happy to review it.

Closing this issue as we're not actively developing gatsby-source-wordpress v3 anymore.

**Closed by TylerBarnes** 2021-03-18 21:56 UTC
Labels: help wanted, topic: WordPress, type: bug
