### ISSUE TITLE
Contentful and Gatsby update broken?  gatsby: ^2.10.2 => 2.18.21 / gatsby-source-contentful: ^2.1.2 => 2.1.76

### ISSUE THREAD

**Issue by imshuffling** [gatsbyjs/gatsby#20591] opened 2020-01-14 10:50 UTC
## Description

I had a working environment (see screenshots below) I Just ran `npm update` and the link between Gatsby and contentful has broken.

Running `gatsby develop` throws and error - 'Cannot query field "allContentfulPage" on type "Query". Did you mean "allSitePage"?',

```
const path = require(`path`)

exports.createPages = ({ graphql, actions }) => {
  const { createPage } = actions

  // Page
  const loadPage = new Promise((resolve, reject) => {
    graphql(`
      {
        allContentfulPage {
          edges {
            node {
              slug
            }
          }
        }
      }
    `).then(result => {
      if (result.errors) {
        throw result.errors
      }
      result.data.allContentfulPage.edges.map(({ node }) => {
        createPage({
          path: `/${node.slug}`,
          component: path.resolve(`./src/templates/page.js`),
          context: {
            slug: node.slug,
          },
        })
      })
      resolve()
    })
  })
  return Promise.all([loadPage])
}
```

### Environment

Working environment
![Screenshot 2020-01-14 at 10 47 17](https://user-images.githubusercontent.com/739061/72337909-4acdb180-36bb-11ea-95aa-7523adf006a9.png)

Updated with npm - Broken
![Screenshot 2020-01-14 at 10 44 46](https://user-images.githubusercontent.com/739061/72337736-f32f4600-36ba-11ea-8abe-28aa1a515b0d.png)

Rolling back to previous package.json works fine.

Have i missed something in the latest docs? it's been a few months.

**Comment by pieh** [comment] 2020-01-14 15:02
Are there any errors in terminal  before the `Cannot query field "allContentfulPage"` error?

**Comment by imshuffling** [comment] 2020-01-14 16:00
When running `gatsby develop`

```
gatsby develop
success open and validate gatsby-configs - 0.085s
success load plugins - 1.586s
success onPreInit - 0.004s
success initialize cache - 0.013s
success copy gatsby files - 0.351s
success onPreBootstrap - 0.028s
success createSchemaCustomization - 0.086s
Starting to fetch data from Contentful
Fetching default locale
default locale is : en-US
contentTypes fetched 32

 ERROR #11321  PLUGIN

"gatsby-source-contentful" threw an error while running the sourceNodes lifecycle:

Maximum call stack size exceeded



  RangeError: Maximum call stack size exceeded
  
  - Function.assign
  
  - normalize.js:74 _.mapValues
    [brand.mirum.london]/[gatsby-source-contentful]/normalize.js:74:18
  
  - lodash.js:13401 
    [brand.mirum.london]/[lodash]/lodash.js:13401:38
  
  - lodash.js:4905 
    [brand.mirum.london]/[lodash]/lodash.js:4905:15
  
  - lodash.js:2990 baseForOwn
    [brand.mirum.london]/[lodash]/lodash.js:2990:24
  
  - lodash.js:13400 Function.mapValues
    [brand.mirum.london]/[lodash]/lodash.js:13400:7
  
  - normalize.js:72 fixIds
    [brand.mirum.london]/[gatsby-source-contentful]/normalize.js:72:28
  
  - normalize.js:85 _.mapValues
    [brand.mirum.london]/[gatsby-source-contentful]/normalize.js:85:12
  
  - lodash.js:13401 
    [brand.mirum.london]/[lodash]/lodash.js:13401:38
  
  - lodash.js:4905 
    [brand.mirum.london]/[lodash]/lodash.js:4905:15
  
  - lodash.js:2990 baseForOwn
    [brand.mirum.london]/[lodash]/lodash.js:2990:24
  
  - lodash.js:13400 Function.mapValues
    [brand.mirum.london]/[lodash]/lodash.js:13400:7
  
  - normalize.js:72 fixIds
    [brand.mirum.london]/[gatsby-source-contentful]/normalize.js:72:28
  
  - normalize.js:85 _.mapValues
    [brand.mirum.london]/[gatsby-source-contentful]/normalize.js:85:12
  
  - lodash.js:13401 
    [brand.mirum.london]/[lodash]/lodash.js:13401:38
  
  - lodash.js:4905 
    [brand.mirum.london]/[lodash]/lodash.js:4905:15
  

warn The gatsby-source-contentful plugin has generated no Gatsby nodes. Do you need it?
success source and transform nodes - 1.963s
success building schema - 0.680s

 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "allContentfulPage" on type "Query".

If you don't expect "allContentfulPage" to exist on the type "Query" it is most likely a typo.
However, if you expect "allContentfulPage" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js, please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "allContentfulPage" and right now it is not used anywhere. Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add a least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define the schema for "Query":
https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions

File: gatsby-node.js:19:20

⠋ createPages

 ERROR 

UNHANDLED REJECTION Cannot read property 'allContentfulPage' of undefined



  TypeError: Cannot read property 'allContentfulPage' of undefined
  
  - gatsby-node.js:31 graphql.then.result
    /private/var/www/brand.mirum.london/gatsby-node.js:31:19
  
⠋ createPages
```

**Comment by pieh** [comment] 2020-01-14 16:23
Ok, this seems like duplicate of https://github.com/gatsbyjs/gatsby/issues/20279

**Comment by pieh** [comment] 2020-01-14 23:07
I'll close this issue as duplicate, please track https://github.com/gatsbyjs/gatsby/issues/20279 / https://github.com/gatsbyjs/gatsby/pull/20313 for progress on this

**Closed by pieh** 2020-01-14 23:07 UTC
