### ISSUE TITLE
New data in createPage does not update between builds

### ISSUE THREAD

**Issue by grebbanniclas** [gatsbyjs/gatsby#29086] opened 2021-01-19 11:13 UTC
## Description

The problem is that the page context is not updating when I fetch data from my API. So if I do a build, change the data in my API, and then do another build, the the pages aren't updated.

I'm using Gatsby 2.30.3 (I've had this issue on earlier versions as well). When I'm fetching data from an API in createPages the context for the pages does not update, and when using develop the __graphQL endpoint is updated but not the pages. I have tried to boil this down to a very simple use case to make sure that other plugins etc. aren't the cause, and I have gotten down to a really minimal example where the problem still persists.

### Steps to reproduce

To reproduce the error all I have to do is to run:

1. gatsby clean
2. gatsby develop - (here the data in /__graphQL and the page is the same)
3. gatsby develop - (the data in /__graphQL data is updated, but the page shows the same data as in the previous run)

https://github.com/grebbanniclas/gatsby-build-issue/commit/48322c1cede4b3dd836c88aeed188c562d2e6b2b

#### First run of gatsby develop - same data
![image](https://user-images.githubusercontent.com/38907065/105026866-57fc4980-5a4f-11eb-9dec-310b6e78b7b1.png)

#### Second run of gatsby develop - different data
![image](https://user-images.githubusercontent.com/38907065/105026926-69455600-5a4f-11eb-8ce4-59cd1252de42.png)

### Expected result

The data shown on the page should update between builds when the data I put into createPage changes.

### Actual result

It does not update.

### Environment

```
  System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 87.0.4280.141
    Firefox: 84.0.1
    Safari: 14.0.2
  npmPackages:
    gatsby: ^2.26.1 => 2.30.3
    gatsby-image: ^2.5.0 => 2.9.0
    gatsby-plugin-manifest: ^2.6.1 => 2.10.0
    gatsby-plugin-offline: ^3.4.0 => 3.8.0
    gatsby-plugin-react-helmet: ^3.4.0 => 3.8.0
    gatsby-plugin-sharp: ^2.8.0 => 2.12.2
    gatsby-source-filesystem: ^2.5.0 => 2.9.1
    gatsby-transformer-sharp: ^2.6.0 => 2.10.1
  npmGlobalPackages:
    gatsby-cli: 2.12.71
```

**Comment by vladar** [comment] 2021-01-19 18:35
Hey @grebbanniclas! Thanks for opening this.

It is a known issue. We have a PR in progress to address this which you can track here: https://github.com/gatsbyjs/gatsby/pull/28590

In the meantime, I am closing this as a duplicate of #26520. Feel free to comment and mention me if you think this issue is different and want to re-open it.

**Closed by vladar** 2021-01-19 18:35 UTC
Labels: status: triage needed, type: bug
