### ISSUE TITLE
plugin-styled-components: Rendering incorrectly in production (with SSR)

### ISSUE THREAD

**Issue by jabczyk** [gatsbyjs/gatsby#21997] opened 2020-03-05 21:42 UTC
## Description
With SSR enabled, additional elements rendered client-side have incorrect styles.
Styles are generated correctly if the changes occur after the component is mounted.

Backstory: I use a Redux store that is preloaded from localStorage. Some components are conditionally rendered client-side based on the state.

### Steps to reproduce
Demo: https://codesandbox.io/s/gatsbyjs-issue-3q0wo
1. Start the app in production (`gatsby build && gatsby serve`)
2. CTRL+F5 to force Server-Side Rendering

### Expected result

New components should be rendered with correct class names and necessary CSS should be generated.

### Actual result

New components have class names (and styles) of existing elements.

### Environment
  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.18.1 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    gatsby: ^2.19.7 => 2.19.7
    gatsby-image: ^2.2.39 => 2.2.39
    gatsby-plugin-manifest: ^2.2.39 => 2.2.39
    gatsby-plugin-offline: ^3.0.32 => 3.0.32
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.21
    gatsby-plugin-sharp: ^2.4.3 => 2.4.3
    gatsby-plugin-styled-components: 3.1.19 => 3.1.19
    gatsby-source-filesystem: ^2.1.46 => 2.1.46
    gatsby-transformer-sharp: ^2.3.13 => 2.3.13

**Comment by vladar** [comment] 2020-03-06 07:52
Thank you for opening this, @jabczyk 

I think the issue is that you are rendering different element trees on the server and on the client (using `isSSR()` check). This is not supported by React hydration process. Here is a quote from [react docs](https://reactjs.org/docs/react-dom.html#hydrate):

```
React expects that the rendered content is identical between the server and the client.
It can patch up differences in text content, but you should treat mismatches as 
bugs and fix them. 
```

The whole section explains what's going on very well. Also, check out [this excellent article](https://joshwcomeau.com/react/the-perils-of-rehydration) on the subject (with suggested workarounds)

We could do better in Gatsby and emit warnings for cases like this but such situations are quite hard to detect. Anyways we do have an issue #17914 where you can track the progress on this.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. And thank you for using Gatsby! 💜

**Closed by vladar** 2020-03-06 07:52 UTC
Labels: type: bug

**Comment by jabczyk** [comment] 2020-03-06 15:28
In case it helps someone, here's my workaround for Redux's useSelector hook:
```ts
export const useSelector: TypedUseSelectorHook<RootState> = selector => {
  const [mounted, setMounted] = useState(false)
  React.useEffect(() => setMounted(true), [])

  const selected = useReduxSelector(selector)

  return mounted ? selected : selector(defaultState)
}
```
