### ISSUE TITLE
gatsby-inlined-css not working with netlify

### ISSUE THREAD

**Issue by sepehr500** [gatsbyjs/gatsby#4230] opened 2018-02-25 02:24 UTC
When I run `gatsby develop` or `gatsby build` locally, I can see the style tag with `id="gatsby-inlined-css"` and my styles are in the style tag, but when netlify builds by website, this tag is empty, and I get no styling on my site as a result. This was not an issue before, and only started a couple days ago even though I made no updates to any of my packages. Upgrading my packages to the latest version did not fix the problem. This leads me to believe it is a problem on the Netlify side. I had to remove the Netlify plugin because of #4226. Somebody in #1929 appears to have the same problem as well.

gatsby-config.js

```
module.exports = {
  siteMetadata: {
    title: 'adfsdfa',
  },
  plugins: ['gatsby-plugin-offline', 'gatsby-plugin-react-helmet', 'gatsby-plugin-sass',
    {
      resolve: 'gatsby-plugin-favicon',
      options: {
        logo: './src/layouts/I66.png',
        injectHTML: true,
        icons: {
          android: true,
          appleIcon: true,
          appleStartup: true,
          coast: false,
          favicons: true,
          firefox: true,
          twitter: false,
          yandex: false,
          windows: false,
        },
      },
    },
    {
      resolve: 'gatsby-plugin-manifest',
      options: {
        name: 'afdadfs',
        description: 'asdfdfsa',
        short_name: 'afdsdafs',
        start_url: '/',
        background_color: '#308446',
        theme_color: 'green',
        display: 'minimal-ui',
        icons: [
          {
            // Everything in /static will be copied to an equivalent
            // directory in /public during development and build, so
            // assuming your favicons are in /static/favicons,
            // you can reference them here
            src: '/favicons/android-chrome-192x192.png',
            sizes: '192x192',
            type: 'image/png',
          },
          {
            src: '/favicons/android-chrome-512x512.png',
            sizes: '512x512',
            type: 'image/png',
          },
        ],
      },
    },
    {
      resolve: 'gatsby-plugin-google-analytics',
      options: {
        trackingId: '324fads',
      },
    },
  ],
};
```

**Comment by erquhart** [comment] 2018-02-26 00:04
Can you share your netlify url so we can troubleshoot a bit?

**Comment by sepehr500** [comment] 2018-02-26 01:01
https://shoulditakei66.today/

**Comment by sepehr500** [comment] 2018-02-26 21:54
Had to switch to working build. But this is the PR that broke the css. https://github.com/sepehr500/i66tolls/commit/a8da0bb121ea7eb932726579bcd423d4b39b6e23

**Comment by sepehr500** [comment] 2018-02-27 02:34
I had to delete my Netlify site and redeploy to fix the problem.

**Comment by erquhart** [comment] 2018-02-27 16:16
Hmm did you ever try manually redeploying a failed build and selecting "clear build cache"?

**Comment by sepehr500** [comment] 2018-02-27 16:18
Where is the clear build cache button?

**Comment by erquhart** [comment] 2018-02-27 16:28
![image](https://user-images.githubusercontent.com/2112202/36740727-4b0c87f6-1bb1-11e8-9bd2-27a56e00ee50.png)

**Comment by erquhart** [comment] 2018-02-27 16:29
![kapture 2018-02-27 at 11 28 41](https://user-images.githubusercontent.com/2112202/36740772-70e3fcd4-1bb1-11e8-9a62-a8247d07f676.gif)

**Comment by sepehr500** [comment] 2018-02-27 16:37
Unfortunately the build does not fail with this issue.  I guess I need to force the build to fail somehow?

**Comment by erquhart** [comment] 2018-02-27 19:19
If you can't reproduce, there's a good chance it was outdated dependencies.

**Comment by JacobDFrank** [comment] 2018-03-28 17:09
Having a similar issue with my deploy using netlify. I redeployed, cleared the cache and still some of my assets as well as the inline scss won't load in. You can view my deploy log as well: https://app.netlify.com/sites/youthful-hamilton-7ed749/deploys/5abbc90d295b551d254a7403
And here's my netlify url https://youthful-hamilton-7ed749.netlify.com/

**Comment by erquhart** [comment] 2018-03-28 17:57
Cloned your repo and built locally, same issue, so this isn't Netlify or host specific. Going to close this as it's becoming a catch all, but feel free to open a separate issue.

**Closed by erquhart** 2018-03-28 17:57 UTC

**Comment by ksurobotics** [comment] 2018-05-07 03:29
I am having the same issue where there is inlined css when I build locally, but not when I build on Netlify. I cleared build cache and updated to latest packages and it still didn't work. Did you all ever come to a solution for this issue?

**Comment by themostcolm** [comment] 2018-05-07 03:41
After looking at [#5100](https://github.com/gatsbyjs/gatsby/issues/5100) I found that I had a capitalization issue in my src files that was unnoticed by windows, but that prevented the inline styles from being generated on the linux-based Netlify environment. Check capitalization!

**Comment by wearegoose** [comment] 2018-05-23 06:00
@themostcolm could you give an example of the capitalization issue? I'm having the exact same issue. All works well locally, but deploy to Netlify and the styles don't get loaded.

Cheers

**Comment by themostcolm** [comment] 2018-05-30 04:02
Sure! I use stylus, so in my import statement I had :

**Comment by themostcolm** [comment] 2018-06-30 15:04
@drake-smith  Sure! I use stylus, so in my import statement I had `@import '../layouts/Header/header.styl'`  when my actual file layout was src/layouts/Header/Header.styl. It worked perfectly in development, but did not work on Netlify. Also make sure if you are using git that you have the correct capitalization in your git repository. Sometimes if you change the capitalization of the file, git doesn’t recognize that at all. You can do this with git mv <oldFileName> <newFileName>
