### ISSUE TITLE
MS Edge/IE11 gatsby-link navigation fails (in built site only)

### ISSUE THREAD

**Issue by pnloyd** [gatsbyjs/gatsby#1704] opened 2017-08-03 08:49 UTC
I was having this issue with my site Iv'e built with gatsby where links are _very_ buggy in Edge. I've been trying to figure out whether it's some issue with my local config or a bug in gatsby. (I'm confused because the gatsby-default-starter demo doesn't exhibit the issue). 

I completely wiped my node modules, ungraded to latest node LTS, then installed gatsby-cli and did a gatsby new test, and the resulting site is still giving me the errors.

> HTTP404: NOT FOUND
> GET - http://staging.patrickloyd.me/undefined

Iv'e tested in all the other modern browsers and haven't seen any issues like this.
I have a copy producing the errors in Edge at [http://staging.patrickloyd.me](http://staging.patrickloyd.me) 

I'm fairly new to working in a node environment so I'm not sure how to debug the issue.

**Comment by sebastienfi** [comment] 2017-08-03 11:37
Confirmed.

In Edge, the navigation doesn't happen where in Chrome it succeeds.
Error is raised from `gatsby\packages\gatsby\src\cache-dir\loader.js` line 289.

![image](https://user-images.githubusercontent.com/5808108/28919997-31590852-7850-11e7-8c50-7471b4e2ca0a.png)

**Comment by pnloyd** [comment] 2017-08-03 13:21
@KyleAMathews Do you happen to know if the gatsby-default-starter demo site is using newish versions of the relevant packages? I'm curious since since it is not giving the errors, but my deployment of the starter is.

**Comment by KyleAMathews** [comment] 2017-08-05 02:31
Seems like there's a bug somewhere in here that's triggered in MS Edge https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/cache-dir/loader.js

If someone wants to be a Gatsby hero, we need to add testing for our runtime which gets run in every browser out there on something like https://saucelabs.com/

**Comment by pnloyd** [comment] 2017-08-07 22:44
Appears as though IE11 is effected as well.

**Comment by jazozaya** [comment] 2017-08-10 14:44
Has anyone been able to crack this one? Happening to me too on EDGE and IE

The same links are broken in both browsers. 

Clicking them produces an error and page does not load.  Oddly enough, entering the URL directly does work and loads the page fine.

**Comment by sebastienfi** [comment] 2017-08-10 15:44
@pnloyd Can you zoo and host your site's source that reproduce the error ?

**Comment by pnloyd** [comment] 2017-08-10 21:32
@sebastienfi I will if there's a specific rational to do so, but I feel like the source produced by `gatsby new` should be sufficient.

**Comment by sebastienfi** [comment] 2017-08-10 22:37
@pnloyd do you see a websocket error previously to this 404 error in IE ?
Something like `WebSocket Error: Network Error 12030`

**Comment by KyleAMathews** [comment] 2017-08-10 22:39
@sebastienfi this is only showing up in built sites not in development

**Comment by pnloyd** [comment] 2017-08-10 22:43
@sebastienfi IE11 isn't throwing any errors like that.
![image](https://user-images.githubusercontent.com/22247793/29195296-977ce2e2-7de2-11e7-969c-434e46c495dd.png)

**Comment by sebastienfi** [comment] 2017-08-10 22:43
@KyleAMathews Yes! I do have the same error in build, preceeded by the socket error.

![image](https://user-images.githubusercontent.com/5808108/29195301-0ec1329a-7e2e-11e7-9069-18e3a8d5a792.png)
![image](https://user-images.githubusercontent.com/5808108/29195306-17dd8d9c-7e2e-11e7-9411-57b986b8e3a7.png)

**Comment by bskimball** [comment] 2017-08-11 00:26
Errors on built site are 404 not found
```javascript
GET - http://localhost/undefined

bundle loading error true
index.js (8,1)

Loading the component for /blog/ failed
loader.js (332,13)
```

**Comment by bskimball** [comment] 2017-08-11 00:38
Unfortunately the callstack is not very informative. If the page is already cached it will work fine but if the loader has to fetch the resource, that's when the issue happens.

it might be in the asyncRequires

**Comment by bskimball** [comment] 2017-08-11 21:15
Narrowing it down to an undefined chunk in a function
```javascript
    // Download the resource
    resourceFunction(function (err, executeChunk) {
      resourceStrCache[resourceName] = executeChunk;
      cb(err, executeChunk);
    });
```
executeChunk is returning as undefined only in Edge or IE11

**Comment by KyleAMathews** [comment] 2017-08-12 02:05
Odds are the problem is in here https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby/src/loaders/gatsby-module-loader

**Comment by bskimball** [comment] 2017-08-12 15:17
Yeah, I'm just trying to wrap my head around how it's loaded. I'm assuming the result returned by the module loader is in a format that Edge can't read.

**Comment by bskimball** [comment] 2017-08-12 16:37
I submitted a PR to fix this issue IE and Edge did not like the carriage returns

PR [#1782](https://github.com/gatsbyjs/gatsby/pull/1782)

**Comment by KyleAMathews** [comment] 2017-08-24 17:19
Curious if https://github.com/gatsbyjs/gatsby/pull/1901 helped any here? Would love if someone could test

**Comment by pnloyd** [comment] 2017-08-24 17:20
I'll test it.

**Comment by danielfarrell** [comment] 2017-08-31 18:51
Seeing this still(on a client site we just launched :-/ )...  I'm digging in.

**Comment by bskimball** [comment] 2017-08-31 19:25
@danielfarrell at one point i had narrowed it down to require.ensure statement in the gatsby-module-loader is where it was failing in IE. I traced that back to an issue with webpack that was resolved in version 2.3.

**Comment by pnloyd** [comment] 2017-08-31 19:26
@bskimball Does that imply the fix for this bug is upgrading webpack?

Patrick Loyd | Full Stack Developer | 425-220-0101
website: http://patrickloyd.me

**Comment by bskimball** [comment] 2017-08-31 19:28
@pnloyd that's what it looks like to me. I worked on it in PR #1782 and #1783

**Comment by jquense** [comment] 2017-08-31 19:33
what is the webpack bug that was fixed? Maybe we can monkey patch it. If someone can track down the commit in webpack 🙇

**Comment by bskimball** [comment] 2017-08-31 19:34
@jquense it looks to me like this issue https://github.com/webpack/webpack/issues/2506

**Comment by jquense** [comment] 2017-08-31 19:40
hmm that issue looks like it might be webpack2 only. The v1 code doesn't seem to suffer from the issue noted in that issue and PR

**Comment by bskimball** [comment] 2017-08-31 19:44
@jquense I must have missed that. I am pretty sure that failure happens at the require.ensure statement in gatsby-module-loader. I didn't figure out why it was failing.

**Comment by jquense** [comment] 2017-08-31 19:46
Can anyone throw up a repo with as little code as possible demonstrating the issue? It'll be easier to track down if we have a reproduction

**Comment by bskimball** [comment] 2017-08-31 19:55
The official gatsby blog fails in IE/Edge.

**Comment by pnloyd** [comment] 2017-08-31 20:47
Ya all you need to do to get a copy that reproduces the error is do `gatsby
new` with latest gatsby.

Patrick Loyd | Full Stack Developer | 425-220-0101
website: http://patrickloyd.me

**Comment by danielfarrell** [comment] 2017-09-01 16:01
Digging deep over here, it looks like the chunkId's are ending up slightly different.  11275408829374971000 vs 11275408829374972000 and that is why it's not finding the correct filename to load in the script. That makes me think it's a webpack issue, but I'm still digging.

**Comment by danielfarrell** [comment] 2017-09-01 16:30
Wow, this is a bad bug, here is the root of the issue...
![screenshot 2017-09-01 12 29 28](https://user-images.githubusercontent.com/13850/29978925-53c9f4a0-8f11-11e7-92a2-fa3f9383f353.png)

**Comment by KyleAMathews** [comment] 2017-09-01 16:32
What?? 😨

**Comment by sebastienfi** [comment] 2017-09-01 17:21
Arf...
On the left side, Chrome console output, right side, Edge's.
![image](https://user-images.githubusercontent.com/5808108/29980604-b6b55f30-8f4a-11e7-96d2-bfa8867ac61d.png)

**Comment by danielfarrell** [comment] 2017-09-01 17:22
Yep, something is casting the chunk id to a number, and IE/Edge has a precision bug, and that is why it's not finding the right chunk.  Trying to find out where that is getting cast still.

**Comment by sebastienfi** [comment] 2017-09-01 17:32
Congrats @danielfarrell for having found this !
Created a bug in Charka's Core issue tracker.
How should we proceed to work around this meanwhile it's fixed in Edge?

**Comment by danielfarrell** [comment] 2017-09-01 17:38
Looks like if I adjust the get-hash-fn file to end up with a smaller number it fixes the issue, and that seems like a smart path.

**Closed** 2017-09-01 18:45 UTC
