### ISSUE TITLE
Panicking because nodes appear to be being changed every time we run queries. This would cause the site to recompile infinitely.

### ISSUE THREAD

**Issue by youngjuning** [gatsbyjs/gatsby#28172] opened 2020-11-19 06:13 UTC
Panicking because nodes appear to be being changed every time we run queries. This would cause the site to recompile infinitely.
Check custom resolvers to see if they are unconditionally creating or mutating nodes on every query.
This may happen if they create nodes with a field that is different every time, such as a timestamp or unique id.

**Comment by LekoArts** [comment] 2020-11-19 08:50
Hi!

Please follow the issue template and [provide a minimal reproduction][reproduction] to your problem. Sadly we don't understand what you're trying to say. Thanks!

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2020-11-27 08:47
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-11-27 08:47 UTC
Labels: status: needs reproduction, type: bug
