### ISSUE TITLE
Setting host for Gatsby not working

### ISSUE THREAD

**Issue by arkadiusz-czerwinski** [gatsbyjs/gatsby#31886] opened 2021-06-12 21:08 UTC
## Description

No matter what I am trying to do, the host on which the app starts is always set to localhost

### Steps to reproduce

gatsby develop -H 0.0.0.0 or gatsby develop --host=0.0.0.0

### Expected result

the app should start at the correct interface

### Actual result

 http://localhost:8000/

### Environment

![image](https://user-images.githubusercontent.com/42278982/121789058-8ce87480-cb87-11eb-8dd2-23ed4d6c78ce.png)

**Comment by HIMANSHUYADAV100** [comment] 2021-06-13 06:56
Assign me this issue, I will solve it

**Comment by LekoArts** [comment] 2021-06-14 06:07
Hi, thanks for the issue!

To make the process of resolving problems quicker for both sides we need you to fill out the issue template and give us a minimal reproduction:

```md
<!--
  Please fill out each section below, otherwise, your issue will be closed. This info allows Gatsby maintainers to diagnose (and fix!) your issue as quickly as possible.

  Useful Links:
  - Documentation: https://www.gatsbyjs.com/docs/
  - How to File an Issue: https://www.gatsbyjs.com/contributing/how-to-file-an-issue/

  Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
-->

## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here. Also name any `flags` you use inside `gatsby-config.js`.
```

**Comment by arkadiusz-czerwinski** [comment] 2021-06-15 12:15
Adding the --open flag seems to have solved the issue, even though the host's os was a Debian-based one.

**Comment by HIMANSHUYADAV100** [comment] 2021-06-15 12:18
Great

**Comment by MitchMigala** [comment] 2021-06-22 16:34
Is it possible to access the Gatsby develop localhost or Gatsby develop -H 127.0.0.1 -p 8000 remotely? Like running develop on a server is Texas and access it in browser in MN?

**Comment by jamo** [comment] 2021-06-23 08:34
`./node_modules/.bin/gatsby develop --host 0.0.0.0` works with gatsby 3.8.0 at least. I can see it listening on `*:8000` and I can access the develop site over a VPN IP (not localhost).

**Comment by jamo** [comment] 2021-06-23 08:35
if you set ` --host 127.0.0.1` then it binds to localhost and is only accessible on localhost.

**Comment by MitchMigala** [comment] 2021-06-23 13:00
Is this still the case if I run gatsby build and then gatsby serve?

**Comment by jamo** [comment] 2021-06-29 05:54
yes:
```
$ ./node_modules/.bin/gatsby build
... lots of logs
$./node_modules/.bin/gatsby serve --host 0.0.0.0
⠀
You can now view gatsby-site-1 in the browser.
⠀
  Local:            http://localhost:9000/
  On Your Network:  http://192.168.1.2:9000/

```

and also validated with lsof and I can access it over vpn.

**Comment by LekoArts** [comment] 2021-07-06 09:55
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-07-06 09:55 UTC
Labels: status: needs reproduction, type: bug
