### ISSUE TITLE
Intermittent base64 Image Error Build Failures — gatsby-source-datocms

### ISSUE THREAD

**Issue by keziahrg** [gatsbyjs/gatsby#29014] opened 2021-01-13 20:47 UTC
## Description

This is an issue across all of our projects using gatsby/datocms. 

Builds fail intermittently and throw the following error:

```2:58:35 PM: info bootstrap finished - 28.943s
2:58:35 PM: success run static queries - 0.337s - 13/13 38.53/s
2:58:56 PM: warning Query takes too long:
2:58:56 PM: File path: /opt/build/repo/src/templates/searchTerm.js
2:58:56 PM: URL path: /recipes/pasta
2:58:56 PM: Context: {
2:58:56 PM:     "id": "DatoCmsSearchTerm-9772027-en",
2:58:56 PM:     "slug": "pasta",
2:58:56 PM:     "title": "Pasta",
2:58:56 PM:     "namePlural": "Pasta",
2:58:56 PM:     "hasParent": true,
2:58:56 PM:     "parent": {
2:58:56 PM:         "title": "Recipes",
2:58:56 PM:         "path": "/recipes"
2:58:56 PM:     }
2:58:56 PM: }
2:59:13 PM: error There was an error in your GraphQL query:
2:59:13 PM: Error: connect ETIMEDOUT 172.67.208.228:443
2:59:13 PM:    93 |       }
2:59:13 PM:    94 |     }
2:59:13 PM:    95 |   }
2:59:13 PM:    96 | }
2:59:13 PM:    97 |
2:59:13 PM:    98 | fragment GatsbyDatoCmsSeoMetaTags on DatoCmsSeoMetaTags {
2:59:13 PM:    99 |   tags
2:59:13 PM:   100 | }
2:59:13 PM:   101 |
2:59:13 PM:   102 | fragment GatsbyDatoCmsFluid on DatoCmsFluid {
2:59:13 PM: > 103 |   base64
2:59:13 PM:       |   ^
2:59:13 PM:   104 |   aspectRatio
2:59:13 PM:   105 |   src
2:59:13 PM:   106 |   srcSet
2:59:13 PM:   107 |   sizes
2:59:13 PM:   108 | }
2:59:13 PM:   109 |
2:59:13 PM:   110 | fragment RecipeBadges on DatoCmsRecipe {
2:59:13 PM:   111 |   dietaryTypes {
2:59:13 PM:   112 |     name
2:59:13 PM:   113 |     badge {
2:59:13 PM: File path: /opt/build/repo/src/templates/searchTerm.js
2:59:13 PM: Url path: /recipes/pasta
2:59:13 PM: Plugin: none
2:59:13 PM: not finished run page queries - 38.405s
2:59:13 PM: not finished Generating image thumbnails - 2.959s
2:59:14 PM: error Command failed with exit code 1.
```
### Steps to reproduce

Run `gatsby build` using gatsby-source-datocms plugin on projects with a large number of media/images.

### Expected result

Build succeeds

### Actual result

Build intermittently fails

### Environment

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.7.0 - ~/.nvm/versions/node/v14.7.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v14.7.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.193
    Firefox: 82.0.3
    Safari: 14.0.1
  npmPackages:
    gatsby: ^2.24.8 => 2.24.65
    gatsby-image: ^2.4.4 => 2.4.19
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5
    gatsby-plugin-create-client-paths: ^2.3.10 => 2.3.11
    gatsby-plugin-firebase: ^0.2.0-beta.4 => 0.2.0-beta.4
    gatsby-plugin-google-tagmanager: ^2.3.11 => 2.3.12
    gatsby-plugin-manifest: ^2.4.6 => 2.4.31
    gatsby-plugin-preact: ^4.0.2 => 4.0.12
    gatsby-plugin-preconnect: ^1.1.54 => 1.1.54
    gatsby-plugin-preload-fonts: ^1.2.21 => 1.2.25
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.3
    gatsby-plugin-sass: ^2.3.1 => 2.3.13
    gatsby-plugin-sharp: ^2.6.6 => 2.6.36
    gatsby-plugin-sitemap: ^2.4.2 => 2.4.13
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.5 => 1.0.5
    gatsby-source-apiserver: ^2.1.7 => 2.1.7
    gatsby-source-custom-api: ^2.1.4 => 2.1.4
    gatsby-source-datocms: 2.5.x => 2.5.2
    gatsby-source-filesystem: ^2.3.3 => 2.3.30
    gatsby-theme-auth0: ^1.1.1 => 1.1.1
    gatsby-transformer-remark: ^2.8.23 => 2.8.35
    gatsby-transformer-sharp: ^2.5.2 => 2.5.15
    gatsby-transformer-yaml: ^2.4.10 => 2.4.12
    
Any ideas on how to prevent this from happening would be much appreciated!

**Comment by LekoArts** [comment] 2021-01-14 08:44
Hi!

Have you created an issue at https://github.com/datocms/gatsby-source-datocms already? At first glance the issues seems to be in connection issues with Dato, not so much a core Gatsby bug. Please create an issue there if you haven't and see what they say. Anyhow, to be able to further look into this we'll need [a minimal reproduction][reproduction] and we'll be able to take another look. Thanks!

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-01-25 09:54
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2021-01-25 09:54 UTC
Labels: status: needs more info, status: needs reproduction, type: bug
