### ISSUE TITLE
Slash added to URL before query params

### ISSUE THREAD

**Issue by vardy** [gatsbyjs/gatsby#30585] opened 2021-03-31 09:00 UTC
## Description

When trying to access pages with query params in the URL, Gatsby will apply a 'trailing' slash _before_ the param, causing an error. This occurs locally and in production when serving the site with `gatsby serve`. The page will render correctly at first, but then the URL updates and the page re-renders and errors.

Correct URL:    
`https://example.com/page?query=string`

What Gatsby changes it to:    
`https://example.com/page/?query=string`

I'm yet to find a fix to this issue.

### Steps to reproduce

Occurs in any Gatsby site I spin up.    
I upgraded to Gatsby 3 and the issue still occurs.

### Expected result

The page renders with query params and if a trailing slash is added, it's after the params.

### Actual result

The slash is added to the URL after the page but before the params.

### Environment

  System:
    OS: macOS Mojave 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 14.9.0 - /usr/local/bin/node
    npm: 6.14.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.24.50 => 2.24.50
    gatsby-image: ^2.4.19 => 2.4.19
    gatsby-plugin-layout: ^1.10.0 => 1.10.0
    gatsby-plugin-react-helmet: ^3.10.0 => 3.10.0
    gatsby-plugin-sass: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^2.6.36 => 2.6.36
    gatsby-plugin-use-query-params: ^1.0.1 => 1.0.1
    gatsby-remark-images: ^3.3.29 => 3.3.29
    gatsby-remark-relative-images: ^2.0.2 => 2.0.2
    gatsby-source-filesystem: ^2.3.28 => 2.3.28
    gatsby-transformer-sharp: ^2.5.15 => 2.5.15
  npmGlobalPackages:
    gatsby-cli: 2.12.91

**Comment by LekoArts** [comment] 2021-04-06 10:16
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-04-14 07:55
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed** 2021-04-14 07:56 UTC
Labels: status: needs reproduction, type: bug
