### ISSUE TITLE
Breaks using JSX inside another JSX with "gatsby-plugin-mdx" plugin

### ISSUE THREAD

**Issue by jonauz** [gatsbyjs/gatsby#24838] opened 2020-06-06 11:50 UTC
## Description

Working with `.mdx` files. Tried to included one JSX component within another JSX component, where child is being parsed as if it is MDX. It seems there are some issues with indentation within child MDX content.

```
"gatsby-plugin-mdx" threw an error while running the onCreateNode lifecycle:

unknown: Expected corresponding JSX closing tag for <Table> (68:2)

  66 | </TableCell>
  67 | `}</code></pre>
> 68 |   </TableRow>
     |   ^
  69 |
  70 |   <TableRow>
  71 |     <TableCell type="propName">title</TableCell>/Users/x/Workspace/project_x/src/documents/path_a/path_a/file_a.mdx: unknown: Expected corresponding JSX closing tag for <Table> (68:2)
```

### Example

```jsx
// example_file.mdx
---
meta...
---

# Some title

More MD text...

<JSXComponentA>
  <JSXComponentAChild>
    Some text
    <JSXComponentA>
      <JSXComponentAChild>
        Inner component child text
      </JSXComponentAChild>
// it all depends if there is empty row here
// if there is, then is it indented at same level as inner component child
// if not, then it throws error similar to written above
      <JSXComponentAChild>
        Inner component child text
      </JSXComponentAChild>
    </JSXComponentA>
    more text
  </JSXComponentAChild>
</JSXComponentA>
```

This seems some limitation on how MDX file is being parsed. Most likely possible to improve, but I don't know how to improve this to make it more bullet proof, so that client/end_user would not need to worry about putting space or indentation incorrectly and making everything not working.

**Comment by pvdz** [comment] 2020-06-16 09:59
@johno is this by design or a bug we could fix?

**Comment by johno** [comment] 2020-06-17 18:38
This is currently a limitation in the MDX v1 parser which will be addressed in v2. For now, you will have to remove the empty line to get it to parse correctly.

You can follow along with the gatsby-plugin-mdx v2 issue to see when this lands (https://github.com/gatsbyjs/gatsby/issues/25068) so going to close this for now. Thanks for opening the issue!

**Closed by johno** 2020-06-17 18:38 UTC
Labels: topic: MDX, type: bug

**Comment by zanami** [comment] 2020-09-17 04:33
More confusing stuff here
I'm trying to nest MD in JSX components but that indentation restrictions are not obvious to me.

```
## this works

<Container>
  <Box className="testBox1">
  <TabPanel>

  ## hello 1

  </TabPanel>
  </Box>
</Container>

## builds fine but md is not parsed, prints '## hello 2'

<Container>
  <Box className="testBox2">
  <TabPanel>

    ## hello 2

  </TabPanel>
  </Box>
</Container>

## this fails to build

<Container>
  <Box className="testBox3">
    <TabPanel>

    ## hello 3

    </TabPanel>
  </Box>
</Container>

## also fails to build

<Container>
    <Box className="testBox4">
    <TabPanel>

    ## hello 4

    </TabPanel>
    </Box>
</Container>

## this works

<Container>
    <Box className="testBox5">
  <TabPanel>

  ## hello 5

  </TabPanel>
    </Box>
</Container>
```
