### ISSUE TITLE
resize(rotate: xx) in gatsby-transformer-sharp is not work.

### ISSUE THREAD

**Issue by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [gatsbyjs/gatsby#5086] opened 2018-04-23 13:56 UTC
## Description
GraphQL function`resize(width: 125, height: 125, rotate: 180)` is not work.

### Steps to reproduce
Visit demo page https://image-processing.gatsbyjs.org/
Compare images in **resize** part with the original [images](https://github.com/gatsbyjs/gatsby/tree/master/examples/image-processing/src/images)

I also checked that problem on my local test code.

### Expected result
In demo page, images in **resize** part should be rotated.

### Actual result
In demo page, images in **resize** part is not rotated.

### Environment
Please check here https://github.com/gatsbyjs/gatsby/blob/master/examples/image-processing/package.json

**Comment by m-allanson** [comment] 2018-04-24 15:41
Huh, that's odd. Would love if you have time to investigate what's causing this.

**Comment by pieh** [comment] 2018-04-26 23:59
So i've did some digging and it seems this was broken for quite some time.

Here we do "empty" rotation to orient image using EXIF information - https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sharp/src/index.js#L75

Later we do actual rotation if `rotate` arg is defined - https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-sharp/src/index.js#L124-L127

Problem is - when we do empty rotation `sharp` will lock into exif information and any rotation with actual value will have no effect ( https://github.com/lovell/sharp/blob/99810c03116f9951faf8b40fe0f8a02c55ce8b02/src/pipeline.cc#L82-L90 ).

So what we could do is don't start with empty rotation, check if user want to rotate and if not fallback to empty rotation or take this upstream (`sharp` repo) first and check there if this is expected behaviour (or do both :) ).

**Comment by KyleAMathews** [comment] 2018-09-08 05:14
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Comment by cwgw** [comment] 2019-05-24 18:11
This is still broken.

I've created a PR following the suggestion from @pieh.

**Closed** 2019-05-28 13:18 UTC
Labels: help wanted, type: bug
