### ISSUE TITLE
After cleaning cache ""gatsby-node.js" threw an error while running the createPagesStatefully lifecycle"

### ISSUE THREAD

**Issue by ktw-studio** [gatsbyjs/gatsby#22963] opened 2020-04-09 13:56 UTC
## Description

Hey, 

Just today my gatsby installation stopped working (I've cleaned cache). I get the following error: 
`Enum type WPGraphQL_LanguageCodeEnum must define one or more values.`

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

My gatsby-node.js:

`
const createPages = require("./create/createPages")

exports.createPagesStatefully = async ({ graphql, actions, reporter }, options) => {
  await createPages({ actions, graphql, reporter }, options)
}
`

And createPages:
`
const pageTemplate = require.resolve("../src/templates/page.js")

const GET_PAGES = `
    query GET_PAGES($first:Int $after:String) {
        wpgraphql {
            pages(
                first: $first
                after: $after
                # This will make sure to only get the parent nodes and no children
                where: {
                    parent: null
                }
            ) {
                pageInfo {
                    hasNextPage
                    endCursor
                }
                nodes {                
                    id
                    title
                    pageId
                    uri
                    isFrontPage
                }
            }
        }
    }
`

const allPages = []
let pageNumber = 0
const itemsPerPage = 10

/**
 * This is the export which Gatbsy will use to process.
 *
 * @param { actions, graphql }
 * @returns {Promise<void>}
 */
module.exports = async ({ actions, graphql, reporter }, options) => {

  /**
   * This is the method from Gatsby that we're going
   * to use to create pages in our static site.
   */
  const { createPage } = actions
  /**
   * Fetch pages method. This accepts variables to alter
   * the query. The variable `first` controls how many items to
   * request per fetch and the `after` controls where to start in
   * the dataset.
   *
   * @param variables
   * @returns {Promise<*>}
   */
  const fetchPages = async (variables) =>
    /**
     * Fetch pages using the GET_PAGES query and the variables passed in.
     */
    await graphql(GET_PAGES, variables).then(({ data }) => {
      /**
       * Extract the data from the GraphQL query results
       */
      const {
        wpgraphql: {
          pages: {
            nodes,
            pageInfo: { hasNextPage, endCursor },
          },
        },
      } = data

      /**
       * Map over the pages for later creation
       */
      nodes
      && nodes.map((pages) => {
        allPages.push(pages)
      })

      /**
       * If there's another page, fetch more
       * so we can have all the data we need.
       */
      if (hasNextPage) {
        pageNumber++
        reporter.info(`fetch page ${pageNumber} of pages...`)
        return fetchPages({ first: itemsPerPage, after: endCursor })
      }

      /**
       * Once we're done, return all the pages
       * so we can create the necessary pages with
       * all the data on hand.
       */
      return allPages
    })

  /**
   * Kick off our `fetchPages` method which will get us all
   * the pages we need to create individual pages.
   */
  await fetchPages({ first: itemsPerPage, after: null }).then((wpPages) => {

    wpPages && wpPages.map((page) => {
      let pagePath = `${page.uri}`

      /**
       * If the page is the front page, the page path should not be the uri,
       * but the root path '/'.
       */
      if(page.isFrontPage) {
        pagePath = '/'
      }

      createPage({
        path: pagePath,
        component: pageTemplate,
        context: {
          id: String(page.pageId)
        },
      })

      reporter.info(`page created: ${pagePath}`)
    })

    reporter.info(`# -----> PAGES TOTAL: ${wpPages.length}`)
  })
}
`

2 hours ago everything worked properly, any idea what could have happend? 

### Expected result

Gatsby develop and build commands will work properly.

### Actual result

Nothing to add than description above, sorry.

### Environment
 System:
    OS: macOS 10.15.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.10.1 - /usr/local/bin/node
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 70.0.1
    Safari: 13.1
  npmPackages:
    gatsby: ^2.20.12 => 2.20.12
    gatsby-image: ^2.3.1 => 2.3.1
    gatsby-plugin-manifest: ^2.3.3 => 2.3.3
    gatsby-plugin-offline: ^3.1.2 => 3.1.2
    gatsby-plugin-react-helmet: ^3.2.1 => 3.2.1
    gatsby-plugin-sharp: ^2.5.3 => 2.5.3
    gatsby-source-graphql: ^2.1.25 => 2.3.2
    gatsby-transformer-sharp: ^2.4.3 => 2.4.3
  npmGlobalPackages:
    gatsby-cli: 2.11.5

**Comment by pieh** [comment] 2020-04-09 14:41
Do you get similar errors if you query your wordpress / wp-graphql instance outside of Gatsby? You can try this through https://github.com/wp-graphql/wp-graphiql (adding `graphiql` "ide" to your wordpress admin panel).

There are few possibilities I can see:
 - either wp-graphql create `enum` with no values in it
 - schema stitching (`gatsby-source-graphql`) might not handle this correctly.

Other question - you mentioned cleaning cache - does it mean just deleting `.cache` directory? Or did you update packages as well? (there might be regression that happened somewhere)

**Comment by ktw-studio** [comment] 2020-04-09 14:44
Using 3rd party query "ide" works properly, I can query and get proper results.
I've deleted .cache directory, node modules and package.lock file, I've also downgraded gatsby-source-graphqpl from 2.3.2 to 2.1.25 as this was suggested in other issue. 

For now, no improvements.

**Comment by jasonbahl** [comment] 2020-04-09 14:57
@ktw-studio the `LanguageCodeEnum` isn't from core WPGraphQL, but is from the WPGraphQL for PolyLang plugin. 

### Quick win: 

I believe you should be able to configure the PolyLang plugin with some languages and this error will go away?

### More Info:

From what I can tell, it looks like the enum doesn't have any values set if Polylang hasn't been configured with any languages. 

I've opened an issue on the WPGraphQL for Polylang repo here: https://github.com/valu-digital/wp-graphql-polylang/issues/20

I've also opened a PR (https://github.com/valu-digital/wp-graphql-polylang/pull/21) to address this and ensure there's a default value (the site's locale) in case no languages are set up yet. I believe the PR should address this, but @esamattis (creator of WPGraphQL for Polylang) should probably weigh in and make sure the PR makes sense.

**Comment by jasonbahl** [comment] 2020-04-09 15:23
@ktw-studio So, I setup WP PolyLang locally along with WPGraphQL for Polylang, and I've confirmed this is indeed the issue. 

If you setup some languages under the PolyLang Languages page (`/wp-admin/admin.php?page=mlang`) the error will go away. 

Here, we can see no languages setup in Polylang: 

![Screen Shot 2020-04-09 at 9 18 43 AM](https://user-images.githubusercontent.com/1260765/78911163-2e83ab80-7a43-11ea-83ed-890991a642ef.png)

And if I query the Enum using GraphQL introspection in WPGraphiQL, we can see there are no values:

![Screen Shot 2020-04-09 at 9 20 06 AM](https://user-images.githubusercontent.com/1260765/78911264-53781e80-7a43-11ea-8471-7067feba6a8d.png)

This is where Gatsby is getting tripped up. 

If I add a language to PolyLang: 

![Screen Shot 2020-04-09 at 9 20 58 AM](https://user-images.githubusercontent.com/1260765/78911354-71de1a00-7a43-11ea-9acf-e48a8b478cd5.png)

And Query the Enum again, there are values: 

![Screen Shot 2020-04-09 at 9 21 35 AM](https://user-images.githubusercontent.com/1260765/78911429-88847100-7a43-11ea-8d19-0a00a0785bb5.png)

----

The PR also addresses this by adding a default language. This will allow users that have installed PolyLang and WPGraphQL for Polylang to not run into issues before going through the Polylang setup. 

Here, I have no languages again: 

![Screen Shot 2020-04-09 at 9 18 43 AM](https://user-images.githubusercontent.com/1260765/78911163-2e83ab80-7a43-11ea-83ed-890991a642ef.png)

And with the code changed in my PR, I can query the Schema and we will see a default value from the locale of the site: 

![Screen Shot 2020-04-09 at 9 23 38 AM](https://user-images.githubusercontent.com/1260765/78911644-cf726680-7a43-11ea-993b-f61c80ead226.png)

**Comment by jasonbahl** [comment] 2020-04-09 15:25
@ktw-studio I'm going to close this issue in favor of the issue/PR I've opened on the WPGraphQL for Polylang repo: 

- **Issue**: https://github.com/valu-digital/wp-graphql-polylang/issues/20
- **PR**: https://github.com/valu-digital/wp-graphql-polylang/pull/21

**Closed by jasonbahl** 2020-04-09 15:25 UTC
Labels: topic: WordPress, type: bug

**Comment by ktw-studio** [comment] 2020-04-09 19:00
@jasonbahl You were absolutely right, seems this issue was not directly caused by gatsby itself. Thank you all for your help and sorry for the trouble! Be safe, be in health, keep on being awesome!

:)
