### ISSUE TITLE
"gatsby new" error "Cannot read properties of undefined"

### ISSUE THREAD

**Issue by benmathews** [gatsbyjs/gatsby#37394] opened 2023-01-02 21:27 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Running `gatsby new` results in an error.

```
❯ node --version
v18.12.1
➜ npm --version
9.2.0
❯ gatsby --version
Gatsby CLI version: 5.3.1
```

```
➜ gatsby new
create-gatsby version 3.3.1



                                                  Welcome to Gatsby!



This command will generate a new Gatsby site for you in ******** with the setup you
select. Let's answer some questions:



What would you like to call your site?
✔ · ******
What would you like to name the folder where your site will be created?
✔ *******
✔ Will you be using JavaScript or TypeScript?
· JavaScript
✔ Will you be using a CMS?
· No (or I'll add it later)
✔ Would you like to install a styling system?
· No (or I'll add it later)
✔ Would you like to install additional features with other plugins?
· Add responsive images
· Add an automatic sitemap
· Add Markdown and MDX support
· Add Markdown support (without MDX)

 ERROR  UNKNOWN

Cannot read properties of undefined (reading 'plugins')



  TypeError: Cannot read properties of undefined (reading 'plugins')
  
  - index.js:1 
    [lib]/[gatsby-cli]/[create-gatsby]/lib/index.js:1:495599
  
  - Array.map
  
  - index.js:1 exports.run
    [lib]/[gatsby-cli]/[create-gatsby]/lib/index.js:1:495577
  
  - task_queues:95 processTicksAndRejections
    node:internal/process/task_queues:95:5
  
  - create-cli.js:456 
    [lib]/[gatsby-cli]/lib/create-cli.js:456:9
  ```

### Reproduction Link

na

### Steps to Reproduce

Run gatsby new

### Expected Result

Functional starter should be generated

### Actual Result

crash

### Environment

```shell
➜ gatsby info --clipboard

  System:
    OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.15 - ~/.asdf/shims/yarn
    npm: 9.2.0 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Languages:
    Python: 3.10.6 - /home/ben/bin/python
  Browsers:
    Chrome: 107.0.5304.121
    Firefox: 108.0.1
  npmGlobalPackages:
    gatsby-cli: 5.3.1
```

### Config Flags

na

**Comment by tyhopp** [comment] 2023-01-03 04:17
Hi @benmathews, I wasn't able to reproduce this on Linux with the same Node and Gatsby versions and prompt responses. If you run the command without the prompt (`npx gatsby new some-site-name`) does it also fail?

**Comment by benmathews** [comment] 2023-01-03 04:23
That worked.

**Comment by tyhopp** [comment] 2023-01-03 04:25
Great! Since there's not much else I can do to triage without being able to reproduce I'll close this.

**Closed by tyhopp** 2023-01-03 04:25 UTC
Labels: type: bug, status: needs more info
