### ISSUE TITLE
[gatsby-source-wordpress] null value from ACF field using Wordpress source

### ISSUE THREAD

**Issue by jooola** [gatsbyjs/gatsby#29529] opened 2021-02-15 21:54 UTC
## Description

An ACF file field 'fichier' has a inconsistent behavior, the field is sometimes null, but no way to predict when or which one (see screenshots). Maybe the field doesn't get the data from WordPress at first launch but is filled when wordpress update the post, which updates the Gatsby data.

**Wordpress:**
- WP Gatsby Version 1.0.1
- WP GraphQL Version  1.1.5
- WPGraphQL for Advanced Custom Fields Version 0.4.0

**Gatsby:**
- "gatsby-source-wordpress": "^4.0.1",

My basic gatsby config:
```
{
  resolve: "gatsby-source-wordpress",
  options: {
    url: "https://xxxxxxxxx/graphql",
  },
},
```
If I force update the fields on the wordpress editor with the same value, while gatsby dev is running, the field gets finally filled on the Gatsby side.

![image](https://user-images.githubusercontent.com/19195485/105627295-5effcf00-5e36-11eb-83bd-097deec194f5.png)
![image](https://user-images.githubusercontent.com/19195485/105627308-7ccd3400-5e36-11eb-9b82-9113787e282f.png)

### Steps to reproduce

- Setup similar ACF fields.
- Run gatsby develop 

### Expected result

File should be filled with proper data.

### Actual result

File is null.

### Environment
```
  System:
    OS: Linux 5.9 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (4) x64 Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
    Shell: 5.7.1 - /usr/bin/zsh
  Binaries:
    Node: 14.15.5 - /tmp/yarn--1613425950823-0.6922920903973984/node
    Yarn: 1.22.5 - /tmp/yarn--1613425950823-0.6922920903973984/yarn
    npm: 6.14.11 - /usr/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Firefox: 78.7.0esr
  npmPackages:
    gatsby: ^2.32.3 => 2.32.3 
    gatsby-image: ^2.11.0 => 2.11.0 
    gatsby-plugin-manifest: ^2.12.0 => 2.12.0 
    gatsby-plugin-react-helmet: ^3.10.0 => 3.10.0 
    gatsby-plugin-robots-txt: ^1.5.5 => 1.5.5 
    gatsby-plugin-sass: ^3.2.0 => 3.2.0 
    gatsby-plugin-sharp: ^2.14.1 => 2.14.1 
    gatsby-plugin-sitemap: ^2.12.0 => 2.12.0 
    gatsby-source-filesystem: ^2.11.0 => 2.11.0 
    gatsby-source-wordpress: ^4.0.1 => 4.0.1 
    gatsby-transformer-sharp: ^2.12.0 => 2.12.0 
```

**Comment by sol-idsnake** [comment] 2021-02-18 16:16
Maybe not a direct fix, but there are updates to these Wordpress plugins:

- WP Gatsby Version 0.9.2 --> 1.01
- WP GraphQL Version 1.1.3 --> 1.1.5

I'd start there and see if you can rule these out.

**Comment by jooola** [comment] 2021-02-18 16:32
I just updated all the dependencies, but it didn't fixed this bug.

**Comment by jooola** [comment] 2021-03-07 17:47
Upgraded to gatsby 3 and gatsby source wordpress 5, and this didn't fix this.

**Comment by jooola** [comment] 2021-03-23 09:31
The WordPress code used to create the custom posts:
```php
add_action('init', function () {
    register_post_type('shows', [
        'label' => __('Émission', 'aro_theme'),
        'description' => __('Émissions', 'aro_theme'),
        'labels' => [
            'name' => _x('Émissions', 'Post Type General Name', 'aro_theme'),
            'singular_name' => _x('Émission', 'Post Type Singular Name', 'aro_theme'),
            'menu_name' => __('Émissions', 'aro_theme'),
            'name_admin_bar' => __('Émissions', 'aro_theme'),
        ],
        'supports' => ['title', 'editor', 'author', 'comments', 'revisions', 'excerpt'],
        'taxonomies' => ['category'],
        'hierarchical' => false,
        'public' => true,
        'show_ui' => true,
        'show_in_menu' => true,
        'menu_position' => 5,
        'menu_icon' => 'dashicons-format-audio',
        'show_in_admin_bar' => true,
        'show_in_nav_menus' => true,
        'can_export' => true,
        'has_archive' => true,
        'exclude_from_search' => false,
        'publicly_queryable' => true,
        'capability_type' => 'page',

        'rewrite' => [
            'slug' => 'emissions',
            'with_front' => false,
        ],
        'cptp_permalink_structure' => '/%category%/%postname%/',

        'show_in_graphql' => true,
        'graphql_single_name' => 'show',
        'graphql_plural_name' => 'shows',
    ]);
}, 0);
```

If this issue is not reproducible, I can give access to the graphql endpoint I have an issue with.

**Comment by jooola** [comment] 2021-03-23 09:33
The field is actually always null on the first Wordpress fetch, but filled when the value gets updated with the auto update functionality.

**Comment by jooola** [comment] 2021-04-08 16:54
@TylerBarnes Sorry to ping you directly, I was hoping to give this ticket some more attention.

I had this bug for a while now, and I could not find a better way to describe it. It seems any file ACF field will result with a null on the first fetch but will be updated if changed on WordPress while having the development server running.

**Comment by TylerBarnes** [comment] 2021-04-08 17:57
Hi @jooola can you please follow the steps here https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/debugging-and-troubleshooting.md#missing-data-in-gatsby

Most likely there's a bug in your WP instance where querying some combination of fields causes the data to come back null when fetching nodes in lists (getting `posts` vs getting one `post` for example)

**Comment by jooola** [comment] 2021-04-08 18:36
I just tried the debugging guide and fetching data using the generated graphql files return the ID and the type name of the supposed null data.


```
query NODE_LIST_QUERY($first: Int!, $after: String) {
  shows(first: $first, after: $after) {
    nodes {
      author {
        node {
          id
        }
      }
      authorDatabaseId
      authorId
      categories(first: 100) {
        nodes {
          id
        }
      }
      commentCount
      commentStatus
      comments(first: 100) {
        nodes {
          id
        }
      }
      content
      contentType {
        node {
          id
        }
      }
      databaseId
      date
      dateGmt
      desiredSlug
      enclosure
      excerpt
      guid
      id
      isRevision
      lastEditedBy {
        node {
          id
        }
      }
      link
      modified
      modifiedGmt
      showMeta {
        episodes {
          fieldGroupName
          file {
            __typename
            id
          }
          title
        }
        fieldGroupName
      }
      slug
      status
      template {
        templateName
        __typename
      }
      terms(first: 100) {
        nodes {
          id
          __typename
        }
      }
      title
      uri
      __typename
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
```

```
{
  "data": {
    "shows": {
      "nodes": [
        {
          "author": {
            "node": {
              "id": "dXNlcjoy"
            }
          },
          "authorDatabaseId": 2,
          "authorId": "dXNlcjoy",
          "categories": {
            "nodes": [
              {
                "id": "dGVybToxMTM="
              }
            ]
          },
          "commentCount": null,
          "commentStatus": "open",
          "comments": {
            "nodes": []
          },
          "content": "<p><strong>Miguel Benasayag était il y a 5 ans l&rsquo;invité du Fenouil à Vapeur<\/strong> -cantine collective et festive- à Avignon.<br \/>\nCette rencontre autour de la notion d&rsquo;engagement n&rsquo;a rien perdu de sa fraîcheur. Elle s&rsquo;appuie sur ses nombreux travaux, recherches, écrits, parmi lesquels ont peut citer : <em>De l&rsquo;engagement dans une époque obscure<\/em> (avec Angélique del Rey) ; <em>Eloge du conflit<\/em> (id.) ; Plus jamais seul ; <em>Les Passions Tristes<\/em> ; <em>Résister c&rsquo;est créer<\/em> (avec Florence Aubenas) ; <em>Clinique du mal-être<\/em> ; <em>Le cerveau augmenté, l&rsquo;homme diminué<\/em>.<\/p>\n<hr \/>\n<p>La rencontre est proposée à l&rsquo;écoute en deux parties (1h10 et 1h20).<\/p>\n<p>(Musiques : G. Trovesi et G. Coscia, Django \/ Les Violons Barbares, Chasseur (extrait) \/ Ostinato, Tourpakak)<\/p>\n",
          "contentType": {
            "node": {
              "id": "cG9zdF90eXBlOnNob3dz"
            }
          },
          "databaseId": 296,
          "date": "2021-04-05T15:53:43",
          "dateGmt": "2021-04-05T13:53:43",
          "desiredSlug": null,
          "enclosure": null,
          "excerpt": "<p>Miguel Benasayag était il y a 5 ans l&rsquo;invité du Fenouil à Vapeur -cantine collective et festive- à Avignon. Cette rencontre autour de la notion d&rsquo;engagement n&rsquo;a rien perdu de sa fraîcheur. Elle s&rsquo;appuie sur ses nombreux travaux, recherches, écrits, parmi lesquels ont peut citer : De l&rsquo;engagement dans une époque obscure (avec Angélique del [&hellip;]<\/p>\n",
          "guid": "https:\/\/XXXXXXXXXXXXXXXX\/?post_type=shows&#038;p=296",
          "id": "cG9zdDoyOTY=",
          "isRevision": false,
          "lastEditedBy": null,
          "link": "https:\/\/XXXXXXXXXXXXX\/emissions\/premier-sons\/resister-jouer-collectif\/de-lengagement-rencontre-avec-miguel-benasayag\/",
          "modified": "2021-04-08 14:04:01",
          "modifiedGmt": "2021-04-08T12:04:01",
          "showMeta": {
            "episodes": [
              {
                "fieldGroupName": "episodes",
                "file": {
                  "__typename": "MediaItem",
                  "id": "cG9zdDozNjc="
                },
                "title": "Partie 1"
              },
              {
                "fieldGroupName": "episodes",
                "file": {
                  "__typename": "MediaItem",
                  "id": "cG9zdDozNjk="
                },
                "title": "Partie 2"
              }
            ],
            "fieldGroupName": "showMeta"
          },
          "slug": "de-lengagement-rencontre-avec-miguel-benasayag",
          "status": "publish",
          "template": {
            "templateName": "Default",
            "__typename": "DefaultTemplate"
          },
          "terms": {
            "nodes": [
              {
                "id": "dGVybToxMTM=",
                "__typename": "Category"
              }
            ]
          },
          "title": "De l’engagement, rencontre avec Miguel Benasayag",
          "uri": "\/emissions\/premier-sons\/resister-jouer-collectif\/de-lengagement-rencontre-avec-miguel-benasayag\/",
          "__typename": "Show"
        }
      ],
      "pageInfo": {
        "hasNextPage": false,
        "endCursor": "YXJyYXljb25uZWN0aW9uOjEyMQ=="
      }
    }
  },
  "extensions": {
    "debug": []
  }
}

```
I could send you the graphl endpoint url.

**Comment by jooola** [comment] 2021-04-08 19:02
I just tested with a fresh wordpress and the bare minimum extensions, and it seem to work. but I haven't tried with a custom post type.

**Comment by veryspry** [comment] 2021-04-13 18:20
Closing this since it seems to be a duplicate of https://github.com/gatsbyjs/gatsby/issues/30755

**Closed by veryspry** 2021-04-13 18:20 UTC
Labels: status: needs more info, topic: WordPress

**Comment by jooola** [comment] 2021-04-13 18:28
Ok, I feel this ticket is more advanced/broad than the new one #30755. I guess we will continue over there.

**Comment by TylerBarnes** [comment] 2021-04-13 18:42
@jooola we'll use the info from this issue there as well, thanks for providing so much good info about the issue. We closed this one in favour of that one because we had also closed another issue in favour of that one (trying to prevent hopping through a chain of issues).
Thanks again!
