### ISSUE TITLE
Gatsby 2.22 throwing FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by rgraber** [gatsbyjs/gatsby#24713] opened 2020-06-02 13:25 UTC
## Description

Upon upgrading fro gatsby 2.21 to 2.22, building develop began throwing FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
errors. We have not substantially changed the number of pages or the queries used to generate them. 
The errors persist even when we up the max_old_space_size to 16384.

### Steps to reproduce

Build command: `node --max_old_space_size=8192 node_modules/gatsby/dist/bin/gatsby develop -p 5335 --host  0.0.0.0`

Unfortunately project is not public, but we build about 20K pages and --max_old_space_size=8192 has been enough up until this upgrade

### Expected result

Develop build succeeds

### Actual result

`<--- Last few GCs --->

[9635:0x4086450]   225601 ms: Mark-sweep 1996.2 (2081.9) -> 1984.9 (2083.4) MB, 1264.1 / 0.0 ms  (average mu = 0.217, current mu = 0.128) allocation failure scavenge might not succeed
[9635:0x4086450]   226973 ms: Mark-sweep 1998.4 (2083.4) -> 1987.1 (2085.7) MB, 1216.7 / 0.0 ms  (average mu = 0.167, current mu = 0.113) allocation failure scavenge might not succeed

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x13a71b9]
    1: StubFrame [pc: 0x133368a]
Security context: 0x245fe53008d1 <JSObject>
    2: getMessages(aka getMessages) [0x35a855cc38a9] [/edx/app/node_modules/gatsby-plugin-intl/gatsby-node.js:~79] [pc=0x9deddffa20c](this=0x08aa04d404b1 <undefined>,0x2cda1f561fb1 <String[26]: /edx/app/src/i18n/messages>,0x1457aa2b8479 <String[#2]: es>)
    3: generatePage(aka generatePage) [0x35a855cc38e9] [/edx/app/node_modules...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

Writing Node.js report to file: report.20200602.130201.9635.0.001.json
Node.js report completed
 1: 0x9ef190 node::Abort() [node]
 2: 0x9f13b2 node::OnFatalError(char const*, char const*) [node]
 3: 0xb5da9e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb5de19 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd0a765  [node]
 6: 0xd0adf6 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xd1760a v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
 8: 0xd18515 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xd1afcc v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xce19bb v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
11: 0x10246ce v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
12: 0x13a71b9  [node]
`

### Environment

  System:
    OS: Linux 4.19 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: (4) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Shell: 4.4.12 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.13 - /usr/bin/python
  npmPackages:
    gatsby: ~2.22.0 => 2.22.15 
    gatsby-cli: ^2.4.15 => 2.7.31 
    gatsby-image: ^2.0.33 => 2.2.8 
    gatsby-link: ^2.0.16 => 2.2.5 
    gatsby-node-helpers: ^0.3.0 => 0.3.0 
    gatsby-plugin-intl: 0.2.8 => 0.2.8 
    gatsby-plugin-netlify: ^2.0.12 => 2.1.5 
    gatsby-plugin-netlify-cms: ^4.0.0 => 4.1.15 
    gatsby-plugin-purgecss: ^5.0.0 => 5.0.0 
    gatsby-plugin-react-helmet: ^3.0.9 => 3.1.3 
    gatsby-plugin-react-helmet-async: ^1.0.7 => 1.0.9 
    gatsby-plugin-sass: ^2.0.11 => 2.1.8 
    gatsby-plugin-segment-js: ^3.0.1 => 3.0.1 
    gatsby-plugin-sharp: ^2.4.5 => 2.4.5 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.8 => 1.1.8 
    gatsby-source-contentful: ^2.1.86 => 2.2.7 
    gatsby-source-filesystem: ^2.0.25 => 2.1.9 
    gatsby-source-greenhouse: ^2.0.2 => 2.0.2 
    gatsby-transformer-json: ^2.1.10 => 2.2.2 
    gatsby-transformer-remark: ^2.3.3 => 2.6.14 
  npmGlobalPackages:
    gatsby: 2.19.28

Related to #24291

**Comment by LekoArts** [comment] 2020-06-03 05:28
Hi!

If fear that you "how to reproduce" steps are not enough to get to the bottom of this. Gatsby sites can largely vary and e.g. each 20K page will be different.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

[reproduction]: https://gatsby.dev/reproduction

**Comment by tim-line** [comment] 2020-06-06 17:43
Left a comment on #24829 but I'm experiencing a similar issue. Build runs fine on 2.21.40 but errors with a JavaScript heap error on 2.22.0. I'll review my code and see if I can create a reproducible example early next week.

**Comment by LekoArts** [comment] 2020-06-16 09:44
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-06-16 09:44 UTC
Labels: status: needs reproduction
