### ISSUE TITLE
Error in function useStaticQuery in ./.cache/gatsby-browser-entry.js:77

### ISSUE THREAD

**Issue by kuroroblog** [gatsbyjs/gatsby#31942] opened 2021-06-16 12:13 UTC
## Description

Unhandled Runtime Error

One unhandled runtime error found in your files. See the list below to fix it:

Error in function useStaticQuery in ./.cache/gatsby-browser-entry.js:77

The result of this StaticQuery could not be fetched. This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues

./.cache/gatsby-browser-entry.js:77
Open in Editor

>  75 |     return context[query].data
  76 |   } else {
 77 |     throw new Error(
     |          ^
  78 |       `The result of this StaticQuery could not be fetched.\n\n` +
  79 |         `This is likely a bug in Gatsby and if refreshing the page does not fix it, ` +
  80 |         `please open an issue in https://github.com/gatsbyjs/gatsby/issues`

<img width="1209" alt="screenshot 2021-06-16 21 03 44" src="https://user-images.githubusercontent.com/23373288/122215605-5e9bc980-cee6-11eb-894b-dc4ff82c7478.png">

### Steps to reproduce

1.  `$ git clone {myProjectFolder}`
2. `$ rm -rf node_modules` 
2. `$ rm -rf .cache`
3. `$ gatsby clean`
4. `$ yarn install`
5. `$ gatsby develop`
6. error...

### Expected result

not error

### Actual result

above error

### Environment
Mac OS Big Sur : 11.4
yarn version : 1.22.4

package.json
```
"dependencies": {
    "@material-ui/core": "^4.11.3",
    "file-type": "^16.3.0",
    "firebase": "^8.3.2",
    "gatsby": "^3.1.2",
    "gatsby-image": "^3.2.0",
    "gatsby-plugin-advanced-sitemap": "^1.6.0",
    "gatsby-plugin-google-adsense": "^1.1.3",
    "gatsby-plugin-google-gtag": "^3.2.0",
    "gatsby-plugin-image": "^1.2.1",
    "gatsby-plugin-lodash": "^4.4.0",
    "gatsby-plugin-manifest": "^3.3.0",
    "gatsby-plugin-offline": "^4.3.0",
    "gatsby-plugin-react-helmet": "^4.2.0",
    "gatsby-plugin-sharp": "^3.2.0",
    "gatsby-plugin-typescript": "^3.2.0",
    "gatsby-source-filesystem": "^3.2.0",
    "gatsby-transformer-sharp": "^3.2.0",
    "lodash": "^4.17.21",
    "node": "^15.12.0",
    "node-fetch": "^2.6.1",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-gist": "^1.2.2",
    "react-helmet": "^6.1.0",
    "react-icons": "^4.2.0",
    "react-lazyload": "^3.2.0",
    "react-markdown": "^5.0.3",
    "react-router-dom": "^5.2.0",
    "react-scroll": "^1.8.2",
    "react-syntax-highlighter": "^15.4.3",
    "remark-gfm": "^1.0.0",
    "source-map-support": "^0.5.19",
    "ts-node": "^9.1.1",
    "typescript": "^4.2.3"
  },
  "devDependencies": {
    "@types/react-helmet": "^6.1.0",
    "@types/react-lazyload": "^3.1.0",
    "@types/react-router-dom": "^5.1.7",
    "@types/react-scroll": "^1.8.2",
    "@types/react-syntax-highlighter": "^13.5.0",
    "@typescript-eslint/eslint-plugin": "^4.20.0",
    "@typescript-eslint/parser": "^4.20.0",
    "eslint": "^7.23.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-react": "^7.23.1",
    "gatsby-plugin-eslint": "^3.0.0",
    "prettier": "^2.2.1"
  },
```

**Comment by ramojej** [comment] 2021-06-16 13:32
I'm having the same problem after updating my dependencies. Here's my environment

```

  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor              
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.48)
  npmPackages:
    gatsby: ^3.7.2 => 3.7.2 
    gatsby-plugin-gatsby-cloud: ^2.7.1 => 2.7.1 
    gatsby-plugin-image: ^1.7.1 => 1.7.1 
    gatsby-plugin-manifest: ^3.7.1 => 3.7.1 
    gatsby-plugin-no-index: ^1.0.2 => 1.0.2 
    gatsby-plugin-offline: ^4.7.1 => 4.7.1 
    gatsby-plugin-postcss: ^4.7.1 => 4.7.1 
    gatsby-plugin-preact: ^5.7.1 => 5.7.1 
    gatsby-plugin-react-helmet: ^4.7.1 => 4.7.1 
    gatsby-plugin-react-svg: ^3.0.1 => 3.0.1 
    gatsby-plugin-sharp: ^3.7.1 => 3.7.1 
    gatsby-source-filesystem: ^3.7.1 => 3.7.1 
    gatsby-source-wordpress: ^5.7.1 => 5.7.1 
    gatsby-transformer-sharp: ^3.7.1 => 3.7.1 
  npmGlobalPackages:
    gatsby-cli: 3.6.0

```

**Comment by cnekol** [comment] 2021-06-17 07:10
This happened when I am following the Gatsby Tutorial at 
Part 4 [Task: Use useStaticQuery to pull the site title into the Layout component](https://www.gatsbyjs.com/docs/tutorial/part-4/#task-use-usestaticquery-to-pull-the-site-title-into-the-layout-component)

with this graphql query

```
const data = useStaticQuery(graphql`
    query {
      site {
        siteMetadata {
          title
        }
      }
    }  
  `)
```

It's OS X Big Sur 11.3.1 and I'm new here, just install node.js/gatsby today and playing with Tutorial.
Stuck there now.

**Comment by kuroroblog** [comment] 2021-06-17 09:59
I was able to fix it using the following procedure.

1. Open terminal.
2. `$ cd desktop`(Go to the desktop.)
3. `$ gatsby new gatsby-starter-blog https://github.com/gatsbyjs/gatsby-starter-blogCopy`(reference : https://www.gatsbyjs.com/starters/gatsbyjs/gatsby-starter-blog)
4. your own repository code rewrites in 3 procedure repo code.

But I can't explain why it worked...

Let's talk if anyone else has done it well!!!

**Comment by LekoArts** [comment] 2021-06-18 06:02
Duplicate of https://github.com/gatsbyjs/gatsby/issues/26563 - please post your full reproduction there. Thanks!

**Closed by LekoArts** 2021-06-18 06:02 UTC
Labels: type: bug
