### ISSUE TITLE
gatsby-source-drupal times out sometimes when it shouldn't

### ISSUE THREAD

**Issue by jstramel** [gatsbyjs/gatsby#34034] opened 2021-11-19 21:20 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I recently updated `gatsby-source-drupal` to the current master branch version due to issues that have been resolved and merged. After the update I consistently receive the following error both on my local machine and a Gatsby Cloud instance pulling from an AWS RDS server. The workaround for me was to reduce the `concurrentAPIRequests` to 5 which of course slows my build time.

There is no consistency as to which jsonapi endpoint is timing out and varies from build to build.

![CleanShot 2021-11-19 at 16 07 48](https://user-images.githubusercontent.com/1660385/142691795-224362ca-7b6e-4f33-b910-ef457eea7c74.png)
s.

### Reproduction Link

n/a

### Steps to Reproduce

1.
2.
3.
...

### Expected Result

Full build without errors

### Actual Result

Multiple errors on various endpoint calls: `Timeout awaiting 'request' for 15000ms`

### Environment

```shell
System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.15.1/bin/yarn
    npm: 8.1.1 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 95.0.4638.69
    Firefox: 93.0
    Safari: 15.0
  npmPackages:
    gatsby: ^4.0.0 => 4.2.0 
    gatsby-cli: ^4.0.0 => 4.2.0 
    gatsby-plugin-emotion: ^7.0.0 => 7.2.0 
    gatsby-plugin-feed: ^4.0.0 => 4.2.0 
    gatsby-plugin-gatsby-cloud: ^4.0.0 => 4.2.0 
    gatsby-plugin-manifest: ^4.0.0 => 4.2.0 
    gatsby-plugin-offline: ^5.0.0 => 5.2.0 
    gatsby-plugin-postcss: ^5.0.0 => 5.2.0 
    gatsby-plugin-react-helmet: ^5.0.0 => 5.2.0 
    gatsby-plugin-sass: ^5.0.0 => 5.2.0 
    gatsby-plugin-sharp: ^4.0.0 => 4.2.0 
    gatsby-plugin-sitemap: ^5.0.0 => 5.2.0 
    gatsby-source-drupal: ^5.0.0 => 5.2.0 
    gatsby-source-filesystem: ^4.0.0 => 4.2.0 
    gatsby-source-graphql: ^4.0.0 => 4.2.0 
    gatsby-transformer-sharp: ^4.0.0 => 4.2.0 
  npmGlobalPackages:
    gatsby-cli: 4.2.0
```

**Comment by LekoArts** [comment] 2021-11-22 07:22
Hi, thanks for the issue!

To make the process of resolving problems quicker for both sides we need you to fill out the issue template and give us a [minimal reproduction][reproduction].

[reproduction]: https://gatsby.dev/reproduction

**Comment by apotheosistech** [comment] 2021-11-22 12:38
Per @KyleAMathews no reproduction was needed because he was also aware of the issue.

**Closed** 2021-11-22 17:11 UTC
Labels: type: bug, status: needs reproduction, topic: source-drupal
