### ISSUE TITLE
Fix "resource preloaded but not used" warning in Chrome

### ISSUE THREAD

**Issue by hogyster** [gatsbyjs/gatsby#14872] opened 2019-06-18 14:27 UTC
I am keep getting the warning message at chrome 

https://www.selectchu.com

"The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally."

The resource https://www.selectchu.com/component---src-pages-index-js-e3609fd82d452154463c.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource https://www.selectchu.com/google-fonts/s/roboto/v19/KFOmCnqEu92Fr1Mu4mxK.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource https://www.selectchu.com/app-97f530f3e5a7162dfd06.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource https://www.selectchu.com/webpack-runtime-c108f36890d85c65bb96.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource https://www.selectchu.com/google-fonts/s/roboto/v19/KFOlCnqEu92Fr1MmWUlfBBc4.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource https://www.selectchu.com/google-fonts/s/notosanskr/v11/Pby7FmXiEBPT4ITbgNA5CgmOalv45bIR.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource https://www.selectchu.com/google-fonts/s/opensans/v16/mem8YaGs126MiZpBA-UFVZ0b.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource https://www.selectchu.com/google-fonts/s/opensans/v16/mem5YaGs126MiZpBA-UN7rgOUuhp.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource https://www.selectchu.com/styles-c23128a881c72b69f101.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource https://www.selectchu.com/google-fonts/s/notosanskr/v11/PbykFmXiEBPT4ITbgNA5CgmG237t.woff2 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
The resource https://www.selectchu.com/1-41a7a9b6ed6c2c325059.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

what can be the main problem? and how to solve it?

these are plugins i use

```
plugins: [
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-styled-components`,
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sass`,
    `gatsby-plugin-sharp`,
    `gatsby-plugin-transition-link`,
    {
      resolve: `gatsby-plugin-prefetch-google-fonts`,
      options: {
        fonts: [
          {
            family: `Noto Sans KR`,
            subsets: [`latin`, 'korean'],
            variants: [`400`, `700`]
          },
          {
            family: `Open Sans`,
            variants: [`400`, `700`]
          },
          {
            family: `Roboto`,
            variants: [`400`, `700`]
          },
        ],
      },
    },
    'gatsby-transformer-remark',
```

**Comment by freiksenet** [comment] 2019-06-20 09:19
Sorry to hear you are having an issue! Could you try if upgrading Gatsby fixes this?

**Comment by hogyster** [comment] 2019-06-20 11:21
Have upgraded to the latest gatsby and the warning still come up

**Comment by hogyster** [comment] 2019-06-20 11:22
> Sorry to hear you are having an issue! Could you try if upgrading Gatsby fixes this?

Have upgraded to the latest gatsby and the warning still come up :(

**Comment by freiksenet** [comment] 2019-06-20 13:15
The issue is that somehow `crossorigin=""` is added to the links. This is a bug. We'll investigate it.

Thanks a lot for reporting this! :muscle: :purple_heart:

**Comment by superhawk610** [comment] 2019-06-21 01:47
@hogyster keep an eye on #14608, I'm working on a plugin that will add `<link preload>` to each route as needed for each font used on that page. It allows the `crossorigin` attribute to be configured per-route if needed!

**Comment by hogyster** [comment] 2019-06-21 01:49
> The issue is that somehow `crossorigin=""` is added to the links. This is a bug. We'll investigate it.
> 
> Thanks a lot for reporting this! 💪 💜

Thanks! hope the warning goes away soon.
:)

**Comment by hogyster** [comment] 2019-06-21 01:51
> preload

great! will look up to it, else, not only to the fonts maybe it will be good if it adds to all the links. The warning I get seems to be happening on other scripts too.

**Comment by m-allanson** [comment] 2019-07-08 15:40
Hey @hogyster this seems like it's expected behaviour for `gatsby-plugin-prefetch-google-fonts`. The plugin is making each font be preloaded, but the fonts aren't necessarily used on each page. Check out #14608 for another approach to this. Closing this as I think it it's a warning that can be fixed. Thanks!

**Closed by m-allanson** 2019-07-08 15:40 UTC
Labels: effort: low, help wanted, impact: med, status: confirmed, type: bug

**Comment by AlexMachin1997** [comment] 2020-08-28 17:21
Hmm I've just across this issue after deploying my site. 

The only difference is I'm using gatsby-plugin-google-fonts instead.

![image](https://user-images.githubusercontent.com/29917195/91595360-52487f00-e95b-11ea-8579-81389f413aa4.png)

Anyone know how to remove this warning ?

**Comment by superhawk610** [comment] 2020-09-09 19:29
@AlexMachin1997 `gatsby-plugin-google-fonts` simply adds a preload for _all fonts_ to _all routes_ in your app, which will cause the (harmless) warnings you're seeing. This is the simplest approach with the least friction, but those warnings are unavoidable if you're not using every font on every route. 

If you'd like to remove those warnings, you'll need to switch to `gatsby-plugin-preload-fonts`, which preloads fonts _per route_, thus only preloading exactly the fonts that are required by each page. However, this plugin does require that you manually update the route-font mapping periodically, so it's up to you whether it's worth the extra effort.

If you need any further help choosing or getting setup, check out [the community page](https://www.gatsbyjs.com/contributing/community/#where-to-get-support) for support links!

**Comment by kimbaudi** [comment] 2020-11-22 16:22
This warning is happening on my site built w/ Gatsbty because the `<link rel="preload" />` tag is missing `crossorigin="anonymous"`. I get 8 warnings a few seconds after the page loads. Looking at the source shows the warnings are related to `<link>` element missing `crossorigin="anonymous"`.

![issue](https://user-images.githubusercontent.com/1864092/99909033-ee53ff00-2c9a-11eb-97c1-18c7b251cd30.png)

**Comment by Hellrungj** [comment] 2021-09-24 05:10
The Gatsby team is currently working on a fix for this issue: [#28982 fix(gatsby): crossOrigin attr to scripts in headComponents](https://github.com/gatsbyjs/gatsby/pull/28982)

**Comment by MadaShindeInai** [comment] 2022-03-17 06:41
Same situation. 14 warnings. Is there a way to fix it?
<img width="872" alt="Screenshot 2022-03-17 at 07 41 07" src="https://user-images.githubusercontent.com/50995397/158751694-410d7cb1-d5d2-4420-bf31-6ebeab41e729.png">

**Comment by fivetwelve** [comment] 2022-04-14 04:44
I'm experiencing similar  warnings. I'm on Gatsby 4.6.2 and loading my fonts from `@fontsource`

![Screen Shot 2022-04-14 at 00 37 57](https://user-images.githubusercontent.com/2784676/163314622-1f305a28-23fc-4170-ad76-ef68603abc6e.png)

**Comment by fivetwelve** [comment] 2022-04-14 05:03
Update, FWIW: I added `gatsby-plugin-preload-fonts` and created the font cache as per its guide; and I don't see any further warnings. I'm glad it resolved itself but I don't see this necessarily as a good solution for medium to large-scale sites unless it can be automated as part of the build process.

**Comment by Christian-Garrison** [comment] 2022-05-13 14:08
## Same warnings around preloaded links

- current versions of gatsby related dependencies

```
"gatsby": "^4.14.0",
"gatsby-plugin-breadcrumb": "^12.3.1",
"gatsby-plugin-image": "^2.14.0",
"gatsby-plugin-manifest": "^4.14.0",
"gatsby-plugin-netlify": "^4.3.1",
"gatsby-plugin-offline": "^5.14.0",
"gatsby-plugin-react-helmet": "^5.14.0",
"gatsby-plugin-sass": "^5.14.0",
"gatsby-plugin-sitemap": "^5.14.0",
"gatsby-source-sanity": "^7.4.2",
```

- `gatsby-plugin-preload-fonts` this was considered or used above, is this the recommended fix? Seems like a band-aid approach and introduces another dependency to worry about

![Screen Shot 2022-05-13 at 8 57 35 AM](https://user-images.githubusercontent.com/75394049/168300343-cf035460-a88c-4588-9d8c-cdc3f0674084.png)

### Other Production Errors

<img width="966" alt="screen_shot_2022-05-12" src="https://user-images.githubusercontent.com/75394049/168301472-e02609d2-6a12-4608-a077-0df2aa10d52b.png">

**Comment by LanguageXange** [comment] 2022-07-12 23:49
any updates on this ?

**Comment by EmekaOrji** [comment] 2022-07-17 13:25
This issue is not closed as it has not been resolved, the solutions for the fonts is okay, but this solution does not address the remaining issues.

**Comment by kcanamar** [comment] 2022-08-02 23:01
I have been receiving the same warnings when working through the Gatsby tutorial.

**Comment by Waqas-Jani** [comment] 2022-08-05 13:27
i'm receiving same warnning on safari, and working fine on chrome

**Comment by beicnet** [comment] 2022-08-12 11:57
Same over here too, any solution or fix for it soon?!

**Comment by andykimchris** [comment] 2022-10-20 06:42
There is a chance this isn't really a constraning bug
https://wordpress.org/support/topic/the-resource-url-was-preloaded-using-link-preload-but-not-used-within/

**Comment by openmindculture** [comment] 2022-11-15 10:20
> There is a chance this isn't really a constraining bug
> https://wordpress.org/support/topic/the-resource-url-was-preloaded-using-link-preload-but-not-used-within/

Thats's the reason to close the issue?
This is not only WordPress related. I keep getting those unhelpful warnings on many sites, cluttering my devtools without adding any value. Still reproducible with the latest Chromium on Linux.

**Comment by uxjulia** [comment] 2022-12-01 18:23
This is definitely still an issue.

**Comment by theCompanyDream** [comment] 2023-03-25 17:41
Any word on if this was fixed I upgraded to gatsby v5 and am still having this issue?

**Comment by s7aks** [comment] 2023-04-20 10:56
[<a href="https://ibb.co/tzmB2Df"><img src="https://i.ibb.co/JqBnpHL/console-warnings.jpg" alt="console-warnings" border="0"></a>](url)

**Comment by s7aks** [comment] 2023-06-05 23:35
![image](https://github.com/gatsbyjs/gatsby/assets/60385571/eee48506-c75c-4d6d-a93f-0f24fdaac2cf)

Going nuts.

**Comment by meenakshi-negi** [comment] 2023-06-14 05:07
I am seeing the same issue .But I am not seeing any network call. Could you please help us out it will busy the server with so much
resource calls. Or its just waring no impact on performance

**Comment by Yanis540** [comment] 2023-07-02 14:27
I had this issue on version 13.4.7, downgrading to 13.4.1 might seem to work for me !

**Comment by juliannehalversen** [comment] 2023-08-01 16:04
Same issue here

**Comment by adluders** [comment] 2023-08-26 19:01
same issue but using next js

**Comment by MS3300studios** [comment] 2023-09-18 14:47
Same issue for GatsbyJS

**Comment by nicitaacom** [comment] 2024-01-28 07:17
### I see same issue
![image](https://github.com/gatsbyjs/gatsby/assets/39565703/66024126-c4df-460d-ba70-4e7974cba7b8)

**Comment by laughing593** [comment] 2025-02-03 06:22
@juliannehalversen https://preprocessor.space/questions/the-contents-of-my-scriptjs-file-do-not-align-with-the-code-in-the-mail

**Comment by nicitaacom** [comment] 2025-02-08 06:45
Hey is this issue still open?

Is someone going to fix that?
