### ISSUE TITLE
Navigating to other pages is causing app crash [Tested with latest version of gatsby (2.21.1) also]

### ISSUE THREAD

**Issue by mghazanfar** [gatsbyjs/gatsby#23583] opened 2020-04-29 09:41 UTC
Since last 2 weeks, my app in prod crashes for just no reason when I navigate. It does not happen every time of navigation but on random pages. I've noticed that pages that call data from server on initial load are prone to crash. The log when app crashes can be seen in the console image as below.
I'm really stranded here as I need to launch my app but facing this issue.
![image](https://user-images.githubusercontent.com/25903155/80582024-789af400-8a27-11ea-8316-be32b4e64202.png)

**Comment by vladar** [comment] 2020-04-29 18:40
@madalynrose I think it relates to this comment: https://github.com/gatsbyjs/gatsby/pull/19290/files#r368007531

Probably need a null check there indeed.

**Comment by vladar** [comment] 2020-04-29 19:00
Hey @mghazanfar 

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

It is hard to deliver a reliable fix without reproduction.

Also please note that we have guidelines on [how to file an issue](https://www.gatsbyjs.org/contributing/how-to-file-an-issue/). Please provide as much context as possible. We appreciate it.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by mghazanfar** [comment] 2020-04-30 11:07
@vladar I just dont think if I can provide more information than above. Please have a keen read and you'll know what's wrong!

**Comment by mghazanfar** [comment] 2020-05-05 04:44
@madalynrose @vladar Most information to reproduce it is already given. What I can add is: I'm using Axios for data fetching. Any page that fetches array of data crashes.
My app live link: http://ec2-18-218-75-71.us-east-2.compute.amazonaws.com:8080/
ou'll be able to navigate to other pages but when you go to Tours or Blogs page from app bar, app will crash.
This is happening on the live prod link. It never happens during development!

**Comment by isabellachen** [comment] 2020-05-06 19:13
@mghazanfar I have the same error `Cannot read property 'innerText' of null` when navigating to pages that use MDXRenderer to render MDX rawBody. The pages that are crashing for you, do they use the MDXRenderer?

**Comment by mghazanfar** [comment] 2020-05-06 21:05
> @mghazanfar I have the same error `Cannot read property 'innerText' of null` when navigating to pages that use MDXRenderer to render MDX rawBody. The pages that are crashing for you, do they use the MDXRenderer?

What is MDXRenderer?

**Comment by isabellachen** [comment] 2020-05-06 22:16
@mghazanfar It is a component to render markdown files with JSX but I guess it's not the problem you have. Are you able to hit the pages directly without using the link? I have the same error but it's because there is an error on the page I want to route to. Commenting out the code that was causing the error allowed me to click on the link to the page.

**Comment by mghazanfar** [comment] 2020-05-06 22:24
When I navigate using gatsby Link, it crashes. Then I reload the window and the page is shown. It happens now with every page in production but seldom in development mode.

**Comment by isabellachen** [comment] 2020-05-06 23:13
It looks like for some reason in prod the server call is slow and is delaying other React operations, including the mounting of the ref in the navigation.js file, resulting in the error: https://github.com/gatsbyjs/gatsby/pull/19290/files#r368007531 
Tbh I don't know if that's true, just an assumption since I get your same error due to the delay caused from the my MDXrenderer error.

**Comment by mghazanfar** [comment] 2020-05-07 06:08
@vladar what’s the status of this issue?

**Comment by mghazanfar** [comment] 2020-05-23 09:36
@madalynrose any update on this???

**Comment by danabrit** [comment] 2020-05-29 22:41
@mghazanfar So sorry for the delay in responding. 

We would like to help get you moved along with your site. Please refer to the link on [how to make a minimal reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) and share that with us along with the data requested in the [how to file an issue](https://www.gatsbyjs.org/contributing/how-to-file-an-issue/) document. That will give us the codebase and information we need to evaluate, reproduce, and help resolve the errors you're facing.

Thank you!

**Comment by madalynrose** [comment] 2020-05-29 22:56
Thanks, @danabrit! 

@mghazanfar A [fix for the nullish ref](https://github.com/gatsbyjs/gatsby/pull/23956) went out a few weeks ago so I'm thinking the issue must be somewhere else. A minimal production, as described above, would be most helpful to debugging and narrowing down what might be happening since I can't reproduce the issue myself.

**Comment by vladar** [comment] 2020-06-03 18:08
Thank you for opening this, @mghazanfar

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. In that case please provide a [minimal reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) as requested above.

We hope we managed to help and thank you for using Gatsby! 💜

**Closed by vladar** 2020-06-03 18:08 UTC
Labels: status: needs more info, status: needs reproduction
