### ISSUE TITLE
Gatsby Cloud build fail error: ERROR Service request 

### ISSUE THREAD

**Issue by Mask2** [gatsbyjs/gatsby#36959] opened 2022-11-04 02:25 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [x] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

After updating `gatsby` from `v4.20.0` to `v4.24.5` and related plugins, this error shows every building time.

<img width="715" alt="image" src="https://user-images.githubusercontent.com/13297501/199871071-3b2d6c2c-95e3-4376-8569-6ced3581bd18.png">

```js
04:19:56 AM:
success Checking for changed pages - 0.001s

04:19:56 AM:
verbose 35.407136504 Found 449 changed pages

04:19:56 AM:
success onPreExtractQueries - 0.000s

04:20:15 AM:
ERROR Service request {

04:20:15 AM:
  resourceSpans: [ { resource: [Object], scopeSpans: [Array], schemaUrl: undefined } ]

04:20:15 AM:
}

04:20:22 AM:
success extract queries from components - 26.073s
```

### Reproduction Link

not

### Steps to Reproduce

1. update to gatsby `v4.24.5` and use Gatsby Cloud building.

### Expected Result

Do not show this error and build success.

### Actual Result

Show this error `ERROR Service request`

### Environment

```shell
System:
    OS: macOS 12.5
    CPU: (10) x64 Apple M1 Max
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.1 - /usr/local/bin/node
    Yarn: 1.22.15 - ~/.yarn/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
  Browsers:
    Chrome: 107.0.5304.87
    Firefox: 105.0.3
    Safari: 15.6
  npmPackages:
    gatsby: ^4.24.5 => 4.24.5
    gatsby-awesome-pagination: ^0.3.8 => 0.3.8
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5
    gatsby-plugin-image: ^2.24.0 => 2.24.0
    gatsby-plugin-manifest: ^4.24.0 => 4.24.0
    gatsby-plugin-material-ui: 3.0.1 => 3.0.1
    gatsby-plugin-mdx: ^4.3.0 => 4.3.0
    gatsby-plugin-react-helmet: ^5.24.0 => 5.24.0
    gatsby-plugin-react-i18next: ^2.0.5 => 2.0.5
    gatsby-plugin-react-svg: ^3.1.0 => 3.1.0
    gatsby-plugin-sharp: ^4.24.0 => 4.24.0
    gatsby-plugin-sitemap: ^5.24.0 => 5.24.0
    gatsby-plugin-smoothscroll: ^1.2.0 => 1.2.0
    gatsby-remark-embed-video: ^3.2.1 => 3.2.1
    gatsby-remark-images: ^6.24.0 => 6.24.0
    gatsby-source-filesystem: ^4.24.0 => 4.24.0
    gatsby-transformer-json: ^4.24.0 => 4.24.0
    gatsby-transformer-sharp: ^4.24.0 => 4.24.0
```

**Comment by LekoArts** [comment] 2022-11-04 07:50
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by Vacilando** [comment] 2022-11-15 15:17
Same problem since a few days!

**Comment by LekoArts** [comment] 2022-11-15 15:20
The service request is error is an error with our analytics in Gatsby Cloud. It's harmless and it'll be fixed.

Since this is not about the Gatsby OSS project I'll close this.

**Closed by LekoArts** 2022-11-15 15:20 UTC
Labels: type: bug, status: needs reproduction

**Comment by Vacilando** [comment] 2022-11-15 22:02
Thanks, it's good to know that
- it's not Gatsby OSS (we had no way to know that unfortunately)
- it's harmless even if it produces a red ERROR message (usually associated with important errors in Gatsby Cloud log)
