### ISSUE TITLE
Images in css files do not get assetsPrefix in production build

### ISSUE THREAD

**Issue by marishkaSunrise** [gatsbyjs/gatsby#37654] opened 2023-02-15 02:54 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When add static background images to css files, Gatsby 5 doesn't add assetPrefix (added to gatsby-config.js) to them in production build. It makes it impossible to use cdn, because not all images can be added to js files as img HTML tag or imported to components where assetPrefix is being applied correctly (with withPrefix function).

### Reproduction Link

https://codesandbox.io/s/wandering-rgb-hx2pp4
### Steps to Reproduce

Create a css file
`.container {
      background-image: url("/logo.svg")
  }`

Add container class name to html 
<div className="container"/ >

Add to gatsby-config.js:
assetPrefix: https://cdn.example.com

Build the app for production, see pages source code , inlined styles do not have assetsPrefix added to image paths. 

### Expected Result

In prod output inlined css styles should look like

<style>.container{backgrround-image:url('https://cdn.example.com/logo.svg')}</style>

### Actual Result

<style>.container{backgrround-image:url('/logo.svg')}</style>

### Environment

```shell
System:
    OS: macOS 13.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.12.1/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v18.12.1/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 108.0.2
    Safari: 16.2
  npmPackages:
    gatsby: ^5.6.0 => 5.6.0
    gatsby-link: ^5.6.0 => 5.6.0
    gatsby-page-utils: ^3.6.0 => 3.6.0
    gatsby-plugin-canonical-urls: ^5.6.0 => 5.6.0
    gatsby-plugin-env-variables: ^2.3.0 => 2.3.0
    gatsby-plugin-eslint: ^4.0.3 => 4.0.3
    gatsby-plugin-manifest: ^5.6.0 => 5.6.0
    gatsby-plugin-preconnect: ^1.4.0 => 1.4.0
    gatsby-plugin-purgecss: ^6.2.1 => 6.2.1
    gatsby-plugin-root-import: ^2.0.9 => 2.0.9
    gatsby-plugin-sass: ^6.4.0 => 6.6.0
    gatsby-plugin-sitemap: ^6.4.0 => 6.6.0
    gatsby-plugin-split-css: ^2.0.3 => 2.0.3
    gatsby-plugin-styled-components: ^6.4.0 => 6.6.0
    gatsby-source-filesystem: ^5.6.0 => 5.6.0
  npmGlobalPackages:
    gatsby-cli: 5.6.0
```

**Comment by pieh** [comment] 2023-02-16 09:14
Are you using `--prefix-paths` toggle when running `gatsby build`? See https://www.gatsbyjs.com/docs/how-to/previews-deploys-hosting/asset-prefix/#enable-prefixing-for-builds

I am getting prefix when I use this toggle. There was regression some time ago, but it was fixed in `gatsby@5.4.0` ( https://github.com/gatsbyjs/gatsby/pull/37429 )

**Comment by marishkaSunrise** [comment] 2023-02-16 18:24
Yes, I do "gatsby build --prefix-paths" when build for prod. I get assets prefix for all css, js , images included directly to html files, but all background images added to css files directly are not getting assets prefix.

**Comment by pieh** [comment] 2023-02-17 07:35
Ok, after some changes I manage to reproduce - this only happens when image / url path starts with `/`. When using correct relative path it works:

![image](https://user-images.githubusercontent.com/419821/219579909-19ff72c3-8f53-4092-a53f-967b73d76b51.png)


This seems to be because of this config https://github.com/gatsbyjs/gatsby/blob/66584a22426d8ce03cfcc9a1eb39d4342ef7f755/packages/gatsby/src/utils/webpack-utils.ts#L313-L321 - I will try to check why it's done like that - there might be valid reason to use that

**Comment by marishkaSunrise** [comment] 2023-02-17 21:50
Thank for checking. When I add background images to css with relative path starting with ../ ... in prod version I get all images (svg, webp, jpg) inlined as something like `background-image:url(data:image/svg+xml;base64,...`.  No assetsPath is being added

Also in your example I see in the prod url `.../static/ ..` folder but in the latest gatsby documentation I see this:
Every file you put into that folder will be copied into the public folder. E.g. if you add a file named sun.jpg to the static folder, it’ll be copied to public/sun.jpg (https://www.gatsbyjs.com/docs/how-to/images-and-media/static-folder/)
Which means that all static files are added to the public directory directly. Not sure how you got assets files copied with static folder into public directory.

**Comment by marishkaSunrise** [comment] 2023-02-23 05:08
Not a bug

**Closed** 2023-02-23 05:08 UTC
Labels: type: bug, topic: media, topic: webpack/babel
