### ISSUE TITLE
Uncaught (in promise) ReferenceError: config is not defined

### ISSUE THREAD

**Issue by kota65535** [gatsbyjs/gatsby#34496] opened 2022-01-14 12:42 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

- Suppose we have foo.js that export a variable named `config` and its setter.
```
export let config

export const setConfig = (c) => {
  config = c
}
```

- And call the setter in onClientEntry function.
```
const {setConfig} = require("./src/foo");

exports.onClientEntry = () => {
  setConfig({test: 1})
}
```

- After running `gatsby develop`, we will see the following error.
![image](https://user-images.githubusercontent.com/10975834/149514707-92540c6e-41d5-4583-9845-acaa2776b078.png)

- What's strange is that changing the variable name `config` to other names fix this error. For example, changing foo.js as follows completely works.
```
export let cfg

export const setConfig = (c) => {
  cfg = c
}
```

- Reproduction project below is created from very simple gatsby-starter-hello-world.

### Reproduction Link

https://github.com/kota65535/gatsby-test

### Steps to Reproduce

1. npm run develop
2. open it in a browser
3. see the developer console

### Expected Result

No error

### Actual Result

![image](https://user-images.githubusercontent.com/10975834/149515636-edc64c25-a23a-4583-ae0e-7d0866ff183e.png)

### Environment

```shell
System: 
  OS: macOS Catalina
  CPU: Intel Core i9
Binaries
  Node: v16.13.1
  NPM 8.1.2
Browsers
  Chrome: 97.0.4692.71（Official Build） （x86_64）
NpmPackages
  gatsby: 4.5.2
```

**Comment by LekoArts** [comment] 2022-01-18 07:38
Duplicate of https://github.com/gatsbyjs/gatsby/issues/33998

**Closed by LekoArts** 2022-01-18 07:38 UTC
Labels: type: bug, topic: core
