### ISSUE TITLE
Error: The result of this StaticQuery could not be fetched.

### ISSUE THREAD

**Issue by iSagnik** [gatsbyjs/gatsby#28059] opened 2020-11-15 00:36 UTC
## Description

Describe the issue that you're seeing.
The image queries are not working and Gatsby Background image is not loading the images on my website https://liquidrocketry.com
### Steps to reproduce
Load the website. The landing page will be black and the image will be missing.

### Expected result
Image loads in the landing page and the 'Test Stand' section

### Actual result
Black background without the image

### Environment
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.6 - /c/Users/isagn/AppData/Local/Programs/Python/Python38-32/python
  Browsers:
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    gatsby: ^2.25.4 => 2.25.4
    gatsby-background-image: ^1.1.1 => 1.1.1
    gatsby-image: ^2.3.5 => 2.3.5
    gatsby-plugin-anchor-links: ^1.1.1 => 1.1.1
    gatsby-plugin-fontawesome-css: ^1.0.0 => 1.0.0
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-manifest: ^2.3.7 => 2.3.7
    gatsby-plugin-offline: ^3.1.5 => 3.1.5
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-react-helmet: ^3.2.5 => 3.2.5
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^2.6.35 => 2.6.35
    gatsby-plugin-styled-components: ^3.3.10 => 3.3.10
    gatsby-source-filesystem: ^2.2.5 => 2.2.5
    gatsby-transformer-sharp: ^2.4.7 => 2.4.7
  npmGlobalPackages:
    gatsby-cli: 2.12.90

**Comment by LekoArts** [comment] 2020-11-16 06:59
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2020-11-27 09:56
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-11-27 09:56 UTC
Labels: status: needs reproduction, type: bug
