### ISSUE TITLE
Gatsby incorrectly creates chunks after upgrading to granular chunking

### ISSUE THREAD

**Issue by abedziak** [gatsbyjs/gatsby#26041] opened 2020-07-27 10:28 UTC
## Description

After upgrading to the version which introduced granular chunking I started having strange issue with how production chunks are generated. This only happens to my homepage index page. Almost every component on this page is added to the main bundle with shared packages
![Screenshot 2020-07-27 at 12 18 39](https://user-images.githubusercontent.com/25925991/88531550-4f2c3d00-d003-11ea-819b-d37f45cc67b7.png)

Then my component--src-templates-index-js is only 700b with just two modules
![Screenshot 2020-07-27 at 12 19 01](https://user-images.githubusercontent.com/25925991/88531592-5c492c00-d003-11ea-9fc8-c848a3d3e7f0.png)

The reason why my index page is in templates instead of page is because of the design of the website and multiple locales. However, it was correctly generated before the upgrade.

The bunlde builds fine andcan be served via Cloudfront. However, I noticed that I started getting some mixed content issue, which was not happening before. My index.html is now correctly served as a document but also as text/html and I have an issue with css main file also having wrong MIME type : text/html

### Expected result

All page modules should be in component--src-templates-index-js chunk

### Actual result

Mixed content in main chunk with common packages together with page modules.

### Environment

```
  System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Languages:
    Python: 2.7.14 - /Library/Frameworks/Python.framework/Versions/2.7/bin/python
  Browsers:
    Chrome: 84.0.4147.89
    Firefox: 78.0.2
    Safari: 13.0.4
  npmGlobalPackages:
    gatsby-cli: 2.12.43
```

**Comment by wardpeet** [comment] 2020-09-25 15:20
Hi @abedziak!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by LekoArts** [comment] 2020-10-12 07:40
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-10-12 07:40 UTC
Labels: status: needs reproduction, type: bug
