### ISSUE TITLE
gatsby-remark-embed-video returning a blank div

### ISSUE THREAD

**Issue by ashishch-98** [gatsbyjs/gatsby#26917] opened 2020-09-16 11:56 UTC
I'm embedding a youtube video with the help of documentation given in gatsby [on working with video](https://www.gatsbyjs.com/docs/working-with-video/#sourcing-video-from-a-host), so I followed it but on the webpage, there was an empty div where the video should have been. I found a blog on the internet [suggesting to use more plugins](https://scotch.io/tutorials/embedding-videos-in-your-gatsbyjs-sites) for embedding the video but the result is the same. Is it a bug or I have missed something?

components/video.js

```
import React from "react"
import "./video.css"
const Video = ({ videoSrcURL, videoTitle, ...props }) => (
  <div className="video">
    <iframe
      src={videoSrcURL}
      title={videoTitle}
      allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
      frameBorder="0"
      webkitallowfullscreen="true"
      mozallowfullscreen="true"
      allowFullScreen
    />
  </div>
)
export default Video
```

in my templates folder
```
import Video from "../components/video"
//code for template

return(
//more code here
<Video
          videoSrcURL={post.frontmatter.videoSrcURL}
          videoTitle={post.frontmatter.videoTitle}
  />        
)

export const query = graphql`
  query SongQuery($slug: String!) {
    markdownRemark(fields: { slug: { eq: $slug } }, fileAbsolutePath: {regex: "/sheets/"}) {
      frontmatter {
        title
        videoSrcURL
        videoTitle
        featureImage{
          childImageSharp{
            fixed{
              ...GatsbyImageSharpFixed
            }
          }
        }
        
      }
      internal {
        content
      }
    }
    site{
      siteMetadata{
        title
      }
    }
  }
`
```

my md file
```
---
title: md title
featureImage: ../image/image.jpg
videoSourceURL: https://www.youtube.com/embed/ZB5sEqs37gU
videoTitle: "Dhanyawad"
<img width="362" alt="div" src="https://user-images.githubusercontent.com/71139972/93333713-5cb2b600-f841-11ea-9fee-df5a9e7488fb.PNG">
<img width="362" alt="div" src="https://user-images.githubusercontent.com/71139972/93333762-6dfbc280-f841-11ea-8d16-48455fdac9a9.PNG">


---
md content 
```

gatsby-config.js
```
module.exports = {
  siteMetadata: {
    title: Gatsby`,
    description: `gatsby blog`,
    author: `@ashish`,
  },
  
  plugins: [
    `gatsby-plugin-sharp`,
    `gatsby-transformer-sharp`,
    `gatsby-transformer-remark`,
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-styled-components`,
    `gatsby-plugin-sass`,

    {
      resolve: "gatsby-remark-embed-video",
      options: {
          width: 800,
          ratio: 1.77, 
          height: 400, 
          related: false,
          noIframeBorder: true
      },
    },
    {
      resolve: `gatsby-remark-responsive-iframe`,
      options: {
          wrapperStyle: `margin-bottom: 1.0725rem`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `sheets`,
        path: `${__dirname}/content/sheets`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `image`,
        path: `${__dirname}/content/image`,
      },
    },
    {
      resolve: `gatsby-plugin-mdx`,
      options: {
        extensions: [`.md`, `.mdx`], // highlight-line
      },
    },
    {
      resolve: `gatsby-remark-images`,
      options: {
        maxWidth: 590,
      },
    },
  ],
}
```
Screenshot of webpage on inspecting. Blank space is shown on inspecting it.
<img width="362" alt="div" src="https://user-images.githubusercontent.com/71139972/93333802-7fdd6580-f841-11ea-9fb8-6b1213d73ab6.PNG">

**Comment by tony** [comment] 2020-09-18 00:18
Is there anything generally in the past few days (on or around gatsby 2.24.62 or mdx 1.6.18) that'd effect mdx and gatsby some how?

I have a more intricate mdx setup (difficult to do a recreation / minimal example for), but stuff that was working with mdx earlier isn't now.

(cc: #26941 which also has a mdx issue, but may not be in scope)

Any feedback on mdx / remark in gatsby changing behavior would be of help - if we need to fork it into a separate topic so this issue isn't interrupted, please do (I don't have enough info to justify beginning one, yet)

**Comment by LekoArts** [comment] 2020-09-21 13:05
Hi!

Since this could be caused by different versions it would be incredibly helpful if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by ascorbic** [comment] 2020-09-24 15:53
Hi. I'm going to close this issue, because it relates to a third-party plugin. It's best if you open an issue on [the plugin's repo](https://github.com/borgfriend/gatsby-remark-embed-video) first. If it can be established that it's an issue with gatsby itself then please open a new issue, linking to the issue on the third party plugin so that we can have the context needed to track it down.

**Closed by ascorbic** 2020-09-24 15:53 UTC
Labels: status: needs reproduction, topic: Markdown/remark, type: bug
