### ISSUE TITLE
gatsby link retaining scroll position and scrolls to top while navigating to other routes

### ISSUE THREAD

**Issue by thanigai1709** [gatsbyjs/gatsby#30026] opened 2021-03-05 10:31 UTC
## Description
this is the [website ](https://coderapper-demo-excrin.netlify.app/)ive been working it has some weired issue when i try to navigate to other pages from a section.

Home page has a section called work . when i click "view case study" from that section it redirects to that page but the problem is after redirecting the scroll position is retained and then it scrolls to top.

But, the page was suppposed start at [0,0] scroll position

Here's the video of the issue

https://user-images.githubusercontent.com/40536034/110104708-82bb1b00-7dcd-11eb-841c-75f32a9671f0.mp4

**Comment by LekoArts** [comment] 2021-03-05 11:07
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by thanigai1709** [comment] 2021-03-05 13:57
https://github.com/code-rapper/agency-site/tree/gatsby-issue-reproduce

**Comment by vladar** [comment] 2021-03-09 13:08
@thanigai1709 The repository is not available. Is it private? Can you please share the repro publicly?

**Comment by rabiiayed** [comment] 2021-03-11 14:58
I have the same issue

**Comment by Oliweer** [comment] 2021-03-16 10:53
This happens in chrome because of "scroll-behavior: smooth;" being set on :root. Among them bootstrap's reboot does this with 
```css
@media (prefers-reduced-motion: no-preference) {
  :root {
    scroll-behavior: smooth;
  }
}
```
You can solve it by setting this
```css
:root {
  scroll-behavior: unset;
}
```

**Comment by LekoArts** [comment] 2021-03-16 11:21
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-03-16 11:21 UTC
Labels: status: needs reproduction, topic: reach/router and navigation, type: bug
