### ISSUE TITLE
[gatsby-image] webp images incorrectly generated

### ISSUE THREAD

**Issue by sirichards** [gatsbyjs/gatsby#19865] opened 2019-11-28 18:14 UTC
Webp images are being generated incorrectly, worth noting this has a transparent background.

### Expected result

![pin-1200](https://user-images.githubusercontent.com/21104091/69826294-74fe0980-120a-11ea-8b8c-b39fffd5067c.png)

### Actual result

Couldn't upload the actual webp image as GitHub doesn't support it for upload, but it looks like this:

![pin-1200-webp](https://user-images.githubusercontent.com/21104091/69826390-cc03de80-120a-11ea-84d3-04e82e390481.png)

### Environment

  System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
  Binaries:
    Node: 12.9.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.18.4 => 2.18.5 
    gatsby-cli: ^2.7.53 => 2.8.14 
    gatsby-image: ^2.2.34 => 2.2.34 
    gatsby-plugin-canonical-urls: ^2.1.10 => 2.1.16 
    gatsby-plugin-google-tagmanager: ^2.1.12 => 2.1.18 
    gatsby-plugin-manifest: ^2.2.20 => 2.2.30 
    gatsby-plugin-offline: ^2.2.10 => 2.2.10 
    gatsby-plugin-react-helmet: ^3.1.10 => 3.1.16 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-resolve-src: ^2.0.0 => 2.0.0 
    gatsby-plugin-sass: ^2.1.17 => 2.1.24 
    gatsby-plugin-sharp: ^2.3.4 => 2.3.4 
    gatsby-plugin-sitemap: ^2.2.16 => 2.2.22 
    gatsby-plugin-styled-components: ^3.1.8 => 3.1.14 
    gatsby-source-filesystem: ^2.1.28 => 2.1.39 
    gatsby-transformer-json: ^2.2.11 => 2.2.20 
    gatsby-transformer-sharp: ^2.3.6 => 2.3.6 

node -v
v12.9.0

**Comment by LekoArts** [comment] 2019-12-02 08:40
This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/14497 :)

**Closed by LekoArts** 2019-12-02 08:40 UTC
