### ISSUE TITLE
`layout` option of `createPage` does not work

### ISSUE THREAD

**Issue by tung-dang** [gatsbyjs/gatsby#3335] opened 2017-12-25 04:20 UTC
## Description

`layout` option of `createPage` does not work. As this document https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#creating-pages-in-gatsby-nodejs, `layout` option can be passed to `createPage` API so Gatsby can get a template from `layouts/${layout}` folder. 

### Environment

Gatsby version: 1.9.138
Node.js version: v8.9.3
Operating System: Mac OS High Sierra 10.13.2

### Actual result

If `layout` option is passed an value to `createPages` API, ex: 'blog-layout', `layouts/blog-layout.js` is not loaded. So I have to ignore the `layout` - don't pass any value, in order to Gatsby falls to default value to load  `layouts/index.js` file.

### Expected behavior

`layout` option should work like in the document (https://www.gatsbyjs.org/docs/creating-and-modifying-pages/#creating-pages-in-gatsby-nodejs) mentions.

**Comment by KyleAMathews** [comment] 2017-12-25 13:08
Could you build a small site reproducting the error? There's a number of people using custom layouts.

**Comment by KyleAMathews** [comment] 2017-12-25 16:40
Sorry you're having trouble. It'd be great if we could figure out better error messages or documentation to smooth the experience.

**Comment by belbiy** [comment] 2018-02-03 01:16
I'm also having this issue as well, using `exports.createPages` like this
```
createPage({
    path: node.data.path,
    layout: 'custom-layout',
    component: path.resolve(node.node.absolutePath),
})
```
Still uses the `index` layout. 

But when I apply layout from `exports.onCreatePage` it works.

**Comment by tung-dang** [comment] 2018-02-03 10:31
@belbiy The workaround works for me. Thanks a lot.
@KyleAMathews: Here is a commit to reproduce this bug: [Commit](https://github.com/tung-dang/gatsby-starter-blog/commit/d4f32998a1ac066cc872f3ddd2568de0cca603a0?diff=unified). Thank you.

**Comment by KyleAMathews** [comment] 2018-09-08 04:10
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Closed by KyleAMathews** 2018-09-08 04:10 UTC
