### ISSUE TITLE
Invalid regular expression with gatsby source wordpress

### ISSUE THREAD

**Issue by Aschab** [gatsbyjs/gatsby#30766] opened 2021-04-08 21:55 UTC
While running `gatsby develop` on a clean environment I get: 

```
error SyntaxError: Invalid regular expression: /https://www.dacast.com/support/knowledgebase/walkthrough-video-on-demand-vod/#:~:text=Creating%20video%20on%20demand%20(VOD,you%20see%20after%20logging%20in.(?!/?wp-content%7C/?wp-admin%7C/?wp-includes)/: Unterminated group
    at new RegExp (<anonymous>)
    at forEach (/home/runner/work/dacast_gatsby/dacast_gatsby/node_modules/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js:832:34)
    at Array.forEach (<anonymous>)
    at nodeStringFilter (/home/runner/work/dacast_gatsby/dacast_gatsby/node_modules/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js:820:17)
    at processNodeString (/home/runner/work/dacast_gatsby/dacast_gatsby/node_modules/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js:867:24)
    at processNode (/home/runner/work/dacast_gatsby/dacast_gatsby/node_modules/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/process-node.js:905:31)
    at /home/runner/work/dacast_gatsby/dacast_gatsby/node_modules/gatsby-source-wordpress/src/steps/source-nodes/create-nodes/create-nodes.js:42:12
    at run (/home/runner/work/dacast_gatsby/dacast_gatsby/node_modules/p-queue/dist/index.js:163:´´´
    
    It is non fatal, but that page gets ignored, not really sure how to approach that issue, not sure where is the wrong regular expression

**Comment by LekoArts** [comment] 2021-04-09 08:21
Hi, thanks for the issue!

To make the process of resolving problems quicker for both sides we need you to fill out the issue template and give us a minimal reproduction:

```md
<!--
  Please fill out each section below, otherwise, your issue will be closed. This info allows Gatsby maintainers to diagnose (and fix!) your issue as quickly as possible.

  Useful Links:
  - Documentation: https://www.gatsbyjs.com/docs/
  - How to File an Issue: https://www.gatsbyjs.com/contributing/how-to-file-an-issue/

  Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
-->

## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
```

**Comment by LekoArts** [comment] 2021-04-16 07:24
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-04-16 07:24 UTC
Labels: status: needs reproduction, topic: WordPress, type: bug
