### ISSUE TITLE
BUG: Broken documentation page, search for Gatsby starter 

### ISSUE THREAD

**Issue by FilipMessa** [gatsbyjs/gatsby#21930] opened 2020-03-03 11:00 UTC
## Description

When a user tries to search for the gatsby starter app failed.

![bug-docs](https://user-images.githubusercontent.com/6354326/75769192-07500500-5d46-11ea-8877-53e4df217789.gif)

```
react-dom.production.min.js:4684 TypeError: Cannot read property 'toLowerCase' of undefined
    at filtered-starters.js:86
    at Array.filter (<anonymous>)
    at n.render (filtered-starters.js:85)
    at qi (react-dom.production.min.js:4289)
    at Ki (react-dom.production.min.js:4280)
    at So (react-dom.production.min.js:6722)
    at hu (react-dom.production.min.js:5696)
    at pu (react-dom.production.min.js:5685)
    at au (react-dom.production.min.js:5441)
    at react-dom.production.min.js:2877
```

### Steps to reproduce

1. go to https://www.gatsbyjs.org/starters/?v=2
2. write some text into the search starter field

### Environment

Chrome: Version 80.0.3987.122 (Official Build) (64-bit)
Firefox: 73.0.1 (64-bit)

**Comment by pvdz** [comment] 2020-03-03 11:08
Thanks for reporting.

This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/21916 which is fixed but the website just has to rebuild.

**Closed by pvdz** 2020-03-03 11:08 UTC
Labels: type: bug, type: documentation
