### ISSUE TITLE
gatsby-source-shopify fails to download images

### ISSUE THREAD

**Issue by roowilliams** [gatsbyjs/gatsby#29056] opened 2021-01-17 09:26 UTC
## Description

After uploading some large transparent PNGs as product images I started getting issues with the build. I resized the PNGs to max 1600px longest dimension but the build process is still failing on an image under 2mb. Console output below, and the image in question was a 1.1mb, 1600px x 900px, PNG-24, but it seems to happen on larger images > 8mb.

```gatsby-source-shopify/evwhere fetched and processed Collection nodes: 1081.537ms

 ERROR 

error an error occurred while sourcing data

success Downloading remote files - 92.931s - 10/23 0.25/s

 ERROR #11321  PLUGIN

"gatsby-source-shopify" threw an error while running the sourceNodes lifecycle:

failed to process https://cdn.shopify.com/s/files/1/0478/0841/3846/products/MIC09047-Edit.png
Failed to download https://cdn.shopify.com/s/files/1/0478/0841/3846/products/MIC09047-Edit.png after 3 attempts
```

Other errors seen include a connection reset and invalid address `cdn.shopify.com`. Will capture the codes if they appear again.

### Steps to reproduce
1. Clone starter https://github.com/AlexanderProd/gatsby-shopify-starter
2. Use a store/token with images? 

### Expected result

Images download, project builds.

### Actual result

Project fails to build, unable to develop.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by LekoArts** [comment] 2021-01-19 10:15
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by ascorbic** [comment] 2021-01-28 12:10
Hi. I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. Thanks!

**Closed by ascorbic** 2021-01-28 12:10 UTC
Labels: status: needs reproduction, topic: Shopify, type: bug

**Comment by roowilliams** [comment] 2021-01-28 13:30
Hi, after some testing I believe it's due to a patchy wifi connection during build. The wifi connection remains but perhaps there is some packet loss creating the effect.

Thanks
Roo

**Comment by jonsherrard** [comment] 2021-08-04 17:30
@roowilliams did you ever solve this. I've got the weirdes thing that I can repeat. When I try and run `gatsby start`, `building-schema` hangs on downloading an image which then _kills my wifi connection_ and eventually my mac. Completely bizarre.

**Comment by roowilliams** [comment] 2021-08-05 11:02
Hi Jon,

It turned out to be my wifi connection - macOS showed my wifi was
connected, but it was actually pretty patchy and then as a result the build
would fail.

Your issue does sound like a strange one. Any chance your wifi could be
patchy also? Any opportunity to try a wired connection?

**Comment by jonsherrard** [comment] 2021-08-05 11:14
Thanks @roowilliams - I would live to dive deeper into my issue. The Shopify recursive image downloading is 100% blocking all internet traffic on my machine. As soon as I force cancel everything loads.

1. `gatsby develop`
2. Wait until `source-shopify` is downloading images
3. Load a page in chrome (which hangs)
4. quit `gatsby develop`
5. chrome page will suddenly load

Utterly bizzare - but I'm not going to dive into it haha

I've switched to not downloading the images at build time and running them straight off the CDN.

I'll upgrade to version 5 once there's a better migration document.
