### ISSUE TITLE
 Build Error [gatsby-telemetry] - Cannot build

### ISSUE THREAD

**Issue by joebentaylor1995** [gatsbyjs/gatsby#26896] opened 2020-09-14 18:01 UTC
## Description

I cant build my app due to this error on build / develop:
```
Error: Cannot find module 'gatsby-telemetry'
  Require stack:
  - /Volumes/Work/L+R/www/website-gatsby/node_modules/gatsby-plugin-page-creator/create-page-wrapper.js
  - /Volumes/Work/L+R/www/website-gatsby/node_modules/gatsby-plugin-page-creator/gatsby-node.js
  - /Volumes/Work/L+R/www/website-gatsby/node_modules/gatsby/dist/bootstrap/resolve-module-exports.js
  - /Volumes/Work/L+R/www/website-gatsby/node_modules/gatsby/dist/bootstrap/load-plugins/validate.js
  - /Volumes/Work/L+R/www/website-gatsby/node_modules/gatsby/dist/bootstrap/load-plugins/load.js
  - /Volumes/Work/L+R/www/website-gatsby/node_modules/gatsby/dist/bootstrap/load-plugins/index.js
  - /Volumes/Work/L+R/www/website-gatsby/node_modules/gatsby/dist/services/initialize.js
  - /Volumes/Work/L+R/www/website-gatsby/node_modules/gatsby/dist/services/index.js
  - /Volumes/Work/L+R/www/website-gatsby/node_modules/gatsby/dist/state-machines/develop/services.js
  - /Volumes/Work/L+R/www/website-gatsby/node_modules/gatsby/dist/state-machines/develop/index.js
  - /Volumes/Work/L+R/www/website-gatsby/node_modules/gatsby/dist/commands/develop-process.js
  - /Volumes/Work/L+R/www/website-gatsby/.cache/tmp-94644-7DZnL5R3B00G
  
  - loader.js:794 Function.Module._resolveFilename
    internal/modules/cjs/loader.js:794:15
  
  - loader.js:687 Function.Module._load
    internal/modules/cjs/loader.js:687:27
  
  - loader.js:849 Module.require
    internal/modules/cjs/loader.js:849:19
  
  - v8-compile-cache.js:159 require
    [website-gatsby]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - create-page-wrapper.js:16 Object.<anonymous>
    [website-gatsby]/[gatsby-plugin-page-creator]/create-page-wrapper.js:16:24
  
  - v8-compile-cache.js:178 Module._compile
    [website-gatsby]/[v8-compile-cache]/v8-compile-cache.js:178:30
  
  - loader.js:973 Object.Module._extensions..js
    internal/modules/cjs/loader.js:973:10
  
  - loader.js:812 Module.load
    internal/modules/cjs/loader.js:812:32
  
  - loader.js:724 Function.Module._load
    internal/modules/cjs/loader.js:724:14
  
  - loader.js:849 Module.require
    internal/modules/cjs/loader.js:849:19
  
  - v8-compile-cache.js:159 require
    [website-gatsby]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - gatsby-node.js:24 Object.<anonymous>
    [website-gatsby]/[gatsby-plugin-page-creator]/gatsby-node.js:24:26
  
  - v8-compile-cache.js:178 Module._compile
    [website-gatsby]/[v8-compile-cache]/v8-compile-cache.js:178:30
  
  - loader.js:973 Object.Module._extensions..js
    internal/modules/cjs/loader.js:973:10
  
  - loader.js:812 Module.load
    internal/modules/cjs/loader.js:812:32
  
  - loader.js:724 Function.Module._load
    internal/modules/cjs/loader.js:724:14
```

### Steps to reproduce

`gatsby develop`

### Expected result

Should build

### Actual result

Didnt build

### Environment

```
System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 85.0.4183.102
    Edge: 83.0.478.54
    Firefox: 78.0.2
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.24.47 => 2.24.58
    gatsby-image: ^2.4.16 => 2.4.17
    gatsby-plugin-alias-imports: ^1.0 => 1.0.5
    gatsby-plugin-canonical-urls: ^2.3.10 => 2.3.10
    gatsby-plugin-google-tagmanager: ^2.3.11 => 2.3.11
    gatsby-plugin-layout: ^1.3.10 => 1.3.10
    gatsby-plugin-mailchimp: ^5.2.2 => 5.2.2
    gatsby-plugin-manifest: ^2.4.23 => 2.4.28
    gatsby-plugin-netlify: ^2.3.13 => 2.3.14
    gatsby-plugin-offline: ^3.2.23 => 3.2.27
    gatsby-plugin-postcss: ^2.3.11 => 2.3.11
    gatsby-plugin-postcss-sass: ^1.0 => 1.0.22
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10
    gatsby-plugin-react-helmet-canonical-urls: ^1.4.0 => 1.4.0
    gatsby-plugin-robots-txt: ^1.5.1 => 1.5.1
    gatsby-plugin-sass: ^2.3.12 => 2.3.12
    gatsby-plugin-sharp: ^2.6.27 => 2.6.35
    gatsby-plugin-sitemap: ^2.4.11 => 2.4.12
    gatsby-plugin-styled-components: ^3.3.10 => 3.3.10
    gatsby-plugin-transition-link: ^1.17.7 => 1.20.2
    gatsby-remark-prettier: ^1.0 => 1.0.0
    gatsby-remark-prismjs: ^3.5.10 => 3.5.12
    gatsby-source-filesystem: ^2.3.24 => 2.3.29
    gatsby-source-graphql: ^2.7.1 => 2.7.3
    gatsby-transformer-remark: ^2.8.28 => 2.8.34
    gatsby-transformer-sharp: ^2.5.13 => 2.5.14
  npmGlobalPackages:
    gatsby-cli: 2.12.96
    gatsby: 2.17.1
```

**Comment by LekoArts** [comment] 2020-09-15 05:33
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by dagoss** [comment] 2020-09-15 10:38
I also started seeing this issue today after running `npm audit fix`

  System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 85.0.4183.102
    Firefox: 78.0.2
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.24.47 => 2.24.47
    gatsby-background-image: ^1.1.2 => 1.1.2
    gatsby-image: ^2.4.16 => 2.4.16
    gatsby-plugin-catch-links: ^2.3.11 => 2.3.11
    gatsby-plugin-emotion: ^4.3.10 => 4.3.10
    gatsby-plugin-google-analytics: ^2.3.13 => 2.3.13
    gatsby-plugin-manifest: ^2.4.23 => 2.4.23
    gatsby-plugin-offline: ^3.2.23 => 3.2.23
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10
    gatsby-plugin-sharp: ^2.6.27 => 2.6.27
    gatsby-plugin-sitemap: ^2.4.12 => 2.4.12
    gatsby-remark-images: ^3.3.27 => 3.3.27
    gatsby-source-filesystem: ^2.3.24 => 2.3.24
    gatsby-transformer-remark: ^2.8.28 => 2.8.28
    gatsby-transformer-sharp: ^2.5.13 => 2.5.13

**Comment by stefanmos** [comment] 2020-09-15 11:28
Any update on this issue, also started experiencing this after a npm audit fix.

**Comment by Tyrrrz** [comment] 2020-09-15 16:50
Installing `gatsby-telemetry` manually seems to fix the issue. However, not sure if that's desirable.

**Comment by joebentaylor1995** [comment] 2020-09-15 16:56
Just delete node modules and package-lock

Then reinstall.

All fixed

Kind regards,

Joe

**Comment by dagoss** [comment] 2020-09-15 17:25
@joebentaylor1995 doing that fixed the issue for me (needed to delete both node_modules and package-lock, not just node_modules which is what I initially tried)

**Comment by t36campbell** [comment] 2020-09-15 19:25
@joebentaylor1995 fixed this issue for me as well. Thank you

**Comment by LekoArts** [comment] 2020-09-16 05:56
As the original issue was resolved, I'll close this as it doesn't seem to be a bug with Gatsby but your npm installation.

**Closed by LekoArts** 2020-09-16 05:56 UTC
Labels: status: needs reproduction, type: bug

**Comment by rob88** [comment] 2020-10-29 14:22
run the following command in your project directory terminal : - 
npm cache verify 
npm cache clean 
npm audit fix 
npm install 

There might be one or two plugins deprecated in node_module
