### ISSUE TITLE
source and transform nodes never ends for me.

### ISSUE THREAD

**Issue by aman-developer** [gatsbyjs/gatsby#7855] opened 2018-09-04 07:48 UTC
Hello - 

https://github.com/gatsbyjs/gatsby/tree/master/www

I am setting up this directory locally. I am using these 2 commands.

yarn install	-->	it runs successfully
yarn run develop	-->	but it stucks at "source and transform nodes" , it never ends for me. i have been waiting for long hours.

**Comment by aman-developer** [comment] 2018-09-04 09:38
System:
    OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
    CPU: x64 Intel(R) Core(TM) i3-4010U CPU @ 1.70GHz
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 8.11.4 - /usr/bin/node
    Yarn: 1.9.4 - /usr/bin/yarn
    npm: 6.4.1 - /usr/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 61.0.1
  npmPackages:
    gatsby: ^2.0.0-rc.4 => 2.0.0-rc.7 
    gatsby-image: next => 2.0.0-rc.1 
    gatsby-plugin-canonical-urls: next => 2.0.0-rc.1 
    gatsby-plugin-catch-links: next => 2.0.2-rc.1 
    gatsby-plugin-feed: next => 2.0.0-rc.2 
    gatsby-plugin-fullstory: ^1.0.4-5 => 1.0.4-9 
    gatsby-plugin-glamor: next => 2.0.0-rc.1 
    gatsby-plugin-google-analytics: next => 2.0.0-rc.1 
    gatsby-plugin-google-tagmanager: next => 2.0.0-rc.1 
    gatsby-plugin-lodash: next => 3.0.1-rc.1 
    gatsby-plugin-mailchimp: ^2.2.3 => 2.2.3 
    gatsby-plugin-manifest: next => 2.0.2-rc.1 
    gatsby-plugin-netlify: next => 2.0.0-rc.1 
    gatsby-plugin-netlify-cache: ^0.1.0 => 0.1.0 
    gatsby-plugin-nprogress: next => 2.0.0-rc.1 
    gatsby-plugin-offline: ^2.0.0-rc.1 => 2.0.0-rc.2 
    gatsby-plugin-react-helmet: next => 3.0.0-rc.1 
    gatsby-plugin-sharp: ^2.0.0-rc.3 => 2.0.0-rc.3 
    gatsby-plugin-sitemap: next => 2.0.0-rc.1 
    gatsby-plugin-twitter: next => 2.0.0-rc.1 
    gatsby-plugin-typography: next => 2.2.0-rc.3 
    gatsby-remark-autolink-headers: next => 2.0.0-rc.1 
    gatsby-remark-copy-linked-files: next => 2.0.0-rc.1 
    gatsby-remark-images: next => 2.0.1-rc.1 
    gatsby-remark-prismjs: next => 3.0.0-rc.2 
    gatsby-remark-responsive-iframe: next => 2.0.0-rc.1 
    gatsby-remark-smartypants: next => 2.0.0-rc.1 
    gatsby-source-filesystem: ^2.0.1-rc.1 => 2.0.1-rc.1 
    gatsby-source-npm-package-search: next => 2.0.0-rc.1 
    gatsby-transformer-csv: next => 2.0.0-rc.1 
    gatsby-transformer-documentationjs: next => 2.0.0-rc.1 
    gatsby-transformer-remark: next => 2.1.1-rc.1 
    gatsby-transformer-screenshot: next => 2.0.0-rc.1 
    gatsby-transformer-sharp: next => 2.1.1-rc.2 
    gatsby-transformer-yaml: next => 2.1.1-rc.1 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

**Comment by kakadiadarpan** [comment] 2018-09-04 11:04
Thanks @aman-developer, for sharing the environment info. I'm able to reproduce this issue, I let it run for close to 30 minutes and it was still stuck at `source and transform nodes`.

**Comment by pieh** [comment] 2018-09-05 11:54
I think this is same issue as in #6654 , if anyone want to try to work on this please check  https://github.com/gatsbyjs/gatsby/issues/6654#issuecomment-417151538 for context where exactly this could be fixed

**Comment by kakadiadarpan** [comment] 2018-09-05 12:05
Closed in favor of #6654

**Closed by kakadiadarpan** 2018-09-05 12:05 UTC
Labels: status: confirmed, status: inkteam to review, type: bug :beetle:

**Comment by aman-developer** [comment] 2018-09-06 12:30
I can't find any relevant answer. you are closing requests yourself without any confirmation. there is no use to put request again. this happens to me 3rd time. I am going to leave it here. I will look for any other frontend js framework. Thank you for your time.

**Comment by pieh** [comment] 2018-09-06 12:34
This issue was closed because it's duplicate of already opened issue which was already investigated and have pointers were the main problem causing this issue is. Did you read last comments before this issue was closed?

**Comment by aman-developer** [comment] 2018-09-06 12:36
@pieh - yes i had read it. i tried to make changes in code but nothing happen. i am getting same issue. can you please send updated code for this file which will fix this issue ?

/packages/gatsby-source-filesystem/src/create-remote-file-node.js

**Comment by SimonIMG** [comment] 2018-10-12 22:23
Not sure if this helps, but I have one Early 2013 Macbook Pro that runs `gatsby develop` perfectly fine on a V2 Gatsby site with `gatsby-source-wordpress` (roughly 90 pages, one custom post type, lots of ACF fields and over 100 media/images). Connected to a live WP backend.

I pull down the repo to my older, but spec'd out, Mid 2011 iMac and try to run `gatsby develop` and it stops at...

```
⠈ source and transform nodes -> wordpress__wp_users fetched : 3
⠁ source and transform nodesPath: /wp-json/wp/v2/users/me?per_page=100&page=1
The server response was "401 Unauthorized"
Inner exception message: "You are not currently logged in."
⡀ source and transform nodes -> wordpress__wp_comments fetched : 0
⠐ source and transform nodesPath: /wp-json/wp/v2/settings?per_page=100&page=1
The server response was "401 Unauthorized"
Inner exception message: "Sorry, you are not allowed to do that."
⠁ source and transform nodes -> wordpress__acf_options fetched : 1
⠁ source and transform nodes
```

...and it will sit there at this final step and never finish.

I have Docker installed on both Macs, but the iMac tends to struggle a bit with Docker, so I quit Docker on the iMac, quit and restart VS Code and `gatsby develop` completes. I also stop and rerun `gatsby develop` and it works fine.

**So hopefully quitting Docker or some other processor/port hungry app on your computer might help.**

For reference, here are the dependencies in my Gatsby V2 site.

```
"dependencies": {
    "babel-plugin-styled-components": "^1.8.0",
    "bluebird": "^3.5.2",
    "gatsby": "^2.0.21",
    "gatsby-image": "^2.0.13",
    "gatsby-plugin-google-tagmanager": "^2.0.5",
    "gatsby-plugin-manifest": "^2.0.5",
    "gatsby-plugin-offline": "^2.0.6",
    "gatsby-plugin-react-helmet": "^3.0.0",
    "gatsby-plugin-sharp": "^2.0.6",
    "gatsby-plugin-styled-components": "^3.0.0",
    "gatsby-plugin-typography": "^2.2.0",
    "gatsby-source-filesystem": "^2.0.3",
    "gatsby-source-wordpress": "^3.0.4",
    "gatsby-transformer-sharp": "^2.1.3",
    "lodash": "^4.17.11",
    "nuka-carousel": "^4.4.1",
    "prop-types": "^15.6.2",
    "react": "^16.5.2",
    "react-dom": "^16.5.2",
    "react-helmet": "^5.2.0",
    "react-typography": "^0.16.13",
    "slash": "^2.0.0",
    "styled-components": "^3.4.10",
    "typography": "^0.16.17"
  },
```

**Comment by SimonKlausLudwig** [comment] 2021-04-30 15:40
I had to close VSCode with a open SSH Connection. (Blocks many ports as well) 

Thanks @SimonIMG
