### ISSUE TITLE
gatsby-source-filesystem gives depreciation warning on nodejs 12

### ISSUE THREAD

**Issue by erik-am** [gatsbyjs/gatsby#20529] opened 2020-01-10 14:33 UTC
## Description

Calling  `createRemoteFileNode()` in `gatsby-source-filesystem`  results in the following depreciation warning on node 12.

```
(node:94963) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
```

I tried the latest version of `gatsby-source-filesystem`.

The warning is written to STDERR which makes our build pipeline fail.

### Steps to reproduce

1. Make a plugin that calls createRemoteFileNode() to download a remote file for certain nodes.
2. Add a page that requires the node so that the plugin is triggered.
3. Run `gatsby develop` or `gatsby build` to get the depreciation warning.

### Expected result

No depreciation warning.

### Actual result

We get a depreciation warning, which makes our build pipeline fail:

```
(node:94963) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
```

### Environment

```
 System:
    OS: macOS 10.15
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.14.1 - /usr/local/opt/node@12/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/opt/node@12/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.117
    Firefox: 71.0
    Safari: 13.0.2
  npmGlobalPackages:
    gatsby-cli: 2.8.23
    gatsby: 2.13.33

```

**Comment by LekoArts** [comment] 2020-01-13 10:24
Thank you for opening this!

This is a duplicate of #18433 and will be fixed by #18857

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2020-01-13 10:24 UTC
