### ISSUE TITLE
Flash of Content

### ISSUE THREAD

**Issue by timsuchanek** [gatsbyjs/gatsby#1687] opened 2017-08-02 08:40 UTC
At https://www.howtographql.com/ we have the problem of Flash of Content (FoC). With that I mean loading the website the first time, there is a quick flash of white when the page is rendering the first time.

I could already nail it down to serveral components, one of them is [graphiql](https://github.com/graphql/graphiql/), which uses `codemirror` under the hood.

Though, even if I wanted to fix these components, I don't know what the exact problem is.

It smells like the React checksum is not right.

Did anyone experience this kind of problem?
Thanks!

**Comment by KyleAMathews** [comment] 2017-08-02 16:59
Try updating Gatsby to the latest? https://github.com/howtographql/howtographql/blob/083025c29d210a614318d628f60c60fa4be737d3/package.json#L9

I think there was a bug near the end of the betas that you're hitting.

Perhaps :-)

Anyways, try updating and see if the problem still exists.

**Comment by timsuchanek** [comment] 2017-08-02 19:32
Well researched, well researched :)
Going to try that! Had some bad luck with the ts plugin, but will push through it :)

**Comment by sebastienfi** [comment] 2017-08-10 22:00
I'm closing this, please re-open if the problem is still here after the update ;)

**Closed by sebastienfi** 2017-08-10 22:00 UTC

**Comment by thebarty** [comment] 2018-01-24 01:39
Hi guys,

I have to reopen as I am experiencing something similar PLUS looking at https://www.howtographql.com/ I still see the flash appear.

In my case the url is softwarepiloten.de.

Any ideas what to try?

**Comment by KyleAMathews** [comment] 2018-01-24 01:47
@thebarty try opening the Gatsby webpack config at `node_modules/gatsby/dist/utils/webpack.config.js` and disabling uglify and then building your site and seeing what the checksum error says (the error is removed by uglify). This *probably* isn't a Gatsby error but something with your code. Please file a new issue if it does seem like there's something that needs fixed!

**Comment by thebarty** [comment] 2018-01-24 09:26
@KyleAMathews You are quick!

Ok, the results of 2 experiments:
1) I disabled uglify, deployed and still had the same flash
2) The flash shows a huge FontAwesome Icon being rendered full-screen, so I switch from using `@fortawesome/react-fontawesome` (which renders svgs for selected fonts) to the real font via css. The result: The FLASH does NOT appear anymore, so I guess it had to do with some css being loaded too late and resulting in the svg being rendered FULL.

For me you can close the topic, BUT looking at https://www.howtographql.com/ I can actually still see an initial flash, so I guess the original problem still exists

Thanks for your help! And keep up the great work!

**Comment by Batistleman** [comment] 2019-02-13 21:35
Did you manage to solve this? I'm also seeing this... (all icons are loaded on top of eachother on pageload)
