### ISSUE TITLE
404 page is generated twice and do not respect plugins.

### ISSUE THREAD

**Issue by rroslaniec** [gatsbyjs/gatsby#24954] opened 2020-06-12 11:31 UTC
## Description
Docs: https://www.gatsbyjs.org/docs/add-404-page/

According to docs adding 404 is easy:
create 404.js file, and everything is ✨🔮 

But actually it is broken

### Steps to reproduce

prepare custom 404 page (https://github.com/rroslaniec/gatsby-404-problem)
then just:

```
yarn build && yarn serve;
```
In my scenario I adding `thisIsMyExternalScriptUsedEverywhereExcept404` variable to html using custom plugin (gatsby-plugin-external-script). But I don't wanna it on 404 page, so I omits that.

### Expected result

all 404 pages (/404/index.html and /404.html) should have same output.

### Actual result

Right now gatsby do not respect properly plugins in 404 pages:

in /404.html i got `thisIsMyExternalScriptUsedEverywhereExcept404` - wrong behavior.
in /404/index.html variable is not present - correct behavior.

Even I think there is no needs to generate 404 page twice?

### Environment

  System:
    OS: macOS 10.15.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.3 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.97
    Firefox: 75.0
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.22.15 => 2.22.15
    gatsby-image: ^2.4.5 => 2.4.5
    gatsby-plugin-manifest: ^2.4.9 => 2.4.9
    gatsby-plugin-offline: ^3.2.7 => 3.2.7
    gatsby-plugin-react-helmet: ^3.3.2 => 3.3.2
    gatsby-plugin-sharp: ^2.6.9 => 2.6.9
    gatsby-source-filesystem: ^2.3.8 => 2.3.8
    gatsby-transformer-sharp: ^2.5.3 => 2.5.3
  npmGlobalPackages:
    gatsby-cli: 2.12.45

**Comment by LekoArts** [comment] 2020-06-16 07:59
Thank you for opening this!

I don't think our implementation is broken, it's working as intended. Every file in the `src/pages` directory gets created as a `<filename>/index.html` file and thus also the 404 page. As hosting providers also have the convention of serving those pages at `<root>/404.html` we also create that (this is mentioned in the second paragraph of the 404 doc).

You'll need to adapt your custom plugin to catch both paths or make sure which version your host will use.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2020-06-16 07:59 UTC
Labels: type: bug

**Comment by rroslaniec** [comment] 2020-06-16 09:42
Thanks for replying @LekoArts, but I am not able to catch `<root>/404.html` page.
In example repo I console out all pathnames and there is no 404.html path. Output:
```
/404/
/
/page-2/
/using-typescript/
```
So it means that `https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/internal-plugins/prod-404/gatsby-node.js` createPage do not triggers plugins somehow.
