### ISSUE TITLE
Webpack error with gatsby-plugin-react-css-modules

### ISSUE THREAD

**Issue by kmcaloon** [gatsbyjs/gatsby#4152] opened 2018-02-20 22:25 UTC
So everything has been compiling relatively smoothly for my project until I added in gatsby-plugin-react-css-modules.  After adding with yarn I updated gatsby-config.js:

```
    {
      resolve: `gatsby-plugin-react-css-modules`,
      options: {
        filetypes: {
          ".scss": { syntax: `postcss-scss` },
        },
        exclude: `\/global\/`,
      },
    },
```

Now gatsby develop is producing the following error:

```
info bootstrap finished - 3.612 s

[ { keyword: 'additionalProperties',
    dataPath: '',
    schemaPath: '#/additionalProperties',
    params: { additionalProperty: 'libraryName' },
    message: 'should NOT have additional properties' } ]
[ { keyword: 'additionalProperties',
    dataPath: '',
    schemaPath: '#/additionalProperties',
    params: { additionalProperty: 'libraryName' },
    message: 'should NOT have additional properties' } ]
error There was an error compiling the html.js component for the development server.

See our docs page on debugging HTML builds for help https://goo.gl/yL9lND

  38 | 
  39 | var MAYBE_ITERATOR_SYMBOL = typeof Symbol === 'function' && Symbol.iterator;
> 40 | var FAUX_ITERATOR_SYMBOL = '@@iterator';
     | ^
  41 | 
  42 | function getIteratorFn(maybeIterable) {
  43 |   if (maybeIterable === null || typeof maybeIterable === 'undefined') {


  WebpackError: 
  
  - react.development.js?1871:40 PluginPass.Program
    ~/react/cjs/react.development.js?1871:40:1
  
  
  
  
  - develop-static-entry.js?2502:33 NodePath.visit
    .cache/develop-static-entry.js?2502:33:9
  
  
  
  
  - develop-static-entry.js?2502:42 Function.traverse.node
    .cache/develop-static-entry.js?2502:42:5
  
  - develop-static-entry.js?2502:7 traverse
    .cache/develop-static-entry.js?2502:7:5
  
  - react.development.js?1871:384 File.transform
    ~/react/cjs/react.development.js?1871:384:4
  
  
  - develop-static-entry.js?2502:7 
    .cache/develop-static-entry.js?2502:7:1
  
  - react.development.js?1871:273 FSReqWrap.readFileAfterOpen [as oncomplete]
    ~/react/cjs/react.development.js?1871:273:1
```

Not really sure where to start here. As soon as I remove the plugin from the config everything goes back to compiling smoothly. Any thoughts?

**Comment by pieh** [comment] 2018-02-21 00:15
This show similar error to one in https://github.com/gatsbyjs/gatsby/issues/2772 - something is adding `libraryName` property to options passed to `babel-plugin-react-css-modules` just not sure what that could be - can you provide sample repo? Default gatsby starter after adding just that plugin doesn't show reproduce this problem.

**Comment by kmcaloon** [comment] 2018-02-22 03:27
Thanks.  Here is the repo https://github.com/kmcaloon/engineering-guidelines

You'll see I used the official netlify cms starter. Haven't really done a whole lot since initial install.

**Comment by m-allanson** [comment] 2018-02-27 17:51
It looks like `gatsby-plugin-antd` is what's triggering the error in `gatsby-plugin-react-modules`. They're both modifying the babel config:

https://github.com/bskimball/gatsby-plugin-antd/blob/master/src/gatsby-node.js
https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-react-css-modules/src/gatsby-node.js

**Comment by KyleAMathews** [comment] 2018-09-08 04:15
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Closed by KyleAMathews** 2018-09-08 04:15 UTC
