### ISSUE TITLE
ANSI colors break gatsby develop output on Linux

### ISSUE THREAD

**Issue by Mithgarthsormr** [gatsbyjs/gatsby#29293] opened 2021-02-01 17:07 UTC
Hello,
I've got a problem with gatsby develop. In November it worked properly but now the output on the console seems wrong (as you see on the screenshot). 
![Bildschirmfoto von 2021-02-01 17-57-36](https://user-images.githubusercontent.com/60277471/106491614-5868fb80-64b7-11eb-85a7-8ca413cf60e3.png)

Steps to reproduce:
1. Set up a new gatsby page, I've used this instruction to make sure the page is minimal: https://www.gatsbyjs.com/docs/using-gatsby-professionally/setting-up-gatsby-without-gatsby-new/
2. try gatsby develop, it will work this time
3. Add a minimal gatsby-config.js file like this:
**module.exports = {
    plugins: [
    ],
}**
4. try gatsby develop again, the outcome should be the same as on the screenshot.

The development mode itself does work, but the logging on the console doesn't.

By the way, I'm working on Ubuntu 20.04 if this makes a difference.

edit:
Using an existing git repo seems to trigger this issue, too. Without the git repo it now seems to work after updating **gatsby-cli**, But after I clone a git repo it doesn't.

**Comment by ishan-biztech** [comment] 2021-02-02 10:09
Same issue with me. I'm converting an application from create-react-app to gatsby, but seems like output is not showing in console, whereas when navigating to http://localhost:8000/, the site works fine.

![gatsby-console-output-not-showing](https://user-images.githubusercontent.com/61005017/106584958-d3d8b480-656c-11eb-9f08-3304873d8be6.png)

 In addition, there's also few 404 errors showing in console "GET http://localhost:8000/page-data/404.html/page-data.json"

**Comment by LekoArts** [comment] 2021-02-03 09:40
I can't reproduce this on my terminals on Windows, WSL or Mac. If you use the mouse to highlight text, do you see any text?

![2021_02_03_233e316b](https://user-images.githubusercontent.com/16143594/106727912-3cc33980-660c-11eb-8a8b-76ffd043162e.gif)

Maybe your CLI colors are set up incorrectly. Anyways, we'll need more information on how to reproduce this.

**Comment by Mithgarthsormr** [comment] 2021-02-03 09:51
Nope, still nothing.
![gatsby_screenshot](https://user-images.githubusercontent.com/60277471/106729438-c293b480-660d-11eb-8cb8-aab75faaf613.png)

**Comment by ascorbic** [comment] 2021-02-11 11:32
Could you try disabling colors like so:

```bash
FORCE_COLOR=0 gatsby develop
```

**Comment by ishan-biztech** [comment] 2021-02-11 11:38
Thanks @ascorbic, that worked for me. Do you know the issue? Will it be fixed in next release?

**Comment by Mithgarthsormr** [comment] 2021-02-11 11:41
@asorbic: Thanks a lot, this worked for me, too!

**Comment by ascorbic** [comment] 2021-02-11 11:42
Great! No, this isn't a known issue, so we would need to work out the cause. Could you both share details of your platform, terminal etc and if you have cusotm terminal fonts for example

**Comment by Mithgarthsormr** [comment] 2021-02-11 11:48
This is the current project I'm working on, but the problem happened with much less packages. With an older git repo combined with a new gatsby page, it happened even with an empty gatsby-config.js file.

  System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    npm: 6.14.11 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Browsers:
    Firefox: 85.0.1
  npmPackages:
    gatsby: ^2.32.3 => 2.32.3
    gatsby-image: ^2.11.0 => 2.11.0
    gatsby-plugin-manifest: ^2.12.0 => 2.12.0
    gatsby-plugin-material-ui: ^2.1.10 => 2.1.10
    gatsby-plugin-matomo: ^0.9.0 => 0.9.0
    gatsby-plugin-mdx: ^1.10.0 => 1.10.0
    gatsby-plugin-offline: ^3.10.0 => 3.10.0
    gatsby-plugin-page-creator: ^2.10.0 => 2.10.0
    gatsby-plugin-react-helmet: ^3.10.0 => 3.10.0
    gatsby-plugin-sass: ^3.2.0 => 3.2.0
    gatsby-plugin-sharp: ^2.14.1 => 2.14.1
    gatsby-source-filesystem: ^2.11.0 => 2.11.0
    gatsby-transformer-sharp: ^2.12.0 => 2.12.0
  npmGlobalPackages:
    gatsby-cli: 2.19.1
    gatsby: 2.31.1

**Comment by aaronkai** [comment] 2021-02-11 20:57
I'm seeing this error as well. 

I'm not in ubuntu, but Fedora 33. Regular gterm terminal. I am using oh-my-zsh and custom terminal font MesloLGS NF with zsh theme ZSH_THEME="powerlevel10k/powerlevel10k"

Running FORCE_COLOR=0 gatsby develop worked for me.

**Comment by pieh** [comment] 2021-02-11 22:10
I could repro on ubuntu in virtual machine:
![Screenshot 2021-02-11 at 22 52 04](https://user-images.githubusercontent.com/419821/107704786-1cefdd80-6cbe-11eb-96c5-a2ddc85c28d5.png)

As a temporary workaround you can use `GATSBY_LOGGER=yurnalist gatsby develop` (that logger seem unaffected):
![Screenshot 2021-02-11 at 22 52 22](https://user-images.githubusercontent.com/419821/107704846-2e38ea00-6cbe-11eb-99f6-0f6bf142350b.png)

It seems to be caused by usage of `terminal-link` here in combination with our default logger (`ink`) https://github.com/gatsbyjs/gatsby/blob/4638cd678b28f7a515df465be21d9d8bcdd71d9a/packages/gatsby/src/utils/handle-flags.ts#L136

**Closed** 2021-02-12 11:12 UTC
Labels: status: confirmed, topic: cli, type: bug

**Comment by Mithgarthsormr** [comment] 2021-02-12 11:15
@pieh: Thanks a lot! This should do until the bug is fixed!

**Comment by ascorbic** [comment] 2021-02-19 09:02
Fixed in `gatsby@2.32.4`
