### ISSUE TITLE
Loading (Static Query)

### ISSUE THREAD

**Issue by rzubrycki** [gatsbyjs/gatsby#27872] opened 2020-11-06 12:18 UTC
## Description

When 'gatsby develop' i see white screen in the browser with 'Loading (Static Query)' text.

### Expected result

Page load.

### Actual result

White screen with Loading (Static Query).

### Environment

  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.183
    Firefox: 79.0
    Safari: 14.0
  npmPackages:
    gatsby: ^2.25.3 => 2.25.3
    gatsby-alias-imports: ^1.0.6 => 1.0.6
    gatsby-background-image: ^1.1.2 => 1.1.2
    gatsby-image: ^2.4.21 => 2.4.21
    gatsby-plugin-google-analytics: ^2.4.0 => 2.4.0
    gatsby-plugin-intl: ^0.3.3 => 0.3.3
    gatsby-plugin-manifest: ^2.5.2 => 2.5.2
    gatsby-plugin-offline: ^3.3.2 => 3.3.2
    gatsby-plugin-purgecss: ^5.0.0 => 5.0.0
    gatsby-plugin-robots-txt: ^1.5.3 => 1.5.3
    gatsby-plugin-sass: ^2.4.2 => 2.4.2
    gatsby-plugin-sharp: ^2.7.1 => 2.7.1
    gatsby-plugin-sitemap: ^2.5.0 => 2.5.0
    gatsby-plugin-styled-components: ^3.3.14 => 3.3.14
    gatsby-remark-emoji: 0.0.3 => 0.0.3
    gatsby-source-filesystem: ^2.4.1 => 2.4.1
    gatsby-transformer-remark: ^2.9.2 => 2.9.2
    gatsby-transformer-sharp: ^2.5.21 => 2.5.21
  npmGlobalPackages:
    gatsby-cli: 2.9.0

I've tried to clear cache, re-install dependencies. No success.

**Comment by vladar** [comment] 2020-11-06 12:41
Hi @rzubrycki !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by rzubrycki** [comment] 2020-11-06 12:45
@vladar I can't share the code base, unfortunately. Everything was working fine, until I update gatsby and other dependencies.

**Comment by rzubrycki** [comment] 2020-11-06 13:26
fun fuct, reverting to previous commit didn't help lol, still got the same white screen even with older version - they worked yesterday

**Comment by LekoArts** [comment] 2020-11-16 07:03
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-11-16 07:03 UTC
Labels: status: needs reproduction, topic: StaticQuery, type: bug

**Comment by amboton1** [comment] 2021-02-15 13:50
This is still an issue for me also.

**Comment by amboton1** [comment] 2021-02-15 13:53
@rzubrycki Did you resolve the problem?
