### ISSUE TITLE
Support new graphql major (15)

### ISSUE THREAD

**Issue by adrienharnay** [gatsbyjs/gatsby#25906] opened 2020-07-21 09:36 UTC
## Description

[graphql 15](https://github.com/graphql/graphql-js/releases/tag/v15.0.0) has been out for a while now (3.5 months), and some libs are starting to upgrade. As a result, today I got this error message:

```
 Error: Cannot use GraphQLDirective "@cacheControl" from another module or realm.
  Ensure that there is only one instance of "graphql" in the node_modules
  directory. If different versions of "graphql" are the dependencies of other
  relied on modules, use "resolutions" to ensure only one version is installed.
  https://yarnpkg.com/en/docs/selective-version-resolutions
  Duplicate "graphql" modules cannot be used at the same time since different
  versions may have different capabilities and behavior. The data from one
  version used in the function from another could produce confusing and
  spurious results.
```

Pinning graphql to 15.3.0 in resolutions makes gatsby crash when running `gatsby develop`.

### Steps to reproduce

Run any gatsby projet with resolutions set to 15.3.0 for graphql.

### Expected result

Gatsby should support the latest graphql major.

### Actual result

Error on build.

### Environment

```
  System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.4.0 - /var/folders/mt/71kkzssd3fq24s3x3y6wpc4h0000gn/T/yarn--1595324137736-0.6757048113533806/node
    Yarn: 1.22.4 - /var/folders/mt/71kkzssd3fq24s3x3y6wpc4h0000gn/T/yarn--1595324137736-0.6757048113533806/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 84.0.4147.89
    Firefox: 72.0.2
    Safari: 13.1.1

```

Thanks in advance!

**Comment by aaronadamsCA** [comment] 2020-10-12 17:48
`graphql-js` version 15 has a lot of new features, one of which—interfaces that implement other interfaces—is nice to have when writing Gatsby GraphQL, since it lets you do `interface Foo implements Node`.

**Comment by vladar** [comment] 2020-10-13 09:29
Yup, GraphQL has so many aspects in Gatsby that I think we will bump it with the next Gatsby major.

**Comment by usmanbinnaeem** [comment] 2020-12-26 15:26
@adrienharnay did you get solution

**Comment by adrienharnay** [comment] 2020-12-27 11:20
@usmanbinnaeem hey, I've kind of stopped using Gatsby altogether so not really, sorry 😕

**Comment by usmanbinnaeem** [comment] 2020-12-31 11:02
@adrienharnay hi, no problem,  my error got removed

**Comment by openscript** [comment] 2021-01-05 15:31
> @adrienharnay hi, no problem, my error got removed

So Gatsby is compatible with GraphQL 15 and greater?

**Comment by MMMalik** [comment] 2021-02-08 14:50
> > @adrienharnay hi, no problem, my error got removed
> 
> So Gatsby is compatible with GraphQL 15 and greater?

No, it's not from what I can see. 

This is quite problematic for me since I'm working in a monorepo with `yarn` workspaces and `lerna`. The problem is that my headless CMS (KeystoneJS) won't accept anything less than `graphql@^15.x` and `gatsby` won't accept anything higher than `graphql@^14.x`. The amount of work I have to put in in order to make `multiple instances of graphql` error go away is insane... With heavy use of yarn's `nohoist` feature I am able to bypass that error but it would be much easier if `gatsby` allowed me to just use yarn `resolutions` and have a fixed `graphql@^15.x`. At this moment I'm starting to question my monorepo setup.

From what I can see [here](https://github.com/gatsbyjs/gatsby/blob/0a25e3f3f98253ffecc06dc3e9a69a87497e4f52/packages/gatsby/package.json#L93) even the next major `gatsby` v3 is still depending on `graphql@^14.6.0` 👎.

**Comment by vladar** [comment] 2021-02-08 16:31
GraphQL bump is ready to get merged via https://github.com/gatsbyjs/gatsby/pull/29090 . It will be released as a part of Gatsby v3.

**Closed** 2021-02-09 10:08 UTC
Labels: topic: GraphQL, type: bug
