### ISSUE TITLE
404 on docs/node-apis/ for source code

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#25206] opened 2020-06-22 16:15 UTC
## Description

404 Error on docs/node-apis/ for source code

### Steps to reproduce

- open https://www.gatsbyjs.org/docs/node-apis/#onCreateWebpackConfig
- click on any source link 

### Expected result

- show source code on github

### Actual result

- 404 for all Source links:

### Related Code

www/src/components/api-reference/doc-block.js

### Related Issues

**Comment by LekoArts** [comment] 2020-06-22 16:25
This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/24914

**Closed by LekoArts** 2020-06-22 16:25 UTC
Labels: type: bug

**Comment by muescha** [comment] 2020-06-22 16:30
oh yes - i searched for this in issues and pr and did not found them :(
