### ISSUE TITLE
react-plugin-offline I got Browser console warning: The resource https://www.example.com/static/d/520/path---offline-plugin-app-shell-fallback-a-30-c5a-NZuapzHg3X9TaN1iIixfv1W23E.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

### ISSUE THREAD

**Issue by JustFly1984** [gatsbyjs/gatsby#10672] opened 2018-12-26 21:40 UTC
## Description
using react-plugin-offline I got Browser console warning: `The resource https://www.example.com/static/d/520/path---offline-plugin-app-shell-fallback-a-30-c5a-NZuapzHg3X9TaN1iIixfv1W23E.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

### Expected result

No browser warning

Browser warning:
The resource https://www.example.com/static/d/520/path---offline-plugin-app-shell-fallback-a-30-c5a-NZuapzHg3X9TaN1iIixfv1W23E.json was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.

### Environment

  System:
    OS: macOS 10.14.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.4.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.5.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 63.0.3
    Safari: 12.0.1
  npmPackages:
    gatsby: 2.0.75 => 2.0.75
    gatsby-plugin-google-gtag: 1.0.8 => 1.0.8
    gatsby-plugin-google-tagmanager: 2.0.7 => 2.0.7
    gatsby-plugin-lodash: 3.0.3 => 3.0.3
    gatsby-plugin-manifest: 2.0.12 => 2.0.12
    gatsby-plugin-offline: 2.0.20 => 2.0.20
    gatsby-plugin-purgecss: 2.4.0 => 2.4.0
    gatsby-plugin-react-helmet: 3.0.5 => 3.0.5
    gatsby-plugin-sitemap: 2.0.3 => 2.0.3
    gatsby-plugin-sri: 1.0.4 => 1.0.4
    gatsby-plugin-webpack-bundle-analyzer: 1.0.3 => 1.0.3
  npmGlobalPackages:
    gatsby-cli: 2.4.6
    gatsby: 2.0.66

**Comment by jgierer12** [comment] 2018-12-26 23:11
Thank you for opening an issue! I'm closing this as it's a duplicate of #7713, please continue discussion of this warning there.

**Closed by jgierer12** 2018-12-26 23:11 UTC
