### ISSUE TITLE
Generating development JavaScript bundle failed  Can't resolve 'module' in '.../node_modules/@babel/standalone'

### ISSUE THREAD

**Issue by BBSQQ** [gatsbyjs/gatsby#29756] opened 2021-02-25 03:50 UTC
Throw error when I upgrade @babel/standalone from 7.12.6 to 7.13.6.
![image](https://user-images.githubusercontent.com/35586469/109100230-785ea880-775f-11eb-8b56-3e5e397465b9.png)

My gatsby version is upper then 2.32.3.

**Comment by LekoArts** [comment] 2021-02-25 09:00
Hello! We have an issue template for a reason, please fill it out (including a minimal reproduction). Thanks!

```
<!--
  Please fill out each section below, otherwise, your issue will be closed. This info allows Gatsby maintainers to diagnose (and fix!) your issue as quickly as possible.

  Useful Links:
  - Documentation: https://www.gatsbyjs.com/docs/
  - How to File an Issue: https://www.gatsbyjs.com/contributing/how-to-file-an-issue/

  Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
-->

## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```

**Comment by LekoArts** [comment] 2021-03-04 09:15
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-03-04 09:15 UTC
Labels: status: needs reproduction, type: bug
