### ISSUE TITLE
Recent change silently makes environment variables `undefined`

### ISSUE THREAD

**Issue by j127** [gatsbyjs/gatsby#36528] opened 2022-09-03 21:30 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

This valid JavaScript was working in Gatsby components until a couple of weeks ago:

```
const { GATSBY_MY_VAR } = process.env;
```

It now silently fails as `undefined` and only works with this syntax:

```
const GATSBY_MY_VAR = process.env.GATSBY_MY_VAR;
```

### Reproduction Link

https://github.com/j127/gatsby-bug

### Steps to Reproduce

1. Clone the repo.
2. Run `npm i`
3. Run `npm run build`
4. Check out the error in the terminal.
5. Check [here](https://github.com/j127/gatsby-bug/blob/main/src/pages/index.tsx#L5) to see the code.

### Expected Result

`const { GATSBY_MY_VAR } = process.env;` should load the environment variable.

### Actual Result

The variable is `undefined`.

### Environment

```shell
System:
    OS: macOS 12.5.1
    CPU: (10) arm64 Apple M1 Max
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.15.1/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Languages:
    Python: 3.10.2 - /Users/username/.pyenv/shims/python
  Browsers:
    Firefox: 104.0.1
    Safari: 15.6.1
  npmPackages:
    gatsby: ^4.22.0 => 4.22.0
```
```


### Config Flags

_No response_

**Comment by KyleAMathews** [comment] 2022-09-04 05:56
Do you know what version this last worked on? Thanks for the reproduction!

**Comment by marvinjude** [comment] 2022-09-05 10:45
Hi @j127,

Seem to me that this has always been the case even before `4.16.0`. I tested `4.15` through `4.22` and the behaviour is the same. 

I'll close this for now. Feel free to reopen if you feel otherwise

**Closed by marvinjude** 2022-09-05 10:45 UTC
Labels: type: bug, status: triage needed

**Comment by j127** [comment] 2022-09-05 18:02
Strange. I'm not sure what is going on, because this code was working until August 16th (on Gatsby 4.16.0), but stopped working as soon as it was updated. I can even go back to 2021 and it was successfully making API requests when loading the environment variable this:

```const { GATSBY_API_KEY } = process.env;```

I tried that bug repo with `4.16.0` and am getting a `_gatsbyScript.PartytownContext is undefined` for some reason, so I'll leave it for now.

**Comment by marvinjude** [comment] 2022-09-06 14:41
> I tried that bug repo with 4.16.0 and am getting a _gatsbyScript.PartytownContext is undefined for some reason, so I'll leave it.

You are seeing this error because your project has a newer version of `gatsby-script` which no longer has `PartytownContext`.  As a workaround, to enable you to test older versions you'd want to pin the "gatsby-script" version(with [resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/)) and force install dependencies. 

We've made the change that wouldn't make `const { GATSBY_API_KEY } = process.env` possible since **2018** so It's hard to tell why you were able to do this in a recent version. 

I'm happy to follow up on this if you find anything.

**Comment by j127** [comment] 2022-09-06 19:20
> We've made the change that wouldn't make const { GATSBY_API_KEY } = process.env possible since 2018 so It's hard to tell why you were able to do this in a recent version.

It's strange, because that syntax was definitely working on my site until August 16th. I can't see any way that people could have used that API without that API key loading. The moment it became `undefined`, the API calls stopped working until I changed that line.

I'll post back here if I ever find the answer. It might be worth fixing anyway, because there are no warnings about why valid JS is failing. If a user sees that `const { GATSBY_API_KEY } = process.env` is failing to load the variable, they probably aren't going to intuitively think that `const GATSBY_API_KEY = process.env.GATSBY_API_KEY` would be the solution.

**Comment by schmod** [comment] 2022-12-16 01:33
For us, this appears to have regressed from 4.14.1 to 4.15.0
