### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by vsolanogo** [gatsbyjs/gatsby#25327] opened 2020-06-26 13:49 UTC
it's probably because of some updated npm packages, but i cant detect which one 

## Description

success Rewriting compilation hashes - 0.007s
failed Building static HTML for pages - 16.059s

 ERROR #95313

Building static HTML failed

See our docs page for more info on this error: https://gatsby.dev/debug-html

  WebpackError: ReferenceError: self is not defined

  - build-html.js:107 doBuildPages
    [my-default-starter]/[gatsby]/dist/commands/build-html.js:107:24

  - build-html.js:121 async buildHTML
    [my-default-starter]/[gatsby]/dist/commands/build-html.js:121:3

  - build.js:219 async build
    [my-default-starter]/[gatsby]/dist/commands/build.js:219:5

not finished Generating image thumbnails - 175.794s

### Environment

  System:
    OS: Windows 10 10.0.19041
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
  Binaries:
    Node: 12.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.19041.1.0
  npmPackages:
    gatsby: ^2.23.11 => 2.23.11
    gatsby-image: ^2.4.9 => 2.4.9
    gatsby-node-helpers: ^0.3.0 => 0.3.0
    gatsby-plugin-emotion: ^4.3.6 => 4.3.6
    gatsby-plugin-google-analytics: ^2.3.6 => 2.3.6
    gatsby-plugin-google-tagmanager: ^2.3.7 => 2.3.7
    gatsby-plugin-manifest: ^2.4.14 => 2.4.14
    gatsby-plugin-offline: ^3.1.2 => 3.2.1
    gatsby-plugin-react-helmet: ^3.3.4 => 3.3.4
    gatsby-plugin-sharp: ^2.6.14 => 2.6.14
    gatsby-plugin-sitemap: ^2.4.7 => 2.4.7
    gatsby-plugin-webfonts: ^1.1.2 => 1.1.2
    gatsby-source-filesystem: ^2.2.2 => 2.3.1
    gatsby-transformer-remark: ^2.7.1 => 2.8.7
    gatsby-transformer-sharp: ^2.5.7 => 2.5.7
  npmGlobalPackages:
    gatsby-cli: 2.12.51

**Comment by insuusvenerati** [comment] 2020-06-27 02:45
Got a way to clone your project and reproduce the error? Unfortunately there really is no way to help with an error like that without at least the rekey source code.

**Comment by vsolanogo** [comment] 2020-06-27 02:57
> Got a way to clone your project and reproduce the error? Unfortunately there really is no way to help with an error like that without at least the relevant source code.

it's pretty big private project

**Comment by insuusvenerati** [comment] 2020-06-27 03:09
I’m afraid you won’t find much help with this type of error without a way to reproduce it or at least specific information about it. 

Good luck

**Comment by blainekasten** [comment] 2020-06-29 14:47
Yeah, there isn't much to offer for advice here. However, the stack trace you have also is extremely poor because of a recent regression we had in our stack traces. I'm working on fixing. Once we publish a fix, an update to the new version should give you better insight to where the problem is occurring.

**Comment by vsolanogo** [comment] 2020-06-29 16:15
it happened after i updated from these: 
"gatsby": "^2.20.29",
"gatsby-image": "^2.4.7",
"gatsby-plugin-emotion": "^4.3.4",
"gatsby-plugin-google-analytics": "^2.2.2",
"gatsby-plugin-google-tagmanager": "^2.2.1",
"gatsby-plugin-manifest": "^2.3.3",
"gatsby-plugin-sharp": "^2.5.4",
"gatsby-plugin-sitemap": "^2.3.1",
`"gatsby-transformer-sharp": "^2.4.4",`
"moment-timezone": "^0.5.28",`
`"react-helmet": "^6.0.0",`

to these: 
"gatsby": "^2.23.11",
"gatsby-image": "^2.4.9",
 "gatsby-plugin-emotion": "^4.3.6",
"gatsby-plugin-google-analytics": "^2.3.6",
"gatsby-plugin-google-tagmanager": "^2.3.7",
"gatsby-plugin-manifest": "^2.4.14",
"gatsby-plugin-sharp": "^2.6.14",
"gatsby-plugin-sitemap": "^2.4.7",
`"gatsby-transformer-sharp": "^2.5.7",`
`"moment-timezone": "^0.5.31",`
`"react-helmet": "^6.1.0",`

i've tried to figure out after what package update it throws error with npm install step by step and then running  gatsby build, but it behaves weird, it started throwing erorr after last packege update but after i tried to downgrade it back it throwed error anyway

**Comment by blainekasten** [comment] 2020-06-29 18:49
Try updating to `gatsby@3.23.12` and you should get a better error message to help you figure it out. I'm going to close the issue because this should get you moving in the right direction. If you can't figure it out, even after the update, please ping back in here and I'd be happy to help you out!

**Closed by blainekasten** 2020-06-29 18:49 UTC
Labels: status: triage needed, type: bug
