### ISSUE TITLE
gatsby-plugin-layout not working in production

### ISSUE THREAD

**Issue by grantmac** [gatsbyjs/gatsby#11712] opened 2019-02-12 14:00 UTC
I've got gatsby-plugin-layout working great in development, but as soon as I deploy it stops working and the components within the layout.js remount on every url change.

Any ideas? Thanks

**Comment by DSchau** [comment] 2019-02-12 14:01
Hi Grant!

Could you reproduce this? A small reproduction demonstrating the issue would be super helpful in helping us understand and fix any potential problems!

**Comment by grantmac** [comment] 2019-02-12 14:06
Sure:
What happens (and is expected) on gatsby develop: https://www.youtube.com/watch?v=qKIdPDHRF6U&feature=youtu.be

When it's deployed: http://neu-test-mainsite.s3-website.eu-west-2.amazonaws.com/

I'm using { connect } from 'react-redux' to hold state.

Thank you

**Comment by grantmac** [comment] 2019-02-12 14:08
Layout.js
![screenshot 2019-02-12 at 14 08 06](https://user-images.githubusercontent.com/3330598/52640963-b584d480-2ecf-11e9-88eb-40a0a8ba96b7.png)

**Comment by grantmac** [comment] 2019-02-12 14:09
layout.js:

![screenshot 2019-02-12 at 14 09 06](https://user-images.githubusercontent.com/3330598/52640994-c7667780-2ecf-11e9-8118-47414387fd1b.png)

**Comment by DSchau** [comment] 2019-02-12 14:11
By reproduction I meant Github repo or some way to share your underlying code. Would you be OK sharing any of that?

That being said--appreciate the screenshots and demo site, they're helpful thank you!

First (simple) solution may be to just update Gatsby. You're on `2.0.67` and I know there was a change to client-routing to ensure that the location pathname was the "key" so that re-mounts wouldn't occur.

**Comment by grantmac** [comment] 2019-02-12 14:21
No luck.

https://github.com/grantmac/gatsby-layout-issue

**Comment by DSchau** [comment] 2019-02-12 14:37
@grantmac I think it's the custom `html.js` that is causing a re-mount.

I removed that component, and it seems like it works just fine, correct?

_Note: you also had a casing issue in src/pages/index.js--it should import `intro` not `Intro`_

https://elegant-tesla-3765e9.netlify.com/

**Comment by grantmac** [comment] 2019-02-12 14:46
thank you @DSchau - that does fix it!

Is there anyway i can also use a custom html.js?

**Comment by DSchau** [comment] 2019-02-12 14:52
@grantmac better question is why you need a custom html.js? It looks like you were just importing an animation library from a CDN?

You could use `gatsby-ssr` APIs to import the library if you prefer, e.g. using [`onRenderBody`](https://www.gatsbyjs.org/docs/ssr-apis/#onRenderBody) and the `setHeadComponents` (as you currently have the library in the head tags) or `setPostBodyComponents` as well--probably better as it's not blocking the render of html that way.

Going to close this as answered--but please feel free to continue the discussion if we can help further!

**Closed by DSchau** 2019-02-12 14:52 UTC
Labels: status: needs reproduction
