### ISSUE TITLE
onCreatePage is not triggered

### ISSUE THREAD

**Issue by maheshkumar2150** [gatsbyjs/gatsby#17498] opened 2019-09-09 03:43 UTC
I have created 10 pages with the help of gatsby-node.js 

```
`createPage({
            path: '${edge.node.id}/${edge.node.link}/',
            component: path.resolve(`./src/templates/custome.js`),
            context: {
                slug: edge.node,
            },
        });`
```

> 15 pages                                                                                                       gatsby-starter-default

I have fifteen pages now.

in gatsby-node.js

i added the following code.

```
`exports.onCreatePage = async ({ page, actions }) => {
    const { createPage } = actions;    
    console.log('page', page);
}`
```

In console, 

{ internalComponentName: 'ComponentDev404Page',
  path: '/dev-404-page/',
....

 { internalComponentName: 'Component404',
  path: '/404/',
.....

{ internalComponentName: 'ComponentIndex',
  path: '/',
.....

{ internalComponentName: 'ComponentPage2',
  path: '/page-2/',
....

{ internalComponentName: 'Component404Html',
  path: '/404.html',
.....

{ internalComponentName: 'Component404',
  path: '/404/',
  matchPath: undefined,
.....

{ internalComponentName: 'ComponentIndex',
  path: '/',
.....

{ internalComponentName: 'ComponentPage2',
  path: '/page-2/',
.....

I found these pages only.

*) Where are the pages i created pragmatically? 

**Additional Question.**

`createPage({
            path: `${edge.node.id}/${edge.node.link}/`,`

I also want 

`createPage({
            path: `${edge.node.id}/${edge.node.link}/[any string]`,`

How do i achieve this?

My app is designed in create react app and i use Reach Router

> 
```
> <Component path="dashboard/" />
> <Component path="dashboard/:id" />
```

I want the similar thing in gatsby.
I am just converting the app to gatsby because meta tags are not recognized by facebook, twitter.

**Comment by maheshkumar2150** [comment] 2019-09-09 08:12
Is this really a bug or am i making any mistake?
I think gatsby is not stable yet.

I have to stick with create react app.

**Comment by jonniebigodes** [comment] 2019-09-09 08:24
If you don't mind waiting a bit i'll create a reproduction based on what you need And a detailed explanation on how to achieve it, do you mind waiting a bit longer?

**Comment by maheshkumar2150** [comment] 2019-09-09 09:01
Sure.
I want to stick with gatsby in my future works. It is easy and beautiful. 
Thank you for looking at this issue and helping

**Comment by LekoArts** [comment] 2019-09-09 09:15
What's your usecase for the `onCreatePage` API? So what do you want to achieve?

You can create client-only pages this way: https://www.gatsbyjs.org/docs/client-only-routes-and-user-authentication/

**Comment by maheshkumar2150** [comment] 2019-09-09 09:28
```
exports.onCreatePage = async ({ page, actions }) => {
  const { createPage } = actions
  // page.matchPath is a special key that's used for matching pages
  // only on the client.
  if (page.path.match(/^\/app/)) {
    page.matchPath = "/app/*"
    // Update the page.
    createPage(page)
  }
}
```

I would like to have similar setup for my different links.

But i have these in my gatsby-node.js
```
exports.onCreatePage = async ({ page, actions }) => {
    const { createPage } = actions;    
    console.log('page', page);
}
```

It does not print the pages which i created using 

```
createPage({
            path: '${edge.node.id}/${edge.node.link}/',
            component: path.resolve(`./src/templates/custome.js`),
            context: {
                slug: edge.node,
            },
        });
```

So how can i have 

```
page.matchPath = "/app/*"
    // Update the page.
    createPage(page)

```

to 

```
page.matchPath = "/\/[0-9]+\/[a-zA-Z0-9\-]+/*" //something like this
    // Update the page.
    createPage(page)
```

**Comment by pieh** [comment] 2019-09-09 12:09
We have mechanism in Gatsby to prevent calling `onCreatePage` for pages created by the same gatsby-node.js to avoid infinite loops/callback

Most common use case for `onCreatePage` is something like:
```js
exports.onCreatePage = async ({ page, actions }) => {
  const { createPage } = actions
  // page.matchPath is a special key that's used for matching pages
  // only on the client.
  if (page.path.match(/^\/app/)) {
    page.matchPath = "/app/*"
    // Update the page.
    createPage(page)
  }
}
```

which would actually cause infinite loop if we didn't have that (as `createPage` call would trigger another `onCreatePage` and so on - that's because user checks just `page.path.match` which would always be satisfied and nothing would break the loop).

It's not perfect solution, because it can cause confusion (like in the case of this issue).

If you are interested in diving in the code that does it - check https://github.com/gatsbyjs/gatsby/blob/ad749575599d14d2ecb572cff2e6932aa4ab9e72/packages/gatsby/src/utils/api-runner-node.js#L250-L257 (as starting point)

**Comment by pieh** [comment] 2019-09-09 12:15
Following up on my previous comment - we are open for better mechanism to avoid infinite loops. First idea that comes to mind is instead of just not calling `onCreatePage` for same gatsby-node file, is to check if new page is already exactly the same as one we already have and short circuit then - but it might not be as straight forward - implication of such change need to be researched

**Comment by maheshkumar2150** [comment] 2019-09-09 12:39
I understand the point you mentioned. You are right. I thought that was a bug. We can't call onCreatePage for gatsby-node.js createpages. 

```
exports.onCreatePage = async ({ page, actions }) => {
  const { createPage } = actions
  // page.matchPath is a special key that's used for matching pages
  // only on the client.
  if (page.path.match(/^\/app/)) {
    page.matchPath = "/app/*"
    // Update the page.
    createPage(page)
  }
}
```

Can we match index.js here? So i can create the custom reach router routes on the index page itself.

**Comment by pieh** [comment] 2019-09-09 13:10
We do something like this for index page in https://github.com/gatsbyjs/gatsby/blob/master/examples/client-only-paths/gatsby-node.js which seems to be working ( https://client-only-paths.netlify.com/ )

**Comment by pieh** [comment] 2019-09-09 13:12
I think regex you use might be not valid, using `/^\//` seems to work tho

**Comment by maheshkumar2150** [comment] 2019-09-09 13:50
Thank you so much. Can i close this issue? Because it is not all an issue. The mistakes were mine.

**Comment by pieh** [comment] 2019-09-09 17:33
> Thank you so much. Can i close this issue? Because it is not all an issue. The mistakes were mine.

Yeah, let's close it. If there is more things happening we can either re-open it or create new issue for it.

**Closed by pieh** 2019-09-09 17:33 UTC
Labels: type: question or discussion

**Comment by Elod23** [comment] 2020-01-26 11:23
Hello guys. I've been trying to build up an app while using this feature and it seems not to work at all:
`exports.onCreatePage = async ({ page, actions }) => {
  const { createPage } = actions
  // page.matchPath is a special key that's used for matching pages
  // only on the client.
  if (page.path.match(/^\/room/)) {
    page.matchPath = "/room/*"
    // Update the page.
    createPage(page)
  }
}`
I've been using this to try and match everything after room to a certain component but it fails miserably. Am I missing something? Been digging on everything that has been given on this feed but could not fix it atm. :(

**Comment by muescha** [comment] 2020-01-27 04:24
@Elod23 can you please create a new issue, so that your problem not get lost?

**Comment by ashoksudani** [comment] 2020-02-12 10:04
Hello People,

I am trying to customise name for html page generated. I am not able to achieve somehow. I am also creating pages using createPage API and onCreatePage event is not getting triggered. Is that the only way to customise name and path for html page generated .
My issue is https://github.com/gatsbyjs/gatsby/issues/21393

**Comment by bradley** [comment] 2021-07-29 17:14
This is very old, but if anyone is trying to match _just_ root (e.g.; `pages/index.js`) I believe the more appropriate regex is `page.path.match(/^\/$/)`. Got bit pretty badly by the one without the `$` due to it matching every other page as well.

**Comment by rlemiengre** [comment] 2023-03-06 05:46
So it's not possible to do dynamic in-browser routing for pages that have been dynamically created with createPage? 
I'm creating all my pages dynamically in gatsby-node.js with createPage, because I need a different build for different languages (etc: /en/contact, /en/app, /fr/contact, /fr/app, etc). But I would also like to be able to use in-browser routing so I can have dynamic url parameters within these dynamically created pages. For example: /fr/confirm_payment/:ordernr
This doesn't seem to be possible since onCreatePage isn't called for these pages, so I can't use page.matchPath. 
Or is there another way to do this?
