### ISSUE TITLE
"Unclosed comment" unhelpful error

### ISSUE THREAD

**Issue by chrish-d** [gatsbyjs/gatsby#26619] opened 2020-08-24 17:43 UTC
## Description

When building my site, I get an "unclosed comment" error with no further information when "Building production JavaScript and CSS bundles".

The source code is available here: https://github.com/Modular-Everything/Yorkshire-Blinds-and-Curtains

[![Screenshot-2020-08-24-at-18-34-21.png](https://i.postimg.cc/bvrCQRF9/Screenshot-2020-08-24-at-18-34-21.png)](https://postimg.cc/PLGQH1HC)

### Expected result

I'd expect webpack to give me an error report that would help me track this down

### Environment

  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.5.0 - ~/.nvm/versions/node/v14.5.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v14.5.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.135
    Firefox: 77.0.1
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.22.15 => 2.23.11 
    gatsby-image: ^2.4.5 => 2.4.9 
    gatsby-plugin-manifest: ^2.4.9 => 2.4.14 
    gatsby-plugin-offline: ^3.2.7 => 3.2.13 
    gatsby-plugin-postcss: ^2.3.4 => 2.3.6 
    gatsby-plugin-react-helmet: ^3.3.4 => 3.3.6 
    gatsby-plugin-sharp: ^2.6.9 => 2.6.14 
    gatsby-source-filesystem: ^2.3.8 => 2.3.14 
    gatsby-source-storyblok: ^0.2.6 => 0.2.6 
    gatsby-transformer-sharp: ^2.5.3 => 2.5.7 
  npmGlobalPackages:
    gatsby-cli: 2.12.87

**Comment by muhzulzidan** [comment] 2020-08-25 11:22
first of all your base url is none

**Comment by vladar** [comment] 2020-08-28 19:35
Hi @chrish-d 

Sorry to hear you're running into an issue. I couldn't reproduce this problem using your project (on the master branch). Can you clarify which branch/commit should we look into to repro?

**Comment by ascorbic** [comment] 2020-09-10 14:14
Hi. I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. Thanks!

**Closed by ascorbic** 2020-09-10 14:14 UTC
Labels: status: needs more info, topic: webpack/babel, type: bug
