### ISSUE TITLE
Build fails with subsequent runs of gatsby build with the GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES flag

### ISSUE THREAD

**Issue by crypto-jones** [gatsbyjs/gatsby#25455] opened 2020-07-01 23:01 UTC
## Description
Build fails with subsequent runs of `gatsby build` with the `GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES` flag

```
...
failed Building static HTML for pages - 45.588s
 ERROR #95313 
Building static HTML failed for path "/careers/engineering/"
See our docs page for more info on this error: https://gatsby.dev/debug-html
  39 |     );
  40 | 
> 41 |     departments.forEach(({ id, parent_id, jobs }) => {
     |                 ^
  42 |         if (positions[id]) {
  43 |             jobs.forEach(job => positions[id].push(job));
  44 |         }
  WebpackError: TypeError: Cannot read property 'forEach' of null
  - GreenhouseContext.js:41 
    src/components/GreenhouseContext.js:41:17
  - memoize-one.esm.js:27 memoized
    node_modules/memoize-one/dist/memoize-one.esm.js:27:1
  - GreenhouseContext.js:56 new GreenhouseProvider
    src/components/GreenhouseContext.js:56:20
...
```

`departments` is fetched with plugin `gatsby-source-apiserver` and passed down from a StaticQuery.

### Steps to reproduce
1.
```
gatsby clean
GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES=true gatsby build --log-pages
```
which builds all pages as expected and logs all pages

2.
Make changes to a page
```
GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES=true gatsby build --log-pages
```

### Expected result
Build should complete successfully and only rebuild necessary pages.

### Actual result
The build breaks during the `Building static HTML for pages` step.

### Environment
```
  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.116
    Firefox: 68.9.0esr
  npmPackages:
    gatsby: 2.21.9 => 2.21.9
    gatsby-cli: 2.12.7 => 2.12.7
    gatsby-link: 2.4.0 => 2.4.0
    gatsby-plugin-intercom-spa: 0.1.0 => 0.1.0
    gatsby-plugin-manifest: 2.4.1 => 2.4.1
    gatsby-plugin-netlify-cms: 4.3.0 => 4.3.0
    gatsby-plugin-polyfill-io: 1.1.0 => 1.1.0
    gatsby-plugin-react-helmet: 3.1.0 => 3.1.0
    gatsby-plugin-robots-txt: 1.5.0 => 1.5.0
    gatsby-plugin-sass: 2.3.0 => 2.3.0
    gatsby-plugin-sentry: 1.0.1 => 1.0.1
    gatsby-plugin-sitemap: 2.4.1 => 2.4.1
    gatsby-source-apiserver: 2.1.3 => 2.1.3
    gatsby-source-filesystem: 2.3.0 => 2.3.0
    gatsby-transformer-json: 2.4.0 => 2.4.0
    gatsby-transformer-yaml: 2.4.0 => 2.4.0
```

**Comment by LekoArts** [comment] 2020-07-02 06:07
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by TylerBarnes** [comment] 2020-07-10 19:18
Hi @crypto-jones !

I'm closing this issue due to no reproduction being posted within 7 days.
Once you have a minimal reproduction feel free to re-open this issue and we'll be happy to take another look. 💜 

Thank you!

**Closed by TylerBarnes** 2020-07-10 19:18 UTC
Labels: status: needs reproduction

**Comment by crypto-jones** [comment] 2020-07-10 19:23
Hi @TylerBarnes 

I was unable to reproduce this issue because there was a bug in `gatsby-source-apiserver` that seems to have been very recently fixed. 
https://github.com/thinhle-agilityio/gatsby-source-apiserver/issues/49#issuecomment-656440872

I'll reopen this issue soon once I have a chance to delve back into it. Thanks!
