### ISSUE TITLE
Gatsby build sharp error: GLib-CRITICAL

### ISSUE THREAD

**Issue by mateodaza** [gatsbyjs/gatsby#27737] opened 2020-10-30 23:30 UTC
## Description

Building the app I come up with 
(sharp:65765): GLib-CRITICAL **: 18:27:19.451: g_hash_table_lookup: assertion 'hash_table != NULL' failed
### Steps to reproduce

gatsby build

### Expected result

What should happen?
build properly

### Actual result

Error
### Environment

  System:
    OS: macOS 10.15.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.18.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 86.0.4240.111
    Safari: 14.0
  npmPackages:
    gatsby: ^2.24.91 => 2.24.91 
    gatsby-image: ^2.4.21 => 2.4.21 
    gatsby-plugin-emotion: ^4.3.14 => 4.3.14 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-mailchimp: ^5.2.2 => 5.2.2 
    gatsby-plugin-manifest: ^2.4.37 => 2.4.37 
    gatsby-plugin-offline: ^3.2.38 => 3.2.38 
    gatsby-plugin-react-helmet: ^3.3.14 => 3.3.14 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-sharp: ^2.6.43 => 2.6.43 
    gatsby-plugin-theme-ui: ^0.3.0 => 0.3.0 
    gatsby-source-filesystem: ^2.3.37 => 2.3.37 
    gatsby-source-graphql: ^2.7.6 => 2.7.6 
    gatsby-source-medium: ^2.3.14 => 2.3.14 
    gatsby-transformer-sharp: ^2.5.20 => 2.5.20 
  npmGlobalPackages:
    gatsby-cli: 2.12.113

**Comment by LekoArts** [comment] 2020-11-02 08:08
I'll close this as a duplicate of https://github.com/gatsbyjs/gatsby/issues/26227 - please provide more information there.

**Closed by LekoArts** 2020-11-02 08:08 UTC
Labels: status: duplicate, type: bug
