### ISSUE TITLE
CSS splitting on production build

### ISSUE THREAD

**Issue by DecadentIpsum** [gatsbyjs/gatsby#18732] opened 2019-10-16 16:19 UTC
## Summary
In the production build of the following [url](https://i18n-dumptruck-dispatcher.netlify.com/en/) when I click "view page source" in Chrome, the source code seems to include all the CSS written for all the pages of the site.

For styling the pages I used CSS modules, where every single one of them is imported to a specific component.

## Expected result
I guess that every page should include only the styles that are written to the imported CSS module file of each component.

### Environment (if relevant)

System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-2600 CPU @ 3.40GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  npmPackages:
    gatsby: ^2.15.21 => 2.15.21
    gatsby-background-image: ^0.8.12 => 0.8.12
    gatsby-image: ^2.2.23 => 2.2.23
    gatsby-plugin-intl: ^0.2.8 => 0.2.8
    gatsby-plugin-mdx: ^1.0.46 => 1.0.46
    gatsby-plugin-react-helmet: ^3.1.8 => 3.1.8
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sharp: ^2.2.27 => 2.2.27
    gatsby-plugin-sitemap: ^2.2.14 => 2.2.14
    gatsby-plugin-styled-components: ^3.1.6 => 3.1.6
    gatsby-remark-images: ^3.1.25 => 3.1.25
    gatsby-source-filesystem: ^2.1.26 => 2.1.26
    gatsby-transformer-sharp: ^2.2.19 => 2.2.19
  npmGlobalPackages:
    gatsby-cli: 2.7.49

**Comment by LekoArts** [comment] 2019-11-04 15:27
Thank you for opening this!

This is working as intended. You can read more about that here: https://github.com/gatsbyjs/gatsby/issues/11072

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2019-11-04 15:27 UTC
Labels: type: question or discussion
