### ISSUE TITLE
Can't use gatsby-plugin-netlify-cms's useStaticQuery in wrapRootElement

### ISSUE THREAD

**Issue by TidyIQ** [gatsbyjs/gatsby#19136] opened 2019-10-30 07:25 UTC
## Description

I'm using Gatsby with Netlify CMS and Material UI. I need to wrap the entire app in Material-UI's `ThemeProvider` component, which takes in a `theme` prop. I'm using Netlify CMS to allow users to easily create the theme, which is then added to the theme prop using `useStaticQuery`.

Unfortunately this doesn't work as it returns the error:

```
Error: The result of this StaticQuery could not be fetched.

This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues
```

Stack trace:

```
useStaticQuery
C:/.../sites/simple-site/.cache/gatsby-browser-entry.js:1

AppProvider
C:/.../themes/gatsby-theme-mytheme/src/components/AppProvider/index.tsx:8

AppProvider
C:/.../node_modules/react-hot-loader/dist/react-hot-loader.development.js:827

renderWithHooks
C:/.../node_modules/react-dom/cjs/react-dom.development.js:16241

mountIndeterminateComponent
C:/.../node_modules/react-dom/cjs/react-dom.development.js:18775

beginWork$1
C:/.../node_modules/react-dom/cjs/react-dom.development.js:20137

HTMLUnknownElement.callCallback
C:/.../node_modules/react-dom/cjs/react-dom.development.js:336

invokeGuardedCallbackDev
C:/.../node_modules/react-dom/cjs/react-dom.development.js:385

invokeGuardedCallback
C:/.../node_modules/react-dom/cjs/react-dom.development.js:440

beginWork$$1
C:/.../node_modules/react-dom/cjs/react-dom.development.js:25738

performUnitOfWork
C:/.../node_modules/react-dom/cjs/react-dom.development.js:24665

workLoopSync
C:/.../node_modules/react-dom/cjs/react-dom.development.js:24638

performSyncWorkOnRoot
C:/.../node_modules/react-dom/cjs/react-dom.development.js:24237

scheduleUpdateOnFiber
C:/.../node_modules/react-dom/cjs/react-dom.development.js:23665

updateContainer
C:/.../node_modules/react-dom/cjs/react-dom.development.js:27061

(anonymous function)
C:/.../node_modules/react-dom/cjs/react-dom.development.js:27485

unbatchedUpdates
C:/.../node_modules/react-dom/cjs/react-dom.development.js:24400

legacyRenderSubtreeIntoContainer
C:/.../node_modules/react-dom/cjs/react-dom.development.js:27484

render
C:/.../node_modules/react-dom/cjs/react-dom.development.js:27572

(anonymous function)
C:/.../sites/simple-site/.cache/app.js:40
```

I have tested that the query is correct in `http://localhost:8000/___graphql`. I have also tried deleting the `.cache` and `public` folders then restarting the server, which does not fix the issue.

I can also confirm that this works fine if I move the component that uses `useStaticQuery` directly into a page instead of using `wrapRootElement`.

### Steps to reproduce

Try to run `useStaticQuery` in a component that is imported into `wrapRootElement`.

### Expected result

No issue

### Actual result

See error above

### Environment

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.10.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.16 - /c/Python27/python
  Browsers:
    Edge: 44.18362.387.0

**Comment by LekoArts** [comment] 2019-11-05 09:54
That's a duplicate of https://github.com/gatsbyjs/gatsby/issues/7747
Please have a look at the issue to know how to workaround this issue. Thanks!

**Closed by LekoArts** 2019-11-05 09:54 UTC
