### ISSUE TITLE
Gatsby restart on every new file/link

### ISSUE THREAD

**Issue by mrfsrf** [gatsbyjs/gatsby#34087] opened 2021-11-27 14:37 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

when you create new file in src/packages you have to restart Gatsby server by Gatsby dev

### Reproduction Link

/none

### Steps to Reproduce

1. gabby new use start hello world theme
2.
3.
...

### Expected Result

if you add new file/link you would except to work immediately

### Actual Result

doesn't work 

### Environment

```shell
System:
    OS: macOS 11.5.2
    CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
    Shell: 5.8 - /usr/local/bin/zsh
  Binaries:
    Node: 17.1.0 - ~/.config/.nvm/versions/node/v17.1.0/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 8.1.2 - ~/.config/.nvm/versions/node/v17.1.0/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  Browsers:
    Chrome: 96.0.4664.55
    Firefox: 92.0
    Safari: 14.1.2
  npmGlobalPackages:
    gatsby-cli: 4.2.0
```

### Config Flags

no

**Comment by LekoArts** [comment] 2021-11-29 08:28
Hi, thanks for the issue!

To make the process of resolving problems quicker for both sides we need you to fill out the issue template and give us a [minimal reproduction][reproduction]. I'd also recommend using Node 16 instead of Node 17.

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-12-14 06:08
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-12-14 06:08 UTC
Labels: type: bug, status: needs reproduction
