### ISSUE TITLE
custom useStaticQuery hooks

### ISSUE THREAD

**Issue by laskar-ksatria** [gatsbyjs/gatsby#29320] opened 2021-02-03 12:02 UTC
I got error like that when i useStaticQueryHooks

×
Error: The result of this StaticQuery could not be fetched.

This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues

  74 | if (context[query]?.data) {
  75 |   return context[query].data
  76 | } else {
> 77 |   throw new Error(
  78 |     `The result of this StaticQuery could not be fetched.\n\n` +
  79 |       `This is likely a bug in Gatsby and if refreshing the page does not fix it, ` +
  80 |       `please open an issue in https://github.com/gatsbyjs/gatsby/issues`

**Comment by LekoArts** [comment] 2021-02-04 10:18
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-02-15 14:10
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-02-15 14:10 UTC
Labels: status: needs reproduction, type: bug
