### ISSUE TITLE
RangeError occurs when package.json name is missing

### ISSUE THREAD

**Issue by jsonmaur** [gatsbyjs/gatsby#15966] opened 2019-07-22 03:34 UTC
I kept getting `error We've encountered an error: RangeError` in the logs for the `gatsby develop` command (and only the develop command.) Took ages to figure out why this was happening, but turns out it was because my package.json didn't have a `name` field (as it was marked as `private: true`.)

[NPM specifically says this field is optional if the package is private](https://docs.npmjs.com/files/package.json).

**Comment by DanielRuf** [comment] 2019-07-22 04:15
Hi @jsonmaur,

I see no mention of it that it is optional in this case.

https://docs.npmjs.com/files/package.json#name

Afaik npm also warns then.

Can you post the full error with the stacktrace so we know where it comes from?

**Comment by jsonmaur** [comment] 2019-07-22 04:17
Last sentence of first paragraph:
> If you don’t plan to publish your package, the name and version fields are optional.

And no stack trace was given when the error was thrown, that's all there was. Even with the `--verbose` option.

**Comment by DanielRuf** [comment] 2019-07-22 04:26
Can you provide some more info like your NodeJS and npm version?

**Comment by jsonmaur** [comment] 2019-07-22 04:30
Sure.
Node: `10.16.0`
NPM: `6.9.0`
Gatsby: `2.13.32`

**Comment by DanielRuf** [comment] 2019-07-22 04:36
Would be very helpful if you could update the first comment with our bug issue template to also include the steps to reproduce this: https://github.com/gatsbyjs/gatsby/issues/new?template=bug_report.md

**Comment by dtinth** [comment] 2019-07-22 15:54
I also get this error. Here’s an example terminal output:

![image](https://user-images.githubusercontent.com/193136/61646375-9d617e80-acd3-11e9-9903-be88efb3bc32.png)

No stack trace is given.

**Comment by DanielRuf** [comment] 2019-07-22 16:12
Where does `We've encountered an error` come from? Seems to be from one of the dependencies / Gatsby itself.

**Comment by DanielRuf** [comment] 2019-07-22 16:15
https://github.com/gatsbyjs/gatsby/blob/11322d865dfbfc15db9dc0416633ce6817ef252e/packages/gatsby-cli/src/reporter/reporters/ink/reporter.js#L157

Maybe we can output the full error including the stacktrace instead of just using the error name: https://github.com/gatsbyjs/gatsby/blob/11322d865dfbfc15db9dc0416633ce6817ef252e/packages/gatsby-cli/src/reporter/reporters/ink/reporter.js#L137

**Comment by dtinth** [comment] 2019-07-22 16:50
Here is the stack trace for the RangeError:

```
RangeError: Maximum call stack size exceeded
    at scheduleWorkToRoot (/Users/dtinth/dt.in.th/node_modules/react-reconciler/cjs/react-reconciler.development.js:1:1)
    at scheduleWork (/Users/dtinth/dt.in.th/node_modules/react-reconciler/cjs/react-reconciler.development.js:11863:14)
    at Object.enqueueSetState (/Users/dtinth/dt.in.th/node_modules/react-reconciler/cjs/react-reconciler.development.js:3152:5)
    at GatsbyReporter.Component.setState (/Users/dtinth/dt.in.th/node_modules/react/cjs/react.development.js:335:16)
    at GatsbyReporter._addMessage (/Users/dtinth/dt.in.th/node_modules/gatsby-cli/lib/reporter/reporters/ink/reporter.js:186:10)
    at Console.console.error.args [as error] (/Users/dtinth/dt.in.th/node_modules/gatsby-cli/lib/reporter/index.js:258:39)
    at warningWithoutStack (/Users/dtinth/dt.in.th/node_modules/react-reconciler/cjs/react-reconciler.development.js:100:32)
    at warnAboutUpdateOnUnmounted (/Users/dtinth/dt.in.th/node_modules/react-reconciler/cjs/react-reconciler.development.js:10458:5)
    at scheduleWork (/Users/dtinth/dt.in.th/node_modules/react-reconciler/cjs/react-reconciler.development.js:11868:11)
    at Object.enqueueSetState (/Users/dtinth/dt.in.th/node_modules/react-reconciler/cjs/react-reconciler.development.js:3152:5)
    at GatsbyReporter.Component.setState (/Users/dtinth/dt.in.th/node_modules/react/cjs/react.development.js:335:16)
    at GatsbyReporter._addMessage (/Users/dtinth/dt.in.th/node_modules/gatsby-cli/lib/reporter/reporters/ink/reporter.js:186:10)
    at Console.console.error.args [as error] (/Users/dtinth/dt.in.th/node_modules/gatsby-cli/lib/reporter/index.js:258:39)
    at warningWithoutStack (/Users/dtinth/dt.in.th/node_modules/react-reconciler/cjs/react-reconciler.development.js:100:32)
    at warnAboutUpdateOnUnmounted (/Users/dtinth/dt.in.th/node_modules/react-reconciler/cjs/react-reconciler.development.js:10458:5)
```

**Comment by sidharthachatterjee** [comment] 2019-08-05 09:50
@jsonmaur I tried to reproduce this in https://github.com/sidharthachatterjee/gatsby-site-has-no-name but was unable to do so 🙂 Both `develop` and `build` seem to work fine with the project (which has no name in its package.json)

Since this appears to be resolved, could you try running this with gatsby 2.13.50 and link to a reproduction if you are still seeing it?

@dtinth This appears to be a separate and unrelated issue. Could you please open another issue with a link to a reproduction/instructions?

Closing this for now!

**Closed by sidharthachatterjee** 2019-08-05 09:50 UTC
Labels: status: awaiting author response, status: needs more info, status: needs reproduction
