### ISSUE TITLE
Remote MDX Frontmatter Image urls not working on Gatsby Cloud - Gatsby 4

### ISSUE THREAD

**Issue by PaulieScanlon** [gatsbyjs/gatsby#33651] opened 2021-10-24 10:12 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi team. I tried to upgrade my theme to Gatsby 4 by when deploying to Gatsby Cloud i've noticed the remote images that are sourced from MDX Frontmatter and converted into File nodes to be processed with `childImageSharpe` using `createRemoteFileNode` aren't displaying

### Reproduction Link

https://build-0b068efd-2e1c-4bfb-8211-96bfbf9c1c92.gtsb.io/posts/2021/remote-image-post/

The PR for this can be found here: https://github.com/PaulieScanlon/gatsby-theme-terminal/pull/52/files

The MDX page containing the Fontmatter field can be found here: https://github.com/PaulieScanlon/gatsby-theme-terminal/blob/feat/upgrade-to-gatsby-4/demo/src/posts/2021/remote-image-post.mdx

And all of the `createSchemaCustomization` code can be found here: https://github.com/PaulieScanlon/gatsby-theme-terminal/blob/feat/upgrade-to-gatsby-4/%40pauliescanlon/gatsby-theme-terminal/gatsby-node.js#L78

### Steps to Reproduce

1. Add remote image url to MDX Frontmatter
2. Use `createRemoteFileNode` from inside `onCreateNode` to source the remote image and store it in a new frontmatter field
```javascript
    if (node.frontmatter.featuredImageUrl) {
      node.featuredImageUrl = await createRemoteFileNode({
        url: node.frontmatter.featuredImageUrl,
        parentNodeId: node.id,
        createNode,
        createNodeId,
        cache,
        store,
      }).catch((error) => {
        console.error(error)
      })
    }
```
3. Re-Type the new frontmatter type as File
```javascript
exports.createSchemaCustomization = async ({ actions }) => {
  const { createTypes } = actions

  createTypes(`
    type Mdx implements Node {
      frontmatter: Frontmatter
      featuredImageUrl: FeaturedImageUrl
    }

    type Frontmatter @dontInfer {
        featuredImage: File @fileByRelativePath
        featuredImageUrl: String
    }

    type FeaturedImageUrl  {
      url: File @link(by: "url")
    }
  `)

}

```
4 .  Query it in `Jsx`

### Expected Result

1. There should be a thumbnail on the post pate for "Remote Image Post" : https://build-0b068efd-2e1c-4bfb-8211-96bfbf9c1c92.gtsb.io/posts/
2. There should be a featured image in the "Remote Image Post": https://build-0b068efd-2e1c-4bfb-8211-96bfbf9c1c92.gtsb.io/posts/2021/remote-image-post/

### Actual Result

When deploying to Gatsby Cloud and Netlify neither of the remote images display

### Environment

```shell
System:
    OS: macOS 11.5.2
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.17.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.24.2 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 95.0.4638.54
    Firefox: 93.0
    Safari: 15.0
  npmGlobalPackages:
    gatsby-cli: 2.15.1
```

**Comment by tariknz** [comment] 2021-10-29 22:58
I haven't tested this  but maybe this:

```js
 if (node.frontmatter.embeddedImageUrls) {
  const nodes = await Promise.all(
    node.frontmatter.embeddedImageUrls.map((url) => {
      try {
        return createRemoteFileNode({
          url,
          parentNodeId: node.id,
          createNode,
          createNodeId,
          cache,
          store,
        })
      } catch (error) {
        console.error(error)
      }
    }),
  )

  createNodeField({ node, name: 'embeddedImages', value: nodes.map(n => n.id) })
}
```

In your type possibly 
```
[File] @link(from: "fields.embeddedImages")
```

🤷

**Comment by PaulieScanlon** [comment] 2021-11-03 18:22
Thanks for the response @tariknz! Yeap that worked a treat. I changed a few things but it's the same solution! 

For completeness this is what worked for me, happy to close this issue now unless you'd prefer to keep it open for others?


```javascript
    if (node.frontmatter.embeddedImageUrls) {
      let embeddedImageUrls = await Promise.all(
        node.frontmatter.embeddedImageUrls.map((url) => {
          return createRemoteFileNode({
            url,
            parentNodeId: node.id,
            createNode,
            createNodeId,
            cache,
            store,
          })
        }),
      )
      if (embeddedImageUrls) {
        createNodeField({
          node,
          name: 'embeddedImageUrls',
          value: embeddedImageUrls.map((embeddedImageUrl) => {
            return embeddedImageUrl.id
          }),
        })
      }
    }
```

and the type becomes

```graphql
  createTypes(`
    type Mdx implements Node {
      embeddedImageUrls: [File] @link(from: "fields.embeddedImageUrls")
    }

    type Frontmatter @dontInfer {
        embeddedImageUrls: [String]
    }
  `)

```

**Comment by tariknz** [comment] 2021-11-03 20:15
Nice @PaulieScanlon, that was a stab in the dark there but happy it's worked out! 😂

**Comment by LekoArts** [comment] 2021-11-04 08:08
I'll close this one as resolved as it's not a bug we need to fix. We're still looking into putting up a warning but the current tests show that checking everything increases build times more than we want. So might take a bit longer to ship that feature.

**Closed by LekoArts** 2021-11-04 08:08 UTC
Labels: type: bug, gatsby 4

**Comment by PaulieScanlon** [comment] 2021-11-10 09:19
In case anyone stumbles upon this same issue, there's a post on the Gatsby blog that has an explanation and a repo for reference.

The post is relating to remote image urls that are sourced from MDX `frontmatter` but the method is transferable to other remote image sourcing requirements

[MDX Embedded Images with the All-New Gatsby Image Plugin](https://www.gatsbyjs.com/blog/mdx-embedded-gatsby-image)
