### ISSUE TITLE
Delay when loading CSS with Gatbsy

### ISSUE THREAD

**Issue by Steffi3rd** [gatsbyjs/gatsby#9902] opened 2018-11-13 09:10 UTC
# Description

When I load for the first time the gatbsy blog, I have a delay before CSS is loading. I think 300ms...
Whatever the browser is, it always do this.

It renders once before CSS is applied and 300ms after is rendered well.

Why? 

[Demo here](https://imgur.com/gallery/av23KHP)

### On page loading 
<img width="720" alt="capture d ecran 2018-11-13 a 10 09 32" src="https://user-images.githubusercontent.com/814410/48402589-4959cf80-e72c-11e8-951b-aff49daa6c6f.png">

### After 300ms
<img width="721" alt="capture d ecran 2018-11-13 a 10 09 45" src="https://user-images.githubusercontent.com/814410/48402590-4959cf80-e72c-11e8-98ae-f364bc407370.png">

### Environment 

```
  System:
    OS: macOS 10.14
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 8.12.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 70.0.3538.77
    Safari: 12.0
  npmPackages:
    gatsby: ^2.0.24 => 2.0.43 
    gatsby-image: ^2.0.15 => 2.0.20 
    gatsby-plugin-lodash: ^3.0.1 => 3.0.2 
    gatsby-plugin-manifest: ^2.0.5 => 2.0.8 
    gatsby-plugin-offline: ^2.0.6 => 2.0.13 
    gatsby-plugin-react-helmet: ^3.0.0 => 3.0.1 
    gatsby-plugin-sharp: ^2.0.7 => 2.0.12 
    gatsby-plugin-sitemap: ^2.0.1 => 2.0.2 
    gatsby-source-prismic: ^2.0.0 => 2.1.0 
    gatsby-transformer-sharp: ^2.1.4 => 2.1.8 
  npmGlobalPackages:
    gatsby-cli: 2.4.5
```

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by Steffi3rd** [comment] 2018-11-13 11:38
It's on `build`. 

On `develop`, I have a blank page very very fast before it renders well.

**Comment by kakadiadarpan** [comment] 2018-11-13 13:16
@Steffi3rd can you provide us with a minimal reproduction repo for this issue?

**Comment by Steffi3rd** [comment] 2018-11-14 09:31
By the way, CSS is not render the same in mobile and web.

![unnamed](https://user-images.githubusercontent.com/814410/48473236-5d6b0300-e7f8-11e8-83b3-29cdc9b848a8.jpg)

**Comment by jonniebigodes** [comment] 2018-11-14 16:30
@Steffi3rd if you can, provide a repo so that this issue can be further investigated and we can provide better assistance with this.

**Comment by aesthytik** [comment] 2018-11-14 18:40
@steffi3rd if you are using a CSS  library then it's better to put the cdn link in html.js. let us access to your repo for further assistance! 😁👍

**Comment by Steffi3rd** [comment] 2018-11-14 20:14
> @Steffi3rd if you are using a CSS library then it's better to put the cdn link in html.js. let us access to your repo for further assistance! 😁👍

I use Styled Component, is there a problem with this?

**Comment by Steffi3rd** [comment] 2018-11-14 20:15
> @Steffi3rd if you can, provide a repo so that this issue can be further investigated and we can provide better assistance with this.



> @Steffi3rd if you can, provide a repo so that this issue can be further investigated and we can provide better assistance with this.



> @Steffi3rd if you can, provide a repo so that this issue can be further investigated and we can provide better assistance with this.

This url is : https://edgebase.github.io/blog/

**Comment by jonniebigodes** [comment] 2018-11-14 20:29
@Steffi3rd no...that's the url for the production build, the full blow website address...What i and other people before me asked is if you could provide a repo as in a github repository address,  where you have your code hosted so that i and other people can check the code and see what is the issue and how we can assist you on resolving your issue. If you cannot provide that address because your code is otherwise private or protected by a company, provide us with an alternative, namely a dummy github url which replicates the exact issue you're experiencing with the library, so that me and other people like me can see what is the actual problem and aid you in fixing it

**Comment by KyleAMathews** [comment] 2018-11-14 21:59
If you're using a css-in-js library, you need to install its corresponding gatsby plugin to ensure that the css for pages is extracted and added to the generated HTML as otherwise, css isn't added until after the JS loads which causes the delay you see.

See https://www.gatsbyjs.org/packages/gatsby-plugin-styled-components/?=styled

**Closed by KyleAMathews** 2018-11-14 21:59 UTC
Labels: status: needs more info

**Comment by Steffi3rd** [comment] 2018-11-15 08:49
> If you're using a css-in-js library, you need to install its corresponding gatsby plugin to ensure that the css for pages is extracted and added to the generated HTML as otherwise, css isn't added until after the JS loads which causes the delay you see.
> 
> See https://www.gatsbyjs.org/packages/gatsby-plugin-styled-components/?=styled

Yeaaaah ! I installed `gatsby-plugin-styled-component` ! It finally works! Thank you @KyleAMathews 

Just found your answer on a another post : https://github.com/gatsbyjs/gatsby/issues/5366

**Comment by j10sanders** [comment] 2019-04-04 01:28
I installed `gatsby-plugin-styled-components` but am still getting this issue.  You can see the css getting moved on the homepage, where the articles all start center aligned.  https://jonsjournal.com/

It does NOT happen on the local develop version.

Repo here: https://github.com/j10sanders/jonsjournal

Possibly also relevant -- I've noticed that setting/reading localStorage is also not working on the deployed, build, version, but is working on the local develop one.

Any suggestions?
Thanks

**Comment by VictorBaudot** [comment] 2019-04-11 16:11
Same problem, I also installed `gatsby-plugin-styled-components` but I still get the delay before the CSS being loaded...

**Comment by watch-janick** [comment] 2019-05-26 12:54
I've got the same issue with `styled-components` and `gatsby-plugin-styled-components`.
Anyone found a fix for this one?

**Comment by paulgaumer** [comment] 2019-07-14 22:38
+1, same issue here with the `styled-components` plugin correctly installed. Has anyone found a solution?

**Comment by sky172839465** [comment] 2019-07-28 13:01
![gatsby-render-layout](https://user-images.githubusercontent.com/9082423/62006866-29aeee00-b179-11e9-9382-1a35aecd41c9.gif)

Repo: https://github.com/sky172839465/yusong-blog

+1 same issue, in `production` Layout component render from wrapPageElement very slow,
I found a [workaround][] by @alexanderwe 's solution, thanks!

[workaround]: https://github.com/gatsbyjs/gatsby/issues/14978#issuecomment-514372027

**Comment by Antoshkiv** [comment] 2020-06-25 10:55
I have same problem, installed gatsby-plugin-styled-components styled-components babel-plugin-styled-components 
Any solution to the problem?

**Comment by elliotrpmorris** [comment] 2020-07-06 18:03
Same problem here too!

**Comment by ismailmri** [comment] 2020-07-20 13:27
Has their been any solutions?

**Comment by ismailmri** [comment] 2020-07-20 13:28
I got the same problem. Has anyone found a solution?

**Comment by hayyaun** [comment] 2020-09-17 17:57
I have the same problem on most of my Gastby projects and not fixed yet...

**Comment by doylemark** [comment] 2020-12-27 01:49
Has anyone found a resolution to this problem? Issue is only prevalent on production for me..

**Comment by hayyaun** [comment] 2020-12-27 01:53
> Has anyone found a resolution to this problem? Issue is only prevalent on production for me..

It turned out in my case that a plug-in called gatsby-plugin-minify was causing this issue. After removing it every thing got ok. In some cases people also reported not using gatsby-plugin-styled-components can cause same issue.
Wish it could help you.

**Comment by doylemark** [comment] 2020-12-27 04:14
Thanks, I think I identified the problem

I found there is a hydration problem using the `wrapRootElement` api with styled-components (and more?), there seems to have been extensive discussion on stack, this issue tracker, and (in detail) [here on repo discussions](https://github.com/gatsbyjs/gatsby/discussions/17914).

In my case, I was adding a `createGlobalStyles` styled-component with the `wrapRootElement` API.. This was not getting rendered server side by gatsby-ssr.js. So the delay I was experiencing was waiting for gatsby to rehydrate the site with the `<GlobalStyles />` component. My "quick fix" is to add global styles to with the `wrapPageElement` API which seems to work (?). However this seems to be a much deeper then just this.. I think this issue (and or others) needs to be re-opened pending more investigation on this. The discussion linked above is very useful. 
Cheers

**Comment by PetrShchukin** [comment] 2021-01-20 23:58
Same problem

**Comment by olivertembo** [comment] 2021-02-25 20:59
@PetrShchukin did you find a solution? I used a different ui in project, I did not have a problem. First time using Mui and it is giving me the same problem.

**Comment by up9cloud** [comment] 2021-04-15 12:00
If you play with Mui, install `gatsby-plugin-material-ui` and set `gatsby-config.js` to something like:
- [Mui Gatsby example](https://github.com/mui-org/material-ui/blob/master/examples/gatsby/gatsby-config.js)
- [Plugin doc](https://www.gatsbyjs.com/plugins/gatsby-plugin-material-ui/#usage-with-styled-components-or-else)

**Comment by vgarmes** [comment] 2021-09-23 08:24
As @doylemark, I moved the styled-components global styles from `wrapRootElement` to `wrapPageElement` and it fixed my delay. This is also explained here: https://github.com/spences10/ama/issues/11
