### ISSUE TITLE
Image load time longer on a Mac OS than on Windows machine.

### ISSUE THREAD

**Issue by janyalda17** [gatsbyjs/gatsby#29200] opened 2021-01-25 21:52 UTC
## Description

The process of pre-rendering the image using a the blur effect lasts longer on a Mac OS system, I know the network connection speed affects it but it's been tested on machines with quite fast connections so that wasn't an issue.

### Steps to reproduce

It takes nothing special to reproduce just needs to be tested/compared between the two operating systems.

### Expected result

The Ideal result would be a similar load time.

### Actual result

Mac OS machine regardless of browser is slower than Windows machine at loading the image.

### Environment

Mac OS: macOS 10.15.7
Windows: Windows 10 10.0.19042

**Comment by LekoArts** [comment] 2021-01-27 09:30
Hi!

Sorry, but I don't understand what you're trying to say. What's the exact problem?
Can you record a video showing the difference you mean and [provide a minimal reproduction][reproduction]?

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-02-04 10:21
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-02-04 10:21 UTC
Labels: status: needs more info, status: needs reproduction, type: bug
