### ISSUE TITLE
Using GATSBY_EMPTY_ALT ignored for figcaption-generation by gatsby-remark-image ie creates non-sense figcaption

### ISSUE THREAD

**Issue by ronalde** [gatsbyjs/gatsby#30285] opened 2021-03-17 10:08 UTC
The fix described in issue #20179 introduces a regression, especially from an accessibility perspective. When declaring an empty alt-attribute for an image using the keyword `GATSBY_EMPTY_ALT` in markdown (`![GATSBY_EMPTY_ALT](rel/path.jpg)` *and* having set `showCaptions: true` in the plugin-options in `gatsby-config.js`, the plugin produces unwanted HTML:

```html
<figure class="gatsby-resp-image-figure" ...>
    <span class="gatsby-resp-image-wrapper" style="...">
      <span class="gatsby-resp-image-background-image" style="..."></span>
        <img class="gatsby-resp-image-image" alt="" title="" src="/path.jpg" ...>
    </span>
</figure>
<figcaption class="gatsby-resp-image-figcaption"><p>GATSBY<em>EMPTY</em>ALT</p></figcaption>
```

* the package produces the empty value for the `alt`-attribute value of the `img`-element like instructed (line 4);
* but it inserts an (obviously) unwanted  `figcaption`-element below the `figure`-element (line 7) that contains unwanted (and non-sense) content:  `<p>GATSBY<em>EMPTY</em>ALT</p>`.
 
This seems to fix the problem for current 4.x versions:

```diff
--- unpatched.index.js	2021-03-15 10:09:19.898810753 +0100
+++ patched.index.js	2021-03-15 10:11:28.041596794 +0100
@@ -114,7 +114,7 @@
           switch (_context.prev = _context.next) {
             case 0:
               getCaptionString = function getCaptionString() {
-                var captionOptions = Array.isArray(options.showCaptions) ? options.showCaptions : options.showCaptions === true ? ["title", "alt"] : false;
+                var captionOptions = Array.isArray(options.showCaptions) ? options.showCaptions : ( options.showCaptions === true && node.alt !== EMPTY_ALT) ? ["title", "alt"] : false;
 
                 if (captionOptions) {
                   for (var _iterator = _createForOfIteratorHelperLoose(captionOptions), _step; !(_step = _iterator()).done;) {
```

Furthermore, this feature should be documented in `README.md:

```diff
--- /tmp/README.md	2021-03-15 16:05:28.328713216 +0100
+++ node_modules/gatsby-remark-images/README.md	2021-03-15 16:12:26.848647108 +0100
@@ -50,8 +50,7 @@
By default, the text `Alt text here` will be used as the alt attribute of the generated `img` tag
-.
+ and for the contents of the generated `figcaption` element.
If an empty alt attribute like `alt=""`
- is wished,
+ and no figcaption is wished,
a reserved keyword `GATSBY_EMPTY_ALT` can be used.
```
 
```diff
--- /tmp/README.md	2021-03-15 16:05:28.328713216 +0100
+++ node_modules/gatsby-remark-images/README.md	2021-03-15 16:12:26.848647108 +0100
@@ -63,7 +62,7 @@
| `showCaptions`          | `false` | Add a caption to each image with the contents of the title attribute, when this is not empty. 
...
If you just want to use the title (and omit captions for images that have alt attributes but no title), pass `['title']`. 
+ If the alt tag contains the reserved `GATSBY_EMPTY_ALT` value no `figcaption` will be produced. |
```

_Originally posted by @ronalde in https://github.com/gatsbyjs/gatsby/issues/20179#issuecomment-798720484_

**Comment by nategiraudeau** [comment] 2021-03-25 01:12
@ronalde, can I work on this issue?

**Comment by ronalde** [comment] 2021-03-25 10:55
@nategiraudeau Please do!

**Comment by Piyush-Chandel** [comment] 2021-03-25 12:31
Hello I Can fix this, but please can explain what exactly the problem is?? What exactly you wanted to get fixed??

**Comment by ronalde** [comment] 2021-03-26 07:46
@nategiraudeau Thanks for your swift and clean PR! 
Do you know what's blocking the linting pipeline (and how to solve that)?

**Comment by nategiraudeau** [comment] 2021-09-08 21:50
@ronalde can this issue be reopened? I was able to fix the problem with the linter that was blocking the pull request from being merged.

**Closed** 2021-10-30 09:21 UTC
Labels: type: bug, topic: remark/mdx
