### ISSUE TITLE
[1.0] Cannot read property 'component' of undefined in production-app.js

### ISSUE THREAD

**Issue by 0x80** [gatsbyjs/gatsby#981] opened 2017-05-17 07:31 UTC
In a production build, when I reload the page and then navigate away to another I get this error.

```
production-app.js:147 Uncaught TypeError: Cannot read property 'component' of undefined
    at renderPage (production-app.js:147)
    at render (production-app.js:182)
```

Line 147 then points to `return $(scriptsCache[page.path].component, (0, _extends3.default)({}, props, scriptsCache[page.path].pageData));` in this piece of code:

```javascript
var renderPage = function renderPage(props) {
  var page = _pages2.default.find(function (page) {
    if (page.matchPath) {
      // Try both the path and matchPath
      return (0, _reactRouterDom.matchPath)(props.location.pathname, { path: page.path }) || (0, _reactRouterDom.matchPath)(props.location.pathname, {
        path: page.matchPath
      });
    } else {
      return (0, _reactRouterDom.matchPath)(props.location.pathname, {
        path: page.path,
        exact: true
      });
    }
  });
  if (page) {
    return $(scriptsCache[page.path].component, (0, _extends3.default)({}, props, scriptsCache[page.path].pageData));
  } else if (notFoundScripts) {
    return $(notFoundScripts.component, (0, _extends3.default)({}, props, notFoundScripts.pageData));
  } else {
    return null;
  }
};
```
This issue seems to come from the fact that I'm trying to use urls without a trailing slash. I have this in my `gatsby-browser.js` file to make that possible

```javascript
exports.modifyRoutes = routes => {
  routes.childRoutes.forEach(
    route => (route.path = route.path.replace(/\/$/, ''))
  )
  return routes
}
```

It appears that the `page.path` needs to be sanitized before using it to look up the cash.  I will see if I can fix this in a PR.

**Comment by KyleAMathews** [comment] 2017-05-17 07:41
`modifyRoutes` isn't an API so not sure what that code is doing unless you're calling it yourself.

And yeah, if you want to modify routes, you can't do it client side. Instead in your gatsby-node.js use `onUpsertPage`.

**Comment by 0x80** [comment] 2017-05-17 08:02
@KyleAMathews Maybe it was left over from when I started in Gatsby 0.x. I couldn't use urls without a trailing slash then and this code, which I copied from somewhere, solved that. I didn't make this up myself :)

So I get understand correctly, in case you want routes without a trailing slash you should create a copy of each route (without slash) using onUpsertPage, and the cache lookup in production-app.js should stay unmodified?

**Comment by KyleAMathews** [comment] 2017-05-17 08:19
Oh yeah sorry, that was an api in v0.

Lemme write up a quick docs page on modifying routes. Am actually working on that right now anyways :-)

**Comment by KyleAMathews** [comment] 2017-05-17 08:23
https://github.com/gatsbyjs/gatsby/pull/982 working on quick docs page right now

**Comment by KyleAMathews** [comment] 2017-05-17 08:41
@0x80 it's merged. Would love feedback on the docs page + general patterns.

**Comment by 0x80** [comment] 2017-05-17 12:21
@KyleAMathews Using the new upsertPage api to remove the trailing slash did not solve the cache lookup problem in the production app. It looks like it still wants the path with a trailing slash.

Also a new error seemed to have occurred due to a recent commit:

```javascript
production-app.js:186 Uncaught TypeError: Cannot read property 'layout' of undefined
    at production-app.js:186
    at loadScriptsForPath (production-app.js:63)
```

Which points to

```javascript
loadScriptsForPath(window.location.pathname, function (scripts) {
  // Use default layout if one isn't set.
  var layout = void 0;
  if (scripts.layout) {
    layout = scripts.layout;
  } else {
```

This happens when I load one of my pages which are constructed from the `pages` directory

**Comment by KyleAMathews** [comment] 2017-05-17 12:30
So "scripts" is undefined?

**Comment by 0x80** [comment] 2017-05-17 12:38
Yes looks like it

**Comment by anthonysapp** [comment] 2017-05-17 14:28
Seems to be the exact issue I'm having as well. Happens with any "upserted" page.

**Comment by anthonysapp** [comment] 2017-05-17 14:46
@KyleAMathews  @0x80  Yeah, so this just has to do with the script loader not finding the script because your path has a trailing slash (probably appended by apache or whatever server you're using), and your Gatsby route doesn't have one. If your route matches the Gatsby route exactly, it does indeed work.

**Comment by KyleAMathews** [comment] 2017-05-17 17:43
@0x80 reproduction steps for this would be great. Also if you could add the output for console.logging `pages` and `requires` in production-app.js

**Comment by anthonysapp** [comment] 2017-05-17 17:49
@0x80 just a side note: if it is the same trailing slash issue I was experiencing, you should probably wipe the .cache folder and do fresh build

**Comment by 0x80** [comment] 2017-05-17 22:06
@KyleAMathews Steps to reproduce would be 

1) put this code in gatsby-node
```javascript
exports.onUpsertPage = ({ page, boundActionCreators }) => {
  const { upsertPage, deletePageByPath } = boundActionCreators

  return new Promise((resolve, reject) => {
    // Remove trailing slash
    const oldPath = page.path
    page.path = page.path.replace(/\/$/, '')

    console.log('path -> oldPath', page.path, oldPath)
    if (page.path && page.path !== oldPath) {
      // Remove the old page
      deletePageByPath(oldPath)

      // Add the new page
      upsertPage(page)
    }

    resolve()
  })
}```

2) Create a link to a page without a trailing slash. 
3) Build the production app
4) Navigate to the other page (without the trailing slash) with the link

The json stringified outputs of requires and pages are:

```json
 {"components":{},"json":{},"layouts":{}}
```

```json
[{"componentChunkName":"page-component---src-templates-work-page-js","jsonName":"work-kaliber.json","path":"/work/kaliber/"},{"componentChunkName":"page-component---src-templates-work-page-js","jsonName":"work-ontspoord.json","path":"/work/ontspoord/"},{"componentChunkName":"page-component---src-templates-work-page-js","jsonName":"work-nln-live.json","path":"/work/nln-live/"},{"componentChunkName":"page-component---src-templates-work-page-js","jsonName":"work-we-need-us.json","path":"/work/we-need-us/"},{"componentChunkName":"page-component---src-templates-work-page-js","jsonName":"work-4-d-sound.json","path":"/work/4d-sound/"},{"componentChunkName":"page-component---src-templates-work-page-js","jsonName":"work-coca-cola-cascada.json","path":"/work/coca-cola-cascada/"},{"componentChunkName":"page-component---src-templates-work-page-js","jsonName":"work-shreditor.json","path":"/work/shreditor/"},{"componentChunkName":"page-component---src-templates-work-page-js","jsonName":"work-segment.json","path":"/work/segment/"},{"componentChunkName":"page-component---src-pages-about-js","jsonName":"about.json","path":"/about"},{"componentChunkName":"page-component---src-pages-index-js","jsonName":"index.json","path":""},{"componentChunkName":"page-component---src-pages-work-js","jsonName":"work.json","path":"/work"}]
```

**Comment by 0x80** [comment] 2017-06-02 13:33
@KyleAMathews I vagely remember that you fixed something related to this? 

I have been using link locations with trailing slashes ever since I got into this problem, but in production quite a few of my users seem to be running into the exact same error. Strangely I have never seen this error myself anymore since I have been using the trailing slash.

I looked a the occurred errors (about 25 now) and they all navigate from/to other pages, so I can find no consistent data or a way to reproduce this. Maybe we can built in a safeguard and log some useful data? What do you think?

**Comment by KyleAMathews** [comment] 2017-06-02 21:52
@0x80 yeah this definitely is needed.

I'm going to do a deep dive on this next week after the first beta/tutorial MVP is out but would love any help you could give in the meantime.

**Comment by KyleAMathews** [comment] 2017-06-02 21:52
all this stuff has to be rock solid.

**Comment by 0x80** [comment] 2017-06-03 15:30
#1096

**Comment by 0x80** [comment] 2017-06-05 18:18
OK now I'm seeing more sensible error messages like this:

`Page cache miss at /work for key /work. Available keys: /work/shreditor`
`Page cache miss at /work/we-need-us for key /work/we-need-us. Available keys: /work/shreditor`
`Page cache miss at /work/nln-live for key /work/nln-live. Available keys: /work/shreditor`

These are 3 separately reported errors but from a single user. 

Could this be a general issue with the some cache becoming stale after a new deploy? Maybe the service worker is not updated correctly when a new version arrives?

I'm suspecting this because I also recently noticed on a client that images disappeared from my production website, and a cmd+shift+r was needed to get them back. The client had previously visited my website, but with the content hashes in the image filenames, this should never happen right?

What should theoretically happen to the a client's registered service worker after a new version of the site is deployed?

**Comment by 0x80** [comment] 2017-06-12 12:57
@KyleAMathews Have you fixed any bugs recently that might solve this?

I'm still seeing this error reported sometimes. The cache miss also happens at the root `/`. I don't see it often anymore, but that might be because I'm not updating my website multiple times a day anymore and not so many people check it as when it was first released.

It's not a pressing issue. I am just curious if you have a clue.

**Comment by KyleAMathews** [comment] 2017-06-12 17:44
Perhaps this https://github.com/gatsbyjs/gatsby/pull/1133 if you've deployed it already.

**Comment by 0x80** [comment] 2017-06-12 20:16
I don't think I deployed that already. But I'll do that soon and keep an eye out. Awesome work on that PR btw! 👍

**Comment by 0x80** [comment] 2017-06-16 12:05
@KyleAMathews Congrats on the beta! 🎉 

I went to the blog post you wrote only to find a blank page with a navbar. I could observe a few errors in the devtools about a missing layout and something else. A cache clear refresh fixed this. (I didn't remember the exact errors)

But this makes me wonder about the service worker as I mentioned earlier. Should the active client service worker be invalidated somehow after a new deploy? 

Possibly this happened to me because the fix/refactor you did was not part of the code that my browser had in cache, and things might go smoothly from now on. But I thought I'd report it anyway.

**Comment by KyleAMathews** [comment] 2017-06-16 15:53
yeah, this is definitely a problem. Figuring out how to invalidate an old version of the site and refresh. Even without a sw there can be problems if you leave a site open and navigate to a new part. Having a sw just makes the problem of having out-of-date / invalid code more likely.

**Comment by 0x80** [comment] 2017-06-16 19:35
I'm not terribly familiar with SW but I did some searching and found [this example on the registration process](https://github.com/GoogleChrome/sw-precache/blob/master/demo/app/js/service-worker-registration.js). 

It says `updatefound is fired if service-worker.js changes.` but if I look at to how Gatsby registers a the service worker for each page it doesn't use any of that. Could this be the key?

**Comment by KyleAMathews** [comment] 2017-11-29 01:40
PR for this https://github.com/gatsbyjs/gatsby/pull/2996

Also two other issues on this so closing this as least focused #2954, #1807

**Closed by KyleAMathews** 2017-11-29 01:40 UTC
Labels: v1
