### ISSUE TITLE
[gatsby-remark-images][gatsby-plugin-mdx] browser code not running

### ISSUE THREAD

**Issue by winkerVSbecks** [gatsbyjs/gatsby#16712] opened 2019-08-18 02:38 UTC
# Summary
Hi, I'm trying to setup a mdx blog and wanted to use `gatsby-remark-images` to load images. My `gatsby-config` is below. The plugin seems to be active. The images are loading and I can even see the the low-res placeholder. However, it renders both the placeholder and the actual image below it. This is what it looks like:

<img width="712" alt="Screenshot 2019-08-17 at 10 29 55 PM" src="https://user-images.githubusercontent.com/42671/63219419-a06b5580-c13f-11e9-98b8-4bc0a0712191.png">

It seems like the `gatsby-browser` part of the plugin isn't working. I've even tried adding logging in `node_modules` and that script doesn't seem to run. Would anyone know why? Am I missing something obvious.

### Environment (if relevant)

```
System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - ~/n/bin/node
    npm: 6.10.3 - ~/n/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 67.0.1
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.13.55 => 2.13.55
    gatsby-plugin-feed: ^2.3.6 => 2.3.6
    gatsby-plugin-google-analytics: ^2.1.7 => 2.1.7
    gatsby-plugin-manifest: ^2.2.5 => 2.2.5
    gatsby-plugin-mdx: ^1.0.23 => 1.0.23
    gatsby-plugin-offline: ^2.2.5 => 2.2.5
    gatsby-plugin-react-helmet: ^3.1.3 => 3.1.3
    gatsby-plugin-sharp: ^2.2.10 => 2.2.10
    gatsby-plugin-styled-components: ^3.1.2 => 3.1.2
    gatsby-plugin-twitter: ^2.1.2 => 2.1.2
    gatsby-remark-autolink-headers: ^2.1.3 => 2.1.3
    gatsby-remark-copy-linked-files: ^2.1.4 => 2.1.4
    gatsby-remark-images: ^3.1.12 => 3.1.12
    gatsby-remark-prismjs: ^3.3.5 => 3.3.5
    gatsby-remark-smartypants: ^2.1.2 => 2.1.2
    gatsby-source-filesystem: ^2.1.9 => 2.1.9
```

### File contents (if changed)

`gatsby-config.js`:

```js
module.exports = {
  siteMetadata: {
  },
  plugins: [
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `content/posts`,
        path: `${__dirname}/content/posts`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `content/assets`,
        path: `${__dirname}/content/assets`,
      },
    },
    {
      resolve: `gatsby-plugin-styled-components`,
      options: {
        displayName: process.env.NODE_ENV !== `production`,
        fileName: false,
      },
    },
    {
      resolve: `gatsby-plugin-google-analytics`,
      options: {
        trackingId: `UA-22315045-9`,
      },
    },
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-twitter`,
    {
      resolve: `gatsby-plugin-mdx`,
      options: {
        defaultLayouts: { default: path.resolve('./src/components/layout.js') },
        gatsbyRemarkPlugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 1152,
              linkImagesToOriginal: false,
              // sizeByPixelDensity: true,
            },
          },
          `gatsby-remark-autolink-headers`,
          `gatsby-remark-smartypants`,
          `gatsby-remark-prismjs`,
          `gatsby-remark-copy-linked-files`,
        ],
      },
    },
    `gatsby-plugin-sharp`,
  ],
};
```

**Comment by aTechGuide** [comment] 2019-08-18 04:08
Hello @winkerVSbecks 
Even I'm facing the same issue

Repro Steps:
- I've used https://github.com/ChristopherBiscardi/gatsby-starter-mdx-basic starter
- Included `gatsby-remark-images`
```
{
      resolve: `gatsby-plugin-mdx`,
      options: {
        defaultLayouts: { default: path.resolve('./src/components/layout.js') },
        gatsbyRemarkPlugins: [
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 300
            }
          }
        ]
      },
    },
```
- Changed index.mdx to use `gatsby-astronaut.png` inside markdown `![Gatsby Image](../images/gatsby-astronaut.png)`
```
import { Link } from 'gatsby'

import Layout from '../components/layout'
import Image from '../components/image'
import SEO from '../components/seo'

<SEO title="Home" keywords={['gatsby', 'application', 'react']} />

# Hi people

Welcome to your new Gatsby site.

Now go build something great.

![Gatsby Image](../images/gatsby-astronaut.png)

<Link to="/page-2/">Go to page 2</Link>
```
- I see the image and its blur version
![Screenshot 2019-08-18 at 9 34 42 AM](https://user-images.githubusercontent.com/8807997/63219978-db02db80-c19b-11e9-836b-0bdd6976d5d6.png)

**Comment by NickyMeuleman** [comment] 2019-08-18 16:11
Hi!
This sounds like the same issue I had in https://github.com/gatsbyjs/gatsby/issues/16629

That turned out to be a duplicate of https://github.com/gatsbyjs/gatsby/issues/15486
The underlying issue is being though about and will eventually be fixed.
You can follow the discussion in https://github.com/gatsbyjs/gatsby/issues/16242

a **temporary** workaround is adding `gatsby-remark-images` to a `plugins` array in the `gatsby-plugin-mdx` entry in your `gatsby-config`.

**Closed** 2019-08-18 21:54 UTC
