### ISSUE TITLE
Disabling built-in ESLint breaks optional chaining

### ISSUE THREAD

**Issue by aaronadamsCA** [gatsbyjs/gatsby#29264] opened 2021-01-29 12:54 UTC
(I didn't want to clutter #29105 with what might be a different issue, but they may well be related, since we're both observing broken optional chaining.)

## Description

Long ago I disabled Gatsby's built-in ESLint for my sites by following [this how-to](https://www.gatsbyjs.com/docs/how-to/custom-configuration/eslint/#disabling-eslint) (TL;DR, `touch .eslintrc`).

This week, when I switched from Lerna + NPM to Yarn (v1) Workspaces, my Gatsby sites started throwing Webpack parsing errors during `gatsby develop` when encountering optional chaining syntax. Everything is fine during `gatsby build`.

If I remove the blank `.eslintrc`, it resolves the issue.

### Steps to reproduce

I'm not entirely sure. I can't say if the different dependency tree calculated by Yarn is actually the root cause. I tried removing recently added dev dependencies like TypeScript, I tried messing with my root workspace ESLint config, but the only thing that works is removing that blank `.eslintrc` file from each site.

I'm not seeing any detrimental effects from removing the blank `.eslintrc`, I just wanted to report the very strange change in behaviour, because I never would have expected that file to impact Webpack behaviour. It took quite some time to figure out.

### Environment

Node 12.19 with Gatsby 2.29.2 (I'm updating some packages later today, I'll update to confirm whether it's still occurring with newer Gatsby).

**Comment by LekoArts** [comment] 2021-02-01 08:59
This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/29105

**Closed by LekoArts** 2021-02-01 08:59 UTC
Labels: status: triage needed, type: bug

**Comment by aaronadamsCA** [comment] 2021-02-01 09:04
Hey @LekoArts, just noting my issue was on 2.29.2.

#29105 is reporting something that broke as of 2.31.0.

I can continue the conversation in the other ticket, but I had opened a separate issue assuming the differing version ranges might indicate a different issue. Just FYI, thanks.

**Comment by LekoArts** [comment] 2021-02-01 09:18
If you inspect your lock file or check with `yarn why gatsby` you probably won't see `2.29.2` - we didn't touch the logic for this in that version range so yarn followed semver and installed `2.31.0` in your project.

**Comment by aaronadamsCA** [comment] 2021-02-01 09:35
@LekoArts You are correct! Sorry about that. I had not considered that in regenerating my lockfile I'd get a Gatsby upgrade as a side effect, my mistake.

Yes, it worked correctly when I actually had 2.29.2. I'll revise my comment in the other thread.
