### ISSUE TITLE
Unknown Runtime Error when following tutorial part 1 on Safari

### ISSUE THREAD

**Issue by react-learner** [gatsbyjs/gatsby#30721] opened 2021-04-06 15:19 UTC
## Description

In the [Using the `<Link />` component](https://www.gatsbyjs.com/docs/tutorial/part-one/#-using-the-link--component) section of the Gatsby tutorial part 1, after `gatsby develop` succeeded I encountered an Unknown Runtime Error when browsing the local site at localhost:8000: `We couldn't find the correct component chunk with the name "component---src-pages-contact-js"`. 

This is despite a contact.js file present in /src/pages/, with a proper React component Contact defined. Just to make sure there was no human error on my end, I overwrote contact.js and index.js with the content of your code samples—didn't work. `gatsby clean` followed by a hard refresh had no effect. However, no error is displayed if I instead use `http://127.0.0.1:8000/`.

I am running Safari 14.0.2 on macOS 10.15.7. I am working on a fresh Gatsby install, installed via Homebrew. 

### Steps to reproduce

1. Follow part one of the Gatsby tutorial (copy+pasting code samples) until you create and fill contact.js.
2. Run `gatsby develop`.
3. Open http://localhost:8000 on Safari.

### Expected result

Functional website w/ no errors.

### Actual result

A few seconds later (it varies), I see the following error:

<img width="1782" alt="Screen Shot 2021-04-06 at 5 14 06 PM" src="https://user-images.githubusercontent.com/68053732/113734337-8bb84880-96fb-11eb-9693-5324eb09b172.png">

After closing the error, /contact/ becomes inaccessible ("Preparing requested page" endless loop).

### Environment

  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.13.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.7.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.114
    Safari: 14.0.2
  npmPackages:
    gatsby: ^3.1.2 => 3.1.2 
  npmGlobalPackages:
    gatsby-cli: 3.2.0

**Comment by ascorbic** [comment] 2021-04-08 08:57
Hi @react-learner 

Sorry to hear you're running into an issue. Thanks for including the steps to reproduce. However, to help us best begin debugging the underlying cause, it would be really helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it. It can be as simple as pushing your repo to GitHub where we can see it.

Thanks!

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-04-15 12:04
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-04-15 12:04 UTC
Labels: status: needs reproduction, type: bug, type: documentation

**Comment by rogercoathup** [comment] 2021-05-17 18:00
Same problem here trying to follow the Gatsby Tutorial -- for a minimal reproduction see: https://www.gatsbyjs.com/docs/tutorial/part-2/

**Comment by neversitdull** [comment] 2021-05-19 00:26
@rogercoathup I ran into the same issue in Safari when getting to part-2 of the tutorial and creating the About page. Thanks for the heads up on emptying the browser cache... that seemed to resolve it for me.

**Comment by aremu-smog** [comment] 2021-08-17 00:37
Emptying cache in Safari solved this for me as well.

**Comment by jakezien** [comment] 2021-12-28 17:44
I've had this issue in Safari with every Gatsby project I've built. Emptying the cache is a workaround but causes unfortunate side effects, as in Safari it also clears local storage. It'd be great if there were a true fix for this, even/especially if the answer is to change something I'm doing wrong.
