### ISSUE TITLE
Props passed to gatsby-link show on <a> and trigger error on W3 validator

### ISSUE THREAD

**Issue by AniaMakes** [gatsbyjs/gatsby#6989] opened 2018-08-03 14:46 UTC
## Description
We have an internal link that looks like a button. 

The set up is as described here: https://www.npmjs.com/package/gatsby-link.

The component we're rendering is [Styled](https://www.styled-components.com/).

On render, the <a> tag has properties that were passed down get written into <a> (`<a class="sc-iAyFgw kTSalc" background="slateblue" color="white" border="slateblue" href="/our-clients">`). This shows up as error on the W3 validator. If those properties are not passed down, eg `{...other}` is deleted from <GatsbyLink> props, then the button doesn't render the desired style. 

### Steps to reproduce

* Set up internal gatsby-link
* Make it a Styled Component

[Our example]( https://github.com/yldio/website/blob/master/src/components/button.js)

* When calling said Styled Component, add custom properties

[Our example](https://github.com/yldio/website/blob/b2aced2900a0a0eea17af8e80257783eaffee43c/src/sections/what-we-do.js#L151)

* Deploy
* Run deployed url through [W3 validator](https://validator.w3.org/nu/) 

### Expected result

The button should only have class and href (and only other properties that <a> is allowed to have).

`<a class="sc-iAyFgw kTSalc" href="/our-clients">`

### Actual result

The button <a> has properties that were passed in. In this case, there's `background`, `color` and `border`.

`<a class="sc-iAyFgw kTSalc" background="slateblue" color="white" border="slateblue" href="/our-clients">`

### Environment

  System:
    OS: Linux 4.4 Ubuntu 16.04.5 LTS (Xenial Xerus)
    CPU: x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Shell: 4.3.48 - /bin/bash
  Binaries:
    Node: 8.11.3 - /usr/bin/node
    Yarn: 1.7.0 - /usr/bin/yarn
    npm: 5.6.0 - /usr/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
  npmPackages:
    gatsby: ^1.9.273 => 1.9.273 
    gatsby-image: ^1.0.54 => 1.0.54 
    gatsby-link: ^1.6.45 => 1.6.45 
    gatsby-plugin-react-helmet: ^2.0.11 => 2.0.11 
    gatsby-plugin-sass: ^1.0.26 => 1.0.26 
    gatsby-plugin-styled-components: ^2.0.11 => 2.0.11 
    gatsby-source-contentful: ^1.3.54 => 1.3.54 
    gatsby-transformer-sharp: ^1.6.27 => 1.6.27 
  npmGlobalPackages:
    gatsby-cli: 1.1.58

### File contents (if changed)

`gatsby-config.js`: 
```
require('dotenv').config({ path: '.env' });

module.exports = {
  plugins: [
    'gatsby-plugin-sass',
    'gatsby-plugin-styled-components',
    'gatsby-plugin-react-helmet',
    'gatsby-transformer-sharp',
    {
      resolve: 'gatsby-source-contentful',
      options: {
        spaceId: process.env.CONTENTFUL_SPACE,
        accessToken: process.env.CONTENTFUL_TOKEN
      }
    }
  ]
}
```
---
`package.json`: 
```
{
  "private": true,
  "version": "1.0.0",
  "scripts": {
    "build": "gatsby build",
    "ci:build": "yarn build",
    "ci:lint": "yarn lint",
    "ci:start-server": "yarn serve -p 8000",
    "ci:unit-tests": "yarn test",
    "ci:feature-tests": "yarn test:features",
    "develop": "gatsby develop",
    "format": "prettier --config .prettierrc --write '**/*'",
    "serve": "gatsby serve",
    "test": "jest",
    "test:watch": "jest --watch",
    "test:features": "cypress run",
    "lint": "eslint '{src,spec,cypress}/**/*.{js,jsx}' --fix",
    "cypress": "cypress open"
  },
  "husky": {
    "hooks": {
      "pre-commit": "pretty-quick --staged && yarn lint"
    }
  },
  "dependencies": {
    "@fortawesome/fontawesome": "^1.1.8",
    "@fortawesome/fontawesome-svg-core": "^1.2.0",
    "@fortawesome/free-solid-svg-icons": "^5.1.0",
    "@fortawesome/react-fontawesome": "^0.1.0",
    "build-array": "^1.0.0",
    "dotenv": "^6.0.0",
    "gatsby": "^1.9.273",
    "gatsby-image": "^1.0.54",
    "gatsby-link": "^1.6.45",
    "gatsby-plugin-react-helmet": "^2.0.11",
    "gatsby-plugin-sass": "^1.0.26",
    "gatsby-plugin-styled-components": "^2.0.11",
    "gatsby-source-contentful": "^1.3.54",
    "gatsby-transformer-sharp": "^1.6.27",
    "google-map-react": "^1.0.5",
    "graphql-tag": "^2.9.2",
    "lodash.find": "^4.6.0",
    "months": "^2.0.0",
    "param-case": "^2.1.1",
    "prop-types": "^15.6.2",
    "react": "^16.4.1",
    "react-helmet": "^5.2.0",
    "react-styled-flexboxgrid": "^2.4.0",
    "react-youtube": "^7.6.0",
    "recompose": "^0.27.1",
    "remcalc": "^1.0.10",
    "styled-components": "^3.3.3",
    "styled-components-breakpoint": "^2.0.2",
    "styled-components-spacing": "^3.0.1",
    "styled-flex-component": "^2.2.2",
    "styled-is": "^1.1.3"
  },
  "devDependencies": {
    "babel-core": "^6.26.3",
    "babel-jest": "^23.2.0",
    "babel-plugin-module-resolver": "^3.1.1",
    "babel-plugin-remove-attribute": "^0.0.8",
    "babel-plugin-styled-components": "^1.5.1",
    "babel-runtime": "^6.26.0",
    "cypress": "^3.0.1",
    "enzyme": "^3.3.0",
    "enzyme-adapter-react-16": "^1.1.1",
    "enzyme-to-json": "^3.3.4",
    "eslint": "^5.0.1",
    "eslint-config-prettier": "^2.9.0",
    "eslint-config-xo-react": "^0.16.0",
    "eslint-config-xo-space": "^0.19.0",
    "eslint-plugin-chai-friendly": "^0.4.1",
    "eslint-plugin-cypress": "^2.0.1",
    "eslint-plugin-jest": "^21.18.0",
    "eslint-plugin-jsx-a11y": "^6.1.1",
    "eslint-plugin-react": "^7.10.0",
    "husky": "^1.0.0-rc.7",
    "jest": "^23.2.0",
    "jest-styled-components": "^5.0.1",
    "prettier": "^1.13.6",
    "pretty-quick": "^1.6.0",
    "react-dom": "^16.4.1",
    "react-router-dom": "^4.3.1",
    "react-test-renderer": "^16.4.1"
  }
}
```
---

`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by KyleAMathews** [comment] 2018-09-08 05:53
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Closed by KyleAMathews** 2018-09-08 05:53 UTC

**Comment by marcysutton** [comment] 2019-03-16 20:13
@AniaMakes I found this issue while searching, and I'm wondering if it's unique to Gatsby-link or if you can reproduce it with Styled Components alone. Have you looked into isolating it to ensure it's caused by gatsby-link?

That said, I would recommend using a button element if it looks like a button, for reasons I describe here: https://marcysutton.com/links-vs-buttons-in-modern-web-applications

**Comment by rroslaniec** [comment] 2019-10-20 15:09
this issue is still here. can somebody re-open this?
