### ISSUE TITLE
Incorrect attribute used for title in Helmet

### ISSUE THREAD

**Issue by qumberhussain** [gatsbyjs/gatsby#27890] opened 2020-11-07 21:20 UTC
## Description

I believe that the following line has the incorrect attribute -> https://github.com/gatsbyjs/gatsby/blob/master/starters/default/src/components/seo.js#L36

### Expected result

I believe the attribute `title` should be `defaultTitle` and statement `defaultTitle={title || defaultTitle}`

**Comment by LekoArts** [comment] 2020-11-09 07:41
Thank you for opening this!

The component works as intended but feel free to modify it to your desired behavior. Since `title` is used everywhere the template will always work.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2020-11-09 07:41 UTC
Labels: type: question or discussion
