### ISSUE TITLE
GraphQL Query Options Reference: 404 on Links to CodeSandBox -> Keep Example running

### ISSUE THREAD

**Issue by muescha** [gatsbyjs/gatsby#25852] opened 2020-07-19 12:29 UTC
## Description

Links to CodeSandBox getting 404, when CodeSandBox App suspends. the app should restarted. 

### Steps to reproduce

- open https://www.gatsbyjs.com/docs/graphql-reference/
- look at iframes
- or open one of the queries ([basic query](https://711808k40x.sse.codesandbox.io/___graphql?query=%7B%0A%20%20site%20%7B%0A%20%20%20%20siteMetadata%20%7B%0A%20%20%20%20%20%20title%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A&explorerIsOpen=false))

### Expected result

- i should see the GraphiQL Explorer

### Actual result

- i get an 404 in iFrames
- the GraphQL endpoint https://711808k40x.sse.codesandbox.io/___graphql is not available: 404

### Workaround

- i can "restart" the app with going to https://711808k40x.sse.codesandbox.io where i see an deploy script and later the example website.
- now i can reload the docs and see the examples

### Note

- i think now you can not see the error because the app is restarted manually
- there is no error until the next time the app is suspended

### Screenshots
<img width="755" alt="page 404" src="https://user-images.githubusercontent.com/184316/87874686-220cd880-c9cc-11ea-9c36-b17857792bcf.png">

<img width="435" alt="iframe source" src="https://user-images.githubusercontent.com/184316/87874685-20431500-c9cc-11ea-8707-8951ffdb04be.png">

**Comment by iamdarshshah** [comment] 2020-07-19 18:36
Hey @muescha It works for me.

>Screenshots:
![Screenshot (38)](https://user-images.githubusercontent.com/25670841/87882232-60ca7f00-ca1c-11ea-9c53-6d93852ba204.png)
![Screenshot (40)](https://user-images.githubusercontent.com/25670841/87882236-6627c980-ca1c-11ea-872d-106c50154b4a.png)

`This is what expected output should look right? Please check it once again and let me know if I am missing out something. Thanks`

**Comment by muescha** [comment] 2020-07-20 13:52
> Note
> - i think now you can not see the error because the app is restarted manually
> - there is no error until the next time the app is suspended

it works now at this moment because i while investigating the issue i "manually" started the app again with calling the root url

**Comment by iamdarshshah** [comment] 2020-07-20 18:08
Okay, Did the issue still exist? because I tried moving forward with the steps you mentioned above in the `steps to reproduce` section, but it worked as expected. Now, I think it works well. and regarding `there is no error until the next time the app is suspended`, can you share the steps to encounter this specific condition?

**Comment by muescha** [comment] 2020-07-20 18:24
i don't know when and why the next time this app will be suspended by CodeSandBox -> so i can not estimate when the error will be next time

**Comment by muescha** [comment] 2020-07-20 18:31
thats the problem to investigate: 
- why it is suspended
- how to avoid
- it's possible to restart while accessing `/___graphql` and not only with a call to the main root url

**Comment by madalynrose** [comment] 2020-07-21 18:37
Hi there @muescha, thank you for reporting this! I can reproduce the problem by looking at that doc. Is this an issue unique to our website or is it rooted in Gatsby itself? 

To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by muescha** [comment] 2020-07-21 18:43
it is an error visible on the gatsby side, so i just opened the page at gatsbyjs.org and see the error.

i think the root of the 404 error is a behavior at CodeSandBox: they suspend an app after a time of inactivity.

i think in this case a minimal reproduction is already there: 
- the example app is still deployed at codesandbox and 
- the iframe with a link to codesandbox is still at the docs page

**Comment by muescha** [comment] 2020-07-21 18:45
the missing part here: that an 404 is not generating a restart of the app. 
only a call to the root of the example app restart the app at CodeSandBox

**Comment by tjcrowder** [comment] 2020-07-27 11:41
As I write this, they're working, presumably because someone manually restarted the app again.

There are other problems with the CodeSandbox integration:

1. It doesn't work by default when using the [Brave browser](https://brave.com), Brave classifies them as trackers. You have do go "shields down" for them to work or they just stick at *Loading...* forever.
2. There's a significant lag (2-10 seconds on my fast connection) between the rest of the documentation appearing and the examples appearing.
3. Coming back to a documentation page you've had open in a tab for a while, the code blocks are just missing (literally just white space where they should be) until/unless you refresh the page.
4. The sample code isn't **in** the page, which is a problem for searches.

Although it's really cool and handy when it works, it seems like relying on a third-party service integration for essential documentation is problematic. :-) I suggest including the examples as marked up code in the page itself, and either providing a link to the CodeSandbox live version (expanding it inline in the page or opening a new tab, etc.), or replacing the static code with the live example when it's done loading, if it can be done without reflow and too much of a flash effect.

I like Gatsby a lot so far, but I've found this aspect of the documentation problematic and frustrating -- even before I ran into the 404s. (Sadly, unlike @muescha, I wasn't smart enough to think to look at the page source and go to CodeSandbox directly.)

**Comment by muescha** [comment] 2020-08-16 13:34
not stale

**Comment by John-Di** [comment] 2020-09-02 02:47
I'm seeing 404 as well. Shame. I was really looking forward to this page. It's reason I decided to go through the tutorial from start to finish as I'm pretty new to Gatsby, React and GraphQL as a whole 😅

**Comment by LekoArts** [comment] 2020-09-09 11:40
We've switched the embeds over to [Gatsby Cloud](https://www.gatsbyjs.com/cloud/) so hosting this on our own now. We'll keep them as we think that the documentation makes more sense in this form rather than static code blocks.

The codesandbox and embed to GraphiQL was linked in the first paragraph for a long time now for quicker access :)

Hence I'll close this one.

**Closed by LekoArts** 2020-09-09 11:40 UTC
Labels: status: confirmed, status: needs more info, topic: website, type: bug
