### ISSUE TITLE
[docs] The referenced repo in the Gatsby Theme - Getting Started tutorial no longer exists.

### ISSUE THREAD

**Issue by billyjacoby** [gatsbyjs/gatsby#13916] opened 2019-05-08 01:06 UTC
## Description

When trying to follow the [Gatsby Themes - Getting Started](https://www.gatsbyjs.org/docs/themes/getting-started/) tutorial, the GitHub repo referenced does not exist.

### Steps to reproduce

The first line in this tutorial, in regards to scaffolding out a Gatsby theme says:
`gatsby new my-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme`

However, the repo "https://github.com/gatsbyjs/gatsby-starter-blog-theme" no longer exists.

### Expected result

You should be able to start a new Gatsby site from the referenced repo to begin scaffolding out a custom theme.

### Actual result

The referenced repository does not exist. 

### Environment

Not applicable.

I would love to issue the PR to correct this in the docs, but I want to make sure that I'm linking to the correct thing first. 

I would assume that the right repo to start the new Gatsby project from would be here:

`https://github.com/gatsbyjs/gatsby/tree/master/themes/gatsby-starter-theme-blog-mdx`

Since the tutorial references scaffolding a starter?

**Comment by LekoArts** [comment] 2019-05-08 07:43
Duplicate of https://github.com/gatsbyjs/gatsby/issues/13481#issuecomment-484827476 :)
Therefore I'm closing this. Thanks for the issue though!

**Closed by LekoArts** 2019-05-08 07:43 UTC
Labels: type: documentation
