### ISSUE TITLE
gatsby develop got stuck... please help

### ISSUE THREAD

**Issue by aks84** [gatsbyjs/gatsby#7684] opened 2018-08-27 22:09 UTC
![gatsby wordpress error](https://user-images.githubusercontent.com/11679963/44689038-c94c9380-aa73-11e8-9abb-3d0b9e95698a.png)

**Comment by btk** [comment] 2018-08-28 08:00
#2097 #7271 #4666

Might be various reasons it might be hanging there, biggest one, you might have a lot of image files in your source wordpress site. If not 

https://github.com/gatsbyjs/gatsby/blob/46290c2b0e7894fca036bdcc658a5d1936c4221f/packages/gatsby-source-filesystem/src/create-remote-file-node.js#L252

This promise seem to be not resolving for some reason. So what I get past this issue was to add a timeout to resolve this promise in my local copy of this plugin;

```
setTimeout(resolve, 70000)
```

But i don't have enough information about what is the reason.

**Comment by aks84** [comment] 2018-08-29 20:28
The same code is working with a wordpress site with less images...
How can I speed up image processing/loading?
Thanks!

**Comment by pieh** [comment] 2018-08-30 00:34
I'll close this as duplicate of https://github.com/gatsbyjs/gatsby/issues/6654 - it has some reproduction steps in it.

**Closed by pieh** 2018-08-30 00:34 UTC
Labels: status: needs more info
