### ISSUE TITLE
Gatsby CLI Error

### ISSUE THREAD

**Issue by tomshaw** [gatsbyjs/gatsby#34502] opened 2022-01-15 22:55 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

After installing Gatsby-CLI `npm install -g gatsby-cli` and running `gatsby` there's an unknown error.

> There was an unhandled error and we could not retrieve more information. Please run the command with the --verbose flag again.

### Reproduction Link

N/A

### Steps to Reproduce

1. `npm install -g gatsby-cli` and running `gatsby` there's an unknown error.

### Expected Result

Zero errors.

### Actual Result

An error message. 

> There was an unhandled error and we could not retrieve more information. Please run the command with the --verbose flag again.

### Environment

```shell
Windows 10
Node v16.13.2
```

### Config Flags

None

**Comment by tomshaw** [comment] 2022-01-15 22:56
The verbose flag produces no extra information.

**Comment by LekoArts** [comment] 2022-01-17 07:48
Duplicate of https://github.com/gatsbyjs/gatsby/issues/34088

**Closed by LekoArts** 2022-01-17 07:48 UTC
Labels: type: bug, status: triage needed
