### ISSUE TITLE
different behavior after build

### ISSUE THREAD

**Issue by bjatwork** [gatsbyjs/gatsby#15385] opened 2019-07-03 23:17 UTC
This error occur only after build, on develop everything works ok. 

What can be reasons that  i get different script behavior in "gatsby develop" and after build? 

Code 
` { this.context.data.orderShow  ? <div className="a">A</div> : <div className="b">B</div> }`

gives me output 

`<div class="b">A</div>
`

**Comment by freiksenet** [comment] 2019-07-04 07:56
Hi @bjatwork!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by bjatwork** [comment] 2019-07-04 08:30
thanks. I just fixed it. It was connected to using localStorage in contex before ContextProviderComponent didMount

**Comment by freiksenet** [comment] 2019-07-04 08:45
Awesome, I'll close the issue then. Thank you for using Gatsby!

**Closed by freiksenet** 2019-07-04 08:45 UTC
Labels: status: needs reproduction
