### ISSUE TITLE
fail to run gatsby build

### ISSUE THREAD

**Issue by luhc228** [gatsbyjs/gatsby#32320] opened 2021-07-10 03:15 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I am working on macOS11.4，16G RAM. I am using the gatsby@3.x. When run `npm run build` in local，it occurs this error:

```markdown
success onPostBuild - 0.017s
⠧ Caching JavaScript and CSS webpack compilation
⠏ Caching HTML renderer compilation

<--- Last few GCs --->

[3183:0x1046b8000]   216764 ms: Mark-sweep 4081.0 (4107.1) -> 4077.6 (4107.6) MB, 2318.2 / 2.1 ms  (average mu = 0.087, current mu = 0.003) allocation failure scavenge might not succeed
[3183:0x1046b8000]   219074 ms: Mark-sweep 4081.6 (4107.6) -> 4078.1 (4107.6) MB, 2303.4 / 1.9 ms  (average mu = 0.047, current mu = 0.003) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x1012b7fd5 node::Abort() (.cold.1) [/Users/luhc228/.nvm/versions/node/v14.6.0/bin/node]
 2: 0x1000a3fa9 node::Abort() [/Users/luhc228/.nvm/versions/node/v14.6.0/bin/node]
 3: 0x1000a410f node::OnFatalError(char const*, char const*) [/Users/luhc228/.nvm/versions/node/v14.6.0/bin/node]
 4: 0x1001e57f7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/luhc228/.nvm/versions/node/v14.6.0/bin/node]
 5: 0x1001e5793 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/luhc228/.nvm/versions/node/v14.6.0/bin/node]
 6: 0x100383775 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/luhc228/.nvm/versions/node/v14.6.0/bin/node]
 7: 0x10038523a v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/Users/luhc228/.nvm/versions/node/v14.6.0/bin/node]
 8: 0x100380909 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/luhc228/.nvm/versions/node/v14.6.0/bin/node]
 9: 0x10037e1a1 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/luhc228/.nvm/versions/node/v14.6.0/bin/node]
10: 0x10038ca3a v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/luhc228/.nvm/versions/node/v14.6.0/bin/node]
11: 0x10038cac1 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/luhc228/.nvm/versions/node/v14.6.0/bin/node]
12: 0x10035a487 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/Users/luhc228/.nvm/versions/node/v14.6.0/bin/node]
13: 0x1006d8758 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/Users/luhc228/.nvm/versions/node/v14.6.0/bin/node]
14: 0x100a4faf9 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/luhc228/.nvm/versions/node/v14.6.0/bin/node]
[1]    3182 abort      npm run build
```

### Reproduction Link

https://github.com/luhc228/aitechlab-site/pull/1

### Steps to Reproduce

1. npm install
2. npm run build

### Expected Result

gatsby build successfully

### Actual Result

has GC error

### Environment

```shell
node@14.6.0
npm@6.14.13
macOS@11.4
```

**Comment by luhc228** [comment] 2021-07-10 03:18
Not work on my mac, but work on the cloud: https://www.gatsbyjs.com/dashboard/undefined/sites/9efab30e-f504-4db8-9764-b7a26f6ba50d/builds/a7213386-d192-4bab-a1f5-c6bd3456589f/details#rawLogs

**Comment by MANTENN** [comment] 2021-07-10 03:55
You don't have enough memory on your mac. Increase memory for node. 

https://support.circleci.com/hc/en-us/articles/360009208393-How-can-I-increase-the-max-memory-for-Node-

**Comment by luhc228** [comment] 2021-07-10 04:00
I have try it, but it still has the same error

**Comment by luhc228** [comment] 2021-07-10 04:03
How can I disable `Caching JavaScript and CSS webpack compilation` and `Caching HTML renderer compilation`

**Comment by MANTENN** [comment] 2021-07-10 04:33
> I have try it, but it still has the same error

Try 8GB, 4096 is 4GB try setting it to 8,192

**Comment by MANTENN** [comment] 2021-07-10 04:36
It fails at 4GB, set it as a global env variable in your terminal config file whether it be `.bashrc` or `.zshrc`

> ```gfm
> <--- Last few GCs --->
> 
> [3183:0x1046b8000]   216764 ms: Mark-sweep 4081.0 (4107.1) -> 4077.6 (4107.6) MB, 2318.2 / 2.1 ms  (average mu = 0.087, current mu = 0.003) allocation failure scavenge might not succeed
> [3183:0x1046b8000]   219074 ms: Mark-sweep 4081.6 (4107.6) -> 4078.1 (4107.6) MB, 2303.4 / 1.9 ms  (average mu = 0.047, current mu = 0.003) allocation failure scavenge might not succeed
> ```

**Comment by MANTENN** [comment] 2021-07-10 04:38
Also try updating one of your dependencies it seems like there is a race condition.

**Comment by MANTENN** [comment] 2021-07-10 05:22
@luhc228 try this: https://www.gatsbyjs.com/docs/how-to/performance/improving-build-performance/#3-reducing-build-times-from-schema-creation-image-processing-and-bundle-generation 

set those and lower the numbers from the default respectively. 
| Environment Variable | Default |
| ------------- | ------------- |
| `GATSBY_EXPERIMENTAL_QUERY_CONCURRENCY` |  `4` |
| `GATSBY_CPU_COUNT` | `default is the number of physical cores available on your machine` |

**Comment by luhc228** [comment] 2021-07-10 05:24
> Also try updating one of your dependencies it seems like there is a race condition.

all of my dependencies are the latest version.

**Comment by luhc228** [comment] 2021-07-10 06:23
> @luhc228 try this: https://www.gatsbyjs.com/docs/how-to/performance/improving-build-performance/#3-reducing-build-times-from-schema-creation-image-processing-and-bundle-generation
> 
> set those and lower the numbers from the default respectively.
> 
> Environment Variable	Default
> `GATSBY_EXPERIMENTAL_QUERY_CONCURRENCY`	`4`
> `GATSBY_CPU_COUNT`	`default is the number of physical cores available on your machine`

I ran `GATSBY_CPU_COUNT=2 gatsby build, but it stills has error. Could you help me clone my repo, and check out to the release-next branch, then run the script `gatsby build` to check if there are any errors.

**Comment by MANTENN** [comment] 2021-07-11 21:45
> > @luhc228 try this: https://www.gatsbyjs.com/docs/how-to/performance/improving-build-performance/#3-reducing-build-times-from-schema-creation-image-processing-and-bundle-generation
> > set those and lower the numbers from the default respectively.
> > Environment Variable	Default
> > `GATSBY_EXPERIMENTAL_QUERY_CONCURRENCY`	`4`
> > `GATSBY_CPU_COUNT`	`default is the number of physical cores available on your machine`
> 
> I ran `GATSBY_CPU_COUNT=2 gatsby build, but it stills has error. Could you help me clone my repo, and check out to the release-next branch, then run the script `gatsby build` to check if there are any errors.
I got more than enough memory:

```
➜  aitechlab-site git:(release-next) ✗ yarn build
yarn run v1.22.10
$ gatsby build
success open and validate gatsby-configs - 0.039s
success load plugins - 0.892s
success onPreInit - 0.026s
success initialize cache - 0.004s
success copy gatsby files - 0.078s
success onPreBootstrap - 0.013s
success createSchemaCustomization - 0.012s
success Checking for changed pages - 0.001s
success source and transform nodes - 0.119s
success building schema - 0.404s
success createPages - 0.001s
success createPagesStatefully - 0.043s
info Total nodes: 167, SitePage nodes: 5 (use --verbose for breakdown)
success Checking for changed pages - 0.001s
success Cleaning up stale page-data - 0.002s
success update schema - 0.064s
success onPreExtractQueries - 0.001s
success extract queries from components - 1.742s
success write out redirect data - 0.612s
warn The icon(src/assets/images/icon.png) you provided to 'gatsby-plugin-manifest' is not square.
The icons we generate will be square and for the best results we recommend you provide a square icon.

success Build manifest and related icons - 0.069s
success onPostBootstrap - 2.449s
info bootstrap finished - 9.052s
success run static queries - 0.011s - 1/1 87.81/s
success run page queries - 0.005s - 1/1 203.13/s
success write out requires - 0.006s
warn undefined
Css Minimizer Plugin: postcss-svgo: /aitechlab-site/styles.1617e6e0b4ff9914cc63.css:18390:3: Error: Plugin name should be specified
warn undefined
Css Minimizer Plugin: postcss-svgo: aitechlab-site/styles.1617e6e0b4ff9914cc63.css:26353:5: Error: Plugin name should be specified
success Building production JavaScript and CSS bundles - 28.372s
success Rewriting compilation hashes - 0.001s
success Building HTML renderer - 4.889s
success Building static HTML for pages - 0.311s - 5/5 16.08/s
success Delete previous page data - 0.001s
success onPostBuild - 0.006s
info Done building in 43.091634521 sec

✨  Done in 43.42s.
```

**Comment by tjands** [comment] 2021-07-13 04:48
Im getting this same issue when updating from gatsby 3.7... Im not sure yet but it looks like its something to do with the fact that might sight has a butt load of images.

Building on my much more powerful server went through with no issues

**Comment by luhc228** [comment] 2021-07-14 02:17
I have lock the gatsby version to 3.6.2. It works.

**Comment by LekoArts** [comment] 2021-07-19 08:51
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by andrecasal** [comment] 2021-08-13 14:59
I'm getting this issue on a MacBook Pro with macOS 11.5.1 (Big Sur).
Node 16.6.0
Gatsby CLI version: 3.10.0
Gatsby version: 3.10.2 Note: this is the Gatsby version for the site at: /Users/andrecasal/Desktop/software-engineering-boss

Error message:
```
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10f7bfde8 node::Abort() [/usr/local/Cellar/node/16.6.0/bin/node]
 2: 0x10f7bff63 node::OnFatalError(char const*, char const*) [/usr/local/Cellar/node/16.6.0/bin/node]
 3: 0x10f8fcba5 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/Cellar/node/16.6.0/bin/node]
 4: 0x10f8fcb4f v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/Cellar/node/16.6.0/bin/node]
 5: 0x10fa396c9 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/Cellar/node/16.6.0/bin/node]
 6: 0x10fa3877f v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/Cellar/node/16.6.0/bin/node]
 7: 0x10fa40682 v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/Cellar/node/16.6.0/bin/node]
 8: 0x10fa406de v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/usr/local/Cellar/node/16.6.0/bin/node]
 9: 0x10fa1ab4c v8::internal::FactoryBase<v8::internal::Factory>::NewRawTwoByteString(int, v8::internal::AllocationType) [/usr/local/Cellar/node/16.6.0/bin/node]
10: 0x10fc1c607 v8::internal::String::SlowFlatten(v8::internal::Isolate*, v8::internal::Handle<v8::internal::ConsString>, v8::internal::AllocationType) [/usr/local/Cellar/node/16.6.0/bin/node]
11: 0x10f90fc47 v8::String::Utf8Length(v8::Isolate*) const [/usr/local/Cellar/node/16.6.0/bin/node]
12: 0x10f7a042f node::Buffer::(anonymous namespace)::ByteLengthUtf8(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/Cellar/node/16.6.0/bin/node]
13: 0x10fecdc8c Builtins_CallApiCallback [/usr/local/Cellar/node/16.6.0/bin/node]
14: 0x11510f6b3 
15: 0x10fecbb2b Builtins_InterpreterEntryTrampoline [/usr/local/Cellar/node/16.6.0/bin/node]
16: 0x1152283c6 
zsh: abort      npm run develop
```

Let me know if any more info is necessary to reproduce this issue.

**Comment by LekoArts** [comment] 2021-08-30 07:06
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-08-30 07:06 UTC
Labels: type: bug, status: needs reproduction

**Comment by divyadaglia-unbxd** [comment] 2022-05-30 16:24
Hi. I am seeing this issue, I increased my node memory size as well.
