### ISSUE TITLE
Migration to gatsby-plugin-image causes `Target container is not a DOM element.` error message

### ISSUE THREAD

**Issue by piemasters** [gatsbyjs/gatsby#30891] opened 2021-04-15 16:39 UTC
## Description

Having migrated from gatsby-image to gatsby-plugin-image, despite the images loading I get the following runtime errors:

```
Uncaught (in promise) Error: Target container is not a DOM element.
    at render (react-dom.development.js:26091)
    at m (lazy-hydrate.tsx:91)
    at eval (gatsby-image.browser.tsx:93) 
```

This error occurs when navigating away from a simple page like:

```
const APage = ({ data }: { data: any }): React.ReactNode => {
  const queryImage =
    data.posts.edges[0].node.frontmatter.featuredImage.childImageSharp
      .gatsbyImageData;

  return (
    <div>
      <div>
        <div>Page A</div>
        <Link to="/b">To B</Link>
      </div>
      <GatsbyImage
        alt={data.posts.edges[0].node.frontmatter.title}
        image={queryImage}
      />
    </div>
  );
};

export default APage;

export const pageQuery = graphql`
  query {
    posts: allMdx(
      sort: { fields: [frontmatter___date], order: DESC }
      limit: 1
      filter: { frontmatter: { published: { eq: true } } }
    ) {
      edges {
        node {
          frontmatter {
            title
            featuredImage {
              childImageSharp {
                gatsbyImageData(layout: CONSTRAINED)
              }
            }
          }
        }
      }
    }
  }
`;

```

I have console logged the result of the query (`image`), put it into a variable and used that with GatsbyImage instead and the error does not occur. I found the only difference between my saved object and the query result is `srcSet` contains carriage returns between values in the string for the query result, while the object I saved has spaces:

```
"/static/35bb649151d59c08d4ab7ad171da7985/ba134/iron-battlefield-cover.webp 450w,↵
/static/35bb649151d59c08d4ab7ad171da7985/e7f7d/iron-battlefield-cover.webp 900w,↵
/static/35bb649151d59c08d4ab7ad171da7985/fc420/iron-battlefield-cover.webp 1800w"
```

### Steps to reproduce

1. Go to https://minitothemax.app/a
2. Open console
3. Click on link 'To B' which will navigate to https://minitothemax.app/b

Codebase: https://github.com/piemasters/MiniToTheMax
Page A - https://github.com/piemasters/MiniToTheMax/blob/master/src/pages/a.tsx
Page B - https://github.com/piemasters/MiniToTheMax/blob/master/src/pages/b.tsx

### Expected result

Page A should load with an image. When clicking the link to page B no error should be thrown.

### Actual result

Page A loads with an image. When clicking to link to page B the above error is thrown.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```
$ gatsby info --clipboard

  System:
    OS: Windows 10 10.0.19042
    CPU: (32) x64 AMD Ryzen 9 3950X 16-Core Processor
  Binaries:
    Node: 12.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.7.4 - /c/ProgramData/Anaconda3/python
  Browsers:
    Chrome: 89.0.4389.114
    Edge: Spartan (44.19041.906.0), Chromium (89.0.774.76)
  npmPackages:
    gatsby: 3.3.0 => 3.3.0
    gatsby-image: 3.3.0 => 3.3.0
    gatsby-plugin-catch-links: 3.3.0 => 3.3.0
    gatsby-plugin-emotion: 6.3.0 => 6.3.0
    gatsby-plugin-eslint: 3.0.0 => 3.0.0
    gatsby-plugin-google-gtag: 3.3.0 => 3.3.0
    gatsby-plugin-image: 1.3.0 => 1.3.0
    gatsby-plugin-manifest: 3.3.0 => 3.3.0
    gatsby-plugin-mdx: 2.3.0 => 2.3.0
    gatsby-plugin-offline: 4.3.0 => 4.3.0
    gatsby-plugin-react-helmet: 4.3.0 => 4.3.0
    gatsby-plugin-react-svg: 3.0.1 => 3.0.1
    gatsby-plugin-robots-txt: 1.5.5 => 1.5.5
    gatsby-plugin-sass: 4.3.0 => 4.3.0
    gatsby-plugin-sharp: 3.3.0 => 3.3.0
    gatsby-plugin-sitemap: 3.3.0 => 3.3.0
    gatsby-plugin-transition-link: 1.20.5 => 1.20.5
    gatsby-plugin-typescript: 3.3.0 => 3.3.0
    gatsby-remark-images: 4.2.0 => 4.2.0
    gatsby-source-filesystem: 3.3.0 => 3.3.0
    gatsby-transformer-sharp: 3.3.0 => 3.3.0
```

**Comment by LekoArts** [comment] 2021-04-16 07:06
Duplicate of https://github.com/gatsbyjs/gatsby/issues/29982 - please comment there. Thanks!

**Closed by LekoArts** 2021-04-16 07:06 UTC
Labels: status: triage needed, type: bug
