### ISSUE TITLE
failed Building production JavaScript and CSS bundles - 0.104s   ERROR #98123  WEBPACK  Generating JavaScript bundles failed  Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by mitul-srashtasoft** [gatsbyjs/gatsby#29006] opened 2021-01-13 04:08 UTC
failed Building production JavaScript and CSS bundles - 0.104s

 ERROR #98123  WEBPACK

Generating JavaScript bundles failed

Cannot read property 'includes' of undefined

**Comment by LekoArts** [comment] 2021-01-13 09:46
Hi!

Please follow the issue template for bugs and [provide a minimal reproduction][reproduction] and we'll be able to take another look.

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-01-22 09:58
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2021-01-22 09:58 UTC
Labels: status: needs reproduction, type: bug
