### ISSUE TITLE
Error: ENOTDIR: not a directory, unlink '/gatsbysite/public/svg/grid-bg.svg'

### ISSUE THREAD

**Issue by IainIsCreative** [gatsbyjs/gatsby#3479] opened 2018-01-11 16:45 UTC
## Description

Okay this is a weird one for me...if I place an SVG file...anywhere, including `static`, Gatsby throws the following error (Note: usernames and directories are omitted for anonymity):

```shell
error ENOTDIR: not a directory, unlink '/gatsbysite/public/svg/grid-bg.svg'


  Error: ENOTDIR: not a directory, unlink '/gatsbysite/public/svg/grid-bg.svg'

error UNHANDLED REJECTION


  Error: ENOTDIR: not a directory, unlink '/gatsbysite/public/svg/grid-bg.svg'
```

If it's any help, I am using `gatsby-starter` for this project. Am I missing something here? I'm not completely understanding what's happening here...

### Expected behavior

As far as I can tell, this should not be a problem and SVGs should be fine. However for some reason Gatsby is throwing a hissy fit of sorts.

**Comment by KyleAMathews** [comment] 2018-01-11 16:47
That's unexpected...

What are the steps to reproduce this?

**Comment by IainIsCreative** [comment] 2018-01-11 16:51
The only thing I've done is placing an SVG under `static`. That's it. 😆

**Comment by KyleAMathews** [comment] 2018-01-11 16:55
Could be a file permission error perhaps. Do other files fail as well?

**Comment by IainIsCreative** [comment] 2018-01-11 17:18
No, I think it's okay with images like JPGs. I'll try with PNGs and GIFs as well. JPGs are placed under `static/images` and get output to `public/images` — I'm hoping that's the correct output as it also outputs an empty `static` folder!

**Comment by IainIsCreative** [comment] 2018-01-11 17:22
GIFs and JPGs are being output fine.

**Comment by shendepu** [comment] 2018-01-19 03:59
I experienced this as well, while I add a file and delete the file in `static` folder. Then I found that the file link still exists in `public` folder. After deleting it in public folder, the error is gone.

**Comment by KyleAMathews** [comment] 2018-09-08 04:08
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Closed by KyleAMathews** 2018-09-08 04:08 UTC
