### ISSUE TITLE
Confusing error on onCreateNode / createFilePath

### ISSUE THREAD

**Issue by camburns** [gatsbyjs/gatsby#27093] opened 2020-09-26 08:42 UTC
###  Description

When providing a data source via a headless CMS and running "gatsby develop", the node.fileAbsolutePath (on gatsby-node.js) is empty, this produces an unclear error, that I (and many others - based on my searching online) have struggled with:

"TypeError: Cannot read property 'replace' of undefined"
 
This is unclear and intimidating to new developers (that are working through the tutorials).

### Steps to reproduce:

A fresh install with the following code on gatsby-node.js:

exports.onCreateNode = ({ node, getNode, actions }) => {
  const { createNodeField } = actions

  // create a slug for each drupal entity
  if (node.internal.type === `node__itinerary`) {
    const slug = createFilePath({
      node,
      getNode,
      basePath: `contentz`,
    })

etc...

### Expected result

clear error:
"fileAbsolutePath of the node provided is null, unable to generate a filePath"

### Actual result

error in console:

TypeError: Cannot read property 'replace' of undefined

### Environment

when running: "gatsby develop"

**Comment by pieh** [comment] 2020-09-28 15:34
I'm a little confused - `createFilePath` doesn't use `fileAbsolutePath` ( https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-filesystem/src/create-file-path.js ). So I'm not sure that diagnosis here that it's `createFilePath` / `fileAbsolutePath` is correct?

I do agree about not great error on this. Are you able to provide way to reproduce this error?

**Comment by camburns** [comment] 2020-09-29 06:00
yes, that's correct it is not needed, I removed it after I realized it wasn't needed (I'm a new gatsby developer) - this wasn't immediately obvious when integrating my Drupal source and from what I've seen online (while searching for a solution) a few other developers have bumped into this error not knowing what it means.

== fileAbsolutePath question ==
From memory, I think this was my guess of what was missing and thus causing the error (as it existed when creating slugs for physical files) - it looks like I was mistaken then.

== reproduce ==
I provided code above - the only other piece needed was the plugin (from memory):

    {
      resolve: 'gatsby-source-drupal',
      options: {
        baseUrl: 'https://site??.pantheonsite.io/',
        apiBase: 'jsonapi', // endpoint of Drupal server
      }

Hope it helps.

**Comment by LekoArts** [comment] 2020-10-12 07:41
Please [provide a minimal reproduction][reproduction] and we'll be able to take another look.

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2020-10-26 08:59
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-10-26 08:59 UTC
Labels: status: needs reproduction, topic: filesystem, type: bug
