### ISSUE TITLE
Issue with <StaticImage /> and gatsby-plugin-image

### ISSUE THREAD

**Issue by juliobarbagallo** [gatsbyjs/gatsby#34922] opened 2022-02-24 13:18 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hello team and everyone here, I just came here while I was following the Tutorial from the Gatby's home page, on Part 3 using
On the terminaI, using gatsby develop got this:
` ERROR

The file loaded from https://pbs.twimg.com/media/E1oMV3QVgAIr1NT?format=jpg&name=large is not a valid image type.
Found "application/octet-stream"`

On the browser don't have errors, but 2 warnings:
static-image.server.tsx:51 No data found for image "https://pbs.twimg.com/media/E1oMV3QVgAIr1NT?format=jpg&name=large" Image not loaded https://pbs.twimg.com/media/E1oMV3QVgAIr1NT?format=jpg&name=large

The code is exactly the one from the Gatsby's tutorial page.
<Layout pageTitle="Home Page"> <p>I'm making this by following the Gatsby Tutorial.</p> <StaticImage alt="Clifford, a reddish-brown pitbull, posing on a couch and looking stoically at the camera" src="https://pbs.twimg.com/media/E1oMV3QVgAIr1NT?format=jpg&name=large" /> </Layout>

I tried removing node_modules, cleaning the cache and also with another image from unsplash and the same.

### Reproduction Link

https://github.com/juliobarbagallo/gatsby-test

### Steps to Reproduce

1. Follow Gatby's tutorial on Part 3, adding plug ins
run with gatby develop

### Expected Result

See the image of the dog.

### Actual Result

Everything is displayed but the picture.

### Environment

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (4) x64 Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.10
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (98.0.1108.56)
  npmPackages:
    gatsby: ^4.8.0 => 4.8.0 
    gatsby-plugin-image: ^2.8.0 => 2.8.0 
    gatsby-plugin-sharp: ^4.8.0 => 4.8.0 
    gatsby-source-filesystem: ^4.8.0 => 4.8.0 
  npmGlobalPackages:
    gatsby-cli: 4.8.0
```

### Config Flags

module.exports = {
    siteMetadata: {
      title: "My First Gatsby Site",
    },
    plugins: [
      "gatsby-plugin-image",
      "gatsby-plugin-sharp",
    ],
  };

**Comment by tyhopp** [comment] 2022-02-25 04:43
Hi @juliobarbagallo, thanks for this. I'll close since this is a duplicate of https://github.com/gatsbyjs/gatsby/issues/34917, please follow that ticket for updates.

**Closed by tyhopp** 2022-02-25 04:43 UTC
Labels: type: bug, status: triage needed
