### ISSUE TITLE
How to deploy a Gatsby app to Google App Engine?

### ISSUE THREAD

**Issue by iAnthonyCoder** [gatsbyjs/gatsby#22711] opened 2020-04-01 05:16 UTC
Hi, I was looking around the web but I didn't find anything useful, the point is, what I must put inside the App.yaml file to serve my app, the one of the google documentation doesnt work for SPA's, the directories don't work

https://cloud.google.com/appengine/docs/standard/python/getting-started/hosting-a-static-website

I heard with a docker config should work but, what i can do? Thanks for reply.

**Comment by arthurjdam** [comment] 2020-04-01 18:45
Though not directly answering the question; it would be a lot easier and cheaper to host on Google Cloud Storage instead of App Engine: [https://cloud.google.com/storage/docs/hosting-static-website](https://cloud.google.com/storage/docs/hosting-static-website)

**Comment by iAnthonyCoder** [comment] 2020-04-02 02:13
> Though not directly answering the question; it would be a lot easier and cheaper to host on Google Cloud Storage instead of App Engine: https://cloud.google.com/storage/docs/hosting-static-website

Even if you are right, that google guide is for usual static websites, remember gatsby is based on react and doing things by that way will breack the routes

**Comment by arthurjdam** [comment] 2020-04-02 03:21
It already takes that into account if you assign `MainPageSuffix` to "index.html", which is described half-way down the page: https://cloud.google.com/storage/docs/hosting-static-website#index-page

**Comment by iAnthonyCoder** [comment] 2020-04-06 12:10
Any idea about this please? @KyleAMathews

**Comment by LekoArts** [comment] 2020-04-06 13:08
Thank you for opening this!

It seems like App Engine expects files in specific folders / folder structures and in a more basic format you'd typically achieve by manually creating the page from scratch. As Gatsby bundles the CSS/JS & creates the HTML files automatically I doubt that this is the right approach to host on Google. As Arthur said you should probably use Google Cloud Storage instead.

If you would want to try it nevertheless I'd recommend asking in Google-specific communities or in their support (communities).

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2020-04-06 13:08 UTC
Labels: type: documentation, type: question or discussion

**Comment by loozhengyuan** [comment] 2020-06-11 12:10
I know the issue is closed but I recently encountered this when I had to serve the site on GAE, so I thought I'll leave this here to help anyone who might need some guidance on this.

Typically, you would have your static assets in the `.public` directory. In your `app.yaml` GAE configuration file, you should define it like that:

```python
runtime: python37
service: my-new-gatsby-site
handlers:
- url: /
  static_files: .public/index.html
  upload: .public/index.html
- url: /(.*)
  static_files: .public/\1
  upload: .public/(.*)
```

Thereafter, you can run `gcloud app deploy`, which will then upload all static assets to GAE and serve the assets accordingly.

You can use any other `runtime`, but this was working fine for me.

**Comment by mrbiotech** [comment] 2020-08-05 23:23
@iAnthonyCoder's request is still important for a different reason: Gcloud-based JAMStack.

- Headless CMS (Directus, Strapi, etc...)
- Google Cloud SQL database
- Static content hosting on Google Cloud Storage behind a Load Balancer
- AND Gatsby to build static content from the headless CMS/db, on App Engine

Publishing content in the headless CMS could trigger an App Engine-based Gatsby instance to build content to the Google Cloud Storage bucket. Seems pretty much in line with what a modern cloud-based JAMStack is all about!

**Comment by nodechef** [comment] 2021-02-18 01:49
> I know the issue is closed but I recently encountered this when I had to serve the site on GAE, so I thought I'll leave this here to help anyone who might need some guidance on this.
> 
> Typically, you would have your static assets in the `.public` directory. In your `app.yaml` GAE configuration file, you should define it like that:
> 
> ```yaml
> runtime: python37
> service: my-new-gatsby-site
> handlers:
> - url: /
>   static_files: .public/index.html
>   upload: .public/index.html
> - url: /(.*)
>   static_files: .public/\1
>   upload: .public/(.*)
> ```
> 
> Thereafter, you can run `gcloud app deploy`, which will then upload all static assets to GAE and serve the assets accordingly.
> 
> You can use any other `runtime` but this was working fine for me.

How did you resolve the issue of routing on GAE ?
