### ISSUE TITLE
there are some broken web links

### ISSUE THREAD

**Issue by fatihyildizhan** [gatsbyjs/gatsby#21891] opened 2020-03-02 00:50 UTC
1- Open this URL : https://www.gatsbyjs.org/showcase/
2- Click any Category and I see a blank page

* Sometimes, it refreshes multiples times and browser-back button disables.

**Comment by b0nbon1** [comment] 2020-03-02 04:56
@fatihyildizhan I think this one is being fixed by this issue https://github.com/gatsbyjs/gatsby/issues/21867.

**Comment by LekoArts** [comment] 2020-03-02 08:42
This is a duplicate of #21867

**Closed by LekoArts** 2020-03-02 08:42 UTC
Labels: type: bug
