### ISSUE TITLE
[www - gatsby-transformer-screenshot] Puppeteer cannot capture Chinese or UTF-8 properly

### ISSUE THREAD

**Issue by rayriffy** [gatsbyjs/gatsby#15700] opened 2019-07-14 17:41 UTC
## Description

Puppeteer itself cannot recognize UTF-8 character (Chinese, Thai etc.) and fallback to square character instead

![Screenshot](https://cdn.discordapp.com/attachments/577046038716874762/600014726050742296/unknown.png)

![Screenshot](https://cdn.discordapp.com/attachments/577046038716874762/600015547895119895/unknown.png)

I think there's a way to resolve this by set system locale to UTF-8 in `Dockerfile` before Gatsby site was built, I will launch PR there.

### Steps to reproduce

Capture some Chinese sites screenshot by using `gatsby-transformer-screenshot`

### Expected result

I will use https://arnondora.in.th as an example

![Screenshot](https://cdn.discordapp.com/attachments/577046038716874762/600016684287393805/unknown.png)

### Actual result

![Screenshot](https://media.discordapp.net/attachments/577046038716874762/600016945969889300/d98e2c1a3229e3eff6fc2f096c464169.png)

### Environment

I think there's no need here

**Comment by sidharthachatterjee** [comment] 2019-07-15 22:46
Thank you for opening this! 

Like @wardpeet mentioned on the pull request, we run this (`/packages/gatsby-transformer-screenshot/lambda/index.js` ) on lambda. 

We're open to a complete rewrite of the service that's more reliable and works with UTF-8 characters.

**Comment by missmatsuko** [comment] 2019-07-15 23:46
Same issue already exists: https://github.com/gatsbyjs/gatsby/issues/5929

**Comment by fk** [comment] 2019-07-16 00:58
☝️👌 Thanks @missmatsuko for pointing that out.
Thanks @rayriffy!

Closing as duplicate of #5929, lets continue over there!

**Closed by fk** 2019-07-16 00:58 UTC
Labels: help wanted, status: confirmed, type: bug
