### ISSUE TITLE
Gatsby 3: gatsby-plugin-image partially rerendering images

### ISSUE THREAD

**Issue by creotip** [gatsbyjs/gatsby#29982] opened 2021-03-04 10:52 UTC
## Description

We migrated to gatsby3 and to the new gatsby-plugin-image. Everything works fine except the following issue:

There is 48 cards with GatsbyImage component. The cards with the images are rendered just fine, but after clicking sort by, the page is re-rendered and some cards are empty, gatsby-image-wrapper is empty, which means that GatsbyImage is not re-rendered and the following error is shown in the console:
```
DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
```

### Steps to reproduce

https://603fcf118d59a000077eecb0--gatsbys-adika-torefront.netlify.app/categories/clothing__tops__all/

click on sort by , or another filter

Here is minimal example repo:
https://github.com/creotip/gatsby-3-images-error

### Expected result
Should re-render images

### Actual result

Partiallly re-rendered images

### Environment

  System:
    OS: macOS 11.1
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.3 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.9 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.72
    Firefox: 86.0
    Safari: 14.0.2
  npmPackages:
    gatsby: ^3.0.0 => 3.0.0 
    gatsby-image: ^3.0.0 => 3.0.0 
    gatsby-plugin-image: ^1.0.0 => 1.0.0 
    gatsby-plugin-lodash: ^4.0.0 => 4.0.0 
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0 
    gatsby-plugin-material-ui: ^2.1.10 => 2.1.10 
    gatsby-plugin-offline: ^4.0.0 => 4.0.0 
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-remove-fingerprints: 0.0.2 => 0.0.2 
    gatsby-plugin-resolve-src: ^2.1.0 => 2.1.0 
    gatsby-plugin-root-import: ^2.0.6 => 2.0.6 
    gatsby-plugin-sharp: ^3.0.0 => 3.0.0 
    gatsby-plugin-styled-components: ^4.0.0 => 4.0.0 
    gatsby-source-filesystem: ^3.0.0 => 3.0.0 
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0

**Comment by Miamnamina** [comment] 2021-03-04 16:20
I have a similar issue: when I manually resize the browser - or in general  - mobile images aren't loaded. just the black wrapper

**Comment by popeating** [comment] 2021-03-05 12:45
Got a similar issue, re-rendering  the image (for example loading a new set of images that reaplace the ones on page, or similar things) cause the insertbefore error

i got this sample:
```
import React, { useState } from 'react';
import { graphql } from 'gatsby';
import { GatsbyImage, getImage } from 'gatsby-plugin-image';
const Test = ({ data }) => {
  const dochange = () => {
    console.log('change');
    setNum(Math.floor(Math.random() * (10 - 20)) + 20);
  };
  const [num, setNum] = useState(Math.floor(Math.random() * (10 - 20)) + 20);
  console.log(data.allFile.edges[num].node);
  const myimage = getImage(data.allFile.edges[num].node);
  console.log(myimage);
  return (
    <div>
      <GatsbyImage image={myimage} alt="test" />
      <a href="#" onClick={dochange}>
        change
      </a>
    </div>
  );
};

export const pquery = graphql`
  query {
    allFile(filter: { relativePath: { regex: "/p//" } }) {
      edges {
        node {
          childImageSharp {
            gatsbyImageData(
              formats: [AUTO, WEBP, AVIF]
              width: 400
              placeholder: BLURRED
            )
          }
        }
      }
    }
  }
`;

export default Test;
```

where the image is "reloaded" with a click that causes the error; the rendered HTML after a couple of clicks starts to missing pieces and so when the re-render try to remove something that isnt on the page i got the error

**Comment by creotip** [comment] 2021-03-06 06:43
Created a minimal example in this repository the throwing erros:
https://github.com/creotip/gatsby-3-images-error

Btw, codesandbox doesn't supporting gatsby 3

**Comment by laurieontech** [comment] 2021-03-19 16:59
A fix for this is now available in gatsby-plugin-image@next

**Comment by popeating** [comment] 2021-03-19 21:51
Tried the fix, it looks it works for the specific error, but actually totally break the app, passing from page to page giving the following error:
`Uncaught (in promise) Error: Target container is not a DOM element. at render (react-dom.development.js:26086)`
reverting to 1.0.0 solve the linking between pages error

**Comment by creotip** [comment] 2021-03-19 22:47
@laurieontech Updated the repo and deployed to netlify. So far looks promising:
https://gatsby-plugin-image-fix.netlify.app/

https://github.com/creotip/gatsby-3-images-error

**Comment by laurieontech** [comment] 2021-03-22 13:02
@popeating Do you have a reproduction I can clone?

**Comment by chrisvince** [comment] 2021-03-23 13:33
@laurieontech I'm getting this issue also. It seems to happen when the GatsbyImage is unmounted quickly (note the 10ms setTimeout, I don't get an error if I try a, say, 1000ms).
I got this error because an image was being unmounted after a redux state update, but this is a more simple reproduction.

Example:
```
import React, { useState, useEffect } from 'react'
import { GatsbyImage } from 'gatsby-plugin-image'

const Component = () => {
    const [ test, setTest ] = useState(true)

    useEffect(() => {
        setTimeout(() => {
            setTest(false)
        }, 10)
    }, [])

    return (
        <div>
            {test && (
                <GatsbyImage
                    alt={product.title}
                    image={variant.image.localFile.childImageSharp.gatsbyImageData}
                />
            )}
        </div>
    )
}
```

**Comment by popeating** [comment] 2021-03-23 15:24
From what i noticed (and luckly solved) this new plugin is a bit more "precise" if you do not unmount everything correctly, in the correct order, and so, it  throws errors
timeout approach may solve, but im refactoring my code to be sure all my useEffect always "clean" correctly

**Comment by laurieontech** [comment] 2021-03-23 15:35
Thanks @chrisvince, I tried that out and wasn't able to reproduce the error. If you have a full reproduction I'd be happy to take a look.

**Comment by chrisvince** [comment] 2021-03-30 17:45
@laurieontech sorry for not getting back to on this, had a busy week last week.

I just installed `1.3.0-next.1` and no longer getting this issue, thanks for your help!

**Comment by philliprognerud** [comment] 2021-04-06 05:00
@popeating I just started getting this error all over my app, same as your error:
```
react-dom.development.js:26091 Uncaught (in promise) Error: Target container is not a DOM element.
    at render (react-dom.development.js:26091)
    at m (lazy-hydrate.tsx:91)
    at eval (gatsby-image.browser.tsx:92)
```
I'm using `gatsby-plugin-image: ^1.2.0-next.0 => 1.2.0`

**Comment by philliprognerud** [comment] 2021-04-06 05:54
I made an issue for this #30696

**Comment by nrandell** [comment] 2021-04-06 14:20
I'm seeing the same error. In this case when I press the back button in development mode it seems to happen a lot. When using back on a production site it appears to be ok. It's almost as if the unmounting has left a couple of things lying around.

**Comment by AlexMorrisonDev716** [comment] 2021-04-06 17:32
I'm having the same issue with any of the versions mentioned in this thread so far. I'm displaying a grid of posts with an image and when I update the state and display the filtered posts I see: 
`Error in function render in ./node_modules/react-dom/cjs/react-dom.development.js:
Target container is not a DOM element.`

**Comment by CLantigua2** [comment] 2021-04-07 03:44
> I just started getting this error all over my app same as @popeating
> 
> ```
> react-dom.development.js:26091 Uncaught (in promise) Error: Target container is not a DOM element.
>     at render (react-dom.development.js:26091)
>     at m (lazy-hydrate.tsx:91)
>     at eval (gatsby-image.browser.tsx:92)
> ```
> 
> I'm using `gatsby-plugin-image: ^1.2.0-next.0 => 1.2.0`
> 
> edit:
> Upgrading to `gatsby-plugin-image: ^1.3.0-next.1 => 1.3.0-next.1` did not work.
> 
> edit:
> Downgrading to `gatsby-plugin-image: ^1.2.0 => 1.2.0` did not work.
> 
> edit:
> Downgrading to `gatsby-plugin-image: 1.1.2 => 1.1.2` **_WORKED!_**
> 
> Conclusion:
> This error did not come up during a page loads. The error only comes up when images are being unmounted dynamically (ie. in my case triggering an image filter) and then this error is being thrown. This was quite difficult to debug since the error itself gives not hints into what is actually the problem.

This work around worked for me. Hopefully we can get some more attention on this one though.

**Comment by sven5** [comment] 2021-04-08 11:45
> https://gatsby-plugin-image-fix.netlify.app/

In Firefox there are just empty grey boxes

**Comment by ascorbic** [comment] 2021-04-08 12:45
> > https://gatsby-plugin-image-fix.netlify.app/
> 
> In Firefox there are just empty grey boxes

Which version of FF? It's working fine for me.

**Comment by ascorbic** [comment] 2021-04-08 12:48
Can anyone who is still getting this in `gatsby-plugin-image@next` please share a reproduction.

**Comment by sven5** [comment] 2021-04-08 13:14
> Which version of FF? It's working fine for me.

Firefox 78.9.0esr (64-Bit

**Comment by AlexMorrisonDev716** [comment] 2021-04-08 14:08
@sven5 Any chance that link has a corresponding repo? I'm curious to see if something is wrong with my implementation before getting my own environment ready for review.

**Comment by sven5** [comment] 2021-04-08 18:46
Hi @AlexMorrisonDev716 . Sorry this demo site is not in my hands.
@creotip  mentioned this link here, I just tested it. 
Perhaps he can provide a repo.

**Comment by stevepepple** [comment] 2021-04-10 22:08
@ascorbic, here's an example of the error occurring with `gatsby-plugin-image@1.4.0-next.0`:

http://143.198.79.69/our-story/why-vibes/

Here's our setup: 

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (2) x64 DO-Premium-Intel
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.12 - /usr/local/bin/npm
  npmPackages:
    gatsby: ^3.4.0-next.0 => 3.4.0-webpack-split-fix.8+7d6f6d62a5
    gatsby-background-image: ^1.5.0 => 1.5.0
    gatsby-cli: ^3.0.0 => 3.2.0
    gatsby-gravityforms-component: ^3.1.0 => 3.1.0
    gatsby-plugin-build-date: ^1.0.0 => 1.0.0
    gatsby-plugin-bundle-stats: ^2.6.0 => 2.8.0
    gatsby-plugin-client-side-redirect: ^1.1.0 => 1.1.0
    gatsby-plugin-facebook-pixel: ^1.0.5 => 1.0.5
    gatsby-plugin-feed: ^3.0.0 => 3.2.0
    gatsby-plugin-google-analytics: ^3.0.0 => 3.2.0
    gatsby-plugin-google-tagmanager: ^3.0.0 => 3.2.0
    gatsby-plugin-image: ^1.4.0-next.0 => 1.4.0-next.0
    gatsby-plugin-loadable-components-ssr: ^2.1.0 => 2.1.0
    gatsby-plugin-manifest: ^3.2.0 => 3.2.0
    gatsby-plugin-netlify: ^3.3.0-next.0 => 3.3.0-next.1
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0
    gatsby-plugin-react-helmet: ^4.0.0 => 4.2.0
    gatsby-plugin-react-helmet-canonical-urls: ^1.4.0 => 1.4.0
    gatsby-plugin-react-i18next: ^1.1.1 => 1.1.1
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.1
    gatsby-plugin-resolve-src: ^2.1.0 => 2.1.0
    gatsby-plugin-robots-txt: ^1.5.1 => 1.5.5
    gatsby-plugin-sass: ^4.0.0 => 4.2.0
    gatsby-plugin-sass-resources: ^2.0.0 => 2.0.0
    gatsby-plugin-sharp: ^3.2.1 => 3.2.1
    gatsby-plugin-sitemap: ^3.0.0 => 3.2.0
    gatsby-plugin-split-css: ^2.0.0 => 2.0.0
    gatsby-plugin-transition-link: ^1.18.0 => 1.20.5
    gatsby-plugin-use-query-params: ^1.0.1 => 1.0.1
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.5 => 1.0.5
    gatsby-source-filesystem: ^3.2.0 => 3.2.0
    gatsby-source-gravityforms: ^1.0.15 => 1.0.17
    gatsby-source-wordpress: ^5.4.0-next.0 => 5.4.0-next.0
    gatsby-transformer-sharp: ^3.2.0 => 3.2.0
  npmGlobalPackages:
    gatsby-cli: 3.2.0

**Comment by AlexMorrisonDev716** [comment] 2021-04-14 15:00
@stevepepple Looks like there's an issue with these links.

**Comment by iamkratos** [comment] 2021-04-15 13:25
I'm having the same issue as @creotip, but only in development.

[Example Site](https://forayv8temp330.gatsbyjs.io/collections/tops)

When I push to Gatsby Cloud and use the filter on this page, there isn't any error being thrown, but when I run my site in development and try to use the filter (after gatsby clean and a fresh reinstall of npm modules), I receive the error:

`Uncaught (in promise) Error: Target container is not a DOM element.`

and the page goes into an infinite loop before needing a force quit, system info below:

```
  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.128
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.0.0 => 3.0.0
    gatsby-plugin-gatsby-cloud: ^2.0.0 => 2.0.0
    gatsby-plugin-image: ^1.4.0-next.0 => 1.4.0-next.0
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0
    gatsby-plugin-offline: ^4.0.0 => 4.0.0
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^3.0.0 => 3.0.0
    gatsby-plugin-styled-components: ^4.0.0 => 4.0.0
    gatsby-source-filesystem: ^3.0.0 => 3.0.0
    gatsby-source-google-sheets: ^1.1.1 => 1.1.1
    gatsby-source-shopify: ^5.0.0-rc.18 => 5.0.0-rc.19
    gatsby-source-wordpress: ^5.0.0 => 5.0.0
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0
  npmGlobalPackages:
    gatsby-cli: 3.2.0
```

**Comment by piemasters** [comment] 2021-04-16 09:50
I raised the same issue in #30891, sorry for the duplicate I missed this thread as the initial error raised was different. 

As I raised in my ticket I found the cause of the issue seems to be due to `srcSet` string returned from the `gatsbyImageData` query contains carriage returns rather than spaces.

```
"/static/35bb649151d59c08d4ab7ad171da7985/ba134/iron-battlefield-cover.webp 450w,↵
/static/35bb649151d59c08d4ab7ad171da7985/e7f7d/iron-battlefield-cover.webp 900w,↵
/static/35bb649151d59c08d4ab7ad171da7985/fc420/iron-battlefield-cover.webp 1800w"
```

When these are replaced with spaces it all works fine. 

I put a demo of the error occurring here:  https://minitothemax.app/a
Page A - https://github.com/piemasters/MiniToTheMax/blob/master/src/pages/a.tsx
Page B - https://github.com/piemasters/MiniToTheMax/blob/master/src/pages/b.tsx

In `a.tsx` I console logged the `gatsbyImageData` out, put it into a JS object and removed the carriage returns. The saved object doesn't throw the error, but the query result does. When doing a diff between the two it only picks up the carriage returns.

I just tried upgrading gatsby-plugin-image to `1.4.0-next.0` but it still throws the same error.

**Closed** 2021-04-16 11:30 UTC
Labels: topic: images/media, type: bug

**Comment by ascorbic** [comment] 2021-04-16 11:46
Could everyone who experienced this please install `gatsby-plugin-image@1.4.0-next.1` and see if it fixes it.

**Comment by iamkratos** [comment] 2021-04-16 12:07
@ascorbic it's now working for me, thank you!

**Comment by piemasters** [comment] 2021-04-16 12:45
@ascorbic can confirm fixed for me for both dev and prod, thanks! ⭐

**Comment by amogh-w** [comment] 2021-04-16 16:43
I was also facing the issue demonstrated by @stevepepple and can confirm that the fix by @ascorbic worked for me too. Thank you very much!

Here are my npm dependencies for your reference.
```
    "@mdx-js/mdx": "^1.6.22",
    "@mdx-js/react": "^1.6.22",
    "@tailwindcss/typography": "^0.4.0",
    "add": "^2.0.6",
    "autoprefixer": "^10.2.5",
    "gatsby": "^3.2.1",
    "gatsby-plugin-dark-mode": "^1.1.2",
    "gatsby-plugin-image": "1.4.0-next.1",
    "gatsby-plugin-mdx": "^2.3.0",
    "gatsby-plugin-postcss": "^4.3.0",
    "gatsby-plugin-react-helmet": "^4.3.0",
    "gatsby-plugin-sharp": "^3.3.0",
    "gatsby-plugin-transition-link": "^1.20.5",
    "gatsby-remark-images": "^5.0.0",
    "gatsby-source-filesystem": "^3.3.0",
    "gatsby-transformer-sharp": "^3.3.0",
    "gsap": "^3.6.1",
    "postcss": "^8.2.10",
    "prismjs": "^1.23.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-helmet": "^6.1.0",
    "react-icons": "^4.2.0",
    "tailwindcss": "^2.1.1",
    "yarn": "^1.22.10"
```

**Comment by philliprognerud** [comment] 2021-04-21 20:17
works, thank you

**Comment by creotip** [comment] 2021-04-21 20:35
Huge respect for @ascorbic . Thank you for a hard work and dedication! 👍

**Comment by diogomoreira** [comment] 2021-04-29 21:42
Thank you @ascorbic! It worked here

**Comment by eth0izzle** [comment] 2021-05-02 02:08
FYI it seems `1.4.0-next.1` was merged in to `latest` so just update your `gatsby-plugin-image` though `npm`.
