### ISSUE TITLE
Parts of page content/data lost with hard refresh in production builds, not dev

### ISSUE THREAD

**Issue by phun-ky** [gatsbyjs/gatsby#34396] opened 2022-01-04 12:27 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Parts of page data/content is lost when accessing a gatsby URL directly (or hitting hard refresh) in production builds only (local and on release site). The page data is not missing when navigating to a sub page, and then clicking the url.

(The documentation files are not present in the reproduction repo, since it is in 4 different repositories, but the details of the setup follows:)

The markdown files are categorized and grouped by `customPath` into one page. The component index page has frontmatter like so, and the page only consist of this file.

```
---
title: 'Components'
order: 1
navOrder: 2
topLevel: true
globalNav: true
mobileGlobalNav: true
category: 'components'
customPath: '/components'
---
```
Could there be some built in cache? I see in the network requests when having cache disabled in browser and "private" mode, and I see that for the production build, the XHR request (see screenshot) only return the paragraphs, not the list of components, but if I access the XHR URL directly, I get the correct data: [https://design.if.eu/page-data/components/page-data.json](https://design.if.eu/page-data/components/page-data.json)

### Reproduction Link

https://github.com/phun-ky/gatsby-reproduceable-css-svg

### Steps to Reproduce

1. Go to this URL: https://design.if.eu/components
2. See that the long list of components is missing and the left hand side menu is not "opened" with all of the sub pages
3. Navigate to `design` in the top level menu bar
4. Navigate back to `components` and the page has more content and the left hand side menu is opened with sub pages

### Expected Result

No page data/content  missing

### Actual Result

Parts of page data/content missing

### Environment

```shell
System:
    OS: Linux 4.15 Ubuntu 18.04.6 LTS (Bionic Beaver)
    CPU: (12) x64 Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 8.2.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 95.0.1
  npmPackages:
    gatsby: ^4.0.1 => 4.3.0 
    gatsby-plugin-catch-links: ^4.0.0 => 4.3.0 
    gatsby-plugin-google-tagmanager: ^4.0.0 => 4.3.0 
    gatsby-plugin-image: ^2.0.0 => 2.3.0 
    gatsby-plugin-manifest: ^4.0.0 => 4.3.0 
    gatsby-plugin-mdx: ^3.0.0 => 3.3.0 
    gatsby-plugin-offline: ^5.0.0 => 5.3.0 
    gatsby-plugin-react-helmet: ^5.0.0 => 5.3.0 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-sharp: ^4.0.1 => 4.3.0 
    gatsby-plugin-stylus: ^4.0.0 => 4.3.0 
    gatsby-plugin-twitter: ^4.0.0 => 4.3.0 
    gatsby-remark-autolink-headers: ^5.0.0 => 5.3.0 
    gatsby-remark-classes: ^1.0.0 => 1.0.2 
    gatsby-remark-copy-linked-files: ^5.0.0 => 5.3.0 
    gatsby-remark-images: ^6.0.0 => 6.3.0 
    gatsby-remark-prismjs: ^6.0.0 => 6.3.0 
    gatsby-source-filesystem: ^4.0.0 => 4.3.0 
    gatsby-transformer-remark: ^5.0.0 => 5.3.0 
    gatsby-transformer-sharp: ^4.0.0 => 4.3.0 
  npmGlobalPackages:
    gatsby: 4.4.0
```

**Comment by phun-ky** [comment] 2022-01-04 12:29
Possibly (weak) related to https://github.com/gatsbyjs/gatsby/issues/34251 ?

**Comment by phun-ky** [comment] 2022-04-05 12:27
Still happens on `gatsby@4.11.1`

**Comment by phun-ky** [comment] 2022-04-05 12:35
I think this effects other queries on the pages as well, for example the side drawer, when doing a hard refresh (https://design.if.eu/components) (see screenshot), get mixed up links and link labels. This only happens on production builds, and also when the page data is lost/cut.
![Screenshot from 2022-04-05 14-34-02](https://user-images.githubusercontent.com/1714029/161754744-f36d0236-2422-4064-b0c9-3985a4336dd1.png)

**Comment by phun-ky** [comment] 2022-04-19 12:48
any triage for this? I do not know if it's relevant or not, but we use a mix of markdown and mdx for out pages (one page can have a mix of both), and we encounter a bug where for example our changelog files (appended to the component, for example here: https://design.if.eu/components/feedback/alert-banner/css) is moved to the top (but it is ordered to be at the bottom). This only  happens in production/prod build as well.

**Comment by pieh** [comment] 2022-04-19 20:24
@phun-ky 

Interesting part with your site I found is that behaviour you describe I can reproduce in Firefox ... but not in Chrome.

Now fun parts about discovery above (Firefox vs Chrome difference):

Because Node.js use basically same thing as Chrome (well, oversimiplification but ...) the behaviours do match, because html part is generated by Node.js and client side rendered by Chrome which are quite close to each other when it comes to "standard library" functions.

I didn't yet found a case where correctly used standard lib methods are different between browsers / node. But I definitely know some examples on when it's used wrongly that it produces different results - for example:

In chrome:
```
[1,4,3,0].sort((a,b) => a > b ? 1 : 0)
(4) [1, 4, 3, 0]
```

In firefox:
```
[1,4,3,0].sort((a,b) => a > b ? 1 : 0)
Array(4) [ 0, 1, 3, 4 ]
```

Result IS different, but `compareFunction` is wrong.

I'm not suggesting that `.sort` might be a problem here - I just think that given that there is a difference between Firefox and Chrome in how they render things - it's problem of "that kind"

**Comment by phun-ky** [comment] 2022-04-20 08:48
@pieh yeah, looks like another issue. Will dig into that sorting issue, just need to get a triage for the original issue then. Thank you for responding :)

**Comment by pieh** [comment] 2022-04-20 10:50
@phun-ky I can't use provided reproduction to add additional debugging due to use of external registries that I don't have access to ( https://github.com/phun-ky/gatsby-reproduceable-css-svg/blob/master/.npmrc ). Just dropping `.npmrc` cause different problems for installation (missing packages in regular npm registry), so at very least I can't run the site at most can browse the code.

I do see what you describe, but only debugging options we have now is trying to debug transpiled and modified browser code which is ... quite difficult to do

**Comment by phun-ky** [comment] 2022-04-20 18:52
Will see if I can get the repro repo updated without that stuff

**Comment by phun-ky** [comment] 2022-05-08 19:30
Until that is done, I came across something that might be relevant (or not..). With `gatsby develop`, when I develop something in a sub page (not index), and I get for example an MDX error (or any other error relevant to bundling the JS), and I go to the index page (root `/`), I am also missing the data, and I get a component present that is only present when some sub page props are passed (boolean prop). To be able to get the root page to work again, I have to restart the dev server.

Might be relevant, or perhaps a different issue.

**Comment by phun-ky** [comment] 2022-05-29 06:15
Still an issue

**Comment by LekoArts** [comment] 2022-06-13 06:43
We still need a minimal reproduction that we can run

**Comment by LekoArts** [comment] 2022-06-21 04:47
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2022-06-21 04:47 UTC
Labels: type: bug, status: needs reproduction
