### ISSUE TITLE
Improve contentful rich text experience

### ISSUE THREAD

**Issue by wardpeet** [gatsbyjs/gatsby#24221] opened 2020-05-19 13:06 UTC
# Summary

I'm not super familiar with contentful rich text. For now this is just a placholder issues.

- rich text causes a full rebuild (I think that's inevitable because it touches code)
- random error appears

**Comment by joshduck** [comment] 2020-05-21 01:36
We use Gatsby static site generator to render Contentful content using the gatsby-source-contentful plugin provided by Gatsby. We’ve seen that when building our site, we encounter out of memory errors when working with Contentful data that has Rich Text fields. 

We believe that this is an architectural issue with gatsby-source-contentful plugin. Gatsby does not use Contentful’s GraphQL design where text structure and links are distinct fields that can be queried independently (represented as `text` and `links` fields in [Contentful GraphQL](https://www.contentful.com/developers/docs/references/graphql/#/reference/schema-generation/rich-text)). 

Instead it implements Rich Text as a single field which holds a tree with any embedded Contentful nodes eagerly [resolved and inlined directly](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/src/rich-text.js#L113). Because this eager inlining [happens recursively](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-contentful/src/rich-text.js#L34), a Rich Text field will contain all the data for anything embedded in it, and all the data embedded in those nodes, etc, etc.

Our content model includes embedded links between blog post nodes for SEO purposes, which means that Gatsby could hypothetically end up eagerly fetching and serialising hundreds of nested nodes in a single rich text field. We have seen that blog posts frequently contain multiple gigabytes of data. 

This could be fixed by implementing Rich Text fields in the same way that Contentful does (using two fields). This would allow the consumer to specify which fields they need from embedded nodes. GraphQL, by design, does not allow users to construct queries that would recursively fetch data.

**Comment by amandasage** [comment] 2020-05-27 01:26
Hi @joshduck checking if https://www.contentful.com/developers/docs/tutorials/general/rich-text-and-gatsby/ will help resolve some of the issues you're seeing.

**Comment by joshduck** [comment] 2020-05-27 23:33
@amandasage, no. That's what we're using right now. 

The problem is that the JSON object referenced in that documentation page (`bodyRichText.json`) can contain way too much data (gigabytes) and crash the process. 

Out fix so far has been to patch `gatsby-source-contentful` to limit the depth of the recursion.

**Comment by amandasage** [comment] 2020-05-28 00:48
Hey @joshduck I will open a ticket on Contentful's end for this

**Comment by daniellangnet** [comment] 2020-06-16 01:29
@joshduck thanks for sharing your insight on this! I'm having the same problem and wondering how you went about patching `gatsby-source-contentful` to limit the depth of recursion? In case that patch is public somewhere, would greatly appreciate it.

@axe312ger excited about your solution. One other issue you might address is that currently the resolved entries that are part of the serialized JSON do _not_ include any incoming link references. For example, a model `Subcategory` would normally contain a field `lc_category` which is an arrow of all the `Category` entries that contain a reference to this subcategory. My hope is that with your approach of resolving the referenced entries outside the JSON structure and being able to define GraphQL query to decide which fields to resolve, it will be possible to also get these incoming links.

**Comment by me4502** [comment] 2020-06-16 04:02
@daniellangnet 
> @joshduck thanks for sharing your insight on this! I'm having the same problem and wondering how you went about patching `gatsby-source-contentful` to limit the depth of recursion? In case that patch is public somewhere, would greatly appreciate it.

Our patch is quite heavily intertwined with a few other patches making it hard to publish, but the main thing that we do is to strip out anything beyond a certain depth within the `prepareRichTextNode` function in `normalize.js` within gatsby-source-contentful. You'll have to experiment with the exact number as what it requires can vary per site/data type.

**Comment by daydream05** [comment] 2020-06-16 06:16
One of the biggest [issue](https://github.com/contentful/rich-text/issues/70) that a lot of us encountered with Rich Text and Gatsby is that there was no easy way to use Gatsby Image inside rich text. Since rich text only returns the image object and we cannot query for the fluid/fixed props that we're used to when working with contentful image, we had to resort to hacky ways.

The current solutions in the wild are:
1. Querying all contentful assets and filtering inside the react to rich text renderer.
2. Grabbing the images from rich text and using those to images as filters when querying all contentful assets.

The former causes performance issues while the latter requires a lot of boiler plate code. 

I found that there's actually a simpler solution which uses the [APIs](https://github.com/gatsbyjs/gatsby/blob/9b077c6e87956c767dc506b6ef15eb8720f47841/packages/gatsby-source-contentful/src/extend-node-type.js#L116) inside `gatsby-source-contentful` to generate fluid or fixed props without having to use GraphQL.

I have successfully used it in production and so far haven't had any issues.

I created a [PR](https://github.com/gatsbyjs/gatsby/pull/24634) for it but here's how it would look like:

```jsx
import GatsbyImg from 'gatsby-image'
import { resolveFluid } from 'gatsby-source-contentful'

const options = {
    [BLOCKS.EMBEDDED_ASSET]: (node) => {
        const { file, title } = data.target.fields
        const image = {
            file: file["en-US"]
        }
        const fluidProps = resolveFluid(image, { maxWidth: 600 })
        return <GatsbyImage fluid={fluidProps} alt={title['en-US']} />
    }
}

```

**Comment by axe312ger** [comment] 2020-06-17 08:51
The PR is was talking about above: #24905

**Comment by disintegrator** [comment] 2020-07-23 11:47
>For rendering, we are going to introduce the biggest change. The current best practice is to use the official Rich Text Renderer directly with the GraphQL field result. We expose a new function from the source plugin, which will wrap documentToReactComponents and takes care of resolving the references based on our custom GraphQL Query data.

@axe312ger this seems problematic if we want to render the rich text differently for various use cases. As an example, rich text used as the body of a blog post will have use different react components to rich text used in the description area of a card widget. Currently, code consuming rich text can directly pass render customizations to `documentToReactComponents`. We have a RichText component today with the following API:

```tsx
import {
  documentToReactComponents,
  Options,
} from "@contentful/rich-text-react-renderer";
import { Document } from "@contentful/rich-text-types";

export interface RichTextProps {
  document: Document;
  renderMark?: Options["renderMark"];
  renderNode?: Options["renderNode"];
  renderText?: Options["renderText"];
}

const RichText: React.FC<RichTextProps> = props => {
  // calls documentToReactComponents with any options passed into props
}
```

**Question: How do you suggest we apply customizations to rich text rendering in those cases?**

**Comment by axe312ger** [comment] 2020-07-23 17:20
@disintegrator we just released an update that covers your suggestiosn as well. See the code at:

https://github.com/gatsbyjs/gatsby/pull/25249

**Comment by disintegrator** [comment] 2020-07-28 18:19
Thanks for the update @axe312ger 

For anyone that comes across memory issues with gatsby-source-contentful. This is likely because of how rich text is handled. In our gatsby project the only property we use out of rich text fields is `json`. For example, we typically write this:

```graphql
{
	contentfulBlogPost(id: {eq: $id}) {
		title
		body {
			json
		}
	}
}
```

A lot of the work that Gatsby does around rich text is on inferring the type for the `content` field. This is a deeply nested object that corresponds to the _parsed_ on the rich text AST from contentful API. It seems overkill that the parsed object is attached to rich text nodes and this is manifesting in a longer and longer bootstrap phase and high memory usage when building gatsby projects as you create more content in the CMS. Additionally, each rich text field is getting its own graphql type which also seemed unnecessary for us. We use `gatsby-plugin-schema-snapshot` to persist the graphql generated due to `gatsby-source-contentful` and I noticed around ~4200 (!) inferred graphql types out of ~4500 total types were related to rich text! The `json` field is not inferred it's a schema extension with a resolver function that gatsby-source-contentful adds. 

All in all, there is a lot of wasted work and memory going into data we never look at in a project.

## Our solution

We use [`patch-package`](https://github.com/ds300/patch-package) to modify `gatsby-source-contentful` like so:
- Omit the `...content` line in [`prepareRichTextNode`](https://github.com/gatsbyjs/gatsby/blob/a4f171df1332c4290d86285db295514588f65afb/packages/gatsby-source-contentful/src/normalize.js#L251). This is the main culprit!
- Make all rich text nodes have the same type instead of [```_.camelCase(`${node.internal.type} ${key} RichTextNode`)```](https://github.com/gatsbyjs/gatsby/blob/a4f171df1332c4290d86285db295514588f65afb/packages/gatsby-source-contentful/src/normalize.js#L257). We changed that to `ContentfulRichTextNode`.
- Update the [schema extension](https://github.com/gatsbyjs/gatsby/blob/a4f171df1332c4290d86285db295514588f65afb/packages/gatsby-source-contentful/src/extend-node-type.js#L546) for rich text so the json field is added on nodes with type `ContentfulRichTextNode`.

Below, I've attached the patch-package patch file that targets gatsby-source-contentful @ 2.3.32 with the changes I listed. I hope it helps you overcome slow builds and OOM errors until the upcoming rebuild of gatsby-source-contentful! 😄 

[**gatsby-source-contentful+2.3.32.patch.zip**](https://github.com/gatsbyjs/gatsby/files/4990366/gatsby-source-contentful%2B2.3.32.patch.zip)

**Comment by axe312ger** [comment] 2020-07-29 10:13
@disintegrator did you find a chance to try the new version of `gatsby-source-contentful@next` with your project?

See: https://github.com/gatsbyjs/gatsby/pull/25249

**Comment by disintegrator** [comment] 2020-07-29 10:41
@axe312ger that's next on my list to evaluate. I need a quick solution to my problem based on the release version of the contentful plugin.

**Comment by daydream05** [comment] 2020-07-31 18:32
Sorry if I missed it. Does this PR  https://github.com/gatsbyjs/gatsby/pull/24905 also fix  the issue with missing content https://github.com/gatsbyjs/gatsby/issues/10592? I'm running on Gatsby Cloud and I end up with missing data whenever I make slight changes on a rich text field.

**Comment by axe312ger** [comment] 2020-08-12 12:12
@daydream05 yes please have a look at the new version from #24905  and give feedback :)

**Comment by daydream05** [comment] 2020-09-11 03:21
Started using it for a new client project and everything thing looks good so far! Great work on this @axe312ger . Waited for this rich text update for so long.

One issue though regarding loading multiple contentful spaces in the same Gatsby app, it seems that it’s broken. 

(The content models for the 2nd space is not loading any attributes or data, just the name of the content model)

I’ll create an issue tomorrow.

**Comment by samsherwood** [comment] 2020-09-25 02:01
> Thanks for the update @axe312ger
> 
> For anyone that comes across memory issues with gatsby-source-contentful. This is likely because of how rich text is handled. In our gatsby project the only property we use out of rich text fields is `json`. For example, we typically write this:
> 
> ```graphql
> {
> 	contentfulBlogPost(id: {eq: $id}) {
> 		title
> 		body {
> 			json
> 		}
> 	}
> }
> ```
> 
> A lot of the work that Gatsby does around rich text is on inferring the type for the `content` field. This is a deeply nested object that corresponds to the _parsed_ rich text AST from contentful API. It seems overkill that the parsed object is attached to rich text nodes and this is manifesting in a longer and longer bootstrap phase and high memory usage when building gatsby projects as you create more content in the CMS. Additionally, each rich text field is getting its own graphql type which also seemed unnecessary for us. We use `gatsby-plugin-schema-snapshot` to persist the graphql types generated due to `gatsby-source-contentful` and I noticed around ~4200 (!) inferred graphql types out of ~4500 total types were related to rich text! The `json` field is not inferred - it's a schema extension with a resolver function that gatsby-source-contentful adds.
> 
> All in all, there is a lot of wasted work and memory going into data we never look at in our project.
> 
> ## Our solution
> We use [`patch-package`](https://github.com/ds300/patch-package) to modify `gatsby-source-contentful` like so:
> 
> * Omit the `...content` line in [`prepareRichTextNode`](https://github.com/gatsbyjs/gatsby/blob/a4f171df1332c4290d86285db295514588f65afb/packages/gatsby-source-contentful/src/normalize.js#L251). This is the main culprit!
> * Make all rich text nodes have the same type instead of [`` _.camelCase(`${node.internal.type} ${key} RichTextNode`) ``](https://github.com/gatsbyjs/gatsby/blob/a4f171df1332c4290d86285db295514588f65afb/packages/gatsby-source-contentful/src/normalize.js#L257). We changed that to `ContentfulRichTextNode`.
> * Update the [schema extension](https://github.com/gatsbyjs/gatsby/blob/a4f171df1332c4290d86285db295514588f65afb/packages/gatsby-source-contentful/src/extend-node-type.js#L546) for rich text so the json field is added on nodes with type `ContentfulRichTextNode`.
> 
> Below, I've attached the patch-package patch file that targets gatsby-source-contentful @ 2.3.32 with the changes I listed. I hope it helps you overcome slow builds and OOM errors until the upcoming rebuild of gatsby-source-contentful! 😄
> 
> [**gatsby-source-contentful+2.3.32.patch.zip**](https://github.com/gatsbyjs/gatsby/files/4990366/gatsby-source-contentful%2B2.3.32.patch.zip)

Just wanted to say 'thank you' for attaching this. I've been beating my head against a wall for weeks now trying to track down a solution.

**Comment by bsgreenb** [comment] 2020-10-14 07:41
Also want to say thanks to @axe312ger who has been pushing through these issues to build a better Rich Text framework.

**Comment by axe312ger** [comment] 2020-10-15 09:45
@bsgreenb thanks! you are welcome! :)

We pushing further, release is coming closer :)

**Closed** 2020-11-09 10:46 UTC
Labels: topic: Contentful, type: feature or enhancement

**Comment by jordan314** [comment] 2020-12-07 06:33
Hi, thanks for this. We're having trouble querying raw and references.
gatsby version: 2.29.0-next.3
gatsby-source-contentful: 2.29.0
We're getting a couple errors:
Cannot query field "raw" on type "contentfulArticleContentRichTextNode".
Cannot query field "references" on type "contentfulArticleContentRichTextNode".
error ENOENT: no such file or directory, open '.cache/json/_.json'

Also, we're using the plugin gatsby-plugin-snapshot, would it be possible to share what the RichTextNode should look like in schema.gql now with these changes?

**Comment by pvdz** [comment] 2020-12-07 09:14
@jordan314 please file a new issue, this one has been merged. But one thing you should try first is to update to the newest version of `gatsby-source-contentful` (4.2.0).

I'll close this issue as it has been resolved and merged. If you were inclined to post a reply to it please open a new issue and refer to this one. Thank you.
