### ISSUE TITLE
Dynamic image unmounting results in: "Target container is not a DOM element."

### ISSUE THREAD

**Issue by philliprognerud** [gatsbyjs/gatsby#30696] opened 2021-04-06 05:53 UTC
## Description

This error does not come up during a page loads. The error only comes up when images are being unmounted dynamically. In my case, applying an image filter on the frontend to re-render new images. Then this error is being thrown for every single image that is being unmounted. This was quite difficult to debug since the error itself gives no hints into what is actually the problem.

```
react-dom.development.js:26091 Uncaught (in promise) Error: Target container is not a DOM element.
    at render (react-dom.development.js:26091)
    at m (lazy-hydrate.tsx:91)
    at eval (gatsby-image.browser.tsx:92)
```

#### FIXING THE PROBLEM (workaround):
I initially saw the error with `gatsby-plugin-image: ^1.2.0-next.0 => 1.2.0`
Upgrading to `gatsby-plugin-image: ^1.3.0-next.1 => 1.3.0-next.1` did not work.
Downgrading to `gatsby-plugin-image: ^1.2.0 => 1.2.0` did not work.
Downgrading to `gatsby-plugin-image: 1.1.2 => 1.1.2` **_WORKED!_**

### Steps to reproduce

Unfortunately, I don't have a minimal reproduction at the moment. But I can lay out what is happening on my site.

I am loading in 24 images using `<GatsbyImage />` nothing special here. I have a filter button that picks new images from the backend. These new images replace the current 24 images, so all the images unmount dynamically by updating the array in which the image data is stored. The moment this switch happens, the error gets thrown 24 times.

### Expected result

No errors should be thrown when images are dynamically unmounted.

### Actual result

```
react-dom.development.js:26091 Uncaught (in promise) Error: Target container is not a DOM element.
    at render (react-dom.development.js:26091)
    at m (lazy-hydrate.tsx:91)
    at eval (gatsby-image.browser.tsx:92)
```

### Environment

```
System:
    OS: Windows 10 10.0.19042
    CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
  Binaries:
    Node: 15.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.6.0 - ~\AppData\Roaming\npm\npm.CMD
  Languages:
    Python: 3.8.5 - /c/Users/phill/AppData/Local/Programs/Python/Python38-32/python
  Browsers:
    Chrome: 89.0.4389.114
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.68)
  npmPackages:
    gatsby: ^3.2.0-next.0 => 3.2.1
    gatsby-env-variables: ^2.0.0 => 2.0.0
    gatsby-plugin-accessibilityjs: ^1.0.3 => 1.0.3
    gatsby-plugin-gatsby-cloud: ^2.2.0-next.0 => 2.2.0
    gatsby-plugin-image: ^1.2.0-next.0 => 1.2.0
    gatsby-plugin-manifest: ^3.2.0-next.0 => 3.2.0
    gatsby-plugin-postcss: ^4.2.0-next.0 => 4.2.0
    gatsby-plugin-react-helmet: ^4.2.0-next.0 => 4.2.0
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-robots-txt: ^1.5.5 => 1.5.5
    gatsby-plugin-segment-js: ^3.6.0 => 3.6.0
    gatsby-plugin-sharp: ^3.2.0-next.0 => 3.2.0
    gatsby-plugin-styled-components: ^4.2.0-next.0 => 4.2.0
    gatsby-plugin-typescript: ^2.8.0 => 2.12.1
    gatsby-source-filesystem: ^3.2.0-next.0 => 3.2.0
    gatsby-source-strapi: ^0.0.12 => 0.0.12
    gatsby-transformer-sharp: ^3.2.0-next.0 => 3.2.0
  npmGlobalPackages:
    gatsby-cli: 3.0.0
```

**Comment by philliprognerud** [comment] 2021-04-06 05:53
For those that need a quick fix. 

Downgrading to `gatsby-plugin-image@1.1.2` fixed the issue for me.

**Comment by LekoArts** [comment] 2021-04-06 07:01
I'll close this as a duplicate of https://github.com/gatsbyjs/gatsby/issues/29982 - please post your findings there. Thanks!

**Closed by LekoArts** 2021-04-06 07:01 UTC
Labels: status: triage needed, type: bug
