### ISSUE TITLE
Gatsby Link expects the 'to' prop to start with '/' prefixed to the path 

### ISSUE THREAD

**Issue by rolwin100** [gatsbyjs/gatsby#25770] opened 2020-07-15 15:48 UTC
## Description

Suppose you there in a client route '/abc'. You have a Link component that routes to 'xyz' route. The 'to' prop your passing it as <Link to="xyz">Page link</Link> ( note that 'to' prop is 'xyz' and not '/xyz'). Then if we click the link it will take us to '/abc/xyz' instead of /xyz.

### Steps to reproduce

1. Go to some client route say /abc. Create a link component to xyz as <Link to="xyz">page route</Link>.
2. When you click on the route it will take you to '/abc/xyz'. Notice the current route getting appended.
3. This issue cannot be replicated on the home page because the home page route is / itself.

### Expected result

1. should route to corresponding route /xyz

### Actual result

appending /abc to route /xyz

### Environment

any env

**Comment by herecydev** [comment] 2020-07-15 20:18
This isn't a bug; it's how relative links are supposed to work. You can find more information here: https://www.gatsbyjs.org/docs/linking-between-pages/#using-relative-links-in-the-link--component

**Comment by LekoArts** [comment] 2020-07-16 06:54
Thank you for opening this!

As Dan said this is working as intended and thus not a bug.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2020-07-16 06:54 UTC
Labels: type: question or discussion
