### ISSUE TITLE
[gatsby-plugin-image] constraint layout wrapper element height is wrong 

### ISSUE THREAD

**Issue by tumdav** [gatsbyjs/gatsby#30885] opened 2021-04-15 10:42 UTC
## Description

In case of images with the constraint layout, wrapper div and actual image heights are not equal

```js
 <StaticImage width="80" src="../../images/logo-dark.png" />
```
This generates image with the size of 80x80, but the wrapper element height is 87px instead of 80

### Steps to reproduce

Add static image on the HTML document and compare the image and wrapper element hrights

### Expected result

Wrapper element height should be the same as image actual height

### Actual result

Wrapper element height is larger then image height

There is an explanation here how we can fix it by adding vertical-align:top to the wrapper element
https://stackoverflow.com/questions/27536428/inline-block-element-height-issue

**Comment by LekoArts** [comment] 2021-04-16 07:21
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-04-26 08:42
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-04-26 08:42 UTC
Labels: status: needs reproduction, topic: images/media, type: bug
