### ISSUE TITLE
adding a custom endpoint to the whitelist routes in gatsby.-config.js file. 

### ISSUE THREAD

**Issue by speculati0n** [gatsbyjs/gatsby#24163] opened 2020-05-17 18:27 UTC
hello, I am using the wordpress plugin for gatsby. I am trying to whitelist a route in my gatsby-config.js file.
![image](https://user-images.githubusercontent.com/26420672/82156610-212fbd00-984a-11ea-82d9-ca942a494f6a.png)

however when I run gatsby develop in the terminal it is not showing up.
as you can see here the last fetch shows the /users
![image](https://user-images.githubusercontent.com/26420672/82156643-53d9b580-984a-11ea-8b15-feff22e50e03.png)

here is the full url link i am trying to call. http://dynamicvol.com/wp-json/rest-routes/v2/singals-and-scores.

does anyone happen to know how I might make this work? I am trying to call data from a plugin in wordpress called wpdatatables, by default you cannot call this data via json format BUT if you download a plugin called Rest Routes in wordpress you are able to create your own custom endpoints. The one I am trying to whitelist is a custom endpoint I created. As you can see from the other fetch calls in the pictures the format is i.e wp-json/wp/v2/users mean while the custom endpoint i made has a "rest-routes" in between the wp-json/ and /wp i.e....wp-json/rest-routes/wp/v2/.  does anyone know if this is the reason why this will not work? Am I not listing it properly in the whitelist section of my gatsby-config.? any help would be great. thanks

**Comment by jasonbahl** [comment] 2020-05-18 14:22
@speculati0n Currently you have your route added as `**/rest-routes`, but since there's no prefix before the route (such as `wp/v2/`), I believe you might need to try adding the route to the `includedRoutes` like so: `rest-routes/**`. 

Can you give that a try and see if that works?

**Comment by speculati0n** [comment] 2020-05-18 18:53
Thanks for replying. unfortunately this did not solve the problem. 

![image](https://user-images.githubusercontent.com/26420672/82248861-d7f96f00-9916-11ea-9832-e223df148a61.png)

as you can see it's still not being fetched when I run this in the terminal.

![image](https://user-images.githubusercontent.com/26420672/82248918-efd0f300-9916-11ea-85da-fbfd6c33e2a1.png)

again here is the custom route i'm trying to access: http://dynamicvol.com/wp-json/rest-routes/v2/singals-and-scores

**Comment by LekoArts** [comment] 2020-06-26 10:02
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by freiksenet** [comment] 2020-07-03 08:16
Hi! 

I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. 

Thanks!

**Closed by freiksenet** 2020-07-03 08:16 UTC
Labels: status: needs reproduction, topic: WordPress
