### ISSUE TITLE
Gatsby Slow Video

### ISSUE THREAD

**Issue by danielmonk** [gatsbyjs/gatsby#17573] opened 2019-09-11 21:54 UTC
Hi!

I've switched from having a video hosted on youtube to stored locally, but it's being really slow loading? Sometimes when trying to load the .mp4 video asset file itself it hangs for a few minutes? Any ideas would be appreciated.

My site url is: https://danielmonk.io/.

Thanks!

**Comment by wardpeet** [comment] 2019-09-12 07:51
Hi @danielmonk !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by LekoArts** [comment] 2019-09-13 10:09
I'm closing this issue as it doesn't seem to be caused by Gatsby itself, but rather the massive video file you're serving to your users.

You will want to minimize the filesize, e.g. by using a tool like Handbrake or offer different video files for different browsers (e.g. webm). Your youtube solution probably worked better in the past as youtube knows pretty well how to compress video without a lot of data loss (and also serve lower res on low-end connections).

Thanks for using Gatsby, please comment here below if you found a solution to your problem.

**Closed by LekoArts** 2019-09-13 10:09 UTC
Labels: status: needs more info, status: needs reproduction

**Comment by danielmonk** [comment] 2019-09-13 11:00
Hi guys, thanks for your help! Took the sound off the video and optimised it down to less than 10mb and now works fine! Thanks again for your help.
