### ISSUE TITLE
backgroundColor isn't transparent even if I set it to transparent

### ISSUE THREAD

**Issue by ricardo-dlc** [gatsbyjs/gatsby#30811] opened 2021-04-11 05:08 UTC
## Description

I have a PNG image which has a transparent background, basically is a "circled" avatar.  When I get it on GraphQL the property `backgroundColor` property is always with a black color (`#080808`) but the documentation says that the default value for this property is `transparent`. Even if I try to set it to `transparent` or another HEX color, it results on `"backgroundColor": "#080808"` no matter what value I set.

### Steps to reproduce

Get the image throught the next query:
```
query MyQuery($backgroundColor: String = "transparent") {
  file(relativePath: {eq: "image.png"}) {
    childImageSharp {
      gatsbyImageData(
        backgroundColor: $backgroundColor
      )
    }
  }
}
```

### Expected result
```json
{
  "data": {
    "file": {
      "childImageSharp": {
        "gatsbyImageData": {
          "layout": "constrained",
          "backgroundColor": "transparent",
          "images": {
            "fallback": {
              "src": "/static/path/to/image.png",
              "srcSet": "/static/path/to/image.png 488w,\n/static/path/to/image.png 976w,\n/static/path/to/image.png 1952w",
              "sizes": "(min-width: 1952px) 1952px, 100vw"
            },
            "sources": [
              {
                "srcSet": "/static/path/to/image.webp 488w,\n/static/path/to/image.webp 976w,\n/static/path/to/image.webp 1952w",
                "type": "image/webp",
                "sizes": "(min-width: 1952px) 1952px, 100vw"
              }
            ]
          },
          "width": 1952,
          "height": 1952
        }
      }
    }
  },
  "extensions": {}
}
```

### Actual result

```json
{
  "data": {
    "file": {
      "childImageSharp": {
        "gatsbyImageData": {
          "layout": "constrained",
          "backgroundColor": "#080808",
          "images": {
            "fallback": {
              "src": "/static/path/to/image.png",
              "srcSet": "/static/path/to/image.png 488w,\n/static/path/to/image.png 976w,\n/static/path/to/image.png 1952w",
              "sizes": "(min-width: 1952px) 1952px, 100vw"
            },
            "sources": [
              {
                "srcSet": "/static/path/to/image.webp 488w,\n/static/path/to/image.webp 976w,\n/static/path/to/image.webp 1952w",
                "type": "image/webp",
                "sizes": "(min-width: 1952px) 1952px, 100vw"
              }
            ]
          },
          "width": 1952,
          "height": 1952
        }
      }
    }
  },
  "extensions": {}
}
```

As you can see, the result on the backgroundColor is a black color, which results on a ugly apparence when the image is loading. What I am missing?

### Environment
System:
    OS: Linux 5.4 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 12.22.0 - ~/.nvm/versions/node/v12.22.0/bin/node
    npm: 6.14.11 - ~/.nvm/versions/node/v12.22.0/bin/npm
  npmPackages:
    gatsby: ^3.2.1 => 3.2.1
    gatsby-plugin-google-gtag: ^3.2.0 => 3.2.0
    gatsby-plugin-image: ^1.2.1 => 1.2.1
    gatsby-plugin-react-helmet: ^4.2.0 => 4.2.0
    gatsby-plugin-sharp: ^3.2.1 => 3.2.1
    gatsby-plugin-sitemap: ^3.2.0 => 3.2.0
    gatsby-plugin-webfonts: ^2.1.0 => 2.1.0
    gatsby-source-filesystem: ^3.2.0 => 3.2.0
    gatsby-source-strapi: 0.0.12 => 0.0.12
    gatsby-transformer-sharp: ^3.2.0 => 3.2.0

**Comment by LekoArts** [comment] 2021-04-13 07:38
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by ricardo-dlc** [comment] 2021-04-15 18:25
Yeah sure, just give me a couple days to get it. Thanks for your reply.

**Comment by ascorbic** [comment] 2021-04-16 10:48
Hi. You need to set placeholder to none, or traced SVG. That background color is being added by the dominant color placeholder (which is the default)

**Comment by LekoArts** [comment] 2021-04-26 08:42
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-04-26 08:42 UTC
Labels: status: needs reproduction, topic: images/media, type: bug

**Comment by SilencerWeb** [comment] 2021-10-06 09:15
Hey @LekoArts! Here is the bug reproduction — https://github.com/pixel-point/gatsby-plugin-sharp-backgroundColor-bug
