### ISSUE TITLE
Product variants not being returned in correct order

### ISSUE THREAD

**Issue by iamkratos** [gatsbyjs/gatsby#32066] opened 2021-04-20 12:26 UTC
For some products, the variant order gets mixed up in the graphql response. Most of the time the variants are in the proper order (they match the Shopify order), but sometimes they get randomly mixed up. [Screenshots attached](https://imgur.com/a/P7l2sDU). Let me know if I can provide more info

**Comment by LekoArts** [comment] 2021-06-24 05:07
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-07-06 09:54
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-07-06 09:54 UTC
Labels: status: needs reproduction, topic: source-shopify, type: bug
