### ISSUE TITLE
Contentful query and Markdown query response are mixed up

### ISSUE THREAD

**Issue by ergunpp** [gatsbyjs/gatsby#10254] opened 2018-12-03 13:16 UTC
Hi,
I have a graphql query on index page like so:

```javascript
export const pageQuery = graphql`
      query IndexQuery {
        site {
          meta: siteMetadata {
            title
            description
            url: siteUrl
            author
            twitter
            adsense
          }
        }
        remark: allMarkdownRemark (
          sort: { fields: [frontmatter___date], order: DESC }
        ) {
          posts: edges {
            post: node {
              html
              frontmatter {
                layout
                title
                path
                category
                tags
                description
                date(formatString: "YYYY/MM/DD")
                image {
                  childImageSharp {
                    fixed(width: 500) {
                      ...GatsbyImageSharpFixed_withWebp
                    }
                  }
                }
              }
            }
          }
        }
        contentful: allContentfulProduct {
          products: edges {
            product: node {
              id
              name
              teaser {
                       teaser
                     }
            }
          }
        }
      }
    `
```
But the data object returns the "teaser" text in the remark object as well. I could not figure out why the data from contentful query response is also returned in remark object.

Pls help.

**Comment by jonniebigodes** [comment] 2018-12-03 19:32
@ergunpp with the repo it will make things easier to correct.
Also did you manage to correct this issue #10092 ? If so please close it or let me know so i can close it ok?

**Comment by ergunpp** [comment] 2018-12-04 05:57
I couldn't solve the problem for #10092. This one is on the same cloud9 environment but compiles fine except for this error.

**Comment by jonniebigodes** [comment] 2018-12-04 18:22
@ergunpp i've cloned your repo and checked to confirm your issue, but it looks the teaser text is where as it should be in the `contentful` object not in the `remark` one.

Also in the repository you provided, you forgot to add the query you mentioned that was not working.
I've changed the code you provided a bit to incorporate the query and these are the results i got in the devtools console of chrome when i ran gatsby develop and opening up `http://localhost:8000`
The site and remark data part
![result_devtools_console_remark_site](https://user-images.githubusercontent.com/22988955/49462772-c7bb0600-f7ee-11e8-8aca-84eea1e269ac.png)

The contentfull part.
![result_devtools_console_contentfull](https://user-images.githubusercontent.com/22988955/49462810-eae5b580-f7ee-11e8-9b17-7f4941ef61f4.png)

Just to cover my bases and see that everything was in order.

I've ran your query with GraphiQL with a tweak, as the tool will not recognize the graphql fragment `GatsbyImageSharpFixed_withWebp`, so instead i changed it to `width` so that that object was populated with something and added the id property in `post`, to check if no duplicates or something wrong.
As you can see [here](https://gist.github.com/jonniebigodes/161bd009b1c480ad470afca0f6fe6efd), there's the query used and the results from it.

I don't know if you're using that starter as a base for your work, but it brought to my attention while diving at the code of the starter, that there's some work needed there.
Also related to your other issue i'm going to take another crack at it and see if we can come up with a solution and/or alternative to get your code up and running.
Bellow is the `index.js` changed i used.
```javascript
import { graphql } from "gatsby";
import React from "react";
import get from "lodash/get";

import Post from "templates/Post";
import Meta from "components/Meta";
import Layout from "components/Layout";

const BlogIndex = ({ data, location }) => {
  console.log(JSON.stringify(data,null,2));
  const posts = get(data, "remark.posts");
  return (
    <Layout location={location}>
      <Meta site={get(data, "site.meta")} />
      {posts.map(({ post }, i) => (
        <Post
          data={post}
          options={{
            isIndex: true
          }}
          key={i}
        />
      ))}
    </Layout>
  );
};

export default BlogIndex;

export const pageQuery = graphql`
query IndexQuery {
  site {
    meta: siteMetadata {
      title
      description
      url: siteUrl
      author
      twitter
      adsense
    }
  }
  remark: allMarkdownRemark (
    sort: { fields: [frontmatter___date], order: DESC }
  ) {
    posts: edges {
      post: node {
        html
        id
        frontmatter {
          layout
          title
          path
          category
          tags
          description
          date(formatString: "YYYY/MM/DD")
          image {
            childImageSharp {
              fixed(width: 500) {
                ...GatsbyImageSharpFixed_withWebp
              }
            }
          }
        }
      }
    }
  }
  contentful: allContentfulProduct {
    products: edges {
      product: node {
        id
        name
        teaser {
          teaser
        }
      }
    }
  }
}
`;

```

**Comment by ergunpp** [comment] 2018-12-04 19:15
But the problem is teaser text should be returned in contentful query, but it was returned in remark. I dont understand this, where the teaser text in remark comes from.

**Comment by jonniebigodes** [comment] 2018-12-04 20:18
@ergunpp based on the response i gave earlier, the teaser text comes from the correct place from contenfull, like i said i've cloned your repo, added the contentfull part of the query that was missing, tested it with graphiql and started gatsby in development mode and checked the devtools console and searched for teaser and it was in the correct place in both places. The only solution i can think of for that behaviour is that the query was not correctly indented when you implemented it and could have messed up.
I've updated the gist with the output of the devtools console i got when i ran the gatsby develop

**Comment by ergunpp** [comment] 2018-12-04 20:59
But when you look at the json returned; the teaser text is also under the remark heading. How does it find its way to here?

**Comment by jonniebigodes** [comment] 2018-12-04 21:45
@ergunpp could you be more specific? I just re-checked the output once more and created a document [here](https://jsoneditoronline.org/?id=0daa4853616444d2b1c817e5fdb6a4d1) so i can see the output i got based on your code/repo and the query you mentioned in the issue in a more structured way. And what i've got is a json object with 1 property `data` that has 3 properties inside

- site
- remark
- contentful

Inside the `site` object is the content that is passed down from the `gatsby-config.js`.
Inside the remark object is the result of the remark graphql query stated.
Namely a object with the following structure:
- Posts 
  - Array of posts objects
     - Post object has the following properties
         - html
         - id
         - frontmatter
            - layout
            - title
            - path
            - category
            - tags
            - description
            - date
            - image


Inside the contentful object i have the following.
- contentful
  - products which is an array of product objects like the one bellow
      - product
         - id
         - name
         - teaser

**Comment by ergunpp** [comment] 2018-12-05 13:55
I have no problem with that. But inside the remark object  I receive 16 post objects that are not stored in the posts folder, and those objects have only one value set (html field) and the value returned are the teaser texts from the contentful query.

**Comment by ergunpp** [comment] 2018-12-05 15:41
I have found a workaround for this by adding the following to allMarkdownRemark query:
`filter:{fileAbsolutePath:{regex: "/content/posts/"}}`
But I still do not understand why part of contentful response is returned in markdown object?

**Comment by jonniebigodes** [comment] 2018-12-06 00:16
@ergunpp based on the code you provided, this is a thing that surpasses me, like i said earlier in my responses, on my end the graphql query was returning the object structure as intended and i could not reproduce the issue at hand.
Sorry i could not be more of a help and glad you've figured it out.

**Comment by ergunpp** [comment] 2018-12-07 15:42
I solved the problem with a workaround.
I have added the following filter to graphql remark query:
`filter:{fileAbsolutePath:{regex:` "/content/posts/"}}`
Now everything is in place.

**Closed** 2018-12-07 15:43 UTC
