### ISSUE TITLE
Importing image into file throws error

### ISSUE THREAD

**Issue by d-ivashchuk** [gatsbyjs/gatsby#11040] opened 2019-01-13 13:07 UTC
## Summary
I am trying to import a pattern image into `global.js` file where I want to use it with styled components. When I try to use standard `import pattern from '../assets/x.jpg'` I think I get a webpack error:
```
✖ ｢wdm｣:
ERROR in ./src/assets/x.jpg 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./src/pages/index.js 8:0-38
 @ ./.cache/sync-requires.js
 @ ./.cache/app.js
 @ multi (webpack)-hot-middleware/client.js?path=/__webpack_hmr&reload=true&overlay=false ./.cache/app
ℹ ｢wdm｣: Failed to compile.
```
Maybe I am missing something, but `url-loader` seems to be present in `node-modules` and I've already tried to delete them and reinstall again. I have tried it with .jpg, .png and it's not working.

### Environment (if relevant)
  System:
    OS: macOS Sierra 10.12.6
    CPU: x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 63.0.1
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.53 => 2.0.53 
    gatsby-image: ^2.0.20 => 2.0.20 
    gatsby-plugin-layout: ^1.0.10 => 1.0.10 
    gatsby-plugin-manifest: ^2.0.9 => 2.0.9 
    gatsby-plugin-offline: ^2.0.16 => 2.0.16 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.2 
    gatsby-plugin-react-svg: ^2.0.0-beta1 => 2.0.0-beta1 
    gatsby-plugin-sharp: ^2.0.17 => 2.0.17 
    gatsby-plugin-styled-components: ^3.0.4 => 3.0.4 
    gatsby-source-contentful: ^2.0.20 => 2.0.20 
    gatsby-source-filesystem: ^2.0.8 => 2.0.8 
    gatsby-transformer-sharp: ^2.1.8 => 2.1.8 
  npmGlobalPackages:
    gatsby-cli: 2.4.3

**Comment by LekoArts** [comment] 2019-01-14 11:55
Do you have a link to a repository or can share your code?

**Comment by sidharthachatterjee** [comment] 2019-01-14 15:30
@d-ivashchuk Does this happen with a specific image or with any image that you try to `import`?

**Comment by sidharthachatterjee** [comment] 2019-01-14 15:50
@d-ivashchuk We've set url-loader's limit option to 10000 bytes (10kb). We do this to set a good default limit. The files you are trying to import are over a MB. 

Remember files handled by this are base64 encoded and add to the size of your bundle. 

Might I recommend using [gatsby-image](https://www.gatsbyjs.org/packages/gatsby-image/)?

**Comment by d-ivashchuk** [comment] 2019-01-14 17:07
Hmm, I didn't know that, thanks! I would like to use image as a background for the website and wasn't sure that `gatsby-image` is the best option for this. Anyways thanks for pointing out, I will try to do it with `Img`

**Comment by sidharthachatterjee** [comment] 2019-01-15 12:40
`gatsby-image` is great because you get a bunch of stuff for free including 
- ability to resize images
- lazy load them
- generate blurred versions while the actual image downloads

Closing this issue in the mean time but please feel free to comment or reopen if there is anything else!

**Closed by sidharthachatterjee** 2019-01-15 12:40 UTC
Labels: type: question or discussion

**Comment by theofromthelabo** [comment] 2019-04-04 04:44
Dear guys -

I got a similar error message and couldn't resolve it with the instructions as above. 

```
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
```

Pretty new at using React and Gatsby
When running a gatsby develop, but I got the error as above for all the images in the directory /src/assets/images/

Here is repository: https://github.com/theofromthelabo/thelabo

How can I resolve the issue?

Let me know if you need further info to replicate the issue.

Thank you in advance and have a good day.

**Comment by jonniebigodes** [comment] 2019-04-05 00:06
@theofromthelabo i picked up on your comment and i've cloned your provided repo and i only found a issue with it. And that's you have added `gatsby-plugin-react-svg` to `gatsby-config.js` and you don't have it installed, this based on your package.json.
Commenting out that entry and issuing `gatsby develop` your site builds fine. And the images are being loaded without any issue. Tested it out by opening up each page you have and all of them showed the images.
Also took it a step further and issued a production build with `gatsby build && gatsby serve` and i got the same result. 

If you don't mind, i would like to offer you some advice when you submit a reproduction to here, or a diferent place.  In your project root folder add a file called `.gitignore` with the contents like [this](https://github.com/gatsbyjs/gatsby-starter-default/blob/master/.gitignore).

**Comment by theofromthelabo** [comment] 2019-04-05 09:16
@jonniebigodes ohww 
thank for the fast and useful answer 
it resolved the issue and I added .gitignore - YEAH !

here is my commit: https://github.com/theofromthelabo/thelabo/commit/495b61b409a3f456e0a2749e61dc10a2224ff657

Thank you again ! have a good day !

**Comment by jonniebigodes** [comment] 2019-04-05 10:10
@theofromthelabo no problem,there's no need to thank, glad i could be of assistance and helped out solving your issue. Have good day aswell

**Comment by mwood23** [comment] 2019-05-31 04:58
Just ran into this error and it was because of `gatsby-plugin-react-svg` and my SVGs living in the same folder as `.png` and `.jpg` files. To fix, I separated them out so my folder structure looks like this.

```
/assets
  /images (for pngs and jpgs)
  /svgs
```

`gatsby-config.js`
```
    {
      resolve: 'gatsby-plugin-react-svg',
      options: {
        rule: {
          include: /svgs/,
        },
      },
    }
```

**Comment by Helloiain** [comment] 2019-06-22 07:29
@mwood23 wow I never would have thought about that. Thanks that fixed it for me.

**Comment by bhavikji** [comment] 2020-02-27 10:52
> Just ran into this error and it was because of `gatsby-plugin-react-svg` and my SVGs living in the same folder as `.png` and `.jpg` files. To fix, I separated them out so my folder structure looks like this.
> 
> ```
> /assets
>   /images (for pngs and jpgs)
>   /svgs
> ```
> 
> `gatsby-config.js`
> 
> ```
>     {
>       resolve: 'gatsby-plugin-react-svg',
>       options: {
>         rule: {
>           include: /svgs/,
>         },
>       },
>     }
> ```

@mwood23 : 
I have followed the same folder structure as mentioned.

```
/static
   /assets
      /images
      /svgs
```
and here is my `gatsby config.js`

```
{
      resolve: 'gatsby-source-filesystem',
      options: {
        path: `${__dirname}/static/assets/images`,
        name: 'assets',
      },
},
{
      resolve: 'gatsby-plugin-react-svg',
      options: {
        rule: {
          include: /svgs/,
        },
      },
},
```
But this isn't working for me.

**Comment by slk333** [comment] 2021-03-09 13:27
> Just ran into this error and it was because of `gatsby-plugin-react-svg` and my SVGs living in the same folder as `.png` and `.jpg` files. To fix, I separated them out so my folder structure looks like this.
> 
> ```
> /assets
>   /images (for pngs and jpgs)
>   /svgs
> ```
> 
> `gatsby-config.js`
> 
> ```
>     {
>       resolve: 'gatsby-plugin-react-svg',
>       options: {
>         rule: {
>           include: /svgs/,
>         },
>       },
>     }
> ```

how is this not mentioned in the plug-in readme?

**Comment by LekoArts** [comment] 2021-03-09 14:39
@slk333 
> how is this not mentioned in the plug-in readme?

You can send in a PR here: https://github.com/jacobmischka/gatsby-plugin-react-svg/pulls

**Comment by charterbran** [comment] 2021-03-24 16:27
> @d-ivashchuk We've set url-loader's limit option to 10000 bytes (10kb). We do this to set a good default limit. The files you are trying to import are over a MB.
> 
> Remember files handled by this are base64 encoded and add to the size of your bundle.
> 
> Might I recommend using [gatsby-image](https://www.gatsbyjs.org/packages/gatsby-image/)?

Hey guys - I have a similar but different issue with this. I have three zip files which are simply folders full of icons in different formats (svg, png, pdf). I want users to be able to click a button and download the zip files so they can access and use these icons. I get the same error that @theofromthelabo got above and I believe its for this same reason (the file size exceeding the default 10 kb limit). 

Any resources you can point me to to configure url-loader so that limit is increased? Thanks!
