### ISSUE TITLE
Loading (StaticQuery) - Gatsby site doesn't load in Netlify production but works fine locally

### ISSUE THREAD

**Issue by rileycookd** [gatsbyjs/gatsby#30670] opened 2021-04-04 00:13 UTC
## Description

I'm using Gatsby, Sanity, and Netlify and everything works as expected locally, both in development and build mode. Now, when I load my site on Netlify (no build errors) all I see is a white screen with "Loading (StaticQuery)". No errors for me to debug. The site just doesn't load at all. 

Only two of my components use Static Queries, the Layout component (which wraps everything, which is I presume why the site doesn't load at all in production) and an SEO component. Both components come from the starter I used and are pretty much untouched.

I'm using a modified version of this Sanity starter: https://github.com/sanity-io/example-company-website-gatsby-sanity-combo

### Steps to reproduce

I have tried to create a reproduction with the same starter but I haven't been able to replicate the issue. It must have something to do with my setup with this site specifically that I haven't been able to isolate. 

```
// Package.json 

"dependencies": {
    "@cloudflare/wrangler": "^1.15.0",
    "@fontsource/montserrat": "^4.2.2",
    "@fontsource/raleway": "^4.2.2",
    "@sanity/block-content-to-react": "^2.0.7",
    "@sanity/client": "^2.7.1",
    "@sanity/image-url": "^0.140.22",
    "date-fns": "^2.19.0",
    "dotenv": "^8.2.0",
    "gatsby": "^3.2.1",
    "gatsby-plugin-anchor-links": "^1.2.1",
    "gatsby-plugin-image": "^1.2.0",
    "gatsby-plugin-manifest": "^3.2.0",
    "gatsby-plugin-react-helmet": "^4.2.0",
    "gatsby-source-sanity": "^7.0.2",
    "get-youtube-id": "^1.0.1",
    "postcss-import": "^14.0.1",
    "postcss-preset-env": "^6.7.0",
    "react": "^17.0.2",
    "react-autosize-textarea": "^7.1.0",
    "react-dom": "^17.0.2",
    "react-helmet": "^6.1.0",
    "react-hook-form": "^6.15.5",
    "react-icons": "^4.2.0",
    "react-script": "^2.0.5",
    "react-tabs": "^3.2.1",
    "react-youtube": "^7.13.1"
  },
  "devDependencies": {
    "eslint": "^7.23.0",
    "eslint-config-standard": "^16.0.2",
    "eslint-config-standard-react": "^11.0.1",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.3.1",
    "eslint-plugin-react": "^7.23.1",
    "eslint-plugin-standard": "^5.0.0",
    "gatsby-plugin-postcss": "^4.2.0",
    "postcss": "^8.2.9",
    "prettier-eslint-cli": "^5.0.1",
    "prop-types": "^15.7.2"
  }
```

```
// Layout.js 

import { graphql, StaticQuery } from 'gatsby'
import React, { useState } from 'react'
import Layout from '../components/layout'

function LayoutContainer (props) {
  const [showNav, setShowNav] = useState(false)
  function handleShowNav () {
    setShowNav(true)
  }
  function handleHideNav () {
    setShowNav(false)
  }
  return (
    <StaticQuery
      query = {graphql`
        query SiteInfoQuery {
          site: sanitySiteSettings(_id: { regex: "/(drafts.|)siteSettings/" }) {
            title
          }
      
          company: sanityCompanyInfo {
            phone
            email
            _rawDescription
            name
            linkedin
            instagram
            facebook
          }
        }
      `}
      render={data => {
        if (!data.site) {
          throw new Error(
            'Missing "Site settings". Open the studio at http://localhost:3333 and add "Site settings" data'
          )
        }
        if (!data.company) {
          throw new Error(
            'Missing "company info". Open the studio at http://localhost:3333 and add "company info" data'
          )
        }
        return (
          <Layout
            {...props}
            showNav={showNav}
            company={data.company}
            siteTitle={data.site.title}
            onHideNav={handleHideNav}
            onShowNav={handleShowNav}
          />
        )
      }}
    />
  )
}

export default LayoutContainer

```

### Expected result

Site loads normally as it does locally. 

### Actual result

Gatsby only loads a single element that just reads "Loading (StaticQuery)" for all pages. 

### Environment

Below is my system environment, but again the problem only exists on Netlify in the production build.

  System:
    OS: Linux 4.4 Ubuntu 18.04.2 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 15.3.0 - ~/.nvm/versions/node/v15.3.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v15.3.0/bin/npm
  Languages:
    Python: 3.8.0 - /usr/bin/python
  npmPackages:
    gatsby: ^3.2.1 => 3.2.1
    gatsby-plugin-anchor-links: ^1.2.1 => 1.2.1
    gatsby-plugin-image: ^1.2.0 => 1.2.0
    gatsby-plugin-manifest: ^3.2.0 => 3.2.0
    gatsby-plugin-postcss: ^4.2.0 => 4.2.0
    gatsby-plugin-react-helmet: ^4.2.0 => 4.2.0
    gatsby-source-sanity: ^7.0.2 => 7.0.2
  npmGlobalPackages:
    gatsby-cli: 2.19.1

**Comment by LekoArts** [comment] 2021-04-06 07:18
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-04-14 07:54
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed** 2021-04-14 07:57 UTC
Labels: status: needs reproduction, type: bug
