### ISSUE TITLE
Issue running "npm install -g gatsby-cli" 

### ISSUE THREAD

**Issue by ohamuy** [gatsbyjs/gatsby#26337] opened 2020-08-10 17:54 UTC
## Description

Cannot properly install Gatsby. 

### Steps to reproduce

Run npm install -g gatsby-cli

### Expected result

Gatsby successfully installed

### Actual result

<img width="1083" alt="Screen Shot 2020-08-10 at 10 49 10 AM" src="https://user-images.githubusercontent.com/46689344/89814235-acda8200-daf7-11ea-9348-03613dd94b47.png">

### Environment

Running this on Mac with macOS Catalina Version 10.15.5
Git 2.28.0
npm 6.14.4
node 13.13.0
brew 2.4.9

**Comment by blainekasten** [comment] 2020-08-10 19:55
According to that screenshot gatsby did install correctly. If you run `gatsby` in the CLI does it not work?

I'm going to close this issue as it appears to be working. Please respond and if there is an issue we will reopen, thanks!

**Closed by blainekasten** 2020-08-10 19:55 UTC
Labels: status: triage needed, type: bug

**Comment by ohamuy** [comment] 2020-08-10 19:59
Thanks for responding! As you can see in the screenshot above i try running a gatsby command and it doesn't work. what am i doing wrong?

**Comment by ohamuy** [comment] 2020-08-10 20:11
Also I have xcode installed as per the instructions on GatsbyJS

**Comment by KyleAMathews** [comment] 2020-08-10 20:16
This can happen for a few reasons — but generally the problem is either where NPM global packages are installed isn't on your $PATH or fs permissions aren't correct for letting you run CLI commands — this stackoverflow has some debugging ideas https://stackoverflow.com/questions/31472755/sudo-npm-command-not-found/39622369
