### ISSUE TITLE
[gatsby-source-wordpress] Gatsby Cloud Preview fails

### ISSUE THREAD

**Issue by igorbumba** [gatsbyjs/gatsby#30610] opened 2021-04-01 08:17 UTC
## Description

Trying to run a preview of the page using WordPress with Gatsby Cloud.

### Steps to reproduce

Run Preview from WordPress CMS.

### Expected result

Should see preview, fails most of the time. Sometimes it works, I would say like 20% of tries.

### Actual result

Getting error in the Gatsby Cloud console (token and URL removed because it's a client project):

```bash
10:00:53 AM:
success  gatsby-source-wordpress  diff schemas - 0.692s

10:00:53 AM:
success  gatsby-source-wordpress  ingest WPGraphQL schema - 0.868s

10:00:53 AM:
success createSchemaCustomization - 0.892s

10:00:53 AM:
info Sourcing previews for the following webhook:

10:00:53 AM:
/usr/src/app/www/node_modules/gatsby-source-wordpress/dist/steps/preview/index.js:258:

10:00:53 AM:
object (size=9) {

10:00:53 AM:
    'previewDatabaseId' => int 453,

10:00:53 AM:
    'id' => string "cG9zdDoxOTk=" (length=12),

10:00:53 AM:
    'singleName' => string "font" (length=4),

10:00:53 AM:
    'remoteUrl' => string "" (length=58),

10:00:53 AM:
    'isDraft' => boolean false,

10:00:53 AM:
    'modified' => string "2021-04-01 08:00:46" (length=19),

10:00:53 AM:
    'parentDatabaseId' => int 199,

10:00:53 AM:
    'token' => string "" (length=349),

10:00:53 AM:
}

10:00:53 AM:
    'userDatabaseId' => int 1,

10:00:54 AM:
ERROR TypeError: Cannot read property 'reporter' of undefined

10:00:54 AM:
    at forEach (/usr/src/app/www/node_modules/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-nodes-paginated.js:105:19)

10:00:54 AM:
    at paginatedWpNodeFetch (/usr/src/app/www/node_modules/gatsby-source-wordpress/src/steps/source-nodes/fetch-nodes/fetch-nodes-paginated.js:95:11)

10:00:54 AM:
    at Array.forEach ()

10:00:54 AM:
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

10:00:54 AM:
    at sourceNodes (/usr/src/app/www/node_modules/gatsby-source-wordpress/src/steps/source-nodes/index.ts:24:5)

10:00:54 AM:
    at runSteps (/usr/src/app/www/node_modules/gatsby-source-wordpress/src/utils/run-steps.ts:41:9)

10:00:54 AM:
    at sourcePreviews (/usr/src/app/www/node_modules/gatsby-source-wordpress/src/steps/preview/index.ts:330:26)

10:00:54 AM:
    at runAPI (/usr/src/app/www/node_modules/gatsby/src/utils/api-runner-node.js:434:16)

10:00:54 AM:
ERROR  gatsby-source-wordpress  

10:00:54 AM:
	Encountered a critical error when running the sourceNodes.sourceNodes build step.

10:00:54 AM:
	See above for more information.

10:00:54 AM:
not finished source and transform nodes - 0.850s

10:00:56 AM:
ERROR Failed to compile
```

### Environment

```bash
  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.12.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.6.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.114
    Edge: 89.0.774.63
    Firefox: 85.0.2
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.2.0 => 3.2.0
    gatsby-plugin-gatsby-cloud: ^2.1.0 => 2.2.0
    gatsby-plugin-image: ^1.0.0 => 1.2.0
    gatsby-plugin-manifest: ^3.0.0 => 3.2.0
    gatsby-plugin-react-helmet: ^4.0.0 => 4.2.0
    gatsby-plugin-root-import: ^2.0.6 => 2.0.6
    gatsby-plugin-sass: ^4.0.0 => 4.2.0
    gatsby-plugin-sharp: ^3.0.0 => 3.2.0
    gatsby-source-filesystem: ^3.0.0 => 3.2.0
    gatsby-source-wordpress: ^5.2.0 => 5.2.0
    gatsby-transformer-sharp: ^3.0.0 => 3.2.0
  npmGlobalPackages:
    gatsby-cli: 3.0.0
```

**Comment by LekoArts** [comment] 2021-04-06 07:32
Duplicate of https://github.com/gatsbyjs/gatsby/issues/30628

**Closed by LekoArts** 2021-04-06 07:32 UTC
Labels: status: triage needed, type: bug
