### ISSUE TITLE
Error Building static HTML failed for path "/home/"

### ISSUE THREAD

**Issue by abdokouta** [gatsbyjs/gatsby#22594] opened 2020-03-26 18:33 UTC
## Description
`Building static HTML failed for path "/404/"

See our docs page for more info on this error: https://gatsby.dev/debug-html

  Error: Minified React error #294; visit https://reactjs.org/docs/error-decoder.html?invariant=294 for the full message or use the non-minified dev environment f  or full errors and additional helpful warnings.

  - react-dom-server.node.production.min.js:46 a.b.render
    [myproject]/[react-dom]/cjs/react-dom-server.node.production.min.js:46:17

  - react-dom-server.node.production.min.js:44 a.b.read
    [myproject]/[react-dom]/cjs/react-dom-server.node.production.min.js:44:18

  - react-dom-server.node.production.min.js:54 renderToString
    [myproject]/[react-dom]/cjs/react-dom-server.node.production.min.js:54:364

  - render-page.js:612 Module../.cache/static-entry.js.__webpack_exports__.default
    E:/myproject/public/render-page.js:612:28

  - render-html.js:28 
    [myproject]/[gatsby]/dist/utils/worker/render-html.js:28:36

  - debuggability.js:384 Promise._execute
    [myproject]/[bluebird]/js/release/debuggability.js:384:9

  - promise.js:518 Promise._resolveFromExecutor
    [myproject]/[bluebird]/js/release/promise.js:518:18

  - promise.js:103 new Promise
    [myproject]/[bluebird]/js/release/promise.js:103:10

  - render-html.js:24 
    [myproject]/[gatsby]/dist/utils/worker/render-html.js:24:47

  - util.js:16 tryCatcher
    [myproject]/[bluebird]/js/release/util.js:16:23

  - map.js:68 MappingPromiseArray._promiseFulfilled
    [myproject]/[bluebird]/js/release/map.js:68:38

  - promise_array.js:115 MappingPromiseArray.PromiseArray._iterate
    [myproject]/[bluebird]/js/release/promise_array.js:115:31

  - promise_array.js:79 MappingPromiseArray.init
    [myproject]/[bluebird]/js/release/promise_array.js:79:10

  - map.js:37 MappingPromiseArray._asyncInit
    [myproject]/[bluebird]/js/release/map.js:37:10

  - async.js:97 _drainQueueStep
    [myproject]/[bluebird]/js/release/async.js:97:12

  - async.js:86 _drainQueue
    [myproject]/[bluebird]/js/release/async.js:86:9

not finished Generating image thumbnails - 228.649s`

### Steps to reproduce
gatsby-clean & gatsby build

### Expected result

to build the project and HMTL static files to be generated
### Actual result
Error Building static HTML failed for path "/home/", "/404/" or any dynamic page created by gatbsy-node file

### Environment
Production

`
System:
    OS: Linux 4.15 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (2) x64 Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.14.2 - /usr/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    gatsby: ^2.19.5 => 2.20.7
    gatsby-cli: ^2.11.2 => 2.11.2
    gatsby-image: ^2.2.39 => 2.2.43
    gatsby-link: ^2.2.28 => 2.2.30
    gatsby-paginate: ^1.1.1 => 1.1.1
    gatsby-plugin-algolia: ^0.5.0 => 0.5.0
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5
    gatsby-plugin-analytics: ^0.2.0 => 0.2.0
    gatsby-plugin-catch-links: ^2.0.2 => 2.1.27
    gatsby-plugin-dark-mode: ^1.1.0 => 1.1.0
    gatsby-plugin-facebook-analytics: ^2.2.20 => 2.2.22
    gatsby-plugin-facebook-pixel: ^1.0.3 => 1.0.3
    gatsby-plugin-feed: ^2.0.5 => 2.3.28
    gatsby-plugin-firebase: ^0.1.8 => 0.1.8
    gatsby-plugin-google-analytics: ^2.1.34 => 2.1.37
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-guess-js: ^1.1.31 => 1.1.31
    gatsby-plugin-i18n: ^1.0.1 => 1.0.1
    gatsby-plugin-intercom-spa: ^0.2.0 => 0.2.0
    gatsby-plugin-intl: ^0.3.3 => 0.3.3
    gatsby-plugin-layout: ^1.0.2 => 1.1.23
    gatsby-plugin-lint-queries: ^0.0.3 => 0.0.3
    gatsby-plugin-mailchimp: ^5.1.2 => 5.1.2
    gatsby-plugin-manifest: ^2.2.40 => 2.2.45
    gatsby-plugin-netlify: ^2.0.0 => 2.1.34
    gatsby-plugin-nprogress: ^2.1.18 => 2.1.20
    gatsby-plugin-offline: ^3.0.33 => 3.0.38
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-provide-react: ^1.0.0 => 1.0.0
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.23
    gatsby-plugin-react-redux: ^1.1.0-0 => 1.1.0-0
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-remove-trailing-slashes: ^2.1.22 => 2.1.22
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sentry: ^1.0.1 => 1.0.1
    gatsby-plugin-sharp: ^2.4.0 => 2.5.3
    gatsby-plugin-sitemap: ^2.2.26 => 2.2.28
    gatsby-plugin-styled-components: ^3.1.18 => 3.1.20
    gatsby-plugin-styled-jsx: ^3.0.1 => 3.1.20
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-remark-copy-linked-files: ^2.0.5 => 2.1.39
    gatsby-remark-emojis: ^0.2.3 => 0.2.5
    gatsby-remark-external-links: ^0.0.4 => 0.0.4
    gatsby-remark-images: ^3.1.43 => 3.1.47
    gatsby-remark-prismjs: ^3.3.30 => 3.3.33
    gatsby-source-filesystem: ^2.1.47 => 2.1.51
    gatsby-source-googlemaps-geocoding: ^1.0.0 => 1.0.0
    gatsby-source-instagram: ^0.7.0 => 0.7.0
    gatsby-source-magento: file:plugins/gatsby-source-magento => 1.6.5
    gatsby-source-wordpress: file:plugins/gatsby-source-wordpress => 3.1.60
    gatsby-transformer-json: ^2.2.25 => 2.2.27
    gatsby-transformer-remark: ^2.6.49 => 2.6.56
    gatsby-transformer-sharp: ^2.3.13 => 2.3.17
  npmGlobalPackages:
    gatsby-cli: 2.10.4
`

**Comment by arthurjdam** [comment] 2020-03-26 19:33
Can't really tell without some source, but, judging by the error it seems like you might be using Suspense which doesn't yet work with gatsby's SSR renderer: https://www.gatsbyjs.org/docs/using-client-side-only-packages/#workaround-4-use-reactlazy-and-suspense-on-client-side-only 

Replacing with [loadable](https://github.com/gregberge/loadable-components) would be the way to go.

**Comment by vladar** [comment] 2020-03-27 14:29
Hi @abdokouta !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by abdokouta** [comment] 2020-03-27 22:26
@arthurjdam thank you for the help i have been into this for 5 days in a row. i will let you know the result.

**Comment by abdokouta** [comment] 2020-04-04 15:06
@arthurjdam after removing Lazyloading i'm getting this error any recommendations please?
<img width="1680" alt="Screen Shot 2020-04-04 at 6 04 58 PM" src="https://user-images.githubusercontent.com/12934929/78454160-fc6af600-769e-11ea-910c-c7ccb7fe33fc.png">

**Comment by arthurjdam** [comment] 2020-04-05 03:56
Not sure without a deeper look into the relevant code, but I assume replacing your suspended component with one through loadable will sort it out: https://github.com/gregberge/loadable-components#example

**Comment by abdokouta** [comment] 2020-04-05 04:04
@arthurjdam i will check and let u know, i have one more question do u have any direct contact line i would like to ask about some stuff related to our project and gatsbyjs. Thank you

**Comment by vuthaiduy1990** [comment] 2020-04-28 05:32
> Can't really tell without some source, but, judging by the error it seems like you might be using Suspense which doesn't yet work with gatsby's SSR renderer: https://www.gatsbyjs.org/docs/using-client-side-only-packages/#workaround-4-use-reactlazy-and-suspense-on-client-side-only
> 
> Replacing with [loadable](https://github.com/gregberge/loadable-components) would be the way to go.

solved my problem

**Comment by apsrcreatix** [comment] 2020-05-01 17:46
Hey folks,

I was getting the same issue then I removed the code of **Suspense** and **Lazy** load from my file. It worked!

I hope it may work for you as well until they add the support for these.

Happy Coding!

**Comment by AishwaryaChat** [comment] 2020-05-07 19:57
@vladar  I have been trying to deploy my gatbsy app on Netlify but I keep getting this error, not sure why is this happening. Here is how my gastby-config.js file looks like const path = require(`path`)

```
module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: path.join(__dirname, `src`, `images`),
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    {
      resolve: `gatsby-plugin-material-ui`,
      options: {
        stylesProvider: {
          injectFirst: true,
        },
      },
    },
    {
      resolve: "gatsby-plugin-webfonts",
      options: {
        fonts: {
          google: [
            {
              family: "Open Sans Condensed",
              variants: ["300", "700"],
            },
          ],
        },
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,
  ],
}
```

<img width="1434" alt="Screenshot 2020-05-08 at 1 23 33 AM" src="https://user-images.githubusercontent.com/19374847/81338716-b4d6f000-90ca-11ea-9766-435c7ba2cb31.png">

**Comment by wardpeet** [comment] 2020-05-13 14:44
I'm going to close this thread, please re-open new issues if you have any problems.

Please checkout https://www.gatsbyjs.org/docs/debugging-html-builds/ for more information.

**Closed by wardpeet** 2020-05-13 14:44 UTC
Labels: status: needs reproduction, type: bug

**Comment by williamkwon97** [comment] 2020-05-27 18:34
I have a same issue, I search the codes if I have lazy or Suspense, but I didn't find any code like that. How do I resolve this issue?
About.js
![Screen Shot 2020-05-27 at 1 31 14 PM](https://user-images.githubusercontent.com/34716439/83058796-86d83200-a01e-11ea-9f9a-f0588963fa98.png)
layout.js
![Screen Shot 2020-05-27 at 1 33 04 PM](https://user-images.githubusercontent.com/34716439/83058909-b424e000-a01e-11ea-84be-1f02252d0c63.png)

![Screen Shot 2020-05-27 at 1 31 09 PM](https://user-images.githubusercontent.com/34716439/83058799-8770c880-a01e-11ea-9805-b3d93b8bfd32.png)

my repository https://github.com/williamkwon97/GatsbyJS

**Comment by Tyerlo** [comment] 2020-06-14 11:07
Well I have the same issue: ailed Building static HTML for pages - 1.440s

 ERROR #95313 

Building static HTML failed for path "/jobdescription/"

See our docs page for more info on this error: https://gatsby.dev/debug-html



  TypeError: Cannot read property 'title' of undefined
  
  - render-page.js:17324 jobdescription
    /Users/thomas/projects/work-publication/public/rende    r-page.js:17324:400
  
  - react-dom-server.node.production.min.js:36 d
    [work-publication]/[react-dom]/cjs/react-dom-server.    node.production.min.js:36:498
  
  - react-dom-server.node.production.min.js:39 $a
    [work-publication]/[react-dom]/cjs/react-dom-server.    node.production.min.js:39:16
  
  - react-dom-server.node.production.min.js:44 a.b.rende    r
    [work-publication]/[react-dom]/cjs/react-dom-server.    node.production.min.js:44:476
  
  - react-dom-server.node.production.min.js:44 a.b.read
    [work-publication]/[react-dom]/cjs/react-dom-server.    node.production.min.js:44:18
  
  - react-dom-server.node.production.min.js:54 renderToS    tring
    [work-publication]/[react-dom]/cjs/react-dom-server.    node.production.min.js:54:364
  
  - render-page.js:633 Module../.cache/static-entry.js._    _webpack_exports__.default
    /Users/thomas/projects/work-publication/public/rende    r-page.js:633:28
  
  - render-html.js:28 _bluebird.default
    [work-publication]/[gatsby]/dist/utils/worker/render    -html.js:28:36
  
  - debuggability.js:384 Promise._execute
    [work-publication]/[bluebird]/js/release/debuggabili    ty.js:384:9
  
  - promise.js:518 Promise._resolveFromExecutor
    [work-publication]/[bluebird]/js/release/promise.js:    518:18
  
  - promise.js:103 new Promise
    [work-publication]/[bluebird]/js/release/promise.js:    103:10
  
  - render-html.js:24 _bluebird.default.map.path
    [work-publication]/[gatsby]/dist/utils/worker/render    -html.js:24:47
  
  - util.js:16 tryCatcher
    [work-publication]/[bluebird]/js/release/util.js:16:    23
  
  - map.js:68 MappingPromiseArray._promiseFulfilled
    [work-publication]/[bluebird]/js/release/map.js:68:3    8
  
  - promise_array.js:115 MappingPromiseArray.PromiseArra    y._iterate
    [work-publication]/[bluebird]/js/release/promise_arr    ay.js:115:31
  
  - promise_array.js:79 MappingPromiseArray.init
    [work-publication]/[bluebird]/js/release/promise_arr    ay.js:79:10

**Comment by lifeeric** [comment] 2020-07-19 11:37
I'm having the same problem, I've been trying to solve for awhile but didn't find any solution! what's happening here?

```

 ERROR #95313 

Building static HTML failed for path "/"

See our docs page for more info on this error: https://gatsby.dev/debug-html





  Error: Minified React error #294; visit https://reactjs.org/docs/error-decoder.html?invariant=294 for   the full message or use the non-minified dev environment for full errors and additional helpful warnin  gs.
  
  - react-dom-server.node.production.min.js:46 a.b.render
    [githubeuser]/[react-dom]/cjs/react-dom-server.node.production.min.js:46:17
  
  - react-dom-server.node.production.min.js:44 a.b.read
    [githubeuser]/[react-dom]/cjs/react-dom-server.node.production.min.js:44:18
  
  - react-dom-server.node.production.min.js:54 renderToString
    [githubeuser]/[react-dom]/cjs/react-dom-server.node.production.min.js:54:364
  
  - render-page.js:622 Module../.cache/static-entry.js.__webpack_exports__.default
    /home/dr/code/ts/gatsby/githubeuser/public/render-page.js:622:28
  
  - render-html.js:28 
    [githubeuser]/[gatsby]/dist/utils/worker/render-html.js:28:36
  
  - debuggability.js:384 Promise._execute
    [githubeuser]/[bluebird]/js/release/debuggability.js:384:9
  
  - promise.js:518 Promise._resolveFromExecutor
    [githubeuser]/[bluebird]/js/release/promise.js:518:18
  
  - promise.js:103 new Promise
    [githubeuser]/[bluebird]/js/release/promise.js:103:10
  
  - render-html.js:24 
    [githubeuser]/[gatsby]/dist/utils/worker/render-html.js:24:47
  
  - util.js:16 tryCatcher
    [githubeuser]/[bluebird]/js/release/util.js:16:23
  
  - map.js:68 MappingPromiseArray._promiseFulfilled
    [githubeuser]/[bluebird]/js/release/map.js:68:38
  
  - promise_array.js:115 MappingPromiseArray.PromiseArray._iterate
    [githubeuser]/[bluebird]/js/release/promise_array.js:115:31
  
  - promise_array.js:79 MappingPromiseArray.init
    [githubeuser]/[bluebird]/js/release/promise_array.js:79:10
  
  - map.js:37 MappingPromiseArray._asyncInit
    [githubeuser]/[bluebird]/js/release/map.js:37:10
  
  - async.js:97 _drainQueueStep
    [githubeuser]/[bluebird]/js/release/async.js:97:12
  
  - async.js:86 _drainQueue
    [githubeuser]/[bluebird]/js/release/async.js:86:9
  

```

**Comment by arthurjdam** [comment] 2020-07-19 18:53
It shows in the error: [ReactDOMServer does not yet support Suspense](https://reactjs.org/docs/error-decoder.html/?invariant=294)
To fix, replace your use of Suspense with [loadable](https://github.com/gregberge/loadable-components#example)

**Comment by lifeeric** [comment] 2020-07-24 04:31
Solved by removing React.lazy

https://stackoverflow.com/questions/62978046/building-static-html-for-pageserror-error-enoent-no-such-file-or-directory/63066839#63066839
