### ISSUE TITLE
[gatsby-image] Webp format not used unless toFormat is specified.

### ISSUE THREAD

**Issue by smurrayatwork** [gatsbyjs/gatsby#17995] opened 2019-09-30 14:54 UTC
## Description

Under the documentation describing how to use fragments with webp, the following appears:

> If you want to automatically use WebP images when the browser supports the file format, use the withWebp fragments. If the browser doesn’t support WebP, gatsby-image will fall back to the default image format.

While this is correct, WebP images don't appear to render using the component from the gatsby-image package without also setting `toFormat: WEBP` with `fixed` or `fluid` queries. This documentation should be updated to mention this, or if this is a bug it should be fixed.

### Steps to reproduce
1. Query a data source using `fixed` or `fluid`  [and a supported webp fragment.](https://www.gatsbyjs.org/packages/gatsby-image/#gatsby-transformer-sharp) Do not use `toFormat`.
2. Using the gatsby-image package, try to render an image from the data, using the `fixed` or `fluid` props.

### Expected result
Using the component from the gatsby-image package with a supported webp fragment renders a picture tag whose source paths reference the webp image path.

### Actual result
The original format of the image renders.

**Comment by FailedSitcom** [comment] 2019-10-01 18:21
@smurrayatwork @pranshuchittora I'd like to take a look at this

**Comment by graysonhicks** [comment] 2019-10-01 19:22
Having this same issue.  When using the `toFormat` workaround, the png fallback seems to break for non-Webp browsers.

**Comment by FailedSitcom** [comment] 2019-10-01 19:30
@smurrayatwork & @graysonhicks using the following code (slightly modifying the Gatsby Starter):

```
const Image = () => {
  const data = useStaticQuery(graphql`
    query {
      placeholderImage: file(relativePath: { eq: "gatsby-astronaut.png" }) {
        childImageSharp {
          fluid(maxWidth: 300) {
            ...GatsbyImageSharpFluid_withWebp
          }
        }
      }
    }
  `)

  return <Img fluid={data.placeholderImage.childImageSharp.fluid} />
}
```

I'm finding the Firefox and Chrome are rendering a webp image and Safari is correctly falling back to a PNG. May I enquire if your query differs greatly from mine, as well as what your image source is? Thank you!

**Comment by graysonhicks** [comment] 2019-10-01 21:12
I just reverted our switch to Webp back to regular Fluid and Fixed fragments.  Only difference I see is we had noBase64, but I did not have a change to test with the regular Webp fragment.  I will both again tomorrow +/- toFormat and double check.

**Comment by graysonhicks** [comment] 2019-10-04 15:19
I believe this was working as intended originally, as I am unable to replicate.  What I can confirm is that `toFormat: WEBP` will remove fallback images for Safari.

**Comment by graysonhicks** [comment] 2019-10-04 15:27
This is a screenshot of using the withWebp fragment on the image.  If the screenshot and my notes are correct, we can close this issue.  (@smurrayatwork and I encountering this issue on same project together) 
<img width="1454" alt="webp vs png" src="https://user-images.githubusercontent.com/16200795/66219785-c7eb9280-e699-11e9-8097-5abe7b1c1df2.png">

**Comment by graysonhicks** [comment] 2019-10-04 15:58
@FailedSitcom If that looks okay to you, I can close.  Now we are left with this issue... #10203 😬

**Comment by FailedSitcom** [comment] 2019-10-04 16:00
@graysonhicks that sounds good to me, will try and take a look at your other issue over the weekend. 🙂

**Closed** 2019-10-04 16:31 UTC
Labels: Hacktoberfest, topic: images/media, type: bug
