### ISSUE TITLE
Building Static HTML failed

### ISSUE THREAD

**Issue by dina-25** [gatsbyjs/gatsby#27557] opened 2020-10-19 20:19 UTC
In development mood my website works fine without any errors, but now I'm trying to build product i keep getting this error and I tried many solutions (including deleting node_modules and reinstall again) but nothing seem to work.

I'm not sure anymore what is the underlying issue behind this error.
Help would be much appreciated.

this is the result i get while building the website
![error](https://user-images.githubusercontent.com/40601380/96506989-d1ba4680-1258-11eb-8b45-95e7e6ffe2a1.PNG)

**Comment by pvdz** [comment] 2020-10-20 10:40
Hi @dina-25, would this happen to be a public repo we can take a look at? It's a bit hard to debug without more information.

**Comment by dina-25** [comment] 2020-10-20 14:48
https://github.com/dina-25/amap there is a link to the repo.

**Comment by ascorbic** [comment] 2020-10-22 11:49
Hi @dina-25,
When I run the build, the error I get is from "gatsby-plugin-intl", because `src/intl/en.json` is missing. Do you have those files locally?

**Comment by dina-25** [comment] 2020-10-22 12:20
I do yes. I will upload them as well

**Comment by ascorbic** [comment] 2020-11-05 11:56
Hi,
I still can't build your repo I'm afraid. There are still missing files. This time it's missing lots of sass files. Are you able to share the full project?

**Comment by ascorbic** [comment] 2020-11-19 10:09
Hi. I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. Thanks!

**Closed by ascorbic** 2020-11-19 10:09 UTC
Labels: status: awaiting author response, status: needs more info, type: bug
