### ISSUE TITLE
Error loading a result for the page query

### ISSUE THREAD

**Issue by melilocacr** [gatsbyjs/gatsby#21944] opened 2020-03-04 00:15 UTC

**Comment by LekoArts** [comment] 2020-03-04 13:31
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2020-03-16 11:19
Let's close this issue. Feel free to open a new one following our issue template and providing a minimal reproduction. Thanks!

**Closed by LekoArts** 2020-03-16 11:19 UTC
Labels: status: needs reproduction
