### ISSUE TITLE
Generating Development bundles failed - EINVAL: invalid argument, mkdir

### ISSUE THREAD

**Issue by saswatawork** [gatsbyjs/gatsby#32007] opened 2021-06-21 17:44 UTC
## Description

After upgrading gatsby version  to 3.7.1 in windows machine gatsby throwing error when trying to generate development build and starting dev servers. The errors occur due to wrong path it's getting when trying to create directory for development bundle.

![image](https://user-images.githubusercontent.com/20141850/122799701-abfda980-d2df-11eb-90e9-ed1f858df2de.png)

### Steps to reproduce
- In windows machine upgrade gatsby version  to 3.7.1
- try yo generate development build
- on `verbose Transition to "startingDevServers"` step it will throw an error
- EINVAL: invalid argument, mkdir
'C:\Users\SaswataPal\workspace\studio\public\C:\Users\SaswataPal\workspace\studio\public'

### Expected result

Development bundle should create succesfully

### Actual result

Development bundle is failing because of wrong path it's getting

### Environment

  System:
    OS: Windows 10 10.0.19043
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - C:\Users\SaswataPal\.windows-build-tools\python27\python.EXE
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.54)
  npmPackages:
    gatsby: ^3.7.1 => 3.7.2 
    gatsby-plugin-loadable-components-ssr: ^3.0.0 => 3.1.0 
    gatsby-plugin-postcss: ^4.7.1 => 4.7.1 
    gatsby-plugin-react-decorators: 0.0.4 => 0.0.4 
    gatsby-plugin-react-helmet: ^4.7.1 => 4.7.1 
    gatsby-plugin-react-svg: ^3.0.1 => 3.0.1 
    gatsby-plugin-root-import: ^2.0.5 => 2.0.6 
    gatsby-plugin-sass: ^4.7.1 => 4.7.1 
    gatsby-plugin-smoothscroll: ^1.2.0 => 1.2.0 
    gatsby-plugin-typescript: ^3.7.1 => 3.7.1 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.22 => 1.1.22 
  npmGlobalPackages:
    gatsby-cli: 3.7.1

**Comment by vladar** [comment] 2021-06-22 08:10
Hi @saswatawork !

Can you please clarify the reproduction steps? I've tried this:

```
gatsby new gh32007 https://github.com/gatsbyjs/gatsby-starter-blog
cd gh32007
yarn add gatsby@3.7.1
yarn develop --verbose
```

And it started the dev server successfully. So it seems that some other component/plugin affects the result for you.

To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.


[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-07-06 09:54
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-07-06 09:54 UTC
Labels: status: needs reproduction, type: bug

**Comment by solomojb** [comment] 2021-07-06 15:56
Hi, We figured out our error. It was related to a plugin that was causing the problem. 

For anyone else looking through the internet who may stumble across this: gatsby-plugin-loadable-components-ssr was the problem.
