### ISSUE TITLE
`yarn serve` after a build has an out of memory error

### ISSUE THREAD

**Issue by ChrisSargent** [gatsbyjs/gatsby#34843] opened 2022-02-17 18:24 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

After running a build, if we try to run `yarn build` results in an out of memory error. Using the same build with https://www.npmjs.com/package/serve, with the command `npx serve public` does not result in the error.

I'm really sorry but at this point I don't have a reproduction repo, I will try to get one.

### Reproduction Link

https://github.com/ChrisSargent/webpack-gatsby-issue/tree/serve-error

### Steps to Reproduce

1. Run `yarn build`
2. Run `yarn serve`

### Expected Result

The site is served

### Actual Result

Out of memory errors

### Environment

```shell
System:
    OS: macOS 12.1
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.0 - /private/var/folders/dw/lgl4dq6j3r30y378tlykv85r0000gn/T/xfs-1e4057c5/node
    Yarn: 3.1.1 - /private/var/folders/dw/lgl4dq6j3r30y378tlykv85r0000gn/T/xfs-1e4057c5/yarn
    npm: 6.14.16 - ~/.nvm/versions/node/v14.19.0/bin/npm
  Languages:
    Python: 3.9.10 - /usr/local/opt/python/libexec/bin/python
  Browsers:
    Chrome: 98.0.4758.102
    Firefox: 94.0.1
    Safari: 15.2
```

### Config Flags

```js
const gatsbyConfig = {
  flags: {
    FAST_DEV: true,
  },
  plugins: [
    'gatsby-plugin-image',
    'gatsby-plugin-react-helmet',
    'gatsby-plugin-sharp',
    'gatsby-transformer-sharp',
    {
      options: {
        display: 'standalone',
        icon: './src/images/app-icon.svg',
        start_url: '/',
      },
      resolve: 'gatsby-plugin-manifest',
    },
    {
      resolve: 'gatsby-plugin-offline',
    },
    {
      __key: 'images',
      options: {
        name: 'images',
        path: './src/images/',
      },
      resolve: 'gatsby-source-filesystem',
    },
    {
      options: {
        autoLabel: 'dev-only',
        cssPropOptimization: true,
        labelFormat: '[local]',
        sourceMap: true,
      },
      resolve: 'gatsby-plugin-emotion',
    },
    {
      options: {
        custom: {
          families: [
            'GT-America-Expanded-Black',
            'GT-America-Expanded-Black-Italic',
            'GT-America-Extended-Black',
            'GT-America-Extended-Medium',
            'GT-America-Standard-Bold',
            'GT-America-Standard-Regular',
            'GT-America-Standard-Regular-Italic',
            '',
          ],
        },
        google: {
          families: ['Poppins:400,600&display=swap'],
        },
      },
      resolve: 'gatsby-plugin-web-font-loader',
    },
    {
      options: {
        disable: process.env.CI || process.env.DISABLE_ANALYSER,
      },
      resolve: 'gatsby-plugin-webpack-bundle-analyser-v2',
    },
    {
      options: {
        enableWebVitalsTracking: true,
        id: process.env.WA_GOOGLE_TAGMANAGER_ID,
        includeInDevelopment: true,
      },
      resolve: 'gatsby-plugin-google-tagmanager',
    },
    {
      options: {
        devKey: process.env.SEGMENT_WRITE_KEY,
        prodKey: process.env.SEGMENT_WRITE_KEY,
        trackPage: true,
      },
      resolve: `gatsby-plugin-segment-js`,
    },
  ],
  siteMetadata: {
    title: 'Noah Application',
  },
};
```

**Comment by tyhopp** [comment] 2022-02-18 03:11
Hi @ChrisSargent !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction].

> After running a build, if we try to run yarn build results in an out of memory error. Using the same build with https://www.npmjs.com/package/serve, with the command npx serve public does not result in the error.

Also can you help clarify what you mean here, do you get an OOM error every time you run `yarn build` on your site? Changing server packages should be unrelated.

Thank you!

[reproduction]: https://gatsby.dev/reproduction

**Comment by ChrisSargent** [comment] 2022-02-18 11:15
Hi @tyhopp - I've added a repo link of the same setup that's causing us a problem - however, the problem does not reproduce here. Few points to note:

* This same module in our monorepo results in an error
* Changing the Gatsby config to a pure JS file prevents the error
* Removing any of those plugins prevents the error
* and the MOST STRANGE one but probably the most telling, is that despite the `export const config` from the `src/config.js` file not being used anywhere, if you rename that export, everything works as expected

I'm happy to provide you access to our monorepo where I have a branch which has this minimal repro too.

For now we can work around by just renaming the export.

Ah, one more thing, if I copy the public folder from the problem repo in to this minimal repro and run `serve` it also works as expected.

I guess there is some dependency conflict between with the Gatsby server.

**Comment by tyhopp** [comment] 2022-02-21 03:13
Hi @ChrisSargent, thanks for creating the reproduction. What version of gatsby are you using in your monorepo? From the points you mentioned this is what came to mind:

- TypeScript support in `gatsby-config` is in progress (can check out [the rfc](https://github.com/gatsbyjs/gatsby/discussions/34613) for more info on this)
- Fixes for config export issues were released in [gatsby@4.7.0](https://www.gatsbyjs.com/docs/reference/release-notes/v4.7/#notable-bugfixes--improvements) that should resolve the `export const config` issue you mentioned

Hopefully this is useful context! If you're not on 4.7 I'd try that and see if it changes the behavior you're seeing.

**Comment by ChrisSargent** [comment] 2022-02-21 12:19
We're on 4.7.2 in the Mono repo. For sure I understand on the Typescript `gatsby-config` part and wouldn't expect that to be supported to be fair - we kinda need it because we're importing some files that need to be compiled though we are working on a new repo structure which will enable those files to be built first which means we can switch to a javascript config file.

We only get this issue with the named export when we try to use the typescript import so if we assume you don't support the typescript config then I guess everything is working as expected.

**Comment by ChrisSargent** [comment] 2022-02-21 12:21
sorry, I just realised the reproduction wasn't using the latest Gatsby. I'll update and see if it correctly reproduces now....

**Comment by tyhopp** [comment] 2022-02-22 06:45
Thanks for update! Since changing to `gatsby-config.js` fixes the issue and we can't reproduce it minimally, I'll close this.

**Closed by tyhopp** 2022-02-22 06:45 UTC
Labels: type: bug, status: awaiting author response
