### ISSUE TITLE
Still having ERROR #11321

### ISSUE THREAD

**Issue by reinisg** [gatsbyjs/gatsby#19994] opened 2019-12-07 19:38 UTC
## Description

Hello, I have similar to an issue which is closed https://github.com/gatsbyjs/gatsby/issues/17051
But I think it's a bit different. So, I setup wordpress local environment run `gatsby new wp-gatsby`, then install gatsby-source-graphql plugin package, setup gatsby-config file and the run gatsby develop. While all are building, console throws:

```
ERROR #11321  PLUGIN
"gatsby-source-graphql" threw an error while running the sourceNodes lifecycle:
Unexpected token < in JSON at position 0
ServerParseError: Unexpected token < in JSON at position 0
This error shows after:
success createSchemaCustomization - 0.006s
```

### Steps to reproduce

1. Setup default WP environment
2. run `gatsby new wp-gatsby`
3. install gatsby-source-graphql plugin
4. config gatsby-config.js adding
```
{
  resolve: `gatsby-source-graphql`,
  options: {
    typeName: `WPGraphql`,
    fieldName: `wpgraphql`,
    url: `http://wp-gatsby.test/graphql`,
  },
},
```

### Expected result

When the `gatsby develop` command is finished, then open localhost:8000/___graphql you can access to wpgraphql

### Actual result

After `gatsby develop` command is finished, in console has that error, but I can open localhost and access to ___graphql, but there is no wpgraphql field.
Is there any solution for this?

### Environment

```
 System:
    OS: Windows 10 10.0.17763
    CPU: (4) x64 Intel(R) Core(TM) i3-2105 CPU @ 3.10GHz
  Binaries:
    Node: 10.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.16.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15 - /c/Python27/python
  Browsers:
    Edge: 44.17763.831.0
  npmPackages:
    gatsby: ^2.18.4 => 2.18.4
    gatsby-image: ^2.2.34 => 2.2.34
    gatsby-plugin-manifest: ^2.2.30 => 2.2.30
    gatsby-plugin-offline: ^3.0.24 => 3.0.24
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.16
    gatsby-plugin-sharp: ^2.3.4 => 2.3.4
    gatsby-source-filesystem: ^2.1.39 => 2.1.39
    gatsby-source-graphql: ^2.1.25 => 2.1.25
    gatsby-transformer-sharp: ^2.3.6 => 2.3.6
```

Also on other WINDOWS PC not working..

```
  System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
  Binaries:
    Node: 10.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.15
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.18.4 => 2.18.4
    gatsby-image: ^2.2.34 => 2.2.34
    gatsby-plugin-manifest: ^2.2.30 => 2.2.30
    gatsby-plugin-offline: ^3.0.24 => 3.0.24
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.16
    gatsby-plugin-sharp: ^2.3.4 => 2.3.4
    gatsby-source-filesystem: ^2.1.39 => 2.1.39
    gatsby-source-graphql: ^2.1.25 => 2.1.25
    gatsby-transformer-sharp: ^2.3.6 => 2.3.6
```

Regards, Reinis.

**Comment by reinisg** [comment] 2019-12-09 11:50
After `gatsby new wp-gatsby` command, I entered folder and tried `yarn add gatsby-source-graphql`. Below is screenshot from console when plugin was installing, maybe here is an issue?
![alt text](https://i.ibb.co/mBvYrcd/gatsby.png "Gatsby issue")

**Comment by LekoArts** [comment] 2019-12-16 10:48
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by reinisg** [comment] 2019-12-16 11:15
Actually, there was a problem with gatsby-source-graphql version, I updated to 2.1.28, which resolve an issue. [#20015](https://github.com/gatsbyjs/gatsby/issues/20015)

**Comment by LekoArts** [comment] 2019-12-16 11:17
Great! Closing then :)

**Closed by LekoArts** 2019-12-16 11:17 UTC
Labels: status: needs reproduction, topic: WordPress
