### ISSUE TITLE
Importing font-awesome npm package gives error

### ISSUE THREAD

**Issue by deepakjois** [gatsbyjs/gatsby#3524] opened 2018-01-15 07:11 UTC
## Description
I am trying to import some CSS from the `font-awesome`. When I use the well-known Webpack syntax `@import '~font-awesome/css/font-awesome.min.css'`, I get this error w/ `gatsby develop`:

```
src/pages/index.css
1:1     ⚠  Failed to find '~font-awesome/css/font-awesome.min.css'
    in [
        /home/deepak/code/website/gatsby-site/src/pages
    ] [postcss-import]

 WARNING  Compiled with 1 warnings                                  12:36:17 PM

 warning  in ./src/pages/index.css

postcss-import: /home/deepak/code/website/gatsby-site/src/pages/index.css:1:1: Failed to find '~font-awesome/css/font-awesome.min.css'
    in [
        /home/deepak/code/website/gatsby-site/src/pages
    ]
```

When I remove the tilde and use `@import 'font-awesome/css/font-awesome.min.css'`, I get an error with loading the fonts (which are specified using a relative path inside the font-awesome CSS).

```
info bootstrap finished - 1.444 s


src/pages/index.css
undefined [undefined]
undefined [undefined]

 ERROR  Failed to compile with 6 errors                                                                                                             12:12:08 PM

These relative modules were not found:

* ../fonts/fontawesome-webfont.eot?v=4.7.0 in ./~/css-loader!./~/postcss-loader!./src/pages/index.css
* ../fonts/fontawesome-webfont.eot in ./~/css-loader!./~/postcss-loader!./src/pages/index.css
* ../fonts/fontawesome-webfont.woff2?v=4.7.0 in ./~/css-loader!./~/postcss-loader!./src/pages/index.css
* ../fonts/fontawesome-webfont.woff?v=4.7.0 in ./~/css-loader!./~/postcss-loader!./src/pages/index.css
* ../fonts/fontawesome-webfont.ttf?v=4.7.0 in ./~/css-loader!./~/postcss-loader!./src/pages/index.css
* ../fonts/fontawesome-webfont.svg?v=4.7.0 in ./~/css-loader!./~/postcss-loader!./src/pages/index.css
```

### Environment

Gatsby version: 1.1.28 (CLI), 1.9.153 (gatsby)
Node.js version: 9.4.0
Operating System: Linux

**Comment by deepakjois** [comment] 2018-01-15 08:45
I did some more digging. It appears that 

```css
@import '~font-awesome/css/font-awesome.min.css'
```

Works fine with `gatsby build`, but not as I reported above with `gatsby develop`

**Comment by deepakjois** [comment] 2018-01-18 12:20
After further investigation, I noticed that the [using-remark sample has this][using-remark] in the layouts file:

[using-remark]: https://github.com/gatsbyjs/gatsby/blob/a38f49efcfdb79b86e0b646e3bd512a61d46e5f4/examples/using-remark/src/layouts/index.js#L10

```js
 require(`prismjs/themes/prism-solarizedlight.css`)
```

So, I did a 

```js
require(`font-awesome/css/font-awesome.css`)
```

And I was able to get it working without any errors.

It would be nice if somebody who wrote the using-remark code (@fk?) could tell me why they use `require`, instead of `import` and whether this should be considered a bug that might be fixed later.

**Comment by fk** [comment] 2018-01-18 14:52
Hi @deepakjois! Back when I added the https://using-remark.gatsbyjs.org/ example, I think I just copy-pasted the `require` bit to import the prismjs theme (but I can't reproduce from where any more :-() – it wasn't a concious decision.

Disclaimer: I'm not super familiar with Webpack in general, and even more so with how its working within Gatsby (yet!), but let me take a look and see what I can figure out…

So, replacing the [`require` in the using-remark sample's `src/layouts/index.js`](https://github.com/gatsbyjs/gatsby/blob/a38f49efcfdb79b86e0b646e3bd512a61d46e5f4/examples/using-remark/src/layouts/index.js#L10) with `import` works fine in both `gatsby develop` and `gatsby build`:

```js
// require(`prismjs/themes/prism-solarizedlight.css`)
import "prismjs/themes/prism-solarizedlight.css"
// require(`font-awesome/css/font-awesome.css`)
import "font-awesome/css/font-awesome.min.css"
```

@KyleAMathews I guess I should update `using-remark` to use `import` instead of the old `require` syntax?

So much for importing from JavaScript, but I guess your initial issue was importing from within CSS? The error you posted says `warning  in ./src/pages/index.css`, and I think the `@import `~…` syntax is to be used in CSS?

**Comment by deepakjois** [comment] 2018-01-18 15:51
Thanks for your response. 

Yes you are right. My initial issue was importing from within CSS (there are so many different ways to do it, which adds to the confusion). I can confirm that replacing `require` w/ `import` in the JS works. So I could use that for now.

It might still be worth investigating why `@import '~font-awesome/css/font-awesome.min.css'` in CSS does not work. I can confirm that it works in [my CRA app here](https://github.com/deepakjois/deepakjois.name/blob/c6f595fe56254567c44512706cbbdb4768048047/src/index.css). Maybe there is something in the gatsby webpack config that can be tweaked.

**Comment by KyleAMathews** [comment] 2018-09-08 04:08
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Closed by KyleAMathews** 2018-09-08 04:08 UTC
Labels: type: question or discussion

**Comment by hamzaabidabid** [comment] 2024-07-16 22:19
@import "font-awesome/css/font-awesome.min.css";     instead to     @import  "~font-awesome/css/font-awesome.min.css";
