### ISSUE TITLE
Link in viewport prefetch  do not work

### ISSUE THREAD

**Issue by bjatwork** [gatsbyjs/gatsby#19396] opened 2019-11-10 10:54 UTC
I see the same issue as in https://github.com/gatsbyjs/gatsby/issues/18961

Steps to reproduce 
1. open https://gatsby-starter-default-demo.netlify.com/
2. switch to mobile view,
3. use parset "3G slow" 
4. Click "go to page 2" 
5. I see delay . 

Delay not occure on desktop mode (prefetch is after link hover).

**Comment by LekoArts** [comment] 2019-11-11 11:06
Duplicate of #18961

**Closed by LekoArts** 2019-11-11 11:06 UTC
