### ISSUE TITLE
Data attribute hydration is broken

### ISSUE THREAD

**Issue by Francesco-Lanciana** [gatsbyjs/gatsby#14175] opened 2019-05-20 10:02 UTC
## Description
A data attributes value can differ between **develop** and **build**.

I have some data attributes on DOM elements whose value depends on the size of the window. If less than a certain size the attribute will be set to ```true``` otherwise it will be set to ```false```. It is also set to ```false``` if the window object does not exist. 

When developing locally using ```gatsby develop``` it behaves perfectly, changing value as I change the window size and also being the correct value on a full page refresh. However when I build the site and serve it the value is always set to ```false``` initially, even if the page is below the threshold. However if you place a breakpoint in the component the value of the variable is set to ```true```, it just isn't reflected in the data attribute. What's stranger is that if I have conditional rendering logic, e.g.
```
        <div data-attribute={attributeValue}>
            The attribute value is: {attributeValue ? "true" : "false"}
        </div>
```
The text will behave correctly, showing that the value is true if the page is loaded on a small screen. I have tried using **useEffect** and setting the value to true, however this does nothing as the value was already true. I can resize the page or move to a new page and it will correct itself, however I can't seem to get React to recognise the difference on initial page load.

### Steps to reproduce
I have made a repo with a simplified example, the value is just based on whether the window object exists, not on the size of the window.

Pull down the following repo: [Gatsby Hydration Issue](https://github.com/Francesco-Lanciana/gatsby-hydration-issue)
In it I have created a component that will check if the window variable exists (proxy for if we are executed in the browser or not). If it exists we set a data-attribute to true and the text shown will be green. If it doesn't it will be false and the text shown will be red. 

Run ```npm run develop```
You should see that the text is green, the value displayed is true and the data attribute on that element is true. Now run:

```npm run build``` and ```npm run serve```
You should see that the text is red, the value displayed is true and the data attribute on that element is false. 

### Expected result

If I run: ```npm run build``` and ```npm run serve```
I should see that the text is green, the value displayed is true and the data attribute on that element is false. 

## Relevant Information
I created the repo using ```gatsby new``` and the only changes I made were to the components, none of the config files were hurt in the making of this repo.

### Environment

```
  System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
  Languages:
    Python: 2.7.13 - /usr/local/opt/python/libexec/bin/python
  Browsers:
    Chrome: 74.0.3729.157
    Firefox: 66.0.3
    Safari: 12.1.1
  npmPackages:
    gatsby: ^2.5.5 => 2.5.5 
    gatsby-image: ^2.1.0 => 2.1.0 
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1 
    gatsby-plugin-offline: ^2.1.1 => 2.1.1 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sharp: ^2.0.37 => 2.0.37 
    gatsby-source-filesystem: ^2.0.36 => 2.0.36 
    gatsby-transformer-sharp: ^2.1.19 => 2.1.19 
  npmGlobalPackages:
    gatsby-cli: 2.5.15
```

## Closing notes
I'm pretty stumped why this behaviour differs between develop and build (I would have thought that they both server render the pages before the content is rendered so they should both have the same problem). Let me know if you need any more information, I would love to get this sorted ASAP and am more than happy to help create a PR for the fix (if it is indeed a bug).

**Comment by wardpeet** [comment] 2019-05-20 10:52
Let me look into this issue. One thing I can already say is that develop does not do any Server side rendering. That's probably the real issue but let me see if I can give you better insights.

**Comment by Francesco-Lanciana** [comment] 2019-05-22 11:41
Interesting, keen to hear what you dig up, it still feels like very odd server side rendering/hydration behaviour

**Comment by wardpeet** [comment] 2019-05-22 13:58
```
import React, { useState } from "react"

import "./index.css";

const IndexPage = () => {
    const [attributeValue, setAttributeValue] = useState(false)

    useEffect(() => {
        setAttributeValue(true)
    }, []);

    return (
        <div data-attribute={attributeValue}>
            The attribute value is: {attributeValue ? "true" : "false"}
        </div>
    )
}

export default IndexPage
```

is how you should do it

**Comment by DSchau** [comment] 2019-05-23 18:53
As @wardpeet has provided an example (presuming that works like you'd expect!) we're going to close this out.

Please reply or re-open if we can help further. Thanks!

**Closed by DSchau** 2019-05-23 18:53 UTC
Labels: type: question or discussion

**Comment by Francesco-Lanciana** [comment] 2019-05-25 03:04
Thanks for finding a way to make it work @wardpeet however I don't understand why the example I provided wouldn't work. Why does useEffect work where just performing some logic in the component doesn't? 

I'm having trouble with a site I've been building (https://pockets.fashion) where the top navigation bar at small widths will have the cart right against the logo. This is because an attribute is not being set correctly that should in turn update the styling. I've updated the example I provided to replicate this issue more precisely, by using a hook called useMedia. The idea behind this hook is that you can give it media queries and if media query matches then the value should change to what you provided, e.g.
```
const [attributeValue, setAttributeValue] = useMedia("(max-width: 800px)", true, false);
```
This would set the value to **true** if the window width is less than 800px or **false** if it is greater, it will also set it to **false** if window doesn't exist. If you run ```npm run build``` and ```npm run serve``` you will see the same issue I described initially. I would really appreciate any help you could provide, I just can't seem to figure it out.

**Comment by wardpeet** [comment] 2019-05-25 09:15
unsure how the useMedia hook works but the problem is that while building gatsby, there is no way to get the screenResolution so it will fell into the default bucket. In the browser it can do the correct media check and needs to rewrite the HTML because of it. TBH you should try to use css media queries instead of js media queries.

I don't really know a good article that explains "React Rehydration" which is the problem you're struggling with.

**Comment by Francesco-Lanciana** [comment] 2019-05-27 09:29
Yeah I really need to dig into React hydration, the behaviour still seems off to me. I completely understand that while building on the server Gatsby could not possibly know the screen width, however when the app is loaded on the browser the components themselves are still executed. During this initial execution the window object and the screen width are available, which is why I'm confused as to the behaviour. The example you provided me just waited until the component had been mounted and then set the attribute but I don't understand why that is necessary, it's really counter intuitive that it is (and seems incorrect).

**Comment by wardpeet** [comment] 2019-05-28 08:09
Sadly that's how React works, you could go for a full client side app so you don't have this issue.

https://www.gatsbyjs.org/docs/building-apps-with-gatsby/#client-only-routes--user-authentication

There are other hacky solutions to put the values in a global variable before react loads but I'm not a fan of that.
