### ISSUE TITLE
`app-data.json` and `page-data.json` xhr requests are resetting components in development mode

### ISSUE THREAD

**Issue by dungle-scrubs** [gatsbyjs/gatsby#29641] opened 2021-02-21 09:15 UTC
## Description

Note:  This is in development mode only.

I am using Gatsby with Material UI and, inside the `<header>`, I have a `<Drawer>` element displaying a menu.  That menu is a loop of links, and when the drawer is toggled open / mounted the `<header>` re-renders and `<Drawer>` disappears. This only happens if the loop of links contains:

```
{element.type !== 'external' && (
    <GatsbyLink
        className={classes.navItem}
        to={`/${element.type}/${element.handle}`}
        key={element.id}
    >
        {element.name}
    </GatsbyLink>
)}
```

At which point it initiates xhr requests for `app-data.json` and `page-data.json` which when complete, re-render the components. This happens for two or three attempts of opening the `<Drawer>` and eventually stops happening. 

I can try to set up a minimal reproduction but though I'd check to see if I'm missing something conceptual first.

### Expected result

I'm not sure, as I don't fully understand how `app-data.json` and `page-data.json` are suppose to work.  However, I can say that this doesn't happen when I `build` and `serve`.

Thanks in advance!

**Comment by LekoArts** [comment] 2021-02-22 13:55
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-03-08 14:41
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-03-08 14:41 UTC
Labels: status: needs reproduction, type: bug
