### ISSUE TITLE
Error: The result of this StaticQuery could not be fetched.

### ISSUE THREAD

**Issue by hilaring** [gatsbyjs/gatsby#27864] opened 2020-11-05 20:01 UTC
## Description

**Error**: The result of this StaticQuery could not be fetched.
This is likely a bug in Gatsby and if refreshing the page does not fix it

.cache/gatsby-browser-entry.js throws an Error at line 77.

**Comment by LekoArts** [comment] 2020-11-06 08:16
Hi!

Please follow our issue template, the questions and prompts exist to speed up the process (for both parties).

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2020-11-16 07:01
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-11-16 07:01 UTC
Labels: status: needs reproduction, type: bug
