### ISSUE TITLE
In production builds, elements sometimes have CSS classes they should not

### ISSUE THREAD

**Issue by anchpop** [gatsbyjs/gatsby#29418] opened 2021-02-09 19:42 UTC
## Description

In production builds, elements sometimes have CSS classes they should not.

### Steps to reproduce

See this github repo for a minimal reproduction. https://github.com/anchpop/gatsby_wrong_classes

The short version: Create a Gatsby project and add this as a page (I used `index.tsx`)

```jsx
import * as React from "react"

const Test = () => {
  return (
    <>
      <p>
        test
        <div className="extract">ok, this should have extract in it</div>
      </p>
    

      <div>
        <p>test to see if extract shows up in here</p>
      </div>
    </>
  )
}

export default Test
```

Then run `gatsby build`. The server-rendered HTML generated is correct, but when viewed in the browser it won't work as expected. Run `gatsby serve` to view it in chrome.

### Expected result

Gatsby renders the javascript at build time and outputs this (correct) HTML:

```html
<div style="outline:none" tabindex="-1" id="gatsby-focus-wrapper"> 
  <p>test
    <div class="extract">ok, this should have extract in it</div>
  </p>
  <div>
    <p>test to see if extract shows up in here</p>
  </div>
</div>
 ```

Since the site is completely static, it should not appreciably change when viewed in Chrome or other browsers.

### Actual result

When viewed in the browser with `gatsby serve`, javascript runs and modifies the DOM in an incorrect way. The last `div` element gets the `extract` CSS class even though it shouldn't have it. 

```html
<div style="outline:none" tabindex="-1" id="gatsby-focus-wrapper">
  <p>test
    <div class="extract">ok, this should have extract in it</div>
  </p>
  <div class="extract"> <!-- Shouldn't have the "extract" class!  -->
    <p>test to see if extract shows up in here</p>
  </div>
</div>
 ```

This only happens during production builds, not during `gatsby develop`. 

(It's definitely a javascript issue - disable javascript and the issue goes away.)

### Environment

The issue also happens on Netlify's build servers, but here's my local environment:

```
  System:
    OS: macOS 11.0
    CPU: (8) arm64 Apple processor
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.4.0 - /opt/homebrew/bin/node
    Yarn: 1.22.10 - /opt/homebrew/bin/yarn
    npm: 7.0.15 - /opt/homebrew/bin/npm
  Languages:
    Python: 3.9.1+ - /Users/andrepopovitch/.pyenv/shims/python
  Browsers:
    Chrome: 88.0.4324.150
    Safari: 14.0.1
  npmPackages:
    gatsby: ^2.32.3 => 2.32.3
    gatsby-plugin-netlify-cms: ^4.10.0 => 4.10.0
  npmGlobalPackages:
    gatsby-cli: 2.16.1
```

**Comment by ascorbic** [comment] 2021-02-11 10:45
Hi. Thanks for the great reproduction. This is a React hydration issue, and is caused by the fact that the HTML is technically invalid. The issue is that you have a `<div>` inside a `<p>` tag, [which is not legal](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/p), but React allows it. However, when rendering the static HTML, the browser corrects this. If you disable JS and look at the DOM, you'll find this: 

```html
<div style="outline:none" tabindex="-1" id="gatsby-focus-wrapper">
<p>test</p>
<div class="extract">ok, this should have extract in it</div>
<p></p>
<div><p>test to see if extract shows up in here</p></div>
</div>
```

Note the different structure, where it's moved the `<div>` elements outside of the `<p>`. The problem is that when React hydrates, the DOM no longer matches the expected structure. This means that React gets confused and applies the classname to the wrong elements.

Changing the wrapping element from a p to a div to this fixes it:

```jsx
import * as React from "react";

const Test = () => {
  return (
    <>
      <div>
        test
        <div className="extract">ok, this should have extract in it</div>
      </div>

      <div>
        <p>test to see if extract shows up in here</p>
      </div>
    </>
  );
};

export default Test;
```

I'm going to close this, but if this doesn't fix it please reply and tag me. Thanks!

**Closed by ascorbic** 2021-02-11 10:45 UTC
Labels: status: triage needed, type: bug

**Comment by anchpop** [comment] 2021-02-11 18:19
Thank you, this resolved it! I had no idea about HTML tag omission rules.
