### ISSUE TITLE
Receiving an unhandled runtime error when using useStaticQuery

### ISSUE THREAD

**Issue by fredrikjohanssonnn** [gatsbyjs/gatsby#30816] opened 2021-04-11 13:48 UTC
## Description

I am trying to fetch data with graphql through the useStaticQuery-hook. However, I am receiving an error telling me the data can't be fetched. I have tried to delete the `node_modules` and the `cache` folder.

### Steps to reproduce

The error happens within this component I think. It is supposed to show a hero image. https://github.com/fredrikjohanssonnn/Coffeeroasters/blob/main/src/components/Hero.js

Otherwise if you clone the project and run `gatsby develop`. You'll see the error when opening the localhost server. Here's an image of the error:

<img width="682" alt="runtime error" src="https://user-images.githubusercontent.com/42123219/114306791-4621c400-9add-11eb-8314-def0ff10e5c4.PNG">

### Expected result

Well the error shouldn't appear. Can't tell if there's any errors in the code. But it works in the GraphiQL interface. The hook should fetch data from a local .json file and display it within the component.

### Actual result

The error abow appears

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

 ```
 System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  Binaries:
    Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.1 - /c/Users/Jzon/AppData/Local/Programs/Python/Python39/python
  Browsers:
    Chrome: 89.0.4389.114
    Edge: Spartan (44.19041.423.0), Chromium (89.0.774.75)
  npmPackages:
    gatsby: ^3.2.1 => 3.2.1
    gatsby-background-image: ^1.5.0 => 1.5.0
    gatsby-plugin-image: ^1.2.1 => 1.2.1
    gatsby-plugin-sass: ^4.2.0 => 4.2.0
    gatsby-plugin-sharp: ^3.2.1 => 3.2.1
    gatsby-source-filesystem: ^3.2.0 => 3.2.0
    gatsby-transformer-json: ^3.2.0 => 3.2.0
    gatsby-transformer-sharp: ^3.2.0 => 3.2.0
  npmGlobalPackages:
    gatsby-cli: 3.2.0
```

**Comment by LekoArts** [comment] 2021-04-19 09:03
Hi, thanks for the issue!

I cloned your repository, ran `yarn install` and `yarn develop` and I don't get any errors. Do you still see the issue? If yes, how can I reproduce this?

**Comment by LekoArts** [comment] 2021-04-26 08:42
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-04-26 08:42 UTC
Labels: status: needs reproduction, type: bug
