### ISSUE TITLE
Custom Build Folder

### ISSUE THREAD

**Issue by ashinzekene** [gatsbyjs/gatsby#7244] opened 2018-08-11 09:49 UTC
## Summary
It would be awesome to be able to set a custom deploy folder. One very good use is we don't need gh-pages to deploy on GitHub pages 

### Basic example
It could possibly be in `gatsby.config.js` file

```js
module.exports = {
  buildFolder: 'https://gatsbyjs.github.io/gatsby-starter-blog/',
},
```

### Motivation
One very good use is we don't need gh-pages to deploy on GitHub pages, which can be automatically deployed in the `docs` folder

**Comment by LeKoArts** [comment] 2018-08-11 10:43
Duplicate of https://github.com/gatsbyjs/gatsby/issues/1878

**Closed by LeKoArts** 2018-08-11 10:43 UTC
