### ISSUE TITLE
Plugins Page - Plugins list not scrolling after plugin details container is scrolled.

### ISSUE THREAD

**Issue by prvnbist** [gatsbyjs/gatsby#14151] opened 2019-05-19 10:12 UTC
## Description
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/17105682/57980665-d53a1480-7a4b-11e9-92ea-95b5e7245ebd.gif)

On plugins page, the webpage has two scrollable containers one for list of plugins and another for plugin details. When the plugin details container is scrolled and then if you try to scroll the plugin list container it won't scroll unless you select a plugin.

Browser with this issue
Google Chrome - Version 74.0.3729.157

Browsers where it's working as expected
Mozilla Firefox
MS Edge

### Steps to reproduce
Issue in Google Chrome - Version 74.0.3729.157

### Expected result

Both containers should independently scroll based on whichever's focused.

### Actual result

After scrolling the plugin details container, the plugin list container can not be scrolled unless a plugin is selected or the page is refreshed.

### Environment

Google Chrome - Version 74.0.3729.157

**Comment by wardpeet** [comment] 2019-05-20 09:22
Thanks for reporting, I wonder if this is a browser bug or something we can actually fix.

**Comment by Jared-Dev** [comment] 2019-05-20 15:59
I tested in FF and Edge and the issue is specific to Chrome. I'm guessing it is actually something that should be reported to their team.

**Comment by Jared-Dev** [comment] 2019-05-20 16:01
Also, I did a quick conversion to `grid` to eliminate any possible overflow bugs that the `contents` `padding` might have been causing and the issue persisted.

**Comment by Jared-Dev** [comment] 2019-05-28 15:22
I have added a bug to the Chromium repo if anyone wants to add context (https://bugs.chromium.org/p/chromium/issues/detail?id=967697).

**Comment by Jared-Dev** [comment] 2019-05-30 19:25
@wardpeet I think the tags on this could safely be removed. I'm not sure how you would normally handle this in terms of leaving it open as a reminder to check in vs closing now and re-opening if the mentioned version doesn't resolve the issue, but...

[The discussion](https://bugs.chromium.org/p/chromium/issues/detail?id=967697#c6) on the Chromium project leads me to believe they had a bug, but it is set to be released in one of the v75.x versions.

**Comment by wardpeet** [comment] 2019-06-03 10:12
Seems to be fixed in chrome canary and beta versions so this will be fixed next stable. Thanks @Jared-Dev to open this in chromium bug reporter! ❤️ 

I'll be closing.

**Closed by wardpeet** 2019-06-03 10:12 UTC
Labels: type: bug, type: upstream
