### ISSUE TITLE
Building many pages exhausts memory

### ISSUE THREAD

**Issue by tfausak** [gatsbyjs/gatsby#6349] opened 2018-07-09 18:35 UTC
## Description

Gatsby is running out of memory when building a site with many (2,500+) pages.

### Steps to reproduce

Given the files below, run:

``` sh
$ env GATSBY_PAGE_COUNT=2600 npm run build
```

The exact number (2600) required to trigger the failure fluctuates. It's usually around 2556 or so. Using 2500 always succeeds for me, and 2600 always fails. 

### Expected result

The site should be built. 

### Actual result

The site fails to build because Node runs out of memory.

```
$ env GATSBY_PAGE_COUNT=2600 time npm run build 

> @ build /.../example
> rm -f -r .cache public public.tar public.tar.gz && gatsby build && tar -c -f public.tar public && gzip -f -k public.tar

success delete html and css files from previous builds — 0.008 s
success open and validate gatsby-config — 0.004 s
success copy gatsby files — 0.015 s
⠁ Generating 2600 pages ...
success onPreBootstrap — 0.012 s
success source and transform nodes — 0.011 s
success building schema — 0.058 s
success createLayouts — 0.005 s
success createPages — 4.298 s
success createPagesStatefully — 0.205 s
success onPreExtractQueries — 0.000 s
success update schema — 0.112 s
success extract queries from components — 0.010 s
success run graphql queries — 0.703 s
success write out page data — 0.033 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.000 s

info bootstrap finished - 6.568 s

success Building CSS — 2.919 s
success Building production JavaScript bundles — 26.349 s
⢀ Building static HTML for pages
<--- Last few GCs --->

[23516:0x104002400]    49209 ms: Mark-sweep 951.3 (1453.8) -> 951.3 (1437.8) MB, 122.6 / 0.0 ms  (average mu = 0.006, current mu = 0.000) last resort GC in old space requested
[23516:0x104002400]    49341 ms: Mark-sweep 951.3 (1437.8) -> 951.3 (1437.8) MB, 131.5 / 0.0 ms  (average mu = 0.003, current mu = 0.001) last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x33656ef841bd]
Security context: 0x16c4e671e6c9 <JSObject>
    1: DoJoin(aka DoJoin) [0x16c47a34cf41] [native array.js:~87] [pc=0x33656f9fa0a2](this=0x16c4769822e1 <undefined>,l=0x16c4bb354d91 <JSArray[2]>,m=2,A=0x16c476982381 <true>,w=0x16c476982441 <String[0]: >,v=0x16c4769823f1 <false>)
    2: Join(aka Join) [0x16c47a34cf91] [native array.js:~112] [pc=0x33656f9b5534](this=0x16c4769822e1 <undefined>,l=0x16c4bb354d...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0x100033aa9 node::Abort() [/usr/local/bin/node]
 2: 0x100035236 node::FatalTryCatch::~FatalTryCatch() [/usr/local/bin/node]
 3: 0x10017a8fb v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 4: 0x10017a89d v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]
 5: 0x1004532f2 v8::internal::Heap::UpdateSurvivalStatistics(int) [/usr/local/bin/node]
 6: 0x100459823 v8::internal::Heap::AllocateRawWithRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]
 7: 0x100439204 v8::internal::Factory::NewRawTwoByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
 8: 0x100671682 v8::internal::Runtime_StringBuilderConcat(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 9: 0x33656ef841bd 
sh: line 1: 23516 Abort trap: 6           gatsby build
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! @ build: `rm -f -r .cache public public.tar public.tar.gz && gatsby build && tar -c -f public.tar public && gzip -f -k public.tar`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.../.npm/_logs/2018-07-09T18_22_01_979Z-debug.log
       51.12 real        60.16 user         6.52 sys
```

### Environment

```
  System:
    OS: macOS High Sierra 10.13.5
    CPU: x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.6.0 - /usr/local/bin/node
    npm: 6.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 67.0.3396.99
    Firefox: 59.0.2
    Safari: 11.1.1
  npmPackages:
    gatsby: 1.9.273 => 1.9.273 
    gatsby-cli: 1.1.58 => 1.1.58 
```

### File contents

`package.json`:
``` json
{
  "dependencies": {
    "gatsby": "1.9.273",
    "gatsby-cli": "1.1.58"
  },
  "scripts": {
    "build": "rm -f -r .cache public public.tar public.tar.gz && gatsby build && tar -c -f public.tar public && gzip -f -k public.tar"
  }
}
```

`gatsby-node.js`: 
``` js
const path = require('path');
const count = process.env.GATSBY_PAGE_COUNT || 2600;
console.log(`Generating ${count} page${count === 1 ? '' : 's'} ...`);
exports.createPages = (gatsby) => {
  const component = path.resolve('template.js');
  for (let number = 1; number <= count; number += 1) {
    gatsby.boundActionCreators.createPage({
      component,
      path: `/numbers/${number}`,
      context: { number },
    });
  }
};
```

`template.js`:
``` js
import React from 'react';
export default class NumberPage extends React.Component {
  render() {
    return (
      <p> This is the number page for { this.props.pathContext.number }. </p>
    );
  }
}
```

**Comment by KyleAMathews** [comment] 2018-07-09 18:47
This is a weakness in v1 which we've fixed in v2. See this PR https://github.com/gatsbyjs/gatsby/pull/4912 for details. @pieh found that `static-site-generator-webpack-plugin` tries to run all HTML builds at once which causes memory usage to spike. I've successfully built 100k pages in this PR https://github.com/gatsbyjs/gatsby/pull/6226 w/o any memory problems.

If you can, we recommend upgrading to v2 https://next.gatsbyjs.org/docs/migrating-from-v1-to-v2/

**Closed by KyleAMathews** 2018-07-09 18:47 UTC

**Comment by tfausak** [comment] 2018-07-09 19:31
Thanks for the quick response! I can confirm that Gatsby `2.0.0-beta.19` is able to build this example without running out of memory. With any luck I will be able to upgrade the real site that was exhibiting this problem to Gatsby v2 🙂

**Comment by KyleAMathews** [comment] 2018-07-09 19:38
Great to hear! Please file any issues you find while upgrading to v2! We're working with beta testers to get this ready for GA release.

**Comment by DSchau** [comment] 2018-10-01 14:10
@amykapernick we're working on this. I can't actually get your site to _build_ however. First I errored out with `Cannot find json5` and now 

```bash
🚨  /Users/dschau/Code/Work/gatsby/test/amy-netlify/src/scss/layouts/article.scss:undefined:undefined: Lexical error on line 1. Unrecognized text.
100vh - $height_header
```

I'm also not quite sure what the build process is for your app. Strange to have Parcel baked in, as well!

**Comment by amykapernick** [comment] 2018-10-01 14:14
Thanks @DSchau, my blog isn't even that big either 😬

**Comment by DSchau** [comment] 2018-10-01 14:14
@amykapernick yeah, it doesn't really seem like you should've hit the OOM error at the scale of your site. Not really sure what's going on, it's possible some optimizations could be made!

**Comment by amykapernick** [comment] 2018-10-01 14:19
@DSchau anything in particular I could try now? Or do I need to wait for changes on your end?

**Comment by DSchau** [comment] 2018-10-01 15:00
@amykapernick it looks like including that (empty) `gatsby-remark-oembed` was causing some issues with the build, perhaps an infinite loop?

I've successfully [deployed your site here](https://dreamy-raman-ca30d1.netlify.com/) and opened a PR against your site with the changes.

**Comment by amykapernick** [comment] 2018-10-01 15:05
Thanks but I'm using `gatsby-remark-oembed` to embed Twitter, Instagram and Codepens in my blog posts from markdown so I need that plugin. I'll have a chat to them and see if they can assist with the issue.

**Comment by DSchau** [comment] 2018-10-01 15:09
@amykapernick ah got it. OK so the issue isn't that you're _using_ the plugin, it's that you have an empty plugins/gatsby-remark-oembed folder.

I'd recommend installing the plugin and then deleting that folder!

**Comment by amykapernick** [comment] 2018-10-01 15:11
@DSchau  I've installed the plugin, I'm using it as a submodule as they're still working on it. I'll have a look and see if I can add it a different way

**Comment by JoseFMP** [comment] 2019-04-09 09:28
Did you got to solve this issue? Over here still happening.   "gatsby": "^2.3.3"
