### ISSUE TITLE
Gatsby source WordPress fails to fetch non-English URLs. 

### ISSUE THREAD

**Issue by adamgen** [gatsbyjs/gatsby#30424] opened 2021-03-23 14:24 UTC
## Description

* Example source URL with URL not encoded - http://me.co.il/אודות
* Example source URL with URL encoded - http://me.co.il/%D7%90%D7%95%D7%93%D7%95%D7%AA

I've had similar issues in the past but it's hard to pinpoint. URLs need to be encoded and decoded, and generally speaking, it's doesn't happen in a strict manner on Gatsby so far... :\

```
warn  gatsby-source-wordpress  Error occurred while fetching media item in step:

"Creating File node from URL where we couldn't find a MediaItem node"

Edit link: http://p3112-113-21108.s113.upress.link/wp-admin/post.php?post=757&action=edit
File url: http://p3112-113-21108.s113.upress.link/wp-content/uploads/2013/04/יעל-150x150.jpg

This error will fail production builds.
⠀

 ERROR 

HTTPError: Response code 404 (Not Found)
    at Request._onResponseBase (/Users/adam/dev/sykoro-super-static-retter/node_modules/gatsby-source-wordpress/node_modules/got/dist/source/core/index.js:899:31)
    at Request._onResponse (/Users/adam/dev/sykoro-super-static-retter/node_modules/gatsby-source-wordpress/node_modules/got/dist/source/core/index.js:934:24)
    at ClientRequest.<anonymous> (/Users/adam/dev/sykoro-super-static-retter/node_modules/gatsby-source-wordpress/node_modules/got/dist/source/core/index.js:948:23)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at ClientRequest.origin.emit (/Users/adam/dev/sykoro-super-static-retter/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
    at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
    at Socket.socketOnData (_http_client.js:509:22)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  code: undefined,
  timings: {
    start: 1616507251210,
    socket: 1616507251210,
    lookup: 1616507251211,
    connect: 1616507251304,
    secureConnect: undefined,
    upload: 1616507251304,
    response: 1616507251462,
    end: 1616507251463,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 0,
      dns: 1,
      tcp: 93,
      tls: undefined,
      request: 0,
      firstByte: 158,
      download: 1,
      total: 253
    }
  }
}

```

### Steps to reproduce

Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

Fetch the URL successfully.

### Actual result

Fails to fetch.

### Environment

```
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 7.5.2 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 85.0.2
    Safari: 14.0.3
  npmPackages:
    gatsby: ^2.28.2 => 2.32.11
    gatsby-awesome-pagination: ^0.3.6 => 0.3.6
    gatsby-plugin-emotion: ^6.1.0 => 6.1.0
    gatsby-plugin-extract-schema: ^0.1.0 => 0.1.0
    gatsby-plugin-intl: ^0.3.3 => 0.3.3
    gatsby-plugin-postcss: ^3.3.0 => 3.7.0
    gatsby-plugin-preact: ^5.1.0 => 5.1.0
    gatsby-plugin-purgecss: ^5.0.0 => 5.0.0
    gatsby-plugin-react-helmet: ^3.1.7 => 3.10.0
    gatsby-plugin-sharp: ^2.2.21 => 2.14.3
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.18 => 1.1.21
    gatsby-source-woocommerce: ^0.2.0 => 0.2.0
    gatsby-source-wordpress: ^5.1.0 => 5.1.0
    gatsby-transformer-sharp: ^2.2.14 => 2.12.1
  npmGlobalPackages:
    gatsby-cli: 3.0.0
```

**Comment by LekoArts** [comment] 2021-03-24 08:39
Hi, thanks for the issue! I think this is a duplicate of https://github.com/gatsbyjs/gatsby/issues/12684 so I'll close this one.

**Closed by LekoArts** 2021-03-24 08:39 UTC
Labels: topic: WordPress, type: bug
