### ISSUE TITLE
gatsby-source-contentful no such file or directory errors when building website

### ISSUE THREAD

**Issue by idosius** [gatsbyjs/gatsby#32362] opened 2021-07-14 10:41 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When running `gatsby develop` or `gatsby build`, the following errors appear in the console for various assets (I've anonymized the data):

```
 ERROR 

[gatsby-source-contentful] Could not getDominantColor from image [Error: ENOENT: no such file or directory, open
'/Users/john/IdeaProjects/project/.cache/contentful/assets/Screenshot 2020-08-12 at 12.32.55-7213587bbfa3103ffbbbe5ac951c2696.png'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/john/IdeaProjects/project/.cache/contentful/assets/Screenshot 2020-08-12 at 12.32.55-7213587bbfa3103ffbbbe5ac951c2696.png'
}
```

I've narrowed it down to the Contentful query which runs in `gatsby-node.js` as part of `createPages`:
```
    query {
      posts: allContentfulBlogPost(sort: { fields: publishedAt, order: DESC }) {
        edges {
          node {
            slug
            content {
              raw
              references {
                ... on ContentfulAsset {
                  # __typename and contentful_id are required to resolve the references
                  __typename
                  contentful_id
                  id
                  title
                  gatsbyImageData(
                    layout: FULL_WIDTH
                    breakpoints: [320, 400, 480, 600, 800, 1200]
                  )
                  file {
                    contentType
                    url
                  }
                  sys {
                    type
                  }
                }
              }
            }
            fields {
              route
            }
          }
        }
      }
    }
```

Notes:
- This issue started happening after upgrading Gatsby + plugins to the latest versions
- The assets that appear in these messages do exist in Contentful, and are not available in the `.cache/contentful/assets` directory
- Other assets do appear in the `.cache/contentful/assets` directory
- Running `gatsby clean` or reinstalling the packages did not solve the issue
- Despite the error messages, the website seems to function and load these assets anyway

### Reproduction Link

https://cant-share-the-code-because-its-private.com

### Steps to Reproduce

Please see description

### Expected Result

No console errors when developing and building the website

### Actual Result

Console errors when developing and building the website

### Environment

```shell
System:
    OS: macOS 11.4
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 91.0.4472.114
    Edge: 91.0.864.67
    Firefox: 89.0.2
    Safari: 14.1.1
  npmPackages:
    gatsby: ^3.9.1 => 3.9.1 
    gatsby-plugin-eslint: ^3.0.0 => 3.0.0 
    gatsby-plugin-google-tagmanager: ^3.9.0 => 3.9.0 
    gatsby-plugin-image: ^1.9.0 => 1.9.0 
    gatsby-plugin-manifest: ^3.9.0 => 3.9.0 
    gatsby-plugin-offline: ^4.9.0 => 4.9.0 
    gatsby-plugin-react-helmet: ^4.9.0 => 4.9.0 
    gatsby-plugin-sharp: ^3.9.0 => 3.9.0 
    gatsby-source-contentful: ^5.9.0 => 5.9.0 
    gatsby-source-filesystem: ^3.9.0 => 3.9.0 
    gatsby-transformer-sharp: ^3.9.0 => 3.9.0 
  npmGlobalPackages:
    gatsby-cli: 3.8.0
```

**Comment by idosius** [comment] 2021-07-14 12:13
Update: even running this simple query produces these errors:
```
query MyQuery {
  allContentfulAsset {
    edges {
      node {
        gatsbyImageData
      }
    }
  }
}
```

**Comment by LekoArts** [comment] 2021-07-19 08:48
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-07-27 08:34
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-07-27 08:34 UTC
Labels: status: needs reproduction, type: bug
