### ISSUE TITLE
Extra attributes from the server: aria-current,class

### ISSUE THREAD

**Issue by iDVB** [gatsbyjs/gatsby#30404] opened 2021-03-23 01:10 UTC
## Description

Using `gatsby@3.1.1` using the core `Link` component  I'm getting the **warning...**
`Extra attributes from the server: aria-current,class` 

...looking at the element I can see it looks like this...
`<a aria-current="page" class href="/">`

...and yet, I'm only passing `to` ....[where are those other attributes coming from](https://codesandbox.io/s/wonderful-morning-b78ip?file=/src/pages/index.js)? (`aria-current` and `class`) I don't see anything in [the gatsby docs](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link) about these being injected in, or how to disable it. Also, why would react complain about it being different between client and server, assuming it should be injected the same on both?

I've even searched [the gatsby src for Link](https://github.com/gatsbyjs/gatsby/blob/gatsby%403.1.0/packages/gatsby-link/src/index.js) and can't see anything that would inject aria attrbs.

### Steps to reproduce
I can't reproduce the React hydrate error, but I am seeing these attributes and no idea how their getting injected in there.
https://codesandbox.io/s/wonderful-morning-b78ip?file=/src/pages/index.js

### Expected result
I would expect that no extra attributes to be added at all. I would expect that IF they are being added, that they would be added at SSR AND Hydration.

### Actual result
`aria-current` and `class` attributes are being added during SSR and not during hydration which is causing a mis-match error.

### Environment
    "react": "^17.0.1",
    "react-dom": "^17.0.1",

System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 84.0
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.1.0 => 3.1.0
    gatsby-cli: ^3.1.0 => 3.1.0
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5
    gatsby-plugin-feed: ^3.1.0 => 3.1.0
    gatsby-plugin-google-gtag: ^3.1.0 => 3.1.0
    gatsby-plugin-image: ^1.1.1 => 1.1.1
    gatsby-plugin-manifest: ^3.1.0 => 3.1.0
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.10
    gatsby-plugin-no-javascript: ^2.0.5 => 2.0.5
    gatsby-plugin-react-helmet: ^4.1.0 => 4.1.0
    gatsby-plugin-remove-trailing-slashes: ^3.1.0 => 3.1.0
    gatsby-plugin-robots-txt: ^1.5.5 => 1.5.5
    gatsby-plugin-sharp: ^3.1.0 => 3.1.0
    gatsby-plugin-sitemap: ^3.1.0 => 3.1.0
    gatsby-plugin-styled-components: ^4.1.0 => 4.1.0
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.21 => 1.1.21
    gatsby-source-filesystem: ^3.1.0 => 3.1.0
    gatsby-transformer-sharp: ^3.1.0 => 3.1.0

**Comment by iDVB** [comment] 2021-03-23 01:20
I [found this](https://github.com/facebook/react/issues/14978) which seems like it could be related in some way. But would only accounts for the `class` tag and not sure where we have control over the loaders in gatbsy. I don't believe we are doing anything outside the box.

**Comment by LekoArts** [comment] 2021-03-24 09:09
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

The `aria-current` comes from our reach-router usage and is expected: https://github.com/gatsbyjs/reach-router/blob/71cf00357c9f7305d4aefa09658512c8fe6f691a/src/index.js#L409
The `class` is expected if you style the `<Link />`. If it's empty you might have a styling mismatch between dev and SSR (so an issue with your code).

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-04-06 10:12
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-04-06 10:12 UTC
Labels: status: needs reproduction, type: bug

**Comment by iDVB** [comment] 2021-04-07 21:40
Turns out this issue was due to [a bug in DEV_SSR](https://github.com/gatsbyjs/gatsby/issues/30750).
It took a whole day of troubleshooting to figure this one out. :)
