### ISSUE TITLE
Gatsby 2.0 RC | Styled components theme crashes prod build

### ISSUE THREAD

**Issue by thibautvs** [gatsbyjs/gatsby#7827] opened 2018-09-03 10:33 UTC
## Description

When using the `<ThemeProvider>`, everything works as expected in development. When building for production, an error occurs.

### Steps to reproduce

Use a `<ThemeProvider>` and in a component, use theme values, such as `${props => props.theme.colors.green}`. See that it works in development when running `gatsby develop` but crashes when running `gatsby build`.

### Expected result

The prod build should complete successfully.

### Actual result

error Building static HTML for pages failed

```
   3 |
   4 | const StyledFontAwesomeIcon = styled(FontAwesomeIcon)`
 > 5 |   color: ${props => props.theme.colors.green};
     |                                        ^
   6 |   margin-right: 15px;
   7 | `
   8 |

```
WebpackError: TypeError: Cannot read property 'green' of undefined

### Environment

  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.4.0 - /usr/local/bin/node
    Yarn: 1.7.0 - /usr/local/bin/yarn
    npm: 6.1.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 61.0.1
    Safari: 11.1.2
  npmPackages:
    gatsby: ^2.0.0-rc.7 => 2.0.0-rc.7 
    gatsby-plugin-react-helmet: ^3.0.0-rc.1 => 3.0.0-rc.1 
    gatsby-plugin-styled-components: ^3.0.0-rc.1 => 3.0.0-rc.1 
  npmGlobalPackages:
    gatsby-cli: 2.0.0-rc.1

**Comment by thibautvs** [comment] 2018-09-18 19:45
Upgrading to Gatsby 2.0.1 and gatsby-plugin-styled-components 3.0.0 fixed the problem!

**Comment by thibautvs** [comment] 2018-09-18 19:50
Just upgraded to Gatsby 2.0.1 and 3.0.0. Still the same issue...

**Comment by DSchau** [comment] 2018-09-18 21:10
@thibautvs I just [created a repo](https://github.com/DSchau/gatsby-7827) demonstrating the usage of styled-components, the gatsby plugin, and ThemeProvider and was unable to reproduce.

[Here's the demo in Netlify showing the built site](https://dazzling-knuth-957de4.netlify.com/)

I'm going to close this one out until you can reproduce! Thanks for your patience!

**Closed by DSchau** 2018-09-18 21:10 UTC
Labels: status: needs more info, status: needs reproduction, type: bug :beetle:

**Comment by thibautvs** [comment] 2018-09-24 10:33
Hello @DSchau,

I could reproduce the problem in this repo: https://github.com/thibautvs/gatsby-theme-crash

Kind regards,

Thibaut

**Comment by EricSSartorius** [comment] 2018-10-09 03:52
@thibautvs Have you found a solution for this yet? I am having the same problem when I migrated to Gatsby 2.0

**Comment by thibautvs** [comment] 2018-10-09 07:52
@EricSSartorius Nope haven't found the problem, though I could isolate it like in the provided repo. It essentially works almost all the time, except for a particular page. Maybe it's related to some 3rd party dependencies, might be worth commenting them out one by one to (in)validate this hypothesis.

**Comment by thibautvs** [comment] 2018-10-09 07:54
@LeKoArts Maybe we can now remove the label "status: needs reproduction"?
@kakadiadarpan Maybe we can now remove the label "status: needs more info"?

Thx!

**Comment by LeKoArts** [comment] 2018-10-09 08:35
your styled components dependency is outdated

**Comment by Vpr99** [comment] 2018-11-03 19:56
@thibautvs I was wondering if you ever figured out what was causing this? I'm having the same issue intermittently.

**Comment by thibautvs** [comment] 2018-11-05 07:20
@Vpr99 I'm still experiencing the same issue

**Comment by Vpr99** [comment] 2018-11-06 17:47
@thibautvs bummer. I managed to make it work by wrapping just that component in its own `ThemeProvider` but that feels super bad.

**Comment by Vpr99** [comment] 2018-11-13 21:53
I ran into this another 5 or 6 times today. Any chance we could reopen @DSchau ? It looks like @thibautvs got a reproducible demo.

**Comment by DSchau** [comment] 2018-11-13 22:08
@thibautvs the main issue that's happening in your example is that `src/pages/index/StyledFontAwesomeIcon.js` is being treated as a page component, and is _not_ being wrapped with the special Layout component. This is leading the component to be rendered during SSR without a ThemeProvider, thus, the error that `theme` is not defined.

I'd recommend that if you have React components that are just that (components!) instead of pages, that you create a `src/components` directory, and place components in that directory. Then those components can be imported into page components like one would expect.

Here's the fix for the reproduction -> https://github.com/thibautvs/gatsby-theme-crash/pull/1

@Vpr99 I can't fix your problem without a reproduction, unless it's a similar one to the one in this case. We've shown that it works with a recommended setup [here](https://github.com/gatsbyjs/gatsby/issues/7827#issuecomment-422556081) so unless you can provide a separate reproduction of your issue, can't help much yet! Please do let us know if we can help further.

**Comment by Vpr99** [comment] 2018-11-13 22:43
@DSchau thanks for the detailed response—I guess I didn't look close enough at Thibaut's repo. My problem is slightly different since I'm using `wrapRootElement` to wrap the entire site in the `ThemeProvider`. It seems to be super intermittent, but I'll try and make a repro here in a few.

Thanks again!

**Comment by thibautvs** [comment] 2018-11-14 08:08
Thanks very much for your explanation and fix @DSchau!

**Comment by Vpr99** [comment] 2018-11-15 02:08
Okay @DSchau I've managed to get a working reproduction of my issue:

https://github.com/Vpr99/gatsby-sc-reproduction

Please take a look when you have a sec—I'm really stumped.

**Comment by LekoArts** [comment] 2018-11-15 08:08
You also have to use the wrapPage thingy in `gatsby-ssr`

**Comment by Vpr99** [comment] 2018-11-15 15:41
@LekoArts you're a legend. Thank you SO much :clap:

**Comment by DSchau** [comment] 2018-11-15 15:44
@Vpr99 you could also just use a [Layout component](https://www.gatsbyjs.org/docs/layout-components/) there as well, correct? Seems weird to have a base template that you use to wrap, when that effectively _is_ a Layout component.

**Comment by Vpr99** [comment] 2018-11-15 16:16
Good q. There were a couple reasons I ended up moving to `wrapRootElement`. First was analytics. I'm using [react-tracking](https://github.com/NYTimes/react-tracking) and I want to fire tracking events when each page mounts. Eg:

```jsx
import track from 'react-tracking';

const Home = () => (
  <main>Home<main>
);

export default track({ page: 'home' })(Home);
```

If I'd imported `BaseLayout` in each page, I would have had to pass that analytics information as props to BaseLayout, since that's where the events are gathered and dispatched:

```jsx
const Home = () => (
  <BaseLayout analyticsPage="home">Home<BaseLayout>
);

export default Home;
```

**Comment by sylvhama** [comment] 2018-12-20 03:49
@DSchau I am new to gatsby and I've looked at your example: https://github.com/DSchau/gatsby-7827
I just wonder why can't we use the gatsby-browser API and its `wrapRootElement` to wrap all the app with ThemeProvider 🤔. In your example the ThemeProvider will unmount and remount at each page change. I thought  `wrapRootElement` was meant to be used with providers.
That's what I am doing here https://github.com/sylvhama/shamann-gatsby but the build fails.

**Comment by sylvhama** [comment] 2018-12-20 16:16
Ok I omited to setup `gatsby-ssr.js` which should contain wrapRootElement as well. The Behind the scenes doc explains why we must do that: https://www.gatsbyjs.org/docs/webpack-and-ssr/

**Comment by dlindahl** [comment] 2019-01-04 05:37
[This addition](https://github.com/gatsbyjs/gatsby/issues/7827#issuecomment-448854236) to `gatsby-ssr.js` should really be documented in the `gatsby-plugin-styled-components` README as it essentially means that the plugin is broken out of the box (`gatsby build` fails if using themes).

**Comment by LekoArts** [comment] 2019-01-04 07:44
The plugin isn’t broken nor not working with themes. There’s something wrong on your end. Can you share a reproduction repo?

**Comment by dlindahl** [comment] 2019-01-08 23:41
Sorry, didn't mean to imply that the plugin itself is broken. It does require an extra step of configuration in order to work that I did not see documented in the plugin. Specifically, the code that needs to be added to `gatsby-ssr.js` that @sylvhama linked to. I think including example code for `gatsby-ssr.js` in the README would be very helpful.

**Comment by kimlianlopez** [comment] 2019-12-18 07:23
I solved mine by also exporting the `wrapRootElement` in gatsby-ssr.js. It is suggested by gatsby documentation to use both.

**Comment by XavierMod** [comment] 2020-09-12 22:09
> You also have to use the wrapPage thingy in `gatsby-ssr.js`

Fixed it for me!
