### ISSUE TITLE
shouldUpdateScroll not working with Firefox & Chrome

### ISSUE THREAD

**Issue by jcontonio** [gatsbyjs/gatsby#24880] opened 2020-06-08 21:30 UTC
## Description

Returning `false` from `shouldUpdateScroll` should prevent scrolling to the top of the page on a route change.

### Steps to reproduce

Add the following to gatsby-browser.js - also note that `getSavedScrollPosition` returns null when passing location.path and location.key.

```
exports.shouldUpdateScroll = ({
  routerProps,
  getSavedScrollPosition
}) => {
  const currentLocation = getSavedScrollPosition(routerProps.location, routerProps.location.key);
  console.log(currentLocation); // null
  return false; // still scrolls in Firefox & Chrome, does as expected in Safari
};

### Expected result

The page shouldn't scroll when clicking a link 

### Actual result

The page scrolls to the top in Firefox, but not in Safari

### Environment

```
  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.0 - ~/.nvm/versions/node/v12.16.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.16.0/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.97
    Firefox: 77.0.1
    Safari: 13.1
  npmPackages:
    gatsby: ^2.23.1 => 2.23.1 
    gatsby-background-image: ^1.1.1 => 1.1.1 
    gatsby-image: ^2.4.6 => 2.4.6 
    gatsby-plugin-eslint: ^2.0.5 => 2.0.8 
    gatsby-plugin-layout: ^1.3.3 => 1.3.3 
    gatsby-plugin-manifest: ^2.4.10 => 2.4.10 
    gatsby-plugin-offline: ^3.2.8 => 3.2.8 
    gatsby-plugin-react-helmet: ^3.3.3 => 3.3.3 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5 
    gatsby-plugin-sass: ^2.3.3 => 2.3.3 
    gatsby-plugin-sharp: ^2.6.10 => 2.6.10 
    gatsby-plugin-typescript: ^2.1.19 => 2.4.4 
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4 
    gatsby-source-filesystem: ^2.3.10 => 2.3.10 
    gatsby-transformer-sharp: ^2.3.16 => 2.5.4 
  npmGlobalPackages:
    gatsby-cli: 2.10.13

```

**Comment by danabrit** [comment] 2020-06-08 23:41
Hi {name}!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2020-06-16 09:39
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-06-16 09:39 UTC
Labels: status: needs reproduction, topic: frontend-core, type: bug
