### ISSUE TITLE
The path "/" errored during SSR. React-Dom

### ISSUE THREAD

**Issue by joebentaylor1995** [gatsbyjs/gatsby#30076] opened 2021-03-08 02:45 UTC
Hi,

Just created a brand new Gatsby build from scratch, nothing installed bu the bare essentials from the gatsby CLI.

Once i try to run `gatsby develop` i get this error:
```
Couldn't read the file /Users/joetaylor/Documents/www/joebentaylor/joetaylor/Documents/www/joebentaylor/node_modules/react-dom/cjs/react-dom-server.node.development.js, possibly due to source maps failing
original error Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    at ReactDOMServerRenderer.render (/Users/joetaylor/Documents/www/joebentaylor/node_modules/react-dom/cjs/react-dom-server.node.development.js:3743:17)
    at ReactDOMServerRenderer.read (/Users/joetaylor/Documents/www/joebentaylor/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
    at renderToString (/Users/joetaylor/Documents/www/joebentaylor/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
    at generateBodyHTML (/Users/joetaylor/Documents/www/joebentaylor/public/webpack:/lib/.cache/ssr-develop-static-entry.js:259:34)
    at Module.default (/Users/joetaylor/Documents/www/joebentaylor/public/webpack:/lib/.cache/ssr-develop-static-entry.js:289:19)
    at /Users/joetaylor/Documents/www/joebentaylor/node_modules/gatsby/src/utils/dev-ssr/render-dev-html-child.js:138:9
    at new Promise (<anonymous>)
    at Object.exports.renderHTML (/Users/joetaylor/Documents/www/joebentaylor/node_modules/gatsby/src/utils/dev-ssr/render-dev-html-child.js:134:3)
    at execFunction (/Users/joetaylor/Documents/www/joebentaylor/node_modules/jest-worker/build/workers/processChild.js:155:17)
warn The path "/" errored during SSR.

    Edit its component joetaylor/Documents/www/joebentaylor/node_modules/react-dom/cjs/react-dom-server.node.development.js to resolve the error.
```

From what I can see here, the issue lies in `react-dom`

Has anybody else had this issue or know a fix?

**Comment by LekoArts** [comment] 2021-03-08 09:30
Hi, thanks for the issue!

Our issue template for bug reports helps both parties to get to a result faster. Please fill it out, thanks!

```md
<!--
  Please fill out each section below, otherwise, your issue will be closed. This info allows Gatsby maintainers to diagnose (and fix!) your issue as quickly as possible.

  Useful Links:
  - Documentation: https://www.gatsbyjs.com/docs/
  - How to File an Issue: https://www.gatsbyjs.com/contributing/how-to-file-an-issue/

  Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
-->

## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
```

**Comment by joebentaylor1995** [comment] 2021-03-10 02:38
## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

### Expected result

Gatsby should build with no issues in development

### Actual result

Hi,

Just created a brand new Gatsby build from scratch, nothing installed bu the bare essentials from the gatsby CLI.


Once i try to run `gatsby develop` i get this error:
```
Couldn't read the file /Users/joetaylor/Documents/www/joebentaylor/joetaylor/Documents/www/joebentaylor/node_modules/react-dom/cjs/react-dom-server.node.development.js, possibly due to source maps failing
original error Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    at ReactDOMServerRenderer.render (/Users/joetaylor/Documents/www/joebentaylor/node_modules/react-dom/cjs/react-dom-server.node.development.js:3743:17)
    at ReactDOMServerRenderer.read (/Users/joetaylor/Documents/www/joebentaylor/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
    at renderToString (/Users/joetaylor/Documents/www/joebentaylor/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
    at generateBodyHTML (/Users/joetaylor/Documents/www/joebentaylor/public/webpack:/lib/.cache/ssr-develop-static-entry.js:259:34)
    at Module.default (/Users/joetaylor/Documents/www/joebentaylor/public/webpack:/lib/.cache/ssr-develop-static-entry.js:289:19)
    at /Users/joetaylor/Documents/www/joebentaylor/node_modules/gatsby/src/utils/dev-ssr/render-dev-html-child.js:138:9
    at new Promise (<anonymous>)
    at Object.exports.renderHTML (/Users/joetaylor/Documents/www/joebentaylor/node_modules/gatsby/src/utils/dev-ssr/render-dev-html-child.js:134:3)
    at execFunction (/Users/joetaylor/Documents/www/joebentaylor/node_modules/jest-worker/build/workers/processChild.js:155:17)
warn The path "/" errored during SSR.

    Edit its component joetaylor/Documents/www/joebentaylor/node_modules/react-dom/cjs/react-dom-server.node.development.js to resolve the error.
```

From what I can see here, the issue lies in `react-dom`

Has anybody else had this issue or know a fix?

### Environment


  System:
    OS: macOS 11.2.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.11.0 - ~/.nvm/versions/node/v15.11.0/bin/node
    npm: 7.6.0 - ~/.nvm/versions/node/v15.11.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 88.0.4324.192
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.0.1 => 3.0.1 
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5 
    gatsby-plugin-breakpoints: ^1.3.2 => 1.3.2 
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0 
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0 
    gatsby-plugin-robots-txt: ^1.5.5 => 1.5.5 
    gatsby-plugin-sitemap: ^3.0.0 => 3.0.0 
    gatsby-plugin-styled-components: ^4.0.0 => 4.0.0 
    gatsby-plugin-transition-link: ^1.20.5 => 1.20.5

**Comment by LekoArts** [comment] 2021-03-10 09:05
I'm afraid this is still not helpful as you left out the "Steps to reproduce" part. Please fill that out and link a minimal reproduction / a repository where this is happening.

**Comment by LekoArts** [comment] 2021-03-16 12:31
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-03-16 12:31 UTC
Labels: status: needs reproduction, type: bug

**Comment by lbittner-pdftron** [comment] 2021-07-22 15:30
+1 seeing this issue on Linux as well.

Looks like there is a bug resolving the path to `react-dom-server.node.development.js`, you can see it has `joetaylor/Documents/www/joebentaylor/joetaylor/Documents/www` twice in the error message
