### ISSUE TITLE
New Translation Request - Portuguese

### ISSUE THREAD

**Issue by virginiarcruz** [gatsbyjs/gatsby#18544] opened 2019-10-12 02:56 UTC
```yaml
name: Portuguese
code: pt
maintainers:
  - virginiarcruz
```

**Comment by jonniebigodes** [comment] 2019-10-12 03:14
@virginiarcruz i see that you hail from brazil...there's already a issue requesting a portuguese brazilian created in #18178. If you don't mind reply there and coordinate your efforts with the maintainers involved. And if possible close this issue as it's a duplicate

**Comment by tesseralis** [comment] 2019-10-27 20:25
duplicate of https://github.com/gatsbyjs/gatsby/issues/18178

**Closed by tesseralis** 2019-10-27 20:25 UTC
Labels: topic: i18n
