### ISSUE TITLE
 `gatsby develop` command gets stuck at source and transform nodes

### ISSUE THREAD

**Issue by KashafS98** [gatsbyjs/gatsby#23829] opened 2020-05-06 11:24 UTC
## Summary
 `gatsby develop` command gets stuck at source and transform nodes. It sometimes magically gets solved using a few options, but the problems persists. no way to find a sure shot solution out of it.
## Relevant information
I have been dealing with this issue since some time now. i have checked issues [#17131](https://github.com/gatsbyjs/gatsby/issues/17131), [7885](https://github.com/gatsbyjs/gatsby/issues/7855), [6645](https://github.com/gatsbyjs/gatsby/issues/6654), [6385](https://github.com/gatsbyjs/gatsby/issues/6385) and more irrelevant ones.

The problem is, one solution worked for me a few days back: **resizing the window**
BUT when i try the same thing again today, it doesn't seem to work right.

I have tried : 

1. clone the repository again 
2. delete `node_modules` and run `yarn install`
3. delete lock files and run `yarn install`
4. clear cache using `gatsby clean`

Issues regarding this have been closed in the past, but there doesn't seem to be one solution to it! 
:-(

### Environment (if relevant)
System:
    OS: Linux 5.3 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 12.14.1 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.13.4 - /usr/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.117
    Firefox: 74.0
  npmPackages:
    gatsby: ^2.19.3 => 2.19.3
    gatsby-cli: ^2.12.11 => 2.12.11
    gatsby-image: ^2.2.39 => 2.2.39
    gatsby-plugin-google-analytics: ^2.1.35 => 2.1.35
    gatsby-plugin-manifest: ^2.2.31 => 2.2.31
    gatsby-plugin-offline: ^3.0.27 => 3.0.27
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.21
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sass: ^2.1.27 => 2.1.27
    gatsby-plugin-sharp: ^2.4.0 => 2.4.0
    gatsby-plugin-sitemap: ^2.2.27 => 2.2.27
    gatsby-plugin-styled-components: ^3.1.18 => 3.1.18
    gatsby-plugin-typography: ^2.3.21 => 2.3.21
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-filesystem: ^2.1.46 => 2.1.46
    gatsby-source-wordpress: ^3.1.58 => 3.1.58
    gatsby-transformer-json: ^2.2.25 => 2.2.25
    gatsby-transformer-sharp: ^2.3.13 => 2.3.13
  npmGlobalPackages:
    gatsby: 2.18.21

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: N/A 
`gatsby-browser.js`: N/A 
`gatsby-ssr.js`: N/A

**Comment by vladar** [comment] 2020-05-06 17:33
Hi @KashafS !

Issues like this can be caused by many different things. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by pvdz** [comment] 2020-05-06 17:57
I'll take any reproducable example for this one ;)

**Comment by KashafS98** [comment] 2020-05-07 07:43
Sure, I'll share the minimal reproduction of this as soon as possible

**Comment by danabrit** [comment] 2020-06-02 22:38
Closing this issue due to no reproduction for several weeks. If you would like to re-open it with a minimal reproduction, we'd be happy to take a look. Thank you!

**Closed by danabrit** 2020-06-02 22:38 UTC
Labels: status: needs reproduction, topic: cli

**Comment by dalalRohit** [comment] 2020-06-25 19:06
> ## Summary
> `gatsby develop` command gets stuck at source and transform nodes. It sometimes magically gets solved using a few options, but the problems persists. no way to find a sure shot solution out of it.
> 
> ## Relevant information
> I have been dealing with this issue since some time now. i have checked issues [#17131](https://github.com/gatsbyjs/gatsby/issues/17131), [7885](https://github.com/gatsbyjs/gatsby/issues/7855), [6645](https://github.com/gatsbyjs/gatsby/issues/6654), [6385](https://github.com/gatsbyjs/gatsby/issues/6385) and more irrelevant ones.
> 
> The problem is, one solution worked for me a few days back: **resizing the window**
> BUT when i try the same thing again today, it doesn't seem to work right.
> 
> I have tried :
> 
> 1. clone the repository again
> 2. delete `node_modules` and run `yarn install`
> 3. delete lock files and run `yarn install`
> 4. clear cache using `gatsby clean`
> 
> Issues regarding this have been closed in the past, but there doesn't seem to be one solution to it!
> :-(
> 
> ### Environment (if relevant)
> System:
> OS: Linux 5.3 Ubuntu 18.04.3 LTS (Bionic Beaver)
> CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
> Shell: 5.4.2 - /usr/bin/zsh
> Binaries:
> Node: 12.14.1 - /usr/bin/node
> Yarn: 1.21.1 - /usr/bin/yarn
> npm: 6.13.4 - /usr/bin/npm
> Languages:
> Python: 2.7.17 - /usr/bin/python
> Browsers:
> Chrome: 79.0.3945.117
> Firefox: 74.0
> npmPackages:
> gatsby: ^2.19.3 => 2.19.3
> gatsby-cli: ^2.12.11 => 2.12.11
> gatsby-image: ^2.2.39 => 2.2.39
> gatsby-plugin-google-analytics: ^2.1.35 => 2.1.35
> gatsby-plugin-manifest: ^2.2.31 => 2.2.31
> gatsby-plugin-offline: ^3.0.27 => 3.0.27
> gatsby-plugin-react-helmet: ^3.1.21 => 3.1.21
> gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
> gatsby-plugin-sass: ^2.1.27 => 2.1.27
> gatsby-plugin-sharp: ^2.4.0 => 2.4.0
> gatsby-plugin-sitemap: ^2.2.27 => 2.2.27
> gatsby-plugin-styled-components: ^3.1.18 => 3.1.18
> gatsby-plugin-typography: ^2.3.21 => 2.3.21
> gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
> gatsby-source-filesystem: ^2.1.46 => 2.1.46
> gatsby-source-wordpress: ^3.1.58 => 3.1.58
> gatsby-transformer-json: ^2.2.25 => 2.2.25
> gatsby-transformer-sharp: ^2.3.13 => 2.3.13
> npmGlobalPackages:
> gatsby: 2.18.21
> 
> ### File contents (if changed)
> `gatsby-config.js`: N/A
> `package.json`: N/A
> `gatsby-node.js`: N/A
> `gatsby-browser.js`: N/A
> `gatsby-ssr.js`: N/A

How did you solve this? I'm also facing the same issue and it gets stuck for hours if not pressed ctrl+c ;(

**Comment by RonaldTshawe** [comment] 2020-06-27 21:19
Yep pretty much does the same on my side...waited for hours and still stuck
> gatsby develop
success open and validate gatsby-configs - 0.041s
success load plugins - 1.051s
success onPreInit - 0.026s
success initialize cache - 0.028s
success copy gatsby files - 0.138s
success onPreBootstrap - 0.018s
success createSchemaCustomization - 0.007s
 -> wordpress__POST fetched : 55508
 -> wordpress__PAGE fetched : 14
 -> wordpress__wp_media fetched : 24939
 -> wordpress__wp_taxonomies fetched : 1
 -> wordpress__CATEGORY fetched : 39
 -> wordpress__TAG fetched : 65748
 -> wordpress__wp_users fetched : 3
⠏ source and transform nodes

**Comment by pvdz** [comment] 2020-07-07 17:33
@RonaldTshawe if you have a repo we can take a look at and build ourselves, then please open a new issue and tag me in it. If I can't reproduce the build then there's nothing I can do to triage. My suspicion is that something is simply taking a long time. This can be the actual download or the processing. This also depends on the speed of your server etc.

Going to lock this issue because the topic is too generic. If your build is "stuck" at `source and transform` nodes then it's more than likely just taking a very long time. This might be caused by many things, large amount of content would be one of them. If you have a large site and it takes long and you can have us build it locally to repro, then open a new issue and feel free to tag me in it.

Thank you :purple_heart:
