### ISSUE TITLE
[gatsby-source-wordpress] can't query a specific page id to get this page's child page

### ISSUE THREAD

**Issue by supriome** [gatsbyjs/gatsby#24433] opened 2020-05-25 10:49 UTC
## Description

I use gatsbyjs with wordpress through [gatsby-source-wordpress] plugin. But when i create a new page named page1 which wordpress_id is 594, then i create a page2 which parent is page1 and wordpress_id is 596.

So when i use graphql to query 

```
{
  wordpressPage(wordpress_id: {eq: 594}) {
    path
    title
    wordpress_id
    wpml_current_locale
    children {
      id
    }
  }
}
```

it's return a data: 

```
{
  "data": {
    "wordpressPage": {
      "path": "/page-1/",
      "title": "page 1",
      "wordpress_id": 594,
      "wpml_current_locale": "zh_CN",
      "children": []
    }
  }
}
```

but the data return in filed "children" is undefined;
![image](https://user-images.githubusercontent.com/19944032/82806311-157e6f00-9eb8-11ea-991e-2c636fbce55b.png)

And wordpress has a function called [get_children()](https://developer.wordpress.org/reference/functions/get_children/),so you can query page2 through page1's wordpress id.

![image](https://user-images.githubusercontent.com/19944032/82806346-2b8c2f80-9eb8-11ea-9462-a19a17f9ad42.png)

### Expected result

The filed "children" should return page2's info which contain wordpress_id and title.

### Environment

```
  System:
    OS: macOS 10.15.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.20.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.138
    Firefox: 76.0.1
    Safari: 13.1
  npmPackages:
    gatsby: ^2.21.37 => 2.22.1 
    gatsby-awesome-pagination: ^0.3.6 => 0.3.6 
    gatsby-image: ^2.4.4 => 2.4.4 
    gatsby-plugin-advanced-sitemap: ^1.5.4 => 1.5.4 
    gatsby-plugin-baidu-analytics: ^2.2.0 => 2.2.0 
    gatsby-plugin-force-trailing-slashes: ^1.0.4 => 1.0.4 
    gatsby-plugin-google-analytics: ^2.3.1 => 2.3.1 
    gatsby-plugin-i18n: ^1.0.1 => 1.0.1 
    gatsby-plugin-lodash: ^3.3.1 => 3.3.1 
    gatsby-plugin-manifest: ^2.4.5 => 2.4.6 
    gatsby-plugin-offline: ^3.2.3 => 3.2.4 
    gatsby-plugin-react-helmet: ^3.3.1 => 3.3.1 
    gatsby-plugin-sharp: ^2.6.4 => 2.6.6 
    gatsby-source-filesystem: ^2.3.4 => 2.3.5 
    gatsby-source-wordpress: ^3.3.5 => 3.3.5 
    gatsby-transformer-sharp: ^2.5.2 => 2.5.2 
  npmGlobalPackages:
    gatsby-cli: 2.7.7
```

**Comment by LekoArts** [comment] 2020-05-25 13:35
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by danabrit** [comment] 2020-06-02 22:26
@supriome - Closing due to no reproduction in 7 days. If you would like to add the minimal repro and re-open the issue, we'd be happy to take a look!

**Closed by danabrit** 2020-06-02 22:26 UTC
Labels: status: needs reproduction, topic: WordPress

**Comment by marco910** [comment] 2021-07-30 09:13
I'm having the same issue. How did you solve it @supriome ?
