### ISSUE TITLE
Starter doesn't work with Module build failed: Error: Couldn't find preset "env" relative to directory home/<user>

### ISSUE THREAD

**Issue by episodeyang** [gatsbyjs/gatsby#3756] opened 2018-01-28 19:13 UTC
## Description

install `gatsby`, do `gatsby create new-site`. go in new-site and do `gatsby develop`, gives following error:

```error
Module build failed: Error: Couldn't find preset "env" relative to directory
```
### Environment

Gatsby version: newest
Node.js version: 9.3.0
Operating System: macOS 10.13.3

### File contents (if changed):

nothing changed. Directly from create.

Dear community, what is the problem here? I don't want to install `babel-preset-env` globally. I use it with every project, but I just do local install since this way it is easy to prevent this kind of bug in my projects.

It seems that gatsby requires babel-preset-env globally?

**Comment by tsriram** [comment] 2018-01-29 13:00
I could not reproduce this issue with same versions of Gatsby & Node on Ubuntu. Can you try with a starter explicitly like mentioned in #2092 and see if it works?

**Comment by ATwrx** [comment] 2018-07-21 00:00
Removing a global babel config from my home folder fixed it for me.

**Comment by JMV2112** [comment] 2018-07-24 20:34
I can confirm that removing my projects .bablerc file fixed the problem for me as I migrate from v1 to v2.

**Comment by KyleAMathews** [comment] 2018-09-08 05:44
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Closed by KyleAMathews** 2018-09-08 05:44 UTC
