### ISSUE TITLE
Command name in help output is wrong.

### ISSUE THREAD

**Issue by ronaldborman** [gatsbyjs/gatsby#12154] opened 2019-02-27 20:31 UTC
## Description

When I run 'npx gatsby --help' (as suggested by https://www.gatsbyjs.org/tutorial/part-zero/) the help text displays the wrong command name:
> Usage: gatsby.js <command> [options]
> 
> Commands:
>   gatsby.js develop...
> 

When I then install the cli globally the help text output (with or without the use of npx) changes to:
>  Usage: index.js <command> [options]
> 
> Commands:
>   index.js develop...
> 

### Steps to reproduce

run 'npx gatsby --help'
run 'npm install -g gatsby-cli'
run 'gatsby --help'

### Expected result

The help text should contain the command name 'gatsby' (without the extension .js).

### Actual result

The help text contains the command name 'gatsby.js' (when npx is used) or 'index.js' (after the global installation of gatsby-cli).

### Environment

Node 8.9.4, npm 5.10.0, gatsby 2.4.11.

**Comment by yogeshkotadiya** [comment] 2019-02-28 07:24
I can't reproduce this, working as expected.
Same as #5838
I'll take a look into this.

**Comment by yogeshkotadiya** [comment] 2019-03-12 15:11
Merged in #12186

**Closed** 2019-03-12 15:10 UTC
Labels: type: question or discussion
