### ISSUE TITLE
WordPress image query incomplete

### ISSUE THREAD

**Issue by adrianhewitt** [gatsbyjs/gatsby#30844] opened 2021-04-13 01:30 UTC
## Description

Some images seem not to be downloading locally from WordPress. The images are shown in GraphiQL IDE inside WordPress, but once Gatsby queries WordPress they are not shown in Gatsby's GraphQL browser or the project.

Example query which should all contain images:

```query MyQuery {
  allWpWork {
    edges {
      node {
        work {
          screenshotDesktop {
            localFile {
              childImageSharp {
                gatsbyImageData
              }
            }
          }
        }
        slug
        featuredImage {
          node {
            localFile {
              childImageSharp {
                gatsbyImageData
              }
            }
          }
        }
      }
    }
  }
}
```

### Steps to reproduce

https://github.com/adrianhewitt/Gatsby-Troubleshooting

Paired the project down as small as I could. Grab it and do the above query, or try to go to the work Work page. 

### Expected result

Every Work item has a Feature Image and 3 other images defined through the ACF plugin. The Work archive pages have a Feature Image thumbnail defined, and the single Work pages have 3 ACF images defined. All images should be readable.

### Actual result

The occasional image will trip up with the error (partially because i'm not testing to see if they exists, although all images do exist in the cms):

```
Error in function eval in ./src/templates/archive-work.js:81
Cannot read property 'localFile' of null
```

Feature Image that refuses to download for:
/work/relationships-australia-tasmania-annual-report-2019-2020/
at
/work/

One of the ACF images refuses to download for 
/work/sacred-seeds-yoga-school/
but it's Feature image is fine at
/work/2

Additionally I can change the image to another and it will query fine, but clearing the gatsby cache and changing it back to that specific image causes the query to die again.. 

### Environment

  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmPackages:
    gatsby: ^3.2.1 => 3.2.1
    gatsby-image: ^3.2.0 => 3.2.0
    gatsby-paginate: ^1.1.1 => 1.1.1
    gatsby-plugin-google-analytics: ^3.2.0 => 3.2.0
    gatsby-plugin-htaccess: ^1.4.0 => 1.4.0
    gatsby-plugin-image: ^1.2.1 => 1.2.1
    gatsby-plugin-postcss: ^4.2.0 => 4.2.0
    gatsby-plugin-purgecss: ^6.0.0 => 6.0.0
    gatsby-plugin-react-helmet: ^4.2.0 => 4.2.0
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.5
    gatsby-plugin-sharp: ^3.2.1 => 3.2.1
    gatsby-plugin-sitemap: ^3.2.0 => 3.2.0
    gatsby-plugin-web-font-loader: ^1.0.4 => 1.0.4
    gatsby-source-filesystem: ^3.2.0 => 3.2.0
    gatsby-source-wordpress: ^5.2.2 => 5.2.2
    gatsby-transformer-sharp: ^3.2.0 => 3.2.0
  npmGlobalPackages:
    gatsby-cli: 3.2.0

**Comment by veryspry** [comment] 2021-04-13 18:08
Closing since this is a duplicate of  https://github.com/gatsbyjs/gatsby/issues/30755

**Closed by veryspry** 2021-04-13 18:08 UTC
Labels: topic: WordPress, type: bug
