### ISSUE TITLE
The first gatsby-image in a Swiper slideshow is always blurred after first loop

### ISSUE THREAD

**Issue by viktor-wolf** [gatsbyjs/gatsby#18528] opened 2019-10-11 18:38 UTC
## Description

I have a [Swiper](https://swiperjs.com/) slideshow filled with gatsby-images on a website. On the initial load, the first image is blurred for a short while and then gets cleared up when it's fully loaded. The slideshow proceeds normally through the rest of the slides and then loops back to the first one, which will display the blurred version of its image, only flashing the correct image for a split-second just before the next slide is shown correctly. This issue persists through all subsequent loops.

### Steps to reproduce

Put gatsby-images into Swiper slideshow slides. The first one should have the issue after the first loop. The issue is consistent between the latest versions of Firefox, Chrome and Edge. The issue can be seen here: [http://new.moravsky.sk](http://new.moravsky.sk)

EDIT: [Minimal reproduction](https://github.com/viktor-wolf/gatsby-image-swiper-bug)

### Expected result

The fully loaded version of the image should always be shown after it has been loaded.

### Actual result

The image in the first slide is blurred until the transition to the next slide starts.

### Environment

  System:
    OS: Windows 10
    CPU: (16) x64 AMD Ryzen 7 1700 Eight-Core Processor          
  Binaries:
    npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.387.0
  npmPackages:
    gatsby: ^2.15.14 => 2.15.14 
    gatsby-image: ^2.2.18 => 2.2.18 
    gatsby-plugin-manifest: ^2.2.16 => 2.2.16 
    gatsby-plugin-offline: ^2.2.10 => 2.2.10 
    gatsby-plugin-react-helmet: ^3.1.7 => 3.1.7 
    gatsby-plugin-sharp: ^2.2.21 => 2.2.21 
    gatsby-plugin-styled-components: ^3.1.5 => 3.1.5 
    gatsby-source-filesystem: ^2.1.22 => 2.1.22 
    gatsby-transformer-sharp: ^2.2.14 => 2.2.14

**Comment by TylerBarnes** [comment] 2019-10-11 18:55
Hi @viktor-wolf!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by viktor-wolf** [comment] 2019-10-11 22:28
@TylerBarnes Hi! I have added a [minimal reproduction](https://github.com/viktor-wolf/gatsby-image-swiper-bug) to my original comment.

**Comment by nstayte** [comment] 2019-10-14 10:53
I'm having the exact same issue using [react-id-swiper](https://github.com/kidjp85/react-id-swiper) component. I've also tried using fixed instead of fluid images and the issue happens with those as well.

**Comment by TylerBarnes** [comment] 2019-10-15 21:56
Hi @viktor-wolf and @nstayte , I pulled down the reproduction to have a look locally. The issue is that swiper is duplicating the DOM nodes of the first and last image and appending them to the end of the swiper-container element. This doesn't play nice with React because swiper is duplicating DOM nodes instead of React elements which removes all of the statefulness of `gatsby-image` and only copies the html. 

So, the issue is upstream on the swiper side, but with that being said, you may be able to get it to work using the `slideChange` event in swiper. That event is fired every time a slide is changed so you may be able to use that to select the active slides DOM node and add `opacity: 1;` to the css of the img.

**Closed** 2019-10-15 21:56 UTC
Labels: status: needs reproduction, type: upstream

**Comment by viktor-wolf** [comment] 2019-10-18 19:42
@TylerBarnes Hi, thanks for looking into it. I have tried playing around with the opacity of the slideshow elements in browser dev tools, but I was unable to get the desired result. If you have time, could you elaborate what led you to believe that opacity was the problem and how your proposed workaround was supposed to work?

**Comment by TylerBarnes** [comment] 2019-10-18 22:44
@viktor-wolf If you inspect the blurred elements and change the CSS manually for the hi-res image to `opacity: 1`, the image shows up. The problem is that Swiper removes the statefulness of gatsby-image when it copies the DOM nodes, so it will never reveal the hi-res image and just displays the base64 low-quality image placeholder. It also might be easier to replace Swiper with a React based slider. 
You can verify this by looking at the DOM, if the slider has 5 images, there will be 7 in the DOM, however in React devtools there will only be 5 elements.

**Comment by viktor-wolf** [comment] 2019-10-22 19:41
@TylerBarnes I don't know what I was doing wrong, but I was unable to get the image to show by changing the opacity, so I just bit the bullet and wrote my own little slideshow script that works correctly with gatsby-image. Thanks again for taking the time to look into this and giving me advice :)

**Comment by TylerBarnes** [comment] 2019-10-22 19:45
@viktor-wolf anytime! Glad to hear you have something working for your site :)

**Comment by Jfelix61** [comment] 2020-06-02 22:25
Thanks @TylerBarnes! For those of you that have this problem here is a snippet of a fix:

```
const [swiper, updateSwiper] = React.useState(null)


const slideParams = {   
    loop: true,
    getSwiper: updateSwiper,   
}


React.useEffect(() => {
    if (swiper) {
      const slides = swiper.slides

      Object.values(slides).forEach(elem => {
        if (
          elem.querySelector &&
          elem.classList.contains("swiper-slide-duplicate")
        ) {
          // @ts-ignore
          elem.querySelector("picture > img").style.opacity = 1
        }
      })
    }
 }, [swiper])

```
