### ISSUE TITLE
"The result of this StaticQuery could not be fetched" on basic graphql query to render gatsby-image

### ISSUE THREAD

**Issue by dfamilia33** [gatsbyjs/gatsby#24127] opened 2020-05-15 19:51 UTC
<h2>Description</h2>

Executing `gatsby develop` throws the following error:

```
Error: The result of this StaticQuery could not be fetched. 
This is likely a bug in Gatsby and if refreshing the page
does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues
```
when executing the basic use case as per the official [tutorial](https://www.gatsbyjs.org/docs/using-gatsby-image/):

```
const  data = useStaticQuery(graphql`
	query  MyQuery {
		file(relativePath: {eq: "myImage.jpg"}) {
			childImageSharp {
				fluid {
					aspectRatio
					base64
					sizes
					src
					srcSet
				}
			}
		}
	}
`);

```
I can not seem to figure out what's wrong as the query in graphql's IDE
at [http://localhost:8000/___graphql](http://localhost:8000/___graphql) seems to be delivering expected results.

<h3>Steps to reproduce</h3>

```
git clone https://github.com/dfamilia33/alphaphiotasreact.git
git reset --hard c4302f9f4abfea9d9d0d3cc13ff9392df3fc2e17
cd alphaphiotasreact
gatsby develop
```
Code that produces bug: `src\pages\index.js`

```
import  React  from  "react"
import  ReactDOM  from  'react-dom';
import  Toolbar  from  "../components/toolbar"
import  Img  from  "gatsby-image"
import { useStaticQuery, graphql} from  "gatsby"

export  default  function  Index() {
	const  data = useStaticQuery(graphql`
		query  MyQuery {
			file(relativePath: {eq: "myImage.jpg"}) {
				childImageSharp {
					fluid {
						aspectRatio
						base64
						sizes
						src
						srcSet
					}
				}
			}
		}
	`);

  

	return (
		<div>
			<Toolbar/>
			<Img  fluid = {data.childImageSharp.fluid}
			alt = "Chapter Photo"
			/>
		</div>
	)
}

ReactDOM.render(<Index/>, document.getElementById('___gatsby'));
```
<h3>Expected Result</h3>

`gatsby develop`  renders page with optimized image

<h3>Actual Result</h3>

`gatsby develop` produces above error

<h3>Environment</h3>

```
System: 
	OS: Ubuntu 18.04.1 LTS (Bionic Beaver)
	CPU: Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
	Shell: version 4.4.19(1)-release
Binaries:
	Node: v13.7.0
	Npm: v6.13.6
Browsers:
	Chrome: 81.0.4044.138
	Edge: 42.17134.1098.0
npmPackages:
├── bootstrap@4.5.0
├── gatsby@2.21.22
├── gatsby-image@2.4.3
├── gatsby-plugin-sharp@2.6.3
├── gatsby-source-filesystem@2.3.3
├── gatsby-transformer-sharp@2.5.2
├── UNMET PEER DEPENDENCY jquery@1.9.1 - 3
├── UNMET PEER DEPENDENCY popper.js@^1.16.0
├── prettier@2.0.5
├── react@16.13.1
├── react-bootstrap@1.0.1
├── react-dom@16.13.1
└── styled-components@5.1.0
```
Thank you!

**Comment by sbardian** [comment] 2020-06-18 04:09
@dfamilia33 I had this error show up out of the blue today.  I did some digging around and console logging in `gatsby/cache-dir/gatsby-browser-entry.js` and found that the hash for my static query was not matching the one in the static queries context (or the one using command `gatsby repl > staticQueries`, I was able to clear this up by tweaking my static query (adding a query field) to generate a new hash.  Then reverting back to my old static query. 

Not sure how this got hung up/out of sync, and `gatsby clean` doesn't appear to clear this up either.  Thought I would mention how I cleared mine up since this doesn't appear to be because of a recent update/etc., and maybe it will help someone track it down.

**Comment by simonwinter** [comment] 2020-06-18 21:39
I can concur with @sbardian - adding a comment to the query seems to resolve this! It does seem like an issue with the cache!

**Comment by sbardian** [comment] 2020-06-19 03:04
I did some reading about how static queries are extracted and stored in the `staticQueryComponents` namespace store/etc.  So I loaded up the dev environment to play around and see if I could spot what was going on/wrong. . . . and my project seems to be fine now.  Sooo. . .  ¯\\_(ツ)_/¯ . . . @simonwinter @dfamilia33  can you confirm your projects/queries are still broken, without the query comment busting the cache?

**Comment by simonwinter** [comment] 2020-06-20 01:20
@sbardian the weird thing was ... on one machine (macbook pro) which I was doing my main development on, everything was cool. Switch to my work desktop (Ubuntu) which had previously been fine, suddenly had issues.

Super ... ¯\_(ツ)_/¯ ... I'll try again next week on the work machine - not 💯  sure this isn't a bug, but reproducibility is somewhat inconsistent so far! Will let you know how I get on.

**Comment by sbardian** [comment] 2020-06-20 14:10
Agreed it is strange, might dig in to see if I can find how the hash is created.  Might be something "variable" there or something ... Shrug.

**Comment by vladar** [comment] 2020-09-02 11:56
Thank you for opening this, @dfamilia33 

The culprit is this line in `pages/index.js`:

```js
ReactDOM.render(<Index/>, document.getElementById('___gatsby'));
```

You don't need it there. This will render the component before the static query is executed by Gatsby. If I remove this line everything works as expected.

We're marking this issue as answered and closing it for now but please feel free to comment and mention me if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Closed by vladar** 2020-09-02 11:56 UTC
Labels: topic: StaticQuery, type: bug
