### ISSUE TITLE
gatsby-remark-embed-video update causes gatsby-plugin-mdx to throw sourceNodes lifecycle error

### ISSUE THREAD

**Issue by janosh** [gatsbyjs/gatsby#18135] opened 2019-10-04 18:01 UTC
## Description

Trying `gatsby develop` in [this repo](https://github.com/janosh/janosh.io) fails with 

```
ERROR #11321  PLUGIN

"gatsby-plugin-mdx" threw an error while running the sourceNodes lifecycle:

Cannot destructure property `beginMarker` of 'undefined' or 'null'.

  - index.js:43 Function.setParserPlugins
    [janosh.io]/[gatsby-remark-embed-video]/dist/index.js:43:27
  
  - source-nodes.js:92 Object.module.exports [as sourceNodes]
    [janosh.io]/[gatsby-plugin-mdx]/gatsby/source-nodes.js:92:47
```

### Environment

```
System:
  OS: macOS 10.14.6
  CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Shell: 5.3 - /bin/zsh
Binaries:
  Node: 12.11.1 - /usr/local/bin/node
  Yarn: 1.19.0 - /usr/local/bin/yarn
  npm: 6.11.3 - /usr/local/bin/npm
Languages:
  Python: 2.7.10 - /usr/bin/python
Browsers:
  Chrome: 76.0.3809.87
  Firefox: 68.0.2
  Safari: 13.0.1
npmPackages:
  gatsby: 2.15.29 => 2.15.29 
  gatsby-image: 2.2.24 => 2.2.24 
  gatsby-plugin-algolia: ^0.3.4 => 0.3.4 
  gatsby-plugin-catch-links: 2.1.12 => 2.1.12 
  gatsby-plugin-favicon: ^3.1.6 => 3.1.6 
  gatsby-plugin-google-analytics: 2.1.20 => 2.1.20 
  gatsby-plugin-lodash: ^3.1.10 => 3.1.10 
  gatsby-plugin-manifest: 2.2.20 => 2.2.20 
  gatsby-plugin-mdx: ^1.0.47 => 1.0.47 
  gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0 
  gatsby-plugin-offline: 3.0.11 => 3.0.11 
  gatsby-plugin-react-helmet: 3.1.10 => 3.1.10 
  gatsby-plugin-sharp: 2.2.28 => 2.2.28 
  gatsby-plugin-styled-components: 3.1.8 => 3.1.8 
  gatsby-remark-autolink-headers: ^2.1.13 => 2.1.13 
  gatsby-remark-code-titles: ^1.1.0 => 1.1.0 
  gatsby-remark-copy-linked-files: ^2.1.24 => 2.1.24 
  gatsby-remark-embed-video: 2.0.0 => 2.0.0 
  gatsby-remark-emojis: ^0.3.2 => 0.3.2 
  gatsby-remark-images: 3.1.25 => 3.1.25 
  gatsby-remark-katex: ^3.1.12 => 3.1.12 
  gatsby-remark-responsive-iframe: 2.2.21 => 2.2.21 
  gatsby-remark-smartypants: 2.1.11 => 2.1.11 
  gatsby-remark-sub-sup: ^1.0.0 => 1.0.0 
  gatsby-remark-vscode: ^1.2.1 => 1.2.1 
  gatsby-source-filesystem: 2.1.29 => 2.1.29 
  gatsby-transformer-sharp: 2.2.20 => 2.2.20 
  gatsby-transformer-yaml: 2.2.12 => 2.2.12 
```

**Comment by janosh** [comment] 2019-10-04 18:22
Aha, the issue was caused by updating `gatsby-remark-embed-video` from 1.7 to 2.0. Downgrading resolves the error.

@d4rekanguok I'm guessing it was introduced by [this commit](https://github.com/borgfriend/gatsby-remark-embed-video/commit/81e2299). Not sure if that commit itself contains the error or if it just brought an error in `gatsby-plugin-mdx` to light.

**Comment by d4rekanguok** [comment] 2019-10-04 18:25
oh crap, that definitely looks like my fault. Let me check -- sorry about that!

**Comment by d4rekanguok** [comment] 2019-10-04 18:47
Hhhm I couldn't reproduce this on a normal repo with just `gatsby-transformer-remark`. I noticed the problematic line is this one<sup>[source](https://github.com/borgfriend/gatsby-remark-embed-video/blob/12a6d52a278bc007207d4823cd825ea214a0e861/src/index.ts#L49)</sup>:

```
Cannot destructure property `beginMarker` of 'undefined' or 'null'.
                                                     vvv
const setParserPlugins = ({ beginMarker, endMarker }) => ...
```

Has the plugin api been changed somehow? I haven't used mdx that much, so guidance in this issue is much appreciated!

**Comment by d4rekanguok** [comment] 2019-10-04 19:17
@janosh I've opened a PR in [gatsby-remark-embed-video](https://github.com/borgfriend/gatsby-remark-embed-video), I think it's safe to close this issue here & watch the one over there.

Thanks for reporting in!

**Closed** 2019-10-04 19:30 UTC
