### ISSUE TITLE
Gatsby 3.11.0 - Generating JavaScript bundles failed

### ISSUE THREAD

**Issue by flikteoh** [gatsbyjs/gatsby#32704] opened 2021-08-05 05:17 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Getting errors after updating Gatsby from `3.10.2` to `3.11.0`.

```
ERROR #98123  WEBPACK

Generating JavaScript bundles failed

Unexpected token (12:287)

File: .cache/production-app.js:12:287
```

### Reproduction Link

0

### Steps to Reproduce

1. Update gatsby-cli
2. Update Gatsby from 3.10.2 to 3.11.0
3. gatsby clean && gatsby build
...

### Expected Result

The site should build as per normal

### Actual Result

Getting error as below

```
ERROR #98123  WEBPACK

Generating JavaScript bundles failed

Unexpected token (12:287)

File: .cache/production-app.js:12:287
```

### Environment

```shell
System:
    OS: macOS 11.5.1
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
    npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 92.0.4515.131
    Safari: 14.1.2
  npmPackages:
    gatsby: ^3.11.0 => 3.11.0 
    gatsby-plugin-catch-links: ^3.11.0 => 3.11.0 
    gatsby-plugin-google-analytics: ^3.11.0 => 3.11.0 
    gatsby-plugin-image: ^1.11.0 => 1.11.0 
    gatsby-plugin-manifest: ^3.11.0 => 3.11.0 
    gatsby-plugin-mdx: ^2.11.0 => 2.11.0 
    gatsby-plugin-netlify: ^3.11.0 => 3.11.0 
    gatsby-plugin-preact: ^5.11.0 => 5.11.0 
    gatsby-plugin-react-helmet: ^4.11.0 => 4.11.0 
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0 
    gatsby-plugin-robots-txt: ^1.6.8 => 1.6.8 
    gatsby-plugin-sharp: ^3.11.0 => 3.11.0 
    gatsby-plugin-sitemap: ^4.7.0 => 4.7.0 
    gatsby-plugin-styled-components: ^4.11.0 => 4.11.0 
    gatsby-remark-autolink-headers: ^4.8.0 => 4.8.0 
    gatsby-remark-images: ^5.8.0 => 5.8.0 
    gatsby-remark-unwrap-images: ^1.0.2 => 1.0.2 
    gatsby-source-filesystem: ^3.11.0 => 3.11.0 
    gatsby-transformer-sharp: ^3.11.0 => 3.11.0 
  npmGlobalPackages:
    gatsby-cli: 3.11.0
```
```


### Config Flags

_No response_

**Comment by matthewkwong2** [comment] 2021-08-05 06:22
Similar issue on my project. This is a hard failure in the production build. Yet, the development build doesn;t seem to be affected.
https://github.com/matthewkwong2/resume-gatsby/tree/next

A bit more details
```
Error parsing bundle asset "C:\Users\kmw111\Documents\project\resume-gatsby\public\polyfill-0fd01837a62087bcf144.js": no such file
Error parsing bundle asset "C:\Users\kmw111\Documents\project\resume-gatsby\public\app-c6f931d9df56eae7c132.js": no such file
Error parsing bundle asset "C:\Users\kmw111\Documents\project\resume-gatsby\public\webpack-runtime-883fcbcd518ee8384a9c.js": no such file

No bundles were parsed. Analyzer will show only original module sizes from stats file.

Webpack Bundle Analyzer is started at http://127.0.0.1:3001
Use Ctrl+C to close it
failed Building production JavaScript and CSS bundles - 31.412s

 ERROR #98123  WEBPACK

Generating JavaScript bundles failed

Unexpected token (12:223)

File: .cache\production-app.js:12:223
```

Gatsby Info
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 7.14.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.5
  Browsers:
    Chrome: 92.0.4515.131
    Edge: Spartan (44.19041.423.0), Chromium (92.0.902.62)
  npmPackages:
    gatsby: ^3.11.0 => 3.11.0 
    gatsby-plugin-emotion: ^6.11.0 => 6.11.0 
    gatsby-plugin-image: ^1.11.0 => 1.11.0 
    gatsby-plugin-manifest: ^3.11.0 => 3.11.0 
    gatsby-plugin-offline: ^4.11.0 => 4.11.0 
    gatsby-plugin-react-helmet: ^4.11.0 => 4.11.0 
    gatsby-plugin-robots-txt: ^1.6.8 => 1.6.8 
    gatsby-plugin-root-import: ^2.0.6 => 2.0.6 
    gatsby-plugin-sharp: ^3.11.0 => 3.11.0 
    gatsby-plugin-sitemap: ^4.7.0 => 4.7.0 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.24 => 1.1.24 
    gatsby-source-filesystem: ^3.11.0 => 3.11.0 
    gatsby-transformer-sharp: ^3.11.0 => 3.11.0 
```

Flags
```
FAST_DEV: true,
PARALLEL_QUERY_RUNNING: true
PARALLEL_SOURCING: true
```
p.s. same error when no flags are used.

**Comment by LekoArts** [comment] 2021-08-05 06:36
I'm closing this in favor of https://github.com/gatsbyjs/gatsby/issues/32705 because you didn't provide a reproduction.

**Closed by LekoArts** 2021-08-05 06:36 UTC
Labels: type: bug
