### ISSUE TITLE
Page content loaded inside a 'gatsby-announcer' div

### ISSUE THREAD

**Issue by romarybintsev** [gatsbyjs/gatsby#23234] opened 2020-04-17 16:00 UTC
## Description

The project works perfectly fine in the development but after building and serving the project, the content of some pages is wrapped by a 'gatsby-announcer' div which has a 'position:absolute;top:0;width:1px;height:1px;padding:0;overflow:hidden;clip:rect(0, 0, 0, 0);white-space:nowrap;border:0' style and therefore the content basically becomes hidden. The problem is that the page loads, I can see it flicker for a split second but very quickly disappears so I'm guessing it has something to do with some gatsby script. 

### Steps to reproduce

Unfortunately I'm not sure how to reproduce the problem myself. For some reason, only my old pages are affected. When creating new pages, they seem to work fine. 

### Expected result

The content to load normally.

### Actual result

The content gets wrapped by a 'small' div.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  Binaries:
    Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.12.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.17
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.19.28 => 2.20.23
    gatsby-image: ^2.2.42 => 2.3.3
    gatsby-plugin-facebook-pixel: ^1.0.3 => 1.0.3
    gatsby-plugin-firebase: ^0.2.0-beta.4 => 0.2.0-beta.4
    gatsby-plugin-manifest: ^2.2.42 => 2.3.4
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.6
    gatsby-plugin-postcss: ^2.1.20 => 2.2.2
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^2.4.5 => 2.5.5
    gatsby-source-filesystem: ^2.1.48 => 2.2.3
    gatsby-transformer-sharp: ^2.3.16 => 2.4.5

**Comment by Js-Brecht** [comment] 2020-04-17 19:17
That's really bizarre!  Definitely something weird going on.  Are you able to share the repo?

**Comment by romarybintsev** [comment] 2020-04-17 19:23
I figured it out. Changing wrapRootElement to wrapPageElement fixed it. This is what I have now in gatsby-browser.js 
`export const wrapPageElement = ({ element }) => {
  return (
    <Provider store={store}>
        <NavBar />
            {element}
        <Footer />
    </Provider>
  )
}`. Still unsure why the behavior changed since everything worked perfectly fine before.

**Comment by Js-Brecht** [comment] 2020-04-17 20:24
SOP is to put UI elements (like `<NavBar />` and `<Footer />` in `wrapPageElement`, and put global state components (like `<Provider>`) in `wrapRootElement`.

Basically, the root element is where the Router and other state management goes in Gatsby, so its kind of the orchestrator for the everything.  The page element is what receives/displays the actual content.

It still seems strange that your content would wind up wrapped by the route announcer.  The route announcer should have been put between your site's `<NavBar>` and `<Footer>` elements, but **next to** the rest of your page content inside of the `gatsby-focus-wrapper`, not **wrapping** your page content.

The route announcer doesn't even accept `children`, so there shouldn't be any way for anything to get inside it 🤔

**Comment by Js-Brecht** [comment] 2020-04-18 06:38
@romarybintsev out of curiosity, were you using `wrapRootElement` in both `gatsby-browser` and `gatsby-ssr`, or just `gatsby-browser`?

**Comment by LekoArts** [comment] 2020-04-20 09:24
Thank you for opening this!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2020-04-20 09:24 UTC
Labels: type: bug

**Comment by lucianokrebs** [comment] 2020-06-22 17:07
Same issue here, not able to fix. Even changing the wrapRootElement to wrapPageElement, the problem persists.

![image](https://user-images.githubusercontent.com/46528605/85315589-b9484400-b491-11ea-8575-ec71b8e78f2b.png)

**Comment by lucianokrebs** [comment] 2020-06-22 17:08
@Js-Brecht do you know what is the best way to fix this? If I remove the css of the `#gatsby-announcer` DOM element, the site return to work

**Comment by Js-Brecht** [comment] 2020-06-22 17:09
Can you share a reproduction of the issue?

**Comment by lucianokrebs** [comment] 2020-06-22 17:09
https://provi-site-dev.firebaseapp.com/

**Comment by Js-Brecht** [comment] 2020-06-22 17:09
Need to see the code

**Comment by lucianokrebs** [comment] 2020-06-22 17:12
```
gatsby info --clipboard

  System:
    OS: macOS 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
    Yarn: 1.17.0 - /usr/local/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.106
    Safari: 13.1.1

```

**Comment by lucianokrebs** [comment] 2020-06-22 17:12
```
gatsby-browser.js


import React from 'react'
import { ToastComponent } from '@provi/provi-components'
import { TemplateProvider } from './src/components/template/provider'
import ErrorBoundary from './src/components/error-boundary'
import 'react-toastify/dist/ReactToastify.css'

export const wrapRootElement = ({ element }) => (
  <ErrorBoundary>
    <TemplateProvider>
      <ToastComponent />
      {element}
    </TemplateProvider>
  </ErrorBoundary>
)
```

**Comment by lucianokrebs** [comment] 2020-06-22 17:13
```
package.json

  "name": "provi-website",
  "private": true,
  "description": "Site Provi",
  "version": "0.1.0",
  "author": "@provicapital",
  "dependencies": {
    "@material-ui/core": "^4.10.2",
    "@material-ui/icons": "^4.9.1",
    "@material-ui/lab": "^4.0.0-alpha.56",
    "@material-ui/styles": "^4.9.0",
    "@provi/provi-components": "1.1.50",
    "@sentry/browser": "^5.12.4",
    "@yazanaabed/react-tabs": "^2.3.6",
    "axios": "^0.19.2",
    "cross-env": "^7.0.2",
    "formik": "^2.1.4",
    "fuse.js": "^3.4.6",
    "gatsby": "^2.23.3",
    "gatsby-image": "^2.2.39",
    "gatsby-plugin-google-analytics": "^2.2.2",
    "gatsby-plugin-google-tagmanager": "^2.1.26",
    "gatsby-plugin-manifest": "^2.2.47",
    "gatsby-plugin-material-ui": "^2.1.6",
    "gatsby-plugin-offline": "^3.2.11",
    "gatsby-plugin-react-helmet": "^3.1.21",
    "gatsby-plugin-sentry": "^1.0.1",
    "gatsby-plugin-sharp": "^2.4.3",
    "gatsby-source-filesystem": "^2.1.48",
    "gatsby-transformer-sharp": "^2.3.13",
    "prop-types": "^15.7.2",
    "pure-react-carousel": "^1.25.2",
    "react": "^16.12.0",
    "react-card-flip": "^1.0.10",
    "react-dom": "^16.12.0",
    "react-helmet": "^5.2.1",
    "react-input-mask": "^2.0.4",
    "react-player": "^1.15.3",
    "react-scroll-parallax": "^2.3.1",
    "react-select": "^3.1.0",
    "react-tabs": "^3.1.0",
    "react-toastify": "^5.5.0",
    "styled-components": "^5.0.0",
    "yup": "^0.28.1"
  },
  "devDependencies": {
    "babel-plugin-styled-components": "^1.10.7",
    "gatsby-plugin-styled-components": "^3.1.19",
    "prettier": "^1.19.1"
  },

```

**Comment by lucianokrebs** [comment] 2020-06-22 17:14
```
gatsby-config.js

module.exports = {
  siteMetadata: {
    title: `Crédito que transforma`,
    description: `Acreditamos que as pessoas podem fazer coisas incríveis se tiverem o incentivo certo no momento correto. Alavanque sua carreira. Conte com a Provi.`,
    author: `@provicapital`,
  },
  plugins: [
    `gatsby-plugin-offline`,
    'gatsby-plugin-material-ui',
    {
      resolve: `gatsby-plugin-google-analytics`,
      options: {
        trackingId: 'GTM-KK6SKR4',
      },
    },
    {
      resolve: 'gatsby-plugin-google-tagmanager',
      options: {
        id: 'GTM-KK6SKR4',
        includeInDevelopment: false,
        defaultDataLayer: { platform: 'gatsby' },
      },
    },
    {
      resolve: 'gatsby-plugin-sentry',
      options: {
        dsn: '',
        environment: process.env.NODE_ENV,
      },
    },
    {
      resolve: `gatsby-plugin-styled-components`,
      options: {
        displayName: true,
      },
    },
    'gatsby-plugin-react-helmet',
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: 'Provi',
        short_name: 'Provi',
        icon: 'src/assets/images/favicon.png',
      },
    }
  ],
}
```

**Comment by lucianokrebs** [comment] 2020-06-22 17:15
@Js-Brecht do you need anything else? It's a private repo, sorry for not be able to share

**Comment by Js-Brecht** [comment] 2020-06-22 17:21
For testing, can you try removing `ErrorBoundary` and `ToastComponent`?

Is there anything in `gatsby-ssr`?

What does `TemplateProvider` do?

I understand not being able to share the repository; that’s pretty common.  However, a simplified reproduction helps a great with troubleshooting.  Sometimes, just the act of recreating the issue as simply as possible is enough to identify the problem.  I have never had this issue, so I’m unable to recreate it myself, and seeing all of the code that is causing the effect is necessary to track down the root cause.  There’s a lot of moving parts to consider

**Comment by lucianokrebs** [comment] 2020-06-22 17:23
```
gatsby-ssr.js
```
Is empty 
![image](https://user-images.githubusercontent.com/46528605/85316851-d716a880-b493-11ea-9842-9de1b85eac47.png)

**Comment by lucianokrebs** [comment] 2020-06-22 17:26
```
Template Provider:

![image](https://user-images.githubusercontent.com/46528605/85317184-599f6800-b494-11ea-85b7-eaf1c588fc3e.png)

```

**Comment by Js-Brecht** [comment] 2020-06-22 17:58
It works for me?  Did something change?

![image](https://user-images.githubusercontent.com/1935258/85319879-ec70e000-b45d-11ea-947c-025835485d47.png)

**Comment by lucianokrebs** [comment] 2020-06-22 18:31
Hahahah strange stuff. Seems that the problem was the order of the `<ToastComponent />`. Move it to outside, after the `children` coming from the `wrapRootElement` fixed the issue @Js-Brecht

**Comment by lucianokrebs** [comment] 2020-06-22 18:32
Working implementation:

`gatsby-browser`
![image](https://user-images.githubusercontent.com/46528605/85322923-7d1ae080-b49d-11ea-919d-53587eb63835.png)


`TemplateProvider`

![image](https://user-images.githubusercontent.com/46528605/85322985-9ae84580-b49d-11ea-8b31-a1f191c51df4.png)

**Comment by lucianokrebs** [comment] 2020-06-22 18:35
And the difference (don't know exactly why) is the content of the builded static site. Now, it is outside of the `#gatsby-annoucer div`

![image](https://user-images.githubusercontent.com/46528605/85323180-f1558400-b49d-11ea-91ff-9b2d353be8c3.png)

**Comment by Js-Brecht** [comment] 2020-06-22 18:52
It's probably a conflict between SSR and hydration in the client.  It may have worked correctly if you had put the `<ToastComponent />` in `wrapPageElement`, and kept everything else in `wrapRootElement`.

Putting `<ToastComponent />` inside of `<TemplateProvider />` actually changes how it is called in the transpiled code.  What would help is seeing a transpiled version of the React tree, but getting that is not a trivial task, especially because it would be important to see the React tree that is generated during SSR, too.

I think as a general rule of thumb, stuff in `wrapRootElement` should not change the DOM.
