### ISSUE TITLE
lmdb version differences between gatsby and @parcel/cache causes yarn install to error

### ISSUE THREAD

**Issue by offirgolan** [gatsbyjs/gatsby#36064] opened 2022-07-05 18:44 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

`@parcel/cache` v2.6.0 has a dependency on [`lmdb@2.3.10`](https://github.com/parcel-bundler/parcel/blob/v2.6.0/packages/core/cache/package.json#L30) which clashes with gatsby's required version `2.5.2`. 

This was updated in `@parcel/cache` v2.6.1. The current workaround is to set a yarn resolution for `@parcel/core` and `@parcel/cache`.

### Reproduction Link

N/A

### Steps to Reproduce

Upgraded app to latest gatsby version (4.17.2)

### Expected Result

Running `yarn` should succeed. 

### Actual Result

Running `yarn` errors:

```
error An unexpected error occurred: "ENOENT: no such file or directory, open 'yarn-cache/v6/npm-lmdb-win32-x64-2.3.10-bff73d12d94084343c569b16069d8d38626eb2d6-integrity/node_modules/lmdb-win32-x64/.yarn-metadata.json'".
```

### Environment

```shell
System:
    OS: macOS 12.4
    CPU: (10) x64 Apple M1 Pro
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0
    Yarn: 1.22.19
    npm: 8.1.0
  Languages:
    Python: 3.10.4
  Browsers:
    Chrome: 103.0.5060.53
    Firefox: 102.0
    Safari: 15.5
```

**Comment by LekoArts** [comment] 2022-07-06 05:15
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2022-07-14 11:34
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2022-07-14 11:34 UTC
Labels: type: bug, status: needs reproduction
