### ISSUE TITLE
storybook integration not working (core-js problems?)

### ISSUE THREAD

**Issue by isokissa** [gatsbyjs/gatsby#26873] opened 2020-09-12 16:56 UTC
## Description

Not able to run storybook with gatsby project (core-js problems?)

### Steps to reproduce

I followed the steps from https://www.gatsbyjs.com/docs/visual-testing-with-storybook/ and ran: 

    npm run storybook

### Expected result

I guess the storybook UI should start. 

### Actual result

I am getting a lot of error messages similar to this: 

    ERROR in ./.storybook/preview.js-generated-config-entry.js
    Module not found: Error: Can't resolve 'core-js/modules/es.array.filter' in '/home/papa/Work/games/alleswisser/.storybook' 

And eventually, last two lines before getting stuck: 

    WARN Broken build, fix the error above.
    WARN You may need to refresh the browser.

### Environment

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Pentium(R) CPU 4405U @ 2.10GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 10.19.0 - /usr/bin/node
    npm: 6.14.8 - /usr/local/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Firefox: 80.0.1
  npmPackages:
    gatsby: ^2.24.57 => 2.24.57 
  npmGlobalPackages:
    gatsby-cli: 2.12.95

**Comment by pfftdammitchris** [comment] 2020-09-13 16:19
Confirmed two projects with gatsby and storybook.
![image](https://user-images.githubusercontent.com/20717348/93023164-eba1a300-f5a1-11ea-99d3-01ce3ef4f85a.png)

Here's some more context:

`main.js` specific to gatsby for storybook:

```js
const path = require('path')
const SRC_PATH = path.join(__dirname, '../src')

module.exports = {
  stories: ['../src/components/Navbar/Navbar.stories.tsx'],
  // stories: ['../src/**/*.stories.mdx', '../src/**/Navbar.stories.@(ts|tsx)'],
  addons: ['@storybook/addon-links', '@storybook/addon-essentials'],
  webpackFinal: async (config) => {
    config.module.rules[0].exclude = [/node_modules\/(?!(gatsby)\/)/]
    config.module.rules[0].use[0].options.plugins.push(
      require.resolve('babel-plugin-remove-graphql-queries'),
    ),
      config.resolve.modules.push(SRC_PATH)
    return config
  },
  typescript: {
    check: false,
    checkOptions: {},
    reactDocgen: 'none',
  },
}
```

**Comment by sidharthachatterjee** [comment] 2020-09-14 11:00
@isokissa Have you tried using the Storybook recipe by any chance? 

Run `gatsby recipes` and then select Storybook TypeScript (since it appears that you have a `tsx` file)

Let me know if that works! Thank you

**Comment by vladar** [comment] 2020-09-14 12:38
@isokissa Can you share your project? I've just followed all the steps from https://www.gatsbyjs.com/docs/visual-testing-with-storybook/ and got the storybook working without any surprises. FWIW here is my project: https://github.com/vladar/gh-26873

From your error, I see you have `./.storybook/preview.js-generated-config-entry.js` which sounds suspicious as I don't see any mentions of this file in docs.

**Comment by vladar** [comment] 2020-09-14 12:42
@pfftdammitchris 

You are missing babel preset in your `main.js`. If I add those lines to your `main.js` it works as expected:

```diff
const path = require('path')
const SRC_PATH = path.join(__dirname, '../src')

module.exports = {
  stories: ['../src/components/Navbar/Navbar.stories.tsx'],
  // stories: ['../src/**/*.stories.mdx', '../src/**/Navbar.stories.@(ts|tsx)'],
  addons: ['@storybook/addon-links', '@storybook/addon-essentials'],
  webpackFinal: async (config) => {
    config.module.rules[0].exclude = [/node_modules\/(?!(gatsby)\/)/]
    config.module.rules[0].use[0].options.plugins.push(
      require.resolve('babel-plugin-remove-graphql-queries'),
    ),
      config.resolve.modules.push(SRC_PATH)
+   config.module.rules[0].use[0].options.presets = [
+     require.resolve("@babel/preset-react"),
+     require.resolve("@babel/preset-env"),
+   ]
    return config
  },
  typescript: {
    check: false,
    checkOptions: {},
    reactDocgen: 'none',
  },
}
```

So this is not related to the original issue.

**Comment by isokissa** [comment] 2020-09-14 17:58
@sidharthachatterjee, would the recipe work on existing JavaScript based project? I am not using TypeScript

**Comment by isokissa** [comment] 2020-09-14 18:20
@vladar, I refreshed all dependencies and ran the `npx -p @storybook/cli sb init`, and now it had different effects to project than before. For example the `.storybook/preview.js` seem to be ready to use, it seem to be already made for gatsby: 

```JavaScript
import { action } from "@storybook/addon-actions"

// Gatsby's Link overrides:
// Gatsby Link calls the `enqueue` & `hovering` methods on the global variable ___loader.
// This global object isn't set in storybook context, requiring you to override it to empty functions (no-op),
// so Gatsby Link doesn't throw any errors.
global.___loader = {
  enqueue: () => {},
  hovering: () => {},
}
// This global variable is prevents the "__BASE_PATH__ is not defined" error inside Storybook.
global.__BASE_PATH__ = "/"

// Navigating through a gatsby app using gatsby-link or any other gatsby component will use the `___navigate` method.
// In Storybook it makes more sense to log an action than doing an actual navigate. Checkout the actions addon docs for more info: https://github.com/storybookjs/storybook/tree/master/addons/actions.

window.___navigate = pathname => {
  action("NavigateTo:")(pathname)
}

export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
}
```

And now the `npm start storybook` starts nicely, so it must be something to deal with versions of dependencies in my package.json. 

I think the issue can be closed, from my point of view, thank you all for the good support!

**Comment by vladar** [comment] 2020-09-15 08:08
Great! I am closing this but don't hesitate to open a new issue if you encounter other problems.

Thanks for using Gatsby 💜

**Closed by vladar** 2020-09-15 08:08 UTC
Labels: status: needs reproduction, type: bug
