### ISSUE TITLE
Chrome tab crashes when code tag is highlighted on documentation website

### ISSUE THREAD

**Issue by South-Paw** [gatsbyjs/gatsby#17291] opened 2019-09-01 09:11 UTC
## Description

Using https://www.gatsbyjs.org/packages/gatsby-image/ documentation and highlighted a small  snippet in a code tag but the browser tab crashes when trying to highlight the first character.

See: https://i.imgur.com/o7XMz3l.gifv

### Steps to reproduce

Visit page and highlight the same code block - also happens on the fixed code tag as well (above fluid).

### Expected result

It shouldn't crash.

### Actual result

It crashes the Chrome browser tab (see gif).

### Environment

Google Chrome Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by antkahn** [comment] 2019-09-13 09:42
Hello!

It happened to me on https://www.gatsbyjs.org/packages/@gatsby-contrib/gatsby-plugin-elasticlunr-search/ on the code block `{ expand: true }`
And also on https://www.gatsbyjs.org/contributing/setting-up-your-local-dev-environment/ on the code block `gatsby-dev --packages gatsby-link`

It seems to depend on the screen resolution.

Cheers!

**Comment by LekoArts** [comment] 2020-05-25 12:15
Can't reproduce this anymore so I'll close this for now.

**Closed by LekoArts** 2020-05-25 12:15 UTC
Labels: status: confirmed, type: bug, type: documentation

**Comment by South-Paw** [comment] 2020-05-25 20:52
👍 It doesn't seem to be crashing anymore for me either.
