### ISSUE TITLE
gatsby-source-wordpress: connect ECONNREFUSED 127.0.0.1:8080

### ISSUE THREAD

**Issue by sunnylam13** [gatsbyjs/gatsby#30294] opened 2021-01-26 03:27 UTC
The plugin is constantly giving me this error even after opening the ports in the firewall, when using `gatsby develop`.

```
info We're shipping new features! For final testing, we're rolling them out first to a small % of Gatsby users
and your site was automatically chosen as one of them. With your help, we'll then release them to everyone in the next minor release.

We greatly appreciate your help testing the change. Please report any feedback good or bad in the umbrella issue. If you do encounter problems, please disable the flag by setting it to false in your gatsby-config.js like:

flags: {
  THE_FLAG: false
}

The following flags were automatically enabled on your site:
- DEV_SSR · (Umbrella Issue (​https://gatsby.dev/dev-ssr-feedback​)) · Server Side Render (SSR) pages on full reloads during develop. Helps you detect SSR bugs and fix them without needing to do full builds.

success open and validate gatsby-configs - 0.140s
success load plugins - 2.363s
success onPreInit - 0.035s
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's no stale data.
success initialize cache - 0.089s
success copy gatsby files - 0.411s
success onPreBootstrap - 0.216s
success  gatsby-source-wordpress  ensuring plugin requirements are met - 5.228s
⠀
info  gatsby-source-wordpress

        This is either your first build or the cache was cleared.
        Please wait while your WordPress data is synced to your Gatsby cache.

        Maybe now's a good time to get up and stretch? :D

success  gatsby-source-wordpress  ingest WPGraphQL schema - 3.569s
success createSchemaCustomization - 8.886s
success  gatsby-source-wordpress  fetch root fields - 0.857s
success  gatsby-source-wordpress  Menu - 0.883s - fetched 1
success  gatsby-source-wordpress  MenuItem - 0.911s - fetched 5
success  gatsby-source-wordpress  PostFormat - 0.924s - fetched 9
success  gatsby-source-wordpress  ContentType - 1.028s - fetched 3
success  gatsby-source-wordpress  Comment - 1.069s - fetched 30
success  gatsby-source-wordpress  Page - 1.167s - fetched 21
success  gatsby-source-wordpress  Tag - 1.249s - fetched 51
success  gatsby-source-wordpress  UserRole - 1.262s - fetched 0
success  gatsby-source-wordpress  Taxonomy - 1.373s - fetched 3
success  gatsby-source-wordpress  User - 1.383s - fetched 1
success  gatsby-source-wordpress  Category - 1.615s - fetched 66
success  gatsby-source-wordpress  Post - 1.788s - fetched 49
error RequestError: connect ECONNREFUSED 127.0.0.1:8080
    at ClientRequest.<anonymous> (Y:\Sync\Programming Projects\gatsbyjs\sunny_site_gatsby_010621_1\node_modules\gatsby-source-wordpress-experimental\node_modules\got\dist\source\core\index.js:953:111)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (Y:\Sync\Programming Projects\gatsbyjs\sunny_site_gatsby_010621_1\node_modules\gatsby-source-wordpress-experimental\node_modules\@szmarczak\http-timer\dist\source\index.js:39:20)
    at Socket.socketErrorListener (_http_client.js:469:9)
    at Socket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16) {
  code: 'ECONNREFUSED',
  timings: {
    start: 1611631082872,
    socket: 1611631082873,
    lookup: 1611631082887,
    connect: undefined,
    secureConnect: undefined,
    upload: undefined,
    response: undefined,
    end: undefined,
    error: 1611631082889,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 14,
      tcp: undefined,
      tls: undefined,
      request: undefined,
      firstByte: undefined,
      download: undefined,
      total: 17
    }
  }
}
 [===========================---] 16/18 7.6 s 2 /s 88% Downloading remote filesY:\Sync\Programming Projects\gatsbyjs\sunny_site_gatsby_010621_1\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

Error: EPERM: operation not permitted, lstat 'Y:\Sync\Programming Projects\gatsbyjs\sunny_site_gatsby_010621_1\.cache\caches\gatsby-source-wordpress-experimental\tmp-b8554c12aeb7e7f19214013dc9802a68.png'
    at Object.lstatSync (fs.js:1077:3)
    at Object.lstatSync (Y:\Sync\Programming Projects\gatsbyjs\sunny_site_gatsby_010621_1\node_modules\graceful-fs\polyfills.js:308:16)
    at Object.removeSync (Y:\Sync\Programming Projects\gatsbyjs\sunny_site_gatsby_010621_1\node_modules\gatsby-source-wordpress-experimental\node_modules\fs-extra\lib\remove\rimraf.js:228:18)
    at Request.<anonymous> (Y:\Sync\Programming Projects\gatsbyjs\sunny_site_gatsby_010621_1\node_modules\gatsby-source-wordpress-experimental\src\steps\source-nodes\create-nodes\create-remote-file-node\index.js:203:10)
    at Request.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4048,
  syscall: 'lstat',
  code: 'EPERM',
  path: 'Y:\\Sync\\Programming Projects\\gatsbyjs\\sunny_site_gatsby_010621_1\\.cache\\caches\\gatsby-source-wordpress-experimental\\tmp-b8554c12aeb7e7f19214013dc9802a68.png'
}
```

Only `gatsby-source-graphql` is working to pull data.  

So I had to switch to only using it.

However I can't access ACF/Advanced Custom Fields or use methods to access it without `gatsby-source-wordpress-experimental`.

**Comment by LekoArts** [comment] 2021-03-26 08:31
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-03-26 08:31 UTC
Labels: status: needs reproduction, topic: WordPress
