### ISSUE TITLE
'gatsby' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by consultwithmike** [gatsbyjs/gatsby#2509] opened 2017-10-18 12:57 UTC
**Operating System:** Windows 10 Pro
**Version:** 10.0.15063 Build 15063
**Command Prompt:** ConEmu
**Startup Tasks:**

    set PATH=%ConEmuBaseDir%\Scripts;%PATH%
    "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\VsDevCmd.bat"
    "C:\Program Files\nodejs\nodevars.bat"

After installing, and re-installing (`npm i gatsby-cli@latest -g`), I still can't execute `gatsby` commands outside of the `Node.js command prompt` on my box.

What did I do wrong?

**Comment by twhiteaker** [comment] 2018-04-10 18:18
Same OS and symptom here. I can run gatsby from the node.js prompt but not the cmd prompt or PowerShell for example.

**Comment by thebetterjort** [comment] 2018-04-26 00:45
Same issue here.

**Comment by pieh** [comment] 2018-04-26 09:37
Can you use any other npm global packages? Can you check if after using `echo %PATH%` in command prompt you see there path to npm? (should be something like `C:\Users\<username>\AppData\Roaming\npm`

**Comment by twhiteaker** [comment] 2018-04-26 18:05
The path to npm is there in both command windows if I run as standard user. But gatsby and seemingly most other node applications are blocked by group policy unless I run the prompt as admin.  As admin, the path to npm shows up in the node prompt (pointing to my users\admin-account\... folder), but not in the Windows command prompt.

**Comment by pieh** [comment] 2018-04-26 20:06
I'm not sure if this something gatsby can fix? This seem more of `npm` issue here especially that this problem exists in other node applications :/

**Comment by twhiteaker** [comment] 2018-04-26 20:31
I just tried with Vue and I got the same behavior.  

Editing my admin account's path variable to include the npm path solved the problem.  

1. Click Start, then type "environment" (without quotes).
2. Click **Edit the system environment variables**.
3. Enter admin credentials.
4. In the user variables for my-admin-account, select Path and click Edit.
5. Click New, and enter C:\Users\<your admin username>\AppData\Roaming\npm.
6. Confirm and close all dialogs.
7. Restart the Windows command prompt as admin.  Gatsby should work now.

Note that I clicked to edit system variables in step 2 so that I would be prompted for my admin creds.  If the OP doesn't have to use an admin account, then he can click **Edit environment variables for your account** instead.

For me the issue is resolved. And thanks @pieh for that tip about the npm path, which has resolved my other similar node issues as well!  Perhaps @consultwithmike could comment on whether this solution works for him.  If so, it is an npm/node issue and not in Gatsby's purview IMO as well.

**Comment by pieh** [comment] 2018-04-26 21:05
I'll close this as this issue is not really gatsby related.

**Closed by pieh** 2018-04-26 21:05 UTC
Labels: 🏷 type: question or discussion

**Comment by oluwadamilola** [comment] 2020-02-28 13:05
This issue is not Gatsby related.

**Comment by bobgravity1** [comment] 2021-09-13 14:23
it is 100% windows 10 and gatsby related. so closing this is silly

**Comment by Daycross** [comment] 2022-05-12 20:57
> I just tried with Vue and I got the same behavior.
> 
> Editing my admin account's path variable to include the npm path solved the problem.
> 
>     1. Click Start, then type "environment" (without quotes).
> 
>     2. Click **Edit the system environment variables**.
> 
>     3. Enter admin credentials.
> 
>     4. In the user variables for my-admin-account, select Path and click Edit.
> 
>     5. Click New, and enter C:\Users<your admin username>\AppData\Roaming\npm.
> 
>     6. Confirm and close all dialogs.
> 
>     7. Restart the Windows command prompt as admin.  Gatsby should work now.
> 
> 
> Note that I clicked to edit system variables in step 2 so that I would be prompted for my admin creds. If the OP doesn't have to use an admin account, then he can click **Edit environment variables for your account** instead.
> 
> For me the issue is resolved. And thanks @pieh for that tip about the npm path, which has resolved my other similar node issues as well! Perhaps @consultwithmike could comment on whether this solution works for him. If so, it is an npm/node issue and not in Gatsby's purview IMO as well.

Thanks, it's solved to me <3
