### ISSUE TITLE
"Error: The result of this StaticQuery could not be fetched." In new template project

### ISSUE THREAD

**Issue by ZPanic0** [gatsbyjs/gatsby#26798] opened 2020-09-06 05:55 UTC
## Description

Building and serving a deploy of the 'gatsby-starter-default' project throws several errors regarding fetching StaticQuery.
`Error: The result of this StaticQuery could not be fetched.`

### Steps to reproduce

- `gatsby new (left the name default)`
- `gatsby-starter-default`
- `cd my-gatsby-project`
- `npm i`
- `gatsby build`
- `gatsby serve`
- Open page on given url and open console

The errors are also emitted again on refresh.

### Expected result

No errors should be emitted in the console.

### Actual result

Three StaticQuery fetch errors post to the console. The purple space man also remains low resolution.

### Environment

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Binaries:
    Node: 14.9.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.5
  Browsers:
    Chrome: 85.0.4183.83
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    gatsby: ^2.24.50 => 2.24.53 
    gatsby-image: ^2.4.16 => 2.4.16 
    gatsby-plugin-manifest: ^2.4.24 => 2.4.27 
    gatsby-plugin-offline: ^3.2.24 => 3.2.26 
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10 
    gatsby-plugin-sharp: ^2.6.28 => 2.6.31 
    gatsby-source-filesystem: ^2.3.25 => 2.3.27 
    gatsby-transformer-sharp: ^2.5.13 => 2.5.14 
  npmGlobalPackages:
    gatsby-cli: 2.12.91

I have also searched around other issues, but they always seem to have some moving part to consider that this does not (Netlify, for example).

I have tried
- Running `gatsby clean`, deleting node_modules, running `npm i`, rebuilding and reserving.
- Removing every gatsby package except gatsby itself.
- Running `npm update` and retrying the above.

**Comment by pvdz** [comment] 2020-09-08 09:38
Hi @ZPanic0! Thanks for your report. I've followed your steps but was unable to reproduce this in chrome nor firefox in linux. I'm going to ask somebody on Windows to verify this.

**Comment by pvdz** [comment] 2020-09-08 09:52
Apparently it works on Windows machines when we tried.

But the error message is not new. For example, https://github.com/gatsbyjs/gatsby/issues/23761

Might there be something in your environment that is changing the behavior from the default?

**Comment by ZPanic0** [comment] 2020-09-08 12:31
If there is, I don't know what. Could you tell me how to check?

I will stand up a vm today and try again inside that as well.

**Comment by ZPanic0** [comment] 2020-09-08 14:33
I can confirm on a brand new vm installation of Windows 10 that I do not see this error on new projects.

**Comment by LekoArts** [comment] 2020-09-18 07:56
You could install the packages (same version as your current system) bit by bit to the VM.

**Comment by LekoArts** [comment] 2020-09-21 07:56
I'll close this as a duplicate of https://github.com/gatsbyjs/gatsby/issues/26563 - please give your reproduction there when possible. Thanks!

**Closed by LekoArts** 2020-09-21 07:56 UTC
Labels: status: needs reproduction, topic: StaticQuery, type: bug

**Comment by ZPanic0** [comment] 2020-09-21 17:33
There is already reproduction steps given here. We have already concluded
this particular issue is the result of something on my machine.

I also don’t use Vercel, so I can’t see how they are related.

**Comment by samarthvats9** [comment] 2022-02-08 17:27
Hey, I am new to this but I have tried this - npm install react@^16.8.0 react-dom@^16.8.0 and it's working now. Please let me know if this is of any help.
