### ISSUE TITLE
gatsby develop rename or delete a file ERROR #98123 WEBPACK 

### ISSUE THREAD

**Issue by Raggok** [gatsbyjs/gatsby#24845] opened 2020-06-06 17:06 UTC
## Description

If i rename or delete a file on /src/pages folder during **"gatsby develop"** and update any file got an "Failed to compile" on web browser and **ERROR #98123  WEBPACK** with the message **ENOENT: no such file or directory**  that is looking for the file that was deleted o renamed (the old name).

### Steps to reproduce

1. gatsby new hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world
2. cd hello-world
3. gatsby develop
4. create new file on /src/pages
5. delete or rename the file
6. update anything on index.js

the error will pop up on browser and console.

### Expected result

Ignore the delete file.

### Actual result

Error #98123  WEBPACK
Need to restart gatsby develop

**Comment by kutukmu** [comment] 2020-06-09 00:47
I am getting same error also. First I tried to remove .cache and it worked but then I started to get same error again

**Comment by pvdz** [comment] 2020-06-16 10:00
Can you confirm whether or not you are using WSL?

**Comment by Raggok** [comment] 2020-06-22 16:18
> Can you confirm whether or not you are using WSL?

Yes i have it installed.

**Comment by kaihaan** [comment] 2020-06-23 16:31
I've just had the same problem - has this been resolved?

**Comment by pvdz** [comment] 2020-06-23 21:07
I think this is a dupe of https://github.com/gatsbyjs/gatsby/issues/21982

Closing as such. Please see that issue for workarounds or reasons why this is a WSL problem.

Please re-open if you can reproduce this problem on a mac or linux machine.

**Closed by pvdz** 2020-06-23 21:07 UTC
Labels: topic: webpack/babel, type: bug
