### ISSUE TITLE
"contentTypeFilter" filter does not work from "gatsby-source-contentful"

### ISSUE THREAD

**Issue by joechoi-git** [gatsbyjs/gatsby#35867] opened 2022-06-07 14:31 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I have a gatsby-source-contentful version 7.14.0 installed.
"gatsby-source-contentful": "^7.14.0",

When trying to use this filter "contentTypeFilter" as documented from the readme, it doesn't seem to work. It does not reduce the size of the cache.
```
{
      resolve: "gatsby-source-contentful",
      options: {        
        contentTypeFilter: contentType => !contentType.sys.id.startsWith('page'),
      },
    },
```

Instead, it is throwing this warning.
```
warn Warning: there are unknown plugin options for "gatsby-source-contentful": contentTypeFilter
Please open an issue at https://ghub.io/gatsby-source-contentful if you believe this option is valid.
```

### Reproduction Link

N/A

### Steps to Reproduce

1. npm install gatsby-source-contentful@7.14.0 
2. In "gatsby-config.js", 
```
{
      resolve: "gatsby-source-contentful",
      options: {        
        contentTypeFilter: contentType => !contentType.sys.id.startsWith('page'),
      },
    },
```
3. gatsby clean
4. gatsby build

### Expected Result

The size of the ".cache/data" folder should be smaller to reflect the filter.

### Actual Result

The filter didn't apply.

### Environment

```shell
Node.js 16.x
NPM 8.x
Install the latest versions of gatsby, contentful, and gatsby-source-contentful.
```

**Comment by LekoArts** [comment] 2022-06-07 15:42
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2022-06-21 04:46
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2022-06-21 04:46 UTC
Labels: type: bug, status: needs reproduction, topic: source-contentful, topic: source-plugins

**Comment by ivanteso** [comment] 2022-07-07 13:09
Hey @LekoArts, I'm experiencing this issue as well.
To be fair, the `contentTypes` are correctly filtered and generated, but the warning is there.

Here are my Gatsby dependencies:

```
    "gatsby": "^4.17.0",
    "gatsby-plugin-catch-links": "^4.17.0",
    "gatsby-plugin-exclude": "^1.0.2",
    "gatsby-plugin-feed": "^4.17.0",
    "gatsby-plugin-gatsby-cloud": "^4.15.0",
    "gatsby-plugin-image": "^2.15.1",
    "gatsby-plugin-launchdarkly": "^0.3.2",
    "gatsby-plugin-manifest": "^4.17.0",
    "gatsby-plugin-netlify": "^4.4.0",
    "gatsby-plugin-preconnect": "^1.3.0",
    "gatsby-plugin-react-helmet": "^5.16.0",
    "gatsby-plugin-remove-serviceworker": "^1.0.0",
    "gatsby-plugin-sharp": "^4.15.1",
    "gatsby-plugin-sitemap": "^5.16.0",
    "gatsby-plugin-styled-components": "^5.16.0",
    "gatsby-source-contentful": "^7.16.0",
    "gatsby-source-filesystem": "^4.17.0",
    "gatsby-source-graphql": "^4.17.0",
    "gatsby-source-greenhouse-job-board": "^1.0.4",
    "gatsby-transformer-json": "^4.17.0",
```
Below the messages I get from the plugin.

<img width="738" alt="Screenshot 2022-07-07 at 15 03 20" src="https://user-images.githubusercontent.com/35341793/177781168-eadc3a2c-46bc-4336-9135-f8ed943114e7.png">

<img width="513" alt="Screenshot 2022-07-07 at 15 03 28" src="https://user-images.githubusercontent.com/35341793/177781215-7574d049-b3ae-417e-be29-7713af2de9e5.png">

**Comment by zachmerrill** [comment] 2022-09-07 14:25
@ivanteso Same issue here. I get the same warning message however the filtering works correctly.

**Comment by bartveneman** [comment] 2023-01-10 12:19
I think it's fixed in https://github.com/gatsbyjs/gatsby/commit/56ace78708ef5f1d311cfe434bd0cc87558f0b29

**Comment by xavivars** [comment] 2023-01-10 12:47
My fault! When I introduced the functionality in https://github.com/gatsbyjs/gatsby/pull/35204, I totally forgot to update the validation, that's why the warning was being shown (but as @ivanteso mentioned, the filtering functionality was working, so it was just a false positive warning)
