### ISSUE TITLE
Extremely slow "run page queries" on last pages... (22k pages) exponentially increasing time as more pages are added

### ISSUE THREAD

**Issue by stevemarksd** [gatsbyjs/gatsby#30962] opened 2021-04-20 15:21 UTC
## Description

![image](https://user-images.githubusercontent.com/58653359/115421497-ea99b980-a1f3-11eb-873e-5fd83571bec8.png)

First 90% of the pages run very fast... but the last 10% they are super slow. Last 2% even slower.

I wonder what is going on.

I also have a lot of `warn Query takes too long:` on last queries.

My guess is that there is some lookup and on later pages the array is huge, therefore every lookup is slower as it reaches the end.

### Steps to reproduce

Add 22k pages.

### Expected result

Time should be the similar for each page query...

### Actual result

... time to run queries exponentially increase on later pages.

### Environment

```
  System:
    OS: Windows 10 10.0.19
    CPU: (16) x64 Intel(R) Core(TM) i7-107
  Binaries:
    Node: 14.15.5 - ~\AppData\Local\Temp\yarn---\node.CMD
    Yarn: 1.22.XX - ~\AppData\Local\Temp\yarn---\yarn.CMD
    npm: 7.X.X - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.X
  npmPackages:
    gatsby: 3.1.2 => 3.1.2 
    gatsby-image: 3.1.0 => 3.1.0 
    gatsby-plugin-catch-links: ^3.1.0 => 3.3.0 
    gatsby-plugin-emotion: ^6.1.0 => 6.3.0 
    gatsby-plugin-image: 1.1.2 => 1.1.2 
    gatsby-plugin-layout: ^2.1.0 => 2.3.0 
    gatsby-plugin-loadable-components-ssr: ^2.1.0 => 2.1.0 
    gatsby-plugin-manifest: ^3.1.0 => 3.3.0 
    gatsby-plugin-material-ui: 3.0.0 => 3.0.0 
    gatsby-plugin-netlify-cms: ^5.2.0 => 5.3.0 
    gatsby-plugin-react-helmet: ^4.1.0 => 4.3.0 
    gatsby-plugin-sharp: 3.1.2 => 3.1.2 
    gatsby-plugin-sitemap: ^3.1.0 => 3.3.0 
    gatsby-plugin-typescript: ^3.1.0 => 3.2.0 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.21 => 1.1.22 
    gatsby-remark-component: ^1.1.3 => 1.1.3 
    gatsby-remark-images: ^4.1.1 => 4.2.0 
    gatsby-remark-relative-images: ^2.0.2 => 2.0.2 
    gatsby-source-filesystem: ^3.1.0 => 3.3.0 
    gatsby-transformer-remark: ^4.0.0 => 4.0.0 
    gatsby-transformer-sharp: 3.1.0 => 3.1.0 
```

**Comment by LekoArts** [comment] 2021-04-21 07:55
Hi!

Thanks for the issue! As you might expect we'd need to have a [minimal reproduction][reproduction] as simply adding 22k pages to a project won't show this behavior (your reproduction steps). Our benchmarks run fine with 100k pages and each project/build is different.

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-05-03 10:09
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-05-03 10:09 UTC
Labels: status: needs reproduction, topic: scaling builds, type: bug
