### ISSUE TITLE
Webpack error after migartion from v2 to v3

### ISSUE THREAD

**Issue by giorgiPapava** [gatsbyjs/gatsby#32060] opened 2021-06-23 14:34 UTC
## Description
I'm trying to migrate big enterprise project from Gatsby v2 to v3. I'm using Flow.js for strong type support. I have followed instruction from [this article](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/). I have upgraded Gatsby and all plugins I have used to latest version. When I'm trying to run `gatsby develop` I end up with webpack errors.
`
### Steps to reproduce
Upgrade Gatsby and all of it's plugins of existing project to latest version. Run `gatsby develop`.

### Expected result

Start project as it should be without webpack errors.

### Actual result

Project could not start. Webpack errors. 
![image](https://user-images.githubusercontent.com/66740160/123115530-39acd680-d451-11eb-8416-a55feaa6608a.png)

### Environment

```
  System:
    OS: Linux 5.10 Manjaro Linux
    CPU: (6) x64 Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.1 - /tmp/yarn--1624458727802-0.2044491584164536/node
    Yarn: 1.22.10 - /tmp/yarn--1624458727802-0.2044491584164536/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm
  Languages:
    Python: 3.9.5 - /usr/bin/python
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0.1
  npmPackages:
    gatsby: ^3.7.2 => 3.8.0 
    gatsby-image: ^3.7.1 => 3.8.0 
    gatsby-plugin-create-client-paths: ^3.7.1 => 3.8.0 
    gatsby-plugin-env-variables: ^1.0.1 => 1.0.2 
    gatsby-plugin-facebook-pixel: ^1.0.8 => 1.0.8 
    gatsby-plugin-flow: ^2.8.0 => 2.8.0 
    gatsby-plugin-force-trailing-slashes: ^1.0.5 => 1.0.5 
    gatsby-plugin-google-analytics: ^3.7.1 => 3.8.0 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-google-tagmanager: ^3.7.1 => 3.8.0 
    gatsby-plugin-intl: ^0.3.3 => 0.3.3 
    gatsby-plugin-layout: ^2.7.1 => 2.8.0 
    gatsby-plugin-manifest: ^3.7.1 => 3.8.0 
    gatsby-plugin-material-ui: ^3.0.1 => 3.0.1 
    gatsby-plugin-modal-routing-3: ^3.0.0 => 3.0.0 
    gatsby-plugin-offline: ^4.7.1 => 4.8.0 
    gatsby-plugin-react-helmet: ^4.7.1 => 4.8.0 
    gatsby-plugin-root-import: ^2.0.5 => 2.0.6 
    gatsby-plugin-sentry: ^1.0.1 => 1.0.1 
    gatsby-plugin-sharp: ^3.7.1 => 3.8.0 
    gatsby-plugin-sitemap: ^4.3.1 => 4.4.0 
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.5 => 1.0.5 
    gatsby-source-filesystem: ^3.7.1 => 3.8.0 
    gatsby-transformer-sharp: ^3.7.1 => 3.8.0 

```

**Comment by LekoArts** [comment] 2021-06-23 14:47
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by giorgiPapava** [comment] 2021-06-24 07:10
Hi @LekoArts! Thanks for response! Since the project is enterprise I can't open source the whole project on GitHub. I will try to give minimal code base if that's necessary.

**Comment by LekoArts** [comment] 2021-07-06 09:55
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-07-06 09:55 UTC
Labels: status: needs reproduction, type: bug

**Comment by montemishkin** [comment] 2021-07-22 05:56
Howdy @LekoArts - I'm experiencing this as well. Created a reproduction-repo [here](https://github.com/montemishkin/repro-issue-gatsby-plugin-flow/commits/main). If I run `npm run develop` in that repo, webpack fails to build. 

To create that repo, here's what I did...

```sh
npm init gatsby
# go with all the defaults
npm add gatsby-plugin-flow
# add 'gatsby-plugin-flow' to gatsby-config.js
# add some flow types to src/pages/index.js
npm run develop
# webpack build fails due to parsing error from the flow types
```

For example, I added this [basic flow code](https://flow.org/en/docs/getting-started/) to `src/pages/index.js`
```js
// @flow
function square(n: number): number {
  return n * n;
}

square("2"); // Error!
```
Then I get the following webpack failure from running `npm run develop`
```
/Users/monte/mdv/my-gatsby-site/src/pages/index.js
  2:17  error  Parsing error: Unexpected token, expected "," (2:17)

✖ 1 problem (1 error, 0 warnings)
```


Let me know if I can provide more info :) And thanks in advance for the help!
