### ISSUE TITLE
Page loads as a blank white screen

### ISSUE THREAD

**Issue by market-south** [gatsbyjs/gatsby#36832] opened 2022-10-17 03:42 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Hi there, 

We are building a Gatsby site for a client. The site has 5 pages and it is in the middle of development. 

We started to have an issue with a particular page loading a white screen when navigating between pages with <Link> tag. Which then requires a manual refresh to load it properly. All the contents are loading as expected when directly visiting the URL or by refreshing the page after navigating from another page of the website.  But this issue doesn't occur on any other pages. 

Url: (https://pilot-brands-dev-git-master-nakedcreative.vercel.app/products)

### Reproduction Link

https://github.com/market-south/pilot-brands-dev

### Steps to Reproduce

Not working scenario:
1. Please Visit the home page [Home page](https://pilot-brands-dev-git-master-nakedcreative.vercel.app/)
2. Navigate to the contact page using the navigation
3. Navigate to the products page using the navigation (white screen) 
4. Refresh the products page after following steps 2 & 3 to load the products page (working)
...

Working scenario:
1. Directly visit the products page [Products](https://pilot-brands-dev-git-master-nakedcreative.vercel.app/products) 
2. Alternatively, navigate to the products page from the home page using navigation before navigating to any other page. (working) 
...

Sometimes getting a 404 error for the common.js file in the console (1 in 20 chances) when the page is blank. All other times no errors were logged in the console

### Expected Result

Expecting all the pages to load when navigating between the pages from anywhere on the website 

### Actual Result

The products page is loading a white screen when navigating from other pages which are linked using the <Link> tag of Gatsby.

### Environment

```shell
System:
    OS: Windows 10 10.0.19043
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
  Binaries:
    Node: 16.4.2 - C:\Program Files\nodejs\node.EXE
    npm: 7.18.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.5
  Browsers:
    Chrome: 106.0.5249.119
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.42)
  npmPackages:
    gatsby: ^4.20.0 => 4.20.0 
    gatsby-cli: ^4.22.0 => 4.22.0 
    gatsby-plugin-google-analytics: ^4.20.0 => 4.20.0 
    gatsby-plugin-image: ^2.20.0 => 2.20.0 
    gatsby-plugin-manifest: ^4.20.0 => 4.20.0 
    gatsby-plugin-mdx: ^3.20.0 => 3.20.0 
    gatsby-plugin-postcss: ^5.20.0 => 5.20.0 
    gatsby-plugin-sharp: ^4.20.0 => 4.20.0 
    gatsby-plugin-sitemap: ^5.20.0 => 5.20.0 
    gatsby-plugin-styled-components: ^5.20.0 => 5.20.0 
    gatsby-source-filesystem: ^4.20.0 => 4.20.0 
    gatsby-transformer-sharp: ^4.20.0 => 4.20.0 
  npmGlobalPackages:
    gatsby-cli: 4.20.0
```

**Comment by LekoArts** [comment] 2022-10-17 07:19
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2022-10-25 11:04
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2022-10-25 11:04 UTC
Labels: type: bug, status: needs reproduction
