### ISSUE TITLE
Migrating to V3 :(( `plugins.provide({process: 'process/browser'})` will mess up `process` in `ssr-develop-static-entry.js`: `process.cwd()` becomes `/` instead of real path

### ISSUE THREAD

**Issue by stevemarksd** [gatsbyjs/gatsby#30551] opened 2021-03-30 10:54 UTC
## Description

`plugins.provide({process: 'process/browser'})` will mess up `process` in `ssr-develop-static-entry.js`: `process.cwd()` becomes `/` instead of real path

### Steps to reproduce

I need vfile because of unified because of rehype react

![image](https://user-images.githubusercontent.com/58653359/112984767-34443680-9157-11eb-9532-e0fe110b29a9.png)

I need to add `plugins.provide({process: 'process/browser'})` to webpack config (from migration from 2 to 3 https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v2-to-v3/#process-is-not-defined )

![image](https://user-images.githubusercontent.com/58653359/112983942-2c37c700-9156-11eb-8fa4-567a450d3d14.png)

![image](https://user-images.githubusercontent.com/58653359/112977491-07d7ec80-914e-11eb-9b16-6693a12f7a9c.png)

Then in file

![image](https://user-images.githubusercontent.com/58653359/112977799-656c3900-914e-11eb-8ebc-1c51af4f1f6b.png)

Becomes `//public/webpack.stats.json` note the `//`

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

Also we seriously recommend a 4 year old (I think unmaintained project)? I even think might be a typo... not sure

![image](https://user-images.githubusercontent.com/58653359/112984059-4f627680-9156-11eb-96c8-fcc1b502f1c7.png)

### Expected result

I expect to dont break process when running in node.js... should only affect client side

### Actual result

Affects server side code
Also it doesnt really work.
![image](https://user-images.githubusercontent.com/58653359/112984401-bed86600-9156-11eb-8f5c-ef34ca0fa69a.png)

### Environment

```


  System:
    OS: Windows 10
    CPU: 
  Binaries:
    Node: 14.15.5 -
    Yarn: 1.22.10 - 
    npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.1
  Browsers:
    
  npmPackages:
    gatsby: 3.1.2 => 3.1.2 
    gatsby-image: 3.1.0 => 3.1.0 
    gatsby-plugin-catch-links: 3.1.0 => 3.1.0 
    gatsby-plugin-emotion: 6.1.0 => 6.1.0 
    gatsby-plugin-layout: 2.1.0 => 2.1.0 
    gatsby-plugin-loadable-components-ssr: 2.1.0 => 2.1.0 
    gatsby-plugin-manifest: 3.1.0 => 3.1.0 
    gatsby-plugin-material-ui: 3.0.0 => 3.0.0 
    gatsby-plugin-netlify-cms: 5.1.0 => 5.1.0 
    gatsby-plugin-react-helmet: 4.1.0 => 4.1.0 
    gatsby-plugin-sharp: 3.1.2 => 3.1.2 
    gatsby-plugin-sitemap: 3.1.0 => 3.1.0 
    gatsby-plugin-typescript: 3.1.0 => 3.1.0 
    gatsby-plugin-webpack-bundle-analyser-v2: 1.1.21 => 1.1.21 
    gatsby-react-router-scroll: 4.1.0 => 4.1.0 
    gatsby-remark-component: 1.1.3 => 1.1.3 
    gatsby-remark-images: 4.1.1 => 4.1.1 
    gatsby-remark-relative-images: 2.0.2 => 2.0.2 
    gatsby-source-filesystem: 3.1.0 => 3.1.0 
    gatsby-transformer-remark: 3.1.0 => 3.1.0 
    gatsby-transformer-sharp: 3.1.0 => 3.1.0 


```

**Comment by KyleAMathews** [comment] 2021-04-02 22:16
This should be fixed in https://github.com/gatsbyjs/gatsby/pull/30605

**Comment by LekoArts** [comment] 2021-04-06 08:48
As this is caused by an experimental feature behind a flag I'll close this in favor of https://github.com/gatsbyjs/gatsby/discussions/28138 - for flags/experiments please redirect your feedback there. Thanks!

You shouldn't only look at the last release (if it works there needs to be no update) but also the downloads (10 million a month).

**Closed by LekoArts** 2021-04-06 08:48 UTC
Labels: type: bug
