### ISSUE TITLE
Error: It appears like Gatsby is misconfigured. on Fresh installs

### ISSUE THREAD

**Issue by joshatoutthink** [gatsbyjs/gatsby#21220] opened 2020-02-05 16:15 UTC
## Description

I can no longer run gatsby develop without getting this error

```
Error: It appears like Gatsby is misconfigured. JSONStore is Gatsby internal development-only component and should never be used in production.

Unless your site has a complex or custom webpack/Gatsby configuration this is likely a bug in Gatsby. Please report this at https://github.com/gatsbyjs/gatsby/issues with steps to reproduce this error.
```

this happens on existing and new sites

I have deleted cache and re-downloaded the node_modules.
I have created new sites with just react, react-dom, and gatsby, but I still get this error.

 
### Steps to reproduce

1. `gatsby new test`
2. `cd test`
3. `gatsby develop`

### Expected result

The site should start up with no errors

### Actual result

I get an error 
```
Error: It appears like Gatsby is misconfigured. JSONStore is Gatsby internal development-only component and should never be used in production.

Unless your site has a complex or custom webpack/Gatsby configuration this is likely a bug in Gatsby. Please report this at https://github.com/gatsbyjs/gatsby/issues with steps to reproduce this error.
```

### Environment

  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 13.7.0 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.6 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 69.0.2
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.19.7 => 2.19.7 
  npmGlobalPackages:
    gatsby-cli: 2.7.30

**Comment by joshatoutthink** [comment] 2020-02-05 16:28
I got it to work with hello-world not sure. why nothing else is working

**Comment by crock** [comment] 2020-02-06 14:39
Did you delete any of the `gatsby-*.js` files? Specifically, if you have any Gatsby plugins included, a `gatsby-config.js` is requried. If you are trying to build pages at build time, you need a `gatsby-node.js`.

**Comment by zanedev** [comment] 2020-02-21 04:05
I'm getting this all of a sudden also didn't change anything with gatsby config all up to date with all dependencies.

**Comment by zanedev** [comment] 2020-02-21 04:14
^ turns out I had run `export NODE_ENV=production` in the same terminal window before so I changed it back to development all good nvm 👍

**Comment by LekoArts** [comment] 2020-02-25 13:16
Thank you for opening this!

This seems like environment issues on your systems and not so much like a bug in Gatsby. Make sure that nothing e.g. changes your `NODE_ENV` as Gatsby accesses this for e.g. webpack.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2020-02-25 13:16 UTC
Labels: status: needs more info, type: question or discussion

**Comment by tomlagier** [comment] 2020-04-30 00:02
Had the same issue with the same root cause. Might be worth updating the error message to note that it can be caused by NODE_ENV?

**Comment by luisabellan** [comment] 2020-12-15 19:11
I'm having this problem right now.
Screenshot here: 
![gatsby-error](https://user-images.githubusercontent.com/4575625/102261244-afb80a00-3f11-11eb-8714-17ad767ae76d.png)
