### ISSUE TITLE
Plugin options schema perPage setting limits total number of WooCommerce products 

### ISSUE THREAD

**Issue by bourneidBH** [gatsbyjs/gatsby#31132] opened 2021-04-30 17:12 UTC
## Description

I'm migrating a large site with WooCommerce from gatsby-source-wordpress v2 to v3. I've reduced schema options perPage to 10 because I kept getting server overload issues but it's not just limiting the number per page. It's limiting the totalCount so I can't paginate to see products past 10. And I can't increase perPage because then the server overloads & develop fails. For testing purposes I created a separate very small site with only 15 products. Originally in my small test site I didn't have the perPage option set because the site was small enough to run develop without overloading Without this option set I could get all products. But when I tested setting that option I was again only able to get 10 products.

### Steps to reproduce

1. Set up WordPress site with these plugins activated: WP Gatsby, WP GrapghQL, WooCommerce, WPGraphQL WooCommerce (WooGraphQL)
2. Create products
3. Create new gatsby site from any starter
4. Add gatsby-config.js  file with these options:
plugins: [
    {
      resolve: "gatsby-source-wordpress",
      options: {
        url: "http://your-url/graphql",
        schema: {
          perPage: 10, //set this number to any number less than number of WooCommerce products created 
          requestConcurrency: 2, 
          previewRequestConcurrency: 1, 
        },
      }]
Link to reproduction repo: https://github.com/bourneidBH/gatsby3test

### Expected result

I should be able to paginate to see the full number of products created.

### Actual result

The perPage number set in gatsby-config.js limits the total number of products available for graphql query to that. Cannot access products over that limit even with pagination.

### Environment

  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz
  Binaries:
    Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.906.0), Chromium (90.0.818.51)
  npmPackages:
    gatsby: ^3.4.0 => 3.4.0 
    gatsby-awesome-pagination: ^0.3.8 => 0.3.8 
    gatsby-plugin-gatsby-cloud: ^2.4.1 => 2.4.1 
    gatsby-plugin-image: ^1.4.0 => 1.4.0 
    gatsby-plugin-manifest: ^3.4.0 => 3.4.0 
    gatsby-plugin-react-helmet: ^4.4.0 => 4.4.0 
    gatsby-plugin-sass: ^4.4.0 => 4.4.0 
    gatsby-plugin-sharp: ^3.4.0 => 3.4.0 
    gatsby-plugin-sitemap: ^4.0.0 => 4.0.0 
    gatsby-source-filesystem: ^3.4.0 => 3.4.0 
    gatsby-source-wordpress: ^5.4.0 => 5.4.0 
    gatsby-transformer-sharp: ^3.4.0 => 3.4.0

**Comment by veryspry** [comment] 2021-05-12 21:28
Hi @bourneidBH!

Sorry to hear you're running into an issue.

In order to debug this further, we'll need to point the Gatsby site you included above to a WordPress site with which this issue is occuring. Can you provide a WordPress site (including DB) that we can run locally or a publicly accessible WordPress site (plus GraphQL endpoint) that we can point that Gatsby site at?

It's also worth noting that the WooCommerce `WpGraphQL` extension is currently not confirmed to work with the Gatsby WordPress source plugin as noted in this [reference doc](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-source-wordpress/docs/usage-with-popular-wp-graphql-extensions.md#unconfirmed-extensions-might-still-work-but-will-have-problems). This may be a source of the trouble since we aren't 100% sure that this extension will always play nicely when sourcing nodes for a Gatsby site.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by bourneidBH** [comment] 2021-05-14 14:16
Hi @veryspry 
Thanks for looking into this. I set up my test WordPress site on Local by FlyWheel. You can download a copy of it to run locally here:  https://findmymobilehome.sharepoint.com/:u:/g/Ebyr-cCYyo9Fmgg2he_5WAMBxkeKhoiwYNL8QbeOVXjs8Q?e=Jxb4MK 
The database .sql file is included in the zip file. The Gatsby site repo is https://github.com/bourneidBH/gatsby3test

**Comment by ardiewen** [comment] 2021-05-20 18:38
If you are using wp-graphql 1.33+ and wp-graphql-woocommerce, this is likely an upstream issue caused by the wordpress plugins.

I have a PR on the upstream plugin's repo [wp-graphql-woocommerce#487](https://github.com/wp-graphql/wp-graphql-woocommerce/pull/487) that explains this in greater detail, as well as links similar issues users are experiencing on that repo.

**Comment by TylerBarnes** [comment] 2021-05-20 18:49
Thanks @ardiewen ! That seems to explain this issue very well so I'm going to close this issue for now. Please follow @ardiewen's linked issue and if the fix that comes out of that doesn't resolve this issue comment here and re-open this issue.

Thanks!

**Closed by TylerBarnes** 2021-05-20 18:49 UTC
Labels: topic: WordPress, type: bug
