### ISSUE TITLE
gatsby-source-wordpress: ACF Gallery field - empty array

### ISSUE THREAD

**Issue by jonlow** [gatsbyjs/gatsby#30306] opened 2021-01-19 00:46 UTC
I have a basic ACF gallery custom field available on all wordpress pages. Using graphiql in WP shows the data but the data is an empty array using `gatsby-source-wordpress-experimental`. It's worth noting that only 1 page in WP has data in this gallery field. 

![image](https://user-images.githubusercontent.com/696226/104973922-6431d800-5a4a-11eb-8f25-fb0cc67d6820.png)
![image](https://user-images.githubusercontent.com/696226/104974487-51b89e00-5a4c-11eb-8954-82ea3b28a4f4.png)

Here's the relevant part of my `gatsby-config.js`. It's worth noting:

- `useGatsbyImage: false`
- `lazyNodes: true`

```
{
  resolve: `gatsby-source-wordpress-experimental`,
  options: {
    url: process.env.GATSBY_GRAPHQL_ENDPOINT, 
    verbose: true,
    schema: {
      timeout: 60000,
      perPage: 100

    },
    html: {
      useGatsbyImage: false,
    },
    debug: {
      graphql: {
        writeQueriesToDisk: false,
      },
    },
    type: {
      MediaItem: {
        lazyNodes: true,
      }
    }
   
  },
}
```

I have all the latest plugin versions below:

**Gatsby**
 "gatsby-source-wordpress-experimental": "7.0.3",
 
 **Wordpress**
    "gatsbyjs/wp-gatsby": "0.9.2",
    "wp-graphql/wp-graphql-acf": "0.4.0",
    "wp-graphql/wp-graphql": "1.1.2",

**Comment by TylerBarnes** [comment] 2021-03-23 00:51
Sorry for the delayed response here. I'm trying to reproduce this but it seems to be working on latest 🤔 is anyone able to share a reproduction where this doesn't work?

**Comment by jooola** [comment] 2021-03-23 09:32
I opened my own issue, as I wasn't sure if it is a duplicate, but it is similar:

https://github.com/gatsbyjs/gatsby/issues/29529

**Comment by DanielRiveraHQ** [comment] 2021-03-25 16:23
> Sorry for the delayed response here. I'm trying to reproduce this but it seems to be working on latest 🤔 is anyone able to share a reproduction where this doesn't work?

I can, do you want me to share access through the wp-graphql slack?

**Comment by LekoArts** [comment] 2021-04-14 07:56
Was there a [minimal reproduction][reproduction] provided? If not, please do so. Thanks!

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-04-21 08:01
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-04-21 08:01 UTC
Labels: status: needs reproduction, topic: WordPress
