### ISSUE TITLE
in graphQL can a collection end in "group"

### ISSUE THREAD

**Issue by amandasage** [gatsbyjs/gatsby#22862] opened 2020-04-06 17:29 UTC
Using gatsby-contentful-source plugin and I have a content type = ArticleGroup.

I'm returning error Unknown field 'entryTitle' on type 'Article'. If I change the content type to ArticleSet, I don't receive the error. Just trying to better understand why the content type/collection can't end in "group".

query MyQuery {
ArticleGroup {
totalCount
}
}

it gives the follow response:
{
"errors": [
{
"message": "Cannot read property 'args' of undefined",
"locations": [
{
"line": 2,
"column": 3
}
],
"path": [
"allArticleGroup"
],
"stack": [
"TypeError: Cannot read property 'args' of undefined",

**Comment by vladar** [comment] 2020-04-06 19:29
Hi @amandasage!

Sorry to hear you're running into an issue. There shouldn't be a difference between `ArticleGroup` or `ArticleSet` as long as you reference the correct type in your query.

It is really hard to say anything else without seeing your code.

To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by kastner** [comment] 2020-04-09 23:12
I think we've run into the same problem. In our case we are using Contentful, and have the following 2 Content Models:
* `mediaResource`
* `mediaResourceGroup`

I tried different versions of gatsby to find the breaking change, and it looks like it was 2.18.5, and I'm guessing this commit: https://github.com/gatsbyjs/gatsby/commit/006ecd8

For debugging, I created a new ContentModel named `resourceGroup`, which works fine. Looking at the generated GraphQL schema (from Gatsby's GraphQL playground), here is the connection type for the broken one (`MediaResourceGroup`):

```graphql
type ContentfulMediaResourceGroupConnection {
  totalCount: Int!
  edges: [ContentfulMediaResourceEdge!]!
  nodes: [ContentfulMediaResource!]!
  pageInfo: PageInfo!
  field: String!
  fieldValue: String
}
```
(it looks like the `edges` and `nodes` types have had their names inferred incorrectly?)

And here is the working one (`ResourceGroup`):
```graphql
type ContentfulResourceGroupConnection {
  totalCount: Int!
  edges: [ContentfulResourceGroupEdge!]!
  nodes: [ContentfulResourceGroup!]!
  pageInfo: PageInfo!
  distinct(field: ContentfulResourceGroupFieldsEnum!): [String!]!
  group(
    skip: Int
    limit: Int
    field: ContentfulResourceGroupFieldsEnum!
  ): [ContentfulResourceGroupGroupConnection!]!
}
```
Looking at a generated schema from an older version (2.18.4), the connection type looks right:
```graphql
type ContentfulMediaResourceGroupConnection {
  totalCount: Int!
  edges: [ContentfulMediaResourceGroupEdge!]!
  nodes: [ContentfulMediaResourceGroup!]!
  pageInfo: PageInfo!
  distinct(field: ContentfulMediaResourceGroupFieldsEnum!): [String!]!
  group(
    skip: Int
    limit: Int
    field: ContentfulMediaResourceGroupFieldsEnum!
  ): [ContentfulMediaResourceGroupGroupConnection!]!
}
```
I have a minimal reproduction, but it relies on Contentful. I don't know if this issue exists with other sources.

**Comment by vladar** [comment] 2020-04-10 10:08
Can you share the reproduction? That would be very helpful.

You can create a temporary delivery access token in contentful and revoke it when we're done here.

**Comment by kastner** [comment] 2020-04-27 18:42
Sorry for the slow response! I tried making a reproduction without all of our data... I did an export then an import on Contentful and the problem goes away. We haven't done it for our real site yet, so this is still preventing us from upgrading, but we have a path forward. I wish I had a clear example for you, it's very bizarre :(

**Comment by LekoArts** [comment] 2020-05-26 10:03
Since the original author of this issue hasn't answered to the ask for a reproduction I'll close this issue. If anyone else encounters this and has a reproduction, please open up a new issue with linking to this one. Thanks!

**Closed by LekoArts** 2020-05-26 10:03 UTC
Labels: status: needs reproduction, type: question or discussion
