### ISSUE TITLE
Emotion 11 api changed.

### ISSUE THREAD

**Issue by 2403772980ygy** [gatsbyjs/gatsby#28062] opened 2020-11-15 03:20 UTC
Emotion 11 uses `@emotion/react` instead of `@emotion/core`, which causes failure for gatsby-plugin-emotion.

**Comment by ben-rogerson** [comment] 2020-11-15 06:34
Here's a workaround while `gatsby-plugin-emotion` gets updated:

Assuming you've already updated `@emotion/react` and `@emotion/styled` to v11:

1. Remove `gatsby-plugin-emotion` from your `gatsby-config.js`
2. Add a `.babelrc` in the project root with the following contents:

```js
// .babelrc
{
  "presets": [
    [
      "babel-preset-gatsby",
      {
        "targets": {
          "browsers": [">0.25%", "not dead"]
        }
      }
    ]
  ],
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    [
      "@emotion/babel-plugin-jsx-pragmatic",
      {
        "export": "jsx",
        "import": "__cssprop",
        "module": "@emotion/react"
      }
    ],
    [
      "@babel/plugin-transform-react-jsx",
      {
        "pragma": "__cssprop",
        "pragmaFrag": "React.Fragment"
      }
    ]
  ]
}
```
3. Install this babel plugin - I'm not sure why/if we need this, but it looks required in "[How to use a custom .babelrc file](https://www.gatsbyjs.com/docs/babel/#how-to-use-a-custom-babelrc-file)":
```shell
npm i -D @babel/plugin-proposal-decorators`
```

**Comment by LekoArts** [comment] 2020-11-16 06:41
Duplicate of https://github.com/gatsbyjs/gatsby/issues/28063

**Closed by LekoArts** 2020-11-16 06:41 UTC
Labels: status: triage needed, type: bug
