### ISSUE TITLE
[gatsby-plugin-emotion] Misleading Documentation

### ISSUE THREAD

**Issue by amitnovick** [gatsbyjs/gatsby#17550] opened 2019-09-11 09:12 UTC
## Description

The following description of `gatsby-plugin-emotion` in its README is misleading:
> Provide support for using the css-in-js library Emotion including server side rendering.
>
> This plugin supports Emotion v10+

Q: Why is this misleading?

A: There is no mention here that the SSR support for Emotion is limited to only two specific APIs. Particularly, there is no SSR support for `css` import from `emotion`. If you go to [Emotion's docs](https://emotion.sh) right now, this API is the first thing you'll see, and yet it is unsupported by the plugin with no mention of it.

The following example snippet shows a usage of Emotion with this Gatsby plugin where the user would expect SSR to work, but it will not. Instead, the following style will be rendered on the client:

```jsx
import { css } from "emotion"

const Header = () => (
 <h2
   className={css`
     color: hotpink;
   `}
 >
   Welcome
 </h2>
) 
```

### Steps to reproduce

1. Install packages:
  - `gatsby`
  - `gatsby-plugin-emotion`
  - `emotion`
2. Add the code from the above snippet to one of the React components.
3. In order to verify that SSR does not work, it is advised to disable JS on your browser. (otherwise, JS will render the style on the client and you may not notice it)

### Expected result

The `h2` header should have a style applied of `color: hotpink`

### Actual result

The `h2` header doesn't have the `color: hotpink` style applied to it.

### Suggestion

I propose to solve this by explaining to users the limitation of the plugin, and being explicit about which API is supported.

Something along the lines of https://github.com/gatsbyjs/gatsby/pull/17444 might be useful. Feel free to suggest ways to make it as friendly as possible, but without omitting the important details.

**Comment by LekoArts** [comment] 2019-09-11 09:41
Hi, thanks for opening the issue!

I have to disagree with the README being misleading. Emotion clearly states on the page you linked that the `emotion` package is framework agnostic and e.g. server-side rendering needs additional setup. Directly below that they state that you should use `@emotion/core` for React. Moreover our docs tell you to install these packages.

I also personally have never seen a tutorial about Emotion & React which used the `emotion` package.

**Comment by amitnovick** [comment] 2019-09-11 10:32
> Emotion clearly states on the page you linked that the `emotion` package is framework agnostic [...].

Framework agnostic doesn't mean incompatible with React. Quite the opposite, it means that the tool is flexible enough that it doesn't rely on any framework's implementation.

A build tool can definitely be made to render these styles on the server, it's simply not currently supported, and users should be aware of it.

> I also personally have never seen a tutorial about Emotion & React which used the `emotion` package.

Not having seen tutorials !== there aren't any:
- [**The best React inline style libraries  compared** by Esteban Herrera](https://blog.logrocket.com/the-best-react-inline-style-libraries-comparing-radium-aphrodite-emotion-849ef148c473/)
- [**Styling React with Emotion** by joshtronic](https://alligator.io/react/react-emotion/)
- [**A Field Guide to CSS-in-JS** by Scott Taylor](https://medium.com/@wonderboymusic/a-field-guide-to-css-in-js-f7cbd9ed79a7)

**Comment by LekoArts** [comment] 2019-09-11 11:19
> A build tool can definitely be made to render these styles on the server, it's simply not currently supported, and users should be aware of it.

As my colleague @dschau wrote in the mentioned PR we already have the correct emotion packages in the installation steps which implicitly tells the user that they should use these packages with `gatsby-plugin-emotion`. I'm fine with adding a short note that people should use these instead of `emotion`, however it really should be a side-note. Otherwise it'll confuse people.

> Not having seen tutorials !== there aren't any. Here are some articles from the first page result of searching "emotion react" on Google:

All these tutorials are referring to emotion version 8 or 9 where it was still the case to import the package for React. With v10 things have changed and the mentioned tutorials are outdated now. But my point was that when people follow up-to-date tutorials they won't have any issues with our emotion plugin as the instructions will already have told them to install `@emotion/core`.

**Comment by zslabs** [comment] 2019-09-26 00:04
Sounds very similar to an issue I'm having https://github.com/gatsbyjs/gatsby/issues/17894 Not sure if this is by design or something I'm doing wrong. I followed the docs as instructed for both `gatsby-browser` and `gatsby-ssr`

**Comment by LekoArts** [comment] 2019-09-26 09:04
The linked issue seems unrelated to this documentation issue. Still, as we think the documentation doesn't need a fix (as laid out in the comment above and in the related PR) and any additions (of the mentioned ones here) would confuse people, I'm closing this issue.

Thanks for opening the issue though!

**Closed by LekoArts** 2019-09-26 09:04 UTC
Labels: type: documentation
