### ISSUE TITLE
Development bundle stuck

### ISSUE THREAD

**Issue by l-u-m-e** [gatsbyjs/gatsby#26987] opened 2020-09-22 07:50 UTC
## Description

While creating the development bundle, sometimes it stucks on `onPostBoostrap` and `Build manifest and related icons`. The problem is related with the plugin _gatsby-plugin-manifest_ or with the cache:

- If I comment out the plugin in _gatsby-config.js_  the problem will not occur again

- If I delete the cache with the command `gatsby clean` the problem will not occur again

The problem is certainly related only to the development bundle not the building one.

### Expected result
gatsby develop works

### Actual result
gatsby develop fails

### Environment

 System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
  Binaries:
    Node: 12.18.0 - D:\node.js\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - D:\node.js\npm.CMD
  Languages:
    Python: 3.8.0
  Browsers:
    Chrome: 85.0.4183.102
    Edge: Spartan (44.18362.449.0)
  npmPackages:
    gatsby: ^2.24.61 => 2.24.61
    gatsby-cli: ^2.12.98 => 2.12.98
    gatsby-image: ^2.4.19 => 2.4.19
    gatsby-plugin-facebook-pixel: ^1.0.3 => 1.0.3
    gatsby-plugin-feed-mdx: ^1.0.1 => 1.0.1
    gatsby-plugin-google-analytics: ^2.3.4 => 2.3.14
    gatsby-plugin-linkedin-insight: ^1.0.1 => 1.0.1
    gatsby-plugin-lunr: ^1.5.2 => 1.5.2
    gatsby-plugin-manifest: ^2.4.30 => 2.4.30
    gatsby-plugin-mdx: ^1.0.57 => 1.2.40
    gatsby-plugin-offline: ^3.0.40 => 3.2.28
    gatsby-plugin-react-helmet: ^3.1.16 => 3.3.11
    gatsby-plugin-sass: ^2.3.6 => 2.3.13
    gatsby-plugin-sharp: ^2.5.7 => 2.6.36
    gatsby-plugin-sitemap: ^2.4.1 => 2.4.13
    gatsby-remark-images: ^3.1.38 => 3.3.30
    gatsby-source-filesystem: ^2.1.40 => 2.3.30
    gatsby-transformer-json: ^2.2.18 => 2.4.12
    gatsby-transformer-sharp: ^2.4.7 => 2.5.15
  npmGlobalPackages:
    gatsby-cli: 2.12.99

and my package json:

"dependencies": {
    "@mdx-js/mdx": "^1.6.16",
    "@mdx-js/react": "^1.5.1",
    "bulma": "^0.9.0",
    "formik": "^2.1.4",
    "gatsby": "^2.24.61",
    "gatsby-cli": "^2.12.98",
    "gatsby-image": "^2.4.19",
    "gatsby-plugin-facebook-pixel": "^1.0.3",
    "gatsby-plugin-feed-mdx": "^1.0.1",
    "gatsby-plugin-google-analytics": "^2.3.4",
    "gatsby-plugin-linkedin-insight": "^1.0.1",
    "gatsby-plugin-lunr": "^1.5.2",
    "gatsby-plugin-manifest": "^2.4.30",
    "gatsby-plugin-mdx": "^1.0.57",
    "gatsby-plugin-offline": "^3.0.40",
    "gatsby-plugin-react-helmet": "^3.1.16",
    "gatsby-plugin-sass": "^2.3.6",
    "gatsby-plugin-sharp": "^2.5.7",
    "gatsby-plugin-sitemap": "^2.4.1",
    "gatsby-remark-images": "^3.1.38",
    "gatsby-source-filesystem": "^2.1.40",
    "gatsby-transformer-json": "^2.2.18",
    "gatsby-transformer-sharp": "^2.4.7",
    "glob": "^7.1.6",
    "node-sass": "^4.14.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-google-recaptcha-v3": "^1.5.2",
    "react-helmet": "^5.2.1",
    "yup": "^0.29.1"
  }

**Comment by pvdz** [comment] 2020-09-22 10:14
Is there any chance you could post a reproduction? A minimal repo we can download and reproduce this problem with?

**Comment by l-u-m-e** [comment] 2020-09-24 15:57
I will reproduce the problem as soon as possible. But now I'm sure that the problem is related with the *gatsby-plugin-manifest*.

**Comment by l-u-m-e** [comment] 2020-09-25 10:02
The issue can be closed since today I run `yarn upgrade` and all the problem related to *gatsby-plugin-manifest* are gone!

**Comment by l-u-m-e** [comment] 2020-09-30 07:59
I need to reopen this issue because unfortunately the problem has come back again. The problem is maily related to the creation of the manifest icon, i will try to reproduce it.

**Comment by ascorbic** [comment] 2020-10-22 10:59
Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it would be really helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

Thanks!

[reproduction]: https://gatsby.dev/reproduction

**Comment by ascorbic** [comment] 2020-11-05 11:35
Hi. I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. Thanks!

**Closed** 2020-11-05 11:38 UTC
Labels: status: needs reproduction, type: bug
