### ISSUE TITLE
Gatsby V3 Incremental build is not working

### ISSUE THREAD

**Issue by ahmadkhalaf1** [gatsbyjs/gatsby#30231] opened 2021-03-13 03:57 UTC
## Description

Incremental build does not seems to work with me , in my project where i have 10500 page everytime i build the project it will generate all pages again . so i made a new gatsby project and it was not working there as well.

### Steps to reproduce

Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.com/contributing/how-to-make-a-reproducible-test-case/

1- gatsby new hello-world https://github.com/gatsbyjs/gatsby-starter-hello-world
2- add post.js under pages folder
3- add --log-pages to build script then build the project
4- get back and change any text inside post.js 
5- build again 

### Expected result

What should happen?
only post page will be updated
### Actual result

What happened.
both 
/ and post.js pages are updated
### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

  System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Shell: 5.5.1 - /bin/zsh
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Browsers:
    Chrome: 87.0.4280.141
    Firefox: 72.0.1
  npmPackages:
    gatsby: ^3.0.1 => 3.0.1 
  npmGlobalPackages:
    gatsby-cli: 3.0.0

**Comment by LekoArts** [comment] 2021-03-13 09:03
Duplicate of https://github.com/gatsbyjs/gatsby/issues/30202#issuecomment-797401616

**Closed by LekoArts** 2021-03-13 09:03 UTC
Labels: status: triage needed, type: bug
