### ISSUE TITLE
Use of `will-change` not cleaned up in gatsby-plugin-image

### ISSUE THREAD

**Issue by jasonbcox** [gatsbyjs/gatsby#32671] opened 2021-08-03 05:32 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

See the "Use Sparingly" section in Mozilla's documentation here: https://developer.mozilla.org/en-US/docs/Web/CSS/will-change According to the doc, best practice is to switch will-change off after the change occurs.

A quick `git blame` does not indicate why `will-change` was included, since it has existed since the initial commit for `gatsby-plugin-image`.

### Reproduction Link

none

### Steps to Reproduce

I'm using StaticImage and noticing that large images may hit Firefox's will-change memory limit. This is apparently causing transitions to fail such that the placeholder remains long after the image has finished loading. While it's not clear if `will-change` is 100% the culprit of the stuck transition, it does raise a red flag since it's not being utilized appropriately.

For reasons I cannot explain, this seems to happen more often in production than development. And replicating in a simple and straightforward manner is neither. For reference, my project involved 12+ StaticImages on a single page, with jpg source images larger than 300kb. Adding more images to the page increased degradation, but there is never a clear cut-off point such that I can demonstrate the issue as a standalone example in a reproducible manner.

### Expected Result

`will-change` should be removed from `.gatsby-image-wrapper` when the opacity transition has completed.

### Actual Result

`will-change: opacity` is present on `.gatsby-image-wrapper` long after the opacity transition has completed.

### Environment

```shell
System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (16) x64 AMD Ryzen 7 3800X 8-Core Processor
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 15.8.0 - ~/n/bin/node
    Yarn: 1.21.0 - ~/n/bin/yarn
    npm: 7.5.1 - ~/n/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 92.0.4515.131
    Firefox: 78.12.0esr
  npmGlobalPackages:
    gatsby-cli: 2.19.0
```

**Comment by TylerBarnes** [comment] 2021-09-17 18:06
Hi @jasonbcox !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-12-14 06:07
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-12-14 06:07 UTC
Labels: type: bug, status: needs reproduction, topic: media
