### ISSUE TITLE
GraphQl Cannot read property 'createPageDependency' of undefined

### ISSUE THREAD

**Issue by BernardA** [gatsbyjs/gatsby#15216] opened 2019-06-28 16:34 UTC
I am trying your [client data fetching example](https://www.gatsbyjs.org/docs/client-data-fetching/), but running on the above error.

By the way, I am doing this on top of the redux-starter

For the index.js page, I do have exactly the same code as per your example, I believe:

`

      import React from 'react';
      import { graphql } from 'gatsby';
      import axios from 'axios';
    import Layout from '../components/layout';
    import Image from '../components/img/image';
    import SEO from '../components/seo';

     export const GatsbyQuery = graphql`
     {
      rickAndMorty {
        character(id: 1) {
          name
          image
        }
      }
    }
    `;

    class IndexPage extends React.Component {
    constructor(props) {
    super(props);
    this.state = {
      loading: false,
      error: false,
      pupper: {
        img: '',
        breed: '',
      },
    };
    }

    componentDidMount() {
      this.fetchRicksPupper();
    }

    render() {
    console.log('state', this.state);

    const {
      rickAndMorty: { character },
    } = this.props.data;
    const { img, breed } = this.state.pupper;
    return (
      <Layout>
        <SEO title="Home" />
        <h1>{character.name} With His Pupper</h1>
        <p>Rick & Morty API data loads at build time.</p>
        <div>
          <img
            src={character.image}
            alt={character.name}
            style={{ width: 300 }}
          />
        </div>
        <div>
          {this.state.loading ? (
            <p>Please hold, pupper incoming!</p>
          ) : img && breed ? (
            <>
              <h2>{`${breed} pupper!`}</h2>
              <img src={img} alt={`cute random `} style={{ maxWidth: 300 }} />
            </>
          ) : (
            <p>Oh noes, error fetching pupper :(</p>
          )}
        </div>
        <Image />
      </Layout>
      );
    }

    fetchRicksPupper = () => {
      this.setState({ loading: true });

      axios
      .get(`https://dog.ceo/api/breeds/image/random`)
      .then(pupper => {
        const {
          data: { message: img },
        } = pupper;
        const breed = img.split('/')[4];

        this.setState({
          loading: false,
          pupper: {
            ...this.state.pupper,
            img,
            breed,
          },
        });
      })
      .catch(error => {
        this.setState({ loading: false, error });
      });
     };
    }

    export default IndexPage;`

Then on gatsby.config.js ( sorry for the format. I couldn't unwrap this thing)

`       {
        resolve: 'gatsby-source-graphql',
       options: {
         typeName: 'RMAPI',
        fieldName: 'rickAndMorty',
        url: 'https://rickandmortyapi-gql.now.sh/',
      },
    }`

**Comment by stefanprobst** [comment] 2019-07-10 06:39
@BernardA Is this still an issue? This might have been #14665 and should be fixed already.

**Comment by BernardA** [comment] 2019-07-11 07:30
Still an issue last time I checked, which was end of last week. I am dealing with something else now and will get back to gatsby next week.

**Comment by stefanprobst** [comment] 2019-07-11 10:40
I cannot reproduce with the provided `IndexPage` + `gatsby-config`, so if this is indeed still an issue, it would be great if you could link to an example repo to easily reproduce the issue. Thanks!

**Comment by davewaterman** [comment] 2019-07-11 18:13
Same problem here on the redux starter. 

Running gatsby 2.7.10. I ran gatsby develop and this error was produced in the console:

error
The GraphQL query from C:/path/to/file.js failed.

Errors:
  Cannot read property 'createPageDependency' of undefined

  GraphQL request (2:3)
  1: query cDevPathPathWebuiSrcPagesFileJs1142989098 {
  2:   rickAndMorty {
       ^
  3:     character(id: 1) {

URL path:
  /file-path/
Context:
  {}
Plugin:
  none
Query:
  query cDevPathPathWebuiSrcPagesFileJs1142989098 {
    rickAndMorty {
      character(id: 1) {
        name
        image
      }
    }
  }

**Comment by stefanprobst** [comment] 2019-07-11 20:23
Can you try with:
* `gatsby-source-graphql` at verson 2.0.19 or above
* `gatsby` at version 2.9.2 or above

**Comment by BernardA** [comment] 2019-07-14 12:41
I updated all my npm packages and it works now.
`"gatsby-source-graphql": "^2.1.2",`
`"gatsby": "^2.13.20",`
I let it open awaiting for @davewaterman

**Comment by stefanprobst** [comment] 2019-07-18 14:04
I'm going to close this, but feel free to reopen if there is still an issue.

**Closed by stefanprobst** 2019-07-18 14:04 UTC

**Comment by samajammin** [comment] 2019-10-13 12:10
I'm hitting this same issue. I cloned [the repo](https://github.com/amberleyromo/gatsby-client-data-fetching) mentioned in the [client data fetching example](https://www.gatsbyjs.org/docs/client-data-fetching/).

```
~/code/gatsby-client-data-fetching « git:(master)
$ yarn develop
yarn run v1.17.3
$ gatsby develop
success open and validate gatsby-configs — 0.013 s
success load plugins — 0.130 s
success onPreInit — 0.082 s
success delete html and css files from previous builds — 0.008 s
success initialize cache — 0.014 s
success copy gatsby files — 0.043 s
success onPreBootstrap — 0.005 s
success source and transform nodes — 0.838 s
success building schema — 0.079 s
success createPages — 0.000 s
success createPagesStatefully — 0.031 s
success onPreExtractQueries — 0.000 s
success update schema — 0.050 s
success extract queries from components — 0.044 s
error
The GraphQL query from /Users/samrichards/code/gatsby-client-data-fetching/src/pages/index.js failed.

Errors:
  Cannot read property 'createPageDependency' of undefined

  GraphQL request (2:3)
  1: query usersSamrichardsCodeGatsbyClientDataFetchingSrcPagesIndexJs1142989098 {
  2:   rickAndMorty {
       ^
  3:     character(id: 1) {

URL path:
  /
Context:
  {}
Plugin:
  none
Query:
  query usersSamrichardsCodeGatsbyClientDataFetchingSrcPagesIndexJs1142989098 {
    rickAndMorty {
      character(id: 1) {
        name
        image
      }
    }
  }
```

**Comment by samajammin** [comment] 2019-10-13 12:11
@stefanprobst please let me know if I should create a new issue. I can't re-open this.

**Comment by stefanprobst** [comment] 2019-10-13 13:14
This looks like a dependency issue in the repo you linked to. Can you try again after removing `yarn.lock`/`package-lock.json` and reinstalling dependencies?

(Optionally you can also remove a bunch of unused deps from package.json -- all the example seems to use is `axios`, `gatsby`, `gatsby-source-graphql` and `react`+`react-dom`)
