### ISSUE TITLE
Type inference of number in createPages of gatsby-node.js

### ISSUE THREAD

**Issue by sysexits** [gatsbyjs/gatsby#27823] opened 2020-11-04 08:48 UTC
Gatsby CLI version: 2.12.115
Gatsby version: 2.25.1

```
"dependencies": {
    "@browniebroke/gatsby-image-gallery": "^3.3.3",
    "@fastly/performance-observer-polyfill": "^1.1.0",
    "@hot-loader/react-dom": "16.11.0",
    "@mdx-js/loader": "^1.5.1",
    "@mdx-js/mdx": "^1.5.1",
    "@reach/router": "^1.3.4",
    "@zauberware/react-scroll-to": "^0.2.2",
    "algoliasearch": "^3.35.1",
    "autoprefixer": "^9.7.2",
    "bootstrap": "^4.4.1",
    "dotenv": "^8.2.0",
    "gatsby": "^2.25.1",
    "gatsby-image": "^2.2.33",
    "gatsby-plugin-algolia": "^0.5.0",
    "gatsby-plugin-google-analytics": "^2.3.6",
    "gatsby-plugin-manifest": "^2.2.27",
    "gatsby-plugin-mdx": "^1.0.57",
    "gatsby-plugin-offline": "^3.0.24",
    "gatsby-plugin-polyfill-io": "^1.1.0",
    "gatsby-plugin-postcss": "^2.1.14",
    "gatsby-plugin-purgecss": "4.0.1",
    "gatsby-plugin-react-helmet": "3.1.14",
    "gatsby-plugin-sharp": "^2.6.38",
    "gatsby-plugin-styled-components": "^3.1.13",
    "gatsby-plugin-webfonts": "^1.1.0",
    "gatsby-remark-copy-linked-files": "^2.1.30",
    "gatsby-remark-images": "^3.1.32",
    "gatsby-remark-images-medium-zoom": "^1.4.0",
    "gatsby-remark-images-modal": "0.0.4",
    "gatsby-remark-images-zoom": "^1.1.0",
    "gatsby-remark-prismjs": "^3.3.24",
    "gatsby-remark-relative-images": "^0.2.3",
    "gatsby-source-filesystem": "^2.1.36",
    "gatsby-source-notion-contents": "^1.1.3",
    "gatsby-transformer-json": "^2.2.17",
    "gatsby-transformer-remark": "^2.6.34",
    "gatsby-transformer-sharp": "^2.5.16",
    "graphql": "^14.7.0",
    "intersection-observer": "^0.7.0",
    "jquery": "^1.12.4",
    "lodash": "^4.17.20",
    "object-fit-images": "^3.2.4",
    "prismjs": "^1.17.1",
    "prop-types": "15.7.2",
    "react": "16.11.0",
    "react-bootstrap": "^1.0.0-beta.16",
    "react-device-detect": "^1.9.10",
    "react-dom": "^16.13.1",
    "react-helmet": "5.2.1",
    "react-image-lightbox": "^5.1.1",
    "react-images": "^1.1.7",
    "react-images-maintained": "^2.0.4",
    "react-instantsearch": "^6.0.0",
    "react-instantsearch-dom": "^6.0.0",
    "react-modal": "^3.11.1",
    "react-redux": "^7.1.3",
    "react-router-dom": "^5.1.2",
    "redux": "^4.0.4",
    "semantic-ui-react": "^0.88.1",
    "styled-components": "^5.0.1",
    "typeface-noto-sans": "0.0.72"
  },
```

Our codebase creates a number of pages using actions in the createPages function.

```
module.exports.createPages = async ({graphql,actions}) => {
    const { createPage, createNodeField } = actions
    ...
    for(yearIter = 2002; yearIter < 2021; yearIter++)
    {
        const yearString = yearIter.toString() + "-01-01"
        const nextYearString = (yearIter + 1).toString() + "-01-01"
        createPage({
            component: newsTemplate,
            path: `/news/` + yearIter,
            context: {
                year: +moment(yearString).format('X'),
                year_next: +moment(nextYearString).format('X'),
                year_string: yearIter.toString(),
                year_int: yearIter
            }
        })
    }
   ....
}
```

in the newsTemplate.js, the GraphQL extracts data from the following query, the filtering has been done using a timestamp.

```
export const query = graphql`
    query( $year: Int!, $year_next: Int! )
    {
        allNewsJson(filter: {fields: {timestamp: {gt: $year, lt: $year_next}}}
            sort: {fields: fields___timestamp, order: DESC}) {
        edges {
            node {
                id
                date(formatString:"MMMM DD, YYYY")
                to(formatString:"MMMM DD")
                content
                type
            }
        }
        }
    }
`
```

After we update old packages, the following error is happened in our project.

```
Variable "$year" of type "Int!" used in position expecting type "Float".

If you're e.g. filtering for specific nodes make sure that you choose the correct field (that has the same type "Int!") or adjust the context variable to the type "Float".
```

This error statement is strange because we call same createPage action in other termplate, that template accepts $year, and $year_next as a Int!. The following page context is happended in other templates.

```
Context: {
    "year": 1451574000,
    "year_next": 1483196400,
    "year_string": "2016",
    "year_int": 2016
}
```

I think that a type inference is failed in some cases. Do we need to downgrade the gatsby version?

**Comment by vladar** [comment] 2020-11-05 11:19
Hi @sysexits !

Given what I see it is a `timestamp` field of the `NewsJson` type that is inferred as `Float`. It has nothing to do with your generated years.

Please check all values of this `timestamp` field and make sure **all** of those are integers. If that doesn't help, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by sysexits** [comment] 2020-11-06 04:23
> 
> 
> Hi @sysexits !
> 
> Given what I see it is a `timestamp` field of the `NewsJson` type that is inferred as `Float`. It has nothing to do with your generated years.
> 
> Please check all values of this `timestamp` field and make sure **all** of those are integers. If that doesn't help, it is incredibly helpful if you're able to create a [minimal reproduction](https://gatsby.dev/reproduction). This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.
> 
> If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction](https://gatsby.dev/reproduction) and we'll be able to take another look.
> 
> Thanks for using Gatsby! 💜

There is null value in the `timestamp` field. Thank you so much for the right solution.

**Comment by vladar** [comment] 2020-11-06 07:25
Hm, `null` value shouldn't cause the field to be inferred as `Float`. Maybe there are other values that are floats there?

Anyways, I am marking this issue as answered and closing it for now but please feel free to comment and mention me if you would like to continue this discussion.

**Closed by vladar** 2020-11-06 07:25 UTC
Labels: status: needs reproduction, topic: GraphQL
