### ISSUE TITLE
Error in function useStaticQuery in ./.cache/gatsby-browser-entry.js:77 (After upgrade to v3)

### ISSUE THREAD

**Issue by logemann** [gatsbyjs/gatsby#29951] opened 2021-03-03 09:37 UTC
## Description

After starting (yarn start) a migrated gatsby v3 project, i am getting a weird error in the frontend (see screenshot). When using browser console i see some stacktraces involving my SEO component (which has a very basic and fully functional staticQuery expression in there) and a stacktrace regarding reach router.  

This error stays but when i make a modification to the source, lets say i change a letter in the JSX, **the error disappears** and i have my running site. 

On the shell i see this after saving my pseudo change (after that everything works)

```
<i> [webpack-dev-middleware] wait until bundle finished: /__original-stack-frame?moduleId=.%2F.cache%2Fgatsby-browser-entry.js&lineNumber=117&columnNumber=11
<i> [webpack-dev-middleware] wait until bundle finished: /__original-stack-frame?moduleId=.%2F.cache%2Fgatsby-browser-entry.js&lineNumber=117&columnNumber=11
```

See below the stacktrace in the browser console when being in error mode:

```
Uncaught Error: The result of this StaticQuery could not be fetched.

This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues
    at useStaticQuery (gatsby-browser-entry.js:77)
    at SEO (SEO.js:6)
    at renderWithHooks (react-dom.development.js:14985)
    at mountIndeterminateComponent (react-dom.development.js:17811)
    at beginWork (react-dom.development.js:19049)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
    at performUnitOfWork (react-dom.development.js:22776)
gatsby-browser-entry.js:77 Uncaught Error: The result of this StaticQuery could not be fetched.

This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues
    at useStaticQuery (gatsby-browser-entry.js:77)
    at Footer (Footer.js:10)
    at renderWithHooks (react-dom.development.js:14985)
    at mountIndeterminateComponent (react-dom.development.js:17811)
    at beginWork (react-dom.development.js:19049)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
    at performUnitOfWork (react-dom.development.js:22776)
react-dom.development.js:20085 The above error occurred in the <SEO> component:

    at SEO (webpack-internal:///./src/components/App/SEO.js:23:26)
    at RecoilRoot (webpack-internal:///./node_modules/recoil/es/recoil.js:1723:3)
    at Layout (webpack-internal:///./src/components/App/Layout.js:20:23)
    at CloudEntwicklung
    at PageRenderer (webpack-internal:///./.cache/page-renderer.js:23:29)
    at PageQueryStore (webpack-internal:///./.cache/query-result-store.js:39:30)
    at RouteHandler
    at div
    at FocusHandlerImpl (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:359:5)
    at FocusHandler (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:330:19)
    at RouterImpl (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:235:5)
    at Location (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:64:23)
    at Router
    at ScrollHandler (webpack-internal:///./node_modules/gatsby-react-router-scroll/scroll-handler.js:34:35)
    at RouteUpdates (webpack-internal:///./.cache/navigation.js:304:32)
    at EnsureResources (webpack-internal:///./.cache/ensure-resources.js:22:30)
    at LocationHandler (webpack-internal:///./.cache/root.js:67:29)
    at LocationProvider (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:84:5)
    at Location (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:64:23)
    at Root
    at ee (webpack-internal:///./node_modules/gatsby-plugin-image/dist/index.browser-c5d45e0e.js:808:13)
    at StaticQueryStore (webpack-internal:///./.cache/query-result-store.js:127:32)
    at ErrorBoundary (webpack-internal:///./.cache/fast-refresh-overlay/components/error-boundary.js:24:35)
    at DevOverlay (webpack-internal:///./.cache/fast-refresh-overlay/index.js:97:23)
    at RootWrappedWithOverlayAndProvider

React will try to recreate this component tree from scratch using the error boundary you provided, LocationProvider.
index.js:80 Uncaught Error: The result of this StaticQuery could not be fetched.

This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues
    at useStaticQuery (gatsby-browser-entry.js:77)
    at SEO (SEO.js:6)
    at renderWithHooks (react-dom.development.js:14985)
    at mountIndeterminateComponent (react-dom.development.js:17811)
    at beginWork (react-dom.development.js:19049)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994)
    at invokeGuardedCallback (react-dom.development.js:4056)
    at beginWork$1 (react-dom.development.js:23964)
    at performUnitOfWork (react-dom.development.js:22776)
useStaticQuery @ gatsby-browser-entry.js:77
SEO @ SEO.js:6
react-dom.development.js:20085 The above error occurred in the <LocationProvider> component:

    at LocationProvider (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:84:5)
    at Location (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:64:23)
    at Root
    at ee (webpack-internal:///./node_modules/gatsby-plugin-image/dist/index.browser-c5d45e0e.js:808:13)
    at StaticQueryStore (webpack-internal:///./.cache/query-result-store.js:127:32)
    at ErrorBoundary (webpack-internal:///./.cache/fast-refresh-overlay/components/error-boundary.js:24:35)
    at DevOverlay (webpack-internal:///./.cache/fast-refresh-overlay/index.js:97:23)
    at RootWrappedWithOverlayAndProvider

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

(i shortened the stacktrace a little bit.)

### Steps to reproduce

for me it was just starting the project.

### Expected result

fully functional gatsby project ;-)

### Actual result

this error screenshot.

![Bildschirmfoto 2021-03-03 um 10 20 09](https://user-images.githubusercontent.com/346353/109785405-64f28800-7c0c-11eb-99c6-8af572257301.png)

### Environment

  System:
    OS: macOS 11.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 15.8.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.5.0 - /usr/local/bin/npm
  Languages:
    Python: 3.9.0 - /Users/ml/.pyenv/shims/python
  Browsers:
    Chrome: 88.0.4324.192
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.0.0 => 3.0.0 
    gatsby-image: ^3.0.0 => 3.0.0 
    gatsby-plugin-google-analytics-reporter: ^1.1.1 => 1.1.1 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-google-tagmanager: ^3.0.0 => 3.0.0 
    gatsby-plugin-html-attributes: ^1.0.5 => 1.0.5 
    gatsby-plugin-image: ^1.0.0 => 1.0.0 
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0 
    gatsby-plugin-netlify: ^3.0.0 => 3.0.0 
    gatsby-plugin-netlify-cms: ^5.0.0 => 5.0.0 
    gatsby-plugin-percy: ^0.1.4 => 0.1.4 
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0 
    gatsby-plugin-react-helmet-canonical-urls: ^1.4.0 => 1.4.0 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-robots-txt: ^1.5.5 => 1.5.5 
    gatsby-plugin-sass: ^4.0.0 => 4.0.0 
    gatsby-plugin-sharp: ^3.0.0 => 3.0.0 
    gatsby-plugin-sitemap: ^3.0.0 => 3.0.0 
    gatsby-plugin-styled-components: ^4.0.0 => 4.0.0 
    gatsby-remark-classes: ^1.0.0 => 1.0.0 
    gatsby-remark-copy-linked-files: ^3.0.0 => 3.0.0 
    gatsby-remark-custom-blocks: ^3.0.0 => 3.0.0 
    gatsby-remark-images: ^4.0.0 => 4.0.0 
    gatsby-remark-prismjs: ^4.0.0 => 4.0.0 
    gatsby-remark-relative-images: ^2.0.2 => 2.0.2 
    gatsby-source-filesystem: ^3.0.0 => 3.0.0 
    gatsby-transformer-json: ^3.0.0 => 3.0.0 
    gatsby-transformer-remark: ^3.0.0 => 3.0.0 
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0 
  npmGlobalPackages:
    gatsby-cli: 2.12.110

**Comment by wardpeet** [comment] 2021-03-03 09:41
@logemann can you share your project or create any reproduction? Have you ran `gatsby clean` before the build?

**Comment by logemann** [comment] 2021-03-03 11:06
yeah i ran `gatsby clean`. Thats what i always do when something weird happens. After more debugging, it seems it is always the StaticQuery in my SEO component which fails.

```
    const {site} = useStaticQuery(
        graphql`
      query {
        site {
          siteMetadata {
            title
            titleSuffix
            description
            image
            siteUrl
          }
        }
      }
    `);
```

But like i said. If the query would be broken, i wouldnt work after changing something and hit save. Unfortunately you only see a query number inside `useStaticQuery` gatsby code. So its hard to debug. Perhaps SiteData is not up and running after development server has started but is ready after first save.

Currently i cant expose the whole project.

**Comment by logemann** [comment] 2021-03-03 13:13
It seems it has something to do with gatsby-plugin-netlify-cms. When i remove this plugin, the error disappears.

**Comment by yurist38** [comment] 2021-03-18 11:41
Totally the same for me! I'm trying to debug it for a couple of days already but no luck so far...

**Comment by lomby92** [comment] 2021-03-18 12:00
Nope
```
  System:
    OS: Linux 5.4 KDE neon 5.21
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 12.20.0 - ~/.nvm/versions/node/v12.20.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.20.0/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 86.0
  npmPackages:
    gatsby: ^3.0.4 => 3.0.4
    gatsby-plugin-image: ^1.0.0 => 1.0.0
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0
    gatsby-plugin-netlify-cms: ^5.0.0 => 5.0.0
    gatsby-plugin-postcss: ^4.0.0 => 4.0.0
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0
    gatsby-plugin-sharp: ^3.0.0 => 3.0.0
    gatsby-plugin-sitemap: ^3.0.0 => 3.0.0
    gatsby-remark-images: ^4.0.0 => 4.0.0
    gatsby-remark-relative-images: ^2.0.2 => 2.0.2
    gatsby-source-filesystem: ^3.0.0 => 3.0.0
    gatsby-transformer-remark: ^3.0.0 => 3.0.0
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0
  npmGlobalPackages:
    gatsby-cli: 3.0.0
```

**Comment by LekoArts** [comment] 2021-03-18 13:12
Please upgrade to the latest version of all packages (we added some improvements to error handling in `gatsby@3.1`) and provide a [minimal reproduction][reproduction].

[reproduction]: https://gatsby.dev/reproduction

**Comment by yurist38** [comment] 2021-03-18 13:13
I've tried to upgrade everything yesterday, including the gatsby@3.1.0, didn't help. I'm builing a repro right now...

**Comment by yurist38** [comment] 2021-03-18 14:04
@LekoArts my minimal reproduction is ready https://github.com/yurist38/gatsby-3-static-query-issue
Please take a look at it... Thanks!

**Comment by logemann** [comment] 2021-03-22 15:18
@yurist38 i dont use MDX. So the error is not related to that.

**Comment by menttys** [comment] 2021-03-23 16:13
Having the same problem, neither `3` or `3.1` works for me.

**Comment by steviss** [comment] 2021-03-23 17:37
Having the same issue on Mac OS machine, while the project is running completely fine on a Windows machine. I've tried updating/upgrading all the packages to the latest version, but it still just displays the same error.

**Comment by LekoArts** [comment] 2021-03-26 09:35
> my minimal reproduction is ready [yurist38/gatsby-3-static-query-issue](https://github.com/yurist38/gatsby-3-static-query-issue)
> Please take a look at it... Thanks!

@yurist38 I followed the steps in the README and can't reproduce it. I also tried it with `yarn`, works, too.

**Comment by yurist38** [comment] 2021-03-26 15:28
@LekoArts it seems like something has changed since then. I've just tested it again with this reproduction repo and the issue is not appearing anymore... 🤔 Let me do more tests with my project next few days. I'll keep you updated.

**Comment by anhonestboy** [comment] 2021-03-27 15:28
Same here with Gatsby 3.1.2 starter blog with these dependencies:

`"gatsby": "^3.1.2",
    "gatsby-plugin-feed": "^3.1.0",
    "gatsby-plugin-gatsby-cloud": "^2.1.0",
    "gatsby-plugin-google-analytics": "^3.1.0",
    "gatsby-plugin-image": "^1.1.2",
    "gatsby-plugin-manifest": "^3.1.0",
    "gatsby-plugin-netlify": "^3.1.0",
    "gatsby-plugin-netlify-cms": "^5.1.0",
    "gatsby-plugin-offline": "^4.1.0",
    "gatsby-plugin-react-helmet": "^4.1.0",
    "gatsby-plugin-sharp": "^3.1.2",
    "gatsby-remark-copy-linked-files": "^3.1.0",
    "gatsby-remark-images": "^4.1.1",
    "gatsby-remark-prismjs": "^4.1.0",
    "gatsby-remark-responsive-iframe": "^3.1.0",
    "gatsby-remark-smartypants": "^3.1.0",
    "gatsby-source-filesystem": "^3.1.0",
    "gatsby-transformer-remark": "^3.1.0",
    "gatsby-transformer-sharp": "^3.1.0",
    "netlify-cms-app": "^2.14.32",
    "netlify-cms-media-library-cloudinary": "^1.3.10",
    "prismjs": "^1.23.0",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-helmet": "^6.1.0",
    "typeface-merriweather": "0.0.72",
    "typeface-montserrat": "0.0.75"`

The hack of save the file and reload looks like working fine at the moment :(

**Comment by phipag** [comment] 2021-03-30 11:04
Facing the same issue with both StaticQuery component and useStaticQuery hook:
```❯ gatsby info

  System:
    OS: macOS 11.2.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.0/bin/yarn
    npm: 7.7.5 - ~/.nvm/versions/node/v14.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 86.0.1
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.1.1 => 3.1.2
    gatsby-plugin-fontawesome-css: ^1.1.0 => 1.1.0
    gatsby-plugin-i18n: ^1.0.1 => 1.0.1
    gatsby-plugin-image: ^1.1.1 => 1.1.2
    gatsby-plugin-netlify: ^3.1.0 => 3.1.0
    gatsby-plugin-netlify-cms: ^5.1.0 => 5.1.0
    gatsby-plugin-postcss: ^4.1.0 => 4.1.0
    gatsby-plugin-react-helmet: ^4.1.0 => 4.1.0
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-sharp: ^3.1.1 => 3.1.2
    gatsby-remark-copy-linked-files: ^3.1.0 => 3.1.0
    gatsby-remark-images: ^4.1.0 => 4.1.1
    gatsby-remark-relative-images: ^2.0.2 => 2.0.2
    gatsby-source-filesystem: ^3.1.0 => 3.1.0
    gatsby-transformer-remark: ^3.1.0 => 3.1.0
    gatsby-transformer-sharp: ^3.1.0 => 3.1.0
```

Reproduction Repo: https://github.com/phipag/gatsby-i18n

**Comment by phipag** [comment] 2021-03-30 11:40
> It seems it has something to do with gatsby-plugin-netlify-cms. When i remove this plugin, the error disappears.

I can now confirm that this issue does not appear when removing gatsby-plugin-netlify-cms. Maybe this is related to the changes to the webpack config the plugin makes: https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-netlify-cms/src/gatsby-node.js#L82

**Comment by ridem** [comment] 2021-03-31 13:57
While this is fixed in gatsby, I can share the configuration that fixed the issue for me:
```js
{
  resolve: "gatsby-plugin-netlify-cms",
  options: {
    ...yourOtherOptions,
    customizeWebpackConfig: (config) => {
      config.plugins = config.plugins.filter(
        (plugin) => plugin.constructor.name !== "StaticQueryMapper"
      );
    },
  },
}
```
If this is confirmed, it will just be a matter of adding that string to https://github.com/gatsbyjs/gatsby/blob/f628c3801226f5b500d74b5b41bca4caa72a9e00/packages/gatsby-plugin-netlify-cms/src/gatsby-node.js#L172

**Comment by phipag** [comment] 2021-03-31 16:12
@ridem Thanks for sharing. It finally works now! Definitely worth adding this to the plugin directly so that others will not be affected by that anymore.

**Closed** 2021-04-02 08:56 UTC
Labels: status: needs reproduction, topic: StaticQuery, type: bug, v3migration
