### ISSUE TITLE
MDX is using assetPrefix instead of pathPrefix for local links

### ISSUE THREAD

**Issue by AlexMeah** [gatsbyjs/gatsby#23524] opened 2020-04-27 12:26 UTC
## Description

The MDX plugin is using assetPrefix rather than pathPrefix to prefix local links. This caused incorrect `href` values to be created.

### Steps to reproduce

- Setup gatsby 
- Add the MDX plugin
- Add an `assetPrefix` to `gatsby-config.js`
- Create a mdx file containing a relative link
- Run `gatsby build --prefix-paths`
- Observe in index.html that the `assetPrefix` has been added to the link

https://github.com/AlexMeah/gatsby-mdx-prefix-repro

### Expected result

It should use `pathPrefix` to prefix relative links

### Actual result

It uses `assetPrefix`

### Environment

  System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.11.0 - ~/.nvm/versions/node/v12.11.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v12.11.0/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v12.11.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 81.0.4044.122
    Firefox: 75.0
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.20.36 => 2.20.36 
    gatsby-plugin-mdx: ^1.1.11 => 1.1.11 
    gatsby-source-filesystem: ^2.3.0 => 2.3.0 
  npmGlobalPackages:
    gatsby-cli: 2.8.27

**Comment by LekoArts** [comment] 2020-04-27 14:50
Hi, thanks for the issue! I think this is a duplicate of https://github.com/gatsbyjs/gatsby/issues/21462

**Closed by LekoArts** 2020-04-27 14:50 UTC
Labels: type: bug
