### ISSUE TITLE
tableOfContent href contains full path

### ISSUE THREAD

**Issue by hirenoble** [gatsbyjs/gatsby#19193] opened 2019-10-31 22:01 UTC
## Description
Using `gatsby-remark-autolink-headings` tableOfContents generated with href full path.

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result
`<li><a href="#prerequisites">Prerequisites</a></li>`
What should happen?
The href should just contain `#id` and not `/path/to/file/#id`
### Actual result
`<li><a href="/README.md/#prerequisites">Prerequisites</a></li>`
What happened.

### Environment
Dev and Prod

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by LekoArts** [comment] 2019-11-01 09:25
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by stefanprobst** [comment] 2019-11-01 17:25
possibly fixed by: #18543

**Comment by Austaras** [comment] 2019-11-22 05:47
It is. For now `gatsby-remark-autolink-headings` is not quite useful for TOC.

**Comment by pieh** [comment] 2019-12-10 14:36
`gatsby-transformer-remark@2.6.42` now support `tableOfContents(absolute: false)`, so links don't contain pathnames and just hashes for anchor scroll

**Closed** 2019-12-16 10:01 UTC
Labels: type: feature or enhancement
