### ISSUE TITLE
Error when using useStaticQuery from Gatsby when making GraphQL call

### ISSUE THREAD

**Issue by tommaton** [gatsbyjs/gatsby#26863] opened 2020-09-11 11:24 UTC
# Summary

We're using Gatsby with Contentful as a datasource. We've setup some microcopy so authors can change and translate parts of the site.

Currently we're getting all the microcopy via GraphQL and then prop drilling which is now getting out of hand. I'm trying to create a ContextProvider where I get all the MicroCopy from our Contentful instance and then wrap it as a Provider eg similar to StyledComponents, ApolloProvider etc and then easily query it.

The ContextProvider is working no problem if I hard code the values or pass a json object in. But when I try to use a GraphQL query (useStaticQuery) I get the following error

![Screenshot 2020-09-11 at 09 35 06](https://user-images.githubusercontent.com/3616123/92919734-ecfb9000-f428-11ea-96cd-825a82b6cb35.png)

This is our ContextProvider

```
import React, { createContext } from 'react';
import { useStaticQuery, graphql } from 'gatsby';

const resourcesQuery = graphql`
  query resourceSet {
    allContentfulResourceSet {
      nodes {
        name
        resources {
          key
          value {
            value
          }
        }
      }
    }
  }
`;

interface IMicrocopyContext {
  i18n: any;
}

export const I18nContext = createContext<IMicrocopyContext>({ i18n: {} });

const I18nProvider = ({ children }) => {
  const response = useStaticQuery(resourcesQuery);
  console.log(response);

  return <I18nContext.Provider value={{ i18n: {} }}>{children}</I18nContext.Provider>;
};
export default I18nProvider;
```

## Relevant information

Can't provide working repo as stored in clients own self hosted Gitlab

### Environment (if relevant)

 System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.5 - ~/.yvm/shim/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 85.0.4183.102
    Edge: 85.0.564.51
    Firefox: 76.0
    Safari: 13.1.2
  npmPackages:
    gatsby: 2.24.27 => 2.24.27
    gatsby-plugin-typescript: 2.3.3 => 2.3.3

### File contents (if changed)

`gatsby-config.js`: N/A 
`package.json`: N/A 
`gatsby-node.js`: we've got another graphQL query which gets all the pages in the createPages and creates the pages dynamically
`gatsby-browser.js`: ApolloProvider for other data queries from 3rd party - even removing this it still errors
`gatsby-ssr.js`: ApolloProvider for other data queries from 3rd party - even removing this it still errors

**Comment by LekoArts** [comment] 2020-09-11 11:56
Hi!

The information you provided is sadly not enough to figure out where your issue lies. If you could provide a [minimal reproduction][reproduction] it would help a lot -- you could use a local data source (e.g. json) instead of Contentful for the static query.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by tommaton** [comment] 2020-09-11 12:42
> Hi!
> 
> The information you provided is sadly not enough to figure out where your issue lies. If you could provide a [minimal reproduction](https://gatsby.dev/reproduction) it would help a lot -- you could use a local data source (e.g. json) instead of Contentful for the static query.
> 
> Thanks for using Gatsby! 💜

Unfortunately the client wants to use contentful rather than share round to translators a JSON file.

I'll see what I can do in regards to a minimal reproduction

**Comment by LekoArts** [comment] 2020-09-11 12:45
I understood that :) I meant that for the minimal reproduction you should use JSON so that you don't have to use your client's access.

**Comment by daydream05** [comment] 2020-09-17 23:05
You're not alone. A similar issue as well: https://github.com/gatsbyjs/gatsby/issues/26925

Did you recently change the fields on that ContentfulResourceSet?

**Comment by ascorbic** [comment] 2020-09-24 15:49
Could you look at the discussion about caching headers in #26925 and see if that fixes it for you?

**Comment by daydream05** [comment] 2020-09-24 17:03
@ascorbic I second that. I was able to fix mine when I fixed my header caching.

@tommaton do you happen to use nginx or amazon s3 for your hosting?

**Comment by LekoArts** [comment] 2020-10-12 07:40
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-10-12 07:40 UTC
Labels: status: needs reproduction, type: bug
