### ISSUE TITLE
When you put special characters in URL, the 404 page can't be shown correctly

### ISSUE THREAD

**Issue by EragonJ** [gatsbyjs/gatsby#19533] opened 2019-11-15 06:59 UTC
## Description

If you access any page which doesn't exist, by default Gatsby will redirect users to the 404 page. But I just noticed that if you put any Chinese character like `測試` (it means `test` in English), Gatsby itself will show the 404 first then after a small delay, it'll make the whole page blank.

### Steps to reproduce

The good news is that you can even make it happen in the official blog : 

**This is the latest article and you can access it without problem**

https://www.gatsbyjs.org/blog/2019-11-14-announcing-gatsby-cloud/

**If you put any random Chinese character into the URL, then the bug will happen**

https://www.gatsbyjs.org/blog/2019-11-14-announcing-gatsby-cloud-測試/

### Expected result

Show 404 page with no problem

### Actual result

It showed the 404 page at first but it made the whole page blank after a small delay

### Environment

Use your browser to test the URL I provided above

### Notes

I did try this with my iPhone and also desktop Chrome in my personal blogs, my friends' blogs and also the official Gatsby blog and this can be reproduced 100%.

I am not sure whether this relates to https://github.com/gatsbyjs/gatsby/issues/19462 because the description of issues are kinda different even though the syndrome is quite similar.

**Comment by LekoArts** [comment] 2019-11-15 08:33
Hi, thanks for the issue!
This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/19462

**Closed by LekoArts** 2019-11-15 08:33 UTC
Labels: type: question or discussion
