### ISSUE TITLE
[Question] Is there a guide for working with Gatsby's built in routing?

### ISSUE THREAD

**Issue by h0rhay** [gatsbyjs/gatsby#8749] opened 2018-10-03 08:47 UTC
I would like to implement some custom routing functionality by adding search params to url..

If I go down this route I will potentially be clashing with Gatsby's amazing built in routing.

I don't want to start messing around with history API etc if there's a better way of manipulating routing with Gatsby.

I was hoping their might be some documentation regarding routing on the docs section of the Gatsby site.

Any pointers massively appreciated 👍 

Many thanks

**Comment by pieh** [comment] 2018-10-03 11:06
@h0rhay There are 2 ways of handling params:
 - using query strings (ie. `/search?q=search_phrase`)
 - using client routing (ie `/search/search_phrase`)

Both can be implemented in gatsby - which one would you like to use?

**Comment by pieh** [comment] 2018-10-03 11:39
Page components have `location` prop. You can access query string by `this.props.location.search` - this will be actual string, so you will need something to parse it - for example https://www.npmjs.com/package/qs

**Comment by h0rhay** [comment] 2018-10-03 11:45
Thanks thats really helpful 👍

**Comment by pieh** [comment] 2018-10-03 13:01
I'll close this for now - feel free to re-open or open new issue if you will have follow up questions

**Closed by pieh** 2018-10-03 13:01 UTC
Labels: type: question or discussion

**Comment by ng-hai** [comment] 2018-11-02 06:49
Hi @pieh , I want to implement `/driver-earning/:driver-id`, but I get many troubles and cannot figure out the right way to do it since I already had another client route `/app/*`. It can run on localhost but when deploying using Docker, `nginx` server treats the route as a new page, and return 404.

My pages folder
![image](https://user-images.githubusercontent.com/19520278/47897344-f2d6d080-dea3-11e8-8f32-d1d1a79a0760.png)

`gatsby-config.js`
```js
{
    resolve: 'gatsby-plugin-create-client-paths',
    options: { prefixes: ['/app/*', '/driver-earning/*'] },
}
```

`driver-earning.js`
```js
function DriverEarning (props) {
  return (
    <Layout {...props}>
      <Router basepath='/driver-earning'>
        <NotFound path='/' />
        <Earning path=':driver-id' />
      </Router>
    </Layout>
  )
}
```

**Comment by ng-hai** [comment] 2018-11-06 16:42
It works like a charm, @pieh! Thank you for saving my time a lot ❤️

**Comment by ng-hai** [comment] 2018-11-09 08:29
After deployed, it did not work as expected 😞
I don't know why the router always renders two routes, but the weirdness is, the second route is nested inside the first route. These are all my attempts to fix without success:

```js
function DriverEarning (props) {
  return (
    <Layout {...props}>
      <Router basepath='/driver-earning'>
        <Underconstruction path='/' />
        <Earning path=':encryptedCode' />
      </Router>
    </Layout>
  )
}
```

```js
function DriverStatement (props) {
  return (
    <Layout {...props}>
      <Match path='/driver-statement/:encryptedCode'>
        {({ match }) =>
          match ? (
            <Statement encryptedCode={match.encryptedCode} />
          ) : (
            <Underconstruction />
          )
        }
      </Match>
    </Layout>
  )
}
```

```js
function DriverStatement (props) {
  return (
    <Layout {...props}>
      <Router basepath='/driver-statement'>
        <Underconstruction default />
        <Statement path=':encryptedCode' />
      </Router>
    </Layout>
  )
}
```

```js
function DriverStatement (props) {
  return (
    <Layout {...props}>
      <Router>
        <Underconstruction path='/'>
          <Statement path=':encryptedCode' />
        </Underconstruction>
      </Router>
    </Layout>
  )
}
```

All of them only work in development mode, the `nginx` server is so messy. Even `reach/router` repo doesn't have any issues related to `nginx`.

Here is my `nginx` config
```bash
server {
    listen      80;

    server_name localhost
                127.0.0.1
                my.server;

    root /app/public;

    location /app {
      try_files $uri $uri/ /app/index.html;
    }

    location /driver-earning {
      try_files $uri $uri/ /driver-earning/index.html;
    }

    location /driver-statement {
      try_files $uri $uri/ /driver-statement/index.html;
    }

    location /health {
        return 200 'OK';
        add_header Content-Type text/plain;
    }
}
```

**Comment by ng-hai** [comment] 2018-11-10 03:52
I have tested `@reach/router` using CRA 2.0 with the same server configuration and it works 🤔

**Comment by pieh** [comment] 2018-11-10 18:33
@ng-hai are you able to share either your repo or minimal reproduction repo?

**Comment by ng-hai** [comment] 2018-11-14 07:44
I think I have found the point. The problem caused by SSR, if I return null when `windows is undefined`, the error will not appear.
