### ISSUE TITLE
JSON data disappears from graphQL on second and subsequent runs of the development server

### ISSUE THREAD

**Issue by jamiemill** [gatsbyjs/gatsby#28730] opened 2020-12-21 23:19 UTC
## Description

I have a website that loads data from several JSON files and uses them to generate pages in in `gatsby-node.js` using `createPage()`.

It works fine the first time I run `npm start`. But if I stop and restart the server, around half of the results from one of the JSON files are no longer returned from graphQL, and so many of the pages do not get generated. There's no visible failure either to tell me anything's gone wrong.

From my experiments there seems to be an interaction between two of the json files (sets.json and press.json). I suspect it might be to do with the same IDs appearing in both files, as I can solve it by deleting one file, or prefixing all the IDs in one with a string. Also, the one record that doesn't disappear is the one ID that isn't also present in the other file.

### Steps to reproduce

I've made a small reproduction of the problem in this repository: https://github.com/jamiemill/gatsby-json-bug

Steps:

1. `npm run clean`
2. `npm start`
3. Observe output, correctly finding and generating 3 press pages:
```
GENERATING
Press records found: 3
Press: createPage #182
Press: createPage #183
Press: createPage #184
Press pages created
GENERATION FINISHED
```

4. `ctrl-c` to terminate dev server
5. `npm start`
6. Observe output changed to only find 1 press page:
```
GENERATING
Press records found: 1
Press: createPage #184
Press pages created
GENERATION FINISHED
```

### Expected result

I expect the number of press records to stay stable at 3 on each run of the dev server.

### Actual result

On the second and subsequent runs the number of press records drops to 1.

### Environment

  System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.1 - ~/.nvm/versions/node/v12.18.1/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v12.18.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 80.0.1
    Safari: 14.0.1
  npmPackages:
    gatsby: ^2.26.1 => 2.29.1 
    gatsby-source-filesystem: ^2.8.0 => 2.8.0 
    gatsby-transformer-json: ^2.8.0 => 2.8.0

**Comment by KyleAMathews** [comment] 2020-12-22 00:39
Yeah the problem is transformer-json uses IDs in the json file if it finds them and node IDs must be globally unique so the two files are clobbering each other. Can you rewrite one file's IDs?

**Comment by jamiemill** [comment] 2020-12-22 08:22
Yes I could make all the IDs unique and solve the problem. But changing the ids would cause my page URLs to change too, breaking any inbound links unless I set up redirects.

In any case I would still consider this a bug. It's a surprising and dangerous behaviour if some pages silently disappear before you publish because of unexpected interactions between independent json files. It took me about two days to debug what was happening.

**Comment by jamiemill** [comment] 2020-12-22 08:25
Ah, maybe I could add a unique private ID separate to the public ID used for the URLs to avoid breaking links.

But I'm surprised this behaviour isn't tripping more people up if this is expected.

**Comment by jamiemill** [comment] 2020-12-23 23:08
How about adding a warning to the documentation that if an ID fields is present in the JSON it will be used as the node's ID in the global namespace and will clobber other records with the same ID?

Or even better, warning in the console if a duplicate ID is added?

**Comment by KyleAMathews** [comment] 2020-12-23 23:30
A warning upon clobbering (or even just erroring) would be very helpful. Would you like to PR it? Or, thinking out loud, perhaps the real bug is just that we use IDs from the JSON file at all — IDs should be guaranteed to be unique. What we do in other transformers/source plugins is if `id` is already set, we copy that to a different field e.g. `id_from_record` and deterministically generate an ID we know to be unique. This would be a breaking change but would completely fix the issue.

**Comment by KyleAMathews** [comment] 2020-12-23 23:31
So we could do both. Add a warning for the current version and do a breaking change which copies the built-in ID (if found) to another field.

**Comment by KyleAMathews** [comment] 2020-12-23 23:31
This is also another fix too @jamiemill which is to just change your `id` fields to be something else.

**Comment by jamiemill** [comment] 2020-12-24 09:28
Thanks Kyle. I solved my immediate problem by moving my `id` fields to `public_id` fields so they don't have to be globally unique.

Can I assume there's no harm in omitting the `id` field from my JSON now? My mental model was close to the react.js `key` concept: that it's somehow helpful for Gatsby if each of my json records has a stable identifier for diffing purposes. But from what you're saying it doesn't seem necessary.

I won't be able to work on a PR for any of the suggested fixes, but I'm happy to have confirmation what was going wrong and a robust workaround.

If there's a precedent for moving user-supplied IDs to another field, that sounds reasonable to me as a more permanent solution.

**Comment by LekoArts** [comment] 2021-01-05 09:26
> Can I assume there's no harm in omitting the id field from my JSON now? My mental model was close to the react.js key concept: that it's somehow helpful for Gatsby if each of my json records has a stable identifier for diffing purposes. But from what you're saying it doesn't seem necessary.

Yeah, you can remove the `id` now.

I'll close this as answered and the bug is now tracked here: https://github.com/gatsbyjs/gatsby/issues/28846

**Closed by LekoArts** 2021-01-05 09:26 UTC
Labels: type: question or discussion
