### ISSUE TITLE
Incremental build not working with React.lazy loaded component when a gatsby-config file exists

### ISSUE THREAD

**Issue by joiglifberg** [gatsbyjs/gatsby#37706] opened 2023-02-27 13:57 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

Gatsby does not update a page with Incremental build when a change in a component imported with `React.lazy` **AND** a `gatsby-config` file exists.

The first video displays when a `gatsby-config` exist and therefore it's **not working**.
In the second video, the `gatsby-config` file is deleted and the change in the `React.lazy` loaded component is detected and the page updated.

https://user-images.githubusercontent.com/640695/221581780-71945dae-db81-4755-9018-9f9bc31dc2e5.mp4

https://user-images.githubusercontent.com/640695/221581890-f96c0797-993b-4756-b7e2-d51615063070.mp4

### Reproduction Link

https://github.com/joiglifberg/gatsby-incremental-build-react-lazy-gatsby-config-reproduction

### Steps to Reproduce

1. Download the repo
2. Run `npx gatsby build --log-pages`.
`Updated page: /` is displayed.
4. Make a change in the component `src/MyComponent.js`
5. Run `npx gatsby build --log-pages`.
`There are no new or changed html files to build.` is displayed.

### Expected Result

I expect the page `/` to have been updated and the console output to be `Updated page: /`

### Actual Result

The page `/` has not been updated and the console output is `There are no new or changed html files to build.`

### Environment

```shell
System:
    OS: macOS 13.2
    CPU: (10) arm64 Apple M1 Pro
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
  Browsers:
    Safari: 16.3
  npmPackages:
    gatsby: ^5.7.0 => 5.7.0
```

**Comment by pieh** [comment] 2023-03-01 08:05
I did initial investigation - I think there are 2 discrete bugs:
 1. relates to not tracking lazily loaded components when checking wether to rebuild pages from template which is main issue presented here
 2. we are setting some internal flags only when `gatsby-config` exist, and when it doesn't gatsby does pre-v5 behaviour when it comes to figuring out which templates to regenerate (in this case change to any frontend file triggers regenerating all html files not just the ones that should be affected - so while this could help with workaround the issue if you don't need config, it's also not the most efficent)

**Comment by pieh** [comment] 2023-03-02 08:48
https://github.com/gatsbyjs/gatsby/pull/37712 adds a test case and a fix. I won't be able to get review on this until at least Monday, but at least letting you know that potential fix was prepared

**Comment by rebeljoi** [comment] 2023-03-10 10:05
@pieh I see that the two referenced PRs has been merged. Will this be fixed in 5.8.0 or in a patch version of 5.7.x?

**Comment by pieh** [comment] 2023-03-10 11:07
Ah sorry. This is available now in `gatsby@next` so you could use that temporarily. This change has slight potential on introducing regresion elsewhere due to not using guaranteed stable sorted list of dynamic imports so we didn't want to backport it to stable / latest and monitor behaviour with this change. If we won't notice regressions this will be included in 5.8.0 that will be released in ~10 days

**Comment by rebeljoi** [comment] 2023-03-28 07:48
@pieh Any status update?

**Comment by rebeljoi** [comment] 2023-05-11 07:14
I can confirm this was fixed by https://github.com/gatsbyjs/gatsby/pull/37749 which was released in https://www.gatsbyjs.com/docs/reference/release-notes/v5.8/.
Please close this issue.

**Closed** 2023-10-12 06:12 UTC
Labels: type: bug, status: confirmed
