### ISSUE TITLE
createpage path without "/" causes back history not to work

### ISSUE THREAD

**Issue by philschonholzer** [gatsbyjs/gatsby#13971] opened 2019-05-11 13:30 UTC
## Description

Going back in the browser history (like pressing the back button) skips over the first page (can't navigate to first "created" page back).

### Steps to reproduce

1. Pass a string to path in createpage without any "/" in it. Example project: https://github.com/philschonholzer/custom-slug Commit with changes to reproduce: https://github.com/philschonholzer/custom-slug/commit/64dd38bcd79fa83148157fa059e3521dc42ebef4
2. Build project (can not be reproduced in dev)
3. Open a created page (like http://localhost:9000/hi, not http://localhost:9000/) directly in the browser by pasting or typing the url in the browser bar.
4. Make sure no cached page is loaded (Shift-Reload) 
5. Click any link (like "My Second Post!" at the bottom of the page). 
6. Press the back button in the browser.

### Expected result

In 6. pressing back should jump back to the first page (like http://localhost:9000/hi)

### Actual result

In 6. you will wrongly skip the first page and land directly at the empty tab screen in your browser.

### Environment

  System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.13.0 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.131
    Safari: 12.1
  npmPackages:
    gatsby: ^2.4.2 => 2.4.2 
    gatsby-image: ^2.0.41 => 2.0.41 
    gatsby-plugin-feed: ^2.2.0 => 2.2.0 
    gatsby-plugin-google-analytics: ^2.0.19 => 2.0.19 
    gatsby-plugin-manifest: ^2.1.1 => 2.1.1 
    gatsby-plugin-offline: ^2.1.0 => 2.1.0 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.0.12 
    gatsby-plugin-sharp: ^2.0.36 => 2.0.36 
    gatsby-plugin-typography: ^2.2.13 => 2.2.13 
    gatsby-remark-copy-linked-files: ^2.0.12 => 2.0.12 
    gatsby-remark-images: ^2.0.6 => 2.0.6 
    gatsby-remark-prismjs: ^3.2.9 => 3.2.9 
    gatsby-remark-responsive-iframe: ^2.1.1 => 2.1.1 
    gatsby-remark-smartypants: ^2.0.9 => 2.0.9 
    gatsby-source-filesystem: ^2.0.33 => 2.0.33 
    gatsby-transformer-remark: ^2.3.12 => 2.3.12 
    gatsby-transformer-sharp: ^2.1.19 => 2.1.19 

It took me almost 2 full days to find the cause of this bug. I know NOW that according to the docs a "/" is needed, but because everything else worked (and in Gatsby 1.0 this bug did not occur) I would not know.  

If I would have gotten an error message or warning this could have spared me a lot of time. Or if a "/" is added if none is around. Or if the browser history bug would not occur when a "/" is missing.

But otherwise thanks to the Gatsby-Team for the awesome project. Gogogo!

**Comment by freiksenet** [comment] 2019-05-16 13:07
Hi! 

Thank you for taking time to write this issue! This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/13975, so I'll close it.

**Closed by freiksenet** 2019-05-16 13:07 UTC
