### ISSUE TITLE
Menu Links randomly disappear in develop and / or build

### ISSUE THREAD

**Issue by maweo** [gatsbyjs/gatsby#37751] opened 2023-03-16 15:33 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

We face a strange behaviour on one of our gatsby frontends. 
Every build / develop, one or more links from the menu are missing. It is not the same link, sometimes it’s just one link missing, sometimes more.

We tried to trace the error via the steps in the trouble-shooting-section. In WPGraphQL, all of the links are there.
When enabling writeQueriesToDisk: true the links are here as well.

In localhost:8000/__graphql, the links are missing, and therefore in the frontend as well. Strangely, when using count in GraphQL, it says the right number of links, while showing fewer links right afterwards. As an example, when we have 4 links in the wp-menu, count says “4", but only 3 links are shown in the query.

We tried playing around with the versions, didn’t change anything.
Any ideas, what we can do here?

**Relevant dependencies:**
“gatsby”: “^4.11.2"
“gatsby-source-wordpress”: “^6.11.2"

### Reproduction Link

/

### Steps to Reproduce

- (Wordpress Setup)
- WP GraphQL Plugin
- Check GraphiQL IDE (full list is available)
- Setup Gatsby
- Check GraphQL structure on localhost:8000/__graphql
- 

### Expected Result

Get all entries from the GraphQl Query, when the count is 4, the query should contain 4 entries (we get 3).

### Actual Result

The Query count is 4, items that are returned are 3.

### Environment

```shell
System:
    OS: macOS 12.2.1
    CPU: (8) arm64 Apple M1
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 18.13.0 - /opt/homebrew/opt/node@18/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.19.3 - /opt/homebrew/opt/node@18/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 111.0.5563.64
    Safari: 15.3
  npmPackages:
    gatsby: ^4.11.2 => 4.25.2
    gatsby-background-image: ^1.5.3 => 1.6.0
    gatsby-image: ^3.11.0 => 3.11.0
    gatsby-plugin-breakpoints: ^1.3.5 => 1.3.9
    gatsby-plugin-catch-links: ^4.11.0 => 4.25.0
    gatsby-plugin-eslint: ^4.0.0 => 4.0.3
    gatsby-plugin-gatsby-cloud: ^4.11.1 => 4.25.0
    gatsby-plugin-gdpr-cookies: ^2.0.6 => 2.0.9
    gatsby-plugin-image: ^2.11.1 => 2.25.0
    gatsby-plugin-manifest: ^4.11.1 => 4.25.0
    gatsby-plugin-offline: ^4.13.0 => 4.15.0
    gatsby-plugin-preact: ^6.11.0 => 6.25.0
    gatsby-plugin-react-helmet: ^5.11.0 => 5.25.0
    gatsby-plugin-react-svg: ^3.1.0 => 3.3.0
    gatsby-plugin-root-import: ^2.0.5 => 2.0.9
    gatsby-plugin-sass: ^5.11.1 => 5.25.0
    gatsby-plugin-sharp: ^4.11.1 => 4.25.0
    gatsby-plugin-sitemap: ^5.7.0 => 5.25.0
    gatsby-plugin-transition-link: ^1.20.5 => 1.20.5
    gatsby-plugin-webfonts: ^2.1.1 => 2.3.2
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.17 => 1.1.30
    gatsby-source-filesystem: ^4.11.1 => 4.25.0
    gatsby-source-instagram-all: ^5.2.1 => 5.2.1
    gatsby-source-wordpress: ^6.11.2 => 6.25.2
    gatsby-transformer-sharp: ^3.13.0 => 3.15.0
  npmGlobalPackages:
    gatsby-cli: 5.6.0
```

**Comment by char-cole** [comment] 2023-04-03 21:20
I've also encountered this issue on a site with a WordPress backend. We gave up and hard-coded the menu as a stopgap.

`"gatsby": "^4.24.7",`
`"gatsby-source-wordpress": "^6.14.1",`

**Comment by nayrbzer** [comment] 2023-04-18 22:06
I encountered this issue so I decided to create custom graphql which displays all the menus and have an identifier. With limitation that you can’t pass arguments to fields you can add id as type.

**Comment by LekoArts** [comment] 2023-04-19 06:57
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2023-04-19 06:57 UTC
Labels: type: bug, status: needs reproduction, topic: source-wordpress, topic: source-plugins

**Comment by Jeet022** [comment] 2023-08-31 14:22
Hi @LekoArts 

I am facing the same issue, when sometime MENU are available in CMS ( wordpress ) but on front end  it disappear.
When i do some changes in them ( and then revert ) those are reflected back on Gatsby after build.

I am not sure how to replicate this issue.
