### ISSUE TITLE
gatsby-plugin-image causing "gatsby develop" being killed

### ISSUE THREAD

**Issue by Shnass** [gatsbyjs/gatsby#31010] opened 2021-04-22 20:06 UTC
## Description

Started to use gatsby-plugin-image instead of gatsby-image, enjoying friendly syntaxis and number of parameters but having some troubles:
- when I added gatsby-plugin-image to the page with one image it was ok, but when I used it on the catalog page with plenty of items (and plenty of images aswell) it is now taking quite a siginficant time to build the development version of site and then after some time it is killed (last output in console is 
 "success run page queries - 0.756s - 1/1 1.32/s
Killed"
- mostly all the images but few stays unrecognizabely pixelated (probably they are not fully loaded before process is killed)

### Steps to reproduce
- make a page with more than 15-20 GatsbyImage components and run "gatsby develop" 

My graphql query looks like this
```
export const PageQuery = graphql`
  query CategoriesTemplate($slug: String!) {
    strapiCategories(slug: {eq: $slug}) {
      gallery{
        localFile{
          childImageSharp{
            gatsbyImageData(
               layout:FIXED
               width: 800
               placeholder: BLURRED
               formats: [AUTO, WEBP, AVIF]
             )
          }
        }
      }
    }
  }
`
```
and I output images like this 
`<GatsbyImage alt="" image={getImage(image.localFile)}/>`

(GatsbyImage and getImage are imported, gatsby-config.js has entries for gatsby-transformer-sharp, gatsby-plugin-sharp and gatsby-plugin-image) 
I use strapi as backend

### Expected result
- nicely optimized pictures that are not killing the site

### Actual result

What happened.
- process is terminated with Killed state, images are blured/pixalated

### Environment

  System:
    OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Xeon(R) Gold 6240R CPU @ 2.40GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  npmPackages:
    gatsby: ^3.2.1 => 3.2.1
    gatsby-image: ^3.1.0 => 3.1.0
    gatsby-plugin-anchor-links: ^1.2.1 => 1.2.1
    gatsby-plugin-google-tagmanager: ^3.3.0 => 3.3.0
    gatsby-plugin-image: ^1.3.1 => 1.3.1
    gatsby-plugin-layout: ^2.1.0 => 2.1.0
    gatsby-plugin-react-helmet: ^4.1.0 => 4.1.0
    gatsby-plugin-sharp: ^3.1.1 => 3.1.1
    gatsby-source-filesystem: ^3.1.0 => 3.1.0
    gatsby-source-strapi: 0.0.12 => 0.0.12
    gatsby-transformer-sharp: ^3.3.0 => 3.3.0

**Comment by wardpeet** [comment] 2021-04-23 14:10
Hi @Shnass!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a minimal reproduction. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could provide a minimal reproduction and we'll be able to take another look.

Thanks for using Gatsby! 💜

**Comment by Shnass** [comment] 2021-04-26 14:40
After few retries I was able to build it without errors, I think right now that maybe it was due to some server side factors. I will try to reproduce this if I will face it again. Thank you!

**Comment by wardpeet** [comment] 2021-04-30 12:17
thanks, @Shnass I'll close the issue for now, feel free to re-open or recreate it if you have more information.

I'm glad it worked out in the end.

**Closed by wardpeet** 2021-04-30 12:17 UTC
Labels: topic: images/media, type: bug
