### ISSUE TITLE
[gatsby-source-contentful] Internal absolute links to same domain are treated as relative links

### ISSUE THREAD

**Issue by ChrisSki** [gatsbyjs/gatsby#3715] opened 2018-01-26 16:32 UTC
## Description

I have absolute urls in my blog posts that navigate to other blog posts. When clicking on these links, the absolute url is treated as a relative url, which sends the user to a 404 page.

### Environment

Gatsby version: 1.9.153
Node.js version: 8.9.1
Operating System: MacOS High Sierra 10.13.2

### Actual result

Internal link: `https://example.com/new-post`

End url: `https://example.com/https://example.com/new-post`

### Expected behavior

This should act naturally like an absolute url would.

**Comment by calcsam** [comment] 2018-01-27 22:46
Can you post a repo reproducing this?

**Comment by KyleAMathews** [comment] 2018-01-27 22:58
Also what plugins are you using?

**Comment by ChrisSki** [comment] 2018-02-07 16:26
Ok, so I tried my best to work this out and find a proper bug, but I couldn't narrow it down. What I came to realize is that it only happens when the absolute link has the same root domain. I had not seen this issue in dev or our QA environment because the links work fine when it's not the same root. I.e., when I'm on localhost the absolute links link out properly to our site. Same with our `qablog.example.com`. But once we're in prod and pointing those absolute links to other pages with the same root, this issue occurs. I can only think this is a React Router issue.

We are migrating our blog, and our past CMS used absolute links when creating links in a post to other posts. So this is the nature of what we're working with. One solution is to go through and modify all the links, which I don't have time to do with over 100 posts. To solve this, I used a regex to turn any internal absolute links into relative ones and this solves the problem.

Below are the plugins we are currently using.

```
"dependencies": {
    "babel-plugin-emotion": "^8.0.12",
    "babel-plugin-lodash": "^3.3.2",
    "emotion": "^8.0.12",
    "emotion-server": "^8.0.12",
    "gatsby": "^1.9.153",
    "gatsby-cli": "^1.1.27",
    "gatsby-link": "^1.6.32",
    "gatsby-plugin-catch-links": "^1.0.14",
    "gatsby-plugin-emotion": "^1.1.10",
    "gatsby-plugin-feed": "^1.3.15",
    "gatsby-plugin-google-analytics": "^1.0.14",
    "gatsby-plugin-lodash": "^1.0.6",
    "gatsby-plugin-manifest": "^1.0.11",
    "gatsby-plugin-nprogress": "^1.0.9",
    "gatsby-plugin-offline": "^1.0.12",
    "gatsby-plugin-react-helmet": "^2.0.3",
    "gatsby-plugin-sharp": "^1.6.24",
    "gatsby-plugin-sitemap": "^1.2.9",
    "gatsby-plugin-twitter": "^1.0.14",
    "gatsby-plugin-typography": "^1.7.10",
    "gatsby-remark-autolink-headers": "^1.4.10",
    "gatsby-remark-copy-linked-files": "^1.5.24",
    "gatsby-remark-images": "^1.5.36",
    "gatsby-remark-prismjs": "^1.2.11",
    "gatsby-remark-responsive-iframe": "^1.4.16",
    "gatsby-source-contentful": "^1.3.31",
    "gatsby-source-filesystem": "^1.5.11",
    "gatsby-transformer-remark": "1.7.26",
    "grid-emotion": "^2.1.0",
    "hidden-styled": "^1.0.0-0",
    "lodash": "^4.17.4",
    "lodash-webpack-plugin": "^0.11.4",
    "react": "^15.6.2",
    "react-disqus-comments": "^1.1.1",
    "react-dom": "^15.6.2",
    "react-emotion": "^8.0.12",
    "react-helmet": "^5.2.0",
    "react-share": "^1.19.0",
    "react-twitter-widgets": "^1.7.1"
  },
  "devDependencies": {
    "cli-glob": "^0.1.0",
    "eslint": "^4.13.1",
    "eslint-config-airbnb": "^16.1.0",
    "eslint-config-prettier": "^2.9.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.0.3",
    "eslint-plugin-react": "^7.5.1",
    "gh-pages": "^1.1.0",
    "prettier": "^1.10.2",
    "remark-cli": "^4.0.0",
    "remark-preset-lint-recommended": "^3.0.1",
    "stylefmt": "^6.0.0",
    "stylelint": "^8.4.0",
    "stylelint-config-standard": "^18.0.0",
    "write-good": "^0.11.3"
  },
```

**Comment by KyleAMathews** [comment] 2018-09-08 04:12
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Closed by KyleAMathews** 2018-09-08 04:12 UTC
