### ISSUE TITLE
Website crashing in production build

### ISSUE THREAD

**Issue by Munien** [gatsbyjs/gatsby#19609] opened 2019-11-19 03:56 UTC
## Description

**Scenario 1 -**

User loads website after a production release on Netlify. If they attempt to navigate using the navbar nothing happens and chunk loading errors can be seen in the dev console.

**Scenario 2 -**

User loads website after a production release on Netlify. If they attempt to visit a page thats not on the navbar the page only partly loads and some elements of the page are missing.

**Additional Info**

The navbar links are using gatsbys link component.

Possibly related to #18866 

### Steps to reproduce

**Scenario 1**

1. Publish a build on netlify.
2. Visit website once the build has uploaded and processed.
3. Try to navigate using the navbar.
4. Nothing happens or a white page displays.

**Scenario 2**

1. Publish a build on netlify.
2. Visit website once the build has uploaded and processed.
3. Try to visit a page editing the url in the url bar.
4. Page partially loads but elements of the page are missing.

### Expected result

Users should be able to navigate using the links and visit internal pages.

### Actual result

Users get chunk loading errors and on pages not in the navbar elements are missing.

### Environment

  System:
    OS: macOS 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.97
    Safari: 13.0.3
  npmPackages:
    gatsby: 2.15.37 => 2.15.37 
    gatsby-image: ^2.2.17 => 2.2.29 
    gatsby-plugin-alias-imports: ^1.0.5 => 1.0.5 
    gatsby-plugin-eslint: ^2.0.8 => 2.0.8 
    gatsby-plugin-google-analytics: ^2.1.14 => 2.1.23 
    gatsby-plugin-google-tagmanager: ^2.1.8 => 2.1.15 
    gatsby-plugin-lodash: ^3.1.6 => 3.1.13 
    gatsby-plugin-manifest: ^2.2.14 => 2.2.23 
    gatsby-plugin-netlify: ^2.1.11 => 2.1.22 
    gatsby-plugin-netlify-cache: ^1.2.0 => 1.2.0 
    gatsby-plugin-netlify-cms: ^4.1.13 => 4.1.25 
    gatsby-plugin-offline: ^3.0.3 => 3.0.16 
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3 
    gatsby-plugin-purgecss: ^4.0.1 => 4.0.1 
    gatsby-plugin-react-helmet: ^3.1.4 => 3.1.13 
    gatsby-plugin-react-leaflet: ^2.0.11 => 2.0.11 
    gatsby-plugin-remove-fingerprints: ^0.0.2 => 0.0.2 
    gatsby-plugin-sharp: ^2.2.20 => 2.2.32 
    gatsby-plugin-sitemap: ^2.2.10 => 2.2.19 
    gatsby-plugin-styled-components: ^3.1.4 => 3.1.11 
    gatsby-source-filesystem: ^2.1.21 => 2.1.33 
    gatsby-transformer-json: ^2.2.7 => 2.2.15 
    gatsby-transformer-sharp: ^2.2.7 => 2.3.0 
  npmGlobalPackages:
    gatsby-cli: 2.8.3

**Comment by LekoArts** [comment] 2019-11-19 09:26
Hi, thanks for the issue!
I'm closing this as a duplicate of https://github.com/gatsbyjs/gatsby/issues/18866

**Closed by LekoArts** 2019-11-19 09:26 UTC
