### ISSUE TITLE
elemMatch not working

### ISSUE THREAD

**Issue by art0rz** [gatsbyjs/gatsby#24008] opened 2020-05-12 13:48 UTC
I have a nested data structure on which I'm trying to run a query using `elemMatch`, but the query is returning all elements rather than just the ones that match the condition.

I'm not sure if I'm using it correctly, or there is a bug somewhere.

I've redacted the actual content, but the source is [gatsby-source-contentstack](https://github.com/contentstack/gatsby-source-contentstack/).

Query:
```graphql
query Foo($category: String!) {
  lists(
    filter: {
      list: {
        items: {
          elemMatch: { category: { eq: $category } }
        }
      }
    }
  ) {
    nodes {
      list {
        items {
          category
        }
      }
    }
  }
}
```

Query variables:
```json
{"category":"some_category"}
```

Result:
```json
{
  "data": {
    "lists": {
      "nodes": [
        {
          "list": {
            "items": [
              {
                "category": "other_category"
              },
              {
                "category": "other_category"
              },
              {
                "category": "other_category"
              },
              {
                "category": "some_category"
              },
              {
                "category": "some_category"
              },
              {
                "category": "another_category"
              },
              {
                "category": "another_category"
              }
            ]
          }
        }
      ]
    }
  }
}
```

I'm using `elemMatch` in another query with content that is nested one level less, and it works just fine.

**Comment by vladar** [comment] 2020-05-12 16:18
СС @pvdz

**Comment by freiksenet** [comment] 2020-05-13 11:03
I'm not 100% sure what result you are looking for. This output is correct - the filter applies to the top level `lists` item, so it sees a correct category as one of the elements and returns that parent item. It won't do filtering of the internal list.

I wonder if you can provide a fuller reproduction with both the working and not-working query. Thank you!

**Comment by art0rz** [comment] 2020-05-13 13:06
### This output is correct - the filter applies to the top level lists item, so it sees a correct category as one of the elements and returns that parent item. It won't do filtering of the internal list.

That makes sense, but not exactly what I expected. I expect this query to return what I am getting now:
```graphql
query Foo($category: String!) {
  lists(
    filter: {
      list: {
        elemMatch: { items: { category: { eq: $category } } }
      }
    }
  ) {
    nodes {
      list {
        items {
          category
        }
      }
    }
  }
}
```
But that fails because `elemMatch` is not available on that element.

Not sure I can provide a reproduction without exposing my ContentStack keys, The working query is essentially the same, except that the key I'm matching on is one level above. The result looks like this:

```json
{
  "data": {
    "news": {
      "nodes": [
        {
          "article": [
            {
              "category": "other_category"
            },
            {
              "category": "other_category"
            },
            {
              "category": "other_category"
            },
            {
              "category": "some_category"
            },
            {
              "category": "some_category"
            },
            {
              "category": "another_category"
            },
            {
              "category": "another_category"
            }
          ]
        }
      ]
    }
  }
}
```

I could resolve this issue by filtering the data using JavaScript, but doing it in a query is more elegant.

**Comment by herecydev** [comment] 2020-05-15 08:49
@art0rz just weighing in here because I've faced similar situations.

> It won't do filtering of the internal list.

I believe this is correct, but it's not clear (hence several issues like this). I'm pretty sure from my experiences there's 2 ways to overcome this:

1) Query all the stuff and then filter in your page/components. Simple solution but means that you have to pull more data then needed, only to filter it and throw some of it away.
2) Use the [schema customization api](https://www.gatsbyjs.org/docs/schema-customization/#createresolvers-api). I use this quite frequently to overcome this problem. By adding a resolver like `articles` you can get access to the data and variables and do the filtering yourself. This will be executed at build time and the page-data will only have the content that you actually want and the pages/components won't have the hacks in them.

**Comment by freiksenet** [comment] 2020-05-18 13:35
@art0rz I'm now a bit confused on what query you are using and what result you are expecting - could you please clarify? 

One way to provide the reproduction would be to export the data to JSON from contentstack and use gatsby-transformer-json to test.

**Comment by LekoArts** [comment] 2020-06-03 08:41
I'll close this as no reproduction was provided after 7 days. Please comment if you can provide that. Thanks!

**Closed by LekoArts** 2020-06-03 08:41 UTC
Labels: status: needs reproduction, topic: GraphQL
