### ISSUE TITLE
Gatsby overrides font-styles in gatsby develop

### ISSUE THREAD

**Issue by Mithgarthsormr** [gatsbyjs/gatsby#29420] opened 2021-02-09 20:18 UTC
## Description
When I use **gatsby develop**, most of my font styles (except color) are overwritten by Gatsby (for example the font-family is changed to "Roboto").
When I mark the font styles as important, they are not overwritten.
In build they are ok, too. Just gatsby devolop makes nonsense.

### Steps to reproduce

Not sure what to do to reproduce except using the same packages.
The error happens both if I import main.scss via gatsby-browser.js and via layout-component.

### Expected result

Expected my styles to be applied just like in **gatsby build** (where they actually do work)
![sass_build](https://user-images.githubusercontent.com/60277471/107422698-a74c0c00-6b1b-11eb-8a2a-58e5bfe38d67.png)

### Actual result

font styles are overwritten by gatsby
![sass_develop](https://user-images.githubusercontent.com/60277471/107422712-ac10c000-6b1b-11eb-9cbc-8aa71b3e5a58.png)

### Environment

  System:
    OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    npm: 6.14.11 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Browsers:
    Firefox: 85.0
  npmPackages:
    gatsby: ^2.32.3 => 2.32.3 
    gatsby-image: ^2.11.0 => 2.11.0 
    gatsby-plugin-manifest: ^2.12.0 => 2.12.0 
    gatsby-plugin-material-ui: ^2.1.10 => 2.1.10 
    gatsby-plugin-matomo: ^0.9.0 => 0.9.0 
    gatsby-plugin-mdx: ^1.10.0 => 1.10.0 
    gatsby-plugin-offline: ^3.10.0 => 3.10.0 
    gatsby-plugin-page-creator: ^2.10.0 => 2.10.0 
    gatsby-plugin-react-helmet: ^3.10.0 => 3.10.0 
    gatsby-plugin-sass: ^3.2.0 => 3.2.0 
    gatsby-plugin-sharp: ^2.14.1 => 2.14.1 
    gatsby-source-filesystem: ^2.11.0 => 2.11.0 
    gatsby-transformer-sharp: ^2.12.0 => 2.12.0 
  npmGlobalPackages:
    gatsby-cli: 2.19.1
    gatsby: 2.31.1

**Comment by LekoArts** [comment] 2021-02-10 08:40
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-02-25 08:39
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-02-25 08:39 UTC
Labels: status: needs reproduction, type: bug

**Comment by Technoh** [comment] 2021-02-26 13:01
I encountered the same issue. Here are the steps to reproduce I used to (re)create the problem:

1. Create a new Gatsby project using `gatsby new projectname`.
2. Create a new stylesheet in the project.
3. Include a `@font-face` directive in the new stylesheet and assign it inside a `font-family` directive for the `body` element. Use a different font than the default one assigned in `layout.css` (at the time of writing: **georgia**, **serif**).
4. Import the newly created stylesheet in gatsby-browser.js, as recommended in the [Styling Tutorial](https://www.gatsbyjs.com/docs/tutorial/part-two/).
5. Overwrite the index.js page with a page not using the Layout component. Inlude some text so as to easily identify the font used.
6. Start gatsby in development mode (e.g. `npm run develop`).
7. Check the font used.

In my case the font declared in layout.css (georgia) was overwriting the one specified in my stylesheet (public sans) _even in pages where I was not using the Layout component_.

**Comment by LekoArts** [comment] 2021-02-26 13:19
Normal CSS files are included on all pages, so this is expected behavior.

**Comment by Technoh** [comment] 2021-02-26 14:24
I see. That was not clear from the tutorials and documentation I read. Do you mean that as soon as a stylesheet is imported in at least one component it will (potentially) overwrite the styles declared in other stylesheets and modules across all pages? If that's the case, why would the Styling Tutorial recommend creating a separate stylesheet and including it in the `gatsby-browser.js` file? Also, is there any way to control the order of inclusion of these stylesheets, in order to prevent styles being overwritten?

Finally, the basic starter should not include a file named `layout.css` as it is unclear that this stylesheet is used across all pages and components. Maybe rename the file `global-styles.css` or something equivalent?
