### ISSUE TITLE
Don't print GraphQL query in the non-page component will not be run error in unused templates

### ISSUE THREAD

**Issue by vavra7** [gatsbyjs/gatsby#20413] opened 2020-01-04 19:22 UTC
I can not find out how to get rid of these warnings in console log during build time.

```
warn The GraphQL query in the non-page component "...some path..." will not be run.
```
Cause of warning is unused template and not GraphQL in non-page component at the first place.

Sice I use headless CMS for sourcing Gatsby I can not rely that CMS user creates always all page types for all Gatsby's templates. Thus it is common for me that some templates remain unused. I was looking for some "if" condition to prevent this warning but unsuccessfully.  So currently my log is filling with this misleading information. 

It would be nice to have a way how to say that unused templates can be intentional and do not printing warnings.

**Comment by sidharthachatterjee** [comment] 2020-01-10 12:34
> It would be nice to have a way how to say that unused templates can be intentional and do not printing warnings.

Great point. 

Perhaps we need a `/* eslint-disable */` style method to disable Gatsby warnings for cases like these since there isn't a way to know which templates are used. 

Or even better, maybe we need conditionally print these only if the template is used (cc @pieh tangentially related to our idea of AOT validation of queries but printing only if used)

**Comment by jsg2021** [comment] 2020-02-19 20:39
Or for shadowed templates.

**Comment by 454de6e** [comment] 2020-04-13 14:47
This is still a problem.

**Comment by davifantasia** [comment] 2020-05-28 13:46
This is still a problem.

**Comment by danielcaldas** [comment] 2020-06-02 07:11
### Steps to reproduce

I'm shadowing queries of a theme.

### Expected result

I should not get warnings. The queries should execute for page components.

### Actual result

```
success extract queries from components - 0.359s
warn The GraphQL query in the non-page component "/Users/dcaldas/dev/goodguydaniel.com/node_modules/@lekoarts/gatsby-theme-minimal-blog-core/src/templates/homepage-query.tsx" will not be run.
warn The GraphQL query in the non-page component "/Users/dcaldas/dev/goodguydaniel.com/node_modules/@lekoarts/gatsby-theme-minimal-blog-core/src/templates/post-query.tsx" will not be run.
Exported queries are only executed for Page components. It's possible you're
trying to create pages in your gatsby-node.js and that's failing for some
reason.
```

### Environment

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
    Yarn: 1.21.1 - ~/.yarn/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.61
    Edge: 83.0.478.44
    Firefox: 76.0.1
    Safari: 13.1
  npmPackages:
    gatsby: ^2.20.36 => 2.22.10
    gatsby-plugin-anchor-links: ^1.1.1 => 1.1.1
    gatsby-plugin-google-analytics: ^2.1.4 => 2.3.2
    gatsby-plugin-manifest: ^2.2.3 => 2.4.9
    gatsby-plugin-offline: ^2.2.4 => 2.2.10
    gatsby-plugin-sitemap: ^2.2.19 => 2.4.3
    gatsby-remark-autolink-headers: ^2.3.3 => 2.3.3
    gatsby-transformer-remark: ^2.8.13 => 2.8.13
  npmGlobalPackages:
    gatsby-cli: 2.12.34
```

**Comment by 454de6e** [comment] 2020-07-02 01:47
This is still a problem.

**Comment by LekoArts** [comment] 2020-07-02 06:00
I'll close this in favor of https://github.com/gatsbyjs/gatsby/issues/23729 as this has a reproduction and clearer description while being the same issue.

**Closed by LekoArts** 2020-07-02 06:00 UTC
Labels: help wanted, topic: themes

**Comment by Didier187** [comment] 2023-07-02 09:25
Make sure the queries have different names, that worked for my case.

> This is still a problem.
