### ISSUE TITLE
gatsby-source-wordpress error when querying comment author

### ISSUE THREAD

**Issue by stevenabadie** [gatsbyjs/gatsby#29998] opened 2021-03-04 16:14 UTC
## Description

When querying comments from allWpComment an error is returned if the comment author is also queried.

#### Gatsby plugin versions:

- gatsby: v3.0.0
- gatsby-source-wordpress: v 5.0.0

#### Wordpress plugin versions:

- WP GraphQLL v1.2.5
- WP Gatsby v1.0.6

#### Steps
From local Gatsby GraphiQL query:
```
query MyQuery {
  allWpComment {
    nodes {
      content
      author {
        node {
          id
        }
      }
    }
  }
}
```

You should receive an error response message of **"Abstract type \"WpCommenter\" was resolve to a type \"CommentAuthor\" that does not exist inside schema.**"

### Expected result

WpComment query should return comment author

### Actual result

WpComment query returns error message "Abstract type \"WpCommenter\" was resolve to a type \"CommentAuthor\" that does not exist inside schema."

### Environment

System:
    OS: Linux 5.8 Pop!_OS 20.10
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.7.0 - ~/.nvm/versions/node/v14.7.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v14.7.0/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 86.0
  npmPackages:
    gatsby: ^3.0.0 => 3.0.0
    gatsby-plugin-image: ^1.0.0 => 1.0.0
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0
    gatsby-plugin-sharp: ^3.0.0 => 3.0.0
    gatsby-plugin-sitemap: ^3.0.0 => 3.0.0
    gatsby-source-filesystem: ^3.0.0 => 3.0.0
    gatsby-source-wordpress: ^5.0.0 => 5.0.0
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0
  npmGlobalPackages:
    gatsby-cli: 2.19.2

**Comment by TylerBarnes** [comment] 2021-03-24 21:03
Closing this as a duplicate of #30311 a fixed has been merged in https://github.com/gatsbyjs/gatsby/pull/30358 and will go out in the next release.

**Closed by TylerBarnes** 2021-03-24 21:03 UTC
Labels: topic: WordPress, type: bug
