### ISSUE TITLE
Self-hosted fonts requested in every page of the project

### ISSUE THREAD

**Issue by tf-currenxie** [gatsbyjs/gatsby#18582] opened 2019-10-14 02:16 UTC
Problem: Each font is requested in the every page of the project.
Question: What am I doing wrong?

Env: **dev**

**My layout file:**

```
...
import normalize from 'styles/normalize'
import fonts from 'styles/fonts'
...

export const MainLayout: FC = ({ children }) => (
  <StaticQuery
    ...
    `}
    render={(data: StaticQueryProps) => (
      <Root>
        <Helmet
          title={data.site.siteMetadata.title}
          meta={[
            { name: 'description', content: data.site.siteMetadata.description },
            { name: 'keywords', content: data.site.siteMetadata.keywords }
          ]}
        />
        <Global styles={() => css([normalize, fonts])} />
        <Header />
        <Main>{children}</Main>
        <Footer />
      </Root>
    )}
  />
)
```

**styles/fonts file:**

```
import StyreneBRegularWoff from 'content/fonts/StyreneB-Regular-Web.woff'
import StyreneBRegularWoff2 from 'content/fonts/StyreneB-Regular-Web.woff2'
import StyreneBMediumWoff from 'content/fonts/StyreneB-Medium-Web.woff'
import StyreneBMediumWoff2 from 'content/fonts/StyreneB-Medium-Web.woff2'

export default `
  @font-face {
    font-family: 'Styrene B Regular';
    src: url('${StyreneBRegularWoff2}') format('woff2'),
    url('${StyreneBRegularWoff}') format('woff');
    font-weight: 400;
    font-style: normal;
    font-stretch: normal;
  }
  
  @font-face {
    font-family: 'Styrene B Medium';
    src: url('${StyreneBMediumWoff2}') format('woff2'),
    url('${StyreneBMediumWoff}') format('woff');
    font-weight: 500;
    font-style: normal;
    font-stretch: normal;
  }
`
```

**styles/normalize file:**

```
export default `
  body {
    font-family: 'Styrene B Regular';
  }

  strong {
    font-family: 'Styrene B Medium';
  }
`
```

<img width="422" alt="Screenshot 2019-10-14 at 10 14 47 AM" src="https://user-images.githubusercontent.com/40813720/66726393-b3628380-ee6b-11e9-8c8b-ffb15688361a.png">

**Comment by universse** [comment] 2019-10-14 05:02
Are you using `gatsby-plugin-layout` for your Layout?

**Comment by tf-currenxie** [comment] 2019-10-14 05:10
No

```
const IndexPage: FC<IndexPageProps> = props => (
  <MainLayout>...</MainLayout>
)

export default IndexPage
```

**Comment by universse** [comment] 2019-10-14 05:16
Can you try moving this to `gatsby-browser.js`

```
import fonts from 'styles/normalize'
import fonts from 'styles/fonts'
```

**Comment by tf-currenxie** [comment] 2019-10-14 06:16
Works ! Thanks a lot !

***gatsby-browser.js file: ***

```
import React from 'react'
import { Global, css } from '@emotion/core'

import fonts from './src/styles/fonts'

export const wrapPageElement = ({ element }) => {
  return (
    <>
      <Global styles={() => css(fonts)} />
      {element}
    </>
  )
}
```

**Comment by universse** [comment] 2019-10-14 06:26
You are welcome. The problem is because `<Global styles={() => css([normalize, fonts])} />` is un-mounting and re-mounting every time you navigate from page to page, causing duplicated requests.

**Closed by universse** 2019-10-14 06:26 UTC
