### ISSUE TITLE
Node files not passed to gatsbyRemarkPlugins

### ISSUE THREAD

**Issue by pepibumur** [gatsbyjs/gatsby#17970] opened 2019-09-28 11:19 UTC
## Description
I moved from Markdown remark to the Gatsby Plugin MDX to generate content from markdown files. After the migration, the plugin [gatsby-remark-social-cards](https://www.npmjs.com/package/gatsby-remark-social-cards) started throwing errors because it can't find the `fields.slug` attribute.

I have a `onCreateNode` hook to create that field, but it seems the `gatsby-plugin-mdx` is not passing the fields down to the `gatsbyRemarkPlugins`.

### Steps to reproduce

1. Add and configure `gatsby-plugin-mdx` to an existing website.
2. Add a Markdown file to be processed by the plubing.
3. Add the following to the `gatsby-node.js` file:

```js
const { createFilePath } = require(`gatsby-source-filesystem`)
const slugify = require("slug")
const path = require(`path`)

exports.onCreateNode = ({ node, getNode, actions }) => {
  const { createNodeField } = actions
  if (node.internal.type === `Mdx`) {
    const internalNode = getNode(node.internal)
    const filename = createFilePath({ node, getNode })
    createNodeField({ node, name: `slug`, value: filename })
  }
}
```

4. Add and configure the `gatsby-remark-social-cards` plugin.

### Expected result

The generation of the website should succeed and the social cards generated.

### Actual result

The generation of the cards fails because the `node.fields.slug` attribute is missing.

### Environment

```

  System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.10.0 - /var/folders/l5/mb8_rrsj3qd6dzfs9csgm6xc0000gn/T/yarn--1569669581709-0.31435177517272384/node
    Yarn: 1.17.3 - /var/folders/l5/mb8_rrsj3qd6dzfs9csgm6xc0000gn/T/yarn--1569669581709-0.31435177517272384/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.10 - /Users/pedropinera/.pyenv/shims/python
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 69.0.1
    Safari: 13.0.1
  npmPackages:
    gatsby: ^2.15.14 => 2.15.26 
    gatsby-image: ^2.0.34 => 2.2.21 
    gatsby-plugin-feed: ^2.0.15 => 2.3.13 
    gatsby-plugin-manifest: ^2.0.24 => 2.2.18 
    gatsby-plugin-mdx: ^1.0.44 => 1.0.44 
    gatsby-plugin-offline: ^3.0.11 => 3.0.11 
    gatsby-plugin-react-helmet: ^3.0.10 => 3.1.8 
    gatsby-plugin-sharp: ^2.0.29 => 2.2.25 
    gatsby-plugin-theme-ui: ^0.2.43 => 0.2.43 
    gatsby-plugin-typography: ^2.2.10 => 2.3.8 
    gatsby-remark-autolink-headers: ^2.0.16 => 2.1.11 
    gatsby-remark-embed-gist: ^1.1.7 => 1.1.9 
    gatsby-remark-images: ^3.0.10 => 3.1.23 
    gatsby-remark-social-cards: git@github.com:pepibumur/gatsby-remark-social-cards.git#18e9c98b9325d5d16911125a6e9be7394606d407 => 0.4.1 
    gatsby-source-filesystem: ^2.0.27 => 2.1.26 
    gatsby-theme-micro-blog: ^1.1.2 => 1.1.3 
    gatsby-transformer-remark: ^2.6.24 => 2.6.24 
    gatsby-transformer-sharp: ^2.1.17 => 2.2.17 
  npmGlobalPackages:
    gatsby-cli: 2.6.0
```

**Comment by jonniebigodes** [comment] 2019-09-29 18:24
@pepibumur can you make a reproduction following [these steps](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) so that it can be looked at in more detail?

**Comment by pepibumur** [comment] 2019-09-30 15:10
Sure, [here](https://github.com/pepibumur/gatsby-mdx-slug-bug) is the repository. You can run `yarn build` and the build should fail.

**Comment by jonniebigodes** [comment] 2019-10-01 21:15
@pepibumur i've been testing this and it seems there's some incompatibilities between the two plugins.
Here are the steps i took to triage this:
- Cloned your repo and installed the dependencies.
- Added some more pages for testing purposes.
- Issue on the console `yarn build` and i'm presented with the error you've supplied in the description.
- Issue `gatsby clean && yarn develop`, to purge the `.cache` and `public` folders and generate a development build, as gatsby in development mode is more permissive. The issue pops up, but one thing was brought to my attention while checking the output in the console. And that is the cards are generated, despite the error being thrown, i confirmed it by going to the `public` folder and seeing a folder created for the page and inside the card was present.
- Opened up the corresponding file for the plugin, namely `node_modules/gatsby-remark-social-cards/index.js` and inserted the following:
```js
 console.log(`markdownNode plugin:${JSON.stringify(markdownNode, null, 2)}`);
```
- Issued `gatsby clean && gatsby develop`, so that `.cache` and `public` folders are deleted and with that the cards already created. And the output i got was the following:
```shell
markdownNode plugin:{
  "id": "bff3ae58-23dc-5e67-bbe5-221c15966256",
  "children": [],
  "parent": "2636b4af-e32e-5edb-8e87-e2753dd1d7b6",
  "internal": {
    "content": "THis is some random text. Below is a random component imported.\r\n",
    "type": "Mdx",
    "contentDigest": "44f0532e987cd18e87ba7fdfa53a17f9",
    "counter": 24,
    "owner": "gatsby-plugin-mdx"
  },
  "frontmatter": {
    "title": ""
  },
  "exports": {},
  "rawBody": "THis is some random text. Below is a random component imported.\r\n",
  "fileAbsolutePath": "...../test_pepibumur/gatsby-mdx-slug-bug/pages/second-page.mdx"
}
markdownNode plugin:{
  "id": "2d80cb9e-880a-5185-be48-158f6f12320a",
  "children": [],
  "parent": "4760649b-79e5-576a-bbcd-7a7d51b87a74",
  "internal": {
    "content": "---\r\ntitle: My Page\r\n---\r\nThis is a test",
    "type": "Mdx",
    "contentDigest": "eea5d69ee6990fffee8ed99377dc8c04",
    "counter": 25,
    "owner": "gatsby-plugin-mdx"
  },
  "frontmatter": {
    "title": "My Page"
  },
  "exports": {},
  "rawBody": "---\r\ntitle: My Page\r\n---\r\nThis is a test",
  "fileAbsolutePath": "...../test_pepibumur/gatsby-mdx-slug-bug/pages/my-page.mdx"
}

 ERROR #11321  PLUGIN

"gatsby-plugin-mdx" threw an error while running the onCreateNode lifecycle:

Cannot read property 'slug' of undefined



  TypeError: Cannot read property 'slug' of undefined

  - index.js:111 module.exports
    [gatsby-mdx-slug-bug]/[gatsby-remark-social-cards]/index.js:111:60

  - get-source-plugins-as-remark-plugins.js:57 transformer
    [gatsby-mdx-slug-bug]/[gatsby-plugin-mdx]/utils/get-source-plugins-as-remark-plugins.js:57:17

  - wrap.js:25 wrapped
    [gatsby-mdx-slug-bug]/[trough]/wrap.js:25:19

  - index.js:57 next
    [gatsby-mdx-slug-bug]/[trough]/index.js:57:24

  - wrap.js:55 done
    [gatsby-mdx-slug-bug]/[trough]/wrap.js:55:16

  - wrap.js:62 then
    [gatsby-mdx-slug-bug]/[trough]/wrap.js:62:5

  - wrap.js:45 wrapped
    [gatsby-mdx-slug-bug]/[trough]/wrap.js:45:9

  - index.js:57 next
    [gatsby-mdx-slug-bug]/[trough]/index.js:57:24

  - wrap.js:55 done
    [gatsby-mdx-slug-bug]/[trough]/wrap.js:55:16

  - wrap.js:62 then
    [gatsby-mdx-slug-bug]/[trough]/wrap.js:62:5

  - wrap.js:45 wrapped
    [gatsby-mdx-slug-bug]/[trough]/wrap.js:45:9

  - index.js:57 next
    [gatsby-mdx-slug-bug]/[trough]/index.js:57:24

  - index.js:31 Object.run
    [gatsby-mdx-slug-bug]/[trough]/index.js:31:10

  - index.js:295 executor
    [gatsby-mdx-slug-bug]/[unified]/index.js:295:20

  - index.js:292 Function.run
    [gatsby-mdx-slug-bug]/[unified]/index.js:292:5

  - index.js:26 pipelineRun
    [gatsby-mdx-slug-bug]/[unified]/index.js:26:5



 ERROR #11321  PLUGIN

"gatsby-plugin-mdx" threw an error while running the onCreateNode lifecycle:

Cannot read property 'slug' of undefined



  TypeError: Cannot read property 'slug' of undefined

  - index.js:111 module.exports
    [gatsby-mdx-slug-bug]/[gatsby-remark-social-cards]/index.js:111:60

  - get-source-plugins-as-remark-plugins.js:57 transformer
    [gatsby-mdx-slug-bug]/[gatsby-plugin-mdx]/utils/get-source-plugins-as-remark-plugins.js:57:17

  - wrap.js:25 wrapped
    [gatsby-mdx-slug-bug]/[trough]/wrap.js:25:19

  - index.js:57 next
    [gatsby-mdx-slug-bug]/[trough]/index.js:57:24

  - wrap.js:55 done
    [gatsby-mdx-slug-bug]/[trough]/wrap.js:55:16

  - wrap.js:62 then
    [gatsby-mdx-slug-bug]/[trough]/wrap.js:62:5

  - wrap.js:45 wrapped
    [gatsby-mdx-slug-bug]/[trough]/wrap.js:45:9

  - index.js:57 next
    [gatsby-mdx-slug-bug]/[trough]/index.js:57:24

  - wrap.js:55 done
    [gatsby-mdx-slug-bug]/[trough]/wrap.js:55:16

  - wrap.js:62 then
    [gatsby-mdx-slug-bug]/[trough]/wrap.js:62:5

  - wrap.js:45 wrapped
    [gatsby-mdx-slug-bug]/[trough]/wrap.js:45:9

  - index.js:57 next
    [gatsby-mdx-slug-bug]/[trough]/index.js:57:24

  - index.js:31 Object.run
    [gatsby-mdx-slug-bug]/[trough]/index.js:31:10

  - index.js:295 executor
    [gatsby-mdx-slug-bug]/[unified]/index.js:295:20

  - index.js:292 Function.run
    [gatsby-mdx-slug-bug]/[unified]/index.js:292:5

  - index.js:26 pipelineRun
    [gatsby-mdx-slug-bug]/[unified]/index.js:26:5


success source and transform nodes - 3.518 s
success Add explicit types - 0.018 s
success Add inferred types - 0.286 s
success Processing types - 0.158 s
success building schema - 0.786 s
markdownNode plugin:{
  "id": "bff3ae58-23dc-5e67-bbe5-221c15966256",
  "children": [],
  "parent": "2636b4af-e32e-5edb-8e87-e2753dd1d7b6",
  "internal": {
    "content": "THis is some random text. Below is a random component imported.\r\n",
    "type": "Mdx",
    "contentDigest": "44f0532e987cd18e87ba7fdfa53a17f9",
    "counter": 24,
    "owner": "gatsby-plugin-mdx",
    "fieldOwners": {
      "slug": "default-site-plugin"
    }
  },
  "frontmatter": {
    "title": ""
  },
  "exports": {},
  "rawBody": "THis is some random text. Below is a random component imported.\r\n",
  "fileAbsolutePath": "..../test_pepibumur/gatsby-mdx-slug-bug/pages/second-page.mdx",
  "fields": {
    "slug": "/second-page/"
  }
}
markdownNode plugin:{
  "id": "2d80cb9e-880a-5185-be48-158f6f12320a",
  "children": [],
  "parent": "4760649b-79e5-576a-bbcd-7a7d51b87a74",
  "internal": {
    "content": "---\r\ntitle: My Page\r\n---\r\nThis is a test",
    "type": "Mdx",
    "contentDigest": "eea5d69ee6990fffee8ed99377dc8c04",
    "counter": 25,
    "owner": "gatsby-plugin-mdx",
    "fieldOwners": {
      "slug": "default-site-plugin"
    }
  },
  "frontmatter": {
    "title": "My Page"
  },
  "exports": {},
  "rawBody": "---\r\ntitle: My Page\r\n---\r\nThis is a test",
  "fileAbsolutePath": "..../test_pepibumur/gatsby-mdx-slug-bug/pages/my-page.mdx",
  "fields": {
    "slug": "/my-page/"
  }
}
success createPages - 1.448 s
success createPagesStatefully - 0.641 s
success onPreExtractQueries - 0.006 s
success update schema - 0.044 s
Generated Twitter Card: public\second-page\twitter-card.jpg
Generated Twitter Card: public\my-page\twitter-card.jpg
success extract queries from components - 0.959 s
success write out requires - 0.040 s
success write out redirect data - 0.002 s
success onPostBootstrap - 0.003 s
⠀
info bootstrap finished - 42.270 s
⠀
success run static queries - 0.015 s — 1/1 124.45 queries/second
success run page queries - 0.031 s — 4/4 153.28 queries/second
success start webpack server - 5.901 s — 1/1 0.59 pages/second
```
As you can see it makes two passes, on the first iteration there's no `fields` property and the error is thrown, but on the second pass the property is present and the plugin works as expected.
- Created a new gatsby site based on the hello world and added the necessary dependencies but this time based on `gatsby-transfomer-remark`, and configured it to match yours, to see what could be the difference.
- After the site was created and the dependencies installed i modified the plugin `index.js` with the same `console.log` to check the output. 
- Issued `gatsby develop` to generate a development build and see what is the output and i'm presented with the following:
```shell
success open and validate gatsby-configs - 0.024 s
success load plugins - 0.746 s
success onPreInit - 0.005 s
success initialize cache - 0.010 s
success copy gatsby files - 0.511 s
success onPreBootstrap - 0.014 s
success source and transform nodes - 0.124 s
success Add explicit types - 0.011 s
success Add inferred types - 0.174 s
success Processing types - 0.126 s
success building schema - 0.755 s
success createPages - 0.043 s
success createPagesStatefully - 0.104 s
success onPreExtractQueries - 0.002 s
success update schema - 0.045 s
success extract queries from components - 0.294 s
success write out requires - 0.032 s
success write out redirect data - 0.002 s
success onPostBootstrap - 0.001 s
⠀
info bootstrap finished - 10.224 s
⠀
success run static queries - 0.016 s — 1/1 113.10 queries/second
markdownNode plugin:{
  "id": "2f7415ee-2883-575e-b110-5207ee071a40",
  "children": [],
  "parent": "e2f11126-67ee-5c49-8b07-77900264dfb5",
  "internal": {
    "content": "\r\nThis is a test",
    "type": "MarkdownRemark",
    "contentDigest": "92ff4502deb6ae20b2d302b7c6c0259d",
    "counter": 23,
    "owner": "gatsby-transformer-remark",
    "fieldOwners": {
      "slug": "default-site-plugin"
    }
  },
  "frontmatter": {
    "title": "My Page"
  },
  "excerpt": "",
  "rawMarkdownBody": "\r\nThis is a test",
  "fileAbsolutePath": "...../test_pepibumur/test-remark-social-plugins/pages/my-page.md",
  "fields": {
    "slug": "/my-page/"
  }
}
markdownNode plugin:{
  "id": "53a98460-71cb-5e8b-817c-487d71f0e262",
  "children": [],
  "parent": "6a02f401-8e5a-584c-9903-662362dec04b",
  "internal": {
    "content": "This is another test",
    "type": "MarkdownRemark",
    "contentDigest": "d1967c7aebfe029e735c3cdad9ebc634",
    "counter": 24,
    "owner": "gatsby-transformer-remark",
    "fieldOwners": {
      "slug": "default-site-plugin"
    }
  },
  "frontmatter": {
    "title": "This is a second page"
  },
  "excerpt": "",
  "rawMarkdownBody": "This is another test",
  "fileAbsolutePath": "..../test_pepibumur/test-remark-social-plugins/pages/second-page.md",
  "fields": {
    "slug": "/second-page/"
  }
}
success run page queries - 0.135 s — 4/4 30.92 queries/second
Generated Twitter Card: public\my-page\twitter-card.jpg
Generated Twitter Card: public\second-page\twitter-card.jpg
success start webpack server - 1.810 s — 1/1 3.75 pages/second
 DONE  Compiled successfully in 3273ms
```
As you can see there's only one pass while using `gatsby-transformer-remark` and the slugs field is already present.

- Based on this test results and checking the commit history of the plugin in question and releases information, this was released before the support for mdx was made official in gatsby.
- Went back to your reproduction and modified the plugin's index file to the following:
```js
module.exports = ({ markdownNode }, options) => {
  console.log(`markdownNode plugin:${JSON.stringify(markdownNode, null, 2)}`);
  const post = markdownNode.frontmatter;
  if (markdownNode.fields) {
    const output = path.join(
      "./public",
      markdownNode.fields.slug,
      "twitter-card.jpg"
    );

    generateCard(post, options)
      .then(image =>
        image
          .writeAsync(output)
          .then(() => console.log("Generated Twitter Card:", output))
          .catch(err => console.log("ERROR GENERATING TWITTER CARD", err))
      )
      .catch(console.error);
  }
  /* const output = path.join("./public", markdownNode.fields.slug, "twitter-card.jpg");

  generateCard(post, options).then(image => image.writeAsync(output).then(() => console.log("Generated Twitter Card:", output)).catch(err => console.log("ERROR GENERATING TWITTER CARD", err))).catch(console.error); */
};
```
- Issued `gatsby clean && gatsby develop` and the development goes through with mdx. 
- Then stopped the development server and issued `gatsby clean && gatsby build` to once again remove the folders and this time to generate a production build and the output was the following:
```shell
$ gatsby build
success open and validate gatsby-configs - 0.032 s
success load plugins - 0.919 s
success onPreInit - 0.006 s
success delete html and css files from previous builds - 0.011 s
success initialize cache - 0.013 s
success copy gatsby files - 0.237 s
success onPreBootstrap - 0.026 s
markdownNode plugin:{
  "id": "2d80cb9e-880a-5185-be48-158f6f12320a",
  "children": [],
  "parent": "4760649b-79e5-576a-bbcd-7a7d51b87a74",
  "internal": {
    "content": "---\r\ntitle: My Page\r\n---\r\nThis is a test",
    "type": "Mdx",
    "contentDigest": "eea5d69ee6990fffee8ed99377dc8c04",
    "counter": 25,
    "owner": "gatsby-plugin-mdx"
  },
  "frontmatter": {
    "title": "My Page"
  },
  "exports": {},
  "rawBody": "---\r\ntitle: My Page\r\n---\r\nThis is a test",
  "fileAbsolutePath": "...../test_pepibumur/gatsby-mdx-slug-bug/pages/my-page.mdx"
}
markdownNode plugin:{
  "id": "bff3ae58-23dc-5e67-bbe5-221c15966256",
  "children": [],
  "parent": "2636b4af-e32e-5edb-8e87-e2753dd1d7b6",
  "internal": {
    "content": "THis is some random text. Below is a random component imported.\r\n",
    "type": "Mdx",
    "contentDigest": "44f0532e987cd18e87ba7fdfa53a17f9",
    "counter": 26,
    "owner": "gatsby-plugin-mdx"
  },
  "frontmatter": {
    "title": ""
  },
  "exports": {},
  "rawBody": "THis is some random text. Below is a random component imported.\r\n",
  "fileAbsolutePath": "...../test_pepibumur/gatsby-mdx-slug-bug/pages/second-page.mdx"
}
markdownNode plugin:{
  "id": "5f2e25a8-fb4f-5244-bdbf-ee7b610e6d91",
  "children": [],
  "parent": "752d0954-5cc0-5173-84bd-e85d75b552f1",
  "internal": {
    "content": "---\r\ntitle: Third page\r\n---\r\nimport DummyComponent from '../src/components/random-component'\r\n\r\n\r\nThis is a third page\r\n\r\nThis is a mdx component\r\n<DummyComponent/>",
    "type": "Mdx",
    "contentDigest": "d5fa91bc634fa1d45f86bb6ec830a2a2",
    "counter": 27,
    "owner": "gatsby-plugin-mdx"
  },
  "frontmatter": {
    "title": "Third page"
  },
  "exports": {},
  "rawBody": "---\r\ntitle: Third page\r\n---\r\nimport DummyComponent from '../src/components/random-component'\r\n\r\n\r\nThis is a third page\r\n\r\nThis is a mdx component\r\n<DummyComponent/>",
  "fileAbsolutePath": "...../test_pepibumur/gatsby-mdx-slug-bug/pages/third-page.mdx"
}
success source and transform nodes - 1.270 s
success Add explicit types - 0.018 s
success Add inferred types - 0.168 s
success Processing types - 0.074 s
success building schema - 0.386 s
markdownNode plugin:{
  "id": "2d80cb9e-880a-5185-be48-158f6f12320a",
  "children": [],
  "parent": "4760649b-79e5-576a-bbcd-7a7d51b87a74",
  "internal": {
    "content": "---\r\ntitle: My Page\r\n---\r\nThis is a test",
    "type": "Mdx",
    "contentDigest": "eea5d69ee6990fffee8ed99377dc8c04",
    "counter": 25,
    "owner": "gatsby-plugin-mdx",
    "fieldOwners": {
      "slug": "default-site-plugin"
    }
  },
  "frontmatter": {
    "title": "My Page"
  },
  "exports": {},
  "rawBody": "---\r\ntitle: My Page\r\n---\r\nThis is a test",
  "fileAbsolutePath": "...../test_pepibumur/gatsby-mdx-slug-bug/pages/my-page.mdx",
  "fields": {
    "slug": "/my-page/"
  }
}
markdownNode plugin:{
  "id": "bff3ae58-23dc-5e67-bbe5-221c15966256",
  "children": [],
  "parent": "2636b4af-e32e-5edb-8e87-e2753dd1d7b6",
  "internal": {
    "content": "THis is some random text. Below is a random component imported.\r\n",
    "type": "Mdx",
    "contentDigest": "44f0532e987cd18e87ba7fdfa53a17f9",
    "counter": 26,
    "owner": "gatsby-plugin-mdx",
    "fieldOwners": {
      "slug": "default-site-plugin"
    }
  },
  "frontmatter": {
    "title": ""
  },
  "exports": {},
  "rawBody": "THis is some random text. Below is a random component imported.\r\n",
  "fileAbsolutePath": ..../test_pepibumur/gatsby-mdx-slug-bug/pages/second-page.mdx",
  "fields": {
    "slug": "/second-page/"
  }
}
markdownNode plugin:{
  "id": "5f2e25a8-fb4f-5244-bdbf-ee7b610e6d91",
  "children": [],
  "parent": "752d0954-5cc0-5173-84bd-e85d75b552f1",
  "internal": {
    "content": "---\r\ntitle: Third page\r\n---\r\nimport DummyComponent from '../src/components/random-component'\r\n\r\n\r\nThis is a third page\r\n\r\nThis is a mdx component\r\n<DummyComponent/>",
    "type": "Mdx",
    "contentDigest": "d5fa91bc634fa1d45f86bb6ec830a2a2",
    "counter": 27,
    "owner": "gatsby-plugin-mdx",
    "fieldOwners": {
      "slug": "default-site-plugin"
    }
  },
  "frontmatter": {
    "title": "Third page"
  },
  "exports": {},
  "rawBody": "---\r\ntitle: Third page\r\n---\r\nimport DummyComponent from '../src/components/random-component'\r\n\r\n\r\nThis is a third page\r\n\r\nThis is a mdx component\r\n<DummyComponent/>",
  "fileAbsolutePath": "..../test_pepibumur/gatsby-mdx-slug-bug/pages/third-page.mdx",
  "fields": {
    "slug": "/third-page/"
  }
}
success createPages - 0.287 s
success createPagesStatefully - 0.263 s
success onPreExtractQueries - 0.279 s
success update schema - 0.047 s
Generated Twitter Card: public\second-page\twitter-card.jpg
Generated Twitter Card: public\my-page\twitter-card.jpg
Generated Twitter Card: public\third-page\twitter-card.jpg
success extract queries from components - 0.248 s
success write out requires - 0.010 s
success write out redirect data - 0.004 s
success onPostBootstrap - 0.003 s
⠀
info bootstrap finished - 9.461 s
⠀
success run static queries - 0.015 s — 1/1 95.53 queries/second
success Building production JavaScript and CSS bundles - 8.742 s
success Rewriting compilation hashes - 0.003 s
success run page queries - 0.031 s — 4/4 142.36 queries/second
⠧ Building static HTML for pages
DummyTemplate:/my-page/
layout pathname:/my-page/
DummyTemplate:/second-page/
layout pathname:/second-page/
DummyTemplate:/third-page/
success Building static HTML for pages - 2.341 s — 4/4 2.81 pages/second
info Done building in 20.873 sec

Done in 21.16s.
```
As you can see no errors and i checked and the cards were present.

If you want and you're willing fork the plugin's repo and make this small change and submit a pr in the hopes that it will be approved and the plugin updated and you particularly in this case and other people can begin to use it with mdx. Or if not i can make the change and submit the pull request.

Feel free to provide feedback so that we can close this issue or continue to work on it until we find a suitable solution. And sorry for not being able to provide you with a more suitable solution for your issue.

**Comment by pepibumur** [comment] 2019-10-07 10:24
That worked! Thank you very much for debugging the issue @jonniebigodes and giving me a solution.

**Comment by jonniebigodes** [comment] 2019-10-13 18:48
@pepibumur as the issue is resolved and now it can handle the mdx card generation via the pull request that i've submitted to the repo of the plugin creator. If you don't mind, i'm going to close this issue as it's resolved. Should any issues resurface feel free to re-open it.

**Closed by jonniebigodes** 2019-10-13 18:48 UTC
Labels: status: awaiting author response
