### ISSUE TITLE
gatsby-plugin-offline plugin. When I use him and do refresh I see the blank line on whole length of page

### ISSUE THREAD

**Issue by ArmenMelk** [gatsbyjs/gatsby#23822] opened 2020-05-06 04:26 UTC
gatsby-plugin-offline plugin. When I use him and do refresh I see the blank line on whole length of page but in hard refresh(ctr+f5) it's work as expected..

gatsby config.js file conf
{
      resolve: `gatsby-plugin-offline`,
      options: {
        precachePages: [`/program/`],
        appendScript: require.resolve(`./static/sw.js`),
      },
    },

![Screenshot_5](https://user-images.githubusercontent.com/34882469/81138427-1be19100-8f73-11ea-9899-2f8a3b17f535.png)

The same issue on all pages.
How to fix it ?

**Comment by vladar** [comment] 2020-05-06 17:10
Hi @ArmenMelk !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by danabrit** [comment] 2020-06-02 22:38
Closing this issue due to no reproduction within 7 days. If you would like to re-open it with a minimal reproduction, we'd be happy to take a look. Thank you!

**Closed by danabrit** 2020-06-02 22:38 UTC
Labels: status: needs reproduction, topic: PWA, topic: frontend-core, type: bug
