### ISSUE TITLE
I didn't get all wordpress query in graphql querylist

### ISSUE THREAD

**Issue by bhautik11** [gatsbyjs/gatsby#10600] opened 2018-12-21 06:36 UTC
## Description

I didn't get all wordpress graphql querylist in my localhost.

### Steps to reproduce
My current gatsby-config.js file
gatsby-config.js
```javascript
module.exports = {
  siteMetadata: {
    title: 'Gatsby Default Starter',
    description:
      'Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.',
    author: '@gatsbyjs',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    'gatsby-transformer-sharp',
    'gatsby-plugin-sharp',
    {
      resolve: 'gatsby-source-wordpress',
      options: {
        baseUrl: 'bhautik11.wordpress.com',
        protocol: 'https',
        hostingWPCOM: true,
        useACF: false,
        auth: {
          wpcom_app_clientSecret:
            '****',
          wpcom_app_clientId: '***',
          wpcom_user: '*****',
          wpcom_pass: '****',
        },
        verboseOutput: false,
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.app/offline
    // 'gatsby-plugin-offline',
  ],
}
```

Also I tried ["using-wordpress"](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-wordpress) example gatsby-config.js file code but it's also didn't show all wordpress querylist(allWordpressPost, allWordpressWpMe, etc).

### Expected result

I want to hit allWordpressPost query using "http://localhost:8000/___graphql"

### Actual result

It didn't saw allWordpressPost query in "http://localhost:8000/___graphql" query list

### Environment
```
  System:
    OS: macOS 10.14.2
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.10.0 - /usr/local/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 71.0.3578.98
    Firefox: 63.0.3
    Safari: 12.0.2
  npmPackages:
    gatsby: ^2.0.53 => 2.0.53 
    gatsby-image: ^2.0.25 => 2.0.25 
    gatsby-plugin-glamor: ^2.0.7 => 2.0.7 
    gatsby-plugin-manifest: ^2.0.9 => 2.0.9 
    gatsby-plugin-offline: ^2.0.16 => 2.0.16 
    gatsby-plugin-react-helmet: ^3.0.2 => 3.0.2 
    gatsby-plugin-sharp: ^2.0.15 => 2.0.15 
    gatsby-plugin-typography: ^2.2.2 => 2.2.2 
    gatsby-source-filesystem: ^2.0.8 => 2.0.8 
    gatsby-source-wordpress: ^3.0.20 => 3.0.20 
    gatsby-transformer-sharp: ^2.1.9 => 2.1.9 
  npmGlobalPackages:
    gatsby-cli: 2.4.6
```

**Comment by sidharthachatterjee** [comment] 2018-12-21 16:01
Hey @bhautik11 

Could you please post a link to a reproduction repo if possible? That might help us debug this sooner. 

Thanks!

**Comment by jonniebigodes** [comment] 2018-12-21 18:48
@bhautik11 i've picked up your issue, and based on the information at hand, it looks like another issue that i commented. What i would like for you to do is to change your `gatsby-config.js` file to accomodate the following:
```javascript
includedRoutes: [
          "/*/*/posts",
          "/*/*/pages",
          "/*/*/media",
          "/*/*/categories",
          "/*/*/tags",
          "/*/*/taxonomies",
          "/*/*/users",
        ],
```
Transforming it into the code block bellow:

```javascript
module.exports = {
  siteMetadata: {
    title: 'Gatsby Default Starter',
    description:
      'Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.',
    author: '@gatsbyjs',
  },
  plugins: [
    'gatsby-plugin-react-helmet',
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    'gatsby-transformer-sharp',
    'gatsby-plugin-sharp',
    {
      resolve: 'gatsby-source-wordpress',
      options: {
        baseUrl: 'bhautik11.wordpress.com',
        protocol: 'https',
        hostingWPCOM: true,
        useACF: false,
        auth: {
          wpcom_app_clientSecret:
            '****',
          wpcom_app_clientId: '***',
          wpcom_user: '*****',
          wpcom_pass: '****',
        },
        includedRoutes: [ //<-add this bit
          "/*/*/posts",
          "/*/*/pages",
          "/*/*/media",
          "/*/*/categories",
          "/*/*/tags",
          "/*/*/taxonomies",
          "/*/*/users",
        ],
        verboseOutput: false,
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.app/offline
    // 'gatsby-plugin-offline',
  ],
}
```
With that you should be able to get access to the posts as you can see bellow.
![allwordpresspost](https://user-images.githubusercontent.com/22988955/50358288-aaa56780-0550-11e9-9271-475dc46b3263.png)
And access to the list of graphql queries like shown bellow
![allwordpressavailable](https://user-images.githubusercontent.com/22988955/50358312-c446af00-0550-11e9-928c-4b952d7b2931.png)

Feel free to provide some feedback to see if what i've mentioned helped out in solving your issue.

**Comment by jonniebigodes** [comment] 2018-12-28 01:01
@bhautik11 once again with the information available, I went onto your site and checked if the permalinks were in plain mode and from what i've seen, while navigating, that is not the case, wich removes one possibility out of the equation.
And assuming that you've added the includedroutes part to the `gatsby-config.js` file under the wordpress plugin configuration, It led me to the following possibility. 
If you can, please delete  both .cache and public folders. When that's done, issue `gatsby develop` and see if everything works out fine, no errors are thrown. The reasoning behind clearing both folders, is that and this based on personal experience, some stale data might still be lingering wich could prevent the correct data to be available.

**Comment by bhautik11** [comment] 2018-12-28 11:53
Now, It's working fine...Problem was that when I run "gatsby develop" command then every time index.html file changed.

**Comment by jonniebigodes** [comment] 2018-12-28 17:20
@bhautik11 glad you got it working. I'm closing this, but feel free to open a new issue should any problem arise. Thanks for using Gatsby 👍.

**Closed by jonniebigodes** 2018-12-28 17:20 UTC
Labels: status: needs reproduction, type: question or discussion
