### ISSUE TITLE
GraphQl failure on imageSharp query

### ISSUE THREAD

**Issue by rcisneros138** [gatsbyjs/gatsby#7667] opened 2018-08-27 03:33 UTC
I'm attempting to use a basic query to pull images and utilize Image Sharp. I mostly followed [this](https://medium.com/@kyle.robert.gill/ridiculously-easy-image-optimization-with-gatsby-js-59d48e15db6e) tutorial.

my query in layout.js:
```
   <StaticQuery  
          query={graphql`
          query SiteTitleQuery {
            site {
              siteMetadata {
                title
              }
            }
            wtf: imageSharp(id: { regex: "/PLEASEWORK.jpg/" }) {
              sizes(maxWidth: 1240) {
                ...GatsbyImageSharpSizes
              }
            }
          }
        `}
```

**However, I can't seem to shake an error property of id is 'undefined':** 

```
Errors:
  Cannot read property 'id' of undefined

  GraphQL request (7:3)
  6:   }
  7:   wtf: imageSharp(id: {regex: "/PLEASEWORK.jpg/"}) {
       ^
  8:     sizes(maxWidth: 1240) {

Plugin:
  none
Query:
  query SiteTitleQuery {
    site {
      siteMetadata {
        title
      }
    }
    wtf: imageSharp(id: {regex: "/PLEASEWORK.jpg/"}) {
      sizes(maxWidth: 1240) {
        ...GatsbyImageSharpSizes
      }
    }
  }

  fragment GatsbyImageSharpSizes on ImageSharpSizes {
    base64
    aspectRatio
    src
    srcSet
    sizes
  }
```

**I'm a novice to say the least with graphql, but the graphiql query seems to at least be finding some images. However, I'm not sure how my regex will ever work if the id never seems to contain my original file name:**

![query](https://user-images.githubusercontent.com/12632749/44638694-eb63ea00-a97d-11e8-9f0d-7d2b8607a096.png)

**to be frank I believe I must be fundamentally misunderstanding something about how these query's work, or don't have something configured correctly. I've spent hours on this, and would appreciate deeply any help that can be provided.**

extra info:

```
 System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i7-6660U CPU @ 2.40GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 9.3.0 - ~/.nvm/versions/node/v9.3.0/bin/node
    Yarn: 1.9.4 - /usr/local/bin/yarn
    npm: 5.5.1 - ~/.nvm/versions/node/v9.3.0/bin/npm
  Browsers:
    Chrome: 70.0.3528.4
    Firefox: 57.0.4
    Safari: 11.1.2
  npmPackages:
    gatsby: next => 2.0.0-rc.0
    gatsby-image: next => 2.0.0-rc.0
    gatsby-plugin-manifest: next => 2.0.2-rc.0
    gatsby-plugin-offline: next => 2.0.0-rc.0
    gatsby-plugin-react-helmet: next => 3.0.0-rc.0
    gatsby-plugin-sharp: ^2.0.0-rc.0 => 2.0.0-rc.0
    gatsby-plugin-styled-components: next => 3.0.0-rc.0
    gatsby-plugin-typography: next => 2.2.0-rc.0
    gatsby-remark-images: next => 2.0.1-rc.0
    gatsby-source-filesystem: next => 2.0.1-rc.0
    gatsby-transformer-remark: next => 2.1.1-rc.0
    gatsby-transformer-sharp: next => 2.1.1-rc.0
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```

my gatsby-config: 

```

 module.exports = {
  siteMetadata: {
    title: 'Integra',
  },
  pathPrefix: '/Integra',
  plugins: [
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/images`,
        name: `images`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        path: `${__dirname}/src/data`,
        name: `data`,
      },
    },
    {
      resolve: `gatsby-plugin-typography`,
      options: {
        pathToConfigModule: `src/utils/typography`,
      },
      resolve: `gatsby-plugin-styled-components`,
      options: {
        displayName: 'true',
      },
    },
    'gatsby-transformer-sharp',
    'gatsby-plugin-sharp',
    'gatsby-plugin-offline',
    'gatsby-plugin-react-helmet',
  ],
}
```

```
{
  "name": "gatsby-starter-default",
  "description": "Gatsby default starter",
  "dependencies": {
    "babel-plugin-styled-components": "^1.5.1",
    "gatsby": "next",
    "gatsby-image": "next",
    "gatsby-plugin-manifest": "next",
    "gatsby-plugin-offline": "next",
    "gatsby-plugin-react-helmet": "next",
    "gatsby-plugin-sharp": "^2.0.0-rc.0",
    "gatsby-plugin-styled-components": "next",
    "gatsby-plugin-typography": "next",
    "gatsby-remark-images": "next",
    "gatsby-source-filesystem": "next",
    "gatsby-transformer-remark": "next",
    "gatsby-transformer-sharp": "next",
    "react": "^16.4.2",
    "react-dom": "^16.4.2",
    "react-helmet": "^5.2.0",
    "react-waypoint": "^8.0.3",
    "styled-components": "^3.4.2"
  },
  "keywords": [
    "gatsby"
  ],
  "license": "MIT",
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write '**/*.js'",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "devDependencies": {
    "prettier": "^1.14.2"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/gatsbyjs/gatsby-starter-default"
  }
}


```

**Comment by LeKoArts** [comment] 2018-08-27 13:05
Duplicate of https://github.com/gatsbyjs/gatsby/issues/7661

Your tutorial is referencing Gatsby v1 but you're using v2. Some things changed including that you shouldn't query by id.

**Closed by LeKoArts** 2018-08-27 13:05 UTC
