### ISSUE TITLE
Generating SSR bundle failed on Gatsby Develop

### ISSUE THREAD

**Issue by jackbisceglia** [gatsbyjs/gatsby#24243] opened 2020-05-19 21:38 UTC
## Description
After I inititalized my Gatsby project with the CLI, I ran develop and got the error 'Generating SSR bundle failed'. It is pointing out an unexpected token "," in the file path generated in api-runner-ssr.js. It seems that because my laptop's username has a single quote in it ('), that it thinks the string closes there. 

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result
Boilerplate Gatsby CLI opens on port 8000.

### Actual result
Error in api-runner-ssr.js

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by LekoArts** [comment] 2020-05-20 08:12
Hi, thanks for the issue! Please fill out the issue template as otherwise we can't help you :) Also, try upgrading to the latest versions of all packages, a bug was fixed in Gatsby some hours ago that might have caused this.

**Comment by danabrit** [comment] 2020-05-29 21:25
Closing due to lack of reproduction or minimal information.

**Closed by danabrit** 2020-05-29 21:25 UTC
Labels: status: needs more info, status: needs reproduction

**Comment by varlevi** [comment] 2020-06-11 14:36
@jackbisceglia I had the same problem and it turned out I had a directory name containing a `'` in it in the path to the gatsby site folder. I renamed the directory to something without the `'` and everything worked fine! This is probably a bug that should be fixed! Hope it helps!
