### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getElementsByTagName' of null 

### ISSUE THREAD

**Issue by saadaouad** [gatsbyjs/gatsby#22920] opened 2020-04-08 12:28 UTC
## Description

When I click on [Gatsby link](https://www.gatsbyjs.org/docs/gatsby-link/) it gives me this error:
```
Uncaught TypeError: Cannot read property 'getElementsByTagName' of null
    at navigation.js:173
```

**PS**: this happened with many recent versions 

### Environment

```Bash
yarn run v1.12.3
warning ../package.json: No license field
$ /Users/saadaouad/fugoki-ui/node_modules/.bin/gatsby info --clipboard

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.14.2 - /var/folders/3h/cv940x756d1gjwjgz65ndr7r0000gn/T/yarn--1586348672321-0.2690320762715743/node
    Yarn: 1.12.3 - /var/folders/3h/cv940x756d1gjwjgz65ndr7r0000gn/T/yarn--1586348672321-0.2690320762715743/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.163
    Firefox: 74.0
    Safari: 13.1
  npmPackages:
    gatsby: 2.18.25 => 2.10.5
    gatsby-image: ^2.3.2 => 2.3.1
    gatsby-plugin-accessibilityjs: ^1.0.3 => 1.0.3
    gatsby-plugin-canonical-urls: ^2.2.1 => 2.2.1
    gatsby-plugin-load-script: ^1.0.6 => 1.0.6
    gatsby-plugin-manifest: ^2.3.3 => 2.3.3
    gatsby-plugin-netlify: ^2.2.1 => 2.2.1
    gatsby-plugin-offline: ^3.1.2 => 3.1.2
    gatsby-plugin-react-helmet: ^3.2.1 => 3.2.1
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-sass: ^2.2.1 => 2.2.1
    gatsby-plugin-sitemap: ^2.3.1 => 2.3.1
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.5 => 1.0.5
    gatsby-source-filesystem: ^2.2.2 => 2.2.2
    gatsby-source-graphql: ^2.3.2 => 2.3.0
    gatsby-transformer-json: ^2.3.1 => 2.3.1

✨  Done in 3.39s.
```

**Comment by LekoArts** [comment] 2020-04-09 08:40
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by saadaouad** [comment] 2020-04-21 11:31
Hi @LekoArts, 
I think this [changes](https://github.com/gatsbyjs/gatsby/pull/23196) will resolve the problem

**Comment by saadaouad** [comment] 2020-05-12 03:54
@LekoArts I'm facing with another issue now, 

**Sometimes** I get a blank page when I click on any link without any error message and when I refresh the page I can get my content (I'm not sure if this is due to the cache or not).

Here is a [record](https://recordit.co/8RMBYzPo2N) for that

**Comment by wardpeet** [comment] 2020-05-13 12:30
Hey @saadaouad ,

I'm going to close this issue as it's not a Gatsby issue. Please reach out on https://gatsby.dev/discord or open a new issue with additional information.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Comment by saadaouad** [comment] 2020-05-13 13:52
> I'm going to close this issue as it's not a Gatsby issue.


@wardpeet this is a Gatsby issue and it's related to Gatsby navigation. 
This happened when I upgrade Gatsby to the recent versions.

**Comment by saadaouad** [comment] 2020-05-13 14:01
@wardpeet first it was giving me `Uncaught TypeError: Cannot read property 'getElementsByTagName' of null` error, and once this has been fixed on https://github.com/gatsbyjs/gatsby/pull/23196 I'm getting right now a blank page https://recordit.co/8RMBYzPo2N without any error on the console.

**Comment by dehamzah** [comment] 2020-05-13 14:04
hi @saadaouad i see the record is the production build. did it work in development?
and are you using client side navigation there?
can you provide minimal example in https://codesandbox.io/ so that we can debug it. the video recording is not too helpful if we cannot see the actual code and error message.

**Comment by saadaouad** [comment] 2020-05-13 14:10
Hi @dehamzah, yes it's a production build, it works well in development env and we are using client side navigation. 
I think this is more related to the cache since when I refresh the page using production env it works well.

**Comment by wardpeet** [comment] 2020-05-14 08:17
I'll re-open but without a proper reproduction we won't be able to tackle this.

**Comment by danabrit** [comment] 2020-05-29 23:12
Closed due to no reproduction. 
@saadaouad - In order to have us investigate further, please follow the doc on [how to create a minimal reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/).

**Closed by danabrit** 2020-05-29 23:12 UTC
Labels: status: needs more info, status: needs reproduction
