### ISSUE TITLE
gatsby-plugin-sitemap: prefixing `sitemap` dir for multiple sitepaths 

### ISSUE THREAD

**Issue by saihaj** [gatsbyjs/gatsby#31204] opened 2021-05-04 05:12 UTC
## Description
When there are multiple sitemap. [`gastby-plugin-sitemap@v4.0.0`](https://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap/#gatsby-plugin-sitemap) defaults to put them in `sitemap` dir and the tree is like this.
```
.
|
...
|
├── sitemap
│   ├── sitemap-0.xml
│   └── sitemap-index.xml
...
```

Inside `sitemap-index.xml` all different sitemap should have prefixed `sitemap` because otherwise it just takes to 404.
```diff
<?xml version="1.0" encoding="UTF-8"?>
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap>
-    <loc>https://ambassadors.media/sitemap-0.xml</loc>
+    <loc>https://ambassadors.media/sitemap/sitemap-0.xml</loc>
  </sitemap>
</sitemapindex>
```

### Steps to reproduce
Install dependencies, build site and see `public/sitemap/sitemap-index.xml`

https://github.com/saihaj/gastby-plugin-sitemap-path-prefix-bug

### Expected result

See diff above.

### Actual result

See diff above.

### Environment
```
  System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.0 - /var/folders/cd/q8bp7mkx43l4yg9b5h37yxh00000gn/T/yarn--1620104395845-0.5575292198906412/node
    Yarn: 1.22.10 - /var/folders/cd/q8bp7mkx43l4yg9b5h37yxh00000gn/T/yarn--1620104395845-0.5575292198906412/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 90.0.4430.93
    Safari: 14.0.3
```

**Comment by LekoArts** [comment] 2021-05-04 07:12
Hi! This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/31167

**Closed by LekoArts** 2021-05-04 07:12 UTC
Labels: status: triage needed, type: bug
