### ISSUE TITLE
Problem with images returning null and changing queries

### ISSUE THREAD

**Issue by jromme** [gatsbyjs/gatsby#20439] opened 2020-01-06 18:56 UTC
Hi!

This is basically the first time using Gatsby for a real project and I'm really stuck on this one. The client has uploaded images via Wordpress and all was going well and working as expected but at a certain moment "it just broke". The url of the images were present in the REST but graphql was returning null for the newly uploaded images:

query:
```
acf {
    fullwidth_image {
        source_url
        alt_text
    }
} 
```
result:
```
"acf": {
    "fullwidth_image": null
}
```

`gatsby clean` does not do the trick

## Relevant information

I've also had other queries failing after using `gatsby clean`. All of a sudden some image queries or download file queries did not need a source_url anymore but the url was passed a level higher. So instead of: 
```
acf {
     fullwidth_image {
          source_url
     }
}
```

this would return the source url:
```
acf {
     fullwidth_image
}
```

```
warning Multiple node fields resolve to the same GraphQL field `wordpress__wp_publications.acf.report_image` - [`report_image`, `report_image___NODE`]. Gatsby will use `report_image___NODE`.
warning Multiple node fields resolve to the same GraphQL field `wordpress__wp_events.acf.seo.image` - [`image`, `image___NODE`]. Gatsby will use `image___NODE`.
warning Multiple node fields resolve to the same GraphQL field `wordpress__wp_events.acf.fullwidth_image` - [`fullwidth_image___NODE`, `fullwidth_image`]. Gatsby will use `fullwidth_image___NODE`.
warning Multiple node fields resolve to the same GraphQL field `wordpress__wp_artists.acf.cv` - [`cv`, `cv___NODE`]. Gatsby will use `cv___NODE`.
warning Multiple node fields resolve to the same GraphQL field `wordpress__wp_artists.acf.seo.image` - [`image`, `image___NODE`]. Gatsby will use `image___NODE`.
warning Multiple node fields resolve to the same GraphQL field `wordpress__wp_artists.acf.preview_image` - [`preview_image___NODE`, `preview_image`]. Gatsby will use `preview_image___NODE`.
warning Multiple node fields resolve to the same GraphQL field `wordpress__wp_exhibitions.acf.press_release` - [`press_release`, `press_release___NODE`]. Gatsby will use `press_release___NODE`.
warning Multiple node fields resolve to the same GraphQL field `wordpress__wp_media.author` - [`author___NODE`, `author`]. Gatsby will use `author___NODE`.
warning Multiple node fields resolve to the same GraphQL field `wordpress__wp_media.guid` - [`guid___NODE`, `guid`]. Gatsby will use `guid___NODE`.
warning Multiple node fields resolve to the same GraphQL field `WordPressAcf_slide.image` - [`image___NODE`, `image`]. Gatsby will use `image___NODE`.
warning Multiple node fields resolve to the same GraphQL field `wordpress__acf_publications.acf.report_image` - [`report_image`, `report_image___NODE`]. Gatsby will use `report_image___NODE`.
warning Multiple node fields resolve to the same GraphQL field `wordpress__acf_events.acf.seo.image` - [`image`, `image___NODE`]. Gatsby will use `image___NODE`.
warning Multiple node fields resolve to the same GraphQL field `wordpress__acf_events.acf.fullwidth_image` - [`fullwidth_image___NODE`, `fullwidth_image`]. Gatsby will use `fullwidth_image___NODE`.
warning Multiple node fields resolve to the same GraphQL field `wordpress__acf_artists.acf.cv` - [`cv`, `cv___NODE`]. Gatsby will use `cv___NODE`.
warning Multiple node fields resolve to the same GraphQL field `wordpress__acf_artists.acf.seo.image` - [`image`, `image___NODE`]. Gatsby will use `image___NODE`.
warning Multiple node fields resolve to the same GraphQL field `wordpress__acf_artists.acf.preview_image` - [`preview_image___NODE`, `preview_image`]. Gatsby will use `preview_image___NODE`.
warning Multiple node fields resolve to the same GraphQL field `WordPressAcf_galleryslides.image` - [`image___NODE`, `image`]. Gatsby will use `image___NODE`.
warning Multiple node fields resolve to the same GraphQL field `wordpress__acf_exhibitions.acf.press_release` - [`press_release`, `press_release___NODE`]. Gatsby will use `press_release___NODE`.
```

### Environment (if relevant)

  System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 69.0.1
    Safari: 13.0.2
  npmPackages:
    gatsby: ^2.8.5 => 2.18.12 
    gatsby-image: ^2.1.2 => 2.2.36 
    gatsby-plugin-feed: ^2.2.2 => 2.3.25 
    gatsby-plugin-google-analytics: ^2.0.20 => 2.1.31 
    gatsby-plugin-manifest: ^2.1.1 => 2.2.33 
    gatsby-plugin-offline: ^3.0.24 => 3.0.29 
    gatsby-plugin-react-helmet: ^3.0.12 => 3.1.18 
    gatsby-plugin-sharp: ^2.1.3 => 2.3.8 
    gatsby-plugin-styled-components: ^3.1.14 => 3.1.16 
    gatsby-plugin-typography: ^2.2.13 => 2.3.20 
    gatsby-remark-copy-linked-files: ^2.0.13 => 2.1.33 
    gatsby-remark-images: ^3.0.14 => 3.1.38 
    gatsby-remark-prismjs: ^3.2.10 => 3.3.27 
    gatsby-remark-responsive-iframe: ^2.1.1 => 2.2.30 
    gatsby-remark-smartypants: ^2.0.9 => 2.1.19 
    gatsby-source-wordpress: ^3.0.64 => 3.1.53 
    gatsby-transformer-remark: ^2.3.12 => 2.6.42 
    gatsby-transformer-sharp: ^2.1.21 => 2.3.9 
  npmGlobalPackages:
    gatsby-cli: 2.8.5

### File contents (if changed)

`gatsby-config.js`:
```js
module.exports = {
  siteMetadata: {
    title: `Von Bartha`,
    author: `Von Bartha`,
    description: `Von Bartha`,
    siteUrl: `https://stage-bartha.netlify.com`,
    social: {
      twitter: `vonbartha`,
    },
  },
  plugins: [
    {
      resolve: "gatsby-source-wordpress",
      options: {
        /*
         * The base URL of the WordPress site without the trailingslash and the protocol. This is required.
         * Example : 'gatsbyjsexamplewordpress.wordpress.com' or 'www.example-site.com'
         */
        baseUrl: "backend.vonbartha.com",
        // The protocol. This can be http or https.
        protocol: "https",
        // Indicates whether the site is hosted on wordpress.com.
        // If false, then the assumption is made that the site is self hosted.
        // If true, then the plugin will source its content on wordpress.com using the JSON REST API V2.
        // If your site is hosted on wordpress.org, then set this to false.
        hostingWPCOM: false,
        // If useACF is true, then the source plugin will try to import the WordPress ACF Plugin contents.
        // This feature is untested for sites hosted on wordpress.com.
        // Defaults to true.
        useACF: true,
        // Include specific ACF Option Pages that have a set post ID
        // Regardless if an ID is set, the default options route will still be retrieved
        // Must be using V3 of ACF to REST to include these routes
        // Example: `["option_page_1", "option_page_2"]` will include the proper ACF option
        // routes with the ID option_page_1 and option_page_2
        // The IDs provided to this array should correspond to the `post_id` value when defining your
        // options page using the provided `acf_add_options_page` method, in your WordPress setup
        // Dashes in IDs will be converted to underscores for use in GraphQL
        acfOptionPageIds: [],
        auth: {
          // If auth.user and auth.pass are filled, then the source plugin will be allowed
          // to access endpoints that are protected with .htaccess.
          htaccess_user: "your-htaccess-username",
          htaccess_pass: "your-htaccess-password",
          htaccess_sendImmediately: false,

          // If hostingWPCOM is true then you will need to communicate with wordpress.com API
          // in order to do that you need to create an app (of type Web) at https://developer.wordpress.com/apps/
          // then add your clientId, clientSecret, username, and password here
          // Learn about environment variables: https://www.gatsbyjs.org/docs/environment-variables
          // If two-factor authentication is enabled then you need to create an Application-Specific Password,
          // see https://en.support.wordpress.com/security/two-step-authentication/#application-specific-passwords
          wpcom_app_clientSecret: process.env.WORDPRESS_CLIENT_SECRET,
          wpcom_app_clientId: "54793",
          wpcom_user: "gatsbyjswpexample@gmail.com",
          wpcom_pass: process.env.WORDPRESS_PASSWORD,

          // If you use "JWT Authentication for WP REST API" (https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/)
          // or (https://github.com/jonathan-dejong/simple-jwt-authentication) requires jwt_base_path, path can be found in WordPress wp-api.
          // plugin, you can specify user and password to obtain access token and use authenticated requests against WordPress REST API.
          jwt_user: process.env.JWT_USER,
          jwt_pass: process.env.JWT_PASSWORD,
          jwt_base_path: "/jwt-auth/v1/token", // Default - can skip if you are using https://wordpress.org/plugins/jwt-authentication-for-wp-rest-api/
        },
        // Set cookies that should be send with requests to WordPress as key value pairs
        cookies: {},
        // Set verboseOutput to true to display a verbose output on `npm run develop` or `npm run build`
        // It can help you debug specific API Endpoints problems.
        verboseOutput: false,
        // Set how many pages are retrieved per API request.
        perPage: 100,
        // Search and Replace Urls across WordPress content.
        searchAndReplaceContentUrls: {
          sourceUrl: "https://source-url.com",
          replacementUrl: "https://replacement-url.com",
        },
        // Set how many simultaneous requests are sent at once.
        concurrentRequests: 10,
        // Set WP REST API routes whitelists
        // and blacklists using glob patterns.
        // Defaults to whitelist the routes shown
        // in the example below.
        // See: https://github.com/isaacs/minimatch
        // Example:  `["/*/*/comments", "/yoast/**"]`
        // ` will either include or exclude routes ending in `comments` and
        // all routes that begin with `yoast` from fetch.
        // Whitelisted routes using glob patterns
        excludeRoutes: [
          "**/categories",
          "**/posts",
          "**/pages",
          "**/media",
          "**/tags",
          "**/taxonomies",
          "**/users",
        ],
        // Blacklisted routes using glob patterns
        excludedRoutes: ["**/posts/1456"],
        // Set this to keep media sizes.
        // This option is particularly useful in case you need access to
        // URLs for thumbnails, or any other media detail.
        // Defaults to false
        keepMediaSizes: false,
        // use a custom normalizer which is applied after the built-in ones.
        normalizer: function({ entities }) {
          return entities
        },
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-google-analytics`,
      options: {
        //trackingId: `ADD YOUR TRACKING ID HERE`,
      },
    },
    `gatsby-plugin-offline`,
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-plugin-styled-components`,
      options: {
        displayName: false
      },
    },
  ],
}
```

`package.json`: 
```json
{
"dependencies": {
    "@n8tb1t/use-scroll-position": "^1.0.43",
    "add": "^2.0.6",
    "babel-plugin-styled-components": "^1.10.6",
    "gatsby": "^2.8.5",
    "gatsby-image": "^2.1.2",
    "gatsby-plugin-feed": "^2.2.2",
    "gatsby-plugin-google-analytics": "^2.0.20",
    "gatsby-plugin-manifest": "^2.1.1",
    "gatsby-plugin-offline": "^3.0.24",
    "gatsby-plugin-react-helmet": "^3.0.12",
    "gatsby-plugin-sharp": "^2.1.3",
    "gatsby-plugin-styled-components": "^3.1.14",
    "gatsby-plugin-typography": "^2.2.13",
    "gatsby-remark-copy-linked-files": "^2.0.13",
    "gatsby-remark-images": "^3.0.14",
    "gatsby-remark-prismjs": "^3.2.10",
    "gatsby-remark-responsive-iframe": "^2.1.1",
    "gatsby-remark-smartypants": "^2.0.9",
    "gatsby-source-wordpress": "^3.0.64",
    "gatsby-transformer-remark": "^2.3.12",
    "gatsby-transformer-sharp": "^2.1.21",
    "lodash": "^4.17.11",
    "prismjs": "^1.16.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-flickity-component": "^3.4.0",
    "react-helmet": "^5.2.1",
    "react-typography": "^0.16.19",
    "styled-components": "^4.4.1",
    "typeface-merriweather": "0.0.72",
    "typeface-montserrat": "0.0.75",
    "typography": "^0.16.19",
    "typography-theme-wordpress-2016": "^0.16.19",
    "yarn": "^1.21.1"
  },
  "devDependencies": {
    "cli-glob": "^0.1.0",
    "eslint": "^6.7.1",
    "eslint-config-airbnb": "^18.0.1",
    "eslint-config-prettier": "^6.7.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-jsx-a11y": "^6.2.3",
    "eslint-plugin-react": "^7.5.1",
    "gh-pages": "^2.1.1",
    "prettier": "^1.18.0",
    "remark-cli": "^7.0.1",
    "remark-preset-lint-recommended": "^3.0.1",
    "stylefmt": "^6.0.0",
    "stylelint": "^12.0.0",
    "stylelint-config-standard": "^19.0.0"
  }
}
```

**Comment by TylerBarnes** [comment] 2020-01-08 19:05
Hi @jromme!

Sorry to hear you're running into an issue. It's hard to say what the cause is from your description but it could possibly be [this bug](https://www.gatsbyjs.org/packages/gatsby-source-wordpress/#graphql-error---unknown-field-localfile-on-type-image-field).
If so, that's a problem inherent to the WP rest API which needs to be fixed upstream.
Additionally it could be related to changing the output settings of the image field in the ACF field group settings.
We may be seeing multiple unrelated problems at once as well.
To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2020-02-17 08:42
Thank you for opening this!

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2020-02-17 08:42 UTC
Labels: status: needs reproduction

**Comment by bourneidBH** [comment] 2021-05-27 16:30
I'm having this same issue with gatsby-source-wordpress v5.4.0 & WPGraphQL For Advanced Custom Fields
