### ISSUE TITLE
Unable to start new Gatsby project

### ISSUE THREAD

**Issue by furious-luke** [gatsbyjs/gatsby#35350] opened 2022-04-06 00:01 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

When starting a new Gatsby project, package installation fails before completing the setup with the following error:

```bash
create-gatsby version 2.12.0-next.3



                                                                 Welcome to Gatsby!



This command will generate a new Gatsby site for you in /home/luke/Workspace with the setup you select. Let's answer some questions:



What would you like to call your site?
✔ · test
What would you like to name the folder where your site will be created?
✔ Workspace/ test
✔ Will you be using JavaScript or TypeScript?
· TypeScript
✔ Will you be using a CMS?
· No (or I'll add it later)
✔ Would you like to install a styling system?
· No (or I'll add it later)
✔ Would you like to install additional features with other plugins?
· Add responsive images


Thanks! Here's what we'll now do:

    🛠  Create a new Gatsby site in the folder test
    🔌 Install gatsby-plugin-image, gatsby-plugin-react-helmet


✔ Created site from template
▸ Installing Gatsby...

warning gatsby > gatsby-cli > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
warning gatsby > st > async-cache@1.1.0: No longer maintained. Use [lru-cache](http://npm.im/lru-cache) version 7.6 or higher, and provide an asynchronous `fetchMethod` option.
warning gatsby > @pmmmwh/react-refresh-webpack-plugin > native-url > querystring@0.2.1: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
error Couldn't find any versions for "msgpackr-extract-darwin-arm64" that matches "1.1.1"                                                         
warning gatsby > react-dev-utils > fork-ts-checker-webpack-plugin > micromatch > snapdragon > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
warning gatsby > eslint-plugin-graphql > graphql-config > @graphql-tools/url-loader > subscriptions-transport-ws@0.9.19: The `subscriptions-transport-ws` package is no longer maintained. We recommend you use `graphql-ws` instead. For help migrating Apollo software to `graphql-ws`, see https://www.apollographql.com/docs/apollo-server/data/subscriptions/#switching-from-subscriptions-transport-ws    For general help using `graphql-ws`, see https://github.com/enisdenjo/graphql-ws/blob/master/README.md
warning gatsby > react-dev-utils > fork-ts-checker-webpack-plugin > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning gatsby > react-dev-utils > fork-ts-checker-webpack-plugin > micromatch > snapdragon > source-map-resolve > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
warning gatsby > react-dev-utils > fork-ts-checker-webpack-plugin > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
Error: Couldn't find any versions for "msgpackr-extract-darwin-x64" that matches "1.1.1"
    at MessageError.ExtendableBuiltin (/usr/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/lib/node_modules/yarn/lib/cli.js:750:123)
    at Function.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:50343:13)
    at Generator.next (<anonymous>)
    at step (/usr/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/lib/node_modules/yarn/lib/cli.js:321:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find any versions for "msgpackr-extract-linux-arm64" that matches "1.1.1"
    at MessageError.ExtendableBuiltin (/usr/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/lib/node_modules/yarn/lib/cli.js:750:123)
    at Function.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:50343:13)
    at Generator.next (<anonymous>)
    at step (/usr/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/lib/node_modules/yarn/lib/cli.js:321:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find any versions for "msgpackr-extract-win32-x64" that matches "1.1.1"
    at MessageError.ExtendableBuiltin (/usr/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/lib/node_modules/yarn/lib/cli.js:750:123)
    at Function.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:50343:13)
    at Generator.next (<anonymous>)
    at step (/usr/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/lib/node_modules/yarn/lib/cli.js:321:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find any versions for "msgpackr-extract-linux-arm" that matches "1.1.1"
    at MessageError.ExtendableBuiltin (/usr/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/lib/node_modules/yarn/lib/cli.js:750:123)
    at Function.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:50343:13)
    at Generator.next (<anonymous>)
    at step (/usr/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/lib/node_modules/yarn/lib/cli.js:321:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Couldn't find any versions for "msgpackr-extract-linux-x64" that matches "1.1.1"
    at MessageError.ExtendableBuiltin (/usr/lib/node_modules/yarn/lib/cli.js:721:66)
    at new MessageError (/usr/lib/node_modules/yarn/lib/cli.js:750:123)
    at Function.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:50343:13)
    at Generator.next (<anonymous>)
    at step (/usr/lib/node_modules/yarn/lib/cli.js:310:30)
    at /usr/lib/node_modules/yarn/lib/cli.js:321:13
    at runMicrotasks (<anonymous>)

 ERROR 

Command failed with exit code 1: yarnpkg add --silent gatsby-plugin-image gatsby-plugin-react-helmet gatsby-plugin-sharp gatsby-transformer-sharp
gatsby-source-filesystem react-helmet
```

### Reproduction Link

Fails during setup, no project possible.

### Steps to Reproduce

1. Run `gatsby new`
2. Select Typescript.
3. Select responsive images, and React Helmet.
...

### Expected Result

I would expect a new project to be successfully setup.

### Actual Result

The setup fails with an error.

### Environment

```shell
System:
    OS: Linux 5.17 Arch Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 17.8.0 - /usr/bin/node
    Yarn: 1.22.18 - /usr/bin/yarn
    npm: 8.5.5 - /usr/bin/npm
  Languages:
    Python: 3.10.4 - /home/luke/.pyenv/shims/python
  Browsers:
    Firefox: 98.0.2
```

**Comment by LekoArts** [comment] 2022-04-06 06:31
Hi!

I've just tried your reproduction steps myself and it all works for me. I think you've run into https://github.com/kriszyp/msgpackr-extract/issues/8 which should be fixed now.

**Closed by LekoArts** 2022-04-06 06:31 UTC
Labels: type: bug
