### ISSUE TITLE
gatsby-plugin-image: React-DOM Insertbefore error

### ISSUE THREAD

**Issue by secretlifeof** [gatsbyjs/gatsby#30176] opened 2021-03-10 21:01 UTC
## Description

After upgrading to Gatsby v3 including React v17 and gatsby-plugin-image one of the image components is crashing. I have narrowed the problem down to gatsby-plugin-image. Present in development & production. The image src comes from a headless CMS.

You click on an thumbnail and a lightbox is opened. First image lightbox opening seems to work and the second one crashes the app.

### Component
The Lightbox component is composed of chakra ui components and react-spring.

```jsx
const Lightbox = ({
  images,
  text,
  viewImageInfo,
}) => {
  const [viewText, setViewText] = useState(true)
  const stylePropsFrame = useSpring({
    top: visible || !animate ? "0%" : "100%",
  })

  const noImages = images && images.length === 0

  return (
    <AnimatedFrame
      style={{ ...stylePropsFrame, ...animationStyle }}
    >
      <Global
        styles={css`
          body::-webkit-scrollbar {
            display: ${visible ? "none" : ""};
          }
        `}
      />
      <Flex
        align="center"
        bg="green"
        w={["100%", "100%", text ? (noImages ? "100%" : "50%") : "100%"]}
        h="100%"
        pos="relative"
        className="imageSlider"
      >
        {images && images.length > 0 && (
          <ImageSlider
            images={images}
            viewImageInfo={viewImageInfo}
            mouseEvents={!viewText}
          >
            {images.map((image, index) => {
              if (!image.imageFile?.childImageSharp) return null

              return (
                <Box h="100%" key={index}>
                  {image && (
                    <GatsbyImage
                      image={image.imageFile.childImageSharp?.gatsbyImageData}
                      alt={image.alt ? image.alt : ""}
                      style={{ height: "100%" }}
                      objectFit="contain"
                      objectPosition="center center"
                      imgStyle={{
                        // objectFit: "contain",
                        margin: 0,
                        // objectPosition: "center center",
                      }}
                    />
                  )}

                  {image.caption && (
                    <Box
                      fontFamily="Traulha"
                      color="brown"
                      pt="0.2em"
                      fontSize={["3xl", "2xl", "md"]}
                    >
                      {image.caption}
                    </Box>
                  )}
                </Box>
              )
            })}
          </ImageSlider>
        )}
      </Flex>
    </AnimatedFrame>
  )
}
```

### Expected result

Image should be rendered without error

### Actual result

Error:
```
Warning: render(...): It looks like the React-rendered content of this container was removed without using React. 
This is not supported and will cause errors. Instead, call ReactDOM.unmountComponentAtNode to empty a container.

uncaught DOMException: Failed to execute 'insertBefore' on 'Node': 
The node before which the new node is to be inserted is not a child of this node.
```

But I did not remove any node or component.

How can I debug this?

### Environment

```
System:
    OS: macOS 10.15.7
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.21.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.11 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 88.0.4324.192
    Firefox: 80.0.1
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.0.2 => 3.0.3 
    gatsby-plugin-chakra-ui: ^0.1.4 => 0.1.4 
    gatsby-plugin-emotion: ^4.3.2 => 4.5.0 
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1 
    gatsby-plugin-image: ^1.1.0-next.1 => 1.1.0-next.1 
    gatsby-plugin-manifest: ^3.0.0 => 3.0.0 
    gatsby-plugin-offline: ^4.0.0 => 4.0.0 
    gatsby-plugin-preact: ^5.0.0 => 5.0.0 
    gatsby-plugin-react-helmet: ^4.0.0 => 4.0.0 
    gatsby-plugin-react-i18next: ^0.0.27 => 0.0.27 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-sharp: ^3.0.0 => 3.0.0 
    gatsby-source-filesystem: ^3.0.0 => 3.0.0 
    gatsby-source-graphql: ^3.0.0 => 3.0.0 
    gatsby-transformer-sharp: ^3.0.0 => 3.0.0 
  npmGlobalPackages:
    gatsby-cli: 2.12.58
```

Many thanks in advance for your help.

**Comment by LekoArts** [comment] 2021-03-11 08:27
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by secretlifeof** [comment] 2021-03-11 11:03
Hello @LekoArts.

I understand that. I have provided a live webpage where the error can be displayed in the console. What I would like to understand, is why the new gatsby-plugin-image has this node create error but the old one does not. How can I debug this myself? If I as an example change the src to an empty string "" or to a stable string the error disappears. There seems to be an issue with updating the src.

**Comment by creotip** [comment] 2021-03-15 12:22
Related to 
https://github.com/gatsbyjs/gatsby/issues/29982#issue-822012630

**Comment by LekoArts** [comment] 2021-03-15 12:52
Closing it as an duplicate of https://github.com/gatsbyjs/gatsby/issues/29982

**Closed by LekoArts** 2021-03-15 12:52 UTC
Labels: status: needs reproduction, topic: images/media, type: bug
