### ISSUE TITLE
socket.io polling errors when Gatsby is started with https

### ISSUE THREAD

**Issue by andreasreuter** [gatsbyjs/gatsby#25001] opened 2020-06-15 11:41 UTC
![Screenshot 2020-06-15 at 13 07 19](https://user-images.githubusercontent.com/5789390/84650915-69093900-af09-11ea-94e8-ad06f0e49f8c.png)

## Description

I see a lot of polling errors from socket.io in my console. After I have activated https using this documentation https://www.gatsbyjs.org/docs/local-https/.

### Steps to reproduce

1. Activate SSL using this documentation of Gatsby https://www.gatsbyjs.org/docs/local-https/
2. Start the Gatsby site with gatsby develop --https

### Expected result

If https is activated socket.io should be request at https://localhost:<random port>.

### Actual result

Gatsby sends requests to socket.io at http://localhost:<random port> which ends in access violation errors.

### Environment

```
System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.14.5 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.97
    Firefox: 77.0.1
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.22.15 => 2.23.3
    gatsby-image: ^2.4.5 => 2.4.7
    gatsby-plugin-google-fonts: ^1.0.1 => 1.0.1
    gatsby-plugin-manifest: ^2.4.9 => 2.4.11
    gatsby-plugin-offline: ^3.2.7 => 3.2.9
    gatsby-plugin-react-helmet: ^3.3.2 => 3.3.4
    gatsby-plugin-sharp: ^2.6.9 => 2.6.11
    gatsby-source-filesystem: ^2.3.8 => 2.3.11
    gatsby-transformer-sharp: ^2.5.3 => 2.5.5
  npmGlobalPackages:
    gatsby-cli: 2.12.44
```

**Comment by LekoArts** [comment] 2020-06-16 07:41
Hi! I think this is a duplicate of https://github.com/gatsbyjs/gatsby/issues/24862 and thus I'll close this one. Please comment on the issue with more details. Thanks!

**Closed by LekoArts** 2020-06-16 07:41 UTC
Labels: type: bug
