### ISSUE TITLE
Invariant Violation: Encountered an error trying to infer a GraphQL type

### ISSUE THREAD

**Issue by iamskok** [gatsbyjs/gatsby#14193] opened 2019-05-20 18:59 UTC
To reproduce the error please clone **[this repo](https://github.com/iamskok/gatsby-shopify-invariant-violation-example)**

Useful Links:

  - [Retrieving metafields with the Storefront API
](https://help.shopify.com/en/api/custom-storefronts/storefront-api/guides/metafields)
  - [Shopify GraphQL Admin API](https://help.shopify.com/en/api/graphql-admin-api)
  - [Shopify GraphQL Storefront API](https://help.shopify.com/en/api/custom-storefronts/storefront-api/getting-started)

## Summary

Recently Shopify released a way to [retrieving metafields with the Storefront API
](https://help.shopify.com/en/api/custom-storefronts/storefront-api/guides/metafields). 
In order to get read access to metafields from [Shopify GraphQL Storefront API](https://help.shopify.com/en/api/custom-storefronts/storefront-api/getting-started) we have to whitelist metafields from [Shopify GraphQL Admin API](https://help.shopify.com/en/api/graphql-admin-api). 

I created 2 local plugins:

  1. [`gatsby-source-shopify-metafields`](https://github.com/iamskok/gatsby-shopify-invariant-violation-example/tree/master/plugins/gatsby-source-shopify-metafields) which uses `graphql-request` to `updateMetafieldStorefrontVisibility` of the exact metafield on a product. To run `updateMetafieldStorefrontVisibility` mutation do `cd plugins/gatsby-source-shopify-metafields && node lib.js`.
  2. [`gatsby-source-shopify`](https://github.com/iamskok/gatsby-shopify-invariant-violation-example/tree/master/plugins/gatsby-source-shopify) it's an updated version of the [`default gatsby-source-shopify`](https://www.gatsbyjs.org/packages/gatsby-source-shopify/) plugin with edited `queries.js`, `nodes.js` and `gatsby-node.js` files to include newly avialable `metafields` field.  

## Relevant information

After running `updateMetafieldStorefrontVisibility` I was able to query product metafields using `curl`:

```bash
curl -X POST \
"https://shop-name.myshopify.com/api/graphql.json" \
-H "Content-Type: application/graphql" \
-H "X-Shopify-Storefront-Access-Token: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" \
-d '
query {
  productByHandle(handle: "nike-air-max-720") {
    metafield(namespace: "global", key: "free_shipping") {
      value
    }
  }
}
'
```

Response: `{"data":{"productByHandle":{"metafield":{"value":"true"}}}}`

But on `gatsby-develop` I get `Invariant Violation: Encountered an error trying to infer a GraphQL type` error:

```bash
gatsby develop
success open and validate gatsby-configs — 0.004 s
success load plugins — 0.368 s
success onPreInit — 0.006 s
success initialize cache — 0.094 s
success copy gatsby files — 0.045 s
success onPreBootstrap — 0.006 s

gatsby-source-shopify/new-dev-sandbox starting to fetch data from Shopify

gatsby-source-shopify/new-dev-sandbox fetched and processed blogs: 274.471ms

gatsby-source-shopify/new-dev-sandbox fetched and processed policies: 278.416ms

gatsby-source-shopify/new-dev-sandbox fetched and processed productTypes: 406.051ms

gatsby-source-shopify/new-dev-sandbox fetched and processed articles: 641.547ms

gatsby-source-shopify/new-dev-sandbox fetched and processed collections: 754.319ms


gatsby-source-shopify/new-dev-sandbox fetched and processed products: 1832.663ms

gatsby-source-shopify/new-dev-sandbox finished fetching data from Shopify: 1848.663ms
success source and transform nodes — 1.903 s
warning Multiple node fields resolve to the same GraphQL field `ShopifyCollection.products` - [`products`, `products___NODE`]. Gatsby will use `products___NODE`.
warning Multiple node fields resolve to the same GraphQL field `ShopifyProduct.metafields` - [`metafields`, `metafields___NODE`]. Gatsby will use `metafields___NODE`.
error UNHANDLED REJECTION


  Error: Invariant Violation: Encountered an error trying to infer a GraphQL type for: `metafields___  NODE`. There is no corresponding node with the `id` field matching: "Shopify__ProductMetafield__und  efined,Shopify__ProductMetafield__undefined,Shopify__ProductMetafield__undefined,Shopify__ProductMe  tafield__undefined".

  - invariant.js:40 invariant
    [gatsby-shopify-invariant-violation-example]/[invariant]/invariant.js:40:15

  - add-inferred-fields.js:259 getFieldConfigFromFieldNameConvention
    [gatsby-shopify-invariant-violation-example]/[gatsby]/dist/schema/infer/add-inferred-fields.js:25    9:3

  - add-inferred-fields.js:161 getFieldConfig
    [gatsby-shopify-invariant-violation-example]/[gatsby]/dist/schema/infer/add-inferred-fields.js:16    1:19

  - add-inferred-fields.js:87 Object.keys.forEach.key
    [gatsby-shopify-invariant-violation-example]/[gatsby]/dist/schema/infer/add-inferred-fields.js:87    :25

  - Array.forEach

  - add-inferred-fields.js:74 addInferredFieldsImpl
    [gatsby-shopify-invariant-violation-example]/[gatsby]/dist/schema/infer/add-inferred-fields.js:74    :28

  - add-inferred-fields.js:38 addInferredFields
    [gatsby-shopify-invariant-violation-example]/[gatsby]/dist/schema/infer/add-inferred-fields.js:38    :3

  - index.js:98 addInferredType
    [gatsby-shopify-invariant-violation-example]/[gatsby]/dist/schema/infer/index.js:98:3

  - index.js:64 typesToInfer.map.typeComposer
    [gatsby-shopify-invariant-violation-example]/[gatsby]/dist/schema/infer/index.js:64:43

  - Array.map

  - index.js:64 addInferredTypes
    [gatsby-shopify-invariant-violation-example]/[gatsby]/dist/schema/infer/index.js:64:23

  - schema.js:140
    [gatsby-shopify-invariant-violation-example]/[gatsby]/dist/schema/schema.js:140:11

  - Generator.next
```

### Environment

*  gatsby `v2.5.2`
* node `v11.14.0`

### File contents

`gatsby-config.js`: 

```js
require('dotenv').config({
  path: `.env.${process.env.NODE_ENV}`
});

module.exports = {
  siteMetadata: {
    title: `Gatsby Default Starter`,
    description: `Kick off your next, great Gatsby project with this default starter. This barebones starter ships with the main Gatsby configuration files you might need.`,
    author: `@gatsbyjs`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: 'gatsby-source-shopify',
      options: {
        shopName: `${process.env.SHOPIFY_SHOP_NAME}`,
        accessToken: `${process.env.SHOPIFY_STOREFRONT_ACCESS_TOKEN}`,
        verbose: true
      }
    },
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/gatsby-icon.png`, // This path is relative to the root of the site.
      },
    },
    // this (optional) plugin enables Progressive Web App + Offline functionality
    // To learn more, visit: https://gatsby.dev/offline
    // `gatsby-plugin-offline`,
  ],
}
```

**Comment by DSchau** [comment] 2019-05-20 21:57
Hello @iamskok!

Thanks for the reproduction, we appreciate it!

I see at least one issue here, and that's probably what is causing the issue.

If we look at the logs, we see a few helpful logs like so:

```
  Error: Invariant Violation: Encountered an error trying to infer a GraphQL type for: `metafields___  NODE`. There is no corresponding node with the `id` field matching: "Shopify__ProductMetafield__und  efined,Shopify__ProductMetafield__undefined,Shopify__ProductMetafield__undefined,Shopify__ProductMe  tafield__undefined".

```

specifically, `Shopify__ProductMetafield__undefined` which is a nice hint that perhaps we're creating something with an undefined id when we wouldn't expect that to be the case.

If we back track to how we got here, we see the following [lines of code](https://github.com/iamskok/gatsby-shopify-invariant-violation-example/blob/master/plugins/gatsby-source-shopify/src/nodes.js#L134). It's attempting to use metafield.id, which when we look at the backing query, is [not requested](https://github.com/iamskok/gatsby-shopify-invariant-violation-example/blob/master/plugins/gatsby-source-shopify/src/queries.js#L139-L143)

I'm not sure if there is a id field for Shopify's API for metafields (although I'd guess there is), but at first glance I am presuming that augmenting the query to request an `id` may resolve this issue.

I'm going to close this as answered--but please re-open or reply if I'm off base and this isn't quite the solution!

**Comment by iamskok** [comment] 2019-05-20 22:21
@DSchau Thanks for your quick response! 

I have added `id` field to the backing query and it fixed `undefined` values, but the error message is still the same. 

```bash
success open and validate gatsby-configs — 0.006 s
success load plugins — 0.451 s
success onPreInit — 0.006 s
success initialize cache — 0.019 s
success copy gatsby files — 0.087 s
success onPreBootstrap — 0.010 s

gatsby-source-shopify/new-dev-sandbox starting to fetch data from Shopify

gatsby-source-shopify/new-dev-sandbox fetched and processed policies: 336.553ms

gatsby-source-shopify/new-dev-sandbox fetched and processed blogs: 342.623ms

gatsby-source-shopify/new-dev-sandbox fetched and processed articles: 365.817ms

gatsby-source-shopify/new-dev-sandbox fetched and processed productTypes: 1105.905ms


gatsby-source-shopify/new-dev-sandbox fetched and processed collections: 1301.820ms


gatsby-source-shopify/new-dev-sandbox fetched and processed products: 7624.784ms

gatsby-source-shopify/new-dev-sandbox finished fetching data from Shopify: 7647.833ms
success source and transform nodes — 7.713 s
warning Multiple node fields resolve to the same GraphQL field `ShopifyArticle.blog` - [`blog`, `blog___NODE`]. Gatsby will use `blog___NODE`.
warning Multiple node fields resolve to the same GraphQL field `ShopifyCollection.products` - [`products`, `products___NODE`]. Gatsby will use `products___NODE`.
warning Multiple node fields resolve to the same GraphQL field `ShopifyProduct.metafields` - [`metafields`, `metafields___NODE`]. Gatsby will use `metafields___NODE`.
error UNHANDLED REJECTION


  Error: Invariant Violation: Encountered an error trying to infer a GraphQL type for: `metafields___  NODE`. There is no corresponding node with the `id` field matching: "Shopify__ProductMetafield__Z2l  kOi8vc2hvcGlmeS9NZXRhZmllbGQvNTc5MTkwMTg3NjI3NQ==,Shopify__ProductMetafield__Z2lkOi8vc2hvcGlmeS9NZX  RhZmllbGQvNTc5Njc3MzEzNDM4Nw==,Shopify__ProductMetafield__Z2lkOi8vc2hvcGlmeS9NZXRhZmllbGQvNTc5Njc3M  zE2NzE1NQ==,Shopify__ProductMetafield__Z2lkOi8vc2hvcGlmeS9NZXRhZmllbGQvNTc5Njc3MzE5OTkyMw==,Shopify  __ProductMetafield__Z2lkOi8vc2hvcGlmeS9NZXRhZmllbGQvNTgwNTU1MzY4MDQzNQ==".

  - invariant.js:40 invariant
    [bva-gatsby-shopify-starter-2]/[invariant]/invariant.js:40:15

  - add-inferred-fields.js:259 getFieldConfigFromFieldNameConvention
    [bva-gatsby-shopify-starter-2]/[gatsby]/dist/schema/infer/add-inferred-fields.js:259:3

  - add-inferred-fields.js:161 getFieldConfig
    [bva-gatsby-shopify-starter-2]/[gatsby]/dist/schema/infer/add-inferred-fields.js:161:19

  - add-inferred-fields.js:87 Object.keys.forEach.key
    [bva-gatsby-shopify-starter-2]/[gatsby]/dist/schema/infer/add-inferred-fields.js:87:25

  - Array.forEach

  - add-inferred-fields.js:74 addInferredFieldsImpl
    [bva-gatsby-shopify-starter-2]/[gatsby]/dist/schema/infer/add-inferred-fields.js:74:28

  - add-inferred-fields.js:38 addInferredFields
    [bva-gatsby-shopify-starter-2]/[gatsby]/dist/schema/infer/add-inferred-fields.js:38:3

  - index.js:98 addInferredType
    [bva-gatsby-shopify-starter-2]/[gatsby]/dist/schema/infer/index.js:98:3

  - index.js:64 typesToInfer.map.typeComposer
    [bva-gatsby-shopify-starter-2]/[gatsby]/dist/schema/infer/index.js:64:43

  - Array.map

  - index.js:64 addInferredTypes
    [bva-gatsby-shopify-starter-2]/[gatsby]/dist/schema/infer/index.js:64:23

  - schema.js:140
    [bva-gatsby-shopify-starter-2]/[gatsby]/dist/schema/schema.js:140:11

  - Generator.next
```

**Comment by DSchau** [comment] 2019-05-20 22:27
@iamskok in the same way that other node types are created (e.g. ShopifyProduct, ShopifyCollection, etc.) you also need to create ShopifyMetafields in `gatsby-node.js`.

You're exporting the helper to do so [here](https://github.com/iamskok/gatsby-shopify-invariant-violation-example/blob/master/plugins/gatsby-source-shopify/src/nodes.js#L144) but then never using it?

For example, if we take a look at [`ProductNode`](https://github.com/iamskok/gatsby-shopify-invariant-violation-example/blob/master/plugins/gatsby-source-shopify/src/nodes.js#L101) we can see we're [using it here in `gatsby-node.js`](https://github.com/iamskok/gatsby-shopify-invariant-violation-example/blob/master/plugins/gatsby-source-shopify/src/gatsby-node.js#L66).

So in this case, you're associating a child node on Product with a node that doesn't exist because it hasn't been created!

To fix, I think you'll want to create Metafield nodes using the helper you exposed (but aren't using) when you're creating a Product since that's when you're creating it. In other words, how ProductVariant works is how this should work too.

**Comment by DSchau** [comment] 2019-05-20 22:44
@iamskok that the issue? If so--please confirm and we can get this closed out. Thanks!

**Comment by iamskok** [comment] 2019-05-20 23:04
I'm not sure if that's the issue, bc I use [`ProductMetafieldNode`](https://github.com/iamskok/gatsby-shopify-invariant-violation-example/blob/master/plugins/gatsby-source-shopify/src/gatsby-node.js#L79) the same we are using [`ProductOptionNode `](https://github.com/iamskok/gatsby-shopify-invariant-violation-example/blob/master/plugins/gatsby-source-shopify/src/gatsby-node.js#L74) or [`ProductVariantNode`](https://github.com/iamskok/gatsby-shopify-invariant-violation-example/blob/master/plugins/gatsby-source-shopify/src/gatsby-node.js#L69), these fields are not required for `product`. I also have to mention that `metafields` has to be available in multiple places, on `products`, `collections`, `articles`, [etc...](https://help.shopify.com/en/api/reference/metafield)

**Comment by DSchau** [comment] 2019-05-20 23:21
> If this will help I can share Shopify API tokens.

Could you share these with me? You can e-mail me at dustin at gatsbyjs dot com.

**Comment by iamskok** [comment] 2019-05-20 23:37
@DSchau sent 📬

**Comment by DSchau** [comment] 2019-05-21 20:03
Got it!

Thanks for the reproduction. There was just a little piece you missed. Giving the following query:

```
query GetProducts($first: Int!, $after: String) {
    shop {
      products(first: $first, after: $after) {
        pageInfo {
          hasNextPage
        }
        edges {
          cursor
          node {
            availableForSale
            createdAt
            description
            descriptionHtml
            handle
            id
            images(first: 250) {
              edges {
                node {
                  id
                  altText
                  originalSrc
                }
              }
            }
            onlineStoreUrl
            metafields(first: 50) {
              edges {
                node {
                	id
                  namespace
                  key
                  value
                  valueType
                  description
                }
              }
            }
            options {
              id
              name
              values
            }
            priceRange {
              minVariantPrice {
                amount
                currencyCode
              }
              maxVariantPrice {
                amount
                currencyCode
              }
            }
            productType
            publishedAt
            tags
            title
            updatedAt
            variants(first: 250) {
              edges {
                node {
                  availableForSale
                  compareAtPrice
                  id
                  image {
                    altText
                    id
                    originalSrc
                  }
                  price
                  selectedOptions {
                    name
                    value
                  }
                  sku
                  title
                  weight
                  weightUnit
                }
              }
            }
            vendor
          }
        }
      }
    }
  }
```

You can see that metafields (and variants) store their array data on `.edges`, e.g. `product.edges[0].metafields.edges`

The resulting data is then available on `.edges[n].node`.

So we just need to fix up gatsby-node.js like so:

```js
if (x.metafields)
  await forEach(x.metafields.edges, async metafield =>
    createNode(await ProductMetafieldNode(imageArgs)(metafield.node))
  )
```

For context on how I checked this--just need to check the existing Spotify fields (e.g. x.variants) and you can see it's `x.variant.edges` and `variant.node`!

<img width="1021" alt="Screen Shot 2019-05-21 at 3 02 52 PM" src="https://user-images.githubusercontent.com/3924690/58126826-87ebad80-7bd9-11e9-96b6-2fa776edf5a0.png">

Now I feel pretty confident closing :) Please reply or re-open if we can help further!

**Closed by DSchau** 2019-05-21 20:03 UTC
Labels: topic: plugins, type: feature or enhancement, type: question or discussion

**Comment by iamskok** [comment] 2019-05-22 17:34
@DSChau Thank you! It fixed the issue 🎉 

I ended up with this block of code:

```js
if (node.metafields) {
  await Array.prototype.forEach.call(node.metafields.edges, async metafield => {
    createNodeFactory(await ProductMetafieldNode(imageArgs)(metafield.node))
  })
}
```

Now I'm going to start implementing `metafields` for [all the queries](https://help.shopify.com/en/api/reference/metafield). And this is how `gatsby-config.js` will look:

```js
{
  resolve: 'gatsby-source-shopify',
  options: {
    shopName: `${process.env.SHOPIFY_SHOP_NAME}`,
    accessToken: `${process.env.SHOPIFY_STOREFRONT_ACCESS_TOKEN}`,
    verbose: true,
  	adminAccessToken: `${process.env.SHOPIFY_ADMIN_ACCESS_TOKEN}`,
  	adminPassword: `${process.env.SHOPIFY_ADMIN_ACCESS_TOKEN}`,
  	updateMetafieldStorefrontVisibility: [
  	  {
  	    "namespace": "global",
  	    "key": "limited",
  	    "ownerType": "PRODUCT"
  	  },
  	  {
  	    "namespace": "global",
  	    "key": "featured",
  	    "ownerType": "PRODUCT"
  	  },
  	  {
  	    "namespace": "local",
  	    "key": "featured",
  	    "ownerType": "PRODUCT"
  	  }
  	  ...
  	}
  ]
}
```

To sum it up:

Quite often Shopify developer [need access to `metafields`](https://github.com/gatsbyjs/gatsby/issues/7659), but it is only available thru Admin API and there is no plugin for @gatsbyjs to do it.

Recently Shopify introduced a way to [retrieve `metafields` from Storefront](https://help.shopify.com/en/api/custom-storefronts/storefront-api/guides/metafields) by whitelisting these fields with Shopify Admin API.

To make it happen we have to create `MetafieldStorefrontVisibility` record:

```js
const updateMetafieldStorefrontVisibility = `
    mutation($input: MetafieldStorefrontVisibilityInput!) {
      metafieldStorefrontVisibilityCreate(input: $input) {
        metafieldStorefrontVisibility {
          id
        }
        userErrors {
          field
          message
        }
      }
    }
  `
```

Define input objects for the mutations:

```
{
  "input": {
    "namespace": "instructions",
    "key": "wash",
    "ownerType": "PRODUCT"
  }
}
```

Retrieve `metafields` with `gatsby-source-shopify` using updated queries: `product`, `collection`, [etc](https://help.shopify.com/en/api/reference/metafield)... [Does it make sense to use GraphQL fragments for this purpose?]

Please let me know if anything above can be improved.

Will @gatsbyjs be interested in this PR for [`gatsby-source-shopify`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-source-shopify)?

**Comment by arhoy** [comment] 2020-04-06 01:14
I am having the same issues, It is outputting horrible blob
success source and transform nodes - 22.633s
⠙ building schema

 ERROR 

UNHANDLED REJECTION Encountered an error trying to infer a GraphQL type for: `products___NODE`. There is no corresponding node with the `id` field matching: "Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ4MDA4NzAyODU0NTI=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ4MDA4Njk2MzAwOTI=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1OTg2MDc2MDk5OTY=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1OTg2MDY0OTU4ODQ=,Shopify__Product__

**Comment by iKeeko** [comment] 2020-07-01 12:45
> I am having the same issues, It is outputting horrible blob
> success source and transform nodes - 22.633s
> ⠙ building schema
> 
> ERROR
> 
> UNHANDLED REJECTION Encountered an error trying to infer a GraphQL type for: `products___NODE`. There is no corresponding node with the `id` field matching: "Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ4MDA4NzAyODU0NTI=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ4MDA4Njk2MzAwOTI=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1OTg2MDc2MDk5OTY=,Shopify__Product__Z2lkOi8vc2hvcGlmeS9Qcm9kdWN0LzQ1OTg2MDY0OTU4ODQ=,Shopify__Product__

Same. Any luck?

**Comment by sumanchapai** [comment] 2020-08-17 12:30
I solved the problem by using the access token from the environment variable rather than using it directly. 
In my ``gatsby-config.js``
```require("dotenv").config();
module.exports = {
plugins: [

// other necessary plugins ,
{
resolve: 'gatsby-source-shopify',
options : {
shopName: 'xx-yz' 
accessToken: process.env.VARIABLE_NAME_IN_DOTENV_FILE
apiVersion: "2020-01"
]
}
```
and in the ``.env`` file in the root of the project directory 
``VARIABLE_NAME_IN_DOTENV_FILE="storefront-api-token-given-by-shopify"``
