### ISSUE TITLE
gatsby does not generate some images files in the static folder, after run gatsby clean and gatsby develop  

### ISSUE THREAD

**Issue by santiagosj** [gatsbyjs/gatsby#20412] opened 2020-01-04 16:53 UTC
System:
    OS: Windows 10 10.0.18362
    CPU: (6) x64 AMD Phenom(tm) II X6 1075T Processor
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.19.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.0 - /c/Users/sanjs/AppData/Local/Programs/Python/Python38-32/python
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.18.11 => 2.18.16
    gatsby-cli: ^2.8.22 => 2.8.22
    gatsby-image: ^2.2.34 => 2.2.36
    gatsby-plugin-manifest: ^2.2.30 => 2.2.33
    gatsby-plugin-offline: ^3.0.24 => 3.0.29
    gatsby-plugin-react-helmet: ^3.1.16 => 3.1.18
    gatsby-plugin-sharp: ^2.3.4 => 2.3.7
    gatsby-source-filesystem: ^2.1.39 => 2.1.42
    gatsby-transformer-json: ^2.2.20 => 2.2.22
    gatsby-transformer-sharp: ^2.3.6 => 2.3.9

I have a data folder and inside of it are a images folder with images... and in data are some json files with data and some of this data is image data like src, srcSet etc like so: 
[
  { 
    ""imgHeader":"./images/imgHeader.jpg",  <--this image it is generated in static folder
     "title":"some Title",
     "photos":[
          {
            "src": "/static/fea29194e5b25393211cc5aa1638a3af/28fc6/open1.jpg",
            "srcSet": [
              "/static/fea29194e5b25393211cc5aa1638a3af/d278e/open1.jpg 200w",
              "/static/fea29194e5b25393211cc5aa1638a3af/8539d/open1.jpg 400w",
              "/static/fea29194e5b25393211cc5aa1638a3af/28fc6/open1.jpg 793w"
            ],  
            "sizes": ["(max-width: 793px) 100vw, 793px"],
            "width": 1.3,
            "height": 1,
            "title":"Open Summer 01"
          },
      ]
  }
]

the issue is that I runed gatsby clean... because I needed to, and now when I run gatsby develop gatsby or npm or whatever should generate the static files does not generate this files and folders...so I bring data that not exist, and my image galleries show empty with an alt attribute.
Here is the error message:

error copying file from C:/Users/sanjs/Desktop/morro-bjj/data/images/open1.jpeg to C:\Users\sanjs\Desktop\morro-bjj\public\static\open1-fea29194e5b25393211cc5aa1638a3af.jpeg { [Error: EBUSY: resource busy or locked, copyfile 'C:\Users\sanjs\Desktop\morro-bjj\data\images\open1.jpeg' -> 'C:\Users\sanjs\Desktop\morro-bjj\public\static\open1-fea29194e5b25393211cc5aa1638a3af.jpeg']
  errno: -4082,
  code: 'EBUSY',
  syscall: 'copyfile',
  path:
   'C:\\Users\\sanjs\\Desktop\\morro-bjj\\data\\images\\open1.jpeg',
  dest:
   'C:\\Users\\sanjs\\Desktop\\morro-bjj\\public\\static\\open1-fea29194e5b25393211cc5aa1638a3af.jpeg' } 

this happened after I run gatsby clean...was working good..
except for that little detail that it doesn't update the image that I changed. And the error message above repeats for each image that I have in a data structure like I show before.

**Comment by jonniebigodes** [comment] 2020-01-05 20:00
@santiagosj can you share the contents of the `gatsby-config.js`, because what it seems to be happening is that probably `gatsby-filesystem` is having contest with another plugin, locking the contents in and not letting the other plugins work properly

**Comment by santiagosj** [comment] 2020-01-06 23:32
Hi @jonniebigodes here is my `gatsby-config.js` : 
```
module.exports = {
  siteMetadata: {
    title: `Morro-BJJ`,
    description: `Página web para el Morro Jiu-Jitsu Oss!`,
    author: `Santi`,
    menuLinks:[
      {
        name:"Historia",
        link:"/about"
      },
      {
        name:"Equipo",
        link:"/team"
      },
      {
        name:"Noticias y Eventos",
        link:"/news"
      }
    ]
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    'gatsby-transformer-json',
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `data`,
        path: `./data`,
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `gatsby-starter-default`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#000000`,
        theme_color: `#000000`,
        display: `minimal-ui`,
        icon: `src/images/morro.png`, // This path is relative to the root of the site.
      },
    },
  ],
}

```
I will try to reproduce the error, I needed to solve this so I had to reset the head commit to an older one. The issue started to appear when I runed `gatsby clear`, some files in the static folder wasn't generated, and some other it was, the big difference between them I thik was the way how I set the json file to generate the data...
```
[
{
""imgHeader":"./images/imgHeader.jpg", <-- this image it is generated in static folder, because is pointing to images folder, which I am indicating in the options property of gatsby-config.js gatsby-source-filesystem
"title":"some Title",
"photos": [ <-- this array of images wasn't generated because this are sources that are generated by the gatsby-source-filesystem which points to images folder...not to static folder...
{
"src": "/static/fea29194e5b25393211cc5aa1638a3af/28fc6/open1.jpg",
"srcSet": [
"/static/fea29194e5b25393211cc5aa1638a3af/d278e/open1.jpg 200w",
"/static/fea29194e5b25393211cc5aa1638a3af/8539d/open1.jpg 400w",
"/static/fea29194e5b25393211cc5aa1638a3af/28fc6/open1.jpg 793w"
],
"sizes": ["(max-width: 793px) 100vw, 793px"],
"width": 1.3,
"height": 1,
"title":"Open Summer 01"
},
]
}
]
```
the reason why I'm setting the data like that is because I'm using react-photo-gallery http://neptunian.github.io/react-photo-gallery/ 
and the component recibes an array of objects as parameter in his attribute photos, so I query the array.
I still doesn't understand the error...I fixed my project...but avoiding put my newbie hands in the error directly so, I decided back in the commit line track...
I hope this help...
thanks for responding.

**Comment by jonniebigodes** [comment] 2020-01-08 19:35
@santiagosj sorry for the delay in the response.

Here are the steps i took to triage your issue and in the end of my comment you'll add a bit more context to what is actually happening.

- Created a new Gatsby site based on the default starter.
- Copied over some images i have laying around to use with issues that involve images as you can see below:
![santiago_1](https://user-images.githubusercontent.com/22988955/72007539-cc4fba80-3249-11ea-8b42-9fffa8274e11.png)
- Add `react-photo-gallery` 
- Checked the documentation for the package and based on that i created two components:
   - `src\components\SimpleImageGallery.js` based on the simple example of the package, with the following content:
```javascript
import React from "react"
import Gallery from "react-photo-gallery"
import { useStaticQuery, graphql } from "gatsby"

/**
 * simple functional component to fetch the images with Gatsby and supply them to React photo Gallery
 * based on simple example supplied by react-photo-gallery
 */
const SimpleImageGallery = () => {
  // create a variable to fetch the images inside the src\images folder with the exception of the icon
  const simpleQueryResult = useStaticQuery(graphql`
    {
      allImageSharp(
        filter: { fluid: { originalName: { ne: "gatsby-icon.png" } } }
      ) {
        nodes {
          id
          fluid {
            src
          }
        }
      }
    }
  `)
  // destructure the result of the query
  const { nodes } = simpleQueryResult.allImageSharp

  // iterates over the query result and creates a array of objects to match the 
  // requirements of the react-photo-gallery package
  const galleryImages = nodes.map((photo, index) => {
    if (index % 2 === 0) {
      return {
        src: photo.fluid.src,
        width: 4,
        height: 3,
      }
    }
    return {
      src: photo.fluid.src,
      width: 1,
      height: 1,
    }
  })
  return (
    <div>
      <Gallery photos={galleryImages}/>
    </div>
  )
}

export default SimpleImageGallery
```
  - And `src\components\ResponsiveImagesGallery.js` that is based on the package's example with setting both the `src` and `srcSet` props with the following content:
```javascript
import React from "react"
import { useStaticQuery, graphql } from "gatsby"
import Gallery from "react-photo-gallery"

/**
 * simple functional component to fetch the images with Gatsby and supply them to React photo Gallery
 * based on example for setting src/srcSet supplied by react-photo-gallery
 */
const ResponsiveImagesGallery = () => {
     // create a variable to fetch the images inside the src\images folder with the exception of the icon
  const ResponsiveQueryResult = useStaticQuery(
    graphql`
      {
        allImageSharp(
          filter: { fluid: { originalName: { ne: "gatsby-icon.png" } } }
        ) {
          nodes {
            id
            fluid(maxWidth: 1920) {
              src
              srcSet
              sizes
            }
          }
        }
      }
    `
  )
   // destructure the result of the query
  const { nodes } = ResponsiveQueryResult.allImageSharp

  // iterates over the query result and creates a array of objects to match the 
  // requirements of the react-photo-gallery package
  const responsiveGalleryImages = nodes.map((photo, index) => {
      /**
       * as the srcSet in Gatsby is a string you can check it by yourself in the graphiQL editor
       *  and the react-photo-gallery expects a array of strings
       * we're going to create a variable to split the string so that it can be supplied
       */
      const splitSrcSet=photo.fluid.srcSet.split(',\n')
      if (index%2===0){
          return {
              src:photo.fluid.src,
              width: 4,
              height: 3,
              sizes:[photo.fluid.sizes],
              srcSet:splitSrcSet
          }
         
      }
      return {
        src: photo.fluid.src,
        width: 1,
        height: 1,
        sizes:[photo.fluid.sizes],
        srcSet:splitSrcSet
      }
  })
  return <div><Gallery photos={responsiveGalleryImages}/></div>
}

export default ResponsiveImagesGallery
```
- Changed `src\pages\index` to:
```javascript
import React from "react"
import { Link } from "gatsby"
import SEO from "../components/seo"
import SimpleImageGallery from "../components/SimpleImageGallery"
const IndexPage = () => (
  <div>
    <SEO title="Simple Gallery" />
    <SimpleImageGallery />
    <Link to="/page-2/">Go to page 2</Link>
  </div>
)

export default IndexPage
```
- `src\pages\page-2.js` to the following:
```javascript
import React from "react"
import { Link } from "gatsby"

import SEO from "../components/seo"
import ResponsiveImagesGallery from '../components/ResponsiveImagesGallery'
const SecondPage = () => (
  <div>
    <SEO title="Responsive Gallery" />
    <ResponsiveImagesGallery/>
    <Link to="/">Go back to the homepage</Link>
  </div>
)

export default SecondPage
```

As you may have noticed i'm not using, nor i have created a `data` folder and used json based files with the image information and nor have i mentioned the `gatsby-transformer-json`

Based on the documentation of the package you can streamline and optimize your code to some extent. In this case you let Gatsby do the "heavy lifting" (pardon the bad pun), make it grab the images and it's information, iterate over a simple query result and supply it to the package and you should be fine with it. 

Should you need to add a title or another field that's a simple matter of adjusting the code accordingly. 

A bit of context of what is happening here. Based on your issue description and following comment.

To the best of my knowledge what seems to be the issue is that Gatsby is trying to look for something that will or will not exist. As you're using a json file to contain the images information, that might lead to some false information. When you issue `gatsby develop` or `gatsby build` it will copy over the images and assign a unique id. That id is not everlasting. Like you mentioned you issued `gatsby clean` and with that it will purge the folders from your system. Issuing `gatsby develop` once again will trigger the copy and id generation once again, but this time they will be completely different from before. 

Also you shouldn't be relying too much on the structure you have mentioned to keep track of the assets, as for instance when you deploy the site to netlify or another cdn the ids will be completely new. And subsequent builds that you trigger might lead to this behaviour over and over again.

I've setup a repo with the code for this issue in [here](https://github.com/jonniebigodes/gatsby_test_react-photo-gallery) and i have a live version of it [here](https://happy-tereshkova-920b52.netlify.com/).

The code is commented so that when you take a look at it you know what is happening at every stage. I would like for you to take a look at it at your own pace and report back if you have any questions.

Also if you need to expand the image information you need to usei'm more than happy to update the repo code and post a comment.

Feel free to provide feedback so that we can close this issue, or continue to work on it until we find a suitable solution.

**Comment by santiagosj** [comment] 2020-01-08 23:01
Hi @jonniebigodes, great response 😀.
I realized what is causing the issue, well... you said it better than me -->

> To the best of my knowledge what seems to be the issue is that <strong>Gatsby is trying to look for something that will or will not exist. </strong> As you're using a json file to contain the images information, that might lead to some false information. When you issue gatsby develop or gatsby build it will copy over the images and assign a unique id. That id is not everlasting. Like you mentioned you issued gatsby clean and with that it will purge the folders from your system. Issuing gatsby develop once again will trigger the copy and id generation once again, <strong>but this time they will be completely different from before</strong>

I like much your method to fill the Gallery component, now I just have to figure it out how to build  different and specific galleries along the app without setting an object in my json files, maybe instead to use an array of objects, just an array of images path like: 

somePage1.json 
```
... 
 "photos": [ "./images/photo1.jpg","./images/photo2.jpg","./images/photo3.jpg"] 
...
```
somePage2.json 
```
... 
 "photos": [ "./images/photo4.jpg","./images/photo5.jpg","./images/photo6.jpg"] 
...
```

and just bring the data and return an array of objects to meet the requirements of the gallery component. 

This issue is solved to me, is clear what is causing it and I will change my data settings. Thank you very much for your help. 

Regards!  🍻

**Closed** 2020-01-08 23:01 UTC
Labels: status: awaiting author response

**Comment by jonniebigodes** [comment] 2020-01-08 23:26
@santiagosj no need to thank, glad that i was able to help solving your issue. If you are interested i can update the reproduction used so that you can use the structure you want to use and create the galleries. If you don't mind waiting a bit longer. I can update it tomorrow and commit it to the repo so that you can take a look at it and proceed from there. Sounds good?

**Comment by santiagosj** [comment] 2020-01-09 02:22
@jonniebigodes yes my friend, sound really good, thanks again, I really appreciate it.

**Comment by jonniebigodes** [comment] 2020-01-09 19:05
@santiagosj i've updated the repo that will allow you to achieve what you need. Without going into into much detail.

Created two extra components:
- `src\components\SimpleGalleryWithJSONGraphql.js` contains a simple implementation on how you retrieve the images and JSON data with `gatsby-transformer.json` and filter out the results and feed the `react-photo-gallery` data
- `src\components\SimpleGalleryWithJSONImport.js` contains almost the same thing as above, but in this case the JSON content is directly imported over without the need of the plugin

Also as a bonus i've updated `gatsby-node.js` to allow you to generate a page with a image gallery programmatically, removing the need of the plugin again. It will import the json content directly, make a single graphql query to fetch the images, filter the images based on the json content and make use of Gatsby's `context` prop to pass in the data. Turning the template into a simple display. 

Once again the code is commented out, up to you on how you wish to proceed, should any issues/ questions pop up about it, feel free to ask.

And once again, no need to thank

**Comment by santiagosj** [comment] 2020-01-10 10:23
@jonniebigodes great!, thanks for the repo, I'll use it to change my code, have a great 2020!

**Comment by jonniebigodes** [comment] 2020-01-10 16:03
@santiagosj no problem, glad that i was able to help you. And same to you, have a excelent 2020. Should any related issues pop up feel free to re-open it and leave a comment.
