### ISSUE TITLE
On page load, source is displayed before being rendered

### ISSUE THREAD

**Issue by davwheat** [gatsbyjs/gatsby#19061] opened 2019-10-27 12:29 UTC
## Description

When loading a page rendered by Gatsby, the source for it is shown momentarily before it is rendered.

### Steps to reproduce

Example project: https://github.com/davwheat/GCSE-Revision-Website

Serve it with `gatsby build && gatsby serve`. Open the site.

Example URL: https://gcse-revision-site.firebaseapp.com/

### Expected result

Page should either remain blank while loading.

### Actual result

Page displays its source code on a blank page for a few seconds before displaying the rendered content (or sometimes not even doing that).

### Environment

NB: Also happens on my Windows machine.

```
  System:
    OS: macOS 10.15
    CPU: (4) x64 Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    npm: 6.12.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.120
    Safari: 13.0.2
  npmPackages:
    gatsby: ^2.16.3 => 2.16.3 
    gatsby-image: ^2.2.29 => 2.2.29 
    gatsby-plugin-google-adsense: ^1.1.3 => 1.1.3 
    gatsby-plugin-manifest: ^2.2.23 => 2.2.23 
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.6 
    gatsby-plugin-offline: ^3.0.16 => 3.0.16 
    gatsby-plugin-react-helmet: ^3.1.13 => 3.1.13 
    gatsby-plugin-remove-console: 0.0.2 => 0.0.2 
    gatsby-plugin-sharp: ^2.2.31 => 2.2.31 
    gatsby-remark-images: ^3.1.28 => 3.1.28 
    gatsby-source-filesystem: ^2.1.33 => 2.1.33 
    gatsby-theme-material-ui: ^1.0.5 => 1.0.5 
    gatsby-transformer-remark: ^2.6.30 => 2.6.30 
    gatsby-transformer-sharp: ^2.2.23 => 2.2.23 
  npmGlobalPackages:
    gatsby-cli: 2.8.5
```

**Comment by roh8raut** [comment] 2019-10-27 18:53
Gonna take this issue

**Comment by roh8raut** [comment] 2019-10-29 04:37
Ok @davwheat  if the issue is still persisting will look into it.

**Comment by davwheat** [comment] 2019-10-29 12:00
@roh8raut Thank you!

**Comment by roh8raut** [comment] 2019-11-02 08:50
Hi @davwheat is there any way i can connect to you i want to discuss few things?

**Comment by davwheat** [comment] 2019-11-03 19:12
@roh8raut In what way? I have Discord, if you also have that. You can also reach me on Telegram under my GitHub username.

**Comment by davwheat** [comment] 2019-11-10 12:44
@roh8raut Any updates on this issue?

**Comment by roh8raut** [comment] 2019-11-10 12:53
Hi David ,

I am currently occupied with another things. Ill try to look into this
sooner

**Comment by davwheat** [comment] 2019-11-11 21:49
Update: this **only happens with a build** and does not happen in `gatsby develop` mode.

**Comment by teisenhower** [comment] 2020-02-10 23:16
Hello,

Have there been any updates on this? I am helping with another project and they are having this same exact issue.

Develop mode shows no issues.

Build version flashes the raw HTML code within the `___gatsby` div

![window](https://user-images.githubusercontent.com/47988669/74198911-ac3c5e00-4c30-11ea-846a-08f611a12914.png)

**Comment by sidharthachatterjee** [comment] 2020-02-12 21:39
Hey @davwheat 

I'm not sure why you're seeing this but I most definitely can't reproduce this. The first request for the HTML serves HTML correctly for me 

<img width="750" alt="Screenshot 2020-02-13 at 3 07 11 AM" src="https://user-images.githubusercontent.com/7701981/74379530-faf31f00-4e0d-11ea-9ac9-85087773f525.png">

If you're referring to some of the page loading after the stuff in the hero section, I can see that some of it renders only after JavaScript is loaded (Disabling JavaScript should show you what I mean)

This doesn't seem to be a Gatsby issue nonetheless and _might_ have to do with your hosting setup perhaps in case you're still seeing this? 

I'll go ahead and close this for now but please let us know if there is anything else we can do to help. Thanks!

**Closed by sidharthachatterjee** 2020-02-12 21:39 UTC
Labels: status: community assigned, type: bug
