### ISSUE TITLE
gatsby-plugin-mdx: newline in the list causes whole list (at 3 or deeper indentation levels) rendered as code

### ISSUE THREAD

**Issue by Stvad** [gatsbyjs/gatsby#28813] opened 2021-01-02 05:05 UTC
## Description

When rendering markdown newline in the list causes whole list (at 3 or deeper indentation levels) rendered as code

### Steps to reproduce

Try rendering the following markdown:
```
- lists
- are
  - awesome
  - the
    - deeper
the better
    - but they don't work :(

```

### Expected result

As rendered here and in any other place I tried - the newline is interpreted as continuation of the given list item:

- lists
- are
  - awesome
  - the
    - deeper
the better
    - but they don't work :(

### Actual result

Parts of the list indented further then 4 spaces rendered as code

![image](https://user-images.githubusercontent.com/81347/103451104-bdd98a80-4c74-11eb-814d-b4380c0cd615.png)

### Environment

```
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.5.0 - ~/.nvm/versions/node/v15.5.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.3.0 - ~/.nvm/versions/node/v15.5.0/bin/npm
  Languages:
    Python: 3.8.5 - /Users/sitalov/.pyenv/shims/python
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 84.0
    Safari: 14.0.2
  npmPackages:
    gatsby: ^2.21.37 => 2.29.3 
  npmGlobalPackages:
    gatsby-cli: 2.16.2
    gatsby-source-roamresearch: 0.4.1
    gatsby: 2.29.3

```

**Comment by LekoArts** [comment] 2021-01-05 09:11
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-01-13 09:48
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Comment by Stvad** [comment] 2021-01-15 05:47
Hi, it does not seem possible for me to reopen the issue :(  
I'll look into creating the min reproduction, but I felt like this has a very simple example attached. Is there anything unclear in issue description?

**Comment by LekoArts** [comment] 2021-01-15 10:49
`gatsby-plugin-mdx` has many moving pieces and you can add any amount of plugins to it. You're also using `gatsby-source-roamresearch` which could also mess things up. This could also be just how the underlying libraries parse it, e.g. if you would indent the "the better" it might work. Thus a minimal reproduction is needed.

**Comment by Stvad** [comment] 2021-01-16 06:09
please find reproduction in https://github.com/Stvad/repro-28813

**Comment by Stvad** [comment] 2021-01-25 04:32
@LekoArts  did you have a chance to look at it?

**Comment by ascorbic** [comment] 2021-01-28 12:03
Hi. This seems to be an upstream issue with MDX. Take a look at your code in the playground: https://mdxjs.com/playground

**Closed by ascorbic** 2021-01-28 12:03 UTC
Labels: status: needs reproduction, type: bug
