### ISSUE TITLE
Wrong display of gatsby-plugin-sass page

### ISSUE THREAD

**Issue by pkino** [gatsbyjs/gatsby#24524] opened 2020-05-27 08:11 UTC
## Description
There is something wrong with the display of the page of "gatsby-plugin-sass".
There is only "README.md".
https://www.gatsbyjs.org/packages/gatsby-plugin-sass/

<img width="1435" alt="スクリーンショット 2020-05-27 17 06 45" src="https://user-images.githubusercontent.com/22070311/82994351-f3fac000-a03c-11ea-80a8-c8abbd5c89d3.png">

### Steps to reproduce
Go to https://www.gatsbyjs.org/packages/gatsby-plugin-sass/

### Expected result
Display a proper page.

### Actual result
Display the only phrase "README.md".

**Comment by LekoArts** [comment] 2020-05-27 09:09
Thanks for the issue but this is a duplicate of https://github.com/gatsbyjs/gatsby/issues/24137

**Closed by LekoArts** 2020-05-27 09:09 UTC
Labels: topic: website
