### ISSUE TITLE
Looping through objects causes href links to be offset / shifted?

### ISSUE THREAD

**Issue by tr1s** [gatsbyjs/gatsby#24962] opened 2020-06-12 16:49 UTC
## Description

During my time working on the [Juno College website](https://junocollege.com) there has been a few instances of links being offset when looping through objects.

For example on the [Alumni page](https://junocollege.com/alumni), people would report to me that when clicking on someones website link, it would actually show the website of the person next on the list. This has also happened on the [events page](https://junocollege.com/events) with the events links, which debunks my theory that this only happens with "templated" pages. Because the Alumni page uses templates with gatsby-node/create-pages/graphql for the data, and the event page just uses regular pages with `useStaticQuery` for the data.

This isn't currently a problem, if. **happens rarely**, but I'm just hoping for some insight as to why it might happen for some people sometimes, and why it might fix itself randomly? The master build is getting triggered multiple times a day from a Contentful hook so I assume maybe sometimes the builds get jumbled and then it fixes itself?

Anyway, if anyone knows what could be the issue, or if you've experienced this before, let me know! I'd love to chat about it.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

Sorry I can't give info, this is currently returning:
```
/Users/tris/.nvm/versions/node/v13.6.0/lib/node_modules/gatsby-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: No valid exports main found for '/Users/tris/.nvm/versions/node/v13.6.0/lib/node_modules/gatsby-cli/node_modules/@urql/core'
    at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
    at applyExports (internal/modules/cjs/loader.js:502:14)
    at resolveExports (internal/modules/cjs/loader.js:551:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/tris/.nvm/versions/node/v13.6.0/lib/node_modules/gatsby-cli/node_modules/urql/dist/urql.js:73:12)
    at Module._compile (internal/modules/cjs/loader.js:1144:30) {
  code: 'MODULE_NOT_FOUND'
}
```

Just something else I'll have to look into.

**Comment by schwartzmj** [comment] 2020-06-14 05:13
I may have seen something similar. In my case I was looping through nav links and one of them was for a shopping cart page, except that nav link would only render if there were items in the cart. This cart check was async, so the rendering logic didn't return anything immediately, but would instead load (or not load) a cart button after that split second of checking the cart status.

This would never affect subsequent page loads because the cart information was stored in some app context, but the first time loading the website here's what would happen: the cart would display correctly (the correct cart icon, the correct number of items in the cart), but the url for the link would be for the Nav item next to it. The interesting thing is that if you clicked the link, it would still go to the cart page even though the browser wasn't showing the cart url. I imagine it still worked because Gatsby intercepts it via javascript.

Anyways, I found that I could fix it by wrapping <Link> with a div. I figure there was some strange rendering logic going on with the Link component.

Not sure if that helps at all but figured I'd share. My issue could be specific to the Link component.

**Comment by LekoArts** [comment] 2020-06-16 07:49
Hi, thanks for the issue!
I don't think this is an error in Gatsby but your React code / specific site. Without a [reproduction][reproduction] of this specific issue we can't move forward with this issue. Thanks!

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2020-06-23 10:57
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-06-23 10:57 UTC
Labels: status: needs reproduction, type: question or discussion

**Comment by tr1s** [comment] 2020-07-22 17:27
We finally got it sorted.

We "moved student categorizing to a useEffect to keep server/client in-sync".

> I believe offset linking issue is being caused by the SSR version of the alumni page being out-of-sync with the initial state the client-side version, which is causing dom/shadow dom sync issues because the SSR version is filtering students by one date, but the client-side version is filtering data by another date, and then when React does a re-render it's updating certain DOM properties but not all.

> This moves the categorizing into a useEffect, meaning the SSR initial and client initial should always be equal.

> Side-effect: current students will always be empty in SEO passes and current students will instead always be blended into the "all" students, until the page is loaded, at which point the current students will move to the right tab. Seems like a minor side-effect.

Maybe this might help someone in the future that runs into this.
