### ISSUE TITLE
gatsby-plugin-mdx doesn't find local plugins?

### ISSUE THREAD

**Issue by nextriot** [gatsbyjs/gatsby#23194] opened 2020-04-16 18:45 UTC
Is this expected? Known issue? 

```js
{
  resolve: `gatsby-plugin-mdx`,
  options: {
    gatsbyRemarkPlugins: [
      `my-local-plugin`, // doesn't work
      {
        resolve: require.resolve('path-to-my-local-plugin') // works
      }
    ]
  }
}
```

**Comment by wardpeet** [comment] 2020-04-17 09:27
Hey @nextriot, it's more like a feature request. This can be handled by gatsby-plugin-mdx.

We're happy to get pull requests.

**Comment by Js-Brecht** [comment] 2020-04-18 07:14
@wardpeet do you think it would it make sense to export [resolvePlugin()](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/bootstrap/load-plugins/load.js#L54-L120) from Gatsby core (or `gatsby-core-utils`, maybe?), effectively making it a public API?  Any plugins that can be extended by additional plugins could then use it to resolve those extensions, and easily remain consistent with Gatsby's behavior.

**Comment by pieh** [comment] 2020-04-20 09:27
There are lots of interconnected issues here. Especially if the `gatsby-plugin-mdx` is declared in theme and not in top-level gatsby-config:
- https://github.com/gatsbyjs/gatsby/issues/21589
- https://github.com/gatsbyjs/gatsby/issues/21592

Note that the issues mostly talk about subplugins being npm packages, but it's actually the same problem for local plugins

Exporting `resolvePlugin` alone wouldn't be enough - there would also need to be some metadata of location of `gatsby-config` that declare given plugin to be able to resolve correctly (to use as `rootDir` param of `resolvePlugin).

On top of that, check this comment https://github.com/gatsbyjs/gatsby/pull/8379#issuecomment-585223189 about work on "selective cache invalidation" - for this to work Gatsby core will need to know about relationships between plugins/subplugins to properly clear caches and exporting `resolvePlugin` will "hide" this information from core, meaning that "selective cache invalidation" won't have enough information to work properly.

**Comment by Js-Brecht** [comment] 2020-04-20 16:51
Definitely a lot more going on than it appears at first glance 😄

**Comment by pieh** [comment] 2020-04-21 17:41
I'll close this issue, because the problem is already captured in https://github.com/gatsbyjs/gatsby/issues/21592 and there's no point in having duplicates.

The `resolvePlugin` option is also already mention there (as well as some limitation of this approach)

**Closed by pieh** 2020-04-21 17:41 UTC
Labels: help wanted, topic: MDX
