### ISSUE TITLE
Broken scroll behaviour involving links with fragments

### ISSUE THREAD

**Issue by wodin** [gatsbyjs/gatsby#3116] opened 2017-12-03 06:47 UTC
On https://www.gatsbyjs.org/docs/deploy-gatsby/, scrolled all the way to the top, click on one of the top three links, e.g. GitLab Pages. That scrolls down the page to the right section. Now click the browser's Back button and nothing happens, except the fragment is removed from the URL in the location bar.

I can reproduce this with latest Firefox and Chrome/Chromium on macOS, Linux and Windows 10 and Safari on macOS. I _cannot_ reproduce this on Edge on Windows 10.

**Comment by ivorpad** [comment] 2017-12-04 00:56
I can't reproduce this in Chrome v62.0.3202.94. All fine.

**Comment by wodin** [comment] 2017-12-04 07:11
Not sure what to tell you. I can. On multiple machines/VMs/operating systems and browsers. So far the only one that I cannot reproduce this on is Edge, although I haven't tried IE or Opera, etc. I've just double checked the version of Chrome on a couple of the machines and it is v62.0.3202.94.

Here's a demonstration: https://gfycat.com/AmusedAdmirableCub

**Comment by markmichon** [comment] 2017-12-04 13:28
I couldn't reproduce in latest FF, but I am seeing the behavior in latest chrome on OSX.

**Comment by wodin** [comment] 2017-12-04 13:59
Well at least I might not be hallucinating! :)

However, I can reproduce this on FF (57.0.1, some 32 bit and some 64 bit) on macOS, Linux and Windows. I have no idea what could be different about these machines compared to yours such that this doesn't happen for you.

If there's any other information I can provide to help get this diagnosed, let me know. Or is this perhaps something that Gatsby has no control over?

**Comment by m-allanson** [comment] 2018-04-18 14:49
I just tried this on macOS and couldn't replicate with Firefox, but could with Safari and Chrome. 

Versions:

- Firefox 59.0.2 (64-bit)
- Safari 11.1 (13605.1.33.1.2)
- Chrome 65.0.3325.181 (Official Build) (64-bit)

Fixes welcome if anyone can investigate further!

**Comment by KyleAMathews** [comment] 2018-09-08 04:36
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Closed by KyleAMathews** 2018-09-08 04:36 UTC
Labels: status: help wanted, type: question or discussion
