### ISSUE TITLE
yoga-layout-prebuilt error with gatsby v3

### ISSUE THREAD

**Issue by ahmadkhalaf1** [gatsbyjs/gatsby#30485] opened 2021-03-26 11:14 UTC
Hello , 

since Gatsby V3 i start getting this annoying error , i saw other issues but nothing helped .
gatsby develop will show this error at createPages step

![image](https://user-images.githubusercontent.com/18447392/112623493-b61d2280-8e2c-11eb-85f2-c4f09b30cb31.png)

node info
Now using node v15.10.0 (npm v7.5.3)

```
gatsby info


  System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Shell: 5.5.1 - /bin/zsh
  Binaries:
    Node: 15.10.0 - ~/.nvm/versions/node/v15.10.0/bin/node
    npm: 6.13.6 - ~/node_modules/.bin/npm
  Browsers:
    Chrome: 87.0.4280.141
    Firefox: 72.0.1
  npmPackages:
    gatsby: ^3.1.2 => 3.1.2
    gatsby-background-image: ^1.5.0 => 1.5.0
    gatsby-image: ^3.1.0 => 3.1.0
    gatsby-link: ^3.1.0 => 3.1.0
    gatsby-plugin-catch-links: ^3.1.0 => 3.1.0
    gatsby-plugin-emotion: ^6.1.0 => 6.1.0
    gatsby-plugin-exclude: ^1.0.2 => 1.0.2
    gatsby-plugin-gdpr-cookies: ^1.0.14 => 1.0.14
    gatsby-plugin-image: ^1.1.2 => 1.1.2
    gatsby-plugin-local-search: ^2.0.0 => 2.0.0
    gatsby-plugin-manifest: ^3.1.0 => 3.1.0
    gatsby-plugin-preact: ^5.1.0 => 5.1.0
    gatsby-plugin-preconnect: ^1.2.0 => 1.2.0
    gatsby-plugin-react-helmet: ^4.1.0 => 4.1.0
    gatsby-plugin-react-helmet-canonical-urls: ^1.4.0 => 1.4.0
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-robots-txt: ^1.5.5 => 1.5.5
    gatsby-plugin-s3: ^0.3.8 => 0.3.8
    gatsby-plugin-sharp: ^3.1.2 => 3.1.2
    gatsby-plugin-sitemap: ^3.1.0 => 3.1.0
    gatsby-plugin-typescript: ^3.1.0 => 3.1.0
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.21 => 1.1.21
    gatsby-source-filesystem: ^3.1.0 => 3.1.0
    gatsby-transformer-sharp: ^3.1.0 => 3.1.0

```

however with gatsby v2 same code will work fine.
working version below 
```
  System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
    Shell: 5.5.1 - /bin/zsh
  Binaries:
    Node: 15.10.0 - ~/.nvm/versions/node/v15.10.0/bin/node
    npm: 6.13.6 - ~/node_modules/.bin/npm
  Browsers:
    Chrome: 87.0.4280.141
    Firefox: 72.0.1
  npmPackages:
    gatsby: ^2.32.7 => 2.32.7
    gatsby-background-image: ^1.4.1 => 1.4.1
    gatsby-image: ^2.11.0 => 2.11.0
    gatsby-link: 2.11.0 => 2.11.0
    gatsby-plugin-catch-links: ^2.10.0 => 2.10.0
    gatsby-plugin-exclude: ^1.0.2 => 1.0.2
    gatsby-plugin-gdpr-cookies: ^1.0.12 => 1.0.12
    gatsby-plugin-local-search: ^2.0.0 => 2.0.0
    gatsby-plugin-manifest: ^2.12.1 => 2.12.1
    gatsby-plugin-preact: ^4.7.0 => 4.7.0
    gatsby-plugin-preconnect: ^1.1.54 => 1.1.54
    gatsby-plugin-react-helmet: 3.10.0 => 3.10.0
    gatsby-plugin-react-helmet-canonical-urls: ^1.4.0 => 1.4.0
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0
    gatsby-plugin-remove-serviceworker: ^1.0.0 => 1.0.0
    gatsby-plugin-robots-txt: ^1.5.5 => 1.5.5
    gatsby-plugin-s3: ^0.3.8 => 0.3.8
    gatsby-plugin-sharp: ^2.14.3 => 2.14.3
    gatsby-plugin-sitemap: 2.12.0 => 2.12.0
    gatsby-plugin-typescript: ^2.12.1 => 2.12.1
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.20 => 1.1.20
    gatsby-source-filesystem: 2.11.1 => 2.11.1
    gatsby-transformer-sharp: ^2.12.0 => 2.12.0
```

Thanks

**Comment by vladar** [comment] 2021-03-26 18:26
Hi @ahmadkhalaf1

The error seems to be related to potrace and `traceSVG` argument. Can you remove any usages of `traceSVG` in your project temporarily to confirm if that's the case?

To say something more specific we will need a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by ahmadkhalaf1** [comment] 2021-03-29 13:08
> Hi @ahmadkhalaf1
> 
> The error seems to be related to potrace and `traceSVG` argument. Can you remove any usages of `traceSVG` in your project temporarily to confirm if that's the case?
> 
> To say something more specific we will need a [minimal reproduction](https://gatsby.dev/reproduction). This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.
> 
> If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction](https://gatsby.dev/reproduction) and we'll be able to take another look.
> 
> Thanks for using Gatsby!

Thank you so much for your reply and time , 
you are 100% correct , after removing all tracedSVG from placeholder with the new Image Plugin , it worked fine again , 
however tracedSVG is really important for my site performance for my Images above the fold , what can we do to fix this ?

Thanks

**Comment by wardpeet** [comment] 2021-04-01 14:19
We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Closed** 2021-04-01 14:18 UTC
Labels: topic: sharp, type: bug
