### ISSUE TITLE
How to disable status bar - gatsby develop

### ISSUE THREAD

**Issue by MattixNow** [gatsbyjs/gatsby#24971] opened 2020-06-13 11:01 UTC
## Summary

how to disable the status bar ? it take a lot of space on the screen
![Annotation 2020-06-02 174919](https://user-images.githubusercontent.com/32040951/84566996-e2702280-ad75-11ea-9dde-e883978e597d.jpg)

**Comment by herecydev** [comment] 2020-06-13 13:42
Closing as a duplicate of #24630

**Closed by herecydev** 2020-06-13 13:42 UTC
Labels: status: triage needed, type: question or discussion

**Comment by MattixNow** [comment] 2020-06-13 14:00
@herecydev I wanted to know how to disable the status bar feature

**Comment by herecydev** [comment] 2020-06-13 14:17
There is no way, you could open a PR to change that but I'm not sure if it would be accepted given the feedback in the previous ticket
