### ISSUE TITLE
Page components don't support export { default } syntax

### ISSUE THREAD

**Issue by robertjk** [gatsbyjs/gatsby#25927] opened 2020-07-21 19:30 UTC
## Description

Page components in `src/pages/` don't support `export { default } from "...";` syntax. Whenever any of my page components has this syntax, I'm getting the following build error on `npm run build`:

```
Using environment config: 'local'
success open and validate gatsby-configs - 0.088s
success load plugins - 0.390s
success onPreInit - 0.002s
success delete html and css files from previous builds - 0.017s
success initialize cache - 0.005s
success copy gatsby files - 0.028s
success onPreBootstrap - 0.009s
success createSchemaCustomization - 0.004s
success source and transform nodes - 0.017s
success building schema - 0.160s
success createPages - 0.001s

 ERROR #11328

A page component must export a React component for it to be valid. Please make sure this file exports a React component:

undefined

not finished createPagesStatefully - 0.079s
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! landing-website-gatsby@0.1.0 build: `gatsby build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the landing-website-gatsby@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/robert/.npm/_logs/2020-07-21T19_20_12_218Z-debug.log
```

As soon as I refactor `export { default } from "...";` to `export { default as default } from "...";` the build process runs without errors. But then the linter raises warnings: `warning  Export default unnecessarily renamed  no-useless-rename`.

It's also worth noting that any non-page components in `src/components/` can have `export { default } from "...";` and the build process still works fine. The problem only appears in page components in `src/pages/`.

So I assume it's some part of the building pages process that doesn't support that syntax.

Here is [documentation of export statement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export), which clearly lists `export { deafult }` as a valid syntax.

### Steps to reproduce

1. Rename `src/pages/index.js` to `src/pages/Home.js`.
2. Create `src/pages/index.js` with the following contents:
    ```javascript
    export { default } from "./Home";
    ```
3. Run `npm run build`.
4. Change contents of `src/pages/index.js` to:
    ```javascript
    export { default as default } from "./Home";
    ```
5. Run `npm run build` again.

### Expected result

The build should run fine both times.

### Actual result

The first build ends with an error pasted below. The second build runs successfully, but the linter reports some warnings on `no-useless-rename` rule.

```
success createPages - 0.001s

 ERROR #11328

A page component must export a React component for it to be valid. Please make sure this file exports a React component:
```3

### Environment


  System:
    OS: Linux 5.7 Arch Linux
    CPU: (12) x64 Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.5.0 - /sbin/node
    Yarn: 1.22.4 - /sbin/yarn
    npm: 6.14.6 - /sbin/npm
  Languages:
    Python: 3.8.3 - /sbin/python

**Comment by wardpeet** [comment] 2020-07-22 06:32
Thank you for reporting this issue. It's valid syntax and it's something we have overlooked.

We're open to receive pull requests to fix this bug.
The code where we validate page components exports is at
https://github.com/gatsbyjs/gatsby/blob/405d3c25caeb533af08edbc589dc50fa8fc32ace/packages/gatsby/src/utils/validate-page-component.ts#L79-L84

We don't have any tests for that file. We should because it's some logic that has some rough edges like the one you pointed out.

Let me know if more information is needed to squash this bug! 💪

**Comment by tanmaylaud** [comment] 2020-07-22 12:51
@wardpeet I would like to work on this issue if it is active

**Comment by adarshaacharya** [comment] 2020-07-23 10:43
@wardpeet  I would like to work on this issue , I think I'e figured out issue.

**Comment by wardpeet** [comment] 2020-07-23 20:10
@tanmaylaud Feel free to do so 👍 

@adarshaacharya @tanmaylaud was first so we'll let him work on it. If something comes up we'll ping you to take over.

Thank you very much for contributing!

**Comment by selrond** [comment] 2020-08-07 12:45
this issue is a duplicate of #12384

**Comment by selrond** [comment] 2020-08-07 12:46
We should probably close it and move the discussion there @wardpeet ?

**Comment by wardpeet** [comment] 2020-08-10 13:18
oh @selrond  thank you, you're right.

**Closed by wardpeet** 2020-08-10 13:18 UTC
Labels: good first issue, help wanted, status: confirmed, status: duplicate, type: bug
