### ISSUE TITLE
Calling page "new-page" gives TypeError when page does not exist 

### ISSUE THREAD

**Issue by watermelemon** [gatsbyjs/gatsby#20658] opened 2020-01-17 04:28 UTC
## Description

Hi everyone, I am working on a Gatsby website and I had created a page called "new-page".  This had the URL "localhost:8000/new-page".  The page ran perfectly fine, but when I deleted the page and tried to go to the same URL to check that it had been successfully deleted, I did not see the Gatsby 404 development page that I usually see.  Instead, the browser displayed an error called "TypeError: Cannot read property 'page' of undefined".  It showed that the error was in "/ui/.cache/root.js:74"  (line 74 of root.js file) in a command starting with "path={encodeURI(".

No other page names I have tried throw up the same error.  All of the following page names go to the Gatsby 404 development page as expected (none of these pages exist on my site yet):

new-mushroom
newpage
home-page
new-site
default-page
new+page
new=page
new==page
new-pages

### Steps to reproduce

With no "new-page" file in the Pages folder ("/ui/src/pages/"), I typed "localhost:8000/new-page" into the browser (my site is currently running through the localhost 8000 port).  This resulted in the following error message:

![image](https://user-images.githubusercontent.com/59897421/72583897-23394c00-393c-11ea-856d-8465f298631e.png)

### Expected result

I expected to see the Gatsby 404 development page (this appeared for all other page names tried above):

![image](https://user-images.githubusercontent.com/59897421/72584018-8dea8780-393c-11ea-9d04-5c48c6b4d28a.png)

### Actual result

The browser displayed the TypError.  I also noticed that even after "new-page" was deleted, this development 404 page listed "new-page" under the available pages.  Refreshing npm by saving the last page I worked on resulted in the "new-page" being removed from the 404 development page, but the "new-page" URL still gave the same error.

It's possible that this could be an issue with me having only recently deleted the "new-page.js" file under "pages" folder.

I'm thinking that perhaps the name "new-page" is being interpreted as something other than the page's path somewhere in the code, and that perhaps "new-page" is seen as a property or something similar and thus is an invalid name.  Please let me know if you find any other seemingly invalid names for pages, or if "new-page" is a valid page name for you.

**Comment by ascorbic** [comment] 2020-01-17 12:41
Have you restarted `gatsby develop` since you deleted it? Could you try running `gatsby clean`?

**Comment by sidharthachatterjee** [comment] 2020-01-23 15:16
@watermelemon Running `gatsby clean` and restarting `gatsby develop` like @ascorbic (rightly) suggested should do the trick but this is definitely a DX issue which we should fix. 

I'll try to reproduce this locally and mark this confirmed then. Thanks!

**Comment by bogodars** [comment] 2020-01-29 10:09
gatsby clean worked for me as well

**Comment by danabrit** [comment] 2020-05-31 03:23
Marking this closed as there is a fix and there haven't been comments on this issue for months.

**Closed by danabrit** 2020-05-31 03:23 UTC
Labels: type: bug
