### ISSUE TITLE
created Pages cause infinite reload in IE9

### ISSUE THREAD

**Issue by js87zz** [gatsbyjs/gatsby#12985] opened 2019-04-01 09:23 UTC
## Description
I was testing gatsby app with `gatsby build && gatsby serve` in remote desktop app. it's very well performed in chrome, safari, ie11, ie10, edge.

However I got infinite reload loop and messages in IE9 console. 
`html1113(Document mode restart from IE9 Standards to Quirks)`
`html1115(x-ua-compatible meta tag ('ie=edge') ignored because document mode is already finalized)`

I confirmed that meta tag and doctype is normal as below.
```<!doctype html>```
```<meta http-equiv="x-ua-compatible" content="ie=edge">```(top in the head tag)

Strangely index main page is stable.. only created pages cause infinite loop in `gatsby-node.js`
I don't know why created page is reloaded infinitely in IE9...

please let me know the cause and solution..thank you in advance.

// gatsby-node.js
```
exports.createPages = ({actions, graphql}) => {
  const {createPage} = actions;

  return graphql(
    `
      {
        allProductsJson {
          edges {
            node {
              id
              type
            }
          }
        }
      }
    `
  ).then(result => {
    if (result.errors) {
      throw result.errors;
    }

    result.data.allProductsJson.edges.forEach(edge => {
      const {id, type} = edge.node;

      if (type !== 'tool') {
        createPage({
          path: `/${id}`,
          component: path.resolve(`./src/templates/DetailPage.js`),
          context: {
            id: id
          }
        });
      }
    });
  });
};
```
// DetailPage.js
```
class DetailPage extends React.PureComponent {
  constructor(props) {
    super(props);
    this.state = {
      selectedIndex: 0
    };
    this.selectTab = this.selectTab.bind(this);
  }

  selectTab(index) {
    this.setState({selectedIndex: index});
  }

  render() {
    const data = this.props.data;
    const {markdownRemark, productsJson} = data;
    const html = markdownRemark ? replaceInvalidHtml(markdownRemark.html) : '';

    return (
      <div className="contents">
        <IntroSection data={productsJson} />
        <div className="content-html">
          <div className="content-container" dangerouslySetInnerHTML={{__html: html}} />
        </div>
      </div>
    );
  }
}

DetailPage.propTypes = {
  data: PropTypes.shape({
    markdownRemark: PropTypes.object.isRequired,
    productsJson: PropTypes.object.isRequired
  })
};

export default DetailPage;

export const query = graphql`
  query DetailPage($id: String!) {
    # query for demo
    productsJson(id: {eq: $id}) {
      id
      name
      description
      demo
      demoSrc
      demoTitles
      type
      link
    }

    # query for title and article
    markdownRemark(frontmatter: {path: {eq: $id}}) {
      html
      frontmatter {
        path
      }
    }
  }
`;
```

## Version
* "gatsby": "^2.1.31",
* "gatsby-plugin-favicon": "^3.1.5",
* "gatsby-plugin-layout": "^1.0.13",
* "gatsby-plugin-react-helmet": "^3.0.9",
* "gatsby-remark-prismjs": "^3.2.5",
* "gatsby-source-filesystem": "^2.0.24",
* "gatsby-transformer-json": "^2.1.11",
* "gatsby-transformer-remark": "^2.3.4",
* "react": "^16.8.4",
* "react-dom": "^16.8.4",
* "react-helmet": "^5.2.0"

**Comment by pieh** [comment] 2019-04-01 13:11
Can you provide reproduction / link to hosted version of your site? 

We did verify that there are some issues with gatsby sites on IE9:
![Screenshot 2019-04-01 at 15 09 14](https://user-images.githubusercontent.com/419821/55330063-694a1f80-5490-11e9-93d0-52cfbfd62bb4.png)

But we didn't see error you are reporting.

**Comment by js87zz** [comment] 2019-04-02 01:01
I've tested my site in local env before production. so it's hard to provide site host.

But I tested using `https://github.com/gatsbyjs/gatsby-starter-blog` kit in IE9 through remote desktop app after making `my-blog-starter` more simple. and then when I accessed the `/hello-world`, I got same infinite loop . 

I changed `my-blog-starter` as below. really simple.

// gatsby-config.js (without any plugin)
```
module.exports = {
  siteMetadata: {
    title: `Gatsby Starter Blog`,
    author: `Kyle Mathews`,
    description: `A starter blog demonstrating what Gatsby can do.`,
    siteUrl: `https://gatsby-starter-blog-demo.netlify.com/`,
    social: {
      twitter: `kylemathews`,
    },
  }
}
```
// gatsby-node.js (only create one page `hello-world`)
```
const path = require(`path`)

exports.createPages = ({ graphql, actions }) => {
  const { createPage } = actions

  const blogPost = path.resolve(`./src/templates/blog-post.js`)
  return Promise.resolve().then(() => {
    createPage({
      path: `/hello-world`,
      component: blogPost,
      context: {
        id: 'hello-world'
      }
    });

    return null;
  });
}

exports.onCreateNode = ({ node, actions, getNode }) => {
  const { createNodeField } = actions

  if (node.internal.type === `MarkdownRemark`) {
    const value = createFilePath({ node, getNode })
    createNodeField({
      name: `slug`,
      node,
      value,
    })
  }
}
```

// layout.js
```
import React from "react"

const layout = (props) => (<div>{props.children}</div>)
export default layout;
```

// pages/index.js
```
import React from "react"

const index = (props) => (<div>index</div>)
export default index;
```

I've captured it.
![infinite_loop](https://user-images.githubusercontent.com/37766175/55368697-2f2f5b00-552e-11e9-9bd9-5f1a0ced02af.gif)

**Comment by js87zz** [comment] 2019-04-03 01:06
@pieh 
I understand `reproduction / link` you said now..
sorry and thank you for looking into this problem.

And I found that infinite loop is caused in IE9 when run script `gatsby build && gatsby serve --host=x.x.x.x`..
when i deloy throuth gh-pages, it's OK.

this is my reproduction test link.
 
git: https://github.com/js87zz/gatsby-reproduction-test
host: https://js87zz.github.io/gatsby-reproduction-test/hello-world/

**Comment by sidharthachatterjee** [comment] 2019-04-10 22:34
Closing this as a duplicate of https://github.com/gatsbyjs/gatsby/issues/13262 and since the latter has more context

**Closed by sidharthachatterjee** 2019-04-10 22:34 UTC
Labels: status: needs reproduction
