### ISSUE TITLE
Getting this error after running 'npm update'

### ISSUE THREAD

**Issue by rchrdnsh** [gatsbyjs/gatsby#27296] opened 2020-10-05 20:38 UTC
## Description

Ran `npm update` in the terminal and now a few pages are not working that were working before, with the following error in the browser window and in the console:

```console
debug.module.js:1 Uncaught TypeError: Cannot read property 'on' of undefined
    at Object.__ (bundle.js:1)
    at g (hooks.module.js:1)
    at Array.forEach (<anonymous>)
    at hooks.module.js:1
    at Array.some (<anonymous>)
    at q (hooks.module.js:1)
```

screenshot:

<img width="433" alt="Screen Shot 2020-10-05 at 1 41 12 PM" src="https://user-images.githubusercontent.com/7884263/95129828-717fbc80-0710-11eb-9e29-7150cf3f038b.png">

### Steps to reproduce

I just ran npm update on a project, so I am assuming it's possibly a bug introduced into gatsby or a dependancy. Just want to give the team a heads-up.

### Expected result

What should happen?

### Actual result

What happened.

### Environment

```bash
^CRN:RYKR rchrdnsh$ gatsby info --clipboard

 ERROR 

(node:89151) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time


 ERROR 

UNHANDLED REJECTION e.filter is not a function



  TypeError: e.filter is not a function
  
  - envinfo.js:1 
    [lib]/[gatsby-cli]/[envinfo]/dist/envinfo.js:1:73205
  
  - task_queues.js:97 processTicksAndRejections
    internal/process/task_queues.js:97:5
  
  - async Promise.all
```

...this seems broken as well?

**Comment by LekoArts** [comment] 2020-10-06 07:20
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by rchrdnsh** [comment] 2020-10-07 20:01
I honestly have no idea where to even start to create a minimal repro on this one...dunno what I'm looking at or what is going wrong...I did turn off preact in my gatsby-config and now the error message is more robust:

<img width="931" alt="Screen Shot 2020-10-07 at 12 59 24 PM" src="https://user-images.githubusercontent.com/7884263/95381438-01eb0800-089d-11eb-95b2-c9d01b467774.png">

...and it looks like the issue is from a Web MIDI Library I am using...I will reach out to them and see if they have any ideas about what might be going on...but this library has been working just fine for months now, and only stopped working when I ran `npm update`, soo...dunno what that means...I will try to investigate further myself and see if I can figure more out from both the gatsby perspective and the library perspective...

**Comment by LekoArts** [comment] 2020-10-19 08:28
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-10-19 08:28 UTC
Labels: status: needs reproduction
