### ISSUE TITLE
gatsby-plugin-offline with password protection shows blank page instead of authentication dialog

### ISSUE THREAD

**Issue by jordan314** [gatsbyjs/gatsby#26942] opened 2020-09-17 17:28 UTC
## Description

We are using lambda@edge to render the website if http authentication is given, or otherwise show a 401 an unauthorized header. When the authentication expires, gatsby-plugin-offline renders the base HTML, but all of the page assets return 401s, so you see a blank page.

### Steps to reproduce

Log into a password-protected website, then revisit the page the next day. 

### Expected result

The authorization headers should pop up and allow you to reauthorize.

### Actual result

gatsby-plugin-offline renders part of the page

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
System:
    OS: macOS 10.15.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 3.0.2 - /usr/local/bin/fish
  Binaries:
    Node: 13.12.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 85.0.4183.102
    Firefox: 80.0
    Safari: 13.1.2
  npmPackages:
    gatsby: https://github.com/brandsoulmates/gatsby-soulmates.git => 2.19.28
    gatsby-cli: ^2.8.2 => 2.10.4
    gatsby-image: ^2.1.4 => 2.2.43
    gatsby-link: ^2.2.29 => 2.2.30
    gatsby-plugin-canonical-urls: ^2.0.12 => 2.1.21
    gatsby-plugin-catch-links: ^2.0.13 => 2.1.27
    gatsby-plugin-feed: ^2.2.3 => 2.3.28
    gatsby-plugin-google-tagmanager: ^2.1.24 => 2.1.26
    gatsby-plugin-i18n: ^1.0.1 => 1.0.1
    gatsby-plugin-manifest: ^2.2.33 => 2.2.45
    gatsby-plugin-netlify: ^2.0.15 => 2.1.34
    gatsby-plugin-offline: ^2.1.3 => 2.2.10
    gatsby-plugin-react-helmet: ^3.0.12 => 3.1.23
    gatsby-plugin-s3: ^0.3.2 => 0.3.3
    gatsby-plugin-schema-snapshot: ^1.0.0 => 1.0.0
    gatsby-plugin-sharp: ^2.1.5 => 2.4.8
    gatsby-plugin-sitemap: ^2.0.12 => 2.2.28
    gatsby-plugin-styled-components: ^3.0.7 => 3.1.20
    gatsby-react-router-scroll: ^2.1.22 => 2.1.23
    gatsby-remark-autolink-headers: ^2.0.16 => 2.1.25
    gatsby-remark-images-contentful: ^2.0.10 => 2.1.33
    gatsby-remark-responsive-iframe: ^2.2.10 => 2.2.33
    gatsby-source-contentful: ^2.1.85 => 2.1.92
    gatsby-source-filesystem: ^2.0.39 => 2.1.51
    gatsby-transformer-remark: ^2.3.10 => 2.6.56
    gatsby-transformer-sharp: ^2.1.21 => 2.3.17
  npmGlobalPackages:
    gatsby-cli: 2.7.30

**Comment by ascorbic** [comment] 2020-09-23 12:29
Hi @jordan314,
I think this is a scenario when the offline plugin isn't a good fit, at leats in its default configuration, precisely because you don't want it to serve a cached page to logged-out users. If you don't want to exclude these pages, you might be able to work around it by changing the caching strategy in workbox to ensure that it revalidates the pages. See [the instructions for overriding workbox settings](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-offline#overriding-workbox-configuration).

I'm going to close this now, as it's not a bug, but if you do think it's misbehaving then please do open a new issue. Thanks.

**Closed by ascorbic** 2020-09-23 12:29 UTC
Labels: status: triage needed, type: bug
