### ISSUE TITLE
babel-preset-gatsby not working

### ISSUE THREAD

**Issue by oprogramador** [gatsbyjs/gatsby#21649] opened 2020-02-21 16:39 UTC
When trying to build I get:
```
⟩ ./node_modules/.bin/gatsby build
success delete html and css files from previous builds — 0.018 s
success open and validate gatsby-config — 0.008 s
success copy gatsby files — 0.016 s
success onPreBootstrap — 0.236 s
success source and transform nodes — 0.158 s
success building schema — 0.417 s
success createLayouts — 0.013 s
success createPages — 0.052 s
success createPagesStatefully — 0.018 s
success onPreExtractQueries — 0.001 s
success update schema — 0.156 s
success extract queries from components — 0.067 s
success run graphql queries — 0.267 s
success write out page data — 0.003 s
success write out redirect data — 0.001 s
success onPostBootstrap — 0.001 s

info bootstrap finished - 2.961 s

success Building CSS — 0.472 s

error Generating JavaScript bundles failed


  Error: ./.cache/production-app.js
  Module build failed: Error: `babel-preset-gatsby` has been loaded, which consumes config generated by the Gatsby CLI. Set `NODE_ENV=test` to bypass, or run `gatsby build` first. (While processing preset  : "/Users/oprogramador/project-1/docs-www/node_modules/babel-preset-gatsby/index.js")
      at loadCachedConfig (/Users/oprogramador/project-1/docs-www/node_modules/babel-preset-gatsby/index.js:18:15)
      at preset (/Users/oprogramador/project-1/docs-www/node_modules/babel-preset-gatsby/index.js:34:29)
      at /Users/oprogramador/project-1/docs-www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:317:46
      at Array.map (<anonymous>)
      at OptionManager.resolvePresets (/Users/oprogramador/project-1/docs-www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
      at OptionManager.mergePresets (/Users/oprogramador/project-1/docs-www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
      at OptionManager.mergeOptions (/Users/oprogramador/project-1/docs-www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
      at OptionManager.init (/Users/oprogramador/project-1/docs-www/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
      at File.initOptions (/Users/oprogramador/project-1/docs-www/node_modules/babel-core/lib/transformation/file/index.js:212:65)
      at new File (/Users/oprogramador/project-1/docs-www/node_modules/babel-core/lib/transformation/file/index.js:135:24)
      at Pipeline.transform (/Users/oprogramador/project-1/docs-www/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
      at transpile (/Users/oprogramador/project-1/docs-www/node_modules/babel-loader/lib/index.js:46:20)
      at /Users/oprogramador/project-1/docs-www/node_modules/babel-loader/lib/fs-cache.js:79:18
      at ReadFileContext.callback (/Users/oprogramador/project-1/docs-www/node_modules/babel-loader/lib/fs-cache.js:15:14)
      at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:237:13)
```

My `.babelrc`:
```
{
  "presets": ["babel-preset-gatsby"]
}
```

### Environment
```
⟩ ./node_modules/.bin/gatsby info

  System:
    OS: macOS 10.14.6
    CPU: x64 Intel(R) Core(TM) i7-3635QM CPU @ 2.40GHz
    Shell: 2.4.0 - /usr/local/bin/fish
  Binaries:
    Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
  Browsers:
    Firefox: 70.0.1
  npmPackages:
    gatsby: ^1.9.279 => 1.9.279
```

**Comment by TylerBarnes** [comment] 2020-02-21 17:14
Hi @oprogramador!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by oprogramador** [comment] 2020-02-21 18:31
@TylerBarnes 

I created https://github.com/oprogramador/babel-preset-gatsby-not-working-example

**Comment by oprogramador** [comment] 2020-02-21 19:09
though it works for gatsby@2 (2.19.19)

**Comment by LekoArts** [comment] 2020-02-21 19:22
What are you trying to do? The preset is intended for packages/plugins, not user sites.

**Comment by oprogramador** [comment] 2020-02-22 00:17
I thought that `babel-preset-gatsby` is a preset providing all the recommended babel plugins for a gatsby project.

**Comment by LekoArts** [comment] 2020-02-22 11:33
Gatsby already handles that for you, you don't need to touch any babel config :)

Closing this issue as answered then 👍

**Closed by LekoArts** 2020-02-22 11:33 UTC
Labels: status: needs reproduction

**Comment by jbertel2** [comment] 2020-05-15 04:46
I face the same issue. While the comments here suggest to not touch .babelrc for a gatsby site, that contradicts the documentation [here](https://www.gatsbyjs.org/docs/babel/#how-to-use-a-custom-babelrc-file).

**Comment by TylerBarnes** [comment] 2020-05-15 18:37
@jbertel2 the comment is that there's no need to touch .babelrc in this specific instance (because `babel-preset-gatsby` is for plugins not for sites and Gatsby handles everything that that plugin does for your site already). You can absolutely use a custom .babelrc file if you need to :)

**Comment by TylerBarnes** [comment] 2020-05-15 21:35
@jbertel2 I tried to reproduce using the hello-world starter and it appears to be working there. Try updating to the latest versions of packages, clear your cache, and run a build again. If it doesn't work please open a new issue with a minimal reproduction. 
Thanks!
