### ISSUE TITLE
adding lastmod property in serialize function doesn't actually work [gatsby-plugin-sitemap]

### ISSUE THREAD

**Issue by brianecook** [gatsbyjs/gatsby#35701] opened 2022-05-19 16:20 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I've followed the instructions [here](https://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap) for how to add a lastmod property to the sitemap generated by gatsby-plugin-sitemap. Adding a value to lastmod in the serialize function, however, does not work. The sitemap is generated, but only has the loc, changefreq, and priority properties set. I've looked at the source code and the serialize function only returns this:

```
function serialize(page, _ref3) {
  var resolvePagePath = _ref3.resolvePagePath;
  return {
    url: "" + resolvePagePath(page),
    changefreq: "daily",
    priority: 0.7
  };
}
```

There isn't actually anything in there that would allow for setting a lastmod property. So there seems to be a discrepency between the documentation and what the plugin actually can do.

Here is the code I am using to try to set the lastmod property per the instructions in the documentation:

```
{
    resolve: 'gatsby-plugin-sitemap',
    options: {
      query: `
      {
        allContentfulPageSectionPage {
          edges {
            node {
              path: slug
              updatedAt
            }
          }
        }
        allContentfulProduct {
          edges {
            node {
              shopifyProduct
            }
          }
        }
        allShopifyProduct {
          edges {
            node {
              storefrontId
              path: handle
              updatedAt
            }
          }
        }
      }
    `,
      resolveSiteUrl: () => 'https://www.nationalfarmstand.com',
      resolvePages: ({
        allContentfulPageSectionPage,
        allContentfulProduct,
        allShopifyProduct,
      }) => {
        const contentfulPages = allContentfulPageSectionPage.edges.map(
          (edge) => edge.node
        );
        const contentfulProductPages = allContentfulProduct.edges
          .map(({ node: { shopifyProduct } }) => {
            const correspondingShopifyProduct = allShopifyProduct.edges.find(
              (edge) => edge.node.storefrontId === shopifyProduct
            );
            if (correspondingShopifyProduct) {
              return {
                path: `/products/${correspondingShopifyProduct.node.path}`,
                updatedAt: correspondingShopifyProduct.node.updatedAt,
              };
            }
          })
          .filter((page) => !!page);

        return [...contentfulPages, ...contentfulProductPages];
      },
      serialize: ({ path, updatedAt }, tools) => { // eslint-disable-line
        return {
          url: path,
          lastmod: moment(updatedAt).format('YYYY-MM-DD'),
        };
      },
    },
  },
```

And here is the sitemap file that is produced

```
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9"
  xmlns:xhtml="http://www.w3.org/1999/xhtml" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"
  xmlns:video="http://www.google.com/schemas/sitemap-video/1.1">
  <url>
    <loc>https://www.nationalfarmstand.com/pacific-northwest-small-farms</loc>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.nationalfarmstand.com/experiences</loc>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.nationalfarmstand.com/southern-small-farms</loc>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
  </url>
  <url>
    <loc>https://www.nationalfarmstand.com/farmers-profile</loc>
    <changefreq>daily</changefreq>
    <priority>0.7</priority>
  </url>
   ...
</urlset>
```

Note: no lastmod property set in sitemap.

### Reproduction Link

https://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap

### Steps to Reproduce

1. Add lastmod property in serialize function
2. No lastmod is set in sitemap.xml

### Expected Result

Expect to see lastmod property in sitemap.xml

### Actual Result

No lastmod property in sitemap.xml, just loc, changefreq, and priority

### Environment

```shell
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 101.0.4951.64
    Safari: 15.4
  npmPackages:
    gatsby: ^4.4.0 => 4.12.1
    gatsby-background-image: ^1.6.0 => 1.6.0
    gatsby-plugin-contentful-optional-fields: ^2.2.2 => 2.2.2
    gatsby-plugin-gatsby-cloud: ^4.4.0 => 4.12.1
    gatsby-plugin-google-gtag: ^4.4.0 => 4.12.1
    gatsby-plugin-google-tagmanager: ^4.13.0 => 4.13.0
    gatsby-plugin-image: ^2.4.0 => 2.12.1
    gatsby-plugin-react-helmet: ^5.4.0 => 5.12.1
    gatsby-plugin-root-import: ^2.0.8 => 2.0.8
    gatsby-plugin-sharp: ^4.4.0 => 4.12.1
    gatsby-plugin-sitemap: ^5.14.0 => 5.14.0
    gatsby-plugin-styled-components: ^5.4.0 => 5.12.1
    gatsby-source-contentful: ^7.2.0 => 7.10.1
    gatsby-source-filesystem: ^4.4.0 => 4.12.1
    gatsby-source-shopify: ^6.4.0 => 6.10.2
    gatsby-transformer-sharp: ^4.4.0 => 4.12.1
```

**Comment by LekoArts** [comment] 2022-07-19 10:57
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

I tried this on a test site:

```js
    {
      resolve: `gatsby-plugin-sitemap`,
      options: {
        output: `/`,
        serialize: (page) => ({
          url: page.path,
          lastmod: `2020-01-01`,
          changefreq: `daily`,
        })
      }
    }
```

And I get the desired output:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1" xmlns:news="http://www.google.com/schemas/sitemap-news/0.9" xmlns:video="http://www.google.com/schemas/sitemap-video/1.1" xmlns:xhtml="http://www.w3.org/1999/xhtml">
   <url>
      <loc>https://www.yourdomain.tld/</loc>
      <lastmod>2020-01-01T00:00:00.000Z</lastmod>
      <changefreq>daily</changefreq>
   </url>
   <url>
      <loc>https://www.yourdomain.tld/page-2/</loc>
      <lastmod>2020-01-01T00:00:00.000Z</lastmod>
      <changefreq>daily</changefreq>
   </url>
</urlset>
```

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2022-08-03 06:00
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2022-08-03 06:00 UTC
Labels: type: bug, status: needs reproduction, topic: plugins
