### ISSUE TITLE
gatsby-source-wordpress fails to get Yoast data

### ISSUE THREAD

**Issue by garryburch** [gatsbyjs/gatsby#23626] opened 2020-04-30 03:13 UTC
## Description

During gatsby develop for local dev and gatsby build on Netlify for production/live site

Path: /wp-json/yoast/v1/indexation/posts?per_page=100&page=1
The server response was "404 Not Found"
Inner exception message: "No route was found matching the URL and request method"

### Steps to reproduce

Updated Yoast Premium to Version 14.0 above error occurs
Reverted back to Yoast Premium Version 12.1 works

### Expected result

The ability to work with yoast_meta: { ... }

### Actual result

Above error, the build completes yet every page has the same Meta information

### Environment

  System:
    OS: Linux 5.3 Ubuntu 19.10 (Eoan Ermine)
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
    Yarn: 1.22.4 - /usr/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Firefox: 75.0
  npmPackages:
    gatsby: ^2.15.34 => 2.19.5
    gatsby-background-image: ^0.8.15 => 0.8.19
    gatsby-image: ^2.2.25 => 2.2.39
    gatsby-plugin-google-tagmanager: ^2.1.13 => 2.1.24
    gatsby-plugin-layout: ^1.1.11 => 1.1.21
    gatsby-plugin-manifest: ^2.2.21 => 2.2.38
    gatsby-plugin-netlify: ^2.1.19 => 2.1.31
    gatsby-plugin-offline: ^2.2.5 => 2.2.10
    gatsby-plugin-postcss: ^2.1.11 => 2.1.19
    gatsby-plugin-react-helmet: ^3.1.11 => 3.1.21
    gatsby-plugin-react-svg: ^2.1.2 => 2.1.2
    gatsby-plugin-sass: ^2.1.18 => 2.1.27
    gatsby-plugin-sharp: ^2.2.32 => 2.4.0
    gatsby-plugin-sitemap: ^2.2.17 => 2.2.26
    gatsby-source-filesystem: ^2.1.31 => 2.1.46
    gatsby-source-wordpress: ^3.1.41 => 3.1.58
    gatsby-transformer-sharp: ^2.2.21 => 2.3.13
  npmGlobalPackages:
    gatsby-cli: 2.11.7

**Comment by TylerBarnes** [comment] 2020-05-01 21:55
Hi @garryburch !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Additionally, I want to make sure you know we're working on a new major version of `gatsby-source-wordpress` which uses WPGraphQL instead of the REST api. There are too many unavoidable issues with the REST api since it's an untyped source. You can read more about it here https://github.com/gatsbyjs/gatsby/issues/19292.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by danabrit** [comment] 2020-06-02 22:38
Closing this issue due to no reproduction within 7 days. If you would like to re-open it with a minimal reproduction, we'd be happy to take a look. Thank you!

**Closed by danabrit** 2020-06-02 22:38 UTC
Labels: status: needs core review, status: needs reproduction, topic: WordPress, type: bug
