### ISSUE TITLE
Result of StaticQuery could not be fetched

### ISSUE THREAD

**Issue by ChildishhAlbino** [gatsbyjs/gatsby#31817] opened 2021-06-08 05:51 UTC
## Description

After updating to Gatsby V3, my page no longer builds. I get the below error. I believe this is coming from the use of `useStaticQuery` in my SEO component. I cannot confirm however.

### Steps to reproduce

Clear steps describing how to reproduce the issue. **Please** link to a reproduction, this makes your issue _much_ easier to diagnose (seriously).

1. git clone https://github.com/ChildishhAlbino/childishhalbino.com.git
2. git checkout gatsby/cannot-run-static-query
3. npm install
4. npm run start

### Expected result

The page should build.

### Actual result

![image](https://user-images.githubusercontent.com/36402974/121130050-2c98c080-c871-11eb-8836-a4d5e12c8500.png)

### Environment

```
System:
    OS: Windows 10 10.0.19042
    CPU: (24) x64 AMD Ryzen 9 3900X 12-Core Processor     
  Binaries:
    Node: 14.6.0 - C:\Program Files\nodejs\node.EXE       
    npm: 7.16.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.0
  Browsers:
    Chrome: 91.0.4472.77
    Edge: Spartan (44.19041.964.0), Chromium (91.0.864.41)
  npmPackages:
    gatsby: ^2.24.5 => 3.6.2
    gatsby-image: ^2.4.13 => 3.6.0
    gatsby-plugin-buildtime-timezone: ^1.0.3 => 1.0.3     
    gatsby-plugin-canonical-urls: ^2.7.0 => 3.6.0
    gatsby-plugin-dark-mode: ^1.1.2 => 1.1.2
    gatsby-plugin-force-trailing-slashes: ^1.0.4 => 1.0.5 
    gatsby-plugin-manifest: ^2.4.18 => 3.6.0
    gatsby-plugin-mdx: ^2.6.0 => 2.6.0
    gatsby-plugin-react-helmet: ^3.3.10 => 4.6.0
    gatsby-plugin-robots-txt: 1.5.6 => 1.6.2
    gatsby-plugin-sass: ^2.3.12 => 4.6.0
    gatsby-plugin-sharp: ^2.14.4 => 3.6.0
    gatsby-plugin-sitemap: ^2.9.0 => 4.2.0
    gatsby-remark-images: ^5.3.0 => 5.3.0
    gatsby-remark-images-contentful: ^4.3.0 => 4.3.0      
    gatsby-remark-prismjs: ^5.3.0 => 5.3.0
    gatsby-source-contentful: ^4.3.1 => 5.6.1
    gatsby-source-filesystem: ^2.3.20 => 3.6.0
    gatsby-transformer-remark: ^2.8.25 => 4.3.0
    gatsby-transformer-sharp: ^2.5.11 => 3.6.0
  npmGlobalPackages:
    gatsby-cli: 3.6.0
```

**Comment by kashesandr** [comment] 2021-06-09 18:32
getting similar issue

**Comment by Rida-N** [comment] 2021-06-10 12:42
Got same error after `gatsby clean && npm install && gatsby develop`

**Comment by ramojej** [comment] 2021-06-18 01:53
I'm having the same issue after updating my dependencies. Anybody here who solved it already? 

```

  System:
    OS: Windows 10 10.0.19043
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor              
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.48)
  npmPackages:
    gatsby: ^3.7.2 => 3.7.2 
    gatsby-plugin-gatsby-cloud: ^2.7.1 => 2.7.1 
    gatsby-plugin-image: ^1.7.1 => 1.7.1 
    gatsby-plugin-manifest: ^3.7.1 => 3.7.1 
    gatsby-plugin-no-index: ^1.0.2 => 1.0.2 
    gatsby-plugin-offline: ^4.7.1 => 4.7.1 
    gatsby-plugin-postcss: ^4.7.1 => 4.7.1 
    gatsby-plugin-preact: ^5.7.1 => 5.7.1 
    gatsby-plugin-react-helmet: ^4.7.1 => 4.7.1 
    gatsby-plugin-react-svg: ^3.0.1 => 3.0.1 
    gatsby-plugin-sharp: ^3.7.1 => 3.7.1 
    gatsby-source-filesystem: ^3.7.1 => 3.7.1 
    gatsby-source-wordpress: ^5.7.1 => 5.7.1 
    gatsby-transformer-sharp: ^3.7.1 => 3.7.1 
  npmGlobalPackages:
    gatsby-cli: 3.6.0

```

**Comment by LekoArts** [comment] 2021-06-18 06:03
Duplicate of https://github.com/gatsbyjs/gatsby/issues/26563 - please post your full reproduction there. Thanks!

**Closed by LekoArts** 2021-06-18 06:03 UTC
Labels: topic: GraphQL, type: bug, v3migration
