### ISSUE TITLE
gatsby-config/node.js doesn't support ESM import/export

### ISSUE THREAD

**Issue by janosh** [gatsbyjs/gatsby#23705] opened 2020-05-02 15:29 UTC
## Summary

[Node v14 is out](https://medium.com/@nodejs/node-js-version-14-available-now-8170d384567e) and with it the removal of the Experimental Modules warning! 🎉

I installed it, added `"type": "module"` to `package.json`, used `export default` in  `gatsby-config.js` and took the default starter for a spin. This is what I got:

>   Error: [ERR_REQUIRE_ESM]: Must use import to load ES Module: gatsby-config.js
>   require() of ES modules is not supported.
>   require() of gatsby-config.js from node_modules/gatsby/dist/bootstrap/get-config-file.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
>   Instead rename gatsby-config.js to end in .cjs, change the requiring code to   use import(), or remove "type": "module" from package.json.

Sounds like Gatsby, specifically `gatsby/dist/bootstrap/get-config-file.js`, stands in the way of using ESM import/export syntax. I think it's time to make gatsby's config and node APIs ESM-ready. 🚀 

### Basic example

```js
export default {
  siteMetadata: {
    title: `Gatsby Default Starter`,
    author: `@gatsbyjs`,
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    // ...
  ],
}
```

### Motivation

Would be really cool if we could finally use a single import/export system all throughout our Gatsby projects! As the release announcement states:

> It is our belief that the current implementation offers a future proof model to authoring ESM modules that paves the path to Universal JavaScript.

If that doesn't get you excited, you must be in the wrong line of work. 😄

**Comment by herecydev** [comment] 2020-05-02 16:57
It's worth highlighting the following parts of the release docs:
> However, the ESM implementation in Node.js remains experimental
> Users should be cautious when using the feature in production environments

So I expect there's still some time before this will be implemented.

**Comment by janosh** [comment] 2020-05-02 19:35
Fair enough. Although it's probably a good idea to start looking into this now.

> As always, corporate users should wait to upgrade their production deployments until October when Node.js is promoted to LTS. **However, now is the best time to start testing applications with Node.js 14, and try out new features.**

**Comment by LekoArts** [comment] 2020-05-04 07:57
Thank you for opening this!

As they say:

> As per our stability index: “The feature is not subject to Semantic Versioning rules. Non-backward compatible changes or removal may occur in any future release.” Users should be cautious when using the feature in production environments.

So I don't think this is ready yet for prime-time in Gatsby as we can ship more impactful features than trying to keep up with breaking changes from them. We want to support it of course once it reached a stable status.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2020-05-04 07:57 UTC
Labels: impact: high, status: triage needed

**Comment by thecodingwizard** [comment] 2021-04-14 07:50
[Node v15](https://nodejs.org/dist/latest-v15.x/docs/api/esm.html#esm_modules_ecmascript_modules) lists ECMAScript module support as stable. Will Gatsby be supporting this anytime soon? Libraries such as [`xdm`](https://github.com/wooorm/xdm) can't be used with Gatsby without this.

**Comment by tujoworker** [comment] 2021-04-14 17:34
@thecodingaviator did you try it actually? Because I think you should be able to import ESM into CJS. You would require it from gatsby-node.js to run it on a certain Gatsby API.

**Comment by thecodingwizard** [comment] 2021-04-14 18:54
For [xdm specifically](https://github.com/wooorm/xdm/issues/40), I've tried a variety of techniques to import it into Gatsby (including using the `esm` package) and none of them worked. Did anybody have better success importing esm libraries into gatsby-node.js?

**Comment by kimbaudi** [comment] 2021-04-28 13:16
I'm facing a similar issue as @thecodingwizard where I want to use the latest `unist-util-visit` v3.0.0 (which is ESM only) in Gatsby. I've also tried using the `esm` package and also adding `"type": "modules"` into my Gatsby package.json, but it doesn't work.

**Comment by alvinometric** [comment] 2021-04-30 08:29
@LekoArts @KyleAMathews Node 16 is out, this is no longer experimental and should be reopened.

**Comment by wdavidw** [comment] 2021-05-06 07:47
> I'm facing a similar issue as @thecodingwizard where I want to use the latest `unist-util-visit` v3.0.0 (which is ESM only) in Gatsby. I've also tried using the `esm` package and also adding `"type": "modules"` into my Gatsby package.json, but it doesn't work.

Same problem here. Several gatsby-remark plugins are created inside the `./plugins` folder of my project. They fail to require the latest `unist-util-visit`. I tried to convert them to `.mjs` and `.cjs` files without much success. The code work with  `unist-util-visit` version  `^2.0.3` and fail with `^3.0.1`. I believe the problem is in how gatsby load local plugins more than in the `unist-util-visit`. This is an extract of the error:

```

 ERROR #11321  PLUGIN

"gatsby-transformer-remark" threw an error while running the createSchemaCustomization lifecycle:

Must use import to load ES Module: /home/user/website/node_modules/unist-util-visit/index.js
require() of ES modules is not supported.
require() of /home/user/website/node_modules/unist-util-visit/index.js from
/home/user/website/plugins/blog-md-url/index.js is an ES module file as it is a .js file whose nearest parent package.json contains
 "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename /home/user/website/node_modules/unist-util-visit/index.js to end in .cjs, change the requiring code to use import(),
 or remove "type": "module" from /home/user/website/node_modules/unist-util-visit/package.json.




  Error: [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/user/website/node_modules/unist-util-visit/index.js
  require() of ES modules is not supported.
  require() of /home/user/website/node_modules/unist-util-visit/index.js from /home/user/website/plugins/blog-md-
  url/index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in th
  at package scope as ES modules.
  Instead rename /home/user/website/node_modules/unist-util-visit/index.js to end in .cjs, change the requiring code to use import(
  ), or remove "type": "module" from /home/user/website/node_modules/unist-util-visit/package.json.
  
  - errors:363 new NodeError
    node:internal/errors:363:5
  
  - loader:1126 Object.Module._extensions..js
    node:internal/modules/cjs/loader:1126:13
  
  - loader:989 Module.load
    node:internal/modules/cjs/loader:989:32
  
  - loader:829 Function.Module._load
    node:internal/modules/cjs/loader:829:14
  
  - loader:1013 Module.require
    node:internal/modules/cjs/loader:1013:19
  
  - v8-compile-cache.js:159 require
    [gatsby]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - index.js:9 Object.<anonymous>
    /home/user/website/plugins/blog-md-url/index.js:9:15
  
  - v8-compile-cache.js:192 Module._compile
    [gatsby]/[v8-compile-cache]/v8-compile-cache.js:192:30
  
  - loader:1138 Object.Module._extensions..js
    node:internal/modules/cjs/loader:1138:10
  
  - loader:989 Module.load
    node:internal/modules/cjs/loader:989:32
  
  - loader:829 Function.Module._load
    node:internal/modules/cjs/loader:829:14
  
  - loader:1013 Module.require
    node:internal/modules/cjs/loader:1013:19
  
  - v8-compile-cache.js:159 require
    [gatsby]/[v8-compile-cache]/v8-compile-cache.js:159:20
  
  - create-schema-customization.js:45 
    [gatsby]/[gatsby-transformer-remark]/create-schema-customization.js:45:28
  
  - Array.forEach
  
  - create-schema-customization.js:44 Object.module.exports [as createSchemaCustomization]
    [gatsby]/[gatsby-transformer-remark]/create-schema-customization.js:44:11
```

Let us know if we need to open a new issue.

**Comment by LekoArts** [comment] 2021-05-07 07:07
Please open a feature request for ESM support here: https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests

**Comment by paulmelnikow** [comment] 2021-07-09 14:56
I found a couple of related and more specific feature requests (#31026 #31599) though I think it still makes sense to create a new feature request for this feature.

**Comment by Ir1d** [comment] 2021-07-17 09:09
hi @kimbaudi have you found a solution for this? We're facing similar issues

**Comment by kimbaudi** [comment] 2021-07-17 12:31
@Ir1d - I haven't found a solution to using import/export in gatsby-config/node.js. The closest I got to using import/export in gatsby-config/node.js is by using the `esm` npm package to `require` serializable js files and convert to es modules to use in gatsby-config/node.js. For example, I had `config/site.js`, which contained serializable javascript like so:

```js
// site.js
const site = {
  title: `my title`,
  description: `my description`,
  url: `https://example.com`,
};

export default site;
```

and I use `esm` npm package to convert site.js from esm to cjs:

```js
// esm.js

require = require('esm')(module)

const {default: site} = require('./site')

module.exports = {
  site
}
```

this way, I can use `site` (which is esm) in gatsby-config.js:

```js
const {site} = require('./src/config/esm')

module.exports = {
  siteMetadata: site,
  ...
}
```

However, this no longer works if you try to convert .js/jsx to .ts/tsx files. I know you can convert .jsx files to .tsx in Gatsby, but `esm` npm package cannot read .ts files so I am unable to update my Gatsby sites to use TypeScript at the moment. I'm probably better off using Next.js at this point if I want to continue using my config files

**Comment by tujoworker** [comment] 2021-07-17 12:52
@kimbaudi and @Ir1d I haven’t used it by my self, but this plugin looks promising, doesn’t it?

https://www.gatsbyjs.com/plugins/gatsby-plugin-ts-config/

**Comment by Ir1d** [comment] 2021-07-17 13:12
We tried using esm's require, but it isn't of much success

**Comment by kimbaudi** [comment] 2021-07-17 13:24
@tujoworker I'm aware of the plugin, but haven't used it myself. 

@Ir1d esm require only works if the es module you are requiring is serializable. If esm's require doesn't work for you, it probably means you are requiring non-serializable js such as react components or something else I'm unaware of.

**Comment by Ir1d** [comment] 2021-07-17 13:41
Thanks @kimbaudi. I'm trying to load `unist-util-visit` which comes from `unified` and `mdx`, similar to  https://github.com/gatsbyjs/gatsby/discussions/31599

**Comment by kimbaudi** [comment] 2021-07-17 13:50
yeah, that probably won't work since `unist-util-visit` references react components, which isn't serializable

**Comment by karlhorky** [comment] 2021-08-06 07:44
Yeah, Gatsby not supporting ESM will become a big problem in the next weeks as people upgrade to the latest `remark` packages, which are full ESM.

@LekoArts would recommend the team reopening this one - it should be an issue, not a feature request.

cc @wooorm

**Comment by Ir1d** [comment] 2021-08-06 08:47
indeed. afaik, no one has ever been able to make gatsby work with esm module unist-util-visit

**Comment by karlhorky** [comment] 2021-08-06 08:50
One thing that I imagine would work would be to compile the `gatsby-config.js` and `gatsby-node.js` and all dependencies (including `node_modules`) first with webpack / esbuild, and then use that resulting file with Gatsby. 🤯

But setting that up... 😬

**Comment by Ir1d** [comment] 2021-08-06 08:56
It requires complex configuration and I don't think that's what remark wanted when they decided to upgrade to esm..

**Comment by tujoworker** [comment] 2021-08-06 09:01
Not «that» complex, see the this doc: https://support.gatsbyjs.com/hc/en-us/articles/1500000294121-Using-ES6-Module-Syntax-in-Gatsby-API-Files-on-Gatsby-Cloud

Sure, I agree, having that build in, would be very nice!

**Comment by karlhorky** [comment] 2021-08-06 09:03
> Not «that» complex, see the this doc: [support.gatsbyjs.com/hc/en-us/articles/1500000294121-Using-ES6-Module-Syntax-in-Gatsby-API-Files-on-Gatsby-Cloud](https://support.gatsbyjs.com/hc/en-us/articles/1500000294121-Using-ES6-Module-Syntax-in-Gatsby-API-Files-on-Gatsby-Cloud)

This doesn't work - just tried it with the new pure ESM packages.

**Comment by karlhorky** [comment] 2021-08-06 09:07
This isn't a "nice to have" or "has a workaround" - Gatsby just doesn't work with new versions of many packages.

**Comment by Ir1d** [comment] 2021-08-06 09:08
@tujoworker thx, but that method doesnt work with remark ecosystem. i've tried that before.

**Comment by tujoworker** [comment] 2021-08-06 09:41
Okay! There is at least some activity going on: https://twitter.com/wardpeet/status/1422843507283316736?s=21
Also, could this help? `await import(dep)`

**Comment by karlhorky** [comment] 2021-08-06 10:07
Nope, dynamic import using `await import()` doesn't seem to work either. Top-level await in the `gatsby-config.js` file is not supported:

```
module.exports = {
  plugins: [
  ...
    {
      resolve: `gatsby-plugin-mdx`,
      options: {
        rehypePlugins: [
          [await import('rehype-autolink-headings'), { behavior: 'wrap' }],
                 ^^^^^^
  SyntaxError: Unexpected token 'import'
```

Without the top-level await, it would need to have some way of accessing the value in the `.then` callback, which it doesn't appear that Gatsby supports (eg. returning a function as a value from `gatsby-config.js`)

**Comment by tujoworker** [comment] 2021-08-06 10:25
You can return an async function as the configuration, inside `gatsby-config` 👍 I have done this at least.

**Comment by karlhorky** [comment] 2021-08-06 12:00
Yeah probably doesn't work with promises. I don't even see anything in the docs about the option to return a function.

**Comment by karlhorky** [comment] 2021-08-06 12:09
Ah, the reason I can't find it in the docs is because returning a function in `gatsby-config.js` is only for themes:

> @DSchau: Exporting a function from `gatsby-config.js` is reserved for themes. Are you trying to create a theme?

https://github.com/gatsbyjs/gatsby/issues/16013#issuecomment-514235110

And yeah, that doesn't support promises / async functions:

> @sidharthachatterjee: Themes _do_ currently accept a function (as you've mentioned) but we expect it to the sync.

https://github.com/gatsbyjs/gatsby/issues/19644#issuecomment-558073951

**Comment by frattaro** [comment] 2021-08-14 00:58
With the entire `unified` stack going to ESM, this has a significant impact on gatsby.

**Comment by bytrangle** [comment] 2021-08-15 10:18
Has anyone found a way to make Gatsby work with `unist-util-visit` v3?

**Comment by karlhorky** [comment] 2021-08-15 10:45
@bytrangle No known way currently. Gatsby is only compatible with packages that are not pure ESM. Downgrade to older versions for use with Gatsby.

The Gatsby team is apparently ["not against" moving to ESM](https://twitter.com/wardpeet/status/1425166009594490886) (tweet from @wardpeet), but I'm guessing it will still be some time before you can use this in your projects.

If you absolutely need to use the new versions, you may want to try experimenting with [bundling / precompiling the dependency to CommonJS](https://github.com/gatsbyjs/gatsby/issues/23705#issuecomment-894109513), although this may be complex.

**Comment by karlhorky** [comment] 2021-08-15 10:47
@wardpeet @LekoArts maybe this can be reopened - this will be a growing issue for Gatsby users as time goes on.

**Comment by LekoArts** [comment] 2021-08-16 13:41
Please follow & comment on https://github.com/gatsbyjs/gatsby/discussions/31599 - it's on our radar but for now we have other things that are higher priority for us + we can't directly act on it without prior planning.

**Comment by karlhorky** [comment] 2021-08-16 14:08
Ok, will do, maybe can you lock this thread then?

**Comment by LekoArts** [comment] 2022-02-07 12:25
Please go to https://github.com/gatsbyjs/gatsby/discussions/34613 and you can use TypeScript with Gatsby. By the time you're reading this it's also possible that the feature already was shipped in Gatsby 4. If that is the case the RFC will be marked as done.

You can also expect ESM support (through this) very soon, please follow https://github.com/gatsbyjs/gatsby/discussions/31599 for progress. Again, if the feature is shipped it'll be noted in the discussion.
