### ISSUE TITLE
Prefix Path in Development Mode

### ISSUE THREAD

**Issue by riyadshauk** [gatsbyjs/gatsby#25215] opened 2020-06-23 00:32 UTC
## Summary

I would like to be able to run `gatsby develop --prefix-paths` (eg, with the `pathPrefix` property set in `gatsby-config.js`), and it should work.

### Motivation

I'm trying to run a production build at the root page (`/`), and a development/staging server (at a prefixed path, such as `/editor/`) for admin controls (like live page editing, which would programmatically get 'published'/built on the production page at `/`). All this while using TinaCMS with Gatsby. Also, if it's weird behavior to have two different path prefixes, I'm fine with having slightly different `gatsby-config.js` files between the production and development/staging websites.

As a side note, perhaps this feature may even be better run as `gatsby staging --prefix-paths` since it's for a staging environment?

I noticed that [people have wanted prefix paths in development for a while](https://github.com/gatsbyjs/gatsby/issues/16040), but I'm not sure what the status is on this... If you guys are willing to give some direction, I'd be willing to implement this feature, either for development or for a new 'staging' command.

**Comment by LekoArts** [comment] 2020-06-23 06:40
Thanks for the issue! I'll close this as a duplicate of https://github.com/gatsbyjs/gatsby/issues/16040

**Closed by LekoArts** 2020-06-23 06:40 UTC
Labels: status: triage needed, type: feature or enhancement
