### ISSUE TITLE
ThumbNails making gatsby develop excruciatingly slow not blazingly fast

### ISSUE THREAD

**Issue by arhoy** [gatsbyjs/gatsby#22842] opened 2020-04-06 01:26 UTC
Hello Gatsby Gurus
I have a eCommerce site with just over 1000 product images. It is making the build process of Gatsby excruciatingly slow :(

For some reason I notice that I have almost 8000 (8x) the amount of 'image thumbals' which is taking very long > 500 seconds to load up.

Why I am getting so many image thumbnails and what can I do to make build faster?

FYI. I am getting the product images via Shopify, as I am using SHopify CMS.

Thank you for your help

**Comment by herecydev** [comment] 2020-04-06 11:21
Are you able to create a reproduction?

I don't the amount if images is excessive but it's a non-trivial addition which will impact speed. How many queries/s is Gatsby reporting?

**Comment by arhoy** [comment] 2020-04-06 19:56
@herecydev thanks for your reply. Not a whole lot. I cannot remember the run time on the query, I don't have a lot of queries/hook and the run time is a small fraction of the total run time.
Here is the last uploaded repo link, I will try and upload a new one later today, I am just trying to fix some errors first
https://github.com/arhoy/dresscodeafrica

**Comment by LekoArts** [comment] 2020-04-14 08:43
Thank you for opening this!

> I have a eCommerce site with just over 1000 product images
> For some reason I notice that I have almost 8000 (8x) the amount of 'image thumbals'
> Why I am getting so many image thumbnails

Since you're using `gatsby-image` multiple images out of your source images are created, as explained here: https://www.gatsbyjs.org/docs/gatsby-image/#images-that-stretch-across-a-fluid-container

> Create flexible sizes for an image that stretches to fill its container. E.g. for a container whose max width is 800px, the automatic sizes would be: 200px, 400px, 800px, 1200px and 1600px – enough to provide close to the optimal image size for every device size / screen resolution. If you want more control over which sizes are output you can use the srcSetBreakpoints parameter.

So you could e.g. change the `maxWidth` parameter or change the `srcSetBreakpoints` if you want less images. Otherwise this is expected behavior.

> what can I do to make build faster?

As laid out above you could change your queries to create less images, you could try using [Cloudinary](https://www.gatsbyjs.org/docs/using-cloudinary-image-service/), [Gatsby Cloud](https://www.gatsbyjs.com/) which handles both caching and image processing really quick or you use things like https://github.com/jlengstorf/netlify-plugin-gatsby-cache or https://www.netlify.com/blog/2020/02/25/gatsby-build-speed-improvements-with-parallel-image-processing/ on Netlify.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2020-04-14 08:43 UTC
Labels: type: question or discussion

**Comment by arhoy** [comment] 2020-04-14 10:51
Thanks @LekoArts for this detailed answer. 
I like your idea of playing around with the image source set.
One issue, is I am using Shopify as the CMS and building the front end in Gatsby using those images. As a result, using something like Cloudinary would not be relevant in this case.
What is the difference between Netlify and Gatsby Cloud ?

Not sure if this is a Gatsby related question, but using the Shopify Plugin, I am only able to get some of my products rendered from Shopify, not all 1200 or so. 

As I plan to continue to add more and more products to the store, is Gatsby the right tool for this or should I look at something like Next in order to get the job done?

I was thinking perhaps incremental builds might solve this problem, but right now since I have not been doing incremental builds I feel like a bit stuck.

Thank you
