### ISSUE TITLE
wrapPageElement receives path: /* during build

### ISSUE THREAD

**Issue by lorensr** [gatsbyjs/gatsby#30726] opened 2021-04-06 20:40 UTC
## Description

My `wrapPageElement` function receives the correct `props.path` in development, but during build, all pages receive `/*` as the path, which breaks my app, since different pages are supposed to get different layouts.

### Steps to reproduce

https://github.com/GraphQLGuide/book/tree/repro-gatsby-path-star

`gatsby build` logs many lines of this:

```
PATH /* 
PATH /* 
PATH /* 
PATH /* 
```

From this line:
https://github.com/GraphQLGuide/gatsby-theme-apollo/blob/b2d3443f378df3dd54de22412bf5ce220ced4a2f/packages/gatsby-theme-apollo-docs/gatsby-ssr.js

### Expected result

```
PATH /
PATH /welcome 
PATH /preface
etc
```

### Environment

  System:
    OS: macOS 11.2.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.21.0 - ~/.nvm/versions/node/v12.21.0/bin/node
    Yarn: 1.22.10 - ~/Dropbox/Documents/guide/book/node_modules/.bin/yarn
    npm: 7.6.0 - ~/.nvm/versions/node/v12.21.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.114
    Safari: 14.0.3
  npmPackages:
    gatsby: ^2.32.11 => 2.32.11 
    gatsby-plugin-heap: ^1.1.0 => 1.1.0 
    gatsby-plugin-use-query-params: ^1.0.1 => 1.0.1 
    gatsby-theme-apollo: ^3.0.3 => 3.0.3 
    gatsby-theme-guide: ^4.7.3 => 4.7.3 
    gatsby-theme-guide-core: ^3.0.26 => 3.0.26

**Comment by ascorbic** [comment] 2021-04-08 09:14
Hi @lorensr 
Thanks for the report. Is there any way you can get me a more minimal reproduction? Ideally one where the problem API isn't inside a theme. As it stands it's hard for me to dig into the issue.

Thanks

**Comment by LekoArts** [comment] 2021-04-15 12:04
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-04-15 12:04 UTC
Labels: status: needs reproduction, type: bug

**Comment by guillaumebriday** [comment] 2021-08-16 20:45
@lorensr Did you find a solution? I have the same issue :/

**Comment by lorensr** [comment] 2021-08-16 21:09
`props.location.pathname` might've had the correct path?

**Comment by guillaumebriday** [comment] 2021-08-16 22:28
It works! Thanks @lorensr 🙏 It was Ss hard to debug this

**Comment by guillaumebriday** [comment] 2021-08-16 22:52
Oups it does not work in SSR. 

```
WebpackError: TypeError: Cannot read property 'pathname' of undefined
```
