### ISSUE TITLE
gatsby-plugin-mdx - utils/mdx.js broken

### ISSUE THREAD

**Issue by caffed** [gatsbyjs/gatsby#34707] opened 2022-02-03 17:31 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I just created a new project with the Quick Start instructions:  https://www.gatsbyjs.com/docs/quick-start/

From the `npm init gatsby` prompt, I enabled Markdown support with MDX. 

It is broken.
 
`@mdx-js/mdx` has been rewritten but Gatsby's gatsby-plugin-mdx package has not:
- `@mdx-js/mdx` https://github.com/mdx-js/mdx/commit/57e637cf55c2036966cc66ddb670114cde3a0082#diff-73fa9cd589cfa1932eeaaeff4ab7ae1142043343fedced20b17b09fce0d1fae7
- Gatsby gatsby-plugin-mdx : https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-mdx/utils/mdx.js

### Reproduction Link

NONE

### Steps to Reproduce

- Follow Quick Start guide and enable Markdown with MDX

### Expected Result

- No errors
- `npm start` works from a fresh install with MDX

### Actual Result

Running `npm start` returns this error:
```
  Error: [ERR_REQUIRE_ESM]: Must use import to load ES Module: /.../node_modules/@mdx-js/mdx/index.js
  require() of ES modules is not supported.
  require() of /.../node_modules/@mdx-js/mdx/index.js from /.../node_modules/gatsby-plugin-mdx/utils/mdx.js is an ES module file as
   it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
  Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /.../node_modules/@mdx-js/mdx/package.json.
```

### Environment

```shell
System:
    OS: macOS 12.2
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.2 - ~/n/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 8.1.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.17 - /usr/local/bin/python
  npmPackages:
    gatsby: ^4.6.1 => 4.6.1
    gatsby-plugin-google-analytics: ^4.6.0 => 4.6.0
    gatsby-plugin-image: ^2.6.0 => 2.6.0
    gatsby-plugin-manifest: ^4.6.0 => 4.6.0
    gatsby-plugin-mdx: ^3.6.0 => 3.6.0
    gatsby-plugin-netlify-cms: ^6.6.0 => 6.6.0
    gatsby-plugin-react-helmet: ^5.6.0 => 5.6.0
    gatsby-plugin-sharp: ^4.6.0 => 4.6.0
    gatsby-plugin-sitemap: ^5.6.0 => 5.6.0
    gatsby-plugin-theme-ui: ^0.13.1 => 0.13.1
    gatsby-source-filesystem: ^4.6.0 => 4.6.0
    gatsby-transformer-sharp: ^4.6.0 => 4.6.0
```

**Comment by jdeola** [comment] 2022-02-03 18:19
Yes, same issue here.

**Comment by LekoArts** [comment] 2022-02-03 19:52
Duplicate of https://github.com/gatsbyjs/gatsby/issues/34706

**Closed by LekoArts** 2022-02-03 19:52 UTC
Labels: type: bug
