### ISSUE TITLE
 The gatsby-source-cloudinary plugin has generated no Gatsby nodes. Do you need it?

### ISSUE THREAD

**Issue by Wookie93** [gatsbyjs/gatsby#25260] opened 2020-06-24 15:50 UTC
## Description

Hello, 
I try to create images gallery in my gatsby project. I decided to use cloudinary, however it do not want to work. I used Static Query the component. 
How can I fix it? 

### Steps to reproduce

Follow instructions from https://scotch.io/tutorials/handling-images-in-gatsby-with-high-performance
1. Install gatsby-source-cloudinary
2. Setup your environments
3. Run local server 

### Expected result

My local server will run and I will see images from cloudinary on my page.

### Actual result

I get errors: 

-  The gatsby-source-cloudinary plugin has generated no Gatsby nodes. Do you need it?
- Cannot query field "allCloudinaryMedia" on type "Query".

### Environment

  System:
    OS: Windows 10 10.0.18363
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
  Binaries:
    Node: 12.17.0 - D:\node.js\node.EXE
    Yarn: 1.22.4 - ~\AppData\Roaming\npm\yarn.CMD  
    npm: 6.14.4 - D:\node.js\npm.CMD
  Languages:
    Python: 3.8.3
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.22.15 => 2.22.15
    gatsby-background-image: ^1.1.1 => 1.1.1
    gatsby-cli: ^2.12.43 => 2.12.43
    gatsby-image: ^2.4.5 => 2.4.5
    gatsby-plugin-layout: ^1.3.3 => 1.3.3
    gatsby-plugin-manifest: ^2.4.9 => 2.4.9
    gatsby-plugin-offline: ^3.2.7 => 3.2.7
    gatsby-plugin-prefetch-google-fonts: ^1.4.3 => 1.4.3
    gatsby-plugin-react-helmet: ^3.3.2 => 3.3.2
    gatsby-plugin-sharp: ^2.6.9 => 2.6.9
    gatsby-plugin-styled-components: ^3.3.3 => 3.3.3
    gatsby-source-cloudinary: ^0.1.14 => 0.1.14
    gatsby-source-filesystem: ^2.3.8 => 2.3.8
    gatsby-source-googlemaps-static: ^1.1.10 => 1.1.10
    gatsby-transformer-sharp: ^2.5.3 => 2.5.3
  npmGlobalPackages:
    gatsby-cli: 2.12.48

**Comment by jzabala** [comment] 2020-06-24 16:05
The plugin [gatsby-source-cloudinary](https://github.com/Chuloo/gatsby-source-cloudinary) is not part of Gatsby core so, you might need to open the issue in that project.

From what I see the problem is that you don't have data in Cloudinary and the plugin is inferring the GraphQL Schema. To fix this the author of the plugin should add the Schema using [createSchemaCustomization](https://www.gatsbyjs.org/docs/node-apis/#createSchemaCustomization) so that you can get an empty array when you don't have data in Cloudinary.

For more information about Schema customization in Gatsby you can check this doc: https://www.gatsbyjs.org/docs/schema-customization/

**Comment by wardpeet** [comment] 2020-06-24 16:46
Like @jzabala mentioned, there is nothing we can do from our end. Api's are working corectly. Please open a ticket in the plugin itself.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby! 💜

**Closed by wardpeet** 2020-06-24 16:46 UTC
Labels: status: triage needed, type: bug, type: question or discussion
