### ISSUE TITLE
Warning The GraphQL query in the non-page component - Then DELETED Static Pages on Production Build!

### ISSUE THREAD

**Issue by shawngrona** [gatsbyjs/gatsby#31872] opened 2021-06-11 04:16 UTC
## Description

I've never seen this one before but today I ran my automated build in production env (ie with production flag set) and I saw the following warning, the build completed with success but deleted all of the associated pages!  This is obviously not acceptable on a production build, any issues running a graphql should fail the build entirely right?

This was a gatsby-source-wordpress page query which failed

```

Warning The GraphQL query in the non-page component "/tmp/site/src/components/WP/single.js" will not be run.
--
740 | Exported queries are only executed for Page components. It's possible you're
741 | trying to create pages in your gatsby-node.js and that's failing for some
742 | reason.
743 | &nbsp;
744 | If the failing component(s) is a regular component and not intended to be a page
745 | component, you generally want to use a &lt;StaticQuery&gt; (https://gatsbyjs.org/docs/static-query)
746 | instead of exporting a page query.
747 | &nbsp;
748 | If you're more experienced with GraphQL, you can also export GraphQL
749 | fragments from components and compose the fragments in the Page component
750 | query and pass data down into the child component — https://graphql.org/learn/queries/#fragments
```

### Steps to reproduce

I don't have steps to repro, as mentioned above this has not happened before nor since. I deleted the cache, ran the build again and it righted itself.  

### Expected result

Never successfully complete a build if a graphql build fails in production build.

### Actual result

Build ran successfully

### Environment

```
 System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.16.0 - ~/.nvm/versions/node/v12.16.0/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 91.0.4472.77
    Firefox: 88.0
    Safari: 14.0.3
  npmPackages:
    gatsby: ^2.24.78 => 2.24.78
    gatsby-image: ^2.4.0 => 2.4.0
    gatsby-plugin-bundle-stats: ^2.5.0 => 2.5.0
    gatsby-plugin-gatsby-cloud: ^2.6.0 => 2.6.0
    gatsby-plugin-layout: ^1.2.1 => 1.2.1
    gatsby-plugin-nprogress: ^2.3.2 => 2.3.2
    gatsby-plugin-postcss: ^2.1.20 => 2.1.20
    gatsby-plugin-react-helmet: ^3.1.22 => 3.1.22
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5
    gatsby-plugin-s3: ^0.3.8 => 0.3.8
    gatsby-plugin-sass: 2.1.28 => 2.1.28
    gatsby-plugin-sharp: ^2.6.3 => 2.6.3
    gatsby-plugin-sitemap: ^2.4.3 => 2.4.3
    gatsby-plugin-tslint: ^0.0.2 => 0.0.2
    gatsby-plugin-typescript: ^2.1.2 => 2.1.27
    gatsby-plugin-webfonts: ^1.1.3 => 1.1.3
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.20 => 1.1.20
    gatsby-source-filesystem: ^2.7.0 => 2.7.0
    gatsby-source-shopify: ^3.2.36 => 3.2.36
    gatsby-source-wordpress: ^5.6.0 => 5.6.0
    gatsby-transformer-sharp: ^2.5.0 => 2.5.0
```

**Comment by TylerBarnes** [comment] 2021-06-11 18:05
Hi @shawngrona, the warning you mention wont be the cause of the issue you're seeing. That warning is printed out when there's a component with a GraphQL query in it which isn't being used for a page. What this means is there were no pages created using that template. Most likely this is due to some logic in gatsby-node.js but could also be a bug in gatsby-source-wordpress. Even though you can't reproduce the problem, we'll need to be able to see the repo to try to understand what's going on.

**Comment by LekoArts** [comment] 2021-06-21 05:30
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-06-21 05:30 UTC
Labels: status: needs reproduction, topic: source-wordpress
