### ISSUE TITLE
Error: The result of this StaticQuery could not be fetched

### ISSUE THREAD

**Issue by catalina-cimpanu** [gatsbyjs/gatsby#27681] opened 2020-10-27 09:33 UTC
## Description

Hi!

I keep on getting the following message:

![error-static-query](https://user-images.githubusercontent.com/67892765/97280347-741b9080-183c-11eb-951e-b0c68ee5190f.png)

### Steps to reproduce

I created a blog with gatsby (strapi as cms), I sometimes get this error, but not all the time, sometimes it does work, and it seems quite random when that happens. 
It's written static query error, but I sometimes get it on a page (on the index page and on the blog page so far, where I query for articles data). When it is on a page, I noticed it helps if I just move the query outside of the component, like so:

```
import React from "react"
import { graphql } from "gatsby"

const ComponentName = ({ data }) => <pre>{JSON.stringify(data, null, 4)}</pre>

export default ComponentName

export const query = graphql`
  {
    allStrapiArticles {
      nodes {
        article_slug
        article_title
        article_summary
      }
    }
  }
`
```

instead of 
```
import React from "react"
import { graphql } from "gatsby"

const ComponentName = ({ data }) => <pre>{JSON.stringify(data, null, 4)}</pre>

export const query = graphql`
  {
    allStrapiArticles {
      nodes {
        article_slug
        article_title
        article_summary
      }
    }
  }
`

export default ComponentName
```

It doesn't always help to move the page query around, so when it doesn't solve it, then I just restart the development after cleaning the cache `gatsby clean && gatsby develop` - and that usually works.
Refreshing the page never worked.

I mention that I do import a component on the blog page (the sidebar for the blog, which shows the categories), in which I do have a static query (for the blog categories). When I got this error message in this component, I think it was because I was mapping through the categories without a key and the error disappeared after adding the `key={category.id}`.

I don't understand though why sometimes it works and sometimes it doesn't though... 

I can't really reproduce it, as you can see. I hope it's no big deal. I am mostly submitting this issue because of the message and because it seems to be quite random and I can't grasp what's happening.

### Expected result

fetch queries correctly

### Actual result

got the above-mentioned error

### Environment

```
  System:
    OS: Windows 10 10.0.19041
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.19.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.9.0 - /c/Python39/python
  Browsers:
    Chrome: 86.0.4240.111
    Edge: Spartan (44.19041.1.0), Chromium (86.0.622.51)
  npmPackages:
    gatsby: ^2.24.86 => 2.24.86 
    gatsby-image: ^2.4.21 => 2.4.21 
    gatsby-plugin-manifest: ^2.4.35 => 2.4.35 
    gatsby-plugin-offline: ^3.2.37 => 3.2.37 
    gatsby-plugin-react-helmet: ^3.3.14 => 3.3.14 
    gatsby-plugin-react-svg: ^3.0.0 => 3.0.0 
    gatsby-plugin-sharp: ^2.6.43 => 2.6.43 
    gatsby-plugin-sitemap: ^2.4.17 => 2.4.17 
    gatsby-plugin-styled-components: ^3.3.14 => 3.3.14 
    gatsby-source-filesystem: ^2.3.36 => 2.3.36 
    gatsby-source-strapi: 0.0.12 => 0.0.12 
    gatsby-transformer-sharp: ^2.5.20 => 2.5.20 
  npmGlobalPackages:
    gatsby-cli: 2.12.113
```

**Comment by vladar** [comment] 2020-10-27 10:21
This sounds like a duplicate of #26563. Let's track it there.

Thanks for reporting this, @catalina-cimpanu !

**Closed by vladar** 2020-10-27 10:21 UTC
Labels: status: triage needed, type: bug

**Comment by catalina-cimpanu** [comment] 2020-10-28 13:16
Thank you! Actually, by reading the [https://github.com/gatsbyjs/gatsby/issues/26563](https://github.com/gatsbyjs/gatsby/issues/26563) thread, I saw that renaming the file might cause this kind of problem. So, I created a new file with a new name for the component that wasn't fetching the data correctly and I simply copied the code from the old file. And now it works!
