### ISSUE TITLE
Large WordPress site with gatsby

### ISSUE THREAD

**Issue by zcuric** [gatsbyjs/gatsby#7271] opened 2018-08-13 08:29 UTC
### Summary 
Hi,

When I run `gatsby develop` with WordPress with over 17k posts, It never finishes. It's usually stuck here
```
⠠ source and transform nodes -> wordpress__POST fetched : 17117
⠠ source and transform nodes -> wordpress__PAGE fetched : 18
⠠ source and transform nodes -> wordpress__wp_media fetched : 25678
⠄ source and transform nodes -> wordpress__wp_types fetched : 1
⠐ source and transform nodes -> wordpress__wp_statuses fetched : 1
⠂ source and transform nodes -> wordpress__wp_taxonomies fetched : 1
⡀ source and transform nodes -> wordpress__CATEGORY fetched : 42
⠠ source and transform nodes -> wordpress__TAG fetched : 6294
⠠ source and transform nodes -> wordpress__wp_users fetched : 10
```

And it doesn't go futher. 

Am I doing something wrong or gatsby cannot handle that amount of data?

Is there a way to cache `source and transform nodes` actions in case WordPress site large amount of data for the next time you run `gatsby develop` cause start up time takes a loot of time in these cases? 

Thanks

### Environment

```
  System:
    OS: macOS High Sierra 10.13.6
    CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.7.0 - ~/.nvm/versions/node/v10.7.0/bin/node
    npm: 6.2.0 - ~/.nvm/versions/node/v10.7.0/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Safari: 11.1.2
  npmPackages:
    gatsby: next => 2.0.0-beta.98 
    gatsby-image: next => 2.0.0-beta.7 
    gatsby-link: next => 2.0.0-beta.20 
    gatsby-plugin-react-helmet: next => 3.0.0-beta.4 
    gatsby-source-wordpress: next => 3.0.0-beta.18 
  npmGlobalPackages:
    gatsby-cli: 1.1.58
```

### File contents

`gatsby-config.js`: 
```
{
      resolve: 'gatsby-source-wordpress',
      options: {
        baseUrl: 'www.mysite.net',
        protocol: 'https',
        hostingWPCOM: false,
        useACF: false,
        verboseOutput: false,
        excludedRoutes: [
          '/*/*/comments',
          '/*/*/feedback',
          '/*/*/jp_pay_order',
          '/*/*/jp_pay_order/**',
          '/yoast/**',
          '/jetpack/**',
          '/instant-images',
          '/instant-images/**',
          '/*/*/users/**',
          '/*/*/settings',
        ],
      },
    },
```

Other files are the same as in `using-wordpress` example.

**Comment by btk** [comment] 2018-08-13 18:35
Oh hey, I just started having this same issue today with a website with just 350 posts. The thing is; netlify has no problem building, but my local machine gets stuck just like yours.

Might this be a new bug? Have you ever taken a build from your WP website before? @zcuric

**Comment by btk** [comment] 2018-08-13 20:55
@Chuloo I don't think it will be helpful, my continuous integration / netlify is able to take a build without problem. So the problem is local, I will try to pull the repository fresh and try again. Just wanted to see if it was a common problem.

**Comment by zcuric** [comment] 2018-08-13 21:34
@btk This is a first time that i did this.

**Comment by LekoArts** [comment] 2018-12-11 11:08
Please comment on this issue: https://github.com/gatsbyjs/gatsby/issues/6654

Closing as duplicate

**Closed by LekoArts** 2018-12-11 11:08 UTC
Labels: status: help wanted, type: duplicate, type: question or discussion

**Comment by MWalid** [comment] 2019-07-23 08:12
@btk I had similar issue, and was caused by some rate limiting from cloud flare. Was very hard to discover.
