### ISSUE TITLE
Add a “CONTRIBUTING.md” file to the default starter

### ISSUE THREAD

**Issue by kripod** [gatsbyjs/gatsby#3750] opened 2018-01-28 08:36 UTC
I think there should be a default guide for contribution towards Gatsby-based projects in general, outlining the most important concepts of the framework (pages, templates and layout). It should give a quick introduction about the directory structure (and other conventions) of a typical Gatsby project, even for developers who have not been working with Gatsby before.

I think that advanced concepts should not be described in this document, but a teaser paragraph along with a link to the official documentation would be reasonable.

**Comment by calcsam** [comment] 2018-01-28 16:55
This definitely seems like something we'd want to add. Would you like to submit a PR for this?

**Comment by kripod** [comment] 2018-01-28 16:58
@calcsam Sorry, but I'm pretty busy nowadays, so I don't think I would be able to submit a PR...

**Comment by calcsam** [comment] 2018-02-04 17:08
You do seem free enough to contribute lots of comments about other stuff we should add :)

**Comment by calcsam** [comment] 2018-02-04 17:21
In any case, this would be really helpful and contributions on this are welcome!

**Comment by fk** [comment] 2018-02-04 18:30
Just stumbled upon this and my first thought was "Let me give this a shot next week, at worst it's a foundation to continue the discussion on what exactly this should contain" … but why go all the way if we can discuss this upfront right here? ;-P

One thing I wonder about is why you only refer to the default starter in the issue title @kripod? I get that this starter _could_ be the one that most of the people new to Gatsby would give a look. _However_ if they're coming from the Gatsby Tutorial, they'd work with `gatsby-starter-hello-world` initially. Long story short—should we think about a generic `CONTRIBUTING.md` for all starters?

Based on @kripod's input and other projects I took a quick look at, here's a start of a TOC outline:

* Preface/simple introduction, s/th like "Thank you for your interest in contributing to […]"
* Code of Conduct (could take the preface from https://www.gatsbyjs.org/community/ and just link to https://www.gatsbyjs.org/code-of-conduct/)
* [Where to get support](https://www.gatsbyjs.org/community/#where-to-get-support) and [How to file an issue](https://www.gatsbyjs.org/docs/how-to-contribute/#filing-an-issue), also https://www.gatsbyjs.org/docs/how-to-contribute/#special-note-on-issues—not sure if this should be so far up though
* > Outline the most important concepts of the framework (pages, templates and layout)
  * If we go for a CONTRIBUTING.md for all starters, we probably should pay attention to not confuse people—e.g. the `hello-world` starter doesn't contain templates or a layout—so we should make clear what is required and what is optional.
   * Maybe we can link to https://www.gatsbyjs.org/docs/building-with-components/ here; it has React, `pages`, `templates` and `layouts` and references the React as well as the Gatsby tutorial?
   * https://www.gatsbyjs.org/docs/querying-with-graphql/
   * Webpack
   * Plugins, transformers
   * APIs
* > Directory structure
  * location of [`gatsby-config.js`](https://www.gatsbyjs.org/docs/gatsby-config/), `gatsby-browser.js`, …
* > Other conventions
  * Requirements Node.js version, NPM vs. Yarn
  * Code guidelines, Prettier (`yarn format`), linting
* How to fork, branch, issue a PR?
* We probably should mention the license like e.g. https://github.com/twbs/bootstrap/blob/master/CONTRIBUTING.md#license

> I think that advanced concepts should not be described in this document, but a teaser paragraph along with a link to the official documentation would be reasonable.

👍

**Comment by KyleAMathews** [comment] 2018-03-14 16:14
I'm not entirely sure this makes sense — people install starters to start using them — not to contribute to them. Any file we add to a starter is another file they'll have to delete. Perhaps just add a small section to the README.md pointing people to the contributions guideline and other helpful info?

Also, the default starter is intended to be small and stable — it rarely (as designed) gets changes.

**Comment by shannonbux** [comment] 2018-08-31 22:40
@fk and @amberleyromo do you think we close this since the default starter READme file is updated? https://github.com/gatsbyjs/gatsby-starter-default

I remember you were working on a contributing.md file, Flo, so we could revisit by re-opening that PR if you want!

**Comment by calcsam** [comment] 2018-09-03 03:50
I'm going to close this, given @KyleAMathews' comment and the README.

**Closed by calcsam** 2018-09-03 03:50 UTC
Labels: type: documentation

**Comment by fk** [comment] 2018-09-03 11:52
👍 🙏
