### ISSUE TITLE
How to find source of a module in the production bundle?

### ISSUE THREAD

**Issue by rohit-gohri** [gatsbyjs/gatsby#22838] opened 2020-04-05 19:58 UTC
## Summary

I am setting up a small [GatsbyJS blog/personal-site](https://github.com/rohit-gohri/blog) with `gatsby-transformer-remark` for markdown posts and `gatsby-theme-mdx-deck` for slides. I have been trying to reduce my total bundle size. It was 2MB+ at the start, it's now less than 900kb. Updating Gatsby (as suggested in #19957) finally reduced my initial js size to ~400kb. 

I am now trying to get rid of large modules, and lodash stands out right now and  I can't figure out where it is coming from:

![image](https://user-images.githubusercontent.com/31949290/78508291-3c1b0600-77a3-11ea-8ca2-89bd1af58add.png)

I also am not sure if `gatsby-theme-mdx-blog` should be in the main app bundle as it's used only under the `/slides` subpath.

## Relevant information

I added `babel-plugin-transform-imports` to my babelrc but the full lodash module still remains in the bundle. I tried the `gatsby-plugin-lodash` with the same results.

```js
// .babelrc.js
module.exports = {
  plugins: [
    [
      "babel-plugin-transform-imports",
      {
        lodash: {
          transform: "lodash/${member}",
          preventFullImport: true,
        },
      },
    ],
  ],
};
```

What I am trying to figure out is where it is coming from? I tried webpack visualizer and various tools but the way gatsby generates the js they weren't of much help.

You can see the current state of the project at https://github.com/rohit-gohri/blog/tree/685a9cbf9c5b783c49dd588418458bd6b71dd80f

### Environment (if relevant)

```
System:
    OS: Linux 4.15 elementary OS 5.1 Hera
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 12.2.0 - ~/.nvm/versions/node/v12.2.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.2.0/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 72.0.2
  npmPackages:
    gatsby: ^2.20.12 => 2.20.12
    gatsby-image: ^2.3.1 => 2.3.1
    gatsby-plugin-draft: 0.0.5 => 0.0.5
    gatsby-plugin-eslint: ^2.0.8 => 2.0.8
    gatsby-plugin-feed: ^2.4.0 => 2.4.0
    gatsby-plugin-manifest: ^2.3.2 => 2.3.2
    gatsby-plugin-netlify: ^2.2.0 => 2.2.0
    gatsby-plugin-offline: ^3.1.2 => 3.1.2
    gatsby-plugin-react-helmet: ^3.2.0 => 3.2.0
    gatsby-plugin-sass: ^2.2.0 => 2.2.0
    gatsby-plugin-sharp: ^2.5.3 => 2.5.3
    gatsby-plugin-transition-link: ^1.18.0 => 1.18.0
    gatsby-plugin-webfonts: ^1.1.2 => 1.1.2
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.8 => 1.1.8
    gatsby-remark-embedder: ^1.16.0 => 1.16.0
    gatsby-remark-external-links: ^0.0.4 => 0.0.4
    gatsby-remark-github: ^2.0.0 => 2.0.0
    gatsby-remark-images: ^3.2.1 => 3.2.1
    gatsby-remark-relative-images: ^0.3.0 => 0.3.0
    gatsby-remark-social-cards: ^0.4.1 => 0.4.1
    gatsby-source-filesystem: ^2.2.1 => 2.2.1
    gatsby-theme-mdx-deck: 3.0.13 => 3.0.13
    gatsby-transformer-remark: ^2.7.0 => 2.7.0
    gatsby-transformer-sharp: ^2.4.2 => 2.4.2
  npmGlobalPackages:
    gatsby-cli: 2.10.0

```
### File contents (if changed)

`gatsby-config.js`: https://github.com/rohit-gohri/blog/blob/685a9cbf9c5b783c49dd588418458bd6b71dd80f/gatsby-config.js
`package.json`: https://github.com/rohit-gohri/blog/blob/685a9cbf9c5b783c49dd588418458bd6b71dd80f/package.json
`gatsby-node.js`: https://github.com/rohit-gohri/blog/blob/685a9cbf9c5b783c49dd588418458bd6b71dd80f/gatsby-node.js
`gatsby-browser.js`: https://github.com/rohit-gohri/blog/blob/685a9cbf9c5b783c49dd588418458bd6b71dd80f/gatsby-browser.js
`gatsby-ssr.js`: https://github.com/rohit-gohri/blog/blob/685a9cbf9c5b783c49dd588418458bd6b71dd80f/gatsby-ssr.js

**Comment by rohit-gohri** [comment] 2020-04-05 21:23
I'm thinking that the full lodash import comes from gatsby itself?

**Comment by kelvindecosta** [comment] 2020-04-05 23:38
Within your site, `lodash` is being imported here:

```
plugins/gatsby-remark-page-creator/gatsby-node.js
plugins/gatsby-source-data/gatsby-node.js
src/components/Footer.js
src/components/Header.js
src/components/PostFeed.js
src/components/Social.js
src/gatsby-theme-mdx-deck/templates/decks.js
src/templates/lego.js
src/utils/Img.js
src/utils/safePrefix.js
src/utils/toStyleObj.js
src/utils/toUrl.js
```

You could discontinue the usage of the library (especially for `_.map()` since its performance is identical to `map()` according to [this experiment](https://hackernoon.com/es6-lodash-native-javascript-nodejs-example-tutorial-map-function-functional-programming-performance-speed-69645e613049)) to reduce your bundle sizes.

**Comment by rohit-gohri** [comment] 2020-04-06 05:00
@kelvindecosta Yes, but even if I use babel pluggin transform imports or gatsby-plugin-lodash, it still shows a full import of `lodash.js`.
I even ran a codemod to modify all imports to lodash/method, but it still had no effect.

**Comment by LekoArts** [comment] 2020-04-06 09:32
Please [provide a minimal reproduction][reproduction] with `gatsby-plugin-lodash` as I can't find that in your repository.

[reproduction]: https://gatsby.dev/reproduction

**Comment by kelvindecosta** [comment] 2020-04-06 13:10
Gatsby's tree-shaking functionality should take care of the issue, shouldn't it?

**Comment by rohit-gohri** [comment] 2020-04-06 15:35
> Please [provide a minimal reproduction](https://gatsby.dev/reproduction) with `gatsby-plugin-lodash` as I can't find that in your repository.

Working on it. I tried it, didn't work so didn't commit.

**Comment by rohit-gohri** [comment] 2020-04-06 16:47
While trying to reproduce it I fixed it, there was a `require("lodash")` instead of an import at https://github.com/rohit-gohri/blog/blob/174f59a7dcb8a6c9d5dc38ac6cd821956d2aa164/src/utils/safePrefix.js#L2 so babel-transform-imports didn't change it.

But the actual problem isn't that I couldn't get rid of it, it's that there isn't tooling support to find which module/file is a chunk coming from. Or if there is an easier way to know that please let me know? Loading the webpack stats file just returns that all modules are from node_modules, there isn't a mapping to actual src files (even if names match that'll be beneficial)

**Comment by LekoArts** [comment] 2020-04-09 08:48
Awesome to hear that you were able to find the culprit. So it wasn't an error with Gatsby after all. I personally don't know any better tool than the bundle-analyzer so can't comment on if there's improved tooling on that. It's not something that Gatsby currently ships with.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2020-04-09 08:48 UTC
Labels: status: needs reproduction

**Comment by roffelsaurus** [comment] 2021-07-29 13:15
For future visitors stuck on this problem; I tried many solutions to get rid of the full lodash chunk, including gatsby-plugin-lodash, only doing  "import get from 'lodash/get'" etc. 

What turned out to fix the issue was changing both the gatsby project usage and one or more in house packages from "import get from lodash/get" to "import get from 'lodash.get'", so none of them had 3rd party dep on the full lodash. I say one or more because one package is esm and the other package is cjs, so could be relevant.

Anyway, use the modularized packages to remove any doubt that it is your own code and not something deep in the gatsby deps. In my case it fixed it.
