### ISSUE TITLE
gatsby-plugin-mdx: MDXRenderer "SyntaxError: Invalid or unexpected token"

### ISSUE THREAD

**Issue by Knaackee** [gatsbyjs/gatsby#19270] opened 2019-11-05 08:30 UTC
I use "gatsby-plugin-mdx" latest version (1.0.55).

When i use `MDXRenderer` like `<MDXRenderer>{"# Hello World"}</MDXRenderer>`.

i get the following below.

```
SyntaxError: Invalid or unexpected token
_construct
node_modules/@babel/runtime/helpers/construct.js:30
  27 |     };
  28 |   }
  29 | 
> 30 |   return _construct.apply(null, arguments);
  31 | }
  32 | 
  33 | module.exports = _construct;
View compiled
(anonymous function)
node_modules/gatsby-plugin-mdx/mdx-renderer.js:30
  27 | 
  28 |   const keys = Object.keys(fullScope)
  29 |   const values = keys.map(key => fullScope[key])
> 30 |   const fn = new Function(`_fn`, ...keys, `${children}`)
  31 | 
  32 |   return fn({}, ...values)
  33 | }, [children, scope])
View compiled
mountMemo
node_modules/react-dom/cjs/react-dom.development.js:16813
  16810 | function mountMemo(nextCreate, deps) {
  16811 |   var hook = mountWorkInProgressHook();
  16812 |   var nextDeps = deps === undefined ? null : deps;
> 16813 |   var nextValue = nextCreate();
  16814 |   hook.memoizedState = [nextValue, nextDeps];
  16815 |   return nextValue;
  16816 | }
View compiled
useMemo
node_modules/react-dom/cjs/react-dom.development.js:17132
  17129 | ReactCurrentDispatcher$1.current = InvalidNestedHooksDispatcherOnMountInDEV;
  17130 | 
  17131 | try {
> 17132 |   return mountMemo(create, deps);
  17133 | } finally {
  17134 |   ReactCurrentDispatcher$1.current = prevDispatcher;
  17135 | }
View compiled
useMemo
node_modules/react/cjs/react.development.js:1643
  1640 | }
  1641 | function useMemo(create, inputs) {
  1642 |   var dispatcher = resolveDispatcher();
> 1643 |   return dispatcher.useMemo(create, inputs);
  1644 | }
  1645 | function useImperativeHandle(ref, create, inputs) {
  1646 |   var dispatcher = resolveDispatcher();
View compiled
wrappedHook [as useMemo]
node_modules/react-hot-loader/dist/react-hot-loader.development.js:2760
  2757 |       inputs.push(getHotGeneration());
  2758 |     }
  2759 | 
> 2760 |     return hook(cb, inputs);
  2761 |   }
  2762 |   return hook(cb, deps);
  2763 | };
View compiled
MDXRenderer
node_modules/gatsby-plugin-mdx/mdx-renderer.js:15
  12 | const mdxScope = useMDXScope(scope)
  13 | 
  14 | // Memoize the compiled component
> 15 | const End = React.useMemo(() => {
  16 |   if (!children) {
  17 |     return null
  18 |   }
View compiled
renderWithHooks
node_modules/react-dom/cjs/react-dom.development.js:16240
  16237 |   }
  16238 | }
  16239 | 
> 16240 | var children = Component(props, refOrContext);
  16241 | 
  16242 | if (didScheduleRenderPhaseUpdate) {
  16243 |   do {
View compiled
mountIndeterminateComponent
node_modules/react-dom/cjs/react-dom.development.js:18774
  18771 |   }
  18772 | 
  18773 |   ReactCurrentOwner$3.current = workInProgress;
> 18774 |   value = renderWithHooks(null, workInProgress, Component, props, context, renderExpirationTime);
  18775 | } // React DevTools reads this flag.
  18776 | 
  18777 | 
View compiled
beginWork$1
node_modules/react-dom/cjs/react-dom.development.js:20136
  20133 | switch (workInProgress.tag) {
  20134 |   case IndeterminateComponent:
  20135 |     {
> 20136 |       return mountIndeterminateComponent(current$$1, workInProgress, workInProgress.type, renderExpirationTime);
  20137 |     }
  20138 | 
  20139 |   case LazyComponent:
View compiled
HTMLUnknownElement.callCallback
node_modules/react-dom/cjs/react-dom.development.js:337
  334 |     window.event = windowEvent;
  335 |   }
  336 | 
> 337 |   func.apply(context, funcArgs);
  338 |   didError = false;
  339 | } // Create a global error event handler. We use this to capture the value
  340 | // that was thrown. It's possible that this error handler will fire more
View compiled
invokeGuardedCallbackDev
node_modules/react-dom/cjs/react-dom.development.js:386
  383 | // errors, it will trigger our global error handler.
  384 | 
  385 | evt.initEvent(evtType, false, false);
> 386 | fakeNode.dispatchEvent(evt);
  387 | 
  388 | if (windowEventDescriptor) {
  389 |   Object.defineProperty(window, 'event', windowEventDescriptor);
View compiled
invokeGuardedCallback
node_modules/react-dom/cjs/react-dom.development.js:441
  438 | function invokeGuardedCallback(name, func, context, a, b, c, d, e, f) {
  439 |   hasError = false;
  440 |   caughtError = null;
> 441 |   invokeGuardedCallbackImpl$1.apply(reporter, arguments);
  442 | }
  443 | /**
  444 |  * Same as invokeGuardedCallback, but instead of returning an error, it stores
View compiled
beginWork$$1
node_modules/react-dom/cjs/react-dom.development.js:25737
  25734 | } // Run beginWork again.
  25735 | 
  25736 | 
> 25737 | invokeGuardedCallback(null, beginWork$1, null, current$$1, unitOfWork, expirationTime);
  25738 | 
  25739 | if (hasCaughtError()) {
  25740 |   var replayError = clearCaughtError(); // `invokeGuardedCallback` sometimes sets an expando `_suppressLogging`.
View compiled
performUnitOfWork
node_modules/react-dom/cjs/react-dom.development.js:24661
  24658 | 
  24659 | if (enableProfilerTimer && (unitOfWork.mode & ProfileMode) !== NoMode) {
  24660 |   startProfilerTimer(unitOfWork);
> 24661 |   next = beginWork$$1(current$$1, unitOfWork, renderExpirationTime);
  24662 |   stopProfilerTimerIfRunningAndRecordDelta(unitOfWork, true);
  24663 | } else {
  24664 |   next = beginWork$$1(current$$1, unitOfWork, renderExpirationTime);
View compiled
workLoopSync
node_modules/react-dom/cjs/react-dom.development.js:24637
  24634 | function workLoopSync() {
  24635 |   // Already timed out, so perform work without checking if we need to yield.
  24636 |   while (workInProgress !== null) {
> 24637 |     workInProgress = performUnitOfWork(workInProgress);
  24638 |   }
  24639 | }
  24640 | /** @noinline */
View compiled
performSyncWorkOnRoot
node_modules/react-dom/cjs/react-dom.development.js:24236
  24233 | 
  24234 | do {
  24235 |   try {
> 24236 |     workLoopSync();
  24237 |     break;
  24238 |   } catch (thrownValue) {
  24239 |     handleError(root, thrownValue);
View compiled
scheduleUpdateOnFiber
node_modules/react-dom/cjs/react-dom.development.js:23664
  23661 |   // root inside of batchedUpdates should be synchronous, but layout updates
  23662 |   // should be deferred until the end of the batch.
  23663 | 
> 23664 |   performSyncWorkOnRoot(root);
  23665 | } else {
  23666 |   ensureRootIsScheduled(root);
  23667 |   schedulePendingInteractions(root, expirationTime);
View compiled
updateContainer
node_modules/react-dom/cjs/react-dom.development.js:27060
  27057 |   }
  27058 | 
  27059 |   enqueueUpdate(current$$1, update);
> 27060 |   scheduleWork(current$$1, expirationTime);
  27061 |   return expirationTime;
  27062 | }
  27063 | function getPublicRootInstance(container) {
View compiled
(anonymous function)
node_modules/react-dom/cjs/react-dom.development.js:27484
  27481 | 
  27482 | 
  27483 |   unbatchedUpdates(function () {
> 27484 |     updateContainer(children, fiberRoot, parentComponent, callback);
  27485 |   });
  27486 | } else {
  27487 |   fiberRoot = root._internalRoot;
View compiled
unbatchedUpdates
node_modules/react-dom/cjs/react-dom.development.js:24399
  24396 | executionContext |= LegacyUnbatchedContext;
  24397 | 
  24398 | try {
> 24399 |   return fn(a);
  24400 | } finally {
  24401 |   executionContext = prevExecutionContext;
  24402 | 
View compiled
legacyRenderSubtreeIntoContainer
node_modules/react-dom/cjs/react-dom.development.js:27483
  27480 |   } // Initial mount should not be batched.
  27481 | 
  27482 | 
> 27483 |   unbatchedUpdates(function () {
  27484 |     updateContainer(children, fiberRoot, parentComponent, callback);
  27485 |   });
  27486 | } else {
View compiled
render
node_modules/react-dom/cjs/react-dom.development.js:27620
  27617 |     !!container._reactHasBeenPassedToCreateRootDEV ? warningWithoutStack$1(false, 'You are calling ReactDOM.render() on a container that was previously ' + 'passed to ReactDOM.createRoot(). This is not supported. ' + 'Did you mean to call root.render(element)?') : void 0;
  27618 |   }
  27619 | 
> 27620 |   return legacyRenderSubtreeIntoContainer(null, element, container, false, callback);
  27621 | },
  27622 | unstable_renderSubtreeIntoContainer: function (parentComponent, element, containerNode, callback) {
  27623 |   if (!isValidContainer(containerNode)) {
View compiled
(anonymous function)
/Users/dknaack/Projects/temp/testtest/.cache/app.js:67
  64 | const preferDefault = m => (m && m.default) || m
  65 | let Root = preferDefault(require(`./root`))
  66 | domReady(() => {
> 67 |   renderer(<Root />, rootElement, () => {
  68 |     apiRunner(`onInitialClientRender`)
  69 |   })
  70 | })
```

**Comment by LekoArts** [comment] 2019-11-06 10:49
Thank you for opening this!

As written in the [README](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-mdx#mdxrenderer) the MDXRenderer expects **compiled** MDX which you get by using gatsby-plugin-mdx and Gatsby's GraphQL data layer.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2019-11-06 10:49 UTC

**Comment by Knaackee** [comment] 2019-11-06 11:10
Ah ok. So it is not possible to use MDX inside a .mdx file as a property and render it using MDXRenderer ? I mean "# Hello from body" below.

```
---
title: This!!
description: CMS Made
date: "2017-07-12T17:12:33.962Z"
templateKey: blog-post
body: >-
  # Hello from body
---

# Hello from Children

```

**Comment by LekoArts** [comment] 2019-11-06 11:20
You'd need to set the mediaType to `text/markdown` then. Read this for more information: https://github.com/gatsbyjs/gatsby/issues/19119

**Comment by Knaackee** [comment] 2019-11-06 11:40
Looks good! Thank you! You can close this.

**Comment by andrewphahn** [comment] 2020-04-25 04:22
Adding a quick note about what I ran into migrating from remark to MDX. `gatsby-plugin-mdx` excerpts are not compiled MDX and using them with `<MDXRenderer>{excerpt}</MDXRenderer>` results in the same error.

**Comment by DataHippo93** [comment] 2021-08-29 04:48
I encountered this error with the following code.
`
export default function BlogPost({ data }) {
  const post = data.blog;
  console.log(post);

  return (
    <Layout>
      <h1> {post.frontmatter.title} </h1>
      <MDXRenderer> {post.body} </MDXRenderer>
    </Layout>
  );
}

export const pageQuery = graphql`
  query DocBySlug($slug: String!) {
    blog: mdx(slug: { eq: $slug }) {
      body
      excerpt
      frontmatter {
        title
      }
    }
  }
`;
`

The issue was caused by the unnecessary spaces inside the MDXRenderer brackets. Removing the spaces fixed the problem. 
 <MDXRenderer>{post.body}</MDXRenderer>

Maybe MDXRenderer component can strip leading and trailing spaces to make this not an issue.

**Comment by davido242** [comment] 2022-05-06 14:28
Mine was having the content data node wrapped withing a paragraph tag as shown below:
 <MDXRenderer>
      **<p>{node.body}</p>**
 </MDXRenderer>
 
 to resolve this, I took off the paragraph tag wrapping it and it works fine.
 
 <MDXRenderer>
      **<p>{node.body}</p>**
 </MDXRenderer>
 
  Peace!!
