### ISSUE TITLE
MDX images showing both blurred and non-blurred images stacked

### ISSUE THREAD

**Issue by mangosing** [gatsbyjs/gatsby#17595] opened 2019-09-12 21:33 UTC
- Documentation: https://www.gatsbyjs.org/docs/mdx/plugins/

## Summary

Going through the docs on MDX and set up a very basic few pages with images. For some reason with the default config of gatsby-remark-images I am getting both the blurred & the regular image stacked on top of each other. Blurred image being on top. I have looked thourgh the docs for something I might have configured wrong and I still might. Then went into the starter library to look for a MDX starter, created a new Gatsby project locally using this starter:

https://github.com/hagnerd/gatsby-starter-blog-mdx

The same issue came up with the blurred image being stacked on top of the regular image.

You can see my repo with the issue at: https://github.com/mangosing/gatsby-mdx

Any and all help in pointing me in the right direction is much appreciated. Tried the discord channel first but no help there. Sorry if this is not the place to ask. Thank you in advance.
 
## Relevant information

Image of issue happening
![Screen Shot 2019-09-12 at 1 28 06 PM](https://user-images.githubusercontent.com/9945415/64822491-f7f7b800-d569-11e9-9662-9e078077041a.png)

### Environment (if relevant)

  System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.9.1 - ~/.nvm/versions/node/v12.9.1/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.2 - ~/.nvm/versions/node/v12.9.1/bin/npm
  Languages:
    Python: 2.7.16 - /usr/local/bin/python
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 69.0
    Safari: 12.1.2
  npmPackages:
    gatsby: ^2.15.14 => 2.15.14
    gatsby-image: ^2.2.18 => 2.2.18
    gatsby-plugin-mdx: ^1.0.41 => 1.0.41
    gatsby-plugin-page-creator: ^2.1.17 => 2.1.17
    gatsby-plugin-sharp: ^2.2.21 => 2.2.21
    gatsby-remark-images: ^3.1.21 => 3.1.21
    gatsby-source-filesystem: ^2.1.22 => 2.1.22
    gatsby-transformer-remark: ^2.6.22 => 2.6.22
    gatsby-transformer-sharp: ^2.2.14 => 2.2.14
  npmGlobalPackages:
    gatsby-cli: 2.7.47

**Comment by LekoArts** [comment] 2019-09-13 09:33
Let's close this as a duplicate of https://github.com/gatsbyjs/gatsby/issues/15486

Sorry for the inconvenience!

**Closed by LekoArts** 2019-09-13 09:33 UTC
