### ISSUE TITLE
[feat] allow gatsby develop to expose into a subfolder

### ISSUE THREAD

**Issue by KnisterPeter** [gatsbyjs/gatsby#16298] opened 2019-08-01 16:15 UTC
## Summary

Right now there is the option to use a `pathPrefix` to allow the gatsby build to live in a subfolder of a webpage.
This is not possible with develop right now, which means we couldn't test this during development.

### Motivation

For our specific requirement: We would like to run `gatsby develop` on AWS and we only have the option to run in a subfolder there (caused by our infrastructure setup).

Currently the `socketio` and `common` javascripts are loaded from `/` all the time.
This could probably relaxed to interate the `pathPrefix` here as well.

**Comment by wardpeet** [comment] 2019-08-01 16:43
Hey @KnisterPeter,

We run in the same issue as outputting data with our output folder (duplicate of #1878 & #14341). which is something we don't feel like taking on for V2 but rather something for v3.

**Comment by KnisterPeter** [comment] 2019-08-01 16:45
Hej @wardpeet,

I think this request is a bit different. Its not the output folder in the filesystem but the path-prefix during `gatsby develop`.
Do you mind to reopen this?

**Comment by wardpeet** [comment] 2019-08-01 17:01
Ok re-opened, it's the same thing, we need to change assets being loaded in the html to contain the assetPrefix as well so there is more work to be done.

We happily accept PRs for it 😄 but it won't be something @gatsbyjs/core will prioritize anytime soon.

**Comment by muescha** [comment] 2019-08-02 01:38
but if we implement something general like https://github.com/gatsbyjs/gatsby/issues/14341#issuecomment-496464447 then a the path prefix could also implemented in this and not need to expose all the `prefixPath` to all methods via a parameter.

**Comment by wardpeet** [comment] 2019-08-05 10:58
Seems like an issue was already open #16040. Closing because of duplicate.

**Closed by wardpeet** 2019-08-05 10:58 UTC
Labels: help wanted, type: feature or enhancement

**Comment by manusa** [comment] 2020-02-24 06:08
https://github.com/gatsbyjs/gatsby/issues/14898
