### ISSUE TITLE
StaticQueries do not load when their components are invoked by `ReactDOMServer.renderToString`

### ISSUE THREAD

**Issue by emckay** [gatsbyjs/gatsby#12564] opened 2019-03-14 01:37 UTC
## Description

StaticQueries do not load when their components are used by `ReactDOMServer.renderToString` or `ReactDOMServer.renderToStaticMarkup` on the client.

Locally, I am using the `useStaticQuery` hook and see this error:

```
Error: The result of this StaticQuery could not be fetched.

This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues
```

In the demo repo linked below, I am using the `StaticQuery` component and I see `<div>Loading (StaticQuery)</div>`

### Steps to reproduce

Call `ReactDOMServer.renderToString(<SomeComponentWIthAStaticQuery />)` in a component's render function.

Reproduction example: 

https://codesandbox.io/s/1r6x310kr3 

### Expected result

`ReactDOMServer.renderToString(<SomeComponentWIthAStaticQuery />)` should be resolved into a string with html.

### Actual result

StaticQuery does not resolve so `<div>Loading(StaticQuery)</div>` is rendered.

### Environment

Code sandbox fork of `gatsby-starter-default`

**Comment by DSchau** [comment] 2019-03-14 01:44
Thanks for the reproduction!

So--I'm not _really_ sure what you're trying to do here, but it's not really expected that this would work with ReactDOMServer.renderToString. We invoke those APIs _for_ you when you're writing a Gatsby app.

Is there a reason you're invoking those APIs here? Maybe there's a use case I'm not understanding here!

Something like [this Codesandbox](https://codesandbox.io/s/98q533zzyr) unravels what you're trying to do here.

**Comment by emckay** [comment] 2019-03-14 02:12
Admittedly this is a very unusual use-case! I should have given more background in the original question because I can see that it looks like I have no idea what I'm doing ;)

I don't want to render the actual DOM elements (as done by your codesandbox) -- I want to render the html string, as shown by the `ExampleComponentWithoutStaticQuery` in [my original sandbox](https://codesandbox.io/s/1r6x310kr3).

My app is a document generator -- the user fills out various fields on a form and a document is generated for them. I use a react component to render a preview for the user. When the user is done, I want to persist the exact html that was rendered as the preview to the database. The easiest way to do this is the `ReactDOMServer.renderToStaticMarkup` function, which _should_ work on client (and does in my reproduction). The only thing that is stopping me from doing this is that the StaticQuery doesn't get picked up by Gatsby.

This isn't a huge deal in my case. I'm pretty sure I can just lift my static query hook to the parent components and pass the data down as props to my renderer component. I'll be trying this tomorrow.

Just wanted to let you guys know about this edge case and provide some documentation in case others search for this :)

**Comment by sidharthachatterjee** [comment] 2019-03-18 14:20
Thank you for opening this and for the detailed writeup @emckay 

This seems like more of a React gotcha (correct me if I'm wrong) as opposed to Gatsby since the reason the reproduction is stuck at `<div>Loading (StaticQuery)</div>` is that the component renders  to String once in the call to renderToStaticMarkup (while data is loading in `develop`) and has no way to render again when the data is available. 

Lifting state up and passing it down should fix this as you mentioned. 

Side note: Your example in the reproduction works with `gatsby build` since we extract queries at build time and inject static data 😉 

Closing this issue for now since it seems unrelated to Gatsby but of course feel free to comment or reopen if we're missing something.

**Closed by sidharthachatterjee** 2019-03-18 14:20 UTC
