### ISSUE TITLE
Uncompiled graphql calls when using graphql as a function instead of a tag

### ISSUE THREAD

**Issue by Zvezdin** [gatsbyjs/gatsby#26703] opened 2020-08-30 06:58 UTC
## Description & reproducing

When using
`export const query = graphql("some arbitrary query string")`
the result is:
`Error: It appears like Gatsby is misconfigured. Gatsby related `graphql` calls are supposed to only be evaluated at compile time, and then compiled away. Unfortunately, something went wrong and the query was left in the compiled code.`

`Unless your site has a complex or custom babel/Gatsby configuration this is likely a bug in Gatsby.`

### Expected result

I think direct function calls are useful when we want to programmatically define graphql query strings. E.g. when many different queries request the same data structure with a different filter. This cannot happen with template literals because the graphql function throws when we have variables in said literals. 

An alternative solution are graphql fragments, but that would require more code instead of changing a single filter value in the same query every time.

### Environment

  System:
    OS: Linux 5.8 Arch Linux
    CPU: (12) x64 Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 14.8.0 - /tmp/yarn--1598770681224-0.9589981925842446/node
    Yarn: 1.22.4 - /tmp/yarn--1598770681224-0.9589981925842446/yarn
    npm: 6.14.7 - /usr/bin/npm
  Languages:
    Python: 3.8.5 - /usr/bin/python
  Browsers:
    Firefox: 80.0
  npmPackages:
    gatsby: ^2.19.45 => 2.24.51 
    gatsby-cli: ^2.12.89 => 2.12.89 
    gatsby-plugin-emotion: ^4.2.1 => 4.3.10 
    gatsby-plugin-typography: ^2.4.1 => 2.5.10 
    gatsby-source-filesystem: ^2.2.2 => 2.3.26 
    gatsby-source-instagram: ^0.8.0 => 0.8.0 
    gatsby-transformer-remark: ^2.7.1 => 2.8.30

**Comment by LekoArts** [comment] 2020-08-31 08:06
Thank you for opening this!

Overall this is working as intended, our babel transform is looking for that ``graphql`query` `` call and `graphql()` is only available in `gatsby-node.js`. If you want to use variable for stuff like filters you'll need to pass that information via pageContext (https://www.gatsbyjs.com/docs/page-query/#how-to-add-query-variables-to-a-page-query) and access is it.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2020-08-31 08:06 UTC
Labels: type: question or discussion
