### ISSUE TITLE
Gatsby adds environment variables (sensitive data) from .env to builds

### ISSUE THREAD

**Issue by jarekpelczynski** [gatsbyjs/gatsby#7277] opened 2018-08-13 12:04 UTC
I've found that Gatsby adds to my build files environment variables from dotenv files, for example, I've found in `component---src-pages-index-js-c8f7e2184f87585fa42c.js` variables like CMS_URL, TOKENS, etc:

`{SITE_URL:"https://***.com",CMS_URL:"***",CMS_PROTOCOL:"https",NODE_ENV:"production",PUBLIC_DIR:"/Users/**/**/**/public"}`

Is it only my case, Gatsby should do it right or it's a bug?

**Comment by jarekpelczynski** [comment] 2018-08-14 08:45
I've investigated some sites built in Gatsby (pages which use Wordpress source plugin), and I've found in their source code same issue. You can find there e.g. user and password for WP instances.

**Comment by jarekpelczynski** [comment] 2018-08-14 13:36
@KyleAMathews especially if you provide Wordpress credentials (user, pass, token, etc).

**Comment by KyleAMathews** [comment] 2018-08-14 13:46
Where are you using those credentials?

**Comment by jarekpelczynski** [comment] 2018-08-14 13:55
I've found that people use credentials for `gatsby-source-wordpress` dependent on an environment (using .env files) then sensitive information appears in build files (also applies to me).

**Comment by Fetten** [comment] 2018-12-01 11:10
This has recently been fixed via #10021.

**Comment by sidharthachatterjee** [comment] 2019-01-14 14:56
Leaking env variables was fixed in https://github.com/gatsbyjs/gatsby/pull/10030

Adding variables defined in `.env.development` and `.env.production` to the bundle is by design as documented in https://www.gatsbyjs.org/docs/environment-variables/

@jarekpelczynski Closing this for now but please feel free to reopen if there is anything else

**Closed by sidharthachatterjee** 2019-01-14 14:56 UTC
Labels: type: question or discussion
