### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by lukasa1993** [gatsbyjs/gatsby#14925] opened 2019-06-19 17:50 UTC
```
(node:54) UnhandledPromiseRejectionWarning: ReferenceError: window is not defined
    at navigate (/srv/public/render-page.js:32363:3)
    at _callee$ (/srv/public/render-page.js:92119:70)
    at tryCatch (/srv/public/render-page.js:1941:40)
    at Generator.invoke [as _invoke] (/srv/public/render-page.js:2167:22)
    at Generator.prototype.<computed> [as throw] (/srv/public/render-page.js:1993:21)
    at asyncGeneratorStep (/srv/public/render-page.js:1131:24)
    at _throw (/srv/public/render-page.js:1157:9)
    at runNextTicks (internal/process/task_queues.js:55:5)
    at listOnTimeout (internal/timers.js:501:9)
    at processTimers (internal/timers.js:475:7)
(node:54) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

how i find which file it is?

**Comment by donaldboulton** [comment] 2019-06-19 22:13
Most likely in you node modules

**Comment by marcysutton** [comment] 2019-06-19 23:02
Looks like a script is being imported that needs access to the browser DOM, which isn't available at build time. Here's a doc on how to work with client-side-only packages: https://www.gatsbyjs.org/docs/using-client-side-only-packages/

If you still have trouble, a reproducible test case would help: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

**Comment by lukasa1993** [comment] 2019-06-20 04:40
none of that was the case it was somewhere in src my code but finding this is unbearable i just went thrue line by line this error must be more specific

**Comment by freiksenet** [comment] 2019-06-20 12:12
@lukasa1993 Could you provide us with a reproduction or access to the code? This way we could help you with this.

**Comment by lukasa1993** [comment] 2019-06-20 12:13
> @lukasa1993 Could you provide us with a reproduction or access to the code? This way we could help you with this.

i already fixed it, but this errors are way harder to track down then it needs to, if it would prince just line where this happens would be much easier

**Comment by sidharthachatterjee** [comment] 2019-06-25 09:24
Thank you for opening this @lukasa1993 

As @marcysutton mentioned, this looks like an SSR issue. We're glad that you managed to fix it and hence, we'll be closing this out. 

I have opened another issue where we'll handle improving stack traces though. Thank you for the valuable feedback and for using Gatsby!

**Closed by sidharthachatterjee** 2019-06-25 09:24 UTC
Labels: status: needs reproduction
