### ISSUE TITLE
Problems with relative urls

### ISSUE THREAD

**Issue by clouddra** [gatsbyjs/gatsby#142] opened 2016-02-24 03:34 UTC
I am encountering problems with relative `urls` referenced in css files i.e. (`.bg { background: url('./background.png'); }` after the gatsby upgrade. Would love someone to give me pointers on how to get it to work.

Here is my webpack configuration.  
```javascript
config.loader('sass', function (cfg) {
      cfg.test = /\.scss$/;
      cfg.loader = 'style!css?modules&localIdentName=[path][name]-[local]-[hash:base64:5]&importLoaders=1!postcss';
      return cfg;
    });
```

**Comment by KyleAMathews** [comment] 2016-02-24 04:33
I think you need to remove the built in sass (new in 0.8) configuration for
yours to work.

**Comment by clouddra** [comment] 2016-02-24 06:09
@KyleAMathews Thanks for the quick reply!
Did you mean adding `config.removeLoader('sass');`? 
Still does not work for me.

**Comment by KyleAMathews** [comment] 2016-02-24 07:19
Ok :-) guess didn't work. Not really familiar with postcss tbh so not sure.
Perhaps it's the other postcss loaders that were added that are interfering
with your setting?

**Comment by clouddra** [comment] 2016-02-24 07:57
it works for `sass-loader` but not with `postcss` (with the `postcss` loaders that gatsby is currently using). 
Using `sass-loader` however would mean that we lose out on all the nice stuff that `postcss` have.

I will work on it for a bit longer to see if I can trace the problem...

**Comment by KyleAMathews** [comment] 2016-02-24 08:15
👍🏻

**Comment by KyleAMathews** [comment] 2016-03-14 06:18
@clouddra closing this for now. Feel free to reopen (or open new issue) if you trace what the problem is with the current webpack loader setup.

**Closed by KyleAMathews** 2016-03-14 06:18 UTC

**Comment by clouddra** [comment] 2016-03-14 07:51
@KyleAMathews np. Thanks for the help
