### ISSUE TITLE
onRenderBody and onPreRenderHTML are not being called in gatsby-ssr

### ISSUE THREAD

**Issue by ilyador** [gatsbyjs/gatsby#28170] opened 2020-11-19 01:20 UTC
This is how my gatsby-ssr looks like:

```js
import React from 'react'
import Helmet from 'react-helmet'
import Wrapper from './src/templates/pages-layout'

export const wrapRootElement = ({ element }) => <Wrapper>{element}</Wrapper>

export const onRenderBody = ({ setHeadComponents, setHtmlAttributes, setBodyAttributes }) => {
...
}

export const onPreRenderHTML = ({ getHeadComponents, replaceHeadComponents }) => {
...
}
```

Whatever I put inside `onRenderBody` and `onPreRenderHTML` is never executed, even the simplest things to test like `console.log`.

For context, I am trying to implement this solution to the SEO issue https://github.com/gatsbyjs/gatsby/issues/22206#issuecomment-710591572

**Comment by ascorbic** [comment] 2020-11-19 09:52
Hi @ilyador 

I've tried reproducing this with similar code to yours, and have had no luck. To help us best begin debugging the underlying cause, it would be really helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

Thanks!

[reproduction]: https://gatsby.dev/reproduction

**Comment by ediblecode** [comment] 2020-11-20 19:51
I was trying to do something similar the other day with `onPreRenderHTML`. It may seem obvious...but that doesn't work in develop mode, only when doing a production build, so double check which mode you're. It took me a while to realise/remember that develop renders client side, so won't call `onPreRenderHTML`. That changes with #27432 though!

**Comment by Darth-Knoppix** [comment] 2020-11-26 17:44
Perfect timing, I ran into this today but 2.27.0 is out 👍

**Comment by LekoArts** [comment] 2020-11-27 08:47
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-11-27 08:47 UTC
Labels: status: needs reproduction, type: bug
