### ISSUE TITLE
Double slash issue within console causing a 404 error on internal pages VM13:1 GET https://www.domain.com/page-data//slug/page-data.json net::ERR_ABORTED 404

### ISSUE THREAD

**Issue by matthewitc** [gatsbyjs/gatsby#28688] opened 2020-12-18 12:23 UTC
I am getting 404 errors in the console for every internal pages only but doesn't happen on the homepage.

This error happens when navigating through the internal pages.

This is the error: VM13:1 GET https://www.buzzluck.com/page-data//promotions/page-data.json net::ERR_ABORTED 404.

Its a weird double slash issue please see screenshots below:

![double-slash-screenshot](https://user-images.githubusercontent.com/49908076/102611910-bd46dd00-4127-11eb-94d0-64e38d767c6f.png)

![double-slash-instpector](https://user-images.githubusercontent.com/49908076/102614251-cc2f8e80-412b-11eb-9888-05a67edf17ee.png)

The solution is using gatsby, typescript and emotion.

**Comment by vladar** [comment] 2020-12-18 14:14
Hi @matthewitc !

That's interesting. Can you create a [minimal reproduction][reproduction]? This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by matthewitc** [comment] 2020-12-21 09:08
Hi @vladar, 

This is possible to do but we have a lot of plugins in the solution so would be hard to replicate a minimal reproduction of the same solution which the issue would probably not happen. Do you know an area we should be looking to solve this problem with the double slashes? 

Thanks Matthew

**Comment by ascorbic** [comment] 2021-01-28 11:59
@matthewitc You could start by looking at links and other references to the `/promotions/` page. Check the `to` prop

**Comment by LekoArts** [comment] 2021-02-04 10:22
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-02-04 10:22 UTC
Labels: status: needs reproduction, type: bug
