### ISSUE TITLE
Gatsby develop refresh endpoint memory leak

### ISSUE THREAD

**Issue by apaniel90vp** [gatsbyjs/gatsby#25868] opened 2020-07-20 10:53 UTC
## Description

Each time the refresh endpoint is hit, memory increases a little bit and it doesn't go down, eventually leading to a heap out of memory after multiple refreshes.

develop process memory previous to a refresh:
![image](https://user-images.githubusercontent.com/40391767/87930698-d1a78080-ca88-11ea-94f4-96db4eebf7e1.png)

develop process memory after a refresh:
![image](https://user-images.githubusercontent.com/40391767/87930711-d53b0780-ca88-11ea-8013-b56cd4634b4e.png)

and hitting more times refresh it just goes higher.

adding **--max_old_space_size** to a high value just delays the out of memory.

### Steps to reproduce

gatsby develop
hit refresh endpoint
wait until refresh finishes
hit refresh endpoint
...

### Expected result

Memory should not increase without getting back to normal over time.

### Actual result

Eventually there is a memory leak

### Environment

  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Xeon(R) CPU E5-1650 v4 @ 3.60GHz
  Binaries:
    Yarn: 1.21.0 - C:\Users\apa\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.4 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.8.3 - /c/Python38/python
  Browsers:
    Edge: 44.17763.831.0
  npmPackages:
    gatsby: 2.24.2 => 2.24.2 
    gatsby-graphiql-explorer: ^0.2.31 => 0.2.31 
    gatsby-plugin-react-decorators: 0.0.4 => 0.0.4 
    gatsby-plugin-react-helmet: ^3.1.18 => 3.1.18 
    gatsby-plugin-sass: ^2.1.26 => 2.1.26 
    gatsby-plugin-sharp: ^2.3.9 => 2.3.9 
    gatsby-plugin-typescript: ^2.1.23 => 2.1.23 
    gatsby-source-contentful: ^2.3.15 => 2.3.15 
    gatsby-source-filesystem: ^2.1.42 => 2.1.42 
    gatsby-transformer-json: ^2.2.22 => 2.2.22 
    gatsby-transformer-sharp: ^2.3.9 => 2.3.9

**Comment by madalynrose** [comment] 2020-07-21 19:25
Hi @apaniel90vp!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction] either in a public repo or on something like codesandbox. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by wardpeet** [comment] 2020-07-22 07:13
@apaniel90vp It's more likely an issue with gatsby-source-contentful than with gatsby refresh endpoint. Do you see the same behaviour without contentful?

**Comment by apaniel90vp** [comment] 2020-07-22 07:21
@wardpeet that is a very good point, probably without contentful plugin it doesn't happen, as I can see the highest memory peak while generating the schema. I won't be able to check this today, but I will do tomorrow! Thanks!

**Comment by axe312ger** [comment] 2020-07-22 08:17
I can confirm that I saw this happening as well.

Any help to identify where it is coming from is very welcome :)

**Comment by AnalogMemory** [comment] 2020-08-26 08:08
Has anyone identified the root issues with this? I've been having issues this week with memory

- Having multiple Contentful sources (2x) runs out of memory (removing one stops issue)
- Debug says ~6000 nodes

Not sure what the best way to debug it further.

**Comment by axe312ger** [comment] 2020-09-09 10:29
@AnalogMemory do you use Rich Text?  There is a bug in the current version of the source plugin which blows up your memory as soon you have Rich Text and some content referenced with a circular reference. The canary version at #25249 does fix this issue

**Comment by axe312ger** [comment] 2020-09-09 10:31
To the actual ticket:

I'd be very happy about anybody doing research what is actually spamming the browser (!) memory and will happily support with a fix for it. Otherwise we have to wait till I find time for this, and 2020 is very busy 😅

**Comment by AnalogMemory** [comment] 2020-09-09 18:03
@axe312ger Yeah I finally figured out it was a combo of 
- Contentful embedded hyperlinks in RichText fields to entries with RichText fields (and then back and forth, forever)
- gatsby-contentful-source couldn't handle that many circular references it seemed

One of my content editors started using more of them just before it happened. Seems to be fine with a few, but when over a 100 entries were linking to each other it was killing the memory when gatsby-contentful-source was trying to build the queries.

I tried the gatsby-contentful-source@next version but it would have been more work to rewrite things and didn't want to push it out to production in that state.

Ended up finding a patch that @disintegrator posted and using that to hold me over till a proper release is ready :)
https://github.com/gatsbyjs/gatsby/issues/24221#issuecomment-665198654

I do have a task to test out the next version when I'm back from vacation next week

Thanks!

**Comment by axe312ger** [comment] 2020-09-16 07:23
IMHO I'd go for the official canary which will contain the fix for later on instead of monkeypatching the old code. But thats you decission.


Please continue discussion in #24221 as this ticket originally is about a bug in the browser while developing, not when sourcing the nodes.

**Comment by ImOnSmoko** [comment] 2020-09-17 17:33
We're struggling with this issues as well. We are using the refresh endpoint to enable preview functionality for our content authors, so refresh is called frequently. Each call incrementally increases memory consumption until the application crashes.

Docker running node:12.18.3-alpine3.11

**"gatsby": "^2.23.3",**
"gatsby-image": "^2.2.42",
"gatsby-plugin-compile-es6-packages": "^2.1.0",
"gatsby-plugin-create-client-paths": "^2.1.22",
"gatsby-plugin-env-variables": "^1.0.1",
"gatsby-plugin-google-tagmanager": "^2.1.25",
"gatsby-plugin-manifest": "^2.2.42",
"gatsby-plugin-material-ui": "^2.1.9",
"gatsby-plugin-offline": "^3.0.35",
"gatsby-plugin-react-helmet": "^3.1.22",
"gatsby-plugin-react-svg": "^3.0.0",
"gatsby-plugin-robots-txt": "^1.5.0",
"gatsby-plugin-sharp": "^2.4.5",
"gatsby-plugin-sitemap": "^2.4.13",
"gatsby-plugin-svgr-loader": "^0.1.0",
"gatsby-plugin-typegen": "^1.1.2",
"gatsby-plugin-typescript": "^2.2.0",
"gatsby-plugin-web-font-loader": "^1.0.4",
**"gatsby-source-contentful": "^2.3.35-next.63",**
"gatsby-source-filesystem": "^2.1.48",
"gatsby-transformer-sharp": "^2.3.16",

**Comment by axe312ger** [comment] 2020-10-02 12:44
Did anybody yet figure out what data is bloating the memory? Or which call is causing it? Any help in research is very much appreciated :)

**Comment by ImOnSmoko** [comment] 2020-10-02 21:44
I’m not aware of a specific question around this. The only hard data we have is the output in the Gatsby Cloud dashboard. Local runs show that the ‘Building production JavaScript and CSS bundles’ is the longest step.

I think it be more valuable to arrange a call so that all involved are up-to-date and doing our utmost to provide the information needed>

Thanks,

Richard George  •  Application Development / Customer Tech Digital • 503-464-7856

**Comment by ImOnSmoko** [comment] 2020-10-06 17:08
Good morning:

Are you in a position to discuss where the POC is at and what, if any, next steps are open to us?

Thanks,

Richard George  •  Application Development / Customer Tech Digital • 503-464-7856


From: Richard George
Sent: Friday, October 2, 2020 2:44 PM
To: gatsbyjs/gatsby <reply@reply.github.com>; gatsbyjs/gatsby <gatsby@noreply.github.com>
Cc: Comment <comment@noreply.github.com>
Subject: RE: [gatsbyjs/gatsby] Gatsby develop refresh endpoint memory leak (#25868)

I’m not aware of a specific question around this. The only hard data we have is the output in the Gatsby Cloud dashboard. Local runs show that the ‘Building production JavaScript and CSS bundles’ is the longest step.

I think it be more valuable to arrange a call so that all involved are up-to-date and doing our utmost to provide the information needed>

Thanks,

Richard George  •  Application Development / Customer Tech Digital • 503-464-7856

**Comment by vladmiller** [comment] 2020-10-09 15:55
I experience the same behaviour with WordPress using `gatsby-source-graphq`.

**Comment by vladar** [comment] 2020-10-27 18:22
Can you try `gatsby@2.24.89`? A potential improvement was shipped in #27685 (won't fix it completely but hopefully will make the leak less offending)

**Comment by axe312ger** [comment] 2021-03-29 10:22
This should be fixed since a while. If you still experience this issue, and use the latest version of gatsby-source-contentful, pls let us know

**Closed by axe312ger** 2021-03-29 10:22 UTC
Labels: topic: Contentful, type: bug
