### ISSUE TITLE
Can't Navigate With Keyboard Through Documentation

### ISSUE THREAD

**Issue by machineghost** [gatsbyjs/gatsby#26788] opened 2020-09-04 19:23 UTC
## Description

You can't use your keyboard to scroll through the documentation.

### Steps to reproduce

Go to (say) https://www.gatsbyjs.com/docs/page-query/ and try to use your keyboard (either Page Down or just Down) to scroll. I tested on both Chrome and Firefox, and it didn't work on either.

### Expected result

You should  be able to use the keyboard to do anything a mouse can do (or at the very least, to scroll the page).

It seems to be something to do with the overflow styles you're using, but normally when an element has overflow styles the user can at least click on the text inside the overflowed element to "focus" it, and then keyboard commands work from that point on. In fact, you *can* scroll the menu to the left of the documentation using the keyboard, if you "focus" it first.

There must be some other style preventing that normal behavior (or an onKey handler of some sort?)

### Actual result

The only way to scroll is with mousewheel scroll, or by dragging the scroll bars.

### Environment

  System:
    OS: Linux 5.4 Linux Mint 20 (Ulyana)
    CPU: (8) x64 Intel(R) Core(TM) i7-4810MQ CPU @ 2.80GHz
    Shell: 5.0.17 - /bin/bash
  Binaries:
    Node: 14.8.0 - /usr/bin/node
    npm: 6.14.7 - /usr/bin/npm
  Browsers:
    Chrome: 84.0.4147.135
    Firefox: 79.0
  npmPackages:
    gatsby: ^2.24.15 => 2.24.15
    gatsby-cli: ^2.12.47 => 2.12.47
    gatsby-image: ^2.4.7 => 2.4.7
    gatsby-plugin-import: ^2.1.5 => 2.1.5
    gatsby-plugin-manifest: ^2.4.11 => 2.4.12
    gatsby-plugin-modal-routing: ^1.2.0 => 1.2.0
    gatsby-plugin-offline: ^3.2.9 => 3.2.11
    gatsby-plugin-react-helmet: ^3.3.4 => 3.3.4
    gatsby-plugin-root-import: ^2.0.5 => 2.0.5
    gatsby-plugin-s3: ^0.3.4 => 0.3.4
    gatsby-plugin-sharp: ^2.6.11 => 2.6.12
    gatsby-source-filesystem: ^2.3.11 => 2.3.12
    gatsby-source-pg: ^0.2.1 => 0.2.1
    gatsby-transformer-sharp: ^2.5.5 => 2.5.5
  npmGlobalPackages:
    gatsby: 2.24.15

**Comment by nolastan** [comment] 2020-09-05 18:09
I'm able to replicate this issue. Neither spacebar nor arrow keys will scroll the page. I am using Safari 13.1.2.

**Comment by LekoArts** [comment] 2020-09-07 06:58
This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/26747

**Closed by LekoArts** 2020-09-07 06:58 UTC
Labels: type: bug, type: documentation
