### ISSUE TITLE
[gatsby-plugin-typography] Using npm to install it can result in errors

### ISSUE THREAD

**Issue by gris** [gatsbyjs/gatsby#26491] opened 2020-08-16 17:05 UTC
## Description

When I follow the part three of the tutorial, after installing `gatsby-plugin-typography` using npm it gives me an error saying that it can't find module `react`.
 
### Steps to reproduce

Follow part three of the tutorial and use the command on it to install `gatsby-plugin-typography` and them try to run `gatsby develop` to see the error. You can find more details in [here](https://discordapp.com/channels/484383807575687178/537691356487876624/744304463426355340) 

### Expected result

To not give an error when running `gatsby develop`. Using yarn to install it, instead of npm removes the problem.

### Actual result
`Cannot find module react`

### Environment

  System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 84.0.4147.125
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.24.41 => 2.24.41 
    gatsby-plugin-typography: ^2.5.10 => 2.5.10 
  npmGlobalPackages:
    gatsby-cli: 2.12.87

**Comment by LekoArts** [comment] 2020-08-25 10:39
Hello and thanks for the issue!
This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/19064 and the issue outlines the reason and possible solutions.

The reason is an upstream issue with npm where it deletes packages from your `node_modules` folder (hence the missing react package) when the lock file is corrupted. Running `npm install` again should fix your issue (if that doesn't work, delete both the `node_modules` folder and the `package-lock.json` file). While we understand that this might be frustrating, we are currently still investigating how we can workaround this upstream issue.

**Closed by LekoArts** 2020-08-25 10:39 UTC
Labels: type: bug
