### ISSUE TITLE
Are you a Gatsby Freelancer ?

### ISSUE THREAD

**Issue by sebastienfi** [gatsbyjs/gatsby#4690] opened 2018-03-24 16:52 UTC
## Gatsby Freelancers

In order to prepare a listing of Gatsby Freelancers on gatsbyjs.org, post your contact info here if you do want to appear in this list.

I'm also looking for someone to do a blog on Netlify CMS + Gatsby because I don't have the stream to do it myself, [drop me a mail](fichot.sebastien@gmail.com) if interested.

**Comment by pzatrick** [comment] 2018-03-24 18:55
pscale01@gmail.com
https://patrickcanfield.com

Also, maybe I'm misunderstanding but does this cover what you're looking for (Netlify CMS + Gatsby)?
 https://www.gatsbyjs.org/docs/netlify-cms/

**Comment by sebastienfi** [comment] 2018-03-24 20:01
@pzatrick Yes, Netlify CMS as CMS to create the pages and articles and edit contents in markdown, then fed to Gatsby using `gatsby-plugin-netlify-cms`. Sent you an email about it.

**Comment by Jaikant** [comment] 2018-03-25 04:15
jaikant@gmail.com 

there were a few issues with netlify CMS and Gatsby integration a few weeks back, not sure if it is resolved now.

**Comment by sebastienfi** [comment] 2018-03-26 13:05
@Jaikant Sent you en email
Which issues are you refering to ?

**Comment by blargity** [comment] 2018-04-02 16:03
@sebastienfi They're able to be worked around, but these are the ones I've hit. They're mostly very reasonable decisions for both projects by themselves, but when you put them together it's frustrating:

- NetlifyCMS creates image paths as absolute paths from the final resulting location of the image. So if the image lives in `static/assets/hello.jpg`, NetlifyCMS will put `/assets/hello.jpg` in the content. This is fine, but Gatsby doesn't see these as images and kick up with Sharp processing until you figure out a relative path from the actual content file. I had to hack around this in `gatsby-node.js` in #4769.
- NetlifyCMS is quite happy to let you have spaces in file names for images. Gatsby is not, and if there are spaces in a filename then the Sharp transformer doesn't pick them up properly, or at least `resize` doesn't work. I have a script that removes spaces from any images referenced in my content that users enter in the CMS.
- NetlifyCMS is quite happy to let you set up content that points to an image, then for you to delete the image without updating the content that points to it. If there is a single image referenced in content that doesn't exist on disk, the Sharp transformer doesn't kick up, and you get strings, breaking all your queries. I have a script I run before build to ensure that if I can't stat the file I remove it from the content, but still, fragile.
- NetlifyCMS defaults to not putting a field in the JSON at all if you don't set it in the UI. While that makes sense as a position, if no content in the site has a particular field, your GraphQL queries break for Gatsby because the field is missing from the schema. I set a default of `""` for my optional fields to ensure that at least one document has the field. It'd be nice to handle this is a less brittle way either in NetlifyCMS or in Gatsby by being able to ensure a schema and not trying to infer it from the content.

**Comment by m-allanson** [comment] 2018-04-04 16:17
Hey @blargity 👋, spaces in filenames is something that Gatsby should handle - would you be interested in writing that up as a new issue?

**Comment by blargity** [comment] 2018-04-06 01:45
I didn't have time to make a repro case so I worked around it for now. If I get time I will. For the moment I'm more worried about #4799. 👍

**Comment by Jaikant** [comment] 2018-04-06 13:52
@sebastienfi the issues related to images as mentioned by @blargity and a few others like the one below.  https://github.com/gatsbyjs/gatsby/issues/4516

The most frustrating one was when the netlify plugin was causing gatsby build failures about a month back. The issue is closed now, so need to try it to see if it works.

**Comment by metamas** [comment] 2018-04-10 15:17
mason@metamas.com

Just rebuilt my personal site with Gatsby, and it's been an absolute pleasure. Would love to do more client work with it in the future.

**Comment by MarcCoet** [comment] 2018-04-17 13:18
Btw, I have never took the time to publish and talk about toile.io. I am a solo developer and my code is a mess but if there is real interest I could try and make the V1 ready for open source.
And if someone is interested in helping for the V2, let me know.

**Comment by giraffesyo** [comment] 2018-07-17 14:50
Michael McQuade 
michael@giraffesyo.io
https://giraffesyo.io

**Comment by lloydh** [comment] 2018-08-21 15:59
Has this listing been created? We're looking for a gatsby freelancer!

**Comment by metamas** [comment] 2018-08-22 16:51
@lloydh I use Gatsby on a few client projects, and I'm looking to do more work with it. I'd like to hear more about your project. DM me on Twitter (@metamas_), or email mason@metamas.com

**Comment by pieh** [comment] 2018-09-21 12:42
Hey @sebastienfi - can this be closed?

**Comment by koreyboone** [comment] 2018-09-21 13:32
Also very curious about a freelance list...

**Comment by sebastienfi** [comment] 2018-09-22 18:50
@pieh I don't think the freelancer list has been ever created... Would you create it?

**Comment by calcsam** [comment] 2018-09-23 08:31
Created this as a Google Group with open membership:

https://groups.google.com/a/gatsbyjs.com/d/forum/freelancers

Please also feel free to add yourselves to the new (dark-deployed) Community page!

https://www.gatsbyjs.org/community

**Comment by LekoArts** [comment] 2018-12-14 16:34
The Creator Showcase is now available here: https://www.gatsbyjs.org/creators

You can find information about it here: https://www.gatsbyjs.org/docs/submit-to-creator-showcase/

Closing this issue as the creator showcase is the preferred way for freelancers and people who try to find freelancers 👍

**Closed by LekoArts** 2018-12-14 16:34 UTC
