### ISSUE TITLE
gatsby-plugin-offline: 404 page not found using pathPrefix

### ISSUE THREAD

**Issue by sktt** [gatsbyjs/gatsby#7882] opened 2018-09-05 00:14 UTC
## Description

the plugin no longer appears to support pathPrefix.

### Steps to reproduce

make a build with path prefix set. clear any existent application data. go to website. observe that it works the first time. reload the page. observe a 404 message. check your server logs. observe that a 404 was generated from a request to `/offline-plugin-app-shell-fallback/index.html`, that is without pathprefix.

### Expected result

the pathprefix should be used

### Actual result

the path prefix is not used

### Environment

```
  System:
    OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
    CPU: x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
    Shell: 5.3.1 - /bin/zsh
  Binaries:
    Node: 10.7.0 - ~/.nvm/versions/node/v10.7.0/bin/node
    Yarn: 1.9.4 - ~/.nvm/versions/node/v10.7.0/bin/yarn
    npm: 6.3.0 - ~/.nvm/versions/node/v10.7.0/bin/npm
  Browsers:
    Chrome: 68.0.3440.106
    Firefox: 52.9.0
  npmPackages:
    gatsby: ^2.0.0-rc.7 => 2.0.0-rc.7
    gatsby-image: ^2.0.0-rc.1 => 2.0.0-rc.1
    gatsby-node-helpers: ^0.3.0 => 0.3.0
    gatsby-plugin-google-analytics: ^2.0.0-rc.1 => 2.0.0-rc.1
    gatsby-plugin-manifest: ^2.0.2-rc.1 => 2.0.2-rc.1
    gatsby-plugin-offline: ^2.0.0-rc.2 => 2.0.0-rc.2
    gatsby-plugin-postcss: ^2.0.0-rc.1 => 2.0.0-rc.1
    gatsby-plugin-react-css-modules: ^2.0.0-rc.1 => 2.0.0-rc.1
    gatsby-plugin-react-helmet: ^3.0.0-rc.1 => 3.0.0-rc.1
    gatsby-plugin-sass: ^2.0.0-rc.1 => 2.0.0-rc.1
    gatsby-plugin-sharp: ^2.0.0-rc.3 => 2.0.0-rc.3
    gatsby-plugin-typography: ^2.2.0-rc.2 => 2.2.0-rc.2
    gatsby-source-filesystem: ^2.0.1-rc.1 => 2.0.1-rc.1
    gatsby-transformer-sharp: ^2.1.1-rc.2 => 2.1.1-rc.2
  npmGlobalPackages:
    gatsby: 2.0.0-beta.87

```

**Comment by kakadiadarpan** [comment] 2018-09-05 06:45
Duplicate of #7861

**Closed by kakadiadarpan** 2018-09-05 06:45 UTC
Labels: type: bug
