### ISSUE TITLE
gatsby-source-wordpress does not delete GraphQL nodes on refresh using ENABLE_GATSBY_REFRESH_ENDPOINT

### ISSUE THREAD

**Issue by jeffreznik** [gatsbyjs/gatsby#19529] opened 2019-11-15 05:07 UTC
## Description

When using the gatsby-source-wordpress plugin and with `ENABLE_GATSBY_REFRESH_ENDPOINT` enabled, data nodes are added/updated as expected when POSTing to the `/__refresh` endpoint, but when content is deleted the nodes remain.

### Steps to reproduce

1. Create new gatsby-starter-wordpress project using gatsby-cli
2. Connect gatsby to any Wordpress site you control (I have mine set up in Docker for testing)
3. Run `gatsby develop`
Note: I ran into an issue here where the starter assumes you have at least one tag on your posts, if you don't the starter breaks.  Just go into Wordpress, and save a new tag to an existing post, then restart `gatsby develop`
4. Add/publish new post in Wordpress
5. Use Postman to POST to `http://localhost:8000/__refresh`, you'll see your new post appear on the page
6. Trash post in Wordpress (can Empty Trash too just to be sure it's gone)
7. Use Postman to POST to `http://localhost:8000/__refresh` again, the post you published still remains

### Expected result

The deleted post should disappear off the page.

### Actual result

The deleted post remains on the page.  Executing an `allWordpressPost` query on the data in `http://localhost:8000/__graphql` shows the deleted post is still present in the model.

### Environment

  System:
    OS: Linux 4.9 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (4) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 10.17.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  npmGlobalPackages:
    gatsby-cli: 2.8.9

**Comment by LekoArts** [comment] 2019-11-15 08:40
Hi, thanks for the issue!
This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/18040 and https://github.com/gatsbyjs/gatsby/pull/18802

**Closed by LekoArts** 2019-11-15 08:40 UTC
