### ISSUE TITLE
creating foreign key relation with post and Tags

### ISSUE THREAD

**Issue by kamit-transient** [gatsbyjs/gatsby#24791] opened 2020-06-04 23:01 UTC
## Summary
I am using ` gatsby source-filesystem` and `gatsby-mdx` plugin for sourcing the contents. When I query the `allMdx or Mdx` for Post I only get tag name as String but I actually want to create foreign key relationship between post and Tag, so that I can query Tag directly from Post.

I went through the official site documentation at [https://www.gatsbyjs.org/docs/schema-customization/](https://www.gatsbyjs.org/docs/schema-customization) but unfortunately even after many attempts its not working for me.

Please suggest, how can I create this foreign key relation between post and tag.

### File contents (if changed)

`gatsby-node.js`: 
```
exports.createSchemaCustomization = ({ actions, schema }) => {
    const { createTypes } = actions;
 const typeDefs = `  type Mdx implements Node {
        frontmatter: MdxFrontmatter
    }
    type MdxFrontmatter {
        category: MdxCategory @Link(by:"title") 
    }

    type MdxCategory{
        title:String
    }
    `
    createTypes(typeDefs)

}

```
Markdown file:
```
//first-post.md

---
title: first post
description: first post description
year: "2020"
collection_type: Post
date: 2020-06-01T20:34:55.880Z
last_modified_date: 2020-06-01T20:34:55.930Z
published: true
cover_image: /uploads/•-you-re-the-greatest-•-1-.png
category: Java Script
tags:
  - reactjs
  - vuejs
---
first postfirst postfirst postfirst postfirst postfirst postfirst post

```

Tag Files
```
//Reactjs.md
---
collection_type: Tag
title: reactjs
published: true
---




and //vuejs.md
---
collection_type: Tag
title: vuejs
published: true
---
```

**Comment by freiksenet** [comment] 2020-06-05 11:17
In `category: MdxCategory @Link(by:"title")` `Link` should be `link` (with non-capital L). Also the example you are showing has `tags` (which would match by title), but you are trying to link `category`.

If that doesn't help, could you provide create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by kamit-transient** [comment] 2020-06-06 00:00
Thanks @freiksenet I solved it with different approach. would u mind sharing a snippet with post and tags example.

For now i am using `mapping` and below is the snippet:

```
  mapping: {
    'Mdx.frontmatter.category': `Mdx.frontmatter.title`,
    'Mdx.frontmatter.tags': `Mdx.frontmatter.title`
  },
```

**Comment by LekoArts** [comment] 2020-07-03 12:48
Hi!

Since you said that you solved your initial issue, I'll close this one. Please [create a minimal reproduction](https://gatsby.dev/reproduction) if you need further help with your second issue. Answering on the `mapping` is not possible without seeing the complete project. Thanks!

**Closed by LekoArts** 2020-07-03 12:48 UTC
Labels: type: question or discussion
