### ISSUE TITLE
www: no codeblocks if JS disabled or on runtime errors

### ISSUE THREAD

**Issue by stufinn** [gatsbyjs/gatsby#25802] opened 2020-07-16 19:25 UTC
## Description

In the "Using Tailwind CSS" reference guide, under step **[1. Install Tailwind](https://www.gatsbyjs.org/docs/tailwind-css/#1-install-tailwind)**,  there should be a command listed: `npm install tailwindcss --save-dev` but it seems to be missing on the live site.

When one navigates to the .md file via the "[edit this page on github](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/tailwind-css.md)" link, the command appears to be there. I'm not sure why it is not displaying correctly.

### Steps to reproduce

Visit the documentation page to observe the missing command: `npm install tailwindcss --save-dev`

Select the [Edit this page on Github](https://github.com/gatsbyjs/gatsby/blob/master/docs/docs/tailwind-css.md) link near the bottom of the screen to navigate to the markdown file on github. You will see that the command is in the .md file.

### Expected result

The command `npm install tailwindcss --save-dev` should be listed under step 1 in the gatsby docs.

### Actual result

The command is MIA in production.

### Environment

Observable on the live site and on Github

**Comment by pieh** [comment] 2020-07-17 09:54
Hi @stufinn, missing code blocks on gatsbyjs.org seems to happen when javascript is disabled (or I guess if there are some runtime errors and javascript crashes). Can you try force refreshing that page and see if that fixes missing code blocks?

In any case, this problem doesn't seem to be speciffic to any documentation page in particular and seems like problem with code blocks not being SSR friendly (they don't seem to be written to html)

**Comment by LekoArts** [comment] 2020-07-17 10:35
This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/25680

> code blocks not being SSR friendly (they don't seem to be written to html)

Yep, there are lazy-loaded and thus not SSR'd

**Comment by stufinn** [comment] 2020-07-17 22:18
@pieh Yes that did the trick. Good to know about that, thanks!  Should I close the issue since it's a duplicate?

**Comment by Escavalier** [comment] 2020-07-20 13:12
As the problem is solved, I will be closing the issue

**Closed by Escavalier** 2020-07-20 13:12 UTC
Labels: topic: website, type: bug
