### ISSUE TITLE
Importing bulma css causes postcss-custom-properties error

### ISSUE THREAD

**Issue by rchaubey** [gatsbyjs/gatsby#2354] opened 2017-10-05 20:07 UTC
All I did was installed bulma

`yarn add bulma`

Then imported bulma css

`import "bulma/css/bulma.css"`

And this is the error I get

![image](https://user-images.githubusercontent.com/26508855/31249938-de34e736-aa36-11e7-93b9-fc63402ccf8c.png)

**Comment by jquense** [comment] 2017-10-05 23:19
does bulma rely on css properties?

**Comment by rchaubey** [comment] 2017-10-06 07:17
@jquense Yes, they do use custom css properties. Is that a problem ?

**Comment by jquense** [comment] 2017-10-06 12:58
No, just trying to understand the issue a bit. I think the problem is here that the default css setup adds a bunch of cssNext setup along with it, which isn't a great default..

**Comment by mikewesthad** [comment] 2017-10-13 21:34
I just ran into the same issue. I created a local copy of the gatsby postcss sass plugin and ripped out the postcss (since I don't need it).

**Comment by mbfisher** [comment] 2018-01-12 04:52
Posting my solution to this for others:

* Install `gatsby-plugin-sass` (see [here](https://github.com/gatsbyjs/gatsby/tree/master/examples/using-sass))
* Create `layouts/index.scss` (see [here](https://github.com/jgthms/bulma/issues/1190#issuecomment-356672849))
```sass
$variable-columns: false;
@import "~bulma/bulma";
```
* Import `index.scss` in `layouts/index.js`

**Comment by marz0** [comment] 2018-03-04 17:27
@mbfisher had to add one more step to get that to work:
* Add `"gatsby-plugin-sass"` to `plugins:` in `gatsby-config.js`

**Comment by KyleAMathews** [comment] 2018-09-08 04:17
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Closed by KyleAMathews** 2018-09-08 04:17 UTC
