### ISSUE TITLE
Can't query "childImageSharp" on MDX frontmatter files

### ISSUE THREAD

**Issue by pmarxbraun** [gatsbyjs/gatsby#21426] opened 2020-02-13 14:44 UTC
## Description

Hey there

I'm trying to query childImageSharp on my MDX's frontmatter _featuredImage_
Unfortunately QraphQL does not offer this option on my environment cf.screen

Btw it works with .md files :-/
I'm am doing something wrong but can't figure out what. Thanks for your help guys. 

![allMdx](https://user-images.githubusercontent.com/28112173/74445628-fd3d9380-4e76-11ea-8520-a11f03f020a1.png)

### Expected result

Query should return the image. 

### Actual result

```
ERROR #85909  GRAPHQL
Field "featuredImage" must not have a selection since type "String" has no subfields
```

### Environment

Config file is as follow : 

```
/**
 * Configure your Gatsby site with this file.
 *
 * See: https://www.gatsbyjs.org/docs/gatsby-config/
 */

module.exports = {
  siteMetadata: {
    title: `FEHR Group`,
    description: `Depuis 1960, FEHR Group complète vos chantiers : béton prêt à l’emploi (BPE), éléments en béton préfabriqué, prédalles, panneaux de bardage.`,
    url: `https://fehrgroup.com`,
    image: "../../FEHR-logotype-baseline.png",
    author: {
      name: "Philippe Braun",
      minibio: `
        This bio is shown at the bottom of each blog post. It supports
        <strong>custom HTML</strong> if you’re into that sort of thing.
      `,
    },
    lang: "fr",
    social: {
      youtube: "https://www.youtube.com/channel/UCqySuQyQi-W_UR6jvxs5hPg",
      facebook: "https://www.facebook.com/fehrgroupe/",
      instagram: "https://www.instagram.com/fehr_groupe/",
      linkedin: "https://fr.linkedin.com/company/fehr-groupe-sas",
      twitterUsername: "@fehrgroup",
    },
  },
  plugins: [
    `gatsby-plugin-react-helmet`,
    `gatsby-plugin-sharp`,
    `gatsby-transformer-sharp`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `pages`,
        path: `${__dirname}/src/pages/`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `src`,
        path: `${__dirname}/src/`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/img`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `emplois`,
        path: `${__dirname}/src/emplois`,
      },
    },
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `realisations`,
        path: `${__dirname}/src/pages/realisations`,
      },
    },
    // {
    //   resolve: `gatsby-source-filesystem`,
    //   options: {
    //     name: `realisations`,
    //     path: `${__dirname}/src/realisations`,
    //   },
    // },
    `gatsby-transformer-remark`,
    {
      resolve: `gatsby-plugin-mdx`,
      options: {
        defaultLayouts: {
          default: require.resolve("./src/components/Layout/LayoutFr.js"),
        },
      },
    },
  ],
}

```

MDX files

```
---
architecte: "Anne Demians"
title: "Black Swans"
seo_title: "Réalisation : Black Swans | FEHR Group"
description: "L ensemble immobilier « Black Swans » s’inscrit dans un projet de reconquête des friches portuaires initié par l’Eurométropole"
site: "Strasbourg"
template: "realTemplate"
path: "/realisations/black-swans"
featuredImage: ../img/aeroport_bale_mulhouse.jpg
---

import { Link } from "gatsby"
import SEO from "../../components/SEO/SEO"
import Hero from "../../components/Hero/Hero"
import Button from "../../components/Button/Button"
import MaxWidth from "../../components/Layout/MaxWidth"
import TwoCol from "../../components/Layout/TwoCol"
import { graphql } from "gatsby"
import Img from "gatsby-image"
import BlackSwansGallery from "../../components/ImageGallery/BlackSwansImageGallery"


<SEO title="Réalisation : Black Swans | FEHR Group" description="L ensemble immobilier « Black Swans » s’inscrit dans un projet de reconquête des friches portuaires initié par l’Eurométropole"></SEO>
<Hero
        title="Black Swans"
        backgroundHero={props.data.bs.childImageSharp.fluid}
      >
        <div style={{display:'inline-block',backgroundColor:'#fff',padding:'3vh 2vw',}}>
            <h2 style={{textTransform:'none',}}>Architecte : Anne Demians</h2>
            <h3 style={{textTransform:'none',}}>Ville : Strasbourg</h3>
            <p>Élément(s) : Précoffré Classique®</p>
            <Link to="/realisations">← Retour aux réalisations</Link>
        </div>
      </Hero>
<MaxWidth style={{marginTop:'5vh',marginBottom:'5vh'}}>
<TwoCol style={{ alignItems: "center",marginBottom : '10vh',marginTop : '10vh',}}> 
<div>
<h2>À propos de ce projet</h2>
<p>L’ensemble immobilier « Black Swans » s’inscrit dans un projet de reconquête des friches portuaires initié par l’Eurométropole.</p>
</div>
<Img fluid={props.data.bs.childImageSharp.fluid}/>
</TwoCol>

<BlackSwansGallery />

<div>
<h2>Chiffres clés :</h2>
<p>10 000m2 Précoffré® Classiques</p>
<p>L’ensemble immobilier « Black Swans » s’inscrit dans un projet de reconquête des friches portuaires initié par l’Eurométropole. Il s’agit d’un ensemble immobilier multiprogrammes de 30 000 m² exceptionnel par son image architecturale et sa volumétrie.</p>
<p>La disposition de l’ensemble immobilier et sa hauteur (logements à 50 mètres de hauteur) ménage des vues d’exception vers la cathédrale et vers la forêt noire en Allemagne.</p>
<h3>Pour en savoir plus :</h3>
<ul>
<li><a target="_blank" href="http://www.icade.fr/references/logement/black-swans-strasbourg-67">http://www.icade.fr/references/logement/black-swans-strasbourg-67</a></li>
<li><a target="_blank" href="https://www.annedemians.com/projets/black-swans/">https://www.annedemians.com/projets/black-swans/</a></li>
<li><a target="_blank" href="https://www.lemoniteur.fr/article/les-tours-black-swans-se-dressent-avec-homogeneite-dans-le-ciel-de-strasbourg-34919220">https://www.lemoniteur.fr/article/les-tours-black-swans-se-dressent-avec-homogeneite-dans-le-ciel-de-strasbourg-34919220</a></li>
</ul>
</div>

<Button buttonURL="/realisations" buttonString="← nos autres réalisations" />
</MaxWidth>

```

  System:
    OS: macOS Mojave 10.14.6
    CPU: (4) x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.6.0 - ~/.nvm/versions/node/v11.6.0/bin/node
    npm: 6.13.7 - ~/.nvm/versions/node/v11.6.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.100
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.17.11 => 2.17.11 
    gatsby-background-image: ^0.9.12 => 0.9.12 
    gatsby-image: ^2.2.34 => 2.2.34 
    gatsby-plugin-mdx: ^1.0.71 => 1.0.71 
    gatsby-plugin-react-helmet: ^3.1.15 => 3.1.15 
    gatsby-plugin-sharp: ^2.3.4 => 2.3.4 
    gatsby-source-filesystem: ^2.1.39 => 2.1.39 
    gatsby-transformer-remark: ^2.6.50 => 2.6.50 
    gatsby-transformer-sharp: ^2.3.6 => 2.3.6 
  npmGlobalPackages:
    gatsby-cli: 2.8.29

**Comment by Js-Brecht** [comment] 2020-02-13 19:05
You would need to tell Gatsby to transform that field into an image, which it looks like `gatsby-plugin-mdx` doesn't do automatically.  Please see [this guide](https://www.gatsbyjs.org/docs/working-with-images-in-markdown/#using-the-mdx-plugin) and let me know if it helps.

I'm not entirely sure if you'll be able to use markdown page metadata that way with `gatsby-plugin-mdx` the same way you can with `gatsby-transformer-remark`.  An alternative might be to do like they did [here](https://github.com/gatsbyjs/gatsby/issues/18271#issuecomment-547097964).

**Comment by pmarxbraun** [comment] 2020-02-13 23:05
@Js-Brecht well this is the guide I've followed. Moreover [it clearly states ](https://www.gatsbyjs.org/docs/working-with-images-in-markdown/#featured-images-with-frontmatter-metadata) `Note: This can be done similarly using MDX as well. Instead of the markdownRemark nodes in GraphQL, Mdx can be swapped in and should work.`

They clearly states that it's working on the other link you gave me:

```
Here is the current GraphQL behaviour when specifying a key in frontmatter if the image at ../assets/cms/hero-image.png exists:

heroImage: ../assets/cms/hero-image.png → works fine
```
His query is as followed : 

```
mdx(fileAbsolutePath: { eq: $fileAbsolutePath }) {
      frontmatter {
        heroImageOne {
          childImageSharp {
            fluid {
              ...GatsbyImageSharpFluid
            }
          }
        }
```

**Comment by Js-Brecht** [comment] 2020-02-13 23:16
Oh, interesting 🤔.  Can you share a minimal reproduction, to make it a bit easier to troubleshoot?

**Comment by pmarxbraun** [comment] 2020-02-13 23:49
I've tried on a new starter and it's works like a charm. 
It seems lots of my plugins are outdated on the project where the bug occurs

```
Package                     Current   Wanted   Latest 
bootstrap                     4.3.1    4.4.1    4.4.1  
gatsby                      2.17.11  2.19.17  2.19.17 
gatsby-background-image      0.9.12   0.9.14   0.9.14  
gatsby-image                 2.2.34   2.2.41   2.2.41  
gatsby-plugin-mdx            1.0.71   1.0.72   1.0.72  
gatsby-plugin-react-helmet   3.1.15   3.1.22   3.1.22  
gatsby-plugin-sharp           2.3.4    2.4.5    2.4.5  
gatsby-source-filesystem     2.1.39   2.1.48   2.1.48  
gatsby-transformer-remark    2.6.50   2.6.51   2.6.51  
gatsby-transformer-sharp      2.3.6   2.3.14   2.3.14  
react                       16.11.0  16.12.0  16.12.0 
react-dom                   16.11.0  16.12.0  16.12.0  
```

I should come from here, doesn't it ?

**Comment by Js-Brecht** [comment] 2020-02-14 00:12
Can you share the starter that works?  I want to compare with what I have, because I am able to replicate the problem, using the latest versions.  I can fix it by creating a custom type definition that indicates that `featuredImage` is a file, but I want to see how yours works without that.

I'm rather interested in how it works without explicitly defining image fields, because I'm not seeing anything in the code for `gatsby-plugin-mdx` that would transform page metadata into images, without using something like `gatsby-remark-images`.  Perhaps there's something I'm not seeing that scans that metadata for file paths 🤷‍♂.  Regardless, I'm sure the difference between your working sample, and my copy (that doesn't do automatic transformations) might hold the key to making it work without defining custom types.

By the way, this worked for transforming field `featuredImage` into an `ImageSharp` type:
```js
// gatsby-node.js
exports.createSchemaCustomization = ({ actions }) => {
    const { createTypes } = actions
  
    createTypes(`
        type Mdx implements Node {
            frontmatter: MdxFrontmatter!
        }
        type MdxFrontmatter {
            featuredImage: File @fileByRelativePath
        }
    `)
}
```

**Comment by pmarxbraun** [comment] 2020-02-14 00:43
Done, let me know if you find something :-)
I'll try updating my plugins tomorrow.

**Comment by Js-Brecht** [comment] 2020-02-14 00:52
I had a typo in my image name, which explains why I had to coerce the type to get it to be `ImageSharp` 🤣.  After I fixed that, it picked it up automatically, like you say.  Even when I used the same version numbers you have.  So, something else interesting is going on.  

With the typo: same error as you... because that image doesn't exist, so I am trying to query subfields for field that is just a string.
Without the type: works without any problems.

**Comment by Js-Brecht** [comment] 2020-02-14 03:38
How much of your original repo can you share?  Using the source from your original repo, can you reduce it to just the mdx, the image, and whatever parts of the configuration & the React tree that are required?

**Comment by pmarxbraun** [comment] 2020-02-14 08:26
@Js-Brecht just shared a simplified project :-)

**Comment by LekoArts** [comment] 2020-02-14 09:40
Thank you for opening this!

I also can't reproduce your problem. Gatsby will pick up the path to the image as a `File` node regardless of whether it's Markdown or MDX. You have to make sure though that it's a valid path or that you don't have any typos. Since this isn't an issue with Gatsby but with your project I'll close this one. But feel free to comment here to get your specific problem figured out. Rebuilding parts of your site might give you a hint where your error lies.

We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2020-02-14 09:40 UTC
Labels: type: question or discussion

**Comment by Js-Brecht** [comment] 2020-02-14 17:09
@pmarxbraun Okay, I figured it out.

The issue is the file path.  It must be relative to the `mdx` file that is using it, since it is Node that is resolving it, not the browser.

Here is your tree
```
.
└── src
    ├── img
    │   └── aeroport_bale_mulhouse-2.jpg
    └── pages
        └── realisations
            └── aeroport-bale-mulhouse.mdx
```

So, the path for the image should be `../../img/aeroport_bale_mulhouse-2.jpg`, instead of `../img/aeroport_bale_mulhouse-2.jpg`.

One easy way to see if your paths are good, is to just `cd` into that directory, and see if you can `ls` the same file path that is in the source:
```shell
cd src/pages/realisations
ls ../img/aeroport_bale_mulhouse-2.jpg
## File not found error

ls ../../img/aeroport_bale_mulhouse-2.jpg
## File stats
```

**Comment by pmarxbraun** [comment] 2020-02-17 15:21
Thank you so much Jeremy !
I knew it was a dumb thing like that...

Philippe Braun
p.marinbraun@gmail.com
