### ISSUE TITLE
UTM Params break pages with window.gtag calls on Gatsby V5

### ISSUE THREAD

**Issue by avodynamics** [gatsbyjs/gatsby#37108] opened 2022-11-27 01:24 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

In Gatsby V5 I'm encountering an issue where url parameters are causing the page to load for an instant any then go to a white screen, and the console throws [React error #423](https://reactjs.org/docs/error-decoder.html?invariant=423). 

I think this has to do with the gtag Google Analytics function, but I'm not sure. The issue is not present without the query parameters.

This only happens on one type of page, not the landing pages.
All pages have the following code in the root element.
```
<Fragment>
      {/* <Script src={`https://www.googletagmanager.com/gtag/js?id=G-XGT7DV90KN`} strategy="off-main-thread" forward={[`gtag`]} /> */}
      <Script src={`https://www.googletagmanager.com/gtag/js?id=G-XGT7DV90KN`} forward={[`gtag`]} />
      <Script
        id="gtag-config"
        // strategy="off-main-thread"
        dangerouslySetInnerHTML={{
          __html: `window.dataLayer = window.dataLayer || [];
          window.gtag = function gtag(){ window.dataLayer.push(arguments);}
          gtag('js', new Date()); 
          gtag('config', 'G-XGT7DV90KN', { send_page_view: false });`,
        }}
      />
      <div>{children}</div>
    </Fragment>
```

So the home page experiences no issues.
But the product page breaks, and it must be something to do with this line.

```
typeof window !== "undefined" &&
    window.gtag("event", "view_item", {
      currency: "USD",
      value: productVariant.price,
      items: [
        {
          // item_id: productVariant.sku,
          item_id: productVariant.shopifyId.split("/").pop(),
          item_name: `${productData.title} | ${productVariant.title}`,
          item_brand: "BoxCave Furniture",
          item_category: productData.collections[0].title,
          item_variant: productVariant.title,
        },
      ],
    });
```

I can't set up a minimal reproduction tonight, but I'll try to if no one has any insight by the time that I can get that together.

### Reproduction Link

N/A

### Steps to Reproduce

1. visit https://boxcavefurniture.com/shop/Furniture/gamebox/?utm_source=test&utm_medium=test&utm_campaign=test&utm_content=test
...

### Expected Result

The page to load, and stay loaded

### Actual Result

The page loads for a second, and then closes.

### Environment

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (24) x64 AMD Ryzen 9 5900X 12-Core Processor            
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 3.10.2
  Browsers:
    Edge: Spartan (44.22621.819.0), Chromium (107.0.1418.56)
  npmPackages:
    gatsby: ^5.0.1 => 5.0.1 
    gatsby-plugin-facebook-pixel: ^1.0.8 => 1.0.8 
    gatsby-plugin-google-gtag: ^5.0.0 => 5.0.0 
    gatsby-plugin-image: ^3.0.0 => 3.0.0 
    gatsby-plugin-mailchimp: ^5.2.2 => 5.2.2 
    gatsby-plugin-manifest: ^5.0.0 => 5.0.0 
    gatsby-plugin-netlify: ^5.0.1 => 5.0.1 
    gatsby-plugin-offline: ^6.0.0 => 6.0.0 
    gatsby-plugin-react-helmet: ^6.0.0 => 6.0.0 
    gatsby-plugin-sharp: ^5.0.0 => 5.0.0 
    gatsby-plugin-sitemap: ^6.0.0 => 6.0.0 
    gatsby-plugin-styled-components: ^6.0.0 => 6.0.0 
    gatsby-source-datocms: ^4.0.5 => 4.0.5 
    gatsby-source-filesystem: ^5.0.0 => 5.0.0 
    gatsby-source-shopify: ^6.0.0 => 6.10.2 
    gatsby-source-yotpo: ^3.0.5 => 3.0.5 
    gatsby-transformer-sharp: ^5.0.0 => 5.0.0 
  npmGlobalPackages:
    gatsby-cli: 4.14.0
```

**Comment by LekoArts** [comment] 2022-11-29 07:35
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2022-12-07 13:00
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2022-12-07 13:00 UTC
Labels: type: bug, status: needs reproduction, topic: plugins-analytics
