### ISSUE TITLE
gatsby-source-graphql - threw an error while running the sourceNodes lifecycle

### ISSUE THREAD

**Issue by hammund0** [gatsbyjs/gatsby#25513] opened 2020-07-03 21:10 UTC
Hello,

I have integrated the gatsby-source-graphql plugin to do queries with the CommerceTools GraphQL endpoint.

This was working perfectly fine until I had cleared node_modules, ran gatsby clean and ran npm install.

package-lock.json and package.json are exactly the same as when they were working.

I am using this setup, as below.

`"gatsby-source-graphql": "^2.5.0",`

```
gatsby-config.js

    {
      resolve: `gatsby-source-graphql`,
      options: {
        typeName: `LIFT`,
        fieldName: `lift`,
        url: `https://api.europe-west1.gcp.commercetools.com/[project-key]/graphql`,
        headers: async () => {
          const token = await getAuthorizationToken();

          return {
            Authorization: `${token.token_type} ${token.access_token}`
          }
        },
        fetchOptions: {}
      },
    },
```

```
const getAuthorizationToken = async () => {
  const authClient = new SdkAuth({
    host: 'https://auth.europe-west1.gcp.commercetools.com',
    projectKey: '[project-key]',
    disableRefreshToken: false,
    credentials: {
      clientId: '###',
      clientSecret: ###',
    },
    scopes: ['manage_project:[project-key'],
    fetch,
  })

  return await authClient.clientCredentialsFlow();
};
```

I have had no issues with this integration thus far until now and the above code has been working fine.

When I now try to locally run gatsby develop or gatsby build we now get an error.

```
"gatsby-source-graphql" threw an error while running the sourceNodes lifecycle:

Schema must contain uniquely named types but contains multiple types named "Reference".

  Error: Schema must contain uniquely named types but contains multiple types named "Reference".
```

“lift” (the field name) is not being returned at all. (it used to be returned fine). What could be causing this issue please?

Thank you

**Comment by vladar** [comment] 2020-07-06 12:36
Can you please check which version of the plugin you actually use (in the `package-lock.json`)? Is it `gatsby-source-graphql@2.6.0`?

Also, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

[reproduction]: https://gatsby.dev/reproduction

**Comment by vladar** [comment] 2020-08-31 16:57
Hi. I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please mention me and I'll reopen. Thanks!

**Closed by vladar** 2020-08-31 16:57 UTC
Labels: topic: GraphQL, topic: data sourcing, type: bug
