### ISSUE TITLE
.cache\develop-static-entry.js: Cannot read property 'has' of undefined

### ISSUE THREAD

**Issue by DasdWaller** [gatsbyjs/gatsby#29218] opened 2021-01-26 22:09 UTC
OS: Windows 10
Node: 15 and 14 latest and various versions
Package manager: npm

This is my first time with Gatsby and this day try to play with but unfortunately it doesn't work after several try. I install the `my-blog-starter` as starter. I try to use different NodeJS versions, clean `package-lock.json`, delete `node_modules`, reinstall, try to update the packages and I do all suggestions I found on issues and on web. I can create a repo with the project for more infos, if you want.

I need to mention this problem I face it only with `develop` mode/script the other modes/scripts works fine.

```
ERROR #98123  WEBPACK

Generating development SSR bundle failed

...\blog\.cache\develop-static-entry.js: Cannot read property 'has' of undefined

File: .cache\develop-static-entry.js

not finished Building development bundle
```

package.json
```
{
  "scripts": {
    "build": "gatsby build",
    "develop": "gatsby develop",
    "format": "prettier --write \"**/*.{js,jsx,ts,tsx,json,md}\"",
    "start": "npm run develop",
    "serve": "gatsby serve",
    "clean": "gatsby clean",
    "test": "echo \"Write tests! -> https://gatsby.dev/unit-testing\" && exit 1"
  },
  "dependencies": {
    "gatsby": "^2.26.1",
    "gatsby-image": "^2.5.0",
    "gatsby-plugin-google-fonts": "^1.0.1",
    "gatsby-plugin-manifest": "^2.6.1",
    "gatsby-plugin-offline": "^3.4.0",
    "gatsby-plugin-react-helmet": "^3.4.0",
    "gatsby-plugin-sharp": "^2.8.0",
    "gatsby-remark-images": "^3.8.0",
    "gatsby-source-filesystem": "^2.5.0",
    "gatsby-transformer-sharp": "^2.6.0",
    "prop-types": "^15.7.2",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-helmet": "^6.1.0"
  },
  "devDependencies": {
    "prettier": "2.2.1"
  }
}
```

**Comment by ascorbic** [comment] 2021-01-28 10:33
Hi. Can you upgrade to the latest version of gatsby and check if it still occurs?

**Comment by DasdWaller** [comment] 2021-01-28 14:29
> Hi. Can you upgrade to the latest version of gatsby and check if it still occurs?

@ascorbic thanks for the response.  Gatsby is latest version.
```
Gatsby CLI version: 2.18.0
Gatsby version: 2.31.1
```

node: v14.15.4
npm: 6.14.10

I try with `gatsby develop` and  `npx gatsby develop` too, the other modes works perfectly.

```
Generating development SSR bundle failed

C:\[Dev]\blog\.cache\develop-static-entry.js: Cannot read property 'has' of undefined

File: .cache\develop-static-entry.js

not finished Building development bundle - 1.189s
```

===============================

node: v15.6.0
npm: v7.4.0

Test with `gatsby develop`
```
ERROR #98123  WEBPACK

Generating development SSR bundle failed

C:\[Dev]\blog\.cache\develop-static-entry.js: Cannot read property 'has' of undefined

File: .cache\develop-static-entry.js

not finished Building development bundle - 1.136s
```

Test with `npx gatsby develop` but different error here.
```
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\Username\\AppData\\Roaming\\nvm\\v15.6.0\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'gatsby',
0 verbose cli   'develop'
0 verbose cli ]
1 info using npm@7.4.0
2 info using node@v15.6.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:C:\Users\Username\AppData\Roaming\nvm\v15.6.0\node_modules\npm\npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 5ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:C:\[Dev]\blog\.npmrc Completed in 2ms
9 timing config:load:project Completed in 3ms
10 timing config:load:file:C:\Users\Username\.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:C:\Program Files\nodejs\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 16ms
19 verbose npm-session 857e7f5ab78ea2fc
20 timing npm:load Completed in 33ms
21 timing command:exec Completed in 16056ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (C:\Users\Username\AppData\Roaming\nvm\v15.6.0\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:379:20)
22 verbose stack     at maybeClose (node:internal/child_process:1065:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:296:5)
23 verbose pkgid blog@1.0.0
24 verbose cwd C:\[Dev]\blog
25 verbose Windows_NT 10.0.19042
26 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Username\\AppData\\Roaming\\nvm\\v15.6.0\\node_modules\\npm\\bin\\npm-cli.js" "exec" "--" "gatsby" "develop"
27 verbose node v15.6.0
28 verbose npm  v7.4.0
29 error code 1
30 error path C:\[Dev]\blog
31 error command failed
32 error command C:\Windows\system32\cmd.exe /d /s /c gatsby develop
33 verbose exit 1
```

**Comment by OddBlueDog** [comment] 2021-02-23 00:40
Did you manage to fix this?

**Comment by moustafa-in3** [comment] 2021-03-08 18:00
@DasdWaller Do you still have this issue?

**Comment by LekoArts** [comment] 2021-03-15 08:45
Hi!

I still can't reproduce this with the steps you gave for now I'll close this. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-03-15 08:45 UTC
Labels: status: awaiting author response, type: bug

**Comment by holmesmr** [comment] 2021-05-01 15:10
I was able to reproduce this independently by accident - it appears the causal factor is the project path containing `[]`.

**Comment by emanuelstrom** [comment] 2023-07-08 11:40
> I was able to reproduce this independently by accident - it appears the causal factor is the project path containing `[]`. Logs indicate this is what causes it for the reporter as [#29218 (comment)](https://github.com/gatsbyjs/gatsby/issues/29218#issuecomment-769097427) indicates the project path also contains these. I guess it's likely the path is being interpreted as a glob.


YES! Haha! Thank you!!
