### ISSUE TITLE
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

### ISSUE THREAD

**Issue by SurajVerma** [gatsbyjs/gatsby#25093] opened 2020-06-18 12:11 UTC
## Description
I am trying to setup a Gatsby site using Gatsby blog theme starter, everything works as expected, till the time I run `gatsby develop`

### Steps to reproduce

Run below commands, which i picked from [Gatsby official documentation](https://www.gatsbyjs.org/tutorial/using-a-theme/)

`gatsby new my-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme`
`cd my-blog`
`gatsby develop`

here is the link to my git repo : [my-blog](https://github.com/SurajVerma/my-blog)

### Expected result
As per the documentation, I am supposed to get below page:

![starter-blog-theme-default](https://user-images.githubusercontent.com/5441349/85018193-66694680-b18a-11ea-8d5b-88abcac7fb11.png)

### Actual result

But I am getting this:

![image](https://user-images.githubusercontent.com/5441349/85018440-cfe95500-b18a-11ea-8e4e-3988f183b04c.png)

### Environment

```
  System:
    OS: Linux 5.4 Ubuntu 20.04 LTS (Focal Fossa)
    CPU: (4) x64 Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
    Shell: 5.0.16 - /bin/bash
  Binaries:
    Node: 14.3.0 - ~/.nvm/versions/node/v14.3.0/bin/node
    npm: 6.14.5 - ~/.nvm/versions/node/v14.3.0/bin/npm
  Browsers:
    Chrome: 83.0.4103.106
    Firefox: 77.0.1
  npmPackages:
    gatsby: ^2.23.3 => 2.23.3 
    gatsby-theme-blog: ^1.6.42 => 1.6.42 
  npmGlobalPackages:
    gatsby-cli: 2.12.46
```

**Comment by jbuget** [comment] 2020-06-18 12:22
I had the same this morning. The problem was that I did not have `yarn` installed (only NPM).

I think the problem is due to a problem with the two dependencies `theme-ui` and a second one that I can not remember the name.

**Comment by laurieontech** [comment] 2020-06-18 15:27
Thanks for opening this issue! At the moment, I'm unable to reproduce the error you're seeing. You noted a link to your specific repo, but I don't believe it's linked. Would you be able to add that?

**Comment by SurajVerma** [comment] 2020-06-18 15:37
@jbuget : I too didn't have `yarn` installed.
@laurieontech: Sorry, updated now.

**Comment by laurieontech** [comment] 2020-06-18 17:20
Wonderful, was able to reproduce. npm and yarn should both work, so I'll dig into this.

**Comment by laurieontech** [comment] 2020-06-18 17:36
To add context, the underlying bug is that there are two different `theme-ui` versions in the current gatsby monorepo. For some odd reason, npm resolves to the bad one and yarn resolves to the good one. I'll get this addressed in another PR now.

**Comment by laurieontech** [comment] 2020-06-18 20:35
Unfortunately the fix did not solve the problem. So continuing to work on this unmet peer dependency issue (only in npm).

**Comment by SurajVerma** [comment] 2020-06-19 03:16
As @jbuget pointed out, I tried yarn and it is working if I am doing following:

`gatsby new my-blog https://github.com/gatsbyjs/gatsby-starter-blog-theme`
`cd my-blog`
`yarn`
`gatsby develop`

**Comment by laurieontech** [comment] 2020-06-19 12:19
Understood. This is definitely only an issue with npm.

**Closed** 2020-06-19 14:24 UTC
Labels: status: confirmed, status: inkteam assigned, topic: themes, type: bug
