### ISSUE TITLE
Documentation: For schema customization extensions / resolver controls

### ISSUE THREAD

**Issue by tony** [gatsbyjs/gatsby#30070] opened 2021-03-07 13:56 UTC
## Summary

It's difficult to find demonstration examples for [Schema Customization](https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization/)

Some recommended topics to cover from [Actions page](https://www.gatsbyjs.com/docs/reference/config-files/actions/#createTypes)

- `@infer`
- `@dontInfer`
- `@dateformat`
- `@link`
- `@fileByRelativePath`
- `@proxy`

### Motivation

I have a field with a `relativeUrl` lookup to a `Filee` is stored, I'm using `portraitSrc: File @link(by: "relativePath")` and while it shows up fine, the typescript typing is wrong. It's pointing to a `File` and not a `FileNode`.  It's not clear how to use these.

## Steps to resolve this issue

I think these are complex and blurred together, they need examples to help clarify difference

For instance, in the case of [`@fileByRelativePath`](https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization/#extensions-and-directives), instead of saying: 

> `fileByRelativePath` is similar to link but will resolve relative paths when linking to File nodes, and `proxy` is helpful when dealing with data that contains field names with characters that are invalid in GraphQL.

Provide an example, and it's not clear (at least to me) what this means.

It may be clearer to refer to them by `@dateformat`, `@proxy` and `@link` instead of `dateformat`, `proxy` and `link` , unless they're being referred to in a functional usage in JS.  If I see `fileByRelativePath` instead of `@fileByRelativePath`, it introduces ambiguity/mystery (in my opinion), is it an undocumented variable or undocumented method? 

### Draft the doc

I'm not familiar enough on this area yet. 

- [ ] Write the doc, following the format listed in these resources:
  - [Overview on contributing to documentation](https://www.gatsbyjs.com/contributing/docs-contributions/)
  - [Docs Templates](https://www.gatsbyjs.com/contributing/docs-templates/)
  - [Example of a similar article]()

### Open a pull request

- [ ] Open a pull request with your work including the words "closes #[this issue's number]" in the pull request description

**Comment by LekoArts** [comment] 2021-03-08 09:26
Hi, thanks for the issue! I'll close this as a duplicate of https://github.com/gatsbyjs/gatsby/issues/14228 -- please copy over your text there. Thanks!

**Closed by LekoArts** 2021-03-08 09:26 UTC
Labels: type: documentation

**Comment by tony** [comment] 2021-03-08 19:35
Thank you @LekoArts!
