### ISSUE TITLE
Gatsby rewrites hrefs?

### ISSUE THREAD

**Issue by aterreno** [gatsbyjs/gatsby#12355] opened 2019-03-06 15:47 UTC
Hi there, 
we are unable to write a simple link using ```<a href="">``` and passing query params, I do wonder if Gatsby rewrites for some reason the links strimming out the params. 

We can't use <Link> from Gatsby since these are external links. 

I looked in previous issues and I can't find much. Is this an expected behaviour? 

Thanks

**Comment by DSchau** [comment] 2019-03-06 15:48
@aterreno what exactly does your `a` look like? Could you provide a [reproduction](https://gatsby.dev/reproduction)?

We shouldn't be doing anything here to "re-write" any of your content, we rely on React serializing to HTML for much of this.

**Comment by aterreno** [comment] 2019-03-06 16:00
@DSchau I'll try to reproduce with a reproduction, the issue is similar to this https://github.com/gatsbyjs/gatsby/issues/9815 but in this case the answer was to use a <GatsbyLink> which would not work for us.

**Comment by aterreno** [comment] 2019-03-06 16:24
Reproduced! This is crazy! https://github.com/aterreno/gatsby-bug-repro

Try the app in local, it should work if you pass query params, then try the deployed version

https://stupefied-fermat-ce7a45.netlify.com/?channel=test

I wonder if it's possible that netlify strips for no reason the query params. Otherwise it must be the gatsby build... 

<img width="525" alt="screenshot 2019-03-06 16 24 00" src="https://user-images.githubusercontent.com/76042/53896639-50368600-402c-11e9-9074-4855ddd2804a.png">
<img width="604" alt="screenshot 2019-03-06 16 23 55" src="https://user-images.githubusercontent.com/76042/53896641-50cf1c80-402c-11e9-96c6-76fe63ada50b.png">

**Comment by aterreno** [comment] 2019-03-06 16:29
One more finding: 100% not netlify fault, steps to reproduce: 

```yarn build```
```cd public```
```python -m SimpleHTTPServer 3000``` 

<img width="434" alt="screenshot 2019-03-06 16 29 20" src="https://user-images.githubusercontent.com/76042/53896969-0ef2a600-402d-11e9-88e5-46935c31c867.png">

**Comment by DSchau** [comment] 2019-03-06 16:33
To be clear, which link is manifesting the issue? Or are all of them?

Generally - GatsbyLink should not be used for _external_ links. It's for internal links to other pages within your application. If you open your console, you'll see warnings like "A page not found for <route>" because you've used an external link.

As far as the search params, I _think_ that's an issue with hydration. The search param isn't known at build time, so you will likely want to tap into `componentDidMount` to grab the search params and update them statefully.

Does that make sense?

**Comment by aterreno** [comment] 2019-03-06 16:50
@DSchau spot on, thanks a lot, it's now fixed and working.

**Comment by DSchau** [comment] 2019-03-06 17:51
Woo hoo!

Glad to hear it :) Closing this out.

Thanks for using Gatsby 💜

**Closed by DSchau** 2019-03-06 17:51 UTC
Labels: type: question or discussion

**Comment by Restuta** [comment] 2019-03-29 09:18
This is very confusing issue, I faced the same one and it was not obvious at all to use componentDidMount for that :(
