### ISSUE TITLE
[gatsby-plugin-mdx] Provide TypeScript typings 

### ISSUE THREAD

**Issue by nisarhassan12** [gatsbyjs/gatsby#17819] opened 2019-09-23 11:57 UTC
## Description

I have gatsby-plugin-mdx installed but I'm getting this. It would be great if you were to add a type for atleast MDXRenderer :smile: .
![image](https://user-images.githubusercontent.com/46004116/65423520-ab8e6100-de22-11e9-9fab-5b819d5c74de.png)

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

### Expected result

What should happen?

### Actual result

What happened.

### Environment

  System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (4) x64 Intel(R) Core(TM) i5-2520M CPU @ 2.50GHz
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 12.10.0 - /usr/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.10.3 - /usr/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 77.0.3865.90
    Firefox: 69.0
  npmPackages:
    gatsby: ^2.15.6 => 2.15.6 
    gatsby-plugin-html-attributes: ^1.0.5 => 1.0.5 
    gatsby-plugin-mdx: ^1.0.43 => 1.0.43 
    gatsby-plugin-react-helmet: ^3.1.6 => 3.1.6 
    gatsby-plugin-typescript: ^2.1.6 => 2.1.6 
    gatsby-source-filesystem: ^2.1.26 => 2.1.26 
  npmGlobalPackages:
    gatsby-cli: 2.7.49

Run `gatsby info --clipboard` in your project directory and paste the output here.

**Comment by LekoArts** [comment] 2019-09-23 12:15
Duplicate of https://github.com/gatsbyjs/gatsby/issues/15924

**Closed by LekoArts** 2019-09-23 12:15 UTC
