### ISSUE TITLE
"Inappropriate ioctl for device" on gatsby serve

### ISSUE THREAD

**Issue by hansifer** [gatsbyjs/gatsby#5122] opened 2018-04-25 01:12 UTC
## Description

Gatsby fails out of the box following the instructions here: https://www.gatsbyjs.org/docs/

### Steps to reproduce

npm install --global gatsby-cli
gatsby new gatsby-site
cd gatsby-site
gatsby build
gatsby serve

### Expected result

site should be accessible at http://localhost:9000

### Actual result

gatsby serve generates the following error and site is not accessible at http://localhost:9000:
```
{ Error: Command failed: xsel --clipboard --input
xsel: Can't open display: (null)
: Inappropriate ioctl for device


    at Promise.all.then.arr (/home/hansifer/sites/blog/node_modules/clipboardy/node_modules/execa/index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:182:7)
  code: 1,
  killed: false,
  stdout: '',
  stderr: 'xsel: Can\'t open display: (null)\n: Inappropriate ioctl for device\n',
  failed: true,
  signal: null,
  cmd: 'xsel --clipboard --input',
  timedOut: false }
```

### Environment

* Gatsby version (`npm list gatsby`): 1.9.250
* gatsby-cli version (`gatsby --version`): 1.1.50
* Node.js version: v9.11.1
* Operating System: Ubuntu 16

### File contents (if changed):

`gatsby-config.js`: not changed
`package.json`: not changed
`gatsby-node.js`: not changed
`gatsby-browser.js`: not changed
`gatsby-ssr.js`: not changed

**Comment by m-allanson** [comment] 2018-04-26 12:11
`gatsby serve` is [a small wrapper](https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby/src/commands/serve.js) around [`serve`](https://github.com/zeit/serve).

Can you replicate this issue using just `serve`?

This should do it:

```shell
node_modules/.bin/serve -p 9000 ./public
```

You could also try installing a newer version of `serve` to see if that does the same thing. [Gatsby is on `^6.4.0`](https://github.com/gatsbyjs/gatsby/blob/3b647d707cb6e35be6e963c309ef12f9b8e11fc3/packages/gatsby/package.json#L100) at the moment, and the latest is `6.5.6`.

**Comment by Bitaxa666** [comment] 2018-04-27 07:56
Hi. I am having the same error when I start serve in docker container. Step to reproduce: 
1.RUN yarn global add serve
2.CMD serve -s build -> Build is successful
And when I create docker image ...serve is started? but with err message - 
{ Error: Command failed: xsel --clipboard --input
xsel: Can't open display: (null)
: Inappropriate ioctl for device ...
So, maybe need to close or disconnect xsel?

**Comment by hansifer** [comment] 2018-04-27 19:52
Hi, thanks for responding.

Yes, I get the same error when running serve directly.

`node_modules/serve/package.json` shows version 6.5.6

**Comment by hansifer** [comment] 2018-04-27 19:59
also: when I do `npm list gatsby` to get the version I get:
```
gatsby-starter-default@1.0.0 /home/hansifer/sites/gatsby-site
└── UNMET DEPENDENCY gatsby@1.9.250

npm ERR! missing: gatsby@1.9.250, required by gatsby-starter-default@1.0.0
```
also, I have since upgraded gatsby-cli to v1.1.51

**Comment by KyleAMathews** [comment] 2018-09-08 05:16
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Closed by KyleAMathews** 2018-09-08 05:16 UTC
Labels: status: help wanted, type: bug :beetle:
