### ISSUE TITLE
Gatsby is not recognized as internal or external command 

### ISSUE THREAD

**Issue by abhishekkacham507** [gatsbyjs/gatsby#32202] opened 2021-07-02 08:07 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

I have installed Gatsby on my office system (windows) by default windows command prompt as admin but after installation of Gatsby CLI I am facing the following issue. Please help me to solve this.

I have also executed the other command also npm -g ls --depth=0

gatsby-cli@3.8.0
`-- windows-build-tools@5.2.2

npm ERR! peer dep missing: graphql@^14.4.1, required by express-graphql@0.9.0

When I am executing this command "npm config get perfix -g"

output is "undefined"

One doubt I would like to use Gatsby with my WordPress to implement a new website. So for I need to install the Gatsby CLI.
 

### Reproduction Link

https://github.com

### Steps to Reproduce

NA

### Expected Result

NA

### Actual Result

NA

### Environment

```shell
Windows 10
nodejs v14.17.1
npm 6.14.13
```

**Comment by wardpeet** [comment] 2021-07-02 08:11
Could you let us know what install command you ran?

**Comment by abhishekkacham507** [comment] 2021-07-02 08:52
npm install -g gatsby-cli

When I am running the below command in normal CMD I mean not as administrator 

 gatsby -v

╔════════════════════════════════════════════════════════════════════════╗
║                                                                        ║
║   Gatsby collects anonymous usage analytics                            ║
║   to help improve Gatsby for all users.                                ║
║                                                                        ║
║   If you'd like to opt-out, you can use `gatsby telemetry --disable`   ║
║   To learn more, checkout https://gatsby.dev/telemetry                 ║
║                                                                        ║
╚════════════════════════════════════════════════════════════════════════╝
Gatsby CLI version: 3.8.0

**Comment by LekoArts** [comment] 2021-07-06 05:59
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2021-07-19 09:52
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or open a new issue with a reproduction. Thanks!

**Closed by LekoArts** 2021-07-19 09:52 UTC
Labels: status: needs reproduction, type: bug
