### ISSUE TITLE
gatsby navigate() function can not navigate url which include "%"

### ISSUE THREAD

**Issue by NeilShang** [gatsbyjs/gatsby#34998] opened 2022-03-01 09:57 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

gatsby navigate() function can not navigate url which include "%"

import { navigate } from 'gatsby-link';

navigate("/demo/will have 2%")
navigate("/demo/will have 2%25")
this two will through decode error

framework-bde73dc2d2b00752c7c6.js:2 Uncaught URIError: URI malformed
    at decodeURIComponent (<anonymous>)
and I do some debug,found navigate decodeURIComponent twice

### Reproduction Link

private url can not give you guys,but this is an normal error

### Steps to Reproduce

1.import { navigate } from 'gatsby-link';

2.use navigate("/demo/will have 2%")

3.use navigate("/demo/will have 2%25")
 wil through Uncaught URIError: URI malformed 

### Expected Result

can redirect to "/demo/will have 2%" page

### Actual Result

through error and block navigate

### Environment

```shell
System:
    OS: macOS 12.2.1
    CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 8.1.4 - /usr/local/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 98.0.4758.109
    Firefox: 97.0.1
    Safari: 15.3
  npmGlobalPackages:
    gatsby-cli: 2.12.117
```

**Comment by LekoArts** [comment] 2022-03-01 10:26
This is probably a duplicate of https://github.com/gatsbyjs/gatsby/issues/34797

**Comment by NeilShang** [comment] 2022-03-01 11:36
This is  duplicate of https://github.com/gatsbyjs/gatsby/issues/34797

**Closed** 2022-03-08 13:41 UTC
Labels: type: bug
