### ISSUE TITLE
301 redirect with trailing slash instead of 302

### ISSUE THREAD

**Issue by keithpacana** [gatsbyjs/gatsby#20299] opened 2019-12-26 09:02 UTC
So I'm currently hosting gatsby with AWS S3 and everytime i go to https://mywebsite.com/page1 it sends a 302 redirect to https://mywebsite.com/page1/. However, I want this to be a 301 instead of a 302 for SEO purposes. Is there any way to do that without having to use createRedirect for every page of my website and redirect it with a trailing slash?

**Comment by tcope25** [comment] 2019-12-30 16:22
AWS S3 uses a 302 by design. Make sure your `rel=canonical` is in place and you should be good. Google will treat a 302 as a 301 over time.

You can also look into Lambda@Edge and handle your redirects there.

**Comment by sidharthachatterjee** [comment] 2020-01-10 15:12
Yup. @tcope25 is correct. 

Closing this as it isn't a Gatsby issue _per se_. Thanks!

**Closed by sidharthachatterjee** 2020-01-10 15:12 UTC
