### ISSUE TITLE
MaxListenersExceededWarning errors with gatsby-plugin-image StaticImage with placeholder

### ISSUE THREAD

**Issue by jonohewitt** [gatsbyjs/gatsby#34795] opened 2022-02-11 14:46 UTC
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/gatsbyjs/gatsby/issues
- [X] This issue is not a question, feature request, RFC, or anything other than a bug report directly related to Gatsby. Please post those things in GitHub Discussions: https://github.com/gatsbyjs/gatsby/discussions

### Description

A console error occurs on develop and build when using `StaticImage` from `gatsby-plugin-image`  with a `placeholder` attribute, [e.g:](https://github.com/jonohewitt/gatsby-image-bug-repro/blob/b4a5ef2c8ee3aa3a07b762e652468a2021f314a4/src/components/componentWithStaticImage.js#L9)

```jsx
<StaticImage src="../images/photo-1.jpg" alt="" placeholder="blurred" />
```

---

* Using `gatsby develop` or `gatsby build`:

```
ERROR

(node:15194) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [PassThrough]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
```

* Using `node --trace-warnings node_modules/.bin/gatsby develop`:

```
ERROR 

(node:15473) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 end listeners added to [PassThrough]. Use emitter.setMaxListeners() to increase limit
    at _addListener (node:events:595:17)
    at PassThrough.addListener (node:events:617:10)
    at PassThrough.Readable.on (node:internal/streams/readable:899:35)
    at eos (node:internal/streams/end-of-stream:169:10)
    at pipe (node:internal/streams/pipeline:348:3)
    at pipelineImpl (node:internal/streams/pipeline:293:9)
    at pipeline (node:internal/streams/pipeline:146:10)
    at probeStream (/Users/hewitt/path/to/project/node_modules/probe-image-size/stream.js:63:8)
    at get_image_size (/Users/hewitt/path/to/project/node_modules/probe-image-size/index.js:13:12)
    at getImageSizeAsync (/Users/hewitt/path/to/project/node_modules/gatsby-plugin-sharp/index.js:63:28)
    at getImageMetadata (/Users/hewitt/path/to/project/node_modules/gatsby-plugin-sharp/image-data.js:33:39)
    at generateImageData (/Users/hewitt/path/to/project/node_modules/gatsby-plugin-sharp/image-data.js:123:26)
    at /Users/hewitt/path/to/project/node_modules/gatsby-plugin-image/dist/node-apis/image-processing.js:255:42
    at step (/Users/hewitt/path/to/project/node_modules/gatsby-plugin-image/dist/node-apis/image-processing.js:33:23)
    at Object.next (/Users/hewitt/path/to/project/node_modules/gatsby-plugin-image/dist/node-apis/image-processing.js:14:53)
    at /Users/hewitt/path/to/project/node_modules/gatsby-plugin-image/dist/node-apis/image-processing.js:8:71
```

Nothing seems to be visibly affected by the error - the build continues successfully afterwards.  

### Reproduction Link

https://github.com/jonohewitt/gatsby-image-bug-repro

### Steps to Reproduce

1. Install the reproduction project
2. Run `gatsby develop` to see basic error
3. Run `node --trace-warnings node_modules/.bin/gatsby develop` to see verbose error

### Expected Result

No error

### Actual Result

Error

### Environment

```shell
System:
    OS: macOS 12.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 17.4.0 - /usr/local/bin/node
    Yarn: 1.22.17 - ~/.yarn/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
  Languages:
    Python: 2.7.18 - /usr/bin/python
  Browsers:
    Chrome: 98.0.4758.80
    Safari: 15.2
  npmPackages:
    gatsby: ^4.7.1 => 4.7.1 
    gatsby-plugin-image: ^2.7.0 => 2.7.0 
    gatsby-plugin-sharp: ^4.7.0 => 4.7.0 
    gatsby-source-filesystem: ^4.7.0 => 4.7.0
```

**Comment by Notaduck** [comment] 2022-02-15 07:57
I can confirm that I am seing the exact same issue here, however the `placeholder` attribute is being set in the `graphql` query in my case.

**Comment by dipankarmaikap** [comment] 2022-02-15 09:42
```js
$ node --trace-warnings node_modules/.bin/gatsby develop
E:\web-development\github\bucketlist-gatsby\node_modules\.bin\gatsby:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
←[90m    at Object.compileFunction (node:vm:352:18)←[39m
←[90m    at wrapSafe (node:internal/modules/cjs/loader:1026:15)←[39m
←[90m    at Module._compile (node:internal/modules/cjs/loader:1061:27)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:975:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)←[39m
←[90m    at node:internal/main/run_main_module:17:47←[39m

Node.js v17.5.0
```
This is what I'm getting.

**Comment by jonohewitt** [comment] 2022-02-15 13:41
@dipankarmaikap That seems a bit different - are you only getting that error when using `StaticImage` with a `placeholder`? It might not be related to this issue.

**Comment by Notaduck** [comment] 2022-02-16 08:35
> ```js
> $ node --trace-warnings node_modules/.bin/gatsby develop
> E:\web-development\github\projectname-gatsby\node_modules\.bin\gatsby:2
> basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
>           ^^^^^^^
> 
> SyntaxError: missing ) after argument list
> ←[90m    at Object.compileFunction (node:vm:352:18)←[39m
> ←[90m    at wrapSafe (node:internal/modules/cjs/loader:1026:15)←[39m
> ←[90m    at Module._compile (node:internal/modules/cjs/loader:1061:27)←[39m
> ←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)←[39m
> ←[90m    at Module.load (node:internal/modules/cjs/loader:975:32)←[39m
> ←[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)←[39m
> ←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)←[39m
> ←[90m    at node:internal/main/run_main_module:17:47←[39m
> 
> Node.js v17.5.0
> ```
> 
> This is what I'm getting.

Looks like a syntax error, is this based on @jonohewitt's repository?

**Comment by hendra-go** [comment] 2022-02-27 12:45
> > ```js
> > $ node --trace-warnings node_modules/.bin/gatsby develop
> > E:\web-development\github\projectname-gatsby\node_modules\.bin\gatsby:2
> > basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
> >           ^^^^^^^
> > 
> > SyntaxError: missing ) after argument list
> > ←[90m    at Object.compileFunction (node:vm:352:18)←[39m
> > ←[90m    at wrapSafe (node:internal/modules/cjs/loader:1026:15)←[39m
> > ←[90m    at Module._compile (node:internal/modules/cjs/loader:1061:27)←[39m
> > ←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)←[39m
> > ←[90m    at Module.load (node:internal/modules/cjs/loader:975:32)←[39m
> > ←[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)←[39m
> > ←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)←[39m
> > ←[90m    at node:internal/main/run_main_module:17:47←[39m
> > 
> > Node.js v17.5.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is what I'm getting.
> 
> Looks like a syntax error, is this based on @jonohewitt's repository? This doesn't seem to be related to this issue.

Definitely not related to this issue.

Hello @dipankarmaikap, i guess you try to run `node --trace-warnings node_modules/.bin/gatsby develop` on Windows right? then run `node --trace-warnings .\node_modules\gatsby\dist\bin\gatsby.js develop` should do the trick, note: i use Windows 11 and PowerShell.

Regarding this issue, yes i also face same problem, i think the problem is not because `placeholder`, my project does not contain any `placeholder` in `StaticImage` but still face this error, most likely because of `at probeStream (/Users/hewitt/path/to/project/node_modules/probe-image-size/stream.js:63:8)`

**Comment by hendra-go** [comment] 2022-02-27 14:10
Ah, i guess i am right 😄 the problem is in `probe-image-size/stream.js` and it is already fixed in [https://github.com/nodeca/probe-image-size/commit/a6da059439614c399b79c09ea1d406a3e4300b27](https://github.com/nodeca/probe-image-size/commit/a6da059439614c399b79c09ea1d406a3e4300b27)

so `probe-image-size` in `gatsby-plugin-sharp` and `gatsby-transformer-sharp` should be updated to the latest version.

@jonohewitt: Please try my suggestion above and if it solve this bug, probably you should create a pull request because you are the one that found this bug first 👍

**Comment by jon-sully** [comment] 2022-02-28 02:01
> so `probe-image-size` in `gatsby-plugin-sharp` and `gatsby-transformer-sharp` should be updated to the latest version.

When this will happen, who knows 😛 they're currently locked to v6!

That said, following this mindset and forcing an override by adding

```json
"resolutions": {
  "probe-image-size": "^7.0.0"
},
```

Fixed the issue for me completely 👍. `probe-image-size` doesn't seem to follow semver to 6 -> 7 didn't appear to have any breaking changes based on their Changelog. Thanks @hendra-go!

**Comment by hendra-go** [comment] 2022-02-28 05:42
After investigating a little further `gatsby-transformer-sharp` use `probe-image-size` Synchronously so it won't cause `MaxListenersExceededWarning`, but in`gatsby-plugin-sharp`, `probe-image-size` used Asynchronously.

If Gatsby team has a spesific reason to lock `probe-image-size` to v6, it think
```
"resolutions": {
  "gatsby-plugin-sharp/probe-image-size": "^7.0.0"
},
```
should be safer

**Comment by danielmacuare** [comment] 2022-02-28 08:46
Thanks folks, I'm seeing the same issue described by @jonohewitt and I get the exact same error when running `node --trace-warnings node_modules/.bin/gatsby develop`

 @hendra-go I'm pretty new to Gatsby or any Front end stack and I'd like to understand where to put the snippet above to set the probe-image-size and workaround this issue. I've been trying adding it to the gatbsy config with no success. 

Do you have an example I can use as a reference?

This is my current `gatsby-config`

```
module.exports = {
    siteMetadata: {
        title: "test.tech",
    },
    plugins: [
        `gatsby-plugin-styled-components`,
        `gatsby-plugin-image`,
        `gatsby-plugin-sharp`,
        `gatsby-transformer-sharp`,
        {
            resolve: `gatsby-source-filesystem`,
            options: {
                name: `images`,
                path: `${__dirname}/src/assets/images/`,
            },
        },
    ],
}
```

Thanks for your help in advance.

**Comment by hendra-go** [comment] 2022-02-28 09:38
Hello @danielmacuare 

```
"resolutions": {
  "gatsby-plugin-sharp/probe-image-size": "^7.0.0"
},
```
The code above should be inserted to your project's `package.json` it is a Yarn's [Selective dependency resolutions](https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/) so you should use Yarn instead npm

**Comment by danielmacuare** [comment] 2022-02-28 10:45
Thanks, that helps. I will look into it.

**Comment by jonohewitt** [comment] 2022-03-01 22:17
Hi @hendra-go, 

> i think the problem is not because placeholder, my project does not contain any placeholder in StaticImage but still face this error

That's interesting - for me if I remove the `placeholder` attribute in my reproduction repo then the error doesn't show up. Weird! 

I can also confirm though that adding:

```json
"resolutions": {
    "gatsby-plugin-sharp/probe-image-size": "^7.0.0"
  }
```
fixes my issue too - great job working it out! I'll try to put in a simple PR and see what the maintainers say about upgrading or if there were any reasons to keep it locked to `^6.0.0`. Thanks very much!

**Closed** 2022-03-07 10:00 UTC
Labels: type: bug, topic: media

**Comment by IsNotASword** [comment] 2023-03-15 20:31
has anoyone fixed this?

i can't build my project on vercel because of this

i've tried @hendra-go solution, but i can't use yarn on vercel!

**Comment by JimLynchCodes** [comment] 2023-04-20 15:40
I'm seeing this error now as well...  I basically took an old project that was built with node v12 and a really old version of gatsby... I just deleted the node_modules and tried to install. There are interesting cases when you do things like this where `npm install` will fail but `yarn install` succeeds... well sort of. Now my build does eventually complete locally, but my ci build on Netlify doesn't... 🤔
