### ISSUE TITLE
CLI doesn't work for anything other than help listing

### ISSUE THREAD

**Issue by prasannavl** [gatsbyjs/gatsby#125] opened 2016-02-12 19:46 UTC
CLI doesn't seem to work since it references an invalid executable, atleast on Windows. 

```
PS > gatsby new blog
module.js:341
    throw err;
    ^

Error: Cannot find module 'C:\Users\PVL\AppData\Roaming\npm\node_modules\gatsby\bin\cli-new'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:139:18)
    at node.js:999:3
 
```
And the npm modules folder is here:

```
PS > ls C:\Users\PVL\AppData\Roaming\npm\node_modules\gatsby\bin\


    Directory: C:\Users\PVL\AppData\Roaming\npm\node_modules\gatsby\bin


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       12-02-2016     21:12            744 build.coffee
-a----       12-02-2016     21:12             74 cli.js
-a----       12-02-2016     21:12            742 develop.coffee
-a----       12-02-2016     21:12            100 gatsby-build.js
-a----       12-02-2016     21:12            102 gatsby-develop.js
-a----       12-02-2016     21:12             98 gatsby-new.js
-a----       12-02-2016     21:12            379 index.coffee
-a----       12-02-2016     21:12            665 new.coffee
-a----       12-02-2016     21:12             22 published.js
```

I surmised its called as gatsby, instead of cli. So, this is a bug. 

**Temporary workaround**: Copying the three `gatsby-*` files as `cli-*` seems to do the trick until its fixed.

**Comment by KyleAMathews** [comment] 2016-02-18 01:02
Closing as duplicate of #80

**Closed by KyleAMathews** 2016-02-18 01:02 UTC
