### ISSUE TITLE
[discussion] Simple & Fun WYSIWYG

### ISSUE THREAD

**Issue by mickeyreiss-visor** [gatsbyjs/gatsby#2565] opened 2017-10-21 00:44 UTC
I'm curious to hear how people are setting up Gatsby, in order to allow non-technical team members to contribute content updates.

One idea I've had was to pull content (e.g. markdown) from a separate repo on Github and then trigger a deploy of my Gatsby codebase each time the content repo receives a new commit that passes CI.

Another idea would be to edit with wordpress and then pull that into Gatsby. But that seems kind of janky...

How are other people solving this problem? Would it make sense to build a new Gatsby plugin that makes WYSIWYG content editing simple and fun, but also safe and fast?

**Comment by KyleAMathews** [comment] 2017-10-21 00:47
Yeah good options right now are:

* WordPress
* Contentful
* Netlify CMS (e.g. @AustinGreen's starter — https://github.com/AustinGreen/gatsby-netlify-cms-boilerplate) p.s. Austin — you should add that to https://www.gatsbyjs.org/docs/gatsby-starters/)

**Comment by KyleAMathews** [comment] 2017-10-21 01:07
Working on upgrading the Drupal plugin as well actually as I'm speaking on it tomorrow at Badcamp https://2017.badcamp.net/session/coding-development/beginner/headless-drupal-building-blazing-fast-websites-reactgatsbyjs

**Comment by AustinGreen** [comment] 2017-10-21 02:00
@KyleAMathews just opened a PR. Could be a good idea for a blog post tutorial as well!

**Comment by roberpoldo** [comment] 2017-10-21 07:54
I have tried `gatsby-source-wordpress` but the problem is the need to have a re-build every-time the wordpress content is updated. This approach is only working with github and netlify continous deployment no? I would dream to have the gatsby public folder fetching automatically the wordpress back-end. I'm curious how people are handling the relation between client-wordpress-gatsby…

**Comment by shannonbux** [comment] 2017-10-23 19:48
Hey guys! I'm Shannon, and I've recently started helping to improve Gatsby guides/tutorials. Would any of you be willing to chat with me for 15 mins about your experiences building with Gatsby and ideas for improvements / roadblocks you've run into? I think this discussion raises some really interesting questions and it would be valuable to get your thoughts. If you'd be willing, just sign up for a time here: [https://calendly.com/shannon-soper](https://calendly.com/shannon-soper) or feel free to email me at shannon.soper@gmail.com!

**Comment by brandonmp** [comment] 2017-11-01 04:08
Contentful with a webhook that pings netlify on new content has been working like a charm for me.

**Comment by jeffnappi** [comment] 2018-01-30 16:19
Would be very cool if someone took up the effort to build something like [cloudcannon.com](https://cloudcannon.com/) for Gatsby. Free startup idea ;)

**Comment by brandonmikeska** [comment] 2018-02-04 06:38
Would a combination of gatsbyjs and simply.io be good? I really want the team to see what their content looks like while they time. Thoughts?

**Comment by brandonmikeska** [comment] 2018-02-04 06:39
Simpla** won’t let me edit on the phone :(. https://www.simplajs.org

**Comment by KyleAMathews** [comment] 2018-09-08 04:10
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Closed by KyleAMathews** 2018-09-08 04:10 UTC
