### ISSUE TITLE
How do I specify the GraphQL schema for siteMetadata?

### ISSUE THREAD

**Issue by JohJonker** [gatsbyjs/gatsby#24366] opened 2020-05-22 19:17 UTC
## Summary
I know we can [customise the GraphQL schema](https://www.gatsbyjs.org/docs/schema-customization/#creating-type-definitions) to specify nullable fields. However, how do I do specify type and make fields nullable for the `siteMetadata` object inside **gatsby-config.js**? I want to query these values in Components without having to worry if they are null or not.

## Relevant information

I am creating a theme and specifying defaults in siteMetadata. Some of these defaults are null. When I query those fields in my theme components, and the site using the theme hasn't provided a value to that field, graphql bombs out because it doesn't know that field is nullable.

**Comment by LekoArts** [comment] 2020-05-25 09:58
This feels like a duplicate of https://github.com/gatsbyjs/gatsby/issues/24427 so I'll close this one.

**Closed by LekoArts** 2020-05-25 09:58 UTC
Labels: status: triage needed, type: question or discussion
