### ISSUE TITLE
Renaming a folder while gatsby develop is running breaks the process

### ISSUE THREAD

**Issue by AdityaAnand1** [gatsbyjs/gatsby#26817] opened 2020-09-08 08:25 UTC
Run gatsby develop

Rename `test1/index.html` to `test2/index.html` and gatsby develop gets stuck forever and needs to be restarted.

Solution: If it doesn't find a file while running, it should ignore it and compile the other files.

**Comment by LekoArts** [comment] 2020-09-08 08:33
Please follow the issue template, without it filled out we can't really help you. Thanks!

```
## Description

Describe the issue that you're seeing.

### Steps to reproduce

Clear steps describing how to reproduce the issue. Please please please link to a demo project if possible, this makes your issue _much_ easier to diagnose (seriously).

How to Make a Minimal Reproduction: https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/

### Expected result

What should happen?

### Actual result

What happened.

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.
```

**Comment by LekoArts** [comment] 2020-09-18 07:58
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-09-18 07:58 UTC
Labels: status: needs reproduction, type: bug
