### ISSUE TITLE
Error: WebpackError: ReferenceError: Super constructor may only be called once

### ISSUE THREAD

**Issue by kumaresan-subramani** [gatsbyjs/gatsby#24909] opened 2020-06-10 15:33 UTC
HI Team,

Below is my gatsby project, when i take build it throws below error

```

failed Building static HTML for pages - 6.815s

 ERROR #95313

Building static HTML failed for path "/16.3.27/"

See our docs page for more info on this error: https://gatsby.dev/debug-html


  5 |
  6 |   return self;
> 7 | }
    | ^
  8 |
  9 | module.exports = _assertThisInitialized;


  Error: WebpackError: ReferenceError: Super constructor may only be called once
  - build-html.js:107 doBuildPages
    [ej2-release-notes]/[gatsby]/dist/commands/build-html.js:107:24


[15:49:36] Finished 'ci-release-publish' after 3.62 min
```

**Comment by kumaresan-subramani** [comment] 2020-06-11 04:37
https://stackoverflow.com/questions/57300607/gatsby-query-was-left-in-the-compiled-code

**Comment by kumaresan-subramani** [comment] 2020-06-11 05:50
https://stackoverflow.com/questions/57300607/gatsby-query-was-left-in-the-compiled-code

**Comment by kumaresan-subramani** [comment] 2020-06-11 06:57
my repository

[ej2-release-notes.zip](https://github.com/gatsbyjs/gatsby/files/4763091/ej2-release-notes.zip)

## repo steps 

- downlabove sample

- give `npm i`

- then run `gulp ci-release-publish`

you will see reported error

**Comment by LekoArts** [comment] 2020-06-16 08:18
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2020-06-23 10:58
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-06-23 10:58 UTC
Labels: status: needs reproduction
