### ISSUE TITLE
Gatsby local plugin no longer found when upgrading to 2.17.8

### ISSUE THREAD

**Issue by trickydisco78** [gatsbyjs/gatsby#20064] opened 2019-12-11 11:04 UTC
## Description
Upgrading gatsby from   "gatsby": "^2.15.14", > 2.17.8 (to fix some service worker issues)

I'm now getting the following error

Couldn't find the "gatsby-plugin-top-layout" plugin declared in "/Users/xxx/source/xxxx/gatsby-config.js".

Tried looking for a local plugin in /Users/xxxxx/source/xxxx/plugins/gatsby-plugin-top-layout.

This folder exists in the project?
![image](https://user-images.githubusercontent.com/3627429/70616309-0f484f00-1c06-11ea-98b2-404f92172625.png)

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```
  System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 71.0
    Safari: 13.0.3
  npmPackages:
    gatsby: ^2.15.14 => 2.17.7 
    gatsby-image: ^2.2.18 => 2.2.19 
    gatsby-plugin-eslint: ^2.0.5 => 2.0.5 
    gatsby-plugin-manifest: ^2.2.16 => 2.2.16 
    gatsby-plugin-material-ui: ^2.1.6 => 2.1.6 
    gatsby-plugin-offline: ^3.0.26 => 3.0.26 
    gatsby-plugin-react-helmet: ^3.1.7 => 3.1.7 
    gatsby-plugin-react-svg: ^2.1.2 => 2.1.2 
    gatsby-plugin-sharp: ^2.2.22 => 2.2.22 
    gatsby-plugin-styled-components: ^3.1.5 => 3.1.5 
    gatsby-plugin-typescript: ^2.1.8 => 2.1.8 
    gatsby-source-filesystem: ^2.1.22 => 2.1.22 
    gatsby-source-graphql: ^2.1.14 => 2.1.14 
    gatsby-transformer-sharp: ^2.2.14 => 2.2.14 
  npmGlobalPackages:
    gatsby-cli: 2.7.53
```

**Comment by jamessimone** [comment] 2019-12-11 22:03
There was a breaking change made several versions ago to local plugins - you now HAVE to have an "index.js" file in your local plugin, even if it's totally empty. Hope this helps!

**Comment by vladar** [comment] 2019-12-12 17:02
Thanks for the report! But looks like it is a duplicate of https://github.com/gatsbyjs/gatsby/issues/19150. Feel free to re-open (or mention me to re-open) if it is a different issue.

**Closed by vladar** 2019-12-12 17:02 UTC
