### ISSUE TITLE
globbing with sass

### ISSUE THREAD

**Issue by rudietuesdays** [gatsbyjs/gatsby#14305] opened 2019-05-24 20:09 UTC
# Description

My build is failing when trying to specify an importer for allowing for globbing sass files. This happens whether I try to use the importer in `gatsby-config.js` or `gatsby-node.js`.

### Steps to reproduce - `gatsby-config.js`
```
const globImporter = require('node-sass-glob-importer')

module.exports = {
  plugins: [
    {
      resolve: 'gatsby-plugin-sass',
      options: {
        importer: globImporter(),
      },
    },
  ]
}
```

### Expected result

Successfully compile globbed scss files.

### Actual result

```
Module build failed (from ./node_modules/sass-loader/lib/loader.js):

'use strict';
^
      Invalid CSS after "'": expected 1 selector or at-rule, was "'use strict';"
```

### Steps to reproduce - `gatsby-node.js` 
I also tried overriding the webpack settings and modifying the webpack config. For this option, I removed the importer option from `gatsby-plugin-sass`.

```
const globImporter = require('node-sass-glob-importer')
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

exports.onCreateWebpackConfig = ({
  stage,
  rules,
  loaders,
  plugins,
  actions,
  getConfig
}) => {
  actions.replaceWebpackConfig({
    resolve: {
      modules: [path.resolve(__dirname, "src"), "node_modules"],
    },
    module: {
      rules: [
        {
          test:/\.(s*)css$/,
          resolve: {
            extensions: ['.scss', '.sass'],
          },
          use: [
            'style-loader!css-loader',
            {
              loader: MiniCssExtractPlugin.loader(),
              options: {
                importer: globImporter(),
              }
            },
            {
              loader: 'sass-loader',
              options: {
                importer: globImporter(),
              }
            },
          ],
        },
      ],
    },
    plugins: [
      new MiniCssExtractPlugin({
        // Options similar to the same options in webpackOptions.output
        // both options are optional
        filename: isDevelopment ? '[name].css' : '[name].[hash].css',
        chunkFilename: isDevelopment ? '[id].css' : '[id].[hash].css'
      }),
    ]
  })
}
```

### Expected result

Successfully compile globbed scss files.

### Actual result
```
Module build failed (from ./node_modules/gatsby-plugin-netlify-cms/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

@import 'vars/*';
^
      File to import not found or unreadable: vars/*.
```

### Environment

```
System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.10.0 - ~/.asdf/installs/nodejs/8.10.0/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 5.6.0 - ~/.asdf/installs/nodejs/8.10.0/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 66.0.3
    Safari: 12.1
  npmPackages:
    gatsby: ^2.1.34 => 2.7.1 
    gatsby-image: ^2.0.23 => 2.1.0 
    gatsby-plugin-netlify: ^2.0.6 => 2.0.17 
    gatsby-plugin-netlify-cms: ^4.0.0 => 4.0.1 
    gatsby-plugin-purgecss: ^3.1.0 => 3.1.1 
    gatsby-plugin-react-helmet: ^3.0.4 => 3.0.12 
    gatsby-plugin-sass: ^2.0.7 => 2.0.11 
    gatsby-plugin-sharp: ^2.0.15 => 2.1.0 
    gatsby-remark-copy-linked-files: ^2.0.7 => 2.0.12 
    gatsby-remark-images: ^3.0.1 => 3.0.12 
    gatsby-remark-relative-images: ^0.2.1 => 0.2.2 
    gatsby-source-filesystem: ^2.0.26 => 2.0.37 
    gatsby-transformer-remark: ^2.3.4 => 2.3.12 
    gatsby-transformer-sharp: ^2.1.9 => 2.1.19 
  npmGlobalPackages:
    gatsby-cli: 2.5.14
```

**Comment by jonniebigodes** [comment] 2019-05-24 20:35
@rudietuesdays can you share a reproduction following these [steps](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) so that it can be looked at  in more detail?

**Comment by rudietuesdays** [comment] 2019-05-28 14:02
@jonniebigodes reproduction is here: https://github.com/rudietuesdays/bug-repro

Thanks for taking a look!

**Comment by jonniebigodes** [comment] 2019-05-29 18:21
@rudietuesdays sorry for the wait. But i've been a bit under the weather. I'm going to document the steps i took to check your issue and the results.

- Cloned your repository code.
- Installed the dependencies.
- I checked the documentation on that package and the approaches used.
- Without 0 configuration i ran `gatsby develop` or `gatsy  build && gatsby serve` yes the error exists.
- Changed the `gatsby-config.js` to the following:
```javascript
const globImporter = require('node-sass-glob-importer');
module.exports = {
  /* Your site config here */
  plugins: [
    {
      resolve:`gatsby-plugin-sass`,
      options:{
        importer: globImporter()
      }
    }
  ]
}
```
- Re issued `gatsby develop` with the following result:

![rudie_tuesdays_1](https://user-images.githubusercontent.com/22988955/58580653-852a3180-8245-11e9-9bb7-85130cc7c315.png)

- Applied the same to methodology to a production build and it yelded the same result.
- Opening up `http://localhost:8000` or `http://localhost:9000` as it's shown below yelds the following: 

![rudie_tuesdays_2](https://user-images.githubusercontent.com/22988955/58580910-1d281b00-8246-11e9-9818-eebf272d8de9.png)

No build errors no nothing so far. I saw that you have a couple of plugins extra plugins in your repository, so what i'm going to do is to expand the testing to allow it's inclusion, namely, going to to create a couple of markdown files with some images and some styling and see if the problem pops up.  Do you mind waiting just a bit longer?

**Comment by rudietuesdays** [comment] 2019-05-30 16:03
@jonniebigodes thank you! I appreciate that. When I use the config you posted above, that's when I get the error
```
Module build failed (from ./node_modules/gatsby-plugin-netlify-cms/node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/lib/loader.js):

'use strict';
^
      Invalid CSS after "'": expected 1 selector or at-rule, was "'use strict';"
```

**Comment by jonniebigodes** [comment] 2019-05-31 00:17
@rudietuesdays like i said on my previous comment i expanded the testing case. I'm going to enumerate the steps i took and my findings.
- Updated the packages to reflect yours, as it seems that you have netlify-cms added and with that some markdown. Now the contents of the file looks like:
```json
"dependencies": {
    "gatsby": "^2.7.3",
    "gatsby-image": "^2.1.2",
    "gatsby-plugin-netlify": "^2.0.17",
    "gatsby-plugin-netlify-cms": "^4.0.1",
    "gatsby-plugin-netlify-cms-paths": "^1.2.1",
    "gatsby-plugin-sass": "^2.0.7",
    "gatsby-plugin-sharp": "^2.1.2",
    "gatsby-remark-copy-linked-files": "^2.0.13",
    "gatsby-remark-images": "^3.0.14",
    "gatsby-remark-prismjs": "^3.2.9",
    "gatsby-remark-relative-images": "^0.2.2",
    "gatsby-remark-responsive-iframe": "^2.1.1",
    "gatsby-source-filesystem": "^2.0.37",
    "gatsby-transformer-remark": "^2.3.12",
    "gatsby-transformer-sharp": "^2.1.20",
    "lodash": "^4.17.5",
    "lodash-webpack-plugin": "^0.11.4",
    "netlify-cms": "^2.9.1",
    "node-sass": "^4.11.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },
  "devDependencies": {
    "mini-css-extract-plugin": "^0.6.0",
    "node-sass-glob-importer": "^5.2.0",
    "prettier": "^1.17.1"
  },
```

- Updated `gatsby-config.js` to the following:
```javascript
const globImporter = require('node-sass-glob-importer');
module.exports = {
  /* Your site config here */
  plugins: [
    {
      resolve:`gatsby-source-filesystem`,
      options:{
        path:`${__dirname}/static/assets`,
        name:`assets`
      }
    },
    {
      resolve:`gatsby-source-filesystem`,
      options:{
        path:`${__dirname}/content/posts`,
        name:`posts`
      }
    },
    {
      resolve: `gatsby-transformer-remark`,
      options: {
        plugins: [
          `gatsby-remark-relative-images`,
          /* {
            resolve: `gatsby-plugin-netlify-cms-paths`,
            options: {
              cmsConfig: `/static/admin/config.yml`,
            },
          }, */
          {
            resolve: `gatsby-remark-images`,
            options: {
              maxWidth: 1500,
            },
          },
          {
            resolve: `gatsby-remark-responsive-iframe`,
            options: {
              wrapperStyle: `margin-bottom: 1.0725rem`,
            },
          },
          {
            resolve:`gatsby-remark-copy-linked-files`,
            options:{
              destinationDir:`${__dirname}/static`
            }
          },
        ],
      },
    },
    `gatsby-transformer-sharp`,
    `gatsby-plugin-sharp`,
    {
      resolve:`gatsby-plugin-sass`,
      options:{
        importer: globImporter()
      }
    },
    `gatsby-plugin-netlify-cms`,
    `gatsby-plugin-netlify` 
  ]
}
```
- Created a folder called `content`and inside some folders to house some dummy posts, which now my project folder structure looks like:
```sh
|root
  - |content
      - |posts
          - |banana
              index.md
              golem.jpg
              salty_egg.jpg
          - |hello-world
              index.md
              lining_up.jpg
          - |second-post
              index.md
              dia_de_los_muertos.jpg
     -|static
        -|admin
           config.yml
............
```
- `./static/admin/config.yml` is the file to emulate the netlify-cms locally and it has the following content:
```yml
backend:
  name: test-repo

media_folder: static/assets
public_folder: assets

collections:
  - name: posts
    label: Posts
    #folder: "src/pages/posts"
    folder: /content/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: description, label: Description }
      - { name: "tags", label: "Tags", widget: "list"}
      - { name: "featuredImage", label: "Featured Image", widget: "image" }
      - { name: body, label: Body, widget: markdown }
```
- Updated `./src/stylesheets/vars` with a couple of files, namely:
  - `_images.scss` with the following content:
  ```css
     .mainImage{
        margin:0.8rem;
        padding-bottom: 2rem;
     }
  ```
  - `_links.scss` with the following content:
    ```css
         .gatsbylink{
            text-decoration: none;
            color: #7396ce;
    
          }
         .gatsbylink:visited{
           color: #c7ccd6;
         }
     ```
- Modified `./stylesheets/vars/_test` with a new rule, now it looks like:
```css
body {
  background-color: #333333;
  color: #fff
}
.site-body{
  margin: 0 auto;
  max-width: 750px;
  padding: 1rem;

  display: flex;
  flex-direction: column;
  min-height: 100vh;

}
```
- Created `gatsby-node.js` with the following content:

 ```javascript

const path = require(`path`)
const { createFilePath } = require(`gatsby-source-filesystem`)
const { fmImagesToRelative } = require("gatsby-remark-relative-images")

exports.createPages = ({ graphql, actions }) => {
  const { createPage } = actions
  const blogPost = path.resolve("./src/templates/blog-post.js")

  return graphql(`
    {
      allMarkdownRemark(
        sort: { fields: [frontmatter___date], order: DESC }
        limit: 1000
      ) {
        edges {
          node {
            id
            fields {
              slug
            }
            frontmatter {
              title
            }
          }
        }
      }
    }
  `).then(result => {
    if (result.errors) {
      throw result.errors
    }
    const { data } = result
    const { allMarkdownRemark } = data
    const { edges } = allMarkdownRemark

    edges.forEach(post => {
      createPage({
        path:post.node.fields.slug,
        component:blogPost,
        context:{
          slug:post.node.fields.slug
        }
      })
    })
  })
}

exports.onCreateNode = ({ node, actions, getNode }) => {
  const { createNodeField } = actions
  fmImagesToRelative(node)
  if (node.internal.type === `MarkdownRemark`) {
    const value = createFilePath({ node, getNode })
    createNodeField({
      name: `slug`,
      node,
      value,
    })
  }
}
```
This is a basic boilerplate file to extract the data from markdown and generate the slugs for each page and also will handle the relative path of the images based on the markdown. To avoid a error that could popup, namely "Field "image" must not have a selection since type "String" has no subfields". 

- Created `./src/templates/blog-post.js` with the following content:
```javascript
import React from "react"
import { graphql } from "gatsby"
import Img from "gatsby-image"

const BlogTemplate = ({ data }) => {
  const { markdownRemark } = data
  return (
    <div>
      <Img
        className="mainImage"
        fluid={markdownRemark.frontmatter.featuredImage.childImageSharp.fluid}
      />
      <div className="site-body">
        <div className="grid grid-gutters grid-justifyCenter">
          <div className="grid-cell">
            <div className="blogTitle singleBlog">
              <h1>{markdownRemark.frontmatter.title}</h1>
              <h6>{markdownRemark.frontmatter.date}</h6>
            </div>
            <div
              className="blogContent"
              dangerouslySetInnerHTML={{ __html: markdownRemark.html }}
            />
            <hr />
          </div>
        </div>
      </div>
    </div>
  )
}
export default BlogTemplate

export const pageQuery = graphql`
  query BlogPostBySlug($slug: String!) {
    markdownRemark(fields: { slug: { eq: $slug } }) {
      id
      excerpt(pruneLength: 160)
      html
      frontmatter {
        title
        date(formatString: "MMMM DD,YYYY")
        featuredImage {
          childImageSharp {
            fluid(maxWidth: 1500) {
              ...GatsbyImageSharpFluid_noBase64
            }
          }
        }
      }
    }
  }
`
```
The rules `site-body` and `mainImage` will be imported from the files above that will globbed into the main css file.

- Finally i modified `./src/pages/index.js` to show me the links to the pages created from markdown, now it has the following content:
```javascript
import React from "react"
import { StaticQuery, graphql, Link } from "gatsby"
export default () => (
  <div className="site-body">
    <StaticQuery
      query={graphql`
        {
          allMarkdownRemark(
            sort: { fields: [frontmatter___date], order: DESC }
            limit: 1000
          ) {
            edges {
              node {
                id
                fields {
                  slug
                }
                frontmatter {
                  title
                }
              }
            }
          }
        }
      `}
      render={data => {
        const { allMarkdownRemark } = data
        const { edges } = allMarkdownRemark
        return (
          <ul>
            {edges.map(item => {
              return (
                <li key={`item_list_${item.node.id}`}>
                  <Link to={item.node.fields.slug} key={`post_link_${item.node.id}`} className="gatsbylink">
                    {item.node.frontmatter.title}
                  </Link>
                </li>
              )
            })}
          </ul>
        )
      }}
    />
  </div>
)

```
Key thing to take from this, as you can see the rules created in the files, namely `gatsbylink` and `site-body` will be injected. As you're already importing everything into the site in `gatsby-browser.js`

- Issued `gatsby develop` let it run and opened `http://localhost:8000` and i'm presented with the following:
![rudie_tuesdays_3](https://user-images.githubusercontent.com/22988955/58672105-51323780-833d-11e9-96ab-c70cc8dfd954.png)

- Stopped the server and issued the following `gatsby clean`, `gatsby build && gatsby serve`, this is going to purge the `.cache` and `public ` folder, issue a production build and serve it mocking a production environment and it yelded the following:
![rudie_tuesdays_4](https://user-images.githubusercontent.com/22988955/58672455-e84bbf00-833e-11e9-8911-cecc8bb6c138.png)

As you can see no errors are popping up, so with that in mind, it lead me to the following question:

Is this happening locally or when you issue a build on a cdn like for instance netlify?
If the case is on a cdn like netlify, based on personal experience out of the box netlify does not install the dev dependencies. Otherwise if it's local, then the issue might be somewhere else and it might need some further investigation.

Feel free to provide feedback

**Comment by rudietuesdays** [comment] 2019-06-03 19:31
@jonniebigodes thanks so much for your time on this! I dug into it more and it turns out this is the case of poor error reporting. The issue was gatsby-browser couldn't find one of my files -- once that problem was rectified, the error went away and the CSS was showing up. What would be really helpful here is a more specific error report in lieu of reporting that `'use strict'` was a problem, which I believe is referring back to the JS loader.

**Comment by jonniebigodes** [comment] 2019-06-03 20:19
@rudietuesdays no need to thank, glad that you managed to figured it out. Sorry that the issue was with the output of the error and with that being misleading, there are a couple of issues with some similar cases, but some improvements are being made to correct it and give people a more clear picture of what is exactly the issue when generating the build. If you don't mind i'm going to close this issue and i really hope that once you get your project up and running you can submit it to the showcase. Sounds good?

**Closed by jonniebigodes** 2019-06-03 20:19 UTC
Labels: status: awaiting author response, status: needs reproduction
