### ISSUE TITLE
On having spaces in the url , blank page is coming instead of the error page .

### ISSUE THREAD

**Issue by aryamanpuri** [gatsbyjs/gatsby#18952] opened 2019-10-23 18:18 UTC
Hi everyone , if any user have make space in the url , link used to go to the 404 page , or the space gets terminated out , the link is used to come up . 
While i was reading docs , same situation comes across me, and a blank page opens up instead of 404 page.
I know %20 in url means space.
We can have a check for url string .
I am interested in solving this bug .
Please give directions 
@KyleAMathews @pieh

**Comment by aryamanpuri** [comment] 2019-10-25 17:15
@sidharthachatterjee

**Comment by LekoArts** [comment] 2019-11-04 16:33
Thank you for opening this!

When creating pages it's your responsibility to convert spaces to other characters for the path, if a user types in spaces into the URL it's normal behavior that it fallbacks to 404 pages. If you don't want that behavior you could hook into reach-router. So this isn't a bug.

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Comment by aryamanpuri** [comment] 2019-11-04 17:50
@LekoArts  I totally agree with you. 
Thanks!

**Comment by zslabs** [comment] 2019-11-22 20:12
@LekoArts Could I get a bit more clarification on this part:

> if a user types in spaces into the URL it's normal behavior that it fallbacks to 404 pages

I'm seeing the behavior that spaces in URLs do NOT show the 404 page, but a blank one. Shouldn't Gatsby be handling 404 pages the same way? For example, if I visit https://www.gatsbyjs.org/test%20test I see the 404 page for a split-second and then it goes to a blank page.

**Comment by aryamanpuri** [comment] 2019-11-22 20:29
@zslabs Yes ur absoulutely write , this is a bug and should be solved .

**Comment by LekoArts** [comment] 2019-11-26 10:32
This is a duplicate of https://github.com/gatsbyjs/gatsby/issues/19462

**Closed by LekoArts** 2019-11-26 10:32 UTC
