### ISSUE TITLE
Gatsby doesn't report the location of the error

### ISSUE THREAD

**Issue by lumenwrites** [gatsbyjs/gatsby#27240] opened 2020-10-02 11:20 UTC
Hi! I often encounter this issue, gatsby tells me that there's an error, but doesn't say which component or mdx file is causing it, so the only way to find out is through the guesswork or trial and error.

For example, right now I'm getting the following logs telling me about the failed build:

<img width="1182" alt="Screenshot 2020-10-02 at 12 16 17" src="https://user-images.githubusercontent.com/4761235/94917785-1f892d80-04a9-11eb-8ae5-1241307b8521.png">

What makes things more difficult is that these are Netlify logs. The command `gatsby build` works just fine on my laptop, but after I push everything to github, netlify fails to build with this error.

Also, I'm pretty sure that the issue isn't with the graphql queries as the error says, but with one of the image links being broken inside of the frontmatter of one of my mdx posts. And the only way for me to track down the error is to delete most of the posts, and add them back one by one, until it breaks again. Very uninformative and misleading error.

Does anyone know a better way to diagnose issues like this?

Edit:

Yes, the issue was caused by the frontmatter in one of my posts linking to a missing post preview image. And so the graphql query requesting the information about the post couldn't find the image.

**Comment by LekoArts** [comment] 2020-10-05 08:11
Hi!

Could you please [provide a minimal reproduction][reproduction]? Normally it should print the file name and query.

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2020-10-19 08:27
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-10-19 08:27 UTC
Labels: status: needs reproduction, type: bug
