### ISSUE TITLE
Graphql page queries created in plugins are not working for gatsby-plugin-mdx

### ISSUE THREAD

**Issue by emanueleperuffo** [gatsbyjs/gatsby#24756] opened 2020-06-03 15:31 UTC
## Issue Description

I'm creating a remark plugin that creates a page query.

Mdx-loader correctly transpiles the AST, however, the page query is not evaluated by Gatsby.

I have no idea when and where Gatsby parses and evaluates page queries so I couldn't inspect this issue myself.

## In gatsby-config.js

```typescript
const gatsbyMdxPluginOptions = {
  remarkPlugins: [
    () => {
      const stripIndent = require('strip-indent');

      return (tree) => {
        tree.children.unshift({type: 'import', value: 'import {graphql} from \'gatsby\''});

        tree.children.push({
          type: 'export',
          value: stripIndent(`
            export const pageQuery = graphql\`
              query {
                site {
                  siteMetadata {
                    title
                  }
                }
              }
            \`;
          `).trim(),
        });
      };
    },
  ],
};
```

## MDX Transpiled to JSX

```javascript
import { mdx } from '@mdx-js/react';
/* @jsx mdx */

import { graphql } from 'gatsby';
export const _frontmatter = {};
export const pageQuery = graphql`
  query {
    site {
      siteMetadata {
        title
      }
    }
  }
`;

const makeShortcode = name => function MDXDefaultShortcode(props) {
  console.warn("Component " + name + " was not imported, exported, or provided by MDXProvider as global scope");
  return <div {...props} />;
};

const layoutProps = {
  _frontmatter,
  pageQuery
};
const MDXLayout = "wrapper";
export default function MDXContent({
  components,
  ...props
}) {
  return <MDXLayout {...layoutProps} {...props} components={components} mdxType="MDXLayout">



    </MDXLayout>;
}
;
```

**Comment by vladar** [comment] 2020-06-03 16:54
Hi @emanueleperuffo !

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by emanueleperuffo** [comment] 2020-06-04 06:40
Thanks @pieh !
I found the issue!

In function *parseFile*, the search for graphql queries bails out if the original source doesn't include the *graphql* word, before calling *preprocessSource*. This way, any modification to the original source (in this case adding the graphql import) is not seen by gatsby.

Since this is the way Gatsby works, should I close this issue?

One way this could be resolved would be adding a new gatsby-node.js API and replacing ```if (!text.includes(`graphql`)) return null``` with something like the following, maybe with a default implementation matching the original ```if (!text.includes(`graphql`)) return null```:

```javascript
const hasQueries = await apiRunnerNode(`hasQueries`, {
  filename: filePath,
  contents: fileStr,
  parentSpan: parentSpan,
})

if (!hasQueries) return null
```

https://github.com/gatsbyjs/gatsby/blob/68976dde3e25ee4c6186e0a59c50afb33ef6fed0/packages/gatsby/src/query/file-parser.js#L401-L421

**Comment by pieh** [comment] 2020-06-04 11:12
This is great find, I wasn't even aware we look for `graphql` string in file content (likely as optimization for bailing early).

I think that adding another gatsby-node hook just for this case is bit of overkill (we might reconsider in future if there are more usecases). 

As alternative - I would propose to only apply early bail if `graphql` is not in file content only for `.js` and `.ts` files - we already have precedent for doing something like this (for very similar reasons) in https://github.com/gatsbyjs/gatsby/blob/a6b26f201134cb189c4cb861fa9f5a0af55aabc8/packages/gatsby/src/utils/validate-page-component.ts#L83-L84

**Comment by emanueleperuffo** [comment] 2020-06-04 11:26
Yeah I know it's overkill. That's why I asked if I should close the issue.

Thank you very much by the way.

**Comment by johno** [comment] 2020-06-17 17:22
If you're trying to reference data that doesn't need access to variables in your MDX files, I'd suggest breaking the query out into its own component that uses StaticQuery or the [useStaticQuery](https://www.gatsbyjs.org/docs/use-static-query/) hook.

If you want access to variables you might want to leverage [programmatic page creation](https://www.gatsbyjs.org/docs/mdx/programmatically-creating-pages/) and the `pageQuery` directly for your MDX file.

I'm going to go ahead and close this since it's something that _should_ be achievable with the above approaches. If for some reason that's not the case, please reopen this issue and we can figure it out. Thanks for opening!

**Closed by johno** 2020-06-17 17:22 UTC
Labels: topic: MDX, type: bug
