### ISSUE TITLE
Error: The result of this StaticQuery could not be fetched.

### ISSUE THREAD

**Issue by ovsw** [gatsbyjs/gatsby#21392] opened 2020-02-12 05:16 UTC
## Description

Trying to run gatsby dev on heroku to use as a custom preview instance. This worked very well in the past.

Gatsby dev fails with Error: The result of this StaticQuery could not be fetched.

This seems to  be an issue with recent versions of gatsby (^2.18 or so, can't be exact here), since I have an instance running fine on the same environment which shows gatsby@2.13.35 as the installed version, with `npm list gatsby`.

### Steps to reproduce

1. `gatsby new test-gatsby-site` 
2. `cd test-gatsby-site`
3. add `Procfile` with `web: gatsby develop -p $PORT -H 0.0.0.0`
4. `heroku create test-gatsby-site`
5. `heroku config:set NODE_ENV=development`
6. `heroku config:set NPM_CONFIG_PRODUCTION=false`
7. commit everything in git
8. `git push heroku master`
9. after deploying, which goes fine, open the ap url (test-gatsby-site.herokuapp.com)

#### Non-working example
Actual example showing the error running at: https://gatsby-plain-test.herokuapp.com/ (give it a minute for the dyno to spin up first, if the page is taking too long too load -  it's just asleep as a free dyno)

#### Working example
As proof that it can work, I've set up another heroku instance with `gatsby@2.13.35` which works just fine https://gatsby-plain-testt.herokuapp.com/ 
The only thing I did was to downgrade the gatsby and corresponding packages versions (react, react-dom, etc)

### Expected result

The index page should render.

### Actual result

![gatsby-error](https://user-images.githubusercontent.com/35622133/74304429-a2684700-4d65-11ea-97e9-08bc26e7c3c9.png)

console shows 3 sets of this type of error, originating from:
```
index.js:2177 The above error occurred in the <Layout> component:
    in Layout (at pages/index.js:9)
    in IndexPage (created by HotExportedIndexPage)
    in AppContainer (created by HotExportedIndexPage)
    in HotExportedIndexPage (created by PageRenderer)
    in PageRenderer (at query-result-store.js:86)
    in PageQueryStore (at root.js:51)
    in RouteHandler (at root.js:73)
    in div (created by FocusHandlerImpl)
    in FocusHandlerImpl (created by Context.Consumer)
    in FocusHandler (created by RouterImpl)
    in RouterImpl (created by Context.Consumer)
    in Location (created by Context.Consumer)
    in Router (created by EnsureResources)
    in ScrollContext (at root.js:64)
    in RouteUpdates (at root.js:63)
    in EnsureResources (at root.js:61)
    in LocationHandler (at root.js:119)
    in LocationProvider (created by Context.Consumer)
    in Location (at root.js:118)
    in Root (at root.js:127)
    in StaticQueryStore (at root.js:133)
    in _default (at app.js:67)
```
```
index.js:2177 The above error occurred in the <AppContainer> component:
    in AppContainer (created by HotExportedIndexPage)
    in HotExportedIndexPage (created by PageRenderer)
    in PageRenderer (at query-result-store.js:86)
    in PageQueryStore (at root.js:51)
    in RouteHandler (at root.js:73)
    in div (created by FocusHandlerImpl)
    in FocusHandlerImpl (created by Context.Consumer)
    in FocusHandler (created by RouterImpl)
    in RouterImpl (created by Context.Consumer)
    in Location (created by Context.Consumer)
    in Router (created by EnsureResources)
    in ScrollContext (at root.js:64)
    in RouteUpdates (at root.js:63)
    in EnsureResources (at root.js:61)
    in LocationHandler (at root.js:119)
    in LocationProvider (created by Context.Consumer)
    in Location (at root.js:118)
    in Root (at root.js:127)
    in StaticQueryStore (at root.js:133)
    in _default (at app.js:67)
```
```
The above error occurred in the <LocationProvider> component:
    in LocationProvider (created by Context.Consumer)
    in Location (at root.js:118)
    in Root (at root.js:127)
    in StaticQueryStore (at root.js:133)
    in _default (at app.js:67)
```

### Environment

Run `gatsby info --clipboard` 
#### Non-Working example (https://gatsby-plain-test.herokuapp.com/ ) env info:
```
  System:
    OS: Linux 4.4 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.16.0 - ~/.heroku/node/bin/node
    Yarn: 1.22.0 - ~/.heroku/yarn/bin/yarn
    npm: 6.13.4 - ~/.heroku/node/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    gatsby: ^2.19.7 => 2.19.7
    gatsby-image: ^2.2.39 => 2.2.39
    gatsby-plugin-react-helmet: ^3.1.21 => 3.1.21
    gatsby-plugin-sharp: ^2.4.3 => 2.4.3
    gatsby-source-filesystem: ^2.1.46 => 2.1.46
    gatsby-transformer-sharp: ^2.3.13 => 2.3.13
```
Also react:
```
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
```
#### Working example (https://gatsby-plain-testt.herokuapp.com/ ) env info
```
System:
    OS: Linux 4.4 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.16.0 - ~/.heroku/node/bin/node
    npm: 6.13.4 - ~/.heroku/node/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    gatsby: 2.13.35 => 2.13.35
    gatsby-image: ^2.0.41 => 2.2.40
    gatsby-plugin-react-helmet: ^3.0.12 => 3.1.22
    gatsby-plugin-sharp: ^2.3.2 => 2.4.5
    gatsby-source-filesystem: ^2.1.38 => 2.1.48
    gatsby-transformer-sharp: ^2.3.5 => 2.3.14
```
Also react:
```
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
```

**Comment by ovsw** [comment] 2020-02-12 07:57
Upon further testing, it appears the bug was introduced somewhere in Gatsby 2.18, as 2.17.17 still works fine.

**Comment by wardpeet** [comment] 2020-02-12 13:03
Hey, does this only occur on heroku?

**Comment by ovsw** [comment] 2020-02-12 16:20
@wardpeet that's where I encountered it. I don't know if it's limited to heroku.

**Comment by shansmith01** [comment] 2020-02-20 19:58
I can also confirm this bug 
```


  System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i7-4558U CPU @ 2.80GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.9.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 80.0.3987.116
    Firefox: 67.0.4
    Safari: 13.0.5
  npmPackages:
    gatsby: ^2.19.16 => 2.19.16 
    gatsby-image: ^2.2.40 => 2.2.40 
    gatsby-plugin-compile-es6-packages: ^1.1.0 => 1.2.0 
    gatsby-plugin-eslint: ^2.0.5 => 2.0.8 
    gatsby-plugin-google-tagmanager: ^2.1.25 => 2.1.25 
    gatsby-plugin-hubspot: ^1.3.3 => 1.3.3 
    gatsby-plugin-manifest: ^2.2.41 => 2.2.41 
    gatsby-plugin-offline: ^2.2.0 => 2.2.10 
    gatsby-plugin-page-creator: ^2.1.40 => 2.1.40 
    gatsby-plugin-react-helmet: ^3.1.22 => 3.1.22 
    gatsby-plugin-react-helmet-canonical-urls: ^1.2.0 => 1.4.0 
    gatsby-plugin-robots-txt: ^1.5.0 => 1.5.0 
    gatsby-plugin-sharp: ^2.4.5 => 2.4.5 
    gatsby-plugin-sitemap: ^2.2.27 => 2.2.27 
    gatsby-plugin-styled-components: ^3.1.19 => 3.1.19 
    gatsby-plugin-webpack-bundle-analyser-v2: ^1.1.8 => 1.1.8 
    gatsby-source-datocms: ^2.1.23 => 2.1.23 
    gatsby-source-filesystem: ^2.1.48 => 2.1.48 
    gatsby-transformer-react-docgen: ^5.0.29 => 5.0.29 
    gatsby-transformer-sharp: ^2.3.14 => 2.3.14 
  npmGlobalPackages:
    gatsby-cli: 2.8.19
```

**Comment by ovsw** [comment] 2020-03-16 09:07
not stale?

**Comment by webriq** [comment] 2020-04-10 09:40
Encountering the same issue.

**Comment by sylvesteraswin** [comment] 2020-04-14 08:46
I am encountering the same issue with the latest version of `gatsby`

My `gatsby.config.js`

```js
module.exports = {
  siteMetadata: {
    siteName: "name",
    social: {
      twitter: "url",
      github: "url",
    },
  },
}
```

And in my react component I am doing this:
```jsx
const data = useStaticQuery(graphql`
    query HeaderQuery {
      site {
        siteMetadata {
          siteName: name
          social {
            twitter
            github
          }
        }
      }
    }
  `);
  console.log(data);
```

**Comment by Pyrax** [comment] 2020-05-06 00:28
I can confirm this is still an issue on Heroku.

Only happens on Heroku. Replacing the hook with `<StaticQuery />` component leads to infinite `Loading(StaticQuery)`, so this doesn't seem to make a difference.

Trying to do some more tests and will let you know if I can find out something.

```
  System:
    OS: Linux 4.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
    CPU: (8) x64 Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 12.16.3 - ~/.heroku/node/bin/node
    Yarn: 1.22.4 - ~/.heroku/yarn/bin/yarn
    npm: 6.14.4 - ~/.heroku/node/bin/npm
  Languages:
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    gatsby: ^2.21.0 => 2.21.0
    gatsby-image: ^2.4.0 => 2.4.0
    gatsby-plugin-manifest: ^2.4.0 => 2.4.0
    gatsby-plugin-offline: ^3.2.0 => 3.2.0
    gatsby-plugin-react-helmet: ^3.3.0 => 3.3.0
    gatsby-plugin-sharp: ^2.6.0 => 2.6.0
    gatsby-source-filesystem: ^2.3.0 => 2.3.0
    gatsby-transformer-sharp: ^2.5.0 => 2.5.0
```

**Comment by dorelljames** [comment] 2020-05-27 01:37
@Pyrax how did you replace the `StaticQuery` or did you just completely removed it?

**Comment by Pyrax** [comment] 2020-05-27 13:04
@dorelljames I had to completely remove it.

**Comment by webriq** [comment] 2020-05-28 01:29
Thank you. I'm going to give it a try.

**Comment by andrewmumblebee** [comment] 2020-05-28 06:59
I'm also experiencing the same issue, trying to set up a live preview server. 

I tried downgrading to @ovsw's working example, but ended up with different Gatsby errors being thrown instead.  

Removing all static queries on the site fixed this for me.

**Comment by danabrit** [comment] 2020-06-02 22:19
@ovsw Would you please attach a [minimal reproduction](https://www.gatsbyjs.org/contributing/how-to-make-a-reproducible-test-case/) so that we can take a look at this? Thanks!

**Comment by alex067** [comment] 2020-06-06 18:08
Want to confirm that this is happening with me as well, and I did absolutely 0 touches to the basic setup.

Step 1: gatsby new gatsby-site
Step 2: gatsby develop

Gatsby version: "^2.22.15",

**Comment by LekoArts** [comment] 2020-06-24 06:57
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by wardpeet** [comment] 2020-06-24 09:04
I ran
```
Step 1: gatsby new gatsby-site
Step 2: gatsby develop
```

I don't have any issues with the latest setup.
```
$  gatsby info

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 12.16.2 - ~\scoop\apps\nvs\current\nodejs\default\node.EXE
    Yarn: 1.22.4 - ~\scoop\apps\yarn\current\Yarn\bin\yarn.CMD
    npm: 6.14.4 - ~\scoop\apps\yarn\current\global\node_modules\.bin\npm.CMD
  Languages:
    Python: 3.8.2
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.23.10 => 2.23.10
    gatsby-image: ^2.4.8 => 2.4.8
    gatsby-plugin-manifest: ^2.4.13 => 2.4.13
    gatsby-plugin-offline: ^3.2.12 => 3.2.12
    gatsby-plugin-react-helmet: ^3.3.5 => 3.3.5
    gatsby-plugin-sharp: ^2.6.13 => 2.6.13
    gatsby-source-filesystem: ^2.3.13 => 2.3.13
    gatsby-transformer-sharp: ^2.5.6 => 2.5.6
```

**Comment by LukeTongue** [comment] 2020-06-25 12:18
I am having this issue too, the OP (@ovsw) has detailed the exact steps to reproduce this issue.

**Comment by kamit-transient** [comment] 2020-07-01 11:05
I am also facing the same issue, only difference is when I run `gatsby develop` its works fine but when I run `gatsby build` I am getting exactly same error.


```
$  gatsby info

  System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 12.16.2 - ~\scoop\apps\nvs\current\nodejs\default\node.EXE
    Yarn: 1.22.4 - ~\scoop\apps\yarn\current\Yarn\bin\yarn.CMD
    npm: 6.14.4 - ~\scoop\apps\yarn\current\global\node_modules\.bin\npm.CMD
  Languages:
    Python: 3.8.2
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    gatsby: ^2.23.10 => 2.23.10
    gatsby-image: ^2.4.8 => 2.4.8
    gatsby-plugin-manifest: ^2.4.13 => 2.4.13
    gatsby-plugin-offline: ^3.2.12 => 3.2.12
    gatsby-plugin-react-helmet: ^3.3.5 => 3.3.5
    gatsby-plugin-sharp: ^2.6.13 => 2.6.13
    gatsby-source-filesystem: ^2.3.13 => 2.3.13
    gatsby-transformer-sharp: ^2.5.6 => 2.5.6

```

**Comment by freiksenet** [comment] 2020-07-03 08:16
Hi! 

I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do reopen the issue. 

Thanks!

**Closed by freiksenet** 2020-07-03 08:16 UTC
Labels: status: needs reproduction, topic: StaticQuery

**Comment by Pyrax** [comment] 2020-07-03 17:19
It should be reproducible by exactly the steps OP has described. Last tested it around 7 days ago and that issue still exists. However, please keep in mind that this issue only appears on Heroku.

**Comment by woodwoerk** [comment] 2020-08-13 08:25
Hey there! This is still an issue. It's also worth noting that this approach is specifically recommended in the [Gatsby docs on how to run a custom preview instance on Heroku](https://www.gatsbyjs.org/docs/running-a-gatsby-preview-server/), so I really think this should be looked into.

The following reproduction is a simple Gatsby starter (`gatsby-starter-hello-world`) with a static query for `siteMetadata` and a `Procfile` for Heroku.

**Here's the reproduction:** https://github.com/woodwoerk/heroku-gatsby-dev-bug-repro.git

@freiksenet @LekoArts could this please be reopened? ❤️

**Comment by Sarah86** [comment] 2020-09-24 11:44
I am also experiencing this random error only when I try to deploy on Netlify.

**Comment by rodrigoreeis** [comment] 2021-01-21 15:09
Hello folks, I'm here to talk who I solved this problem, first think you knows is I don't know who I solved it because I try several things and probably some of these resolved.

The first think I did was this:

This is my old component using `StaticQuery`;

```js
import { StaticQuery, graphql } from 'gatsby'

import If from 'components/If'
import Img from 'gatsby-image'
import classnames from 'classnames'

import { getStaticImageByFilename } from './helpers'

import './Image.scss'

const Image = ({ filename, className, alt }) => (
  <StaticQuery
    query={graphql`
      query {
        images: allFile(filter: { sourceInstanceName: { eq: "images" } }) {
          edges {
            node {
              relativePath
              name
              childImageSharp {
                fluid(maxWidth: 578, quality: 100) {
                  ...GatsbyImageSharpFluid
                  ...GatsbyImageSharpFluid_withWebp
                }
              }
            }
          }
        }
      }
    `}
    render={({ images }) => {
      const image = getStaticImageByFilename({ images, filename })

      return (
        <If
          condition={image}
          renderIf={
            <Img
              className={classnames('image', {
                [className]: className,
              })}
              fluid={image?.node?.childImageSharp?.fluid}
              alt={alt}
            />
          }
        />
      )
    }}
  />
)
export default Image
```

I change from `StaticQuery` to `useStaticQuery`: 

```js

import { useStaticQuery, graphql } from 'gatsby'

import Img from 'gatsby-image'
import classnames from 'classnames'
import { getStaticImageByFilename } from './helpers'

import './Image.scss'

const useImageData = () => {
  const { images } = useStaticQuery(
    graphql`
      query {
        images: allFile(filter: { sourceInstanceName: { eq: "images" } }) {
          edges {
            node {
              relativePath
              name
              childImageSharp {
                fluid(maxWidth: 578, quality: 100) {
                  ...GatsbyImageSharpFluid
                  ...GatsbyImageSharpFluid_withWebp
                }
              }
            }
          }
        }
      }
    `
  )
  return images
}

export default ({ filename, className, data, ...props }) => {
  const images = useImageData()
  const staticImage = getStaticImageByFilename({ images, filename })

  return (
    <Img
      className={classnames('image', {
        [className]: className,
      })}
      fluid={staticImage?.node?.childImageSharp?.fluid}
      {...props}
    />
  )
}

```

Same after that I still received error on console(but just in production) in development(local) it worked normally... Because its no worked I try something else and was to update version `gastby` from `2.19.7` to `2.31.0`, and together I update my `buildspec.yml` my application is on the AWS I add some things for to do before start build: 

```yml
      - rm -rf node_modules
      - rm -rf yarn.lock
      - yarn install --frozen-lockfile
      - yarn clean
      - NODE_ENV="$ENVIRONMENT" ORGANIC="$ORGANIC" yarn build --prefix-paths="$ORGANIC"
```


After I did this things starts to works again but for moment I don't know what was the real problem I just try many things and some worked...
