### ISSUE TITLE
How to handle models from Contentful when there are no records in them?

### ISSUE THREAD

**Issue by lipis** [gatsbyjs/gatsby#11590] opened 2019-02-06 12:50 UTC
We have a case that sometimes the model is completely empty in Contentful (no job postings at the moment) and I'm getting the following error. Is there a way to handle that? Am I holding it wrong?

---

GraphQL
```graphql
{
  allContentfulJob {
    edges {
      node {
        id
      }
    }
  }
}
```
Result:

```json
{
  "errors": [
    {
      "message": "Cannot query field \"allContentfulJob\" on type \"Query\". Did you mean \"allContentfulSpt\", \"allContentfulJobsMeta\", \"allContentfulAsset\", \"contentfulSpt\", or \"allContentfulContact\"?",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```

**Comment by lsirivong** [comment] 2019-02-07 03:21
I (believe) this is the main issue where this is being discussed: https://github.com/gatsbyjs/gatsby/issues/3344

Most folks seem to take the route of publishing some dummy data to work around the build error, and filtering it out of your app build in some way if necessary.

**Comment by sidharthachatterjee** [comment] 2019-02-08 22:29
This is being worked on in https://github.com/gatsbyjs/gatsby/pull/11480

Closing this since it looks like a duplicate of https://github.com/gatsbyjs/gatsby/issues/3344 
Please follow along there!

**Closed by sidharthachatterjee** 2019-02-08 22:29 UTC
Labels: type: question or discussion

**Comment by arnevankauter** [comment] 2020-11-12 15:14
Is there any updates regarding this?
Would really like to prevent adding dummy content to fix this issue.
