### ISSUE TITLE
Broken markdown captions in gatsby-remark-images when using MDX

### ISSUE THREAD

**Issue by Swizec** [gatsbyjs/gatsby#26882] opened 2020-09-14 01:28 UTC
## Description

![image](https://user-images.githubusercontent.com/56883/93034380-ba9b8f80-f5ee-11ea-9c61-3868b57a1052.png)

After upgrading `gatsby-plugin-mdx` and later `gatsby-remark-images` while debugging, image captions became broken.

That is when writing Markdown as `![Caption](url)`.

I can't tell if the bug is with `gatsby-remark-images` or with `gatsby-plugin-mdx`. The issue changed from saying `[object Promise]` to the code printout in my screenshot when I upgraded gatsby-remark-images.

### Steps to reproduce

This is my full gatsby config: https://github.com/Swizec/swizec.com/blob/master/gatsby-config.js

Changing `markdownCaptions: false` fixes the bug. Turn it true and you get the strange behavior.

### Expected result

![image](https://user-images.githubusercontent.com/56883/93034450-e9b20100-f5ee-11ea-98ba-2c3060c88a79.png)

Image caption should be populated from the text between square brackets.

### Actual result

![image](https://user-images.githubusercontent.com/56883/93034427-dacb4e80-f5ee-11ea-91b9-5b05ea9dbbd5.png)

### Environment

Run `gatsby info --clipboard` in your project directory and paste the output here.

```

  System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.18.2 - /usr/local/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.14.5 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Firefox: 71.0
    Safari: 13.1.2
  npmPackages:
    gatsby: ^2.24.57 => 2.24.57 
    gatsby-plugin-advanced-sitemap: ^1.5.5 => 1.5.5 
    gatsby-plugin-catch-links: ^2.1.2 => 2.2.1 
    gatsby-plugin-facebook-pixel: ^1.0.3 => 1.0.3 
    gatsby-plugin-feed: ^2.5.11 => 2.5.11 
    gatsby-plugin-google-analytics: ^2.1.20 => 2.2.2 
    gatsby-plugin-instagram-embed: ^2.0.1 => 2.0.1 
    gatsby-plugin-manifest: ^2.2.23 => 2.3.3 
    gatsby-plugin-mdx: ^1.0.22 => 1.2.39 
    gatsby-plugin-meta-redirect: ^1.1.1 => 1.1.1 
    gatsby-plugin-netlify: ^2.3.13 => 2.3.13 
    gatsby-plugin-offline: ^3.0.16 => 3.1.2 
    gatsby-plugin-react-helmet: ^3.1.3 => 3.2.2 
    gatsby-plugin-remove-fingerprints: ^0.0.2 => 0.0.2 
    gatsby-plugin-sharp: ^2.2.31 => 2.6.19 
    gatsby-plugin-simple-analytics: ^1.0.1 => 1.0.3 
    gatsby-plugin-slug: ^1.1.0 => 1.1.0 
    gatsby-plugin-theme-ui: ^0.2.26 => 0.2.53 
    gatsby-plugin-twitter: ^2.2.2 => 2.2.2 
    gatsby-redirect-from: ^0.2.4 => 0.2.4 
    gatsby-remark-copy-linked-files: ^2.1.28 => 2.2.1 
    gatsby-remark-embedder: ^3.0.0 => 0.0.0-semantically-released 
    gatsby-remark-giphy: ^1.1.2 => 1.1.2 
    gatsby-remark-images: ^3.1.28 => 3.3.29 
    gatsby-remark-relative-images: ^0.2.3 => 0.2.3 
    gatsby-source-filesystem: ^2.1.33 => 2.2.2 
    gatsby-transformer-remark: ^2.6.37 => 2.7.1 
    gatsby-transformer-sharp: ^2.2.23 => 2.4.4 
  npmGlobalPackages:
    gatsby-cli: 2.7.54

```

**Comment by laurieontech** [comment] 2020-09-14 13:19
Thanks for the PR! This is a duplicate of #25137. As noted in [this comment](https://github.com/gatsbyjs/gatsby/issues/25137#issuecomment-647535957) the issue is a broader one related to parsing and remark plugins. It's on our radar and we're looking into potential options that will work across plugins.

**Closed by laurieontech** 2020-09-14 13:19 UTC
Labels: topic: MDX, type: bug

**Comment by solace** [comment] 2021-03-26 06:17
@Swizec What did you do as an alternative? Just manually add the caption below?
