### ISSUE TITLE
Cannot use socket.io-client in Gatsby since it already includes a different version

### ISSUE THREAD

**Issue by idosius** [gatsbyjs/gatsby#28345] opened 2020-11-28 11:47 UTC
## Description

I'm developing a website using Gatsby. One of the requirements is to establish a Web Socket connection to a server. I've tried using socket.io version 3.0.3 both on the client and the server, but the web socket failed to connect.

After some investigation, I realized that Gatsby already includes socket.io-client version 2.3.0. Even though I installed + imported the latest socket.io-client 3.0.3, it seemed to be ignored. I downgraded the socket.io running on my server to 2.3.0, and low and behold, everything was working.

Not sure if this is just a Gatsby issue, but it looks like running two different versions of socket.io-client in the same environment is not possible.

### Steps to reproduce

Creat

1. e a demo socket.io (version 3.0.3) server on some port
2. Install + run Gatsby 2.24.50 in development mode
3. In Gatsby, install socket.io-client in version 3.0.3
4. In a Gatsby component or page, try to establish a web socket connection to the above server via socket.io-client - the connection will fail
5. Downgrade socket.io on the above server to version 2.3.0 and restart the server
6. Try to establish the web socket connection again - it will succeed
7. You can even remove the socket.io-client import in Gatsby, it will still work

### Expected result

The expected behavior is that it should be possible to use any socket.io-client version in Gatsby.

### Actual result

Couldn't use a different socket.io-client version than the one that Gatsby uses already.

### Environment

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.18.4/bin/npm
  Languages:
    Python: 3.9.0 - /Users/idosius/.pyenv/shims/python
  Browsers:
    Chrome: 87.0.4280.67
    Firefox: 83.0
    Safari: 13.0.4
  npmPackages:
    gatsby: ^2.27.0 => 2.27.4 
    gatsby-image: ^2.4.16 => 2.4.16 
    gatsby-plugin-copy-files: ^1.0.3 => 1.0.3 
    gatsby-plugin-eslint: ^2.0.8 => 2.0.8 
    gatsby-plugin-firebase: ^0.2.0-beta.4 => 0.2.0-beta.4 
    gatsby-plugin-i18n: ^1.0.1 => 1.0.1 
    gatsby-plugin-manifest: ^2.4.24 => 2.4.24 
    gatsby-plugin-offline: ^3.2.24 => 3.2.24 
    gatsby-plugin-react-helmet: ^3.3.10 => 3.3.10 
    gatsby-plugin-sass: ^2.3.13 => 2.3.13 
    gatsby-plugin-sharp: ^2.6.28 => 2.6.28 
    gatsby-source-filesystem: ^2.3.25 => 2.3.25 
    gatsby-transformer-sharp: ^2.5.13 => 2.5.13 
  npmGlobalPackages:
    gatsby-cli: 2.12.117

**Comment by LekoArts** [comment] 2020-11-30 10:08
Hi!

Have you tried using yarn's `resolutions` feature to force only one version?

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2020-12-14 16:21
Hi!

Since we didn't receive an answer for 7 business days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-12-14 16:21 UTC
Labels: status: needs reproduction, type: bug

**Comment by dmitry-korolev** [comment] 2021-01-18 20:48
@LekoArts I can confirm that the problem exists.

Here is the minimal reproduction — https://github.com/dmitry-korolev/gatsby-socket-io-reproduce
It uses socket.io@3.1.0 on the server-side and tries to use socket.io-client@3.1 on client side which fails. You will see network errors in the networks tab.

**Comment by dmitry-korolev** [comment] 2021-01-22 08:07
@idosius @LekoArts 👋

**Comment by dmitry-korolev** [comment] 2021-01-25 20:48
I feel lost...

**Comment by zcmgyu** [comment] 2021-02-24 04:24
I got the same issue

> import { version } from 'socket.io-client/package.json';
> 
> console.log(version); // 2.3.0

**Comment by KyleAMathews** [comment] 2021-02-24 05:15
You need to use socket.io version 2 until we can upgrade socket.io as part of Gatsby v3. To install that, run `npm install socket.io@2.3.0`

**Comment by KyleAMathews** [comment] 2021-02-24 05:16
We could upgrade Gatsby v2 to socket.io@v3 as it's just used in development. If any of your are interested in creating a PR, raise your hand and we can help you know how to test.

**Comment by zcmgyu** [comment] 2021-02-24 08:47
Thank for your advices.
