### ISSUE TITLE
pageQuery doesn't reflect changes on its own

### ISSUE THREAD

**Issue by vojtaholik** [gatsbyjs/gatsby#24705] opened 2020-06-02 09:55 UTC
## Description

I have a [basic blog setup](https://github.com/vojtaholik/page-query-doesnt-reflect-changes) that is nearly identical to [`gatsby-theme-blog-core`](https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-theme-blog-core#readme).

After adding a new post (markdown file) to a folder which is being used to incrementally build pages (/content/posts), I need to manually edit a pageQuery to reflect the changes. Even after building the site, the new post won't show up. I recorded a short [screen capture describing the issue](https://share.getcloudapp.com/lluJjDe7).

### Steps to reproduce

Follow instructions in this repo: https://github.com/vojtaholik/page-query-doesnt-reflect-changes#steps-to-reproduce-a-bug-with-pagequery-not-reflecting-changes

### Expected result

pageQuery should reflect changes in the file tree on its own without needing to edit it.

### Actual result

pageQuery didn't reflect changes in file tree, even though they're visible in graphiql. 

May be related to something that isn't hooked up in the data dependency tracking, specifically around the frontmatter values in MDX files?

<details>
  <summary>
<b>Environment</b>
</summary>

```
  System:
    OS: macOS 10.15.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.21.1 - ~/.nvm/versions/node/v10.16.0/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 76.0.1
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.22.15 => 2.22.15 
    gatsby-core-utils: ^1.3.3 => 1.3.3 
    gatsby-image: ^2.4.5 => 2.4.5 
    gatsby-link: ^2.4.3 => 2.4.3 
    gatsby-plugin-catch-links: ^2.3.3 => 2.3.3 
    gatsby-plugin-feed: ^2.5.3 => 2.5.3 
    gatsby-plugin-manifest: ^2.4.9 => 2.4.9 
    gatsby-plugin-mdx: ^1.2.13 => 1.2.13 
    gatsby-plugin-meta-redirect: ^1.1.1 => 1.1.1 
    gatsby-plugin-offline: ^3.2.7 => 3.2.7 
    gatsby-plugin-postcss: ^2.3.2 => 2.3.2 
    gatsby-plugin-react-helmet: ^3.3.2 => 3.3.2 
    gatsby-plugin-sharp: ^2.6.9 => 2.6.9 
    gatsby-plugin-twitter: ^2.3.2 => 2.3.2 
    gatsby-remark-copy-linked-files: ^2.3.3 => 2.3.3 
    gatsby-remark-images: ^3.3.8 => 3.3.8 
    gatsby-remark-prismjs: ^3.5.2 => 3.5.2 
    gatsby-remark-smartypants: ^2.3.2 => 2.3.2 
    gatsby-source-filesystem: ^2.3.8 => 2.3.8 
    gatsby-transformer-remark: ^2.8.13 => 2.8.13 
    gatsby-transformer-sharp: ^2.5.3 => 2.5.3 
  npmGlobalPackages:
    gatsby-cli: 2.8.15
```

</details>

**Comment by pieh** [comment] 2020-06-03 08:01
Just used reproduction and can confirm it's happening. Investigating now

(awesome bug report btw, repo and steps to reproduce are very clear!)

**Comment by pieh** [comment] 2020-06-03 08:21
> May be related to something that isn't hooked up in the data dependency tracking, specifically around the frontmatter values in MDX files?

It seems related to data dependency tracking from my initial findings.

First some context on how things work today to explain why the bug happens:

Gatsby keep track of individual nodes used in query results as well as node type collections and reruns query whenever those individual nodes or collections change. 

Problem we see here is that our data tracking doesn't seem to handle cases when custom node interface is defined that is implemented then by some concrete node types. In your reproduction you have `BlogPost` node interface and `MdxBlogPost` that implements it ( https://github.com/vojtaholik/page-query-doesnt-reflect-changes/blob/11e27f19ff1b6b0cfca7a9976f5a3d168e9fdd56/gatsby-node.js#L52-L118 ). When you query for `allBlogPost` we add collection dependency for `BlogPost` "type" - but this is virtual type - there are no actual nodes with that type (but there are nodes of `MdxBlogPost` type). To illustrate this - this is screenshot from my debugging:

![Screenshot 2020-06-03 at 10 14 29](https://user-images.githubusercontent.com/419821/83612988-70345c80-a583-11ea-9693-4c51274e153a.png)

You can see from my screenshot that we don't mark `BlogPost` collection as dirty (and would queue up query to rerun) because we rely only on concrete node types here.

There are few ways I think we can approach this to fix it:
1. Around the code I was debugging - check for interfaces that are implemented by our types and mark them as dirty as well
2. When querying interfaces (`allBlogPost`) - add all node types that implement it to our data tracking system and not just interface alone

**Comment by pieh** [comment] 2020-06-03 09:56
After chatting with few collegues about this - we decided to go with approach 2) (from my previous comment). I hope to open PR with fix sometime this week

**Comment by pieh** [comment] 2020-06-03 15:09
Just opened draft pull request for it in https://github.com/gatsbyjs/gatsby/pull/24754 (if you want to keep track of it). Until this is merged and published I can release canary `gatsby` version with the proposed fix for you to use in meantime

**Comment by vojtaholik** [comment] 2020-06-03 21:56
Great news! Thank you so much @pieh, awesome work. ✨ Canary version would def be nice, but no big deal if not. :)

**Closed** 2020-06-04 08:53 UTC
Labels: status: confirmed, status: needs core review, topic: webpack/babel, type: bug

**Comment by pieh** [comment] 2020-06-04 09:00
@vojtaholik PR was handled quickly even before I had chance to publish canary ;) So please upgrade to at least `gatsby@2.22.22` and issue should be fixed

**Comment by vojtaholik** [comment] 2020-06-04 09:06
I can confirm this is now fixed 🥳 thank you @pieh!
