### ISSUE TITLE
[gatsby-plugin-mdx] timeToRead does not account for code blocks

### ISSUE THREAD

**Issue by brotzky** [gatsbyjs/gatsby#17264] opened 2019-08-30 18:26 UTC
Reference from https://github.com/narative/gatsby-theme-novela/issues/99

> I have an article which is 5min read according to Novela, but in practice it's more 15-20min, due to many code fragments and MDX demo components.

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-mdx/gatsby/source-nodes.js#L18

https://github.com/gatsbyjs/gatsby/blob/master/packages/gatsby-plugin-mdx/gatsby/source-nodes.js#L218

It would be nice to have code blocks including in reading time for MDX. Right now it appears to only take into account words.

## Description

Reading time is only taking into account paragraphs/words

### Expected result

Reading time also takes into account code blocks

**Comment by LekoArts** [comment] 2019-09-04 07:16
Duplicate of https://github.com/gatsbyjs/gatsby/issues/16760

**Closed by LekoArts** 2019-09-04 07:16 UTC
Labels: topic: MDX

**Comment by brotzky** [comment] 2019-09-04 15:49
Ah! Darn, I tried looking it up before, too! Thanks so much @LekoArts.
