### ISSUE TITLE
Copying code from docs results in single line string

### ISSUE THREAD

**Issue by muuvmuuv** [gatsbyjs/gatsby#11964] opened 2019-02-21 16:08 UTC
## Description

When I copy something from a code block somewhere in a docs page (e.g. https://www.gatsbyjs.org/tutorial/part-seven/) the pasted content is a single line string. This would be no problem since my formatter beautifies it but some of them, especially those with comments, it has its problems so I need to copy it line by line.

### Steps to reproduce

Copy something from a code block into an editor.

### Expected result

Should look like the example on the docs page

### Actual result

.. single line string

### Environment

  System:
    OS: macOS 10.14.3
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
    Yarn: 1.13.0 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
  Languages:
    Python: 2.7.15 - /usr/local/bin/python
  Browsers:
    Chrome: 72.0.3626.109
    Firefox: 65.0.1
    Safari: 12.0.3
  npmPackages:
    gatsby: ^2.0.85 => 2.1.13 
    gatsby-plugin-emotion: ^4.0.4 => 4.0.4 
    gatsby-plugin-sass: ^2.0.10 => 2.0.10 
    gatsby-plugin-typescript: ^2.0.0 => 2.0.8 
    gatsby-plugin-typography: ^2.2.7 => 2.2.7 
    gatsby-source-filesystem: ^2.0.21 => 2.0.21 
    gatsby-transformer-remark: ^2.2.5 => 2.2.5 
  npmGlobalPackages:
    gatsby-cli: 2.4.11

**Comment by yogeshkotadiya** [comment] 2019-02-21 16:58
I can't reproduce this, pasted code is exactly formatted as in docs.
Tested in VSCode and OS's text editor.

**Comment by muuvmuuv** [comment] 2019-02-22 11:41
@yogeshkotadiya did you have tried all code blocks? The first one seems fine, the rest keeps printing parts of it as single line

**Comment by yogeshkotadiya** [comment] 2019-02-22 11:47
@muuvmuuv Yup tried multiple same result nothing weird.
Check your editor's settings or try resetting it.

**Comment by muuvmuuv** [comment] 2019-02-22 12:38
@yogeshkotadiya still the same. Noticed that it is just my firefox and firefox developer edition, so it might be a browser problem... 

tested safari, chrome, firefox, firefox developer edition with vscode, plain text editor and sublime

**Comment by yogeshkotadiya** [comment] 2019-02-22 12:56
Just tried using firefox and you are right I can reproduce this.
One thing I noticed that it only affects the code which is highlighted.

**Comment by wardpeet** [comment] 2019-02-22 13:15
I haven't looked into this yet but if any of you have more info where this might happend and maybe create a PR we would be happy to accept 😄

**Comment by 17cupsofcoffee** [comment] 2019-02-22 16:42
Think I have an idea what might be causing this!

If you copy and paste the HTML for one of those code blocks from your dev tools into a text editor, you get this:

```html
<div class="gatsby-highlight" data-language="javascript"><pre class="language-javascript"><code class="language-javascript">exports<span class="token punctuation">.</span><span class="token function-variable function">onCreateNode</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">{</span> node <span class="token punctuation">}</span><span class="token punctuation">)</span> <span class="token operator">=&gt;</span> <span class="token punctuation">{</span>
<span class="gatsby-highlight-code-line">  <span class="token keyword">if</span> <span class="token punctuation">(</span>node<span class="token punctuation">.</span>internal<span class="token punctuation">.</span>type <span class="token operator">===</span> <span class="token template-string"><span class="token string">`MarkdownRemark`</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span></span><span class="gatsby-highlight-code-line">    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>node<span class="token punctuation">.</span>internal<span class="token punctuation">.</span>type<span class="token punctuation">)</span></span><span class="gatsby-highlight-code-line">  <span class="token punctuation">}</span></span><span class="token punctuation">}</span></code></pre></div>
```

Notice that line breaks are inserted properly outside of highlighted lines, but there isn't actually a line break for each `gatsby-highlight-code-line` - they're instead made to fill the entire width of the container via `display: block`, which naturally shoves the next bit of text onto a new line.

Chrome seems to be able to work out the intent and replicates the structure when you copy and paste, whereas it seems like Firefox will only insert line breaks where they're actually present in the text (the latter seems more correct to me, if less useful!).

**Comment by LekoArts** [comment] 2019-09-23 12:36
Thank you for opening this!

I can't reproduce this error.

We're marking this issue as answered and closing it for now but please feel free to reopen this and comment if you would like to continue this discussion. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2019-09-23 12:36 UTC
Labels: type: documentation
