### ISSUE TITLE
[gatsby-plugin-image] doesn't work with remote SVG's

### ISSUE THREAD

**Issue by mmclafferty** [gatsbyjs/gatsby#30906] opened 2021-04-16 21:14 UTC
## Description

I am attempting to load an SVG from gatsby-sanity-source and it appears that this new plugin doesn't seem to support it.

### Steps to reproduce

The image data looks like the following:
```
{
  "images": {
    "sources": [
      {
        "srcSet": "https://cdn.sanity.io/images/dm4o0ui7/staging/121ecff050cdf4372977a1a45bffff802801850c-132x20.svg?rect=2,0,128,20&w=32&h=5&auto=format 32w,\nhttps://cdn.sanity.io/images/dm4o0ui7/staging/121ecff050cdf4372977a1a45bffff802801850c-132x20.svg?rect=3,0,126,20&w=132&h=21&auto=format 132w",
        "sizes": "(min-width: 32px) 32px, 100vw",
        "type": "image/svg"
      }
    ]
  },
  "layout": "constrained",
  "width": 32,
  "height": 5
}
```

Setting this on the GatsgbyImage results in the following error:
Failed prop type: The prop `src` is marked as required in `J`, but its value is `undefined`.
  in J
  in Picture
  in MainImage
  
  The DOM element looks like:

```
<picture>
  <source type="image/svg" srcset="https://cdn.sanity.io/images/dm4o0ui7/staging/121ecff050cdf4372977a1a45bffff802801850c-132x20.svg?rect=2,0,128,20&amp;w=32&amp;h=5&amp;auto=format,
https://cdn.sanity.io/images/dm4o0ui7/staging/121ecff050cdf4372977a1a45bffff802801850c-132x20.svg?rect=3,0,126,20&amp;w=132&amp;h=21&amp;auto=format">
  <img class="ComparisonChartstyles__PrimaryBrandLogo-hDTPxt hqXnuL" width="32" height="5" data-main-image="" decoding="async" alt="Brand Logo" style="object-fit: cover; opacity: 0;">
</picture>

```

### Expected result

The image should load.

### Actual result

No image loads.

### Environment

  System:
    OS: macOS 11.2.3
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 7.7.5 - ~/.nvm/versions/node/v12.18.4/bin/npm
  Languages:
    Python: 2.7.16 - /usr/bin/python
  Browsers:
    Chrome: 89.0.4389.128
    Safari: 14.0.3
  npmPackages:
    gatsby: ^3.3.0 => 3.3.0
    gatsby-plugin-env-variables: 2.0.0 => 2.0.0
    gatsby-plugin-graphql-codegen: ^2.7.1 => 2.7.1
    gatsby-plugin-image: ^1.3.0 => 1.3.0
    gatsby-plugin-netlify: ^3.3.0 => 3.3.0
    gatsby-plugin-output: ^0.1.2 => 0.1.3
    gatsby-plugin-preact: ^5.3.0 => 5.3.0
    gatsby-plugin-react-helmet: ^4.3.0 => 4.3.0
    gatsby-plugin-resolve-src: ^2.1.0 => 2.1.0
    gatsby-plugin-robots-txt: ^1.5.5 => 1.5.5
    gatsby-plugin-sharp: ^3.3.0 => 3.3.0
    gatsby-plugin-sitemap: ^3.1.0 => 3.1.0
    gatsby-plugin-styled-components: ^4.1.0 => 4.1.0
    gatsby-plugin-typescript: ^3.1.0 => 3.1.0
    gatsby-plugin-webfonts: ^2.1.0 => 2.1.0
    gatsby-plugin-webpack-bundle-analyzer: ^1.0.5 => 1.0.5
    gatsby-source-sanity: ^7.0.4 => 7.0.4

**Comment by EliotSlevin** [comment] 2021-04-19 01:27
I believe the previous gatsby-image plugin never supported SVGs. The new version does, at least locally with `<StaticImage/>`? (just tested)

But, are you sure you want to be rendering your remote SVGs via gatsby-plugin-image? It will render your SVG as a bitmap format. SVGs are already pretty dang efficient, I doubt you'd see any performance increase rendering a 32px wide SVG as a bitmap - in fact it'd probably be slower?

**Comment by mmclafferty** [comment] 2021-04-19 02:12
It’s not that I want to render svgs. It’s whatever image content is uploaded to the cms (sanity) that will end up here. In this case, they set the image to a bunch of svgs and thus they don’t render due to the bug.

**Comment by LekoArts** [comment] 2021-04-19 08:15
Thank you for opening this!

This is working as intended, please see: https://github.com/gatsbyjs/gatsby/discussions/30886
And also see this comment: https://github.com/gatsbyjs/gatsby/discussions/27950#discussioncomment-127534

You can open a feature request about the second comment here: https://github.com/gatsbyjs/gatsby/discussions/categories/ideas-feature-requests

We're marking this issue as answered and closing it for now but please feel free to comment here if you would like to continue this discussion. We also recommend heading over to our [communities](https://www.gatsbyjs.org/contributing/community/#where-to-get-support) if you have questions that are not bug reports or feature requests. We hope we managed to help and thank you for using Gatsby!

**Closed by LekoArts** 2021-04-19 08:15 UTC
Labels: topic: images/media, type: bug

**Comment by AlonsoAraya-eL** [comment] 2021-05-15 21:04
My SVG's do work when bringing them from Sanity and using gatsby-plugin-image, although they are getting that annoying error.

**Comment by bojackhorseman0309** [comment] 2021-05-15 21:05
My SVG's do work when bringing them from Sanity and using gatsby-plugin-image, although they are getting that annoying error.
