### ISSUE TITLE
[gatsby-remark-code-repls and gatsby-remark-images] Doesn't listen to pathPrefix

### ISSUE THREAD

**Issue by Swizec** [gatsbyjs/gatsby#3124] opened 2017-12-04 02:40 UTC
This is a bug.

I'm using Gatsby to build for gh-pages where sites have a path prefix. For example [on my workshop page](https://swizec.github.io/intro-to-react-workshop/2-your-first-component/#two-flavors-of-components)

That page is at `.../intro-to-react-workshop/` which works fine for the most part.

One of the problems I've found is that `gatsby-remark-code-repls` works wonderfully in local development where I compile without prefixes. But when compiling for github with this command: 

```
rm -rf .cache && rm -rf public && gatsby build --prefix-paths && gh-pages -d public
```

It constructs incorrect links for Codepen redirects. 

```
https://swizec.github.io/redirect-to-codepen/your-first-component/class-component
```

is put in the page. But it should be

```
https://swizec.github.io/intro-to-react-workshop/redirect-to-codepen/your-first-component/class-component
```

gatsby-remark-images experiences a similar problem, but only for gifs. It works for every other type of image, but gifs are always constructed without a path prefix, which leads to 404 errors.

**Comment by KyleAMathews** [comment] 2017-12-04 02:57
Hmm yeah — sorry about that :-( 

Would you like to put together PRs for these?

**Comment by Swizec** [comment] 2017-12-05 04:13
Sure, I can give it a shot this weekend. :)

**Comment by Sorgrum** [comment] 2017-12-07 19:31
I seem to be having this issue with png files. So maybe the issue is more general than previously thought?

I'm referencing the file into my markdown using this syntax
`![](screenrc_example.png)`

Can anyone confirm that this isn't a `gif` only issue?

**Comment by djm158** [comment] 2018-03-07 02:05
I'm experiencing the same problem. neither `![](my_image.png)` or `![](./my_image.png)` seem to work for me.

**Comment by KyleAMathews** [comment] 2018-09-08 04:27
Due to the high volume of issues, we're closing out older ones without recent activity. Please open a new issue if you need help!

**Closed by KyleAMathews** 2018-09-08 04:27 UTC
Labels: type: bug :beetle:
