### ISSUE TITLE
Unable to run on windows

### ISSUE THREAD

**Issue by mlabrum** [gatsbyjs/gatsby#16758] opened 2019-08-20 08:32 UTC
## Description
Running the starter blog on windows doesn't work at all due to the main drive having a capital `C:/` 

### Steps to reproduce
```
gatsby new blog https://github.com/gatsbyjs/gatsby-starter-blog
npm run develop
```

### Expected result
it should run without errors

### Actual result

```
> gatsby-starter-blog@0.1.0 develop c:\git\lynkz\blog
> gatsby develop

success open and validate gatsby-configs - 0.070 s
success load plugins - 1.487 s
success onPreInit - 0.040 s
info One or more of your plugins have changed since the last time you ran Gatsby. As
a precaution, we're deleting your site's cache to ensure there's not any stale
data
success initialize cache - 0.056 s
success copy gatsby files - 0.144 s
warn gatsby-plugin-feed was initialized in gatsby-config.js without a feeds option.
This means that the plugin will use the internal RSS feed creation, which may not match your use case.
This behavior will be removed in the next major release of gatsby-plugin-feed.
For more info, check out: https://gatsby.dev/adding-rss-feed
success onPreBootstrap - 0.082 s
success source and transform nodes - 0.282 s
success building schema - 0.373 s
warn Your site's "gatsby-node.js" created a page with a component path that doesn't match the casing of the actual file. This may
work locally, but will break on systems which are case-sensitive, e.g. most CI/CD pipelines.

page.component:     "c:/git/lynkz/blog/src/templates/blog-post.js"
path in filesystem: "C:/git/lynkz/blog/src/templates/blog-post.js"
                     ^
success createPages - 0.082 s
warn The plugin "dev-404-page" created a page with a component path that doesn't match the casing of the actual file. This may work locally, but will break on systems which are case-sensitive, e.g. most CI/CD pipelines.

page.component:     "c:/git/lynkz/blog/.cache/dev-404-page.js"
path in filesystem: "C:/git/lynkz/blog/.cache/dev-404-page.js"
                     ^
warn The plugin "gatsby-plugin-page-creator" created a page with a component path that doesn't match the casing of the actual file. This may work locally, but will break on systems which are case-sensitive, e.g. most CI/CD pipelines.

page.component:     "c:/git/lynkz/blog/src/pages/404.js"
path in filesystem: "C:/git/lynkz/blog/src/pages/404.js"
                     ^
warn The plugin "gatsby-plugin-page-creator" created a page with a component path that doesn't match the casing of the actual file. This may work locally, but will break on systems which are case-sensitive, e.g. most CI/CD pipelines.

page.component:     "c:/git/lynkz/blog/src/pages/index.js"
path in filesystem: "C:/git/lynkz/blog/src/pages/index.js"
                     ^
success createPagesStatefully - 0.114 s
success onPreExtractQueries - 0.053 s
success update schema - 0.074 s

 ERROR #85901  GRAPHQL

There was an error in your GraphQL query:

Error: RelayParser: Encountered duplicate defintitions for one or more documents: each document must have a unique name. Duplicated documents:
- BlogPostBySlug
- cGitLynkzBlogSrcPages404Js1097489062
- cGitLynkzBlogSrcPagesIndexJs2785444898

success extract queries from components - 0.447 s
success write out requires - 0.072 s
success write out redirect data - 0.052 s
success Build manifest and related icons - 0.155 s
success onPostBootstrap - 0.215 s
⠀
info bootstrap finished - 8.804 s
⠀
success run static queries - 0.052 s
success run page queries - 0.077 s — 7/7 330.73 queries/second
 WARNING  Compiled with 17 warnings                                                                                      6:25:11 PM⠀
 warning  in C:/git/lynkz/blog/node_modules/gray-percentage/index.js
⠀
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\git\lynkz\blog\node_modules\gray-percentage\index.js
    Used by 1 module(s), i. e.
    C:\git\lynkz\blog\node_modules\typography-theme-wordpress-2016\dist\index.js
* c:\git\lynkz\blog\node_modules\gray-percentage\index.js
    Used by 1 module(s), i. e.
    c:\git\lynkz\blog\node_modules\typography-theme-wordpress-2016\dist\index.js
⠀
 warning  in C:/git/lynkz/blog/node_modules/object-assign/index.js
⠀
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\git\lynkz\blog\node_modules\object-assign\index.js
    Used by 3 module(s), i. e.
    C:\git\lynkz\blog\node_modules\react\cjs\react.development.js
* c:\git\lynkz\blog\node_modules\object-assign\index.js
    Used by 4 module(s), i. e.
    c:\git\lynkz\blog\node_modules\react\cjs\react.development.js
⠀
 warning  in C:/git/lynkz/blog/node_modules/prop-types/checkPropTypes.js
⠀
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\git\lynkz\blog\node_modules\prop-types\checkPropTypes.js
    Used by 2 module(s), i. e.
    C:\git\lynkz\blog\node_modules\react\cjs\react.development.js
* c:\git\lynkz\blog\node_modules\prop-types\checkPropTypes.js
    Used by 4 module(s), i. e.
    c:\git\lynkz\blog\node_modules\react\cjs\react.development.js
⠀
 warning  in C:/git/lynkz/blog/node_modules/prop-types/factoryWithTypeCheckers.js
⠀
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\git\lynkz\blog\node_modules\prop-types\factoryWithTypeCheckers.js
    Used by 1 module(s), i. e.
    C:\git\lynkz\blog\node_modules\prop-types\index.js
* c:\git\lynkz\blog\node_modules\prop-types\factoryWithTypeCheckers.js
    Used by 1 module(s), i. e.
    c:\git\lynkz\blog\node_modules\prop-types\index.js
⠀
 warning  in C:/git/lynkz/blog/node_modules/prop-types/index.js
⠀
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\git\lynkz\blog\node_modules\prop-types\index.js
    Used by 12 module(s), i. e.
    c:\git\lynkz\blog\node_modules\gatsby\dist\utils\babel-loader.js??ref--4-0!c:\git\lynkz\blog\node_modules\eslint-loader\index.js??ref--11-0!C:\git\lynkz\blog\.cache\dev-404-page.js
* c:\git\lynkz\blog\node_modules\prop-types\index.js
    Used by 25 module(s), i. e.
    c:\git\lynkz\blog\node_modules\gatsby\dist\utils\babel-loader.js??ref--4-0!c:\git\lynkz\blog\node_modules\eslint-loader\index.js??ref--11-0!c:\git\lynkz\blog\.cache\navigation.js
⠀
 warning  in C:/git/lynkz/blog/node_modules/prop-types/lib/ReactPropTypesSecret.js
⠀
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\git\lynkz\blog\node_modules\prop-types\lib\ReactPropTypesSecret.js
    Used by 2 module(s), i. e.
    C:\git\lynkz\blog\node_modules\prop-types\factoryWithTypeCheckers.js
* c:\git\lynkz\blog\node_modules\prop-types\lib\ReactPropTypesSecret.js
    Used by 2 module(s), i. e.
    c:\git\lynkz\blog\node_modules\prop-types\checkPropTypes.js
⠀
 warning  in C:/git/lynkz/blog/node_modules/react-is/cjs/react-is.development.js
⠀
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\git\lynkz\blog\node_modules\react-is\cjs\react-is.development.js
    Used by 1 module(s), i. e.
    C:\git\lynkz\blog\node_modules\react-is\index.js
* c:\git\lynkz\blog\node_modules\react-is\cjs\react-is.development.js
    Used by 1 module(s), i. e.
    c:\git\lynkz\blog\node_modules\react-is\index.js
⠀
 warning  in C:/git/lynkz/blog/node_modules/react-is/index.js
⠀
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\git\lynkz\blog\node_modules\react-is\index.js
    Used by 2 module(s), i. e.
    C:\git\lynkz\blog\node_modules\prop-types\index.js
* c:\git\lynkz\blog\node_modules\react-is\index.js
    Used by 3 module(s), i. e.
    c:\git\lynkz\blog\node_modules\prop-types\index.js
⠀
 warning  in C:/git/lynkz/blog/node_modules/react/cjs/react.development.js
⠀
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\git\lynkz\blog\node_modules\react\cjs\react.development.js
    Used by 1 module(s), i. e.
    C:\git\lynkz\blog\node_modules\react\index.js
* c:\git\lynkz\blog\node_modules\react\cjs\react.development.js
    Used by 1 module(s), i. e.
    c:\git\lynkz\blog\node_modules\react\index.js
⠀
 warning  in C:/git/lynkz/blog/node_modules/react/index.js
⠀
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\git\lynkz\blog\node_modules\react\index.js
    Used by 82 module(s), i. e.
    c:\git\lynkz\blog\node_modules\gatsby\dist\utils\babel-loader.js??ref--4-0!c:\git\lynkz\blog\node_modules\eslint-loader\index.js??ref--11-0!C:\git\lynkz\blog\.cache\dev-404-page.js
* c:\git\lynkz\blog\node_modules\react\index.js
    Used by 83 module(s), i. e.
    c:\git\lynkz\blog\node_modules\gatsby\dist\utils\babel-loader.js??ref--4-0!c:\git\lynkz\blog\node_modules\eslint-loader\index.js??ref--11-0!c:\git\lynkz\blog\.cache\app.js
⠀
 warning  in C:/git/lynkz/blog/node_modules/shallowequal/index.js
⠀
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\git\lynkz\blog\node_modules\shallowequal\index.js
    Used by 1 module(s), i. e.
    C:\git\lynkz\blog\node_modules\react-side-effect\lib\index.js
* c:\git\lynkz\blog\node_modules\shallowequal\index.js
    Used by 1 module(s), i. e.
    c:\git\lynkz\blog\node_modules\react-hot-loader\dist\react-hot-loader.development.js
⠀
 warning  in C:/git/lynkz/blog/node_modules/typography-breakpoint-constants/dist/index.js
⠀
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\git\lynkz\blog\node_modules\typography-breakpoint-constants\dist\index.js
    Used by 1 module(s), i. e.
    C:\git\lynkz\blog\node_modules\typography-theme-wordpress-2016\dist\index.js
* c:\git\lynkz\blog\node_modules\typography-breakpoint-constants\dist\index.js
    Used by 1 module(s), i. e.
    c:\git\lynkz\blog\node_modules\typography-theme-wordpress-2016\dist\index.js
⠀
 warning  in C:/git/lynkz/blog/node_modules/typography-theme-wordpress-2016/dist/index.js
⠀
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\git\lynkz\blog\node_modules\typography-theme-wordpress-2016\dist\index.js
    Used by 4 module(s), i. e.
    c:\git\lynkz\blog\node_modules\gatsby\dist\utils\babel-loader.js??ref--4-0!c:\git\lynkz\blog\node_modules\eslint-loader\index.js??ref--11-0!C:\git\lynkz\blog\src\utils\typography.js
* c:\git\lynkz\blog\node_modules\typography-theme-wordpress-2016\dist\index.js
    Used by 4 module(s), i. e.
    c:\git\lynkz\blog\node_modules\gatsby\dist\utils\babel-loader.js??ref--4-0!c:\git\lynkz\blog\node_modules\eslint-loader\index.js??ref--11-0!c:\git\lynkz\blog\src\utils\typography.js
⠀
 warning  in C:/git/lynkz/blog/node_modules/typography/dist/index.js
⠀
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\git\lynkz\blog\node_modules\typography\dist\index.js
    Used by 2 module(s), i. e.
    c:\git\lynkz\blog\node_modules\gatsby\dist\utils\babel-loader.js??ref--4-0!c:\git\lynkz\blog\node_modules\eslint-loader\index.js??ref--11-0!C:\git\lynkz\blog\src\utils\typography.js
* c:\git\lynkz\blog\node_modules\typography\dist\index.js
    Used by 2 module(s), i. e.
    c:\git\lynkz\blog\node_modules\gatsby\dist\utils\babel-loader.js??ref--4-0!c:\git\lynkz\blog\node_modules\eslint-loader\index.js??ref--11-0!c:\git\lynkz\blog\src\utils\typography.js
⠀
 warning  in C:/git/lynkz/blog/node_modules/webpack/buildin/global.js
⠀
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\git\lynkz\blog\node_modules\webpack\buildin\global.js
    Used by 2 module(s), i. e.
    C:\git\lynkz\blog\node_modules\typography\dist\index.js
* c:\git\lynkz\blog\node_modules\webpack\buildin\global.js
    Used by 1 module(s), i. e.
    c:\git\lynkz\blog\node_modules\typography\dist\index.js
⠀
 warning  in C:/git/lynkz/blog/node_modules/webpack/buildin/harmony-module.js
⠀
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* C:\git\lynkz\blog\node_modules\webpack\buildin\harmony-module.js
    Used by 8 module(s), i. e.
    c:\git\lynkz\blog\node_modules\gatsby\dist\utils\babel-loader.js??ref--4-0!c:\git\lynkz\blog\node_modules\eslint-loader\index.js??ref--11-0!C:\git\lynkz\blog\.cache\dev-404-page.js
* c:\git\lynkz\blog\node_modules\webpack\buildin\harmony-module.js
    Used by 19 module(s), i. e.
    c:\git\lynkz\blog\node_modules\gatsby\dist\utils\babel-loader.js??ref--4-0!c:\git\lynkz\blog\node_modules\eslint-loader\index.js??ref--11-0!c:\git\lynkz\blog\.cache\app.js
⠀
 warning  in C:/git/lynkz/blog/src/utils/typography.js
⠀
There are multiple modules with names that only differ in casing.
This can lead to unexpected behavior when compiling on a filesystem with other case-semantic.
Use equal casing. Compare these module identifiers:
* c:\git\lynkz\blog\node_modules\gatsby\dist\utils\babel-loader.js??ref--4-0!c:\git\lynkz\blog\node_modules\eslint-loader\index.js??ref--11-0!C:\git\lynkz\blog\src\utils\typography.js
    Used by 16 module(s), i. e.
    c:\git\lynkz\blog\node_modules\gatsby\dist\utils\babel-loader.js??ref--4-0!c:\git\lynkz\blog\node_modules\eslint-loader\index.js??ref--11-0!C:\git\lynkz\blog\src\templates\blog-post.js
* c:\git\lynkz\blog\node_modules\gatsby\dist\utils\babel-loader.js??ref--4-0!c:\git\lynkz\blog\node_modules\eslint-loader\index.js??ref--11-0!c:\git\lynkz\blog\src\utils\typography.js
    Used by 1 module(s), i. e.
    c:\git\lynkz\blog\node_modules\gatsby\dist\utils\babel-loader.js??ref--4-0!c:\git\lynkz\blog\node_modules\gatsby-plugin-typography\.cache\typography.js
⠀
You can now view gatsby-starter-blog in the browser.
⠀
  http://localhost:8000/
⠀
View GraphiQL, an in-browser IDE, to explore your site's data and schema
⠀
  http://localhost:8000/___graphql
⠀
Note that the development build is not optimized.
To create a production build, use npm run build
⠀
‼ ｢wdm｣:
i ｢wdm｣: Compiled with warnings.
```
### Environment
```

  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    npm: 6.10.0 - C:\Program Files\nodejs\npm.CMD
  Languages:
    Python: 2.7.16
  Browsers:
    Edge: 44.18362.267.0
````

**Comment by karland** [comment] 2019-08-20 09:50
This is the same issue as https://github.com/gatsbyjs/gatsby/issues/16721.

**Comment by wardpeet** [comment] 2019-09-04 13:01
i'm closing as a duplicate of https://github.com/gatsbyjs/gatsby/issues/16721

**Closed by wardpeet** 2019-09-04 13:01 UTC
Labels: type: bug

**Comment by karland** [comment] 2019-09-06 09:46
@wardpeet @LekoArts I think it is good to close duplicates. But could we "rescue" the label `type: bug` and assign the label to https://github.com/gatsbyjs/gatsby/issues/16721, so that it is not forgotten? That would be great. 

@waltercruz Do you already have an idea how to fix the bug? Would it make sense to reverse the PR until we have an idea how to solve the issue for Windows users?

Thanks to all.
