### ISSUE TITLE
ERROR #11321 on createPages process with contenful integration

### ISSUE THREAD

**Issue by darkouz** [gatsbyjs/gatsby#25021] opened 2020-06-16 14:05 UTC
## Description

Error during createPages process

### Steps to reproduce

gastby develop / gatsby build

### Expected result

Build without error

### Actual result

"gatsby-node.js" threw an error while running the createPages lifecycle:

ENOENT: no such file or directory, open '/Users/me/Documents/GitHub/my-project/.cache/contentful/assets/Rectangle 15-9f67c961183d4f5f8b2321d7e06ddba5.jpg'

### Environment

  System:
    OS: macOS 10.15.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
  Languages:
    Python: 2.7.13 - /Applications/MAMP/Library/bin//python
  Browsers:
    Chrome: 83.0.4103.97
    Firefox: 66.0.3
    Safari: 13.1.1
  npmPackages:
    gatsby: ^2.23.3 => 2.23.3
    gatsby-image: ^2.4.7 => 2.4.7
    gatsby-plugin-postcss: ^2.3.4 => 2.3.4
    gatsby-plugin-react-helmet: ^3.3.4 => 3.3.4
    gatsby-plugin-sass: ^2.3.4 => 2.3.4
    gatsby-plugin-sharp: ^2.6.11 => 2.6.11
    gatsby-plugin-typescript: ^2.4.6 => 2.4.6
    gatsby-source-contentful: ^2.3.15 => 2.3.15
    gatsby-source-graphql: ^2.5.4 => 2.5.4
    gatsby-transformer-sharp: ^2.5.5 => 2.5.5

**Comment by LekoArts** [comment] 2020-06-17 07:14
Hi!

Sorry to hear you're running into an issue. To help us best begin debugging the underlying cause, it is incredibly helpful if you're able to create a [minimal reproduction][reproduction]. This is a simplified example of the issue that makes it clear and obvious what the issue is and how we can begin to debug it.

If you're up for it, we'd very much appreciate if you could [provide a minimal reproduction][reproduction] and we'll be able to take another look.

Thanks for using Gatsby! 💜

[reproduction]: https://gatsby.dev/reproduction

**Comment by LekoArts** [comment] 2020-06-26 06:53
Hi!

Since we didn't receive an answer for 7 days or more about the ask of a reproduction I'm going to close this now, as we can't do much to help without a reproduction. If you are able to [create a minimal reproduction](https://gatsby.dev/reproduction) for this then please do answer here or reopen the issue. Thanks!

**Closed by LekoArts** 2020-06-26 06:53 UTC
Labels: status: needs reproduction
